# -*- coding: utf-8 -*-
"""Lecture 11 and 12 rows for the CMS I Exam 2 ophthalmology comparison chart.

Jaquith's chart instruction -- pain, laterality, and the physical exam
abnormality -- was given for Lecture 10, but the Acute Vision Loss objective is
itself a compare-and-contrast across the same axes, so these rows carry the
same three columns. Slide numbers are from each lecture's own deck; the deck
column in the rendered chart names which one.
"""

# name: (pain, laterality, physical exam giveaway)
DIFF_NEW = {
 # ---- Lecture 12, Acute Vision Loss ----
 "Amaurosis fugax": ("<b>NO &mdash; painless</b>", "Usually unilateral",
   "<b>Transient</b> curtain; <b>everything is normal by the time you see them</b>"),
 "Acute angle-closure glaucoma": ("<b>YES &mdash; severe and sudden</b>", "Unilateral",
   "<b>HAZY CORNEA</b>, mid-dilated pupil, <b>intraocular pressure 40&ndash;80</b>, coloured halos"),
 "Chronic open-angle glaucoma": ("<b>NO &mdash; painless</b>", "<b>Bilateral</b>",
   "<b>OPTIC NERVE CUPPING</b>, bayoneting, splinter haemorrhages; <b>peripheral field lost first</b>"),
 "Optic neuritis": ("<b>YES &mdash; on EYE MOVEMENT</b>", "Unilateral",
   "<b>Relative afferent pupillary defect</b>, <b>loss of colour vision</b>, often a <b>normal disc</b>"),
 "Retinal detachment": ("<b>NO &mdash; painless</b>", "Unilateral",
   "<b>Elevated grey retina with folds</b>; flashes and floaters first; <b>changes with head position</b>"),
 "Central retinal artery occlusion (CRAO)": ("<b>NO &mdash; painless</b>", "Unilateral",
   "<b>CHERRY-RED SPOT</b> on a pale retina; pupil <b>slow direct, brisk consensual</b>"),
 "Branch retinal artery occlusion (BRAO)": ("<b>NO &mdash; painless</b>", "Unilateral",
   "<b>Sectoral pallor</b> in one arterial territory; <b>partial</b> field loss"),
 "Central retinal vein occlusion (CRVO)": ("<b>NO &mdash; painless</b>", "Unilateral",
   "<b>&ldquo;BLOOD AND THUNDER&rdquo;</b> &mdash; disc swelling, venous dilation, cotton wool spots"),
 "Branch retinal vein occlusion (BRVO)": ("<b>NO &mdash; painless</b>", "Unilateral",
   "<b>Sectoral haemorrhage</b> along one branch vein; <b>partial</b> field loss"),
 "Arteritic AION (giant cell arteritis)": ("<b>NO in the eye</b> &mdash; but <b>scalp tenderness and jaw claudication</b>", "One eye first; <b>second eye at risk</b>",
   "<b>Swollen PALE disc</b>; <b>raised ESR and CRP</b>; temporal headache in a patient over 55"),
 "Non-arteritic AION": ("<b>NO &mdash; painless</b>", "One eye first; second eye at risk",
   "<b>Swollen PALE disc</b> on a <b>small crowded &ldquo;disc at risk&rdquo;</b>; markers <b>normal</b>"),
 "Papilledema": ("<b>NO in the eye</b> &mdash; but <b>headache</b>", "<b>BILATERAL</b>",
   "<b>Disc pushed OUT</b> with blurred margins and engorged veins; <b>raised INTRACRANIAL pressure</b>"),
 # ---- Lecture 11, Neuro-Ophthalmology ----
 "Relative afferent pupillary defect (Marcus Gunn)": ("<b>NO</b>", "Unilateral",
   "Swinging flashlight &rarr; <b>BOTH pupils DILATE</b> when the light reaches the affected eye"),
 "Horner syndrome": ("<b>NO</b>", "Unilateral",
   "<b>Ptosis + MIOSIS + anhidrosis</b>; hallmark is <b>DILATION LAG</b>; <b>normal levator function</b>"),
 "Argyll Robertson pupil": ("<b>NO</b>", "<b>BILATERAL</b>",
   "<b>Small pupils</b>: <b>no light reaction, brisk near reaction</b> &mdash; light-near dissociation"),
 "Adie tonic pupil": ("<b>NO</b> &mdash; may have photophobia", "Usually unilateral",
   "<b>LARGE pupil</b>, poor light response, <b>slow tonic near response</b>; <b>sector paralysis</b>"),
 "Cranial nerve III palsy": ("<b>NO</b> in itself", "Unilateral",
   "<b>Ptosis + MYDRIASIS</b> + impaired movement. <b>Pupil INVOLVED &rarr; STAT angiography</b>"),
 "Cranial nerve IV palsy": ("<b>NO</b>", "Unilateral",
   "<b>VERTICAL binocular diplopia</b>; <b>head tilted AWAY</b> from the affected eye"),
 "Cranial nerve VI palsy": ("<b>NO</b>", "Unilateral",
   "<b>HORIZONTAL binocular diplopia</b>; failure of abduction"),
 "Nystagmus": ("<b>NO</b> &mdash; vertigo and oscillopsia", "Bilateral eye movement",
   "<b>Involuntary rhythmic oscillation</b>, named for the <b>FAST beat</b>; compensatory head position"),
}

AVL = "Acute vision loss"
NEU = "Neuro-ophthalmology"
D12 = "12. Acute Vision Loss"
D11 = "11. Neuro-Ophthalmology"

# name, group, giveaway, presentation, testing, treatment, urgency, education, slides
ROWS_NEW = [
 ("Amaurosis fugax", AVL,
  "<b>Transient</b> monocular curtain &middot; <b>seconds to minutes</b> &middot; then <b>full recovery</b>",
  "&ldquo;Fleeting blindness.&rdquo; Mild blurring or fogging through to complete blackness, in part or all of the field. <b>Painless.</b> Lasting <b>hours argues against a transient ischemic attack</b>.",
  "<b>Carotid Doppler</b> if carotid suspected &middot; <b>echocardiogram</b> if cardiac &middot; <b>MRA (magnetic resonance angiography) for everyone</b>.",
  "<b>Treat the underlying cause.</b> Aspirin and clopidogrel for stroke risk; <b>carotid endarterectomy</b> for carotid emboli; <b>calcium channel blockers</b> for vasospasm.",
  "Urgent",
  "A transient ischemic attack is a <b>major warning that a stroke is coming</b>. About <b>85% recover fully</b>; the rest progress to a central retinal artery occlusion.",
  "4&ndash;8", D12),
 ("Acute angle-closure glaucoma", AVL,
  "<b>Severe pain + headache + vomiting</b> &middot; <b>coloured halos</b> &middot; <b>hazy cornea</b>",
  "The <b>iris blocks the drainage circuit</b> and pressure rises dramatically. Severe sudden eye pain, decreased vision, halos around lights, headache, nausea and vomiting. May present as an <b>intractable headache behind the eye</b>.",
  "<b>Tonometry or gonioscopy</b> &mdash; intraocular pressure <b>40&ndash;80 mmHg</b>. Pupillary dilation, hazy cornea, narrow or occluded angle.",
  "Topical <b>pilocarpine</b> or <b>timolol</b>; <b>IV acetazolamide</b> then mannitol or isosorbide. <b>Definitive: laser peripheral iridotomy, 1&ndash;2 days after onset.</b>",
  "Emergent",
  "<b>Systemic anticholinergics and nebulized bronchodilators can precipitate it.</b> Permanent blindness without prompt treatment.",
  "9, 13&ndash;14, 16&ndash;17, 20", D12),
 ("Chronic open-angle glaucoma", AVL,
  "<b>Asymptomatic</b> &middot; <b>&ldquo;tunnel vision&rdquo;</b> &middot; <b>optic nerve cupping</b>",
  "Trabecular meshwork abnormality by the canal of Schlemm, from ageing. <b>Asymptomatic in most patients.</b> Peripheral field is lost first, then central. <b>Painless.</b>",
  "Tonometry or gonioscopy &mdash; pressure <b>may be normal OR elevated</b>. Optic nerve: <b>increased cup-to-disc ratio</b>, rim pitting, <b>bayoneting</b>, splinter haemorrhages, rim thinning.",
  "First-line <b>latanoprost, tafluprost or timolol drops</b>. <b>Laser trabeculoplasty</b> if refractory or advanced. <b>Surgery is definitive.</b>",
  "Routine",
  "<b>A leading cause of blindness worldwide.</b> Found by <b>annual eye examinations</b>, because patients have no symptoms. Some remain on drops for life.",
  "9, 15&ndash;16, 18&ndash;19, 21", D12),
 ("Optic neuritis", AVL,
  "<b>PAINFUL EYE MOVEMENT</b> &middot; <b>loss of colour vision</b> &middot; <b>young woman</b>",
  "<b>18&ndash;45 years, 75% female.</b> Unilateral loss over <b>hours to several days</b>, with pain on eye movement and often central vision loss. Inflammation from <b>multiple sclerosis</b>, autoimmune disease, postviral or idiopathic.",
  "Slit lamp, dilated fundoscopy, <b>colour vision assessment</b> and neurological examination. <b>MRI brain AND orbits, with and without contrast.</b> Disc often <b>normal-appearing</b>; <b>relative afferent pupillary defect</b>.",
  "<b>Corticosteroids</b> if a demyelinating cause is found. <b>At least 2 demyelinating lesions</b> &rarr; neurology or neuro-ophthalmology.",
  "Urgent",
  "<b>Spontaneous recovery is the rule</b> &mdash; usually normal within a year. <b>Recurrence raises the risk of multiple sclerosis</b>, so find the cause.",
  "22&ndash;24", D12),
 ("Retinal detachment", AVL,
  "<b>Flashes and floaters</b>, then a <b>curtain that STAYS</b> &middot; <b>painless</b>",
  "Traction detachment after a <b>retinal tear or hole</b>. Grey or black peripheral shadows that may cover the eye <b>within days</b>. <b>If the macula is involved, sudden loss of vision.</b> The deficit <b>changes with head position</b>.",
  "Direct and dilated ophthalmoscopy: <b>elevated grey retina with folds</b>, pigmented well-demarcated area, <b>orange crescent-shaped tears</b>. <b>Ultrasound is more sensitive than fundoscopy</b> and types it.",
  "<b>Refer immediately.</b> Surgery urgently or within a week by type: laser photocoagulation, cryotherapy, <b>pneumatic retinopexy</b>, vitrectomy, <b>scleral buckle</b>.",
  "Emergent",
  "<b>Most common after age 50.</b> Risks: myopia, trauma, cataract extraction, diabetes, connective tissue disease. Flashes and floaters mean <b>a tear</b> &mdash; get seen.",
  "25&ndash;30", D12),
 ("Central retinal artery occlusion (CRAO)", AVL,
  "<b>Painless profound loss over SECONDS</b> &middot; <b>CHERRY-RED SPOT</b>",
  "An embolus blocks the central retinal artery &mdash; <b>a stroke in the eye</b>. Acuity from <b>counting fingers to light perception</b>, with an <b>island of vision in the temporal field</b>. Pupil <b>slow to direct light, brisk consensually</b>.",
  "<b>Pale swelling</b> of the posterior segment with a <b>cherry-red spot at the fovea</b>; emboli visible in the artery. <b>Colour fundus photography and fluorescein angiography.</b>",
  "<b>High-concentration inhaled oxygen and digital massage</b>, <b>IV acetazolamide</b>, <b>anterior chamber paracentesis</b>, and <b>thrombolytic into the ophthalmic artery within 8 hours</b>.",
  "Emergent",
  "<b>Irreversible damage after 90 minutes.</b> Stroke risk rises at onset &mdash; plaque reaching a retinal artery means far more remains in the carotid.",
  "36&ndash;40", D12),
 ("Branch retinal artery occlusion (BRAO)", AVL,
  "<b>Painless</b> loss of a <b>WEDGE</b> of field &middot; sectoral pallor",
  "The same disease as CRAO with the blockage in a <b>branch</b> vessel, so only part of the retina is affected and the field loss is <b>partial and localised</b>.",
  "As for CRAO, with the findings confined to one arterial territory.",
  "As for CRAO &mdash; the management does not change.",
  "Emergent",
  "The only difference from the central form is <b>where the blockage sits</b>.",
  "41", D12),
 ("Central retinal vein occlusion (CRVO)", AVL,
  "<b>Painless</b> loss &middot; <b>&ldquo;BLOOD AND THUNDER&rdquo; fundus</b>",
  "A <b>thrombus</b> occludes the central retinal vein. Sudden and painless, though in some patients loss develops <b>gradually over days to weeks</b>. <b>More common than CRAO.</b>",
  "Disc swelling, <b>venous dilation</b>, <b>cotton wool spots</b>, retinal haemorrhages &mdash; the blood and thunder appearance. Confirm with <b>colour fundus photography and fluorescein angiography</b>.",
  "<b>Urgent ophthalmology referral to restore blood flow.</b> Evaluate and treat the underlying disorders.",
  "Urgent",
  "<b>Neovascularization appears weeks to months after</b> the occlusion. Risks are the clotting risks: hypertension, diabetes, hyperlipidaemia, hypercoagulable states.",
  "31&ndash;34", D12),
 ("Branch retinal vein occlusion (BRVO)", AVL,
  "<b>Painless</b> loss of <b>PART</b> of the field &middot; sectoral haemorrhage",
  "The same disease as CRVO with the clot in a <b>smaller branch</b> vein, affecting only part of the retina rather than the whole.",
  "As for CRVO, with haemorrhage confined to the territory of one branch vein.",
  "As for CRVO &mdash; urgent referral, and treat the underlying disorder.",
  "Urgent",
  "Everything except the extent of the field loss is identical to the central form.",
  "35", D12),
 ("Arteritic AION (giant cell arteritis)", AVL,
  "<b>Over 55</b> &middot; <b>NEW temporal headache</b> &middot; <b>scalp tenderness, jaw claudication</b>",
  "Anterior ischemic optic neuropathy caused by <b>giant cell (temporal) arteritis</b>. Sudden painless loss of side or central vision, with systemic <b>malaise, weight loss, fever</b>. Usually an <b>elderly woman with no prior headache history</b>.",
  "<b>ESR (erythrocyte sedimentation rate) and CRP (C-reactive protein)</b> rule it in or out. <b>Temporal artery biopsy is the gold standard.</b> Disc is <b>swollen and pale</b>.",
  "<b>IV methylprednisolone &times;3 days, then a slow oral taper</b> to the lowest suppressive dose, typically <b>6&ndash;12 months</b>. Add <b>famotidine</b> for ulcer prophylaxis. <b>Do not wait for the biopsy.</b>",
  "Emergent",
  "<b>Refer emergently any patient over 50 with sudden visual loss.</b> Untreated it blinds; the <b>second eye is at risk</b>. Prognosis depends on how early steroids start.",
  "47, 49&ndash;51", D12),
 ("Non-arteritic AION", AVL,
  "<b>40&ndash;60</b> &middot; <b>painless</b> &middot; <b>&ldquo;disc at risk&rdquo;</b> &middot; <b>normal markers</b>",
  "<b>90&ndash;95% of anterior ischemic optic neuropathy.</b> Sudden painless loss of side or central vision, with a <b>swollen pale disc</b>. Linked to a <b>small structural optic disc</b> and to hypertension, diabetes, high cholesterol and <b>sleep apnea</b>.",
  "<b>A diagnosis of exclusion &mdash; the workup is identical to the arteritic form</b>, to be sure there is no giant cell arteritis. Then evaluate for hypertension, diabetes and anaemia; neuroimaging if unclear.",
  "<b>Observation and cardiovascular risk factor modification.</b> Consider <b>avoiding antihypertensives at bedtime</b>.",
  "Urgent",
  "<b>Nocturnal hypotension can worsen it</b>, which is why the bedtime dose is moved. The second eye remains at risk.",
  "47&ndash;48, 50, 52", D12),
 ("Papilledema", AVL,
  "<b>BILATERAL</b> swollen discs &middot; <b>headache, nausea, vomiting</b> &middot; <b>INTRACRANIAL</b> pressure",
  "Swelling of the optic disc from <b>raised intracranial pressure</b> &mdash; not intraocular. Non-specific visual change: <b>flickering, blurry, double vision</b>. Causes: tumour, trauma, intracranial infection, haemorrhage, <b>vitamin A toxicity</b>.",
  "Ophthalmoscopy: <b>engorged retinal veins, swollen optic disc</b>, &plusmn; haemorrhages. <b>MRI and/or CT head to rule out a mass</b>, then <b>lumbar puncture &mdash; increased opening pressure confirms</b>.",
  "<b>Treat the underlying disorder.</b>",
  "Emergent",
  "<b>Papilledema pushes the disc OUT; glaucoma cups it IN.</b> Acute has haemorrhages and cotton wool spots; chronic does not; the atrophic phase means the axons have died.",
  "42&ndash;46", D12),
 ("Relative afferent pupillary defect (Marcus Gunn)", NEU,
  "Swinging flashlight &rarr; <b>BOTH pupils DILATE</b> on the bad eye",
  "An <b>afferent</b> defect, usually at the <b>retina or optic nerve</b>. Moving a bright light onto the affected eye makes both pupils dilate, because the perceived illumination has just dropped.",
  "<b>Swinging flashlight test.</b> Pupils are equal at rest.",
  "Treat the underlying retinal or optic nerve disease.",
  "Urgent",
  "It is a <b>sign, not a diagnosis</b> &mdash; find what is damaging the nerve or retina.",
  "25&ndash;26", D11),
 ("Horner syndrome", NEU,
  "<b>Ptosis + MIOSIS + anhidrosis</b> &middot; <b>DILATION LAG</b>",
  "Damage anywhere along the three-neuron sympathetic chain; <b>often idiopathic</b>. Anisocoria is <b>most evident in the first 4&ndash;5 seconds after dimming the lights</b>. Anhidrosis may be absent depending on the level.",
  "<b>Dilute apraclonidine drops</b> &mdash; ineffective in a normal pupil, they <b>dilate the Horner pupil</b>. Localise: 1st order brainstem or cord above T1; 2nd order <b>Pancoast tumour</b>; 3rd order <b>carotid dissection</b>.",
  "Treat the cause. <b>Levator function is normal</b>, so the ptosis is mild.",
  "Emergent",
  "<b>Horner with neck pain, trauma or focal neurology is a carotid dissection until proven otherwise.</b>",
  "13, 15, 27&ndash;30", D11),
 ("Argyll Robertson pupil", NEU,
  "<b>Small BILATERAL</b> pupils &middot; <b>no light, brisk near</b>",
  "Bilateral miosis with <b>light-near dissociation</b>. <b>Classically tertiary syphilis</b>, with <b>tabes dorsalis</b> and sensory loss from posterior column involvement.",
  "Test light and near responses separately. Lesion suspected in the <b>pretectal area of the dorsal midbrain</b>.",
  "Treat the underlying syphilis.",
  "Urgent",
  "The pupillary near pathway <b>skips part of the light pathway&rsquo;s route</b>, which is why one can fail while the other works.",
  "19, 31&ndash;33", D11),
 ("Adie tonic pupil", NEU,
  "<b>LARGE</b> pupil &middot; <b>poor light, slow tonic near</b> &middot; <b>sector paralysis</b>",
  "Inflammation damages the <b>ciliary ganglion</b> or short ciliary nerves, followed by <b>aberrant reinnervation</b>. Typically <b>women in their 30s</b>, often unilateral, and <b>often asymptomatic</b>; may have photophobia and blurred vision.",
  "Slit lamp shows <b>sector paralysis</b> of the iris. <b>Decreased regional corneal sensation.</b> <b>Absent Achilles or patellar reflexes</b> in Holmes-Adie syndrome.",
  "Reassurance; treat symptoms. Dilute pilocarpine constricts it through denervation supersensitivity.",
  "Routine",
  "A large pupil that reacts poorly to light but slowly to near &mdash; the opposite pattern to Argyll Robertson.",
  "34&ndash;37", D11),
 ("Cranial nerve III palsy", NEU,
  "<b>Ptosis + MYDRIASIS</b> &middot; impaired movement &middot; <b>pupil involved = STAT</b>",
  "Most commonly <b>microvascular</b> (diabetes, hypertension). The dreaded cause is <b>compression by an enlarging posterior communicating artery aneurysm</b>, threatening rupture <b>within hours to days</b>.",
  "Classified <b>complete vs incomplete</b> and <b>pupil-involved vs pupil-spared</b>. <b>Pupil involved &rarr; STAT CTA head or MRA brain.</b> Pupil-spared &rarr; imaging, but not STAT.",
  "Depends on aetiology. Traumatic: observe about 6 months, patching in the interim.",
  "Emergent",
  "Parasympathetic fibres run on the <b>outside</b> of the nerve, so compression reaches them first while microvascular disease spares them.",
  "39&ndash;41", D11),
 ("Cranial nerve IV palsy", NEU,
  "<b>VERTICAL</b> binocular diplopia &middot; <b>head tilt AWAY</b> from the bad eye",
  "The trochlear nerve supplies the <b>superior oblique</b>, which <b>intorts and depresses</b>. Isolated palsy is <b>most commonly congenital, even in adults</b>; acquired causes are trauma, even mild, and microvascular disease.",
  "<b>MRI brain with and without contrast</b> if isolated and atraumatic. Check <b>haemoglobin A1C</b> if at risk and not known diabetic.",
  "Traumatic: <b>observe about 6 months</b> before corrective treatment; <b>patch one eye</b> meanwhile.",
  "Urgent",
  "<b>The only nerve arising from the dorsal brainstem, and it crosses</b> &mdash; the left nucleus supplies the right eye.",
  "42&ndash;43, 46", D11),
 ("Cranial nerve VI palsy", NEU,
  "<b>HORIZONTAL</b> binocular diplopia &middot; failure of abduction",
  "The abducens nerve supplies the <b>lateral rectus</b>. In <b>children the most common cause is intracranial tumour</b>, especially brainstem and posterior fossa; in <b>adults, microvascular disease</b>, or major trauma and skull base fracture.",
  "<b>MRI brain with and without contrast</b> if isolated and atraumatic; <b>haemoglobin A1C</b> if at risk.",
  "Traumatic: observe about 6 months; patch one eye in the interim.",
  "Urgent",
  "A child with a sixth nerve palsy needs imaging &mdash; the base rate of tumour is what changes the threshold.",
  "44&ndash;46", D11),
 ("Nystagmus", NEU,
  "<b>Involuntary rhythmic oscillation</b> &middot; named for the <b>FAST beat</b>",
  "Involuntary, biphasic, rhythmic, tremor-like oscillation. Congenital or acquired, and <b>usually symptomatic unless acquired before age 8</b>. <b>Vertigo is often the primary symptom</b>; also oscillopsia, blurring and compensatory head positioning.",
  "Jerk nystagmus is classified by trajectory and <b>increases with gaze toward the fast phase</b>. <b>Horizontal is the most common form.</b>",
  "<b>Ophthalmology for a complete ophthalmic exam &rarr; imaging &rarr; labs if relevant.</b> The underlying aetiology must be addressed.",
  "Urgent",
  "Work up <b>infants and young children</b>, anything <b>acquired in adolescence or adulthood</b>, and concerning non-physiologic nystagmus in adults.",
  "3&ndash;5", D11),
]

# Pictures for the new rows. Every one was viewed before assignment; the four
# papilledema panels were identified by their own visible features rather than
# by file order, because extraction order does not follow the slide's A/B/C/D
# layout. Files are the 600 px JPEGs, matching the Lecture 10 convention.
IMGS_NEW = {
 "Nystagmus": ("l11-s004_1.jpg", 4),
 "Adie tonic pupil": ("l11-s020_1.jpg", 20),
 "Cranial nerve III palsy": ("l11-s039_2.jpg", 39),
 "Acute angle-closure glaucoma": ("l12-s012_1.jpg", 12),
 "Chronic open-angle glaucoma": ("l12-s019_1.jpg", 19),
 # slide 23 is labelled ABOVE / MIDDLE / BELOW: _1 is the fundus photograph of
 # optic nerve swelling, _3 is the periventricular FLAIR. A comparison chart of
 # eye findings wants the eye.
 "Optic neuritis": ("l12-s023_1.jpg", 23),
 "Retinal detachment": ("l12-s028_1.jpg", 28),
 "Papilledema": ("l12-s045_1.jpg", 45),
}
