# -*- coding: utf-8 -*-
"""Stem fingerprints for the lead-in map -- GENERATED, do not hand-edit.

_cmse3_leadins.LEADINS is keyed by (pool module, index). That key breaks
silently if a pool is ever reordered or has a question inserted: the lead-in
would attach to the wrong question and quietly change which option is correct.
These are the first 46 characters of each stem as it stood when the lead-ins
were written; apply_leadins.py asserts the stem still starts this way, so a
reorder fails the build instead of corrupting the item.

Regenerate with tools/gen_leadin_fingerprints.py after a deliberate reorder.
"""

FP = {
  ("cms_e3l18_vig_a", 0): 'A 9-year-old girl has a painless midline neck ',
  ("cms_e3l18_vig_a", 1): 'A 20-year-old man has a tender fluctuant swell',
  ("cms_e3l18_vig_a", 2): 'A 61-year-old man who smokes and drinks daily ',
  ("cms_e3l18_vig_a", 3): 'An 18-month-old has a soft, doughy, non-tender',
  ("cms_e3l18_vig_a", 4): 'A 5-month-old has a red, soft, compressible ne',
  ("cms_e3l18_vig_a", 5): 'A newborn has a large firm neck mass present a',
  ("cms_e3l18_vig_a", 6): 'A 7-week-old has a firm, painless, discrete ma',
  ("cms_e3l18_vig_a", 7): 'A 5-year-old has a 2 centimetre cervical node ',
  ("cms_e3l18_vig_a", 8): 'A 4-year-old has a unilateral neck mass in the',
  ("cms_e3l18_vig_a", 9): 'A 10-year-old boy has tender preauricular and ',
  ("cms_e3l18_vig_a", 10): 'A 30-year-old man has a fluctuant, tender subm',
  ("cms_e3l18_vig_a", 11): 'A 50-year-old woman has a solitary thyroid nod',
  ("cms_e3l18_vig_a", 12): "A 31-year-old woman's thyroid nodule biopsy sh",
  ("cms_e3l18_vig_a", 13): 'An 80-year-old woman has a hard thyroid mass t',
  ("cms_e3l18_vig_a", 15): 'A 64-year-old woman with long-standing Hashimo',
  ("cms_e3l18_vig_b", 0): 'A 45-year-old woman has a neck mass that pulse',
  ("cms_e3l18_vig_b", 1): 'A 35-year-old man has a neck mass that has gro',
  ("cms_e3l18_vig_b", 2): 'A 64-year-old smoker has a firm cervical node.',
  ("cms_e3l18_vig_b", 3): 'A 26-year-old woman has a slow-growing painles',
  ("cms_e3l18_vig_b", 4): 'A 49-year-old trumpet player has hoarseness, c',
  ("cms_e3l18_vig_b", 5): 'A 13-year-old has a midline submental mass tha',
  ("cms_e3l18_vig_b", 6): 'An 11-year-old has a slow-growing asymptomatic',
  ("cms_e3l18_vig_b", 7): 'A 34-year-old man with untreated HIV has gener',
  ("cms_e3l18_vig_b", 8): 'A 41-year-old man who hunts rabbits has fever,',
  ("cms_e3l18_vig_b", 9): 'A 39-year-old dairy worker who drinks unpasteu',
  ("cms_e3l18_vig_b", 10): 'A 53-year-old man has a painless, fluctuant sw',
  ("cms_e3l18_vig_b", 11): 'A 57-year-old woman on immunosuppression after',
  ("cms_e3l18_vig_b", 12): 'A 3-year-old has five days of high fever, red ',
  ("cms_e3l18_vig_b", 13): 'A 57-year-old woman with a thyroid carcinoma i',
  ("cms_e3l18_vig_b", 14): 'A 40-year-old man with untreated HIV has a rap',
  ("cms_e3l18_vig_c", 0): 'A 55-year-old man has had a firm neck lump for',
  ("cms_e3l18_vig_c", 1): 'A 48-year-old woman has a soft, mobile, painle',
  ("cms_e3l18_vig_c", 2): 'A clinician palpates a neck mass and finds it ',
  ("cms_e3l18_vig_c", 3): 'A 52-year-old woman has an immobile midline ne',
  ("cms_e3l18_vig_c", 4): 'A 27-year-old woman has a thyroid nodule. She ',
  ("cms_e3l18_vig_c", 5): 'A 46-year-old man has a 1.4 centimetre thyroid',
  ("cms_e3l18_vig_c", 7): 'A 58-year-old man with a neck mass reports nig',
  ("cms_e3l18_vig_c", 8): 'A clinician documents a cervical node as immob',
  ("cms_e3l18_vig_c", 10): 'A surgeon plans an approach through the triang',
  ("cms_e3l18_vig_c", 11): 'A wound in the posterior triangle has injured ',
  ("cms_e3l18_vig_c", 12): 'A 24-year-old has tonsillitis and a tender nod',
  ("cms_e3l18_vig_c", 13): "A 59-year-old woman's neck mass has persisted ",
  ("cms_e3l18_vig_c", 14): 'A 66-year-old man has an asymptomatic, slowly ',
  ("cms_e3l18_vig_d", 0): 'A 36-year-old woman has papillary thyroid carc',
  ("cms_e3l18_vig_d", 1): 'A patient treated for medullary thyroid carcin',
  ("cms_e3l18_vig_d", 2): 'A 28-year-old man has a painless firm supracla',
  ("cms_e3l18_vig_d", 3): 'A 52-year-old man from a high-prevalence regio',
  ("cms_e3l18_vig_d", 4): 'A 5-year-old has a hot, tender, fluctuant subm',
  ("cms_e3l18_vig_d", 5): 'A 50-year-old woman has a slowly enlarging lat',
  ("cms_e3l18_vig_d", 6): 'A 4-year-old has a midline neck mass that beco',
  ("cms_e3l18_vig_d", 7): 'A 44-year-old smoker has what looks like a bra',
  ("cms_e3l18_vig_d", 8): 'A 47-year-old man has a persistent neck mass. ',
  ("cms_e3l18_vig_d", 9): 'A 60-year-old man with a 40 pack-year history ',
  ("cms_e3l18_vig_d", 11): 'A 4-month-old has a large neck haemangioma and',
  ("cms_e3l18_vig_d", 12): 'A 30-year-old woman has tender cervical nodes,',
  ("cms_e3l18_vig_d", 13): 'A 26-year-old woman returned from a rural stay',
  ("cms_e3l19_vig_a", 0): 'A 16-year-old treated with penicillin for phar',
  ("cms_e3l19_vig_a", 1): 'A 3-year-old has two days of fever, sore throa',
  ("cms_e3l19_vig_a", 2): 'A 47-year-old man with poorly controlled diabe',
  ("cms_e3l19_vig_a", 3): 'A 5-year-old has a few hours of high fever, dr',
  ("cms_e3l19_vig_a", 4): 'A 19-year-old student treated with amoxicillin',
  ("cms_e3l19_vig_a", 5): 'A 46-year-old man has recurrent painful swelli',
  ("cms_e3l19_vig_a", 6): 'An 81-year-old woman four days after hip surge',
  ("cms_e3l19_vig_a", 7): 'A 64-year-old man using an inhaled corticoster',
  ("cms_e3l19_vig_a", 8): 'A 61-year-old man who has chewed tobacco for t',
  ("cms_e3l19_vig_a", 9): 'A 58-year-old woman who smokes and drinks has ',
  ("cms_e3l19_vig_a", 10): 'A 39-year-old man has painless white lesions o',
  ("cms_e3l19_vig_a", 11): 'A 56-year-old woman has lacy white lines on bo',
  ("cms_e3l19_vig_a", 12): 'A 31-year-old man has recurrent painful oral u',
  ("cms_e3l19_vig_a", 13): 'An 8-year-old boy who shouts constantly during',
  ("cms_e3l19_vig_a", 14): 'A 53-year-old man who smokes heavily and shout',
  ("cms_e3l19_vig_a", 15): 'A 59-year-old woman has a breathy hoarse voice',
  ("cms_e3l19_vig_b", 0): 'An 11-year-old has two days of sore throat wit',
  ("cms_e3l19_vig_b", 1): 'A 22-year-old has a sore throat with cough, ho',
  ("cms_e3l19_vig_b", 2): 'A 9-year-old develops migratory joint pains an',
  ("cms_e3l19_vig_b", 3): 'A 52-year-old smoker has constant throat clear',
  ("cms_e3l19_vig_b", 4): 'A 6-year-old has a unilateral, solitary, tende',
  ("cms_e3l19_vig_b", 5): 'A 42-year-old man has a dental abscess. The to',
  ("cms_e3l19_vig_b", 6): 'A 35-year-old man has gums that are red, swoll',
  ("cms_e3l19_vig_b", 7): 'A 31-year-old man has a painful lower wisdom t',
  ("cms_e3l19_vig_b", 8): 'A 36-year-old woman has facial pain, jaw click',
  ("cms_e3l19_vig_b", 9): 'A 62-year-old man who smokes and drinks has an',
  ("cms_e3l19_vig_b", 10): 'A 59-year-old man has a tonsillar squamous cel',
  ("cms_e3l19_vig_b", 11): 'A 60-year-old man has a slowly enlarging painl',
  ("cms_e3l19_vig_b", 12): 'A 57-year-old woman has a parotid mass with pa',
  ("cms_e3l19_vig_b", 13): 'A 9-year-old recently arrived from a region wi',
  ("cms_e3l19_vig_b", 14): 'A 20-year-old student has recurrent painful or',
  ("cms_e3l19_vig_b", 15): 'A 28-year-old woman has recurrent painful lesi',
  ("cms_e3l19_vig_c", 0): 'A 24-year-old with a peritonsillar abscess can',
  ("cms_e3l19_vig_c", 1): 'A 27-year-old man has had three peritonsillar ',
  ("cms_e3l19_vig_c", 2): 'A 21-year-old rugby player is confirmed to hav',
  ("cms_e3l19_vig_c", 3): 'A 3-month-old breastfed infant has white plaqu',
  ("cms_e3l19_vig_c", 4): 'A 70-year-old man has chronic unilateral parot',
  ("cms_e3l19_vig_c", 5): 'A 48-year-old man has severe sore throat, odyn',
  ("cms_e3l19_vig_c", 6): 'A 4-year-old with recurrent respiratory papill',
  ("cms_e3l19_vig_c", 7): 'A 58-year-old smoker has been hoarse for seven',
  ("cms_e3l19_vig_c", 8): 'A 15-year-old is referred with an abnormal bit',
  ("cms_e3l19_vig_c", 9): 'A pregnant woman at 30 weeks asks about vaccin',
  ("cms_e3l19_vig_c", 10): 'A 44-year-old man has a diffuse greyish-white ',
  ("cms_e3l19_vig_c", 11): 'A 32-year-old woman notices small yellow-white',
  ("cms_e3l19_vig_c", 12): 'A 34-year-old woman has painless oral erosions',
  ("cms_e3l19_vig_c", 13): 'A clinician is describing a cervical node and ',
  ("cms_e3l19_vig_c", 14): 'A 7-year-old unimmunised boy has bilateral pai',
  ("cms_e3l19_vig_c", 15): 'A 55-year-old man who chews betel nut and smok',
  ("cms_e3l19_vig_c", 16): 'A 9-year-old has cervical adenitis with a fluc',
  ("cms_e3l19_vig_c", 17): 'A 60-year-old man with untreated periodontal d',
  ("cms_e3l19_vig_c", 18): 'A 38-year-old woman has severe toothache. The ',
  ("cms_e3l19_vig_c", 19): 'A student asks why a retropharyngeal abscess i',
  ("cms_e3l19_vig_c", 20): 'A 61-year-old woman has a tumour of a minor sa',
  ("cms_e3l19_vig_c", 21): 'A 6-year-old has fever and sore throat with sm',
  ("cms_e3l19_vig_c", 22): 'A 44-year-old man has a stone palpable in the ',
  ("cms_e3l19_vig_c", 23): 'A 50-year-old woman has recurrent submandibula',
  ("cms_e3l19_vig_c", 24): 'A 46-year-old man develops fever, sore throat ',
  ("cms_e3l19_vig_c", 25): 'A 66-year-old woman with dentures complains th',
  ("cms_e3l19_vig_c", 26): 'A 63-year-old man with a suspicious oral lesio',
  ("cms_e3l19_vig_c", 27): 'A 15-year-old has inflammation of both the ton',
  ("cmsent_l15_pool", 0): 'An 8-year-old boy has left ear pain. His fathe',
  ("cmsent_l15_pool", 1): 'A 62-year-old man with poorly controlled type ',
  ("cmsent_l15_pool", 2): 'A 25-year-old patient has acute otitis media w',
  ("cmsent_l15_pool", 3): 'A 30-year-old man is admitted for stapedectomy',
  ("cmsent_l15_pool", 4): 'A 37-year-old man reports constant fullness in',
  ("cmsent_l15_pool", 5): 'A 30-year-old woman is struck on the side of t',
  ("cmsent_l15_pool", 6): 'A 3-year-old girl has had two days of fever an',
  ("cmsent_l15_pool", 7): 'A 4-year-old boy has had acute otitis media fo',
  ("cmsent_l15_pool", 8): 'A 29-year-old woman has had a blocked, full se',
  ("cmsent_l15_pool", 9): 'A 6-year-old girl had acute otitis media six w',
  ("cmsent_l15_pool", 10): 'A 4-year-old boy is brought in after putting a',
  ("cmsent_l15b_pool", 0): 'A 19-year-old wrestler is seen four hours afte',
  ("cmsent_l15b_pool", 1): 'A 71-year-old man reports gradual reduction in',
  ("cmsent_l15b_pool", 2): 'A 44-year-old woman has had three weeks of int',
  ("cmsent_l15b_pool", 3): 'A 34-year-old woman has had gradually worsenin',
  ("cmsent_l15b_pool", 4): 'A 68-year-old man has had a discharging left e',
  ("cmsent_l15b_pool", 5): 'A 26-year-old man has had intermittent painles',
  ("cmsent_l15b_pool", 6): 'A 41-year-old man descends on a flight with a ',
  ("cmsent_l15b_pool", 7): 'A 5-year-old girl has had a foul-smelling disc',
  ("cmsent_l15b_pool", 8): 'A 2-year-old boy has had four episodes of acut',
  ("cmsent_l15b_pool", 9): 'A 74-year-old woman with type 2 diabetes has s',
  ("cmsent_l15b_pool", 10): 'A 33-year-old woman had severe right ear pain ',
  ("cmsent_l15b_pool", 11): 'A 55-year-old man has had otitis externa treat',
  ("cmsent_l15c_pool", 0): 'A 15-year-old competitive swimmer has had thre',
  ("cmsent_l15c_pool", 1): 'A 5-year-old with acute otitis media has compl',
  ("cmsent_l15c_pool", 2): 'A 44-year-old woman with a known cholesteatoma',
  ("cmsent_l15c_pool", 3): 'A student asks why acute otitis media can prog',
  ("cmsent_l15c_pool", 4): 'A 22-year-old woman develops a firm, rubbery, ',
  ("cmsent_l15c_pool", 5): 'A 28-year-old man has a laceration of the auri',
  ("cmsent_l15c_pool", 6): 'A 4-year-old has had a bilateral middle ear ef',
  ("cmsent_l15c_pool", 7): 'A 41-year-old man with allergic rhinitis has r',
  ("cmsent_l15c_pool", 8): 'A 34-year-old woman with a heavy cold is due t',
  ("cmsent_l15c_pool", 9): 'A 70-year-old man with diabetes is being inves',
  ("cmsent_l15c_pool", 10): 'A 13-year-old girl has an earring back embedde',
  ("cmsent_l15c_pool", 11): 'A 52-year-old man has had a dry central perfor',
  ("cmsent_l15c_pool", 12): 'A clinician is teaching the single most useful',
  ("cmsent_l16_pool", 0): 'A 67-year-old woman is brought by her husband,',
  ("cmsent_l16_pool", 1): 'A 61-year-old patient has a one-week history o',
  ("cmsent_l16_pool", 2): 'A 45-year-old man has had four episodes over t',
  ("cmsent_l16_pool", 3): 'A 38-year-old woman develops sudden severe ver',
  ("cmsent_l16_pool", 4): 'A 52-year-old man wakes to find he cannot hear',
  ("cmsent_l16_pool", 5): 'A 56-year-old woman has noticed over 18 months',
  ("cmsent_l16_pool", 6): 'A 78-year-old man says he can hear that people',
  ("cmsent_l16_pool", 7): 'A 49-year-old woman describes a whooshing soun',
  ("cmsent_l16_pool", 8): 'A 54-year-old woman has pulsatile tinnitus and',
  ("cmsent_l16_pool", 9): 'A 31-year-old man attends a loud concert and a',
  ("cmsent_l16_pool", 10): "A patient's tuning fork examination shows Webe",
  ("cmsent_l16_pool", 11): 'A 42-year-old man develops sudden severe verti',
  ("cmsent_l16_pool", 12): 'A 36-year-old man strains heavily while weight',
  ("cmsent_l16_pool", 13): 'A 24-year-old man claims complete bilateral de',
  ("cmsent_l16_pool", 14): 'A 46-year-old man has fluctuating sensorineura',
  ("cmsent_l16b_pool", 0): "An audiogram reports a patient's thresholds at",
  ("cmsent_l16b_pool", 1): 'A patient with reduced hearing has a tympanogr',
  ("cmsent_l16b_pool", 2): 'A clinician wishes to assess each vestibular a',
  ("cmsent_l16b_pool", 3): 'A 32-year-old competitive surfer has bilateral',
  ("cmsent_l16b_pool", 4): 'A patient reports that they hear conversation ',
  ("cmsent_l16b_pool", 5): 'A 74-year-old woman with symmetrical high-freq',
  ("cmsent_l16b_pool", 6): 'A 24-year-old man fires a rifle without ear pr',
  ("cmsent_l16b_pool", 7): 'A 47-year-old woman with confirmed Meniere dis',
  ("cmsent_l16b_pool", 8): 'A 76-year-old man with hypertension and atrial',
  ("cmsent_l16b_pool", 9): 'A 69-year-old woman has sudden severe vertigo ',
  ("cmsent_l16b_pool", 10): 'A 58-year-old man completes a course of intrav',
  ("cmsent_l16b_pool", 11): 'A 39-year-old woman has bilateral sensorineura',
  ("cmsent_l16b_pool", 12): 'A newborn fails the hearing screen. Examinatio',
  ("cmsent_l16b_pool", 13): 'A 44-year-old man develops unilateral hearing ',
  ("cmsent_l16b_pool", 14): 'A 58-year-old woman with a positive right Dix-',
  ("cmsent_l16b_pool", 15): 'A 63-year-old man has bilateral high-pitched r',
  ("cmsent_l16c_pool", 0): "A patient's Weber test lateralises to the left",
  ("cmsent_l16c_pool", 1): 'A student asks why the Rinne test alone cannot',
  ("cmsent_l16c_pool", 3): 'A 48-year-old man with a unilateral sensorineu',
  ("cmsent_l16c_pool", 4): 'A patient asks which frequencies are affected ',
  ("cmsent_l16c_pool", 5): 'A 40-year-old man with vestibular neuronitis a',
  ("cmsent_l16c_pool", 6): 'An audiogram of a 45-year-old factory worker s',
  ("cmsent_l16c_pool", 7): 'A clinician explains why sudden sensorineural ',
  ("cmsent_l16c_pool", 8): 'A clinician lists the features of tinnitus tha',
  ("cmsent_l16c_pool", 9): 'A clinician explains why untreated conductive ',
  ("cmsent_l16c_pool", 10): 'A patient with a suspected perilymphatic fistu',
  ("cmsent_l16c_pool", 11): 'A 79-year-old woman with presbycusis is reluct',
  ("cmsent_l16c_pool", 12): 'A student asks what cranial nerve deficits mig',
  ("cmsent_l16c_pool", 13): 'A 42-year-old woman with rapidly progressive b',
  ("cmsent_l16c_pool", 14): 'A clinician suspects non-organic hearing loss ',
  ("cmsent_l16c_pool", 15): 'A clinician is taught which features of acute ',
  ("cmsent_l17_pool", 0): 'A 25-year-old patient has had ten days of nasa',
  ("cmsent_l17_pool", 1): 'A 30-year-old woman has had four days of nasal',
  ("cmsent_l17_pool", 2): 'A 19-year-old man with a week of sinusitis sym',
  ("cmsent_l17_pool", 3): 'A 4-year-old boy has had two weeks of purulent',
  ("cmsent_l17_pool", 4): 'A 73-year-old man comes to the emergency depar',
  ("cmsent_l17_pool", 5): 'A 9-year-old boy has recurrent nosebleeds from',
  ("cmsent_l17_pool", 6): 'A 16-year-old girl is struck in the nose durin',
  ("cmsent_l17_pool", 7): 'A 27-year-old man is punched in the nose. He h',
  ("cmsent_l17_pool", 8): 'A 7-year-old boy is found to have multiple gre',
  ("cmsent_l17_pool", 9): 'A 22-year-old woman has clear discharge from b',
  ("cmsent_l17_pool", 10): 'A 44-year-old man of southern Chinese origin h',
  ("cmsent_l17_pool", 11): 'A 39-year-old man has nasal crusting, whistlin',
  ("cmsent_l17b_pool", 0): 'A 34-year-old woman had a cold that improved o',
  ("cmsent_l17b_pool", 1): 'A 41-year-old man has had nasal congestion, fa',
  ("cmsent_l17b_pool", 2): 'A 63-year-old man with poorly controlled diabe',
  ("cmsent_l17b_pool", 3): 'A patient with a nosebleed is being instructed',
  ("cmsent_l17b_pool", 4): 'A 3-year-old inserted a small button battery i',
  ("cmsent_l17b_pool", 5): 'A 38-year-old man has chronic unilateral nasal',
  ("cmsent_l17b_pool", 6): 'A patient with ethmoid sinusitis develops orbi',
  ("cmsent_l17b_pool", 7): 'A 26-year-old man with perennial allergic rhin',
  ("cmsent_l17b_pool", 8): 'A 45-year-old woman with asthma has nasal poly',
  ("cmsent_l17b_pool", 9): 'A 24-year-old woman is struck in the nose. She',
  ("cmsent_l17b_pool", 10): 'A 55-year-old man on no medication has a singl',
  ("cmsent_l17b_pool", 11): 'A patient with an undrained septal haematoma r',
  ("cmsent_l17c_pool", 0): 'A 29-year-old woman with sinusitis asks why he',
  ("cmsent_l17c_pool", 1): 'A clinician lists the features that shift an a',
  ("cmsent_l17c_pool", 2): 'A 47-year-old man with chronic rhinosinusitis ',
  ("cmsent_l17c_pool", 3): 'A 66-year-old man has heavy bleeding from both',
  ("cmsent_l17c_pool", 4): 'A 3-year-old has a bead in the left nostril. T',
  ("cmsent_l17c_pool", 5): 'A 44-year-old woman has a septal perforation. ',
  ("cmsent_l17c_pool", 6): 'A 26-year-old man with sinusitis develops alte',
  ("cmsent_l17c_pool", 7): 'A 31-year-old woman with allergic rhinitis is ',
  ("cmsent_l17c_pool", 8): 'A 52-year-old man with nasal polyps had endosc',
  ("cmsent_l17c_pool", 9): 'A 30-year-old man is assaulted and has clear f',
  ("cmsent_l17c_pool", 10): 'A clinician is asked which virus is most stron',
  ("cmsent_l17c_pool", 11): 'A 58-year-old woman on chemotherapy has facial',
  ("cmsent_l18_pool", 0): 'A 14-year-old girl has a painless swelling in ',
  ("cmsent_l18_pool", 1): 'A 21-year-old man has a tender, fluctuant swel',
  ("cmsent_l18_pool", 2): 'A 58-year-old man who smokes and drinks daily ',
  ("cmsent_l18_pool", 3): 'A 52-year-old woman has a solitary thyroid nod',
  ("cmsent_l18_pool", 4): 'A 34-year-old woman has a thyroid nodule. Fine',
  ("cmsent_l18_pool", 5): 'A 41-year-old man is diagnosed with a thyroid ',
  ("cmsent_l18_pool", 6): 'A 2-year-old girl has a soft, doughy, non-tend',
  ("cmsent_l18_pool", 7): 'A 6-month-old has a red, soft, compressible ma',
  ("cmsent_l18_pool", 8): 'A 3-year-old has a unilateral neck mass in the',
  ("cmsent_l18_pool", 9): 'An 81-year-old woman has a rapidly enlarging h',
  ("cmsent_l18_pool", 10): 'A 66-year-old woman with long-standing Hashimo',
  ("cmsent_l18_pool", 11): 'A surgeon is operating in the triangle bounded',
  ("cmsent_l18_pool", 12): 'A patient has an infected palatine tonsil. A s',
  ("cmsent_l18_pool", 13): 'A 12-year-old boy has a tender preauricular an',
  ("cmsent_l18b_pool", 0): 'A 47-year-old woman has a neck mass that is pu',
  ("cmsent_l18b_pool", 1): 'A 33-year-old man has a neck mass that has enl',
  ("cmsent_l18b_pool", 2): 'A 49-year-old woman has a firm thyroid nodule ',
  ("cmsent_l18b_pool", 3): 'A clinician is performing fine needle aspirati',
  ("cmsent_l18b_pool", 4): 'A 24-year-old woman has a slowly growing, pain',
  ("cmsent_l18b_pool", 5): 'A 6-week-old infant has a firm, painless, disc',
  ("cmsent_l18b_pool", 6): 'A 52-year-old professional trumpet player has ',
  ("cmsent_l18b_pool", 7): 'A newborn has a large firm neck mass noted at ',
  ("cmsent_l18b_pool", 8): 'A 44-year-old man who hunts rabbits has fever,',
  ("cmsent_l18b_pool", 9): 'A 51-year-old man has a painless, fluctuant sw',
  ("cmsent_l18b_pool", 10): 'A 55-year-old woman with a thyroid carcinoma i',
  ("cmsent_l18b_pool", 11): 'A trauma patient has a penetrating wound in th',
  ("cmsent_l18b_pool", 12): 'A 36-year-old man with newly diagnosed HIV has',
  ("cmsent_l18b_pool", 13): 'A 9-year-old has a slow-growing, asymptomatic ',
  ("cmsent_l18b_pool", 14): 'A clinician is taught that age changes the pri',
  ("cmsent_l18c_pool", 0): 'A 62-year-old smoker has a firm cervical node.',
  ("cmsent_l18c_pool", 1): 'A clinician explains why fine needle aspiratio',
  ("cmsent_l18c_pool", 2): 'A 6-year-old has a 2 centimetre cervical node ',
  ("cmsent_l18c_pool", 3): 'A radionuclide scan of a solitary thyroid nodu',
  ("cmsent_l18c_pool", 4): 'A 29-year-old woman has papillary thyroid carc',
  ("cmsent_l18c_pool", 5): 'A 38-year-old man who drinks unpasteurised mil',
  ("cmsent_l18c_pool", 6): 'A 55-year-old woman on immunosuppression after',
  ("cmsent_l18c_pool", 7): 'A 4-year-old has five days of high fever, bila',
  ("cmsent_l18c_pool", 8): 'A pulsatile neck mass has been identified. Ima',
  ("cmsent_l18c_pool", 10): 'A patient treated for medullary thyroid carcin',
  ("cmsent_l18c_pool", 11): 'A surgeon operating in the occipital triangle ',
  ("cmsent_l18c_pool", 12): 'A 12-year-old has a midline submental mass tha',
  ("cmsent_l18c_pool", 13): 'A 33-year-old man has a fluctuant, tender neck',
  ("cmsent_l18c_pool", 14): 'A clinician palpates a neck mass and finds it ',
  ("cmsent_l19_pool", 0): 'A 17-year-old attended four days ago with a 10',
  ("cmsent_l19_pool", 1): 'A 68-year-old with a 50 pack-year smoking hist',
  ("cmsent_l19_pool", 2): 'A 4-year-old is brought in with a few hours of',
  ("cmsent_l19_pool", 3): 'A 19-year-old university student is treated wi',
  ("cmsent_l19_pool", 4): 'A 20-year-old is confirmed to have infectious ',
  ("cmsent_l19_pool", 5): 'A 48-year-old man has recurrent painful swelli',
  ("cmsent_l19_pool", 6): 'A 62-year-old man using an inhaled corticoster',
  ("cmsent_l19_pool", 7): 'A 59-year-old man who has chewed tobacco for t',
  ("cmsent_l19_pool", 8): 'A 61-year-old woman who smokes and drinks has ',
  ("cmsent_l19_pool", 9): 'A 46-year-old man with poorly controlled diabe',
  ("cmsent_l19_pool", 10): 'A 3-year-old has fever, sore throat, neck stif',
  ("cmsent_l19_pool", 11): 'A 10-year-old has a two-day sore throat with a',
  ("cmsent_l19_pool", 12): 'A 9-year-old boy who shouts constantly during ',
  ("cmsent_l19_pool", 13): 'A 51-year-old man who smokes heavily and uses ',
  ("cmsent_l19_pool", 14): 'A 34-year-old woman has facial pain, clicking ',
  ("cmsent_l19_pool", 15): 'A 79-year-old woman is four days after hip sur',
  ("cmsent_l19_pool", 16): 'An 8-year-old recently arrived from a region w',
  ("cmsent_l19b_pool", 0): 'A 19-year-old student has recurrent painful or',
  ("cmsent_l19b_pool", 1): 'A 54-year-old woman has lacy white lines on bo',
  ("cmsent_l19b_pool", 2): 'A 29-year-old man has recurrent painful oral u',
  ("cmsent_l19b_pool", 3): 'A 26-year-old woman has recurrent painful lesi',
  ("cmsent_l19b_pool", 4): 'A clinician wants the most sensitive test to d',
  ("cmsent_l19b_pool", 5): 'A 58-year-old man has a slowly enlarging painl',
  ("cmsent_l19b_pool", 6): 'A student asks how the site of a salivary tumo',
  ("cmsent_l19b_pool", 7): 'A 61-year-old woman has a breathy hoarse voice',
  ("cmsent_l19b_pool", 8): 'A patient with vocal cord paralysis after a ne',
  ("cmsent_l19b_pool", 9): 'A 3-year-old with recurrent respiratory papill',
  ("cmsent_l19b_pool", 10): 'A 6-year-old with suspected epiglottitis is tr',
  ("cmsent_l19b_pool", 11): 'A student is asked to distinguish pharyngitis,',
  ("cmsent_l19b_pool", 12): 'A 33-year-old man has gums that are red, swoll',
  ("cmsent_l19b_pool", 13): 'A 40-year-old man has a dental abscess. The to',
  ("cmsent_l19b_pool", 14): 'A 7-year-old has a unilateral, solitary, tende',
  ("cmsent_l19b_pool", 15): 'A clinician is describing a cervical node and ',
  ("cmsent_l19b_pool", 16): 'A 57-year-old smoker has been hoarse for seven',
  ("cmsent_l19c_pool", 0): 'A 22-year-old with a peritonsillar abscess has',
  ("cmsent_l19c_pool", 1): 'A 25-year-old man has had three peritonsillar ',
  ("cmsent_l19c_pool", 2): 'A student asks why retropharyngeal abscess car',
  ("cmsent_l19c_pool", 3): 'A 44-year-old man with Ludwig angina and diabe',
  ("cmsent_l19c_pool", 4): 'A clinician is defining the boundary between t',
  ("cmsent_l19c_pool", 5): 'A 64-year-old man has a squamous cell carcinom',
  ("cmsent_l19c_pool", 6): 'A 58-year-old woman with a tongue lesion repor',
  ("cmsent_l19c_pool", 7): 'A 3-month-old breastfed infant has white plaqu',
  ("cmsent_l19c_pool", 8): 'A 41-year-old man has painless white lesions o',
  ("cmsent_l19c_pool", 9): 'A 68-year-old man has had chronic unilateral p',
  ("cmsent_l19c_pool", 10): 'A 46-year-old man has severe sore throat, odyn',
  ("cmsent_l19c_pool", 11): 'A clinician explains why untreated streptococc',
  ("cmsent_l19c_pool", 12): 'A student is asked to describe the malocclusio',
  ("cmsent_l19c_pool", 13): 'A 29-year-old man has a painful lower wisdom t',
  ("cmsent_l19c_pool", 14): 'A clinician is asked when a pregnant woman sho',
  ("cmsent_topup2_pool", 0): 'A clinician explains why acute otitis media is',
  ("cmsent_topup2_pool", 1): 'A 6-year-old with mild acute otitis media, no ',
  ("cmsent_topup2_pool", 2): 'A 24-year-old woman has a red, hot, exquisitel',
  ("cmsent_topup2_pool", 3): 'A 68-year-old man with a conductive loss from ',
  ("cmsent_topup2_pool", 4): 'A 32-year-old diver has ear pain and vertigo o',
  ("cmsent_topup2_pool", 5): 'A clinician is asked how the character of ear ',
  ("cmsent_topup2_pool", 6): 'A 58-year-old man with otitis externa has spre',
  ("cmsent_topup2_pool", 7): 'A clinician is examining the ear of a 2-year-o',
  ("cmsent_topup2_pool", 8): 'A clinician is asked how acute, subacute and c',
  ("cmsent_topup2_pool", 9): 'A patient having a nosebleed asks whether to b',
  ("cmsent_topup2_pool", 10): 'A 48-year-old man has clear bilateral rhinorrh',
  ("cmsent_topup2_pool", 11): 'A clinician lists the conditions associated wi',
  ("cmsent_topup2_pool", 12): 'A 5-year-old has ten days of purulent nasal di',
  ("cmsent_topup2_pool", 13): 'A 55-year-old man has lost his sense of smell ',
  ("cmsent_topup2_pool", 14): 'A 26-year-old man with a displaced nasal fract',
  ("cmsent_topup2_pool", 15): 'A clinician is taught what to look for after a',
  ("cmsent_topup_pool", 0): 'A 60-year-old man needs wax removed. He has a ',
  ("cmsent_topup_pool", 1): 'A clinician is asked which organisms otitis ex',
  ("cmsent_topup_pool", 2): 'A clinician performs pneumatic otoscopy on a c',
  ("cmsent_topup_pool", 3): 'A 30-year-old woman with chronic suppurative o',
  ("cmsent_topup_pool", 4): 'A 28-year-old woman with otosclerosis asks abo',
  ("cmsent_topup_pool", 5): 'A 21-year-old man is struck on the ear with an',
  ("cmsent_topup_pool", 6): 'A student asks which paranasal sinuses are pre',
  ("cmsent_topup_pool", 7): 'A 78-year-old woman on warfarin has a noseblee',
  ("cmsent_topup_pool", 8): 'A 35-year-old man has used a topical decongest',
  ("cmsent_topup_pool", 9): 'A clinician explains why computed tomography i',
  ("cmsent_topup_pool", 10): 'A 5-year-old has chronic mouth breathing, snor',
  ("cmsent_topup_pool", 11): 'A 33-year-old woman has a mildly deviated sept',
  ("cmsent_topup_pool", 12): 'A clinician is asked what duration of a neck m',
  ("cmsent_topup_pool", 13): 'A clinician ranks the four thyroid carcinomas ',
  ("cmsent_topup_pool", 14): 'A 42-year-old man with untreated HIV has a rap',
  ("cmsent_topup_pool", 15): 'A clinician explains why the primary tumour mu',
  ("cmsent_topup_pool", 16): 'A 60-year-old man has a mass in the upper neck',
  ("cmsent_topup_pool", 17): 'A clinician is asked why the level of an invol',
  ("cmsent_topup_pool", 18): 'A clinician performs the Dix-Hallpike manoeuvr',
  ("cmsent_topup_pool", 19): 'A patient has both an air-bone gap and elevate',
  ("cmsent_topup_pool", 20): 'A patient starting a prolonged aminoglycoside ',
  ("cmsent_topup_pool", 21): 'A clinician is asked why oral examination is e',
  ("cmsent_l16c_pool", 2): 'A clinician wants to name the drug classes mos',
  ("cmsent_l18c_pool", 9): 'A student is asked to name the commonest conge',
}
