# -*- coding: utf-8 -*-
"""Rewritten stems for the Pharmacology I topic quizzes.

Jaxon, 2026-08-30: the exams were to be rewritten, not just trimmed. 175 of the
340 stems either opened with lecture-preamble ("what does the lecture say
about X") or ran past 95 characters. No exam question is phrased that way.

These are HAND-WRITTEN. A regex pass was tried twice and abandoned -- deleting
the subject strands the verb and yields "Which uses is for propranolol". Each
rewrite keeps the question asking exactly what it asked before, so the existing
answer key stays correct; only the wording changes.
"""
REWRITE = {
 "A genetically susceptible patient given succinylcholine with halothane develops muscular rigidity, metabolic acidosis, tachycardia and a very high temperature. What does the lecture direct?": "Succinylcholine with halothane causes rigidity, acidosis, tachycardia and fever. What is the treatment?",
 "A lesion is oozing, vesicular and crusting. Which end of the vehicle range does the lecture pair with that presentation?": "A lesion is oozing, vesicular and crusting. Which vehicle suits it?",
 "A parent asks what to do at home for a child with atopic dermatitis. Which set matches the lecture's non-pharmacologic advice?": "What is the home advice for a child with atopic dermatitis?",
 "A patient asks about the ciclopirox nail lacquer for onychomycosis. What does the lecture say about how well it works?": "How well does ciclopirox nail lacquer work for onychomycosis?",
 "A patient develops athlete's foot after prolonged use of occlusive footwear. Which predisposing factor is this?": "Athlete's foot after prolonged occlusive footwear. Which predisposing factor?",
 "A patient develops oral candidiasis after a course of broad-spectrum antibiotics. Which predisposing factor does this illustrate?": "Oral candidiasis after broad-spectrum antibiotics. Which predisposing factor?",
 "A patient develops pustular inflammation on the trunk a few weeks after starting a systemic corticosteroid. What does the lecture say happens when the steroid is stopped?": "Pustular inflammation on the trunk weeks after starting a steroid. What happens when it stops?",
 "A patient has diarrhoea, urination, small pupils, a slow heart, wet lungs, vomiting, watering eyes and drooling. Which picture is this?": "Diarrhoea, urination, small pupils, slow heart, wet lungs, vomiting, tearing, drooling. Which picture?",
 "A patient has encephalitis attributed to a herpes simplex virus. Which type does the lecture associate with the brain?": "Herpes simplex encephalitis. Which type affects the brain?",
 "A patient has meningitis attributed to a herpes simplex virus. Which type does the lecture associate with the meninges?": "Herpes simplex meningitis. Which type affects the meninges?",
 "A patient is agitated and hallucinating, with dilated pupils, flushed dry skin, fever, urinary retention and a fast heart. Which toxidrome is this?": "Agitation, hallucinations, dilated pupils, dry flushed skin, fever, retention. Which toxidrome?",
 "A patient is starting a topical azole. What does the lecture support telling them about duration?": "A patient is starting a topical azole. How long is the course?",
 "A patient on imiquimod reports redness, swelling and erosions at the site. What does the lecture say about this?": "A patient on imiquimod has redness, swelling and erosions. What does this mean?",
 "A patient presents on day 4 of an influenza-like illness. What does the lecture imply about oseltamivir?": "A patient presents on day 4 of influenza. What limits oseltamivir?",
 "A patient taking an aminopenicillin is also on warfarin. What does the lecture identify as the interaction?": "An aminopenicillin is added to warfarin. What is the interaction?",
 "A patient with poorly controlled diabetes develops a fungal infection. Which predisposing category does this represent?": "A poorly controlled diabetic develops a fungal infection. Which predisposing category?",
 "A patient's corticosteroid is not controlling a plaque. Based on the concentration gradient principle in the lecture, what does that principle predict?": "A corticosteroid is not controlling a plaque. What does the concentration gradient predict?",
 "An exacerbation warrants a medium to high potency corticosteroid. What does the lecture say to do next?": "An exacerbation needs a medium to high potency steroid. What next?",
 "An immunocompromised patient has systemic aspergillosis that has not responded to itraconazole or amphotericin B. Which class does the lecture position for this?": "Systemic aspergillosis unresponsive to itraconazole and amphotericin B. Which class?",
 "Besides blocking norepinephrine reuptake, what other action does the lecture give cocaine?": "Besides blocking norepinephrine reuptake, what else does cocaine do?",
 "For a time-dependent agent with no post-antibiotic effect, what dosing strategy does the lecture recommend?": "Which dosing strategy suits a time-dependent agent with no post-antibiotic effect?",
 "For which form of acne does the lecture name a topical retinoid as first line?": "For which form of acne is a topical retinoid first line?",
 "From what is acetylcholine synthesised, per the lecture's diagram?": "From what is acetylcholine synthesised?",
 "From which plants does the lecture say atropine is derived?": "From which plants is atropine derived?",
 "How does atropine's cardiovascular effect vary, per the lecture?": "How does atropine's cardiovascular effect vary with dose?",
 "How does bacitracin work, and what does the lecture say about its systemic toxicity?": "How does bacitracin work, and what is its systemic toxicity?",
 "How does the lecture characterise dopamine?": "What kind of agent is dopamine?",
 "How does the lecture describe the neuromuscular blocking drugs structurally?": "How are the neuromuscular blocking drugs described structurally?",
 "How does the lecture describe the nicotinic receptor?": "How is the nicotinic receptor structured?",
 "How does the lecture describe the two sections of an autonomic efferent pathway?": "What are the two sections of an autonomic efferent pathway?",
 "How does the lecture divide acne lesions?": "How are acne lesions divided?",
 "How does the lecture divide the efferent division of the peripheral nervous system?": "How is the efferent division of the peripheral nervous system divided?",
 "How does the lecture split topical against systemic therapy in acne?": "When is acne treated topically rather than systemically?",
 "How is norepinephrine given, per the lecture?": "How is norepinephrine given?",
 "How many steps does the lecture give for adrenergic neurotransmission?": "How many steps are there in adrenergic neurotransmission?",
 "How often is imiquimod applied, per the lecture?": "How often is imiquimod applied?",
 "Most topical acne agents cause skin irritation. What does the lecture say that leads to, and how does it advise starting?": "Most topical acne agents irritate. What does that cause, and how should you start?",
 "Norepinephrine extravasates from a drip and the skin blanches. What does the lecture give as treatment?": "Norepinephrine extravasates and the skin blanches. What is the treatment?",
 "Several antivirals in this lecture are prodrugs. Which set is correct?": "Which set of antivirals are prodrugs?",
 "The catecholamines penetrate the central nervous system poorly, yet the lecture still lists central-type adverse effects. Which are they?": "Catecholamines barely enter the brain, yet cause central-type effects. Which?",
 "The lecture lists five bacteriostatic agents. Which group is correct?": "Which group of five agents is bacteriostatic?",
 "The lecture says occlusion increases efficacy. What does it flag alongside that?": "Occlusion increases efficacy. What is flagged alongside it?",
 "Under drug factors for choosing a regimen, which toxicities does the lecture list as the organ systems to consider?": "Under drug factors, which organ-system toxicities are considered?",
 "What are acyclovir and penciclovir used for topically in the lecture, and what kind of molecule are they?": "What are topical acyclovir and penciclovir used for, and what are they?",
 "What are the two limits the lecture places on pralidoxime?": "What are the two limits on pralidoxime?",
 "What are the two proposed actions of azelaic acid in the lecture?": "What are the two proposed actions of azelaic acid?",
 "What collateral consequence of fluoroquinolone overuse does the lecture emphasise?": "What is the collateral consequence of fluoroquinolone overuse?",
 "What distinguishes a bacteriostatic drug from a bactericidal drug, as the lecture defines them?": "What distinguishes a bacteriostatic drug from a bactericidal one?",
 "What distinguishes scopolamine from atropine in the lecture?": "What distinguishes scopolamine from atropine?",
 "What do the bladder antimuscarinics do, per the lecture?": "What do the bladder antimuscarinics do?",
 "What does bacterial lipase do in the acne cascade the lecture describes?": "What does bacterial lipase do in the acne cascade?",
 "What does imiquimod do, per the lecture?": "What does imiquimod do?",
 "What does the afferent division of the peripheral nervous system do, and what example does the lecture give?": "What does the afferent division do, and what is an example?",
 "What does the lecture advise patients about washing in acne?": "What is the advice about washing in acne?",
 "What does the lecture call the two phases of succinylcholine's action?": "What are the two phases of succinylcholine's action?",
 "What does the lecture note about oseltamivir resistance?": "What is happening to oseltamivir resistance?",
 "What does the lecture say about cardioselectivity at higher doses?": "What happens to cardioselectivity at higher doses?",
 "What does the lecture say about isotretinoin and pregnancy?": "What is the position on isotretinoin in pregnancy?",
 "What does the lecture say about neostigmine's absorption and central penetration?": "What is neostigmine's absorption and central penetration?",
 "What does the lecture say about nystatin's absorption?": "How well is nystatin absorbed?",
 "What does the lecture say about starting acyclovir within the first 24 hours of chickenpox?": "What does acyclovir achieve if started within 24 hours of chickenpox?",
 "What does the lecture say about the enteric nervous system?": "What is the enteric nervous system?",
 "What does the lecture say distinguishes dobutamine from other sympathomimetics?": "What distinguishes dobutamine from other sympathomimetics?",
 "What does the lecture say happens when epinephrine is given to a patient on a beta blocker?": "What happens when epinephrine is given to a patient on a beta blocker?",
 "What does the lecture say happens with nicotine at autonomic ganglia?": "What does nicotine do at autonomic ganglia?",
 "What does the lecture say nicotine does at the nicotinic receptor across concentrations?": "What does nicotine do at the nicotinic receptor as concentration rises?",
 "What does the lecture say norepinephrine acts as?": "What does norepinephrine act as?",
 "What does the lecture tell patients to do after handling a scopolamine patch?": "What must a patient do after handling a scopolamine patch?",
 "What does the lecture warn about stopping clonidine abruptly?": "What is the risk of stopping clonidine abruptly?",
 "What does the lecture warn happens if oxymetazoline is used beyond three days?": "What happens if oxymetazoline is used beyond three days?",
 "What is carbachol's clinical use in the lecture, and what receptor activity does it have?": "What is carbachol used for, and what receptors does it hit?",
 "What is mupirocin's mechanism in the lecture?": "What is mupirocin's mechanism?",
 "What is pyridostigmine's clinical role in the lecture?": "What is pyridostigmine's clinical role?",
 "What is the anti-inflammatory action the lecture attributes to tetracyclines in acne?": "What is the anti-inflammatory action of tetracyclines in acne?",
 "What is the approximate rate of penicillin cross-sensitivity with cephalosporins in this lecture?": "What is the approximate rate of penicillin cross-sensitivity with cephalosporins?",
 "What is the depot effect described in the lecture, and what does it allow?": "What is the depot effect, and what does it allow?",
 "What is the mechanism the lecture gives for the topical azole antifungals?": "What is the mechanism of the topical azole antifungals?",
 "What loading dose does the lecture give for vancomycin in critically ill patients?": "What is the vancomycin loading dose in a critically ill patient?",
 "What monitoring does the lecture specify for daptomycin?": "What monitoring does daptomycin need?",
 "What monitoring does the lecture specify for the penicillinase-resistant penicillins?": "What monitoring do the penicillinase-resistant penicillins need?",
 "What rank order of potency does the lecture give for alpha receptors?": "What is the rank order of potency at alpha receptors?",
 "What term does the lecture give as synonymous with an indirect-acting cholinergic agonist?": "What is another term for an indirect-acting cholinergic agonist?",
 "What warning does the lecture attach to polymyxin B?": "What warning applies to polymyxin B?",
 "Where does the lecture place M2 receptors?": "Where are M2 receptors found?",
 "Where does the lecture place alpha-one as against alpha-two receptors?": "Where are alpha-one receptors found, against alpha-two?",
 "Which adverse effect does the lecture attach to atracurium specifically?": "Which adverse effect is specific to atracurium?",
 "Which adverse effect does the lecture attach to physostigmine at high doses?": "Which adverse effect does physostigmine cause at high doses?",
 "Which adverse effect of benzoyl peroxide most needs to be raised with a patient before they start it?": "Which benzoyl peroxide effect must be raised before starting it?",
 "Which adverse effects does the lecture attach to the older bladder agents such as oxybutynin and tolterodine?": "Which adverse effects do the older bladder agents cause?",
 "Which adverse effects does the lecture list for albuterol?": "What are albuterol's adverse effects?",
 "Which adverse effects does the lecture list for dopamine?": "What are dopamine's adverse effects?",
 "Which adverse reactions does the lecture list for the antipseudomonal penicillins?": "What are the antipseudomonal penicillins' adverse reactions?",
 "Which agent does the lecture place in class 1, superpotent?": "Which agent is class 1, superpotent?",
 "Which agents does the lecture call the gold standard for atopic dermatitis?": "Which agents are the gold standard for atopic dermatitis?",
 "Which agents does the lecture name for Alzheimer disease, and what is the rationale?": "Which agents treat Alzheimer disease, and why?",
 "Which antiandrogen does the lecture name for acne?": "Which antiandrogen is used for acne?",
 "Which antimuscarinic does the lecture identify as approved for axillary hyperhidrosis?": "Which antimuscarinic is approved for axillary hyperhidrosis?",
 "Which antisecretory use does the lecture give for atropine?": "What is atropine's antisecretory use?",
 "Which antiviral in this lecture does NOT act on viral nucleic acid?": "Which antiviral does NOT act on viral nucleic acid?",
 "Which azole penetrates the central nervous system and is therefore used in cryptococcal meningitis?": "Which azole enters the brain and treats cryptococcal meningitis?",
 "Which azole replaced amphotericin B for systemic aspergillosis, and what is its characteristic adverse effect?": "Which azole replaced amphotericin B for aspergillosis, and with what effect?",
 "Which body sites does the lecture name as more permeable to a topical drug?": "Which body sites are more permeable to a topical drug?",
 "Which cephalosporin is preferred in neonatal fever or sepsis, and which is restricted in the first 30 days of life?": "Which cephalosporin is preferred in neonatal sepsis, and which is restricted?",
 "Which conditions make up the atopic triad the lecture places atopic dermatitis within?": "Which conditions make up the atopic triad?",
 "Which drug interaction of sulfamethoxazole/trimethoprim involves cytochrome P450 2C9 inhibition?": "Which Bactrim interaction runs through CYP2C9 inhibition?",
 "Which effect do the alpha-adrenergic blocking agents share, per the lecture?": "Which effect do the alpha-adrenergic blocking agents share?",
 "Which effects does the lecture give as predominating with ganglionic blockade?": "Which effects predominate with ganglionic blockade?",
 "Which emergency indications does the lecture give for epinephrine?": "What are epinephrine's emergency indications?",
 "Which forms of shock does the lecture pair with dopamine?": "Which forms of shock is dopamine used for?",
 "Which gap in coverage does the lecture flag for tolnaftate?": "Which gap in coverage does tolnaftate have?",
 "Which herpesviruses does this lecture group together as targets for antiviral therapy?": "Which herpesviruses are grouped as targets for antiviral therapy?",
 "Which hypertensive crisis does the lecture pair with phentolamine?": "Which hypertensive crisis is phentolamine used for?",
 "Which indications does the lecture give for the echinocandins?": "What are the echinocandins' indications?",
 "Which interaction does the lecture describe between benzoyl peroxide and tretinoin?": "What is the interaction between benzoyl peroxide and tretinoin?",
 "Which laboratory change does the lecture list among isotretinoin's adverse reactions?": "Which laboratory change does isotretinoin cause?",
 "Which manifestations does the lecture attribute to cytomegalovirus?": "Which manifestations does cytomegalovirus cause?",
 "Which metabolic effect does the lecture attribute to the alpha-one blockers used for hypertension?": "Which metabolic effect do the alpha-one blockers have?",
 "Which muscarinic receptor subtypes does the lecture say are functionally characterised?": "Which muscarinic receptor subtypes are functionally characterised?",
 "Which muscles does the lecture say are paralysed first by a nondepolarizing blocker?": "Which muscles does a nondepolarizing blocker paralyse first?",
 "Which mycoses does the lecture place in the subcutaneous category?": "Which mycoses are subcutaneous?",
 "Which neurotransmitter does the lecture describe as the major inhibitory transmitter in the brain?": "Which is the major inhibitory transmitter in the brain?",
 "Which non-cardiovascular use does the lecture give for phentolamine?": "What is phentolamine's non-cardiovascular use?",
 "Which of the two does the lecture link to preventing cardiovascular mortality in heart failure?": "Which of the two prevents cardiovascular mortality in heart failure?",
 "Which of these is a LOCAL adverse effect of topical steroids in the lecture, rather than a systemic one?": "Which is a LOCAL adverse effect of topical steroids, not a systemic one?",
 "Which organism does the lecture name as proliferating in the anaerobic conditions created by pooled sebum?": "Which organism proliferates in the anaerobic conditions of pooled sebum?",
 "Which organism has increasingly rendered the penicillinase-resistant penicillins ineffective, and what replaces them?": "Which organism defeats the penicillinase-resistant penicillins, and what replaces them?",
 "Which organisms does the lecture list as causes of systemic mycoses affecting internal organs?": "Which organisms cause systemic mycoses of the internal organs?",
 "Which organisms does the lecture list as excellent tetracycline coverage?": "Which organisms do tetracyclines cover excellently?",
 "Which patient does the lecture say should avoid topical tacrolimus or pimecrolimus?": "Which patient should avoid topical tacrolimus or pimecrolimus?",
 "Which patient should not be given a topical retinoid, per the lecture?": "Which patient should not be given a topical retinoid?",
 "Which pharmacokinetic properties does the lecture list under drug factors when choosing a regimen?": "Which pharmacokinetic properties count under drug factors?",
 "Which pigmentary adverse effect does the lecture attach to azelaic acid?": "Which pigmentary adverse effect does azelaic acid cause?",
 "Which poisoning does the lecture say physostigmine treats?": "Which poisoning does physostigmine treat?",
 "Which problem does the lecture specifically attach to topical neomycin?": "Which problem is specific to topical neomycin?",
 "Which rank order of potency does the lecture give for beta receptors?": "What is the rank order of potency at beta receptors?",
 "Which retinoid does the lecture pair with Kaposi sarcoma?": "Which retinoid is used for Kaposi sarcoma?",
 "Which sequence describes neurotransmission at a cholinergic neuron in the lecture?": "Which sequence describes neurotransmission at a cholinergic neuron?",
 "Which set gives the MAJOR indicators of atopic dermatitis as the lecture lists them?": "Which set gives the MAJOR indicators of atopic dermatitis?",
 "Which set matches atropine's adverse effects in the lecture?": "Which set matches atropine's adverse effects?",
 "Which set matches the nicotinic effects the lecture lists?": "Which set matches the nicotinic effects?",
 "Which set of cardiovascular effects does the lecture give for acetylcholine itself?": "Which cardiovascular effects does acetylcholine itself have?",
 "Which statement about antimuscarinic agents matches the lecture?": "Which statement about antimuscarinic agents is correct?",
 "Which systemic corticosteroid does the lecture explicitly exclude from causing drug-induced acne?": "Which systemic corticosteroid does NOT cause drug-induced acne?",
 "Which systemic effects does the lecture attribute to topical corticosteroids?": "Which systemic effects do topical corticosteroids cause?",
 "Which terms does the lecture give as synonymous with cholinergic antagonists?": "Which terms mean the same as cholinergic antagonists?",
 "Which three actions does the lecture attribute to topical retinoic acid?": "Which three actions does topical retinoic acid have?",
 "Which three classes make up the cholinergic antagonists in the lecture?": "Which three classes make up the cholinergic antagonists?",
 "Which three general types of signalling between cells does the lecture list?": "What are the three general types of signalling between cells?",
 "Which three polyene agents does the lecture name?": "Which are the three polyene agents?",
 "Which three systems make up the autonomic division in the lecture?": "Which three systems make up the autonomic division?",
 "Which topical antibiotic does the lecture name as the preferred agent for acne, and what is happening to the alternative?": "Which topical antibiotic is preferred for acne, and what is happening to the alternative?",
 "Which two agents does the lecture name as allylamines, and how do they work?": "Which two agents are allylamines, and how do they work?",
 "Which two agents does the lecture name as having intrinsic sympathomimetic activity?": "Which two agents have intrinsic sympathomimetic activity?",
 "Which two alpha-one blockers does the lecture direct to benign prostatic hyperplasia?": "Which two alpha-one blockers are used for benign prostatic hyperplasia?",
 "Which two antiviral agents in this lecture are given intravenously as the parent compound?": "Which two antivirals are given intravenously as the parent compound?",
 "Which two groups are contraindicated from receiving tetracyclines, per the lecture?": "Which two groups must not receive tetracyclines?",
 "Which two groups does the lecture divide the direct-acting cholinergic agonists into?": "Into which two groups do the direct-acting cholinergic agonists divide?",
 "Which two problems does the lecture attach to intralesional steroid injection of an inflammatory nodule?": "Which two problems follow intralesional steroid injection of a nodule?",
 "Which two properties does the lecture use to distinguish adapalene from tretinoin?": "Which two properties distinguish adapalene from tretinoin?",
 "Which use does the lecture give for mupirocin beyond ordinary skin infection?": "What is mupirocin used for beyond ordinary skin infection?",
 "Which uses does the lecture list for neostigmine?": "What is neostigmine used for?",
 "Which uses does the lecture list for phenylephrine?": "What is phenylephrine used for?",
 "Which uses does the lecture list for propranolol beyond hypertension?": "What is propranolol used for beyond hypertension?",
 "Which vehicle does the lecture place at the most drying end of its range, and which at the least?": "Which vehicle is the most drying, and which the least?",
 "Why does the lecture counsel caution with dobutamine in atrial fibrillation?": "Why is caution advised with dobutamine in atrial fibrillation?",
 "Why does the lecture include a sedating antihistamine in the non-pharmacologic advice for a child with atopic dermatitis?": "Why is a sedating antihistamine advised for a child with atopic dermatitis?",
 "Why does the lecture prefer a selective beta-two agonist for chronic asthma over epinephrine?": "Why is a selective beta-two agonist preferred over epinephrine in chronic asthma?",
 "Why does the lecture say an azole is sometimes combined with a corticosteroid?": "Why is an azole sometimes combined with a corticosteroid?",
 "Why does the lecture say an oral corticosteroid course for atopic dermatitis needs a tapering dose?": "Why does an oral corticosteroid course for atopic dermatitis need a taper?",
 "Why does the lecture say competitive neuromuscular blockers significantly increased the safety of anaesthesia?": "Why did competitive neuromuscular blockers make anaesthesia safer?",
 "Why does the lecture say to apply topical acne therapy to the whole affected area rather than to individual spots?": "Why is topical acne therapy applied to the whole area rather than to spots?",
 "Why does the lecture say tretinoin should be applied at night?": "Why is tretinoin applied at night?",
 "Why does the lecture suggest a small dose of a nondepolarizing blocker before succinylcholine?": "Why give a small dose of a nondepolarizing blocker before succinylcholine?",
 "Why is influenza treatment framed around a season in this lecture?": "Why is influenza treatment framed around a season?",
 "Why is succinylcholine suited to rapid sequence intubation, per the lecture?": "Why is succinylcholine suited to rapid sequence intubation?",
}
