# CMS I Lecture 3 (Dermatology II) — SET 1 pool B (objective style).
# Erythema nodosum, granuloma annulare, pyoderma gangrenosum, acne rosacea,
# hyperhidrosis.
#
# Options drafted at matched lengths, per the practice that took pool A from a
# projected 66% length-gameable down to 17%.
#
# Correct answer is ALWAYS written first (c=0); the partition script rotates.
SRC = "3. Dermatology  II.pptx"
def c(n): return f"{SRC}, Slide {n}"

IOA = "Objective a — Etiologies, manifestations, diagnosis and management of dermatological conditions"

POOL_B = [
 dict(topic="Erythema nodosum", io=IOA,
   q="What kind of process is erythema nodosum, histologically?",
   opts=[
     ["A septal panniculitis without vasculitis",
      "Correct — the most common form of panniculitis, a delayed hypersensitivity reaction in subcutaneous fat."],
     ["A lobular panniculitis with associated vasculitis",
      "That describes nodular vasculitis, or erythema induratum, a differential."],
     ["A palisading granuloma around degenerating collagen",
      "That describes granuloma annulare."],
     ["A dense neutrophilic infiltrate without organisms",
      "That describes pyoderma gangrenosum."]],
   c=0, cite=c(42)),

 dict(topic="Erythema nodosum", io=IOA,
   q="Which single feature most usefully distinguishes erythema nodosum from nodular vasculitis?",
   opts=[
     ["Erythema nodosum nodules do not ulcerate",
      "Correct, and they sit on the anterior shins whereas nodular vasculitis favours the posterior legs and ulcerates."],
     ["Erythema nodosum nodules appear only on the posterior legs",
      "The anterior shins are the characteristic site."],
     ["Erythema nodosum nodules are painless on palpation",
      "The nodules are tender, which is part of the classic description."],
     ["Erythema nodosum nodules occur exclusively in men",
      "There is a female predominance of three to six to one."]],
   c=0, cite=c(43)),

 dict(topic="Erythema nodosum", io=IOA,
   q="What is the most common infectious trigger of erythema nodosum?",
   opts=[
     ["Group A Streptococcus",
      "Correct, alongside Yersinia, tuberculosis, coccidioidomycosis, histoplasmosis and hepatitis B and C."],
     ["Mycoplasma pneumoniae",
      "Mycoplasma is a leading trigger of erythema multiforme rather than erythema nodosum."],
     ["Herpes simplex virus",
      "Herpes simplex triggers over half of erythema multiforme cases."],
     ["Staphylococcus aureus",
      "This organism is not among the named triggers."]],
   c=0, cite=c(42)),

 dict(topic="Erythema nodosum", io=IOA,
   q="How do erythema nodosum lesions evolve, and what is that appearance called?",
   opts=[
     ["Over three to six weeks from bright red to bruise-like, called erythema contusiforme",
      "Correct, often preceded by a prodrome of fever, arthralgia and malaise one to three weeks earlier."],
     ["Over three to six days from bruise-like to bright red, called erythema migrans",
      "The sequence runs the other way and erythema migrans is the rash of Lyme disease."],
     ["Over several months into permanent atrophic scars, called atrophie blanche",
      "Atrophie blanche is a chronic feature of stasis disease."],
     ["Over one to two weeks into target lesions, called iris lesions",
      "Target or iris lesions belong to erythema multiforme."]],
   c=0, cite=c(43)),

 dict(topic="Erythema nodosum", io=IOA,
   q="Which investigation is used to look for the sarcoidosis association in erythema nodosum?",
   opts=[
     ["Chest radiograph, seeking bilateral hilar lymphadenopathy",
      "Correct — Löfgren syndrome, which has the best prognosis of all sarcoidosis presentations."],
     ["Colonoscopy, seeking mucosal ulceration and skip lesions",
      "Colonoscopy is done when inflammatory bowel disease symptoms are present."],
     ["Antistreptolysin O titre with a throat culture",
      "These exclude a streptococcal trigger."],
     ["Serum protein electrophoresis, seeking a monoclonal band",
      "That screens for the gammopathy associated with pyoderma gangrenosum."]],
   c=0, cite=c(44)),

 dict(topic="Granuloma annulare", io=IOA,
   q="What does biopsy show in granuloma annulare?",
   opts=[
     ["Palisading granulomas with central necrobiosis and mucin deposition",
      "Correct — thought to involve a type IV delayed hypersensitivity reaction around degenerating collagen."],
     ["Septal panniculitis without vasculitis and Miescher's granulomas",
      "That is erythema nodosum."],
     ["A dense neutrophilic infiltrate at the ulcer edge",
      "That is pyoderma gangrenosum."],
     ["Interface dermatitis with scattered necrotic keratinocytes",
      "That is erythema multiforme."]],
   c=0, cite=c(51)),

 dict(topic="Granuloma annulare", io=IOA,
   q="Which variant of granuloma annulare carries the strongest systemic associations?",
   opts=[
     ["Generalised or disseminated, associated with diabetes, thyroid disease, dyslipidaemia and lymphoma",
      "Correct, and it is more common in adults over forty."],
     ["Localised, which predominates and affects children and young adults",
      "Localised disease accounts for about 75% of cases and is asymptomatic."],
     ["Subcutaneous, occurring almost exclusively in children under six",
      "This variant may mimic rheumatoid nodules but lacks those systemic links."],
     ["Perforating, with central umbilication and extrusion of collagen",
      "This variant may scar but is not the one with systemic associations."]],
   c=0, cite=c(50)),

 dict(topic="Granuloma annulare", io=IOA,
   q="What is the main differential for localised granuloma annulare, and how is it separated?",
   opts=[
     ["Tinea corporis, which has a scaling border and is potassium hydroxide positive",
      "Correct — granuloma annulare has no scale on its ring."],
     ["Necrobiosis lipoidica, which has a yellow-waxy atrophic centre on the shins",
      "This is a differential but is distinguished by its site and appearance rather than being the main one."],
     ["Rheumatoid nodules, which are firm, periarticular and serology positive",
      "These are a differential chiefly for the subcutaneous variant."],
     ["Lichen planus, which is violaceous and polygonal with Wickham striae",
      "This is a listed differential but not the principal one."]],
   c=0, cite=c(50)),

 dict(topic="Granuloma annulare", io=IOA,
   q="What is the expected course of localised granuloma annulare?",
   opts=[
     ["Half of cases resolve spontaneously within two years, so watchful waiting is reasonable",
      "Correct — treatment is primarily for cosmesis or discomfort, and there is no malignant potential."],
     ["Nearly all cases progress without systemic therapy, so early treatment is essential",
      "Localised disease is benign and self-limiting in about half of patients."],
     ["Most cases transform into squamous cell carcinoma if left untreated",
      "There is no malignant potential."],
     ["Lesions persist unchanged lifelong and never resolve without intervention",
      "Spontaneous resolution occurs in about half within two years."]],
   c=0, cite=c(51)),

 dict(topic="Pyoderma gangrenosum", io=IOA,
   q="What is pyoderma gangrenosum, despite its name?",
   opts=[
     ["A neutrophilic dermatosis that is not infectious",
      "Correct — dysregulated innate immune activation with neutrophil recruitment causes the tissue destruction."],
     ["A deep bacterial infection requiring prolonged antibiotics",
      "The name is misleading; wound cultures are obtained precisely to exclude infection."],
     ["A vasculitis of medium-sized vessels with immune complex deposition",
      "Vasculitis is among the differentials that must be excluded."],
     ["A malignant ulcerating tumour of keratinocyte origin",
      "Squamous cell carcinoma is a differential requiring biopsy to exclude."]],
   c=0, cite=c(57)),

 dict(topic="Pyoderma gangrenosum", io=IOA,
   q="Which systemic association is present in a quarter to a half of pyoderma gangrenosum cases?",
   opts=[
     ["Inflammatory bowel disease",
      "Correct, and peristomal disease occurs in up to 15% of patients with intestinal ostomies and bowel disease."],
     ["Rheumatoid arthritis and seronegative arthritis",
      "These are recognised associations but not at that frequency."],
     ["Haematologic malignancy such as acute myeloid leukaemia",
      "This is associated particularly with the bullous variant but not at that rate."],
     ["Monoclonal gammopathy of undetermined significance",
      "This is a recognised association but not the most frequent one."]],
   c=0, cite=c(57)),

 dict(topic="Pyoderma gangrenosum", io=IOA,
   q="What is pathergy, and what does it mean for management?",
   opts=[
     ["Worsening of the ulcer with trauma or debridement, which is why debridement must be avoided",
      "Correct — this is the single most consequential management point in the condition."],
     ["Spread of the ulcer to distant sites through the bloodstream",
      "Pathergy refers to the local response to trauma rather than dissemination."],
     ["Failure of the ulcer to culture any organism despite clinical infection",
      "Culture negativity helps exclude infection but is not pathergy."],
     ["Recurrence of the ulcer at the same site after apparent healing",
      "That describes a fixed recurrence rather than pathergy."]],
   c=0, cite=c(58)),

 dict(topic="Pyoderma gangrenosum", io=IOA,
   q="How is the diagnosis of pyoderma gangrenosum established?",
   opts=[
     ["By exclusion, since there is no gold standard test",
      "Correct — biopsy from the ulcer edge shows dense neutrophils and rules out malignancy and infection."],
     ["By biopsy showing a pathognomonic palisading granuloma",
      "Palisading granulomas belong to granuloma annulare."],
     ["By wound culture growing a characteristic organism",
      "Cultures are obtained to exclude an infectious cause; they are negative in pyoderma gangrenosum."],
     ["By serum antibody testing against dermal structural proteins",
      "The condition is not antibody-mediated in that way."]],
   c=0, cite=c(59)),

 dict(topic="Pyoderma gangrenosum", io=IOA,
   q="Which biologic is approved for pyoderma gangrenosum in inflammatory bowel disease?",
   opts=[
     ["Infliximab at 5 mg/kg intravenously",
      "Correct — the biologic of choice in that setting, with adalimumab and ustekinumab for refractory cases."],
     ["Omalizumab at 300 mg subcutaneously every four weeks",
      "That is approved for refractory chronic urticaria."],
     ["Etanercept at 25 to 50 mg subcutaneously",
      "That is described as an emerging adjunct in Stevens-Johnson syndrome."],
     ["Dupilumab given subcutaneously every two weeks",
      "That has been reported in refractory granuloma annulare."]],
   c=0, cite=c(60)),

 dict(topic="Acne rosacea", io=IOA,
   q="Which rosacea subtype is most common, and what defines it?",
   opts=[
     ["Erythematotelangiectatic, with persistent central facial erythema, flushing and telangiectasias but no papules or pustules",
      "Correct — the skin is often described as sensitive and stinging."],
     ["Papulopustular, with transient central facial papules and pustules on erythema and no comedones",
      "This is the classic presentation but not the most common subtype."],
     ["Phymatous, with skin thickening and nodular enlargement of the nose and chin",
      "This predominates in males but is not the most common subtype."],
     ["Ocular, with blepharitis, conjunctivitis and meibomian gland dysfunction",
      "This may precede or follow the skin findings but is not the most common subtype."]],
   c=0, cite=c(66)),

 dict(topic="Acne rosacea", io=IOA,
   q="Which feature separates papulopustular rosacea from acne vulgaris?",
   opts=[
     ["Rosacea has no comedones",
      "Correct — open or closed comedones point to acne vulgaris instead."],
     ["Rosacea produces pustules and acne vulgaris does not",
      "Both produce pustules; the comedones are what differ."],
     ["Rosacea occurs only in patients over the age of sixty",
      "Peak onset is between thirty and sixty."],
     ["Rosacea spares the central face entirely",
      "Central facial involvement is characteristic of rosacea."]],
   c=0, cite=c(68)),

 dict(topic="Acne rosacea", io=IOA,
   q="Which organism contributes to papulopustular rosacea?",
   opts=[
     ["Demodex folliculorum, whose overgrowth drives inflammation",
      "Correct, which is why ivermectin 1% cream outperforms metronidazole in Demodex-associated disease."],
     ["Malassezia, whose overgrowth drives inflammation in sebum-rich areas",
      "Malassezia drives seborrhoeic dermatitis."],
     ["Staphylococcus aureus, colonising the follicles",
      "This organism is not implicated in rosacea."],
     ["Cutibacterium acnes, proliferating within blocked follicles",
      "That organism relates to acne vulgaris."]],
   c=0, cite=c(65)),

 dict(topic="Acne rosacea", io=IOA,
   q="What is the role of sub-antimicrobial dose doxycycline in rosacea?",
   opts=[
     ["It is approved for papulopustular rosacea and works as an anti-inflammatory rather than an antimicrobial",
      "Correct, at 40 mg modified-release daily."],
     ["It eradicates Demodex folliculorum from the follicles over several weeks",
      "Ivermectin targets Demodex; doxycycline at this dose acts on inflammation."],
     ["It reduces flushing by blocking alpha-adrenergic receptors in the skin",
      "That is the mechanism of brimonidine and oxymetazoline."],
     ["It prevents rhinophyma from developing in male patients",
      "Rhinophyma is managed with isotretinoin, laser or surgery."]],
   c=0, cite=c(69)),

 dict(topic="Acne rosacea", io=IOA,
   q="Which rosacea complication requires urgent ophthalmology referral?",
   opts=[
     ["Ocular rosacea with keratitis, visual symptoms or corneal involvement",
      "Correct — untreated ocular disease risks corneal scarring."],
     ["Rhinophyma causing nasal airway narrowing over several years",
      "This is managed by dermatologic or plastic surgery rather than urgently."],
     ["Persistent central facial erythema unresponsive to topical therapy",
      "This is treated with laser or light therapy rather than urgent referral."],
     ["Papules and pustules spreading beyond the central face",
      "This warrants dermatology input rather than urgent ophthalmology."]],
   c=0, cite=c(70)),

 dict(topic="Hyperhidrosis", io=IOA,
   q="Which feature most reliably distinguishes primary from secondary hyperhidrosis?",
   opts=[
     ["Primary disease is bilateral, focal and absent during sleep",
      "Correct — secondary disease is generalised, may be asymmetric, and can occur at night."],
     ["Primary disease is generalised and worse at night",
      "That pattern indicates secondary hyperhidrosis."],
     ["Primary disease begins after the age of fifty",
      "Primary disease begins in adolescence, with peak onset between fourteen and twenty-five."],
     ["Primary disease always has an identifiable underlying cause",
      "Primary hyperhidrosis is idiopathic; secondary disease has an underlying cause."]],
   c=0, cite=c(73)),

 dict(topic="Hyperhidrosis", io=IOA,
   q="Which test objectively maps the distribution and severity of sweating?",
   opts=[
     ["Minor's starch-iodine test",
      "Correct, with gravimetry giving a quantitative sweat output measurement."],
     ["Photopatch testing with ultraviolet A irradiation",
      "That is the gold standard for photoallergy."],
     ["The autologous serum skin test",
      "That is used for autoimmune chronic urticaria."],
     ["Minimal erythema dose phototesting",
      "That assesses ultraviolet sensitivity in photodermatoses."]],
   c=0, cite=c(74)),

 dict(topic="Hyperhidrosis", io=IOA,
   q="Which investigation excludes phaeochromocytoma as a cause of secondary hyperhidrosis?",
   opts=[
     ["Twenty-four hour urine metanephrines and catecholamines",
      "Correct — episodic sweating with headache, palpitations and hypertension is the clue."],
     ["Thyroid-stimulating hormone with anti-thyroid peroxidase antibodies",
      "Those assess thyroid disease, another secondary cause."],
     ["Serum protein electrophoresis with immunofixation",
      "That screens for monoclonal gammopathy in pyoderma gangrenosum."],
     ["Fasting glucose with haemoglobin A1c",
      "Those assess diabetes, another secondary cause."]],
   c=0, cite=c(74)),

 dict(topic="Hyperhidrosis", io=IOA,
   q="What is first-line topical therapy for primary hyperhidrosis?",
   opts=[
     ["Aluminium chloride 20%, applied nightly to dry skin",
      "Correct, with glycopyrronium cloth approved for axillary disease and gel for palmar disease."],
     ["Botulinum toxin A injected intradermally into the affected area",
      "That is third-line procedural therapy lasting three to six months."],
     ["Oral glycopyrrolate at 1 to 2 mg twice daily",
      "Oral anticholinergics are second line."],
     ["Iontophoresis using tap water three times weekly",
      "That is a second-line physical treatment for palms and soles."]],
   c=0, cite=c(75)),

 dict(topic="Hyperhidrosis", io=IOA,
   q="What is the principal risk a patient must understand before endoscopic thoracic sympathectomy?",
   opts=[
     ["Compensatory sweating elsewhere, occurring in over 30%",
      "Correct — the procedure is permanent, so the trade-off has to be discussed thoroughly beforehand."],
     ["The need for retreatment every three to six months",
      "That applies to botulinum toxin rather than sympathectomy."],
     ["Dry mouth and urinary retention as ongoing side effects",
      "Those are the anticholinergic effects of oral therapy."],
     ["Permanent destruction of axillary glands by microwave energy",
      "That describes microwave thermolysis rather than sympathectomy."]],
   c=0, cite=c(75)),
]
