# -*- coding: utf-8 -*-
# CMS I Lecture 6 — SET 2, vignette pool B.
# Onychomycosis, id (dermatophytid) reaction, tinea incognito, cutaneous
# candidiasis and intertrigo, pityriasis versicolor.
#
# THE SLIDE IS AUTHORITATIVE (Jaxon, 2026-08-20). Every fact is from the deck.
# Lead-ins are explicit; distractors match the answer's shape.
# Correct answer is ALWAYS written first (c=0); the partition script rotates.
SRC = "6. Fungal and Viral Skin Infections - Jaquith.pptx"
def c(n): return f"{SRC}, Slide {n}"

IOA = "Objective a — Interpret a potassium hydroxide (KOH) wet mount preparation"
IOB = "Objective b — Compare and contrast the etiologies, epidemiology, risk factors, clinical manifestations, differential diagnosis, diagnostic testing (including ordering and interpretation), management (acute and chronic, including applicable rehabilitative and palliative care), appropriate referrals, patient education, and prognosis of cutaneous viral and fungal infections"
IOC = "Objective c — Identify medical care strategies for cutaneous viral and fungal infections for infant, child, adolescent, adult and elderly populations"

VIG_B = [
 dict(topic="Onychomycosis", io=IOC, lead="diagnosis",
   q="A 68-year-old man with diabetes has thickened, discoloured, crumbling great toenails with subungual debris and separation of the nail from its bed. Which risk factors in his history does the lecture specifically link to this condition?",
   opts=[
     ["Tinea pedis, age, diabetes, trauma, occlusive footwear, psoriasis, and vascular disease",
      "Correct — seven named risk factors."],
     ["Obesity, incontinence, immobility, recent antibiotics, and immunosuppression",
      "Those are the intertrigo risk factors."],
     ["Heat, humidity, oily skin, sweating, and corticosteroid exposure",
      "Those favour pityriasis versicolor."],
     ["Sharing combs and hats, contact with pets, and exposure to fallen hairs",
      "Those are the tinea capitis transmission routes."]],
   c=0, cite=c(47)),

 dict(topic="Onychomycosis", io=IOB, lead="next step",
   q="A patient with dystrophic toenails asks for oral terbinafine. Which is the most appropriate next step before prescribing?",
   opts=[
     ["Confirm fungus first, because many dystrophic nails are not fungal",
      "Correct — the deck devotes a whole slide to non-fungal dystrophy."],
     ["Prescribe the terbinafine, because the clinical appearance alone is diagnostic",
      "Appearance alone does not establish onychomycosis."],
     ["Prescribe a topical agent instead, because oral therapy is never used for nails",
      "Oral terbinafine is first-line for most dermatophyte nail disease."],
     ["Obtain a Wood lamp examination, because fluorescence confirms nail infection",
      "The lamp is not the confirmatory nail test."]],
   c=0, cite=c(51)),

 dict(topic="Onychomycosis", io=IOB, lead="test",
   q="A 64-year-old has thickened discoloured toenails and you decide to confirm the diagnosis before prescribing. Which tests does the lecture list, and how should the sample be taken?",
   opts=[
     ["Potassium hydroxide microscopy, periodic acid–Schiff stain of clippings, culture, or amplification testing; sample the most proximal accessible diseased nail bed",
      "Correct — sample subungual debris after trimming the onycholytic nail. Sampling proximally is the part most often missed."],
     ["Potassium hydroxide microscopy or fungal culture only; sample the most distal free edge of the nail plate before any trimming of the onycholytic nail is performed",
      "The deck asks for the most proximal accessible diseased tissue."],
     ["Serology for dermatophyte antibodies or a blood culture; no local sampling of the nail is required at any stage",
      "Neither test appears in the deck."],
     ["A Wood lamp examination followed by biopsy of the nail matrix; sample only after six weeks of topical therapy has failed",
      "That is not the described diagnostic pathway."]],
   c=0, cite=c(51)),

 dict(topic="Onychomycosis", io=IOB, lead="treatment",
   q="A patient has confirmed dermatophyte onychomycosis of the toenails. Which is the first-line treatment, and for how long?",
   opts=[
     ["Oral terbinafine, usually for 12 weeks",
      "Correct — fingernails are usually 6 weeks, toenails 12."],
     ["Oral terbinafine, usually for 6 weeks",
      "Six weeks is the usual fingernail course."],
     ["Topical ciclopirox, usually for 12 weeks",
      "Topicals are for limited disease and have lower cure rates."],
     ["Oral fluconazole, usually for 12 weeks",
      "Fluconazole is off label for this in the United States."]],
   c=0, cite=c(52)),

 dict(topic="Onychomycosis", io=IOB, lead="treatment",
   q="A patient cannot take terbinafine for confirmed onychomycosis. Which alternative does the lecture name, and what does it say about fluconazole?",
   opts=[
     ["Itraconazole is an alternative; fluconazole is off label in the United States",
      "Correct — both points come from the same slide."],
     ["Fluconazole is the alternative; itraconazole is off label in the United States",
      "The deck assigns these the other way round."],
     ["Griseofulvin is the alternative; fluconazole is first-line in the United States",
      "Griseofulvin is the tinea capitis agent for Microsporum."],
     ["Nystatin is the alternative; fluconazole is contraindicated in nail disease",
      "Nystatin treats Candida only."]],
   c=0, cite=c(52)),

 dict(topic="Onychomycosis", io=IOB, lead="education",
   q="Six weeks into oral therapy for toenail onychomycosis, a patient is discouraged that the nail still looks abnormal. Which is the most appropriate response?",
   opts=[
     ["Improvement requires nail growth, so the appearance lags behind the treatment",
      "Correct — and any coexisting tinea pedis must also be managed."],
     ["The therapy has failed, so it should be stopped and a topical agent substituted",
      "A slow visible change is expected, not a treatment failure."],
     ["The nail should look normal by now, so the original diagnosis was probably wrong",
      "Nail appearance is expected to lag."],
     ["Improvement requires nail growth, so the course should be extended to two years",
      "The explanation is right but the extension is invented."]],
   c=0, cite=c(52)),

 dict(topic="Onychomycosis", io=IOB, lead="treatment",
   q="A patient has limited onychomycosis affecting one nail and wishes to avoid oral therapy. Which options does the lecture give, and with what caveat?",
   opts=[
     ["Topical efinaconazole, tavaborole, or ciclopirox, with lower cure rates",
      "Correct — an honest trade-off to explain to the patient."],
     ["Topical nystatin, terbinafine cream, or selenium sulfide, with equal cure rates",
      "Those are not the topical nail agents named."],
     ["Topical efinaconazole, tavaborole, or ciclopirox, with higher cure rates than oral therapy",
      "The cure rates are lower, not higher."],
     ["No topical option exists, so oral therapy is the only route for any nail disease",
      "Limited disease may be treated topically."]],
   c=0, cite=c(52)),

 dict(topic="Id reaction", io=IOB, lead="diagnosis",
   q="A 26-year-old develops an intensely itchy papulovesicular eruption on the fingers about ten days after being treated for a foot infection. Careful examination shows an asymptomatic fissure and maceration in the toe webs. Which is the most likely diagnosis?",
   opts=[
     ["A dermatophytid (id) reaction",
      "Correct — a distant inflammatory dermatitis, one to two weeks after the primary infection."],
     ["Tinea manuum",
      "That produces a thickened dry scaly palm, not an acute vesicular eruption."],
     ["Vesiculobullous tinea pedis",
      "That is on the foot itself, not at a distant site."],
     ["Herpetic whitlow",
      "Whitlow is a painful infection of one distal finger, not a widespread eruption."]],
   c=0, cite=c(60)),

 dict(topic="Id reaction", io=IOA, lead="test",
   q="A patient has an itchy vesicular eruption on the hands and scaling between the toes. Potassium hydroxide microscopy is performed at both sites. Which pattern of results would support an id reaction?",
   opts=[
     ["Positive at the feet and negative at the hands",
      "Correct — fungal elements are absent from the id reaction site."],
     ["Positive at both the feet and the hands",
      "A positive hand result would indicate infection there, not an id reaction."],
     ["Negative at both the feet and the hands",
      "An id reaction requires a proven dermatophyte infection elsewhere."],
     ["Negative at the feet and positive at the hands",
      "That reverses the expected pattern entirely."]],
   c=0, cite=c(62)),

 dict(topic="Id reaction", io=IOB, lead="diagnosis",
   q="A 26-year-old has an itchy hand eruption and you suspect an id reaction. Which three criteria does the lecture give for establishing it?",
   opts=[
     ["A dermatophyte infection elsewhere, absence of fungal elements at the reaction site, and resolution when the primary infection is treated",
      "Correct — all three must be satisfied."],
     ["A dermatophyte infection elsewhere, presence of fungal elements at the reaction site, and resolution when a corticosteroid is applied",
      "Fungal elements must be ABSENT at the reaction site."],
     ["A bacterial infection elsewhere, absence of fungal elements at the reaction site, and resolution when an antibiotic is given",
      "The primary infection is a dermatophyte one."],
     ["A positive Wood lamp at the reaction site, a negative culture elsewhere, and resolution within 24 hours of treatment",
      "None of these are the criteria given."]],
   c=0, cite=c(62)),

 dict(topic="Id reaction", io=IOB, lead="treatment",
   q="A patient has a confirmed id reaction on the hands secondary to tinea pedis. Which is the most appropriate management?",
   opts=[
     ["Treat the primary dermatophyte infection, since the id reaction resolves when it is treated",
      "Correct — the distant eruption follows the primary site."],
     ["Treat the hand eruption with a topical antifungal, since fungus is present at both sites",
      "The id reaction site has no fungal elements."],
     ["Treat the hand eruption with an oral antibiotic, since the reaction is bacterial in origin",
      "The reaction is a hypersensitivity phenomenon, not bacterial."],
     ["Observe both sites without treatment, since the reaction and the primary infection both self-resolve",
      "The primary infection needs treating for the reaction to clear."]],
   c=0, cite=c(62)),

 dict(topic="Id reaction", io=IOB, lead="diagnosis",
   q="A patient with a confirmed id reaction asks what is causing the eruption on his hands. What is the proposed mechanism, and which primary infection is commonly responsible?",
   opts=[
     ["The mechanism is unknown, possibly a delayed-type hypersensitivity; tinea pedis is the common primary infection",
      "Correct — the deck is explicit that the mechanism is unknown."],
     ["The mechanism is direct fungal spread through the bloodstream; tinea capitis is the common primary infection",
      "Fungal elements are absent from the reaction site."],
     ["The mechanism is an immediate immunoglobulin E reaction; tinea cruris is the common primary infection",
      "The deck suggests a delayed-type mechanism, not immediate."],
     ["The mechanism is toxin-mediated; onychomycosis is the common primary infection",
      "No toxin mechanism is described."]],
   c=0, cite=c(59)),

 dict(topic="Tinea incognito", io=IOB, lead="diagnosis",
   q="A patient has an unusual, poorly defined, extensive eruption on the trunk. She has been applying a topical corticosteroid for months; it settles while she uses it and flares when she stops, prompting more steroid. Which is the most likely diagnosis?",
   opts=[
     ["Tinea incognito",
      "Correct — tinea whose appearance is altered by inappropriate steroid treatment."],
     ["Nummular eczema",
      "That is commonly confused with tinea corporis but is not steroid-altered tinea."],
     ["Psoriasis",
      "Psoriasis is in the tinea corporis differential but does not follow this steroid cycle."],
     ["An id reaction",
      "That is a distant eruption with no fungal elements at the site."]],
   c=0, cite=c(64)),

 dict(topic="Tinea incognito", io=IOB, lead="next step",
   q="A patient is diagnosed with tinea incognito. Which is the most appropriate next step, and what should you warn her about?",
   opts=[
     ["Stop the corticosteroid or calcineurin inhibitor and obtain testing from an active edge; warn that inflammation may rebound after withdrawal",
      "Correct — the rebound is expected and should be anticipated."],
     ["Continue the corticosteroid while adding an antifungal; warn that the eruption may worsen if the steroid is stopped abruptly",
      "The inappropriate agent must be stopped, not continued."],
     ["Stop the corticosteroid and obtain testing from the cleared centre; warn that the eruption should settle immediately",
      "Sample the active edge, and expect a rebound rather than immediate settling."],
     ["Increase the corticosteroid potency and re-test in six weeks; warn that testing is unreliable during treatment",
      "Escalating the steroid is the opposite of what is needed."]],
   c=0, cite=c(65)),

 dict(topic="Tinea incognito", io=IOB, lead="treatment",
   q="A patient with tinea incognito has extensive, follicular disease. Which is the most appropriate treatment?",
   opts=[
     ["Systemic antifungal therapy",
      "Correct — extensive, follicular or refractory infection warrants systemic therapy."],
     ["Topical antifungal therapy alone",
      "That is for localized disease."],
     ["A more potent topical corticosteroid",
      "Steroids created the problem."],
     ["Oral antibiotic therapy",
      "The infection is fungal, not bacterial."]],
   c=0, cite=c(65)),

 dict(topic="Cutaneous candidiasis", io=IOB, lead="diagnosis",
   q="A 58-year-old woman with obesity and diabetes has a sore, burning rash under both breasts. There are well-demarcated erythematous patches with small papules and pustules scattered just beyond the edge. Which is the most likely diagnosis, and which finding supports it?",
   opts=[
     ["Cutaneous candidiasis, supported by the satellite papules and pustules",
      "Correct — satellite lesions support Candida."],
     ["Tinea corporis, supported by the well-demarcated border of the patches",
      "Tinea corporis clears centrally and does not throw satellite pustules."],
     ["Pityriasis versicolor, supported by the involvement of the trunk",
      "Versicolor gives finely scaling macules, not eroded fold disease."],
     ["Erythrasma, supported by the involvement of a body fold",
      "Erythrasma may fluoresce coral-red and lacks satellite lesions."]],
   c=0, cite=c(68)),

 dict(topic="Cutaneous candidiasis", io=IOB, lead="diagnosis",
   q="A 61-year-old woman with obesity has a sore rash under both breasts and asks what intertrigo means and whether she has a yeast infection. What is intertrigo, and how does Candida relate to it?",
   opts=[
     ["An inflammatory rash caused by friction, moisture and heat trapped in body folds, which Candida may secondarily infect",
      "Correct — Candida is a secondary invader of an existing intertrigo."],
     ["A primary Candida infection of the body folds, which trapped friction, moisture and heat then worsen over time",
      "The deck describes Candida as the secondary infection, not the primary event."],
     ["A dermatophyte infection of the body folds, which yeast may secondarily infect once treated",
      "Intertrigo is not a dermatophyte infection."],
     ["A hypersensitivity reaction to a distant fungal infection, which appears in the body folds",
      "That describes an id reaction."]],
   c=0, cite=c(68)),

 dict(topic="Cutaneous candidiasis", io=IOB, lead="diagnosis",
   q="A 70-year-old with obesity, diabetes and incontinence is examined for candidal skin disease. Which sites does the lecture list as the common ones to inspect?",
   opts=[
     ["Inframammary, axillary, abdominal, inguinal, and interdigital folds",
      "Correct — the perineal folds are on the list too, making six named sites."],
     ["The scalp, the beard area, the eyebrows, and the nasolabial folds",
      "Those are seborrheic dermatitis sites."],
     ["The trunk, the neck, and the proximal arms",
      "Those favour pityriasis versicolor."],
     ["The palms, the soles, and the periungual skin",
      "Those are tinea manuum, pedis and onychomycosis sites."]],
   c=0, cite=c(68)),

 dict(topic="Cutaneous candidiasis", io=IOB, lead="next step",
   q="A patient's intertriginous rash has become malodorous with erosions and drainage. Which does this raise concern for?",
   opts=[
     ["Bacterial coinfection",
      "Correct — malodor, erosion or drainage point beyond Candida."],
     ["An id reaction at a distant site",
      "Those features are local, not distant."],
     ["Tinea incognito from prior steroid use",
      "That would need a history of inappropriate steroid treatment."],
     ["Malignant transformation of the plaque",
      "Not a concern raised in this deck."]],
   c=0, cite=c(68)),

 dict(topic="Cutaneous candidiasis", io=IOB, lead="treatment",
   q="A patient with candidal intertrigo is prescribed a topical antifungal. What distinguishes nystatin from a topical azole here?",
   opts=[
     ["Nystatin treats Candida only, whereas topical azoles treat Candida and many dermatophytes",
      "Correct — that difference in spectrum drives the choice."],
     ["Nystatin treats Candida and many dermatophytes, whereas topical azoles treat Candida only",
      "The spectra are the other way round."],
     ["Nystatin treats dermatophytes only, whereas topical azoles treat Candida only",
      "Nystatin has no dermatophyte activity."],
     ["The two have identical spectra, and the choice between them is purely a matter of cost",
      "The deck draws a clear spectrum distinction."]],
   c=0, cite=c(72)),

 dict(topic="Cutaneous candidiasis", io=IOB, lead="treatment",
   q="A 58-year-old woman with candidal intertrigo is prescribed a topical azole. Beyond the antifungal, which environmental measures does the lecture require?",
   opts=[
     ["Gently dry the folds, reduce friction and occlusion, use moisture-wicking fabric or absorbent material, and address incontinence or hyperhidrosis",
      "Correct — correcting the environment is listed first."],
     ["Apply an occlusive dressing to the folds, avoid all washing and drying of the area, use a non-absorbent fabric, and treat incontinence only once the rash has settled",
      "Occlusion is precisely what has to be reduced."],
     ["Soak the folds in warm water twice daily, apply talcum powder, and cover the area with a waterproof film",
      "None of these appear in the deck."],
     ["Expose the folds to direct sunlight daily, avoid moisture-wicking fabric, and treat incontinence only if it is severe",
      "The deck asks for the opposite on each point."]],
   c=0, cite=c(72)),

 dict(topic="Cutaneous candidiasis", io=IOB, lead="treatment",
   q="A patient with candidal intertrigo has marked inflammation. What does the lecture say about adding a corticosteroid?",
   opts=[
     ["Consider a low-potency corticosteroid only briefly, and only alongside adequate antifungal treatment",
      "Correct — brief, low-potency, and never alone."],
     ["Use a high-potency corticosteroid for several weeks, alongside adequate antifungal treatment",
      "The deck specifies low potency and a brief course."],
     ["Use a low-potency corticosteroid as the sole treatment until the inflammation settles",
      "It must accompany adequate antifungal treatment."],
     ["Never use a corticosteroid in any circumstance, because it will always cause tinea incognito",
      "A brief low-potency steroid is permitted alongside antifungal therapy."]],
   c=0, cite=c(72)),

 dict(topic="Cutaneous candidiasis", io=IOB, lead="next step",
   q="A patient has recurrent, extensive candidal intertrigo. Which is the most appropriate next step?",
   opts=[
     ["Evaluate for diabetes and immunosuppression",
      "Correct — recurrent or extensive disease prompts this."],
     ["Repeat the same topical course for a further six months",
      "Recurrence is a reason to look for an underlying cause."],
     ["Switch to a systemic corticosteroid to control the inflammation",
      "A systemic steroid would worsen a fungal infection."],
     ["Refer for surgical excision of the affected skin folds",
      "Not a management step described in the deck."]],
   c=0, cite=c(72)),

 dict(topic="Pityriasis versicolor", io=IOB, lead="diagnosis",
   q="A 19-year-old lifeguard has multiple velvety tan and white finely scaling macules across his upper trunk and neck. They are asymptomatic. Which organism is responsible, and is he contagious?",
   opts=[
     ["Overgrowth of lipid-dependent Malassezia species that normally inhabit the skin; it is not considered contagious",
      "Correct — a normal resident overgrowing, so it does not spread person to person."],
     ["Infection with Trichophyton rubrum acquired from another person; it is considered contagious",
      "That is the common dermatophyte, not the versicolor organism."],
     ["Infection with Candida albicans acquired from the patient's own gut flora; it is not considered contagious",
      "Candida causes intertrigo, not versicolor."],
     ["Overgrowth of lipid-dependent Malassezia species acquired from communal showers; it is considered contagious",
      "The organism is right but it is not contagious."]],
   c=0, cite=c(74)),

 dict(topic="Pityriasis versicolor", io=IOB, lead="diagnosis",
   q="A 21-year-old asks why his pityriasis versicolor keeps returning each summer. Which factors does the lecture say make it more common?",
   opts=[
     ["Heat, humidity, oily skin, sweating, immunosuppression, or corticosteroid exposure",
      "Correct — six named factors."],
     ["Cold, dry air, low sebum production, and frequent bathing with antibacterial soap",
      "These oppose the named factors."],
     ["Obesity, incontinence, immobility, and recent antibiotic use in hospital",
      "Those are intertrigo risk factors."],
     ["Occlusive footwear, nail trauma, and peripheral vascular disease",
      "Those are onychomycosis risk factors."]],
   c=0, cite=c(74)),

 dict(topic="Pityriasis versicolor", io=IOA, lead="test",
   q="A 23-year-old has finely scaling tan macules on the trunk, and you perform potassium hydroxide microscopy on a scale from one lesion. Which finding would you expect?",
   opts=[
     ["Short hyphae with clusters of yeast, described as \"spaghetti and meatballs\"",
      "Correct — that is the classic appearance."],
     ["Long branching septate hyphae without any yeast forms present",
      "That is the dermatophyte pattern, not this one."],
     ["Budding yeast and pseudohyphae without any short hyphal fragments",
      "That pattern suggests Candida."],
     ["Multinucleated giant cells with intranuclear inclusions",
      "That is a Tzanck finding in herpesvirus infection."]],
   c=0, cite=c(80)),

 dict(topic="Pityriasis versicolor", io=IOB, lead="test",
   q="A Wood lamp examination is performed on a 20-year-old with suspected pityriasis versicolor and shows no fluorescence. Which is the most appropriate interpretation?",
   opts=[
     ["It does not exclude the diagnosis, because the lamp's sensitivity is limited",
      "Correct — a yellow-gold fluorescence may be seen but is not reliable."],
     ["It excludes the diagnosis, because all versicolor lesions fluoresce yellow-gold",
      "Sensitivity is explicitly described as limited."],
     ["It excludes the diagnosis, because a coral-red fluorescence is expected instead",
      "Coral-red fluorescence belongs to erythrasma."],
     ["It confirms the diagnosis, because absence of fluorescence is the characteristic finding",
      "Absence of fluorescence confirms nothing here."]],
   c=0, cite=c(80)),

 dict(topic="Pityriasis versicolor", io=IOB, lead="diagnosis",
   q="A patient has completely white, sharply defined patches with no scale at all. Which diagnosis in the differential does this suggest?",
   opts=[
     ["Vitiligo, which is completely depigmented and autoimmune",
      "Correct — depigmentation without scale points away from versicolor."],
     ["Seborrheic dermatitis, whose patches have an erythematous yellowish tint with soft greasy scales",
      "That is scaly and erythematous, not depigmented."],
     ["Pityriasis rosea, in which a herald patch precedes patches in a Christmas tree distribution",
      "That has a distinctive sequence and distribution."],
     ["Pityriasis versicolor, whose hypopigmented lesions are completely depigmented and scale-free",
      "Versicolor lesions are hypopigmented with fine scale, not depigmented."]],
   c=0, cite=c(79)),

 dict(topic="Pityriasis versicolor", io=IOB, lead="education",
   q="Four weeks after completing treatment for pityriasis versicolor, a patient's pale patches have not repigmented. She asks whether the treatment failed. Which is the most appropriate response?",
   opts=[
     ["Colour change alone does not prove treatment failure; hypopigmentation reflects altered melanocyte function and recovery can lag months behind clearance of the yeast",
      "Correct — look for scale, or confirm with microscopy."],
     ["Colour change alone proves treatment failure; melanocyte function recovers immediately, so the patches should have repigmented within two weeks of clearance",
      "Pigment recovery is expected to lag."],
     ["Colour change alone does not prove treatment failure; the pale patches are permanent and will never repigment",
      "Recovery lags but does occur."],
     ["Colour change alone proves treatment failure; a further systemic course should be started immediately",
      "Escalating on colour alone is exactly what the deck warns against."]],
   c=0, cite=c(77)),

 dict(topic="Pityriasis versicolor", io=IOB, lead="treatment",
   q="A patient has pityriasis versicolor over the upper trunk. Which is the most appropriate first-line treatment?",
   opts=[
     ["Topical therapy, such as ketoconazole shampoo or cream, selenium sulfide, zinc pyrithione, ciclopirox, or topical terbinafine",
      "Correct — topical therapy is first-line."],
     ["Oral therapy, such as fluconazole or itraconazole, given to every patient at presentation whatever the extent of disease",
      "Systemic therapy is reserved for extensive, recurrent or refractory disease."],
     ["Oral terbinafine, given for six weeks because it concentrates well in sweat",
      "Oral terbinafine is ineffective here for exactly the opposite reason."],
     ["Topical nystatin, applied twice daily until the scale has fully resolved",
      "Nystatin treats Candida only."]],
   c=0, cite=c(81)),

 dict(topic="Pityriasis versicolor", io=IOB, lead="treatment",
   q="A 22-year-old with pityriasis versicolor is prescribed selenium sulfide and asks exactly how to use it. Which regimen does the lecture describe?",
   opts=[
     ["Daily application for 7 days, with a 10-minute contact time before rinsing",
      "Correct — the contact time matters as much as the frequency."],
     ["Daily application for 7 days, rinsed off immediately after application",
      "A 10-minute contact time is specified."],
     ["Weekly application for 7 weeks, with a 10-minute contact time before rinsing",
      "The regimen given is daily for seven days."],
     ["Twice-daily application for 6 weeks, rinsed off after one minute",
      "Neither the frequency nor the contact time matches."]],
   c=0, cite=c(81)),

 dict(topic="Pityriasis versicolor", io=IOB, lead="treatment",
   q="A patient with extensive, recurrent pityriasis versicolor has failed topical therapy. Why is oral terbinafine NOT an appropriate choice?",
   opts=[
     ["Because adequate drug levels are not achieved in sweat, although topical terbinafine can be effective",
      "Correct — the route matters for this organism."],
     ["Because it is ineffective against Malassezia by any route, including topically",
      "Topical terbinafine can be effective."],
     ["Because it carries an unacceptable risk of hepatic and adrenal toxicity in superficial infection",
      "That warning attaches to oral ketoconazole."],
     ["Because it is off label in the United States for any superficial fungal infection",
      "That statement is made about fluconazole in nail disease."]],
   c=0, cite=c(82)),

 dict(topic="Pityriasis versicolor", io=IOB, lead="treatment",
   q="A 30-year-old with extensive pityriasis versicolor asks about an oral tablet a friend was given. Which oral agent does the lecture say must NOT be used here, and why?",
   opts=[
     ["Oral ketoconazole, because serious hepatic and adrenal toxicity outweighs the benefit in a superficial infection",
      "Correct — the risk-benefit balance fails for superficial disease."],
     ["Oral fluconazole, because serious hepatic and adrenal toxicity outweighs the benefit in superficial infection",
      "Fluconazole is one of the permitted systemic options."],
     ["Oral itraconazole, because it achieves inadequate levels in sweat to clear the organism",
      "That objection belongs to oral terbinafine."],
     ["Oral griseofulvin, because it has no activity against Malassezia species at any dose",
      "Griseofulvin is not the agent singled out with this warning."]],
   c=0, cite=c(82)),

 dict(topic="Pityriasis versicolor", io=IOB, lead="education",
   q="A patient in a warm climate has had pityriasis versicolor three summers in a row. Which measure does the lecture suggest?",
   opts=[
     ["Intermittent prophylactic topical therapy",
      "Correct — recurrence is common, especially in warm climates."],
     ["Continuous oral antifungal therapy year-round",
      "Systemic therapy is reserved, not used prophylactically."],
     ["Avoiding all sun exposure during the summer months",
      "Not a measure named in the deck."],
     ["A single course of oral ketoconazole each spring",
      "Oral ketoconazole is explicitly to be avoided here."]],
   c=0, cite=c(81)),
]
