# -*- coding: utf-8 -*-
# CMS I Lecture 9 — pool E. Kaposi sarcoma, cutaneous T-cell lymphoma, nail unit neoplasms.
# THE SLIDE IS AUTHORITATIVE (Jaquith deck). Correct answer first (c=0).
SRC = "Premalignant and Malignant Cutaneous Lesions - Jaquith.pptx"
def c(n): return f"{SRC}, Slide {n}"
IOA = "1 — Compare and contrast the etiologies, epidemiology, risk factors, clinical manifestations, differential diagnosis, diagnostic testing (including ordering and interpretation), management (acute and chronic, including applicable rehabilitative and palliative care), appropriate referrals, patient education, and prognosis of pre-malignant and malignant cutaneous lesions"
IOB = "11 — Identify medical care strategies for pre-malignant and malignant cutaneous lesions for adult and elderly populations"

POOL_E = [
 dict(topic="Kaposi sarcoma", io=IOA, slot="etiology",
   q="What causes Kaposi sarcoma, and which cells does it arise from?",
   opts=[
     ["Human herpesvirus 8 combined with a weakened immune system, arising in the cells lining blood and lymph vessels",
      "Correct — the virus alone is not sufficient."],
     ["Human papillomavirus combined with a weakened immune system, arising in the keratinocytes of the epidermis",
      "That virus and cell type belong to warts and squamous disease."],
     ["Ultraviolet damage combined with fair skin, arising in the basal cells of the epidermis",
      "That describes basal cell carcinoma."],
     ["Malignant T cells migrating into the skin over years, arising in the lymphoid tissue",
      "That describes cutaneous T-cell lymphoma."]],
   c=0, cite=c(57)),

 dict(topic="Kaposi sarcoma", io=IOA, slot="epidemiology",
   q="Which clinical forms of Kaposi sarcoma does the deck describe?",
   opts=[
     ["Classic in older men with a chronic course; endemic, often aggressive in young Black men in equatorial Africa; iatrogenic with immunosuppressive therapy; and epidemic in acquired immunodeficiency",
      "Correct — four forms, each with a different population and course."],
     ["Superficial, nodular, pigmented and morpheaform disease, each occurring in a different population and each with a different histologic behaviour and course",
      "Those are basal cell carcinoma subtypes."],
     ["Superficial spreading, lentigo maligna, nodular and acral lentiginous disease, each occurring in a different population and each with a different growth pattern and course",
      "Those are melanoma subtypes."],
     ["Patch, plaque, tumour and erythrodermic disease, each occurring in a different population and each representing a successive stage of the same underlying process",
      "That is closer to the cutaneous T-cell lymphoma progression."]],
   c=0, cite=c(63)),

 dict(topic="Kaposi sarcoma", io=IOA, slot="manifestation",
   q="What does Kaposi sarcoma look like, and which examination does the deck call essential when it is suspected?",
   opts=[
     ["Red or purple macules, plaques or nodules on skin or mucous membranes; ORAL examination is essential, since hard palate lesions are common and may be the presenting site",
      "Correct — the mouth may be where it declares itself."],
     ["Red or purple macules, plaques or nodules on skin only; NAIL examination is essential, since subungual lesions are common and may be the presenting site",
      "The deck emphasises the oral cavity, not the nails."],
     ["Pearly translucent papules with telangiectasias; ocular examination is essential, since eyelid lesions are the usual presenting site",
      "Those are basal cell carcinoma features."],
     ["Erythematous scaly patches and plaques on the trunk; scalp examination is essential, since follicular involvement is the presenting sign",
      "Those are cutaneous T-cell lymphoma features."]],
   c=0, cite=c(64)),

 dict(topic="Kaposi sarcoma", io=IOA, slot="test finding",
   q="What warning does the deck give about oedema in Kaposi sarcoma?",
   opts=[
     ["Marked oedema may occur even with few or no visible skin lesions, so oedema severity must not be used to gauge disease burden",
      "Correct — the skin can look almost clear while disease is extensive."],
     ["Marked oedema occurs only in advanced disease with many visible lesions, so its severity reliably indicates the cutaneous disease burden",
      "The deck says the opposite."],
     ["Marked oedema is never a feature of Kaposi sarcoma at any stage, and its presence should prompt a search for venous thrombosis instead",
      "Marked oedema is an explicit feature."],
     ["Marked oedema occurs only in the classic form of the disease, and its severity can therefore be used to distinguish classic from epidemic Kaposi sarcoma",
      "No such form-specific rule is given."]],
   c=0, cite=c(64)),

 dict(topic="Kaposi sarcoma", io=IOA, slot="first-line",
   q="What is the first priority in acquired immunodeficiency syndrome-associated Kaposi sarcoma?",
   opts=[
     ["Begin or optimise antiretroviral therapy — immune restoration is the cornerstone of treatment for epidemic disease",
      "Correct — antiretroviral therapy comes before local measures."],
     ["Begin liposomal doxorubicin and paclitaxel — systemic chemotherapy is the cornerstone of treatment for epidemic disease",
      "Systemic chemotherapy is added for advanced disease, after antiretroviral therapy."],
     ["Begin intralesional vinblastine and radiation — local palliation is the cornerstone of treatment for epidemic disease",
      "That is the classic, older-adult approach."],
     ["Reduce immunosuppressive medication doses — dose reduction is the cornerstone of treatment for epidemic disease",
      "That is the iatrogenic-form approach."]],
   c=0, cite=c(66)),

 dict(topic="Kaposi sarcoma", io=IOB, slot="escalation",
   q="Which systemic agents are first-line in Kaposi sarcoma, and what does the deck say about combining them with antiretroviral therapy?",
   opts=[
     ["Liposomal doxorubicin and paclitaxel; antiretroviral therapy plus chemotherapy is more effective than antiretroviral therapy alone in advanced disease",
      "Correct — combination beats antiretroviral therapy alone once disease is advanced."],
     ["Liposomal doxorubicin and paclitaxel; antiretroviral therapy alone is more effective than the combination in advanced disease",
      "The deck says the combination is more effective."],
     ["Vismodegib and sonidegib; antiretroviral therapy plus a hedgehog inhibitor is more effective than antiretroviral therapy alone",
      "Hedgehog inhibitors belong to basal cell carcinoma."],
     ["Romidepsin and vorinostat; antiretroviral therapy plus a histone deacetylase inhibitor is more effective than antiretroviral therapy alone",
      "Those agents belong to cutaneous T-cell lymphoma."]],
   c=0, cite=c(66)),

 dict(topic="Cutaneous T-cell lymphoma", io=IOA, slot="etiology",
   q="What is mycosis fungoides, and how does it behave over time?",
   opts=[
     ["A cutaneous T-cell lymphoma that begins in skin and may remain confined there for years or decades, with malignant T cells forming skin infiltrates before any potential systemic spread",
      "Correct — skin-limited for a long time in many patients."],
     ["A cutaneous B-cell lymphoma that begins in the bone marrow and seeds the skin within weeks, with malignant B cells forming infiltrates only after systemic spread",
      "It is a T-cell lymphoma that begins in the skin."],
     ["A vascular tumour caused by human herpesvirus 8 that begins in the skin and spreads to the viscera within months of the first cutaneous lesion appearing",
      "That describes Kaposi sarcoma."],
     ["A keratinocyte carcinoma that begins as an actinic keratosis in sun-damaged skin and becomes invasive over years before any potential nodal spread",
      "That describes squamous cell carcinoma."]],
   c=0, cite=c(69)),

 dict(topic="Cutaneous T-cell lymphoma", io=IOA, slot="manifestation",
   q="What is the early morphology of cutaneous T-cell lymphoma, and what is it commonly mistaken for?",
   opts=[
     ["Localised or generalised erythematous patches or scaly plaques, usually on the trunk and frequently larger than 5 cm; it may resemble psoriasis, eczema or tinea",
      "Correct — which is why diagnosis is often delayed."],
     ["Localised pearly papules with telangiectasias, usually on the face and frequently smaller than 5 mm; it may resemble sebaceous hyperplasia",
      "Those are basal cell carcinoma features."],
     ["Red or purple macules and nodules, usually on the lower limbs and oral mucosa; it may resemble bacillary angiomatosis",
      "Those are Kaposi sarcoma features."],
     ["Rough sandpaper papules on sun-exposed skin, usually under 6 mm; it may resemble seborrheic keratosis",
      "Those are actinic keratosis features."]],
   c=0, cite=c(70)),

 dict(topic="Cutaneous T-cell lymphoma", io=IOA, slot="test finding",
   q="Which two clinical clues does the deck give for suspecting cutaneous T-cell lymphoma in a chronic eruption?",
   opts=[
     ["Itch out of proportion to the apparent inflammatory activity, and follicular involvement with hair loss",
      "Correct — folliculotropism discriminates from routine eczema or psoriasis."],
     ["Itch that is entirely absent even in extensive disease, and complete sparing of the hair follicles",
      "Pruritus is common and may be severe, and follicular involvement is a clue."],
     ["Sharp demarcation with thick silvery scale, and rapid complete response to a topical corticosteroid",
      "Rapid response argues against it; treatment resistance is a discriminator."],
     ["Annular plaques with progressive central clearing, and a positive potassium hydroxide preparation from the border",
      "That describes tinea, one of the mimics."]],
   c=0, cite=c(70)),

 dict(topic="Cutaneous T-cell lymphoma", io=IOA, slot="first-line",
   q="What treatment philosophy does the deck set out for cutaneous T-cell lymphoma?",
   opts=[
     ["A stage-directed, skin-first approach for most early disease, because early aggressive treatment has not been proven to cure or prevent progression and may cause complications and premature death",
      "Correct — aggression is a harm here, not a virtue."],
     ["Immediate aggressive systemic chemotherapy for all stages regardless of extent, because early aggressive treatment reliably cures the disease and prevents progression to systemic involvement",
      "The deck explicitly rejects this."],
     ["Observation alone at every stage without skin-directed treatment, because no therapy has been shown to alter the course of the disease or to relieve symptoms",
      "Skin-directed therapy is offered for early disease."],
     ["Total-skin electron-beam treatment as the initial therapy for every patient regardless of stage, because skin-directed topical therapy has no demonstrated benefit",
      "That is reserved for progressive disease."]],
   c=0, cite=c(75)),

 dict(topic="Cutaneous T-cell lymphoma", io=IOA, slot="agent/regimen",
   q="Which initial skin-directed therapies does the deck list for cutaneous T-cell lymphoma?",
   opts=[
     ["Topical corticosteroids, topical mechlorethamine, bexarotene gel, and ultraviolet phototherapy",
      "Correct — four skin-directed options."],
     ["Topical corticosteroids, topical fluorouracil, imiquimod, and photodynamic therapy",
      "Those are the actinic keratosis field-directed options."],
     ["Intralesional vincristine, vinblastine, bleomycin, and radiation",
      "Those are palliative options in classic Kaposi sarcoma."],
     ["Liposomal doxorubicin, paclitaxel, romidepsin and vorinostat",
      "Those are systemic agents rather than skin-directed ones."]],
   c=0, cite=c(75)),

 dict(topic="Nail unit neoplasms", io=IOA, slot="etiology",
   q="Where does nail unit melanoma most often arise, which sites are high-yield, and is it ultraviolet-driven?",
   opts=[
     ["Most often in the matrix; the thumb and great toe are high-yield sites; it is NOT clearly ultraviolet-driven and may occur in any skin tone",
      "Correct — delayed recognition contributes to advanced-stage presentation."],
     ["Most often in the nail bed; the index finger and little toe are high-yield sites; it is clearly ultraviolet-driven and occurs mainly in fair skin",
      "The matrix is the usual origin, and it is not clearly ultraviolet-driven."],
     ["Most often in the proximal nail fold; all digits equally; it is clearly ultraviolet-driven and occurs mainly in fair skin",
      "Neither the site nor the ultraviolet claim matches."],
     ["Most often in the hyponychium; the thumb and great toe are high-yield sites; it is driven by high-risk human papillomavirus",
      "Human papillomavirus is associated with nail unit squamous disease, not melanoma."]],
   c=0, cite=c(79)),

 dict(topic="Nail unit neoplasms", io=IOA, slot="epidemiology",
   q="Which is the MOST COMMON malignant nail tumour, and what is it associated with?",
   opts=[
     ["Nail unit squamous cell carcinoma or Bowen disease, associated with high-risk human papillomavirus, immunosuppression, chronic inflammation or trauma, prior radiation, and older age",
      "Correct — periungual disease may be multifocal."],
     ["Nail unit melanoma, associated with high-risk human papillomavirus, immunosuppression, chronic inflammation or trauma, prior radiation, and older age, and often multifocal",
      "Melanoma is not the commonest malignant nail tumour."],
     ["Nail unit basal cell carcinoma, associated with cumulative ultraviolet exposure, fair skin, chronic trauma, prior radiation and older age",
      "The deck calls nail unit basal cell carcinoma exceptionally uncommon."],
     ["Glomus tumour, associated with chronic inflammation or trauma, immunosuppression, prior radiation and older age",
      "The glomus tumour is benign."]],
   c=0, cite=c(79)),

 dict(topic="Nail unit neoplasms", io=IOA, slot="manifestation",
   q="What is the Hutchinson sign in the nail unit, and what should it prompt?",
   opts=[
     ["Periungual pigment extending onto the proximal nail fold — highly concerning for nail unit melanoma, prompting urgent expert evaluation regardless of other features",
      "Correct — it outranks the rest of the picture."],
     ["Pigment confined strictly beneath the nail plate without any periungual extension — reassuring, and allowing routine follow-up whatever the other features",
      "The sign is defined by extension ONTO the nail fold."],
     ["Vesicles on the tip or side of the nose — concerning for ocular involvement in herpes zoster, prompting same-day ophthalmology review",
      "That is the Hutchinson sign of zoster ophthalmicus, a different sign of the same name."],
     ["A small red-blue subungual focus with paroxysmal pain and cold sensitivity — concerning for a glomus tumour, prompting imaging and specialist review",
      "That is the glomus triad."]],
   c=0, cite=c(84)),

 dict(topic="Nail unit neoplasms", io=IOA, slot="differential",
   q="What does the deck say about amelanotic nail melanoma?",
   opts=[
     ["It may appear red, pink, eroded or mass-like without a dark band, and the absence of pigment does NOT exclude melanoma",
      "Correct — a pigment-free nail lesion can still be melanoma, so consider biopsy for any unexplained, progressive single-nail lesion."],
     ["It always shows at least a faint pigmented band somewhere in the nail, so the complete absence of pigment reliably excludes melanoma from the differential",
      "The deck says absence of pigment does not exclude it."],
     ["It occurs only in patients who already have multiple pigmented bands across several nails, so a single unexplained lesion can be observed",
      "Single-nail disease is the concerning pattern."],
     ["It is a benign variant of longitudinal melanonychia requiring no biopsy, provided the nail plate itself remains intact and unsplit",
      "It is melanoma and warrants biopsy."]],
   c=0, cite=c(84)),

 dict(topic="Nail unit neoplasms", io=IOA, slot="manifestation",
   q="What is the classic triad of a glomus tumour?",
   opts=[
     ["A small red-blue subungual focus with severe paroxysmal pain, exquisite point tenderness, and cold sensitivity",
      "Correct — the nail may look nearly normal."],
     ["A verrucous periungual plaque with subungual hyperkeratosis, onycholysis and painless bleeding",
      "That is the squamous cell carcinoma or Bowen pattern."],
     ["A longitudinal pigmented band with proximal widening, blurred borders and nail splitting",
      "That is the melanoma pattern."],
     ["A rapidly growing friable bleeding papule with an epithelial collarette",
      "That describes pyogenic granuloma."]],
   c=0, cite=c(86)),

 dict(topic="Nail unit neoplasms", io=IOB, slot="escalation",
   q="What does the deck say about amputation in nail unit melanoma?",
   opts=[
     ["It is NOT automatic — digit-sparing wide excision or Mohs with immunostaining is contemporary care, with amputation reserved for deep, extensive or bone-involving disease",
      "Correct — the digit is preserved where margins can be reliably assessed."],
     ["It is the automatic first treatment for any nail unit melanoma whatever the depth or extent, since margins cannot be reliably assessed in the nail unit",
      "The deck explicitly says amputation is not automatic."],
     ["It is never indicated at all, since digit-sparing wide excision clears every nail unit melanoma regardless of depth, extent or bone involvement",
      "It is reserved for deep, extensive or bone-involving disease."],
     ["It is reserved for benign nail unit tumours such as glomus tumour or onychomatricoma that recur after local removal",
      "Amputation is not used for benign disease."]],
   c=0, cite=c(94)),

 dict(topic="Nail unit neoplasms", io=IOB, slot="referral",
   q="Which findings does the deck list as urgent referral triggers in the nail unit?",
   opts=[
     ["New or changing single-digit longitudinal melanonychia, proximal widening, Hutchinson sign, or nail dystrophy with pigment",
      "Correct — the list also includes an unexplained subungual mass, persistent ulceration or bleeding, and a chronic wart or infection that fails appropriate therapy. That failed-wart history is the one most easily dismissed."],
     ["Longitudinal pigmented bands present in several nails since childhood, unchanged in width, colour, thickness and spacing over many years, with no nail dystrophy",
      "That pattern is reassuring rather than urgent."],
     ["Any nail change at all in a patient over 65, and any nail that has been abnormal for more than a month, whatever the appearance or the number of digits involved",
      "Age and duration alone are not the triggers."],
     ["Only a subungual mass confirmed on imaging, since clinical features such as pigment, widening, dystrophy or bleeding cannot themselves indicate urgency",
      "The clinical features listed are exactly what drives urgency."]],
   c=0, cite=c(95)),
]
