# CMS I Exam 2, Lecture 11 — OBJECTIVE set pool, part B.
# Completes the pool to a workable size and pulls the patient-stem share up:
# part A came out 0% on the first set, and the standard measures that even here.
SRC = "11. Neuro-Ophthalmology STUDENT VERSION 2026.pptx"
def c(n): return f"{SRC}, Slide {n}"
IO = ("a — Describe the pupillary pathways, cranial nerve palsies and chiasmal lesions, "
      "and identify medical care strategies for neuro-ophthalmological disorders")

POOL_B = [
 dict(topic="Nystagmus", io=IO, lead="recall",
   q="A 6-month-old infant has nystagmus present since birth. Which category is used?",
   opts=[["Congenital", "Correct: infantile or latent, as against acquired."],
         ["Physiologic gaze-evoked", "That is a normal response at extremes of gaze."],
         ["Upbeat", "That is a concerning pattern in adults."],
         ["Torsional", "That is a trajectory, not a category of onset."]],
   c=0, cite=c(3)),
 dict(topic="Nystagmus", io=IO, lead="recall",
   q="A 28-year-old woman has nystagmus that increases when she looks toward the fast phase. Which type is this?",
   opts=[["Jerk nystagmus", "Correct, and it is named for the fast beat's direction."],
         ["Latent nystagmus", "That appears when one eye is covered."],
         ["Spasmus nutans", "That is an infantile syndrome."],
         ["Physiologic nystagmus", "That is a normal endpoint response."]],
   c=0, cite=c(4)),
 dict(topic="Horner syndrome", io=IO, lead="recall",
   q="A 52-year-old man has a first-order Horner syndrome. Which cause fits that level?",
   opts=[["Brainstem stroke", "Correct, along with spinal cord lesions above T1."],
         ["Pancoast tumour", "That is second-order."],
         ["Carotid dissection", "That is third-order."],
         ["Thyroid carcinoma", "That is second-order."]],
   c=0, cite=c(30)),
 dict(topic="Horner syndrome", io=IO, lead="recall",
   q="A 60-year-old woman has ptosis and miosis after COVID-19 requiring intubation. Which association is noted?",
   opts=[["Horner syndrome after mechanical ventilation", "Correct, with possible lung injury proposed."],
         ["Papilledema after ventilation", "That follows raised intracranial pressure."],
         ["Adie pupil after infection", "Adie pupil is attributed to ciliary ganglion inflammation, not this."],
         ["Argyll Robertson pupil after COVID", "That is associated with tertiary syphilis."]],
   c=0, cite=c(15)),
 dict(topic="Third nerve palsy", io=IO, lead="recall",
   q="A 55-year-old man has a third nerve palsy. Which muscles does the inferior division supply?",
   opts=[["Inferior rectus, medial rectus, inferior oblique", "Correct, along with the parasympathetic fibres."],
         ["Levator palpebrae and superior rectus", "Those are the superior division."],
         ["Superior oblique alone", "That is the fourth nerve."],
         ["Orbicularis oculi", "That is the seventh nerve."]],
   c=0, cite=c(39)),
 dict(topic="Third nerve palsy", io=IO, lead="recall",
   q="A 70-year-old man has a third nerve palsy after a fall with loss of consciousness. Which cause is listed?",
   opts=[["Severe head trauma", "Correct, alongside microvascular disease and aneurysm."],
         ["Giant cell arteritis", "Not listed as a cause of this palsy."],
         ["Multiple sclerosis", "Associated with optic neuritis in these lectures."],
         ["Tertiary syphilis", "Associated with Argyll Robertson pupils."]],
   c=0, cite=c(40)),
 dict(topic="Fourth nerve palsy", io=IO, lead="recall",
   q="A 46-year-old man has an acquired fourth nerve palsy. Which causes are named?",
   opts=[["Trauma and microvascular disease", "Correct, with even mild trauma sufficient."],
         ["Aneurysm and herniation", "Those relate to the third nerve."],
         ["Intracranial tumour in children", "That is the sixth nerve in children."],
         ["Giant cell arteritis", "Not named for this palsy."]],
   c=0, cite=c(43)),
 dict(topic="Sixth nerve palsy", io=IO, lead="recall",
   q="A 33-year-old man has a sixth nerve palsy after major trauma. Which injury is associated with it?",
   opts=[["Skull base fracture", "Correct, listed for adults alongside microvascular disease."],
         ["Orbital blowout fracture", "That traps the inferior rectus and restricts upgaze rather than abduction."],
         ["Nasal fracture", "It does not reach the course of the abducens nerve."],
         ["Cervical spine fracture", "The abducens nerve runs along the skull base, well above the cervical spine, and it is a basal skull fracture that damages it."]],
   c=0, cite=c(45)),
 dict(topic="Anisocoria", io=IO, lead="recall",
   q="A 39-year-old woman has physiologic anisocoria. What size difference is given as typical?",
   opts=[["Under about half a millimetre", "Correct, and equal in light and dark."],
         ["Two to three millimetres", "That is larger than physiologic."],
         ["Four millimetres or more", "That suggests a pathological cause."],
         ["Exactly one millimetre in all cases", "The figure is an upper limit rather than a fixed value; physiologic anisocoria varies and may change from day to day."]],
   c=0, cite=c(21)),
 dict(topic="Pupillary pathway", io=IO, lead="recall",
   q="A 44-year-old man has an efferent pupillary problem. Why does that make his pupils unequal?",
   opts=[["The efferent command is normally bilateral and equal", "Correct, so inequality means an efferent pathway has failed."],
         ["Afferent input differs between eyes", "Afferent differences are averaged, keeping size equal."],
         ["The pupils are never truly equal", "They should be equal unless a pathway fails."],
         ["The iris muscles fatigue independently", "Fatigue is not the mechanism."]],
   c=0, cite=c(21)),
 dict(topic="Adie tonic pupil", io=IO, lead="recall",
   q="A 33-year-old woman has an Adie pupil. Which demographic is given?",
   opts=[["Women in their thirties", "Correct, and it is often unilateral."],
         ["Children under five", "Adie pupil follows damage to the ciliary ganglion and typically presents in young adult women, not in young children."],
         ["Men in their twenties", "Both details are wrong: Adie pupil predominates in women, and typically in the third decade rather than the second."],
         ["Postmenopausal women", "The sex fits but the age does not; onset is described in the thirties."]],
   c=0, cite=c(36)),
 dict(topic="Argyll Robertson pupil", io=IO, lead="recall",
   q="A 58-year-old man has Argyll Robertson pupils. Besides syphilis, which causes are listed?",
   opts=[["Diabetes, alcohol, sarcoidosis, multiple sclerosis", "Correct, though syphilis remains the classic association."],
         ["Trauma and aneurysm", "Those relate to cranial nerve palsies."],
         ["Glaucoma and cataract", "Those are ocular rather than neurological."],
         ["Migraine and cluster headache", "Not listed for this sign."]],
   c=0, cite=c(32)),
 dict(topic="Visual fields", io=IO, lead="recall",
   q="A 66-year-old man has a homonymous hemianopsia with macular sparing. Which feature identifies the cortex as the site?",
   opts=[["The macular sparing", "Correct, it is the cortical signature."],
         ["The completeness of the defect", "Completeness does not localise it."],
         ["The unilateral involvement", "Both eyes are involved in a homonymous defect."],
         ["The associated ptosis", "Ptosis is not part of this."]],
   c=0, cite=c(52)),
 dict(topic="Care strategies", io=IO, lead="recall",
   q="A 50-year-old woman presents with a neuro-ophthalmological complaint. Which is placed first?",
   opts=[["A thorough history and physical examination", "Correct, with labs and imaging if indicated."],
         ["Immediate imaging", "Imaging follows the clinical assessment."],
         ["Laboratory testing", "Labs come later and only if indicated."],
         ["Empiric corticosteroids", "Treatment is not started before assessment."]],
   c=0, cite=c(54)),
 dict(topic="Opioid toxicity", io=IO, lead="recall",
   q="A 27-year-old woman has opioid toxicity. Which two features actually matter clinically?",
   opts=[["Reduced consciousness and respiratory depression", "Correct; the miosis is a clue rather than the danger."],
         ["Tachycardia and hypertension", "Those are not features of opioid toxicity here."],
         ["Mydriasis and agitation", "That is an anticholinergic picture."],
         ["Fasciculations and weakness", "Those are nicotinic effects."]],
   c=0, cite=c(12)),
 dict(topic="Accommodation", io=IO, lead="recall",
   q="A 21-year-old man focuses on a near object. Which globe movement occurs?",
   opts=[["Both eyes adduct", "Correct: the convergence reflex."],
         ["Both eyes abduct", "That is divergence, for distance."],
         ["Both eyes elevate", "Elevation is not part of the near response."],
         ["Both eyes depress", "Depression is not part of the near response."]],
   c=0, cite=c(18)),
 dict(topic="Marcus Gunn pupil", io=IO, lead="recall",
   q="A 30-year-old woman has a Marcus Gunn pupil. Is the lesion pre- or post-chiasmal?",
   opts=[["Pre-chiasmal", "Correct: retina or optic nerve."],
         ["Post-chiasmal", "Those produce field defects rather than this sign."],
         ["Always chiasmal", "A chiasmal lesion gives bitemporal loss."],
         ["Cortical", "Cortical lesions spare the pupillary reflex."]],
   c=0, cite=c(26)),
 dict(topic="Ptosis", io=IO, lead="recall",
   q="A 61-year-old man has ptosis. Which muscle provides the main lid elevation?",
   opts=[["Levator palpebrae superioris", "Correct, supplied by the oculomotor nerve."],
         ["Muller's muscle", "That adds only a millimetre or two."],
         ["Orbicularis oculi", "That closes the lid."],
         ["Superior rectus", "That elevates the globe."]],
   c=0, cite=c(48)),
 dict(topic="Horner syndrome", io=IO, lead="recall",
   q="A 48-year-old man is tested with apraclonidine. Which pupil dilates?",
   opts=[["The affected one", "Correct; a normal pupil is unaffected by the dilute drop."],
         ["The normal one", "The drop is ineffective in a normal pupil."],
         ["Neither", "Most affected pupils do dilate."],
         ["It depends on the light level", "Lighting is not the determinant."]],
   c=0, cite=c(28)),
 dict(topic="Cranial nerves", io=IO, lead="recall",
   q="A 37-year-old woman has a peripheral fourth nerve lesion. Which eye is affected relative to the lesion?",
   opts=[["The same side", "Correct: a peripheral lesion after the nerve exits gives an ipsilateral deficit."],
         ["The opposite side", "That applies to a nuclear lesion, since the nerve crosses."],
         ["Neither eye", "A deficit is present."],
         ["It alternates", "Not a described pattern."]],
   c=0, cite=c(42)),
]
