# Clinical Medicine and Surgery I, Lecture 2 (General Dermatology I) — pool B
# SET 1 (instructional-objective style). The eczemas and the dermatitides.
#
# Correct answer is ALWAYS written first (c=0); the partition script rotates.
SRC = "2. General Dermatology I.pptx"
def c(n): return f"{SRC}, Slide {n}"

IOC = "c — Etiologies, manifestations, diagnosis and management of dermatological conditions"

POOL_B = [
 dict(topic="Eczema — general", io=IOC,
   q="What is the relationship between the terms dermatitis and eczema?",
   opts=[
     ["Dermatitis is a broad term for inflammatory skin disorders; eczema describes a pruritic inflammatory reaction pattern, and the two are used interchangeably",
      "Correct. Atopic dermatitis is the commonest eczema, which is why 'eczema' often means it."],
     ["Eczema is the broad category and dermatitis is one subtype of it",
      "The hierarchy runs the other way."],
     ["They describe the same condition at different ages",
      "Neither term is age-defined."],
     ["Dermatitis is infectious and eczema is inflammatory",
      "Dermatitis refers to inflammatory disorders, not infectious ones."]],
   c=0, cite=c(46)),

 dict(topic="Eczema — general", io=IOC,
   q="How does eczema change in appearance from acute to chronic?",
   opts=[
     ["Acute shows erythema, oedema, papules, vesicles, oozing and crusting; chronic shows xerosis, fissuring, lichenification and pigment alteration",
      "Correct, with a subacute stage of scaling, erythema, papules and excoriations between them."],
     ["Acute shows lichenification; chronic shows vesicles and oozing",
      "The stages are reversed."],
     ["The appearance is fixed and does not evolve over time",
      "Eczema changes appearance over time, which is the point being made."],
     ["Acute shows pigment loss; chronic shows vesiculation",
      "Neither is correct for the stage described."]],
   c=0, cite=c(46)),

 dict(topic="Atopic dermatitis", io=IOC,
   q="Which barrier protein is most notably reduced in atopic dermatitis?",
   opts=[
     ["Filaggrin",
      "Correct — reduced filaggrin production is the named epidermal-barrier defect, alongside immune dysregulation."],
     ["Keratin",
      "Keratin is the structural protein of the epidermis but is not the named defect here."],
     ["Collagen",
      "Collagen is a dermal protein and is not implicated in this way."],
     ["Elastin",
      "Elastin provides recoil and is not the barrier protein named."]],
   c=0, cite=c(51)),

 dict(topic="Atopic dermatitis", io=IOC,
   q="What is the atopic triad, and what proportion of patients have at least one of its components?",
   opts=[
     ["Atopic dermatitis, asthma and allergic rhinitis — approximately 80%",
      "Correct."],
     ["Atopic dermatitis, urticaria and food allergy — approximately 50%",
      "Urticaria and food allergy are not the named triad."],
     ["Eczema, psoriasis and seborrhoeic dermatitis — approximately 30%",
      "These are separate conditions rather than a triad."],
     ["Asthma, allergic rhinitis and chronic sinusitis — approximately 60%",
      "Atopic dermatitis is part of the triad by definition."]],
   c=0, cite=c(51)),

 dict(topic="Atopic dermatitis", io=IOC,
   q="How does the distribution of atopic dermatitis change with age?",
   opts=[
     ["Infants: cheeks, scalp and extensor surfaces. Children: antecubital and popliteal fossae, wrists and ankles. Adults: flexures, hands, neck, face and eyelids",
      "Correct — the shift from extensor to flexural is the pattern to hold."],
     ["Infants: flexures. Children: extensor surfaces. Adults: scalp and cheeks",
      "The infantile and childhood patterns are reversed."],
     ["The distribution is the same at every age",
      "Distribution evolves with age, which the lecture stresses."],
     ["Infants: palms and soles. Children: trunk. Adults: lower legs",
      "None of these matches the described pattern."]],
   c=0, cite=c(54)),

 dict(topic="Atopic dermatitis", io=IOC,
   q="What proportion of children worldwide are affected by atopic dermatitis, and in which sex is it more common?",
   opts=[
     ["About 20% of children, more common in males",
      "Correct. It often begins in infancy or childhood; adult-onset disease occurs but is rare."],
     ["About 20% of children, more common in females",
      "It is more common in males."],
     ["About 5% of children, more common in males",
      "The figure given is 20%."],
     ["About 40% of children, with no sex difference",
      "Neither figure nor the absence of a sex difference matches."]],
   c=0, cite=c(52)),

 dict(topic="Atopic dermatitis", io=IOC,
   q="How is atopic dermatitis diagnosed?",
   opts=[
     ["Clinically, supported by family history, personal atopy, recurrent rash and elevated immunoglobulin E, though routine laboratory testing is not required",
      "Correct. Patch testing is reserved for atypical, adult-onset or treatment-resistant disease, and biopsy for atypical or refractory disease."],
     ["By skin biopsy in every case",
      "Biopsy is reserved for atypical or refractory disease."],
     ["By serum immunoglobulin E level, which is routinely measured",
      "Immunoglobulin E supports the diagnosis but is not routinely tested."],
     ["By patch testing in every case",
      "Patch testing is reserved for atypical, adult-onset or treatment-resistant disease."]],
   c=0, cite=c(56)),

 dict(topic="Atopic dermatitis", io=IOC,
   q="Which agents are used for sensitive areas such as the face and eyelids in atopic dermatitis?",
   opts=[
     ["Tacrolimus and pimecrolimus, which are calcineurin inhibitors",
      "Correct — they avoid the atrophy risk of steroids at those sites. Crisaborole, a topical phosphodiesterase-4 inhibitor, is also used."],
     ["High-potency topical corticosteroids",
      "High potency at those sites risks atrophy; low potency or non-steroids are preferred."],
     ["Topical retinoids",
      "Retinoids are used for acne, photoaging and psoriasis rather than atopic dermatitis."],
     ["Topical antifungals",
      "Atopic dermatitis is not a fungal condition."]],
   c=0, cite=c(57)),

 dict(topic="Atopic dermatitis", io=IOC,
   q="When should herpes simplex virus polymerase chain reaction be ordered in atopic dermatitis?",
   opts=[
     ["For painful monomorphic erosions or systemic illness",
      "Correct. Culture is reserved instead for purulent, pustular or significantly crusted lesions."],
     ["For every flare, since secondary infection is common",
      "It is targeted to that specific presentation rather than routine."],
     ["Only when the patient has known herpes simplex",
      "The test is used to establish it, not confirm a known case."],
     ["Only in adult-onset disease",
      "The trigger is the lesion morphology, not the age of onset."]],
   c=0, cite=c(56)),

 dict(topic="Dyshidrotic eczema", io=IOC,
   q="Where does dyshidrotic eczema occur, and what are its vesicles classically called?",
   opts=[
     ["On the palms, lateral and dorsal fingers and soles, with intensely pruritic vesicles described as tapioca vesicles",
      "Correct. Vesicles may coalesce into bullae, then desiccate and resolve with desquamation."],
     ["On the flexural surfaces, with vesicles described as herald patches",
      "The herald patch belongs to pityriasis rosea."],
     ["On the extensor surfaces, with vesicles described as tense bullae",
      "Tense bullae belong to bullous pemphigoid."],
     ["On the scalp, with vesicles described as exclamation point lesions",
      "Exclamation point hairs belong to alopecia areata."]],
   c=0, cite=c(65)),

 dict(topic="Dyshidrotic eczema", io=IOC,
   q="What is first-line treatment for dyshidrotic eczema?",
   opts=[
     ["High-potency topical corticosteroids",
      "Correct, with systemic corticosteroids reserved for severe cases."],
     ["Low-potency topical corticosteroids",
      "High potency is specified as first line for this condition."],
     ["Topical antifungals",
      "The condition is not fungal; its aetiology is unknown."],
     ["Oral antibiotics",
      "Antibiotics are not first-line here."]],
   c=0, cite=c(66)),

 dict(topic="Nummular eczema", io=IOC,
   q="What is the main differential for nummular eczema, and what distinguishes them?",
   opts=[
     ["Tinea corporis — tinea has central clearing and nummular eczema does not",
      "Correct, and this single feature is the discriminator the lecture gives."],
     ["Psoriasis — psoriasis has silvery scale and nummular eczema does not",
      "Psoriasis is a differential for other conditions but is not the one named here."],
     ["Pityriasis rosea — pityriasis has a herald patch",
      "Pityriasis rosea is not the named main differential."],
     ["Contact dermatitis — contact dermatitis is well demarcated",
      "Contact dermatitis is not the named main differential."]],
   c=0, cite=c(73)),

 dict(topic="Nummular eczema", io=IOC,
   q="Who most commonly develops nummular eczema?",
   opts=[
     ["Men, and more often adults over the age of 50, though it can occur at any age",
      "Correct. It is likely caused by some degree of skin barrier dysfunction."],
     ["Women in their twenties and thirties",
      "It is more common in men and in older adults."],
     ["Infants and young children",
      "That pattern fits atopic dermatitis rather than nummular eczema."],
     ["Adolescents following streptococcal infection",
      "That pattern fits guttate psoriasis."]],
   c=0, cite=c(71)),

 dict(topic="Nummular eczema", io=IOC,
   q="How are nummular eczema plaques described?",
   opts=[
     ["Intensely pruritic, round coin-shaped, light pink, scaly, thin plaques 1 to 10 cm, uniform without central clearing",
      "Correct, most commonly on the extremities though they can occur on the trunk."],
     ["Well-demarcated salmon plaques with silvery scale on extensor surfaces",
      "That describes plaque psoriasis."],
     ["Greasy yellow scaling plaques in sebum-rich areas",
      "That describes seborrhoeic dermatitis."],
     ["Violaceous flat-topped polygonal papules with fine white lines",
      "That describes lichen planus."]],
   c=0, cite=c(72)),

 dict(topic="Irritant contact dermatitis", io=IOC,
   q="What causes irritant contact dermatitis, and how common is it relative to the allergic form?",
   opts=[
     ["A response to chemicals or friction that disrupts the skin barrier, and it is the most common form of contact dermatitis",
      "Correct — frequently occupational, as in healthcare and janitorial staff who wash their hands often."],
     ["A delayed type IV hypersensitivity reaction, and it is the less common form",
      "That describes allergic contact dermatitis."],
     ["An immunoglobulin E-mediated immediate reaction, and it is the most common form",
      "Irritant contact dermatitis is not immunologically mediated."],
     ["Overgrowth of Malassezia, and it is the most common form",
      "That is seborrhoeic dermatitis."]],
   c=0, cite=c(80)),

 dict(topic="Irritant contact dermatitis", io=IOC,
   q="How does the timing of irritant contact dermatitis vary with the irritant?",
   opts=[
     ["Mild irritants such as soaps may progress over weeks, while alkalis and acids may present within minutes or be delayed up to 24 hours or more",
      "Correct — the agent determines the tempo."],
     ["All irritants produce symptoms within minutes of exposure",
      "Mild irritants can take weeks."],
     ["All irritants produce symptoms 48 to 72 hours after exposure",
      "That timing belongs to delayed hypersensitivity in the allergic form."],
     ["Timing does not vary with the irritant",
      "The lecture states it varies by exposure."]],
   c=0, cite=c(81)),

 dict(topic="Allergic contact dermatitis", io=IOC,
   q="What type of immune reaction is allergic contact dermatitis?",
   opts=[
     ["An immunologic cell-mediated, delayed, type IV hypersensitivity reaction",
      "Correct — it requires prior sensitisation to the specific allergen."],
     ["An immunoglobulin E-mediated type I hypersensitivity reaction",
      "That is the immediate reaction pattern, not this one."],
     ["An antibody-mediated type II hypersensitivity reaction",
      "That is not the mechanism described."],
     ["An immune complex type III hypersensitivity reaction",
      "That is not the mechanism described."]],
   c=0, cite=c(85)),

 dict(topic="Allergic contact dermatitis", io=IOC,
   q="What is the most common cause of allergic contact dermatitis, and roughly what proportion of people in the United States react to it?",
   opts=[
     ["Urushiol sap from Toxicodendron species — approximately 50 to 75%",
      "Correct, which explains why not everyone who contacts poison ivy, sumac or oak reacts."],
     ["Nickel — approximately 90%",
      "Nickel is the most common metal allergen but not the most common cause overall."],
     ["Neomycin — approximately 30%",
      "Neomycin and bacitracin are common topical antibiotic causes but not the most common overall."],
     ["Perfumes — approximately 60%",
      "Perfumes are a listed cause but not the most common."]],
   c=0, cite=c(85)),

 dict(topic="Allergic contact dermatitis", io=IOC,
   q="How do urushiol lesions present, and over what time course?",
   opts=[
     ["Intensely pruritic vesicular lesions in linear distributions, erupting within 4 to 96 hours and persisting up to 3 weeks",
      "Correct — the linear pattern comes from grazing the plant in passing."],
     ["Well-demarcated plaques shaped like the object contacted, erupting within minutes",
      "That pattern fits metal, adhesive or jewellery allergy rather than urushiol."],
     ["Diffuse urticarial wheals resolving within 24 hours",
      "That describes urticaria."],
     ["Greasy scaling patches in sebum-rich areas over several weeks",
      "That describes seborrhoeic dermatitis."]],
   c=0, cite=c(87)),

 dict(topic="Allergic contact dermatitis", io=IOC,
   q="Is urushiol contact dermatitis contagious?",
   opts=[
     ["No, but it may spread to other areas or people if urushiol is not removed from skin or clothing",
      "Correct — the rash itself does not spread person to person; the resin does."],
     ["Yes, direct contact with the rash transmits it",
      "The rash is not contagious."],
     ["Yes, but only during the vesicular stage",
      "The rash is not contagious at any stage."],
     ["No, and the resin cannot be transferred once it is on clothing",
      "Transfer from clothing and fabrics is exactly how it spreads."]],
   c=0, cite=c(87)),

 dict(topic="Allergic contact dermatitis", io=IOC,
   q="How are severe or extensive allergic contact dermatitis eruptions treated?",
   opts=[
     ["High-dose oral corticosteroids tapered over two to three weeks, because early discontinuation causes high rates of rebound",
      "Correct. Limited eruptions can be managed with high-potency topical steroids."],
     ["High-potency topical steroids alone regardless of extent",
      "Topical therapy suits limited body surface area only."],
     ["A five-day course of oral corticosteroids without taper",
      "Early discontinuation results in high rates of rebounding."],
     ["Oral antihistamines alone",
      "Antihistamines address itch but are not the treatment for severe eruptions."]],
   c=0, cite=c(89)),

 dict(topic="Seborrhoeic dermatitis", io=IOC,
   q="What organism is implicated in seborrhoeic dermatitis, and who is most affected?",
   opts=[
     ["Overgrowth of Malassezia, most common in males aged 20 to 50",
      "Correct — Malassezia is normal skin flora that overgrows in sebum-rich areas."],
     ["Overgrowth of Candida, most common in infants",
      "Candida is the commonest infectious complication of diaper dermatitis instead."],
     ["Infection with Staphylococcus aureus, most common in children",
      "That organism causes bacterial skin infections rather than this."],
     ["Reactivation of varicella zoster virus, most common in the elderly",
      "That is shingles."]],
   c=0, cite=c(93)),

 dict(topic="Seborrhoeic dermatitis", io=IOC,
   q="How do seborrhoeic dermatitis lesions appear, and where?",
   opts=[
     ["Poorly demarcated pruritic erythematous plaques 5 to 20 mm, greasy with flaking or yellow scaling, in areas rich in sebaceous glands",
      "Correct — scalp, eyebrows, under facial hair, nasolabial creases, forehead, nose, behind the ears and the external auditory canal."],
     ["Well-demarcated plaques with silvery scale on extensor surfaces",
      "That describes plaque psoriasis."],
     ["Coin-shaped plaques without central clearing on the extremities",
      "That describes nummular eczema."],
     ["Tense bullae on the trunk and flexures",
      "That describes bullous pemphigoid."]],
   c=0, cite=c(94)),

 dict(topic="Seborrhoeic dermatitis", io=IOC,
   q="What is the mainstay of treatment for seborrhoeic dermatitis?",
   opts=[
     ["Topical antifungals such as ketoconazole, with steroids used early to reduce inflammation",
      "Correct. Scalp disease uses ketoconazole or selenium sulfide shampoo; facial disease uses ketoconazole cream or lotion."],
     ["High-potency topical corticosteroids alone, long term",
      "Steroids are adjunctive and used early; antifungals are the mainstay."],
     ["Oral terbinafine",
      "Topical antifungals are the mainstay for this condition."],
     ["Oral doxycycline",
      "Tetracyclines are used for perioral dermatitis rather than this."]],
   c=0, cite=c(95)),

 dict(topic="Perioral dermatitis", io=IOC,
   q="What is the most important modifiable association of perioral dermatitis?",
   opts=[
     ["Topical corticosteroid exposure",
      "Correct — and treatment begins by stopping it, with a warning that the eruption may temporarily worsen on withdrawal."],
     ["Sun exposure",
      "Photoreactions are covered in General Dermatology II rather than being this association."],
     ["Malassezia overgrowth",
      "That is seborrhoeic dermatitis."],
     ["Nickel exposure",
      "Nickel causes allergic contact dermatitis."]],
   c=0, cite=c(98)),

 dict(topic="Perioral dermatitis", io=IOC,
   q="Which feature is characteristic of perioral dermatitis on examination?",
   opts=[
     ["Grouped monomorphic papules, papulovesicles or papulopustules with sparing of a narrow area next to the vermilion border",
      "Correct — that spared rim is the classic clue."],
     ["Open and closed comedones around the mouth",
      "Comedones point to acne vulgaris instead."],
     ["Central facial erythema with flushing and telangiectasia",
      "That points to rosacea."],
     ["Prominent scale over the scalp, eyebrows and nasolabial folds",
      "That points to seborrhoeic dermatitis."]],
   c=0, cite=c(99)),

 dict(topic="Perioral dermatitis", io=IOC,
   q="How is mild perioral dermatitis treated once the corticosteroid is stopped?",
   opts=[
     ["Topical metronidazole, erythromycin, pimecrolimus or azelaic acid",
      "Correct, with oral tetracycline or doxycycline for more extensive or persistent disease."],
     ["A higher-potency topical corticosteroid",
      "Continued corticosteroid exposure perpetuates the condition."],
     ["Topical ketoconazole",
      "Antifungals are the mainstay of seborrhoeic dermatitis rather than this."],
     ["Oral prednisone",
      "Systemic steroids are not the treatment described."]],
   c=0, cite=c(102)),

 dict(topic="Diaper dermatitis", io=IOC,
   q="Which feature distinguishes irritant from candidal diaper dermatitis?",
   opts=[
     ["Irritant disease affects convex surfaces and spares the inguinal folds; candidal disease involves the folds with satellite papules or pustules",
      "Correct — fold involvement is the discriminator, and it is called essential in the lecture."],
     ["Irritant disease involves the folds and candidal disease spares them",
      "The pattern is reversed."],
     ["Irritant disease produces satellite lesions and candidal disease does not",
      "Satellite lesions belong to candidal disease."],
     ["Only candidal disease causes erythema",
      "Both cause erythema; distribution is what separates them."]],
   c=0, cite=c(107)),

 dict(topic="Diaper dermatitis", io=IOC,
   q="Why are the inguinal folds generally spared in irritant diaper dermatitis?",
   opts=[
     ["They are less exposed to urine and faeces",
      "Correct — the eruption follows exposure, so it lands on convex surfaces."],
     ["They have thicker skin than the surrounding area",
      "Skin thickness is not the reason given."],
     ["They are protected by resident Candida",
      "Candida is a complication rather than a protection."],
     ["They receive less friction from the diaper",
      "Exposure to urine and faeces is the stated reason."]],
   c=0, cite=c(107)),

 dict(topic="Diaper dermatitis", io=IOC,
   q="What is the foundation of treatment for diaper dermatitis?",
   opts=[
     ["Reducing moisture and irritant exposure through frequent changes, gentle cleansing, air exposure and superabsorbent diapers, with a thick zinc oxide or petrolatum barrier at each change",
      "Correct. The previous barrier layer need not be scrubbed away if it remains clean."],
     ["A topical antifungal at every change regardless of cause",
      "Antifungals are added when candidal disease is suspected or confirmed."],
     ["Oral antibiotics to prevent secondary infection",
      "Antibiotics are used only when bacterial infection is clinically supported."],
     ["A high-potency topical corticosteroid until resolution",
      "Only a brief course of a low-potency steroid is used, under guidance."]],
   c=0, cite=c(109)),

 dict(topic="Stasis dermatitis", io=IOC,
   q="What underlies stasis dermatitis?",
   opts=[
     ["Chronic venous hypertension, most commonly from chronic venous insufficiency",
      "Correct — incompetent valves, obstruction or impaired calf-muscle pumping raise venous pressure."],
     ["Arterial insufficiency from peripheral arterial disease",
      "Arterial disease is a differential and a safety consideration, not the cause."],
     ["Lymphatic obstruction",
      "Lymphoedema is listed among the differentials rather than the cause."],
     ["Autoimmune damage to the basement membrane",
      "That is bullous pemphigoid."]],
   c=0, cite=c(112)),

 dict(topic="Stasis dermatitis", io=IOC,
   q="Where does stasis dermatitis characteristically appear?",
   opts=[
     ["In the gaiter region of one or both lower legs",
      "Correct, with pruritic erythematous, violaceous or hyperpigmented patches and plaques."],
     ["On the extensor surfaces of the elbows and knees",
      "That is plaque psoriasis."],
     ["In the antecubital and popliteal fossae",
      "That is childhood atopic dermatitis."],
     ["On the palms and soles",
      "That is dyshidrotic eczema."]],
   c=0, cite=c(114)),

 dict(topic="Stasis dermatitis", io=IOC,
   q="What are the two primary clinical priorities in stasis dermatitis?",
   opts=[
     ["Distinguishing it from cellulitis, and determining whether compression therapy can be used safely",
      "Correct — both are named as the priorities."],
     ["Identifying the causative organism and selecting an antibiotic",
      "It is not an infectious condition."],
     ["Determining the allergen and arranging patch testing",
      "That belongs to allergic contact dermatitis."],
     ["Staging the ulcer and measuring its depth",
      "Ulceration is a complication rather than the stated priority."]],
   c=0, cite=c(112)),

 dict(topic="Stasis dermatitis", io=IOC,
   q="Which finding should raise concern for deep venous thrombosis in a patient with suspected stasis dermatitis?",
   opts=[
     ["Acute unilateral swelling or pain",
      "Correct. Other considerations include peripheral arterial disease, vasculitis, lymphoedema and cutaneous malignancy."],
     ["Bilateral chronic hyperpigmentation",
      "That is the expected chronic picture of stasis dermatitis itself."],
     ["Pruritus with scaling",
      "That fits the dermatitis rather than a thrombosis."],
     ["Atrophie blanche",
      "That is a chronic feature of stasis disease."]],
   c=0, cite=c(115)),

 dict(topic="Stasis dermatitis", io=IOC,
   q="What is the cornerstone of management for stasis dermatitis, and what must be established first?",
   opts=[
     ["Compression therapy, once adequate arterial circulation has been established",
      "Correct — an ankle-brachial index or toe pressure is considered when arterial status must be clarified before substantial compression."],
     ["Compression therapy, applied immediately in all patients",
      "Arterial status must be established first; compression on an ischaemic limb is harmful."],
     ["Long-term systemic antibiotics",
      "It is not an infection."],
     ["High-potency topical corticosteroids as monotherapy",
      "A short steroid course controls inflammation but is not the cornerstone."]],
   c=0, cite=c(117)),
]
