# -*- coding: utf-8 -*-
"""CMS I Exam 2, Lecture 13 -- vignette set A.

Per the house style the lead-in VARIES and decides the answer: diagnosis, next
step, initial versus confirmatory test, treatment, education, prognosis. Set 1
carries the risk-factor and defining-feature questions; these carry the decision.
Distractors are right-disease / wrong-phase wherever possible.
"""
D = "Chronic Vision Loss & Tumors - Dr Rappa.pptx, Slide %d"
IO_A = "a — Chronic vision loss disorders: etiology, manifestations, testing, management"
IO_B = "b — Identify medical care strategies for common ophthalmological disorders by age"

QUESTIONS = [
 dict(topic="Idiopathic intracranial hypertension", io=IO_A, lead="next step", cite=D % 5,
  q="A 27-year-old woman with obesity has six weeks of headache, pulsatile tinnitus and papilledema. Brain imaging with venography is normal. What is the next step?",
  opts=[["Lumbar puncture to measure opening pressure", "Correct. Imaging first, then the pressure measurement that confirms it."],
        ["Start acetazolamide and review in a month", "Treatment should follow confirmation."],
        ["Repeat the scan with contrast", "The scan is already normal."],
        ["Refer for shunt placement", "Surgery is a last resort."],
        ["Reassure and treat as migraine", "Papilledema rules that out."]]),

 dict(topic="Idiopathic intracranial hypertension", io=IO_A, lead="education", cite=D % 5,
  q="A 32-year-old woman with idiopathic intracranial hypertension asks what will keep it from coming back. What do you tell her?",
  opts=[["Sustained weight reduction", "Correct. Medication covers her while that happens."],
        ["Lifelong acetazolamide", "That controls rather than resolves."],
        ["Avoiding bright light", "That has no effect on pressure."],
        ["Yearly lumbar punctures", "Those diagnose rather than treat."],
        ["Blood pressure control alone", "The pressure at issue is intracranial."]]),

 dict(topic="Idiopathic intracranial hypertension", io=IO_A, lead="reasoning", cite=D % 6,
  q="A 29-year-old woman has papilledema and headache. Why is venography included with her scan?",
  opts=[["To exclude venous sinus thrombosis", "Correct. A clot raises pressure and mimics the idiopathic form."],
        ["To measure the opening pressure", "That needs a lumbar puncture."],
        ["To look for multiple sclerosis", "That needs contrast imaging of the brain."],
        ["To assess the carotid arteries", "Those relate to ocular ischaemic syndrome."],
        ["To grade the papilledema", "Imaging does not grade it."]]),

 dict(topic="Primary open-angle glaucoma", io=IO_A, lead="diagnosis", cite=D % 9,
  q="A 69-year-old man has painless loss of peripheral vision over years, cupped discs and a raised pressure. Which diagnosis fits?",
  opts=[["Primary open-angle glaucoma", "Correct, with central acuity spared until late."],
        ["Acute angle-closure glaucoma", "That is sudden and painful."],
        ["Macular degeneration", "That takes the centre first."],
        ["Optic neuritis", "That is rapid and painful."],
        ["Cataract", "That clouds rather than constricts the field."]]),

 dict(topic="Primary open-angle glaucoma", io=IO_A, lead="next step", cite=D % 9,
  q="A 58-year-old woman with diabetes has never had an eye examination. What do you arrange?",
  opts=[["Annual ophthalmology review", "Correct. A medical eye risk needs the medical specialist."],
        ["Optometry for a refraction", "That addresses glasses, not disease."],
        ["Review only if vision changes", "Screening exists because it is silent."],
        ["Tonometry alone every five years", "Pressure alone is not enough."],
        ["No follow-up while she sees well", "Good vision does not exclude damage."]]),

 dict(topic="Primary open-angle glaucoma", io=IO_A, lead="education", cite=D % 9,
  q="A 74-year-old man with glaucoma asks why he must keep using drops when he sees no better. What do you say?",
  opts=[["They protect the vision he still has", "Correct. Damage already done cannot be reversed."],
        ["They will restore the lost field", "Lost field does not return."],
        ["They can be stopped once pressure normalises", "Stopping lets pressure rise again."],
        ["They treat the cataract as well", "They do not act on the lens."],
        ["They are needed only if symptoms appear", "By then damage is done."]]),

 dict(topic="Age-related macular degeneration", io=IO_A, lead="diagnosis", cite=D % 11,
  q="An 81-year-old woman reports straight lines looking bent and a blur at the centre of her reading. Which diagnosis fits?",
  opts=[["Age-related macular degeneration", "Correct. Central distortion is the hallmark."],
        ["Primary open-angle glaucoma", "That takes the periphery."],
        ["Nuclear cataract", "That clouds vision generally."],
        ["Retinal detachment", "That gives a curtain and flashes."],
        ["Presbyopia with near blur", "That is a focusing change, without distortion."]]),

 dict(topic="Age-related macular degeneration", io=IO_A, lead="next step", cite=D % 14,
  q="A 79-year-old man with known dry macular degeneration reports his central blur worsened sharply over a week. What is the concern?",
  opts=[["Conversion to the wet form", "Correct. New vessels bleeding cause a rapid change."],
        ["Progression of the dry form", "Dry disease changes slowly."],
        ["A new cataract", "That would not change over a week."],
        ["Glaucoma developing", "That is peripheral and slow."],
        ["Refractive change", "That does not distort the centre."]]),

 dict(topic="Age-related macular degeneration", io=IO_A, lead="treatment", cite=D % 14,
  q="An 83-year-old woman is confirmed to have wet macular degeneration. Which treatment is offered?",
  opts=[["Intravitreal anti-VEGF injection", "Correct, with photodynamic therapy and laser as alternatives."],
        ["The AREDS2 supplement alone", "That is for dry disease."],
        ["Lens replacement surgery", "That treats cataract."],
        ["Pressure-lowering drops", "Those treat glaucoma."],
        ["Patching the affected eye", "That treats childhood amblyopia."]]),

 dict(topic="Age-related macular degeneration", io=IO_A, lead="education", cite=D % 14,
  q="A 70-year-old man with early dry macular degeneration smokes 20 a day. What is the most useful advice?",
  opts=[["Stop smoking", "Correct. It is the risk factor he can change."],
        ["Take beta carotene at high dose", "That raised lung cancer risk in smokers."],
        ["Wear sunglasses indoors", "Not a stated measure."],
        ["Reduce dietary salt", "That does not affect the disease."],
        ["Stop reading in the evening", "Reading does not drive progression."]]),

 dict(topic="Refractive errors", io=IO_A, lead="next step", cite=D % 18,
  q="A 16-year-old girl cannot read the whiteboard but reads a book comfortably. What is the next step?",
  opts=[["Refer to optometry for refraction", "Correct. An isolated refractive error is their work."],
        ["Refer urgently to ophthalmology", "No medical eye disease is suggested."],
        ["Arrange brain imaging", "Nothing points to a neurological cause."],
        ["Start pressure-lowering drops", "There is no glaucoma here."],
        ["Patch the better eye", "That treats amblyopia, not myopia."]]),

 dict(topic="Refractive errors", io=IO_A, lead="reasoning", cite=D % 19,
  q="A 45-year-old man is farsighted. Why does a convex lens correct him?",
  opts=[["It converges light onto the retina", "Correct. His eye focuses behind the retina."],
        ["It scatters light backwards", "That corrects myopia."],
        ["It creates several focal points", "That is what astigmatism does."],
        ["It magnifies the retinal image", "Magnification is not the mechanism."],
        ["It filters ultraviolet light", "That is unrelated to focus."]]),

 dict(topic="Strabismus", io=IO_A, lead="next step", cite=D % 25,
  q="A 3-year-old boy has one eye that does not follow a toy. What is the next step?",
  opts=[["Refer to ophthalmology for full assessment", "Correct. Untreated misalignment leads to amblyopia."],
        ["Reassure that he will grow out of it", "Waiting risks permanent visual loss."],
        ["Prescribe glasses without assessment", "Assessment comes first."],
        ["Patch the affected eye", "Patching the weaker eye worsens it."],
        ["Review in a year", "The window for treatment is closing."]]),

 dict(topic="Strabismus", io=IO_A, lead="diagnosis", cite=D % 29,
  q="A 62-year-old man has sudden ptosis, a dilated pupil and an eye deviated down and out. What must be excluded urgently?",
  opts=[["An aneurysm compressing the third nerve", "Correct. Pupil involvement makes this an emergency."],
        ["Myasthenia gravis", "That spares the pupil and fluctuates."],
        ["Thyroid eye disease", "That restricts movement without pupil change."],
        ["Amblyopia", "That is developmental and painless."],
        ["Simple refractive error", "That does not affect the pupil."]]),

 dict(topic="Amblyopia", io=IO_B, lead="next step", cite=D % 30,
  q="A 4-year-old girl has 20/60 in the right eye and 20/25 in the left, with no ocular disease. What is the treatment?",
  opts=[["Patch or atropinise the left eye", "Correct. The better eye is occluded to train the weaker one."],
        ["Patch the right eye", "That would worsen the amblyopic eye."],
        ["Glasses alone and review in a year", "Glasses alone will not reverse it."],
        ["Refer for strabismus surgery", "No misalignment is described."],
        ["No action until school age", "Delay narrows the treatment window."]]),

 dict(topic="Amblyopia", io=IO_B, lead="prognosis", cite=D % 30,
  q="A 6-year-old boy starts patching for amblyopia. What do you tell his parents about outcome?",
  opts=[["Good, though not always fully normal vision", "Correct, and starting before five is better still."],
        ["Vision will be entirely normal", "Many do not reach normal acuity."],
        ["Treatment rarely works at this age", "Before seven the outlook is good."],
        ["He will need surgery regardless", "Surgery is not automatic."],
        ["Depth perception will be unaffected", "Stereo vision may still be impaired."]]),

 dict(topic="Amblyopia", io=IO_B, lead="reasoning", cite=D % 32,
  q="A toddler cries only when his right eye is covered. What does the examiner conclude?",
  opts=[["The left eye sees poorly", "Correct. He objects when his good eye is taken away."],
        ["The right eye sees poorly", "He tolerates the left being covered, so the right is better."],
        ["Both eyes are equal", "Equal eyes give a symmetric response."],
        ["He has a squint on the right", "The test assesses vision, not alignment."],
        ["The test is uninterpretable", "The asymmetry is the result."]]),

 dict(topic="Cataract", io=IO_A, lead="diagnosis", cite=D % 36,
  q="A 74-year-old woman has two years of gradual blurring, glare at night and a dimmed red reflex. Which diagnosis fits?",
  opts=[["Cataract", "Correct. Slow blurring, glare and a dulled reflex."],
        ["Macular degeneration", "That distorts the centre, and the reflex stays normal."],
        ["Open-angle glaucoma", "That takes the periphery and spares the reflex."],
        ["Optic neuritis", "That is rapid and painful."],
        ["Retinal detachment", "That is sudden with flashes and floaters."]]),

 dict(topic="Cataract", io=IO_A, lead="next step", cite=D % 39,
  q="A 71-year-old man has a cataract but manages daily life without difficulty. What do you advise?",
  opts=[["Defer until it affects daily life", "Correct, unless another eye disease forces the issue."],
        ["Operate now to prevent worsening", "Timing is driven by function, not by the finding."],
        ["Start drops to slow it", "No drop slows a cataract."],
        ["Refer urgently to ophthalmology", "Non-urgent unless complicated."],
        ["Repeat glasses every three months", "That does not address the lens."]]),

 dict(topic="Cataract", io=IO_A, lead="next step", cite=D % 36,
  q="A 66-year-old woman has a cataract and cannot have her retina examined because of it. Does that change the plan?",
  opts=[["Yes, surgery is needed to see behind it", "Correct. It blocks diagnosis of other eye disease."],
        ["No, wait until vision is worse", "Waiting leaves other disease unmonitored."],
        ["No, imaging can substitute entirely", "A view of the retina is still needed."],
        ["Yes, but only if she has glaucoma", "Any obstructed assessment counts."],
        ["No, cataracts never interfere with this", "They plainly can."]]),

 dict(topic="Cataract", io=IO_B, lead="next step", cite=D % 36,
  q="A newborn has an absent red reflex in one eye. What happens next?",
  opts=[["Urgent ophthalmology referral", "Correct. Both retinoblastoma and congenital cataract present this way."],
        ["Review at the six-week check", "Far too slow for leukocoria."],
        ["Reassure, as reflexes vary", "An absent reflex is never normal."],
        ["Refer to optometry", "This needs medical ophthalmology."],
        ["Repeat the examination in a month", "Delay risks both sight and life."]]),

 dict(topic="Retinoblastoma", io=IO_B, lead="next step", cite=D % 42,
  q="You suspect retinoblastoma in a 2-year-old and the offered appointment is in two months. What do you do?",
  opts=[["Call the specialist and get it brought forward", "Correct, and document it if they will not."],
        ["Accept the appointment offered", "Two months is unacceptable for a suspected malignancy."],
        ["Refer to a different specialty instead", "The right specialty is needed, sooner."],
        ["Wait and reassess in a month", "Delay costs lives here."],
        ["Arrange imaging and review the results first", "The referral should not wait on that."]]),

 dict(topic="Retinoblastoma", io=IO_A, lead="reasoning", cite=D % 42,
  q="A child has a retinal mass typical of retinoblastoma. Why is the diagnosis made without tissue?",
  opts=[["Biopsy risks seeding the tumour", "Correct. Examination and imaging suffice."],
        ["Pathology cannot distinguish it", "Pathology could; the risk is the objection."],
        ["The lesion is inaccessible", "Access is not the barrier."],
        ["Imaging is definitive for all eye tumours", "It is the seeding risk that decides it."],
        ["Parents usually decline biopsy", "The reason is clinical, not preference."]]),

 dict(topic="Uveal melanoma", io=IO_A, lead="next step", cite=D % 46,
  q="A 60-year-old woman has a raised pigmented iris lesion with a feeder vessel that has grown. What is the next step?",
  opts=[["Refer to ophthalmology, likely ocular oncology", "Correct. Growth and vascularity raise real concern."],
        ["Reassure and review in a year", "A growing vascular lesion is not observed casually."],
        ["Biopsy it in clinic", "Iris lesions are not sampled in primary care."],
        ["Start topical steroid", "That treats inflammation, not tumour."],
        ["Photograph and repeat in five years", "Far too slow for a changing lesion."]]),

 dict(topic="Uveal melanoma", io=IO_A, lead="education", cite=D % 46,
  q="A 64-year-old man treated for choroidal melanoma asks what follow-up he needs. What do you tell him?",
  opts=[["Surveillance for liver metastasis", "Correct. The liver is where it goes."],
        ["Yearly chest imaging only", "The liver is the priority site."],
        ["Brain imaging every six months", "Not the commonest site."],
        ["Examination of the other eye only", "Systemic spread is the concern."],
        ["No follow-up once treated locally", "Local control does not exclude spread."]]),

 dict(topic="Uveal melanoma", io=IO_A, lead="prognosis", cite=D % 46,
  q="Two patients have uveal melanoma, one of the iris and one of the ciliary body. What do you expect?",
  opts=[["The iris tumour carries the better outlook", "Correct, roughly 4 to 10 percent mortality against far worse."],
        ["The ciliary body tumour does better", "It is found later and does worse."],
        ["The outlook is identical", "Site changes prognosis considerably."],
        ["Neither can be treated", "Both are treatable."],
        ["Both are almost always fatal", "The iris form in particular is not."]]),

 dict(topic="Iris nevus", io=IO_A, lead="next step", cite=D % 49,
  q="A 35-year-old man has a flat, 2 mm, avascular pigmented iris spot noticed at a routine visit. What do you do?",
  opts=[["Refer to ophthalmology to document and monitor", "Correct. Likely benign, but a baseline is needed."],
        ["Reassure with no referral", "A baseline measurement matters."],
        ["Refer for urgent oncology assessment", "Disproportionate for a flat avascular spot."],
        ["Start surveillance imaging of the liver", "That follows a melanoma diagnosis."],
        ["Excise it in clinic", "Iris lesions are not excised in primary care."]]),

 dict(topic="Iris nevus", io=IO_A, lead="reasoning", cite=D % 48,
  q="A 52-year-old woman has an iris lesion and asks how it will be told from a cancer. What distinguishes them?",
  opts=[["Growth, size and vascularity", "Correct. A nevus stays flat, small and avascular."],
        ["Colour alone", "Both may be brown."],
        ["Which eye it is in", "Side is not a discriminator."],
        ["Whether it is painful", "Both are typically painless."],
        ["Whether it affects vision", "Both are usually asymptomatic."]]),

 dict(topic="Conjunctival melanoma", io=IO_A, lead="diagnosis", cite=D % 52,
  q="A 58-year-old woman has a raised, vascular pigmented conjunctival lesion that has enlarged. Which diagnosis is most concerning?",
  opts=[["Conjunctival melanoma", "Correct. Raised, vascular and growing."],
        ["Conjunctival nevus", "That is flat, stable and often cystic."],
        ["Racial melanosis", "That is bilateral and symmetric."],
        ["Primary acquired melanosis", "That is flat and patchy."],
        ["Pinguecula", "That is a yellow non-pigmented nodule."]]),

 dict(topic="Chronic vision loss", io=IO_A, lead="reasoning", cite=D % 22,
  q="A 55-year-old man has reduced acuity and says colours look washed out. Which cause does that point to?",
  opts=[["Optic neuropathy", "Correct. It is the one that takes colour vision."],
        ["Cataract", "That clouds without stripping colour."],
        ["Open-angle glaucoma", "That takes peripheral field."],
        ["Macular degeneration", "That distorts the centre."],
        ["Refractive error", "That blurs and corrects with lenses."]]),
]
