# -*- coding: utf-8 -*-
"""Lecture 25 vignette pool C -- Heart Failure: right-sided and combined failure,
acute versus chronic, the defibrillator pathway, perfusion and referral.

KEYS ARE WRITTEN SHORT ON PURPOSE -- detail lives in the explanation.

Next-step and referral lead-ins carry this pool, so the vignette sets do not lean
on diagnosis. The defibrillator criteria are keyed to the slide (life expectancy
of at least one year); the recording inverted it, so the class may have heard the
opposite. Right heart catheterization is keyed only for "hemodynamic severity" --
its pressure table was declared not tested. The congestion case is a fresh
patient built on the slide's own lines ("Clinical diagnosis requires congestion;
Congestion = Edema"), not the slide's unanswered case.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _cmse3_q import Q
from cms_e4l25_scope import *


def S(topic, io, q, opts, cite, slot):
    d = Q(topic, io, q, opts, cite); d["slot"] = slot; return d


def V(topic, io, q, opts, cite, slot, lead):
    d = S(topic, io, q, opts, cite, slot); d["lead"] = lead; return d


QUESTIONS = [

V("Right-sided heart failure", IO_A,
  "A 61-year-old woman has had left-sided heart failure with reduced ejection fraction for five years. Over two months she has developed leg edema, jugular venous distension (distended neck veins), an enlarged liver, nausea and poor appetite. Which is the most likely explanation for her new findings?",
  [["Right-sided failure from her left-sided failure",
    "Correct. Chronic left-sided failure is the most common cause of right-sided failure. Systemic overload gives edema and distended neck veins; portal overload gives nausea, poor appetite and hepatomegaly."],
   ["High-output failure from increased demand",
    "High-output failure comes from anemia, hyperthyroidism or an arteriovenous fistula. Her picture is right-sided failure following chronic left-sided disease."],
   ["Worsening systolic failure of the left only",
    "Left-sided worsening would add orthopnea and crackles. Edema, neck veins and portal congestion mean the right ventricle has now failed."],
   ["Primary liver disease with ascites",
    "The enlarged liver here is congestion from right ventricular failure, which also explains her distended neck veins and edema."]],
  C(9), "etiology", "diagnosis"),

V("Right-sided heart failure", IO_A,
  "A 34-year-old woman has progressive leg edema and jugular venous distension (distended neck veins). At the apex there is a low-pitched diastolic rumble with an opening snap. Which is the most likely cause of her right-sided heart failure?",
  [["Mitral valve stenosis",
    "Correct. A rumbling diastolic murmur at the apex with an opening snap is mitral stenosis, one of the three causes of right-sided failure with chronic left-sided failure and pulmonary arterial hypertension."],
   ["Tricuspid regurgitation",
    "Tricuspid regurgitation gives a holosystolic murmur at the left lower sternal border, louder on inspiration. An apical diastolic rumble with a snap is mitral stenosis."],
   ["Aortic valve stenosis",
    "Aortic stenosis is the most common valvular cause of heart failure overall but does not give an apical diastolic rumble with a snap. This is mitral stenosis."],
   ["Hypertrophic cardiomyopathy",
    "Hypertrophic cardiomyopathy leads the diastolic chain with a fourth heart sound. An apical diastolic rumble with a snap is mitral stenosis."]],
  C(10), "etiology", "diagnosis"),

V("Right-sided heart failure", IO_A,
  "A 58-year-old man has leg edema and jugular venous distension (distended neck veins) with a raised B-type natriuretic peptide. Right-sided heart failure is suspected. Which test establishes the definitive diagnosis?",
  [["Echocardiogram",
    "Correct. Clinical heart failure with distended neck veins raises suspicion of right-sided failure, and the echocardiogram gives the definitive diagnosis by ejection fraction."],
   ["Right heart catheterization",
    "Catheterization measures hemodynamic severity once right-sided failure is suspected or confirmed. The definitive diagnosis comes from the echocardiogram."],
   ["Repeat natriuretic peptide",
    "The peptide supports heart failure but cannot say which ventricle has failed. The echocardiogram gives the definitive diagnosis."],
   ["Twelve-lead electrocardiogram",
    "The electrocardiogram may show right heart strain but does not make the diagnosis. The echocardiogram does."]],
  C(10), "gold standard", "test"),

V("Right-sided heart failure", IO_A,
  "A 63-year-old woman has right-sided heart failure confirmed by echocardiogram. Her team now wants to know how hemodynamically severe it is. Which is the most appropriate next step?",
  [["Right heart catheterization",
    "Correct. Once right-sided failure is established, right heart catheterization measures its hemodynamic severity. The echocardiogram has already made the diagnosis."],
   ["Repeat echocardiogram",
    "The echocardiogram made the diagnosis by ejection fraction. Hemodynamic severity is measured by right heart catheterization."],
   ["Chest radiograph series",
    "A radiograph shows effusions and heart size but not hemodynamics. Severity is measured by right heart catheterization."],
   ["Troponin trend over a day",
    "Troponin addresses infarction or ischemic cardiomyopathy. Severity is measured by right heart catheterization."]],
  C(10), "initial test", "next step"),

V("Right-sided heart failure", IO_A,
  "A 67-year-old man with chronic left-sided heart failure now has right-sided failure as well. Which management approach is most appropriate?",
  [["Treat as left-sided failure and its cause",
    "Correct. Right-sided failure is treated the same as left-sided failure, with symptom management and treatment of the underlying cause, moving to transplant or palliative care as it advances."],
   ["Stop his left-sided heart failure drugs",
    "Right-sided failure is treated the same as left-sided failure, so his guideline-directed therapy continues alongside treatment of the cause."],
   ["Start a calcium channel blocker",
    "Calcium channel blockers are avoided in heart failure. Right-sided failure is treated as left-sided failure is, plus its cause."],
   ["Start home inotropic support",
    "Inotropes are for intensive care use only. Right-sided failure is treated as left-sided failure is, plus its cause."]],
  C(10), "first-line", "treatment"),

V("Right-sided heart failure", IO_A,
  "A 70-year-old man with chronic left-sided heart failure develops right-sided failure. He asks what this means for his outlook. Which reply is accurate?",
  [["His prognosis is now much worse",
    "Correct. Right-sided failure carries a much worse prognosis than left-sided failure, and in him it marks progression of chronic left-sided disease."],
   ["His prognosis is unchanged",
    "The outlook does change: right-sided failure carries a much worse prognosis than left-sided failure."],
   ["His prognosis is now better",
    "The comparison runs the other way. Right-sided failure carries a much worse prognosis than left-sided failure."],
   ["It improves once edema clears",
    "Clearing edema relieves symptoms but does not change the outlook: right-sided failure carries a much worse prognosis."]],
  C(9), "prognosis", "complication"),

V("Right-sided heart failure", IO_A,
  "A 64-year-old man has combined right and left heart failure with symptoms at rest despite optimized guideline-directed therapy. Which course is most appropriate to discuss?",
  [["Transplant evaluation or comfort care",
    "Correct. Combined right and left failure is managed with symptom control, comfort care and heart transplant. When optimized therapy no longer controls symptoms, those are the options to raise."],
   ["Adding a calcium channel blocker",
    "Calcium channel blockers are avoided in heart failure. Combined failure beyond optimized therapy points to transplant evaluation or comfort care."],
   ["Continuing dobutamine at home",
    "Inotropes are for intensive care use only. Combined failure beyond optimized therapy points to transplant evaluation or comfort care."],
   ["Stopping all medicines and observing",
    "Abandoning symptom control is not the plan. Combined failure beyond optimized therapy points to transplant evaluation or comfort care."]],
  C(11), "referral", "referral"),

V("Right-sided heart failure", IO_A,
  "An 84-year-old woman with right-sided heart failure has progressive symptoms despite treatment of its cause and is not a transplant candidate. Which approach is most appropriate?",
  [["Palliative care focused on symptoms",
    "Correct. Right-sided failure is treated like left-sided failure, with symptom management, treatment of the cause, heart transplant or palliative care. When transplant is not an option, palliative care is the route."],
   ["Calcium channel blocker for comfort",
    "Calcium channel blockers are avoided in heart failure. Without a transplant option, palliative care focused on symptoms is the route."],
   ["Inotropes started for home use",
    "Inotropes are for intensive care use only. Without a transplant option, palliative care focused on symptoms is the route."],
   ["Discharge without follow-up care",
    "Withdrawing care is not the plan. Without a transplant option, palliative care focused on symptoms is the route."]],
  C(10), "referral", "referral"),

V("Devices", IO_F,
  "A 58-year-old man had an anterior myocardial infarction one week ago with acute heart failure. Echocardiogram shows an ejection fraction of 30%. He is now stable. Which is the most appropriate next step for protection against sudden death?",
  [["Wearable defibrillator while therapy is optimized",
    "Correct. After acute heart failure from infarction with an ejection fraction below 35%, the pathway is a wearable defibrillator vest, optimized guideline-directed therapy with cardiac rehabilitation, a repeat echocardiogram, and an implantable device only if there is no improvement."],
   ["Implantable defibrillator before discharge",
    "The implantable device comes last, only if a repeat echocardiogram after optimized therapy shows no improvement. The first step is a wearable defibrillator."],
   ["No protection until a repeat echo in a year",
    "Leaving him unprotected ignores the risk; about half of cardiac arrests in these patients are ventricular arrhythmias. A wearable defibrillator comes first."],
   ["Home inotropes until the heart recovers",
    "Inotropes are for intensive care use only. The first step is a wearable defibrillator while therapy is optimized."]],
  C(53), "escalation", "next step"),

V("Devices", IO_F,
  "A 60-year-old woman wore a defibrillator vest for three months after an infarction, with optimized guideline-directed therapy and cardiac rehabilitation. Her repeat echocardiogram shows an ejection fraction of 28%. She is class II and expected to live many years. Which is the most appropriate next step?",
  [["Implantable cardioverter-defibrillator",
    "Correct. The pathway ends with an implantable device when the repeat echocardiogram shows no improvement. She also meets the criteria: ejection fraction 35% or less, class II or III, optimal therapy and life expectancy of at least one year."],
   ["Continue the vest indefinitely",
    "The vest bridges the recovery period. With no improvement on the repeat echocardiogram, the next step is an implantable defibrillator."],
   ["Heart transplant evaluation now",
    "Transplant is reserved for failure that cannot be controlled. She is class II and meets the criteria for an implantable defibrillator."],
   ["Stop therapy and recheck in a year",
    "Stopping therapy would undo the optimization. With no improvement, the next step is an implantable defibrillator."]],
  C(53), "escalation", "next step"),

V("Devices", IO_F,
  "A 55-year-old man wore a defibrillator vest after an infarction while his guideline-directed therapy was optimized and he completed cardiac rehabilitation. His repeat echocardiogram shows an ejection fraction of 47%. Which is the most appropriate next step?",
  [["Continue therapy without a device",
    "Correct. The implantable defibrillator is placed only if the repeat echocardiogram shows no improvement. At 47% his fraction is well above the 35% threshold, so therapy continues without a device."],
   ["Implantable cardioverter-defibrillator",
    "The device requires an ejection fraction of 35% or less after optimized therapy. At 47% he no longer meets that."],
   ["Continue the vest indefinitely",
    "The vest bridges the recovery period only. With his fraction recovered to 47%, he continues therapy without a device."],
   ["Start inotropic therapy at home",
    "Inotropes are for intensive care use only, and his heart has improved. He continues guideline-directed therapy without a device."]],
  C(53), "escalation", "next step"),

V("Devices", IO_F,
  "A 62-year-old woman is three days out from a myocardial infarction complicated by acute heart failure, with an ejection fraction of 30%. A colleague proposes an implantable defibrillator before discharge. Which step is premature at this point?",
  [["Implanting a defibrillator now",
    "Correct. After acute heart failure from infarction, the pathway is a wearable defibrillator, optimized therapy and cardiac rehabilitation, then a repeat echocardiogram; the implantable device follows only if there is no improvement."],
   ["Starting a wearable defibrillator",
    "The wearable defibrillator is exactly the first step for her. What is premature is the implantable device."],
   ["Optimizing her guideline therapy",
    "Optimizing therapy is part of the pathway now. What is premature is the implantable device."],
   ["Referring to cardiac rehabilitation",
    "Cardiac rehabilitation is part of the pathway now. What is premature is the implantable device."]],
  C(53), "avoid", "avoid"),

V("Devices", IO_A,
  "A 71-year-old man with ischemic cardiomyopathy has an ejection fraction of 25%, is class II on optimal guideline-directed therapy, and has metastatic cancer with an expected survival of a few months. Which is most appropriate regarding an implantable defibrillator?",
  [["It is not indicated for him",
    "Correct. The device is indicated only with a life expectancy of at least one year, together with ejection fraction 35% or less, class II or III and optimal therapy. His expected survival of months fails that criterion."],
   ["Implant it before discharge",
    "His fraction and class qualify, but the life expectancy criterion of at least one year does not. The device is not indicated."],
   ["Implant it once he is class IV",
    "Class IV falls outside the class II to III criterion, and his life expectancy still fails. The device is not indicated."],
   ["Implant it after a cardiac arrest",
    "The criteria do not wait for an arrest, and his life expectancy of months fails them. The device is not indicated."]],
  C(53), "avoid", "avoid"),

V("Devices", IO_A,
  "A 64-year-old woman with non-ischemic dilated cardiomyopathy has an ejection fraction of 30% after six months of optimized guideline-directed therapy. She is breathless with exertion but not at rest and is otherwise healthy. Which is the most appropriate next step?",
  [["Implantable cardioverter-defibrillator",
    "Correct. She meets every criterion: non-ischemic cardiomyopathy with ejection fraction 35% or less, class II, optimal guideline-directed therapy and life expectancy of at least one year."],
   ["A calcium channel blocker for rate",
    "Calcium channel blockers are avoided in heart failure. She meets the criteria for an implantable cardioverter-defibrillator."],
   ["Heart transplant listing right away",
    "Transplant is for failure beyond control; she is class II. She meets the criteria for an implantable cardioverter-defibrillator."],
   ["Inotropes in the intensive care unit",
    "She is stable and class II; inotropes are for critical illness. She meets the criteria for an implantable defibrillator."]],
  C(53), "escalation", "next step"),

V("Devices", IO_A,
  "A 68-year-old man hospitalized with heart failure with reduced ejection fraction asks why a defibrillator is being discussed. Which cause accounts for about half of cardiac arrests in hospitalized patients like him?",
  [["Ventricular arrhythmias",
    "Correct. About 52% of cardiac arrests in hospitalized patients with reduced ejection fraction are due to ventricular arrhythmias, which is the reason for defibrillator protection in those who meet the criteria."],
   ["Acute pulmonary embolism",
    "Pulmonary embolism is not the leading cause of these arrests. About half of these cardiac arrests are due to ventricular arrhythmias."],
   ["Complete heart block",
    "Complete heart block is not the leading cause of these arrests. About half of these cardiac arrests are due to ventricular arrhythmias."],
   ["Low potassium alone",
    "Electrolytes matter on diuretics, but about half of these cardiac arrests are due to ventricular arrhythmias."]],
  C(53), "complication", "complication"),

V("Devices", IO_F,
  "A 57-year-old woman recovering from acute heart failure after an infarction, with an ejection fraction of 31%, asks why she must wear a defibrillator vest. Which explanation is accurate?",
  [["It protects her while therapy is optimized",
    "Correct. The vest covers the period in which guideline-directed therapy is optimized and she completes cardiac rehabilitation; the echocardiogram is then repeated to decide whether she needs an implantable device."],
   ["It replaces her heart failure medicines",
    "The vest does not replace therapy; it protects her while therapy is optimized, before the echocardiogram is repeated."],
   ["It is permanent for everyone after infarction",
    "The vest is a bridge. After optimized therapy and rehabilitation the echocardiogram is repeated to decide whether an implantable device is needed."],
   ["It measures her ejection fraction daily",
    "The vest protects against sudden death; it does not measure function. The echocardiogram is repeated after optimized therapy."]],
  C(53), "education", "education"),

V("Devices", IO_F,
  "A 59-year-old man is recovering from acute heart failure after an infarction with an ejection fraction of 29%. He wears a defibrillator vest while his guideline-directed therapy is being optimized. Which referral should accompany this phase?",
  [["Cardiac rehabilitation",
    "Correct. After acute heart failure with an ejection fraction below 35%, the pathway pairs optimized guideline-directed therapy with cardiac rehabilitation while he wears the vest, before the echocardiogram is repeated."],
   ["Hospice enrollment",
    "Hospice does not fit a recovery pathway that ends in a repeat echocardiogram. The referral that accompanies this phase is cardiac rehabilitation."],
   ["Transplant evaluation",
    "Transplant is for failure that progresses despite management. The referral that accompanies this phase is cardiac rehabilitation."],
   ["Valve surgery review",
    "Nothing points to valve disease. The referral that accompanies optimized therapy after acute failure is cardiac rehabilitation."]],
  C(53), "referral", "referral"),

V("Acute and chronic heart failure", IO_F,
  "A 75-year-old man with heart failure diagnosed three years ago has had four days of worsening orthopnea (breathlessness lying flat) and leg swelling. How is this episode classified?",
  [["Acute on chronic heart failure",
    "Correct. Heart failure present for more than a year is chronic, and a sudden worsening on top of it is acute on chronic heart failure, the last step of the sequence from pre-heart failure through exacerbation."],
   ["Acute new-onset heart failure",
    "New-onset failure is a first symptomatic episode. He has had heart failure for three years, so this is acute on chronic heart failure."],
   ["Pre-heart failure, stage B",
    "Pre-heart failure is asymptomatic structural disease. He is symptomatic with known chronic disease: acute on chronic heart failure."],
   ["High-output heart failure",
    "Nothing suggests anemia, hyperthyroidism or a fistula. This is a sudden worsening of chronic disease, acute on chronic heart failure."]],
  C(31), "differential", "diagnosis"),

V("Acute and chronic heart failure", IO_F,
  "A 73-year-old woman has grade II diastolic dysfunction with an ejection fraction of 46%. She has fatigue and breathlessness with exertion but has never had pulmonary or peripheral edema and has never needed a diuretic. Does she meet a clinical diagnosis of congestive heart failure?",
  [["No, because congestion is required",
    "Correct. A clinical diagnosis of congestive heart failure requires congestion, meaning pulmonary or peripheral edema. She has symptoms and a mildly reduced ejection fraction, but without edema the congestive label does not apply."],
   ["Yes, because she has symptoms",
    "Symptoms make heart failure clinical, but calling it congestive requires congestion, meaning edema, which she has never had."],
   ["Yes, because her fraction is 46%",
    "Her fraction places her in the mildly reduced group; it does not make the heart failure congestive. Congestion, meaning edema, is required."],
   ["Yes, because she is older than 65",
    "Age does not define the diagnosis. A clinical diagnosis of congestive heart failure requires congestion, meaning edema."]],
  C(30), "differential", "diagnosis"),

V("Diagnostic testing", IO_A,
  "A 66-year-old man presents for the first time with breathlessness, leg edema, crackles and a B-type natriuretic peptide of 720. Which is the most appropriate next step to classify his heart failure?",
  [["Echocardiogram",
    "Correct. Signs, symptoms and an elevated peptide support a clinical diagnosis, and the echocardiogram then shows structure most accurately and sorts him into an ejection fraction group, which decides therapy."],
   ["Right heart catheterization",
    "Catheterization grades hemodynamic severity in selected right-sided failure. Classification by ejection fraction and structure starts with an echocardiogram."],
   ["Repeat the peptide next week",
    "Repeating the peptide will not classify him. The echocardiogram defines structure and ejection fraction group."],
   ["Exercise stress testing",
    "Stress testing does not classify heart failure. The echocardiogram defines structure and ejection fraction group."]],
  C(32), "initial test", "next step"),

V("Natriuretic peptides", IO_F,
  "A 55-year-old woman has breathlessness on exertion for a week. Her B-type natriuretic peptide is 45. Which is the most appropriate next step?",
  [["Look for a non-cardiac cause",
    "Correct. A level below 100 rules out acute heart failure with a negative predictive value above 90%, so her breathlessness needs another explanation."],
   ["Start a loop diuretic today",
    "A diuretic treats congestion from heart failure, which a level of 45 rules out acutely. Another cause should be sought."],
   ["Admit for acute heart failure",
    "Acute heart failure is likely only above 900. At 45 it is ruled out, and another cause should be sought."],
   ["Order an implantable device",
    "A defibrillator requires established reduced ejection fraction and other criteria. At 45 acute heart failure is ruled out."]],
  C(38), "test finding", "next step"),

V("Reduced ejection fraction therapy", IO_D,
  "A 66-year-old woman with reduced ejection fraction (fraction 30%) has gained weight with leg edema and crackles. She takes a beta blocker, sacubitril-valsartan, spironolactone and dapagliflozin. Which drug relieves her fluid overload now?",
  [["A loop diuretic such as furosemide",
    "Correct. Diuretics are used as needed for congestion in every ejection fraction group; loops such as furosemide and bumetanide are the potassium-wasting diuretics that clear fluid."],
   ["Diltiazem to slow the heart rate",
    "Diltiazem is a calcium channel blocker, which is avoided in heart failure. Her congestion needs a loop diuretic."],
   ["Dobutamine given at home",
    "Dobutamine is an inotrope for intensive care use only. Her congestion needs a loop diuretic."],
   ["Hydralazine given on its own",
    "Hydralazine is paired with isosorbide dinitrate for selected patients in functional class III or IV; it does not clear fluid. Her congestion needs a loop diuretic."]],
  C(52), "first-line", "treatment"),

V("Acute and chronic heart failure", IO_F,
  "An 80-year-old man in the intensive care unit with acute heart failure has cool extremities and hypotension, and inotropic support is being considered. Which agents are used for this?",
  [["Dobutamine or milrinone",
    "Correct. Inotropic therapy for intensive care use includes the sympathomimetics dobutamine, norepinephrine and epinephrine and the phosphodiesterase inhibitor milrinone."],
   ["Diltiazem or verapamil",
    "These are calcium channel blockers, which are avoided in heart failure. Inotropic support uses dobutamine or milrinone."],
   ["Spironolactone or eplerenone",
    "These are mineralocorticoid receptor antagonists for chronic reduced ejection fraction. Inotropic support uses dobutamine or milrinone."],
   ["Losartan or irbesartan",
    "These are angiotensin receptor blockers for chronic therapy. Inotropic support in intensive care uses dobutamine or milrinone."]],
  C(51), "agent/regimen", "treatment"),

V("Patient education", IO_A,
  "A 45-year-old woman with a family history of heart failure smokes, drinks heavily and is obese. Her heart is structurally normal. Which counseling point best lowers her heart failure risk?",
  [["Quit tobacco, cut alcohol, lose weight",
    "Correct. Tobacco, excessive alcohol and obesity are modifiable risk factors for heart failure. Her family history is a risk factor she cannot change, so counseling targets the ones she can."],
   ["Family history cannot be offset at all",
    "Family history is fixed, but her modifiable risk factors (tobacco, alcohol, obesity) can still be changed to lower her risk."],
   ["Start a loop diuretic as prevention",
    "Diuretics treat congestion and do not prevent heart failure. Counseling targets tobacco, alcohol and obesity."],
   ["Wait for symptoms before changing",
    "Waiting forfeits prevention. Tobacco, excess alcohol and obesity are modifiable now."]],
  C(18), "education", "education"),

V("Complications", IO_A,
  "A 78-year-old woman with chronic heart failure has increasing lethargy, episodes of near-syncope and cool extremities, without new edema. Which feature of the heart failure syndrome do these findings reflect?",
  [["Inadequate tissue perfusion",
    "Correct. Weakness, fatigue, lethargy, malaise, syncope or near-syncope and obtundation are signs of inadequate tissue perfusion, the low-output side of the syndrome, distinct from congestion."],
   ["Worsening pulmonary congestion",
    "Congestion shows as orthopnea, crackles and edema, which she lacks. Lethargy, near-syncope and cool extremities reflect inadequate perfusion."],
   ["Portal venous overload",
    "Portal overload gives nausea, poor appetite and an enlarged liver. Her findings reflect inadequate perfusion."],
   ["Systemic volume overload",
    "Systemic overload shows as edema and distended neck veins, which she lacks. Her findings reflect inadequate perfusion."]],
  C(26), "complication", "complication"),
]
