# -*- coding: utf-8 -*-
# CMS I Lecture 6 — SET 2, vignette pool C.
# Viral skin infections: varicella, herpes zoster and its complications, herpes
# simplex, herpetic whitlow, molluscum contagiosum, and warts.
#
# THE SLIDE IS AUTHORITATIVE (Jaxon, 2026-08-20). Every fact is from the deck.
# Lead-ins are explicit; distractors match the answer's shape.
# Correct answer is ALWAYS written first (c=0); the partition script rotates.
SRC = "6. Fungal and Viral Skin Infections - Jaquith.pptx"
def c(n): return f"{SRC}, Slide {n}"

IOB = "Objective b — Compare and contrast the etiologies, epidemiology, risk factors, clinical manifestations, differential diagnosis, diagnostic testing (including ordering and interpretation), management (acute and chronic, including applicable rehabilitative and palliative care), appropriate referrals, patient education, and prognosis of cutaneous viral and fungal infections"
IOC = "Objective c — Identify medical care strategies for cutaneous viral and fungal infections for infant, child, adolescent, adult and elderly populations"

VIG_C = [
 dict(topic="Varicella", io=IOC, lead="diagnosis",
   q="A 6-year-old has fever and a generalized itchy eruption. On the trunk, scalp and face there are macules, papules, vesicles and crusts all present at the same time. Which is the most likely diagnosis?",
   opts=[
     ["Varicella",
      "Correct — several stages appearing simultaneously is the defining feature."],
     ["Herpes zoster",
      "Zoster is a unilateral dermatomal eruption that stops at the midline."],
     ["Molluscum contagiosum",
      "Molluscum gives umbilicated pearly papules, not vesicles and crusts."],
     ["Herpes simplex",
      "Herpes simplex gives grouped vesicles at one site, not a generalized eruption."]],
   c=0, cite=c(84)),

 dict(topic="Varicella", io=IOC, lead="treatment",
   q="A 5-year-old with varicella has fever and discomfort. The mother asks which over-the-counter medicine to give. Which is the most appropriate response?",
   opts=[
     ["Give supportive care, avoid aspirin, and use caution with non-steroidal anti-inflammatory drugs",
      "Correct — aspirin is avoided in children with varicella."],
     ["Give supportive care, avoid paracetamol, and use aspirin freely for the fever and discomfort",
      "This reverses the advice; aspirin is the drug to avoid."],
     ["Give an oral antiviral to every child, and avoid all analgesia until the lesions have crusted",
      "Antivirals are considered for higher-risk patients, not all children."],
     ["Give a systemic corticosteroid for the inflammation, and avoid antihistamines for the itch",
      "Systemic steroids are not part of varicella care here."]],
   c=0, cite=c(87)),

 dict(topic="Varicella", io=IOB, lead="next step",
   q="A patient with varicella has severe, disseminated disease. Which is the most appropriate management?",
   opts=[
     ["Intravenous acyclovir",
      "Correct — reserved for severe or disseminated disease."],
     ["Oral acyclovir alone at standard dose",
      "Early oral antivirals are for higher-risk patients, not severe disease."],
     ["Supportive care alone with no antiviral",
      "Severe disease warrants intravenous therapy."],
     ["Varicella-zoster immune globulin alone",
      "That is a postexposure measure, not treatment of severe disease."]],
   c=0, cite=c(87)),

 dict(topic="Varicella", io=IOC, lead="next step",
   q="You are covering a clinic and several patients with varicella are booked in. Which of these situations does the lecture say warrants prompt consultation?",
   opts=[
     ["Pregnancy, neonatal exposure, immunocompromise, or severe complications",
      "Correct — four named triggers for prompt consultation."],
     ["A preadolescent child with a typical eruption and no fever",
      "That is the usual host with typical disease."],
     ["Any patient whose lesions have already crusted over completely",
      "Crusted lesions mark the end of contagiousness."],
     ["Any patient who has previously received one dose of vaccine",
      "Prior vaccination is not itself a consultation trigger."]],
   c=0, cite=c(87)),

 dict(topic="Varicella", io=IOB, lead="education",
   q="A parent asks when her child with varicella may return to normal activities. Which is the most appropriate response?",
   opts=[
     ["The child is contagious from 1 to 2 days before the rash until all lesions have crusted",
      "Correct — contagiousness begins before the rash is visible."],
     ["The child is contagious only from the day the rash appears until the fever resolves",
      "Contagiousness starts 1 to 2 days before the rash and ends with crusting."],
     ["The child is contagious for 21 days from exposure regardless of the lesions",
      "The deck ties contagiousness to the lesions, not to a fixed interval."],
     ["The child is contagious only while new vesicles are forming, not once any have crusted",
      "All lesions must crust, not merely some."]],
   c=0, cite=c(89)),

 dict(topic="Varicella", io=IOB, lead="education",
   q="A child has breakthrough varicella with lesions that do not form crusts. How is the end of the contagious period determined?",
   opts=[
     ["When no new lesions have appeared for 24 hours",
      "Correct — the rule for breakthrough disease without crusts."],
     ["When the last lesion has been present for 24 hours",
      "The rule concerns new lesions, not the age of the last one."],
     ["When 21 days have elapsed since the exposure",
      "That is not the criterion given."],
     ["When the fever has been absent for 24 hours",
      "Fever is not the criterion used."]],
   c=0, cite=c(89)),

 dict(topic="Varicella", io=IOB, lead="next step",
   q="A patient with varicella is admitted to hospital. Which precautions are required?",
   opts=[
     ["Standard, airborne, and contact precautions",
      "Correct — all three are required."],
     ["Contact precautions alone, with no airborne component",
      "Airborne precautions are also required."],
     ["Droplet precautions alone",
      "The deck specifies airborne and contact, not droplet."],
     ["Standard precautions alone",
      "Airborne and contact precautions are added."]],
   c=0, cite=c(89)),

 dict(topic="Herpes zoster", io=IOC, lead="diagnosis",
   q="A 72-year-old has three days of burning pain in a band across the left side of his chest, followed by grouped vesicles on an erythematous base confined to that band. The eruption stops abruptly at the midline. Which is the most likely diagnosis?",
   opts=[
     ["Herpes zoster",
      "Correct — a dermatomal eruption that does not cross the midline."],
     ["Varicella",
      "Varicella is generalized with lesions in several stages at once."],
     ["Contact dermatitis",
      "In the differential, but it does not respect a dermatome."],
     ["Herpes simplex",
      "In the differential, but it does not follow a thoracic dermatome."]],
   c=0, cite=c(100)),

 dict(topic="Herpes zoster", io=IOB, lead="diagnosis",
   q="A 74-year-old has a dermatomal zoster eruption across the chest. Which dermatome is most frequently involved in herpes zoster, and what proportion of cases does it account for?",
   opts=[
     ["Thoracic, at 55%",
      "Correct — followed by cranial at 20%."],
     ["Cranial, at 55%",
      "Cranial accounts for 20%."],
     ["Lumbar, at 55%",
      "Lumbar accounts for 15%."],
     ["Sacral, at 55%",
      "Sacral accounts for 5%."]],
   c=0, cite=c(100)),

 dict(topic="Herpes zoster", io=IOB, lead="diagnosis",
   q="A 66-year-old woman has severe unilateral dermatomal pain but no rash at all. Which term does the lecture use for this?",
   opts=[
     ["Zoster sine herpete",
      "Correct — pain without the vesicular eruption."],
     ["Postherpetic neuralgia",
      "That is pain persisting 90 days or more after a rash has appeared."],
     ["Ramsay Hunt syndrome",
      "That is facial palsy with vesicles of the ear canal or oropharynx."],
     ["Herpes zoster ophthalmicus",
      "That involves the ophthalmic division of the trigeminal nerve."]],
   c=0, cite=c(99)),

 dict(topic="Herpes zoster", io=IOB, lead="education",
   q="A patient with acute herpes zoster asks how long he remains infectious. Which is the most appropriate response?",
   opts=[
     ["Until the lesions have dried",
      "Correct — infectious until the lesions dry."],
     ["Until the pain has resolved completely",
      "Pain may outlast infectivity by months."],
     ["For 21 days from the onset of the rash",
      "The deck ties it to drying of the lesions."],
     ["He was never infectious at any point",
      "Vesicular fluid can transmit varicella to a susceptible contact."]],
   c=0, cite=c(98)),

 dict(topic="Herpes zoster", io=IOB, lead="education",
   q="A grandfather with active shingles asks whether he can visit his daughter, who is 20 weeks pregnant and has no history of chickenpox. Which is the most appropriate response?",
   opts=[
     ["He should cover the lesions, avoid touching or scratching them, use hand hygiene, and avoid contact with susceptible pregnant people until the lesions are crusted",
      "Correct — she cannot catch shingles, but she could catch varicella."],
     ["He may visit freely and needs no precautions at all, because a susceptible contact cannot acquire anything whatever from a person with active shingles",
      "Exposure to vesicular fluid can cause varicella."],
     ["He should avoid all contact permanently, because shingles is directly transmissible as shingles between people",
      "A contact does not \"catch shingles\"; they may develop varicella."],
     ["He may visit provided he takes an oral antiviral that day, since treatment eliminates transmission immediately",
      "Antiviral therapy does not make him immediately non-infectious."]],
   c=0, cite=c(91)),

 dict(topic="Herpes zoster", io=IOB, lead="treatment",
   q="A 70-year-old presents 36 hours after the onset of a thoracic zoster rash. Which is the most appropriate treatment?",
   opts=[
     ["Start oral valacyclovir, famciclovir, or acyclovir as soon as possible",
      "Correct — ideally within 72 hours of rash onset."],
     ["Start a topical antiviral applied to the affected dermatome",
      "Topical antivirals are not the treatment for zoster."],
     ["Start an oral corticosteroid alone without any antiviral",
      "Steroids never replace antiviral therapy."],
     ["Observe without treatment, since the rash will resolve on its own",
      "Antiviral therapy is indicated within this window."]],
   c=0, cite=c(106)),

 dict(topic="Herpes zoster", io=IOB, lead="next step",
   q="A patient presents 5 days after the onset of a zoster rash, and new lesions are still forming. Which is the most appropriate next step?",
   opts=[
     ["Start antiviral therapy, because ongoing new lesion formation justifies treatment after 72 hours",
      "Correct — one of the named indications for late treatment."],
     ["Withhold antiviral therapy, because the 72-hour window has closed in every circumstance",
      "The window is not absolute when new lesions are forming."],
     ["Start a systemic corticosteroid alone, because antivirals are no longer of any use",
      "Steroids never replace antiviral therapy."],
     ["Start gabapentin alone, because the only remaining goal is preventing later neuralgia",
      "Antiviral therapy is still indicated here."]],
   c=0, cite=c(106)),

 dict(topic="Herpes zoster", io=IOB, lead="next step",
   q="A patient with zoster has severe disseminated disease with visceral involvement. Which is the most appropriate management?",
   opts=[
     ["Intravenous acyclovir with specialist or hospital management",
      "Correct — also for central nervous system or sight-threatening disease."],
     ["Oral valacyclovir at standard dose as an outpatient",
      "Severe disseminated disease needs intravenous therapy."],
     ["A systemic corticosteroid alone with close outpatient review",
      "Steroids never replace antiviral therapy."],
     ["Topical antiviral therapy with cool compresses and calamine",
      "Those are comfort measures, not treatment for severe disease."]],
   c=0, cite=c(106)),

 dict(topic="Herpes zoster", io=IOB, lead="treatment",
   q="A patient with acute zoster has mild pain. Which comfort measures does the lecture describe?",
   opts=[
     ["Acetaminophen or a non-steroidal anti-inflammatory drug, with cool compresses, calamine, loose clothing, and lesion coverage",
      "Correct — lesion coverage also reduces exposure of contacts."],
     ["A long-acting opioid from the outset, with warm compresses, occlusive dressings, tight clothing, and the lesions left uncovered",
      "None of these are the measures described."],
     ["A systemic corticosteroid from the outset, with cool compresses, calamine, and lesion coverage",
      "Steroids require individualized assessment and do not prevent neuralgia."],
     ["No analgesia at all, with cool compresses, calamine, loose clothing, and lesion coverage",
      "Analgesia is explicitly offered for mild pain."]],
   c=0, cite=c(107)),

 dict(topic="Herpes zoster", io=IOB, lead="test",
   q="A patient has an atypical, widespread vesicular eruption and is immunocompromised. Which test does the lecture prefer, and from what sample?",
   opts=[
     ["Polymerase chain reaction, from vesicle fluid, a scab, or cells from the lesion base",
      "Correct — preferred for atypical or immunocompromised presentations."],
     ["Serology for varicella-zoster immunoglobulin M, from a venous blood sample",
      "Serology is not the preferred test here."],
     ["Viral culture, from a swab of intact skin adjacent to the eruption",
      "Culture is not named as preferred, and the sample site is wrong."],
     ["Potassium hydroxide microscopy, from scale at the advancing border",
      "That test is for fungal elements."]],
   c=0, cite=c(105)),

 dict(topic="Herpes zoster", io=IOB, lead="diagnosis",
   q="A 63-year-old has a grouped vesicular eruption that is not clearly dermatomal. Which conditions does the lecture list in the differential diagnosis of herpes zoster?",
   opts=[
     ["Herpes simplex, contact dermatitis, impetigo, folliculitis, insect bites, and varicella",
      "Correct — dermatitis herpetiformis is on the list too, making seven named entities."],
     ["Psoriasis, nummular eczema, atopic dermatitis, discoid lupus, and fixed drug eruption",
      "That is the tinea corporis differential."],
     ["Basal cell carcinoma, sebaceous hyperplasia, and condyloma acuminatum",
      "That is the molluscum differential."],
     ["Folliculitis, psoriasis, seborrheic dermatitis, and alopecia areata",
      "That is the tinea capitis differential."]],
   c=0, cite=c(105)),

 dict(topic="Postherpetic neuralgia", io=IOC, lead="diagnosis",
   q="A 78-year-old had a thoracic zoster rash four months ago. The rash healed, but she has constant burning pain in the same area and cannot bear her shirt touching the skin. Which is the most likely diagnosis?",
   opts=[
     ["Postherpetic neuralgia",
      "Correct — pain persisting 90 days or more after rash onset, with allodynia."],
     ["Zoster sine herpete",
      "That is dermatomal pain without any rash having appeared."],
     ["Recurrent herpes zoster in the same dermatome",
      "The rash has healed; this is persisting pain, not a new eruption."],
     ["Ramsay Hunt syndrome",
      "That is facial palsy with vesicles of the ear canal or oropharynx."]],
   c=0, cite=c(102)),

 dict(topic="Postherpetic neuralgia", io=IOB, lead="treatment",
   q="A patient with postherpetic neuralgia needs pain control. Which is the most appropriate first-line option?",
   opts=[
     ["Gabapentin or pregabalin, an appropriate tricyclic antidepressant, or topical lidocaine",
      "Correct — a capsaicin patch may also help."],
     ["A long-acting opioid titrated to effect over several months, with a capsaicin patch",
      "The deck says to avoid routine long-term opioids."],
     ["A systemic corticosteroid tapered over three months",
      "Steroids do not prevent or treat this."],
     ["Continued antiviral therapy at a suppressive dose",
      "Antivirals do not treat established neuralgia."]],
   c=0, cite=c(109)),

 dict(topic="Postherpetic neuralgia", io=IOC, lead="next step",
   q="Before prescribing for an 84-year-old with postherpetic neuralgia, which factors does the lecture say to individualize for?",
   opts=[
     ["Kidney function, falls, anticholinergic burden, and drug interactions",
      "Correct — four named considerations."],
     ["Hepatic function, weight, dietary habits, and smoking history",
      "Those are not the factors listed here."],
     ["Cardiac function, blood pressure, exercise tolerance, and diet",
      "Those are not the factors listed here."],
     ["Immune status, vaccination history, and prior antiviral use",
      "Those matter for zoster itself, not for individualizing this therapy."]],
   c=0, cite=c(109)),

 dict(topic="Postherpetic neuralgia", io=IOB, lead="education",
   q="A patient asks whether taking a corticosteroid during his shingles rash would have prevented his current neuralgia. Which is the most appropriate response?",
   opts=[
     ["Topical and systemic corticosteroids do not prevent postherpetic neuralgia and should never replace antiviral therapy",
      "Correct — a common misconception the deck addresses directly."],
     ["Topical and systemic corticosteroids reliably prevent postherpetic neuralgia when given within 72 hours",
      "They do not prevent it."],
     ["Systemic corticosteroids prevent it, though topical ones do not, so it should have been offered",
      "Neither route prevents it."],
     ["Corticosteroids prevent it and may be given in place of antiviral therapy in mild disease",
      "They must never replace antiviral therapy."]],
   c=0, cite=c(107)),

 dict(topic="Herpes zoster ophthalmicus", io=IOB, lead="next step",
   q="A 68-year-old has a zoster eruption over the forehead and upper eyelid, with lesions on the tip of the nose. He reports eye pain and photophobia. Which is the most appropriate next step?",
   opts=[
     ["Start systemic antiviral therapy immediately and arrange same-day ophthalmology evaluation",
      "Correct — do not delay the antiviral while awaiting the eye review."],
     ["Arrange ophthalmology evaluation within two weeks and withhold antivirals until then",
      "Antiviral therapy starts immediately, and the review is same-day."],
     ["Start a topical antiviral eye ointment and review the patient in one week",
      "Systemic therapy is what is indicated."],
     ["Start a systemic corticosteroid alone and arrange same-day ophthalmology evaluation",
      "Steroids never replace antiviral therapy."]],
   c=0, cite=c(103)),

 dict(topic="Herpes zoster ophthalmicus", io=IOB, lead="diagnosis",
   q="A patient with forehead zoster has no lesions on the nose. What does that tell you about his risk of eye involvement?",
   opts=[
     ["Absence of the Hutchinson sign does not exclude eye involvement",
      "Correct — a negative sign is not reassuring."],
     ["Absence of the Hutchinson sign reliably excludes eye involvement",
      "The deck states the opposite explicitly."],
     ["Absence of the Hutchinson sign means ophthalmology review can wait two weeks",
      "Eye symptoms still prompt same-day review."],
     ["Absence of the Hutchinson sign confirms involvement of a different cranial nerve",
      "It confirms nothing about which nerve is involved."]],
   c=0, cite=c(103)),

 dict(topic="Ramsay Hunt syndrome", io=IOB, lead="diagnosis",
   q="A 59-year-old has right-sided facial droop, ear pain, and painful vesicles in the right external auditory canal. She also reports tinnitus and vertigo. Which is the most likely diagnosis?",
   opts=[
     ["Ramsay Hunt syndrome",
      "Correct — peripheral facial palsy with vesicles of the ear canal or auricle."],
     ["Herpes zoster ophthalmicus",
      "That involves the ophthalmic division of the trigeminal nerve."],
     ["Postherpetic neuralgia",
      "That is persisting pain after a healed rash, without palsy."],
     ["Herpetic whitlow",
      "That is a painful infection of the distal finger."]],
   c=0, cite=c(104)),

 dict(topic="Ramsay Hunt syndrome", io=IOB, lead="treatment",
   q="A patient is diagnosed with Ramsay Hunt syndrome and cannot fully close the right eye. Which is the most appropriate management?",
   opts=[
     ["Start antiviral therapy plus a systemic corticosteroid early when not contraindicated, arrange urgent ear, nose and throat or neurology evaluation, and protect the cornea",
      "Correct — corneal protection matters when eyelid closure is impaired."],
     ["Start antiviral therapy alone and arrange routine ear, nose and throat review in six weeks, with no specific eye care",
      "Corticosteroid, urgency, and corneal protection are all part of the plan."],
     ["Start a systemic corticosteroid alone and arrange urgent ear, nose and throat or neurology evaluation, with no antiviral therapy and no corneal protection",
      "Corticosteroid never replaces the antiviral."],
     ["Start antiviral therapy plus a systemic corticosteroid and arrange same-day ophthalmology evaluation for Hutchinson sign",
      "The Hutchinson sign belongs to zoster ophthalmicus, not this syndrome."]],
   c=0, cite=c(104)),

 dict(topic="Herpes zoster", io=IOC, lead="education",
   q="A healthy 55-year-old asks about the shingles vaccine. What should she be offered?",
   opts=[
     ["Two doses of recombinant zoster vaccine, at a standard interval of 2 to 6 months",
      "Correct — two doses for immunocompetent adults 50 and over."],
     ["One dose of recombinant zoster vaccine, with no second dose required",
      "Two doses are recommended."],
     ["Two doses of recombinant zoster vaccine, but only from the age of 65",
      "The threshold for immunocompetent adults is 50."],
     ["No vaccine, since she is under 65 and immunocompetent",
      "She is eligible at 50."]],
   c=0, cite=c(110)),

 dict(topic="Herpes zoster", io=IOC, lead="education",
   q="A 24-year-old is about to begin immunosuppressive therapy. What does the lecture recommend regarding zoster vaccination?",
   opts=[
     ["Two doses of recombinant zoster vaccine, since adults 19 and over who are or will be immunodeficient or immunosuppressed are eligible",
      "Correct — the \"or will be\" wording covers planned immunosuppression."],
     ["No vaccine at all until she reaches the age of 50, whatever her immune status turns out to be once treatment has started",
      "The age-19 threshold applies to this group."],
     ["One dose of recombinant zoster vaccine now, with a second dose only if zoster occurs",
      "Two doses are recommended."],
     ["Two doses of recombinant zoster vaccine, but only after the immunosuppression has been stopped",
      "The recommendation includes those who will be immunosuppressed."]],
   c=0, cite=c(110)),

 dict(topic="Herpes zoster", io=IOC, lead="next step",
   q="An immunocompromised patient has had the first dose of recombinant zoster vaccine and needs faster completion. What interval is permitted for the second dose?",
   opts=[
     ["1 to 2 months after the first dose",
      "Correct — a permitted shortening from the standard 2 to 6 months."],
     ["2 to 6 months after the first dose, with no shortening permitted",
      "That is the standard interval, which may be shortened here."],
     ["6 to 12 months after the first dose",
      "Longer than any interval given."],
     ["At least 12 months after the first dose",
      "No such interval appears in the deck."]],
   c=0, cite=c(110)),

 dict(topic="Herpes simplex virus", io=IOB, lead="diagnosis",
   q="A 24-year-old has a first episode of painful grouped vesicles on an erythematous base on the vulva, which have broken down into shallow ulcers. She has fever, headache and tender inguinal nodes. Which is the most likely diagnosis?",
   opts=[
     ["Herpes simplex virus infection",
      "Correct — grouped vesicles becoming shallow painful ulcers, with a systemic prodrome."],
     ["Primary syphilis",
      "The syphilitic lesion starts as a raised papule that erodes and is usually painless."],
     ["Chancroid ulceration",
      "Chancroid causes painful necrotizing ulcers rather than grouped vesicles."],
     ["Vulvovaginal candidiasis",
      "In the differential, but it does not produce grouped vesicles and ulcers."]],
   c=0, cite=c(119)),

 dict(topic="Herpes simplex virus", io=IOB, lead="test",
   q="A patient presents with a fresh genital vesicle. Which test does the lecture prefer?",
   opts=[
     ["Type-specific nucleic acid amplification testing from the vesicle",
      "Correct — swab a fresh vesicle, ulcer base, or crust."],
     ["Viral culture from the vesicle, because it is the most sensitive test",
      "Culture is less sensitive, especially in healing or recurrent lesions."],
     ["Type-specific serology drawn during the acute episode",
      "Serology has selected uses but is not preferred here."],
     ["Herpes simplex immunoglobulin M from a venous sample",
      "The deck says not to use immunoglobulin M."]],
   c=0, cite=c(122)),

 dict(topic="Herpes simplex virus", io=IOB, lead="treatment",
   q="A patient has a confirmed first clinical episode of genital herpes simplex. Which is the most appropriate treatment?",
   opts=[
     ["Oral acyclovir, valacyclovir, or famciclovir",
      "Correct — treat every first clinical episode."],
     ["A topical antiviral applied to the lesions",
      "Topical antivirals provide minimal benefit for genital herpes."],
     ["An oral antibiotic with supportive care only",
      "The infection is viral."],
     ["Observation alone, reserving treatment for recurrences",
      "Every first clinical episode is treated."]],
   c=0, cite=c(124)),

 dict(topic="Herpes simplex virus", io=IOB, lead="education",
   q="A patient with recurrent genital herpes simplex asks how to reduce the risk of infecting his partner. Which is the most appropriate response?",
   opts=[
     ["Suppressive valacyclovir lowers transmission and condoms reduce risk, but neither eliminates it; avoid contact during the prodrome and while lesions are active",
      "Correct — risk is reduced, never abolished."],
     ["Suppressive valacyclovir eliminates transmission entirely, so no other precaution is needed once it is started",
      "Transmission risk is lowered, not eliminated."],
     ["Condoms eliminate transmission entirely, so antiviral therapy adds nothing for a patient who uses them",
      "Condoms reduce but do not eliminate risk."],
     ["Neither suppressive antivirals nor condoms affect transmission at all, so the only option available is to avoid sexual contact permanently",
      "Both measures do reduce risk."]],
   c=0, cite=c(124)),

 dict(topic="Herpetic whitlow", io=IOB, lead="diagnosis",
   q="A 31-year-old dental hygienist has a painful, swollen, erythematous index fingertip with grouped vesicles. She had burning and tingling in the finger the day before. Which is the most likely diagnosis?",
   opts=[
     ["Herpetic whitlow",
      "Correct — a prodrome followed by grouped vesicles on a swollen digit."],
     ["Bacterial felon",
      "A mimic, but it does not produce grouped vesicles after a burning prodrome."],
     ["Contact dermatitis",
      "A mimic, but it would not follow a tingling prodrome in one digit."],
     ["Onychomycosis",
      "That is a chronic nail disease, not an acute painful eruption."]],
   c=0, cite=c(126)),

 dict(topic="Herpetic whitlow", io=IOB, lead="next step",
   q="A colleague suggests incising and draining the swollen fingertip of a patient with herpetic whitlow. Which is the most appropriate response?",
   opts=[
     ["Do not incise and drain it, because that does not treat the virus and can delay healing",
      "Correct — explicitly contraindicated."],
     ["Incise and drain it, because decompression shortens the course of the infection",
      "Incision is exactly what the deck forbids."],
     ["Incise and drain it, but only after 72 hours of oral antiviral therapy have failed",
      "Incision is not indicated at any point."],
     ["Do not incise and drain it, because the lesion is sterile and will resolve within 24 hours",
      "The reasoning is wrong even though the conclusion is right."]],
   c=0, cite=c(128)),

 dict(topic="Molluscum contagiosum", io=IOC, lead="diagnosis",
   q="A 4-year-old has about fifteen discrete, smooth, firm, flesh-coloured dome-shaped pearly papules on the trunk, each 3 to 5 millimetres with a dimple in the centre. They are asymptomatic. Which is the most likely diagnosis?",
   opts=[
     ["Molluscum contagiosum",
      "Correct — central umbilication is characteristic."],
     ["Verruca vulgaris",
      "Common warts are rough and grayish, without central umbilication."],
     ["Varicella",
      "Varicella gives vesicles and crusts in multiple stages, with fever."],
     ["Sebaceous hyperplasia",
      "In the differential, but it does not present as crops in a young child."]],
   c=0, cite=c(134)),

 dict(topic="Molluscum contagiosum", io=IOC, lead="education",
   q="The parents of a child with molluscum contagiosum want it treated immediately. Which is the most appropriate response?",
   opts=[
     ["Observation is appropriate for many patients, because most clear spontaneously and procedures may blister, pigment, or scar",
      "Correct — although resolution may take months to years."],
     ["Immediate destruction of every lesion is required, because untreated molluscum progresses to malignancy",
      "No malignant potential is described."],
     ["Observation is appropriate, because the lesions always resolve within two to three weeks without treatment",
      "Resolution may take months to several years."],
     ["Immediate oral antiviral therapy is required, because the lesions will otherwise spread to the whole family",
      "Oral antivirals are not used for molluscum."]],
   c=0, cite=c(136)),

 dict(topic="Molluscum contagiosum", io=IOC, lead="treatment",
   q="The parents of a 3-year-old with molluscum want a treatment they can apply at home. Which approved option fits?",
   opts=[
     ["Berdazimer 10.3% gel, once daily, approved from age 1 year",
      "Correct — the at-home option."],
     ["Cantharidin 0.7%, once daily, approved from age 1 year",
      "Cantharidin is applied by a clinician, from age 2."],
     ["Salicylic acid 40%, once daily, approved from age 2 years",
      "That is a wart treatment."],
     ["Topical retinoid, once daily, approved from age 3 years",
      "Topical retinoids are off label for molluscum."]],
   c=0, cite=c(136)),

 dict(topic="Molluscum contagiosum", io=IOB, lead="next step",
   q="A 35-year-old man has extensive giant molluscum lesions across the face. Which is the most appropriate next step?",
   opts=[
     ["Evaluate for immunosuppression, including human immunodeficiency virus when appropriate",
      "Correct — extensive or atypical disease raises this question."],
     ["Reassure him that facial lesions resolve within weeks and arrange no follow-up",
      "Extensive facial disease warrants evaluation."],
     ["Excise every lesion surgically under general anaesthesia at the first visit",
      "Not the response described in the deck."],
     ["Start an oral antifungal, since extensive facial lesions suggest a dermatophyte",
      "Molluscum is a poxvirus infection."]],
   c=0, cite=c(133)),

 dict(topic="Molluscum contagiosum", io=IOC, lead="next step",
   q="A 6-year-old girl has molluscum lesions in the genital area. Which is the most appropriate approach?",
   opts=[
     ["Context-sensitive assessment, because location alone does not prove abuse",
      "Correct — the deck is deliberate about this."],
     ["Immediate mandatory reporting on the basis of the lesion location alone",
      "Location alone does not prove abuse."],
     ["No assessment at all, because genital molluscum is expected in young children",
      "Careful assessment is called for."],
     ["Screening for sexually transmitted infections in every case as the sole action",
      "That is the approach for adolescents and adults."]],
   c=0, cite=c(133)),

 dict(topic="Warts", io=IOC, lead="diagnosis",
   q="A 12-year-old has several elevated, round, less than 1-centimetre papules with a rough greyish surface on his fingers. Trimming the surface reveals tiny red-black dots. Which is the most likely diagnosis, and what are the dots?",
   opts=[
     ["Verruca vulgaris, and the dots are thrombosed dilated capillaries",
      "Correct — trimming makes the capillaries more prominent."],
     ["Molluscum contagiosum, and the dots are impacted keratin plugs",
      "Molluscum papules are smooth and pearly with central umbilication."],
     ["Seborrheic keratosis, and the dots are melanin deposits within the lesion",
      "In the differential, but the capillary dots point to a wart."],
     ["Verruca plana, and the dots are thrombosed dilated capillaries",
      "Flat warts are smooth and flat-topped, not rough and elevated."]],
   c=0, cite=c(142)),

 dict(topic="Warts", io=IOC, lead="diagnosis",
   q="A 16-year-old has multiple smooth, slightly elevated, flat-topped, light-brown papules on her forehead and shins. She shaves her legs. Which is the most likely diagnosis, and what is spreading them?",
   opts=[
     ["Verruca plana, spread by autoinoculation during shaving",
      "Correct — shaving spreads flat warts."],
     ["Verruca vulgaris, spread by autoinoculation during shaving",
      "Common warts are rough, elevated and greyish."],
     ["Molluscum contagiosum, spread by autoinoculation during shaving",
      "Molluscum papules are umbilicated and pearly."],
     ["Verruca plantaris, spread by walking barefoot in communal areas",
      "Plantar warts sit on weight-bearing surfaces of the feet."]],
   c=0, cite=c(143)),

 dict(topic="Warts", io=IOB, lead="treatment",
   q="A 30-year-old runner has a painful plantar wart on the ball of the foot. Which treatments does the lecture give?",
   opts=[
     ["Salicylic acid 40% or cryotherapy",
      "Correct — the two named options for plantar warts."],
     ["Cantharidin 0.7% or curettage",
      "Those are molluscum treatments."],
     ["Berdazimer 10.3% gel or a topical retinoid",
      "Those are molluscum treatments."],
     ["Oral terbinafine or topical ciclopirox",
      "Those are antifungals."]],
   c=0, cite=c(146)),

 dict(topic="Warts", io=IOB, lead="next step",
   q="A patient has an asymptomatic plantar wart found incidentally. Which is the most appropriate approach?",
   opts=[
     ["No therapy is required, since plantar warts need treatment only when painful",
      "Correct — and many warts resolve spontaneously."],
     ["Cryotherapy every two to three weeks until the lesion has fully resolved",
      "Treatment is reserved for painful lesions."],
     ["Immediate surgical excision to prevent it clustering into a mosaic wart",
      "Excision is not the described approach."],
     ["Salicylic acid 40% daily for twelve weeks in every patient found to have one",
      "Treatment is not required unless the wart is painful."]],
   c=0, cite=c(145)),

 dict(topic="Warts", io=IOB, lead="next step",
   q="A 62-year-old has a wart-like lesion on the dorsal hand that has been growing, bleeding, and has not responded to salicylic acid. Which is the most appropriate next step?",
   opts=[
     ["Biopsy or refer, since bleeding, growing and refractory lesions warrant it",
      "Correct — squamous cell carcinoma is in the differential."],
     ["Repeat the same salicylic acid course for a further twelve weeks",
      "Refractory disease is a reason to biopsy or refer."],
     ["Add a topical corticosteroid to reduce the bleeding and inflammation",
      "That does not address the concern."],
     ["Reassure the patient, since bleeding is expected in a resolving wart",
      "Bleeding is a named referral criterion."]],
   c=0, cite=c(148)),

 dict(topic="Warts", io=IOB, lead="education",
   q="A patient asks whether cryotherapy will cure her human papillomavirus infection. Which is the most appropriate response?",
   opts=[
     ["No therapy eradicates the virus with certainty, and recurrence can occur",
      "Correct — set expectations before starting treatment."],
     ["Cryotherapy eradicates the virus reliably, so recurrence will not occur",
      "No therapy eradicates it with certainty."],
     ["Salicylic acid eradicates the virus reliably, though cryotherapy does not",
      "Neither eradicates it with certainty."],
     ["Only surgical excision eradicates the virus, so it should be arranged now",
      "Excision is not offered as curative here."]],
   c=0, cite=c(149)),

 dict(topic="Warts", io=IOC, lead="next step",
   q="A pregnant patient has several periungual warts that have failed initial treatment. Which is the most appropriate next step?",
   opts=[
     ["Refer, since periungual, extensive, recalcitrant, and pregnancy-affected cases warrant it",
      "Correct — periungual and recalcitrant lesions are both on the referral list."],
     ["Apply aggressive cryotherapy every week until the lesions have cleared",
      "The deck warns against excessive destructive therapy."],
     ["Start an oral antiviral, since human papillomavirus responds to systemic therapy",
      "No oral antiviral is described for warts."],
     ["Observe indefinitely, since periungual warts always resolve during pregnancy",
      "Referral is the described route for these features."]],
   c=0, cite=c(149)),

 dict(topic="Warts", io=IOB, lead="education",
   q="A patient with a few small asymptomatic common warts asks for aggressive freezing to remove them quickly. Which is the most appropriate response?",
   opts=[
     ["Avoid excessive freezing or destructive therapy for benign lesions likely to resolve spontaneously",
      "Correct — weigh the harms against a self-limiting lesion."],
     ["Aggressive freezing is appropriate, because it eradicates the virus and prevents recurrence",
      "No therapy eradicates the virus with certainty."],
     ["Aggressive freezing is appropriate, because common warts do not resolve without treatment",
      "Spontaneous resolution is the natural history."],
     ["Avoid freezing entirely, because cryotherapy is never an appropriate wart treatment",
      "Cryotherapy is a listed option; the caution is against excess."]],
   c=0, cite=c(149)),
]
