# -*- coding: utf-8 -*-
"""Lecture 24 objective pool C -- Coronary Artery Disease: catheterization and
revascularization, post-infarction care and sudden cardiac death, vasospastic
angina, microvascular angina.

KEYS ARE WRITTEN SHORT ON PURPOSE -- detail lives in the explanation.

Set 1 is recall against the syllabus objectives, so no stem carries a patient
age. Slides are the only content source; the recording only weights (the
"words have meaning" procedure terms, the six-week dual antiplatelet coin flip,
beta blockers yes / calcium channel blockers no, the vasospastic gold
standard). The slide wins over his spoken slips: coronary artery bypass uses an
ARTERY first; vasospastic angina avoids NONSELECTIVE beta blockers. Vasospastic
electrocardiogram items key only transient ST elevation during an episode.
Dual antiplatelet durations are not keyed. Scope caps live in
cms_e4l24_scope.py.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _cmse3_q import Q
from cms_e4l24_scope import *


def S(topic, io, q, opts, cite, slot):
    d = Q(topic, io, q, opts, cite); d["slot"] = slot; return d


QUESTIONS = [

# ---------------------------------------------------------------- catheterization and revascularization
S(T_REV, IO_ACS,
  "Which procedure uses dye to identify a coronary lesion or blockage?",
  [["Coronary angiography",
    "Correct. Coronary angiography sprays contrast dye into the coronary arteries and takes pictures to identify the lesion. The catheter is the access; the angiography is the picture of the blockage."],
   ["Left heart catheterization",
    "Left heart catheterization is the introduction of a guidewire to reach the heart chambers and coronary arteries. It is the access route; the dye study that shows the lesion is coronary angiography."],
   ["Plain old balloon angioplasty",
    "Plain old balloon angioplasty opens a narrowed artery with a balloon and leaves no stent. It treats a lesion already found; dye to identify the lesion is coronary angiography."],
   ["Atherectomy",
    "Atherectomy physically removes coronary atheroma, calcium and excess cellular material during an intervention. It does not identify the lesion; coronary angiography does that with dye."]],
  C(50), "initial test"),

S(T_REV, IO_ACS,
  "Besides dual antiplatelet therapy, which drug belongs to medical optimization after a stent?",
  [["A statin",
    "Correct. Medical optimization after stent placement is dual antiplatelet therapy, a statin, an angiotensin-converting enzyme inhibitor, and anticoagulation only if indicated."],
   ["Routine anticoagulation",
    "Anticoagulation after a stent is given only if indicated, not routinely. The fixed parts of optimization are dual antiplatelet therapy, a statin and an angiotensin-converting enzyme inhibitor."],
   ["A calcium channel blocker",
    "Calcium channel blockers are not on the post-stent list and do not improve prognosis overall after infarction. The list is dual antiplatelet therapy, a statin and an angiotensin-converting enzyme inhibitor."],
   ["Intravenous nitroglycerin",
    "Intravenous nitrates belong to the initial treatment of unstable angina and non-ST-elevation infarction. After a stent, optimization adds a statin and an angiotensin-converting enzyme inhibitor to dual antiplatelet therapy."]],
  C(52), "agent/regimen"),

S(T_REV, IO_ACS,
  "What does plain old balloon angioplasty leave out that percutaneous coronary intervention includes?",
  [["A stent",
    "Correct. Plain old balloon angioplasty opens a narrowed artery without using a stent. Percutaneous coronary intervention places a drug-eluting or non-drug-eluting stent to keep the artery open."],
   ["A balloon",
    "The balloon is the whole of plain old balloon angioplasty: it dilates the narrowed vessel. What the procedure leaves out is the stent that percutaneous coronary intervention places."],
   ["A guidewire",
    "Both procedures begin with catheterization, the introduction of a guidewire into the heart and coronary arteries. The difference is the stent, which only the intervention leaves behind."],
   ["Contrast dye",
    "Both procedures rely on angiography, dye that identifies the lesion. What balloon angioplasty alone leaves out is the stent that keeps the artery open after the balloon is removed."]],
  C(50, 51), "differential"),

S(T_REV, IO_ACS,
  "Which term describes passing a guidewire into the heart chambers and coronary arteries?",
  [["Left heart catheterization",
    "Correct. Left heart catheterization is the introduction of a guidewire and access to the chambers of the heart and the coronary arteries. The terms are not interchangeable: the catheter is the access."],
   ["Coronary angiography",
    "Coronary angiography is the dye study done once access is gained: contrast is injected to identify the lesion. The guidewire access itself is the left heart catheterization."],
   ["Coronary angioplasty",
    "Coronary angioplasty uses a device to balloon open a narrowed artery. It follows access and angiography; the guidewire access itself is called left heart catheterization."],
   ["Coronary artery bypass",
    "Coronary artery bypass grafting is open surgery that sews an artery or vein beyond the blockage. Passing a guidewire into the heart is left heart catheterization."]],
  C(50), "differential"),

S(T_REV, IO_ACS,
  "During percutaneous coronary intervention, what is atherectomy?",
  [["Removal of plaque material",
    "Correct. Atherectomy is the physical removal of coronary atheroma, calcium and excess cellular material. It is one of the three things a patient can undergo during the intervention, with balloon angioplasty and stenting."],
   ["Balloon dilation of the vessel",
    "Balloon dilation of the occluded vessel is balloon angioplasty. Atherectomy is different: it physically removes atheroma, calcium and excess cellular material from the artery."],
   ["Placement of a mesh stent",
    "Stent placement, usually after balloon pre-dilation, is a separate step. Atherectomy is the physical removal of coronary atheroma, calcium and excess cellular material."],
   ["Injection of contrast dye",
    "Injecting dye to identify the lesion is coronary angiography, the diagnostic step. Atherectomy is therapeutic: it physically removes atheroma, calcium and excess cellular material."]],
  C(69), "escalation"),

S(T_REV, IO_ACS,
  "When is a stent usually placed during percutaneous coronary intervention?",
  [["After balloon pre-dilation",
    "Correct. The stent is usually placed after balloon pre-dilation of the narrowed segment. Direct stenting, without pre-dilation, may lead to better outcomes, so the order is not absolute."],
   ["Before any guidewire is passed",
    "Nothing can be placed before access: the guidewire of the catheterization comes first. The stent then usually follows balloon pre-dilation of the narrowed segment."],
   ["Only after a failed atherectomy",
    "Atherectomy is an option during the intervention, not a gate the stent must wait for. The stent is usually placed after balloon pre-dilation, and direct stenting may do better."],
   ["Only after bypass grafting",
    "Bypass grafting is open surgery, an alternative to a stent rather than a step before one. During the intervention the stent usually follows balloon pre-dilation."]],
  C(69, 70), "agent/regimen"),

S(T_REV, IO_ACS,
  "Dual antiplatelet therapy after a stent pairs aspirin with which drug class?",
  [["A P2Y12 receptor antagonist",
    "Correct. Dual antiplatelet therapy after stent placement is a P2Y12 receptor antagonist such as clopidogrel plus a cyclooxygenase inhibitor, aspirin, alongside a statin and an angiotensin-converting enzyme inhibitor."],
   ["A vitamin K antagonist",
    "Warfarin, a vitamin K antagonist, is an anticoagulant rather than an antiplatelet drug; it is added only when indicated. The antiplatelet partner of aspirin is a P2Y12 receptor antagonist."],
   ["A glycoprotein 2b/3a inhibitor",
    "Glycoprotein 2b/3a inhibitors such as eptifibatide have fallen out of favor. The second antiplatelet drug paired with aspirin after a stent is a P2Y12 receptor antagonist such as clopidogrel."],
   ["A direct thrombin inhibitor",
    "Direct thrombin inhibitors such as bivalirudin are anticoagulants, not antiplatelet drugs. The partner of aspirin in dual antiplatelet therapy is a P2Y12 receptor antagonist."]],
  C(52), "agent/regimen"),

S(T_REV, IO_ACS,
  "Missing dual antiplatelet doses in the first 6 weeks after a stent carries what risk of sudden in-stent restenosis?",
  [["About 50%",
    "Correct. Noncompliance with dual antiplatelet therapy in the first 6 weeks carries a 50% risk of sudden in-stent restenosis, a coin flip. Patients are taught that they have to take these medications."],
   ["About 5%",
    "The risk is far higher than one in twenty. Stopping dual antiplatelet therapy in the first 6 weeks gives about a 50% risk of sudden in-stent restenosis, which is why adherence is stressed."],
   ["About 20%",
    "One in five understates it. Noncompliance in the first 6 weeks carries about a 50% risk of sudden in-stent restenosis, the coin flip that makes adherence the key teaching point."],
   ["Close to 100%",
    "Restenosis is not certain. Noncompliance in the first 6 weeks gives about a 50% risk, a coin flip, which is still high enough that taking every dose is the central instruction."]],
  C(52), "education"),

S(T_REV, IO_ACS,
  "Which antithrombotic class has fallen out of favor in coronary care?",
  [["Glycoprotein 2b/3a inhibitors",
    "Correct. Glycoprotein 2b/3a inhibitors (eptifibatide, abciximab, tirofiban) have fallen out of favor. Aspirin with a P2Y12 receptor antagonist is the antiplatelet pairing in use."],
   ["P2Y12 receptor antagonists",
    "P2Y12 receptor antagonists such as clopidogrel remain central: they are half of dual antiplatelet therapy after a stent. The class that has fallen out of favor is the glycoprotein 2b/3a inhibitors."],
   ["Cyclooxygenase inhibitors",
    "Aspirin, the cyclooxygenase inhibitor, is still recommended after infarction and forms the other half of dual antiplatelet therapy. Glycoprotein 2b/3a inhibitors are the class that has fallen out of favor."],
   ["Fibrinolytic agents",
    "Fibrinolytics are still given when the nearest intervention unit is 2 or more hours away, and tenecteplase is the most common today. Glycoprotein 2b/3a inhibitors are the class out of favor."]],
  C(74), "avoid"),

S(T_REV, IO_ACS,
  "Which conduit is used first in coronary artery bypass grafting?",
  [["A mammary or radial artery",
    "Correct. Bypass grafting anastomoses one or both mammary arteries, or a radial artery, to the coronary artery distal to the obstruction. A vein is used only when an artery cannot be."],
   ["The great saphenous vein",
    "The great saphenous vein is the usual vein, but a vein is used only if an artery cannot bypass the obstruction. The first conduit is a mammary or radial artery."],
   ["The femoral vein",
    "The femoral vein is not a bypass conduit. Grafting uses one or both mammary arteries or a radial artery first, and the great saphenous vein only when an artery cannot be used."],
   ["A synthetic tube graft",
    "A synthetic tube is not the conduit used. Coronary bypass anastomoses a mammary or radial artery beyond the lesion, falling back to the great saphenous vein if needed."]],
  C(76, 77), "escalation"),

S(T_REV, IO_ACS,
  "When a vein is used for coronary bypass, what does it connect?",
  [["The aorta and the coronary beyond the block",
    "Correct. A vein graft, usually the great saphenous vein, forms a connection between the aorta and the coronary artery distal to the obstruction. It is used when an artery cannot be."],
   ["The coronary artery and the coronary sinus",
    "Joining a coronary artery to the coronary sinus would send blood straight into the venous return. A vein graft runs from the aorta to the coronary artery distal to the obstruction."],
   ["The pulmonary artery and the coronary artery",
    "The pulmonary artery carries deoxygenated blood and is never a graft source. A vein graft carries aortic blood to the coronary artery distal to the obstruction."],
   ["The two ends of the blocked segment only",
    "A vein graft does not simply bridge the plaque from end to end. It forms a connection between the aorta and the coronary artery beyond the obstruction."]],
  C(76), "agent/regimen"),

# ---------------------------------------------------------------- post-infarction care and sudden cardiac death
S(T_POST, IO_AMI,
  "Which drug class improves survival across the board after a myocardial infarction?",
  [["Beta blockers",
    "Correct. Beta blockers improve survival rates across the board after infarction. Calcium channel blockers, by contrast, do not improve prognosis overall."],
   ["Calcium channel blockers",
    "Calcium channel blockers do not improve prognosis overall after infarction; only diltiazem and verapamil reduce mortality, and only with preserved left ventricular function. Beta blockers improve survival across the board."],
   ["Long-acting nitrates",
    "Nitrates relieve anginal pain but are not the class that improves survival after infarction. Beta blockers improve survival rates across the board."],
   ["Glycoprotein 2b/3a inhibitors",
    "Glycoprotein 2b/3a inhibitors have fallen out of favor and are not post-infarction survival drugs. Beta blockers are the class that improves survival across the board."]],
  C(80), "prognosis"),

S(T_POST, IO_AMI,
  "After infarction, diltiazem and verapamil reduce mortality only in which patients?",
  [["Preserved left ventricular function",
    "Correct. Calcium channel blockers do not improve prognosis overall after infarction, but diltiazem and verapamil reduce mortality rates in patients with preserved left ventricular function."],
   ["Reduced left ventricular function",
    "Reduced left ventricular function is the indication for an angiotensin-converting enzyme inhibitor, to prevent dilation and heart failure. Diltiazem and verapamil help only when function is preserved."],
   ["A right ventricular infarct",
    "A right ventricular infarct is preload dependent, and its key rule is to withhold nitroglycerin. The mortality benefit of diltiazem and verapamil is limited to preserved left ventricular function."],
   ["Cardiogenic shock",
    "Cardiogenic shock is a complication, more common after left-sided infarcts, not a group that benefits from calcium channel blockers. The benefit is limited to preserved left ventricular function."]],
  C(80), "agent/regimen"),

S(T_POST, IO_ACS,
  "Which patients with an acute coronary syndrome should receive high-intensity statin therapy?",
  [["All of them",
    "Correct. High-intensity statin therapy (atorvastatin or rosuvastatin) is for all patients with an acute coronary syndrome, regardless of the baseline low-density lipoprotein cholesterol."],
   ["Only high cholesterol",
    "The baseline cholesterol does not decide it. Every patient with an acute coronary syndrome receives a high-intensity statin regardless of the baseline low-density lipoprotein level."],
   ["Only diabetics",
    "Diabetes is a risk factor but not the gate for statin therapy here. All patients with an acute coronary syndrome receive a high-intensity statin, whatever their lipid levels."],
   ["Only after a second event",
    "Statin therapy is not held for a recurrence. It is started for every acute coronary syndrome, at high intensity, and instituted before hospital discharge."]],
  C(81), "first-line"),

S(T_POST, IO_ACS,
  "When should high-intensity statin therapy start after an acute coronary syndrome?",
  [["Before hospital discharge",
    "Correct. High-intensity statin therapy should be instituted prior to hospital discharge, for every patient with an acute coronary syndrome and regardless of the baseline cholesterol."],
   ["At the first clinic visit",
    "Waiting for the first outpatient visit delays it. The high-intensity statin is started before the patient leaves the hospital after an acute coronary syndrome."],
   ["After lipids are rechecked",
    "No lipid result is needed first: the statin is given regardless of the baseline low-density lipoprotein. It is started before hospital discharge."],
   ["After cardiac rehab ends",
    "Statin therapy is not deferred until rehabilitation is complete. It is instituted before hospital discharge in every acute coronary syndrome."]],
  C(81), "agent/regimen"),

S(T_POST, IO_AMI,
  "After infarction, angiotensin-converting enzyme inhibitors are especially indicated for which patients?",
  [["Reduced left ventricular function",
    "Correct. Angiotensin-converting enzyme inhibitors reduce myocardial remodeling (scarring) and are indicated with reduced left ventricular function to prevent dilation and heart failure; most patients go home on one."],
   ["Vasospastic angina",
    "Vasospastic angina is treated first-line with calcium channel blockers, plus smoking cessation. The post-infarction indication for an angiotensin-converting enzyme inhibitor is reduced left ventricular function."],
   ["Right ventricular infarct",
    "The defining rule in a right ventricular infarct is to withhold nitroglycerin because the ventricle is preload dependent. Angiotensin-converting enzyme inhibitors target reduced left ventricular function."],
   ["Bradycardia after infarction",
    "Bradycardia is the reason to hold a beta blocker in acute infarction. Angiotensin-converting enzyme inhibitors are indicated for reduced left ventricular function, to prevent dilation."]],
  C(82), "first-line"),

S(T_POST, IO_AMI,
  "After which infarct is warfarin recommended?",
  [["A large anterior wall infarct",
    "Correct. Warfarin is recommended after large anterior wall myocardial infarctions. Aspirin is recommended for all, and clopidogrel is necessary for patients who have had a stent."],
   ["A minor inferior infarct",
    "A minor inferior infarct is not the stated indication. Warfarin is recommended in patients with large anterior wall myocardial infarctions, alongside aspirin."],
   ["Any non-ST-elevation infarct",
    "A non-ST-elevation infarction is treated like unstable angina, with dual antiplatelet therapy and anticoagulation only if indicated. Warfarin is recommended after large anterior wall infarcts."],
   ["A vasospastic episode",
    "Vasospasm is treated with calcium channel blockers and nitrates, and it is not an infarct indication for warfarin. Warfarin is recommended after large anterior wall infarctions."]],
  C(83), "agent/regimen"),

S(T_POST, IO_AMI,
  "Cardiogenic shock after infarction is more common with which infarcts?",
  [["Left-sided infarcts",
    "Correct. Cardiogenic shock is a mechanical complication of myocardial infarction that is more common in left-sided infarcts, in keeping with left ventricular involvement carrying the higher mortality."],
   ["Right-sided infarcts",
    "Right-sided infarcts can tip into shock if preload is dropped, for example with nitroglycerin, but cardiogenic shock as a complication is more common in left-sided infarcts."],
   ["Silent infarcts",
    "Silent ischemia describes absent chest discomfort, as in diabetes or neuropathy; it says nothing about shock risk. Cardiogenic shock is more common in left-sided infarcts."],
   ["Vasospastic episodes",
    "Vasospastic episodes are transient and resolve, usually within 5 to 15 minutes, in arteries without high-grade stenosis. Cardiogenic shock is more common after left-sided infarcts."]],
  C(78, 12), "complication"),

S(T_POST, IO_AMI,
  "Pericarditis after a myocardial infarction is known as which syndrome?",
  [["Dressler syndrome",
    "Correct. Pericarditis after infarction is Dressler syndrome, one of the mechanical complications alongside heart failure, rupture, ventricular aneurysm, thromboembolism and cardiogenic shock."],
   ["Cardiac syndrome X",
    "Cardiac syndrome X is the former name of microvascular angina: angina with normal coronary arteries on angiography. Post-infarction pericarditis is Dressler syndrome."],
   ["Marfan syndrome",
    "Marfan syndrome is a connective tissue disorder of the aorta, not a complication of infarction. Pericarditis after a myocardial infarction is Dressler syndrome."],
   ["Brugada syndrome",
    "Brugada syndrome is an inherited electrical disorder, not a post-infarction complication. Pericarditis after a myocardial infarction is called Dressler syndrome."]],
  C(78), "complication"),

S(T_POST, IO_AMI,
  "What is the most common cause of sudden cardiac death?",
  [["Ventricular fibrillation",
    "Correct. Ventricular fibrillation is the most common cause of sudden cardiac death. Other causes include left ventricular hypertrophy, hypertrophic cardiomyopathy, hypoxia and electrolyte abnormalities."],
   ["Complete heart block",
    "Complete heart block follows injury to the atrioventricular node, supplied by the right coronary artery, and is a dysrhythmia of infarction. The most common cause of sudden death is ventricular fibrillation."],
   ["Hypertrophic cardiomyopathy",
    "Hypertrophic cardiomyopathy is one of the other causes of sudden cardiac death, but not the most common. Ventricular fibrillation is the most common cause."],
   ["Electrolyte abnormalities",
    "Electrolyte abnormalities are among the other causes, with hypoxia and left ventricular hypertrophy. The single most common cause of sudden cardiac death is ventricular fibrillation."]],
  C(85), "etiology"),

S(T_POST, IO_AMI,
  "In what share of patients is sudden cardiac death the first manifestation of coronary artery disease?",
  [["Over 20%",
    "Correct. Sudden cardiac death is the initial manifestation of coronary artery disease in over 20% of patients, roughly one in five, with ventricular fibrillation the most common cause."],
   ["Under 1%",
    "Far from rare, sudden death is the first sign of coronary artery disease in over 20% of patients, about one in five, most often from ventricular fibrillation."],
   ["About 5%",
    "The figure is higher than one in twenty. Sudden cardiac death is the initial manifestation of coronary artery disease in over 20% of patients."],
   ["Over 90%",
    "Most patients do present with other forms of the disease first, such as angina. Sudden cardiac death is the initial manifestation in over 20%, about one in five."]],
  C(85), "epidemiology"),

S(T_POST, IO_AMI,
  "Which belongs to risk-factor control after a myocardial infarction?",
  [["Smoking cessation",
    "Correct. Post-infarction management identifies and controls risk factors: blood pressure, lipid and glucose control, weight loss, alcohol restriction, exercise, smoking cessation and stress management."],
   ["Strict bed rest",
    "Prolonged bed rest is not part of post-infarction risk-factor control; exercise is. The list includes smoking cessation, weight loss, alcohol restriction and stress management."],
   ["Home oxygen for all",
    "Oxygen is given only when saturation is below 91%, and it is not part of long-term risk-factor control. Smoking cessation, exercise and weight loss are."],
   ["Stopping all exercise",
    "Exercise is part of the risk-factor control list after infarction, not something to stop. Smoking cessation, weight loss and blood pressure, lipid and glucose control round it out."]],
  C(79), "education"),

# ---------------------------------------------------------------- vasospastic angina
S(T_VSA, IO_VSA,
  "Vasospastic angina typically occurs under which circumstance?",
  [["At rest",
    "Correct. Vasospastic angina occurs at rest, from coronary artery vasospasm in normal or diseased arteries, and responds to nitroglycerin. Most patients have their pain between midnight and early morning."],
   ["During exertion",
    "Pain brought on by exertion and relieved by rest is stable angina. Vasospastic angina is the opposite pattern: it occurs at rest, often between midnight and early morning."],
   ["After a large meal",
    "A meal is not the trigger. Vasospastic angina occurs at rest, caused by coronary spasm, and drugs such as cocaine, amphetamine or triptans may precipitate it."],
   ["With deep breathing",
    "Pain that changes with breathing or position points away from cardiac ischemia. Vasospastic angina occurs at rest and responds to nitroglycerin."]],
  C(88), "manifestation"),

S(T_VSA, IO_VSA,
  "What is the major risk factor for vasospastic angina?",
  [["Cigarette smoking",
    "Correct. Cigarette smoking is a major risk factor for vasospastic angina, and stopping smoking is the first line of its treatment, alongside nitrates for symptoms and calcium channel blockers."],
   ["Hypertension",
    "Hypertension is a modifiable risk factor for atherosclerotic coronary artery disease. For vasospastic angina, the major named risk factor is cigarette smoking."],
   ["Obesity",
    "Obesity is a modifiable risk factor for atherosclerotic coronary artery disease, not the named driver of vasospasm. Cigarette smoking is the major risk factor for vasospastic angina."],
   ["Diabetes mellitus",
    "Diabetes is a coronary artery disease risk factor and a cause of silent ischemia. The major risk factor named for vasospastic angina is cigarette smoking."]],
  C(89), "risk factors"),

S(T_VSA, IO_VSA,
  "Which drug can precipitate vasospastic angina?",
  [["Cocaine",
    "Correct. Drugs that may precipitate vasospastic angina are cocaine, ephedrine, marijuana, alcohol, amphetamine and triptans. Triptans are also on the list of drugs to avoid in the condition."],
   ["Diltiazem",
    "Diltiazem is a calcium channel blocker, the first-line therapy for vasospastic angina, so it prevents rather than precipitates spasm. Cocaine is a precipitant."],
   ["Amlodipine",
    "Amlodipine is a calcium channel blocker used first-line in vasospastic angina. The precipitating drugs include cocaine, ephedrine, marijuana, alcohol, amphetamine and triptans."],
   ["Nitroglycerin",
    "Vasospastic angina responds to nitroglycerin, and nitrates are its symptomatic treatment. Cocaine, amphetamine and triptans are among the drugs that precipitate it."]],
  C(89, 92), "etiology"),

S(T_VSA, IO_VSA,
  "When do vasospastic angina episodes most often occur?",
  [["Overnight, before dawn",
    "Correct. Most patients with vasospastic angina have pain from midnight to early morning, more often between midnight and 8 in the morning, at rest, coming on and off gradually over 5 to 15 minutes."],
   ["Late afternoon",
    "Late afternoon is not the pattern. Vasospastic episodes occur at rest and most often between midnight and 8 in the morning."],
   ["Right after lunch",
    "A post-meal timing is not described. Vasospastic angina most often strikes between midnight and early morning, at rest."],
   ["During exercise",
    "Exertional timing belongs to stable angina. Vasospastic pain occurs at rest, most often from midnight to early morning."]],
  C(89, 90), "manifestation"),

S(T_VSA, IO_VSA,
  "What does an electrocardiogram show during a vasospastic angina episode?",
  [["Transient ST elevation",
    "Correct. Vasospastic angina shows transient ST-segment elevation on the electrocardiogram at the time of an episode, ischemic changes in multiple leads that resolve, usually within 15 minutes."],
   ["Persistent Q waves",
    "Pathologic Q waves mark an infarction that has already happened and they persist. Vasospasm causes transient ST elevation during the episode that resolves afterward."],
   ["A new left bundle block",
    "A new left bundle branch block is treated as an ST-elevation infarction equivalent. Vasospasm instead produces transient ST elevation at the time of the episode."],
   ["Fixed ST elevation",
    "Fixed, persisting ST elevation belongs with an evolving ST-elevation infarction. In vasospastic angina the ST elevation is transient and resolves after the episode."]],
  C(90), "test finding"),

S(T_VSA, IO_VSA,
  "Which test is the gold standard for vasospastic angina?",
  [["Provoked spasm at angiography",
    "Correct. The gold standard is coronary artery spasm during angiography when ergonovine or acetylcholine is delivered, then resolved with nitroglycerin given through the catheter."],
   ["Exercise treadmill test",
    "Vasospasm occurs at rest, so an exertional test does not reproduce it. The gold standard is spasm provoked at angiography with ergonovine or acetylcholine."],
   ["Nuclear stress test",
    "A nuclear stress test separates reversible from fixed perfusion defects in atherosclerotic disease. The gold standard for vasospasm is spasm provoked at angiography."],
   ["Coronary calcium score",
    "A calcium score is for risk stratification, not for acute disease or spasm. The gold standard for vasospastic angina is provoked spasm at coronary angiography."]],
  C(91), "gold standard"),

S(T_VSA, IO_VSA,
  "Which agent is delivered at angiography to provoke coronary spasm?",
  [["Ergonovine",
    "Correct. Ergonovine or acetylcholine is delivered during angiography; coronary spasm that then resolves with nitroglycerin through the catheter is the gold standard for vasospastic angina."],
   ["Nitroglycerin",
    "Nitroglycerin is what relieves the provoked spasm through the catheter, and vasospasm responds to it. The provoking agent is ergonovine or acetylcholine."],
   ["Diltiazem",
    "Diltiazem is a calcium channel blocker, first-line to prevent vasospasm, so it would blunt rather than provoke spasm. Ergonovine or acetylcholine provokes it."],
   ["Amlodipine",
    "Amlodipine is a first-line calcium channel blocker for vasospastic angina, used to prevent spasm. The agent given to provoke it at angiography is ergonovine or acetylcholine."]],
  C(91), "initial test"),

S(T_VSA, IO_VSA,
  "What is the first-line drug therapy for vasospastic angina?",
  [["Calcium channel blockers",
    "Correct. First-line therapy for vasospastic angina is a calcium channel blocker such as diltiazem or amlodipine, with smoking cessation and nitrates for symptoms."],
   ["Nonselective beta blockers",
    "Nonselective beta blockers are on the avoid list for vasospastic angina, with aspirin and triptans. First-line therapy is a calcium channel blocker."],
   ["Daily aspirin",
    "Aspirin is to be avoided in vasospastic angina, although it is standard in atherosclerotic disease. First-line therapy is a calcium channel blocker such as diltiazem."],
   ["Triptans",
    "Triptans can precipitate vasospasm and are to be avoided. First-line therapy for vasospastic angina is a calcium channel blocker such as diltiazem or amlodipine."]],
  C(92), "first-line"),

S(T_VSA, IO_VSA,
  "Which drug class should be avoided in vasospastic angina?",
  [["Nonselective beta blockers",
    "Correct. Nonselective beta blockers are avoided in vasospastic angina, along with aspirin and triptans. Calcium channel blockers are the first-line therapy instead."],
   ["Calcium channel blockers",
    "Calcium channel blockers such as diltiazem and amlodipine are the first-line therapy for vasospastic angina, not a class to avoid. Nonselective beta blockers are avoided."],
   ["Sublingual nitroglycerin",
    "Vasospastic angina responds to nitroglycerin, and nitrates are used for symptoms. The class to avoid is nonselective beta blockers, with aspirin and triptans."],
   ["Diltiazem",
    "Diltiazem is a first-line calcium channel blocker for vasospastic angina. Nonselective beta blockers, aspirin and triptans are the drugs to avoid."]],
  C(92), "avoid"),

S(T_VSA, IO_D,
  "Vasospastic angina most often affects which age group?",
  [["Often under 50",
    "Correct. Vasospastic angina is relatively uncommon and often affects people under 50, younger than the typical patient with atherosclerotic coronary artery disease."],
   ["Often over 70",
    "An older group is the typical atherosclerotic picture, with risk starting at 45 in men and 55 in women. Vasospastic angina is often seen under 50."],
   ["Mainly infants",
    "No pediatric pattern is described for vasospasm. Vasospastic angina is an adult condition, often in patients under 50, with smoking as a major risk factor."],
   ["Mostly over 80",
    "By 80 the sex gap in atherosclerotic risk has narrowed, but that is not vasospasm. Vasospastic angina is often seen in patients under 50."]],
  C(88), "epidemiology"),

S(T_VSA, IO_VSA,
  "What does coronary arteriography typically show in vasospastic angina?",
  [["No high-grade stenosis",
    "Correct. Coronary arteriography shows no high-grade coronary stenoses in vasospastic angina: the arteries spasm shut but are not blocked, and the spasm may occur in normal or diseased vessels."],
   ["Multivessel occlusion",
    "Multivessel occlusion is severe atherosclerotic disease. In vasospastic angina the arteries show no high-grade stenosis; the problem is spasm."],
   ["A ruptured plaque",
    "Plaque rupture with thrombus drives the acute coronary syndromes. Vasospastic angina shows no high-grade stenosis at arteriography."],
   ["Left main narrowing",
    "Fixed left main disease is atherosclerotic. In vasospastic angina, coronary arteriography shows no high-grade stenoses."]],
  C(88, 90), "test finding"),

# ---------------------------------------------------------------- microvascular angina
S(T_MVA, IO_ANG,
  "Microvascular angina was formerly called what?",
  [["Cardiac syndrome X",
    "Correct. Microvascular angina was formerly called cardiac syndrome X: angina with ST changes, possibly elevated biomarkers, but normal coronary arteries on angiography."],
   ["Prinzmetal angina",
    "Prinzmetal angina is another name for vasospastic, or variant, angina: coronary spasm at rest. Microvascular angina was formerly called cardiac syndrome X."],
   ["Dressler syndrome",
    "Dressler syndrome is pericarditis after a myocardial infarction. The former name of microvascular angina is cardiac syndrome X."],
   ["Stable ischemic disease",
    "Stable ischemic heart disease is the other name for stable angina, the most common form. Microvascular angina was formerly called cardiac syndrome X."]],
  C(93), "differential"),

S(T_MVA, IO_ANG,
  "What does coronary angiography show in microvascular angina?",
  [["Normal coronary arteries",
    "Correct. Microvascular angina is angina with ST changes, possibly even elevated cardiac biomarkers, but normal coronary arteries on the angiogram."],
   ["A single occluded vessel",
    "An occluded epicardial artery is atherosclerotic coronary artery disease. In microvascular angina, the angiogram shows normal coronary arteries."],
   ["Provoked coronary spasm",
    "Spasm provoked by ergonovine or acetylcholine is the gold standard for vasospastic angina. In microvascular angina the coronary arteries look normal."],
   ["Left main narrowing",
    "Left main narrowing is obstructive atherosclerotic disease. Microvascular angina is defined by normal coronary arteries on angiography."]],
  C(94), "test finding"),

S(T_MVA, IO_D,
  "Microvascular angina is more frequent in which group?",
  [["Women",
    "Correct. Microvascular angina is more frequent in females and is often associated with stress or anxiety; estrogen deficiency is among its proposed mechanisms."],
   ["Men",
    "Male sex is a nonmodifiable risk factor for atherosclerotic coronary artery disease. Microvascular angina is more frequent in females, often with stress or anxiety."],
   ["Children",
    "No pediatric pattern is described. Microvascular angina is more frequent in adult females and is often associated with stress or anxiety."],
   ["Smokers",
    "Smoking is the major risk factor for vasospastic angina. Microvascular angina is more frequent in females, often associated with stress or anxiety."]],
  C(94), "epidemiology"),

S(T_MVA, IO_ANG,
  "How is microvascular angina diagnosed?",
  [["By exclusion",
    "Correct. Microvascular angina is a diagnosis of exclusion and requires angiography to rule out coronary artery disease; the angiogram shows normal coronary arteries."],
   ["By troponin alone",
    "Biomarkers may be elevated, but a troponin result cannot make the diagnosis. Microvascular angina is a diagnosis of exclusion after angiography rules out coronary artery disease."],
   ["By calcium score",
    "A calcium score is a risk-stratification tool, not a diagnostic test for angina. Microvascular angina is diagnosed by exclusion, with angiography to rule out coronary artery disease."],
   ["By provoked spasm",
    "Spasm provoked at angiography diagnoses vasospastic angina. Microvascular angina is a diagnosis of exclusion once angiography has ruled out coronary artery disease."]],
  C(94), "initial test"),

S(T_MVA, IO_ANG,
  "Which is a proposed mechanism of microvascular angina?",
  [["Endothelial dysfunction",
    "Correct. Proposed mechanisms of microvascular angina include endothelial dysfunction, myocardial ischemia, insulin resistance or diabetes, abnormal autonomic control, altered cardiac sensitivity, estrogen deficiency and altered pain perception."],
   ["Plaque rupture",
    "Plaque rupture with platelet activation and thrombus drives the acute coronary syndromes. Endothelial dysfunction is a proposed mechanism of microvascular angina."],
   ["Aortic valve narrowing",
    "Aortic valve narrowing is a valvular cause of angina, not a microvascular mechanism. Endothelial dysfunction and estrogen deficiency are proposed mechanisms."],
   ["Complete heart block",
    "Complete heart block is a conduction problem tied to the right coronary artery's supply of the atrioventricular node. Endothelial dysfunction is a proposed microvascular mechanism."]],
  C(95), "etiology"),

S(T_MVA, IO_ANG,
  "How is microvascular angina treated?",
  [["Much like coronary artery disease",
    "Correct. Treatment is very similar to coronary artery disease: lifestyle modification and risk-factor reduction, a calcium channel blocker, beta blockers, an angiotensin-converting enzyme inhibitor and a statin."],
   ["With urgent bypass grafting",
    "The coronary arteries are normal on angiography, so there is nothing to bypass. Treatment mirrors coronary artery disease: risk-factor reduction, calcium channel blocker, beta blocker, statin."],
   ["With fibrinolytic drugs",
    "Fibrinolytics dissolve clot in an ST-elevation infarction when intervention is far away. Microvascular angina is treated much like coronary artery disease, with risk-factor reduction and medications."],
   ["With no therapy at all",
    "It is treated, not ignored: lifestyle and risk-factor reduction, a calcium channel blocker, beta blockers, an angiotensin-converting enzyme inhibitor and a statin, much as in coronary artery disease."]],
  C(96), "first-line"),

]
