# CMS I Lecture 3 (Dermatology II) — SET 1 pool A (objective style).
# Erythema multiforme, dermatitis herpetiformis, acanthosis nigricans,
# epidermolysis bullosa, urticaria.
#
# WRITTEN WITH MATCHED OPTION LENGTHS. The Lecture 2 pools came out 66%
# length-gameable and took four remediation rounds, because the correct answers
# were enumerations and the distractors were single clauses. Here every option
# in a question is drafted to roughly the same length as it is written, which is
# the actual fix -- remediation afterwards is repair, not design.
#
# Correct answer is ALWAYS written first (c=0); the partition script rotates.
SRC = "3. Dermatology  II.pptx"
def c(n): return f"{SRC}, Slide {n}"

IOA = "a — Etiologies, manifestations, diagnosis and management of dermatological conditions"

POOL_A = [
 dict(topic="Erythema multiforme", io=IOA,
   q="What triggers the majority of erythema multiforme cases?",
   opts=[
     ["Herpes simplex virus, accounting for over 50% of cases",
      "Correct. Other infectious causes include Mycoplasma pneumoniae, histoplasmosis, Epstein-Barr virus and coxsackievirus."],
     ["Sulfonamide antibiotics, accounting for over 50% of cases",
      "Drugs including sulfonamides are triggers, but they are far from the majority."],
     ["Mycoplasma pneumoniae, accounting for over 50% of cases",
      "Mycoplasma is a recognised infectious trigger but not the leading one."],
     ["Idiopathic causes, accounting for over 50% of cases",
      "Idiopathic causes account for roughly 10% of cases."]],
   c=0, cite=c(8)),

 dict(topic="Erythema multiforme", io=IOA,
   q="How is the classic erythema multiforme target lesion described?",
   opts=[
     ["Three concentric zones: a central dusky or necrotic area, a pale oedematous ring, and an outer erythematous halo",
      "Correct, and the lesions are distributed symmetrically on acral surfaces — palms, soles and dorsal hands."],
     ["Two concentric zones: a central pale area surrounded by a single wide erythematous ring",
      "The classic lesion has three zones, not two, and the centre is dusky rather than pale."],
     ["A single uniform erythematous plaque with a raised advancing border and central clearing",
      "That describes an annular lesion such as tinea corporis rather than a target."],
     ["Grouped vesicles on an erythematous base following a single dermatome",
      "That describes herpes zoster rather than erythema multiforme."]],
   c=0, cite=c(9)),

 dict(topic="Erythema multiforme", io=IOA,
   q="What distinguishes erythema multiforme minor from erythema multiforme major?",
   opts=[
     ["Minor involves skin only; major involves two or more mucosal surfaces",
      "Correct. Erythema multiforme minor constitutes the majority of cases."],
     ["Minor lasts under one week; major lasts more than one month",
      "Lesions evolve over one to two weeks in both and the disease is self-limited."],
     ["Minor is drug-triggered; major is triggered by herpes simplex virus",
      "Both forms share the same trigger list, with herpes simplex predominating."],
     ["Minor occurs in children; major occurs only in adults over forty",
      "Peak occurrence for both is in adults aged twenty to forty."]],
   c=0, cite=c(9)),

 dict(topic="Erythema multiforme", io=IOA,
   q="What does direct immunofluorescence show in erythema multiforme, and why does it matter?",
   opts=[
     ["It is negative, which distinguishes erythema multiforme from pemphigoid and pemphigus",
      "Correct. Biopsy shows interface dermatitis with vacuolar degeneration of the basal layer and necrotic keratinocytes."],
     ["It shows granular immunoglobulin A in the dermal papillae, confirming the diagnosis",
      "That finding is the gold standard for dermatitis herpetiformis instead."],
     ["It shows linear immunoglobulin G at the basement membrane zone, confirming the diagnosis",
      "That pattern indicates bullous pemphigoid."],
     ["It shows intercellular immunoglobulin G throughout the epidermis, confirming the diagnosis",
      "That pattern indicates pemphigus."]],
   c=0, cite=c(11)),

 dict(topic="Erythema multiforme", io=IOA,
   q="What is used for suppressive therapy in recurrent herpes-associated erythema multiforme?",
   opts=[
     ["Acyclovir 400 mg twice daily or valacyclovir 500 mg daily",
      "Correct. Dapsone or hydroxychloroquine are used for refractory non-herpes recurrent disease."],
     ["Dapsone 25 to 200 mg daily with regular monitoring of the blood count",
      "Dapsone is reserved for refractory recurrent disease that is not herpes-associated."],
     ["Hydroxychloroquine 200 mg twice daily taken indefinitely",
      "Hydroxychloroquine is also reserved for refractory non-herpes recurrent disease."],
     ["Prednisone 40 to 60 mg daily for five days at each recurrence",
      "A short steroid course is used in some acute settings rather than as suppression."]],
   c=0, cite=c(12)),

 dict(topic="Dermatitis herpetiformis", io=IOA,
   q="What is the underlying mechanism of dermatitis herpetiformis?",
   opts=[
     ["Immunoglobulin A antibodies against epidermal transglutaminase, depositing in the dermal papillae",
      "Correct, in genetically susceptible individuals consuming gluten, producing subepidermal blisters."],
     ["Immunoglobulin G antibodies against the epithelial basement membrane zone",
      "That mechanism produces bullous pemphigoid."],
     ["Immunoglobulin G antibodies against keratinocyte adhesion molecules",
      "That mechanism produces pemphigus."],
     ["Immunoglobulin E mediated mast cell degranulation with histamine release",
      "That mechanism produces urticaria."]],
   c=0, cite=c(16)),

 dict(topic="Dermatitis herpetiformis", io=IOA,
   q="Which haplotypes are strongly associated with dermatitis herpetiformis?",
   opts=[
     ["HLA-DQ2 and HLA-DQ8",
      "Correct, and nearly all patients have underlying gluten-sensitive enteropathy even when gastrointestinally asymptomatic."],
     ["HLA-B*15:02 and HLA-B*58:01",
      "Those are the pharmacogenomic risk alleles for Stevens-Johnson syndrome."],
     ["HLA-Cw6 and HLA-B27",
      "Those are associated with psoriasis and psoriatic arthritis."],
     ["HLA-A31 and HLA-BW35",
      "Those are the suggested susceptibility haplotypes for granuloma annulare."]],
   c=0, cite=c(16)),

 dict(topic="Dermatitis herpetiformis", io=IOA,
   q="Which test is the gold standard for diagnosing dermatitis herpetiformis?",
   opts=[
     ["Perilesional skin biopsy with direct immunofluorescence showing granular immunoglobulin A in the dermal papillae",
      "Correct. Immunoglobulin A anti-epidermal transglutaminase is the most specific serological test."],
     ["Lesional skin biopsy with haematoxylin and eosin showing subepidermal blistering with neutrophils",
      "Histology supports the diagnosis but the immunofluorescence pattern is what settles it."],
     ["Serum immunoglobulin A anti-tissue transglutaminase with anti-endomysial antibodies",
      "These serologies support the diagnosis but are not the gold standard."],
     ["Small bowel biopsy demonstrating villous atrophy consistent with coeliac disease",
      "Up to 90% show villous atrophy, but that confirms coeliac disease rather than the skin diagnosis."]],
   c=0, cite=c(18)),

 dict(topic="Dermatitis herpetiformis", io=IOA,
   q="What must be checked before starting dapsone for dermatitis herpetiformis?",
   opts=[
     ["Glucose-6-phosphate dehydrogenase status",
      "Correct, and the blood count is then monitored for haemolytic anaemia and methaemoglobinaemia."],
     ["Thyroid-stimulating hormone and anti-thyroid peroxidase antibodies",
      "Autoimmune thyroid disease is an association but is not the pre-treatment check."],
     ["Serum immunoglobulin A level to exclude selective deficiency",
      "This affects serological interpretation rather than dapsone safety."],
     ["HLA-DQ2 and HLA-DQ8 typing to confirm susceptibility",
      "Typing is used when serology is equivocal rather than before dapsone."]],
   c=0, cite=c(19)),

 dict(topic="Dermatitis herpetiformis", io=IOA,
   q="What is the cornerstone of long-term management in dermatitis herpetiformis?",
   opts=[
     ["A strict lifelong gluten-free diet",
      "Correct, and it may allow dapsone to be reduced or stopped over one to two years."],
     ["Indefinite daily dapsone at the lowest effective dose",
      "Dapsone gives rapid relief but the diet is the long-term cornerstone."],
     ["Long-term high-potency topical corticosteroids to affected sites",
      "Topical steroids are used for localised flares only."],
     ["Sulfapyridine taken indefinitely in place of dietary change",
      "Sulfapyridine is an alternative for patients intolerant of dapsone."]],
   c=0, cite=c(19)),

 dict(topic="Acanthosis nigricans", io=IOA,
   q="What mechanism underlies the most common form of acanthosis nigricans?",
   opts=[
     ["Hyperinsulinaemia stimulating keratinocyte and fibroblast proliferation through insulin-like growth factor 1 receptor cross-activation",
      "Correct — the insulin-resistant or benign form is the commonest."],
     ["A paraneoplastic process driven by an underlying gastric adenocarcinoma",
      "Malignant acanthosis nigricans is rare, at under 1% of cases."],
     ["A delayed type IV hypersensitivity reaction to a contacted allergen",
      "That mechanism produces allergic contact dermatitis."],
     ["Autoantibody deposition along the epithelial basement membrane zone",
      "That mechanism produces bullous pemphigoid."]],
   c=0, cite=c(22)),

 dict(topic="Acanthosis nigricans", io=IOA,
   q="Which features suggest malignant rather than benign acanthosis nigricans?",
   opts=[
     ["Rapid onset, extensive involvement, oral mucosal change and tripe palms",
      "Correct — malignant disease is paraneoplastic, especially with gastric adenocarcinoma."],
     ["Gradual onset over years confined to the posterior neck and axillae",
      "That is the pattern of the common insulin-resistant form."],
     ["Velvety hyperpigmented plaques appearing only in the inframammary folds",
      "Fold involvement is typical of the benign form."],
     ["Lesions that wipe away completely with an isopropyl alcohol swab",
      "That describes terra firma-forme dermatosis, a differential."]],
   c=0, cite=c(23)),

 dict(topic="Acanthosis nigricans", io=IOA,
   q="Which laboratory tests evaluate the commonest cause of acanthosis nigricans?",
   opts=[
     ["Fasting glucose, haemoglobin A1c, fasting insulin and HOMA-IR",
      "Correct — these assess insulin resistance, with a lipid panel and body measurements for metabolic syndrome."],
     ["Serum protein electrophoresis with antinuclear and antineutrophil antibodies",
      "That panel screens for the associations of pyoderma gangrenosum."],
     ["Antistreptolysin O titre, chest radiograph and interferon gamma release assay",
      "That panel investigates the triggers of erythema nodosum."],
     ["Serum tryptase, complement C4 and C1-esterase inhibitor function",
      "That panel investigates urticaria and angio-oedema."]],
   c=0, cite=c(24)),

 dict(topic="Acanthosis nigricans", io=IOA,
   q="Which counselling point is emphasised for acanthosis nigricans?",
   opts=[
     ["It is a metabolic warning sign rather than a hygiene problem, and 5 to 10% weight loss improves the findings",
      "Correct — the hygiene misconception is specifically addressed."],
     ["It is a benign cosmetic change that carries no systemic implication at all",
      "It is a visible marker of insulin resistance and sometimes of malignancy."],
     ["It responds fully to topical antifungal therapy within several weeks",
      "That would treat tinea versicolor, one of the differentials."],
     ["It resolves spontaneously in most patients without any intervention",
      "It reflects an underlying process that must itself be treated."]],
   c=0, cite=c(25)),

 dict(topic="Epidermolysis bullosa", io=IOA,
   q="Which type of epidermolysis bullosa is most common, and what is its cleavage level?",
   opts=[
     ["Epidermolysis bullosa simplex, at about 70% of cases, with intraepidermal cleavage",
      "Correct — it results from keratin 5 and 14 mutations and is autosomal dominant."],
     ["Junctional epidermolysis bullosa, at about 70% of cases, with cleavage in the lamina lucida",
      "Junctional disease carries the highest mortality but is not the commonest."],
     ["Dystrophic epidermolysis bullosa, at about 70% of cases, with sub-lamina densa cleavage",
      "Dystrophic disease arises from COL7A1 mutations but is not the commonest."],
     ["Kindler epidermolysis bullosa, at about 70% of cases, with mixed cleavage planes",
      "Kindler disease is rare and arises from FERMT1 mutation."]],
   c=0, cite=c(29)),

 dict(topic="Epidermolysis bullosa", io=IOA,
   q="Which epidermolysis bullosa subtype carries the highest mortality?",
   opts=[
     ["Junctional epidermolysis bullosa, especially the Herlitz subtype",
      "Correct, which is why early palliative care integration is appropriate in severe Herlitz disease."],
     ["Epidermolysis bullosa simplex, especially the localised palmoplantar form",
      "Simplex disease is localised to palms and soles and heals without scarring."],
     ["Dystrophic epidermolysis bullosa, especially the dominant form",
      "Dystrophic disease causes severe scarring and squamous cell carcinoma risk rather than the highest mortality."],
     ["Epidermolysis bullosa acquisita, the autoimmune acquired form",
      "This acquired form is autoimmune rather than genetic and is not the highest-mortality type."]],
   c=0, cite=c(29)),

 dict(topic="Epidermolysis bullosa", io=IOA,
   q="What is the gold standard test for determining the cleavage plane in epidermolysis bullosa?",
   opts=[
     ["Skin biopsy with transmission electron microscopy",
      "Correct, with immunofluorescence antigen mapping used to localise missing or reduced proteins."],
     ["Skin biopsy with direct immunofluorescence for immunoglobulin G",
      "That distinguishes acquired autoimmune blistering disease rather than mapping the cleavage plane."],
     ["Genetic testing of the known structural protein genes",
      "Genetic testing is confirmatory and guides prognosis and counselling."],
     ["Serum enzyme-linked immunosorbent assay for structural protein antibodies",
      "Inherited epidermolysis bullosa is not antibody-mediated."]],
   c=0, cite=c(31)),

 dict(topic="Epidermolysis bullosa", io=IOA,
   q="Which surveillance is required in recessive dystrophic epidermolysis bullosa?",
   opts=[
     ["Annual squamous cell carcinoma surveillance after the age of ten",
      "Correct — the severe scarring of dystrophic disease carries squamous cell carcinoma risk."],
     ["Annual colonoscopy from the age of ten to detect bowel involvement",
      "Endoscopy is used if oesophageal stricture is suspected rather than for cancer surveillance."],
     ["Annual echocardiography to monitor for cardiomyopathy",
      "This is not among the described surveillance requirements."],
     ["Annual bone density scanning to monitor for osteoporosis",
      "This is not among the described surveillance requirements."]],
   c=0, cite=c(31)),

 dict(topic="Epidermolysis bullosa", io=IOA,
   q="What is beremagene geperpavec?",
   opts=[
     ["A topical gene therapy gel approved in 2023 for dystrophic epidermolysis bullosa",
      "Correct, accessible through dermatology referral centres and gene therapy trials."],
     ["A monoclonal antibody given intravenously for junctional epidermolysis bullosa",
      "It is a topical gene therapy rather than an antibody."],
     ["An oral small molecule that restores keratin 5 and 14 function",
      "It is a topical gel and does not act on keratin genes."],
     ["A non-adherent biological dressing designed for fragile skin",
      "Mepitel and Mepilex are the dressings described; this is a gene therapy."]],
   c=0, cite=c(31)),

 dict(topic="Urticaria", io=IOA,
   q="What single feature most reliably separates urticaria from its differentials?",
   opts=[
     ["Individual lesions last less than twenty-four hours",
      "Correct — this is called the key diagnostic feature, and lesions persisting beyond it suggest urticarial vasculitis."],
     ["Individual lesions are intensely pruritic and blanch under pressure",
      "Both are typical of urticaria but neither separates it from the differentials as reliably."],
     ["Lesions appear symmetrically on the palms and soles",
      "That acral distribution is characteristic of erythema multiforme."],
     ["Lesions leave residual bruising as they resolve",
      "Residual bruising suggests urticarial vasculitis rather than simple urticaria."]],
   c=0, cite=c(37)),

 dict(topic="Urticaria", io=IOA,
   q="How are acute and chronic urticaria distinguished, and how common is chronic disease?",
   opts=[
     ["Acute lasts under six weeks; chronic exceeds six weeks and affects 0.5 to 1% of the population",
      "Correct. Lifetime prevalence of urticaria overall is 15 to 25%."],
     ["Acute lasts under twenty-four hours; chronic exceeds twenty-four hours in any single lesion",
      "That interval describes individual lesion duration, not the acute-chronic division."],
     ["Acute lasts under two weeks; chronic exceeds two weeks and affects 15 to 25% of people",
      "Six weeks is the dividing line, and 15 to 25% is the lifetime prevalence of urticaria overall."],
     ["Acute is immunoglobulin E mediated; chronic is always autoimmune in origin",
      "Over half of chronic urticaria is idiopathic rather than autoimmune."]],
   c=0, cite=c(36)),

 dict(topic="Urticaria", io=IOA,
   q="Which finding should prompt a search for hereditary angio-oedema?",
   opts=[
     ["Recurrent angio-oedema occurring without any wheals",
      "Correct — check complement C4 and C1-esterase inhibitor level and function."],
     ["Wheals that persist beyond twenty-four hours and leave bruising",
      "That picture suggests urticarial vasculitis, investigated by biopsy."],
     ["Wheals accompanied by Darier's sign and an elevated tryptase",
      "That combination suggests mastocytosis."],
     ["Wheals appearing only after exposure to cold or vibration",
      "That indicates a physical urticaria rather than hereditary angio-oedema."]],
   c=0, cite=c(38)),

 dict(topic="Urticaria", io=IOA,
   q="What is first-line treatment for urticaria?",
   opts=[
     ["Second-generation antihistamines such as cetirizine, loratadine or fexofenadine",
      "Correct, and in chronic disease these can be scheduled at up to four times the standard dose."],
     ["A short course of oral prednisone at 40 to 60 mg for five days",
      "That is reserved for severe acute urticaria rather than used first line."],
     ["Omalizumab given as 300 mg subcutaneously every four weeks",
      "Omalizumab is approved for refractory chronic urticaria."],
     ["Cyclosporine titrated to response with monitoring of renal function",
      "Cyclosporine is reserved for refractory autoimmune urticaria."]],
   c=0, cite=c(39)),

 dict(topic="Urticaria", io=IOA,
   q="Which biologic is approved for refractory chronic urticaria?",
   opts=[
     ["Omalizumab, an anti-immunoglobulin E antibody given every four weeks",
      "Correct, at 300 mg subcutaneously."],
     ["Infliximab, a tumour necrosis factor alpha inhibitor given intravenously",
      "Infliximab is approved for pyoderma gangrenosum in inflammatory bowel disease."],
     ["Dupilumab, an interleukin-4 receptor antagonist given subcutaneously",
      "Dupilumab has been reported in refractory granuloma annulare rather than approved here."],
     ["Etanercept, a tumour necrosis factor inhibitor given subcutaneously",
      "Etanercept is described as an emerging adjunct in Stevens-Johnson syndrome."]],
   c=0, cite=c(39)),
]
