# -*- coding: utf-8 -*-
"""CMS I Exam 3, Lecture 17 -- objective set B.

The septum, epistaxis, nasal trauma and foreign bodies, polyps, rhinitis and
the neoplasms.

Grounded in the deck (Prof. Hugh Griffenkranz, 3 September 2026).
SELF-CONTAINED. FIVE options; correct answer authored FIRST.
"""
D = "hughie Nose & Paranasal Sinuses fall 2026.pptx, Slide %d"
IO_A = ("a — Nose and paranasal sinus disorders: etiologies, epidemiology, risk factors, clinical "
        "manifestations, differential diagnosis, diagnostic testing, management, referrals, "
        "patient education, prognosis")
IO_B = ("b — Identify medical care strategies for nose and paranasal sinus disorders by "
        "population: adolescent, adult, elderly")

QUESTIONS = [
 dict(topic="Deviated septum", io=IO_A, lead="defining feature", cite=D % 32,
  q="What defines a deviated septum?",
  opts=[["The septum is displaced to one side, making one passage smaller", "Correct."],
        ["A hole through the septum", "That is a perforated septum."],
        ["Blood between septum and perichondrium", "That is a septal haematoma."],
        ["Loss of the septal cartilage entirely", "Deviation displaces the cartilage; it does not destroy it."],
        ["Inflammation of the septal mucosa", "That is rhinitis, not a structural deviation."]]),

 dict(topic="Deviated septum", io=IO_A, lead="clinical manifestation", cite=D % 32,
  q="Which findings occur in severe deviated septum?",
  opts=[["Obstructive sleep apnoea, snoring, facial pain and recurrent nosebleeds", "Correct."],
        ["Fever and purulent discharge", "Those suggest infection."],
        ["Bilateral clear discharge", "That suggests allergic rhinitis."],
        ["Anosmia alone with no other feature", "Anosmia can occur, but the severe picture is broader."],
        ["A neck mass", "That suggests nasopharyngeal carcinoma."]]),

 dict(topic="Deviated septum", io=IO_A, lead="treatment", cite=D % 32,
  q="What is the treatment for a symptomatic deviated septum?",
  opts=[["Septoplasty", "Correct, performed by an otorhinolaryngologist."],
        ["Long-term intranasal steroids", "They do not straighten the septum."],
        ["Nasal packing", "That treats bleeding."],
        ["Antibiotics", "There is no infection to treat."],
        ["Antihistamines", "They do not address the anatomy."]]),

 dict(topic="Perforated septum", io=IO_A, lead="etiology", cite=D % 37,
  q="Which two causes of septal perforation act through chronic ischaemia?",
  opts=[["Intranasal steroid use and cocaine use", "Correct."],
        ["Allergic rhinitis and asthma", "Neither perforates the septum."],
        ["Nasal polyps and sinusitis", "Both obstruct the nose without perforating the septum."],
        ["Deviated septum and snoring", "A deviation is a displacement, not a hole."],
        ["Foreign body and epistaxis", "Neither acts by chronic ischaemia."]]),

 dict(topic="Perforated septum", io=IO_A, lead="etiology", cite=D % 37,
  q="Which autoimmune disease is named as a rare cause of nasal deformity?",
  opts=[["Granulomatosis with polyangiitis", "Correct &mdash; a vascular autoimmune disease."],
        ["Rheumatoid arthritis", "A joint disease; not the vasculitis described."],
        ["Systemic lupus erythematosus", "Not the vasculitis named here."],
        ["Sarcoidosis", "Not the disease named here."],
        ["Ankylosing spondylitis", "A spondyloarthropathy; the nose is not involved."]]),

 dict(topic="Perforated septum", io=IO_A, lead="etiology", cite=D % 37,
  q="Which infection is named as a rare cause of septal perforation?",
  opts=[["Secondary syphilis", "Correct, though rarely seen now."],
        ["Tuberculosis", "Not the infection named as a cause of perforation."],
        ["Gonorrhoea", "Syphilis is the treponemal infection implicated, not this one."],
        ["Influenza", "Not a cause of perforation."],
        ["Epstein-Barr virus", "That is linked to nasopharyngeal carcinoma."]]),

 dict(topic="Perforated septum", io=IO_A, lead="treatment", cite=D % 40,
  q="What is the first approach to a perforated septum?",
  opts=[["Treat the underlying cause, so it may grow back", "Correct; otherwise septoplasty."],
        ["Immediate surgery in every case", "Surgery follows if treating the cause fails."],
        ["Nasal packing", "That treats bleeding."],
        ["Long-term antibiotics", "Not the described approach."],
        ["Observation with no action", "The underlying cause needs addressing."]]),

 dict(topic="Septal haematoma", io=IO_A, lead="defining feature", cite=D % 41,
  q="Where does blood collect in a septal haematoma?",
  opts=[["Between the septum and the perichondrium", "Correct."],
        ["Inside the maxillary sinus", "A sinus cavity, not the septal space."],
        ["Beneath the nasal bone", "The collection is in the septum, not under bone."],
        ["In the orbit", "Orbital haematoma is a different injury."],
        ["Within the turbinate", "The turbinates are on the lateral wall, not the septum."]]),

 dict(topic="Septal haematoma", io=IO_A, lead="etiology", cite=D % 41,
  q="What is the usual cause of a septal haematoma?",
  opts=[["Trauma", "Correct; bleeding disorders, cocaine, foreign body and medications are others."],
        ["Allergy", "Allergy causes rhinorrhoea, not a septal collection."],
        ["Chronic sinusitis", "An infective process rather than a bleeding one."],
        ["Nasal polyps", "Polyps obstruct; they do not bleed into the septum."],
        ["Viral infection", "Not among the listed causes."]]),

 dict(topic="Septal haematoma", io=IO_A, lead="treatment", cite=D % 41,
  q="How is a septal haematoma treated?",
  opts=[["Drainage via intranasal incision under general anaesthesia", "Correct."],
        ["Observation and ice alone", "It requires drainage."],
        ["Nasal packing", "Packing treats bleeding, not a collection."],
        ["Oral antibiotics only", "Antibiotics do not drain it."],
        ["Septoplasty at six months", "Drainage is required now."]]),

 dict(topic="Epistaxis", io=IO_A, lead="epidemiology", cite=D % 45,
  q="At which ages does epistaxis peak?",
  opts=[["Before ten, and between forty-five and sixty-five", "Correct, with a winter predominance."],
        ["Only in infancy", "The first peak is before ten, not confined to infancy."],
        ["Only over eighty", "The adult peak is forty-five to sixty-five."],
        ["Evenly across all ages", "There are two clear peaks."],
        ["Only in adolescence", "Adolescence falls between the two peaks."]]),

 dict(topic="Epistaxis", io=IO_A, lead="etiology", cite=D % 45,
  q="What is the commonest cause of epistaxis?",
  opts=[["Trauma from the patient's own finger", "Correct."],
        ["Hypertension", "Not the commonest cause described."],
        ["Anticoagulant medication", "A concerning factor, but not the commonest cause."],
        ["Nasal tumour", "Rare."],
        ["Sinus infection", "Not the commonest cause."]]),

 dict(topic="Epistaxis", io=IO_A, lead="defining feature", cite=D % 46,
  q="Where do about ninety per cent of nosebleeds originate?",
  opts=[["Kiesselbach's plexus, on the nasal septum", "Correct &mdash; the anterior vascular watershed."],
        ["The sphenopalatine artery", "That is the posterior source."],
        ["The internal carotid artery directly", "Posterior bleeds may involve carotid branches, but this is not the usual source."],
        ["The greater palatine artery", "It supplies the palate rather than the anterior septum."],
        ["The frontal sinus", "Not a source of bleeding."]]),

 dict(topic="Epistaxis", io=IO_A, lead="defining feature", cite=D % 46,
  q="Which vessel most commonly causes posterior epistaxis?",
  opts=[["The sphenopalatine artery", "Correct &mdash; its posterolateral branches."],
        ["Kiesselbach's plexus", "That is the anterior source."],
        ["The superior labial artery", "It contributes anteriorly, not posteriorly."],
        ["The anterior ethmoid artery", "Anterior, as its name says."],
        ["The facial vein", "Not an arterial source."]]),

 dict(topic="Epistaxis", io=IO_A, lead="prognosis", cite=D % 45,
  q="Why is posterior epistaxis higher risk than anterior?",
  opts=[["Aspiration and subsequent infection", "Correct."],
        ["It is more painful", "Pain is not the concern."],
        ["It always requires surgery", "Packing usually controls it; surgery is not automatic."],
        ["It causes permanent anosmia", "Smell is not affected by the bleed."],
        ["It is harder to see", "Visibility is not the stated risk."]]),

 dict(topic="Epistaxis", io=IO_A, lead="treatment", cite=D % 49,
  q="Which spray is used during initial tamponade for epistaxis?",
  opts=[["Oxymetazoline", "Correct."],
        ["Intranasal corticosteroid", "That is not the tamponade agent."],
        ["Saline alone", "Saline does not vasoconstrict."],
        ["Ipratropium", "An anticholinergic for rhinorrhoea, not haemostasis."],
        ["An antihistamine spray", "It treats allergy, not bleeding."]]),

 dict(topic="Epistaxis", io=IO_A, lead="treatment", cite=D % 49,
  q="How long should the patient pinch the alae against the septum?",
  opts=[["Ten minutes, continuously", "Correct."],
        ["Thirty seconds", "Far too short."],
        ["Two minutes", "Shorter than instructed."],
        ["Thirty minutes", "Longer than instructed."],
        ["Until the bleeding stops, checking every minute", "Checking interrupts the pressure."]]),

 dict(topic="Epistaxis", io=IO_A, lead="patient education", cite=D % 50,
  q="How should a patient with epistaxis position themselves?",
  opts=[["Sitting up and leaning forward at the waist", "Correct &mdash; so blood is not swallowed."],
        ["Lying flat on the back", "That encourages swallowing blood."],
        ["Head tilted back", "The classic mistake &mdash; blood runs into the pharynx."],
        ["Lying on the affected side", "Lying down at all allows blood to be swallowed."],
        ["Standing with arms raised", "Arm position has no effect on nasal bleeding."]]),

 dict(topic="Epistaxis", io=IO_A, lead="diagnostic technique", cite=D % 49,
  q="Is a prothrombin time with international normalised ratio routine in epistaxis?",
  opts=[["No &mdash; only for the anticoagulated patient", "Correct."],
        ["Yes, in every patient", "It is explicitly not routine."],
        ["Yes, but only in children", "Age is not the criterion."],
        ["Yes, before any packing", "Packing does not require it."],
        ["Never, under any circumstances", "It is indicated in anticoagulated patients."]]),

 dict(topic="Epistaxis", io=IO_A, lead="next step", cite=D % 49,
  q="What is required in massive or prolonged epistaxis?",
  opts=[["Haematocrit, type and crossmatch, and two large-bore intravenous lines", "Correct."],
        ["A single small cannula", "Two large-bore lines are specified."],
        ["Immediate computed tomography", "Not the stated step."],
        ["Oral iron", "Not the acute step."],
        ["Observation alone", "Massive bleeding requires active management."]]),

 dict(topic="Epistaxis", io=IO_A, lead="patient education", cite=D % 51,
  q="What must a patient avoid after epistaxis is controlled?",
  opts=[["Blowing the nose", "Correct."],
        ["Drinking fluids", "Fluids are unrestricted."],
        ["Sleeping upright", "Upright is helpful rather than avoided."],
        ["Using a cold compress", "That is recommended."],
        ["Taking paracetamol", "Unlike aspirin, it does not promote bleeding."]]),

 dict(topic="Nasal foreign body", io=IO_B, lead="defining feature", cite=D % 54,
  q="Which presentation strongly suggests a nasal foreign body in a young child?",
  opts=[["Unilateral purulent, foul-smelling discharge", "Correct."],
        ["Bilateral clear discharge", "That suggests allergic rhinitis."],
        ["Fever with facial pain", "That suggests sinusitis."],
        ["Recurrent nosebleeds", "Common in children generally, and not specific to a foreign body."],
        ["Snoring", "Suggests obstruction such as a deviated septum or polyps."]]),

 dict(topic="Nasal foreign body", io=IO_A, lead="defining feature", cite=D % 54,
  q="Where are nasal foreign bodies most commonly located?",
  opts=[["On the floor under the inferior turbinate, or in front of the middle turbinate", "Correct."],
        ["In the frontal sinus", "Objects do not reach the frontal sinus through the nostril."],
        ["Behind the soft palate", "Beyond the described nasal locations."],
        ["In the maxillary sinus", "A sinus cavity rather than the nasal passage."],
        ["At the nasopharynx only", "Too posterior &mdash; the two described sites are further forward."]]),

 dict(topic="Nasal foreign body", io=IO_A, lead="diagnostic technique", cite=D % 54,
  q="What establishes the diagnosis of a nasal foreign body?",
  opts=[["Visualisation", "Correct &mdash; imaging is rarely needed."],
        ["Computed tomography", "Imaging is rarely needed once the object is seen."],
        ["Plain radiography", "Many objects are radiolucent, and imaging is rarely needed."],
        ["Culture of the discharge", "That identifies organisms, not the object."],
        ["Nasal endoscopy under anaesthesia in all cases", "Direct visualisation usually suffices."]]),

 dict(topic="Nasal fracture", io=IO_A, lead="next step", cite=D % 57,
  q="Which four criteria allow a nasal fracture to be managed without radiographs?",
  opts=[["Swelling isolated to the bony bridge, breathing through each naris, a straight nose, and no septal haematoma",
         "Correct &mdash; all four must hold."],
        ["Age under forty, no bleeding, no pain, and no bruising", "Age plays no part in the decision."],
        ["Normal vision, no headache, no vomiting, and no amnesia", "Those assess head injury, not the nose."],
        ["No fever, no discharge, no anosmia, and no snoring", "Infective and obstructive symptoms, not fracture criteria."],
        ["Normal blood pressure, pulse, temperature and saturations", "Vital signs are not the criteria."]]),

 dict(topic="Nasal fracture", io=IO_A, lead="clinical manifestation", cite=D % 56,
  q="Which finding over the nasal bridge indicates a fracture?",
  opts=[["Contusion and tenderness", "Correct."],
        ["Clear rhinorrhoea alone", "Clear fluid after trauma raises a different concern entirely."],
        ["Bilateral congestion", "Non-specific, and common without trauma."],
        ["Anosmia", "Points to polyps or obstruction rather than fracture."],
        ["Sneezing", "An irritative symptom, not a fracture sign."]]),

 dict(topic="Nasal fracture", io=IO_A, lead="next step", cite=D % 56,
  q="Which other injuries should be suspected with a nasal fracture?",
  opts=[["Orbital and midface fractures", "Correct, along with an associated septal haematoma."],
        ["Cervical spine fracture only", "Considered in trauma generally, but not the injuries paired with nasal fracture."],
        ["Skull base fracture only", "Not the pairing described."],
        ["Mandibular dislocation", "The jaw is not among the injuries paired here."],
        ["Clavicle fracture", "Not related."]]),

 dict(topic="Nasal fracture", io=IO_A, lead="treatment", cite=D % 56,
  q="What is the initial treatment of a nasal fracture?",
  opts=[["Ice and head of bed elevated", "Correct."],
        ["Immediate surgical reduction", "Reduction follows once swelling settles."],
        ["Nasal packing in every case", "Packing treats bleeding."],
        ["Oral steroids", "They have no role in acute nasal fracture."],
        ["Antibiotics for all patients", "There is no infection to treat."]]),

 dict(topic="Nasal polyps", io=IO_A, lead="defining feature", cite=D % 59,
  q="What do nasal polyps look like?",
  opts=[["Grey, glistening masses", "Correct, filled with inflammatory material."],
        ["Red, friable growths", "That description suggests malignancy."],
        ["Black necrotic tissue", "That suggests fungal disease."],
        ["Yellow crusted plaques", "That describes a skin lesion, not a polyp."],
        ["Clear fluid-filled blisters", "Polyps are solid inflammatory masses."]]),

 dict(topic="Nasal polyps", io=IO_A, lead="defining feature", cite=D % 59,
  q="Which triad makes up aspirin-exacerbated respiratory disease?",
  opts=[["Nasal polyps, asthma and aspirin sensitivity", "Correct."],
        ["Polyps, deviated septum and epistaxis", "Three separate conditions rather than a syndrome."],
        ["Polyps, sinusitis and hearing loss", "Hearing loss belongs to the ear lectures."],
        ["Asthma, eczema and hay fever", "That is the atopic triad, not this one."],
        ["Polyps, anosmia and snoring", "Symptoms rather than the syndrome."]]),

 dict(topic="Nasal polyps", io=IO_B, lead="next step", cite=D % 61,
  q="What must every child with benign multiple nasal polyposis be evaluated for?",
  opts=[["Cystic fibrosis and asthma", "Correct."],
        ["Diabetes and hypertension", "Neither is linked to childhood polyposis."],
        ["Congenital heart disease", "Not associated with nasal polyps."],
        ["Immunodeficiency alone", "Too narrow &mdash; the two named are cystic fibrosis and asthma."],
        ["Coeliac disease", "No association with nasal polyps."]]),

 dict(topic="Nasal polyps", io=IO_A, lead="diagnostic technique", cite=D % 64,
  q="Which test is used when cystic fibrosis is suspected in a child with polyps?",
  opts=[["The chloride sweat test", "Correct."],
        ["A nasal smear for eosinophils", "That is used for a different purpose."],
        ["Serum IgE", "That is part of the allergy workup."],
        ["Computed tomography", "That defines extent."],
        ["Culture of nasal discharge", "That identifies organisms."]]),

 dict(topic="Nasal polyps", io=IO_A, lead="prognosis", cite=D % 60,
  q="What is the outlook after surgery for nasal polyps?",
  opts=[["Temporary relief &mdash; they recur within months to years", "Correct."],
        ["Permanent cure in most patients", "Recurrence is the rule."],
        ["Immediate recurrence within days", "Recurrence takes months to years."],
        ["Malignant transformation", "Benign polyps are not described as transforming."],
        ["Complete loss of smell permanently", "Anosmia often improves once the polyps are removed."]]),

 dict(topic="Allergic rhinitis", io=IO_A, lead="clinical manifestation", cite=D % 67,
  q="Which examination findings fit allergic rhinitis?",
  opts=[["Clear discharge from each nostril and a bluish, oedematous mucosa", "Correct."],
        ["Unilateral purulent foul-smelling discharge", "That suggests a foreign body."],
        ["A grey glistening mass", "That describes a polyp."],
        ["Black necrotic tissue", "That suggests fungal disease."],
        ["A friable bleeding growth", "That suggests malignancy."]]),

 dict(topic="Allergic rhinitis", io=IO_A, lead="treatment", cite=D % 68,
  q="Which combination is used for allergic rhinitis?",
  opts=[["A non-drowsy antihistamine by day, a leukotriene inhibitor at night, and intranasal steroids",
         "Correct &mdash; about eighty per cent of patients take two or more medicines."],
        ["Oral antibiotics and antifungals", "There is no infection to treat."],
        ["Nasal packing and decongestant spray only", "Packing treats bleeding."],
        ["Systemic steroids alone, long term", "Not the described approach."],
        ["Surgery as first line", "Medical management comes first."]]),

 dict(topic="Allergic rhinitis", io=IO_A, lead="mechanism", cite=D % 13,
  q="How does allergy relate to sinus infection?",
  opts=[["It creates the environment for infection without itself causing inflammation of the sinus",
         "Correct &mdash; allergy does not cause an inflammation per se."],
        ["It directly infects the sinus", "Allergy is not an infection."],
        ["It has no relationship at all", "It is described as predisposing."],
        ["It prevents sinus infection", "It predisposes rather than protects."],
        ["It only matters in children", "Age is not the distinction."]]),

 dict(topic="Nasopharyngeal carcinoma", io=IO_A, lead="risk factor", cite=D % 69,
  q="Which virus is associated with nasopharyngeal carcinoma?",
  opts=[["Epstein-Barr virus", "Correct, along with human papillomavirus and smoking."],
        ["Cytomegalovirus", "Not among the viruses linked to this tumour."],
        ["Herpes simplex virus", "Not linked to nasopharyngeal carcinoma."],
        ["Influenza virus", "An acute respiratory pathogen with no oncogenic link here."],
        ["Varicella zoster virus", "Not linked to this tumour."]]),

 dict(topic="Nasopharyngeal carcinoma", io=IO_A, lead="epidemiology", cite=D % 69,
  q="Where is nasopharyngeal carcinoma endemic?",
  opts=[["Southern China, Southeast Asia, North Africa and the Arctic", "Correct."],
        ["The United States and Western Europe", "It is rare there."],
        ["South America only", "Not among the regions listed."],
        ["Australia and New Zealand", "Incidence there is low."],
        ["Northern Europe", "Western Europe is explicitly where it is rare."]]),

 dict(topic="Nasopharyngeal carcinoma", io=IO_A, lead="clinical manifestation", cite=D % 70,
  q="How does nasopharyngeal carcinoma present?",
  opts=[["Headache, diplopia, facial numbness and a neck mass", "Correct."],
        ["Clear bilateral rhinorrhoea", "That suggests allergic rhinitis."],
        ["Unilateral foul discharge in a toddler", "That suggests a foreign body."],
        ["Facial pain worse bending forward", "That suggests sinusitis."],
        ["Anosmia with grey masses", "That suggests polyps."]]),

 dict(topic="Nasopharyngeal carcinoma", io=IO_A, lead="diagnostic technique", cite=D % 70,
  q="How is nasopharyngeal carcinoma diagnosed?",
  opts=[["Referral to ENT and endoscopic guided biopsy", "Correct."],
        ["Computed tomography alone", "Imaging does not establish the tissue diagnosis."],
        ["Nasal swab culture", "Culture identifies organisms, not malignancy."],
        ["Serum Epstein-Barr titres alone", "Association is not diagnosis."],
        ["Clinical appearance alone", "Biopsy is required."]]),
]
