# CMS I Lecture 2 (General Dermatology I) — SET 1 pool E: SLOT REBALANCE.
#
# tools/check_slot_coverage.py measured this pool as heavy on what-is-it and
# what-does-it-look-like and empty on the back half of the CMS objective. This
# pool fills the slots that were under floor: risk factors, initial test, gold
# standard, escalation, avoid, education, complication and prognosis.
#
# Every question carries an explicit slot="..." so coverage is measured from
# what the question actually asks, not from how the stem happens to be worded.
#
# Options drafted at matched lengths. Correct answer is ALWAYS written first.
SRC = "2. General Dermatology I.pptx"
def c(n): return f"{SRC}, Slide {n}"

IOC = "Objective c — Etiologies, epidemiology, risk factors, manifestations, differential diagnosis, testing, management, referrals, education and prognosis of dermatological conditions"

POOL_E = [
 # ---------------- risk factors
 dict(topic="Atopic dermatitis", io=IOC, slot="risk factors",
   q="Which risk factors are named for atopic dermatitis?",
   opts=[
     ["Personal or family atopy, raised immunoglobulin E, allergen exposure, xerosis, irritants, heat, stress, infection and overbathing",
      "Correct — barrier dysfunction sits underneath most of them."],
     ["Chronic venous insufficiency, obesity, immobility, previous deep vein thrombosis and chronic lower-limb oedema",
      "Those are the risk factors for stasis dermatitis."],
     ["Occlusive clothing, hot humid weather, obesity, poor hygiene and nasal staphylococcal carriage",
      "Those are the risk factors for folliculitis in Lecture 4."],
     ["Cumulative ultraviolet exposure, fair skin, outdoor occupation, immunosuppression and older age",
      "Those are the risk factors for actinic damage in Lecture 3."]],
   c=0, cite=c(52)),

 dict(topic="Atopic dermatitis", io=IOC, slot="epidemiology",
   q="What proportion of children worldwide does atopic dermatitis affect, and which sex predominates?",
   opts=[
     ["About 20% of children, and it is more common in males than females",
      "Correct. It often begins in infancy or childhood, and adult-onset disease is rare."],
     ["About 5% of children, and it is more common in females than males",
      "That understates the prevalence and reverses the sex difference."],
     ["About 50% of children, and it affects both sexes equally overall",
      "That overstates the prevalence given in the lecture."],
     ["About 2% of children, and it is confined almost entirely to males",
      "That understates the prevalence substantially."]],
   c=0, cite=c(52)),

 dict(topic="Perioral dermatitis", io=IOC, slot="risk factors",
   q="Which exposure most commonly precipitates perioral dermatitis?",
   opts=[
     ["Topical corticosteroid applied to the face",
      "Correct — continued exposure perpetuates it, so the steroid must be stopped."],
     ["Prolonged immersion of the hands in water",
      "That predisposes to chronic paronychia and irritant dermatitis."],
     ["Occlusion of the skin under a plaster cast",
      "That produces acne mechanica."],
     ["Repeated shaving of the beard area with a blade",
      "That produces pseudofolliculitis barbae."]],
   c=0, cite=c(98)),

 dict(topic="Stasis dermatitis", io=IOC, slot="risk factors",
   q="Which underlying process drives stasis dermatitis?",
   opts=[
     ["Chronic venous disease with lower-leg oedema",
      "Correct — the dermatitis is a consequence of venous hypertension."],
     ["Chronic arterial insufficiency with reduced perfusion",
      "Arterial disease matters here, but as a contraindication to compression."],
     ["Repeated contact with an environmental allergen",
      "That produces allergic contact dermatitis."],
     ["Autoimmune destruction of the epidermal basement membrane",
      "That describes bullous pemphigoid."]],
   c=0, cite=c(113)),

 # ---------------- initial test
 dict(topic="Nummular eczema", io=IOC, slot="initial test",
   q="Which test is ordered in nummular eczema when tinea corporis cannot be ruled out?",
   opts=[
     ["A potassium hydroxide preparation",
      "Correct. Bacterial culture is added if lesions look secondarily infected."],
     ["A bacterial culture and sensitivity",
      "That is used where the lesions appear secondarily infected."],
     ["Allergy patch testing of a standard series",
      "That is considered in chronic or recurrent disease."],
     ["Direct immunofluorescence of perilesional skin",
      "That investigates autoimmune blistering disease."]],
   c=0, cite=c(74)),

 dict(topic="Perioral dermatitis", io=IOC, slot="initial test",
   q="When should a potassium hydroxide preparation be ordered in suspected perioral dermatitis?",
   opts=[
     ["When tinea or Candida is suspected",
      "Correct. Bacterial culture is ordered where pustules, crusting or drainage suggest infection."],
     ["When allergic contact dermatitis is suspected",
      "That is the indication for patch testing."],
     ["When the lesions are persistent or granulomatous",
      "That is the indication for skin biopsy."],
     ["When the patient has failed a topical antibiotic",
      "Treatment failure is not the stated trigger for this test."]],
   c=0, cite=c(101)),

 dict(topic="Stasis dermatitis", io=IOC, slot="initial test",
   q="Which test should be considered before starting substantial compression for stasis dermatitis?",
   opts=[
     ["An ankle-brachial index or toe pressure",
      "Correct — arterial status has to be clarified first, because compression on an ischaemic limb causes harm."],
     ["A venous duplex ultrasound of the affected leg",
      "That is ordered when reflux, obstruction or thrombosis is suspected."],
     ["A punch biopsy of the affected gaiter skin",
      "Biopsy is not part of the routine stasis dermatitis workup."],
     ["A bacterial culture taken from the affected skin",
      "That would only address suspected secondary infection."]],
   c=0, cite=c(116)),

 dict(topic="Diaper dermatitis", io=IOC, slot="initial test",
   q="Which finding on a potassium hydroxide preparation supports candidal diaper dermatitis?",
   opts=[
     ["Budding yeast or pseudohyphae",
      "Correct — fold involvement with satellite lesions is what prompts the test."],
     ["Branching septate hyphae only",
      "That pattern indicates a dermatophyte rather than Candida."],
     ["Multinucleated giant cells",
      "That is the Tzanck smear finding in herpesvirus infection."],
     ["Mites, eggs or faecal pellets",
      "That is the mineral oil preparation finding in scabies."]],
   c=0, cite=c(108)),

 dict(topic="Alopecia areata", io=IOC, slot="initial test",
   q="Which dermoscopic findings support alopecia areata?",
   opts=[
     ["Yellow dots, black dots, broken hairs, tapered hairs and short regrowth",
      "Correct — the diagnosis is clinical and dermoscopy strengthens it."],
     ["Finger-like projections with a moth-eaten border at the edge",
      "That is the dermoscopic appearance of solar lentigo."],
     ["A dense dark head with the body, eggs and burrow trailing behind",
      "That is the delta-wing jet sign in scabies."],
     ["Comedone-like openings and a stuck-on surface appearance",
      "That is the dermoscopic appearance of seborrheic keratosis."]],
   c=0, cite=c(139)),

 # ---------------- gold standard / confirmatory
 dict(topic="Bullous pemphigoid", io=IOC, slot="gold standard",
   q="Which specimens are taken to confirm bullous pemphigoid?",
   opts=[
     ["Lesional tissue for histopathology and perilesional tissue for direct immunofluorescence",
      "Correct — serum indirect immunofluorescence or ELISA identifies anti-basement membrane zone antibodies."],
     ["Lesional tissue for direct immunofluorescence and perilesional tissue for histopathology",
      "That reverses which specimen goes for which test."],
     ["A superficial scraping of the blister roof examined in mineral oil",
      "That is the technique for scabies."],
     ["A swab of the blister base examined for multinucleated giant cells",
      "That is the Tzanck smear for herpesvirus."]],
   c=0, cite=c(124)),

 dict(topic="Pemphigus", io=IOC, slot="gold standard",
   q="What does biopsy demonstrate in pemphigus, and what is confirmatory?",
   opts=[
     ["Acantholysis on biopsy, with immunofluorescence and serum ELISA for pathogenic antibodies confirmatory",
      "Correct — the split is intraepidermal, which is what acantholysis describes."],
     ["Subepidermal separation on biopsy, with a serum antinuclear antibody panel confirmatory",
      "Subepidermal separation is bullous pemphigoid."],
     ["Band-like lymphocytic infiltration, with a potassium hydroxide preparation confirmatory",
      "That histology belongs to lichen planus."],
     ["Full-thickness epidermal necrosis, with blood cultures confirmatory",
      "That histology belongs to toxic epidermal necrolysis."]],
   c=0, cite=c(132)),

 dict(topic="Bullous pemphigoid", io=IOC, slot="test finding",
   q="What does light microscopy show in bullous pemphigoid?",
   opts=[
     ["Neutrophils aligned in a straight narrow row at the dermal-epidermal junction",
      "Correct — a distinctive pattern at the level where the split occurs."],
     ["Acantholytic keratinocytes separated from one another within the epidermis",
      "That is the pemphigus finding."],
     ["A band-like infiltrate of lymphocytes filling the papillary dermis",
      "That is the lichen planus finding."],
     ["Granular immunoglobulin A deposited at the tips of the dermal papillae",
      "That is dermatitis herpetiformis, in Lecture 3."]],
   c=0, cite=c(124)),

 dict(topic="Lichen planus", io=IOC, slot="test finding",
   q="Besides band-like lymphocytic infiltration, which histological features are characteristic of lichen planus?",
   opts=[
     ["Hyperkeratosis without parakeratosis, basal vacuolisation, Civatte bodies and a saw-tooth rete ridge",
      "Correct — Civatte bodies are apoptotic keratinocytes in the lower epidermis."],
     ["Parakeratosis with Munro microabscesses, thinning above the papillae and tortuous capillaries",
      "That histology belongs to psoriasis."],
     ["Acantholysis with a suprabasal split and a row of tombstone basal cells",
      "That histology belongs to pemphigus."],
     ["Spongiosis with intraepidermal vesiculation and a perivascular infiltrate",
      "That is a non-specific eczematous pattern."]],
   c=0, cite=c(177)),

 # ---------------- escalation / second line
 dict(topic="Psoriasis", io=IOC, slot="escalation",
   q="A patient with plaque psoriasis has failed emollients, topical steroids, calcipotriene and phototherapy. Which agents come next?",
   opts=[
     ["Methotrexate, acitretin, apremilast, or a biologic such as etanercept, infliximab, adalimumab or ixekizumab",
      "Correct — that is the moderate to severe tier, used after first-line topical therapy fails."],
     ["Salicylic acid and coal tar preparations applied directly to each of the affected plaques twice daily",
      "Those are the second-line topical agents, tried before the systemic tier."],
     ["Superpotent topical corticosteroids applied twice daily under occlusion",
      "Topical steroids are already part of the first-line tier that failed."],
     ["Oral antihistamines with a fragrance-free emollient applied twice daily",
      "Those address pruritus and barrier repair rather than the disease."]],
   c=0, cite=c(163)),

 dict(topic="Lichen planus", io=IOC, slot="escalation",
   q="Superpotent topical steroids have not controlled a patient's lichen planus. Which options follow?",
   opts=[
     ["Oral steroids for severe disease, with PUVA or phototherapy for refractory cases",
      "Correct — topical tacrolimus is used for oral and vaginal disease specifically."],
     ["A longer course of the same superpotent topical steroid under occlusion",
      "Repeating a failed first-line therapy is not the described escalation."],
     ["Oral terbinafine, since resistant lichenoid eruptions are usually fungal",
      "Lichen planus is not a fungal condition."],
     ["Intralesional triamcinolone into each affected plaque every four weeks",
      "That is not among the described options for this condition."]],
   c=0, cite=c(178)),

 dict(topic="Bullous pemphigoid", io=IOC, slot="escalation",
   q="A patient with bullous pemphigoid has not responded to prednisone and doxycycline. Which agents are used for refractory disease?",
   opts=[
     ["Immunosuppressives such as methotrexate and azathioprine, with biologics and intravenous immunoglobulin also used",
      "Correct — low-dose methotrexate is described as safe and effective in the elderly, with folic acid."],
     ["Ultrapotent topical corticosteroids applied to the whole of the skin surface twice daily for several weeks",
      "Those are used for mild disease rather than for refractory disease."],
     ["Rituximab as the sole first-line agent, since it is used in pemphigus",
      "Rituximab is the initial choice in pemphigus rather than here."],
     ["Oral antihistamines and emollients while the disease burns itself out",
      "Those do not control an autoimmune blistering disease."]],
   c=0, cite=c(125)),

 dict(topic="Atopic dermatitis", io=IOC, slot="escalation",
   q="Which measures are used for severe atopic dermatitis that topical therapy has not controlled?",
   opts=[
     ["Referral to a specialist, with phototherapy and systemic treatment",
      "Correct — emollient wet wraps are also used for selected severe flares."],
     ["A stronger topical corticosteroid applied to the face and eyelids",
      "High potency agents are specifically avoided on those sites."],
     ["A prolonged course of an oral antibiotic covering staphylococci",
      "Antibiotics address secondary infection rather than the eczema."],
     ["Discontinuing emollients so that the skin can dry and settle down",
      "Emollients are foundational and are not withdrawn."]],
   c=0, cite=c(57)),

 dict(topic="Allergic contact dermatitis", io=IOC, slot="escalation",
   q="How does treatment of allergic contact dermatitis change when the eruption is extensive rather than limited?",
   opts=[
     ["High-dose oral corticosteroids replace the high-potency topical steroid used for limited disease",
      "Correct — soothing measures such as oatmeal baths and cool compresses are used throughout."],
     ["A more potent topical corticosteroid is applied to a larger surface area instead",
      "Extensive disease moves to systemic therapy rather than more topical."],
     ["An oral antibiotic is added, since extensive disease is usually secondarily infected",
      "Antibiotics are not the described escalation here."],
     ["Phototherapy is started three times weekly over a five-week course",
      "That is not the described escalation for this condition."]],
   c=0, cite=c(89)),

 # ---------------- avoid / do-not
 dict(topic="Perioral dermatitis", io=IOC, slot="avoid",
   q="Which measure is essential in treating perioral dermatitis, and what should the patient be warned about?",
   opts=[
     ["Stop facial topical corticosteroids, warning that the eruption may temporarily worsen after withdrawal",
      "Correct — continued exposure perpetuates the condition."],
     ["Continue the facial topical corticosteroids, warning that improvement takes several months",
      "Continuing the steroid is what sustains the disease."],
     ["Stop all emollients, warning that the skin will feel dry for the first two weeks",
      "A simplified skincare routine is recommended rather than no moisturiser at all."],
     ["Stop oral antibiotics, warning that the eruption commonly rebounds afterwards",
      "Oral tetracycline or doxycycline is used for extensive or persistent disease."]],
   c=0, cite=c(102)),

 dict(topic="Diaper dermatitis", io=IOC, slot="avoid",
   q="When applying a barrier preparation for diaper dermatitis, what is not necessary?",
   opts=[
     ["Scrubbing away the entire previous layer, provided it remains clean",
      "Correct — a thick layer of zinc oxide or petrolatum goes on with each change."],
     ["Changing the diaper frequently and allowing periods of air exposure",
      "Both are part of the foundation of treatment."],
     ["Applying the barrier at every single diaper change without exception",
      "That is exactly what is recommended."],
     ["Adding a topical antifungal when candidal dermatitis is suspected",
      "That is recommended when Candida is suspected or confirmed."]],
   c=0, cite=c(109)),

 dict(topic="Androgenetic alopecia", io=IOC, slot="avoid",
   q="In which patients is finasteride contraindicated or not indicated?",
   opts=[
     ["It is not indicated in women and is contraindicated in pregnancy",
      "Correct — about 2% of men report reduced libido and erectile function, reversible on stopping."],
     ["It is not indicated in men over sixty and is contraindicated in diabetes",
      "Neither restriction is described."],
     ["It is not indicated alongside minoxidil, because the two interact",
      "The two work best in combination."],
     ["It is not indicated in anyone under forty, because of bone effects",
      "No such restriction is described."]],
   c=0, cite=c(148)),

 # ---------------- education
 dict(topic="Atopic dermatitis", io=IOC, slot="education",
   q="Which education points are named for atopic dermatitis?",
   opts=[
     ["Apply emollient after rinsing, avoid irritants, use fragrance-free skincare, demonstrate quantity and application, and give a written flare and infection action plan",
      "Correct — corticosteroid concerns are addressed directly rather than avoided."],
     ["Bathe as little as possible, avoid all moisturisers, use only prescription cleansers, and stop any topical steroid at the first sign of improvement",
      "Overbathing is a risk factor but emollients are foundational."],
     ["Apply the strongest available steroid at the first sign of a flare, then stop abruptly",
      "Potency is chosen by site, and application is demonstrated rather than maximised."],
     ["Avoid all sun exposure and apply broad-spectrum sunscreen several times daily",
      "That is photoprotection advice from Lecture 3."]],
   c=0, cite=c(58)),

 dict(topic="Dyshidrotic eczema", io=IOC, slot="education",
   q="Which hand-care advice is given for dyshidrotic eczema?",
   opts=[
     ["Lukewarm water and soap-free cleansers, dry thoroughly, then emollient immediately and as often as possible",
      "Correct, alongside avoiding detergents, solvents, hair lotions or dyes, and acidic foods."],
     ["Hot water with an antibacterial soap, air dry, then a light lotion once daily",
      "Hot water and harsh soap worsen the barrier dysfunction."],
     ["Wash the hands as infrequently as possible and avoid all emollients, since they trap the vesicles",
      "Emollients are applied as often as possible."],
     ["Wear occlusive gloves continuously, including overnight and during sleep",
      "Cotton gloves over heavy emollient at night belong to irritant contact dermatitis."]],
   c=0, cite=c(66)),

 dict(topic="Irritant contact dermatitis", io=IOC, slot="education",
   q="Which specific overnight measure is described for irritant contact dermatitis of the hands?",
   opts=[
     ["Sleep in cotton gloves after applying a heavy emollient such as petroleum jelly",
      "Correct — avoiding the exposure and repairing the barrier are the two halves of treatment."],
     ["Sleep with the hands elevated above the level of the heart",
      "That measure belongs to stasis dermatitis of the legs."],
     ["Sleep with an occlusive plastic wrap placed over a potent topical steroid",
      "Occlusion of a potent steroid is not the described measure."],
     ["Sleep without any product on the hands so the skin can recover",
      "Barrier repair with emollient is the point of the measure."]],
   c=0, cite=c(82)),

 # ---------------- referral
 dict(topic="Atopic dermatitis", io=IOC, slot="referral",
   q="When should a patient with atopic dermatitis be referred?",
   opts=[
     ["For uncertain diagnosis, moderate-to-severe disease, or recurrent infection",
      "Correct — those are the three stated triggers."],
     ["Only once both phototherapy and systemic treatment have already failed",
      "Referral comes earlier than that in the stated criteria."],
     ["At the first presentation of any child with flexural eczema",
      "Most disease is managed without referral."],
     ["Only when the family requests a specialist opinion themselves",
      "The criteria are clinical rather than by request."]],
   c=0, cite=c(58)),

 dict(topic="Stasis dermatitis", io=IOC, slot="referral",
   q="Which referrals should be considered in stasis dermatitis?",
   opts=[
     ["Dermatology, vascular surgery or wound care, for refractory disease, venous reflux or ulceration",
      "Correct — compression remains the cornerstone once arterial circulation is established."],
     ["Rheumatology and nephrology, for the autoimmune and the renal causes of leg oedema",
      "Those are not the referrals named for this condition."],
     ["Infectious diseases, since the condition is usually secondary to cellulitis",
      "Stasis dermatitis is frequently mistaken for cellulitis rather than caused by it."],
     ["Endocrinology, since venous disease is usually the first sign of diabetes",
      "That is not the described referral pathway."]],
   c=0, cite=c(117)),

 dict(topic="Alopecia areata", io=IOC, slot="referral",
   q="Which supportive measure is described as one of the most important considerations in alopecia areata?",
   opts=[
     ["Psychological support, with support groups offered",
      "Correct — the visible nature of the condition carries real psychological weight."],
     ["Referral to endocrinology for thyroid function assessment",
      "Autoimmune associations exist but this is not what is named here."],
     ["Referral for hair transplantation early in the disease course",
      "Transplantation is discussed for androgenetic rather than areata."],
     ["Referral to a wig service before starting any medical therapy",
      "That is not what the lecture names."]],
   c=0, cite=c(140)),

 # ---------------- complications
 dict(topic="Atopic dermatitis", io=IOC, slot="complication",
   q="A patient with atopic dermatitis develops painful monomorphic punched-out erosions over a flaring area. Which test should be ordered?",
   opts=[
     ["Herpes simplex virus polymerase chain reaction",
      "Correct — that presentation is eczema herpeticum until proven otherwise."],
     ["A bacterial culture of the crusted areas",
      "Culture is ordered for purulent, pustular or significantly crusted lesions."],
     ["Allergy patch testing of a standard series",
      "That addresses atypical, adult-onset or treatment-resistant disease."],
     ["A potassium hydroxide preparation of the scale",
      "That would investigate a fungal cause."]],
   c=0, cite=c(56)),

 dict(topic="Nummular eczema", io=IOC, slot="complication",
   q="Which test is ordered when nummular eczema lesions appear secondarily infected?",
   opts=[
     ["A bacterial culture",
      "Correct, with the secondary infection treated if present."],
     ["A potassium hydroxide preparation",
      "That is used when tinea corporis cannot be ruled out."],
     ["Allergy patch testing",
      "That is considered in chronic or recurrent disease."],
     ["A punch biopsy for histology",
      "Biopsy is not the described step for suspected infection."]],
   c=0, cite=c(74)),

 dict(topic="Lichen simplex chronicus", io=IOC, slot="complication",
   q="When should a lichen simplex chronicus plaque be biopsied?",
   opts=[
     ["When it is atypical, unilateral, nodular, ulcerated or treatment-resistant",
      "Correct — the purpose is to exclude neoplasia or another inflammatory disorder."],
     ["When it has been present for longer than six weeks in any location",
      "Duration alone is not the stated trigger."],
     ["When the patient reports that the itch is worse at night than by day",
      "Nocturnal itch is characteristic rather than a biopsy indication."],
     ["When emollients alone have failed to settle the plaque completely",
      "Failure of emollients alone is not the stated trigger."]],
   c=0, cite=c(182)),

 dict(topic="Lichen simplex chronicus", io=IOC, slot="complication",
   q="What should generalised or unexplained pruritus prompt?",
   opts=[
     ["A targeted systemic evaluation guided by history, medications, review of systems and examination",
      "Correct — itching everywhere for no local reason has to be worked up."],
     ["Immediate biopsy of the most prominent plaque on the body",
      "Biopsy addresses an atypical plaque rather than generalised itch."],
     ["A trial of a superpotent topical steroid over the whole body surface",
      "That treats the symptom without investigating the cause."],
     ["Reassurance, since generalised pruritus is a normal and expected feature of ageing",
      "Unexplained generalised pruritus warrants evaluation."]],
   c=0, cite=c(182)),

 # ---------------- prognosis
 dict(topic="Atopic dermatitis", io=IOC, slot="prognosis",
   q="What is the prognosis of atopic dermatitis?",
   opts=[
     ["Chronic and relapsing, but many patients improve with age",
      "Correct — it may improve, persist or recur."],
     ["Self-limiting over six to eight weeks with no recurrence",
      "That is the course of pityriasis rosea."],
     ["Steadily progressive, with universal involvement by adulthood",
      "Many patients improve as they get older."],
     ["Curable with a single course of a potent topical corticosteroid",
      "The condition is controlled rather than cured."]],
   c=0, cite=c(58)),

 dict(topic="Pityriasis rosea", io=IOC, slot="prognosis",
   q="What is the treatment and prognosis of pityriasis rosea?",
   opts=[
     ["Self-limited, so reassurance, with antihistamines or cautious topical steroids for itch",
      "Correct — phototherapy or sunlight helps if started in the first week, and aciclovir is used in severe cases."],
     ["Chronic and relapsing, so long-term topical corticosteroid maintenance is needed",
      "The eruption resolves on its own."],
     ["Progressive without treatment, so systemic therapy is started at diagnosis",
      "The condition is self-limited."],
     ["Curable only with a full course of an oral antifungal agent",
      "It is not a fungal condition."]],
   c=0, cite=c(171)),

 dict(topic="Xerosis", io=IOC, slot="prognosis",
   q="What is the expected course of xerosis with consistent barrier care?",
   opts=[
     ["Most patients improve, but recurrence is expected while exposure, ageing or systemic risk persists",
      "Correct — the underlying driver has not gone away."],
     ["Most patients are cured permanently once the barrier has been restored",
      "Recurrence is expected when the driver persists."],
     ["Most patients progress to eczema regardless of how well it is treated",
      "That progression is not described."],
     ["Most patients see no benefit at all from emollients and will require systemic therapy",
      "Consistent barrier care is what improves it."]],
   c=0, cite=c(153)),

 dict(topic="Lichen simplex chronicus", io=IOC, slot="prognosis",
   q="What determines whether lichen simplex chronicus recurs?",
   opts=[
     ["Whether the initiating itch is controlled, since recurrence is common if it is not",
      "Correct — sleep, anxiety, neuropathic symptoms and the primary dermatosis all need addressing."],
     ["Whether the plaque was biopsied before treatment was started",
      "Biopsy is diagnostic rather than a determinant of recurrence."],
     ["Whether a superpotent rather than a potent steroid was used",
      "A potent steroid for a limited course is what is described."],
     ["Whether the patient was over sixty years of age at the first presentation",
      "Age is not the stated determinant."]],
   c=0, cite=c(183)),

 dict(topic="Psoriasis", io=IOC, slot="first-line",
   q="Which first-line topical agent for mild plaque psoriasis acts quickest, and what is the caution?",
   opts=[
     ["Calcipotriene, a vitamin D analogue, with caution for nephrotoxicity",
      "Correct — emollients, topical steroids and ultraviolet B phototherapy make up the rest of first line."],
     ["Coal tar preparation, with caution for staining and photosensitivity",
      "Coal tar is a second-line agent."],
     ["Salicylic acid, with caution for stinging on fissured skin",
      "Salicylic acid is a second-line agent."],
     ["Methotrexate, with caution for hepatotoxicity and marrow suppression",
      "Methotrexate belongs to the moderate to severe tier."]],
   c=0, cite=c(163)),

 dict(topic="Psoriasis", io=IOC, slot="first-line",
   q="How is guttate psoriasis treated?",
   opts=[
     ["No treatment is needed, though phototherapy and topical steroids may be used",
      "Correct — pustular psoriasis by contrast needs acitretin or methotrexate."],
     ["Acitretin is started immediately, with methotrexate if that fails",
      "That is the treatment of pustular psoriasis."],
     ["A biologic agent is started at diagnosis in every patient",
      "Biologics belong to moderate to severe plaque disease."],
     ["High-potency topical steroids are contraindicated in this form",
      "Topical steroids may be used."]],
   c=0, cite=c(164)),

 dict(topic="Seborrhoeic dermatitis", io=IOC, slot="first-line",
   q="Which agent class is the mainstay of treatment for seborrhoeic dermatitis?",
   opts=[
     ["Topical antifungals such as ketoconazole",
      "Correct — steroids are used early to reduce the inflammatory response."],
     ["Topical calcineurin inhibitors such as tacrolimus",
      "Those are used for sensitive sites in atopic dermatitis."],
     ["Topical retinoids such as adapalene or tretinoin",
      "Those treat acne and photoaging."],
     ["Oral tetracyclines such as doxycycline or minocycline",
      "Those are used in perioral dermatitis and acne."]],
   c=0, cite=c(95)),

 dict(topic="Alopecia areata", io=IOC, slot="first-line",
   q="How does first-line treatment of alopecia areata differ between children and adults?",
   opts=[
     ["Topical steroids first line in children ten and under; intralesional steroids first line in adolescents and adults",
      "Correct — injections are avoided in young children."],
     ["Intralesional steroids first line in children ten and under; topical steroids first line in adults",
      "That reverses the two."],
     ["Oral minoxidil first line in children; oral finasteride first line in adults",
      "Those are treatments for androgenetic alopecia."],
     ["Phototherapy first line in children; systemic immunosuppression first line in adults",
      "Neither is described as first line here."]],
   c=0, cite=c(140)),
]
