# -*- coding: utf-8 -*-
"""Lecture 21 objective-style pool B -- Hypotension: reflex syncope, cardiogenic
syncope, non-hypotensive causes, postural orthostatic tachycardia syndrome,
treatment and the drug-to-condition match, education and populations.

KEYS ARE WRITTEN SHORT ON PURPOSE — detail lives in the explanation.

The drugs are tested by ROLE only -- best-with, avoid-with, adjunct, setting --
never by mechanism (Carter: "there will be no test questions on the mechanism")
and never by dose. The syndrome is written out in full as "postural orthostatic
tachycardia syndrome"; the deck expands the letters as "positional", and no
question turns on that word.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _cmse3_q import Q
from cms_e4l21_scope import *


def S(topic, io, q, opts, cite, slot):
    d = Q(topic, io, q, opts, cite); d["slot"] = slot; return d


QUESTIONS = [

S("Reflex syncope", IO2,
  "What triggers situational reflex syncope?",
  [["Certain bodily functions or actions",
    "Correct. Situational syncope is triggered by certain bodily functions or physical actions, such as urination at night, coughing or sneezing."],
   ["Emotional stress, fear or pain",
    "Emotional stress, fear, pain, heat exposure and prolonged standing are the triggers of vasovagal syncope, the other reflex type."],
   ["Standing after autonomic nerve damage",
    "A postural drop from autonomic damage is neurogenic orthostatic syncope, a sustained drop rather than a triggered reflex."],
   ["A rapid ventricular rhythm",
    "A rapid ventricular rhythm causes arrhythmic cardiogenic syncope, often abrupt and with palpitations, rather than reflex syncope."]],
  C(14), "etiology"),

S("Vasovagal syncope", IO2,
  "Which triggers are typical of vasovagal syncope?",
  [["Fear, pain, heat or prolonged standing",
    "Correct. Vasovagal syncope is triggered by emotional stress, fear, pain, heat exposure or standing for a long time, and trigger avoidance is its treatment."],
   ["Urination, coughing or sneezing",
    "Bodily functions such as urination, coughing and sneezing trigger situational syncope, the other type of reflex syncope."],
   ["Standing after a diuretic increase",
    "A postural drop after a diuretic increase is non-neurogenic orthostatic syncope from medication and volume loss."],
   ["Exertion with known heart disease",
    "Syncope with structural heart disease is cardiogenic, investigated with echocardiography and cardiology consultation."]],
  C(14), "risk factors"),

S("Vasovagal syncope", IO2,
  "Which type of reflex syncope is known as the common faint?",
  [["Vasovagal syncope",
    "Correct. Vasovagal syncope is the most common type, known as the common faint, and is most commonly seen in young women."],
   ["Situational syncope",
    "Situational syncope is the reflex type triggered by bodily functions or physical actions, such as micturition syncope."],
   ["Neurogenic syncope",
    "Neurogenic syncope is an orthostatic type caused by autonomic dysfunction, such as from diabetes or Parkinson disease."],
   ["Cardiogenic syncope",
    "Cardiogenic syncope comes from an arrhythmia, structural disease or a vascular cause, not from a reflex."]],
  C(14), "differential"),

S("Vasovagal syncope", IO5,
  "In whom is vasovagal syncope most commonly seen?",
  [["Young women",
    "Correct. Vasovagal syncope, the common faint, is most commonly seen in young women, and its triggers include fear, pain, heat and prolonged standing."],
   ["Older men",
    "Older men feature in situational micturition syncope and in cardiogenic syncope, but vasovagal syncope is most common in young women."],
   ["Adolescent boys",
    "Adolescence matters for postural orthostatic tachycardia syndrome thresholds, and that syndrome, too, affects women more than men."],
   ["Adults with diabetes",
    "Long-standing diabetes is a cause of neurogenic orthostatic hypotension through autonomic neuropathy, not a feature of vasovagal syncope."]],
  C(14), "epidemiology"),

S("Vasovagal syncope", IO2,
  "What is known about the cause of vasovagal syncope?",
  [["Unclear; possibly genetic",
    "Correct. The etiology of vasovagal syncope is unclear, with a possible genetic predisposition, even though its triggers and reflex chain are well described."],
   ["Autonomic nerve damage",
    "Autonomic nerve damage is the cause of neurogenic orthostatic syncope, in which the heart rate rises only minimally on standing."],
   ["Chronic volume depletion",
    "Volume depletion causes non-neurogenic orthostatic hypotension, where the intact autonomic system raises the heart rate significantly."],
   ["Structural heart disease",
    "Structural heart disease, such as infarction, cardiomyopathy, heart failure or valve disease, causes cardiogenic syncope."]],
  C(14), "etiology"),

S("Vasovagal syncope", IO2,
  "Which chain of events produces vasovagal syncope?",
  [["Vagal surge, bradycardia, vasodilation",
    "Correct. A transient rise in parasympathetic outflow with sympathetic inhibition causes bradycardia, vasodilation and reduced cardiac output, so systolic pressure falls."],
   ["Sympathetic surge, tachycardia, constriction",
    "A sympathetic surge would raise pressure. The vasovagal reflex runs the opposite way, with vagal dominance and sympathetic withdrawal."],
   ["Autonomic failure, fixed heart rate",
    "A fall with a nearly fixed heart rate reflects autonomic failure, the neurogenic orthostatic pattern, rather than a transient reflex."],
   ["Fluid loss, compensatory tachycardia",
    "Fluid loss with a compensatory heart rate rise is non-neurogenic orthostatic hypotension, showing an intact autonomic reflex."]],
  C(14), "etiology"),

S("Vasovagal syncope", IO2,
  "In vasovagal syncope, what finally causes the loss of consciousness?",
  [["Cerebral flow below autoregulation",
    "Correct. Bradycardia, vasodilation and reduced output drop systolic pressure until cerebral blood flow falls below the limits of autoregulation and consciousness is lost."],
   ["Seizure activity across the cortex",
    "Seizure is a non-hypotensive cause of transient loss of consciousness; vasovagal syncope works through reduced cerebral blood flow."],
   ["Low blood glucose in the brain",
    "Hypoglycemia is a separate, non-hypotensive cause of syncope that is excluded with a blood glucose measurement."],
   ["A ventricular rhythm stopping flow",
    "A ventricular arrhythmia is a cardiogenic cause of syncope, recognized by abrupt collapse without warning and confirmed on an electrocardiogram."]],
  C(14), "complication"),

S("Reflex syncope", IO2,
  "How is reflex syncope diagnosed?",
  [["Mainly by the history",
    "Correct. History is the most important portion of diagnosing reflex syncope, summed up as history, history, history, with a log of pattern and frequency."],
   ["Mainly by tilt-table testing",
    "The tilt-table test is listed for postural orthostatic tachycardia syndrome, and a negative result tells little given its 40% sensitivity."],
   ["Mainly by echocardiography",
    "Echocardiography evaluates structural cardiogenic syncope, such as cardiomyopathy or valve disease, not reflex syncope."],
   ["Mainly by serum electrolytes",
    "Electrolytes help exclude a metabolic contributor, but reflex syncope is diagnosed from the history of its triggers."]],
  C(15), "initial test"),

S("Reflex syncope", IO2,
  "What should a patient with recurrent reflex syncope be asked to keep?",
  [["A log of pattern and frequency",
    "Correct. A patient log helps determine the pattern and frequency of episodes, which supports a diagnosis built mainly on the history."],
   ["A daily blood glucose diary",
    "Glucose checks exclude hypoglycemia, a non-hypotensive cause, but the recommended record for reflex syncope is an episode log."],
   ["A weekly weight chart",
    "Weight charts suit volume questions. Reflex syncope is tracked with a log of when and how often episodes occur."],
   ["A home blood pressure average",
    "An averaged home pressure hides the transient reflex episodes. The log records the pattern and frequency of the faints themselves."]],
  C(15), "education"),

S("Reflex syncope", IO2,
  "What is the first-line treatment for reflex syncope?",
  [["Trigger avoidance",
    "Correct. Reflex syncope is treated by avoiding its triggers, with safety precautions when a trigger cannot be avoided; no drug is first-line."],
   ["Daily midodrine",
    "Midodrine is best with neurogenic syncope and is avoided with supine hypertension, severe heart disease and chronic kidney disease."],
   ["Fludrocortisone",
    "Fludrocortisone is best with postural orthostatic tachycardia syndrome and is avoided in heart failure because it retains salt and water."],
   ["Droxidopa therapy",
    "Droxidopa has mild efficacy and is usually an adjunct to midodrine or fludrocortisone, not a first-line treatment for reflex syncope."]],
  C(15), "first-line"),

S("Reflex syncope", IO2,
  "When a reflex trigger cannot be avoided, what is advised?",
  [["Safety precautions during the trigger",
    "Correct. Trigger avoidance is the treatment, and safety precautions are recommended during unavoidable triggers to limit harm from a faint."],
   ["Vasopressors before each exposure",
    "Vasopressors such as norepinephrine and phenylephrine are for the emergency department and intensive care only."],
   ["Tilt-table testing each time",
    "Tilt-table testing is a diagnostic test for postural orthostatic tachycardia syndrome, not a protective measure for reflex triggers."],
   ["Fluid restriction beforehand",
    "Restricting fluid lowers volume and makes a faint more likely; the advice for unavoidable triggers is safety precautions."]],
  C(15), "education"),

S("Hypotension treatment", IO2,
  "For reflex hypotension, what is the treatment principle?",
  [["Reduce or remove the trigger",
    "Correct. The principle is to remove the offending agent or trigger: reflex causes are managed by reducing or removing the trigger."],
   ["Reduce or remove the medication",
    "Reducing or removing a medication is the approach for iatrogenic hypotension, where a drug is the offending agent."],
   ["Treat the autonomic disease",
    "Treating an underlying condition is the approach for orthostasis, such as autonomic failure or volume loss, rather than for reflex causes."],
   ["Start a vasopressor infusion",
    "Vasopressor infusions are for the emergency department and intensive care only, not the management of reflex hypotension."]],
  C(23), "first-line"),

S("Situational syncope", IO4,
  "Which setting is typical of micturition syncope?",
  [["Voiding while standing at night",
    "Correct. Nocturnal urination after abruptly standing from bed, voiding in the standing position, triggers an exaggerated autonomic reflex with vagal activity and reduced vascular tone."],
   ["Exertion while climbing stairs",
    "Syncope during exertion raises concern for a cardiogenic cause, which needs electrocardiography, echocardiography and cardiology input."],
   ["Shock at hearing bad news",
    "Emotional stress and fear are triggers of vasovagal syncope, the common faint, rather than the situational micturition type."],
   ["Diarrhea for several days",
    "Several days of diarrhea cause volume depletion and non-neurogenic orthostatic hypotension, with a significant heart rate rise on standing."]],
  C(27), "manifestation"),

S("Situational syncope", IO4,
  "Which factors further predispose an older man to micturition syncope?",
  [["Alcohol, dehydration, an alpha-1 blocker",
    "Correct. Alcohol use, relative dehydration and an alpha-1 blocker taken with an angiotensin-converting enzyme inhibitor add to the risk of hypotension during nocturnal voiding."],
   ["Diabetes, Parkinson disease, neuropathy",
    "These cause neurogenic orthostatic hypotension through autonomic failure, with a minimal heart rate rise on standing."],
   ["Fear, pain and heat exposure",
    "Fear, pain and heat are triggers of vasovagal syncope rather than factors that predispose to micturition syncope."],
   ["Prior infarction, low ejection fraction",
    "Prior infarction and reduced ejection fraction raise concern for cardiogenic syncope, such as nonsustained ventricular tachycardia."]],
  C(27), "risk factors"),

S("Situational syncope", IO4,
  "Which history favors reflex syncope over a seizure?",
  [["Brief prodrome, then rapid recovery",
    "Correct. A brief prodrome of warmth, nausea, sweating and lightheadedness followed by rapid recovery favors reflex syncope over seizure or a primary arrhythmia."],
   ["Tongue biting and long confusion",
    "Tongue biting and prolonged confusion afterward point toward seizure; their absence is what supports syncope."],
   ["Rhythmic jerking and incontinence",
    "Convulsive movements and incontinence unrelated to urination point toward seizure rather than a reflex faint."],
   ["No warning, then palpitations",
    "Abrupt collapse without warning after palpitations points toward cardiogenic syncope from an arrhythmia."]],
  C(27), "differential"),

S("Cardiogenic syncope", IO4,
  "Which are the three types of cardiogenic syncope?",
  [["Arrhythmia, structural and vascular",
    "Correct. Arrhythmias include atrial fibrillation and ventricular tachycardia; structural causes include infarction, cardiomyopathy, heart failure and valve disease; vascular causes include dissection and embolism."],
   ["Reflex, orthostatic and situational",
    "Reflex and orthostatic are separate main groups of syncope, and situational is a type of reflex syncope rather than a cardiogenic type."],
   ["Neurogenic, volume and drug-related",
    "These describe the orthostatic group, split into neurogenic and non-neurogenic causes such as volume loss and medication."],
   ["Toxic, infectious and cardiogenic",
    "These are the causes of hypotension, from overdose to sepsis to cardiomyopathy, rather than the types of cardiogenic syncope."]],
  C(16), "etiology"),

S("Cardiogenic syncope", IO4,
  "Which cause belongs to the vascular group of cardiogenic syncope?",
  [["Pulmonary embolism",
    "Correct. The vascular group comprises peripheral vascular disease, dissection, aneurysm, stroke and pulmonary embolism, and needs emergent testing in the emergency department."],
   ["Atrial fibrillation",
    "Atrial fibrillation belongs to the arrhythmia group, worked up with an electrocardiogram, monitoring, a stress test and cardiology consultation."],
   ["Valvular disease",
    "Valve disease belongs to the structural group, worked up with echocardiography, stress echocardiography and cardiology consultation."],
   ["Cardiomyopathy",
    "Cardiomyopathy is a structural cause, evaluated with echocardiography, and it also produces chronic hypotension."]],
  C(16), "differential"),

S("Cardiogenic syncope", IO4,
  "Which work-up is listed for arrhythmic cardiogenic syncope?",
  [["Electrocardiogram, monitor, stress test",
    "Correct. Arrhythmia is investigated with an electrocardiogram, cardiac monitoring and a stress test, together with cardiology consultation."],
   ["Echocardiogram and stress echocardiogram",
    "Echocardiography and stress echocardiography are the work-up for structural causes such as cardiomyopathy and valve disease."],
   ["Emergent testing in the emergency room",
    "Emergent testing in the emergency department is reserved for vascular causes such as dissection, stroke and pulmonary embolism."],
   ["Tilt-table test and an episode log",
    "A tilt-table test belongs to the tachycardia syndrome and a log to reflex syncope; neither is the arrhythmia work-up."]],
  C(16), "initial test"),

S("Cardiogenic syncope", IO4,
  "Which test evaluates structural cardiogenic syncope?",
  [["Echocardiogram",
    "Correct. Structural causes, infarction, cardiomyopathy, heart failure and valve disease, are evaluated with echocardiography or stress echocardiography plus cardiology consultation."],
   ["Tilt-table test",
    "The tilt-table test diagnoses postural orthostatic tachycardia syndrome and has low sensitivity, so it is not the structural work-up."],
   ["Symptom log",
    "An episode log supports the history-based diagnosis of reflex syncope, not the evaluation of structural heart disease."],
   ["Orthostatic vitals",
    "Supine and standing vital signs diagnose orthostatic hypotension; structural heart disease needs imaging of the heart."]],
  C(16), "gold standard"),

S("Cardiogenic syncope", IO4,
  "How should a suspected vascular cause of syncope be evaluated?",
  [["Emergently, in the emergency department",
    "Correct. Vascular causes, dissection, aneurysm, stroke and pulmonary embolism, need emergent testing in the emergency department plus cardiology consultation."],
   ["Electively, with an outpatient monitor",
    "Outpatient monitoring suits a suspected arrhythmia. Vascular causes such as dissection or embolism need emergent evaluation."],
   ["Routinely, with a symptom log",
    "An episode log supports reflex syncope. A suspected vascular catastrophe cannot wait for a pattern to emerge."],
   ["Later, with a tilt-table test",
    "Tilt-table testing belongs to postural orthostatic tachycardia syndrome and has no role in excluding a vascular emergency."]],
  C(16), "referral"),

S("Cardiogenic syncope", IO4,
  "Which referral applies to all three types of cardiogenic syncope?",
  [["Cardiology consultation",
    "Correct. Arrhythmic, structural and vascular cardiogenic syncope each list cardiology consultation alongside their own tests."],
   ["Neurology consultation",
    "Neurologic input suits autonomic failure or a suspected seizure; each cardiogenic type lists cardiology consultation instead."],
   ["Endocrinology referral",
    "Endocrine disease such as diabetes causes neurogenic orthostatic hypotension; cardiogenic syncope is referred to cardiology."],
   ["Physical therapy referral",
    "Physical therapy has no listed role in cardiogenic syncope, whose work-up pairs cardiac testing with cardiology consultation."]],
  C(16), "referral"),

S("Cardiogenic syncope", IO4,
  "Which history points toward cardiogenic rather than reflex syncope?",
  [["Abrupt collapse without any warning",
    "Correct. Abrupt syncope with minimal prodrome, often after brief palpitations, in someone with coronary disease or reduced ejection fraction points to a cardiac cause."],
   ["Warmth, nausea and sweating beforehand",
    "A prodrome of warmth, nausea, sweating and lightheadedness followed by rapid recovery favors reflex syncope."],
   ["Fainting at the sight of blood",
    "Fear and emotional stress are vasovagal triggers, so a faint at the sight of blood points to reflex syncope."],
   ["Fainting after urinating at night",
    "Fainting during nocturnal voiding is situational micturition syncope, a reflex type rather than a cardiac cause."]],
  C(40), "differential"),

S("Non-hypotensive syncope", IO4,
  "Which cause of syncope is non-hypotensive?",
  [["Hypoglycemia",
    "Correct. Hypoglycemia is listed with seizure, toxic overdose, electrolyte imbalance, hypoxia, anxiety, anemia and the tachycardia syndrome as non-hypotensive causes."],
   ["Volume depletion",
    "Volume depletion lowers pressure on standing and is the typical cause of non-neurogenic orthostatic hypotension."],
   ["Vasovagal reflex",
    "The vasovagal reflex lowers pressure through bradycardia and vasodilation, making it a hypotensive cause of syncope."],
   ["Autonomic failure",
    "Autonomic failure produces neurogenic orthostatic hypotension, a hypotensive cause with a minimal heart rate rise."]],
  C(17), "differential"),

S("Non-hypotensive syncope", IO4,
  "Which pair are both non-hypotensive causes of syncope?",
  [["Seizure and anemia",
    "Correct. Both appear on the non-hypotensive list with hypoglycemia, toxic overdose, electrolyte imbalance, hypoxia, anxiety and the tachycardia syndrome."],
   ["Diarrhea and hemorrhage",
    "Diarrhea and hemorrhage cause volume loss and non-neurogenic orthostatic hypotension, which are hypotensive causes."],
   ["Fear and pain",
    "Fear and pain trigger vasovagal syncope, in which pressure falls through the reflex, so they are hypotensive causes."],
   ["Arrhythmia and embolism",
    "Arrhythmia and pulmonary embolism are cardiogenic causes of syncope within the arrhythmic and vascular groups."]],
  C(17), "differential"),

S("Postural tachycardia syndrome", IO2,
  "How is postural orthostatic tachycardia syndrome defined in adults?",
  [["Heart rate up over 30, or above 120, in 10 minutes",
    "Correct. The heart rate rises by more than 30 beats per minute, or exceeds 120, within 10 minutes of standing, and usually improves when lying down."],
   ["Systolic fall over 20 mmHg in 3 minutes",
    "A systolic fall of more than 20 mmHg within 3 minutes of standing is the orthostatic hypotension criterion, a pressure rather than a heart rate test."],
   ["Heart rate up over 30, or above 120, in 3 minutes",
    "The window for this syndrome is 10 minutes of standing. Three minutes is the window for the orthostatic pressure criteria."],
   ["Heart rate up over 10 when lying down",
    "Symptoms of the syndrome usually improve when lying down; the criteria are about the rise within 10 minutes of standing."]],
  C(18), "manifestation"),

S("Postural tachycardia syndrome", IO5,
  "What heart rate rise defines postural orthostatic tachycardia syndrome in adolescents?",
  [["An increase of 40 beats per minute",
    "Correct. In adolescents the threshold is an increase of 40 beats per minute, higher than the adult rise of more than 30, and adolescence is when the syndrome is often first considered."],
   ["An increase of 30 beats per minute",
    "More than 30 beats per minute is the adult threshold. Adolescents need a larger rise of 40 to meet the definition."],
   ["An increase of 20 beats per minute",
    "Twenty is the systolic pressure fall used for orthostatic hypotension, not a heart rate threshold for the syndrome."],
   ["An increase of 10 beats per minute",
    "Ten is the diastolic pressure fall used for orthostatic hypotension. The adolescent heart rate threshold is 40."]],
  C(18), "test finding"),

S("Postural tachycardia syndrome", IO5,
  "Who is typically affected by postural orthostatic tachycardia syndrome?",
  [["Ages 15 to 50, more often women",
    "Correct. The syndrome affects people aged 15 to 50, usually women more than men, and is associated with Ehlers-Danlos syndrome."],
   ["Over 70, more often men",
    "Older men are typical of situational micturition syncope. This syndrome affects a younger group, more often women."],
   ["Infants, equally both sexes",
    "The syndrome is described in people aged 15 to 50, usually women more than men, rather than in infants of either sex."],
   ["Over 60, with Parkinson disease",
    "Parkinson disease in older adults causes neurogenic orthostatic hypotension, with a pressure fall and minimal heart rate rise."]],
  C(18), "epidemiology"),

S("Postural tachycardia syndrome", IO2,
  "Which condition is associated with postural orthostatic tachycardia syndrome?",
  [["Ehlers-Danlos syndrome",
    "Correct. Ehlers-Danlos syndrome is the association given for the syndrome, which mostly affects women aged 15 to 50."],
   ["Parkinson disease",
    "Parkinson disease is an example cause of neurogenic orthostatic hypotension, where the heart rate rises only minimally."],
   ["Multiple system atrophy",
    "Multiple system atrophy causes neurogenic orthostatic hypotension through autonomic failure, not the tachycardia syndrome."],
   ["Long-standing diabetes",
    "Long-standing diabetes with neuropathy causes diabetic autonomic neuropathy and neurogenic orthostatic hypotension."]],
  C(18), "risk factors"),

S("Postural tachycardia syndrome", IO2,
  "Which test diagnoses postural orthostatic tachycardia syndrome?",
  [["Tilt-table test",
    "Correct. The tilt-table test is the listed diagnostic test, with a sensitivity of about 40% and a specificity above 80%."],
   ["Echocardiogram",
    "Echocardiography evaluates structural cardiogenic syncope such as cardiomyopathy and valve disease, not the tachycardia syndrome."],
   ["Stress test",
    "A stress test is part of the arrhythmia work-up for cardiogenic syncope, together with an electrocardiogram and monitoring."],
   ["Episode log",
    "An episode log supports the history-based diagnosis of reflex syncope rather than confirming the tachycardia syndrome."]],
  C(18), "gold standard"),

S("Postural tachycardia syndrome", IO2,
  "With a sensitivity near 40% and specificity above 80%, what does a negative tilt-table test mean?",
  [["It does little to exclude the syndrome",
    "Correct. Low sensitivity means many patients with the syndrome test negative, so a negative result tells almost nothing, while a positive result carries more weight."],
   ["It reliably rules the syndrome out",
    "Ruling out needs high sensitivity. At about 40%, most of the weight sits with a positive result instead."],
   ["It confirms autonomic failure",
    "Autonomic failure is shown by a pressure fall with a minimal heart rate rise on orthostatic vitals, not by a negative tilt test."],
   ["It points to a cardiac cause",
    "A negative tilt test says nothing about the heart. Cardiac causes are pursued with an electrocardiogram, monitoring or echocardiography."]],
  C(18), "test finding"),

S("Postural tachycardia syndrome", IO2,
  "What is first-line treatment for postural orthostatic tachycardia syndrome?",
  [["More water and salt intake",
    "Correct. Increasing water and salt intake comes first, and fludrocortisone is the drug that is best suited to the syndrome."],
   ["Daily midodrine therapy",
    "Midodrine is best with neurogenic syncope, not with the tachycardia syndrome, whose first step is water and salt."],
   ["Vasopressor infusion",
    "Vasopressor infusions are for the emergency department and intensive care only, not for an outpatient tachycardia syndrome."],
   ["Strict fluid restriction",
    "Fluid restriction runs opposite to the treatment, which increases water and salt intake."]],
  C(18), "first-line"),

S("Drug therapy", IO2,
  "Which drug is best suited to postural orthostatic tachycardia syndrome?",
  [["Fludrocortisone",
    "Correct. Fludrocortisone is best with the tachycardia syndrome; because it causes salt and water retention it is avoided in heart failure."],
   ["Midodrine",
    "Midodrine is best with neurogenic syncope and is avoided with supine hypertension, severe heart disease and chronic kidney disease."],
   ["Droxidopa",
    "Droxidopa has mild efficacy, is better with supine hypertension, and is usually an adjunct to midodrine or fludrocortisone."],
   ["Phenylephrine",
    "Phenylephrine is among the pressors used only in the emergency department and intensive care, not for an outpatient syndrome."]],
  C(23), "agent/regimen"),

S("Drug therapy", IO2,
  "Which drug is best used with neurogenic syncope?",
  [["Midodrine",
    "Correct. Midodrine is best with neurogenic syncope, but it is avoided with supine hypertension, severe heart disease and chronic kidney disease."],
   ["Fludrocortisone",
    "Fludrocortisone is best with postural orthostatic tachycardia syndrome and is avoided in heart failure."],
   ["Droxidopa",
    "Droxidopa has only mild efficacy and is usually added to midodrine or fludrocortisone rather than chosen first."],
   ["Vasopressin",
    "Vasopressin is among the pressors reserved for the emergency department and intensive care, not outpatient neurogenic syncope."]],
  C(23), "agent/regimen"),

S("Drug therapy", IO2,
  "In which setting should midodrine be avoided?",
  [["Supine hypertension",
    "Correct. Midodrine is avoided with supine hypertension (high pressure while lying flat), severe heart disease and chronic kidney disease, despite being best with neurogenic syncope."],
   ["Diabetic neuropathy",
    "Diabetic autonomic neuropathy causes neurogenic orthostatic hypotension, exactly the setting in which midodrine is best."],
   ["Parkinson disease",
    "Parkinson disease is an example cause of neurogenic orthostatic hypotension, where midodrine is the best listed drug."],
   ["Multiple system atrophy",
    "Multiple system atrophy is a neurogenic cause, and neurogenic syncope is where midodrine is best used."]],
  C(23), "avoid"),

S("Drug therapy", IO2,
  "Which comorbidity is a reason to avoid midodrine?",
  [["Chronic kidney disease",
    "Correct. Chronic kidney disease joins supine hypertension and severe heart disease as the settings in which midodrine is avoided."],
   ["Long-standing diabetes",
    "Long-standing diabetes can cause neurogenic orthostatic hypotension, the condition midodrine is best suited to."],
   ["Ehlers-Danlos syndrome",
    "Ehlers-Danlos syndrome is associated with the tachycardia syndrome; it is not a listed reason to avoid midodrine."],
   ["Recent diarrheal illness",
    "Diarrhea causes volume depletion, which is managed by treating the underlying cause; it is not a listed midodrine contraindication."]],
  C(23), "avoid"),

S("Drug therapy", IO2,
  "Why is fludrocortisone avoided in heart failure?",
  [["It causes salt and water retention",
    "Correct. Fludrocortisone causes salt and water retention, which helps the tachycardia syndrome but is why it is avoided in congestive heart failure."],
   ["It causes supine hypertension",
    "Supine hypertension is the setting in which midodrine is avoided and droxidopa is preferred, not the stated fludrocortisone concern."],
   ["It slows the heart rate sharply",
    "Heart rate slowing is not the listed problem. The concern in heart failure is the salt and water it retains."],
   ["It worsens kidney function",
    "Chronic kidney disease is a listed reason to avoid midodrine. Fludrocortisone is avoided in heart failure because of fluid retention."]],
  C(23), "avoid"),

S("Drug therapy", IO2,
  "Which drug is preferred when supine hypertension limits therapy?",
  [["Droxidopa",
    "Correct. Droxidopa has mild efficacy but is better with supine hypertension (high pressure while lying flat), the setting in which midodrine is avoided."],
   ["Midodrine",
    "Midodrine is avoided with supine hypertension, severe heart disease and chronic kidney disease, even though it is best with neurogenic syncope."],
   ["Phenylephrine",
    "Phenylephrine is a pressor used only in the emergency department and intensive care, not an outpatient choice."],
   ["Norepinephrine",
    "Norepinephrine is among the pressors reserved for the emergency department and intensive care."]],
  C(23), "escalation"),

S("Drug therapy", IO2,
  "How is droxidopa usually used?",
  [["As an adjunct to midodrine or fludrocortisone",
    "Correct. Droxidopa has only mild efficacy, so it is usually added to midodrine or fludrocortisone, and it is the better choice when supine hypertension is present."],
   ["As sole first-line therapy for fainting",
    "First-line care is removing the cause or trigger and slow position changes; droxidopa is a mild adjunct rather than a first-line agent."],
   ["As an emergency infusion in intensive care",
    "The emergency and intensive care drugs are epinephrine, norepinephrine, dopamine, phenylephrine and vasopressin."],
   ["As a substitute for trigger avoidance",
    "Reflex syncope is managed by trigger avoidance and safety precautions, which a drug does not replace."]],
  C(23), "escalation"),

S("Drug therapy", IO3,
  "Where are vasopressors such as norepinephrine and vasopressin used for hypotension?",
  [["Emergency department and intensive care only",
    "Correct. Epinephrine, norepinephrine, dopamine, phenylephrine and vasopressin are listed for the emergency department and intensive care unit only."],
   ["Primary care for chronic hypotension",
    "Chronic hypotension in primary care is managed by treating its cause and education; pressors are not outpatient drugs."],
   ["Home use for recurrent reflex syncope",
    "Recurrent reflex syncope is treated with trigger avoidance and safety precautions rather than pressors at home."],
   ["Outpatient use for the tachycardia syndrome",
    "The tachycardia syndrome is treated with water, salt and fludrocortisone, not with vasopressors."]],
  C(23), "escalation"),

S("Hypotension treatment", IO2,
  "Why is patient education central to hypotension management?",
  [["Understanding is the key to compliance",
    "Correct. A patient who understands why the hypotension happens is far more likely to follow slow position changes, trigger avoidance and medication changes."],
   ["It replaces the need to find a cause",
    "Education supports treatment of the cause rather than replacing it; the real diagnosis still has to be found and treated."],
   ["It allows vasopressors to be stopped",
    "Vasopressors belong in the emergency department and intensive care; education matters for the outpatient measures patients carry out themselves."],
   ["It shortens the orthostatic test",
    "Education does not change the diagnostic criteria, which still require readings within 3 minutes of standing."]],
  C(23), "education"),

S("Orthostatic treatment", IO2,
  "Which advice suits a patient with orthostatic syncope?",
  [["Change position slowly",
    "Correct. Slow positional changes are listed treatment for orthostatic syncope, alongside treating the underlying cause, the real diagnosis."],
   ["Stand up quickly to adapt",
    "Standing abruptly is the provoking event in orthostatic syncope; the advice is to change position slowly."],
   ["Restrict fluids each morning",
    "Restricting fluid worsens volume depletion, a common cause of non-neurogenic orthostatic hypotension."],
   ["Avoid all physical activity",
    "Activity itself is not the problem; the advice targets the moment of standing, with slow positional changes."]],
  C(13), "education"),

S("Non-neurogenic orthostatic", IO5,
  "Which of these is a cause of non-neurogenic orthostatic hypotension?",
  [["Advanced age",
    "Correct. Advanced age is listed with hypovolemia and medication as a cause of non-neurogenic orthostatic hypotension in the elderly."],
   ["Ehlers-Danlos syndrome",
    "Ehlers-Danlos syndrome is associated with postural orthostatic tachycardia syndrome, which affects ages 15 to 50."],
   ["Emotional triggers",
    "Emotional stress and fear are triggers of vasovagal syncope, which is most commonly seen in young women."],
   ["Autoimmune disorders",
    "Autoimmune disorders are listed behind neurogenic orthostatic hypotension, the form with a minimal heart rate rise."]],
  C(12), "epidemiology"),

S("Syncope definitions", IO1,
  "What is the expected course of a syncopal episode?",
  [["Brief and self-limited",
    "Correct. Syncope is by definition transient and self-limited, followed by spontaneous recovery, which is part of what separates it from seizure."],
   ["Prolonged coma needing support",
    "Prolonged unconsciousness needing support falls outside the definition of syncope, which is brief and self-limited."],
   ["Recovery only after glucose",
    "Recovery after glucose describes hypoglycemia, a non-hypotensive cause, rather than the spontaneous recovery of syncope."],
   ["Recovery with lasting confusion",
    "Prolonged confusion afterward points toward seizure; syncope ends in rapid, complete recovery."]],
  C(8), "prognosis"),

]
