# -*- coding: utf-8 -*-
"""CMS I Exam 3, Lecture 16 -- objective set B.

The conditions: tinnitus, canal and middle ear masses, the acquired
sensorineural causes, the inner ear syndromes, the retrocochlear and central
causes, and non-organic loss.

Grounded in the deck (Prof. Monique Jaquith, 3 September 2026). The
types-of-vertigo comparison was flagged as a chart to know outright, so the
features that separate those five entities are asked directly.

FIVE options. Correct answer authored FIRST; cms_e3_partition.py rotates it.
"""
D = "16. Disorders of Inner Ear 2026 - Dr. Jaquith.pptx, Slide %d"
IO_A = ("a — Inner ear, balance and hearing loss conditions: etiologies, epidemiology, risk "
        "factors, clinical manifestations, differential diagnosis, diagnostic testing, "
        "management, referrals, patient education, prognosis")
IO_G = ("g — Identify medical care strategies for disorders of the inner ear, balance and "
        "hearing loss by population: infant, child, adolescent, adult")

QUESTIONS = [
 # ---------------------------- presbycusis ----------------------------
 dict(topic="Presbycusis", io=IO_A, lead="mechanism", cite=D % 60,
  q="Which two changes underlie age-related hearing loss?",
  opts=[["Hair cell loss and cochlear nerve degeneration", "Correct."],
        ["Stapes fixation and drum thickening", "Both block sound mechanically rather than damaging the cochlea."],
        ["Wax accumulation and canal narrowing", "Those are conductive and reversible."],
        ["Middle ear fluid and tube blockage", "Both are reversible obstructions rather than cell loss."],
        ["Vestibular nerve inflammation", "That affects balance rather than hearing."]]),

 dict(topic="Presbycusis", io=IO_A, lead="defining feature", cite=D % 60,
  q="Which description matches the pattern of age-related hearing loss?",
  opts=[["Bilateral, symmetrical and gradual", "Correct."],
        ["Unilateral and sudden", "That describes sudden sensorineural loss."],
        ["Fluctuating and unilateral", "That fits an inner ear syndrome."],
        ["Bilateral but stepwise", "Stepwise deterioration suggests an autoimmune cause."],
        ["Unilateral and progressive", "That raises concern about a retrocochlear cause."]]),

 dict(topic="Presbycusis", io=IO_G, lead="patient education", cite=D % 61,
  q="What is the most useful communication advice for the family of a patient with age-related hearing loss?",
  opts=[["Face the patient and do not shout", "Correct — discrimination rather than volume is the problem."],
        ["Speak much louder than usual", "Volume alone does not restore word clarity."],
        ["Speak from another room to test them", "That makes communication harder."],
        ["Use only written notes", "Speech remains useful with the right technique."],
        ["Speak very quickly to keep attention", "Slower, clearer speech helps more."]]),

 # ------------------------------ tinnitus ------------------------------
 dict(topic="Tinnitus", io=IO_A, lead="defining feature", cite=D % 44,
  q="What is tinnitus?",
  opts=[["Sound perceived with no external source", "Correct — ringing, buzzing, humming or hissing."],
        ["Reduced hearing at high frequencies", "That is a hearing loss, not tinnitus."],
        ["A spinning sensation", "That is vertigo."],
        ["Pain within the ear", "That is otalgia."],
        ["Discharge from the ear canal", "That is otorrhoea."]]),

 dict(topic="Tinnitus", io=IO_A, lead="defining feature", cite=D % 44,
  q="What distinguishes objective tinnitus from the subjective form?",
  opts=[["The examiner can hear it too", "Correct, and it is uncommon."],
        ["It occurs only at night", "Timing is not the distinction."],
        ["It is always bilateral", "Laterality is not the distinction."],
        ["It never accompanies hearing loss", "Tinnitus commonly accompanies hearing loss."],
        ["It responds to antibiotics", "Response to treatment is not the distinction."]]),

 dict(topic="Tinnitus", io=IO_A, lead="next step", cite=D % 45,
  q="Which pattern of tinnitus is a red flag requiring investigation?",
  opts=[["Unilateral or pulsatile", "Correct."],
        ["Bilateral and constant", "That is the common, less concerning pattern."],
        ["Worse in a silent room", "Everyone notices head noise in silence."],
        ["Present only after loud music", "That is a temporary effect of noise exposure."],
        ["Described as ringing rather than buzzing", "The described quality is not a red flag."]]),

 dict(topic="Tinnitus", io=IO_A, lead="treatment", cite=D % 46,
  q="What is known about drug treatment for tinnitus?",
  opts=[["No drug has outperformed placebo", "Correct — biofeedback and masking noises may help instead."],
        ["Antibiotics resolve most cases", "There is no infection to treat."],
        ["Corticosteroids are curative", "They are not a cure."],
        ["Antihistamines are first-line", "No antihistamine has an established role here."],
        ["Diuretics eliminate it", "Diuretics do not abolish the noise."]]),

 dict(topic="Tinnitus", io=IO_A, lead="patient education", cite=D % 46,
  q="Which lifestyle measure is advised for a patient with tinnitus?",
  opts=[["Avoid stimulants and loud noise", "Correct, along with daily exercise and adequate rest."],
        ["Increase caffeine to stay alert", "Stimulants are to be avoided."],
        ["Spend time in complete silence daily", "Silence makes head noise more noticeable."],
        ["Avoid all physical exercise", "Daily exercise is advised."],
        ["Sleep less to reduce awareness", "Adequate rest is advised."]]),

 # -------------------- canal and middle ear masses --------------------
 dict(topic="Exostosis", io=IO_A, lead="risk factor", cite=D % 48,
  q="Which exposure produces bony growths in the external canal?",
  opts=[["Repeated cold water exposure", "Correct — divers and surfers."],
        ["Repeated loud noise exposure", "Noise damages hair cells instead."],
        ["Repeated air travel", "Pressure change causes barotrauma."],
        ["Chronic antibiotic drop use", "Drops do not cause bony growth."],
        ["High altitude living", "Altitude is not a risk factor."]]),

 dict(topic="Exostosis", io=IO_A, lead="defining feature", cite=D % 48,
  q="How are canal exostoses characteristically distributed?",
  opts=[["Bilaterally and symmetrically", "Correct."],
        ["Unilaterally on the dominant side", "Both ears meet the same cold water, so both are affected."],
        ["Randomly on one side only", "The distribution is symmetrical rather than random."],
        ["Only in the bony inner canal of one ear", "They are bilateral and symmetrical."],
        ["Only on the auricle", "They are within the canal."]]),

 dict(topic="Glomus tumour", io=IO_A, lead="defining feature", cite=D % 50,
  q="Which combination of findings characterises a glomus tumour?",
  opts=[["Conductive hearing loss with pulsatile tinnitus", "Correct."],
        ["Sensorineural loss with episodic vertigo", "That fits an inner ear syndrome."],
        ["Itching with white curd-like debris", "That fits fungal canal infection."],
        ["Painless discharge with keratin debris", "That fits cholesteatoma."],
        ["Bilateral symmetrical high-frequency loss", "That fits age-related loss."]]),

 dict(topic="Glomus tumour", io=IO_A, lead="prognosis", cite=D % 50,
  q="Paralysis of which cranial nerves may accompany a glomus tumour?",
  opts=[["The ninth, tenth and eleventh", "Correct."],
        ["The first and second", "Smell and vision are not involved."],
        ["The third, fourth and sixth", "Eye movement nerves are not involved."],
        ["The fifth alone", "The trigeminal nerve is involved in acoustic neuroma, not here."],
        ["The twelfth alone", "The hypoglossal nerve is not among those affected."]]),

 # -------------------- acquired sensorineural --------------------
 dict(topic="Ototoxicity", io=IO_A, lead="etiology", cite=D % 52,
  q="Which drug class is the most ototoxic and the most commonly implicated?",
  opts=[["Aminoglycosides", "Correct — peak levels are monitored for this reason."],
        ["Penicillins", "Not implicated in this way."],
        ["Macrolides", "Not the class named as most ototoxic."],
        ["Antihistamines", "Antihistamines are not named as ototoxic."],
        ["Proton pump inhibitors", "These are not named as ototoxic."]]),

 dict(topic="Ototoxicity", io=IO_A, lead="etiology", cite=D % 52,
  q="Besides aminoglycosides, which agents are named as ototoxic?",
  opts=[["Furosemide, aspirin and platinum chemotherapy", "Correct."],
        ["Amoxicillin, cephalexin and doxycycline", "These are not the named ototoxic agents."],
        ["Metformin, insulin and glipizide", "These are not named."],
        ["Warfarin, heparin and aspirin alone", "Aspirin is named, but the other two are not."],
        ["Paracetamol, ibuprofen and codeine", "These are not the named agents."]]),

 dict(topic="Ototoxicity", io=IO_A, lead="next step", cite=D % 53,
  q="A drug is identified as ototoxic. Which other organ should be considered?",
  opts=[["The kidney", "Correct — ototoxic drugs are frequently nephrotoxic and vice versa."],
        ["The liver", "Liver injury is not the toxicity paired with hearing damage."],
        ["The pancreas", "No pancreatic toxicity is described for these agents."],
        ["The thyroid", "No thyroid toxicity is described for these agents."],
        ["The spleen", "The spleen is not affected by these agents."]]),

 dict(topic="Ototoxicity", io=IO_A, lead="defining feature", cite=D % 52,
  q="What pattern of hearing loss does ototoxicity produce?",
  opts=[["Bilateral sensorineural", "Correct."],
        ["Unilateral conductive", "Not the pattern produced."],
        ["Unilateral sensorineural", "The loss is bilateral."],
        ["Bilateral conductive", "The loss is sensorineural."],
        ["Fluctuating low-frequency", "That fits a different inner ear condition."]]),

 dict(topic="Noise-induced hearing loss", io=IO_A, lead="defining feature", cite=D % 54,
  q="What is a temporary threshold shift?",
  opts=[["Hearing loss recovering in twenty-four to forty-eight hours", "Correct, with fullness and a sensation of crickets."],
        ["Permanent loss after a single exposure", "That is a permanent threshold shift."],
        ["Loss that fluctuates over months", "Not the described phenomenon."],
        ["Loss confined to one ear", "The shift is not defined by laterality."],
        ["Loss that only affects low tones", "It is not defined by frequency."]]),

 dict(topic="Noise-induced hearing loss", io=IO_A, lead="risk factor", cite=D % 55,
  q="At approximately which sound level does pain and injury occur?",
  opts=[["One hundred and twenty decibels", "Correct."],
        ["Sixty decibels", "Ordinary conversation, well below the injury level."],
        ["Eighty decibels", "Damage becomes possible after about two hours at this level."],
        ["Ninety-five decibels", "Damage becomes possible after about fifty minutes."],
        ["One hundred and five decibels", "Damage becomes possible in under five minutes."]]),

 dict(topic="Noise-induced hearing loss", io=IO_A, lead="epidemiology", cite=D % 54,
  q="Which body regulates occupational noise exposure?",
  opts=[["The Occupational Safety and Health Administration", "Correct."],
        ["The Food and Drug Administration", "It regulates drugs and devices."],
        ["The Centers for Disease Control and Prevention", "It does not set these exposure limits."],
        ["The Environmental Protection Agency", "It regulates environmental rather than workplace exposure."],
        ["The Federal Aviation Administration", "It regulates aviation, not workplace noise generally."]]),

 dict(topic="Acoustic trauma", io=IO_A, lead="defining feature", cite=D % 56,
  q="How does acoustic trauma differ from ordinary noise-induced hearing loss?",
  opts=[["A single loud noise causes immediate loss", "Correct, and it may perforate the drum."],
        ["It only occurs over many years", "That describes cumulative noise exposure."],
        ["It never affects hearing", "Hearing loss is the defining consequence."],
        ["It is always reversible", "It may be permanent."],
        ["It only affects children", "Age is not a defining feature."]]),

 dict(topic="Acoustic trauma", io=IO_A, lead="prognosis", cite=D % 57,
  q="What is the characteristic consequence of a penetrating ear injury involving the stapes?",
  opts=[["Profound sensorineural hearing loss", "Correct — such injuries usually involve stapes subluxation."],
        ["Mild conductive loss only", "The loss is profound and sensorineural."],
        ["No hearing consequence", "There is a serious consequence."],
        ["Temporary loss for two days", "The loss is not temporary."],
        ["Loss confined to low frequencies", "The loss is not frequency-limited in that way."]]),

 dict(topic="Perilymphatic fistula", io=IO_A, lead="mechanism", cite=D % 63,
  q="What is a perilymphatic fistula?",
  opts=[["An abnormal opening between inner and middle ear", "Correct — at the round or oval window."],
        ["A hole in the tympanic membrane", "That is a drum perforation."],
        ["A blocked eustachian tube", "That is tube dysfunction."],
        ["A tumour of the eighth nerve", "That is an acoustic neuroma."],
        ["Inflammation of the labyrinth", "That is labyrinthitis."]]),

 dict(topic="Perilymphatic fistula", io=IO_A, lead="risk factor", cite=D % 63,
  q="Which events are named as causes of an acquired perilymphatic fistula?",
  opts=[["Barotrauma, temporal bone trauma or stapes surgery", "Correct."],
        ["Loud noise exposure over years", "That produces noise-induced loss."],
        ["Ageing", "That produces presbycusis."],
        ["Aminoglycoside use", "That produces ototoxicity."],
        ["Viral upper respiratory infection", "That is not a named cause."]]),

 dict(topic="Perilymphatic fistula", io=IO_A, lead="defining feature", cite=D % 64,
  q="Which detail in the history points to a perilymphatic fistula?",
  opts=[["An audible pop at the moment of onset", "Correct, with sudden loss and vertigo after straining or barotrauma."],
        ["A gradual decline over ten years", "That fits age-related loss."],
        ["Symptoms only in noisy environments", "Not a feature of this condition."],
        ["Itching in the canal", "That fits canal irritation."],
        ["Discharge from the ear", "Discharge is not a feature."]]),

 dict(topic="Autoimmune sensorineural loss", io=IO_A, lead="defining feature", cite=D % 65,
  q="What course does autoimmune sensorineural hearing loss typically follow?",
  opts=[["Bilateral and progressive, in steps", "Correct — periods of deterioration alternating with stabilisation."],
        ["Unilateral and sudden", "That fits sudden sensorineural loss."],
        ["Bilateral and perfectly steady", "The stepwise pattern is characteristic."],
        ["Unilateral and fluctuating", "Not the described course."],
        ["Reversible within a week", "It is not reversible in that way."]]),

 dict(topic="Autoimmune sensorineural loss", io=IO_A, lead="next step", cite=D % 66,
  q="What is the appropriate approach to autoimmune screening in sensorineural hearing loss?",
  opts=[["Test only when the picture suggests it", "Correct — routine screening is not warranted."],
        ["Screen every patient at first presentation", "Routine screening is not warranted."],
        ["Screen only patients over sixty-five", "Routine screening is not warranted at any age."],
        ["Screen only children", "Children are not singled out for this screening."],
        ["Never test for autoimmune causes", "Testing has a place when the picture suggests it."]]),

 dict(topic="Syphilitic sensorineural loss", io=IO_A, lead="diagnostic technique", cite=D % 68,
  q="Which tests should be ordered when syphilis is suspected as a cause of hearing loss?",
  opts=[["Fluorescent treponemal antibody and microhaemagglutination assays", "Correct."],
        ["The Venereal Disease Research Laboratory test", "It is specifically described as not helpful here."],
        ["A full blood count", "Non-specific."],
        ["An autoimmune panel", "That addresses a different cause."],
        ["A thyroid function test", "Not relevant to this diagnosis."]]),

 dict(topic="Syphilitic sensorineural loss", io=IO_A, lead="defining feature", cite=D % 68,
  q="Why is syphilis specifically sought as a cause of sensorineural hearing loss?",
  opts=[["It is treatable and mimics another condition exactly", "Correct — its presentation is often indistinguishable."],
        ["It is the commonest cause overall", "It is uncommon."],
        ["It always causes conductive loss", "The loss is sensorineural."],
        ["It only affects children", "Both congenital and acquired forms occur."],
        ["It resolves without treatment", "Treatment is required."]]),

 dict(topic="Syphilitic sensorineural loss", io=IO_A, lead="treatment", cite=D % 68,
  q="What is the treatment for syphilitic sensorineural hearing loss?",
  opts=[["An antibiotic with systemic corticosteroids", "Correct."],
        ["Corticosteroids alone", "The infection must be treated."],
        ["An antifungal", "The organism is bacterial."],
        ["A hearing aid alone", "The underlying infection needs treating."],
        ["Observation", "Treatment is required."]]),

 dict(topic="Hereditary sensorineural loss", io=IO_A, lead="defining feature", cite=D % 71,
  q="Which syndromes are named as hereditary causes of sensorineural hearing loss?",
  opts=[["Waardenburg, Alport and Usher", "Correct."],
        ["Marfan, Ehlers-Danlos and Turner", "These are connective tissue and chromosomal disorders."],
        ["Down, Edwards and Patau", "These are trisomy syndromes."],
        ["Cushing, Addison and Conn", "These are endocrine disorders."],
        ["Crohn, Whipple and coeliac", "These are gastrointestinal disorders."]]),

 dict(topic="Sudden sensorineural hearing loss", io=IO_A, lead="defining feature", cite=D % 79,
  q="How is sudden sensorineural hearing loss best characterised?",
  opts=[["A syndrome rather than a disease", "Correct — the exact cause is rarely certain."],
        ["A single well-defined disease", "It is explicitly described as a syndrome."],
        ["A form of conductive loss", "The loss is sensorineural."],
        ["A normal variant", "It is a genuine clinical problem."],
        ["A purely psychological phenomenon", "It has organic causes."]]),

 dict(topic="Sudden sensorineural hearing loss", io=IO_A, lead="etiology", cite=D % 79,
  q="Which causes underlie sudden sensorineural hearing loss?",
  opts=[["Viral or vascular", "Correct; retrocochlear pathology is rare."],
        ["Bacterial or fungal", "No infective organism is named as the usual cause."],
        ["Traumatic or toxic only", "Trauma and drugs cause hearing loss, but not this syndrome."],
        ["Congenital only", "Onset is sudden in an established ear."],
        ["Allergic only", "Not a named cause."]]),

 dict(topic="Sudden sensorineural hearing loss", io=IO_A, lead="next step", cite=D % 79,
  q="What does sudden sensorineural hearing loss demand?",
  opts=[["Prompt specialist referral", "Correct — the corticosteroid window is short."],
        ["Review in three months", "Delay closes the treatment window."],
        ["Reassurance alone", "It requires urgent assessment."],
        ["A trial of ear drops", "Drops do not reach the inner ear."],
        ["Immediate surgery", "Surgery is not the first response."]]),

 # ------------------------ inner ear syndromes ------------------------
 dict(topic="Meniere disease", io=IO_A, lead="defining feature", cite=D % 69,
  q="Which frequency range is affected in the hearing loss of this inner ear syndrome with fluctuating loss, fullness and low-tone tinnitus?",
  opts=[["Low frequencies", "Correct — that is distinctive against most sensorineural causes."],
        ["High frequencies", "High-frequency loss fits age-related and noise-induced causes."],
        ["Middle frequencies only", "Not the described pattern."],
        ["All frequencies equally", "The loss is not uniform."],
        ["No frequencies; hearing is normal", "Hearing is affected."]]),

 dict(topic="Meniere disease", io=IO_A, lead="defining feature", cite=D % 69,
  q="How long does a typical vertigo attack last in Meniere disease?",
  opts=[["Several hours", "Correct — minutes to hours, distinguishing it from other causes."],
        ["Ten to sixty seconds", "That fits benign positional vertigo."],
        ["Several days to weeks", "That fits labyrinthitis or vestibular neuronitis."],
        ["A few minutes at most", "The attacks run longer."],
        ["Continuously for months", "The attacks are episodic."]]),

 dict(topic="Meniere disease", io=IO_A, lead="defining feature", cite=D % 69,
  q="Which sensation in the ear accompanies the vertigo and hearing loss of Meniere disease?",
  opts=[["Fullness", "Correct, on the affected side."],
        ["Itching", "That fits canal irritation."],
        ["Sharp stabbing pain", "Pain is not a feature."],
        ["Burning", "Burning is not among the described sensations."],
        ["Numbness of the auricle", "Sensation of the auricle is unaffected."]]),

 dict(topic="Benign paroxysmal positional vertigo", io=IO_A, lead="defining feature", cite=D % 91,
  q="How long does the vertigo of benign paroxysmal positional vertigo last?",
  opts=[["Ten to sixty seconds", "Correct — beyond a minute, another diagnosis should be considered."],
        ["Several hours", "That fits Meniere disease."],
        ["Several days", "That fits vestibular neuronitis."],
        ["Several weeks continuously", "The episodes are brief."],
        ["Under one second", "The episodes last longer than that."]]),

 dict(topic="Benign paroxysmal positional vertigo", io=IO_A, lead="mechanism", cite=D % 92,
  q="Which mechanism is thought to cause most benign paroxysmal positional vertigo?",
  opts=[["Debris in the posterior semicircular canal", "Correct."],
        ["Inflammation of the vestibular nerve", "That is vestibular neuronitis."],
        ["A tumour of the eighth nerve", "That is an acoustic neuroma."],
        ["Excess fluid in the inner ear", "That mechanism belongs to a different condition."],
        ["Fixation of the stapes", "That is a conductive problem."]]),

 dict(topic="Benign paroxysmal positional vertigo", io=IO_A, lead="treatment", cite=D % 93,
  q="Which manoeuvre treats benign paroxysmal positional vertigo?",
  opts=[["The Epley manoeuvre", "Correct — it repositions the debris."],
        ["The Dix-Hallpike manoeuvre", "That is the diagnostic test."],
        ["The Valsalva manoeuvre", "That equalises middle ear pressure."],
        ["The Weber test", "That is a hearing test."],
        ["Insufflation", "That assesses drum mobility."]]),

 dict(topic="Labyrinthitis", io=IO_A, lead="defining feature", cite=D % 95,
  q="Which feature distinguishes labyrinthitis from vestibular neuronitis?",
  opts=[["Hearing is affected", "Correct — that single difference separates them."],
        ["Vertigo is present", "Both cause vertigo."],
        ["Onset is sudden", "Both are sudden in onset."],
        ["Nausea occurs", "Both may cause nausea."],
        ["It lasts days", "Both last days."]]),

 dict(topic="Labyrinthitis", io=IO_A, lead="treatment", cite=D % 95,
  q="Which medication is used during the acute vertigo of labyrinthitis?",
  opts=[["Meclizine", "Correct — oral diazepam is the alternative."],
        ["Amoxicillin", "Antibiotics are added only if bacterial features are present."],
        ["Furosemide", "Not used for acute vertigo here."],
        ["Aspirin", "Not used for acute vertigo."],
        ["Gentamicin", "It is ototoxic and not used this way."]]),

 dict(topic="Vestibular neuronitis", io=IO_A, lead="mechanism", cite=D % 96,
  q="Which structure is inflamed in vestibular neuronitis?",
  opts=[["The vestibular portion of the eighth cranial nerve", "Correct."],
        ["The membranous labyrinth", "That is labyrinthitis."],
        ["The tympanic membrane", "The drum is not involved."],
        ["The mastoid air cells", "That is mastoiditis."],
        ["The stapes", "That is otosclerosis."]]),

 dict(topic="Vestibular neuronitis", io=IO_A, lead="prognosis", cite=D % 96,
  q="What is the expected course of vestibular neuronitis?",
  opts=[["Benign and self-limiting", "Correct, though balance symptoms may last months."],
        ["Progressive and permanent", "It is self-limiting."],
        ["Fatal without treatment", "It is benign."],
        ["Recurrent every week for life", "That is not the described course."],
        ["Resolving within one hour", "It lasts days with gradual improvement."]]),

 # ---------------------- retrocochlear and central ----------------------
 dict(topic="Acoustic neuroma", io=IO_A, lead="defining feature", cite=D % 72,
  q="Which symptom is characteristic of an acoustic neuroma?",
  opts=[["Poor word understanding for the degree of loss", "Correct — discrimination is worse than the tone loss predicts."],
        ["Hearing better in background noise", "That fits otosclerosis."],
        ["Bilateral symmetrical high-frequency loss", "That fits age-related loss."],
        ["Itching with discharge", "Both are canal findings, and the canal is normal here."],
        ["Pain on moving the tragus", "That sign belongs to external canal infection."]]),

 dict(topic="Acoustic neuroma", io=IO_A, lead="treatment", cite=D % 75,
  q="Which management options exist for an acoustic neuroma?",
  opts=[["Observation with annual imaging, surgery or radiation", "Correct."],
        ["Antibiotics alone", "It is a tumour, not an infection."],
        ["Ear drops alone", "Drops do not reach it."],
        ["Tympanostomy tubes", "Tubes address middle ear ventilation."],
        ["A hearing aid alone", "That does not address the tumour."]]),

 dict(topic="Vertebrobasilar occlusion", io=IO_A, lead="clinical manifestation", cite=D % 77,
  q="Which combination of findings accompanies vertigo in vertebrobasilar occlusion?",
  opts=[["Facial paralysis with crossed sensory loss", "Correct — with gaze paralysis and Horner syndrome."],
        ["Itching and canal discharge", "Those indicate canal infection."],
        ["Fullness and low-tone tinnitus", "Those fit an inner ear syndrome."],
        ["Pain on moving the tragus", "That indicates canal infection."],
        ["Bilateral high-frequency loss", "That fits age-related loss."]]),

 dict(topic="Vertebrobasilar occlusion", io=IO_A, lead="diagnostic technique", cite=D % 87,
  q="Which study is used to assess the vessels in suspected vertebrobasilar disease?",
  opts=[["Magnetic resonance angiography", "Correct, alongside carotid Doppler studies."],
        ["Tympanometry", "That assesses the middle ear."],
        ["Pure tone audiometry", "That measures hearing."],
        ["The Dix-Hallpike manoeuvre", "That provokes positional vertigo."],
        ["Otoscopy", "That examines the canal and drum."]]),

 dict(topic="Vertebrobasilar occlusion", io=IO_A, lead="epidemiology", cite=D % 85,
  q="What is the commonest non-vestibular cause of dizziness and balance loss in elderly patients?",
  opts=[["Small vessel ischaemic disease", "Correct."],
        ["Benign positional vertigo", "A vestibular cause, giving brief attacks on head movement."],
        ["Meniere disease", "A vestibular cause, and it comes with hearing loss."],
        ["Labyrinthitis", "A vestibular cause, and it begins suddenly."],
        ["Wax impaction", "That causes conductive loss rather than imbalance."]]),

 dict(topic="Cerebellar infarction", io=IO_A, lead="next step", cite=D % 78,
  q="Which findings alongside vertigo should prompt evaluation for a cerebellar cause?",
  opts=[["Ataxia, headache or facial numbness", "Correct."],
        ["Ear fullness and tinnitus", "Those fit an inner ear syndrome."],
        ["Itching and discharge", "Those fit canal infection."],
        ["Pain on moving the auricle", "That fits canal infection."],
        ["Hearing better in noise", "That fits otosclerosis."]]),

 # ---------------------------- non-organic ----------------------------
 dict(topic="Functional hearing loss", io=IO_A, lead="defining feature", cite=D % 80,
  q="Which observation suggests a functional rather than organic hearing loss?",
  opts=[["A normal voice despite claimed profound loss", "Correct — voice and speech quality carry the information."],
        ["A sloping high-frequency audiogram", "That is an organic pattern."],
        ["Weber lateralising to one side", "That indicates an organic loss."],
        ["A flat tympanogram", "That indicates middle ear fluid."],
        ["Visible wax in the canal", "That is an organic conductive cause."]]),

 # -------------------------- mastoiditis (syllabus) --------------------------
 dict(topic="Mastoiditis", io=IO_A, lead="mechanism", cite=D % 78,
  q="From which condition does mastoiditis most often arise?",
  opts=[["Acute otitis media", "Correct — infection spreads into the mastoid air cells."],
        ["Otitis externa", "That is confined to the canal skin."],
        ["Otosclerosis", "That is a bony disease of the stapes."],
        ["Presbycusis", "That is age-related hearing loss."],
        ["Benign positional vertigo", "That is a balance disorder."]]),
]
