# -*- coding: utf-8 -*-
"""Lecture 27 objective pool C -- aortic aneurysms (abdominal and thoracic),
pseudoaneurysm and aortic dissection.

KEYS ARE WRITTEN SHORT ON PURPOSE -- detail lives in the explanation.

Set 1 recall, no patient ages. Slides only. Threshold questions ask for the
rule itself; no stem places a measured diameter on a boundary. Abdominal
aneurysm rapid growth is 0.5 cm in six months; thoracic is >0.5 cm per year.
Slide 119 (dissection filed under true aneurysms) is never used.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _cmse3_q import Q
from cms_e5l27_scope import *


def S(topic, io, q, opts, cite, slot):
    d = Q(topic, io, q, opts, cite); d["slot"] = slot; return d


AAA = "Abdominal aortic aneurysm"
TAA = "Thoracic aortic aneurysm"
PSA = "Pseudoaneurysm"
DIS = "Aortic dissection"

QUESTIONS = [

# ---------------------------------------------------------------- abdominal aortic aneurysm
S(AAA, IO_A,
  "How is an aneurysm defined?",
  [["Dilation over 50% of normal diameter",
    "Correct. An aneurysm is a pathologic dilation of a segment of a blood vessel, defined as localized dilation of an arterial segment greater than 50% of its normal diameter."],
   ["Dilation over 10% of normal diameter",
    "Ten percent is far too small a change. The definition is localized dilation of more than 50% of normal diameter."],
   ["Any narrowing of the arterial lumen",
    "Narrowing is stenosis, the opposite change. An aneurysm is a dilation greater than 50% of normal diameter."],
   ["A tear through the intima alone",
    "An intimal tear that opens a false lumen describes dissection. An aneurysm is dilation beyond 50% of normal diameter."]],
  C(82), "etiology"),

S(AAA, IO_A,
  "Above what diameter is the infrarenal abdominal aorta considered aneurysmal?",
  [["3 cm",
    "Correct. The average infrarenal abdominal aortic diameter is 2 cm, and more than 3 cm is considered aneurysmal; thoracic normal diameter varies with location, habitus, sex and age."],
   ["2 cm",
    "Two centimeters is the average normal infrarenal diameter. More than 3 cm is aneurysmal."],
   ["4 cm",
    "Four centimeters is already well into the aneurysmal range. The threshold is more than 3 cm."],
   ["6 cm",
    "Six centimeters is a large aneurysm, not the threshold. More than 3 cm is aneurysmal."]],
  C(83), "test finding"),

S(AAA, IO_A,
  "What share of abdominal aortic aneurysms arise below the renal arteries?",
  [["90%",
    "Correct. Ninety percent of abdominal aortic aneurysms originate below the kidneys (infrarenal), usually involving the aortic bifurcation and the common iliac arteries; the abdominal aorta is the commonest aneurysm site."],
   ["50%",
    "Half understates it. Ninety percent of abdominal aortic aneurysms are infrarenal."],
   ["30%",
    "Thirty percent is far too low. Ninety percent of abdominal aortic aneurysms originate below the kidneys."],
   ["70%",
    "Seventy percent still understates it. The figure is 90% infrarenal, usually involving the bifurcation."]],
  C(82), "epidemiology"),

S(AAA, IO_A,
  "Which layers of the wall does a true aneurysm involve?",
  [["All three layers",
    "Correct. True aneurysms involve all three layers of the vessel wall, either saccular (part of the circumference) or fusiform (the whole circumference); a false aneurysm lies outside the wall."],
   ["The intima alone",
    "An intimal tear leading into the media is the start of a dissection. A true aneurysm involves all three layers."],
   ["The adventitia alone",
    "A single layer does not make a true aneurysm. All three layers of the wall are involved."],
   ["No layer at all",
    "A cavity outside the wall is a pseudoaneurysm (false aneurysm). A true aneurysm involves all three layers."]],
  C(84), "etiology"),

S(AAA, IO_A,
  "How does a saccular aneurysm differ from a fusiform one?",
  [["It involves part of the circumference",
    "Correct. A saccular aneurysm involves only a portion of the circumference, an outpouching of the wall; a fusiform aneurysm affects the entire circumference, a diffusely dilated lesion."],
   ["It involves the whole circumference",
    "Whole-circumference, diffuse dilation describes the fusiform aneurysm. The saccular type is a partial outpouching."],
   ["It lies outside the vessel wall",
    "A cavity outside the wall is a false aneurysm. A saccular aneurysm is a true aneurysm of part of the circumference."],
   ["It forms from a false lumen",
    "A false lumen in the media is dissection. A saccular aneurysm is an outpouching of part of the circumference."]],
  C(84), "differential"),

S(AAA, IO_A,
  "Failure of which structural proteins underlies aortic aneurysm?",
  [["Elastin and collagen of the media",
    "Correct. Aortic aneurysm reflects failure of the major structural proteins, elastin and collagen, in the media; the cause is unclear, with genetic predisposition and possible mechanical weakening by atherosclerosis."],
   ["Keratin and collagen of the intima",
    "Keratin is not an arterial wall protein. The failure is of elastin and collagen in the media."],
   ["Actin and myosin of the adventitia",
    "Contractile proteins of the outer coat are not the named failure. Medial elastin and collagen fail."],
   ["Fibrin and platelets of the lumen",
    "Fibrin and platelets make up clot and atheroemboli. Aneurysm reflects medial elastin and collagen failure."]],
  C(80), "etiology"),

S(AAA, IO_A,
  "How does syphilis lead to aortic aneurysm?",
  [["It destroys the vasa vasorum",
    "Correct. Syphilitic infection destroys the vasa vasorum, the small vessels that supply or drain the walls of larger arteries; other listed causes are Marfan syndrome, vasculitis, trauma and congenital aneurysm."],
   ["It seeds clot in the lumen",
    "Luminal clot is not the mechanism given. Syphilis destroys the vasa vasorum that nourish the aortic wall."],
   ["It calcifies the intima",
    "Intimal calcification is not the stated mechanism. The infection destroys the vasa vasorum."],
   ["It narrows the renal arteries",
    "The renal arteries are not involved. Syphilis destroys the vasa vasorum of the aortic wall."]],
  C(85), "etiology"),

S(AAA, IO_A,
  "Which vasculitis is listed among the causes of aortic aneurysm?",
  [["Takayasu arteritis",
    "Correct. The listed vasculitides are Takayasu arteritis and giant cell arteritis, alongside Marfan syndrome, syphilis, trauma and congenital aortic aneurysms."],
   ["Medial calcific sclerosis",
    "Medial calcific sclerosis is one of the three forms of arteriosclerosis, not a vasculitis. The listed vasculitides are Takayasu and giant cell arteritis."],
   ["Leriche syndrome",
    "Leriche syndrome is aortoiliac occlusive disease, not a vasculitis. Takayasu arteritis is the listed cause."],
   ["Arteriolar sclerosis",
    "Arteriolar sclerosis is a form of arteriosclerosis, not a vasculitis. The vasculitides named are Takayasu arteritis and giant cell arteritis."]],
  C(85), "etiology"),

S(AAA, IO_A,
  "Which is the strongest risk factor for aortic aneurysm?",
  [["Ever having smoked",
    "Correct. Smoking, current or past, with any history of ever smoking, is the strongest risk factor; male sex, advancing age, Caucasian race, atherosclerosis, hypertension and family history follow."],
   ["Having diabetes",
    "Diabetes is associated with decreased risk. Ever smoking is the strongest risk factor."],
   ["Female sex",
    "Female sex is protective, although women's aneurysms rupture more often. The strongest risk factor is smoking."],
   ["High dietary salt",
    "Salt is not on the list. Ever smoking, current or past, is the strongest risk factor."]],
  C(86), "risk factors"),

S(AAA, IO_A,
  "Which factor is associated with a decreased risk of abdominal aortic aneurysm?",
  [["Diabetes",
    "Correct. Decreased risk is associated with female sex, non-Caucasian race and diabetes; the reason for diabetes is unknown, possibly its treatment regimens or diabetic arterial stiffness."],
   ["Hypertension",
    "Hypertension raises aneurysm risk and speeds rupture. Diabetes is the protective association."],
   ["Family history",
    "A family history of aneurysm raises risk. Diabetes is associated with decreased risk."],
   ["Male sex",
    "Male sex is a risk factor. Diabetes, female sex and non-Caucasian race are protective."]],
  C(88), "risk factors"),

S(AAA, IO_POP,
  "How does the male-to-female ratio of abdominal aortic aneurysm change after age 80?",
  [["From 2:1 to 1:1",
    "Correct. Men outnumber women 2:1 under 80 years, and the ratio evens to 1:1 over 80 years; Caucasian men have the highest incidence."],
   ["From 1:1 to 2:1",
    "The direction is reversed. Men outnumber women 2:1 under 80, and the ratio evens to 1:1 over 80."],
   ["From 4:1 to 2:1",
    "Four to one is not the stated figure. Men outnumber women 2:1 under 80 and 1:1 over 80."],
   ["Stays at 3:1",
    "The ratio does change with age. It moves from 2:1 in men under 80 to an even 1:1 over 80."]],
  C(80), "epidemiology"),

S(AAA, IO_POP,
  "Which group has the highest incidence of abdominal aortic aneurysm?",
  [["Caucasian men",
    "Correct. Caucasian men have the highest incidence; aneurysm is uncommon in African American, Asian and Hispanic populations, and men outnumber women 2:1 under 80."],
   ["Hispanic women",
    "Aneurysm is uncommon in Hispanic populations and in women. The highest incidence is in Caucasian men."],
   ["Asian men",
    "Aneurysm is uncommon in Asian populations. Caucasian men have the highest incidence."],
   ["African American women",
    "Aneurysm is uncommon in African American populations. Caucasian men have the highest incidence."]],
  C(80), "epidemiology"),

S(AAA, IO_POP,
  "Which of these is a risk factor for aortic aneurysm?",
  [["Advancing age",
    "Correct. Advancing age is a risk factor alongside ever smoking, male sex, Caucasian race, atherosclerosis, hypertension, family history and other large-artery aneurysms."],
   ["Diabetes",
    "Diabetes is associated with decreased aneurysm risk. Advancing age is the risk factor."],
   ["Female sex",
    "Female sex is protective, though women's aneurysms rupture more often. Advancing age raises risk."],
   ["Non-Caucasian race",
    "Non-Caucasian race is associated with decreased risk. Advancing age is the listed risk factor."]],
  C(86), "risk factors"),

S(AAA, IO_A,
  "Which other aneurysms raise the risk of abdominal aortic aneurysm?",
  [["Iliac, femoral or popliteal",
    "Correct. Other large-artery aneurysms (iliac, femoral, popliteal) are a risk factor, together with atherosclerosis, hypertension and a family history of abdominal aortic aneurysm."],
   ["Cerebral berry aneurysms",
    "These are not on the list. The listed risk is other large-artery aneurysms: iliac, femoral or popliteal."],
   ["Coronary artery aneurysms",
    "Coronary aneurysms are not named. The risk factor is iliac, femoral or popliteal aneurysm."],
   ["Retinal microaneurysms",
    "Microaneurysms are not large-artery aneurysms. The listed ones are iliac, femoral and popliteal."]],
  C(87), "risk factors"),

S(AAA, IO_A,
  "Which triad marks a ruptured abdominal aortic aneurysm?",
  [["Pain, pulsatile mass, hypotension",
    "Correct. Sudden escape of blood into the retroperitoneum causes the classic presentation in 50% of patients: severe abdominal or back pain, a pulsatile abdominal mass and hypotension."],
   ["Pain, fever, jaundice",
    "Fever and jaundice point to biliary disease. Rupture gives pain, a pulsatile mass and hypotension."],
   ["Pain, hypertension, bradycardia",
    "Rupture causes hypotension from blood loss. The triad is pain, pulsatile mass and hypotension."],
   ["Pain, hematuria, flank mass",
    "That picture suggests the renal colic rupture is often mistaken for. The triad is pain, pulsatile mass, hypotension."]],
  C(90), "manifestation"),

S(AAA, IO_A,
  "Which finding is virtually diagnostic of a ruptured abdominal aortic aneurysm?",
  [["Pulsatile abdominal mass",
    "Correct. A pulsatile abdominal mass is virtually diagnostic and is more likely to be noted with rupture; an abdominal bruit, by contrast, is nonspecific."],
   ["Abdominal bruit",
    "An abdominal bruit is nonspecific. The pulsatile abdominal mass is virtually diagnostic."],
   ["Early satiety",
    "Early satiety is a symptom of the unruptured, expanding aneurysm. A pulsatile mass is virtually diagnostic of rupture."],
   ["Isolated groin pain",
    "Groin pain from femoral nerve pressure occurs with expansion. A pulsatile mass is the virtually diagnostic sign."]],
  C(90), "differential"),

S(AAA, IO_A,
  "What does Grey Turner sign indicate?",
  [["Retroperitoneal hemorrhage",
    "Correct. Grey Turner sign is flank ecchymosis, which appears with retroperitoneal hemorrhage from a ruptured abdominal aortic aneurysm."],
   ["Pulmonary edema",
    "Pulmonary edema is not signaled by a skin finding on the flank. Grey Turner sign is flank ecchymosis from retroperitoneal bleeding."],
   ["Aortic regurgitation",
    "Aortic regurgitation belongs to ascending aneurysm and dissection. Grey Turner sign marks retroperitoneal hemorrhage."],
   ["Critical limb ischemia",
    "Limb ischemia shows in the feet, not the flank. Grey Turner sign is flank ecchymosis from retroperitoneal bleeding."]],
  C(91), "test finding"),

S(AAA, IO_A,
  "A ruptured abdominal aortic aneurysm is often misdiagnosed as which condition?",
  [["Renal colic",
    "Correct. Ruptured aneurysm is often misdiagnosed as renal colic, diverticulitis, gastrointestinal hemorrhage or ischemic bowel, because the pain sits in the abdomen, back or flank."],
   ["Carotid stenosis",
    "Carotid stenosis causes neurologic symptoms, not abdominal pain. Rupture is often mistaken for renal colic."],
   ["Critical limb ischemia",
    "Limb ischemia affects the feet. Ruptured aneurysm is often misdiagnosed as renal colic."],
   ["Peripheral neuropathy",
    "Neuropathy causes burning feet. Rupture is often mistaken for renal colic or diverticulitis."]],
  C(90), "differential"),

S(AAA, IO_A,
  "Which study is the choice for initial abdominal aortic aneurysm screening?",
  [["Abdominal ultrasound",
    "Correct. Abdominal ultrasound is the diagnostic study of choice for initial screening for an aneurysm and is used for serial documentation of its size."],
   ["Abdominal X-ray",
    "An X-ray shows a calcified outline in only 75%, missing the rest. Ultrasound is the screening study of choice."],
   ["Conventional angiography",
    "Angiography is invasive and not a screening test. Abdominal ultrasound is the study of choice."],
   ["Magnetic resonance imaging",
    "Magnetic resonance imaging suits stable patients with dye allergy. Initial screening uses abdominal ultrasound."]],
  C(94), "initial test"),

S(AAA, IO_A,
  "Which study is best for abdominal aortic aneurysm diagnosis and pre-intervention planning?",
  [["Computed tomography angiography",
    "Correct. Computed tomography angiography is the best diagnostic and pre-intervention planning study, accurately delineating the location, size and extent of the aneurysm."],
   ["Abdominal ultrasound",
    "Ultrasound is the initial screening and surveillance study. Computed tomography angiography is best for diagnosis and planning."],
   ["Abdominal X-ray",
    "An X-ray shows a calcified outline in 75% at best. Planning requires computed tomography angiography."],
   ["Transesophageal echocardiography",
    "Transesophageal echocardiography evaluates the aortic valve and root. Abdominal planning uses computed tomography angiography."]],
  C(97), "gold standard"),

S(AAA, IO_A,
  "In what share of abdominal aortic aneurysms does an abdominal X-ray show a calcified outline?",
  [["75%",
    "Correct. On abdominal X-ray a calcified outline of the aneurysm may be seen in 75%; the other 25% are not calcified and are not visualized, which is why ultrasound screens."],
   ["25%",
    "Twenty-five percent is the share not seen because they are not calcified. The outline is visible in 75%."],
   ["50%",
    "Half understates it. A calcified aneurysm outline is visible on abdominal X-ray in 75%."],
   ["95%",
    "That overstates it, because a quarter are not calcified and cannot be seen. The figure is 75%."]],
  C(94), "test finding"),

S(AAA, IO_A,
  "When is magnetic resonance imaging useful for abdominal aortic aneurysm?",
  [["Stable patients with dye allergy",
    "Correct. Magnetic resonance imaging is comparable to computed tomography without dye or ionizing radiation, and useful in stable patients with a dye allergy."],
   ["Unstable patients with rupture",
    "An unstable ruptured aneurysm is a surgical emergency, not a time for a long scan. The imaging suits stable patients with dye allergy."],
   ["Routine population screening",
    "Screening uses abdominal ultrasound. Magnetic resonance imaging suits stable patients with dye allergy."],
   ["Patients with a pacemaker",
    "Pacemakers are a contraindication to magnetic resonance studies. It suits stable patients with dye allergy."]],
  C(96), "initial test"),

S(AAA, IO_A,
  "How often should a 3.4 cm abdominal aortic aneurysm be imaged?",
  [["Ultrasound every three years",
    "Correct. Surveillance depends on size: 3.0 to 3.9 cm is imaged with ultrasound every three years; 4.0 to 5.4 cm with ultrasound or computed tomography every six to 12 months."],
   ["Ultrasound every month",
    "Monthly imaging is far more than needed for a small aneurysm. The interval for 3.0 to 3.9 cm is every three years."],
   ["Imaging every six months",
    "Six- to 12-month imaging is for 4.0 to 5.4 cm aneurysms. A 3.4 cm aneurysm is imaged every three years."],
   ["No further imaging",
    "Once identified, an aneurysm needs routine follow-up of size and growth. For 3.0 to 3.9 cm, ultrasound every three years."]],
  C(95), "agent/regimen"),

S(AAA, IO_A,
  "How often should a 4.8 cm abdominal aortic aneurysm be imaged?",
  [["Every six to 12 months",
    "Correct. An aneurysm of 4.0 to 5.4 cm is followed with ultrasound or computed tomography every six to 12 months, while 3.0 to 3.9 cm is imaged every three years."],
   ["Every three years",
    "Three-yearly ultrasound is for 3.0 to 3.9 cm aneurysms. At 4.8 cm the interval is six to 12 months."],
   ["Every five years",
    "Five years is too long for any aneurysm in surveillance. At 4.8 cm, image every six to 12 months."],
   ["Every week",
    "Weekly imaging is unnecessary. The interval at 4.0 to 5.4 cm is six to 12 months."]],
  C(95), "agent/regimen"),

S(AAA, IO_A,
  "At what diameter is elective abdominal aortic aneurysm repair advised in women?",
  [["5.0 cm or larger",
    "Correct. Elective repair is advised at 5.0 cm or larger in women and above 5.5 cm in men, and any aneurysm growing rapidly (0.5 cm in six months) should be repaired."],
   ["4.0 cm or larger",
    "At 4.0 cm the aneurysm is still under surveillance. Women are repaired at 5.0 cm or larger."],
   ["5.5 cm or larger",
    "Above 5.5 cm is the elective threshold for men. Women are repaired at 5.0 cm or larger."],
   ["6.5 cm or larger",
    "Waiting that long is not advised. The elective threshold for women is 5.0 cm or larger."]],
  C(95), "escalation"),

S(AAA, IO_A,
  "Which growth rate prompts repair of an abdominal aortic aneurysm?",
  [["0.5 cm in six months",
    "Correct. Evidence of rapid growth, 0.5 cm in six months, means the abdominal aortic aneurysm should be repaired; fast expansion also raises rupture risk."],
   ["0.5 cm in two years",
    "That pace is slower than the threshold. Rapid growth prompting repair is 0.5 cm in six months."],
   ["0.1 cm in six months",
    "That is too small a change to prompt repair. Rapid growth is 0.5 cm in six months."],
   ["2 cm in one year",
    "Repair is indicated well before that. The rapid-growth threshold is 0.5 cm in six months."]],
  C(95), "escalation"),

S(AAA, IO_A,
  "Below what diameter do abdominal aortic aneurysms rarely rupture?",
  [["5 cm",
    "Correct. Aneurysms rarely rupture until the diameter exceeds 5 cm; the risk rises above 5.5 cm, with expansion over 0.5 cm in six months, continued smoking and hypertension."],
   ["3 cm",
    "Three centimeters is merely the aneurysmal threshold. Rupture is rare until the diameter exceeds 5 cm."],
   ["2 cm",
    "Two centimeters is the average normal infrarenal diameter. Rupture is rare below 5 cm."],
   ["8 cm",
    "Rupture risk rises well before 8 cm. Rupture is rare only until the aneurysm exceeds 5 cm."]],
  C(99), "prognosis"),

S(AAA, IO_A,
  "Which factor raises the rupture risk of an abdominal aortic aneurysm?",
  [["Continued smoking",
    "Correct. Rupture risk rises with a diameter over 5.5 cm, expansion over 0.5 cm in six months, continued cigarette smoking and hypertension."],
   ["Diabetes",
    "Diabetes is associated with lower aneurysm risk and is not a rupture factor. Continued smoking raises rupture risk."],
   ["Moderate exercise",
    "Moderate exercise is recommended in medical management. Continued smoking raises rupture risk."],
   ["Non-Caucasian race",
    "Non-Caucasian race is protective against aneurysm. Continued smoking raises rupture risk."]],
  C(99), "prognosis"),

S(AAA, IO_A,
  "What is true of aneurysms in women despite their lower incidence?",
  [["They rupture more often",
    "Correct. Female sex is associated with a decreased risk of aneurysm, although women with aneurysms rupture more often, which is why their repair threshold is lower at 5.0 cm."],
   ["They never need repair",
    "Women's aneurysms are repaired, at 5.0 cm or larger. They also rupture more often."],
   ["They grow only in the chest",
    "Location is not the difference. Women's aneurysms rupture more often despite lower incidence."],
   ["They rupture less often",
    "The opposite is true. Female sex lowers aneurysm risk, but women with aneurysms rupture more often."]],
  C(88), "prognosis"),

S(AAA, IO_A,
  "At what size is an abdominal aortic aneurysm referred for vascular specialty care and observation?",
  [["4.5 cm or larger",
    "Correct. Referral for vascular specialty care, observation and assessment is advised at 4.5 cm or larger, and urgently for aneurysmal pain whatever the size."],
   ["3.0 cm or larger",
    "At 3.0 to 3.9 cm the aneurysm is watched with ultrasound every three years. Specialty referral starts at 4.5 cm."],
   ["6.0 cm or larger",
    "Waiting for 6.0 cm is too late; repair is already due. Specialty referral starts at 4.5 cm."],
   ["Only if it ruptures",
    "Rupture is a surgical emergency, not a referral. Specialty referral is advised from 4.5 cm."]],
  C(100), "referral"),

S(AAA, IO_A,
  "When is urgent vascular referral needed regardless of aneurysm size?",
  [["Aneurysmal pain",
    "Correct. A patient who complains of aneurysmal pain needs urgent vascular referral regardless of aneurysm size, because pain occurs with expansion."],
   ["Early satiety alone",
    "Early satiety is an expansion symptom but not the named trigger. Aneurysmal pain prompts urgent referral."],
   ["A new diagnosis of diabetes",
    "Diabetes is protective against aneurysm. Aneurysmal pain is the trigger for urgent referral."],
   ["A single high blood pressure",
    "Hypertension is managed aggressively, but the urgent trigger is aneurysmal pain."]],
  C(100), "referral"),

S(AAA, IO_A,
  "Which exercise advice fits medical management of an abdominal aortic aneurysm?",
  [["Moderate exercise, such as swimming",
    "Correct. Medical management means smoking cessation, aggressive blood pressure control and moderate exercise such as running, biking, swimming and hiking."],
   ["Strict avoidance of all exercise",
    "Exercise is not forbidden. Moderate exercise such as running, biking, swimming and hiking is advised."],
   ["Maximal heavy weightlifting",
    "Maximal lifting is not among the advised activities. Moderate exercise such as swimming or hiking is."],
   ["Bed rest until repair",
    "Bed rest is not advised. Moderate exercise such as swimming is part of medical management."]],
  C(100), "education"),

S(AAA, IO_A,
  "What does endovascular aneurysm repair involve?",
  [["A modular graft lining the aorta",
    "Correct. Endovascular aneurysm repair places a modular graft through the iliac or femoral arteries to line the aorta and exclude the aneurysm sac from circulation; open repair replaces the segment."],
   ["Replacing the aorta via laparotomy",
    "Replacing the diseased segment with a tube or bifurcated graft is open repair. The endovascular route places a modular graft inside."],
   ["Injecting thrombin into the sac",
    "Ultrasound-guided thrombin injection treats a pseudoaneurysm. Endovascular repair lines the aorta with a modular graft."],
   ["Shaving plaque from the wall",
    "Removing plaque is atherectomy or endarterectomy. Endovascular repair lines the aorta with a modular graft."]],
  C(101), "escalation"),

S(AAA, IO_A,
  "Which step belongs to management of a ruptured abdominal aortic aneurysm?",
  [["Type and cross-match",
    "Correct. A ruptured aneurysm is hemodynamically unstable and a surgical emergency: place large-bore intravenous catheters, type and cross-match blood, and go to surgery."],
   ["Ultrasound in six months",
    "Surveillance ultrasound is for small, stable aneurysms. Rupture needs type and cross-match and emergency surgery."],
   ["Start a supervised exercise plan",
    "Exercise belongs to chronic management. Rupture needs large-bore access, type and cross-match and surgery."],
   ["Outpatient vascular referral",
    "Rupture is a surgical emergency. Large-bore access and type and cross-match come before surgery."]],
  C(92), "first-line"),

S(AAA, IO_A,
  "Which drug class controls blood pressure in a symptomatic, unruptured abdominal aortic aneurysm?",
  [["Beta blockers",
    "Correct. Symptomatic unruptured aneurysm management evaluates stability, places large-bore intravenous catheters, controls pain and blood pressure with beta blockers, then repairs surgically."],
   ["Thrombolytics",
    "Thrombolytics dissolve clot in acute limb ischemia. Blood pressure here is controlled with beta blockers."],
   ["Antiplatelet agents",
    "Antiplatelets treat occlusive disease. Blood pressure in a symptomatic aneurysm is controlled with beta blockers."],
   ["Xanthine derivatives",
    "Pentoxifylline, a xanthine derivative, is for claudication. Beta blockers control pressure here."]],
  C(92), "first-line"),

S(AAA, IO_A,
  "About how many deaths a year in the United States are due to abdominal aortic aneurysm?",
  [["15,000",
    "Correct. About 15,000 deaths a year in the United States are due to abdominal aortic aneurysm, the only mortality figure given for these conditions."],
   ["1,500",
    "That understates it tenfold. The figure is about 15,000 deaths a year in the United States."],
   ["150,000",
    "That overstates it tenfold. About 15,000 deaths a year are due to abdominal aortic aneurysm."],
   ["50,000",
    "That overstates it. The stated figure is about 15,000 deaths a year in the United States."]],
  C(80), "prognosis"),

S(AAA, IO_A,
  "Isolated groin pain from an expanding abdominal aortic aneurysm reflects pressure on which nerve?",
  [["Femoral nerve",
    "Correct. A symptomatic, unruptured aneurysm can cause abdominal, back or flank pain, pain radiating to the low back, and isolated groin pain from pressure on the femoral nerve."],
   ["Sciatic nerve",
    "The sciatic nerve runs in the buttock and back of the thigh. Groin pain comes from femoral nerve pressure."],
   ["Phrenic nerve",
    "The phrenic nerve serves the diaphragm. Groin pain reflects femoral nerve pressure."],
   ["Recurrent laryngeal nerve",
    "The recurrent laryngeal nerve is compressed by an aortic arch aneurysm, causing hoarseness. Groin pain is femoral."]],
  C(89), "manifestation"),

# ---------------------------------------------------------------- thoracic aortic aneurysm
S(TAA, IO_A,
  "An aortic arch aneurysm causes hoarseness through pressure on which nerve?",
  [["Recurrent laryngeal nerve",
    "Correct. Manifestations depend on location: an arch aneurysm causes hoarseness through the recurrent laryngeal nerve, an ascending one aortic regurgitation and heart failure."],
   ["Femoral nerve",
    "Femoral nerve pressure causes groin pain from an abdominal aneurysm. Arch hoarseness is recurrent laryngeal."],
   ["Phrenic nerve",
    "The phrenic nerve is not the one named. Hoarseness comes from recurrent laryngeal nerve compression."],
   ["Vagal cardiac branch",
    "Cardiac branches do not control the voice. Compression of the recurrent laryngeal nerve does."]],
  C(104), "manifestation"),

S(TAA, IO_A,
  "Which finding points to an ascending thoracic aortic aneurysm?",
  [["Aortic regurgitation",
    "Correct. An ascending thoracic aortic aneurysm can cause aortic regurgitation and heart failure; arch aneurysms cause hoarseness, descending ones compress the trachea or esophagus."],
   ["Hoarseness",
    "Hoarseness from the recurrent laryngeal nerve belongs to the arch. Ascending aneurysm gives aortic regurgitation."],
   ["Dysphagia",
    "Dysphagia from esophageal compression belongs to the descending aneurysm. Ascending gives aortic regurgitation."],
   ["Stridor",
    "Stridor from tracheal compression belongs to the descending aneurysm. Ascending gives aortic regurgitation."]],
  C(104), "complication"),

S(TAA, IO_A,
  "Which symptoms suggest a descending thoracic aortic aneurysm?",
  [["Stridor, cough and dysphagia",
    "Correct. A descending thoracic aneurysm causes dyspnea, stridor, wheezing, cough and dysphagia from compression of the trachea or esophagus."],
   ["Hoarseness and voice change",
    "Hoarseness from recurrent laryngeal compression points to the arch. Descending aneurysm compresses trachea and esophagus."],
   ["Heart failure and regurgitation",
    "Aortic regurgitation and heart failure point to the ascending aorta. Descending aneurysm causes stridor and dysphagia."],
   ["Groin pain and early satiety",
    "These belong to an expanding abdominal aneurysm. Descending thoracic aneurysm causes stridor, cough and dysphagia."]],
  C(104), "manifestation"),

S(TAA, IO_A,
  "How are most thoracic aortic aneurysms found?",
  [["Incidentally on chest radiograph",
    "Correct. Most thoracic aortic aneurysms are asymptomatic and found incidentally on chest radiograph; a history of hypertension is common, and symptoms depend on location."],
   ["By sudden tearing chest pain",
    "Sudden tearing pain describes aortic dissection. Most thoracic aneurysms are asymptomatic and found incidentally."],
   ["By a pulsatile abdominal mass",
    "A pulsatile abdominal mass belongs to abdominal aneurysm. Thoracic aneurysms are mostly incidental radiograph findings."],
   ["By blue toe syndrome",
    "Blue toe follows emboli to the digits. Most thoracic aneurysms are found incidentally on chest radiograph."]],
  C(104), "manifestation"),

S(TAA, IO_A,
  "Which history is common in thoracic aortic aneurysm?",
  [["Hypertension",
    "Correct. A history of hypertension is common in thoracic aortic aneurysm, and management includes aggressive blood pressure control, beta blockers and smoking cessation."],
   ["Diabetes",
    "Diabetes is linked to lower abdominal aneurysm risk. Hypertension is the common history in thoracic aneurysm."],
   ["Recent viral illness",
    "A viral prodrome is not described for aneurysm. Hypertension is the common history."],
   ["Hypothyroidism",
    "Thyroid disease is not named for thoracic aneurysm. A history of hypertension is common."]],
  C(104), "risk factors"),

S(TAA, IO_A,
  "Which chest radiograph finding suggests a thoracic aortic aneurysm?",
  [["Widened mediastinal shadow",
    "Correct. Chest radiograph findings include widening of the mediastinal shadow and displacement or compression of the trachea or left mainstem bronchus."],
   ["Calcified abdominal outline",
    "A calcified outline on abdominal X-ray belongs to abdominal aneurysm. The chest film shows a widened mediastinum."],
   ["Short horizontal lung lines",
    "Short horizontal lines at the lung periphery signal pulmonary edema. Thoracic aneurysm widens the mediastinum."],
   ["Air under the diaphragm",
    "Free air under the diaphragm is a different emergency. Thoracic aneurysm widens the mediastinal shadow."]],
  C(105), "test finding"),

S(TAA, IO_A,
  "Which imaging is most widely used for thoracic aortic aneurysm?",
  [["Computed tomography angiography",
    "Correct. Computed tomography angiography is the most widely used study, visualizing the entire thoracic and abdominal aorta; magnetic resonance angiography is time consuming."],
   ["Abdominal ultrasound",
    "Abdominal ultrasound screens abdominal aneurysms. Thoracic aneurysm is imaged most widely with computed tomography angiography."],
   ["Magnetic resonance angiography",
    "Magnetic resonance angiography shows location, extent and size but is time consuming. Computed tomography angiography is most widely used."],
   ["Duplex ultrasonography",
    "Duplex ultrasonography screens carotid and leg arteries. Thoracic aneurysm is imaged with computed tomography angiography."]],
  C(106), "initial test"),

S(TAA, IO_A,
  "What does transesophageal echocardiography evaluate in thoracic aortic aneurysm?",
  [["Aortic valve and aortic root",
    "Correct. Transesophageal echocardiography evaluates the aortic valve and aortic root; computed tomography angiography remains the most widely used study for the whole aorta."],
   ["Aortic bifurcation and iliacs",
    "The bifurcation is abdominal and beyond the probe's view. Transesophageal echocardiography evaluates the aortic valve and root."],
   ["Carotid bulb and bifurcation",
    "The carotids are screened with duplex ultrasonography. The transesophageal study evaluates the aortic valve and root."],
   ["Femoral access site",
    "Femoral sites are assessed with ultrasound. Transesophageal echocardiography evaluates the aortic valve and root."]],
  C(106), "test finding"),

S(TAA, IO_A,
  "Which thoracic aortic aneurysms should all be repaired?",
  [["Every symptomatic one",
    "Correct. Repair is recommended for all symptomatic thoracic aortic aneurysms; asymptomatic repair depends on diameter, location and expansion rate."],
   ["Every one over 3 cm",
    "Three centimeters is the abdominal aneurysm threshold, not a repair rule. All symptomatic thoracic aneurysms are repaired."],
   ["Every one found incidentally",
    "Incidental, asymptomatic aneurysms are repaired only by size, location and growth. Symptomatic ones are all repaired."],
   ["Only ruptured ones",
    "Waiting for rupture is not the rule. Every symptomatic thoracic aneurysm should be repaired."]],
  C(108), "escalation"),

S(TAA, IO_A,
  "Above what diameter is surgery generally indicated for an asymptomatic ascending thoracic aneurysm?",
  [["5.5 cm",
    "Correct. Surgery is generally indicated for ascending aneurysms over 5.5 cm and descending aneurysms over 6.0 cm, or with growth over 0.5 cm per year."],
   ["4.5 cm",
    "At 4.5 to 5.4 cm the aneurysm is imaged every 6 to 12 months. Ascending repair begins above 5.5 cm."],
   ["6.0 cm",
    "Over 6.0 cm is the threshold for descending aneurysms. Ascending ones qualify above 5.5 cm."],
   ["3.0 cm",
    "Three centimeters defines an abdominal aneurysm. Ascending thoracic repair begins above 5.5 cm."]],
  C(109), "escalation"),

S(TAA, IO_A,
  "Which growth rate indicates repair of a thoracic aortic aneurysm?",
  [["Over 0.5 cm per year",
    "Correct. A growth rate over 0.5 cm per year indicates surgical repair of a thoracic aneurysm; for the abdominal aorta, rapid growth is 0.5 cm in six months."],
   ["Over 0.5 cm per month",
    "A monthly rate is far faster than the threshold. Thoracic repair is indicated above 0.5 cm per year."],
   ["Over 2 cm per year",
    "Two centimeters a year is far beyond the threshold. Repair is indicated above 0.5 cm per year."],
   ["Over 0.1 cm per year",
    "That pace is too slow to prompt repair. The thoracic threshold is over 0.5 cm per year."]],
  C(109), "escalation"),

S(TAA, IO_A,
  "What must follow chest or back pain in a patient with a known thoracic aortic aneurysm?",
  [["Urgent imaging",
    "Correct. Chest or back pain with a known or suspected thoracic aortic aneurysm must undergo urgent imaging to rule out the aneurysm as the cause of the pain."],
   ["Routine yearly imaging",
    "Pain changes the urgency. It requires urgent imaging, not routine scheduled surveillance."],
   ["An exercise stress test",
    "Stress testing is not the step named. The patient needs urgent imaging of the aneurysm."],
   ["Reassurance and analgesia",
    "Pain cannot be dismissed. Urgent imaging must rule out the aneurysm as its cause."]],
  C(108), "referral"),

S(TAA, IO_A,
  "How often is a thoracic aortic aneurysm under 4.5 cm imaged?",
  [["Every 3-5 years",
    "Correct. A root, ascending or descending aneurysm under 4.5 cm is imaged with computed tomography or magnetic resonance every 3 to 5 years; 4.5 to 5.4 cm every 6 to 12 months."],
   ["Every 6-12 months",
    "Six- to 12-month imaging is for 4.5 to 5.4 cm aneurysms. Under 4.5 cm the interval is 3 to 5 years."],
   ["Every month",
    "Monthly imaging is unnecessary for a small aneurysm. The interval is every 3 to 5 years."],
   ["Every 10 years",
    "Ten years is too long an interval. Aneurysms under 4.5 cm are imaged every 3 to 5 years."]],
  C(109), "agent/regimen"),

S(TAA, IO_A,
  "How is an ascending thoracic aortic aneurysm usually repaired?",
  [["Open repair with root replacement",
    "Correct. An ascending thoracic aneurysm often requires an open surgical approach with aortic root replacement, while a descending one can be repaired open or endovascularly."],
   ["Thrombin injection into the sac",
    "Thrombin injection seals a pseudoaneurysm leak. Ascending aneurysms usually need open repair with root replacement."],
   ["Endovascular repair only",
    "Endovascular repair is an option for descending aneurysms. Ascending ones usually need open root replacement."],
   ["Medical therapy with no repair",
    "Medical therapy alone does not fix a qualifying aneurysm. Ascending repair is usually open with root replacement."]],
  C(110), "agent/regimen"),

# ---------------------------------------------------------------- pseudoaneurysm
S(PSA, IO_A,
  "What is a pseudoaneurysm?",
  [["A blood-filled cavity outside the wall",
    "Correct. A pseudoaneurysm is a communication between the arterial lumen and overlying connective tissue after arterial rupture; a blood-filled cavity forms outside the vessel wall and seals the leak as it thromboses."],
   ["A dilation of all three wall layers",
    "Involvement of all three layers defines a true aneurysm. A pseudoaneurysm lies outside the vessel wall."],
   ["A false lumen within the media",
    "A false lumen within the media is aortic dissection. A pseudoaneurysm is a cavity outside the wall."],
   ["A fusiform widening of the aorta",
    "Fusiform widening is a true aneurysm. A pseudoaneurysm is a blood-filled cavity outside the wall."]],
  C(112), "etiology"),

S(PSA, IO_A,
  "What is the common site of a pseudoaneurysm?",
  [["Femoral artery after catheterization",
    "Correct. The common site is the femoral artery after cardiac catheterization, caused by laceration of the artery by the access needle."],
   ["Carotid bulb after endarterectomy",
    "Endarterectomy's complications are stroke or nerve damage. Pseudoaneurysm typically follows femoral catheterization."],
   ["Infrarenal aorta in smokers",
    "The infrarenal aorta is the site of true abdominal aneurysms. Pseudoaneurysm typically affects the femoral artery after catheterization."],
   ["Popliteal artery after bypass",
    "Bypass complications are listed separately. Pseudoaneurysm is typically femoral after cardiac catheterization."]],
  C(112), "epidemiology"),

S(PSA, IO_A,
  "What causes a pseudoaneurysm after cardiac catheterization?",
  [["Laceration by the access needle",
    "Correct. A femoral pseudoaneurysm after cardiac catheterization is caused by laceration of the artery by the access needle, with blood escaping into the connective tissue."],
   ["Degeneration of medial elastin",
    "Medial elastin and collagen failure underlies true aneurysm and dissection. Pseudoaneurysm follows a needle laceration."],
   ["Syphilis of the vasa vasorum",
    "Syphilis causes true aortic aneurysm. Pseudoaneurysm follows laceration by an access needle."],
   ["An embolus from the heart",
    "Cardiac emboli cause acute limb ischemia. Pseudoaneurysm follows laceration by the access needle."]],
  C(112), "etiology"),

S(PSA, IO_A,
  "Which pseudoaneurysms may be managed by watching and waiting?",
  [["Those under 2 cm",
    "Correct. A pseudoaneurysm under 2 cm in diameter may undergo spontaneous thrombosis and regression, so watch and wait; otherwise an ultrasound-guided thrombin injection seals the leak."],
   ["Those over 5 cm",
    "Large pseudoaneurysms are unlikely to seal on their own. Watch and wait is for those under 2 cm."],
   ["Those in the aorta",
    "The typical pseudoaneurysm is femoral, not aortic. Watch and wait is for any under 2 cm."],
   ["Those causing nerve pain",
    "Symptomatic compression argues for treatment. Watch and wait suits pseudoaneurysms under 2 cm."]],
  C(113), "first-line"),

S(PSA, IO_A,
  "Which treatment seals a pseudoaneurysm leak?",
  [["Ultrasound-guided thrombin injection",
    "Correct. Treatment is watch and wait under 2 cm, or ultrasound-guided injection of thrombin, which promotes clot, to seal the leak."],
   ["Endovascular aneurysm repair",
    "Endovascular repair with a modular graft treats abdominal aortic aneurysm. A pseudoaneurysm leak is sealed with guided thrombin."],
   ["Intravenous heparin infusion",
    "Heparin anticoagulates, the opposite of sealing a leak. Ultrasound-guided thrombin injection seals it."],
   ["Carotid endarterectomy",
    "Endarterectomy removes carotid plaque. A pseudoaneurysm is sealed with ultrasound-guided thrombin."]],
  C(113), "escalation"),

S(PSA, IO_A,
  "Which features separate a pseudoaneurysm from a true aneurysm?",
  [["Thin wall, irregular, hematoma",
    "Correct. A pseudoaneurysm has a thin wall, an irregular outline and a surrounding hematoma, whereas a true aneurysm has a thick wall and a smooth outline."],
   ["Thick wall, smooth outline",
    "A thick wall and smooth outline describe the true aneurysm. The pseudoaneurysm is thin-walled and irregular."],
   ["All three wall layers intact",
    "All three layers define a true aneurysm. The pseudoaneurysm lies outside the wall with a hematoma."],
   ["A false lumen in the media",
    "A false lumen in the media is dissection. Pseudoaneurysm is thin-walled and irregular with hematoma."]],
  C(112), "differential"),

S(PSA, IO_A,
  "What causes the pain of a pseudoaneurysm?",
  [["Swelling or nerve compression",
    "Correct. A pseudoaneurysm presents with pain from increased pressure due to swelling, or from nerve compression, at the site of the arterial leak."],
   ["Muscle ischemia on walking",
    "Walking-induced muscle ischemia is claudication. Pseudoaneurysm pain comes from swelling or nerve compression."],
   ["A tear through the intima",
    "An intimal tear gives the tearing pain of dissection. Pseudoaneurysm pain comes from swelling or nerve compression."],
   ["Retroperitoneal bleeding",
    "Retroperitoneal bleeding marks a ruptured abdominal aneurysm. Pseudoaneurysm pain is from swelling or nerve compression."]],
  C(113), "manifestation"),

# ---------------------------------------------------------------- aortic dissection
S(DIS, IO_A,
  "What defines aortic dissection?",
  [["An intimal tear with a false lumen",
    "Correct. Aortic dissection forms from an intimal tear typically contained by the media; the wall layers separate, creating a false lumen within the media where blood can pool."],
   ["A cavity outside the vessel wall",
    "A cavity outside the wall is a pseudoaneurysm. Dissection is an intimal tear with a false lumen in the media."],
   ["Dilation of all three layers",
    "Dilation of all three layers is a true aneurysm. Dissection separates the layers after an intimal tear."],
   ["Plaque narrowing of the lumen",
    "Plaque narrowing is atherosclerotic stenosis. Dissection is an intimal tear creating a false lumen."]],
  C(114), "etiology"),

S(DIS, IO_A,
  "What is the most common predisposing factor for aortic dissection?",
  [["Medial collagen and elastin degeneration",
    "Correct. The most common predisposing factor is degeneration of medial collagen and elastin, with Marfan syndrome the classic medial degeneration."],
   ["Laceration by an access needle",
    "Needle laceration causes a femoral pseudoaneurysm. Dissection is predisposed by medial collagen and elastin degeneration."],
   ["Embolism from atrial fibrillation",
    "Cardiac emboli cause acute limb ischemia. Dissection rests on medial collagen and elastin degeneration."],
   ["Destruction of the carotid bulb",
    "The carotid bulb is not involved. Dissection is predisposed by medial degeneration of collagen and elastin."]],
  C(115), "etiology"),

S(DIS, IO_POP,
  "At what age does aortic dissection usually occur outside Marfan syndrome?",
  [["60s to 70s",
    "Correct. Aortic dissection usually occurs in the 60s and 70s, except in Marfan syndrome, with males more affected than females and hypertension present in most cases."],
   ["20s to 30s",
    "Young onset fits Marfan syndrome, the stated exception. Otherwise dissection occurs in the 60s and 70s."],
   ["40s to 50s",
    "That is younger than the stated range. Dissection usually occurs in the 60s and 70s."],
   ["Over 90",
    "That is older than the stated range. The typical age for aortic dissection is the 60s to 70s."]],
  C(115), "epidemiology"),

S(DIS, IO_A,
  "Which history is present in most cases of aortic dissection?",
  [["Hypertension",
    "Correct. A history of hypertension is present in most cases of aortic dissection, which occurs mainly in the 60s and 70s and in males more than females."],
   ["Recent cardiac catheterization",
    "Catheterization is the setting of femoral pseudoaneurysm. Most dissections occur with a history of hypertension."],
   ["Diabetes",
    "Diabetes is not the listed association. A history of hypertension is present in most cases."],
   ["Recent viral illness",
    "A viral prodrome is not described for dissection. Hypertension is present in most dissections."]],
  C(115), "risk factors"),

S(DIS, IO_A,
  "Which syndrome is the classic medial degeneration behind aortic dissection?",
  [["Marfan syndrome",
    "Correct. Marfan syndrome, a connective tissue disorder, is the classic medial degeneration and an exception to the usual 60s-to-70s age of dissection."],
   ["Leriche syndrome",
    "Leriche syndrome is aortoiliac occlusive disease with claudication. Marfan syndrome is the classic medial degeneration."],
   ["Blue toe syndrome",
    "Blue toe results from atheroemboli to the digits. Marfan syndrome is the classic medial degeneration."],
   ["Metabolic syndrome",
    "Metabolic syndrome is not named for dissection. Marfan syndrome is the classic medial degeneration."]],
  C(115), "etiology"),

S(DIS, IO_A,
  "How is the pain of aortic dissection classically described?",
  [["Sudden, tearing or ripping",
    "Correct. Dissection pain is sudden, severe, tearing or ripping chest pain whose location depends on the site and may change as the dissection propagates distally."],
   ["Gradual, dull and positional",
    "A gradual, dull pain does not fit. Dissection pain is sudden and tearing or ripping."],
   ["Burning and relieved by food",
    "Food-relieved burning suggests a peptic cause. Dissection pain is sudden and tearing."],
   ["Crampy and relieved by rest",
    "Crampy pain relieved by rest describes claudication. Dissection is sudden, tearing chest pain."]],
  C(116), "manifestation"),

S(DIS, IO_A,
  "Why can aortic dissection cause aortic regurgitation?",
  [["Dilatation of the aortic root",
    "Correct. Aortic regurgitation in dissection results from dilatation of the aortic root; other features are syncope and either hypertension or hypotension."],
   ["Rupture of the mitral valve",
    "The mitral valve is not involved. Dissection causes aortic regurgitation by dilating the aortic root."],
   ["Compression of the trachea",
    "Tracheal compression causes stridor in descending aneurysm. Regurgitation follows aortic root dilatation."],
   ["Clot in the false lumen",
    "Clot in the false lumen does not open the valve. Aortic root dilatation causes the regurgitation."]],
  C(116), "complication"),

S(DIS, IO_A,
  "What may the electrocardiogram show in aortic dissection?",
  [["It may be normal",
    "Correct. The electrocardiogram may be normal in aortic dissection, so the diagnosis rests on computed tomography of the chest and abdomen, magnetic resonance imaging or transesophageal echocardiography."],
   ["Always ST elevation",
    "ST elevation is not described as a feature of dissection. The electrocardiogram may be entirely normal."],
   ["Always low voltage",
    "Low voltage is not described for dissection. The electrocardiogram may be normal."],
   ["Diagnostic Q waves",
    "Q waves are not described. A normal electrocardiogram does not exclude dissection."]],
  C(117), "test finding"),

S(DIS, IO_A,
  "Which study delineates the extent of an aortic dissection?",
  [["Chest and abdominal computed tomography",
    "Correct. Computed tomography of the chest and abdomen delineates the extent of dissection; magnetic resonance imaging is good but slower, and transesophageal echocardiography is also used."],
   ["Abdominal ultrasound alone",
    "Abdominal ultrasound screens for abdominal aneurysm. Dissection extent is delineated by chest and abdominal computed tomography."],
   ["An electrocardiogram",
    "The electrocardiogram may be normal. Extent is shown by chest and abdominal computed tomography."],
   ["An ankle-brachial index",
    "The ankle-brachial index grades leg disease. Dissection extent needs chest and abdominal computed tomography."]],
  C(117), "initial test"),

S(DIS, IO_A,
  "What is the drawback of magnetic resonance imaging in aortic dissection?",
  [["Longer imaging time",
    "Correct. Magnetic resonance imaging is good for dissection but has a longer imaging time, so computed tomography of the chest and abdomen is used to delineate extent."],
   ["It cannot show the aorta",
    "It shows the aorta well. Its drawback in acute dissection is a longer imaging time."],
   ["It requires arterial puncture",
    "Arterial puncture belongs to conventional angiography. The magnetic resonance drawback is time."],
   ["It exposes to ionizing radiation",
    "Magnetic resonance uses no ionizing radiation. Its drawback is longer imaging time."]],
  C(117), "avoid"),

S(DIS, IO_A,
  "To what systolic pressure is blood pressure lowered in acute aortic dissection?",
  [["100-120 mmHg",
    "Correct. Progression is stopped by reducing blood pressure, with a systolic target of 100 to 120 mmHg using a beta blocker (esmolol) or a vasodilator (nitroprusside), plus pain control and surgery."],
   ["140-160 mmHg",
    "That target is too high to halt propagation. Systolic pressure is lowered to 100 to 120 mmHg."],
   ["70-80 mmHg",
    "That is lower than the stated target. The goal is a systolic pressure of 100 to 120 mmHg."],
   ["Below 140 mmHg",
    "Below 140 is the general goal in peripheral artery disease. Dissection needs 100 to 120 mmHg."]],
  C(118), "first-line"),

S(DIS, IO_A,
  "Which agents lower blood pressure in acute aortic dissection?",
  [["Esmolol or nitroprusside",
    "Correct. A beta blocker (esmolol) or a vasodilator (nitroprusside) reduces systolic pressure to 100 to 120 mmHg; pain management and surgical grafting complete treatment."],
   ["Heparin or alteplase",
    "These anticoagulate and dissolve clot in acute limb ischemia. Dissection pressure is lowered with esmolol or nitroprusside."],
   ["Aspirin or clopidogrel",
    "These are antiplatelets for occlusive disease. Dissection needs esmolol or nitroprusside."],
   ["Cilostazol or pentoxifylline",
    "These treat claudication. Dissection pressure is lowered with esmolol or nitroprusside."]],
  C(118), "agent/regimen"),

S(DIS, IO_A,
  "What is the prognosis of untreated acute aortic dissection?",
  [["High mortality",
    "Correct. Acute untreated aortic dissection carries a high mortality rate, which is why pressure is lowered at once and diseased aorta is grafted and replaced surgically."],
   ["Spontaneous full recovery",
    "Untreated acute dissection does not reliably heal. It carries a high mortality rate."],
   ["Slow, harmless enlargement",
    "Dissection is not benign. Untreated acute dissection carries a high mortality rate."],
   ["Regression under 2 cm",
    "Regression under 2 cm applies to a small pseudoaneurysm. Untreated dissection carries high mortality."]],
  C(118), "prognosis"),

S(DIS, IO_A,
  "Which surgery treats aortic dissection?",
  [["Grafting and replacing the aorta",
    "Correct. Surgery for dissection grafts and replaces the diseased portion of the aorta, after blood pressure is lowered with esmolol or nitroprusside and pain is managed."],
   ["Ultrasound-guided thrombin injection",
    "Thrombin injection seals a pseudoaneurysm. Dissection surgery grafts and replaces the aorta."],
   ["Carotid endarterectomy",
    "Endarterectomy removes carotid plaque. Dissection surgery replaces the diseased aorta with a graft."],
   ["Catheter-directed thrombolysis",
    "Thrombolysis treats acute limb ischemia. Dissection surgery grafts and replaces the aorta."]],
  C(118), "escalation"),
]
