# -*- coding: utf-8 -*-
"""Lecture 27 objective pool A -- Arterial Occlusive Disease and Aortic Aneurysm:
atherosclerosis background and peripheral artery disease (history, examination,
testing, management, differential).

KEYS ARE WRITTEN SHORT ON PURPOSE -- detail lives in the explanation.

Set 1 is recall against the syllabus objectives, so no stem carries a patient
age. Slides are the only content source (no recording yet: the lecture is on
2026-10-01). Scope caps and contested facts live in cms_e5l27_scope.py.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _cmse3_q import Q
from cms_e5l27_scope import *


def S(topic, io, q, opts, cite, slot):
    d = Q(topic, io, q, opts, cite); d["slot"] = slot; return d


BG = "Atherosclerosis background"
PAD = "Peripheral artery disease"

QUESTIONS = [

# ---------------------------------------------------------------- background
S(BG, IO_A,
  "Where do atherosclerotic lesions most often form?",
  [["At branch points and turbulent sites",
    "Correct. Atherosclerotic lesions form at arterial bifurcations (branching) and at sites of increased turbulence, and they develop over many decades before causing stenosis, thrombosis or atheroemboli."],
   ["In the smallest arterioles of the skin",
    "Atherosclerosis affects intermediate and large arteries such as the coronary, carotid and femoral arteries and the aorta, not the skin's smallest arterioles."],
   ["In straight segments with laminar flow",
    "Laminar flow along straight segments is the protected pattern. Lesions favor bifurcations and turbulent regions, where flow swirls against the wall."],
   ["In the veins draining the lower legs",
    "Atherosclerosis is an arterial disease of intermediate and large arteries. It forms at arterial branch points and sites of turbulence, not in leg veins."]],
  C(7), "etiology"),

S(BG, IO_A,
  "What does the word part \"athero\" in atherosclerosis refer to?",
  [["The fatty core of the plaque",
    "Correct. Athero means gruel or paste and refers to the fatty material in the core of the plaque; sclerosis (hardness) refers to the fibrous tissue that stiffens the wall over it."],
   ["The fibrous cap over the plaque",
    "The fibrous tissue forming over the plaque is what the sclerosis half (hardness) describes. Athero, gruel or paste, names the fatty core beneath it."],
   ["The calcium in the arterial media",
    "Medial calcific sclerosis is a separate form of arteriosclerosis. Athero, meaning gruel or paste, names the fatty material in the plaque's core."],
   ["The clot at a site of rupture",
    "Thrombosis at a rupture site is a later event in the plaque sequence. Athero, gruel or paste, refers to the fatty material in the plaque's core."]],
  C(5), "etiology"),

S(BG, IO_A,
  "Which plaque is the vulnerable, unstable type?",
  [["Fatty core, thin fibrous shell",
    "Correct. A vulnerable plaque has a fatty core under a thin fibrous outer shell and can rupture into the bloodstream; clotting then begins at the rupture site and can go on to occlude the artery."],
   ["Small core, thick fibrous shell",
    "A thick fibrous shell is the stable plaque. The vulnerable plaque is the one with a fatty core and a thin fibrous outer shell that can rupture."],
   ["Fatty streak, no fibrous shell",
    "The fatty streak is the earliest lesion, developing between the intima and the media. The unstable plaque has a fatty core with a thin fibrous shell."],
   ["Calcified core, thick media layer",
    "Calcification of the media belongs to medial calcific sclerosis. The unstable plaque of atherosclerosis has a fatty core and a thin fibrous shell."]],
  C(6), "etiology"),

# ---------------------------------------------------------------- pad
S(PAD, IO_A,
  "What produces the pain of peripheral artery disease?",
  [["Muscle blood flow below metabolic need",
    "Correct. Peripheral artery disease is a lack of blood flow to the musculature relative to its metabolism, which produces pain in the affected muscle groups; its pathophysiology is similar to coronary artery disease."],
   ["Inflammation of the peripheral nerves",
    "Nerve pain belongs to peripheral neuropathy, a continuous burning in the foot that exercise does not affect. Arterial pain comes from flow falling short of muscle demand."],
   ["Pooling of blood in the leg veins",
    "Venous pooling causes calf swelling and discomfort on standing. Arterial disease hurts because muscle blood flow falls below its metabolic need."],
   ["Narrowing of the lumbar spinal canal",
    "Spinal stenosis gives claudication-like symptoms eased by sitting or leaning forward. Peripheral artery disease pain comes from inadequate muscle blood flow."]],
  C(10), "etiology"),

S(PAD, IO_A,
  "What share of patients with peripheral artery disease also have coronary artery disease?",
  [["About 50%",
    "Correct. Half of patients with peripheral artery disease also have coronary artery disease, which fits the shared atherosclerotic pathophysiology of the two conditions."],
   ["About 10%",
    "Ten percent understates the overlap considerably. Half of patients with peripheral artery disease also carry coronary artery disease."],
   ["About 25%",
    "One in four is too low. The overlap is about 50%, because both diseases share the same atherosclerotic pathophysiology."],
   ["About 90%",
    "Ninety percent overstates it. About half of patients with peripheral artery disease also have coronary artery disease."]],
  C(10), "epidemiology"),

S(PAD, IO_POP,
  "In an adult with no other risk factors, peripheral artery disease risk is flagged above which age?",
  [["60 years",
    "Correct. Age is a risk factor above 60 years in someone without other risk factors; with risk factors such as smoking, diabetes or hypertension the threshold falls to 50 years."],
   ["40 years",
    "Forty is younger than either threshold. Without other risk factors the age flag is over 60; with risk factors it is 50."],
   ["50 years",
    "Fifty is the age threshold when other risk factors, such as smoking or diabetes, are present. Without them it is over 60 years."],
   ["75 years",
    "Seventy-five is later than the stated threshold. Age counts as a risk factor above 60 without other risk factors, or at 50 with them."]],
  C(11), "epidemiology"),

S(PAD, IO_POP,
  "In an adult who smokes and has diabetes, peripheral artery disease risk is flagged from which age?",
  [["50 years",
    "Correct. With risk factors such as smoking, diabetes, hypertension, hyperlipidemia, a sedentary lifestyle or obesity, age counts from 50 years; without them it counts above 60."],
   ["30 years",
    "Thirty is well below either threshold. With risk factors such as smoking or diabetes the age threshold for peripheral artery disease is 50 years."],
   ["40 years",
    "Forty is younger than the threshold given. Age counts from 50 with other risk factors and above 60 without them."],
   ["60 years",
    "Over 60 is the threshold for someone without other risk factors. Smoking and diabetes bring the age threshold down to 50 years."]],
  C(11), "risk factors"),

S(PAD, IO_A,
  "How much does cigarette smoking raise peripheral artery disease risk?",
  [["Three times",
    "Correct. Cigarette smoking carries three times the risk of nonsmokers, alongside male sex, family history, diabetes, dyslipidemia, hypertension, obesity, elevated homocysteine and age."],
   ["Twice",
    "Doubling understates it for peripheral artery disease. Smoking carries three times the nonsmoker risk; it is stroke risk in carotid disease that smoking nearly doubles."],
   ["Five times",
    "Five times overstates it. Cigarette smoking carries three times the peripheral artery disease risk of nonsmokers."],
   ["Ten times",
    "Tenfold is far above the stated figure. Smoking triples the risk of peripheral artery disease compared with nonsmokers."]],
  C(11), "risk factors"),

S(PAD, IO_A,
  "Which elevated blood level is a peripheral artery disease risk factor tied to earlier atherosclerosis?",
  [["Homocysteine",
    "Correct. Elevated homocysteine, an amino acid, is associated with earlier onset of atherosclerosis and is listed among the peripheral artery disease risk factors; folic acid with vitamins B12 and B6 treats it."],
   ["Uric acid",
    "Uric acid is not among the listed risk factors. The amino acid linked to earlier-onset atherosclerosis is homocysteine."],
   ["Potassium",
    "Potassium plays no part in the risk factor list. Elevated homocysteine is the level associated with earlier-onset atherosclerosis."],
   ["Bilirubin",
    "Bilirubin is not a listed risk factor for arterial disease. The listed blood level is homocysteine, an amino acid tied to earlier atherosclerosis."]],
  C(11), "risk factors"),

S(PAD, IO_A,
  "Which three segments does lower-extremity peripheral artery disease involve?",
  [["Aortoiliac, femoral-popliteal, tibial",
    "Correct. Lower-extremity disease is described at three segmental sites: the aortoiliac, femoral-popliteal and tibial segments, and the level of blockage predicts where claudication is felt."],
   ["Iliac, renal, mesenteric",
    "The renal and mesenteric arteries do not supply the leg. The three lower-extremity segments are aortoiliac, femoral-popliteal and tibial."],
   ["Carotid, subclavian, femoral",
    "Carotid and subclavian arteries serve the head and arm. The lower-extremity segments are aortoiliac, femoral-popliteal and tibial."],
   ["Aortic arch, iliac, pedal",
    "The aortic arch is thoracic. Lower-extremity peripheral artery disease is divided into aortoiliac, femoral-popliteal and tibial segments."]],
  C(12), "etiology"),

S(PAD, IO_A,
  "Buttock and hip claudication points to disease at which level?",
  [["Aortoiliac segment",
    "Correct. Buttock and hip claudication reflects aortoiliac disease, with aching, possible hip or thigh weakness on walking, diminished femoral pulses and, when severe, erectile dysfunction."],
   ["Common femoral artery",
    "Common femoral disease produces thigh claudication with normal femoral pulses and decreased distal pulses. Buttock and hip pain points to the aortoiliac segment."],
   ["Popliteal artery",
    "Popliteal stenosis produces pain in the lower third of the calf. Buttock and hip claudication points higher, to the aortoiliac segment."],
   ["Tibial arteries",
    "Tibial and peroneal disease produces foot claudication. Buttock and hip claudication reflects the aortoiliac segment."]],
  C(14), "manifestation"),

S(PAD, IO_A,
  "Which site of claudication is the most common?",
  [["Calf",
    "Correct. Calf claudication is the most common: superficial femoral stenosis gives pain in the upper two-thirds of the calf, popliteal stenosis in the lower third, described as an escalating pain."],
   ["Buttock",
    "Buttock and hip claudication reflects aortoiliac disease and is the less frequent pattern. The calf is the most common site."],
   ["Thigh",
    "Thigh claudication reflects common femoral disease. The most common site is the calf, from superficial femoral or popliteal stenosis."],
   ["Foot",
    "Foot claudication comes from tibial and peroneal disease. The calf, not the foot, is the most common site."]],
  C(15), "manifestation"),

S(PAD, IO_A,
  "Pain in the upper two-thirds of the calf points to stenosis of which artery?",
  [["Superficial femoral artery",
    "Correct. Superficial femoral artery stenosis gives claudication in the upper two-thirds of the calf; popliteal stenosis gives it in the lower third, and calf pain is the most common pattern."],
   ["Popliteal artery",
    "Popliteal stenosis gives claudication in the lower third of the calf. The upper two-thirds maps to the superficial femoral artery."],
   ["Common femoral artery",
    "Common femoral disease produces thigh claudication. Upper calf pain maps to superficial femoral artery stenosis."],
   ["Posterior tibial artery",
    "Tibial disease produces foot claudication. Upper two-thirds calf pain maps to the superficial femoral artery."]],
  C(15), "differential"),

S(PAD, IO_A,
  "Which triad defines Leriche syndrome?",
  [["Claudication, weak femoral pulses, erectile dysfunction",
    "Correct. Leriche syndrome is the triad of claudication, absent or diminished femoral pulses and erectile dysfunction, the severe form of aortoiliac disease presenting as buttock and hip pain."],
   ["Claudication, foot ulcers, absent pedal pulses",
    "Foot ulcers and absent pedal pulses fit distal disease and critical limb ischemia. Leriche syndrome pairs claudication with weak femoral pulses and erectile dysfunction."],
   ["Rest pain, dependent rubor, erectile dysfunction",
    "Rest pain and dependent rubor mark critical ischemia. The Leriche triad is claudication, diminished femoral pulses and erectile dysfunction."],
   ["Calf pain, cool feet, delayed capillary refill",
    "These are general findings of distal arterial disease. The Leriche triad of aortoiliac disease is claudication, weak femoral pulses and erectile dysfunction."]],
  C(14), "manifestation"),

S(PAD, IO_A,
  "Intermittent claudication is usually relieved by how long a rest?",
  [["About 10 minutes",
    "Correct. Intermittent claudication is pain in one or more lower-extremity muscle groups brought on by activity and relieved with rest, usually within 10 minutes; the word comes from the Latin for limping."],
   ["About 1 minute",
    "A single minute is shorter than the usual recovery. Claudication is typically relieved by about 10 minutes of rest."],
   ["About 30 minutes",
    "Half an hour is longer than typical. Claudication usually settles within about 10 minutes of rest."],
   ["Several hours",
    "Pain lasting hours after stopping does not fit claudication. Rest pain of critical ischemia is constant; claudication settles within about 10 minutes."]],
  C(19), "manifestation"),

S(PAD, IO_A,
  "Besides degree of stenosis and vigor of exercise, what governs claudication severity?",
  [["Collateral circulation",
    "Correct. Claudication severity depends on the degree of stenosis, the collateral circulation and the vigor of exercise; it is the leg's counterpart of angina in the heart."],
   ["Blood glucose level",
    "Glucose control is a risk-factor target, not a determinant of claudication severity. Severity depends on stenosis, collaterals and exercise vigor."],
   ["Resting heart rate",
    "Heart rate is not listed as a determinant. Claudication severity depends on the degree of stenosis, collateral circulation and vigor of exercise."],
   ["Serum cholesterol",
    "Cholesterol drives the underlying atherosclerosis but does not set symptom severity directly. Severity depends on stenosis, collaterals and exercise vigor."]],
  C(20), "etiology"),

S(PAD, IO_A,
  "Which skin change is typical of a leg with severely reduced arterial flow?",
  [["Dry, thin, shiny skin",
    "Correct. With severely diminished flow the skin may be dry, thin, brittle and shiny, with loss of hair and toenails, brittle nails, muscle atrophy and poor wound healing."],
   ["Warm, moist, flushed skin",
    "Warm, moist skin does not fit arterial insufficiency; the ischemic limb is cool. Severely reduced flow leaves dry, thin, shiny skin."],
   ["Thick skin with dense hair",
    "Arterial insufficiency causes loss of dermal appendages such as hair and toenails. The skin becomes dry, thin and shiny."],
   ["Swollen skin with pitting",
    "Pitting swelling suggests venous or fluid problems. The arterially starved leg shows dry, thin, shiny skin with hair loss."]],
  C(28), "manifestation"),

S(PAD, IO_A,
  "How is limb skin temperature best assessed on examination?",
  [["With the back of the hand",
    "Correct. Skin temperature reflects dermal blood flow and is palpated with the back (dorsum) of the hand; the ischemic limb is cool, and the level of temperature change roughly marks the occlusion."],
   ["With the fingertips",
    "The fingertips are used for pulses and fine texture. Temperature is assessed with the back of the hand, which is more sensitive to it."],
   ["With the palm of the hand",
    "The palm is not the surface used. Temperature is palpated with the dorsum, the back of the hand."],
   ["With a thermometer probe",
    "No instrument is needed at the bedside. Skin temperature is compared by palpation with the back of the hand."]],
  C(33), "manifestation"),

S(PAD, IO_A,
  "Where do diminished or absent pulses appear in peripheral artery disease?",
  [["Below the stenosis",
    "Correct. Pulses are diminished or absent below the level of the arterial stenosis or occlusion, which is why pulses are checked from the brachial and radial down to the dorsalis pedis and posterior tibial."],
   ["Above the stenosis",
    "Flow above a stenosis is preserved, so pulses there stay normal. Loss of pulse occurs below the narrowed segment."],
   ["Only in the arms",
    "The arms are checked mainly for pressure, not because disease shows there. Pulse loss in leg disease is below the level of stenosis."],
   ["Only at the stenosis",
    "The narrowed segment itself is not where the pulse is lost. Diminished or absent pulses appear distal to, below, the stenosis."]],
  C(34), "manifestation"),

S(PAD, IO_A,
  "What is used when a lower-extremity pulse is difficult to palpate?",
  [["A handheld Doppler",
    "Correct. If a pulse is difficult to palpate, a handheld Doppler is used; auscultation also looks for bruits over the abdominal aorta, iliac, femoral and popliteal arteries."],
   ["A pulse oximeter",
    "Pulse oximetry gives oxygen saturation, not a distal pulse signal. A handheld Doppler is used when a pulse cannot be felt."],
   ["A reflex hammer",
    "A reflex hammer tests nerve reflexes. A handheld Doppler detects a pulse that is too weak to palpate."],
   ["A tuning fork",
    "A tuning fork tests vibration sense, part of the neurologic exam. A hard-to-feel pulse is found with a handheld Doppler."]],
  C(35), "initial test"),

S(PAD, IO_A,
  "In the Buerger test, how is the leg positioned first?",
  [["Raised to 45 degrees for 1 minute",
    "Correct. With the patient supine, one leg is elevated to 45 degrees and held for 1 minute; pallor shows arterial flow cannot overcome gravity, and the patient then sits with the legs hanging down."],
   ["Raised to 90 degrees for 5 minutes",
    "The elevation is 45 degrees, held for 1 minute. The patient then sits up with the legs hanging over the side of the bed."],
   ["Hung over the bed for 1 minute",
    "Dependency is the second step. The test starts with the leg raised to 45 degrees for 1 minute, looking for pallor."],
   ["Raised to 20 degrees for 10 minutes",
    "The angle and time differ. The leg is raised to 45 degrees for 1 minute with the patient supine."]],
  C(30), "initial test"),

S(PAD, IO_A,
  "Which color change marks the dependency phase of a positive Buerger test?",
  [["Deep red rubor",
    "Correct. When the legs hang down the foot turns deep red, dependent rubor, from reactive hyperemia (post-hypoxic vasodilation); in severe cases cyanosis may appear before the rubor."],
   ["Marked pallor",
    "Pallor is the finding on elevation, when arterial flow cannot overcome gravity. Dependency produces a deep red rubor."],
   ["Yellow tinge",
    "A yellow tinge has no place in the test. The dependency phase shows dependent rubor, a deep red color."],
   ["Brown staining",
    "Brown staining is not the arterial sign tested here. Hanging the leg down produces dependent rubor, a deep red color."]],
  C(30), "test finding"),

S(PAD, IO_A,
  "In darker skin, which signs help replace color change when judging blood flow?",
  [["Temperature, texture, capillary refill",
    "Correct. Pallor and redness can be harder to see in darker skin, so temperature, texture (rough, scaly, dry or atrophic skin, hair loss) and capillary refill time serve as additional indicators."],
   ["Pulse rate, blood pressure, weight",
    "These are vital signs, not skin indicators of limb perfusion. Temperature, texture and capillary refill are the added signs."],
   ["Sweating, nail color, hair color",
    "Nail and hair color are not the named markers. The substitutes are skin temperature, skin texture and capillary refill time."],
   ["Itch, bruising, swelling",
    "None of these is named as a perfusion sign. In darker skin, look at temperature, texture and capillary refill."]],
  C(30), "manifestation"),

S(PAD, IO_A,
  "Which bedside test is the important initial test for peripheral artery disease?",
  [["Ankle-brachial index",
    "Correct. The ankle-brachial index is a simple bedside test and the important initial test; duplex ultrasound is the initial imaging, and conventional angiography is the gold standard."],
   ["Conventional angiography",
    "Angiography is the invasive gold standard, used mainly to guide a planned intervention. The bedside initial test is the ankle-brachial index."],
   ["Computed tomography angiography",
    "Computed tomography angiography needs contrast and mainly guides intervention. The initial bedside test is the ankle-brachial index."],
   ["Magnetic resonance angiography",
    "Magnetic resonance angiography is an alternative when contrast allergy rules out computed tomography. The initial bedside test is the ankle-brachial index."]],
  C(42), "initial test"),

S(PAD, IO_A,
  "An ankle-brachial index of 0.62 fits which picture?",
  [["Claudication",
    "Correct. An ankle-brachial index between 0.4 and 0.9 fits claudication; above 0.9 up to 1.3 is normal, 0 to 0.4 is rest pain with tissue loss, and above 1.3 is abnormal from calcified arteries."],
   ["Normal flow",
    "Normal is above 0.9, up to 1.3. A value of 0.62 sits in the claudication band, 0.4 to 0.9."],
   ["Rest pain",
    "Rest pain with ulcer or gangrene sits at 0 to 0.4. A value of 0.62 falls in the claudication band."],
   ["Calcified arteries",
    "Calcified, noncompressible arteries give a value above 1.3. At 0.62 the index fits claudication."]],
  C(42), "test finding"),

S(PAD, IO_A,
  "What does an ankle-brachial index of 1.45 suggest?",
  [["Noncompressible arteries",
    "Correct. An index above 1.3 is abnormal because calcified artery walls cannot be compressed by the cuff, as in a diabetic patient; the number overstates flow."],
   ["Normal arterial flow",
    "Normal is above 0.9 up to 1.3. Above 1.3 the index is abnormal, from calcified, noncompressible arteries."],
   ["Mild claudication",
    "Claudication lowers the index to 0.4 to 0.9. A high value above 1.3 reflects calcified vessel walls."],
   ["Critical ischemia",
    "Critical ischemia drives the index down to 0 to 0.4. A value of 1.45 points to noncompressible, calcified arteries."]],
  C(42), "test finding"),

S(PAD, IO_A,
  "How is each leg's ankle-brachial index calculated?",
  [["Higher ankle pressure over higher arm pressure",
    "Correct. Each leg's index is the higher of that ankle's two pressures (posterior tibial or dorsalis pedis) divided by the higher of the two arm pressures."],
   ["Lower ankle pressure over lower arm pressure",
    "Both lower values would distort the ratio. Each leg uses its higher ankle pressure over the higher arm pressure."],
   ["Higher ankle pressure over lower arm pressure",
    "The denominator is the higher arm pressure, which is why both arms are measured. The numerator is that leg's higher ankle pressure."],
   ["Average ankle pressure over average arm pressure",
    "Averages are not used. The ratio takes that leg's higher ankle pressure over the higher of the two arm pressures."]],
  C(43), "test finding"),

S(PAD, IO_A,
  "Which value is reported as the patient's overall ankle-brachial index?",
  [["The lower leg value",
    "Correct. Each leg gets its own index, and the lower of the two numbers is the patient's overall ankle-brachial index."],
   ["The higher leg value",
    "Reporting the higher value would hide the worse leg. The overall index is the lower of the two legs."],
   ["The two legs averaged",
    "The two legs are not averaged. The lower of the two leg values is the overall index."],
   ["The symptomatic leg",
    "Symptoms do not choose the value. The lower of the two calculated leg values is reported as the overall index."]],
  C(43), "test finding"),

S(PAD, IO_A,
  "Which test is the mainstay initial imaging when arterial stenosis is suspected?",
  [["Duplex ultrasound",
    "Correct. Duplex ultrasound is noninvasive, needs no contrast or radiation, determines flow status and is the mainstay initial vascular imaging when stenosis or obstruction is suspected."],
   ["Conventional angiography",
    "Conventional angiography is the invasive gold standard, reserved mainly for guiding intervention. Initial imaging is duplex ultrasound."],
   ["Plain radiography",
    "Plain films do not assess arterial flow. Duplex ultrasound is the mainstay initial imaging study."],
   ["Computed tomography angiography",
    "Computed tomography angiography uses contrast and is used mainly to plan intervention. The initial noninvasive imaging is duplex ultrasound."]],
  C(46), "initial test"),

S(PAD, IO_A,
  "Which test is the gold standard for peripheral artery disease?",
  [["Conventional angiography",
    "Correct. Conventional angiography is the gold standard, the most accurate and informative test, but invasive: it requires vascular puncture, catheters at the stenosis and injected contrast."],
   ["Duplex ultrasound",
    "Duplex ultrasound is the mainstay initial imaging, not the gold standard. Conventional angiography is the most accurate test."],
   ["Ankle-brachial index",
    "The ankle-brachial index is the important initial bedside test. The gold standard is conventional angiography."],
   ["Pulse volume recording",
    "Pulse volume recordings locate site and severity in the vascular lab. The gold standard remains conventional angiography."]],
  C(48), "gold standard"),

S(PAD, IO_A,
  "Which condition contraindicates computed tomography angiography?",
  [["Decreased renal function",
    "Correct. Computed tomography angiography uses contrast, so contrast allergy and decreased renal function contraindicate it; magnetic resonance angiography is the alternative when contrast allergy is the problem."],
   ["A cardiac pacemaker",
    "A pacemaker contraindicates magnetic resonance angiography. Computed tomography angiography is limited by contrast allergy and decreased renal function."],
   ["Intracranial aneurysm clips",
    "Aneurysm clips contraindicate magnetic resonance angiography. For computed tomography angiography the barriers are contrast allergy and renal impairment."],
   ["A prior bypass graft",
    "A previous bypass is not a contraindication. Contrast allergy and decreased renal function contraindicate computed tomography angiography."]],
  C(47), "avoid"),

S(PAD, IO_A,
  "Which patient should not undergo magnetic resonance angiography?",
  [["One with a pacemaker",
    "Correct. Magnetic resonance angiography is contraindicated with pacemakers and intracranial aneurysm clips; it is the alternative to computed tomography angiography when contrast allergy is present."],
   ["One with contrast allergy",
    "Contrast allergy is the reason to choose magnetic resonance angiography over computed tomography angiography. Pacemakers and aneurysm clips contraindicate it."],
   ["One with renal impairment",
    "Decreased renal function contraindicates computed tomography angiography. Magnetic resonance angiography is barred by pacemakers and aneurysm clips."],
   ["One with diabetes",
    "Diabetes is not a contraindication to magnetic resonance angiography. Pacemakers and intracranial aneurysm clips are."]],
  C(47), "avoid"),

S(PAD, IO_A,
  "When are computed tomography angiography and conventional angiography mainly used in peripheral artery disease?",
  [["To guide a planned intervention",
    "Correct. Computed tomography angiography, magnetic resonance angiography and conventional angiography are used primarily for guidance when an endovascular or open surgical procedure is planned."],
   ["To screen people without symptoms",
    "Screening is done at the bedside with history and the ankle-brachial index. The angiographic studies mainly guide a planned intervention."],
   ["To replace the ankle-brachial index",
    "The ankle-brachial index stays the important initial test. Angiographic studies are mainly for planning intervention."],
   ["To track statin response",
    "Lipid therapy is followed with a lipid profile. Angiography is reserved mainly for guiding a planned intervention."]],
  C(48), "avoid"),

S(PAD, IO_A,
  "Why is renal function checked in peripheral artery disease?",
  [["Risk of renal insufficiency",
    "Correct. Patients with peripheral artery disease are at risk for renal insufficiency, so renal function joins the electrocardiogram, blood count, lipid profile, metabolic panel and hemoglobin A1c."],
   ["Risk of kidney stones",
    "Stones are not the concern named. Renal function is checked because these patients are at risk of renal insufficiency."],
   ["To measure homocysteine",
    "Homocysteine is a blood level, not a kidney function test. Renal function is checked for the risk of renal insufficiency."],
   ["To grade the claudication",
    "Claudication is graded by history and the ankle-brachial index. Renal function is checked because of renal insufficiency risk."]],
  C(49), "complication"),

S(PAD, IO_A,
  "What does hemoglobin A1c measure in the peripheral artery disease work-up?",
  [["Average glucose over three months",
    "Correct. Hemoglobin A1c measures the glucose average over the last three months, checked with a fasting glucose because diabetes is a major peripheral artery disease risk factor."],
   ["Average glucose over one week",
    "One week is too short. Hemoglobin A1c reflects the average glucose over the last three months."],
   ["The current fasting glucose",
    "A fasting glucose is a single reading from the metabolic panel. Hemoglobin A1c reflects the average over three months."],
   ["Average glucose over one year",
    "A year is too long. Hemoglobin A1c reflects roughly the last three months of glucose control."]],
  C(49), "test finding"),

S(PAD, IO_A,
  "What blood pressure goal applies to a diabetic patient with peripheral artery disease?",
  [["Below 130/80 mmHg",
    "Correct. The goal is below 140/90 mmHg in general, and below 130/80 mmHg for diabetic patients and those with renal failure, as part of risk-factor reduction."],
   ["Below 140/90 mmHg",
    "Below 140/90 mmHg is the general goal. Diabetes or renal failure lowers the goal to below 130/80 mmHg."],
   ["Below 150/90 mmHg",
    "That target is looser than either goal given. Diabetic patients aim for below 130/80 mmHg."],
   ["Below 110/70 mmHg",
    "That is tighter than the stated goal. Diabetes or renal failure sets the target at below 130/80 mmHg."]],
  C(50), "first-line"),

S(PAD, IO_A,
  "Which exercise program is more successful for claudication?",
  [["A supervised program",
    "Correct. Patients should be referred to an exercise rehabilitation program; a supervised program is more successful than a home-based one, and consistent moderate exercise improves walking distance."],
   ["A home-based program",
    "Home-based exercise helps but is less successful. A supervised exercise rehabilitation program works better."],
   ["Rest until pain resolves",
    "Rest avoids symptoms but does not improve walking distance. Consistent supervised exercise does."],
   ["Brief sprint training",
    "Vigorous sprinting is not the prescription. Consistent moderate exercise in a supervised program improves walking distance."]],
  C(50), "referral"),

S(PAD, IO_A,
  "What is the minimum exercise prescription for peripheral artery disease?",
  [["30-45 minutes, three times weekly",
    "Correct. The minimum is 30 to 45 minutes three times per week of consistent moderate exercise, which improves walking distance, ideally within a supervised rehabilitation program."],
   ["10 minutes, once weekly",
    "That is far below the minimum. The prescription is 30 to 45 minutes three times per week."],
   ["60 minutes, twice weekly",
    "Frequency matters as well as length. The minimum is 30 to 45 minutes, three times a week."],
   ["15 minutes, five times weekly",
    "The sessions are too short. The minimum is 30 to 45 minutes, three times per week."]],
  C(50), "agent/regimen"),

S(PAD, IO_A,
  "Which drugs are the antiplatelet agents used in peripheral artery disease?",
  [["Aspirin, clopidogrel, cilostazol",
    "Correct. The antiplatelet agents are aspirin, clopidogrel and cilostazol; they lower overall cardiovascular risk from heart attack and stroke and improve walking distance."],
   ["Simvastatin, pravastatin, pentoxifylline",
    "Simvastatin and pravastatin are the lipid-lowering drugs and pentoxifylline is a xanthine derivative. The antiplatelets are aspirin, clopidogrel and cilostazol."],
   ["Heparin, alteplase, clopidogrel",
    "Heparin and alteplase belong to acute limb ischemia. The long-term antiplatelets are aspirin, clopidogrel and cilostazol."],
   ["Esmolol, nitroprusside, aspirin",
    "Esmolol and nitroprusside lower pressure in aortic dissection. The antiplatelets are aspirin, clopidogrel and cilostazol."]],
  C(51), "first-line"),

S(PAD, IO_A,
  "Besides improving walking distance, what benefit do antiplatelet agents give in peripheral artery disease?",
  [["Lower heart attack and stroke risk",
    "Correct. Antiplatelet agents decrease the overall risk of cardiovascular disease from heart attack and stroke, and improve walking distance by enhancing circulation."],
   ["Regression of existing plaque",
    "Plaque regression is not the benefit claimed. Antiplatelets reduce heart attack and stroke risk and improve walking distance."],
   ["Faster healing of arterial ulcers",
    "Ulcer healing depends on restoring blood supply. Antiplatelets reduce overall cardiovascular risk from heart attack and stroke."],
   ["Lower resting blood pressure",
    "Blood pressure is managed with antihypertensives. Antiplatelets reduce heart attack and stroke risk."]],
  C(51), "prognosis"),

S(PAD, IO_A,
  "What low-density lipoprotein target applies to a high-risk patient with peripheral artery disease?",
  [["Below 70 mg/dL",
    "Correct. The lipid target is a low-density lipoprotein below 100 mg/dL, and below 70 mg/dL for high-risk patients such as those with diabetes or continued smoking, using simvastatin or pravastatin."],
   ["Below 100 mg/dL",
    "Below 100 mg/dL is the general target. High risk, such as diabetes or continued smoking, lowers it to below 70 mg/dL."],
   ["Below 130 mg/dL",
    "That target is looser than either stated goal. High-risk patients aim for below 70 mg/dL."],
   ["Below 160 mg/dL",
    "That is far above the stated goals. High-risk patients with peripheral artery disease aim for below 70 mg/dL."]],
  C(52), "agent/regimen"),

S(PAD, IO_A,
  "Which therapy treats hyperhomocysteinemia in peripheral artery disease?",
  [["Folic acid, B12 and B6",
    "Correct. Hyperhomocysteinemia is treated with folic acid and vitamins B12 and B6; elevated homocysteine is an amino acid linked with earlier-onset atherosclerosis."],
   ["Vitamin D and calcium",
    "Vitamin D and calcium are not the listed therapy. Folic acid with vitamins B12 and B6 treats elevated homocysteine."],
   ["Iron and vitamin C",
    "Iron is not part of this treatment. Hyperhomocysteinemia is treated with folic acid and vitamins B12 and B6."],
   ["Pentoxifylline alone",
    "Pentoxifylline is the xanthine derivative for flow through narrowed arteries. Homocysteine is lowered with folic acid, B12 and B6."]],
  C(52), "agent/regimen"),

S(PAD, IO_A,
  "Pentoxifylline belongs to which drug class?",
  [["Xanthine derivative",
    "Correct. Pentoxifylline is a xanthine derivative, listed alongside the antiplatelet and lipid-lowering drugs as part of drug therapy for peripheral artery disease."],
   ["Antiplatelet agent",
    "The antiplatelet agents are aspirin, clopidogrel and cilostazol. Pentoxifylline is classed as a xanthine derivative."],
   ["Statin",
    "The statins named are simvastatin and pravastatin. Pentoxifylline is a xanthine derivative."],
   ["Thrombolytic",
    "The thrombolytic named is alteplase, for acute limb ischemia. Pentoxifylline is a xanthine derivative."]],
  C(52), "agent/regimen"),

S(PAD, IO_A,
  "When is revascularization recommended for claudication?",
  [["Severe disability despite exercise and drugs",
    "Correct. Revascularization is recommended for claudication with severe functional disability and an inadequate response to exercise or pharmacological therapy."],
   ["As soon as claudication is diagnosed",
    "Claudication is first managed with risk-factor reduction, exercise and drugs. Revascularization follows an inadequate response with severe disability."],
   ["Whenever a femoral bruit is heard",
    "A bruit is an examination finding, not an indication. Revascularization is for severe disability despite exercise and drug therapy."],
   ["Only once dry gangrene has set in",
    "Waiting for gangrene is not the threshold. Severe functional disability despite exercise and drugs is enough."]],
  C(53), "escalation"),

S(PAD, IO_A,
  "Which procedures are the endovascular options for peripheral artery disease?",
  [["Angioplasty and atherectomy",
    "Correct. Endovascular procedures include percutaneous transluminal angioplasty, with or without stenting, and atherectomy; they are minimally invasive, similar to a heart catheterization."],
   ["Bypass and endarterectomy",
    "Bypass grafting and endarterectomy are open, invasive surgeries. The endovascular options are angioplasty, with or without stenting, and atherectomy."],
   ["Endarterectomy and amputation",
    "Both are open surgical procedures. The minimally invasive options are angioplasty and atherectomy."],
   ["Bypass and amputation",
    "Both are open operations. Endovascular treatment means angioplasty, with or without stenting, and atherectomy."]],
  C(53), "escalation"),

S(PAD, IO_A,
  "Which is a complication of peripheral bypass grafting?",
  [["Graft infection",
    "Correct. Bypass grafting is invasive and highly effective, and its complications are heart attack and stroke, infection of the graft and peripheral embolization."],
   ["Aortic dissection",
    "Dissection is not among the listed bypass complications. They are heart attack, stroke, graft infection and peripheral embolization."],
   ["Carotid stenosis",
    "Carotid stenosis is a separate atherosclerotic disease. Bypass complications include graft infection and peripheral embolization."],
   ["Venous ulceration",
    "Venous ulcers are not a listed complication. Bypass grafting risks heart attack, stroke, graft infection and peripheral embolization."]],
  C(57), "complication"),

S(PAD, IO_A,
  "What does an endarterectomy do?",
  [["Removes plaque through open surgery",
    "Correct. Endarterectomy is invasive surgery that removes plaque directly from inside the artery through an open incision; amputation is the last surgical option."],
   ["Dilates the artery with a balloon",
    "Balloon dilation is angioplasty, an endovascular procedure. Endarterectomy removes plaque from inside the artery through open surgery."],
   ["Reroutes flow around the blockage",
    "Rerouting flow with a vein or synthetic graft is bypass. Endarterectomy removes the plaque itself through an incision."],
   ["Dissolves clot through a catheter",
    "Dissolving clot is catheter-directed thrombolysis. Endarterectomy is open removal of plaque from inside the artery."]],
  C(58), "agent/regimen"),

S(PAD, IO_A,
  "Which feature separates peripheral neuropathy from claudication?",
  [["Pain unaffected by exercise",
    "Correct. Peripheral neuropathy, common in older patients with diabetes or alcoholism, is a continuous burning sensation in the foot that exercise does not affect, unlike claudication."],
   ["Pain relieved by rest",
    "Relief with rest is the pattern of claudication. Neuropathic burning continues regardless of exercise or rest."],
   ["Pain in the calf muscle",
    "Calf pain is the most common site of claudication. Neuropathy gives a continuous burning in the foot."],
   ["Pain brought on by walking",
    "Walking-induced pain describes claudication. Neuropathic pain is unaffected by exercise."]],
  C(40), "differential"),

S(PAD, IO_A,
  "What relieves spinal stenosis pain but not claudication?",
  [["Sitting or leaning forward",
    "Correct. Spinal stenosis gives claudication-like symptoms with numbness and weakness, relieved by rest and by sitting down or leaning forward to straighten the lumbar spine."],
   ["Standing still briefly",
    "Standing still relieves arterial claudication within minutes. Spinal stenosis needs sitting or leaning forward."],
   ["Raising the legs",
    "Raising the legs worsens arterial rest pain and does not define spinal stenosis. Sitting or leaning forward eases it."],
   ["Slowing the walking pace",
    "Slowing down lessens muscle demand in claudication. The discriminator for spinal stenosis is relief by sitting or leaning forward."]],
  C(41), "differential"),

S(PAD, IO_A,
  "Which leg-pain feature points to venous insufficiency rather than arterial disease?",
  [["Calf swelling on standing",
    "Correct. Venous insufficiency causes swelling and discomfort in the calf with standing, worse after prolonged walking, whereas arterial disease causes pain relieved by rest."],
   ["Cool, hairless skin",
    "Cool, hairless skin is a sign of arterial insufficiency. Venous insufficiency shows calf swelling on standing."],
   ["Pain relieved by rest",
    "Relief with rest defines arterial claudication. Venous insufficiency gives swelling and discomfort with standing."],
   ["Absent pedal pulses",
    "Absent pulses point to arterial occlusion. Venous insufficiency gives calf swelling with standing."]],
  C(40), "differential"),

S(PAD, IO_A,
  "Which cause of leg pain is often present at rest and worsened by exercise?",
  [["Hip or knee osteoarthritis",
    "Correct. Osteoarthritis of the hip or knee is often present at rest and exacerbated by exercise, and the pain may improve when weight is taken off the joint."],
   ["Intermittent claudication",
    "Claudication is absent at rest and brought on by activity. Osteoarthritis pain is present at rest and worse with exercise."],
   ["Venous insufficiency",
    "Venous insufficiency causes calf swelling and discomfort on standing. Joint pain present at rest and worse with exercise is osteoarthritis."],
   ["Peripheral neuropathy",
    "Neuropathy gives a continuous foot burning that exercise does not affect. Osteoarthritis worsens with exercise."]],
  C(41), "differential"),

S(PAD, IO_A,
  "What should patients with risk factors but few symptoms be asked about?",
  [["Decline in function over time",
    "Correct. Patients with peripheral artery disease risk factors often report no or few symptoms, so they should be asked about functional capacity and any decline in activity over time."],
   ["Nighttime leg cramps only",
    "Night cramps alone are not the focus. Asymptomatic patients should be asked about functional capacity and its decline."],
   ["Recent weight changes",
    "Weight is a general history item. The key question is functional capacity and decline in activity over time."],
   ["Skin color changes",
    "Color change is examined rather than asked about. The history focuses on functional capacity and decline."]],
  C(17), "manifestation"),

S(PAD, IO_A,
  "How should the patient be prepared before the peripheral vascular examination?",
  [["Supine, warm, rested 15 minutes",
    "Correct. The exam is best with the patient supine, warmed if the room is cold and rested for 15 minutes; in advanced ischemia, time lying flat can itself bring on pain."],
   ["Standing, after brisk walking",
    "Walking first would mix exertional changes into the findings. The patient should lie supine, warm and rested for 15 minutes."],
   ["Seated, after a large meal",
    "Neither position nor timing is right. The exam is done supine, warm, after 15 minutes of rest."],
   ["Supine, cooled, rested 5 minutes",
    "Cooling would itself make the limbs pale and cool. The patient should be warmed and rested 15 minutes, supine."]],
  C(26), "manifestation"),

S(PAD, IO_A,
  "What may fever indicate in a patient with peripheral artery disease?",
  [["An infected wound or ulcer",
    "Correct. Fever may indicate an infected skin wound or ulcer, and tachycardia and tachypnea may also point to infection, which is why vital signs open the examination."],
   ["Acute limb ischemia",
    "Acute limb ischemia presents with the six P's, not fever. Fever points to an infected wound or ulcer."],
   ["Worsening claudication",
    "Claudication is exertional pain without fever. Fever suggests infection of a skin wound or ulcer."],
   ["A new carotid plaque",
    "Carotid disease does not cause fever. In peripheral artery disease, fever suggests an infected wound or ulcer."]],
  C(27), "complication"),

S(PAD, IO_A,
  "Which risk-factor change heads peripheral artery disease management?",
  [["Smoking cessation",
    "Correct. Risk-factor reduction starts with smoking cessation, then antihypertensive therapy, diabetes control, exercise therapy and weight control."],
   ["Low-protein diet",
    "Diet protein is not part of the plan. Management starts with smoking cessation, then blood pressure, diabetes, exercise and weight."],
   ["Daily compression stockings",
    "Compression treats venous problems, not arterial disease. Management begins with smoking cessation."],
   ["Strict bed rest",
    "Rest does not improve walking distance. Management starts with smoking cessation and includes regular exercise."]],
  C(50), "education"),

S(PAD, IO_A,
  "What is reactive hyperemia?",
  [["A brief surge in flow after ischemia",
    "Correct. Reactive hyperemia is a transient increase in blood flow after a brief period of ischemia; accumulated metabolites such as carbon dioxide, lactic acid and adenosine cause vasodilation."],
   ["A lasting fall in flow after exercise",
    "A lasting fall in flow is not the phenomenon. Reactive hyperemia is a transient surge after brief ischemia."],
   ["Pallor when the leg is raised",
    "Elevation pallor is the first half of the Buerger test. Reactive hyperemia is the flow surge that makes a dependent leg red."],
   ["Swelling of the leg on standing",
    "Swelling on standing suggests venous insufficiency. Reactive hyperemia is a transient post-ischemic increase in flow."]],
  C(29), "etiology"),

S(PAD, IO_A,
  "Which history question best measures claudication?",
  [["How far can you walk before pain?",
    "Correct. The history asks where the pain is, how far the patient can walk before it starts, whether that distance has changed, and how long rest takes to relieve it."],
   ["Does coughing make the pain worse?",
    "Pain with coughing points away from arterial disease. The key question is the walking distance before pain begins."],
   ["Is the pain worse after meals?",
    "Pain after meals is not a limb question. Claudication is measured by how far the patient can walk before pain."],
   ["Did the pain follow a cold?",
    "A preceding viral illness is irrelevant to claudication. The core question is walking distance before pain."]],
  C(18), "education"),
]
