# -*- coding: utf-8 -*-
"""Lecture 22 vignette pool C -- screening across the age groups, risk
estimation and the primary-prevention categories, lipoprotein(a), the physical
signs, lifestyle counseling and secondary-cause work-up.

KEYS ARE WRITTEN SHORT ON PURPOSE — detail lives in the explanation.

The populations objective lives mostly here (children 9 to 11, elective
screening from 2, adults from 20, and over-75 decisions). The second pediatric
screening window is not keyed: one slide says 17 to 19, the next 17 to 21.
The 10-year risk estimates used avoid 7.5% and 20% exactly. Named findings
carry their description from the deck (slides 32-36).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _cmse3_q import Q
from cms_e4l22_scope import *


def S(topic, io, q, opts, cite, slot):
    d = Q(topic, io, q, opts, cite); d["slot"] = slot; return d


def V(topic, io, q, opts, cite, slot, lead):
    d = S(topic, io, q, opts, cite, slot); d["lead"] = lead; return d


QUESTIONS = [

V("Screening", IO_POP,
  "A healthy 22-year-old man establishes care. He has never had cholesterol tested and has no symptoms or family history of heart disease. What is the most appropriate step regarding lipids?",
  [["Screen for high blood cholesterol",
    "Correct. Screening of all adults aged 20 years or older for high blood cholesterol is recommended, whatever their symptoms; most dyslipidemia is found on laboratory testing."],
   ["No testing until he turns 40",
    "Age 40 opens the 10-year risk pathway, but cholesterol screening is recommended from age 20."],
   ["Test only if xanthomas appear",
    "Most patients have no signs or symptoms, so waiting for xanthomas would miss them."],
   ["Coronary calcium score first",
    "Calcium scoring settles uncertain statin decisions at 40 to 75; it is not a screening test for a 22-year-old."]],
  C(65), "initial test", "next step"),

V("Screening", IO_POP,
  "A 10-year-old girl is seen for a well-child visit. She is healthy, and there is no known family history of lipid disorders. Which lipid test is appropriate?",
  [["A non-fasting lipid profile",
    "Correct. Pediatric patients are screened with a non-fasting lipid profile once between ages 9 and 11, and again later in adolescence."],
   ["A fasting panel after 12 hours",
    "In most children the initial screen is non-fasting, so an overnight fast is not needed at this visit."],
   ["No test until age 20",
    "Age 20 begins routine adult screening; children are screened once with a non-fasting profile between 9 and 11."],
   ["Skin biopsy for receptors",
    "Skin biopsy confirms homozygous familial hypercholesterolemia in a child with very high cholesterol, not routine screening."]],
  C(65), "initial test", "test"),

V("Screening", IO_POP,
  "A 3-year-old boy is brought for a routine visit. His father had a heart attack at 40 and was found to have very high cholesterol. What is the most appropriate step regarding the boy's lipids?",
  [["Elective lipid screening now",
    "Correct. Elective screening is appropriate for patients as young as 2 years old with a family history of heart disease or high cholesterol."],
   ["Wait until age 9 to 11",
    "Routine screening is at 9 to 11, but his father's premature disease and high cholesterol justify elective screening now."],
   ["Start a statin without testing",
    "A statin follows a diagnosis of familial hypercholesterolemia; he has not yet been tested."],
   ["Screen only after puberty",
    "His father's premature heart attack and high cholesterol make screening appropriate from age 2, well before puberty."]],
  C(66), "initial test", "next step"),

V("Risk assessment", IO_A,
  "A 48-year-old man without cardiovascular disease has hypertension and smokes. His clinician wants to estimate his 10-year risk of atherosclerotic disease to guide statin therapy. Which tool is appropriate?",
  [["Pooled Cohort Equation",
    "Correct. It estimates 10-year primary risk of atherosclerotic cardiovascular disease in patients 40 to 79 without pre-existing disease, using variables such as age, sex, cholesterol, systolic pressure, diabetes and smoking."],
   ["Skin biopsy for receptors",
    "Skin biopsy confirms homozygous familial hypercholesterolemia and does not estimate population risk."],
   ["Fundoscopic examination",
    "Fundoscopy finds lipemia retinalis in chylomicronemia and has no role in 10-year risk estimation."],
   ["Metabolic syndrome criteria",
    "The syndrome's five criteria define a diagnosis; they do not give a 10-year risk percentage."]],
  C(25), "initial test", "test"),

V("Primary prevention", IO_A,
  "A 45-year-old woman without diabetes has low-density lipoprotein of 120 mg/dL and a 10-year atherosclerotic risk of 3%. She has no risk-enhancing factors. What is the most appropriate management?",
  [["Emphasize lifestyle",
    "Correct. Low risk (under 5%) calls for a risk discussion that emphasizes lifestyle to reduce risk factors, rather than a statin."],
   ["High-intensity statin",
    "High intensity is for clinical disease, severe hypercholesterolemia or high 10-year risk, not a 3% estimate."],
   ["Moderate-intensity statin",
    "A moderate-intensity statin is started at intermediate risk when the discussion favors it; at 3% lifestyle is emphasized."],
   ["Ezetimibe alone",
    "Ezetimibe is an adjunct to a maximal statin in higher-risk patients, not therapy for low-risk primary prevention."]],
  C(96), "first-line", "treatment"),

V("Primary prevention", IO_A,
  "A 52-year-old woman without diabetes has a 10-year atherosclerotic risk of 6% and low-density lipoprotein of 150 mg/dL. She went through menopause at 38. What is the most appropriate next step?",
  [["Discuss a moderate-intensity statin",
    "Correct. At borderline risk (5% to under 7.5%), risk enhancers such as premature menopause before 40 prompt a risk discussion about moderate-intensity statin therapy."],
   ["Start a high-intensity statin",
    "High intensity is for very high low-density lipoprotein, clinical disease or high 10-year risk, not borderline risk."],
   ["No discussion is needed",
    "Borderline risk with an enhancer is exactly where a statin discussion is recommended."],
   ["Order a skin biopsy",
    "Skin biopsy confirms homozygous familial hypercholesterolemia and plays no part in this decision."]],
  C(105), "risk factors", "next step"),

V("Primary prevention", IO_A,
  "A 63-year-old man without diabetes has low-density lipoprotein of 160 mg/dL and a 10-year atherosclerotic risk of 24%. After discussion he agrees to treatment. What should therapy aim for?",
  [["Lower low-density lipoprotein 50% or more",
    "Correct. When 10-year risk is high (20% or more), the statin should reduce low-density lipoprotein by 50% or more; at intermediate risk the target is 30% or more."],
   ["Lower low-density lipoprotein 10% to 20%",
    "Even low-intensity statins exceed that; at high 10-year risk the aim is a reduction of 50% or more."],
   ["Lower triglyceride below 150 first",
    "Low-density lipoprotein is the primary target; triglyceride is addressed afterward if it stays above 200."],
   ["Raise high-density lipoprotein above 60",
    "High-density lipoprotein is best improved by lifestyle; the statin target is a percentage fall in low-density lipoprotein."]],
  C(104), "first-line", "treatment"),

V("Lipoprotein(a)", IO_B,
  "A 58-year-old man whose brother had a heart attack at 50 has lipoprotein(a) measured at 85 mg/dL. His low-density lipoprotein is 140 mg/dL. What does the lipoprotein(a) result mean for his management?",
  [["He needs aggressive low-density lowering",
    "Correct. Elevated lipoprotein(a) is a causal and independent risk factor for atherosclerotic disease, and a patient with it needs aggressive therapy to decrease low-density lipoprotein."],
   ["It is protective and lowers his risk",
    "Lipoprotein(a) is a causal factor for atherosclerotic disease and an independent risk factor, not protective."],
   ["He needs a fibrate for the value",
    "Fibrates are the triglyceride drugs; the response to high lipoprotein(a) is aggressive low-density lowering."],
   ["It changes nothing in his plan",
    "At 50 mg/dL or more it is a risk-enhancing factor and calls for aggressive low-density lowering."]],
  C(7), "first-line", "treatment"),

V("Clinical presentation", IO_B,
  "A 30-year-old woman has soft yellow plaques on both upper eyelids near the inner canthi (xanthelasmas). Her low-density lipoprotein is 205 mg/dL. Which counseling point is most appropriate?",
  [["They suggest an inherited lipid disorder",
    "Correct. Xanthelasmas usually indicate an underlying genetic condition, and ruling out primary causes matters because they influence her own risk and the management of her family members."],
   ["They are harmless and need no work-up",
    "In a young woman with high low-density lipoprotein they usually indicate an underlying genetic condition and warrant evaluation."],
   ["They show her triglyceride is very high",
    "Very high triglyceride produces eruptive xanthomas (small papules on the back and limbs), not eyelid plaques."],
   ["They are caused by her eye makeup",
    "Xanthelasmas are lipid deposits that usually indicate a genetic condition, not a reaction to cosmetics."]],
  C(35), "manifestation", "education"),

V("Clinical presentation", IO_B,
  "A 32-year-old man has a white-gray ring around the edge of each cornea (corneal arcus). His low-density lipoprotein is 250 mg/dL with a normal triglyceride, and his father died of a heart attack at 52. Which is the most likely diagnosis?",
  [["Heterozygous familial hypercholesterolemia",
    "Correct. Corneal arcus before 40 usually indicates a genetic condition, and low-density lipoprotein of 200 to 400 with normal triglyceride and premature family coronary disease fits the heterozygous form, in which arcus is common."],
   ["Homozygous familial hypercholesterolemia",
    "The homozygous form presents in childhood with xanthomas and total cholesterol of about 400 to above 1000; an adult with low-density lipoprotein of 250 fits one mutant allele."],
   ["Familial chylomicronemia syndrome",
    "Chylomicronemia raises triglyceride above 1000 with eruptive papules and lipemia retinalis; his triglyceride is normal."],
   ["Familial dysbetalipoproteinemia",
    "Dysbetalipoproteinemia raises triglyceride and total cholesterol together with palmar xanthomas; his triglyceride is normal."]],
  C(36), "differential", "diagnosis"),

V("Therapeutic lifestyle changes", IO_B,
  "A 47-year-old man with borderline-high low-density lipoprotein asks which foods can help lower his cholesterol. Which dietary advice is most appropriate?",
  [["Add soluble fiber and plant sterols",
    "Correct. Therapeutic lifestyle changes include less saturated fat, more soluble fiber and plant stanols or sterols, cholesterol-lowering substances found in grains, vegetables, fruits, nuts and seeds."],
   ["Add more saturated and trans fat",
    "Saturated and trans fat down-regulate hepatic low-density lipoprotein receptors and raise low-density lipoprotein, the opposite of the goal."],
   ["Eat more refined carbohydrate",
    "Excess carbohydrate increases hepatic very-low-density triglyceride secretion, worsening the lipid profile."],
   ["Cut out all vegetables",
    "Vegetables are among the natural sources of plant stanols and sterols, which lower cholesterol."]],
  C(74), "education", "education"),

V("Therapeutic lifestyle changes", IO_B,
  "A 54-year-old woman with dyslipidemia weighs 200 pounds and asks how much weight she should aim to lose. Which goal is most appropriate?",
  [["About 10 to 20 pounds",
    "Correct. Therapeutic lifestyle changes aim for a 5% to 10% reduction of initial weight; for 200 pounds that is 10 to 20 pounds."],
   ["About 1 to 2 pounds",
    "One to two pounds is only 0.5% to 1% of her weight, well short of the 5% to 10% goal."],
   ["About 60 to 80 pounds",
    "That is 30% to 40% of her weight, far beyond the 5% to 10% reduction set by the lifestyle plan."],
   ["No weight loss is needed",
    "Obesity raises hepatic very-low-density production, and a 5% to 10% loss is part of treatment."]],
  C(75), "education", "education"),

V("Therapeutic lifestyle changes", IO_A,
  "A 60-year-old man with a prior heart attack asks whether eating fish will help his heart. Which counseling point is most appropriate?",
  [["Eat fish at least twice a week",
    "Correct. Fatty fish or fish-oil supplements are associated with lower risk of coronary disease and coronary death, and at least 2 servings of fish per week are recommended."],
   ["Fish raises his coronary risk",
    "Fatty fish or fish-oil supplements are associated with lower coronary risk and coronary death, not higher."],
   ["Fish can replace his statin",
    "Fish is an addition to therapy; the statin remains the backbone of secondary prevention."],
   ["Eat fish only once a month",
    "Once a month falls short of the at least 2 servings a week that are recommended."]],
  C(87), "education", "education"),

V("Primary prevention", IO_A,
  "A 62-year-old woman who smokes a pack a day has a 10-year atherosclerotic risk of 13% and an uncertain statin decision. Her coronary artery calcium score is zero. Which conclusion is inappropriate?",
  [["Withholding a statin because of the zero",
    "Correct. A zero score lowers risk and can justify withholding or delaying a statin, except in cigarette smokers, diabetes and strong family history; she smokes, so the zero does not settle it."],
   ["Continuing the statin discussion",
    "The shared risk discussion continues and is appropriate, especially because smoking overrides the reassurance of a zero score."],
   ["Advising her to stop smoking",
    "Smoking cessation is part of therapeutic lifestyle changes and is always appropriate."],
   ["Counting smoking as a risk factor",
    "Smoking is a major coronary risk factor and a high-risk condition, so counting it is correct."]],
  C(106), "avoid", "avoid"),

V("Heterozygous familial hypercholesterolemia", IO_B,
  "A 38-year-old man with untreated heterozygous familial hypercholesterolemia asks why treatment matters when he feels well. Which complication is he at risk of?",
  [["A premature heart attack",
    "Correct. Heterozygous familial hypercholesterolemia accounts for up to 5% of premature heart attacks in men under 55 and women under 65, and it causes premature atherosclerotic disease."],
   ["Acute pancreatitis",
    "Pancreatitis is the risk of triglyceride above 500; triglyceride is normal in familial hypercholesterolemia."],
   ["Sudden death in childhood",
    "Sudden childhood death is the devastating complication of the homozygous form; he is an adult with one mutant allele."],
   ["Loss of vision",
    "Corneal arcus is a common marker of the disorder rather than its danger; the threat is premature coronary disease."]],
  C(51), "complication", "complication"),

V("Secondary causes", IO_B,
  "A 45-year-old woman has new swelling of both legs, heavy protein in her urine and low-density lipoprotein of 220 mg/dL. Before a statin is started, which condition should be ruled out?",
  [["Nephrotic syndrome",
    "Correct. Elevated low-density lipoprotein calls for ruling out nephrotic syndrome, which drives excess very-low-density production and raises triglyceride and low-density lipoprotein."],
   ["Familial chylomicronemia",
    "Chylomicronemia is a triglyceride disorder with pancreatitis and eruptive xanthomas, not edema and proteinuria."],
   ["Heterozygous familial form",
    "A genetic cause is sought only after secondary causes are ruled out, and her edema and proteinuria point to the kidney."],
   ["Metabolic syndrome",
    "Metabolic syndrome is diagnosed from waist, triglyceride, high-density lipoprotein, blood pressure and glucose, not proteinuria."]],
  C(92), "differential", "test"),

V("Diabetes statin group", IO_B,
  "A 67-year-old man with type 2 diabetes, hypertension and current smoking has low-density lipoprotein of 135 mg/dL. He has no atherosclerotic disease. Which statin intensity is reasonable for him?",
  [["High-intensity statin",
    "Correct. In diabetes at higher risk, especially with multiple risk factors or age 50 to 75, a high-intensity statin to lower low-density lipoprotein by 50% or more is reasonable."],
   ["Low-intensity statin",
    "Low intensity lowers low-density lipoprotein under 30%, too little for a diabetic with multiple risk factors."],
   ["No statin, lifestyle only",
    "Diabetes at 40 to 75 with low-density lipoprotein of 70 or more is itself a statin indication."],
   ["Statin only after a stroke",
    "Waiting for an event abandons primary prevention; his diabetes already qualifies him for a statin."]],
  C(102), "first-line", "treatment"),

V("Primary prevention", IO_POP,
  "An 81-year-old woman with no history of atherosclerotic disease asks whether she should start a statin for prevention. Her low-density lipoprotein is 145 mg/dL. What is the most appropriate approach?",
  [["Clinical assessment and risk discussion",
    "Correct. Above 75 in primary prevention the approach is clinical assessment and a risk discussion rather than an automatic prescription."],
   ["Automatic high-intensity statin",
    "High intensity is not automatic above 75 in primary prevention; the decision follows assessment and discussion."],
   ["Calculate the Pooled Cohort risk",
    "The Pooled Cohort Equation estimates risk for ages 40 to 79, so an 81-year-old falls outside its range."],
   ["Refuse any statin due to age",
    "Age alone does not rule out a statin; the approach is individual assessment and discussion."]],
  C(96), "agent/regimen", "next step"),

V("Clinical atherosclerotic disease", IO_A,
  "A 72-year-old man had a heart attack last year. He stopped his high-intensity statin because of muscle aches, which then resolved. What is the most appropriate next step?",
  [["Moderate-intensity statin",
    "Correct. If a high-intensity statin is not tolerated in clinical atherosclerotic disease, a moderate-intensity statin is used, so he still receives secondary prevention."],
   ["Stop all lipid therapy",
    "Abandoning therapy after a heart attack leaves him unprotected; the fallback is a moderate-intensity statin."],
   ["Fish oil in place of statins",
    "Fish oil is associated with lower coronary death but does not replace statin therapy in secondary prevention."],
   ["A fibrate instead",
    "Fibrates are the triglyceride drugs; his secondary prevention rests on a tolerated statin."]],
  C(97), "escalation", "next step"),

V("Statin therapy", IO_B,
  "A 47-year-old man started a moderate-intensity statin eight weeks ago. His low-density lipoprotein has fallen from 160 to 104 mg/dL. How is his response to therapy judged?",
  [["By the percentage fall from baseline",
    "Correct. Responses to lifestyle and statin therapy are defined by percentage reductions in low-density lipoprotein from baseline; his 35% fall matches a moderate-intensity response of 30% to under 50%."],
   ["By whether total cholesterol is 200",
    "Total cholesterol bands describe the lab table; statin response is judged by the percentage low-density reduction."],
   ["By whether any xanthomas persist",
    "Most patients never have xanthomas, so response is measured on the lipid panel as a percentage."],
   ["By his high-density lipoprotein alone",
    "Statins raise high-density lipoprotein modestly, but response is defined by the low-density percentage fall."]],
  C(107), "test finding", "test"),

V("Severe hypertriglyceridemia", IO_B,
  "A 51-year-old man with obesity and type 2 diabetes has a triglyceride of 720 mg/dL, elevated total cholesterol, reduced high-density lipoprotein and a normal low-density lipoprotein. Which is the most likely diagnosis?",
  [["Severe hypertriglyceridemia",
    "Correct. Triglyceride above 500 with elevated total cholesterol and reduced high-density lipoprotein, usually without raised low-density lipoprotein, defines it, typically on a polygenic background with obesity or insulin resistance."],
   ["Mixed dyslipidemia",
    "Mixed dyslipidemia raises low-density lipoprotein above 130 as well as triglyceride; his low-density lipoprotein is normal."],
   ["Heterozygous familial form",
    "Familial hypercholesterolemia raises low-density lipoprotein with normal triglyceride, the reverse of his panel."],
   ["Familial dysbetalipoproteinemia",
    "Dysbetalipoproteinemia raises triglyceride and total cholesterol together to 250 to 500 with palmar xanthomas."]],
  C(43), "test finding", "diagnosis"),

V("Homozygous familial hypercholesterolemia", IO_POP,
  "A 7-year-old boy with homozygous familial hypercholesterolemia and under 2% of normal receptor activity asks, through his parents, why he needs frequent sessions attached to a machine. Which explanation is most appropriate?",
  [["It filters the bad cholesterol out",
    "Correct. Apheresis is like dialysis: the elective removal of low-density particles from the circulation, and it is the treatment of choice for the homozygous disorder."],
   ["It replaces his missing liver cells",
    "Replacing receptors is what liver transplantation may do; apheresis removes low-density particles from the blood."],
   ["It lowers his triglyceride level",
    "His triglyceride is normal; the machine removes low-density lipoprotein particles."],
   ["It cures the disorder in weeks",
    "Apheresis removes particles repeatedly; the inherited receptor defect remains, so treatment continues."]],
  C(109), "first-line", "education"),

V("Secondary causes", IO_B,
  "A 58-year-old man with hypertension was switched to a beta blocker three months ago. His triglyceride has risen from 140 to 260 mg/dL, and his thyroid and kidney tests are normal. Which counseling point is most appropriate?",
  [["The beta blocker can raise triglyceride",
    "Correct. Beta blockers can elevate triglyceride, as can estrogen, glucocorticoids, isotretinoin and bexarotene, so a new rise after starting one should be recognized as a secondary cause."],
   ["The beta blocker lowers triglyceride",
    "Beta blockers are listed as a cause of raised triglyceride, not a treatment for it."],
   ["The rise must be familial disease",
    "A rise that follows a new drug points to the drug; genetic causes are considered once secondary causes are excluded."],
   ["The rise means he has hypothyroidism",
    "His thyroid tests are normal, so the timing points to the new beta blocker instead."]],
  C(62), "etiology", "education"),

V("Screening", IO_B,
  "A 44-year-old woman with a family history of premature heart disease had total and high-density cholesterol drawn without fasting at a health fair. What do these two values allow?",
  [["Calculation of her total-to-high-density ratio",
    "Correct. Total and high-density cholesterol need no fasting, give the total-to-high-density ratio (the most efficient and cost-effective way to predict coronary risk) and can be used for risk assessment."],
   ["Calculation of her low-density lipoprotein",
    "A calculated low-density value needs a fasting triglyceride, which a non-fasting health-fair sample does not provide."],
   ["Diagnosis of familial chylomicronemia syndrome",
    "Chylomicronemia is diagnosed from fasting triglyceride usually above 1000, which was not measured."],
   ["Confirmation of homozygous familial disease",
    "Homozygous disease is confirmed by skin biopsy and receptor activity, not by a screening ratio."]],
  C(66), "test finding", "test"),

V("Heterozygous familial hypercholesterolemia", IO_B,
  "A 36-year-old woman has just been told she has heterozygous familial hypercholesterolemia. She asks whether any single test can prove it. Which answer is accurate?",
  [["No definitive test exists for her form",
    "Correct. No definitive diagnostic test is available for the heterozygous form; the skin biopsy with receptor activity confirms only the homozygous disorder."],
   ["A skin biopsy proves it in her case",
    "Skin biopsy with receptor-activity measurement confirms the homozygous form, not the heterozygous one."],
   ["A calcium score of zero rules it out",
    "Calcium scoring guides primary-prevention statin decisions and cannot exclude an inherited receptor defect."],
   ["Fundoscopy settles the question",
    "Fundoscopy looks for lipemia retinalis in chylomicronemia and plays no part in confirming her disorder."]],
  C(52), "gold standard", "education"),
]
