# -*- coding: utf-8 -*-
"""Lecture 22 objective-style pool B -- risk assessment, clinical presentation,
the primary (genetic) disorders, secondary causes and screening.

KEYS ARE WRITTEN SHORT ON PURPOSE — detail lives in the explanation.

Weighted by Carter's signals: familial hypercholesterolemia homozygous vs
heterozygous (8.7 minutes, "big thing I need you guys to understand"),
familial chylomicronemia syndrome ("one that can save somebody's life"), mixed
dyslipidemia as the most common type, and ruling out secondary causes before a
statin. NOT keyed, because the deck contradicts itself: the second pediatric
screening window (17-19 on one slide, 17-21 on the next), and whether 10-year
risk is calculated at ">2" or "2 or more" risk factors. Prevalence numbers are
de-weighted (his own "you'll still pass" remark) and appear only where the
contrast between two disorders is the point.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _cmse3_q import Q
from cms_e4l22_scope import *


def S(topic, io, q, opts, cite, slot):
    d = Q(topic, io, q, opts, cite); d["slot"] = slot; return d


QUESTIONS = [

S("Risk assessment", IO_A,
  "Which is one of the major coronary risk factors identified by the Framingham Heart Study?",
  [["Physical inactivity",
    "Correct. The Framingham major risk factors are high blood pressure, high serum cholesterol, smoking, obesity, diabetes and physical inactivity."],
   ["Low dietary fiber",
    "Soluble fiber appears among the lifestyle treatments, but it is not one of the six Framingham major risk factors."],
   ["Elevated lipoprotein(a)",
    "Lipoprotein(a) is an independent risk factor and a risk enhancer, but it is not among the six original Framingham major risk factors."],
   ["Hypothyroidism",
    "Hypothyroidism is a secondary cause of raised low-density lipoprotein, not one of the Framingham major coronary risk factors."]],
  C(20), "risk factors"),

S("Risk assessment", IO_A,
  "How does a high-density lipoprotein of 60 mg/dL or more affect the coronary risk-factor count?",
  [["It removes one risk factor",
    "Correct. High-density lipoprotein of 60 mg/dL or more counts as a negative risk factor, so its presence removes one risk factor from the total; below 40 mg/dL it counts as a risk factor."],
   ["It adds one risk factor",
    "A low high-density lipoprotein below 40 mg/dL adds a risk factor; a level of 60 or more does the reverse and subtracts one."],
   ["It doubles the calculated risk",
    "High high-density lipoprotein lowers risk; it counts as a negative risk factor and takes one away from the total."],
   ["It has no effect on the count",
    "It does change the count: 60 mg/dL or more is a negative risk factor that removes one risk factor from the total."]],
  C(21), "risk factors"),

S("Risk assessment", IO_A,
  "Which family history counts as premature coronary heart disease?",
  [["A male first-degree relative before 55",
    "Correct. Premature coronary heart disease means disease in a male first-degree relative before 55 or a female first-degree relative before 65."],
   ["A male first-degree relative before 65",
    "65 is the cutoff for a female first-degree relative; for a male relative the threshold is before 55 years old."],
   ["A female first-degree relative before 55",
    "55 is the male cutoff; a female first-degree relative counts if her coronary disease began before 65."],
   ["Any second-degree relative before 70",
    "Only first-degree relatives count, with coronary disease before 55 in a male and before 65 in a female."]],
  C(21), "risk factors"),

S("Risk assessment", IO_A,
  "What does the Pooled Cohort Equation estimate?",
  [["10-year risk of atherosclerotic disease",
    "Correct. It estimates the 10-year primary risk of atherosclerotic cardiovascular disease in patients aged 40 to 79 without pre-existing cardiovascular disease, and it identifies statin candidates."],
   ["Lifetime risk of familial hypercholesterolemia",
    "Familial hypercholesterolemia is suspected from very high low-density lipoprotein and family history; no risk equation diagnoses it."],
   ["Risk of pancreatitis from triglycerides",
    "Pancreatitis risk follows triglyceride above 500 mg/dL; the equation estimates atherosclerotic cardiovascular risk."],
   ["30-day risk after a heart attack",
    "The equation is for primary prevention in people without pre-existing cardiovascular disease, over a 10-year horizon."]],
  C(25), "initial test"),

S("Risk assessment", IO_A,
  "A 10-year atherosclerotic risk of 12% falls in which category?",
  [["Intermediate",
    "Correct. The categories are low under 5%, borderline 5% to under 7.5%, intermediate from 7.5% to under 20%, and high above 20%."],
   ["Borderline",
    "Borderline is 5% to under 7.5%; a risk of 12% is above that band, in the intermediate range."],
   ["High",
    "High risk is above 20%; a risk of 12% sits in the intermediate band between 7.5% and 20%, one category lower."],
   ["Low",
    "Low risk is under 5%, well below a 12% estimate, which falls two categories higher in the intermediate band."]],
  C(26), "test finding"),

S("Risk assessment", IO_A,
  "Which history makes a patient very high risk for future atherosclerotic events?",
  [["Multiple major atherosclerotic events",
    "Correct. Very high risk means a history of multiple major events, or one major event plus multiple high-risk conditions. Major events are recent acute coronary syndrome, prior heart attack, ischemic stroke and symptomatic peripheral arterial disease."],
   ["A single high-risk condition alone",
    "One high-risk condition such as hypertension or age 65 or more is not enough; it takes multiple major events, or one event plus multiple conditions."],
   ["Hypertension without any event",
    "Hypertension is a high-risk condition, but very high risk requires at least one major atherosclerotic event with multiple high-risk conditions."],
   ["A borderline 10-year risk estimate",
    "A borderline estimate of 5% to under 7.5% is a primary-prevention category, not the very-high-risk group built on prior events."]],
  C(27), "risk factors"),

S("Risk assessment", IO_A,
  "Which is a major atherosclerotic cardiovascular disease event?",
  [["History of ischemic stroke",
    "Correct. Major events are a recent acute coronary syndrome within 12 months, a history of heart attack, a history of ischemic stroke and symptomatic peripheral arterial disease."],
   ["Current cigarette smoking",
    "Current smoking is listed as a high-risk condition that adds to an event, not as a major event itself."],
   ["Chronic kidney disease",
    "Chronic kidney disease is a high-risk condition in the very-high-risk definition, not a major atherosclerotic event."],
   ["Age of 65 or older",
    "Age 65 or more is a high-risk condition; the major events are heart attack, ischemic stroke, recent acute coronary syndrome and symptomatic peripheral arterial disease."]],
  C(27), "complication"),

S("Risk assessment", IO_A,
  "Which is a coronary heart disease risk equivalent?",
  [["Diabetes mellitus",
    "Correct. Coronary risk equivalents include diabetes mellitus, peripheral arterial disease, abdominal aortic aneurysm, symptomatic carotid disease and a Framingham risk above 20%."],
   ["Low dietary fiber",
    "Fiber intake is a lifestyle measure, not a condition that carries the same risk as established coronary heart disease."],
   ["Isolated high-density lipoprotein of 65",
    "A high-density lipoprotein of 60 or more is protective and counts as a negative risk factor, the opposite of a risk equivalent."],
   ["Borderline triglyceride of 170",
    "Borderline triglyceride of 150 to 199 is a lab category, not a coronary heart disease risk equivalent."]],
  C(29), "risk factors"),

S("Clinical presentation", IO_B,
  "Eruptive xanthomas are usually seen with extremely high levels of which lipoproteins?",
  [["Chylomicrons or very-low-density lipoprotein",
    "Correct. Eruptive xanthomas (clusters of small yellowish-white papules) are usually seen with extremely high chylomicrons or very-low-density lipoprotein, the triglyceride carriers."],
   ["Low-density lipoprotein or lipoprotein(a)",
    "High low-density lipoprotein goes with tendinous xanthomas on the Achilles, patella and back of the hand, not eruptive papules."],
   ["High-density lipoprotein or apolipoprotein A-I",
    "High-density lipoprotein and its structural apolipoprotein A-I are protective and produce no xanthomas; the eruptive form reflects the triglyceride-rich particles."],
   ["Intermediate-density lipoprotein alone",
    "Intermediate-density lipoprotein is the remnant of very-low-density lipoprotein and is not the particle behind eruptive xanthomas."]],
  C(32), "manifestation"),

S("Clinical presentation", IO_B,
  "Where are tendinous xanthomas typically found?",
  [["Achilles, patellar and hand tendons",
    "Correct. Tendinous xanthomas sit on the tendons of the Achilles, patella and back of the hand, may be seen with high low-density lipoprotein and usually indicate an underlying genetic condition."],
   ["Eyelids near the inner canthus",
    "Yellow plaques on the eyelids near the inner canthus are xanthelasmas, not tendon xanthomas."],
   ["Back, buttocks and extensor limbs",
    "Clusters of small papules over the back, buttocks and extensor limbs are eruptive xanthomas of very high triglyceride."],
   ["The rim of the cornea",
    "A white or gray ring at the edge of the cornea is corneal arcus, abnormal under age 40."]],
  C(33), "manifestation"),

S("Clinical presentation", IO_B,
  "What does corneal arcus before age 40 usually indicate?",
  [["A genetic lipid disorder",
    "Correct. Corneal arcus is a white or gray ring around the cornea from cholesterol deposition; common in older adults (arcus senilis), it usually indicates an underlying genetic condition before 40."],
   ["Normal aging of the eye",
    "Arcus in older adults is common and called arcus senilis, but under age 40 it is an abnormal finding pointing to a genetic condition."],
   ["Severe hypertriglyceridemia",
    "Very high triglyceride shows in the eye as lipemia retinalis (opalescent retinal vessels), not as a corneal ring."],
   ["Recent acute pancreatitis",
    "Pancreatitis is a risk of severe hypertriglyceridemia and has no corneal sign; arcus reflects cholesterol deposition."]],
  C(36), "manifestation"),

S("Clinical presentation", IO_B,
  "At what age does coronary artery disease count as a premature presentation of genetic dyslipidemia?",
  [["Ages 30 to 50",
    "Correct. Premature coronary artery disease at ages 30 to 50 appears with pancreatitis and the xanthomas as presentations that usually indicate an underlying genetic condition."],
   ["Ages 60 to 75",
    "Disease at 60 to 75 is not labeled premature; the presentation that suggests genetic dyslipidemia is coronary disease at 30 to 50."],
   ["Only after age 75",
    "Age above 75 is handled by clinical assessment and risk discussion; premature disease is the 30-to-50 range."],
   ["Only in infancy",
    "Symptomatic atherosclerosis before puberty is specific to homozygous familial hypercholesterolemia; the general premature range is 30 to 50."]],
  C(37), "manifestation"),

S("Metabolic syndrome", IO_B,
  "How many criteria establish metabolic syndrome?",
  [["Any three of five",
    "Correct. Any 3 of abdominal obesity by waist circumference, triglyceride above 150, low high-density lipoprotein, blood pressure above 130/85 and fasting glucose above 110 establish it."],
   ["Any two of five",
    "Two criteria are not enough; metabolic syndrome needs any three of the five defining levels."],
   ["All five together",
    "All five are not required; any three of the five defining levels are enough to establish the syndrome."],
   ["Any four of six",
    "There are five criteria, not six, and any three of them are enough to establish metabolic syndrome."]],
  C(38), "manifestation"),

S("Metabolic syndrome", IO_B,
  "Which measurement defines abdominal obesity for metabolic syndrome?",
  [["Waist circumference",
    "Correct. Abdominal obesity is defined by waist circumference, more than 40 inches in men and more than 35 inches in women, rather than by body weight or body mass index."],
   ["Body mass index",
    "Body mass index is not one of the defining levels; the criterion is measured waist circumference."],
   ["Total body weight",
    "Total weight does not define the criterion; waist circumference above 40 inches in men and 35 inches in women does."],
   ["Hip circumference",
    "Hip measurement is not used; waist circumference defines abdominal obesity for the syndrome."]],
  C(38), "differential"),

S("Severe hypertriglyceridemia", IO_B,
  "Which acute complication does severe hypertriglyceridemia put a patient at risk of?",
  [["Acute pancreatitis",
    "Correct. Triglyceride above 500 mg/dL carries a risk of acute pancreatitis; above 500 the plan is a very low-fat diet, weight management, activity and a fibrate, niacin or both."],
   ["Tendon rupture",
    "Tendon xanthomas belong to high low-density lipoprotein states such as familial hypercholesterolemia, and the danger of very high triglyceride is the pancreas, not the tendons."],
   ["Acute kidney injury",
    "Kidney disease is a secondary cause of raised triglyceride, not the acute complication of very high triglyceride."],
   ["Sudden death in childhood",
    "Sudden death in childhood from accelerated atherosclerosis is the most devastating complication of homozygous familial hypercholesterolemia."]],
  C(43), "complication"),

S("Severe hypertriglyceridemia", IO_B,
  "Which lipid pattern is typical of severe hypertriglyceridemia?",
  [["High triglyceride, low high-density, normal low-density",
    "Correct. Triglyceride above 500 mg/dL with elevated total cholesterol and reduced high-density lipoprotein, usually without elevated low-density lipoprotein or apolipoprotein B."],
   ["High low-density, normal triglyceride, high total",
    "Normal triglyceride with high low-density lipoprotein is the familial hypercholesterolemia pattern, the opposite picture."],
   ["High triglyceride and total both near 250 to 500",
    "Triglyceride and total cholesterol both at 250 to 500 mg/dL describe familial dysbetalipoproteinemia and its remnants."],
   ["High triglyceride over 150 and low-density over 130",
    "Triglyceride above 150 with low-density lipoprotein above 130 defines mixed dyslipidemia, not the severe form."]],
  C(43), "test finding"),

S("Familial chylomicronemia syndrome", IO_B,
  "What fundoscopic finding is seen in familial chylomicronemia syndrome?",
  [["Lipemia retinalis",
    "Correct. Lipemia retinalis is opalescence of the retinal blood vessels, seen with fasting triglyceride above 500 and usually above 1000 mg/dL, alongside eruptive xanthomas and pancreatitis."],
   ["Corneal arcus",
    "Corneal arcus is a white or gray corneal ring from cholesterol deposition, tied to genetic high-cholesterol states rather than chylomicronemia."],
   ["Xanthelasma",
    "Xanthelasmas are yellow plaques on the eyelids near the inner canthus, not a retinal finding on fundoscopy."],
   ["Papilledema",
    "Optic disc swelling is not the lipid sign here; the retinal sign of chylomicronemia is opalescent retinal vessels (lipemia retinalis)."]],
  C(44), "test finding"),

S("Familial chylomicronemia syndrome", IO_B,
  "How does familial chylomicronemia syndrome typically first present?",
  [["Severe abdominal pain from acute pancreatitis",
    "Correct. It can present in childhood or adulthood with severe abdominal pain from acute pancreatitis, plus eruptive xanthomas, lipemia retinalis and sometimes hepatosplenomegaly."],
   ["Tendon nodules on the Achilles tendon",
    "Achilles tendon xanthomas point to high low-density lipoprotein and familial hypercholesterolemia, not chylomicronemia."],
   ["Chest pain from coronary disease before 20",
    "Symptomatic atherosclerosis in childhood is the homozygous familial hypercholesterolemia picture, not the triglyceride syndrome."],
   ["Yellow creases across the palms",
    "Palmar xanthomas are the distinctive sign of familial dysbetalipoproteinemia, the remnant disorder."]],
  C(44), "manifestation"),

S("Familial hypercholesterolemia", IO_B,
  "What is the underlying defect in familial hypercholesterolemia?",
  [["Faulty low-density lipoprotein receptor",
    "Correct. A genetic mutation reduces low-density lipoprotein receptor function, so low-density lipoprotein is cleared from the circulation at a reduced rate, with normal triglycerides."],
   ["Mutated apolipoprotein E gene",
    "An apolipoprotein E mutation, with apolipoprotein E2 homozygosity, causes familial dysbetalipoproteinemia, the remnant disorder."],
   ["Impaired lipolysis of triglyceride",
    "Impaired triglyceride lipolysis is the etiology given for severe hypertriglyceridemia, not for familial hypercholesterolemia."],
   ["Excess clearance of high-density lipoprotein",
    "Excessive clearance or underproduction of high-density lipoprotein is a primary cause of low high-density lipoprotein."]],
  C(46), "etiology"),

S("Familial hypercholesterolemia", IO_B,
  "Which lipid pattern characterizes familial hypercholesterolemia?",
  [["Low-density usually over 190 with normal triglyceride",
    "Correct. Familial hypercholesterolemia raises low-density lipoprotein cholesterol, usually above 190 mg/dL, with normal triglycerides, tendon xanthomas and premature atherosclerotic disease."],
   ["Triglyceride over 1000 with normal low-density",
    "Fasting triglyceride usually above 1000 mg/dL is familial chylomicronemia syndrome, not familial hypercholesterolemia."],
   ["Triglyceride and total both at 250 to 500",
    "Matched elevation of triglyceride and total cholesterol at 250 to 500 mg/dL is familial dysbetalipoproteinemia."],
   ["High-density under 40 with normal low-density",
    "Isolated low high-density lipoprotein is its own problem; familial hypercholesterolemia is defined by very high low-density lipoprotein."]],
  C(46), "test finding"),

S("Familial hypercholesterolemia", IO_B,
  "How is familial hypercholesterolemia inherited?",
  [["Codominant genetic disorder",
    "Correct. It is codominant: homozygous patients carry two mutant alleles and heterozygous patients one, and the homozygous form presents in childhood while the heterozygous form is often found on screening."],
   ["X-linked recessive disorder",
    "Both sexes are affected and one allele produces disease, so it is not X-linked; it is codominant with homozygous and heterozygous forms."],
   ["Mitochondrial inheritance",
    "It arises from mutations in the low-density lipoprotein receptor gene, a codominant nuclear trait, not a mitochondrial one."],
   ["Acquired, not inherited",
    "It is genetic, and a strong family history of elevated lipids in parents and first-degree relatives is typical."]],
  C(47), "etiology"),

S("Familial hypercholesterolemia", IO_B,
  "How does homozygous familial hypercholesterolemia usually present?",
  [["In childhood, with xanthomas and early atherosclerosis",
    "Correct. The homozygous form presents in childhood with cutaneous xanthomas on the hands, wrists, elbows, knees, heels or buttocks and symptomatic atherosclerosis before puberty."],
   ["In middle age, found on routine screening",
    "Incidental discovery on routine screening, despite high cholesterol from birth, is typical of the heterozygous form."],
   ["In infancy, with pancreatitis and eruptive papules",
    "Pancreatitis and eruptive xanthomas belong to familial chylomicronemia syndrome, a triglyceride disorder."],
   ["In old age, with corneal arcus alone",
    "Arcus in older adults is common arcus senilis; the homozygous disease declares itself in childhood."]],
  C(49), "manifestation"),

S("Familial hypercholesterolemia", IO_B,
  "How is homozygous familial hypercholesterolemia confirmed?",
  [["Skin biopsy measuring receptor activity",
    "Correct. Diagnosis is confirmed by a skin biopsy with measurement of low-density lipoprotein receptor activity; by contrast, no definitive diagnostic test exists for the heterozygous form."],
   ["Fasting triglyceride above 1000",
    "Triglyceride above 1000 mg/dL points to familial chylomicronemia syndrome; familial hypercholesterolemia has normal triglycerides."],
   ["Coronary artery calcium scoring",
    "Calcium scoring helps when a primary-prevention statin decision is uncertain; it does not confirm the homozygous disorder."],
   ["Fundoscopy for retinal opalescence",
    "Opalescent retinal vessels (lipemia retinalis) belong to familial chylomicronemia syndrome, not familial hypercholesterolemia."]],
  C(50), "gold standard"),

S("Familial hypercholesterolemia", IO_B,
  "Which diagnostic statement is true of heterozygous familial hypercholesterolemia?",
  [["No definitive diagnostic test exists",
    "Correct. No definitive diagnostic test is available for the heterozygous form, which is recognized from low-density lipoprotein of 200 to 400, tendon xanthomas and corneal arcus."],
   ["Skin biopsy is the confirmatory test",
    "Skin biopsy with receptor-activity measurement confirms the homozygous form; the heterozygous form has no definitive test."],
   ["Fundoscopy settles the diagnosis",
    "Fundoscopy finds lipemia retinalis in chylomicronemia; it has no role in confirming heterozygous familial hypercholesterolemia."],
   ["A calcium score of zero excludes it",
    "Calcium scoring guides primary-prevention statin decisions and cannot exclude an inherited receptor defect."]],
  C(52), "gold standard"),

S("Familial hypercholesterolemia", IO_B,
  "What is the typical low-density lipoprotein range in heterozygous familial hypercholesterolemia?",
  [["200 to 400 mg/dL",
    "Correct. The heterozygous form is characterized by low-density lipoprotein of 200 to 400 mg/dL; the homozygous form runs total cholesterol from about 400 to above 1000 mg/dL."],
   ["130 to 159 mg/dL",
    "130 to 159 mg/dL is the borderline-high band of the general lab table, far below the heterozygous range."],
   ["Above 1000 mg/dL",
    "Total cholesterol reaching above 1000 mg/dL belongs to the homozygous form, not the heterozygous one."],
   ["100 to 129 mg/dL",
    "100 to 129 mg/dL is near or above optimal on the lab table and would not suggest familial hypercholesterolemia."]],
  C(51), "test finding"),

S("Familial hypercholesterolemia", IO_B,
  "Which is the prognosis of untreated receptor-negative homozygous familial hypercholesterolemia?",
  [["Rarely survive past the second decade",
    "Correct. Untreated receptor-negative patients (under 2% of normal receptor activity) rarely survive past the second decade; receptor-defective patients (2% to 25%) do better but develop cardiovascular disease by 30."],
   ["Normal life expectancy with diet alone",
    "Diet alone does not rescue the homozygous disease; untreated receptor-negative patients rarely reach their twenties."],
   ["Cardiovascular disease only after age 60",
    "Disease appears far earlier: symptomatic atherosclerosis before puberty and death often in the second decade."],
   ["Pancreatitis by early adulthood",
    "Pancreatitis is the risk of severe hypertriglyceridemia; homozygous familial hypercholesterolemia kills through accelerated atherosclerosis."]],
  C(48), "prognosis"),

S("Familial dysbetalipoproteinemia", IO_B,
  "Which skin finding is distinctive of familial dysbetalipoproteinemia?",
  [["Palmar xanthomas",
    "Correct. Its cutaneous xanthomas are distinctive: palmar xanthomas and tuberoeruptive xanthomas, and the disorder is associated with accelerated atherosclerosis."],
   ["Xanthelasma of the eyelids",
    "Yellow eyelid plaques usually indicate an underlying genetic condition but are not the distinctive sign of this remnant disorder."],
   ["Achilles tendon xanthomas",
    "Achilles tendon xanthomas are typical of heterozygous familial hypercholesterolemia, present in about 75% of patients."],
   ["Corneal arcus",
    "Corneal arcus is common in heterozygous familial hypercholesterolemia, not the distinctive sign of dysbetalipoproteinemia."]],
  C(56), "manifestation"),

S("Familial dysbetalipoproteinemia", IO_B,
  "What causes the lipid elevation in familial dysbetalipoproteinemia?",
  [["Accumulation of chylomicron and very-low-density remnants",
    "Correct. An apolipoprotein E mutation, associated with apolipoprotein E2 homozygosity, lets chylomicron and very-low-density remnants accumulate, so triglyceride and total cholesterol both rise to 250 to 500 mg/dL."],
   ["Reduced activity of the low-density lipoprotein receptor",
    "Reduced receptor activity is the familial hypercholesterolemia defect, which raises low-density lipoprotein with normal triglycerides."],
   ["Defective apolipoprotein B-100 on low-density lipoprotein",
    "Defective apolipoprotein B-100 is a separate disorder that raises low-density lipoprotein cholesterol with tendon xanthomas."],
   ["Increased clearance of high-density lipoprotein from plasma",
    "Excessive high-density lipoprotein clearance is a genetic cause of low high-density lipoprotein, not of remnant accumulation."]],
  C(55), "etiology"),

S("Familial defective apolipoprotein B-100", IO_B,
  "Which features does familial defective apolipoprotein B-100 share with familial hypercholesterolemia?",
  [["Tendon xanthomas and premature atherosclerotic disease",
    "Correct. Familial defective apolipoprotein B-100 causes elevated low-density lipoprotein cholesterol with tendon xanthomas and premature atherosclerotic cardiovascular disease."],
   ["Lipemia retinalis and recurrent acute pancreatitis",
    "Opalescent retinal vessels and pancreatitis are features of familial chylomicronemia syndrome, a severe triglyceride disorder."],
   ["Palmar xanthomas and remnant particle accumulation",
    "Palmar xanthomas and remnant accumulation belong to familial dysbetalipoproteinemia, caused by an apolipoprotein E mutation."],
   ["Isolated low high-density lipoprotein and obesity",
    "Low high-density lipoprotein with obesity is a secondary pattern to rule out, not the presentation of defective apolipoprotein B-100."]],
  C(53), "differential"),

S("Secondary causes", IO_B,
  "Which endocrine disorder should be screened for in a patient with elevated low-density lipoprotein?",
  [["Hypothyroidism",
    "Correct. Low thyroid hormone down-regulates hepatic low-density lipoprotein receptors and raises low-density lipoprotein, so patients with elevated levels should be screened for low thyroid."],
   ["Hyperthyroidism",
    "It is decreased thyroid hormone that down-regulates the receptors and raises low-density lipoprotein."],
   ["Adrenal insufficiency",
    "The adrenal disorder on the list is Cushing syndrome, glucocorticoid excess, which raises very-low-density synthesis and low-density lipoprotein."],
   ["Hyperparathyroidism",
    "Parathyroid disease is not among the secondary causes; hypothyroidism is the endocrine cause to exclude."]],
  C(61), "initial test"),

S("Secondary causes", IO_B,
  "Which medication can raise triglycerides and also increase high-density lipoprotein?",
  [["Estrogen",
    "Correct. Estrogen can elevate triglyceride while increasing high-density lipoprotein; monitor patients starting birth control pills or postmenopausal estrogen, or who are pregnant."],
   ["Anabolic steroids",
    "Anabolic steroids decrease high-density lipoprotein rather than raising it, the opposite of the estrogen effect on that fraction."],
   ["Glucocorticoids",
    "Glucocorticoids raise both triglyceride and low-density lipoprotein; the drug that raises triglyceride while increasing high-density lipoprotein is estrogen."],
   ["Beta blockers",
    "Beta blockers can elevate triglyceride without the rise in high-density lipoprotein that makes estrogen the answer here."]],
  C(62), "etiology"),

S("Secondary causes", IO_B,
  "How does excessive alcohol raise triglycerides?",
  [["It inhibits hepatic fatty acid oxidation",
    "Correct. Excessive alcohol inhibits hepatic oxidation of free fatty acids, raising triglyceride, which is why an alcohol history matters in any patient with elevated triglycerides."],
   ["It down-regulates hepatic receptors",
    "Down-regulated hepatic low-density lipoprotein receptors explain the cholesterol rise of hypothyroidism and of saturated or trans fat."],
   ["It blocks cholesterol absorption from food",
    "Blocking dietary cholesterol absorption describes a class of lipid-lowering drug, not how alcohol acts on the liver."],
   ["It destroys high-density lipoprotein",
    "Alcohol's listed effect is on triglyceride through fatty-acid oxidation; the drug that lowers high-density lipoprotein is anabolic steroids."]],
  C(60), "etiology"),

S("Screening", IO_B,
  "What determines the decision to screen for dyslipidemia?",
  [["Overall cardiovascular risk",
    "Correct. The decision to screen rests on overall cardiovascular risk (age, sex, hypertension, smoking, family history of premature coronary disease, diabetes) independent of lipid levels."],
   ["A prior abnormal lipid panel",
    "Screening is meant to find the abnormality in the first place, so it is driven by overall cardiovascular risk rather than a prior result."],
   ["Visible skin xanthomas",
    "Most patients have no signs, so waiting for xanthomas would miss them; overall cardiovascular risk drives screening."],
   ["Body weight alone",
    "Obesity is one risk factor, but screening decisions weigh age, sex, hypertension, smoking, family history and diabetes together."]],
  C(64), "initial test"),

S("Screening", IO_B,
  "Which screening test pair needs no fasting?",
  [["Total cholesterol and high-density lipoprotein",
    "Correct. Total and high-density cholesterol need no fasting, give the total-to-high-density ratio (the most efficient and cost-effective predictor of coronary risk) and support risk assessment."],
   ["Triglyceride and calculated low-density lipoprotein",
    "Triglyceride and a calculated low-density lipoprotein require a 9- to 12-hour fast before the sample is drawn."],
   ["Triglyceride and total cholesterol",
    "Triglyceride is the fasting-dependent value; only the total and high-density cholesterol pair is valid without fasting."],
   ["Calculated low-density and high-density lipoprotein",
    "The calculated low-density value relies on a fasting triglyceride, so this pair needs a 9- to 12-hour fast."]],
  C(66), "initial test"),

S("Screening", IO_POP,
  "When should most children first receive a non-fasting lipid screen?",
  [["Between ages 9 and 11",
    "Correct. Pediatric patients get a non-fasting lipid profile once between ages 9 and 11 and again later in adolescence; elective screening can start at 2 with a family history."],
   ["At birth for every infant",
    "Routine screening is not at birth; elective screening can begin as young as 2 years with a family history, and routine screening at 9 to 11."],
   ["Only after age 20",
    "Age 20 is the start of routine adult screening; children are screened once between 9 and 11."],
   ["Only if a xanthoma appears",
    "Most dyslipidemia is silent, so screening is scheduled rather than prompted by skin findings."]],
  C(65), "initial test"),

S("Screening", IO_POP,
  "How young can elective lipid screening begin in a child with a family history of heart disease or high cholesterol?",
  [["As young as 2 years",
    "Correct. Elective screening is appropriate for patients as young as two years old with a family history of heart disease or high cholesterol; most children get a first non-fasting screen at 9 to 11."],
   ["Not before age 9",
    "Routine screening begins at 9 to 11, but a family history allows elective screening as young as 2."],
   ["Not before puberty",
    "A family history of heart disease or high cholesterol justifies elective screening far earlier, from age 2."],
   ["Not before age 20",
    "20 is the adult screening age; a child with a strong family history can be screened from age 2."]],
  C(66), "initial test"),
S("Familial chylomicronemia syndrome", IO_B,
  "Where do the eruptive xanthomas of familial chylomicronemia syndrome cluster?",
  [["Back, buttocks and extensor limbs",
    "Correct. They are clusters of small yellowish-white papules on the back, buttocks and extensor surfaces of the arms and legs, alongside lipemia retinalis and pancreatitis."],
   ["Achilles and patellar tendons",
    "Nodules on the Achilles and patellar tendons are tendinous xanthomas of high low-density lipoprotein, not the eruptive papules of chylomicronemia."],
   ["Palms and palmar creases",
    "Palmar xanthomas are the distinctive sign of familial dysbetalipoproteinemia, the remnant disorder with an apolipoprotein E mutation."],
   ["Eyelids near the inner canthus",
    "Yellow plaques on the eyelids near the inner canthus are xanthelasmas, which usually indicate an underlying genetic condition."]],
  C(44), "manifestation"),

S("Familial hypercholesterolemia", IO_B,
  "What is the most devastating complication of homozygous familial hypercholesterolemia?",
  [["Accelerated atherosclerosis",
    "Correct. The most devastating complication is accelerated atherosclerosis, which can result in disability and sudden death in childhood, after symptomatic atherosclerosis before puberty."],
   ["Recurrent acute pancreatitis",
    "Acute pancreatitis is the danger of triglyceride above 500 mg/dL; triglyceride is normal in familial hypercholesterolemia."],
   ["Hepatosplenomegaly",
    "Hepatosplenomegaly may be present in familial chylomicronemia syndrome, not as the defining complication of the homozygous cholesterol disorder."],
   ["Loss of vision",
    "The devastating complication is vascular, not ocular: accelerated atherosclerosis causing disability and sudden death in childhood."]],
  C(49), "complication"),
]
