# CMS I Lecture 3 (Dermatology II) — SET 1 pool D: SLOT REBALANCE.
#
# Fills the slots check_slot_coverage.py measured as under floor: epidemiology,
# risk factors, gold standard, first-line, escalation, avoid, education,
# referral, complication and prognosis. Every question carries slot="...".
#
# Options drafted at matched lengths. Correct answer is ALWAYS written first.
SRC = "3. Dermatology  II.pptx"
def c(n): return f"{SRC}, Slide {n}"

IOA = "Objective a — Etiologies, manifestations, diagnosis and management of dermatological conditions"

POOL_D = [
 dict(topic="Erythema multiforme", io=IOA, slot="risk factors",
   q="Which risk factors are named for erythema multiforme?",
   opts=[
     ["Recurrent herpes simplex infection, immunosuppression, high-risk medications, recent respiratory infection and a prior episode",
      "Correct — a prior episode itself carries recurrence risk."],
     ["Chronic venous insufficiency, obesity, immobility, previous deep vein thrombosis and chronic lower-limb oedema",
      "Those are the risk factors for stasis dermatitis in Lecture 2."],
     ["Cumulative ultraviolet exposure, fair skin, outdoor work, immunosuppression and older age",
      "Those are the risk factors for actinic damage."],
     ["Nasal staphylococcal carriage, obesity, diabetes, occlusive clothing and humid weather",
      "Those are the risk factors for folliculitis in Lecture 4."]],
   c=0, cite=c(9)),

 dict(topic="Erythema multiforme", io=IOA, slot="differential",
   q="Which features separate a fixed drug eruption from erythema multiforme?",
   opts=[
     ["It recurs at the same site, leaves residual hyperpigmentation, and has few lesions without three concentric zones",
      "Correct — the three-zone target is what defines an erythema multiforme lesion."],
     ["It produces wheals that migrate, blanch fully and resolve within twenty-four hours of first appearing",
      "That describes urticaria."],
     ["It produces extensive epidermal detachment with mucosal involvement and systemic toxicity",
      "That describes Stevens-Johnson syndrome and toxic epidermal necrolysis."],
     ["It produces tender nodules on the anterior shins that never go on to ulcerate",
      "That describes erythema nodosum."]],
   c=0, cite=c(10)),

 dict(topic="Erythema multiforme", io=IOA, slot="first-line",
   q="How is herpes-triggered erythema multiforme managed acutely?",
   opts=[
     ["Supportive care with analgesia, antihistamines and wound care, plus oral aciclovir or valaciclovir",
      "Correct — any offending drug is discontinued immediately."],
     ["High-dose systemic corticosteroids continued until the whole eruption has fully cleared",
      "That is not the described acute management."],
     ["Immediate burn unit admission with intravenous immunoglobulin and cyclosporine",
      "That belongs to Stevens-Johnson syndrome and toxic epidermal necrolysis."],
     ["A short course of oral antibiotics directed at Mycoplasma pneumoniae",
      "Mycoplasma is a trigger, but antibiotics are not the acute treatment described."]],
   c=0, cite=c(12)),

 dict(topic="Erythema multiforme", io=IOA, slot="escalation",
   q="A patient has had four episodes of herpes-associated erythema multiforme this year. Which chronic measure is appropriate?",
   opts=[
     ["Suppressive antiviral therapy, such as aciclovir 400 mg twice daily",
      "Correct — preventing the herpes recurrence prevents the eruption."],
     ["A standing prescription for oral prednisone to take at each episode",
      "Steroid at each episode does not prevent recurrence."],
     ["Long-term oral antihistamines taken continuously through the year",
      "Antihistamines address pruritus rather than recurrence."],
     ["Annual phototherapy given as a five-week course each spring",
      "That is preventive therapy for polymorphous light eruption."]],
   c=0, cite=c(12)),

 dict(topic="Erythema multiforme", io=IOA, slot="complication",
   q="When should a patient with erythema multiforme major be hospitalised?",
   opts=[
     ["When oral intake is poor or mucosal disease is extensive",
      "Correct — those are the two stated triggers for admission."],
     ["When more than ten target lesions are present on the trunk",
      "Lesion count is not the stated trigger."],
     ["When the eruption has lasted longer than two weeks in total",
      "Duration alone is not the stated trigger."],
     ["When herpes simplex virus is confirmed as the underlying trigger",
      "A herpes trigger prompts antiviral therapy rather than admission."]],
   c=0, cite=c(12)),

 dict(topic="Dermatitis herpetiformis", io=IOA, slot="etiology",
   q="What is the immunological basis of dermatitis herpetiformis?",
   opts=[
     ["Immunoglobulin A antibodies against epidermal transglutaminase, forming complexes that deposit in the dermal papillae",
      "Correct — complement and neutrophils are then activated, producing subepidermal blisters."],
     ["Immunoglobulin G antibodies directed against the epidermal basement membrane zone at the dermal junction",
      "That is bullous pemphigoid."],
     ["Immunoglobulin G antibodies against desmoglein between the keratinocytes",
      "That is pemphigus vulgaris."],
     ["A T-cell mediated destruction of melanocytes within the affected epidermis",
      "That is vitiligo."]],
   c=0, cite=c(16)),

 dict(topic="Dermatitis herpetiformis", io=IOA, slot="epidemiology",
   q="Which human leukocyte antigen haplotypes are strongly associated with dermatitis herpetiformis?",
   opts=[
     ["HLA-DQ2 and HLA-DQ8",
      "Correct — the same haplotypes that underlie coeliac disease."],
     ["HLA-B*15:02 and HLA-B*58:01",
      "Those are the severe cutaneous drug reaction associations."],
     ["HLA-B27 and HLA-DR4",
      "Those are associated with other rheumatological conditions."],
     ["HLA-Cw6 and HLA-DR3",
      "HLA-Cw6 is associated with early-onset psoriasis."]],
   c=0, cite=c(16)),

 dict(topic="Acanthosis nigricans", io=IOA, slot="etiology",
   q="What drives the commonest, insulin-resistant form of acanthosis nigricans?",
   opts=[
     ["Hyperinsulinaemia stimulating keratinocyte and fibroblast proliferation through insulin-like growth factor 1 receptor cross-activation",
      "Correct. Malignant, drug-induced and endocrine forms make up the rest."],
     ["Autoimmune destruction of the melanocytes within the affected intertriginous skin",
      "That is vitiligo."],
     ["Chronic ultraviolet exposure driving proliferation of the basal layer melanocytes and increased melanin production",
      "That is solar lentigo."],
     ["Immunoglobulin A deposition in the dermal papillae activating neutrophils",
      "That is dermatitis herpetiformis."]],
   c=0, cite=c(22)),

 dict(topic="Acanthosis nigricans", io=IOA, slot="etiology",
   q="Which drugs are named as causes of acanthosis nigricans?",
   opts=[
     ["Niacin, corticosteroids, oral contraceptives and protease inhibitors",
      "Correct — drug-induced disease sits alongside the insulin-resistant and malignant forms."],
     ["Carbamazepine, phenytoin, lamotrigine and allopurinol preparations",
      "Those cause Stevens-Johnson syndrome and toxic epidermal necrolysis."],
     ["Doxycycline, ciprofloxacin, amiodarone and the thiazide diuretics",
      "Those cause drug-induced photosensitivity."],
     ["Lithium, systemic steroids and acnegenic mineral oil exposure",
      "Those are the drug factors named for acne vulgaris."]],
   c=0, cite=c(22)),

 dict(topic="Urticaria", io=IOA, slot="first-line",
   q="What is first-line treatment for acute urticaria?",
   opts=[
     ["A second-generation antihistamine such as cetirizine, loratadine or fexofenadine",
      "Correct — a short prednisone course is added for severe acute disease."],
     ["Intramuscular epinephrine at 0.3 mg given immediately on presentation",
      "That is for anaphylaxis rather than for uncomplicated urticaria."],
     ["Omalizumab 300 mg subcutaneously repeated every four weeks",
      "That is for refractory chronic disease."],
     ["A first-generation sedating antihistamine taken four times daily",
      "Second-generation non-sedating agents are first line."]],
   c=0, cite=c(39)),

 dict(topic="Urticaria", io=IOA, slot="escalation",
   q="A patient with chronic urticaria is still symptomatic on a standard dose of a non-sedating antihistamine. What comes next?",
   opts=[
     ["Increase to up to four times the standard dose, and consider adding an H2 blocker",
      "Correct — omalizumab and ciclosporin follow if that fails."],
     ["Switch immediately to a long-term oral corticosteroid taken daily",
      "Long-term systemic steroid is not the described escalation."],
     ["Switch across to a first-generation sedating antihistamine at standard dose",
      "The escalation is in dose of the non-sedating agent, not a switch back."],
     ["Stop the antihistamine and start a leukotriene antagonist alone",
      "Stopping the antihistamine is not the described step."]],
   c=0, cite=c(39)),

 dict(topic="Urticaria", io=IOA, slot="avoid",
   q="Which situation requires immediate epinephrine rather than an antihistamine in a patient with urticaria?",
   opts=[
     ["Anaphylaxis — 0.3 mg intramuscularly, given immediately",
      "Correct. Antihistamines do not treat airway or circulatory compromise."],
     ["Wheals covering more than half of the body surface area",
      "Extent alone does not make it anaphylaxis."],
     ["Urticaria that has persisted for longer than six weeks",
      "That defines chronic urticaria, which is managed with antihistamines."],
     ["Urticaria in a patient who also has a known food allergy",
      "A known allergy alone does not require epinephrine."]],
   c=0, cite=c(39)),

 dict(topic="Erythema nodosum", io=IOA, slot="referral",
   q="Which referrals are named for erythema nodosum, and what determines each?",
   opts=[
     ["Pulmonology or rheumatology for Löfgren syndrome, gastroenterology for inflammatory bowel disease, infectious diseases for tuberculosis or endemic mycoses, dermatology for atypical cases",
      "Correct — the referral follows the suspected underlying cause."],
     ["Dermatology in every single case, since the diagnosis requires a deep incisional biopsy taken from one of the affected nodules before any treatment at all begins",
      "Biopsy is reserved for atypical presentations."],
     ["Vascular surgery in every case, since the nodules reflect venous disease",
      "Erythema nodosum is a panniculitis rather than a venous condition."],
     ["Oncology in every case, since the condition is usually paraneoplastic",
      "Malignancy is not the leading association here."]],
   c=0, cite=c(45)),

 dict(topic="Erythema nodosum", io=IOA, slot="education",
   q="Which is the central education point for a patient with erythema nodosum?",
   opts=[
     ["It is a reaction pattern rather than an isolated disease, so identifying and treating the trigger is the point",
      "Correct — that is why the workup matters as much as the symptomatic care."],
     ["It is an infection of the subcutaneous fat that requires a prolonged course of oral antibiotics",
      "It is a delayed hypersensitivity reaction rather than an infection."],
     ["It is a chronic condition that will require lifelong immunosuppressive therapy",
      "Most cases settle once the trigger is addressed."],
     ["It is a premalignant change that requires excision of the affected nodules",
      "The nodules are benign and are not excised."]],
   c=0, cite=c(45)),

 dict(topic="Granuloma annulare", io=IOA, slot="referral",
   q="Which referral is indicated for generalised granuloma annulare in an older adult?",
   opts=[
     ["Oncology, if lymphoma is suspected",
      "Correct, alongside dermatology for phototherapy or systemic therapy and endocrine workup for diabetes or thyroid disease."],
     ["Vascular surgery, if venous reflux is suspected",
      "That referral belongs to stasis dermatitis."],
     ["Thoracic surgery, if refractory disease is present",
      "That referral belongs to hyperhidrosis."],
     ["Ophthalmology, if any ocular symptoms have developed",
      "That referral belongs to rosacea and to severe drug reactions."]],
   c=0, cite=c(52)),

 dict(topic="Granuloma annulare", io=IOA, slot="prognosis",
   q="What should a patient with localised granuloma annulare be told about the course?",
   opts=[
     ["It is benign and self-limiting, so reassurance is the main intervention",
      "Correct — about half resolve within two years."],
     ["It is progressive and will generalise without early systemic therapy",
      "Localised disease is self-limiting."],
     ["It is premalignant and each ring should be excised with clear margins",
      "There is no malignant potential."],
     ["It is contagious and close contacts should be examined and treated",
      "The condition is not infectious."]],
   c=0, cite=c(52)),

 dict(topic="Pyoderma gangrenosum", io=IOA, slot="first-line",
   q="What is first-line systemic therapy for acute rapidly progressive pyoderma gangrenosum?",
   opts=[
     ["Prednisone at 0.5 to 1 mg/kg daily",
      "Correct — ciclosporin at 3 to 5 mg/kg daily is the alternative."],
     ["Infliximab at 5 mg/kg intravenously",
      "That is used in inflammatory bowel disease-associated and refractory disease."],
     ["Dapsone at 100 mg daily by mouth",
      "That is not the described first-line systemic agent."],
     ["Doxycycline at 100 mg twice daily",
      "Antibiotics do not treat this neutrophilic dermatosis."]],
   c=0, cite=c(60)),

 dict(topic="Pyoderma gangrenosum", io=IOA, slot="avoid",
   q="Which wound care measures are used in pyoderma gangrenosum, and which is avoided?",
   opts=[
     ["Moist dressings and non-adherent contact layers are used; debridement is avoided because pathergy worsens the ulcer",
      "Correct — topical tacrolimus or clobetasol goes to the wound edges for pain."],
     ["Sharp debridement is used at every dressing change; moist dressings are avoided because they macerate",
      "That reverses both halves and would enlarge the ulcer."],
     ["Dry gauze packing is used; any topical agent is avoided because of absorption",
      "Moist wound dressings are what is described."],
     ["Compression bandaging is used; elevation is avoided because it slows perfusion",
      "That is stasis and venous ulcer management."]],
   c=0, cite=c(60)),

 dict(topic="Pyoderma gangrenosum", io=IOA, slot="manifestation",
   q="Which pyoderma gangrenosum variant is most often associated with haematologic malignancy?",
   opts=[
     ["The bullous variant, with tense superficial bullae and blue-grey overhanging edges on the upper limbs and face",
      "Correct — acute myeloid leukaemia is the named association."],
     ["The classic ulcerative variant, with an undermined violaceous border on the lower extremities only",
      "That is the commonest form and associates with inflammatory bowel disease."],
     ["The pustular variant, with painful discrete pustules arising on inflamed skin",
      "That variant is not the one tied to haematologic malignancy."],
     ["The vegetative variant, with a slowly enlarging superficial verrucous plaque",
      "That variant is not the one tied to haematologic malignancy."]],
   c=0, cite=c(58)),

 dict(topic="Acne rosacea", io=IOA, slot="referral",
   q="Which rosacea presentation requires urgent referral, and to whom?",
   opts=[
     ["Ocular rosacea with keratitis, visual symptoms or corneal involvement — urgently to ophthalmology",
      "Correct. Dermatology handles refractory papulopustular and phymatous disease."],
     ["Phymatous rosacea of the nose — urgently to plastic surgery for operative shaping of it",
      "That referral is appropriate but not urgent."],
     ["Erythematotelangiectatic rosacea — urgently to dermatology for laser",
      "Laser is elective rather than urgent."],
     ["Papulopustular rosacea — urgently to gastroenterology for Helicobacter",
      "That referral applies only if eradication is being considered."]],
   c=0, cite=c(70)),

 dict(topic="Acne rosacea", io=IOA, slot="prognosis",
   q="What should a patient newly diagnosed with rosacea be told about the course?",
   opts=[
     ["It is a chronic condition requiring long-term management rather than a cure",
      "Correct — daily sun protection, trigger avoidance and gentle skincare go alongside."],
     ["It resolves permanently after a single twelve-week antibiotic course",
      "Therapy controls rather than eliminates the disease."],
     ["It resolves spontaneously within two years in about half of patients",
      "That is the course of granuloma annulare."],
     ["It progresses to rhinophyma in the great majority of affected patients",
      "Phymatous change occurs in a minority and predominantly in men."]],
   c=0, cite=c(70)),

 dict(topic="Hyperhidrosis", io=IOA, slot="referral",
   q="Which referral is named for palmar hyperhidrosis refractory to all other treatments?",
   opts=[
     ["Thoracic surgery, for endoscopic thoracic sympathectomy",
      "Correct — dermatology handles botulinum toxin, microwave thermolysis and glycopyrronium."],
     ["Dermatology, for a further trial of topical aluminium chloride",
      "That is the first-line therapy that has already failed."],
     ["Endocrinology, for assessment of thyroid and adrenal function",
      "That referral addresses secondary hyperhidrosis."],
     ["Psychiatry, since refractory palmar sweating is usually anxiety-driven",
      "Anxiety exacerbates but does not cause primary disease."]],
   c=0, cite=c(76)),

 dict(topic="Stevens-Johnson syndrome", io=IOA, slot="referral",
   q="Which long-term follow-up is named for a survivor of Stevens-Johnson syndrome?",
   opts=[
     ["Ophthalmology for symblepharon and corneal scarring, dermatology for dyspigmentation, urology or gynaecology for strictures, and psychological support for post-traumatic stress",
      "Correct — physical and occupational therapy also feature, for contracture prevention."],
     ["Dermatology alone, since the sequelae are confined to the skin surface",
      "The sequelae span several organ systems."],
     ["Infectious diseases alone, since the reaction is usually driven by some underlying infection rather than by any of the drugs the patient has been taking",
      "It is drug-induced in over 80% of cases."],
     ["No routine follow-up, since survivors recover completely within weeks",
      "Long-term morbidity is substantial."]],
   c=0, cite=c(84)),

 dict(topic="Toxic epidermal necrolysis", io=IOA, slot="complication",
   q="Which systemic complications are named in toxic epidermal necrolysis?",
   opts=[
     ["Sepsis, acute respiratory distress syndrome, acute kidney injury, electrolyte imbalance, hypovolaemia and gastrointestinal haemorrhage",
      "Correct — survivors also face sicca syndrome, lung disease and psychological trauma."],
     ["Acute post-streptococcal glomerulonephritis, acute rheumatic fever and a post-infectious reactive arthritis of the knee",
      "Those follow streptococcal infection."],
     ["Neurocutaneous melanosis, hydrocephalus and seizures in early childhood",
      "Those belong to large congenital melanocytic naevi."],
     ["Symblepharon alone, with no involvement of any other organ system",
      "Ocular scarring is one complication among many."]],
   c=0, cite=c(88)),

 dict(topic="Sunburn", io=IOA, slot="avoid",
   q="Which measure is specifically advised against in the management of sunburn?",
   opts=[
     ["Popping blisters, because intact blisters are protective",
      "Correct — cool rather than cold water is also specified."],
     ["Starting a nonsteroidal anti-inflammatory drug early in the course",
      "Early nonsteroidals are recommended."],
     ["Applying aloe vera or a soy-based topical moisturiser",
      "Those are soothing, though they do not alter healing."],
     ["Giving oral or intravenous fluids for systemic symptoms",
      "Hydration is part of management."]],
   c=0, cite=c(96)),

 dict(topic="Photodermatitis", io=IOA, slot="differential",
   q="Which feature separates photodermatitis from seborrhoeic dermatitis on the face?",
   opts=[
     ["Photodermatitis spares the nasolabial folds, which seborrhoeic dermatitis involves",
      "Correct — shadowed areas are protected from light."],
     ["Photodermatitis involves the nasolabial folds, which seborrhoeic dermatitis spares",
      "That reverses the two."],
     ["Photodermatitis produces greasy yellow scale, which seborrhoeic dermatitis lacks",
      "Greasy yellow scale is the seborrhoeic finding."],
     ["Photodermatitis is confined to the scalp, which seborrhoeic dermatitis spares",
      "Neither statement is correct."]],
   c=0, cite=c(101)),

 dict(topic="Polymorphous light eruption", io=IOA, slot="test finding",
   q="What does skin biopsy show in polymorphous light eruption, and how useful is it?",
   opts=[
     ["A perivascular lymphocytic infiltrate with dermal oedema — supportive but not pathognomonic",
      "Correct. The diagnosis is largely clinical, from history and morphology."],
     ["Full-thickness epidermal necrosis with dermal-epidermal separation — pathognomonic",
      "That is Stevens-Johnson syndrome and toxic epidermal necrolysis."],
     ["Granular immunoglobulin A at the dermal papillae — diagnostic in every case",
      "That is dermatitis herpetiformis."],
     ["Solar elastosis with tangled elastin fibres — the defining histological change",
      "That is dermatoheliosis."]],
   c=0, cite=c(106)),

 dict(topic="Actinic keratosis", io=IOA, slot="complication",
   q="Which features in an actinic keratosis are described as concerning?",
   opts=[
     ["Pruritus, tenderness and bleeding",
      "Correct — a hypertrophic, thickened and verrucous lesion also carries higher malignant potential."],
     ["A sandpaper texture on palpation of the lesion",
      "That is the ordinary description of the lesion."],
     ["A diameter between two and ten millimetres",
      "That is the typical size range."],
     ["A skin-coloured to red-brown appearance overall",
      "That is the typical colour range."]],
   c=0, cite=c(113)),

 dict(topic="Dermatoheliosis", io=IOA, slot="prognosis",
   q="What should a patient with established photoaging be told about what treatment can achieve?",
   opts=[
     ["Photoaging is largely preventable, and even established change can be meaningfully improved, especially pigmentation and texture",
      "Correct — tretinoin needs six to twelve months for visible results."],
     ["Photoaging is irreversible once it has become established, so treatment is purely preventive from that point onward",
      "Established change can be meaningfully improved."],
     ["Photoaging resolves spontaneously if all further sun exposure is avoided completely",
      "Avoidance prevents progression rather than reversing existing change."],
     ["Photoaging responds fully to a single course of laser resurfacing within weeks",
      "No single treatment achieves that."]],
   c=0, cite=c(120)),

 dict(topic="Dermatoheliosis", io=IOA, slot="referral",
   q="Which referral is named when squamous or basal cell carcinoma is confirmed in a photoaged patient?",
   opts=[
     ["Dermatologic surgery, including Mohs surgery",
      "Correct — oncology handles melanoma and advanced squamous cell carcinoma."],
     ["Plastic surgery, for advanced cosmetic restoration",
      "That referral is for cosmetic rather than oncological work."],
     ["Genetics, for suspected DNA repair disorder assessment",
      "That referral applies to premature photoaging suggesting xeroderma pigmentosum."],
     ["Rheumatology, for the connective tissue changes of solar elastosis",
      "Solar elastosis is not managed by rheumatology."]],
   c=0, cite=c(120)),
 dict(topic="Urticaria", io=IOA, slot="epidemiology",
   q="How are acute and chronic urticaria distinguished?",
   opts=[
     ["By duration — chronic urticaria has persisted beyond six weeks",
      "Correct. Both are mast cell-mediated, with transient pruritic wheals."],
     ["By severity — chronic urticaria involves more of the body surface",
      "Extent of involvement is not what defines the split."],
     ["By trigger — chronic urticaria always has an identifiable cause",
      "Over half of chronic cases have no identifiable trigger."],
     ["By age — chronic urticaria occurs only in adults over forty",
      "Age is not what defines the split."]],
   c=0, cite=c(33)),

 dict(topic="Hyperhidrosis", io=IOA, slot="risk factors",
   q="Which features should raise suspicion of secondary rather than primary hyperhidrosis?",
   opts=[
     ["Generalised sweating, nocturnal sweating, or an asymmetric distribution",
      "Correct — primary disease is bilateral, focal and absent during sleep."],
     ["Bilateral palmar sweating that has been present since adolescence",
      "That pattern describes primary focal disease."],
     ["Sweating that worsens with anxiety and improves in a cool room",
      "Anxiety exacerbates primary disease without indicating a secondary cause."],
     ["Sweating confined to the axillae with a family history of the same",
      "That pattern describes primary focal disease."]],
   c=0, cite=c(74)),

 dict(topic="Epidermolysis bullosa", io=IOA, slot="gold standard",
   q="Which investigation is the gold standard for epidermolysis bullosa?",
   opts=[
     ["Transmission electron microscopy with immunofluorescence antigen mapping",
      "Correct — a genetic panel and nutritional labs support it."],
     ["Perilesional direct immunofluorescence looking for granular immunoglobulin A",
      "That establishes dermatitis herpetiformis."],
     ["Punch biopsy showing full-thickness epidermal necrosis of the specimen",
      "That is Stevens-Johnson syndrome and toxic epidermal necrolysis."],
     ["Serum enzyme-linked immunosorbent assay for anti-desmoglein antibodies",
      "That supports pemphigus."]],
   c=0, cite=c(125)),
 dict(topic="Acne rosacea", io=IOA, slot="risk factors",
   q="Which patient group does rosacea predominantly affect?",
   opts=[
     ["Fair-skinned adults",
      "Correct — the phymatous subtype predominates in males."],
     ["Dark-skinned children",
      "That is not the group described."],
     ["Adolescent males only",
      "Acne vulgaris in adolescence is more common and severe in males; rosacea is an adult condition."],
     ["Pregnant women only",
      "Pregnancy is not a defining risk group here."]],
   c=0, cite=c(61)),
]
