# -*- coding: utf-8 -*-
"""Lecture 28 vignette pool C -- Cardiomyopathy: acute myocarditis and
restrictive cardiomyopathy.

KEYS ARE WRITTEN SHORT ON PURPOSE -- detail lives in the explanation.

Patient vignettes with a varied lead-in (the lead-in decides the answer).
Slides only; no recording exists yet (lecture 2026-10-01). Restrictive
disease is separated from constrictive pericarditis by cardiac magnetic
resonance imaging (slide 96), never by the Kussmaul sign, which slide 92 says
is common in both. Verapamil and diltiazem are named by generic name only.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _cmse3_q import Q
from cms_e5l28_scope import *


def S(topic, io, q, opts, cite, slot):
    d = Q(topic, io, q, opts, cite); d["slot"] = slot; return d


def V(topic, io, q, opts, cite, slot, lead):
    d = S(topic, io, q, opts, cite, slot); d["lead"] = lead; return d


MYO = "Acute myocarditis"
RCM = "Restrictive cardiomyopathy"

QUESTIONS = [

V(MYO, IO_A,
  "A 23-year-old previously healthy man has breathlessness, chest pain and exercise intolerance ten days after a flulike illness with fever, myalgia and diarrhea. He is tachycardic with a third heart sound (an early diastolic sound just after the second heart sound) and crackles at both bases. Troponin is elevated and coronary angiography is normal. Which is the most likely diagnosis?",
  [["Acute viral myocarditis",
    "Correct. Acute heart failure in an otherwise healthy young man with no cardiac history, one to two weeks after a flulike prodrome, with raised troponin and normal coronaries, is acute viral myocarditis."],
   ["Takotsubo cardiomyopathy",
    "Stress (Takotsubo) cardiomyopathy follows an emotional or physical stressor, and 90% of cases are postmenopausal women. A viral prodrome in a young man points to myocarditis."],
   ["Hypertrophic cardiomyopathy",
    "Hypertrophic cardiomyopathy is an inherited thickening of the septum with an outflow murmur and exertional syncope, not acute heart failure after a viral illness."],
   ["Restrictive cardiomyopathy",
    "Restrictive cardiomyopathy is rare, presents late with right-sided congestion, and follows infiltration, radiation or chemotherapy rather than a recent viral illness."]],
  C(51), "differential", "diagnosis"),

V(MYO, IO_A,
  "A 27-year-old man admitted with presumed viral myocarditis keeps deteriorating despite full medical treatment. Coronary angiography is normal, and valvular, toxic and ischemic causes of heart failure have been excluded. Which test establishes the diagnosis?",
  [["Endomyocardial biopsy",
    "Correct. Endomyocardial biopsy is the gold standard for myocarditis once other causes of heart failure are excluded, and it is recommended for acute deterioration of unknown origin that does not respond to treatment."],
   ["Cardiac catheterization",
    "Catheterization and angiography are used to rule out coronary ischemia as the cause of new heart failure, and his were normal. Biopsy is what establishes myocarditis."],
   ["Chest radiograph",
    "The chest radiograph in myocarditis is nonspecific and may only show cardiomegaly. The gold standard is endomyocardial biopsy."],
   ["Serum troponin",
    "Troponin indicates myonecrosis but does not identify its cause. Endomyocardial biopsy is the gold standard that establishes myocarditis."]],
  C(55), "gold standard", "test"),

V(MYO, IO_A,
  "A 21-year-old man has mild breathlessness and fatigue two weeks after a viral upper respiratory infection. Troponin is mildly raised, echocardiogram shows mildly reduced function, and he is hemodynamically stable. Which is the mainstay of his treatment?",
  [["Supportive care",
    "Correct. Treatment of myocarditis is directed toward the clinical scenario, and supportive care is the mainstay, with vasodilators, angiotensin-converting enzyme inhibitors, diuretics, antiarrhythmics or anticoagulation as needed."],
   ["Immediate biopsy",
    "Biopsy is reserved for acute deterioration of unknown origin not responding to treatment. A stable patient with mild symptoms is managed with supportive care."],
   ["Transplant listing",
    "Most patients with mild symptoms recover completely, so transplant listing has no place here. Supportive care is the mainstay of treatment."],
   ["Septal ablation",
    "Alcohol septal ablation treats outflow obstruction in hypertrophic cardiomyopathy. Myocarditis is treated with supportive care directed at the clinical scenario."]],
  C(56), "first-line", "treatment"),

V(MYO, IO_A,
  "A 19-year-old woman with a week of fever and myalgia now has severe breathlessness. She is cold and clammy with a blood pressure of 78/50, heart rate 128, raised jugular venous pressure and crackles throughout both lungs. Myocarditis is suspected. Which is the most appropriate next step?",
  [["Aggressive hemodynamic stabilization",
    "Correct. Myocarditis can present as cardiogenic shock, and although supportive care is the mainstay, treatment is directed toward the scenario and may require aggressive hemodynamic stabilization first."],
   ["Outpatient follow-up in one week",
    "She is in cardiogenic shock, a presentation of myocarditis that can be rapidly fatal. Delay is unsafe; aggressive hemodynamic stabilization comes first."],
   ["Elective biopsy before any support",
    "Biopsy can establish the diagnosis later, but it is not done before a patient in shock is stabilized. Aggressive hemodynamic stabilization comes first."],
   ["Exercise testing to grade severity",
    "Exercise testing has no place in cardiogenic shock. Myocarditis this severe needs aggressive hemodynamic stabilization."]],
  C(56), "escalation", "next step"),

V(MYO, IO_A,
  "A 45-year-old man presents with new-onset heart failure a week after a flulike illness. He smokes and has hyperlipidemia, so the team wants to exclude coronary disease before labeling this myocarditis. Which test rules out coronary ischemia as the cause of his new heart failure?",
  [["Cardiac angiography",
    "Correct. Cardiac angiography is used in the myocarditis work-up to rule out coronary ischemia as the cause of new-onset heart failure, which matters in a patient with coronary risk factors."],
   ["Endomyocardial biopsy",
    "Biopsy is the gold standard for confirming myocarditis once other causes are excluded, but it does not image the coronary arteries. Angiography rules out ischemia."],
   ["Sedimentation rate",
    "The erythrocyte sedimentation rate may be elevated in myocarditis but is nonspecific and cannot exclude coronary disease. Angiography does."],
   ["Chest radiograph",
    "The chest radiograph is nonspecific and may show cardiomegaly, but it cannot show the coronary arteries. Cardiac angiography rules out ischemia."]],
  C(54), "initial test", "test"),

V(MYO, IO_A,
  "A 26-year-old man with suspected viral myocarditis has an elevated troponin and normal coronary arteries. His cardiologist wants to see how much of the heart muscle is inflamed without an invasive procedure. Which test shows the extent of inflammation?",
  [["Gadolinium-enhanced cardiac magnetic resonance imaging",
    "Correct. Gadolinium-enhanced magnetic resonance imaging is part of the myocarditis work-up because the gadolinium improves visibility of the inflammation and shows its extent."],
   ["Ambulatory rhythm monitoring for forty-eight hours",
    "Ambulatory monitoring detects arrhythmias and grades sudden death risk, most notably in hypertrophic cardiomyopathy. It cannot show inflamed heart muscle."],
   ["Exercise echocardiography with treadmill testing",
    "Exercise echocardiography assesses functional capacity, ischemia and obstruction in hypertrophic cardiomyopathy. It does not show the extent of inflammation."],
   ["Right heart catheterization with pressure tracings",
    "Pressure tracings help evaluate restrictive physiology. Inflammation is shown noninvasively by gadolinium-enhanced magnetic resonance imaging."]],
  C(54), "test finding", "test"),

V(MYO, IO_A,
  "A 24-year-old woman with chest pain and breathlessness after a recent viral illness is being evaluated for myocarditis. Her electrocardiogram shows sinus tachycardia. Which laboratory result would indicate cardiac myonecrosis?",
  [["Elevated serum troponin",
    "Correct. Serum troponin is the indicator of cardiac myonecrosis in myocarditis. The rest of the work-up adds leukocytosis on the blood count, a possibly elevated sedimentation rate and electrocardiogram changes."],
   ["A low white cell count",
    "The blood count in myocarditis shows leukocytosis, a raised rather than low white cell count, and it does not measure myocardial injury. Troponin does."],
   ["Normal sedimentation rate",
    "The erythrocyte sedimentation rate may be elevated in myocarditis, and in either case it does not indicate myonecrosis. Troponin is the marker of heart muscle injury."],
   ["A low natriuretic peptide",
    "A B-type natriuretic peptide below 100 pg/mL argues against heart failure; it is not a marker of myonecrosis. Elevated troponin is."]],
  C(54), "test finding", "test"),

V(MYO, IO_A,
  "A 22-year-old man has recovered from mild viral myocarditis and feels well at discharge. He asks whether he needs any long-term follow-up with a cardiologist. Which later complication does follow-up watch for?",
  [["Dilated cardiomyopathy",
    "Correct. Most patients with mild myocarditis recover completely, but one third subsequently develop dilated cardiomyopathy, and viral myocarditis accounts for about 20% of dilated cardiomyopathy cases."],
   ["Hypertrophic cardiomyopathy",
    "Hypertrophic cardiomyopathy is mostly inherited through sarcomere gene mutations and is not a consequence of myocarditis. One third of patients later develop dilated cardiomyopathy."],
   ["Restrictive cardiomyopathy",
    "Restrictive cardiomyopathy follows infiltration, storage disease, sarcoidosis or radiation and chemotherapy. After myocarditis, the late risk is dilated cardiomyopathy."],
   ["Takotsubo cardiomyopathy",
    "Takotsubo cardiomyopathy is a transient response to emotional or physical stress, mostly in postmenopausal women. Myocarditis leads on to dilated cardiomyopathy in one third."]],
  C(50), "complication", "complication"),

V(MYO, IO_A,
  "A 20-year-old man with acute myocarditis after a flulike illness is on the ward with heart failure symptoms. He reports new palpitations, and his nurse notes a brief episode of lightheadedness. Which complication poses the most immediate threat to his life?",
  [["Ventricular arrhythmia",
    "Correct. Palpitations, syncope or sudden cardiac death in myocarditis are due to underlying ventricular arrhythmias or atrioventricular block, and myocarditis can cause rapidly progressive, often fatal, arrhythmia."],
   ["Aortic dissection",
    "Aortic dissection is not a complication of myocarditis. The life-threatening risk behind palpitations and presyncope here is ventricular arrhythmia or heart block."],
   ["Pericardial thickening",
    "Pericardial thickening marks constrictive pericarditis, the differential of restrictive cardiomyopathy. Myocarditis threatens life through ventricular arrhythmia."],
   ["Mitral valve prolapse",
    "Mitral valve prolapse is a valve disorder unrelated to myocarditis. Palpitations with near-syncope in myocarditis signal ventricular arrhythmia or heart block."]],
  C(51), "complication", "complication"),

V(MYO, IO_A,
  "A 29-year-old man with acute myocarditis after a viral illness has fluid retention with bilateral leg edema and crackles, but his blood pressure is stable. He is receiving supportive care. Which medication may be added as needed for his fluid retention?",
  [["A diuretic",
    "Correct. Supportive care is the mainstay of myocarditis treatment, and medications are added as needed for the clinical scenario: diuretics for fluid retention, with vasodilators, angiotensin-converting enzyme inhibitors, antiarrhythmics and anticoagulation as indicated."],
   ["A positive inotrope",
    "He is hemodynamically stable, so nothing calls for an inotrope. Fluid retention in myocarditis is treated with a diuretic as part of supportive care."],
   ["A thrombolytic drug",
    "Thrombolytics dissolve clot and have no role in myocarditis fluid overload. A diuretic is added as needed for fluid retention."],
   ["Alcohol septal ablation",
    "Septal ablation treats outflow obstruction in hypertrophic cardiomyopathy. Fluid retention in myocarditis is managed with a diuretic."]],
  C(56), "agent/regimen", "treatment"),

# ---- Restrictive cardiomyopathy (slides 83-99) ----

V(RCM, IO_A,
  "A 72-year-old man has months of progressive breathlessness, abdominal swelling and bilateral pedal edema. He prefers to sit upright. Jugular venous pressure is raised and he has a Kussmaul sign (jugular venous pressure rises with inspiration), hepatomegaly and ascites. His electrocardiogram shows low voltage (small complexes) in all leads, and echocardiogram shows normal-sized ventricles, marked biatrial enlargement and a preserved ejection fraction. Which is the most likely diagnosis?",
  [["Restrictive cardiomyopathy",
    "Correct. Stiff ventricles with a near-normal cavity, preserved ejection fraction and big atria, presenting late with right-sided failure, are restrictive cardiomyopathy; low voltage points to amyloidosis, the most common cause in the United States."],
   ["Dilated cardiomyopathy",
    "Dilated cardiomyopathy shows dilated, thin-walled ventricles with a reduced ejection fraction. Normal-sized ventricles with a preserved fraction and big atria are restrictive."],
   ["Hypertrophic cardiomyopathy",
    "Hypertrophic cardiomyopathy shows asymmetric septal thickening with an outflow murmur and prominent Q waves rather than low voltage. Right-sided congestion with big atria fits restrictive disease."],
   ["Takotsubo cardiomyopathy",
    "Stress cardiomyopathy is a sudden, transient apical weakness after a stressor. Months of right-sided congestion with stiff ventricles and big atria is restrictive disease."]],
  C(85), "differential", "diagnosis"),

V(RCM, IO_A,
  "A 58-year-old woman received mediastinal radiation and chemotherapy for a chest cancer 15 years ago. She now has progressive exercise intolerance, orthopnea (breathlessness lying flat), ascites and swollen legs. Echocardiogram shows stiff ventricles of normal size, marked atrial enlargement and abnormal diastolic function with a preserved ejection fraction. Which is the most likely diagnosis?",
  [["Restrictive cardiomyopathy",
    "Correct. Mediastinal radiation and chemotherapy cause inflammation and then fibrosis that restricts filling, and a prior history of radiation or chemotherapy is a named clue in restrictive cardiomyopathy."],
   ["Dilated cardiomyopathy",
    "Chemotherapy can also cause dilated cardiomyopathy, but that gives dilated, thin walls with a reduced ejection fraction. Stiff, normal-sized ventricles with big atria are restrictive."],
   ["Acute myocarditis",
    "Myocarditis follows a recent viral prodrome with acute heart failure and raised troponin. A slow course years after radiation with stiff ventricles is restrictive disease."],
   ["Hypertrophic cardiomyopathy",
    "Hypertrophic cardiomyopathy is inherited, with an asymmetric thick septum and outflow murmur. Treatment-related fibrosis with big atria is restrictive cardiomyopathy."]],
  C(87), "etiology", "diagnosis"),

V(RCM, IO_A,
  "A 66-year-old man has right-sided heart failure with a raised jugular venous pressure and ascites. Echocardiogram shows abnormal diastolic filling, normal-sized ventricles and big atria, but the team cannot tell restrictive cardiomyopathy from constrictive pericarditis. Which test is used to differentiate them?",
  [["Cardiac magnetic resonance imaging",
    "Correct. Echocardiography alone is not definitive because restrictive cardiomyopathy and constrictive pericarditis look alike; cardiac magnetic resonance imaging differentiates them by showing pericardial thickening in pericarditis."],
   ["Repeat transthoracic echocardiogram",
    "Echocardiography alone is not definitive for this distinction, so repeating it adds little. Cardiac magnetic resonance imaging shows the pericardial thickening that settles it."],
   ["Exercise stress echocardiogram",
    "Exercise echocardiography is used for functional capacity and obstruction in hypertrophic cardiomyopathy. Magnetic resonance imaging separates restriction from constriction."],
   ["Ambulatory rhythm monitoring",
    "Rhythm monitoring detects arrhythmias such as atrial fibrillation but cannot image the pericardium. Cardiac magnetic resonance imaging differentiates the two."]],
  C(96), "differential", "test"),

V(RCM, IO_A,
  "A 69-year-old woman with right-sided heart failure, ascites and a raised jugular venous pressure has cardiac magnetic resonance imaging to decide between restrictive cardiomyopathy and constrictive pericarditis. Which imaging finding would point to constrictive pericarditis instead?",
  [["Pericardial thickening",
    "Correct. Cardiac magnetic resonance imaging is used to differentiate the two conditions, and pericardial thickening is the finding that identifies constrictive pericarditis rather than restrictive cardiomyopathy."],
   ["Marked atrial enlargement",
    "Marked enlargement of one or both atria is a feature of restrictive cardiomyopathy itself, caused by impaired ventricular filling. It does not point to pericarditis."],
   ["Preserved ejection fraction",
    "A preserved ejection fraction until late stages is typical of restrictive cardiomyopathy, so it does not separate it from constriction. Pericardial thickening does."],
   ["Normal ventricular cavity size",
    "A normal or near-normal cavity size is expected in restrictive cardiomyopathy. The finding that points to constrictive pericarditis is pericardial thickening."]],
  C(96), "test finding", "test"),

V(RCM, IO_A,
  "A 74-year-old man with restrictive cardiomyopathy is found to have cardiac amyloidosis, with amyloid protein deposited in the heart tissue. He has breathlessness, leg edema and ascites. Which electrocardiogram finding is expected with this infiltrative disease?",
  [["Low QRS voltage",
    "Correct. The electrocardiogram in restrictive cardiomyopathy may show low QRS voltage in amyloidosis infiltrative disease, and atrial fibrillation and bundle branch blocks are also common."],
   ["Prominent Q waves",
    "Prominent Q waves in the inferior and lateral leads reflect septal depolarization of hypertrophied muscle in hypertrophic cardiomyopathy. Amyloidosis gives low QRS voltage."],
   ["Left axis deviation",
    "Left axis deviation is listed among the electrocardiogram findings of hypertrophic cardiomyopathy. Infiltrative amyloid disease produces low QRS voltage."],
   ["ST elevation",
    "ST elevation with T-wave inversion is the electrocardiogram of stress cardiomyopathy. Amyloid infiltration of the heart gives low QRS voltage."]],
  C(95), "test finding", "test"),

V(RCM, IO_A,
  "A 70-year-old woman with restrictive cardiomyopathy has pulmonary and systemic congestion, with crackles and leg edema. A diuretic is being started. Which statement about diuretic use in her is most accurate?",
  [["Use with caution; stiff ventricles need preload",
    "Correct. Diuretics are used for pulmonary and systemic congestion in restrictive cardiomyopathy, but with caution, because they lower preload and the noncompliant ventricles depend on preload to maintain cardiac output."],
   ["Contraindicated in any restrictive disease",
    "Diuretics are not contraindicated; they treat the pulmonary and systemic congestion. They are simply used with caution because stiff ventricles need preload."],
   ["Give aggressively to fully dry the lungs",
    "Aggressive diuresis drops the preload that stiff ventricles rely on and can collapse cardiac output. Diuretics are used, but cautiously."],
   ["Only useful once the ejection fraction falls",
    "Diuretics treat congestion whatever the ejection fraction, which is usually preserved until late. The caution is about lowering preload."]],
  C(98), "avoid", "avoid"),

V(RCM, IO_A,
  "A 68-year-old man with restrictive cardiomyopathy has worsening breathlessness since developing atrial fibrillation with a fast ventricular rate. His ejection fraction is preserved. Which medication may improve his ventricular filling?",
  [["Verapamil or diltiazem",
    "Correct. Beta blockers and the calcium channel blockers verapamil and diltiazem may benefit restrictive cardiomyopathy by lengthening left ventricular filling time, improving relaxation and decreasing compensatory sympathetic stimulation."],
   ["Nitroglycerin infusion",
    "Nitrates lower preload, which stiff, noncompliant ventricles depend on. Lengthening filling time with verapamil, diltiazem or a beta blocker is what helps."],
   ["Epinephrine infusion",
    "Epinephrine speeds the heart and shortens filling time, the opposite of what stiff ventricles need. Verapamil or diltiazem slows the rate and improves filling."],
   ["Nifedipine, a vasodilator",
    "Nifedipine is a dihydropyridine that mainly vasodilates. The calcium channel blockers used to improve filling are verapamil and diltiazem."]],
  C(98), "agent/regimen", "treatment"),

V(RCM, IO_A,
  "A 71-year-old woman with restrictive cardiomyopathy and marked biatrial enlargement has had palpitations for a week, and the electrocardiogram now shows atrial fibrillation. Which treatment reduces her risk of embolism?",
  [["Anticoagulation",
    "Correct. Atrial fibrillation is common in restrictive cardiomyopathy because of atrial enlargement, it raises the risk of atrial thrombus, and anticoagulants may be needed to prevent embolism from atrial thrombi."],
   ["Aggressive diuresis",
    "Diuretics treat congestion and must be used cautiously in restrictive disease; they do nothing to prevent emboli. Anticoagulation prevents embolism from atrial thrombi."],
   ["Surgical myectomy",
    "Myectomy removes obstructing septal muscle in hypertrophic cardiomyopathy. Embolism from atrial thrombi in restrictive disease is prevented with anticoagulation."],
   ["A positive inotrope",
    "Inotropes do not prevent thromboembolism. With atrial fibrillation and big atria, anticoagulation is used to prevent embolism."]],
  C(99), "agent/regimen", "treatment"),

V(RCM, IO_A,
  "A 76-year-old man with restrictive cardiomyopathy from cardiac sarcoidosis has two episodes of syncope. His heart rate is 34, and the electrocardiogram shows complete heart block. Which is the most appropriate next step?",
  [["Permanent pacemaker",
    "Correct. Fibrosis of the sinoatrial and atrioventricular nodes in restrictive cardiomyopathy can lead to heart block, and a permanent pacemaker is used for this conduction system disease."],
   ["Surgical myectomy",
    "Myectomy relieves outflow obstruction in hypertrophic cardiomyopathy and does not treat heart block. Conduction system disease needs a permanent pacemaker."],
   ["Alcohol septal ablation",
    "Alcohol septal ablation treats septal outflow obstruction, and it can itself cause heart block. Complete heart block from nodal fibrosis needs a permanent pacemaker."],
   ["Endomyocardial biopsy",
    "A biopsy may help find a cause when imaging and genetic testing are negative, but it does not treat symptomatic heart block. A permanent pacemaker does."]],
  C(99), "escalation", "next step"),

V(RCM, IO_A,
  "A 73-year-old woman has just been diagnosed with restrictive cardiomyopathy from amyloidosis. She has right-sided heart failure and asks how her condition compares with other kinds of heart muscle disease. Which statement about her prognosis is most accurate?",
  [["Poorest of all heart muscle diseases",
    "Correct. Restrictive cardiomyopathy has the poorest prognosis among all types of heart muscle disease, and it often presents at an advanced stage with pronounced cardiopulmonary symptoms."],
   ["Complete recovery within weeks",
    "Complete recovery in most patients is the course of stress (Takotsubo) cardiomyopathy. Restrictive cardiomyopathy has the poorest prognosis of all heart muscle diseases."],
   ["A normal life span with diuretics",
    "Diuretics relieve congestion but do not change the outlook, which is the poorest among heart muscle diseases. Transplantation is an option in advanced disease."],
   ["Better than other cardiomyopathies",
    "Restrictive cardiomyopathy carries the poorest prognosis among heart muscle diseases rather than a better one, partly because it presents late."]],
  C(99), "prognosis", "complication"),

V(RCM, IO_A,
  "A 64-year-old man has restrictive cardiomyopathy confirmed on imaging, but cardiac magnetic resonance imaging and genetic testing have not identified a cause. His team is considering endomyocardial biopsy. When is biopsy performed in this condition?",
  [["When imaging and genetic tests are negative",
    "Correct. Endomyocardial biopsy is performed when all imaging studies and genetic testing are negative, or when a tissue sample is likely to confirm or exclude a diagnosis that would change management."],
   ["As the first test in every suspected case",
    "Biopsy is not the first test; echocardiography, electrocardiogram and radiograph come first, then cardiac magnetic resonance imaging. Biopsy follows negative imaging and genetic testing."],
   ["Only after cardiac transplantation is done",
    "Biopsy is used during the diagnostic work-up, when imaging and genetic testing are negative, not only after transplantation."],
   ["Never, since it cannot change management",
    "Biopsy is performed precisely when a tissue sample could confirm or exclude a diagnosis that would change management, after negative imaging and genetic tests."]],
  C(97), "gold standard", "test"),

V(RCM, IO_A,
  "A 67-year-old woman with suspected restrictive cardiomyopathy has right-sided heart failure and big atria on echocardiogram. Her cardiologist wants to measure pressures inside both ventricles to characterize the filling problem. Which invasive test evaluates ventricular pressure tracings?",
  [["Cardiac catheterization",
    "Correct. Cardiac catheterization is useful in restrictive cardiomyopathy to evaluate ventricular pressure tracings, alongside cardiac magnetic resonance imaging and, when needed, endomyocardial biopsy."],
   ["Endomyocardial biopsy",
    "Biopsy samples tissue to confirm or exclude a diagnosis; it does not record pressure tracings. Catheterization measures ventricular pressures."],
   ["Transesophageal echocardiogram",
    "Transesophageal echocardiography images the valves and chambers with ultrasound but does not record direct ventricular pressure tracings. Cardiac catheterization does."],
   ["Exercise echocardiography",
    "Exercise echocardiography assesses functional capacity and obstruction, mainly in hypertrophic cardiomyopathy. Ventricular pressure tracings need catheterization."]],
  C(97), "initial test", "test"),

V(RCM, IO_A,
  "A 75-year-old man is newly diagnosed with restrictive cardiomyopathy caused by hemochromatosis, with iron deposited in the heart tissue. He has congestion and fatigue. Which is the first principle of his management?",
  [["Treat the underlying disorder",
    "Correct. Management of restrictive cardiomyopathy begins with treating the underlying disorder, such as iron storage in hemochromatosis, with cautious diuretics, rate-slowing drugs and anticoagulation added as needed."],
   ["Septal myectomy for relief",
    "Myectomy relieves septal outflow obstruction in hypertrophic cardiomyopathy. Restrictive disease is managed first by treating its underlying cause."],
   ["An inotrope to raise output",
    "Systolic function is usually normal in restrictive cardiomyopathy, and an inotrope does not address the stiff filling. The first principle is treating the cause."],
   ["A high-intensity exercise program",
    "Exercise does not treat infiltrative or storage disease of the heart. Restrictive cardiomyopathy management starts with the underlying disorder."]],
  C(98), "first-line", "treatment"),

V(RCM, IO_A,
  "A 71-year-old woman with restrictive cardiomyopathy has fatigue and exercise intolerance along with leg edema, hepatomegaly and ascites, but her lungs are relatively clear. Which pattern of heart failure is expected to dominate in this condition?",
  [["Right-sided heart failure",
    "Correct. Although filling pressures are raised in both ventricles, right heart failure is often more prominent and may dominate in restrictive cardiomyopathy, giving edema, hepatomegaly and ascites."],
   ["Isolated left-sided failure",
    "Left-sided failure brings pulmonary congestion, crackles and orthopnea to the fore. In restrictive cardiomyopathy right-sided failure often dominates instead."],
   ["High-output heart failure",
    "Restrictive cardiomyopathy reduces output because stiff ventricles fill poorly. The dominant pattern is right-sided failure, not a high-output state."],
   ["Pure systolic failure",
    "Systolic function is usually normal in restrictive cardiomyopathy; the problem is diastolic filling, and right-sided failure tends to dominate."]],
  C(90), "manifestation", "complication"),
]
