# -*- coding: utf-8 -*-
"""Lecture 26 vignette pool B -- Venous Disorders: deep vein thrombosis cases.

KEYS ARE WRITTEN SHORT ON PURPOSE -- detail lives in the explanation.

Patient vignettes (Set 2) with a varied lead-in (the lead-in decides the answer).
Carries the three priorities Shah stressed, by stem word: the Virchow triad,
the Wells criteria (score arithmetic checked item by item against slide 55:
travel is NOT an item; immobilization means bedridden after surgery or a
cast; a score of exactly 0 is never used) and the D-dimer versus ultrasound
decision (slide 56). Duration, setting, agents, reversal, filter and
thrombolysis follow slides 61-71. No dosing, no brand names.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _cmse3_q import Q
from cms_e5l26_scope import *


def S(topic, io, q, opts, cite, slot):
    d = Q(topic, io, q, opts, cite); d["slot"] = slot; return d


def V(topic, io, q, opts, cite, slot, lead):
    d = S(topic, io, q, opts, cite, slot); d["lead"] = lead; return d


TV = "Virchow triad"
TW = "Wells criteria"
TD = "D-dimer and ultrasound"
TX = "Differential diagnosis of a swollen leg"
TA = "Anticoagulation choices"
TT = "Duration and setting of treatment"
TR = "Bleeding, filters and thrombolysis"
TC = "Upper-extremity disease and complications"

QUESTIONS = [

# ---------------------------------------------------------------- Virchow triad
V(TV, IO_A,
  "A 71-year-old man has been on strict bed rest for six days during an admission for pneumonia and now has swelling and aching of the entire left leg. Which component of the Virchow triad does his prolonged bed rest represent?",
  [["Venous stasis",
    "Correct. Bed rest is immobilization, which alters blood flow and lets blood pool in the leg veins, the venous stasis component of the Virchow triad. Prolonged immobilization raises the risk of deep vein thrombosis about twenty-fold."],
   ["Hypercoagulable state",
    "A hypercoagulable state is an inherited or acquired clotting tendency, such as factor V Leiden, cancer, estrogen use or pregnancy. Lying still changes blood flow rather than clotting chemistry, so it is stasis."],
   ["Endothelial trauma",
    "Endothelial trauma is direct injury to the vein wall from surgery, fracture, burns, catheters or injection. Bed rest for pneumonia does not injure the vessel lining; it slows flow, which is stasis."],
   ["Arterial vasospasm",
    "Arterial vasospasm is not a component of the Virchow triad, which comprises venous stasis, hypercoagulable state and endothelial trauma. Immobility acts on the veins by slowing their blood flow."]],
  C(49), "etiology", "diagnosis"),

V(TV, IO_A,
  "A 27-year-old woman has a first deep vein thrombosis of the left leg. Genetic testing shows factor V Leiden, an inherited clotting abnormality. Which component of the Virchow triad does this finding represent?",
  [["Hypercoagulable state",
    "Correct. Factor V Leiden is an inherited hypercoagulable state, like prothrombin gene mutation and protein C, protein S or antithrombin deficiency. It makes the blood clot too readily, the hypercoagulable component of the triad."],
   ["Venous stasis",
    "Venous stasis means slowed flow from immobilization, heart failure or venous insufficiency. Her gene change alters the blood's clotting tendency, not its flow, so it belongs in the hypercoagulable component."],
   ["Endothelial trauma",
    "Endothelial trauma is injury to the vein wall from surgery, fracture, burns or injection. Factor V Leiden leaves the vessel lining intact and changes coagulation, which is the hypercoagulable component instead."],
   ["Venous insufficiency",
    "Venous insufficiency, such as valve failure, is listed under venous stasis rather than clotting tendency. An inherited change in a clotting factor is a hypercoagulable state, the correct component."]],
  C(49), "risk factors", "diagnosis"),

V(TV, IO_A,
  "A 52-year-old man with a pacemaker implanted two weeks ago has three days of swelling and aching of the left arm. The pacemaker lead has injured the wall of the subclavian vein. Which component of the Virchow triad does this injury represent?",
  [["Endothelial trauma",
    "Correct. Damage to the vessel lining from an indwelling device is endothelial trauma, one leg of the Virchow triad. Pacemakers, implanted defibrillators and central venous catheters are the most common causes of upper-extremity deep vein thrombosis."],
   ["Venous stasis",
    "Venous stasis arises from immobilization, heart failure or venous insufficiency. A lead scraping the vein wall is physical injury to the lining, which is the endothelial trauma component."],
   ["Hypercoagulable state",
    "A hypercoagulable state is a clotting tendency from inherited disorders, cancer, estrogen or pregnancy. Mechanical injury to the vein wall from a lead is endothelial trauma instead."],
   ["Impaired lymphatic drainage",
    "Impaired lymphatic drainage causes lymphedema and is not part of the Virchow triad. Injury to the subclavian vein wall is endothelial trauma, the third triad component."]],
  C(47), "etiology", "diagnosis"),

V(TV, IO_A,
  "A 32-year-old woman who is 34 weeks pregnant sits in a car for nine hours and develops left calf swelling and pain. Her pregnancy supplies a hypercoagulable state and the long ride supplies venous stasis. Which additional component would complete the Virchow triad?",
  [["Endothelial trauma",
    "Correct. The Virchow triad is venous stasis, hypercoagulable state and endothelial trauma. Pregnancy and the car ride supply two components, so the missing one is injury to the vein wall, as from trauma, surgery, burns or injection."],
   ["Venous stasis",
    "Venous stasis is already present from nine hours of sitting still, so it cannot be the additional component. The one still missing is endothelial trauma, injury to the vessel wall."],
   ["Hypercoagulable state",
    "Pregnancy already supplies the hypercoagulable state by raising clotting tendency, so it is present rather than missing. The component still absent is endothelial trauma."],
   ["Arterial thrombosis",
    "Arterial thrombosis is a clot in an artery and is not a component of the Virchow triad. The venous component still absent in this scenario is endothelial trauma."]],
  C(49), "risk factors", "diagnosis"),

V(TV, IO_A,
  "A 64-year-old woman must stay in bed for several days after major abdominal surgery. Her team wants a preventive measure aimed at the venous stasis component of the Virchow triad. Which measure is most appropriate?",
  [["Intermittent pneumatic compression",
    "Correct. Intermittent pneumatic compression, sequential devices that squeeze the legs in turn, imitates the calf muscle pump and keeps blood moving, countering stasis. It is used especially when a patient is immobilized after surgery or hospitalized for long."],
   ["Inferior vena cava filter",
    "An inferior vena cava filter catches clots after they form and is reserved for acute proximal deep vein thrombosis when anticoagulation is contraindicated. It is not a routine preventive measure for stasis after surgery."],
   ["Thrombolytic infusion",
    "Thrombolysis breaks down an existing clot in selected patients with a large proximal deep vein thrombosis or stable pulmonary embolism. It treats established clots and carries bleeding risk, so it is not prevention."],
   ["Warm compresses to the calves",
    "Warm compresses are a comfort measure for superficial phlebitis and do nothing to keep deep venous blood moving. Intermittent pneumatic compression mimics the muscle pump and counters stasis."]],
  C(71), "first-line", "treatment"),

V(TV, IO_A,
  "A 63-year-old man is diagnosed with a first proximal deep vein thrombosis five days after knee replacement under two hours of general anesthesia. His clot is attributed to the venous stasis and endothelial trauma of the Virchow triad, both from the surgery. What duration of anticoagulation is appropriate?",
  [["Three months",
    "Correct. A clot provoked by a major transient, reversible risk factor, such as surgery under general anesthesia for more than 30 minutes, is treated for three months. Three months is also the minimum initial duration for any first venous thromboembolism."],
   ["Three to six months",
    "Three to six months fits a clot provoked by a minor transient factor such as estrogen therapy, pregnancy, minor surgery or prolonged travel. Major surgery is a stronger reversible trigger, so three months suffices."],
   ["Indefinitely",
    "Indefinite anticoagulation is for a first clot with no identifiable risk factor. His clot has a clear, reversible surgical cause, so open-ended treatment is not needed."],
   ["Six weeks",
    "Six weeks falls short of the minimum. Every first venous thromboembolism, provoked or not, is treated for at least three months before the duration is reconsidered."]],
  C(64), "first-line", "treatment"),

V(TV, IO_A,
  "A 68-year-old woman with active pancreatic cancer, which supplies the hypercoagulable component of the Virchow triad, has an acute proximal deep vein thrombosis of the left leg. She also has active gastrointestinal bleeding. Which treatment is most appropriate?",
  [["Inferior vena cava filter",
    "Correct. An inferior vena cava filter is used for acute proximal lower-extremity deep vein thrombosis when there is active bleeding or anticoagulation is otherwise contraindicated. The filter keeps the clot from traveling to the lungs and causing pulmonary embolism."],
   ["Unfractionated heparin infusion",
    "Unfractionated heparin is an anticoagulant, and active bleeding contraindicates every anticoagulant. Giving it would worsen the hemorrhage; a filter protects the lungs without thinning the blood."],
   ["Systemic thrombolysis",
    "Thrombolysis breaks down clots and carries a high bleeding risk, so it is dangerous with active hemorrhage. It is reserved for large proximal clots or stable pulmonary embolism in patients who can bleed safely."],
   ["Outpatient rivaroxaban",
    "Rivaroxaban is a direct factor Xa inhibitor, an anticoagulant, and active bleeding contraindicates anticoagulants. Her bleeding must be controlled first, and a filter covers the clot risk meanwhile."]],
  C(69), "escalation", "treatment"),

V(TV, IO_A,
  "A 70-year-old woman with heart failure is admitted with a tender, swollen left calf, and duplex ultrasound confirms deep vein thrombosis. Her daughter asks why heart failure raises the risk of a clot. Which Virchow triad component should the clinician name?",
  [["Venous stasis",
    "Correct. Heart failure is listed under venous stasis, the Virchow component reflecting altered blood flow. A weak pump lets blood pool and slow in the veins of the legs, so clots form more readily."],
   ["Hypercoagulable state",
    "A hypercoagulable state comes from inherited thrombophilia, cancer, estrogen therapy or pregnancy. Heart failure raises clot risk by slowing venous return, which is stasis rather than a change in clotting chemistry."],
   ["Endothelial trauma",
    "Endothelial trauma is injury to the vein wall from surgery, fracture, burns or injection. Heart failure does not damage the vessel lining; it reduces venous flow, the stasis component."],
   ["Elevated platelet count",
    "An elevated platelet count is not one of the three Virchow triad components. Heart failure raises clotting risk through slowed venous flow, which is venous stasis."]],
  C(49), "risk factors", "education"),

# ---------------------------------------------------------------- Wells criteria
V(TW, IO_A,
  "A 58-year-old man receiving chemotherapy for colon cancer comes to the emergency department with three days of left calf swelling that measures 4 cm more than the right, plus tenderness along the deep veins of the calf. He has no history of clots and nothing else explains his leg. The team debates whether to order a D-dimer or go straight to imaging. Using the Wells criteria, which is the best next step?",
  [["Venous duplex ultrasound",
    "Correct. Active cancer, calf swelling over 3 cm and tenderness along the deep veins total 3 points, a high likelihood. A score of 3 or more skips the D-dimer and goes directly to venous duplex ultrasound of the leg."],
   ["D-dimer testing first",
    "Starting with a D-dimer is the path for low or moderate scores. With a high Wells score the D-dimer is skipped, because even a negative result would not exclude deep vein thrombosis and ultrasound is needed."],
   ["Contrast ascending venography",
    "Contrast ascending venography is the invasive gold standard but has been replaced by venous duplex ultrasound, which is noninvasive and is the imaging test ordered for a high score."],
   ["Ankle-brachial index",
    "The ankle-brachial index screens for peripheral artery disease in arterial insufficiency. His swollen, tender calf points to venous thrombosis, so the test needed is venous duplex ultrasound."]],
  C(55), "initial test", "next step"),

V(TW, IO_A,
  "A 24-year-old soccer player comes to urgent care with left calf pain that began two days ago when he felt a sudden pull while sprinting, and he has bruising around the ankle. He has no leg swelling, tenderness along the deep veins, cancer, cast or history of clots. By the Wells criteria, a calf muscle tear is at least as likely as deep vein thrombosis. Which is the most appropriate first test?",
  [["D-dimer blood test",
    "Correct. The likelier alternative diagnosis subtracts 2 from his Wells score, giving a low likelihood. Low-likelihood patients start with a D-dimer, and a negative result lets the clinician stop, since D-dimer is a sensitive rule-out test."],
   ["Venous duplex ultrasound",
    "Venous duplex ultrasound is ordered first for a high Wells score, or after a positive D-dimer. For this low-likelihood patient it is not the first test, because a negative D-dimer could end the work-up."],
   ["Contrast ascending venography",
    "Contrast ascending venography is invasive and has been replaced by duplex ultrasound. It is not an initial test for a low-likelihood patient, whose first step is a D-dimer."],
   ["Computed tomography of the leg",
    "Computed tomography of the leg is not part of the deep vein thrombosis pathway, which relies on the D-dimer for low-likelihood patients and venous duplex ultrasound for confirmation."]],
  C(56), "initial test", "test"),

V(TW, IO_A,
  "A 47-year-old woman with a previous deep vein thrombosis two years ago comes to the emergency department with swelling of the entire right leg. She has no pitting edema, calf asymmetry over 3 cm, tenderness along the deep veins, collateral veins, cancer, recent bed rest, surgery or cast, and no better alternative diagnosis. By the Wells criteria, which likelihood category applies?",
  [["Moderate (score of 1 to 2)",
    "Correct. A previously documented deep vein thrombosis adds 1 point and swelling of the entire leg adds 1 point, for 2 in total, the moderate band of 1 to 2. Moderate likelihood leads to a D-dimer next."],
   ["Low (score below 1)",
    "A low likelihood is a score below 1, reached only with few positives or the minus 2 credit for a likelier alternative diagnosis. Her two positive items total 2, which is above the low band."],
   ["High (score of 3 or more)",
    "High likelihood requires 3 or more points. She has only two positive items, so she falls in the moderate band and receives a D-dimer rather than going straight to ultrasound."],
   ["Moderate (score of 3 to 4)",
    "The moderate band is 1 to 2 points, and a score of 3 or more is already high likelihood. Her total of 2 is moderate, but the numeric range offered here is wrong."]],
  C(55), "risk factors", "test"),

V(TW, IO_A,
  "A 41-year-old woman returns from a 14-hour flight and reports two days of right calf pain. Her calf measures 4 cm more than the left and she has pitting edema confined to that leg. She has no cancer, surgery, cast, paralysis, previous clot or better alternative diagnosis. Her urgent care clinician asks whether a D-dimer or an ultrasound should come first. Using the Wells criteria, which is the best next step?",
  [["Order a D-dimer test",
    "Correct. Calf swelling over 3 cm and pitting edema confined to the leg total 2 points, a moderate likelihood that calls for a D-dimer. The flight adds nothing, because travel is not a Wells item; immobilization there means bed rest after surgery or a cast."],
   ["Order venous duplex ultrasound",
    "Counting the flight as immobilization would raise the score to 3 and prompt ultrasound. Travel is not a Wells item, so her score stays at 2 and the D-dimer comes first."],
   ["Order contrast venography",
    "Contrast venography is invasive and has been replaced by venous duplex ultrasound. It is not a first-line test for a moderate-likelihood patient, who needs a D-dimer first."],
   ["Reassure without testing",
    "A moderate score of 2 cannot be dismissed without testing, because untreated deep vein thrombosis can embolize to the lungs. The pathway calls for a D-dimer, then ultrasound if it is positive."]],
  C(55), "test finding", "next step"),

V(TW, IO_A,
  "A 33-year-old man had a plaster cast removed from his right lower leg two days ago after a tibial fracture. He now has right calf swelling that measures 4 cm more than the left, and tenderness along the deep veins of the calf. Nothing else on the Wells criteria is present and no alternative diagnosis is as likely. What is his Wells score?",
  [["Three points",
    "Correct. Recent plaster immobilization of the lower extremity, calf swelling over 3 cm and tenderness along the deep venous system are worth 1 point each, for 3. A score of 3 or more means high likelihood, so ultrasound is ordered."],
   ["Two points",
    "Two points would omit one positive item. The plaster immobilization, the calf swelling over 3 cm and the deep venous tenderness each score 1, so the total is three."],
   ["Four points",
    "Four points would need another positive item, such as pitting edema, swelling of the entire leg or active cancer, and he has none of these. His three findings total three."],
   ["One point",
    "One point undercounts. Each of his three positive items is worth 1 point, and none is offset by a likelier alternative diagnosis, which would subtract 2, so his total is three."]],
  C(55), "risk factors", "test"),

V(TW, IO_A,
  "A 66-year-old woman who received pelvic radiation for cervical cancer four years ago has two weeks of left calf swelling measuring 4 cm more than the right, pitting edema confined to that leg, and tenderness along the deep veins. Her cancer is in remission and untreated. Her clinician judges chronic lymphedema at least as likely as deep vein thrombosis. Which test comes next by the Wells criteria?",
  [["D-dimer blood test",
    "Correct. Three positive items (calf swelling, pitting edema, deep venous tenderness) give 3 points, and the likelier alternative diagnosis subtracts 2, leaving 1, a moderate likelihood. Moderate scores of 1 to 2 need a D-dimer."],
   ["Venous duplex ultrasound",
    "Ultrasound goes first only for a high score of 3 or more. Subtracting 2 for lymphedema leaves her at 1, a moderate score that starts with a D-dimer."],
   ["Contrast ascending venography",
    "Contrast ascending venography is the invasive gold standard that venous duplex ultrasound replaced. It is not an initial test for a moderate score, which begins with a D-dimer."],
   ["No testing is required",
    "Lymphedema is only on the differential, and a moderate score of 1 still needs a D-dimer to exclude a clot. Chronic edema after pelvic radiation can coexist with deep vein thrombosis."]],
  C(55), "differential", "test"),

V(TW, IO_A,
  "A 71-year-old man hospitalized for six days with pneumonia develops swelling of the left calf. His team considers using the Wells criteria to estimate his probability of deep vein thrombosis. Which statement about applying the Wells criteria to him is accurate?",
  [["Meant for outpatient or emergency use",
    "Correct. The Wells criteria are used in the outpatient and emergency department settings, not for inpatients, in whom the score is less useful. A hospitalized patient needs clinical judgment and ultrasound rather than this pathway."],
   ["Most accurate in hospitalized patients",
    "The score is less useful in hospitalized patients; it is validated for outpatients and emergency department patients. Inpatients need clinical judgment and ultrasound instead of this pathway."],
   ["Designed for upper-extremity clots",
    "The Wells criteria for deep vein thrombosis address suspected leg clots, with items such as calf swelling and pitting edema of the leg. Upper-extremity clots are not what this score was built for."],
   ["A low score replaces all testing",
    "A low score does not replace testing; it leads to a D-dimer first, and only a negative result stops the work-up. The score guides which test comes next, not whether to test."]],
  C(54), "initial test", "test"),

V(TW, IO_A,
  "A 29-year-old woman seen in urgent care for mild left calf aching has a low Wells score. Her D-dimer is negative. What is the next step?",
  [["No further testing needed",
    "Correct. In a low-likelihood patient a negative D-dimer stops the work-up, because the test is sensitive and useful for ruling out deep vein thrombosis. No ultrasound is required."],
   ["Venous duplex ultrasound of the thigh",
    "Ultrasound follows a positive D-dimer or a high score. After a negative D-dimer in a low-likelihood patient the pathway ends, so imaging adds nothing."],
   ["Contrast ascending venography",
    "Contrast ascending venography is invasive, was the historical gold standard and has been replaced by ultrasound. A negative D-dimer in a low-likelihood patient ends the work-up before any imaging."],
   ["Repeat D-dimer in one week",
    "A repeat D-dimer is not part of the pathway. Because D-dimer is sensitive, one negative result in a low-likelihood patient is enough to exclude deep vein thrombosis and stop."]],
  C(56), "test finding", "next step"),

V(TW, IO_A,
  "A 62-year-old woman on chemotherapy for breast cancer comes to the emergency department with a calf 4 cm larger than the other, tenderness along the deep veins and no better explanation, so her Wells score is high. Her D-dimer, drawn at triage, is negative. Which action should be avoided?",
  [["Ending the work-up at the D-dimer",
    "Correct. With a high Wells score the D-dimer is skipped, or if it was drawn, a negative result does not end the evaluation: she still goes to venous duplex ultrasound. Stopping here risks missing a clot with high pretest probability."],
   ["Ordering a venous duplex ultrasound",
    "Ultrasound is exactly what a high Wells score calls for, whatever the D-dimer shows. It is the appropriate next test, so ordering it is the right action, not one to avoid."],
   ["Asking about shortness of breath",
    "Pointed questions about breathing are part of the evaluation, because the lower-extremity clot can send an embolus to the lungs. This is good practice rather than a mistake to avoid."],
   ["Measuring both calf circumferences",
    "Comparing the calves at a set point below the tibial tuberosity is how the Wells item for swelling over 3 cm is scored. It is a useful step, not an error."]],
  C(56), "avoid", "avoid"),

# ---------------------------------------------------------------- D-dimer
V(TD, IO_A,
  "A 36-year-old woman who smokes and takes an oral contraceptive has mild calf aching. Her Wells score is low, and her D-dimer returns positive. What is the next step?",
  [["Venous duplex ultrasound",
    "Correct. In a low-likelihood patient a positive D-dimer cannot exclude deep vein thrombosis, so venous duplex ultrasound follows. A positive ultrasound makes the diagnosis; a negative one rules it out."],
   ["Empiric anticoagulation alone",
    "Treating without imaging exposes her to bleeding risk on an unconfirmed diagnosis, and a positive D-dimer is nonspecific. Ultrasound confirms or excludes the clot before anticoagulation is committed."],
   ["Reassurance and discharge",
    "Discharge is for a negative D-dimer in a low-likelihood patient. A positive result means fibrinolysis is occurring somewhere and needs ultrasound to find out whether it is a clot."],
   ["Repeat D-dimer tomorrow",
    "Repeating a nonspecific test does not clarify anything. A positive D-dimer moves the patient on to venous duplex ultrasound, which can actually visualize a clot."]],
  C(56), "initial test", "next step"),

V(TD, IO_A,
  "A 55-year-old man has a positive D-dimer during evaluation of calf pain two weeks after a bicycle crash with extensive bruising. He asks why his clinician says the result cannot confirm a clot. Which explanation is accurate?",
  [["It reflects fibrinolysis from many causes",
    "Correct. D-dimer elevation implies increased fibrinolysis, but it is sensitive and not specific. Bruising, surgery, cancer and many other conditions raise it, so a positive result needs imaging while a negative one helps rule out a clot."],
   ["It is specific but not sensitive",
    "This reverses the facts: D-dimer is sensitive but not specific. Its sensitivity is why a negative result helps rule out a clot, and its poor specificity is why a positive one needs imaging."],
   ["It rises only with pulmonary embolism",
    "D-dimer rises with fibrinolysis anywhere in the body, including after trauma, and is useful as a rule-out test for both deep vein thrombosis and pulmonary embolism. It is not limited to one disease."],
   ["It rises only with thigh clots",
    "D-dimer does not localize a clot to the thigh or anywhere else. It reflects fibrinolysis from many causes, so ultrasound is needed to find and locate any thrombus."]],
  C(57), "education", "education"),

V(TD, IO_A,
  "A 33-year-old woman eight weeks postpartum has mild calf aching and a low pretest probability of deep vein thrombosis. Her clinician orders a D-dimer. Which characteristic makes a negative result useful for excluding a clot?",
  [["High sensitivity",
    "Correct. D-dimer is sensitive but not specific, so a negative result in a low-likelihood patient effectively rules out deep vein thrombosis and pulmonary embolism. It cannot confirm a clot, since fibrinolysis has many causes."],
   ["High specificity",
    "D-dimer is not specific; many conditions raise it, so a positive result cannot confirm a clot. Its value as a rule-out test comes from high sensitivity."],
   ["Direct visualization of clot",
    "D-dimer is a blood test that detects fibrin breakdown and cannot show a clot. Visualizing the thrombus is the job of venous duplex ultrasound."],
   ["Measurement of vein compressibility",
    "Testing whether a vein compresses is done with duplex ultrasound, not a blood test. D-dimer rules out disease through its sensitivity, not through any imaging feature."]],
  C(57), "test finding", "test"),

# ---------------------------------------------------------------- differential
V(TX, IO_A,
  "A 57-year-old man with knee osteoarthritis felt a sudden sharp pain behind the right knee while climbing stairs, followed by severe calf discomfort and swelling. Venous duplex ultrasound shows no thrombus. What is the most likely diagnosis?",
  [["Ruptured popliteal (Baker) cyst",
    "Correct. A ruptured popliteal (Baker) cyst produces severe, sudden calf discomfort that mimics deep vein thrombosis, and the ultrasound shows no clot. It is a standard item on the differential of a swollen calf."],
   ["Calf muscle tear",
    "A calf muscle tear follows an inciting injury and may leave bruising at the ankle. Here the pain began behind the knee during ordinary activity, which fits a ruptured cyst better."],
   ["Post-thrombotic syndrome",
    "Post-thrombotic syndrome is chronic venous insufficiency appearing 6 to 24 months after a clot, with slow-onset edema and skin change. A sudden calf event with no prior clot is not that."],
   ["Superficial thrombophlebitis",
    "Superficial thrombophlebitis gives a tender, indurated cord along a superficial vein with local redness. A sudden severe calf pain that began behind the knee is not a superficial vein process."]],
  C(52), "differential", "diagnosis"),

V(TX, IO_A,
  "A 59-year-old woman had a left leg deep vein thrombosis 11 months ago. She now has chronic left leg heaviness, edema and brownish ankle skin that worsen with standing and improve with elevation. What is the most likely diagnosis?",
  [["Post-thrombotic syndrome",
    "Correct. Post-thrombotic (postphlebitic) syndrome is symptomatic chronic venous insufficiency that follows a deep vein thrombosis, appearing 6 to 24 months later, with heaviness, edema and brownish skin change from venous hypertension."],
   ["Recurrent deep vein thrombosis",
    "A recurrent clot would usually present acutely with new swelling, pain and warmth. Slowly progressive heaviness with skin change, relieved by elevation, points to chronic venous disease."],
   ["Lymphedema",
    "Lymphedema is chronic edema usually following pelvic surgery, malignancy or radiation, and brawny skin change from venous hypertension is rare. Her prior clot and postural pattern favor a venous cause."],
   ["Drug-induced edema",
    "Drug-induced edema, such as from dihydropyridine calcium channel blockers, is usually bilateral without inflammation. Her unilateral swelling after a leg clot points to post-thrombotic syndrome."]],
  C(52), "differential", "diagnosis"),

V(TX, IO_A,
  "A 68-year-old man who started amlodipine for hypertension five weeks ago has bilateral, symmetric ankle swelling without warmth, redness or tenderness. Which is the most appropriate next step?",
  [["Review the medication as the cause",
    "Correct. Dihydropyridine calcium channel blockers such as amlodipine commonly cause edema, typically bilateral and without signs of inflammation. Recognizing drug-induced edema and reviewing the medication list is the appropriate step."],
   ["Bilateral leg ultrasound",
    "Symmetric swelling without warmth or tenderness after starting amlodipine is the classic picture of drug-induced edema, not of clot, which is usually unilateral. Imaging is not the first step."],
   ["Start therapeutic anticoagulation",
    "Anticoagulation treats a confirmed clot and carries bleeding risk. Bilateral swelling with no inflammation after a new calcium channel blocker points to a drug effect, so a clot is unlikely."],
   ["Order a D-dimer",
    "A D-dimer is a nonspecific test used when deep vein thrombosis is a real concern. With bilateral, noninflamed swelling after a new drug, the likelier explanation is the medication."]],
  C(53), "differential", "next step"),

# ---------------------------------------------------------------- anticoagulation
V(TA, IO_A,
  "A 45-year-old man with a first deep vein thrombosis is otherwise healthy and hemodynamically stable. The plan is oral anticoagulation monotherapy with a loading phase followed by maintenance, without any injection lead-in. Which drug fits this strategy?",
  [["Apixaban",
    "Correct. Apixaban, a direct factor Xa inhibitor, is given as oral monotherapy with a loading dose followed by a maintenance dose, one of the three major anticoagulation strategies. Rivaroxaban follows the same pattern."],
   ["Dabigatran",
    "Dabigatran, a direct thrombin inhibitor, is started only after about five days of parenteral therapy. It does not follow the loading-then-maintenance oral monotherapy strategy that this plan describes."],
   ["Edoxaban",
    "Edoxaban is an anti-Xa agent, but it also follows five days of parenteral anticoagulation rather than serving as a stand-alone oral loading strategy. Apixaban fits an oral-only plan."],
   ["Fondaparinux",
    "Fondaparinux is an indirect factor Xa inhibitor given by injection, so it cannot be the oral monotherapy the plan describes. Apixaban is the oral direct factor Xa inhibitor for that strategy."]],
  C(61), "agent/regimen", "treatment"),

V(TA, IO_A,
  "A 52-year-old man starts outpatient treatment for deep vein thrombosis with low molecular weight heparin injections overlapped with warfarin. The injections continue for at least five days and until his international normalized ratio is above which value?",
  [["Above 2",
    "Correct. Parenteral therapy overlaps with warfarin for at least five days and until the international normalized ratio is above 2, when warfarin has reached its therapeutic effect and the heparin can stop."],
   ["Above 1",
    "An international normalized ratio just above 1 is barely different from normal, so warfarin has not yet taken effect. The overlap continues until the value is above 2."],
   ["Above 3",
    "The overlap ends once the international normalized ratio is above 2, the therapeutic threshold for this indication. Waiting for a value above 3 would prolong the injections without benefit."],
   ["Above 4",
    "An international normalized ratio above 4 is over-anticoagulated and raises the bleeding risk. The heparin overlap stops once warfarin is therapeutic, at a value above 2."]],
  C(66), "agent/regimen", "treatment"),

V(TA, IO_A,
  "A 74-year-old woman with newly diagnosed deep vein thrombosis has chronic kidney disease with a creatinine clearance below 30 mL/min. Which approach should be avoided?",
  [["Beginning therapy as an outpatient",
    "Correct. Patients with a creatinine clearance below 30 mL/min are hospitalized to start treatment, because renal insufficiency also excludes outpatient therapy. Starting at home is the approach to avoid."],
   ["Admission for intravenous heparin",
    "Hospital admission for unfractionated heparin, given as a loading bolus then a continuous infusion, is the recommended approach for severe renal disease, so it is appropriate rather than one to avoid."],
   ["Adjusting heparin by lab results",
    "Unfractionated heparin is titrated to the activated partial thromboplastin time, so laboratory-guided adjustment is standard and appropriate rather than an error."],
   ["Overlapping heparin with warfarin",
    "Heparin is given together with warfarin for at least five days and until the international normalized ratio is above 2 for at least 24 hours. This overlap is standard, not a mistake."]],
  C(67), "avoid", "avoid"),

# ---------------------------------------------------------------- duration and setting
V(TT, IO_A,
  "A 49-year-old man has a first proximal deep vein thrombosis with no surgery, trauma, hormone use, travel, cancer or other identifiable trigger, and no inherited disorder has been found. How long should anticoagulation continue?",
  [["Indefinitely",
    "Correct. A first venous thromboembolism with no identifiable risk factor is unprovoked, and its source, such as an undiscovered inherited clotting disorder, is unknown. Treatment therefore continues for an indefinite length of time."],
   ["Three months",
    "Three months is the minimum for a clot provoked by a major transient risk factor such as surgery or major trauma. An unprovoked clot has no reversible trigger, so treatment continues beyond it."],
   ["Three to six months",
    "Three to six months fits a clot provoked by a minor transient factor such as estrogen therapy, pregnancy, minor surgery or travel. An unprovoked clot has no such trigger and needs longer therapy."],
   ["Six weeks",
    "Six weeks is shorter than the minimum of three months required after any first venous thromboembolism. An unprovoked clot needs indefinite therapy."]],
  C(64), "prognosis", "treatment"),

V(TT, IO_A,
  "A 44-year-old man develops a first calf deep vein thrombosis one week after minor knee arthroscopy under a local nerve block, followed by a long car trip. Which duration of anticoagulation is appropriate?",
  [["Three to six months",
    "Correct. A clot provoked by a minor transient risk factor, such as estrogen therapy, pregnancy, minor surgery, prolonged travel or minor leg injury, is treated for three to six months, chosen from the patient's history."],
   ["Three months",
    "Three months is for a major transient risk factor such as surgery under general anesthesia, prolonged hospitalization or major trauma. His minor surgery and travel are minor factors, warranting three to six months."],
   ["Indefinitely",
    "Indefinite treatment is reserved for an unprovoked first clot. His clot has identifiable transient triggers, so open-ended anticoagulation is not needed."],
   ["Six weeks",
    "Six weeks is below the three-month minimum that applies to every first venous thromboembolism. His clot warrants three to six months."]],
  C(64), "agent/regimen", "treatment"),

V(TT, IO_A,
  "A 48-year-old man with a first calf deep vein thrombosis is hemodynamically stable, has low bleeding risk and normal kidney function, and has a supportive spouse who will bring him to every follow-up visit. Which is the best setting for treatment?",
  [["Outpatient anticoagulation",
    "Correct. Outpatient therapy suits patients who are hemodynamically stable, have low bleeding risk and no renal insufficiency, and have good support with reliable follow-up. He meets every criterion."],
   ["Hospital admission for heparin",
    "Admission is for iliofemoral clots, symptomatic pulmonary embolism, high bleeding risk or comorbidities needing inpatient care. He has none of these, so he can be treated at home."],
   ["Intensive care unit monitoring",
    "Intensive monitoring is not required for a stable patient with an uncomplicated calf clot and low bleeding risk. Outpatient anticoagulation is appropriate for him."],
   ["Observation without treatment",
    "Anticoagulation is the mainstay of treatment and is needed for at least three months. Withholding it would leave the clot free to propagate or embolize."]],
  C(65), "first-line", "next step"),

# ---------------------------------------------------------------- reversal, thrombolysis
V(TR, IO_A,
  "A 66-year-old man taking apixaban for deep vein thrombosis develops an acute intracranial hemorrhage. Which agent reverses the anticoagulant?",
  [["Andexanet alfa",
    "Correct. Andexanet alfa reverses the direct factor Xa inhibitors apixaban and rivaroxaban in life-threatening or intracranial bleeding, and it is also used off-label for edoxaban. Hemorrhage is the most serious adverse effect of anticoagulation."],
   ["Protamine sulfate",
    "Protamine sulfate reverses unfractionated heparin and low molecular weight heparin. Apixaban is a direct factor Xa inhibitor, and its reversal agent is andexanet alfa."],
   ["Idarucizumab",
    "Idarucizumab reverses dabigatran, a direct thrombin inhibitor. Apixaban is an anti-Xa agent, so its reversal agent is andexanet alfa."],
   ["Vitamin K by mouth",
    "Oral vitamin K corrects warfarin, not the direct factor Xa inhibitors. For apixaban with intracranial bleeding, the specific reversal agent is andexanet alfa."]],
  C(68), "complication", "treatment"),

V(TR, IO_A,
  "A 69-year-old man receiving an unfractionated heparin infusion for deep vein thrombosis develops life-threatening bleeding. Which agent reverses the heparin?",
  [["Protamine sulfate",
    "Correct. Protamine sulfate is the reversal agent for unfractionated heparin and low molecular weight heparin when bleeding is life-threatening. Each anticoagulant has its own specific reversal agent."],
   ["Idarucizumab",
    "Idarucizumab reverses dabigatran, a direct thrombin inhibitor, and does nothing for heparin. The agent that neutralizes heparin is protamine sulfate."],
   ["Andexanet alfa",
    "Andexanet alfa reverses the direct factor Xa inhibitors apixaban and rivaroxaban. Heparin is reversed instead by protamine sulfate."],
   ["Vitamin K by mouth",
    "Oral vitamin K is a warfarin reversal option and works slowly. Heparin has its own reversal agent, protamine sulfate, which acts on the drug directly."]],
  C(68), "complication", "treatment"),

V(TR, IO_A,
  "A 39-year-old man has a large proximal deep vein thrombosis together with a pulmonary embolism, remains hemodynamically stable and has no bleeding risk. Beyond anticoagulation, which therapy can be considered?",
  [["Thrombolysis",
    "Correct. Thrombolysis with tissue plasminogen activator, which breaks down the clot, is helpful for a large proximal deep vein thrombosis or a pulmonary embolism in a hemodynamically stable patient. Thrombectomy is another option."],
   ["Inferior vena cava filter",
    "A filter is used for acute proximal deep vein thrombosis when there is active bleeding or anticoagulation is otherwise contraindicated. He can take anticoagulants, so it is not indicated."],
   ["Venous sclerotherapy",
    "Sclerotherapy injects an agent to fibrose and obliterate superficial varicose veins. It has no role in removing a large clot in the deep venous system."],
   ["Saphenous vein stripping",
    "Vein stripping is a surgical option for varicose veins and superficial reflux. It does not treat a large proximal deep clot, which calls for thrombolysis or thrombectomy."]],
  C(70), "escalation", "treatment"),

# ---------------------------------------------------------------- upper extremity and complications
V(TC, IO_A,
  "A 62-year-old woman receiving chemotherapy through a central venous catheter has two days of right arm swelling and aching. The catheter injuring the vein wall is the endothelial trauma component of the Virchow triad. Which is the best diagnostic test?",
  [["Venous duplex ultrasound",
    "Correct. Venous duplex ultrasound of the involved extremity is the diagnostic test for deep vein thrombosis, including arm clots from central venous catheters. It has replaced venography, the old invasive gold standard."],
   ["Contrast ascending venography",
    "Contrast ascending venography was the gold standard but is invasive and has been replaced by venous duplex ultrasound. It is not the first test for a catheter-related arm clot."],
   ["Ankle-brachial index",
    "The ankle-brachial index compares ankle and arm pressures to detect peripheral artery disease in the legs. It does not evaluate a swollen arm for a venous clot."],
   ["D-dimer alone",
    "D-dimer is nonspecific and is often elevated in cancer, so a positive result cannot confirm a clot and cannot replace imaging. Venous duplex ultrasound is the test that shows the thrombus."]],
  C(57), "initial test", "test"),

V(TC, IO_A,
  "A 45-year-old woman has a catheter-related deep vein thrombosis of the right arm and asks how likely a pulmonary embolism is compared with a leg clot. Which statement is accurate?",
  [["Up to 6%, versus 15 to 30% for leg clots",
    "Correct. Pulmonary embolism occurs in up to 6% of upper-extremity deep vein thromboses, versus 15% to 30% of lower-extremity clots. Arm clots are only 5% to 10% of all deep vein thromboses."],
   ["15 to 30%, versus up to 6% for leg clots",
    "This reverses the figures. Pulmonary embolism complicates 15% to 30% of lower-extremity clots and only up to 6% of upper-extremity clots, so her risk is the lower one."],
   ["About 3% for arm and leg clots alike",
    "About 3% is the estimated fatal-embolism rate for untreated symptomatic non-massive pulmonary embolism, not the frequency of embolism, which differs by site: up to 6% for arm and 15% to 30% for leg clots."],
   ["Under 1% for arm clots, 6% for leg clots",
    "Under 1% is the untreated fatal-embolism estimate for a clot without pulmonary embolism. The actual frequency of embolism is up to 6% for arm clots and 15% to 30% for leg clots."]],
  C(47), "epidemiology", "complication"),

V(TC, IO_A,
  "A 50-year-old woman with a diagnosed leg deep vein thrombosis, not yet treated, develops sudden shortness of breath and pleuritic chest pain. Which complication has occurred?",
  [["Pulmonary embolism",
    "Correct. Part of the thrombus can break off and travel to the lungs, causing a pulmonary embolism, the most important complication of deep vein thrombosis. Sudden breathlessness and pleuritic pain in this setting should prompt that concern."],
   ["Post-thrombotic syndrome",
    "Post-thrombotic syndrome is symptomatic chronic venous insufficiency that appears 6 to 24 months after a clot. It develops slowly in the leg and does not cause sudden breathlessness."],
   ["Septic thrombophlebitis",
    "Septic thrombophlebitis is an infected superficial vein, marked by high fever, purulent drainage and redness spreading beyond the vein, usually after cannulation. It does not produce acute breathlessness."],
   ["Acute myocardial infarction",
    "Infarction of the heart is arterial, and nothing in this scenario suggests it. A known leg clot with sudden dyspnea and pleuritic pain points to embolization to the pulmonary arteries."]],
  C(72), "complication", "complication"),
]
