# -*- coding: utf-8 -*-
"""Lecture 25 objective pool A -- Heart Failure: definition, epidemiology, etiology,
left versus right, systolic versus diastolic, pathology.

KEYS ARE WRITTEN SHORT ON PURPOSE -- detail lives in the explanation.

Set 1 is recall against the syllabus objectives, so no stem carries a patient
age. Slides are the only content source; the recording only weights (the
systolic/diastolic chain is the lecture's spine, 15 minutes and "burn this in
your memory"). Scope caps live in cms_e4l25_scope.py.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _cmse3_q import Q
from cms_e4l25_scope import *


def S(topic, io, q, opts, cite, slot):
    d = Q(topic, io, q, opts, cite); d["slot"] = slot; return d


QUESTIONS = [

S("Definition and syndrome", IO_A,
  "Which description defines heart failure?",
  [["Output below demand, or met only at high filling pressures",
    "Correct. The heart cannot pump blood at a rate that meets the body's metabolic needs at rest and during effort, or manages it only because filling pressures are abnormally high. That second half is why a normal output does not exclude the syndrome."],
   ["Any ejection fraction that falls below the normal range",
    "Ejection fraction sorts heart failure into groups, but a preserved ejection fraction does not exclude it. The definition rests on inadequate output or high filling pressures."],
   ["Persistently low systolic blood pressure from any cause",
    "Low pressure has many causes outside the heart. Heart failure is defined by inadequate cardiac output for metabolic demand or output achieved only at high filling pressures."],
   ["Blockage of coronary flow causing death of heart muscle",
    "That describes myocardial infarction, which is one cause of ischemic cardiomyopathy. Heart failure is the pumping syndrome that can follow it, not the infarct itself."]],
  C(4), "etiology"),

S("Definition and syndrome", IO_A,
  "Besides signs and symptoms from a structural or functional cardiac problem, what else does clinical heart failure require?",
  [["Elevated natriuretic peptide or objective cardiogenic congestion",
    "Correct. Clinical heart failure needs the signs and symptoms plus one of two supports: an elevated B-type natriuretic peptide, or objective evidence of cardiogenic pulmonary or systemic congestion."],
   ["An ejection fraction measured at 35% or less on imaging",
    "Ejection fraction is not part of the definition; heart failure with a preserved ejection fraction is still heart failure. The added requirement is an elevated natriuretic peptide or congestion."],
   ["A documented prior myocardial infarction on the electrocardiogram",
    "Infarction is one cause of heart failure, not a requirement for the diagnosis. The definition asks for an elevated natriuretic peptide or objective congestion."],
   ["Abnormal pressures measured by right heart catheterization",
    "Catheterization grades hemodynamic severity in selected patients. It is not needed to define clinical heart failure, which uses a natriuretic peptide or evidence of congestion."]],
  C(26), "test finding"),

S("Definition and syndrome", IO_A,
  "How is congestive heart failure diagnosed?",
  [["Clinically, from signs and symptoms plus supporting evidence",
    "Correct. Congestive heart failure is a clinical diagnosis: signs and symptoms of heart failure plus an elevated B-type natriuretic peptide or cardiogenic pulmonary or systemic congestion. No single test makes the diagnosis alone."],
   ["By an ejection fraction measurement on echocardiography alone",
    "Echocardiography classifies heart failure by ejection fraction and shows structure, but a number alone is not the diagnosis. The diagnosis is clinical, built on signs, symptoms and supporting evidence."],
   ["By right heart catheterization performed in every patient",
    "Right heart catheterization is reserved for grading hemodynamic severity. The diagnosis of congestive heart failure is made clinically."],
   ["By a natriuretic peptide level interpreted on its own",
    "A natriuretic peptide supports the diagnosis only alongside signs and symptoms of heart failure. On its own it does not make a clinical diagnosis."]],
  C(32), "initial test"),

S("Acute and chronic heart failure", IO_F,
  "What does a clinical diagnosis of congestive heart failure require?",
  [["Congestion, meaning pulmonary or peripheral edema",
    "Correct. Clinical heart failure means the patient is symptomatic, and calling it congestive requires congestion, which is edema in the lungs, the periphery or both. Fatigue and exertional dyspnea without edema do not meet it."],
   ["An ejection fraction within the reduced range",
    "Congestion, not the ejection fraction group, is what makes heart failure congestive. A patient with a preserved ejection fraction and edema qualifies."],
   ["Symptoms lasting longer than one full year",
    "More than a year of symptoms defines chronic heart failure. Congestive describes the presence of edema, which is a separate question from duration."],
   ["A fourth heart sound heard on auscultation",
    "A fourth heart sound points toward a stiff, hypertrophied ventricle. The requirement for congestive heart failure is congestion, meaning pulmonary or peripheral edema."]],
  C(30), "differential"),

S("Acute and chronic heart failure", IO_F,
  "Which duration defines chronic heart failure?",
  [["More than one year",
    "Correct. Chronic heart failure is present for more than a year, with chronic fatigue, dyspnea and edema. Acute heart failure is sudden, whether it is new onset or an exacerbation of known disease."],
   ["More than one month",
    "One month is far short of the threshold. Chronic heart failure is defined as lasting more than one year, while acute heart failure is sudden in onset."],
   ["More than six months",
    "Six months still falls short. Chronic heart failure is defined as more than one year of disease with chronic fatigue, dyspnea and edema."],
   ["More than five years",
    "Five years overstates it. The threshold for chronic heart failure is more than one year, after which acute worsening is called acute on chronic heart failure."]],
  C(30), "manifestation"),

S("Acute and chronic heart failure", IO_F,
  "Which description fits acute heart failure?",
  [["Sudden onset, either new or an exacerbation",
    "Correct. Acute means sudden, and it covers both acute new-onset heart failure and an exacerbation of established disease, which in a chronic patient is called acute on chronic heart failure."],
   ["Symptoms present for more than a year",
    "Duration over a year defines chronic heart failure. Acute heart failure is defined by sudden onset rather than by how long it has lasted."],
   ["Structural disease with no symptoms at all",
    "Asymptomatic structural heart disease is pre-heart failure, stage B. Acute heart failure is symptomatic and sudden in onset."],
   ["Failure limited to the right ventricle",
    "Right-sided failure describes which ventricle is involved, not the time course. Acute heart failure is defined by sudden onset, new or as an exacerbation."]],
  C(30), "manifestation"),

S("Acute and chronic heart failure", IO_F,
  "A patient with long-standing heart failure develops a sudden worsening. How is the episode classified?",
  [["Acute on chronic heart failure",
    "Correct. In the sequence pre-heart failure, acute new onset, resolution, exacerbation, chronic heart failure and acute on chronic heart failure, a sudden worsening on a background of chronic disease is acute on chronic heart failure."],
   ["Acute new-onset heart failure",
    "New-onset heart failure is the first symptomatic episode in someone without prior heart failure. A sudden worsening of established chronic disease is acute on chronic heart failure."],
   ["Pre-heart failure with new symptoms",
    "Pre-heart failure is by definition asymptomatic structural disease. A symptomatic worsening of known chronic disease is acute on chronic heart failure."],
   ["High-output heart failure",
    "High-output failure describes elevated cardiac output from increased peripheral demand such as anemia. It says nothing about a sudden worsening of chronic disease."]],
  C(31), "differential"),

S("Epidemiology", IO_A,
  "What is the lifetime risk of developing heart failure?",
  [["About one in four",
    "Correct. Lifetime risk is 24%, about one in four, and about 6.7 million Americans older than 20 have heart failure. The burden rises steeply with age."],
   ["About one in twenty",
    "One in twenty badly understates it. The lifetime risk of heart failure is about 24%, roughly one person in four."],
   ["About one in ten",
    "One in ten still understates it. The lifetime risk of heart failure is about 24%, roughly one person in four."],
   ["About one in two",
    "One in two overstates it. The lifetime risk of heart failure is about 24%, roughly one person in four."]],
  C(6), "epidemiology"),

S("Populations", IO_G,
  "What share of patients with heart failure are older than 65?",
  [["About 60%",
    "Correct. Sixty percent of patients with heart failure are older than 65, which is why care of the elderly dominates heart failure practice and why age heads the list of risk factors."],
   ["About 15%",
    "That understates the age skew considerably. About 60% of patients with heart failure are older than 65."],
   ["About 35%",
    "That still understates it. About 60% of patients with heart failure are older than 65, and prevalence keeps rising after 80."],
   ["About 90%",
    "That overstates it. About 60% of patients with heart failure are older than 65; the rest are younger adults."]],
  C(6), "epidemiology"),

S("Populations", IO_G,
  "Roughly what proportion of people older than 80 have heart failure?",
  [["10 to 15%",
    "Correct. Between 10 and 15% of people older than 80 have heart failure, which is part of why elderly patients carry most of the burden of the syndrome."],
   ["1 to 2%",
    "That understates prevalence in the very old. Between 10 and 15% of people older than 80 have heart failure."],
   ["25 to 30%",
    "That overstates it. Between 10 and 15% of people older than 80 have heart failure, while lifetime risk overall is about one in four."],
   ["45 to 50%",
    "That is far too high. Between 10 and 15% of people older than 80 have heart failure."]],
  C(6), "epidemiology"),

S("Populations", IO_G,
  "Among patients older than 65 with heart failure, what is the one-year mortality after a hospitalization?",
  [["About 35%",
    "Correct. One-year mortality after a heart failure hospitalization is about 35% in this older group, which is why heart failure is described as a syndrome with reduced longevity."],
   ["About 5%",
    "That badly understates the risk. About 35% of these patients die within a year of a heart failure hospitalization."],
   ["About 15%",
    "That still understates it. One-year mortality after a heart failure hospitalization is about 35% in patients older than 65."],
   ["About 70%",
    "That overstates it. One-year mortality after a heart failure hospitalization is about 35% in patients older than 65."]],
  C(6), "prognosis"),

S("Left and right heart failure", IO_A,
  "What proportion of heart failure is left-sided?",
  [["70 to 80%",
    "Correct. Left-sided heart failure is by far the most common, at 70 to 80% of cases, and it is also the most common cause of right-sided heart failure."],
   ["10 to 20%",
    "That reverses the balance. Left-sided failure accounts for 70 to 80% of heart failure, far more than right-sided disease."],
   ["About half",
    "That understates it. Left-sided heart failure makes up 70 to 80% of cases, far more than right-sided or combined failure."],
   ["Nearly 100%",
    "That overstates it. Right-sided and combined failure exist in their own right; left-sided failure is 70 to 80% of cases."]],
  C(8), "epidemiology"),

S("Left and right heart failure", IO_A,
  "What is the most common cause of right-sided heart failure?",
  [["Chronic left-sided heart failure",
    "Correct. Left-sided failure backs pressure into the lungs and the right ventricle, which first hypertrophies and then dilates. Mitral stenosis and pulmonary arterial hypertension are the other causes named, but less common."],
   ["Mitral valve stenosis",
    "Mitral stenosis is a recognized cause of right-sided failure, but not the most common one. Chronic left-sided heart failure is."],
   ["Pulmonary arterial hypertension",
    "Pulmonary arterial hypertension causes right-sided failure, but less often than chronic left-sided heart failure, which is the most common cause."],
   ["Right coronary artery infarction",
    "Ischemia in the right coronary territory can injure the right ventricle, but the most common cause of right-sided failure is chronic left-sided heart failure."]],
  C(9), "etiology"),

S("Left and right heart failure", IO_A,
  "How does the prognosis of right-sided heart failure compare with left-sided heart failure?",
  [["Much worse",
    "Correct. Right-sided failure carries a much worse prognosis than left-sided failure, and because it usually grows out of chronic left-sided disease it often marks progression."],
   ["Much better",
    "The comparison runs the other way. Right-sided heart failure carries a much worse prognosis than left-sided failure."],
   ["About the same",
    "The two are not equivalent. Right-sided heart failure carries a much worse prognosis than left-sided failure."],
   ["Better once edema is treated",
    "Treating edema relieves symptoms but does not change the comparison: right-sided heart failure carries a much worse prognosis than left-sided failure."]],
  C(9), "prognosis"),

S("Left and right heart failure", IO_A,
  "Which findings reflect portal overload in right-sided heart failure?",
  [["Nausea, poor appetite and hepatomegaly",
    "Correct. Right ventricular failure backs fluid up. Portal overload gives nausea, loss of appetite and hepatomegaly with congestion or ascites, while systemic overload gives peripheral edema and jugular venous distension."],
   ["Peripheral edema and distended neck veins",
    "These are right-sided findings too, but they reflect systemic overload. Portal overload shows as nausea, loss of appetite and hepatomegaly."],
   ["Orthopnea, crackles and a third heart sound",
    "These point to the left side: pulmonary congestion and rapid filling of a dilated left ventricle. Portal overload shows as nausea, poor appetite and hepatomegaly."],
   ["Narrow pulse pressure and cool extremities",
    "These are signs of low perfusion rather than congestion. Portal overload in right-sided failure shows as nausea, poor appetite and hepatomegaly."]],
  C(10), "manifestation"),

S("Left and right heart failure", IO_A,
  "Which murmur accompanies mitral stenosis as a cause of right-sided heart failure?",
  [["Diastolic rumble at the apex with an opening snap",
    "Correct. Mitral stenosis gives a rumbling diastolic murmur at the apex with an opening snap. It is one of the three causes of right-sided failure, alongside chronic left-sided failure and pulmonary arterial hypertension."],
   ["Holosystolic murmur at the left lower sternal border",
    "That describes tricuspid regurgitation, which accompanies pulmonary arterial hypertension. Mitral stenosis gives a rumbling diastolic murmur at the apex with an opening snap."],
   ["Systolic murmur at the base radiating to the neck",
    "A basal systolic murmur radiating to the neck is the pattern of aortic stenosis, a left-sided lesion. Mitral stenosis gives a rumbling diastolic murmur at the apex with an opening snap."],
   ["Continuous murmur beneath the left clavicle",
    "A continuous murmur does not belong to any of the three causes of right-sided failure. Mitral stenosis gives a rumbling diastolic murmur at the apex with an opening snap."]],
  C(10), "manifestation"),

S("Left and right heart failure", IO_A,
  "How does the murmur of tricuspid regurgitation change with breathing?",
  [["Louder on inspiration",
    "Correct. Tricuspid regurgitation, which accompanies pulmonary arterial hypertension in right-sided failure, is a holosystolic murmur at the left lower sternal border that grows louder on inspiration."],
   ["Louder on expiration",
    "The change runs the other way. The holosystolic murmur of tricuspid regurgitation grows louder on inspiration."],
   ["Silent on inspiration",
    "It does not disappear. The tricuspid regurgitation murmur is holosystolic and grows louder on inspiration."],
   ["Unchanged by breathing",
    "It does vary with respiration. The holosystolic murmur of tricuspid regurgitation grows louder on inspiration."]],
  C(27), "differential"),

S("Diagnostic testing", IO_A,
  "In suspected right-sided heart failure, which test gives the definitive diagnosis?",
  [["Echocardiogram",
    "Correct. Clinical heart failure with jugular venous distension raises suspicion of right-sided disease, and the echocardiogram gives the definitive diagnosis by ejection fraction. Right heart catheterization then grades hemodynamic severity."],
   ["Right heart catheterization",
    "Catheterization measures hemodynamic severity once right-sided failure is suspected or established. The definitive diagnosis comes from the echocardiogram."],
   ["Natriuretic peptide level",
    "A natriuretic peptide supports a diagnosis of heart failure but cannot say which ventricle has failed. The echocardiogram gives the definitive diagnosis."],
   ["Electrocardiogram",
    "The electrocardiogram can show right heart strain but does not diagnose right-sided failure. The echocardiogram gives the definitive diagnosis."]],
  C(10), "gold standard"),

S("Diagnostic testing", IO_A,
  "What does right heart catheterization add in right-sided heart failure?",
  [["Hemodynamic severity",
    "Correct. Once right-sided failure is suspected clinically and confirmed by echocardiogram, right heart catheterization measures its hemodynamic severity. Reading the individual pressure values is left to cardiology."],
   ["The definitive diagnosis",
    "The definitive diagnosis of right-sided heart failure comes from the echocardiogram. Catheterization is used to grade hemodynamic severity."],
   ["Exclusion of acute failure",
    "Ruling out acute heart failure is a job for the natriuretic peptide, not catheterization, which grades hemodynamic severity."],
   ["Valve structure detail",
    "Structure, including the valves, is best shown by echocardiogram. Right heart catheterization grades hemodynamic severity."]],
  C(10), "test finding"),

S("Left and right heart failure", IO_A,
  "What does management of combined right and left heart failure include?",
  [["Symptom management, comfort care and transplant",
    "Correct. Combined failure is managed with symptom control, comfort care and heart transplant, the same end-of-spectrum options that appear for right-sided failure alongside palliative care."],
   ["Inotropes continued at home as maintenance",
    "Inotropic therapy such as dobutamine or milrinone is reserved for the intensive care unit. Combined failure is managed with symptom control, comfort care and transplant."],
   ["Calcium channel blockers for symptom control",
    "Calcium channel blockers are avoided in heart failure. Combined failure is managed with symptom control, comfort care and transplant."],
   ["Observation until symptoms become persistent",
    "Waiting is not the plan. Combined failure is managed actively with symptom control, comfort care and consideration of transplant."]],
  C(11), "first-line"),

S("Systolic versus diastolic", IO_B,
  "What is systolic heart failure?",
  [["Failure of contraction, the squeeze",
    "Correct. Systole is the squeeze, so systolic heart failure is dysfunction of contraction. Diastole is the rest, so diastolic failure is dysfunction of relaxation. That one distinction drives the rest of the chain."],
   ["Failure of relaxation, the rest",
    "That is diastolic heart failure. Systolic heart failure is a failure of contraction, the squeeze."],
   ["Failure of the valves to close",
    "Valve disease is a cause of heart failure, not the definition of systolic failure, which is dysfunction of contraction."],
   ["Failure of the atria to contract",
    "Atrial contraction is not what defines it. Systolic heart failure is dysfunction of ventricular contraction, the squeeze."]],
  C(12), "etiology"),

S("Systolic versus diastolic", IO_B,
  "Diastolic heart failure traces back to which cardiomyopathy?",
  [["Hypertrophic cardiomyopathy",
    "Correct. Increased muscle contracts strongly but relaxes poorly, so filling suffers. The chain runs diastolic failure, hypertrophic cardiomyopathy, hypertension, a fourth heart sound, then peripheral and pulmonary edema."],
   ["Dilated cardiomyopathy",
    "Dilated, thin, ballooned muscle contracts poorly, which is the systolic chain rather than the diastolic one. Diastolic failure traces to hypertrophic cardiomyopathy."],
   ["Ischemic cardiomyopathy",
    "Ischemic cardiomyopathy leads the systolic chain along with dilated cardiomyopathy. Diastolic failure traces to hypertrophic cardiomyopathy."],
   ["Toxin-related cardiomyopathy",
    "Toxins such as alcohol and chemotherapy cause heart failure, but the diastolic chain is anchored to hypertrophic cardiomyopathy."]],
  C(17), "etiology"),

S("Systolic versus diastolic", IO_B,
  "Most systolic heart failure traces back to which causes?",
  [["Ischemic or dilated cardiomyopathy",
    "Correct. Systolic failure runs to ischemic or dilated cardiomyopathy in the great majority of patients, then a reduced ejection fraction, normal or low blood pressure, a third heart sound and pulmonary edema."],
   ["Hypertrophic cardiomyopathy from hypertension",
    "Hypertension and hypertrophy lead the diastolic chain. Systolic failure traces to ischemic or dilated cardiomyopathy."],
   ["High-output states such as anemia",
    "Anemia causes high-output failure, a separate type. Systolic failure traces to ischemic or dilated cardiomyopathy."],
   ["Mitral stenosis with pulmonary hypertension",
    "Those are causes of right-sided failure. Systolic left-sided failure traces to ischemic or dilated cardiomyopathy."]],
  C(25), "etiology"),

S("Systolic versus diastolic", IO_B,
  "Which blood pressure pattern goes with systolic heart failure?",
  [["Normal or low",
    "Correct. A weak squeeze cannot generate a high pressure, so systolic failure runs with a normal or low blood pressure, a third heart sound and pulmonary edema. Hypertension belongs to the diastolic chain."],
   ["Elevated",
    "Hypertension belongs to the diastolic chain, with hypertrophic cardiomyopathy and a fourth heart sound. Systolic failure runs with a normal or low pressure."],
   ["Widely fluctuating",
    "Lability is not the pattern. Systolic failure runs with a normal or low blood pressure because the ventricle cannot squeeze effectively."],
   ["Orthostatic rise",
    "A rise on standing is not part of the pattern. Systolic failure runs with a normal or low blood pressure."]],
  C(39), "manifestation"),

S("Systolic versus diastolic", IO_B,
  "Which heart sound belongs to diastolic heart failure?",
  [["Fourth heart sound",
    "Correct. A fourth heart sound is strong left atrial contraction against a stiff, hypertrophied left ventricle, and it sits in the diastolic chain with hypertension and edema that starts peripherally."],
   ["Third heart sound",
    "A third heart sound is rapid filling of a dilated left ventricle, which belongs to the systolic chain. Diastolic failure gives a fourth heart sound."],
   ["An opening snap",
    "An opening snap belongs to mitral stenosis, a cause of right-sided failure. Diastolic failure gives a fourth heart sound."],
   ["A pericardial rub",
    "A rub is not part of the heart failure chain. Diastolic failure gives a fourth heart sound from atrial contraction against a stiff ventricle."]],
  C(26), "manifestation"),

S("Systolic versus diastolic", IO_B,
  "What does a third heart sound represent in heart failure?",
  [["Rapid filling of a dilated left ventricle",
    "Correct. The third heart sound falls in early diastole just after the second sound and marks rapid filling of a dilated ventricle. It belongs to the systolic chain, while the fourth sound belongs to the diastolic chain."],
   ["Atrial contraction against a stiff ventricle",
    "That is the fourth heart sound, which belongs to diastolic failure with a hypertrophied ventricle. The third sound is rapid filling of a dilated ventricle."],
   ["Closure of the atrioventricular valves",
    "Closure of the atrioventricular valves is the first heart sound. The third sound is rapid filling of a dilated left ventricle."],
   ["Closure of the aortic and pulmonic valves",
    "Closure of the outflow valves is the second heart sound. The third sound is rapid filling of a dilated left ventricle."]],
  C(26), "manifestation"),

S("Systolic versus diastolic", IO_B,
  "In the diastolic heart failure chain, how does edema progress?",
  [["Peripheral first, then pulmonary",
    "Correct. The diastolic chain ends in peripheral edema and then pulmonary edema, while the systolic chain goes straight to pulmonary edema. The order is one of the discriminators between them."],
   ["Pulmonary first, then peripheral",
    "That reverses the diastolic order. The systolic chain ends in pulmonary edema; the diastolic chain gives peripheral edema first, then pulmonary."],
   ["Pulmonary only, never peripheral",
    "That is closer to the systolic chain. Diastolic failure gives peripheral edema first and then pulmonary edema."],
   ["Peripheral only, never pulmonary",
    "The diastolic chain does reach the lungs. It gives peripheral edema first and then pulmonary edema."]],
  C(56), "manifestation"),

S("Systolic versus diastolic", IO_B,
  "How does dilated cardiomyopathy differ from hypertrophic cardiomyopathy?",
  [["Thin, ballooned muscle that contracts poorly",
    "Correct. Dilated cardiomyopathy is decreased muscle with poor contraction and loss of elasticity. Hypertrophic cardiomyopathy is increased muscle that contracts strongly but relaxes poorly."],
   ["Thickened muscle that relaxes poorly",
    "That describes hypertrophic cardiomyopathy, which leads the diastolic chain. Dilated cardiomyopathy is thin and ballooned and contracts poorly."],
   ["Normal muscle with leaking valves",
    "Valve disease is a separate cause of heart failure. Dilated cardiomyopathy is thin, ballooned muscle that contracts poorly."],
   ["Thickened muscle that contracts poorly",
    "Thickened muscle contracts strongly and relaxes poorly. Dilated cardiomyopathy is thin, ballooned muscle with poor contraction."]],
  C(13), "differential"),

S("Pathology", IO_A,
  "Which is one of the four basic mechanisms of heart failure?",
  [["Excessive afterload",
    "Correct. The four are increased blood volume (excess preload), increased resistance (excess afterload), decreased contractility and decreased filling. Each leads through acute damage or chronic stress to remodeling."],
   ["Increased contractility",
    "Contractility is decreased, not increased, in the mechanism list. The four are excess preload, excess afterload, decreased contractility and decreased filling."],
   ["Increased filling",
    "Filling is decreased, not increased. The four mechanisms are excess preload, excess afterload, decreased contractility and decreased filling."],
   ["Reduced blood volume",
    "Volume is increased in the mechanism list, as excessive preload. The four are excess preload, excess afterload, decreased contractility and decreased filling."]],
  C(19), "etiology"),

S("Pathology", IO_A,
  "What does cardiac remodeling consist of?",
  [["Myocyte hypertrophy and collagen fibrosis",
    "Correct. Acute damage or chronic conditions drive remodeling, which is myocyte hypertrophy and collagen fibrosis. Neurohormonal activation, inflammation and mechanical stress push it along."],
   ["Myocyte regeneration and scar resorption",
    "Remodeling is not repair. It consists of myocyte hypertrophy and collagen fibrosis driven by damage and neurohormonal activation."],
   ["Valve calcification and annular widening",
    "Those are valve changes rather than remodeling of the myocardium, which consists of myocyte hypertrophy and collagen fibrosis."],
   ["Coronary plaque rupture and thrombosis",
    "Plaque rupture causes infarction, one route to damage. Remodeling itself is myocyte hypertrophy and collagen fibrosis."]],
  C(19), "etiology"),

S("Pathology", IO_A,
  "Which neurohormonal system is a beneficial compensation rather than a driver of damage in heart failure?",
  [["Natriuretic peptides",
    "Correct. Natriuretic peptides dilate vessels and reduce cardiac load. The sympathetic nervous system and the renin-angiotensin-aldosterone system exacerbate the damage and drive remodeling."],
   ["Renin-angiotensin-aldosterone system",
    "This system exacerbates the damage, retaining salt and water and driving remodeling. The beneficial compensation comes from the natriuretic peptides."],
   ["Sympathetic nervous system",
    "Sympathetic activation raises catecholamines and exacerbates the damage. The beneficial compensation comes from the natriuretic peptides."],
   ["Catecholamine surge",
    "Catecholamines come from sympathetic activation, which worsens remodeling. The beneficial compensation comes from the natriuretic peptides."]],
  C(20), "etiology"),

S("Pathology", IO_A,
  "How does the body respond to increased metabolic demand in heart failure?",
  [["Raises heart rate, contractility and preload",
    "Correct. Neurohormonal input raises the heart rate, catecholamines and autonomic input raise contractility, and venous capacitance and renal compensation augment preload. These help at first and later drive damage."],
   ["Slows heart rate to lengthen filling time",
    "The response is the opposite: neurohormonal input increases heart rate, alongside greater contractility and augmented preload."],
   ["Lowers preload through venous pooling",
    "Preload is augmented, not lowered, through venous capacitance and renal compensation, alongside a faster heart rate and greater contractility."],
   ["Lowers contractility to spare oxygen",
    "Contractility rises through catecholamines and autonomic input, together with heart rate and preload."]],
  C(4), "etiology"),

S("Etiology", IO_A,
  "What is the most common valvular cause of heart failure?",
  [["Aortic stenosis",
    "Correct. Valvular disease is among the causes of heart failure, and aortic stenosis is the most common valvular one. Mitral stenosis appears instead as a cause of right-sided failure."],
   ["Mitral stenosis",
    "Mitral stenosis is a cause of right-sided heart failure. The most common valvular cause of heart failure overall is aortic stenosis."],
   ["Tricuspid regurgitation",
    "Tricuspid regurgitation is a murmur heard with pulmonary arterial hypertension in right-sided failure. The most common valvular cause is aortic stenosis."],
   ["Pulmonic stenosis",
    "Pulmonic stenosis is not the leading valvular cause. The most common valvular cause of heart failure is aortic stenosis."]],
  C(16), "etiology"),

S("Etiology", IO_A,
  "Which causes fall under ischemic cardiomyopathy?",
  [["Infarction, ongoing ischemia or shock",
    "Correct. Ischemic cardiomyopathy covers myocardial infarction, persistent or chronic intermittent myocardial ischemia, and hypoperfusion from shock. Everything else is non-ischemic cardiomyopathy."],
   ["Alcohol and chemotherapy exposure",
    "Toxins such as alcohol and chemotherapy are causes of heart failure, but they are non-ischemic. Ischemic cardiomyopathy covers infarction, ischemia and shock."],
   ["Diabetes, thyroid disease and lupus",
    "These are autoimmune and metabolic causes and count as non-ischemic. Ischemic cardiomyopathy covers infarction, ischemia and shock."],
   ["Congenital structural heart disease",
    "Congenital disease is a non-ischemic cause. Ischemic cardiomyopathy covers infarction, persistent or intermittent ischemia and shock."]],
  C(16), "etiology"),

S("Etiology", IO_A,
  "Which toxins cause heart failure?",
  [["Alcohol and chemotherapy",
    "Correct. Toxins such as alcohol and chemotherapy sit among the non-ischemic causes of heart failure, alongside hypertension, valvular disease and autoimmune or metabolic disease."],
   ["Caffeine and nicotine gum",
    "These are not among the toxic causes. The toxins that cause heart failure are alcohol and chemotherapy."],
   ["Lead and arsenic salts",
    "Lead and arsenic are not among the toxic causes of heart failure. Alcohol and chemotherapy are the toxic causes of heart failure."],
   ["Aspirin and acetaminophen",
    "Common analgesics such as these are not toxic causes of heart failure. Alcohol and chemotherapy are the toxic causes of heart failure."]],
  C(16), "etiology"),

S("Etiology", IO_A,
  "Which statement captures the etiology of all heart failure?",
  [["Every case has a cardiomyopathy etiology",
    "Correct. All heart failure, as a syndrome, has a cardiomyopathy behind it, whether ischemic or non-ischemic. That is why the causes are sorted as ischemic cardiomyopathy versus everything else."],
   ["Every case begins with coronary disease",
    "Coronary disease drives ischemic cardiomyopathy, but non-ischemic causes such as hypertension, valve disease and toxins also cause heart failure."],
   ["Every case begins with hypertension",
    "Hypertension is common but not universal. What all heart failure shares is an underlying cardiomyopathy, ischemic or non-ischemic."],
   ["Every case begins with valve disease",
    "Valve disease, most often aortic stenosis, is only one cause. All heart failure shares an underlying cardiomyopathy."]],
  C(16), "etiology"),

S("Risk factors", IO_A,
  "Which of these is a risk factor for heart failure?",
  [["Chronic tachyarrhythmias",
    "Correct. Chronic tachyarrhythmias sit on the risk factor list with age, hypertension, coronary artery disease, diabetes, obesity, alcohol, tobacco, family history, genetics and cardiotoxic medicines."],
   ["Regular aerobic exercise",
    "Exercise is not a risk factor. The list includes chronic tachyarrhythmias, hypertension, diabetes, obesity and tobacco, among others."],
   ["Low dietary potassium",
    "Low dietary potassium is not a heart failure risk factor. Chronic tachyarrhythmias are, along with hypertension, diabetes and coronary artery disease."],
   ["Chronic bradycardia",
    "Chronic slow rhythms are not a heart failure risk factor; fast ones are. Chronic tachyarrhythmias are, along with hypertension, diabetes and coronary artery disease."]],
  C(18), "risk factors"),

S("Risk factors", IO_A,
  "Which metabolic condition is a risk factor for heart failure?",
  [["Obesity or metabolic syndrome",
    "Correct. Obesity and metabolic syndrome are risk factors, along with diabetes, hypertension and coronary artery disease. They are also targets a patient can change."],
   ["Low body mass with good fitness",
    "Leanness and fitness are not risk factors. Obesity and metabolic syndrome are, along with diabetes and hypertension."],
   ["Iron overload from diet alone",
    "Dietary iron is not on the list. Obesity and metabolic syndrome are risk factors, along with diabetes and hypertension."],
   ["Low blood cholesterol levels",
    "Low cholesterol is not a risk factor. Obesity and metabolic syndrome are, along with diabetes, hypertension and coronary artery disease."]],
  C(18), "risk factors"),

S("Risk factors", IO_A,
  "Which heart failure risk factors can a patient change?",
  [["Tobacco, excess alcohol and obesity",
    "Correct. These are modifiable, so they are the targets of prevention counseling. Age, family history and genetic abnormality are risk factors a patient cannot change."],
   ["Age, family history and genetics",
    "These are real risk factors, but none can be changed. Tobacco, excess alcohol and obesity are the modifiable ones."],
   ["Age, genetics and prior infarction",
    "Age and genetics cannot be changed, and a past infarction cannot be undone. Tobacco, excess alcohol and obesity are the modifiable targets."],
   ["Family history and advancing age",
    "Neither can be changed. Tobacco, excess alcohol and obesity are the risk factors a patient can modify."]],
  C(18), "education"),
]
