# CMS I Lecture 3 (Dermatology II) — SET 2, vignette pool C.
# Stevens-Johnson syndrome, toxic epidermal necrolysis, sunburn, drug-induced
# photosensitivity, photodermatitis, polymorphous light eruption, solar lentigo,
# actinic keratosis, dermatoheliosis.
#
# Options drafted at matched lengths. Lead-ins were counted against pools A and
# B before drafting (diagnosis 10, test 8, next step 7, education 7, treatment 9
# across 41 questions) and this pool holds that spread so the partition's 40%
# skew guard passes on both forms.
#
# Correct answer is ALWAYS written first (c=0); the partition script rotates.
SRC = "3. Dermatology  II.pptx"
def c(n): return f"{SRC}, Slide {n}"

IOA = "a — Etiologies, manifestations, diagnosis and management of dermatological conditions"

POOL_C = [
 dict(topic="Stevens-Johnson syndrome", io=IOA,
   q="A 34-year-old man started lamotrigine three weeks ago. He has three days of fever and sore throat, then painful dusky macules on the trunk, erosions of the lips and conjunctivae, and epidermal detachment over about 6% of his body surface. Which is the most likely diagnosis?",
   opts=[
     ["Stevens-Johnson syndrome",
      "Correct — detachment under 10% with mucosal involvement, three weeks into an aromatic anticonvulsant."],
     ["Toxic epidermal necrolysis",
      "That requires detachment above 30% of the body surface area."],
     ["Staphylococcal scalded skin syndrome",
      "That is toxin-mediated and spares the mucous membranes entirely."],
     ["Erythema multiforme major",
      "That is usually herpes-associated with acral targets and less mucosal disease."]],
   c=0, cite=c(80)),

 dict(topic="Stevens-Johnson syndrome", io=IOA,
   q="A 41-year-old woman with painful skin and oral erosions has suspected Stevens-Johnson syndrome. Which diagnostic test is considered pathognomonic?",
   opts=[
     ["Punch biopsy showing full-thickness epidermal necrosis with junctional separation",
      "Correct — that histology is the pathognomonic finding named for this condition."],
     ["Direct immunofluorescence showing granular immunoglobulin A at the papillae",
      "That finding establishes dermatitis herpetiformis."],
     ["Transmission electron microscopy with immunofluorescence antigen mapping",
      "That is the gold standard for epidermolysis bullosa."],
     ["Serum tryptase measured within four hours of the acute eruption",
      "That is used in the evaluation of mast cell disease and anaphylaxis."]],
   c=0, cite=c(82)),

 dict(topic="Stevens-Johnson syndrome", io=IOA,
   q="A 52-year-old man is admitted with Stevens-Johnson syndrome six days after starting trimethoprim-sulfamethoxazole. Which is the single most important initial action?",
   opts=[
     ["Discontinue the suspected drug and every other non-essential medication",
      "Correct — earlier withdrawal is strongly associated with improved survival, and each day of delay worsens it."],
     ["Begin intravenous immunoglobulin at one gram per kilogram for three days",
      "Immunomodulation follows, but drug withdrawal is the action that changes survival."],
     ["Begin high-dose systemic corticosteroids and continue for several weeks",
      "Steroids remain controversial and are avoided where infection is active."],
     ["Apply silver sulfadiazine dressings to the areas of detached epidermis",
      "Silver sulfadiazine is specifically avoided because of sulfonamide cross-reaction."]],
   c=0, cite=c(83)),

 dict(topic="Stevens-Johnson syndrome", io=IOA,
   q="A 28-year-old woman is recovering from carbamazepine-induced Stevens-Johnson syndrome and is being discharged. Which is the most appropriate counselling point?",
   opts=[
     ["Avoid the causative drug class for life, wear a medical alert bracelet, and have first-degree relatives counselled on shared genetic risk",
      "Correct — the human leukocyte antigen association makes family counselling part of the discharge advice."],
     ["Avoid the causative drug for six months, after which cautious rechallenge under supervision is reasonable",
      "Rechallenge is never appropriate; avoidance is lifelong."],
     ["Expect complete recovery within weeks, with no need for any specialist follow-up after discharge",
      "Long-term ophthalmology, dermatology and psychological follow-up are all expected."],
     ["Avoid sun exposure and use broad-spectrum sunscreen daily to prevent the eruption from recurring",
      "The reaction is drug-triggered rather than light-triggered."]],
   c=0, cite=c(84)),

 dict(topic="Stevens-Johnson syndrome", io=IOA,
   q="A 36-year-old man with Stevens-Johnson syndrome reports gritty, painful eyes on the day of admission. Which is the most appropriate next step?",
   opts=[
     ["Urgent ophthalmology consultation with slit-lamp examination",
      "Correct — ocular involvement drives the blinding sequelae of symblepharon and corneal scarring."],
     ["Reassure and reassess the eyes once the skin has re-epithelialised",
      "Delay is what permits permanent ocular scarring."],
     ["Begin topical antibiotic eye drops and review in seventy-two hours",
      "Empirical drops without examination miss the extent of corneal involvement."],
     ["Patch both eyes closed until the acute skin disease has settled",
      "Patching does not prevent adhesions and delays daily assessment."]],
   c=0, cite=c(83)),

 dict(topic="Toxic epidermal necrolysis", io=IOA,
   q="A 67-year-old man taking allopurinol for two weeks has fever, painful erythema and flaccid bullae, with sheets of epidermis separating over an estimated 45% of his body surface. Which is the most likely diagnosis?",
   opts=[
     ["Toxic epidermal necrolysis",
      "Correct — detachment above 30% with allopurinol exposure. The slide names allopurinol as the commonest cause IN ASIA, alongside aromatic anticonvulsants, sulfonamides, oxicam non-steroidals and nevirapine."],
     ["Stevens-Johnson and toxic epidermal necrolysis overlap",
      "Overlap is defined by detachment between 10 and 30%."],
     ["Generalised bullous fixed drug eruption of the trunk",
      "That produces discrete round plaques recurring at the same sites."],
     ["Autoimmune pemphigus vulgaris with widespread erosions",
      "That evolves over weeks with intercellular immunoglobulin G on immunofluorescence."]],
   c=0, cite=c(87)),

 dict(topic="Toxic epidermal necrolysis", io=IOA,
   q="A 58-year-old woman is admitted with toxic epidermal necrolysis. She has a known lymphoma, a heart rate of 132, detachment of 35% of her body surface, blood urea nitrogen of 34 mg/dL, bicarbonate of 17 mEq/L and glucose of 190 mg/dL. Which score should be calculated and what does it indicate?",
   opts=[
     ["A SCORTEN of 6, indicating a predicted mortality of about 90%",
      "Correct — age, malignancy, heart rate, detachment, urea and bicarbonate each score, and glucose is below threshold."],
     ["A SCORTEN of 4, indicating a predicted mortality of about 35%",
      "That undercounts; six of the seven variables are above threshold here."],
     ["A SCORTEN of 2, indicating a predicted mortality of about 12%",
      "That would apply to a far less severe presentation than this one."],
     ["A SCORTEN of 7, indicating a predicted mortality of about 90%",
      "Glucose of 190 mg/dL is below the 252 mg/dL threshold, so it does not score."]],
   c=0, cite=c(89)),

 dict(topic="Toxic epidermal necrolysis", io=IOA,
   q="A 49-year-old man with toxic epidermal necrolysis has been admitted to the burn unit and the offending drug stopped. Which pharmacologic therapy has the strongest current evidence base?",
   opts=[
     ["Cyclosporine at 3 to 5 mg/kg daily, started early",
      "Correct — early initiation is preferred and the evidence is the strongest of the available options."],
     ["Prophylactic broad-spectrum intravenous antibiotics",
      "Antibiotic prophylaxis is specifically not recommended; treat confirmed infection."],
     ["Pulsed methylprednisolone continued for fourteen days",
      "Systemic corticosteroids remain controversial in this setting."],
     ["Subcutaneous omalizumab given every four weeks",
      "That is a therapy for refractory chronic urticaria."]],
   c=0, cite=c(90)),

 dict(topic="Toxic epidermal necrolysis", io=IOA,
   q="A 71-year-old woman with toxic epidermal necrolysis has a SCORTEN of 5 on admission. Beyond intensive care, which referral is specifically indicated at this score?",
   opts=[
     ["Palliative care, for an early goals-of-care discussion",
      "Correct — a score of five or above carries a predicted mortality near 90% and palliative involvement is named."],
     ["Genetics, for human leukocyte antigen haplotype testing",
      "That is appropriate later, and for at-risk populations rather than at this score."],
     ["Physical therapy, for early prevention of joint contracture",
      "Rehabilitation matters in survivors but is not what the score triggers."],
     ["Plastic surgery, for planning of definitive skin grafting",
      "Wound care uses biological dressings rather than early grafting."]],
   c=0, cite=c(90)),

 dict(topic="Sunburn", io=IOA,
   q="A 24-year-old woman spent six hours at the beach. Eight hours later her shoulders are red, hot and tender, without blisters. Which is the most appropriate management?",
   opts=[
     ["Cool compresses, oral hydration and an early nonsteroidal anti-inflammatory drug",
      "Correct — early nonsteroidals reduce the prostaglandin-mediated inflammation and pain."],
     ["A short course of oral corticosteroids tapered over the following week",
      "Systemic steroids are not part of the management of ordinary sunburn."],
     ["Cold water immersion with ice packs applied directly to the erythema",
      "Cool rather than cold water is advised, and ice risks further injury."],
     ["Topical silver sulfadiazine applied twice daily under an occlusive layer",
      "That is a burn dressing agent and is not used for first-degree sunburn."]],
   c=0, cite=c(96)),

 dict(topic="Sunburn", io=IOA,
   q="A 19-year-old man has extensive blistering sunburn over his back and chest with fever, nausea and tachycardia after a day on the water. Which is the most appropriate next step?",
   opts=[
     ["Admit for intravenous fluids and wound care given the systemic toxicity",
      "Correct — severe blistering above 20% of the body surface with systemic symptoms warrants hospitalisation."],
     ["Deroof the blisters in clinic and dress the base with a non-adherent layer",
      "Intact blisters are protective and should not be popped."],
     ["Discharge with oral ibuprofen and aloe vera gel, reviewing in one week",
      "That underestimates a presentation with fever, nausea and tachycardia."],
     ["Start oral antibiotics to prevent secondary infection of the blistered skin",
      "Prophylactic antibiotics are not indicated for uninfected burn blisters."]],
   c=0, cite=c(96)),

 dict(topic="Sunburn", io=IOA,
   q="A 17-year-old asks whether using a tanning bed before a holiday will protect her from burning. Which is the most appropriate counselling point?",
   opts=[
     ["Tanning beds are classified as Group 1 carcinogens and are not safer than natural sun",
      "Correct — the International Agency for Research on Cancer classification is the specific point to make."],
     ["A base tan from a tanning bed gives protection equivalent to sunscreen of SPF 15",
      "There is no safe level of tanning, and a base tan is not meaningful protection."],
     ["Tanning beds are safe when used for under ten minutes at a time before travel",
      "Duration does not make the exposure safe; the classification applies regardless."],
     ["Tanning beds emit only ultraviolet A, which does not contribute to skin cancer",
      "Ultraviolet A drives oxidative damage and contributes to cancer and photoaging."]],
   c=0, cite=c(96)),

 dict(topic="Photosensitivity", io=IOA,
   q="A 26-year-old man started doxycycline four days ago and after one hour of gardening develops a burning, sharply demarcated erythema on his forearms and neck that looks like an exaggerated sunburn. Which is the most likely mechanism?",
   opts=[
     ["Phototoxicity, a non-immunologic dose-dependent reaction",
      "Correct — it occurs on first exposure, within hours, and doxycycline is the classic agent."],
     ["Photoallergy, an immunologic delayed hypersensitivity reaction",
      "That requires prior sensitisation and produces an eczematous eruption."],
     ["Photoaggravation of an underlying connective tissue disease",
      "That would come with systemic features and positive autoantibodies."],
     ["Phytophotodermatitis from a furanocoumarin-containing plant",
      "That produces streaked, linear lesions where the plant sap touched."]],
   c=0, cite=c(98)),

 dict(topic="Photosensitivity", io=IOA,
   q="A 44-year-old woman has an itchy, eczematous eruption on sun-exposed skin that extends onto covered areas, beginning after two weeks of a new sunscreen. Which test establishes the diagnosis?",
   opts=[
     ["Photopatch testing with duplicate sets, one of which is irradiated",
      "Correct — it is the gold standard for photoallergy; a reaction only on the irradiated set confirms it."],
     ["Minimal erythema dose testing to ultraviolet A and ultraviolet B",
      "That quantifies light sensitivity but does not identify the responsible chemical."],
     ["Skin biopsy of the eruption sent for direct immunofluorescence",
      "Biopsy is rarely needed and immunofluorescence addresses other diseases."],
     ["Antinuclear antibody panel including anti-Ro and anti-La antibodies",
      "That screens for lupus rather than confirming a photoallergy."]],
   c=0, cite=c(99)),

 dict(topic="Photosensitivity", io=IOA,
   q="A 62-year-old woman on amiodarone develops photosensitivity, and the cardiologist cannot substitute the drug. Which is the most appropriate management?",
   opts=[
     ["Strict photoprotection with broad-spectrum SPF 50 and physical blockers",
      "Correct — zinc oxide and titanium dioxide are named where the agent cannot be withdrawn."],
     ["Prophylactic narrowband ultraviolet B phototherapy given each spring",
      "That is used for persistent light reaction and for polymorphous light eruption."],
     ["Oral hydroxychloroquine at 200 mg twice daily as a long-term measure",
      "That is reserved for refractory polymorphous light eruption."],
     ["Oral antihistamines taken each morning through the summer months",
      "Antihistamines address pruritus and do not prevent phototoxic injury."]],
   c=0, cite=c(99)),

 dict(topic="Photodermatitis", io=IOA,
   q="A 31-year-old man returns from a beach holiday with painful blisters followed by odd streaked brown marks on both forearms. He had been squeezing limes into drinks in the sun. Which is the most likely diagnosis?",
   opts=[
     ["Phytophotodermatitis from furanocoumarins in lime juice",
      "Correct — linear streaked hyperpigmentation after lime plus sun is the classic presentation."],
     ["Berloque dermatitis from bergapten in a fragrance product",
      "That produces a drip pattern on the neck and décolletage."],
     ["Chronic actinic dermatitis of the forearms and dorsal hands",
      "That is a persistent eczematous eruption in older males."],
     ["Allergic contact dermatitis to an ingredient in his sunscreen",
      "That would be eczematous and would not follow a streaked pattern."]],
   c=0, cite=c(100)),

 dict(topic="Photodermatitis", io=IOA,
   q="A 33-year-old woman with resolved phytophotodermatitis is distressed by persistent brown streaks on her arms. Which is the most appropriate counselling point?",
   opts=[
     ["The pigmentation fades over months, and daily sunscreen prevents it darkening further",
      "Correct — reassurance is first line, with hydroquinone or azelaic acid if it persists."],
     ["The pigmentation is permanent and only laser resurfacing will remove it",
      "It fades over months without any procedural intervention."],
     ["The pigmentation indicates ongoing inflammation requiring potent steroids",
      "The acute phase has resolved; the pigment is post-inflammatory."],
     ["The pigmentation signals a risk of melanoma at those sites in future",
      "There is no malignant risk from phytophotodermatitis."]],
   c=0, cite=c(101)),

 dict(topic="Polymorphous light eruption", io=IOA,
   q="A 28-year-old woman develops itchy 3 mm red papules on her chest and forearms hours after the first sunny weekend of spring. The same thing happened last April and settled by midsummer. Her face is spared. Which is the most likely diagnosis?",
   opts=[
     ["Polymorphous light eruption",
      "Correct — spring onset, sparing of chronically exposed skin, and summer hardening are all characteristic."],
     ["Subacute cutaneous lupus erythematosus",
      "That is distinguished by antinuclear and anti-Ro antibodies and does not harden."],
     ["Solar urticaria of the chest and forearms",
      "That produces wheals within minutes that resolve within an hour."],
     ["Erythropoietic protoporphyria of adult onset",
      "That begins in childhood with burning pain and raised red-cell protoporphyrin."]],
   c=0, cite=c(105)),

 dict(topic="Polymorphous light eruption", io=IOA,
   q="A 35-year-old woman has a clinically typical polymorphous light eruption. Which investigation is described as mandatory before the diagnosis is accepted?",
   opts=[
     ["An antinuclear antibody panel including anti-Ro and anti-La",
      "Correct — lupus must be excluded because it can present identically."],
     ["A urine, stool and red-cell porphyrin screen sent together",
      "That is ordered only where erythropoietic protoporphyria is suspected."],
     ["Photopatch testing to a standard series of photoallergens",
      "That is reserved for suspected photoallergic contact dermatitis."],
     ["A skin biopsy of a fresh papule taken within the first day",
      "Biopsy is supportive rather than pathognomonic and is not mandatory."]],
   c=0, cite=c(106)),

 dict(topic="Polymorphous light eruption", io=IOA,
   q="A 30-year-old woman has had polymorphous light eruption ruin the first weeks of every summer for four years. It is now February. Which is the most effective preventive strategy?",
   opts=[
     ["Prophylactic narrowband ultraviolet B, three times weekly for five weeks in spring",
      "Correct — it induces tolerance and is named as the most effective preventive strategy."],
     ["Hydroxychloroquine at 200 mg twice daily started at the first eruption",
      "That is for refractory cases rather than the most effective prevention."],
     ["A short course of oral prednisolone taken at the onset of each episode",
      "That treats a severe acute episode rather than preventing recurrence."],
     ["Moderate-potency topical corticosteroid applied to the areas each spring",
      "Topical steroids treat the acute eruption; they do not induce tolerance."]],
   c=0, cite=c(106)),

 dict(topic="Solar lentigo", io=IOA,
   q="A 68-year-old man has several uniformly tan, well-demarcated macules 5 to 12 mm across on the dorsal hands and forearms, with no scale or induration. Dermoscopy shows finger-like projections and a moth-eaten border. Which is the most likely diagnosis?",
   opts=[
     ["Solar lentigo",
      "Correct — uniform pigment on chronically exposed skin with those dermoscopic features."],
     ["Lentigo maligna",
      "That is asymmetric with irregular border and structureless pigment on dermoscopy."],
     ["Seborrheic keratosis",
      "That is stuck-on with comedone-like openings on dermoscopy."],
     ["Pigmented actinic keratosis",
      "That has a rough scaly texture rather than a smooth macular surface."]],
   c=0, cite=c(111)),

 dict(topic="Solar lentigo", io=IOA,
   q="A 64-year-old woman has one facial pigmented macule that is asymmetric with an irregular border and two darker areas within it, unlike her other lesions. Which is the most appropriate next step?",
   opts=[
     ["Biopsy the lesion to exclude lentigo maligna",
      "Correct — atypical or uncertain morphology on dermoscopy is the stated indication for biopsy."],
     ["Treat the lesion with cryotherapy for five seconds",
      "Destroying an atypical lesion removes the ability to diagnose it."],
     ["Begin topical hydroquinone 4% and review in three months",
      "Bleaching an atypical pigmented lesion delays a melanoma diagnosis."],
     ["Reassure and arrange routine review in twelve months",
      "The asymmetry and colour variation warrant assessment now."]],
   c=0, cite=c(111)),

 dict(topic="Actinic keratosis", io=IOA,
   q="A 72-year-old outdoor worker has rough, scaly, erythematous papules with a sandpaper texture scattered across his balding scalp and dorsal hands. Which is the most likely diagnosis?",
   opts=[
     ["Actinic keratosis",
      "Correct — sandpaper texture on chronically sun-exposed skin, the commonest precancerous lesion worldwide."],
     ["Seborrheic keratosis",
      "That is stuck-on and waxy without the gritty sandpaper feel."],
     ["Bowen disease",
      "That is a well-demarcated scaly plaque rather than multiple gritty papules."],
     ["Scalp psoriasis",
      "That produces thick silvery plaques with a different distribution."]],
   c=0, cite=c(113)),

 dict(topic="Actinic keratosis", io=IOA,
   q="A 70-year-old man has more than thirty confluent actinic keratoses across his scalp and forehead. Which is the most appropriate treatment approach?",
   opts=[
     ["Field-directed therapy, such as topical 5-fluorouracil or photodynamic therapy",
      "Correct — field cancerization means the surrounding normal-looking skin also carries mutations."],
     ["Lesion-directed cryotherapy to each keratosis over several sessions",
      "Cryotherapy is standard for isolated lesions but leaves the affected field untreated."],
     ["Shave excision with curettage and electrodessication of every lesion",
      "That is a lesion-directed technique and is impractical at this number."],
     ["Observation with photographic monitoring and review in twelve months",
      "Confluent disease at this density warrants treatment rather than observation."]],
   c=0, cite=c(113)),

 dict(topic="Actinic keratosis", io=IOA,
   q="A 66-year-old woman has an actinic keratosis on the cheek that has become indurated, tender and has bled twice. Which is the most appropriate next step?",
   opts=[
     ["Biopsy the lesion to exclude invasive squamous cell carcinoma",
      "Correct — induration, tenderness and bleeding are the concerning features named for progression."],
     ["Apply liquid nitrogen with two to three freeze-thaw cycles",
      "Destroying a lesion with concerning features forfeits the diagnosis."],
     ["Begin imiquimod 5% twice weekly for a sixteen-week course",
      "Field therapy does not address a lesion suspicious for invasion."],
     ["Begin diclofenac 3% gel and reassess it in three months",
      "That is for mild disease and would delay diagnosis here."]],
   c=0, cite=c(113)),

 dict(topic="Actinic keratosis", io=IOA,
   q="A 55-year-old kidney transplant recipient asks why she is being seen so often for skin checks. Which is the most appropriate counselling point?",
   opts=[
     ["Immunosuppression raises the risk of actinic keratosis and skin cancer about sixty-fold",
      "Correct — transplant recipients need aggressive photoprotection and biannual skin surveillance."],
     ["Transplant medication makes the skin more sensitive to burning within minutes of sun",
      "The concern is cumulative carcinogenic risk rather than acute burning."],
     ["Frequent review is a routine protocol requirement rather than a clinical necessity",
      "The elevated risk is the clinical reason for the increased surveillance."],
     ["Skin cancers in transplant recipients behave less aggressively than in other patients",
      "They are both more frequent and more aggressive in this group."]],
   c=0, cite=c(112)),

 dict(topic="Dermatoheliosis", io=IOA,
   q="A 74-year-old farmer has deep coarse wrinkles, mottled pigmentation, telangiectasias and thick furrowed skin on the back of his neck. His sun-protected skin looks far younger. Which is the most likely diagnosis?",
   opts=[
     ["Dermatoheliosis, with cutis rhomboidalis nuchae",
      "Correct — the furrowed posterior neck is the classic marker of severe photoaging."],
     ["Intrinsic chronological aging of the skin",
      "That affects sun-protected skin equally and lacks the dyspigmentation."],
     ["Poikiloderma of Civatte of the lateral neck",
      "That typically affects perimenopausal women and spares the submental shadow."],
     ["Acquired cutis laxa involving the neck",
      "That is a loss of elastic tissue from genetic or inflammatory causes."]],
   c=0, cite=c(117)),

 dict(topic="Dermatoheliosis", io=IOA,
   q="A 59-year-old woman wants treatment for photoaging of her face. Which topical agent is the only one approved by the Food and Drug Administration for this indication?",
   opts=[
     ["Tretinoin at 0.025 to 0.1%",
      "Correct — it stimulates collagen and inhibits matrix metalloproteinases, over six to twelve months."],
     ["Vitamin C at 10 to 20%",
      "It neutralises reactive oxygen species but is not approved for photoaging."],
     ["Hydroquinone at 2 to 4%",
      "That treats hyperpigmentation rather than photoaging as a whole."],
     ["Niacinamide applied twice daily",
      "It is anti-inflammatory and reduces sallowness but is not approved."]],
   c=0, cite=c(119)),

 dict(topic="Dermatoheliosis", io=IOA,
   q="A 47-year-old man with early photoaging asks what single measure will most reduce further damage. Which is the most appropriate counselling point?",
   opts=[
     ["Daily broad-spectrum sunscreen of SPF 30 or higher, applied as the last skincare step",
      "Correct — it is the single most evidence-supported intervention, at about one teaspoon for face and neck."],
     ["Nightly topical retinoid, since it reverses the collagen loss already sustained",
      "Retinoid improves established damage but photoprotection is what prevents progression."],
     ["Annual laser resurfacing, since it is the most effective option for texture",
      "Resurfacing treats existing change rather than preventing new damage."],
     ["Oral antioxidant supplements taken daily through the summer months",
      "Supplements are not among the named interventions for photoaging."]],
   c=0, cite=c(119)),
]
