# CMS I, Lecture 1 — question pool, part B
# Clinical principles and decision-making / the naturalistic approach
SRC = "1. svClinical Reasoning and Problem Solving.pptx"

def c(n): return f"{SRC}, Slide {n}"

POOL_B = [
 # ---------------- Clinical reasoning process (Slide 11) ----------------
 dict(topic="Clinical reasoning process", io="Discuss clinical principles and decision-making",
   q="What is the first step of the clinical reasoning process as presented in the lecture?",
   opts=[
     ["Gather initial patient information",
      "Correct. Step 1 is gathering initial patient information; interpretation, synthesis and hypothesis generation all follow it."],
     ["Generate hypotheses",
      "Hypothesis generation is Step 4, after information has been gathered, organised and synthesised."],
     ["Plan the diagnostic and treatment strategy",
      "Planning strategy is the final step, Step 6."],
     ["Establish a working diagnosis",
      "A working diagnosis is established at Step 5, once hypotheses have been tested."]],
   c=0, cite=c(11)),

 dict(topic="Clinical reasoning process", io="Discuss clinical principles and decision-making",
   q="In the six-step clinical reasoning process, developing the problem representation occurs at which point?",
   opts=[
     ["Before any patient information is gathered",
      "Nothing can be represented before information exists; gathering is Step 1."],
     ["When clinical information is synthesised, at Step 3",
      "Correct. Step 3 is to synthesise clinical information and develop the problem representation, between organising the information and generating hypotheses."],
     ["Only after a working diagnosis is established",
      "The working diagnosis comes at Step 5, well after the problem representation is formed."],
     ["As the final step, after the treatment plan",
      "Planning the diagnostic and treatment strategy is the last step, Step 6."]],
   c=1, cite=c(11)),

 dict(topic="Clinical reasoning process", io="Discuss clinical principles and decision-making",
   q="Which sequence correctly orders the middle of the clinical reasoning process?",
   opts=[
     ["Generate hypotheses, then organise and interpret information",
      "This inverts the order — information is organised and interpreted before hypotheses are generated."],
     ["Establish a working diagnosis, then generate hypotheses",
      "Hypotheses are generated first and then tested to arrive at a working diagnosis."],
     ["Organise and interpret information, synthesise and develop the problem representation, generate hypotheses",
      "Correct. These are Steps 2, 3 and 4 in order."],
     ["Plan treatment strategy, then test hypotheses",
      "Testing hypotheses is Step 5 and planning strategy is Step 6, so this is reversed."]],
   c=2, cite=c(11)),

 dict(topic="Clinical decision making", io="Discuss clinical principles and decision-making",
   q="Which of the following is NOT one of the questions the lecture says clinicians will need to answer?",
   opts=[
     ["What disease does the patient have?",
      "This is listed as one of the three questions."],
     ["Should testing be done?",
      "This is listed as one of the three questions."],
     ["Should this patient be treated?",
      "This is listed as one of the three questions."],
     ["Which clinician should take over the patient's care?",
      "Correct. The lecture lists three questions — what disease, should testing be done, and should this patient be treated. Transfer of care is not among them."]],
   c=3, cite=c(13)),

 dict(topic="Clinical decision making", io="Discuss clinical principles and decision-making",
   q="Clinical decision making, as framed in the lecture, covers all of the following EXCEPT which?",
   opts=[
     ["Setting the sensitivity and specificity of the tests available",
      "Correct. Sensitivity and specificity are fixed properties of a test, not decisions a clinician makes at the bedside."],
     ["What information to gather from a patient",
      "This is listed as part of clinical decision making."],
     ["What diagnostics to order",
      "This is listed as part of clinical decision making."],
     ["What management a patient needs",
      "This is listed as part of clinical decision making."]],
   c=0, cite=c(12)),

 # ---------------- Differential diagnosis and mnemonics (Slides 14-17) ----------------
 dict(topic="Differential diagnosis", io="Discuss clinical principles and decision-making",
   q="When building a differential for shortness of breath, the lecture's first recommendation is to consider what?",
   opts=[
     ["Which treatment is most likely to be tolerated",
      "Tolerance of treatment is weighed once a diagnosis is being managed, not while building the differential."],
     ["The signs and symptoms and which organ or system may be involved",
      "Correct. The lecture's worked example asks whether shortness of breath is cardiac, pulmonary or haematologic — organ and system first."],
     ["The base rate of every disease in the population",
      "Base rate awareness is listed separately under suggestions for good decision-making."],
     ["Whether the patient is stable enough for the naturalistic approach",
      "Stability drives the event-driven approach in emergencies; it is not the first step in constructing a differential."]],
   c=1, cite=c(14)),

 dict(topic="Differential diagnosis", io="Discuss clinical principles and decision-making",
   q="In the VINDICATE mnemonic, what do the two letters \"I\" stand for?",
   opts=[
     ["Idiopathic and Inherited",
      "Neither term appears in the lecture's expansion of the mnemonic."],
     ["Inflammatory and Ischaemic",
      "These are plausible clinical categories but are not the lecture's letters."],
     ["Infectious and Iatrogenic",
      "Correct. VINDICATE runs Vascular, Infectious, Neoplastic, Degenerative, Iatrogenic, Congenital, Autoimmune, Trauma, Endocrine (metabolic)."],
     ["Immunologic and Infiltrative",
      "Autoimmune appears as the letter A; neither of these is used for I."]],
   c=2, cite=c(16)),

 dict(topic="Differential diagnosis", io="Discuss clinical principles and decision-making",
   q="In VINDICATE, the letter E stands for which category?",
   opts=[
     ["Environmental",
      "Environmental exposure is not one of the lecture's categories."],
     ["Embolic",
      "Embolic disease would sit under Vascular in this scheme."],
     ["Eosinophilic",
      "This is not a category in the mnemonic."],
     ["Endocrine (metabolic)",
      "Correct. E closes the mnemonic as Endocrine, with metabolic given in parentheses."]],
   c=3, cite=c(16)),

 dict(topic="Differential diagnosis", io="Discuss clinical principles and decision-making",
   q="Applying VINDICATE to a chief complaint of confusion, which pairing matches the lecture's worked example?",
   opts=[
     ["Vascular — stroke, transient ischaemic attack, subarachnoid haemorrhage",
      "Correct. These are the vascular causes the lecture lists for confusion."],
     ["Neoplastic — meningitis and encephalitis",
      "Meningitis and encephalitis are given under Infectious; Neoplastic covers primary brain tumour or metastasis."],
     ["Congenital — Alzheimer's disease and other dementias",
      "Dementias are listed under Degenerative. Congenital is illustrated by epilepsy in the post-ictal state."],
     ["Endocrine — traumatic brain injury and subdural haematoma",
      "Those are Traumatic. Endocrine and metabolic causes given include hypoglycaemia and sodium and calcium disturbances."]],
   c=0, cite=c(17)),

 dict(topic="Differential diagnosis", io="Discuss clinical principles and decision-making",
   q="In the confusion example, which cause does the lecture place under Iatrogenic/intoxication?",
   opts=[
     ["Hypoglycaemia",
      "Hypoglycaemia is listed under Endocrine and metabolic causes."],
     ["Narcotics, and alcohol intoxication or withdrawal",
      "Correct. The lecture lists narcotics and alcohol intoxication or withdrawal as the iatrogenic and intoxication causes of confusion."],
     ["Central nervous system lupus",
      "That is given under Autoimmune, alongside neurosarcoidosis."],
     ["Primary brain tumour",
      "A primary brain tumour or metastasis is the Neoplastic entry."]],
   c=1, cite=c(17)),

 dict(topic="Differential diagnosis", io="Discuss clinical principles and decision-making",
   q="The alternative mnemonic \"Tom G. Prince, MD, Psychiatrist, General Hospital\" is used for what purpose?",
   opts=[
     ["To sequence the six steps of the clinical reasoning process",
      "The six-step process is presented separately and is not encoded in this mnemonic."],
     ["To structure the counselling of a patient about adherence",
      "Counselling is structured by the Five As and FRAMES, not by this mnemonic."],
     ["As an alternative organ-system checklist when building a differential",
      "Correct. It is offered alongside VINDICATE as a way to run through systems — toxin/trauma, oncologic, musculoskeletal, gastrointestinal, pulmonary, renal, infectious, neurologic, cardiovascular, endocrine, metabolic/genetic, dermatologic, psychiatric, genitourinary, haematologic."],
     ["To decide whether the benefit of treatment outweighs its risk",
      "The treat-versus-not-treat balance is discussed under implications for treatment."]],
   c=2, cite=c(15)),

 # ---------------- Hypothetico-deductive method (Slides 18-19) ----------------
 dict(topic="Hypothetico-deductive method", io="Discuss clinical principles and decision-making",
   q="The hypothetico-deductive method is best described as which of the following?",
   opts=[
     ["Treating the presenting signs and symptoms before a definitive diagnosis",
      "That is the naturalistic, event-driven approach used largely in emergency medicine."],
     ["Applying an if-then rule drawn from a published guideline",
      "That describes the use of clinical guidelines, a separate analytic tool."],
     ["Recognising a familiar disease pattern and acting on it quickly",
      "That is pattern recognition, described as the lowest level of decision making."],
     ["Proposing hypotheses and testing whether the data observed is consistent with them",
      "Correct. The lecture defines it as proposing hypotheses and testing whether they are acceptable by deciding if the data is consistent with what is observed."]],
   c=3, cite=c(18)),

 dict(topic="Hypothetico-deductive method", io="Discuss clinical principles and decision-making",
   q="In the hypothetico-deductive sequence, what is the purpose of the hypothesis evaluation stage?",
   opts=[
     ["Gathering data to confirm or exclude the diagnostic hypotheses",
      "Correct. Evaluation is defined as data gathering to confirm or exclude the hypotheses already generated."],
     ["Listing every potential diagnosis triggered by patient cues",
      "That is hypothesis generation, the stage before evaluation."],
     ["Adding new hypotheses prompted by the data gathered",
      "That is hypothesis refinement, which follows evaluation."],
     ["Monitoring the patient's response to management",
      "Monitoring response belongs to the final patient management stage."]],
   c=0, cite=c(19)),

 dict(topic="Hypothetico-deductive method", io="Discuss clinical principles and decision-making",
   q="Which stage of the hypothetico-deductive method involves adding new diagnostic hypotheses to the differential list?",
   opts=[
     ["Hypothesis verification",
      "Verification confirms the fit of the hypotheses with the assembled data rather than adding new ones."],
     ["Hypothesis refinement",
      "Correct. Refinement adds new diagnostic hypotheses triggered by data gathering to the differential list."],
     ["Hypothesis generation",
      "Generation produces the initial list from patient cues; adding to it after data gathering is refinement."],
     ["Patient management",
      "Management gathers data to monitor the patient's response, after the diagnostic work."]],
   c=1, cite=c(19)),

 dict(topic="Hypothetico-deductive method", io="Discuss clinical principles and decision-making",
   q="Which three cue sources feed the start of the hypothetico-deductive sequence?",
   opts=[
     ["Guidelines, literature review, and cost data",
      "These belong to evidence-based practice rather than the initial cues in this sequence."],
     ["Risk, benefit, and likelihood of success",
      "These are the considerations weighed when deciding whether to treat."],
     ["Initial history, initial examination, and screening diagnostic testing",
      "Correct. The sequence opens with initial history cues, initial examination cues and screening diagnostic testing cues."],
     ["Ask, advise, and assess",
      "These are three of the Five As used in counselling."]],
   c=2, cite=c(19)),

 dict(topic="Hypothetico-deductive method", io="Discuss clinical principles and decision-making",
   q="What does the hypothesis verification stage accomplish?",
   opts=[
     ["It generates the first list of possible diagnoses",
      "Generating the initial list is the role of hypothesis generation."],
     ["It gathers data to monitor the patient's response to treatment",
      "Monitoring response is the patient management stage that follows."],
     ["It selects which screening test to order first",
      "Screening test cues feed into the beginning of the sequence rather than being chosen at verification."],
     ["It confirms the fit of the diagnostic hypotheses with the assembled data",
      "Correct. Verification is defined as confirming the fit of the diagnostic hypotheses with the data assembled."]],
   c=3, cite=c(19)),

 # ---------------- Pattern recognition vs analytic (Slide 20) ----------------
 dict(topic="Clinical decision making", io="Discuss clinical principles and decision-making",
   q="How does the lecture characterise the use of pattern recognition in diagnosis?",
   opts=[
     ["The lowest level of decision making, easy to use, but subject to error",
      "Correct. It is easy to use but can produce errors because other possibilities are not considered."],
     ["The highest level of decision making, reserved for complex cases",
      "Complex situations call for analytic methods; pattern recognition is described as the lowest level."],
     ["A method that eliminates the need to consider other possibilities safely",
      "The stated weakness is precisely that other possibilities are not considered."],
     ["A quantitative technique requiring odds and probability",
      "Odds and probability sit under the analytic, quantitative approach rather than pattern recognition."]],
   c=0, cite=c(20)),

 dict(topic="Clinical decision making", io="Discuss clinical principles and decision-making",
   q="In more complex clinical situations, the lecture recommends analytic decision making, which may include which of the following?",
   opts=[
     ["Relying on intuitive, automatic thinking",
      "Intuitive and automatic thinking is what analytic methods are contrasted against, and suits straightforward situations."],
     ["Principles of evidence-based medicine, clinical guidelines, and quantitative techniques",
      "Correct. These are the three analytic methods the lecture lists for complex situations."],
     ["Treating empirically before any diagnosis is considered",
      "Treating before a definitive diagnosis is the naturalistic approach, used for unstable or atypical presentations."],
     ["Deferring the decision until a specialist is available",
      "Deferral to a specialist is not offered as an analytic method here."]],
   c=1, cite=c(20)),

 dict(topic="Clinical decision making", io="Discuss clinical principles and decision-making",
   q="The lecture contrasts an intuitive system of thinking with what alternative?",
   opts=[
     ["A system that avoids all use of probability",
      "The deliberate alternative explicitly makes use of logic and probabilities."],
     ["A system driven entirely by patient preference",
      "Patient preference is addressed under counselling and adherence, not as the counterpart to intuitive thinking."],
     ["A more deliberate and controlled thought process using logic and probabilities",
      "Correct. The lecture pairs quick, automatic thinking against a deliberate, controlled process that uses logic and probabilities."],
     ["A system that applies only to unstable emergency patients",
      "Unstable patients are the domain of the naturalistic approach, a separate concept."]],
   c=2, cite=c(20)),

 # ---------------- Evidence-based medicine and guidelines (Slides 21-23) ----------------
 dict(topic="Evidence-based medicine", io="Discuss clinical principles and decision-making",
   q="What is the first step in applying the principles of evidence-based medicine as presented here?",
   opts=[
     ["Evaluate the quality and validity of the evidence",
      "Appraisal comes after a question has been posed and evidence gathered."],
     ["Decide how to use the evidence to care for patients",
      "Application is the last of the steps described."],
     ["Search MEDLINE and UpToDate for a review of the literature",
      "Gathering evidence is the second step; it needs a formulated question to guide it."],
     ["Formulate a clinical question",
      "Correct. The lecture begins with formulating a clinical question, illustrated by whether a chest x-ray or chest computed tomography best evaluates a 65-year-old male smoker with chest pain and haemoptysis."]],
   c=3, cite=c(21)),

 dict(topic="Evidence-based medicine", io="Discuss clinical principles and decision-making",
   q="Which two limitations of evidence-based medicine does the lecture identify?",
   opts=[
     ["It is time consuming, and many clinical questions have no relevant studies in the literature",
      "Correct. These are the two limitations given."],
     ["It is inexpensive, and it applies only to rare diseases",
      "Cost-effectiveness is attributed to clinical guidelines, and no restriction to rare disease is stated."],
     ["It cannot be combined with clinical guidelines, and it ignores patient values",
      "Guidelines are presented as a complementary analytic tool, and neither limitation is listed."],
     ["It requires quantitative techniques, and it excludes the physical examination",
      "Quantitative techniques are a separate analytic method, and nothing here excludes the examination."]],
   c=0, cite=c(22)),

 dict(topic="Clinical guidelines", io="Discuss clinical principles and decision-making",
   q="\"If a patient is febrile and neutropenic, then use broad-spectrum antibiotics\" is given as an example of what?",
   opts=[
     ["The naturalistic, event-driven approach",
      "The naturalistic approach treats signs and symptoms before a definitive diagnosis in unstable patients, rather than applying a published rule."],
     ["A clinical guideline following an if-then rule",
      "Correct. The lecture offers this as its example of a guideline built on an if-then rule."],
     ["A quantitative technique using odds and probability",
      "No probability calculation is involved in applying this rule."],
     ["A counselling strategy for treatment adherence",
      "Counselling strategies concern helping patients adhere to plans, not selecting antibiotics."]],
   c=1, cite=c(23)),

 dict(topic="Clinical guidelines", io="Discuss clinical principles and decision-making",
   q="Which caution does the lecture attach to the use of clinical guidelines?",
   opts=[
     ["They should be avoided because they are rarely cost-effective",
      "The lecture describes guidelines as cost-effective, not the reverse."],
     ["They should be used only when evidence-based medicine has failed",
      "No such ordering is given; guidelines are one analytic option among several."],
     ["They should be applied to patients with similar characteristics to those studied",
      "Correct. Guidelines are described as straightforward and easy to use but should be applied to patients with similar characteristics."],
     ["They should replace the standard of care in complex cases",
      "Guidelines are themselves described as the standard of care, not a replacement for it."]],
   c=2, cite=c(23)),

 # ---------------- Clinical principles and good decision-making (Slides 25-26) ----------------
 dict(topic="Clinical principles", io="Discuss clinical principles and decision-making",
   q="Which treatment principle does the lecture state?",
   opts=[
     ["If what you are doing is not working, increase the dose",
      "The stated principle is to stop doing it, not to intensify it."],
     ["If you do not know what to do, choose the most aggressive option",
      "The lecture advises doing nothing when you do not know what to do."],
     ["If what you are doing is working, change to something better",
      "The principle is to keep on doing what is working."],
     ["If what you are doing is not working, stop doing it",
      "Correct. The three treatment principles are: if it is working keep doing it, if it is not working stop doing it, and if you do not know what to do, do not do anything."]],
   c=3, cite=c(25)),

 dict(topic="Clinical principles", io="Discuss clinical principles and decision-making",
   q="Among the suggestions for good decision-making, which does the lecture explicitly recommend regarding your own hypothesis?",
   opts=[
     ["Ask questions designed to disprove it rather than confirm it",
      "Correct. The lecture advises asking questions to disprove rather than confirm your current hypothesis, and actively seeking alternative diagnoses."],
     ["Ask questions designed to confirm it as quickly as possible",
      "This is the tendency the advice is written to counter."],
     ["Avoid revisiting it once a working diagnosis is set",
      "The lecture advises actively seeking alternatives, which means revisiting it."],
     ["Accept it if it matches a familiar pattern",
      "Pattern matching is described as error-prone because other possibilities go unconsidered."]],
   c=0, cite=c(26)),

 dict(topic="Clinical principles", io="Discuss clinical principles and decision-making",
   q="Which of the following is listed among the lecture's suggestions for good decision-making?",
   opts=[
     ["Decide quickly to avoid delaying care",
      "The first suggestion is the opposite — slow down."],
     ["Remember you are often wrong, and consider the immediate implications",
      "Correct. This appears alongside slowing down, weighing base rates, considering what data is truly relevant, and seeking alternatives."],
     ["Gather every available piece of data before deciding",
      "The advice is to consider what data is truly relevant, not to gather everything."],
     ["Rely on the first diagnosis that fits the presentation",
      "This is close to pattern recognition, which the lecture flags as error-prone."]],
   c=1, cite=c(26)),

 # ---------------- Naturalistic approach (Slide 24) ----------------
 dict(topic="Naturalistic approach", io="Discuss the naturalistic approach",
   q="The naturalistic (event-driven) approach is characterised by which practice?",
   opts=[
     ["Withholding all treatment until a definitive diagnosis is confirmed",
      "This is the opposite of the approach, which treats before the diagnosis is definitive."],
     ["Applying a published if-then guideline to a stable patient",
      "That describes the use of clinical guidelines rather than the event-driven approach."],
     ["Treating signs and symptoms before a definitive diagnosis is reached",
      "Correct. The lecture defines the naturalistic, event-driven approach as treating signs and symptoms before a definitive diagnosis."],
     ["Formulating a clinical question and reviewing the literature",
      "That is the evidence-based medicine sequence, which is deliberate rather than event-driven."]],
   c=2, cite=c(24)),

 dict(topic="Naturalistic approach", io="Discuss the naturalistic approach",
   q="In which setting does the lecture say the naturalistic approach is mostly used?",
   opts=[
     ["Outpatient preventive care",
      "Preventive care is where screening for occult disease belongs, not the event-driven approach."],
     ["Elective surgical planning",
      "Elective planning allows time for definitive diagnosis before intervention."],
     ["Long-term chronic disease management",
      "Chronic management follows an established diagnosis rather than preceding one."],
     ["Emergency medicine",
      "Correct. The lecture states it is used mostly in emergency medicine, for unstable patients and atypical presentations."]],
   c=3, cite=c(24)),

 dict(topic="Naturalistic approach", io="Discuss the naturalistic approach",
   q="Which patient circumstances does the lecture list as suiting the naturalistic approach?",
   opts=[
     ["Unstable patients and atypical presentations",
      "Correct. Both are listed, along with ruling out the worst-case scenario and following responses to interventions."],
     ["Stable patients with classic presentations",
      "A stable patient with a classic presentation allows the deliberate, analytic route."],
     ["Patients enrolled in a screening programme",
      "Screening identifies the likelihood of occult disease in people without symptoms."],
     ["Patients who have already completed treatment",
      "The approach concerns acute decision making, not post-treatment follow-up."]],
   c=0, cite=c(24)),

 dict(topic="Naturalistic approach", io="Discuss the naturalistic approach",
   q="Beyond treating before diagnosis, which two actions does the lecture associate with the naturalistic approach?",
   opts=[
     ["Formulating a clinical question and appraising the literature",
      "These belong to evidence-based medicine."],
     ["Ruling out the worst-case scenario and following responses to interventions",
      "Correct. Both are listed under the naturalistic, event-driven approach."],
     ["Calculating pretest probability and applying sensitivity and specificity",
      "These are the quantitative techniques used in analytic decision making."],
     ["Assessing readiness to change and arranging follow-up",
      "These belong to behaviour-change counselling and the Five As."]],
   c=1, cite=c(24)),
]
