# -*- coding: utf-8 -*-
# CMS I Lecture 6 — pool E. Herpes simplex virus, herpetic whitlow, molluscum
# contagiosum, and warts (verruca vulgaris, plana, plantaris).
#
# THE SLIDE IS AUTHORITATIVE. Jaxon, 2026-08-20: "especially Dr. Jaquith audio
# because she says words wrong all the time, so go by the powerpoints unless
# told otherwise." Every fact in this pool comes from the deck.
#
# Correct answer is ALWAYS written first (c=0); the partition script rotates.
# Distractors are written to the SAME compound shape as the answer they sit
# beside — pool D landed at 79% gameable because they were not.
SRC = "6. Fungal and Viral Skin Infections - Jaquith.pptx"
def c(n): return f"{SRC}, Slide {n}"

IOB = "Objective b — Compare and contrast the etiologies, epidemiology, risk factors, clinical manifestations, differential diagnosis, diagnostic testing (including ordering and interpretation), management (acute and chronic, including applicable rehabilitative and palliative care), appropriate referrals, patient education, and prognosis of cutaneous viral and fungal infections"
IOC = "Objective c — Identify medical care strategies for cutaneous viral and fungal infections for infant, child, adolescent, adult and elderly populations"

POOL_E = [
 dict(topic="Herpes simplex virus", io=IOB, slot="etiology",
   q="Does the site of a herpes simplex lesion tell you which viral type caused it?",
   opts=[
     ["No — either type can cause oral or genital infection, so location does not reliably determine type",
      "Correct — the deck states this directly."],
     ["Yes — type 1 causes only oral infection and type 2 causes only genital infection, without exception",
      "The deck says location does not reliably determine type."],
     ["Yes — location determines type in adults, although not in children or in immunocompromised patients",
      "No such age qualification appears in the deck."],
     ["No — but only because a single lesion may carry both viral types at the same anatomical site",
      "Coinfection of one lesion is not the reason given."]],
   c=0, cite=c(112)),

 dict(topic="Herpes simplex virus", io=IOB, slot="etiology",
   q="How is herpes simplex virus transmitted?",
   opts=[
     ["By contact with infected oral or genital secretions or lesions, and it can occur during asymptomatic shedding",
      "Correct — transmission does not require visible lesions."],
     ["Only by contact with an open lesion, so a patient with no visible lesion cannot transmit the virus",
      "Asymptomatic shedding transmits, so this is wrong."],
     ["By the airborne route from respiratory droplets, and it can occur during the prodromal phase only",
      "Herpes simplex is not spread by the airborne route."],
     ["By contaminated surfaces and shared objects, and it can occur for weeks after the lesions have healed",
      "That is the molluscum and wart route, not this one."]],
   c=0, cite=c(112)),

 dict(topic="Herpes simplex virus", io=IOB, slot="epidemiology",
   q="How does genital herpes simplex type 1 compare with genital type 2 over time?",
   opts=[
     ["Type 1 genital infection generally recurs and sheds less often than type 2 genital infection",
      "Correct — that is the comparison the deck draws."],
     ["Type 1 genital infection generally recurs and sheds more often than type 2 genital infection",
      "The deck states the opposite direction."],
     ["The two are identical in recurrence and shedding once the first episode has fully resolved",
      "The deck distinguishes them."],
     ["Type 1 genital infection never recurs at all, whereas type 2 recurs several times each year",
      "\"Less often\" is not the same as never."]],
   c=0, cite=c(112)),

 dict(topic="Herpes simplex virus", io=IOB, slot="etiology",
   q="What kind of virus is herpes simplex, and what defines its behaviour in the host?",
   opts=[
     ["A double-stranded DNA virus of the Herpesviridae family that produces latent but lifelong infection",
      "Correct — latency for life is the defining feature."],
     ["A single-stranded RNA virus of the Poxviridae family that produces latent but lifelong infection",
      "Wrong genome and wrong family; that is closer to molluscum."],
     ["A double-stranded DNA virus of the Papillomaviridae family that is cleared once lesions resolve",
      "That is the wart family, and herpes is not cleared."],
     ["A single-stranded DNA virus of the Herpesviridae family that is confined entirely to the epidermis",
      "Confinement to the epidermis describes warts."]],
   c=0, cite=c(116)),

 dict(topic="Herpes simplex virus", io=IOB, slot="manifestation",
   q="What does neurovirulence mean for herpes simplex virus?",
   opts=[
     ["It invades and replicates in the nervous system, where it establishes latency and later reactivates",
      "Correct — that is the deck's definition."],
     ["It invades and replicates in the epidermal keratinocytes, where it remains without ever spreading",
      "Keratinocyte confinement describes human papillomavirus."],
     ["It invades and destroys peripheral nerves permanently, so sensation is lost in the affected area",
      "The deck does not describe permanent nerve destruction."],
     ["It invades the bone marrow and lymphoid tissue, where it persists until immunity later declines",
      "Latency is neural, not marrow-based."]],
   c=0, cite=c(116)),

 dict(topic="Herpes simplex virus", io=IOB, slot="manifestation",
   q="How does a first episode of herpes simplex differ from a recurrent episode?",
   opts=[
     ["The first episode has more prominent symptoms of longer duration; recurrences are milder and shorter",
      "Correct — that is the classification the deck uses."],
     ["The first episode is milder and shorter; recurrences become progressively more prominent over time",
      "The deck describes the reverse pattern."],
     ["The first episode and recurrent episodes are indistinguishable in severity and in their duration",
      "The deck explicitly separates them."],
     ["The first episode is always asymptomatic; only recurrent episodes produce any visible skin lesions",
      "First episodes are the more symptomatic ones."]],
   c=0, cite=c(117)),

 dict(topic="Herpes simplex virus", io=IOB, slot="risk factors",
   q="Which stimuli are associated with reactivation of latent herpes simplex virus?",
   opts=[
     ["Stress, illness, menstruation, and exposure to ultraviolet light",
      "Correct — the deck lists these four."],
     ["Cold weather, dehydration, high altitude, and vigorous exercise",
      "None of these are the stimuli listed."],
     ["Antibiotic use, dietary change, dental work, and recent travel",
      "These are not the reactivation triggers named."],
     ["Occlusive clothing, excessive sweating, and communal shower use",
      "Those are tinea risk factors from earlier in the deck."]],
   c=0, cite=c(117)),

 dict(topic="Herpes simplex virus", io=IOB, slot="manifestation",
   q="What symptoms occur before herpes simplex lesions appear?",
   opts=[
     ["Tenderness, pain, mild paresthesias or burning, and some patients have no prodrome at all",
      "Correct — the deck notes the prodrome may be absent."],
     ["Painless swelling and pruritus in every patient, always beginning about a week before lesions",
      "The prodrome is described as painful, and it is not universal."],
     ["High fever and a generalised rash in every patient, always beginning the day before lesions",
      "A generalised rash is not the herpes simplex prodrome."],
     ["Loss of sensation over the affected area in every patient, always preceding lesions by hours",
      "Paresthesia, not sensory loss, is what the deck describes."]],
   c=0, cite=c(118)),

 dict(topic="Herpes simplex virus", io=IOB, slot="manifestation",
   q="Which prodromal symptoms are described as characteristic of herpes simplex?",
   opts=[
     ["Localized pain, tender lymphadenopathy, headache, generalized aching, and fever",
      "Correct — that is the deck's list."],
     ["Localized numbness, painless lymphadenopathy, dizziness, joint swelling, and chills",
      "Each element differs from the list the deck gives."],
     ["Diffuse pruritus, hepatosplenomegaly, photophobia, muscle weakness, and night sweats",
      "None of these are the characteristic prodrome."],
     ["Sore throat, nasal congestion, cough, conjunctival injection, and loss of taste",
      "That is an upper respiratory pattern, not this prodrome."]],
   c=0, cite=c(118)),

 dict(topic="Herpes simplex virus", io=IOB, slot="manifestation",
   q="What is seen on examination in herpes simplex, and how do the lesions evolve?",
   opts=[
     ["Grouped vesicles on an erythematous base that break down to form a shallow painful ulcer",
      "Correct — grouped vesicles then shallow ulceration."],
     ["Scattered pustules on a normal base that break down to form a deep necrotizing ulcer",
      "Necrotizing ulceration describes chancroid in the differential."],
     ["Grouped papules on an erythematous base that enlarge to form a firm painless nodule",
      "A painless lesion points away from herpes simplex."],
     ["Umbilicated papules on a normal base that soften to form a shallow crusted erosion",
      "Umbilication describes molluscum contagiosum."]],
   c=0, cite=c(119)),

 dict(topic="Herpes simplex virus", io=IOB, slot="prognosis",
   q="How long do herpes simplex lesions last, and do they scar?",
   opts=[
     ["They may last about two weeks and heal without scarring",
      "Correct — the deck says lesions heal without scarring."],
     ["They may last about two days and heal with permanent scarring",
      "Both the duration and the scarring are wrong."],
     ["They may last several months and heal with atrophic scarring",
      "The deck gives roughly two weeks, without scarring."],
     ["They may last about two weeks and always heal with keloids",
      "The deck states healing occurs without scarring."]],
   c=0, cite=c(119)),

 dict(topic="Herpes simplex virus", io=IOB, slot="manifestation",
   q="Which symptom does the deck specifically associate with genital herpes simplex lesions in women?",
   opts=[
     ["Dysuria",
      "Correct — the deck names dysuria in women."],
     ["Haematuria",
      "The deck names dysuria, not blood in the urine."],
     ["Urinary frequency",
      "Frequency is not the symptom named."],
     ["Urinary incontinence",
      "Incontinence is not mentioned in the deck."]],
   c=0, cite=c(119)),

 dict(topic="Herpes simplex virus", io=IOB, slot="differential",
   q="Which sexually transmitted infection in the herpes simplex differential causes painful necrotizing ulcers with inguinal lymphadenopathy?",
   opts=[
     ["Chancroid, a bacterial infection caused by Haemophilus ducreyi",
      "Correct — painful ulcers with inguinal nodes."],
     ["Syphilis, a bacterial infection caused by Treponema pallidum",
      "Syphilitic ulcers are usually painless."],
     ["Candidiasis, a fungal infection caused by Candida albicans",
      "Candidiasis is in the differential but does not ulcerate this way."],
     ["Molluscum contagiosum, a viral infection caused by a poxvirus",
      "Molluscum produces umbilicated papules, not ulcers."]],
   c=0, cite=c(121)),

 dict(topic="Herpes simplex virus", io=IOB, slot="differential",
   q="How does the syphilitic lesion in the herpes simplex differential begin and behave?",
   opts=[
     ["As solitary raised papules that erode, and it is usually painless",
      "Correct — painlessness is the discriminator here."],
     ["As solitary raised papules that erode, and it is usually exquisitely painful",
      "Pain would point towards chancroid or herpes simplex."],
     ["As grouped vesicles that rupture, and it is usually painless throughout",
      "Grouped vesicles describe herpes simplex itself."],
     ["As multiple umbilicated papules that persist, and it is usually painless",
      "Umbilication describes molluscum, not syphilis."]],
   c=0, cite=c(121)),

 dict(topic="Herpes simplex virus", io=IOB, slot="gold standard",
   q="What is the preferred diagnostic test for herpes simplex, and what should be sampled?",
   opts=[
     ["Type-specific nucleic acid amplification testing, from a fresh vesicle, ulcer base, or crust",
      "Correct — the deck names this as preferred."],
     ["Viral culture, from a fresh vesicle, ulcer base, or crust, because it is the most sensitive test",
      "Culture is less sensitive, not more."],
     ["Type-specific serology, from a venous blood sample taken during the acute clinical episode",
      "Serology has selected uses but is not the preferred test."],
     ["Tzanck smear, from scrapings taken from the base of an unroofed vesicle at the bedside",
      "The deck names amplification testing as preferred."]],
   c=0, cite=c(122)),

 dict(topic="Herpes simplex virus", io=IOB, slot="test finding",
   q="What is the limitation of viral culture for herpes simplex?",
   opts=[
     ["It is less sensitive, especially in healing or recurrent lesions, and a negative result does not exclude infection",
      "Correct — a negative culture cannot rule out herpes."],
     ["It is highly sensitive but very slow, so a negative result reliably excludes infection once it returns",
      "Culture is less sensitive; a negative does not exclude."],
     ["It cannot distinguish type 1 from type 2, although its sensitivity is equal to amplification testing",
      "The named limitation is sensitivity, not typing."],
     ["It is only valid in the first episode, and it performs better than amplification in recurrent lesions",
      "Culture performs worse in recurrent lesions."]],
   c=0, cite=c(122)),

 dict(topic="Herpes simplex virus", io=IOB, slot="initial test",
   q="What does the deck say about routine herpes simplex serologic screening of asymptomatic adults?",
   opts=[
     ["It is not recommended, and low-positive results may be false positives",
      "Correct — the deck advises against routine screening."],
     ["It is recommended annually for all adults, and low-positive results are reliable",
      "Routine screening of asymptomatic adults is not recommended."],
     ["It is recommended once in every adult, and low-positive results should be repeated",
      "The deck does not recommend routine screening at all."],
     ["It is not recommended, because serology cannot distinguish type 1 from type 2",
      "Serology is type-specific; the issue is false positives."]],
   c=0, cite=c(122)),

 dict(topic="Herpes simplex virus", io=IOB, slot="test finding",
   q="A patient with an older, healing genital ulcer has a negative herpes simplex swab. What does that mean?",
   opts=[
     ["It does not exclude infection, because viral shedding is intermittent",
      "Correct — intermittent shedding limits a negative result."],
     ["It excludes infection, because the swab is reliable at any lesion age",
      "A negative swab from an older lesion cannot exclude."],
     ["It excludes infection only if serology is also negative on the same day",
      "The deck does not offer this combination rule."],
     ["It does not exclude infection, because the swab cannot detect type 2",
      "Amplification testing detects and types both."]],
   c=0, cite=c(123)),

 dict(topic="Herpes simplex virus", io=IOB, slot="avoid",
   q="Which herpes simplex test does the deck tell you not to use?",
   opts=[
     ["Immunoglobulin M serology",
      "Correct — the deck says do not use it."],
     ["Immunoglobulin G serology",
      "Type-specific IgG serology has selected uses."],
     ["Lesion amplification testing",
      "That is the preferred test."],
     ["Viral culture",
      "Culture is less sensitive but is not forbidden."]],
   c=0, cite=c(123)),

 dict(topic="Herpes simplex virus", io=IOB, slot="test finding",
   q="What should be done with a low-positive herpes simplex type 2 serology result?",
   opts=[
     ["Confirm it with a second method when one is available",
      "Correct — low-positive results may be false positives."],
     ["Accept it as diagnostic and begin suppressive therapy",
      "A low-positive result needs confirmation first."],
     ["Discard it and repeat the identical assay in six months",
      "The deck advises a second method, not the same one."],
     ["Confirm it with an immunoglobulin M level on the same sample",
      "The deck says not to use IgM."]],
   c=0, cite=c(123)),

 dict(topic="Herpes simplex virus", io=IOB, slot="differential",
   q="Beyond herpes simplex, what else should prompt evaluation in a patient with a genital ulcer?",
   opts=[
     ["Other causes including syphilis, evaluated according to the patient's risk",
      "Correct — the deck names syphilis and risk-based testing."],
     ["Other causes including tinea cruris, evaluated in every patient regardless of risk",
      "Tinea cruris does not ulcerate; it is not the named cause."],
     ["Other causes including onychomycosis, evaluated according to the patient's age",
      "Onychomycosis is a nail disease and is unrelated here."],
     ["No other causes, because a genital ulcer is diagnostic of herpes simplex",
      "The deck explicitly asks for broader evaluation."]],
   c=0, cite=c(123)),

 dict(topic="Herpes simplex virus", io=IOB, slot="first-line",
   q="How should a first clinical episode of herpes simplex be treated?",
   opts=[
     ["Treat every first clinical episode with oral acyclovir, valacyclovir, or famciclovir",
      "Correct — every first episode is treated orally."],
     ["Treat only severe first episodes, with oral acyclovir, valacyclovir, or famciclovir",
      "The deck says treat every first clinical episode."],
     ["Treat every first clinical episode with a topical antiviral applied to each lesion",
      "Topical antivirals provide minimal benefit."],
     ["Treat every first clinical episode with an oral antibiotic and supportive care",
      "This is a viral infection; antibiotics have no role here."]],
   c=0, cite=c(124)),

 dict(topic="Herpes simplex virus", io=IOB, slot="agent/regimen",
   q="What are the two management options for recurrent genital herpes simplex?",
   opts=[
     ["Patient-initiated episodic therapy, or daily suppressive therapy",
      "Correct — those are the two strategies given."],
     ["Clinician-administered intravenous therapy, or weekly oral therapy",
      "Neither of these appears in the deck."],
     ["Patient-initiated topical therapy, or intermittent topical suppression",
      "Topical antivirals provide minimal benefit."],
     ["Daily antibiotic prophylaxis, or immunoglobulin given after exposure",
      "Neither is used for recurrent genital herpes simplex."]],
   c=0, cite=c(124)),

 dict(topic="Herpes simplex virus", io=IOB, slot="education",
   q="What does the deck say about suppressive valacyclovir and condoms for transmission?",
   opts=[
     ["Suppressive valacyclovir lowers type 2 transmission, and condoms reduce but do not eliminate risk",
      "Correct — risk is reduced, never abolished."],
     ["Suppressive valacyclovir prevents type 2 transmission entirely, and condoms eliminate residual risk",
      "Neither eliminates transmission risk."],
     ["Suppressive valacyclovir has no effect on transmission, and condoms are the only useful measure",
      "Suppressive therapy does lower transmission."],
     ["Suppressive valacyclovir lowers type 1 transmission only, and condoms make no measurable difference",
      "The deck names type 2, and condoms do reduce risk."]],
   c=0, cite=c(124)),

 dict(topic="Herpes simplex virus", io=IOB, slot="education",
   q="When should a patient with herpes simplex avoid sexual or direct lesion contact?",
   opts=[
     ["During the prodrome and while lesions are active",
      "Correct — the prodrome counts, not just visible lesions."],
     ["Only while lesions are visibly active, never during the prodrome",
      "The deck includes the prodrome."],
     ["Only during the first episode, never during recurrences",
      "The advice is not limited to the first episode."],
     ["Only for the first 48 hours after lesions appear",
      "No such time limit is given."]],
   c=0, cite=c(124)),

 dict(topic="Herpetic whitlow", io=IOB, slot="etiology",
   q="What is herpetic whitlow, and how is it usually acquired?",
   opts=[
     ["A painful herpes simplex infection of the distal finger, often after inoculation through broken skin",
      "Correct — inoculation through broken skin."],
     ["A painful bacterial infection of the distal finger, often after inoculation through broken skin",
      "Whitlow is viral; a bacterial felon is in its differential."],
     ["A painless fungal infection of the proximal nail fold, acquired from prolonged water exposure",
      "That describes chronic paronychia, not whitlow."],
     ["A painful poxvirus infection of the distal finger, acquired by autoinoculation from genital lesions",
      "Autoinoculation with a poxvirus describes molluscum."]],
   c=0, cite=c(126)),

 dict(topic="Herpetic whitlow", io=IOB, slot="manifestation",
   q="How does herpetic whitlow present?",
   opts=[
     ["Prodromal burning or tingling, then grouped vesicles on an erythematous swollen digit, sometimes with fever or lymphangitis",
      "Correct — that is the sequence the deck gives."],
     ["Painless swelling of the whole hand, then a single large bulla on the palm, sometimes with joint stiffness",
      "Whitlow is painful and affects the distal finger."],
     ["Sudden nail plate separation, then thickening and yellow discolouration, sometimes with subungual debris",
      "That is onychomycosis, described earlier in the deck."],
     ["A slowly enlarging painless nodule on the finger, then central umbilication, sometimes with satellite lesions",
      "Umbilicated papules describe molluscum contagiosum."]],
   c=0, cite=c(126)),

 dict(topic="Herpetic whitlow", io=IOB, slot="differential",
   q="What does herpetic whitlow mimic?",
   opts=[
     ["Bacterial felon or paronychia, contact dermatitis, and blistering dactylitis",
      "Correct — those are the three named mimics."],
     ["Squamous cell carcinoma, seborrheic keratosis, and molluscum contagiosum",
      "Those are the wart differential, not whitlow's."],
     ["Basal cell carcinoma, sebaceous hyperplasia, and condyloma acuminatum",
      "Those belong to the molluscum differential."],
     ["Chancroid, syphilis, trauma, and candidiasis",
      "That is the genital herpes simplex differential."]],
   c=0, cite=c(126)),

 dict(topic="Herpetic whitlow", io=IOB, slot="gold standard",
   q="How should an atypical case of herpetic whitlow be confirmed?",
   opts=[
     ["Herpes simplex amplification testing from a fresh vesicle or the lesion base",
      "Correct — sample a fresh vesicle or the base."],
     ["Bacterial culture of pus obtained by incising the swollen fingertip",
      "The deck forbids incision and drainage here."],
     ["Potassium hydroxide preparation of scrapings from the nail plate",
      "That is the test for a dermatophyte, not for whitlow."],
     ["Herpes simplex immunoglobulin M serology drawn during the acute phase",
      "The deck says not to use immunoglobulin M."]],
   c=0, cite=c(126)),

 dict(topic="Herpetic whitlow", io=IOB, slot="avoid",
   q="What must NOT be done for herpetic whitlow, and why?",
   opts=[
     ["Do not incise and drain it, because that does not treat the virus and can delay healing",
      "Correct — incision is explicitly contraindicated."],
     ["Do not give any oral antiviral, because early treatment prolongs the course of the illness",
      "Early oral antivirals may shorten symptoms."],
     ["Do not cover the lesions, because occlusion traps the virus and worsens the infection",
      "The deck says to cover the lesions."],
     ["Do not use hand hygiene, because repeated washing spreads virus to the other digits",
      "Hand hygiene is advised, not avoided."]],
   c=0, cite=c(128)),

 dict(topic="Herpetic whitlow", io=IOB, slot="education",
   q="What infection-control advice is given for herpetic whitlow?",
   opts=[
     ["Cover the lesions, use hand hygiene, and avoid contact with mucosa or broken skin until healed",
      "Correct — those are the three measures."],
     ["Leave the lesions open to air, use hand hygiene, and avoid contact with mucosa for 48 hours",
      "The deck says to cover the lesions, and until healed."],
     ["Cover the lesions, avoid hand hygiene, and avoid contact with intact skin until fully healed",
      "Hand hygiene is part of the advice."],
     ["Cover the lesions, use hand hygiene, and isolate the patient with airborne precautions",
      "Airborne precautions are not indicated for whitlow."]],
   c=0, cite=c(128)),

 dict(topic="Herpetic whitlow", io=IOB, slot="first-line",
   q="What is the role of oral antivirals and antibiotics in herpetic whitlow?",
   opts=[
     ["Early oral antivirals may shorten symptoms; treat bacterial superinfection only when it is present",
      "Correct — antibiotics are not routine."],
     ["Early oral antivirals may shorten symptoms; give an antibiotic routinely to every patient as well",
      "Antibiotics are only for actual superinfection."],
     ["Oral antivirals have no role at any stage; treat every case with an antibiotic from the outset",
      "Antivirals may shorten symptoms."],
     ["Oral antivirals are given only after 72 hours; treat bacterial superinfection in every patient",
      "Neither half matches the deck."]],
   c=0, cite=c(128)),

 dict(topic="Herpetic whitlow", io=IOB, slot="escalation",
   q="What should be considered for a patient with frequently recurring herpetic whitlow?",
   opts=[
     ["Suppressive therapy",
      "Correct — the deck names suppression for frequent recurrence."],
     ["Surgical nail removal",
      "Not mentioned, and incision is contraindicated."],
     ["Long-term antibiotics",
      "Antibiotics treat superinfection only."],
     ["Topical corticosteroid",
      "Not a treatment named for whitlow."]],
   c=0, cite=c(128)),

 dict(topic="Molluscum contagiosum", io=IOB, slot="etiology",
   q="What causes molluscum contagiosum, and what does it produce?",
   opts=[
     ["A benign poxvirus infection producing smooth, dome-shaped, centrally umbilicated papules",
      "Correct — a poxvirus with umbilicated papules."],
     ["A benign papillomavirus infection producing rough, grayish, elevated round papules",
      "That describes verruca vulgaris."],
     ["A benign herpesvirus infection producing grouped vesicles on an erythematous base",
      "Grouped vesicles describe herpes simplex."],
     ["A benign dermatophyte infection producing an annular scaly plaque with central clearing",
      "That describes tinea corporis."]],
   c=0, cite=c(130)),

 dict(topic="Molluscum contagiosum", io=IOB, slot="etiology",
   q="How does molluscum contagiosum spread?",
   opts=[
     ["By direct skin contact, shared contaminated objects, and autoinoculation, with sexual contact common in adults with genital lesions",
      "Correct — all three routes, plus sexual contact in adults."],
     ["By the airborne route, by respiratory droplets, and by autoinoculation, with sexual contact common in adults with genital lesions",
      "Molluscum is not airborne."],
     ["By reactivation of latent virus in a sensory ganglion, with ultraviolet light a common trigger",
      "Latency and reactivation describe the herpesviruses."],
     ["By contact with infected soil and animal fur, with occupational exposure common in adults",
      "Those routes are not described for molluscum."]],
   c=0, cite=c(130)),

 dict(topic="Molluscum contagiosum", io=IOB, slot="prognosis",
   q="What is the natural history of molluscum contagiosum in an immunocompetent patient?",
   opts=[
     ["Most clear spontaneously, although resolution may take months to several years",
      "Correct — spontaneous but often slow."],
     ["Most clear spontaneously, always within two to three weeks of first appearing",
      "Resolution may take months to years."],
     ["Few clear spontaneously, so nearly every patient needs destructive treatment",
      "Most do clear on their own."],
     ["None clear spontaneously, because the virus establishes lifelong latency in the skin",
      "Latency belongs to the herpesviruses."]],
   c=0, cite=c(130)),

 dict(topic="Molluscum contagiosum", io=IOC, slot="risk factors",
   q="How does molluscum contagiosum behave in an immunosuppressed patient?",
   opts=[
     ["Lesions are more numerous, larger, or atypical",
      "Correct — immunosuppression amplifies the disease."],
     ["Lesions are fewer, smaller, and resolve more quickly",
      "The deck describes the opposite."],
     ["Lesions are unchanged, because the virus is not affected by immunity",
      "Immune status clearly affects the presentation."],
     ["Lesions become painful and ulcerate in every case",
      "Molluscum lesions are typically asymptomatic."]],
   c=0, cite=c(130)),

 dict(topic="Molluscum contagiosum", io=IOC, slot="referral",
   q="A child has genital molluscum lesions. What does the deck say about interpreting this?",
   opts=[
     ["It requires context-sensitive assessment, because location alone does not prove abuse",
      "Correct — location alone is not proof."],
     ["It confirms sexual abuse, so a report should be filed on the location alone",
      "The deck warns specifically against this inference."],
     ["It excludes sexual abuse, because genital lesions in children are always autoinoculated",
      "The deck does not exclude it either."],
     ["It requires no assessment at all, because genital lesions are expected in children",
      "The deck calls for careful assessment."]],
   c=0, cite=c(133)),

 dict(topic="Molluscum contagiosum", io=IOB, slot="referral",
   q="What should extensive or giant facial molluscum lesions prompt?",
   opts=[
     ["Evaluation for immunosuppression, including human immunodeficiency virus when appropriate",
      "Correct — extensive disease raises this question."],
     ["Immediate surgical excision of every lesion under general anaesthesia, whatever the patient's age",
      "Not the response the deck describes."],
     ["Reassurance alone, because facial lesions always resolve within weeks",
      "Extensive facial disease warrants evaluation."],
     ["Evaluation for an underlying dermatophyte infection of the face",
      "The concern is immunosuppression, not fungus."]],
   c=0, cite=c(133)),

 dict(topic="Molluscum contagiosum", io=IOB, slot="manifestation",
   q="Describe the individual molluscum lesion and its typical size.",
   opts=[
     ["Discrete, smooth-surfaced, firm, flesh-coloured, dome-shaped pearly papules averaging 3 to 5 millimetres",
      "Correct — with characteristic central umbilication."],
     ["Discrete, rough-surfaced, soft, grayish, flat-topped papules averaging 10 to 15 millimetres",
      "Rough and grayish describes a common wart."],
     ["Confluent, scaly, erythematous plaques with an advancing border averaging 3 to 5 centimetres",
      "That is a dermatophyte plaque."],
     ["Grouped, fluid-filled vesicles on an erythematous base averaging 1 to 2 millimetres",
      "Grouped vesicles describe herpes simplex."]],
   c=0, cite=c(134)),

 dict(topic="Molluscum contagiosum", io=IOB, slot="manifestation",
   q="Which single feature is characteristic of the molluscum lesion?",
   opts=[
     ["Central umbilication",
      "Correct — the deck calls it characteristic."],
     ["An advancing scaly border",
      "That is the dermatophyte pattern."],
     ["A thrombosed capillary dot",
      "Those are seen in common warts."],
     ["A shallow painful ulcer",
      "Ulceration describes herpes simplex."]],
   c=0, cite=c(134)),

 dict(topic="Molluscum contagiosum", io=IOB, slot="differential",
   q="What is the differential diagnosis for molluscum contagiosum?",
   opts=[
     ["Basal cell carcinoma, sebaceous hyperplasia, and condyloma acuminatum",
      "Correct — the three named in the deck."],
     ["Squamous cell carcinoma, seborrheic keratosis, and verruca vulgaris",
      "That is the wart differential."],
     ["Chancroid, syphilis, trauma, and candidiasis",
      "That is the genital herpes simplex differential."],
     ["Bacterial felon, contact dermatitis, and blistering dactylitis",
      "Those mimic herpetic whitlow."]],
   c=0, cite=c(135)),

 dict(topic="Molluscum contagiosum", io=IOB, slot="initial test",
   q="How is molluscum contagiosum diagnosed?",
   opts=[
     ["Clinically, with biopsy reserved for uncertain cases",
      "Correct — clinical, and biopsy only if uncertain."],
     ["By viral culture of material expressed from a lesion",
      "Culture is not part of this workup."],
     ["By potassium hydroxide preparation of a lesion scraping",
      "That test is for dermatophytes and yeast."],
     ["By serology for poxvirus antibodies in every patient",
      "Serology is not used for molluscum."]],
   c=0, cite=c(135)),

 dict(topic="Molluscum contagiosum", io=IOB, slot="first-line",
   q="Why is observation appropriate for many patients with molluscum contagiosum?",
   opts=[
     ["Because procedures may blister, pigment, or scar",
      "Correct — the harm of treating can exceed the benefit."],
     ["Because no treatment has ever been approved for it",
      "Two agents are approved."],
     ["Because treatment reliably makes the lesions spread",
      "That is not the reason given."],
     ["Because lesions are painful and treatment worsens pain",
      "Molluscum lesions are typically asymptomatic."]],
   c=0, cite=c(136)),

 dict(topic="Molluscum contagiosum", io=IOC, slot="agent/regimen",
   q="Which approved molluscum treatment is applied at home once daily, and from what age?",
   opts=[
     ["Berdazimer 10.3% gel, from age one year",
      "Correct — the at-home option in the deck."],
     ["Cantharidin 0.7%, from age one year",
      "Cantharidin is clinician-applied, from age two."],
     ["Berdazimer 10.3% gel, from age twelve years",
      "The age given is one year."],
     ["Salicylic acid 40%, from age two years",
      "That is a wart treatment, not a molluscum one."]],
   c=0, cite=c(136)),

 dict(topic="Molluscum contagiosum", io=IOC, slot="agent/regimen",
   q="Which approved molluscum treatment is applied by a clinician, and from what age?",
   opts=[
     ["Cantharidin 0.7%, from age two years",
      "Correct — the clinician-applied option."],
     ["Berdazimer 10.3% gel, from age two years",
      "Berdazimer is applied at home, from age one."],
     ["Cantharidin 0.7%, from age twelve years",
      "The age given is two years."],
     ["Cryotherapy every two to three weeks, from age two years",
      "Cryotherapy is listed under other options."]],
   c=0, cite=c(136)),

 dict(topic="Molluscum contagiosum", io=IOB, slot="escalation",
   q="Which other molluscum options does the deck list, and which is off label?",
   opts=[
     ["Curettage or cryotherapy, with topical retinoids off label",
      "Correct — retinoids are the off-label option."],
     ["Curettage or cryotherapy, with cantharidin off label",
      "Cantharidin is approved, not off label."],
     ["Salicylic acid or cryotherapy, with curettage off label",
      "Salicylic acid is a wart treatment here."],
     ["Oral antivirals or curettage, with cryotherapy off label",
      "Oral antivirals are not used for molluscum."]],
   c=0, cite=c(136)),

 dict(topic="Warts", io=IOB, slot="etiology",
   q="What causes warts, and which cells does the virus infect?",
   opts=[
     ["Human papillomavirus, which infects keratinocytes and remains confined to the epidermis",
      "Correct — a benign proliferation confined to the epidermis."],
     ["Human papillomavirus, which infects dermal fibroblasts and extends deep into the dermis",
      "Warts are confined to the epidermis."],
     ["A poxvirus, which infects keratinocytes and remains confined to the epidermis",
      "A poxvirus causes molluscum contagiosum."],
     ["A herpesvirus, which infects sensory ganglia and reaches the skin along a nerve",
      "That describes the varicella-zoster pattern."]],
   c=0, cite=c(138)),

 dict(topic="Warts", io=IOB, slot="etiology",
   q="How are warts transmitted?",
   opts=[
     ["By skin-to-skin contact, autoinoculation, and contaminated surfaces",
      "Correct — the three routes named."],
     ["By respiratory droplets, autoinoculation, and contaminated surfaces",
      "Warts are not spread by droplets."],
     ["By reactivation of latent virus after stress or ultraviolet light",
      "Latency and reactivation describe herpes simplex."],
     ["By contact with infected oral or genital secretions only",
      "That is the herpes simplex route."]],
   c=0, cite=c(138)),

 dict(topic="Warts", io=IOB, slot="manifestation",
   q="Which variations of verruca does the deck list?",
   opts=[
     ["Verruca vulgaris, verruca plana, verruca plantaris, mosaic warts, and genital warts",
      "Correct — five variants."],
     ["Verruca vulgaris, verruca plana, verruca plantaris, and molluscum contagiosum",
      "Molluscum is a poxvirus disease, not a wart."],
     ["Verruca vulgaris, seborrheic keratosis, and squamous cell carcinoma",
      "Those two are in the wart differential, not variants."],
     ["Verruca vulgaris, verruca plantaris, and condyloma acuminatum only",
      "The deck's list is longer than this."]],
   c=0, cite=c(138)),

 dict(topic="Warts", io=IOB, slot="manifestation",
   q="What does the underside of a wart look like, and how deep does it actually go?",
   opts=[
     ["Round and smooth with no roots; it is confined to the epidermis but displaces the dermis",
      "Correct — it only gives the impression of depth."],
     ["Irregular with fine root-like projections; it extends genuinely into the deep dermis",
      "Warts have no roots."],
     ["Round and smooth with no roots; it extends genuinely into the subcutaneous fat",
      "It is confined to the epidermis."],
     ["Irregular with no roots; it is confined to the dermis but never involves the epidermis",
      "The epidermis is exactly where a wart lives."]],
   c=0, cite=c(139)),

 dict(topic="Warts", io=IOC, slot="epidemiology",
   q="At what ages does verruca vulgaris occur most often, and what is its natural history?",
   opts=[
     ["Most often between 5 and 20 years, with spontaneous resolution",
      "Correct — common warts usually resolve on their own."],
     ["Most often between 40 and 60 years, with spontaneous resolution",
      "The age range given is 5 to 20."],
     ["Most often between 5 and 20 years, with progression to carcinoma",
      "Common warts resolve; they do not become cancer here."],
     ["Most often after the age of 65, with lifelong persistence once acquired",
      "Neither the age nor the course matches."]],
   c=0, cite=c(140)),

 dict(topic="Warts", io=IOB, slot="manifestation",
   q="Where do common warts usually occur, and who gets periungual, lip and tongue warts?",
   opts=[
     ["Usually on the hands, favouring fingers and palms; nail biters get the periungual, lip and tongue lesions",
      "Correct — nail biting explains that distribution."],
     ["Usually on the soles, favouring weight-bearing surfaces; nail biters get the periungual lesions",
      "Weight-bearing soles describe plantar warts."],
     ["Usually on the face and shins, favouring the forehead; shaving spreads them to the lips and tongue",
      "That distribution describes flat warts."],
     ["Usually on the trunk, favouring the axillae and groin; sexual contact spreads them to the lips",
      "That distribution is not the one given."]],
   c=0, cite=c(140)),

 dict(topic="Warts", io=IOB, slot="test finding",
   q="What are the tiny red or black dots seen in a common wart, and what makes them clearer?",
   opts=[
     ["Thrombosed dilated capillaries, made more prominent by trimming the surface",
      "Correct — trimming brings the capillaries out."],
     ["Impacted keratin plugs, made more prominent by trimming the surface",
      "The dots are vascular, not keratin."],
     ["Melanin deposits, made more prominent by applying potassium hydroxide",
      "They are thrombosed capillaries."],
     ["Fungal spores, made more prominent by examining under ultraviolet light",
      "Warts are viral, and no such test is described."]],
   c=0, cite=c(142)),

 dict(topic="Warts", io=IOB, slot="manifestation",
   q="How do flat warts appear, and where are they common?",
   opts=[
     ["Multiple smooth, slightly elevated, flat-topped, skin-coloured to light-brown papules; face, forehead, dorsal hands, and shins",
      "Correct — that is the flat wart distribution."],
     ["Single rough, markedly elevated, dome-shaped, grayish to brown papules; the palms, the soles, and the periungual skin",
      "That describes common warts."],
     ["Multiple umbilicated, pearly, dome-shaped, flesh-coloured papules; trunk, axillae, and groin",
      "Umbilication describes molluscum contagiosum."],
     ["Multiple smooth, flat-topped, deeply pigmented plaques; weight-bearing surfaces of the feet only",
      "Weight-bearing feet describe plantar warts."]],
   c=0, cite=c(143)),

 dict(topic="Warts", io=IOB, slot="education",
   q="What spreads flat warts, and what does the deck advise about treating them?",
   opts=[
     ["Shaving spreads them by autoinoculation; observation is reasonable because spontaneous resolution is common",
      "Correct — shaving spreads, and watchful waiting is reasonable."],
     ["Shaving spreads them by autoinoculation; every lesion should be destroyed at first presentation",
      "Observation is explicitly reasonable."],
     ["Sun exposure spreads them by reactivation; observation is reasonable because they resolve quickly",
      "Reactivation is not the mechanism for warts."],
     ["Communal showers spread them by direct contact; every lesion needs salicylic acid immediately",
      "Neither half matches the deck for flat warts."]],
   c=0, cite=c(143)),

 dict(topic="Warts", io=IOB, slot="avoid",
   q="What must be balanced when choosing treatment for flat warts?",
   opts=[
     ["The benefit of treatment against the risk of dyspigmentation and scarring",
      "Correct — the deck asks for this balance explicitly."],
     ["The benefit of treatment against the risk of malignant transformation",
      "Malignant change is not the risk named here."],
     ["The cost of treatment against the risk of transmitting the virus",
      "Cost is not the trade-off given."],
     ["The speed of treatment against the risk of systemic absorption",
      "Systemic absorption is not raised in the deck."]],
   c=0, cite=c(143)),

 dict(topic="Warts", io=IOB, slot="manifestation",
   q="Where do plantar warts occur, and what do they form when they cluster?",
   opts=[
     ["On weight-bearing surfaces, and clustered together they form a mosaic wart",
      "Correct — mosaic warts are clustered plantar warts."],
     ["On the dorsal foot, and clustered together they form a giant condyloma",
      "Plantar warts sit on weight-bearing surfaces."],
     ["On weight-bearing surfaces, and clustered together they form a single deep abscess",
      "Clustering produces a mosaic wart, not an abscess."],
     ["On the fingers and palms, and clustered together they form a periungual band",
      "That distribution describes common warts."]],
   c=0, cite=c(145)),

 dict(topic="Warts", io=IOB, slot="first-line",
   q="When do plantar warts require therapy?",
   opts=[
     ["Only when they are painful",
      "Correct — pain is the trigger for treating them."],
     ["Always, as soon as they are found",
      "The deck says therapy is not required unless painful."],
     ["Only when they exceed one centimetre",
      "Size is not the criterion given."],
     ["Only in immunocompromised patients",
      "Pain, not immune status, is the stated trigger."]],
   c=0, cite=c(145)),

 dict(topic="Warts", io=IOB, slot="agent/regimen",
   q="Which two treatments does the deck give for plantar warts?",
   opts=[
     ["Salicylic acid 40% and cryotherapy",
      "Correct — the two named options."],
     ["Cantharidin 0.7% and curettage",
      "Those are molluscum treatments."],
     ["Berdazimer 10.3% gel and topical retinoid",
      "Berdazimer is for molluscum."],
     ["Oral acyclovir and topical lidocaine",
      "Those are antiviral and neuropathic pain agents."]],
   c=0, cite=c(146)),

 dict(topic="Warts", io=IOB, slot="differential",
   q="What is the differential diagnosis for warts?",
   opts=[
     ["Squamous cell carcinoma, molluscum contagiosum, and seborrheic keratosis",
      "Correct — the three named in the deck."],
     ["Basal cell carcinoma, sebaceous hyperplasia, and condyloma acuminatum",
      "That is the molluscum differential."],
     ["Chancroid, syphilis, trauma, and candidiasis",
      "That is the genital herpes simplex differential."],
     ["Bacterial felon, contact dermatitis, and blistering dactylitis",
      "Those mimic herpetic whitlow."]],
   c=0, cite=c(147)),

 dict(topic="Warts", io=IOB, slot="initial test",
   q="How are warts diagnosed, and when is biopsy appropriate?",
   opts=[
     ["Clinically; biopsy is generally unnecessary but may suit immunocompromised patients or uncertain lesions",
      "Correct — including to rule out squamous cell carcinoma."],
     ["Clinically; biopsy should be taken from every lesion before any treatment is started, whatever the immune status",
      "Biopsy is generally unnecessary."],
     ["By polymerase chain reaction for human papillomavirus; biopsy is never appropriate",
      "Amplification testing is not described for warts."],
     ["By potassium hydroxide preparation; biopsy is reserved for painful plantar lesions",
      "That test is for dermatophytes and yeast."]],
   c=0, cite=c(147)),

 dict(topic="Warts", io=IOB, slot="complication",
   q="What are the adverse effects of cryotherapy for warts, and how often is it given?",
   opts=[
     ["Pain, blistering and pigment change; every two to three weeks",
      "Correct — both the harms and the interval."],
     ["Pain, blistering and pigment change; every two to three days",
      "The interval is two to three weeks."],
     ["Systemic absorption and hepatotoxicity; every two to three weeks",
      "Cryotherapy is destructive, not systemic."],
     ["Permanent nerve damage and bone loss; every two to three months",
      "Neither the harms nor the interval match."]],
   c=0, cite=c(148)),

 dict(topic="Warts", io=IOB, slot="referral",
   q="Which wart features should prompt biopsy or referral?",
   opts=[
     ["Atypical, bleeding, ulcerated, growing, or refractory lesions",
      "Correct — these five features."],
     ["Painless, stable, small, unchanging, and long-standing lesions",
      "Those are the reassuring features."],
     ["Any lesion on the hands or the weight-bearing sole",
      "Site alone is not a referral criterion."],
     ["Any lesion in a patient younger than twenty years",
      "That is the usual age for common warts."]],
   c=0, cite=c(148)),

 dict(topic="Warts", io=IOB, slot="prognosis",
   q="What does the deck say about eradicating human papillomavirus with wart therapy?",
   opts=[
     ["No therapy eradicates it with certainty, and recurrence can occur",
      "Correct — set expectations accordingly."],
     ["Cryotherapy eradicates it reliably, so recurrence does not occur",
      "No therapy eradicates it with certainty."],
     ["Salicylic acid eradicates it reliably when used for six weeks",
      "The deck makes no such claim."],
     ["Surgical excision eradicates it reliably in immunocompetent patients",
      "Excision is not offered as curative here."]],
   c=0, cite=c(149)),

 dict(topic="Warts", io=IOC, slot="first-line",
   q="On what basis should a wart treatment be chosen?",
   opts=[
     ["Location, symptoms, age, pregnancy status, immune status, and risk of scarring or dyspigmentation",
      "Correct — six considerations."],
     ["Lesion colour, patient preference, the season of the year, and the cost of the chosen agent",
      "None of these are the stated criteria."],
     ["Only the size of the lesion and how long it has been present",
      "The deck's list is much broader."],
     ["Only the patient's age and whether the lesion is painful",
      "Those are two of six considerations."]],
   c=0, cite=c(149)),

 dict(topic="Warts", io=IOB, slot="avoid",
   q="What does the deck warn against for benign warts likely to resolve on their own?",
   opts=[
     ["Excessive freezing or destructive therapy",
      "Correct — do not over-treat a self-limiting lesion."],
     ["Any period of observation without treatment",
      "Observation is reasonable, not discouraged."],
     ["Trimming the surface of the lesion",
      "Trimming is used to reveal capillaries."],
     ["Salicylic acid at any concentration",
      "Salicylic acid is a listed treatment."]],
   c=0, cite=c(149)),

 dict(topic="Warts", io=IOB, slot="referral",
   q="Which wart cases does the deck say to refer?",
   opts=[
     ["Periungual, facial, extensive, recalcitrant, diagnostically uncertain, or immunocompromised cases",
      "Correct — six referral categories."],
     ["Only plantar warts that have been present for more than one year and have failed salicylic acid",
      "The referral list is far broader."],
     ["Only warts in children under the age of five years",
      "Age alone is not a referral criterion."],
     ["Only mosaic warts that have failed salicylic acid",
      "That is one narrow slice of the actual list."]],
   c=0, cite=c(149)),
]
