# -*- coding: utf-8 -*-
"""Lecture 23 objective pool C -- Valvular Heart Disease: pulmonic stenosis,
pulmonic regurgitation, tricuspid stenosis, tricuspid regurgitation, and
prosthetic valves with their anticoagulation (syllabus objective 12).

KEYS ARE WRITTEN SHORT ON PURPOSE -- detail lives in the explanation.

Set 1 recall, no patient ages. "Just as likely a tricuspid valve question as an
aortic valve question", so the right-sided lesions get the same depth as the
left. Not keyed: pulmonic and tricuspid stenosis grading (58, 68), the suffusion
sign, pulmonic regurgitation "almost always congenital" (64), tricuspid
stenosis inflow "from the LA" (65 -- slide 66 is used), the slide 74 age
cut-offs. International normalized ratio targets are laboratory targets, not
doses.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _cmse3_q import Q
from cms_e4l23_scope import *


def S(topic, io, q, opts, cite, slot):
    d = Q(topic, io, q, opts, cite); d["slot"] = slot; return d


QUESTIONS = [

# ---------------------------------------------------------------- pulmonic stenosis
S(T_PS, IO_PS,
  "What is the usual cause of pulmonic stenosis?",
  [["Congenital disease",
    "Correct. Pulmonic stenosis, obstruction of right ventricular outflow to the lungs, is almost always congenital. Carcinoid disease is another cause, and it is commonly part of tetralogy of Fallot."],
   ["Rheumatic fever",
    "Rheumatic fever is the leading cause of mitral stenosis and, worldwide, of tricuspid stenosis. Pulmonic stenosis is almost always congenital."],
   ["Degenerative calcification",
    "Degenerative calcification is the aortic stenosis process of patients over 70. Pulmonic stenosis is almost always congenital."],
   ["Intravenous drug use",
    "Intravenous drug use leads to tricuspid valve endocarditis and primary tricuspid regurgitation. Pulmonic stenosis is almost always congenital."]],
  C(55), "etiology"),

S(T_PS, IO_PS,
  "Pulmonic stenosis is commonly part of which congenital condition?",
  [["Tetralogy of Fallot",
    "Correct. Pulmonic stenosis is commonly part of tetralogy of Fallot. It is almost always congenital, and carcinoid disease is the other listed cause."],
   ["Marfan syndrome",
    "Marfan syndrome dilates the aortic root and causes aortic regurgitation. Pulmonic stenosis is commonly part of tetralogy of Fallot."],
   ["A bicuspid aortic valve",
    "A bicuspid aortic valve is the leading cause of aortic stenosis under 70. Pulmonic stenosis is commonly part of tetralogy of Fallot."],
   ["Ankylosing spondylitis",
    "Ankylosing spondylitis is a valvular cause of aortic regurgitation. Pulmonic stenosis is commonly part of tetralogy of Fallot."]],
  C(55), "etiology"),

S(T_PS, IO_PS,
  "Which description fits the pulmonic stenosis murmur?",
  [["Harsh mid-systolic ejection at the left upper sternal border",
    "Correct. Pulmonic stenosis is a harsh, high-pitched crescendo-decrescendo mid-systolic ejection murmur at the left second to fourth intercostal space or left upper sternal border, with a split second heart sound."],
   ["Harsh systolic ejection at the right upper sternal border",
    "The same harsh ejection murmur at the right upper sternal border, radiating to the carotids, is aortic stenosis. Side is the discriminator."],
   ["Brief early diastolic decrescendo at the left second space",
    "A brief early diastolic decrescendo at the left second intercostal space is pulmonic regurgitation. Stenosis is harsh and systolic."],
   ["Holosystolic murmur at the lower left sternal border",
    "A holosystolic murmur at the lower left sternal border near the epigastrium is tricuspid regurgitation. Pulmonic stenosis is a harsh mid-systolic ejection murmur higher up."]],
  C(57), "manifestation"),

S(T_PS, IO_PS,
  "How does inspiration change the pulmonic stenosis murmur?",
  [["It gets louder",
    "Correct. The pulmonic stenosis murmur increases with inspiration, which raises venous return to the right heart, and it comes with a split second heart sound."],
   ["It gets softer",
    "Softening on inspiration would fit a left-sided murmur. Pulmonic stenosis is right-sided, so inspiration makes it louder."],
   ["It does not change",
    "Right-sided murmurs respond to respiration. Pulmonic stenosis grows louder on inspiration as right-sided preload rises."],
   ["It turns diastolic",
    "Respiration changes loudness, not timing. Pulmonic stenosis stays a mid-systolic ejection murmur and grows louder on inspiration."]],
  C(9, 57), "test finding"),

S(T_PS, IO_PS,
  "Which electrocardiogram findings fit pulmonic stenosis?",
  [["Right axis deviation, right ventricular hypertrophy",
    "Correct. Pulmonic stenosis raises right ventricular pressure, and the electrocardiogram shows right axis deviation with right ventricular hypertrophy. The echo shows abnormal valve motion and a raised jet on Doppler."],
   ["Left axis deviation, left ventricular hypertrophy",
    "Left-sided hypertrophy belongs to aortic stenosis and chronic aortic regurgitation. Pulmonic stenosis loads the right ventricle."],
   ["Left atrial abnormality, atrial fibrillation",
    "Left atrial abnormality with atrial fibrillation is the mitral stenosis pattern. Pulmonic stenosis gives right axis deviation and right ventricular hypertrophy."],
   ["Right atrial enlargement, no ventricular change",
    "Right atrial enlargement out of proportion to right ventricular change is tricuspid stenosis. Pulmonic stenosis thickens the right ventricle."]],
  C(58), "test finding"),

S(T_PS, IO_PS,
  "Which symptoms appear in severe pulmonic stenosis?",
  [["Exertional dyspnea, fatigue, angina, syncope",
    "Correct. Mild to moderate pulmonic stenosis is usually asymptomatic. Severe disease brings right heart failure symptoms: exertional dyspnea, fatigue, angina and syncope."],
   ["Hemoptysis, hoarseness and dysphagia",
    "Hemoptysis, hoarseness and dysphagia come from the enlarged left atrium of mitral stenosis. Severe pulmonic stenosis brings exertional dyspnea, fatigue, angina and syncope."],
   ["Cardiogenic shock and pulmonary edema",
    "Shock with pulmonary edema is the presentation of acute aortic regurgitation. Severe pulmonic stenosis gives exertional right heart failure symptoms."],
   ["Palpitations alone, otherwise well",
    "Palpitations with no other symptoms fit mild mitral regurgitation. Severe pulmonic stenosis causes exertional dyspnea, fatigue, angina and syncope."]],
  C(57), "manifestation"),

S(T_PS, IO_PS,
  "What treatment does mild to moderate pulmonic stenosis need?",
  [["None",
    "Correct. Mild to moderate pulmonic stenosis needs no treatment and carries a 94% 20-year survival. Severe symptomatic disease is treated with diuretics and pulmonic balloon valvuloplasty."],
   ["A loop diuretic",
    "Diuretics are for symptomatic right heart failure in severe pulmonic stenosis. Mild to moderate disease needs no treatment."],
   ["Balloon valvuloplasty",
    "Pulmonic balloon valvuloplasty is for severe pulmonic stenosis with symptoms. Mild to moderate disease needs none."],
   ["Valve replacement",
    "Replacement may be needed for severe congenital disease. Mild to moderate pulmonic stenosis needs no treatment."]],
  C(59), "first-line"),

S(T_PS, IO_PS,
  "Which procedure treats severe, symptomatic pulmonic stenosis?",
  [["Pulmonic balloon valvuloplasty",
    "Correct. Severe pulmonic stenosis with symptoms is treated with diuretics for right heart failure symptoms and pulmonic balloon valvuloplasty; severe congenital disease may need replacement."],
   ["A mitral valve clip",
    "A mitral valve clip reduces a mitral regurgitant leak. The right ventricular outflow obstruction of pulmonic stenosis is opened with balloon valvuloplasty."],
   ["Tricuspid annuloplasty",
    "Annuloplasty treats tricuspid regurgitation from annular dilation. Severe pulmonic stenosis is opened with pulmonic balloon valvuloplasty."],
   ["Afterload reduction",
    "Afterload reduction is medical therapy for chronic aortic regurgitation. Severe symptomatic pulmonic stenosis needs balloon valvuloplasty."]],
  C(59), "escalation"),

S(T_PS, IO_PS,
  "What is the 20-year survival of mild to moderate pulmonic stenosis?",
  [["94%",
    "Correct. Mild to moderate pulmonic stenosis has a 94% 20-year survival and needs no treatment; symptoms and intervention belong to severe disease."],
   ["75%",
    "Seventy-five percent is the 3-year mortality of symptomatic aortic stenosis. Mild to moderate pulmonic stenosis has a 94% 20-year survival."],
   ["50%",
    "Fifty percent is far too low for a condition that needs no treatment when mild to moderate. Its 20-year survival is 94%."],
   ["80%",
    "Eighty percent is the one-year mortality of untreated endocarditis. Mild to moderate pulmonic stenosis has a 94% 20-year survival."]],
  C(59), "prognosis"),

S(T_PS, IO_PS,
  "When should pulmonic stenosis be referred to cardiology?",
  [["Whenever it is seen on echocardiogram",
    "Correct. Whether congenital or related to heart failure, pulmonic stenosis should be referred to a cardiologist whenever it is present on an echocardiogram."],
   ["Only once right heart failure appears",
    "Referral does not wait for heart failure. Pulmonic stenosis seen on an echocardiogram is referred to cardiology."],
   ["Only if it is part of tetralogy of Fallot",
    "Congenital or not, pulmonic stenosis present on an echocardiogram is referred to a cardiologist."],
   ["Only after a 20-year follow-up",
    "The 94% 20-year survival describes mild to moderate disease; it does not delay referral. Echocardiographic pulmonic stenosis is referred."]],
  C(59), "referral"),

# ---------------------------------------------------------------- pulmonic regurgitation
S(T_PR, IO_PR,
  "What is the most common cause of pulmonic regurgitation?",
  [["Iatrogenic injury",
    "Correct. The most common cause of pulmonic regurgitation is iatrogenic: surgical valvotomy, valvectomy or valvuloplasty done to relieve right ventricular outflow tract obstruction leaves the valve leaking."],
   ["Pulmonary hypertension",
    "Pulmonary hypertension is the high-pressure cause of pulmonic regurgitation, but it is not the most common. Iatrogenic injury after outflow tract procedures is."],
   ["Carcinoid disease",
    "Carcinoid disease is a low-pressure cause of pulmonic regurgitation, but not the most common one. Iatrogenic injury is."],
   ["A bicuspid valve",
    "A congenital bicuspid pulmonic valve is a low-pressure cause, but the most common cause of pulmonic regurgitation is iatrogenic."]],
  C(61), "etiology"),

S(T_PR, IO_PR,
  "Which is the high-pressure cause of pulmonic regurgitation?",
  [["Pulmonary hypertension",
    "Correct. Pulmonary hypertension is the high-pressure cause of pulmonic regurgitation. The low-pressure causes are a congenital bicuspid valve, carcinoid disease and iatrogenic injury, the most common cause overall."],
   ["Carcinoid disease",
    "Carcinoid disease is listed among the low-pressure causes of pulmonic regurgitation. The high-pressure cause is pulmonary hypertension."],
   ["Surgical valvotomy",
    "Surgical valvotomy is the iatrogenic, low-pressure cause and the most common overall. The high-pressure cause is pulmonary hypertension."],
   ["A bicuspid valve",
    "A congenital bicuspid valve is a low-pressure cause. Pulmonary hypertension is the high-pressure cause of pulmonic regurgitation."]],
  C(61), "etiology"),

S(T_PR, IO_PR,
  "What is the Graham Steell murmur?",
  [["Pulmonic regurgitation's early diastolic murmur",
    "Correct. The Graham Steell murmur is the brief, high-pitched, early diastolic decrescendo murmur of pulmonic regurgitation at the left second intercostal space, radiating to the mid-right sternal border with full inspiration."],
   ["Tricuspid regurgitation's inspiratory murmur",
    "The inspiratory increase of the holosystolic tricuspid regurgitation murmur is the Carvallo sign, not the Graham Steell murmur."],
   ["Aortic stenosis's harsh systolic murmur",
    "The harsh systolic ejection murmur radiating to the carotids is aortic stenosis. The Graham Steell murmur is pulmonic regurgitation, early in diastole."],
   ["Tricuspid stenosis's mid-diastolic rumble",
    "The mid-diastolic rumble near the xiphoid is tricuspid stenosis. The Graham Steell murmur is the early diastolic pulmonic regurgitation murmur."]],
  C(63), "manifestation"),

S(T_PR, IO_PR,
  "Which change makes the pulmonic regurgitation murmur louder?",
  [["Squatting",
    "Correct. Anything that increases venous return makes the pulmonic regurgitation murmur louder: inspiration, squatting and lying supine. Expiration and standing, which reduce venous return, soften it."],
   ["Standing",
    "Standing reduces venous return, so the pulmonic regurgitation murmur gets softer, not louder."],
   ["Expiration",
    "Expiration reduces venous return to the right heart and softens pulmonic regurgitation. Inspiration makes it louder."],
   ["Sitting upright",
    "Moving from supine to upright reduces venous return. The pulmonic regurgitation murmur is louder lying supine, squatting or on inspiration."]],
  C(63), "test finding"),

S(T_PR, IO_PR,
  "Which symptoms does significant pulmonic regurgitation produce?",
  [["Right-sided heart failure",
    "Correct. Retrograde flow from the pulmonary artery overloads the right ventricle, producing right-sided heart failure: fatigue, peripheral edema, jugular venous distension and ascites."],
   ["Left-sided heart failure",
    "Left-sided failure with orthopnea and pulmonary edema follows left-sided lesions such as mitral and aortic disease. Pulmonic regurgitation overloads the right ventricle."],
   ["Exertional syncope and angina",
    "Exertional syncope and angina are cardinal symptoms of aortic stenosis. Pulmonic regurgitation causes right-sided heart failure."],
   ["Hoarseness and dysphagia",
    "Hoarseness and dysphagia come from the enlarged left atrium of mitral stenosis. Pulmonic regurgitation causes right-sided heart failure."]],
  C(62), "manifestation"),

S(T_PR, IO_PR,
  "How is pulmonic regurgitation usually discovered?",
  [["Incidentally, on echo or examination",
    "Correct. Pulmonic regurgitation is usually an incidental finding on an echocardiogram or on physical examination; management is to treat the underlying condition."],
   ["By catheterization after syncope",
    "Catheterization after syncope is not how pulmonic regurgitation comes to light. It is usually found incidentally on an echocardiogram or examination."],
   ["By an electrocardiogram showing right axis deviation",
    "Right axis deviation with right ventricular hypertrophy is the pulmonic stenosis electrocardiogram. Regurgitation is usually found incidentally on echo or examination."],
   ["By a chest radiograph after hemoptysis",
    "Hemoptysis belongs to mitral stenosis. Pulmonic regurgitation is usually an incidental finding on an echocardiogram or physical examination."]],
  C(64), "initial test"),

S(T_PR, IO_PR,
  "What is the management approach to pulmonic regurgitation?",
  [["Treat the underlying condition",
    "Correct. Pulmonic regurgitation is managed by treating the underlying condition, with referral when it is seen on an echocardiogram or when right heart failure symptoms and signs appear."],
   ["Pulmonic balloon valvuloplasty",
    "Balloon valvuloplasty opens a stenotic pulmonic valve, and outflow tract procedures like it are the most common cause of pulmonic regurgitation, not its treatment."],
   ["Lifelong anticoagulation",
    "Lifelong anticoagulation is for mechanical heart valves. Pulmonic regurgitation is managed by treating the underlying condition."],
   ["Tricuspid annuloplasty",
    "Annuloplasty repairs tricuspid regurgitation from annular dilation. Pulmonic regurgitation is managed by treating the underlying condition."]],
  C(64), "first-line"),

S(T_PR, IO_PR,
  "When should pulmonic regurgitation be referred?",
  [["When seen on echo or with right heart failure",
    "Correct. Pulmonic regurgitation is referred when it is seen on an echocardiogram or when there are symptoms and signs of right heart failure."],
   ["Only after a first episode of syncope",
    "Syncope is not the trigger. Pulmonic regurgitation is referred when seen on an echocardiogram or with right heart failure symptoms or signs."],
   ["Only when the cause is iatrogenic",
    "The cause does not decide referral. Pulmonic regurgitation is referred when seen on an echocardiogram or with right heart failure."],
   ["Never, since it is always benign",
    "Significant pulmonic regurgitation overloads the right ventricle and causes right heart failure. It is referred when seen on echo or with those signs."]],
  C(64), "referral"),

# ---------------------------------------------------------------- tricuspid stenosis
S(T_TS, IO_TS,
  "Worldwide, what is the most common cause of tricuspid stenosis?",
  [["Rheumatic fever",
    "Correct. Worldwide, tricuspid stenosis is most commonly due to rheumatic fever. In the United States it is almost always congenital, and carcinoid disease is another cause."],
   ["Congenital disease",
    "Congenital disease is the leading cause in the united states. Worldwide, rheumatic fever is the most common cause of tricuspid stenosis."],
   ["Carcinoid disease",
    "Carcinoid disease is one listed cause of tricuspid stenosis, but not the most common. Worldwide it is rheumatic fever."],
   ["Intravenous drug use",
    "Intravenous drug use causes tricuspid valve endocarditis and primary tricuspid regurgitation. Worldwide, tricuspid stenosis is most often rheumatic."]],
  C(65), "etiology"),

S(T_TS, IO_TS,
  "In the United States, what is tricuspid stenosis almost always?",
  [["Congenital",
    "Correct. In the United States tricuspid stenosis is almost always congenital, while worldwide it is most commonly due to rheumatic fever. It is most common in women."],
   ["Rheumatic",
    "Rheumatic fever is the leading cause worldwide, and it has become rare in developed countries. In the United States tricuspid stenosis is almost always congenital."],
   ["Iatrogenic",
    "Iatrogenic injury is the most common cause of pulmonic regurgitation. In the United States tricuspid stenosis is almost always congenital."],
   ["Degenerative",
    "Degenerative disease is the leading cause of aortic stenosis over 70. In the United States tricuspid stenosis is almost always congenital."]],
  C(65), "epidemiology"),

S(T_TS, IO_TS,
  "Tricuspid stenosis obstructs flow between which chambers?",
  [["Right atrium to right ventricle",
    "Correct. Tricuspid stenosis narrows the valve between the right atrium and right ventricle, obstructing inflow; the right atrium dilates and hypertrophies, with low cardiac output and portal congestion."],
   ["Left atrium to left ventricle",
    "Obstruction between the left atrium and left ventricle is mitral stenosis. Tricuspid stenosis blocks inflow from the right atrium to the right ventricle."],
   ["Right ventricle to pulmonary artery",
    "Obstruction of right ventricular outflow to the lungs is pulmonic stenosis. Tricuspid stenosis obstructs inflow from the right atrium."],
   ["Left ventricle to aorta",
    "Obstruction of left ventricular outflow is aortic stenosis. Tricuspid stenosis obstructs right atrial to right ventricular inflow."]],
  C(65, 66), "etiology"),

S(T_TS, IO_TS,
  "Which description fits the tricuspid stenosis murmur?",
  [["Mid-diastolic rumble near the xiphoid, louder on inspiration",
    "Correct. Tricuspid stenosis gives a soft opening snap and a mid-diastolic rumble at the left lower sternal border near the xiphoid process, increasing with inspiration, with jugular vein distension."],
   ["Diastolic rumble at the apex, best on the left side",
    "A diastolic rumble at the apex, heard with the patient on the left side, is mitral stenosis. The tricuspid rumble is near the xiphoid and grows on inspiration."],
   ["Holosystolic murmur near the epigastrium, louder on inspiration",
    "A holosystolic murmur near the epigastrium that grows on inspiration is tricuspid regurgitation. Stenosis is a mid-diastolic rumble."],
   ["Harsh mid-systolic murmur at the left upper sternal border",
    "A harsh mid-systolic ejection murmur at the left upper sternal border is pulmonic stenosis. Tricuspid stenosis is a diastolic rumble near the xiphoid."]],
  C(67), "manifestation"),

S(T_TS, IO_TS,
  "Which symptom of severe tricuspid stenosis comes from an enlarged liver?",
  [["Right upper quadrant pain",
    "Correct. Severe tricuspid stenosis causes right upper quadrant pain from an enlarged, congested liver, cold skin from low cardiac output, and a quivering discomfort in the neck."],
   ["Cold skin",
    "Cold skin in severe tricuspid stenosis comes from low cardiac output, not from the liver. Hepatic enlargement causes right upper quadrant pain."],
   ["Hemoptysis",
    "Hemoptysis comes from ruptured bronchial veins under high left atrial pressure in mitral stenosis. Liver enlargement in tricuspid stenosis causes right upper quadrant pain."],
   ["Hoarseness",
    "Hoarseness is Ortner syndrome of mitral stenosis, from the left atrium on the recurrent laryngeal nerve. Tricuspid stenosis causes right upper quadrant pain."]],
  C(67), "manifestation"),

S(T_TS, IO_TS,
  "Which electrocardiogram finding points to tricuspid stenosis?",
  [["Right atrial enlargement out of proportion to the right ventricle",
    "Correct. Tricuspid stenosis shows right atrial enlargement out of proportion to right ventricular hypertrophy, because the obstruction sits behind the right atrium and spares the ventricle."],
   ["Left atrial enlargement out of proportion to the left ventricle",
    "Left atrial abnormality with a spared left ventricle is the mitral stenosis pattern. Tricuspid stenosis enlarges the right atrium."],
   ["Right ventricular hypertrophy out of proportion to the right atrium",
    "Dominant right ventricular hypertrophy with right axis deviation fits pulmonic stenosis. Tricuspid stenosis enlarges the right atrium more than the ventricle."],
   ["Left ventricular hypertrophy out of proportion to the left atrium",
    "Left ventricular hypertrophy is the aortic stenosis and chronic aortic regurgitation finding. Tricuspid stenosis shows right atrial enlargement."]],
  C(68), "test finding"),

S(T_TS, IO_TS,
  "Which medical measures treat severe, symptomatic tricuspid stenosis?",
  [["Low salt, diuretics, an aldosterone antagonist",
    "Correct. Severe symptomatic tricuspid stenosis is managed with a low-salt diet, diuretics and an aldosterone antagonist, with bioprosthetic valve replacement preferred when surgery is needed."],
   ["Nitrates, beta blockers, calcium channel blockers",
    "Nitrates, beta blockers and calcium channel blockers are the classes avoided in aortic stenosis. Tricuspid stenosis is treated with low salt, diuretics and an aldosterone antagonist."],
   ["Hydralazine, nitroprusside, intravenous fluids",
    "Vasodilators suit aortic regurgitation, and extra fluid would worsen venous congestion. Tricuspid stenosis is treated with low salt, diuretics and an aldosterone antagonist."],
   ["Warfarin, heparin bridging, antiplatelets",
    "Warfarin with heparin bridging is the mechanical valve regimen. Tricuspid stenosis symptoms are treated with low salt, diuretics and an aldosterone antagonist."]],
  C(69), "first-line"),

S(T_TS, IO_TS,
  "Which valve replacement is preferred for severe tricuspid stenosis?",
  [["Bioprosthetic",
    "Correct. When severe symptomatic tricuspid stenosis needs replacement, a bioprosthetic valve is preferred. Balloon valvotomy and repair are reserved for hepatic congestion or severe systemic venous congestion."],
   ["Mechanical",
    "Mechanical valves need lifelong anticoagulation; for tricuspid stenosis the preferred replacement is bioprosthetic."],
   ["Transcatheter aortic",
    "A transcatheter aortic valve replaces the aortic valve in aortic stenosis. Tricuspid stenosis replacement is preferably bioprosthetic."],
   ["Human donor",
    "A donor valve is not the listed option. For severe tricuspid stenosis a bioprosthetic replacement is preferred."]],
  C(69), "agent/regimen"),

S(T_TS, IO_TS,
  "For tricuspid stenosis, what is balloon valvotomy reserved for?",
  [["Hepatic congestion that may lead to cirrhosis",
    "Correct. Balloon valvotomy and valve repair are reserved for tricuspid stenosis with hepatic congestion that may lead to cirrhosis, or severe systemic venous congestion."],
   ["Every patient with a murmur",
    "An audible murmur alone does not justify valvotomy. It is reserved for hepatic congestion that may progress to cirrhosis or severe venous congestion."],
   ["Mild disease without symptoms",
    "Mild, asymptomatic disease is not an indication. Valvotomy is reserved for hepatic congestion threatening cirrhosis or severe venous congestion."],
   ["Children and young adults only",
    "Age is the valvuloplasty rule for aortic stenosis. In tricuspid stenosis, valvotomy is reserved for hepatic or severe systemic venous congestion."]],
  C(69), "escalation"),

# ---------------------------------------------------------------- tricuspid regurgitation
S(T_TR, IO_TR,
  "What is the most common cause of tricuspid regurgitation?",
  [["Pulmonary hypertension dilating the annulus",
    "Correct. Tricuspid regurgitation is most commonly due to dilation of the tricuspid annulus from right ventricular dilation in the setting of pulmonary hypertension. Primary disease is infective endocarditis in drug users."],
   ["Endocarditis from intravenous drug use",
    "Endocarditis in intravenous drug users is the primary cause of tricuspid regurgitation, but not the most common. That is annular dilation with pulmonary hypertension."],
   ["Rheumatic scarring of the leaflets",
    "Rheumatic scarring leads to stenosis of the mitral valve and, worldwide, the tricuspid valve. Tricuspid regurgitation most often follows annular dilation."],
   ["Carcinoid disease of the valve",
    "Carcinoid disease is listed for pulmonic and tricuspid stenosis and pulmonic regurgitation. Tricuspid regurgitation most often follows annular dilation."]],
  C(70), "etiology"),

S(T_TR, IO_TR,
  "Primary tricuspid regurgitation from infective endocarditis is typical of whom?",
  [["Intravenous drug users",
    "Correct. Primary tricuspid regurgitation comes from infective endocarditis in intravenous drug users. Endocarditis from other sources more often involves the mitral valve."],
   ["Healthy women aged 15 to 30",
    "Healthy women 15 to 30 are the typical patients with mitral valve prolapse. Tricuspid endocarditis is typical of intravenous drug users."],
   ["Adults older than 70",
    "Over 70 the leading valve problem is degenerative aortic stenosis. Primary tricuspid regurgitation from endocarditis is typical of intravenous drug users."],
   ["Children with tetralogy of Fallot",
    "Tetralogy of Fallot commonly includes pulmonic stenosis. Tricuspid endocarditis is typical of intravenous drug users."]],
  C(70), "risk factors"),

S(T_TR, IO_TR,
  "Where is the tricuspid regurgitation murmur heard?",
  [["Lower left sternal border, near the epigastrium",
    "Correct. Tricuspid regurgitation is a holosystolic murmur at the left mid or lower sternal border near the epigastrium that increases with inspiration (the Carvallo sign)."],
   ["At the apex, radiating to the axilla",
    "A holosystolic murmur at the apex radiating to the axilla is mitral regurgitation. Tricuspid regurgitation sits at the lower left sternal border."],
   ["Right second space, radiating to the carotids",
    "The second right intercostal space with radiation to the carotids is aortic stenosis. Tricuspid regurgitation is at the lower left sternal border."],
   ["Left second space, toward the right sternum",
    "The left second intercostal space radiating toward the right sternal border is the pulmonic regurgitation murmur. Tricuspid regurgitation is lower, near the epigastrium."]],
  C(71), "manifestation"),

S(T_TR, IO_TR,
  "Which finding distinguishes tricuspid regurgitation from mitral regurgitation?",
  [["The murmur grows louder on inspiration",
    "Correct. Both are holosystolic, but the tricuspid regurgitation murmur increases with inspiration, the Carvallo sign, because inspiration raises right-sided venous return. That distinguishes it from mitral regurgitation."],
   ["The murmur is holosystolic",
    "Both tricuspid and mitral regurgitation are holosystolic, so timing cannot separate them. The inspiratory increase (Carvallo sign) does."],
   ["The murmur is blowing",
    "Both regurgitant murmurs are blowing. The distinguishing feature of tricuspid regurgitation is the inspiratory increase, the Carvallo sign."],
   ["The murmur softens on standing",
    "Standing softens mitral regurgitation too, so it does not discriminate. The Carvallo sign, louder on inspiration, marks tricuspid regurgitation."]],
  C(71), "differential"),

S(T_TR, IO_TR,
  "Which neck findings fit tricuspid regurgitation?",
  [["Raised jugular pressure and a venous thrill",
    "Correct. Tricuspid regurgitation raises the jugular venous pressure with neck pulsations and a venous thrill over the right jugular vein, as blood is driven back into the right atrium."],
   ["A weak, delayed carotid pulse",
    "A weak, delayed carotid pulse with a forceful apex beat signals severe aortic stenosis. Tricuspid regurgitation shows raised jugular pressure and a venous thrill."],
   ["A collapsing pulse with head bobbing",
    "A collapsing pulse with head bobbing (Corrigan and de Musset signs) belongs to aortic regurgitation. Tricuspid regurgitation shows venous findings in the neck."],
   ["Hoarseness from nerve compression",
    "Hoarseness from the left atrium pressing the left recurrent laryngeal nerve is mitral stenosis. Tricuspid regurgitation shows raised jugular pressure and a thrill."]],
  C(71), "manifestation"),

S(T_TR, IO_TR,
  "Which symptoms appear in severe tricuspid regurgitation?",
  [["Pedal edema and ascites",
    "Correct. Mild to moderate tricuspid regurgitation is usually asymptomatic; severe disease causes pedal edema and ascites as systemic venous pressure rises."],
   ["Hemoptysis and hoarseness",
    "Hemoptysis and hoarseness come from the high-pressure, enlarged left atrium of mitral stenosis. Severe tricuspid regurgitation causes pedal edema and ascites."],
   ["Angina and exertional syncope",
    "Angina and exertional syncope are cardinal symptoms of aortic stenosis. Severe tricuspid regurgitation causes pedal edema and ascites."],
   ["Head bobbing and wide pulses",
    "Head bobbing and a wide pulse pressure are chronic aortic regurgitation signs. Severe tricuspid regurgitation causes pedal edema and ascites."]],
  C(71), "manifestation"),

S(T_TR, IO_TR,
  "Which study diagnoses tricuspid regurgitation?",
  [["Doppler echocardiogram",
    "Correct. Doppler echocardiography shows the regurgitation and the leaflets, which may be prolapsed, scarred or displaced. Referral follows when it is identified on echo or with right heart failure symptoms."],
   ["Left heart catheterization",
    "Left heart catheterization is the definitive study for aortic stenosis. Tricuspid regurgitation is diagnosed on Doppler echocardiography."],
   ["Chest radiograph",
    "A chest radiograph cannot show regurgitant flow across the tricuspid valve. Doppler echocardiography diagnoses it."],
   ["Electrocardiogram",
    "The electrocardiogram cannot show a leaking valve. Tricuspid regurgitation is diagnosed with Doppler echocardiography."]],
  C(72), "initial test"),

S(T_TR, IO_TR,
  "Which procedure treats tricuspid regurgitation caused by annular dilation?",
  [["Annuloplasty",
    "Correct. Tricuspid regurgitation from annular dilation is treated with annuloplasty after treating the underlying condition; valve repair or replacement is used when the cause is primary."],
   ["Valve replacement",
    "Replacement, like repair, is used when tricuspid regurgitation has a primary cause such as endocarditis. Annular dilation is treated with annuloplasty."],
   ["Balloon valvotomy",
    "Balloon valvotomy opens a stenotic valve; it would worsen a leak. Annular dilation is treated with annuloplasty."],
   ["A mitral valve clip",
    "A mitral valve clip treats mitral regurgitation. Tricuspid regurgitation from annular dilation is treated with annuloplasty."]],
  C(72), "agent/regimen"),

S(T_TR, IO_TR,
  "When should tricuspid regurgitation be referred?",
  [["On echo or with right heart failure symptoms",
    "Correct. Tricuspid regurgitation is referred when it is identified on an echocardiogram or when the patient has right heart failure symptoms, after treating the underlying condition."],
   ["Only if the cause is endocarditis",
    "The cause does not decide referral. Tricuspid regurgitation is referred when identified on an echocardiogram or with right heart failure symptoms."],
   ["Only once ascites needs draining",
    "Referral should not wait for severe ascites. Tricuspid regurgitation is referred when seen on echo or with right heart failure symptoms."],
   ["Never, as primary care can manage it",
    "Tricuspid regurgitation identified on an echocardiogram, or with right heart failure symptoms, is referred."]],
  C(72), "referral"),

# ---------------------------------------------------------------- prosthetic valves
S(T_PV, IO_12,
  "Which long-term anticoagulant class is recommended for a mechanical heart valve?",
  [["A vitamin K antagonist",
    "Correct. For patients with mechanical heart valves, vitamin K antagonist therapy is recommended over no vitamin K antagonist and over antiplatelet agents for long-term management."],
   ["An antiplatelet agent",
    "Antiplatelet agents are specifically ranked below vitamin K antagonist therapy for mechanical valves. The recommended long-term class is a vitamin K antagonist."],
   ["Heparin alone",
    "Heparin is the bridge used when surgery interrupts warfarin, not the long-term agent. Mechanical valves are managed with a vitamin K antagonist."],
   ["No anticoagulant",
    "Mechanical valves need lifelong anticoagulation; it is biological valves that need none beyond the immediate postoperative period. The class is a vitamin K antagonist."]],
  C(75), "agent/regimen"),

S(T_PV, IO_12,
  "Which drug is the most commonly used vitamin K antagonist for a mechanical valve?",
  [["Warfarin",
    "Correct. Warfarin is the most commonly used vitamin K antagonist, the long-term anticoagulant for mechanical heart valves; if surgery requires heparin instead, warfarin is bridged until the ratio is therapeutic."],
   ["Heparin",
    "Heparin is not a vitamin K antagonist; it is the bridging agent used around surgery. The most common vitamin K antagonist is warfarin."],
   ["Aspirin",
    "Aspirin is an antiplatelet agent, and antiplatelets are ranked below vitamin K antagonists for mechanical valves. The vitamin K antagonist is warfarin."],
   ["Clopidogrel",
    "Clopidogrel is an antiplatelet agent, not a vitamin K antagonist. The most commonly used vitamin K antagonist is warfarin."]],
  C(75), "agent/regimen"),

S(T_PV, IO_12,
  "What is the target international normalized ratio for a mechanical aortic valve?",
  [["2.5 (range 2.0 to 3.0)",
    "Correct. A mechanical aortic valve targets an international normalized ratio of 2.5, range 2.0 to 3.0. A mechanical mitral valve, or valves in both positions, targets 3.0."],
   ["3.0 (range 2.5 to 3.5)",
    "A target of 3.0, range 2.5 to 3.5, is for a mechanical mitral valve or for valves in both positions. The aortic target is 2.5."],
   ["1.5 (range 1.0 to 2.0)",
    "A ratio of 1.5 is below any mechanical valve target. The mechanical aortic valve target is 2.5, range 2.0 to 3.0."],
   ["4.0 (range 3.5 to 4.5)",
    "A ratio of 4.0 exceeds every mechanical valve target. The aortic target is 2.5, and the highest target, mitral or both, is 3.0."]],
  C(75), "test finding"),

S(T_PV, IO_12,
  "What is the target international normalized ratio for a mechanical mitral valve?",
  [["3.0 (range 2.5 to 3.5)",
    "Correct. A mechanical mitral valve targets an international normalized ratio of 3.0, range 2.5 to 3.5, higher than the aortic target of 2.5."],
   ["2.5 (range 2.0 to 3.0)",
    "A target of 2.5, range 2.0 to 3.0, is for a mechanical aortic valve. The mitral target is higher, 3.0."],
   ["2.0 (range 1.5 to 2.5)",
    "A target of 2.0 is below both mechanical valve targets. A mechanical mitral valve targets 3.0, range 2.5 to 3.5."],
   ["3.5 (range 3.0 to 4.0)",
    "A target of 3.5 overshoots. A mechanical mitral valve targets 3.0, range 2.5 to 3.5."]],
  C(75), "test finding"),

S(T_PV, IO_12,
  "What ratio target applies when mechanical valves sit in both the aortic and mitral positions?",
  [["3.0 (range 2.5 to 3.5)",
    "Correct. With mechanical valves in both the aortic and mitral positions, the target international normalized ratio is 3.0, range 2.5 to 3.5: stick with the higher of the two targets."],
   ["2.5 (range 2.0 to 3.0)",
    "A target of 2.5 is for a mechanical aortic valve alone. With both positions replaced, the higher mitral target of 3.0 applies."],
   ["2.75, the average",
    "The two targets are not averaged. With valves in both positions the higher target, 3.0, range 2.5 to 3.5, applies."],
   ["5.5, the sum",
    "The targets are not added together. With mechanical valves in both positions, the target is the higher one, 3.0."]],
  C(75), "test finding"),

S(T_PV, IO_12,
  "Surgery requires stopping warfarin in a patient with a mechanical valve. What must happen?",
  [["Bridge with heparin until the ratio is therapeutic",
    "Correct. If surgery requires transition to heparin, warfarin must be bridged: heparin covers the gap until the international normalized ratio is therapeutic again. The mechanical valve cannot go unprotected."],
   ["Stop all anticoagulation until after surgery",
    "Leaving a mechanical valve without anticoagulation risks clot on the valve. Warfarin is bridged with heparin until the ratio is therapeutic."],
   ["Switch permanently to an antiplatelet agent",
    "Antiplatelet agents are ranked below vitamin K antagonists for mechanical valves. The patient is bridged with heparin and returns to warfarin."],
   ["Replace the valve with a biological one first",
    "Changing the valve is not how surgery is managed. Warfarin is bridged with heparin until the international normalized ratio is therapeutic."]],
  C(75), "escalation"),

S(T_PV, IO_12,
  "How do mechanical and biological valves differ in anticoagulation?",
  [["Mechanical needs it lifelong; biological does not",
    "Correct. A mechanical valve (titanium and carbon) needs lifelong anticoagulation, while a biological valve (pig or cow tissue) does not need anticoagulation beyond the immediate postoperative period."],
   ["Biological needs it lifelong; mechanical does not",
    "This is reversed. Mechanical valves need lifelong anticoagulation, while biological tissue valves do not beyond the immediate postoperative period."],
   ["Both need lifelong anticoagulation",
    "Only the mechanical valve needs lifelong anticoagulation. A biological valve needs none beyond the immediate postoperative period."],
   ["Neither needs anticoagulation",
    "Mechanical valves need lifelong vitamin K antagonist therapy. Only biological valves avoid long-term anticoagulation."]],
  C(21, 52, 74), "differential"),

S(T_PV, IO_12,
  "Which patient is preferred for a bioprosthetic rather than a mechanical valve?",
  [["One with a contraindication to anticoagulation",
    "Correct. Bioprosthetic valves are preferred when there is any contraindication to anticoagulation, or when life expectancy is shorter than the expected longevity of the bioprosthetic valve."],
   ["One whose life expectancy exceeds the valve's",
    "A bioprosthetic valve is preferred when life expectancy is shorter than the valve's expected longevity. Outliving the valve argues the other way."],
   ["One who wants lifelong vitamin K antagonist therapy",
    "Lifelong vitamin K antagonist therapy is the burden of a mechanical valve. Bioprosthetic valves are preferred when anticoagulation is contraindicated."],
   ["One with mild, asymptomatic valve disease",
    "Mild, asymptomatic disease is not replaced at all. Bioprosthetic valves are preferred when anticoagulation is contraindicated."]],
  C(74), "education"),

S(T_PV, IO_12,
  "What are mechanical heart valves made of?",
  [["Titanium and carbon",
    "Correct. Mechanical valves are titanium and carbon and need lifelong anticoagulation; biological valves are pig or cow tissue and do not."],
   ["Pig or cow tissue",
    "Pig or cow tissue is the biological valve, which does not need anticoagulation beyond the immediate postoperative period. Mechanical valves are titanium and carbon."],
   ["Human donor tissue",
    "Donor tissue is not the listed material. Mechanical valves are titanium and carbon; biological valves are pig or cow tissue."],
   ["Stainless steel wire",
    "Stainless steel is not the listed material. Mechanical valves are titanium and carbon, which is why they need lifelong anticoagulation."]],
  C(21, 52), "agent/regimen"),

S(T_PV, IO_12,
  "Which is avoided as the sole long-term therapy for a mechanical heart valve?",
  [["An antiplatelet agent",
    "Correct. Vitamin K antagonist therapy is recommended over antiplatelet agents for the long-term management of mechanical valves, so an antiplatelet agent alone is not adequate."],
   ["A vitamin K antagonist",
    "A vitamin K antagonist such as warfarin is exactly the recommended long-term therapy for mechanical valves. Antiplatelet therapy alone is what falls short."],
   ["Warfarin",
    "Warfarin is the most commonly used vitamin K antagonist and the recommended therapy for mechanical valves, not something to avoid."],
   ["Warfarin with a heparin bridge for surgery",
    "Bridging warfarin with heparin around surgery is required, not avoided. Antiplatelet therapy alone is inadequate for a mechanical valve."]],
  C(75), "avoid"),

S(T_PV, IO_12,
  "How long does a bioprosthetic valve need anticoagulation?",
  [["Only right after surgery",
    "Correct. A bioprosthetic valve does not need anticoagulation beyond the immediate postoperative period, which is why it is preferred when anticoagulation is contraindicated."],
   ["For life",
    "Lifelong anticoagulation is the mechanical valve requirement. A bioprosthetic valve needs none beyond the immediate postoperative period."],
   ["For ten years",
    "There is no ten-year anticoagulation course. A bioprosthetic valve needs anticoagulation only in the immediate postoperative period."],
   ["Until the ratio hits 3.0",
    "A ratio target of 3.0 applies to mechanical mitral valves. A bioprosthetic valve needs no anticoagulation beyond the immediate postoperative period."]],
  C(74), "first-line"),

S(T_PV, IO_12,
  "What should a patient receiving a mechanical heart valve be told about anticoagulation?",
  [["It will be needed for life",
    "Correct. A mechanical valve needs lifelong anticoagulation with a vitamin K antagonist, most commonly warfarin, monitored against an international normalized ratio target."],
   ["It stops after six weeks",
    "Short postoperative anticoagulation describes a bioprosthetic valve. A mechanical valve needs lifelong anticoagulation."],
   ["Aspirin alone will do",
    "Antiplatelet agents are ranked below vitamin K antagonists for mechanical valves. Lifelong vitamin K antagonist therapy is required."],
   ["It is only for surgery",
    "Heparin bridging covers surgery, but the underlying need is lifelong. A mechanical valve needs a vitamin K antagonist for life."]],
  C(21, 75), "education"),
]
