# -*- coding: utf-8 -*-
"""CMS I Exam 2, Lecture 13 -- objective set B.

Strabismus, amblyopia, cataract, and the ocular tumours: retinoblastoma, uveal
melanoma, iris nevus and conjunctival melanoma. Patient stems throughout, and
self-contained: nothing refers to "the lecture".
"""
D = "Chronic Vision Loss & Tumors - Dr Rappa.pptx, Slide %d"
IO_A = "a — Chronic vision loss disorders: etiology, manifestations, testing, management"
IO_B = "b — Identify medical care strategies for common ophthalmological disorders by age"

QUESTIONS = [
 # ---------------- strabismus ----------------
 dict(topic="Strabismus", io=IO_A, lead="symptom", cite=D % 25,
  q="A 40-year-old man reports double vision that disappears when he covers either eye. What does that indicate?",
  opts=[["Binocular diplopia from ocular misalignment", "Correct. Covering one eye removes the second image."],
        ["A cataract in one eye", "That blurs rather than doubles."],
        ["Optic neuritis", "That reduces acuity and colour, not alignment."],
        ["Macular degeneration", "That distorts the centre of vision."],
        ["Amblyopia", "That is reduced acuity, not diplopia."]]),

 dict(topic="Strabismus", io=IO_A, lead="exam finding", cite=D % 25,
  q="A 4-year-old girl is assessed for suspected strabismus. Which test elicits fixation of the misaligned eye?",
  opts=[["The cover test", "Correct, and the corneal light reflex is displaced in larger deviations."],
        ["The Amsler grid", "That detects central distortion."],
        ["Tonometry", "That measures pressure."],
        ["The swinging flashlight test", "That detects a relative afferent pupillary defect."],
        ["Fluorescein staining", "That shows corneal epithelial defects."]]),

 dict(topic="Strabismus", io=IO_A, lead="differential", cite=D % 29,
  q="A 58-year-old man has ptosis, a dilated pupil and an eye turned down and out. Which nerve is involved?",
  opts=[["Cranial nerve three", "Correct. Pupil involvement makes it urgent."],
        ["Cranial nerve four", "That gives vertical diplopia worse on downgaze."],
        ["Cranial nerve six", "That gives horizontal diplopia with esotropia."],
        ["Cranial nerve two", "That is the optic nerve and moves nothing."],
        ["Cranial nerve seven", "That moves the face, not the globe."]]),

 dict(topic="Strabismus", io=IO_A, lead="differential", cite=D % 29,
  q="A 34-year-old woman has ptosis and diplopia that vary through the day. Which diagnosis fits?",
  opts=[["Myasthenia gravis", "Correct. It is variable and mimics any strabismus pattern."],
        ["Cranial nerve three palsy", "That does not fluctuate hour to hour."],
        ["Thyroid eye disease", "That restricts movement rather than fluctuating."],
        ["Amblyopia", "That is fixed and developmental."],
        ["Retinoblastoma", "That is a childhood tumour."]]),

 dict(topic="Strabismus", io=IO_A, lead="differential", cite=D % 29,
  q="A 9-year-old boy with Down syndrome is screened for eye problems. Which is he more likely to have?",
  opts=[["Esotropia", "Correct. Down syndrome carries a higher prevalence of it."],
        ["Uveal melanoma", "That is an adult tumour."],
        ["Presbyopia", "That comes with middle age."],
        ["Giant cell arteritis", "That affects older adults."],
        ["Conjunctival melanoma", "That is not the association."]]),

 # ---------------- amblyopia ----------------
 dict(topic="Amblyopia", io=IO_B, lead="epidemiology", cite=D % 33,
  q="A 5-year-old boy has reduced vision in one eye that glasses do not correct. What is the commonest cause of childhood vision loss?",
  opts=[["Amblyopia", "Correct, affecting 3 to 5 percent of children."],
        ["Congenital cataract", "A cause of amblyopia rather than the commonest diagnosis."],
        ["Retinoblastoma", "That is rare."],
        ["Glaucoma", "That is uncommon in children."],
        ["Macular degeneration", "That is a disease of older adults."]]),

 dict(topic="Amblyopia", io=IO_A, lead="mechanism", cite=D % 33,
  q="A 3-year-old girl has one eye with a much stronger prescription than the other. How does amblyopia arise?",
  opts=[["The brain favours one eye and the other fails to develop", "Correct. Strabismus, refractive difference or deprivation all do this."],
        ["The optic nerve is compressed", "No compression is involved."],
        ["Intraocular pressure rises", "Pressure is not the mechanism."],
        ["The lens clouds over", "That is a cataract, which can cause it but is not the mechanism."],
        ["The retina detaches", "That is a separate condition."]]),

 dict(topic="Amblyopia", io=IO_A, lead="exam finding", cite=D % 32,
  q="A 2-year-old boy is calm when his left eye is covered but cries when the right is covered. What does that show?",
  opts=[["The left eye is amblyopic", "Correct. Losing the good eye is what distresses him."],
        ["The right eye is amblyopic", "He objects when the RIGHT is covered, so it is the better eye."],
        ["Both eyes see equally", "Equal eyes would give no asymmetry."],
        ["He has a cataract on the right", "Nothing here points to the lens."],
        ["He has retinoblastoma", "The test does not assess for tumour."]]),

 dict(topic="Amblyopia", io=IO_A, lead="diagnosis", cite=D % 30,
  q="A 7-year-old girl reads 20/50 with one eye and 20/30 with the other. What defines unilateral amblyopia?",
  opts=[["Two or more lines of difference", "Correct, on best corrected acuity."],
        ["Any difference at all", "A small difference is not enough."],
        ["Five or more lines", "The threshold is lower."],
        ["Worse than 20/200 in one eye", "That is a blindness threshold, not this."],
        ["Loss of colour vision", "That points to optic neuropathy."]]),

 dict(topic="Amblyopia", io=IO_B, lead="screening", cite=D % 33,
  q="By what age should every child be screened for amblyopia?",
  opts=[["Under five years", "Correct, per the preventive task force and the paediatric academy."],
        ["Under two years", "Screening is recommended by five, not two."],
        ["Under ten years", "That is too late to treat well."],
        ["At school entry only", "A specific age threshold is given."],
        ["Only if a parent is affected", "Screening is universal."]]),

 dict(topic="Amblyopia", io=IO_A, lead="treatment", cite=D % 30,
  q="A 4-year-old boy has amblyopia of the left eye. What is the treatment?",
  opts=[["Patch or blur the good right eye", "Correct. Forcing the weaker eye to work is the point."],
        ["Patch the amblyopic left eye", "That would worsen it."],
        ["Lens extraction", "That treats cataract."],
        ["Anti-VEGF injection", "That treats wet macular degeneration."],
        ["Acetazolamide", "That lowers intracranial pressure."]]),

 dict(topic="Amblyopia", io=IO_A, lead="prognosis", cite=D % 30,
  q="A mother asks when her daughter's amblyopia must be treated by. What is true?",
  opts=[["Before seven, and under five is better", "Correct. Starting earlier gives the better outcome."],
        ["Any time before adulthood", "The window closes in childhood."],
        ["Only after the eye stops growing", "Waiting loses the window."],
        ["There is no time limit", "There is a clear one."],
        ["Only in the first year of life", "The window is wider than that."]]),

 dict(topic="Amblyopia", io=IO_A, lead="patient education", cite=D % 33,
  q="An adult treated late for childhood amblyopia has good acuity but struggles with 3D films. Why?",
  opts=[["Stereo vision never developed", "Correct. The brain still uses one eye at a time."],
        ["The lens is still cloudy", "Acuity is good, so the media are clear."],
        ["He has an uncorrected refractive error", "That would blur rather than flatten depth."],
        ["His optic nerve is damaged", "Colour and acuity would suffer."],
        ["He has developed glaucoma", "That takes peripheral field."]]),

 # ---------------- cataract ----------------
 dict(topic="Cataract", io=IO_A, lead="symptom", cite=D % 36,
  q="A 72-year-old man has months of blurring and glare from oncoming headlights. Which diagnosis fits?",
  opts=[["Cataract", "Correct. Slow blurring with glare is the pattern."],
        ["Acute angle-closure glaucoma", "That is sudden and painful."],
        ["Retinal detachment", "That gives flashes and a curtain."],
        ["Optic neuritis", "That is rapid and painful on eye movement."],
        ["Amblyopia", "That is established in childhood."]]),

 dict(topic="Cataract", io=IO_A, lead="exam finding", cite=D % 36,
  q="A 79-year-old woman has a dense cataract. What is seen on ophthalmoscopy?",
  opts=[["Loss of the red reflex", "Correct, and a dense lens makes the pupil look grey or white."],
        ["A relative afferent pupillary defect", "A cataract alone does not cause one."],
        ["Disc cupping", "That is glaucoma."],
        ["A cherry-red spot", "That is arterial occlusion."],
        ["Flame haemorrhages", "Those are not a cataract sign."]]),

 dict(topic="Cataract", io=IO_A, lead="reasoning", cite=D % 36,
  q="A 75-year-old man with a cataract also has a relative afferent pupillary defect. What does that tell you?",
  opts=[["Something besides the cataract is present", "Correct. A cataract alone never causes one."],
        ["The cataract is unusually dense", "Density does not produce the defect."],
        ["Surgery will not help him", "It may still help; the defect needs separate explanation."],
        ["He has presbyopia as well", "That would not cause it."],
        ["The finding is expected", "It is not expected and needs a cause."]]),

 dict(topic="Cataract", io=IO_A, lead="classification", cite=D % 37,
  q="A 64-year-old woman has brown discoloration of the central lens and worse distance than near vision. Which cataract is this?",
  opts=[["Nuclear", "Correct, and the myopic shift is why near vision holds up."],
        ["Cortical", "That gives spoke-like peripheral opacities."],
        ["Posterior subcapsular", "That is a plate-like opacity behind the lens."],
        ["Polar cataract", "That is a paediatric type."],
        ["Zonular", "That is the commonest paediatric type."]]),

 dict(topic="Cataract", io=IO_A, lead="classification", cite=D % 36,
  q="A 46-year-old man on long-term corticosteroids has glare, trouble reading, and symptoms that ease once dilated. Which cataract is this?",
  opts=[["Posterior subcapsular", "Correct. It comes on faster and classically under fifty, with steroids or diabetes."],
        ["Nuclear cataract", "That is slower and yellows the lens centre."],
        ["Cortical", "That starts in the periphery and stays quiet."],
        ["Congenital polar", "That is present from birth."],
        ["Zonular cataract", "That is a paediatric type."]]),

 dict(topic="Cataract", io=IO_A, lead="classification", cite=D % 37,
  q="A 70-year-old woman has spoke-like opacities running in from the lens periphery. What is her main complaint once they reach the centre?",
  opts=[["Glare", "Correct. Cortical cataract is quiet until the centre is involved."],
        ["Sudden painless vision loss", "That suggests a vascular event."],
        ["Loss of colour vision", "That points to optic neuropathy."],
        ["Double vision in one eye", "Not the described complaint."],
        ["Eye pain on movement", "That suggests optic neuritis."]]),

 dict(topic="Cataract", io=IO_B, lead="classification", cite=D % 38,
  q="A newborn is found to have a cataract. Which paediatric type is commonest?",
  opts=[["Zonular", "Correct, a white opacity round the nucleus."],
        ["Polar", "Less common, though easier to spot as it is central."],
        ["Nuclear", "Not the commonest paediatric type."],
        ["Posterior lenticonus", "An uncommon posterior form."],
        ["Cortical", "That is an acquired adult pattern."]]),

 dict(topic="Cataract", io=IO_B, lead="next step", cite=D % 36,
  q="A newborn has a dense unilateral cataract. Why is surgery not deferred?",
  opts=[["To prevent amblyopia developing", "Correct. The visual system will not wait."],
        ["Because the lens will rupture", "That is not the risk."],
        ["To lower intraocular pressure", "Pressure is not the issue."],
        ["Because it will otherwise become malignant", "Cataracts do not transform."],
        ["To restore colour vision", "Colour is not the concern."]]),

 dict(topic="Cataract", io=IO_A, lead="treatment", cite=D % 39,
  q="A 77-year-old man asks what will fix his cataract. What is the answer?",
  opts=[["Surgery to replace the lens", "Correct, deferred until it interferes with daily activities."],
        ["Drops that dissolve the opacity", "No drop clears a cataract."],
        ["Stronger glasses indefinitely", "Glasses stop helping eventually."],
        ["Laser to reshape the cornea", "That treats refractive error."],
        ["Anti-VEGF injections", "Those treat wet macular degeneration."]]),

 dict(topic="Cataract", io=IO_A, lead="complication", cite=D % 39,
  q="A 68-year-old woman's vision clouds again two years after cataract surgery. What has happened, and what treats it?",
  opts=[["Posterior capsule opacification, treated by laser", "Correct. Residual lens epithelial cells cloud the capsule."],
        ["The cataract has regrown", "The lens is gone; it cannot regrow."],
        ["Macular degeneration has started", "That distorts the centre rather than clouding."],
        ["The implant has dislocated", "Not the described picture."],
        ["Glaucoma has developed", "That takes the peripheral field."]]),

 # ---------------- retinoblastoma ----------------
 dict(topic="Retinoblastoma", io=IO_B, lead="diagnosis", cite=D % 41,
  q="A mother notices one pupil looks white in photographs of her 2-year-old. What must be excluded?",
  opts=[["Retinoblastoma", "Correct. Leukocoria is retinoblastoma until proven otherwise."],
        ["Amblyopia", "That does not whiten the pupil."],
        ["Strabismus alone", "Misalignment can occur but does not explain leukocoria."],
        ["Conjunctivitis", "That reddens the surface."],
        ["Refractive error", "That has no effect on the reflex."]]),

 dict(topic="Retinoblastoma", io=IO_B, lead="screening", cite=D % 42,
  q="Which examination should a primary care clinician perform on every infant?",
  opts=[["The red reflex", "Correct, to catch leukocoria and strabismus early."],
        ["Tonometry", "Not a routine infant test."],
        ["Perimetry", "An infant cannot perform it."],
        ["Fluorescein angiography", "That is a specialist study."],
        ["Slit lamp examination", "Not routine in primary care."]]),

 dict(topic="Retinoblastoma", io=IO_A, lead="reasoning", cite=D % 42,
  q="A 3-year-old has a retinal mass suspicious for retinoblastoma. Why is biopsy avoided?",
  opts=[["It risks seeding tumour cells", "Correct, so diagnosis rests on examination and imaging."],
        ["The tissue is too small to sample", "Size is not the reason."],
        ["Pathology cannot identify it", "Pathology could, but the risk forbids it."],
        ["Anaesthesia is unsafe at that age", "Anaesthesia is not the objection."],
        ["It would damage the optic nerve", "Seeding is the stated risk."]]),

 dict(topic="Retinoblastoma", io=IO_B, lead="next step", cite=D % 42,
  q="A newborn has a parent who had retinoblastoma. When should the baby be seen?",
  opts=[["Within the first eight weeks of life", "Correct, by someone experienced in retinoblastoma."],
        ["At the one-year check", "Far too late for a known family history."],
        ["Only if the red reflex is abnormal", "A normal reflex does not exclude it."],
        ["At school entry", "Much too late."],
        ["Only if vision seems poor", "Screening precedes symptoms."]]),

 dict(topic="Retinoblastoma", io=IO_A, lead="prognosis", cite=D % 42,
  q="Parents of a child with treated retinoblastoma ask about outcome. What is true?",
  opts=[["Over 95 percent five-year survival when treated", "Correct, against near-certain death untreated."],
        ["Survival is poor even with treatment", "Treated survival is high."],
        ["It is always fatal", "Untreated it nearly is; treated it is not."],
        ["Treatment only preserves vision", "Survival, not just vision, is at stake."],
        ["Recurrence is expected lifelong", "No recurrence at five years counts as cured."]]),

 # ---------------- uveal melanoma and nevus ----------------
 dict(topic="Uveal melanoma", io=IO_A, lead="epidemiology", cite=D % 45,
  q="A 61-year-old man is told he has the commonest eye cancer in adults. Which is it?",
  opts=[["Uveal melanoma", "Correct, arising from melanocytes of the choroid, ciliary body or iris."],
        ["Retinoblastoma", "That is a childhood tumour."],
        ["Conjunctival melanoma", "A distinct and less common entity."],
        ["Squamous cell carcinoma", "Not the commonest adult intraocular cancer."],
        ["Choroidal haemangioma", "That is benign."]]),

 dict(topic="Uveal melanoma", io=IO_A, lead="exam finding", cite=D % 45,
  q="A 57-year-old woman has a pigmented iris lesion. Which feature most suggests melanoma over a freckle?",
  opts=[["A prominent feeder vessel", "Correct. Tumours build their own blood supply; freckles do not."],
        ["Location on the inferior iris", "Both sit there."],
        ["Brown colour", "Both can be brown."],
        ["Presence since puberty", "Long-standing favours a nevus."],
        ["A flat surface", "Flatness favours a nevus."]]),

 dict(topic="Uveal melanoma", io=IO_A, lead="exam finding", cite=D % 45,
  q="A 63-year-old man has an iris lesion. Which dimensions raise concern for melanoma?",
  opts=[["Over 3 mm across and over 1 mm deep", "Correct. A nevus is usually smaller and flat."],
        ["Under 1 mm across", "That is reassuring."],
        ["Any size, if bilateral", "Bilateral multifocal pigment favours freckles."],
        ["Only lesions over 10 mm", "The threshold is much lower."],
        ["Size does not matter", "Size is a key discriminator."]]),

 dict(topic="Uveal melanoma", io=IO_A, lead="prognosis", cite=D % 46,
  q="A 59-year-old woman with uveal melanoma asks where it would spread. Which site is commonest?",
  opts=[["The liver", "Correct, and surveillance is directed there."],
        ["The brain", "Not the commonest site for this tumour."],
        ["Bone", "Not the commonest site."],
        ["The contralateral eye", "Spread is systemic, not to the other eye."],
        ["The lungs", "Less common than the liver here."]]),

 dict(topic="Uveal melanoma", io=IO_A, lead="treatment", cite=D % 46,
  q="A 66-year-old man needs treatment for choroidal melanoma. Which is used most often now?",
  opts=[["Radiation therapy", "Correct, and it spares the globe where removal once did not."],
        ["Enucleation in every case", "Removal is now less common."],
        ["Topical chemotherapy drops", "Not a treatment for an intraocular tumour."],
        ["Observation alone", "A melanoma is treated."],
        ["Laser photocoagulation alone", "Not the mainstay here."]]),

 dict(topic="Iris nevus", io=IO_A, lead="management", cite=D % 49,
  q="A 30-year-old woman has a flat 2 mm pigmented spot on the inferior iris, unchanged for years. What is the plan?",
  opts=[["Refer to ophthalmology for surveillance", "Correct. It is likely benign, but growth has to be excluded."],
        ["Reassure with no follow-up", "It still needs monitoring."],
        ["Refer urgently for enucleation", "Wildly disproportionate for a nevus."],
        ["Start radiation therapy", "That treats melanoma."],
        ["Biopsy it in clinic", "Iris lesions are not biopsied in primary care."]]),

 dict(topic="Iris nevus", io=IO_A, lead="differential", cite=D % 48,
  q="A 12-year-old boy has bilateral tan iris nodules and multiple café-au-lait patches. What do the nodules represent?",
  opts=[["Lisch nodules of neurofibromatosis type 1", "Correct, bilateral, multifocal and non-progressive."],
        ["Iris melanoma", "That is unilateral and grows."],
        ["Iris freckles", "Freckles are flat surface pigment, not nodules."],
        ["Melanocytoma", "That is a solitary dark lesion."],
        ["Conjunctival nevus", "That sits on the conjunctiva, not the iris."]]),

 dict(topic="Conjunctival melanoma", io=IO_A, lead="differential", cite=D % 52,
  q="A 60-year-old man has a raised vascular pigmented lesion on the conjunctiva. Which favours melanoma over a nevus?",
  opts=[["It is raised and vascular", "Correct. A conjunctival nevus is flat and often has clear cysts."],
        ["It contains small clear cysts", "Cysts favour a nevus."],
        ["It has been present since childhood", "Long standing favours a nevus."],
        ["It is bilateral", "Bilateral symmetric pigment suggests racial melanosis."],
        ["It is flat", "Flatness favours a nevus."]]),
]
