# CMS I Lecture 5 (Dermatological Infestations) — SET 1 pool B (objective style).
# Bedbugs, fleas and tungiasis, Hymenoptera, caterpillars, cutaneous larva migrans.
#
# Options drafted at matched lengths. Correct answer is ALWAYS written first
# (c=0); the partition script rotates.
SRC = "CMS I Dermatological Infestations - Shahsv.pptx"
def c(n): return f"{SRC}, Slide {n}"

IOA = "Objective a — Etiologies, epidemiology, risk factors, manifestations, differential diagnosis, testing, management, referrals, education and prognosis of dermatological infestations"
IOB = "Objective b — Differentiate primary from secondary skin lesions"
IOC = "Objective c — Medical care strategies across infant, child, adolescent, adult and elderly populations"

POOL_B = [
 dict(topic="Bedbugs", io=IOA,
   q="What draws bedbugs out to feed, and where do they hide during the day?",
   opts=[
     ["Warmth and carbon dioxide draw them out; they hide in cracks and crevices of headboards and picture frames",
      "Correct — they also hide behind loose wallpaper and in other dark places."],
     ["Light and movement draw them out; they hide in the seams of clothing worn close to the skin",
      "Clothing seams are where body lice and their nits are found."],
     ["Perspiration and body odour draw them out; they burrow into the stratum corneum of the skin",
      "Burrowing into the stratum corneum describes the scabies mite."],
     ["Blood on the skin surface draws them out; they live permanently attached to the hair shaft",
      "Attachment to the hair shaft describes lice and their nits."]],
   c=0, cite=c(32)),

 dict(topic="Bedbugs", io=IOA,
   q="How often do bedbugs need a blood meal, and how long can they survive without one?",
   opts=[
     ["Every five to ten days, but they can survive for up to a year",
      "Correct, which is why an unoccupied room does not clear an infestation."],
     ["Every one to two days, and they die within a week without one",
      "That underestimates both the interval and the survival."],
     ["Once a month, and they can survive for up to three months",
      "That is not the interval the lecture gives."],
     ["Twice daily, and they cannot survive more than forty-eight hours",
      "That is far more frequent than described."]],
   c=0, cite=c(32)),

 dict(topic="Bedbugs", io=IOA,
   q="What is the classic pattern of bedbug bites?",
   opts=[
     ["Multiple painless bites grouped in a linear row of three, called breakfast, lunch and dinner",
      "Correct — wheals and papules with a haemorrhagic punctum, and blood flecks on bed linen."],
     ["A single painful bite followed within thirty minutes by cramping abdominal pain and spasms",
      "That describes a black widow spider bite."],
     ["A serpentine raised trail that advances two to three centimetres each day with intense itch",
      "That describes cutaneous larva migrans."],
     ["Erythematous papules arranged in linear streaks after contact with a caterpillar's hairs",
      "That describes gypsy moth caterpillar dermatitis."]],
   c=0, cite=c(33)),

 dict(topic="Bedbugs", io=IOA,
   q="How is a bedbug infestation diagnosed and managed?",
   opts=[
     ["Diagnosis is by physical examination; management is symptomatic with a professional exterminator required",
      "Correct — topical antiseptic or antibiotic for secondary infection, steroids or antihistamines for itch."],
     ["Diagnosis is by skin scraping under mineral oil; management is topical permethrin applied overnight",
      "That is the approach to scabies."],
     ["Diagnosis is by dermoscopy showing ovoid eggs; management is surgical excision or cryotherapy",
      "That is the approach to tungiasis."],
     ["Diagnosis is by serology; management is oral doxycycline for ten to fourteen days",
      "That is the approach to Lyme disease."]],
   c=0, cite=c(35)),

 dict(topic="Fleas and tungiasis", io=IOA,
   q="What is tungiasis?",
   opts=[
     ["Infestation caused by an adult female flea penetrating human skin to lay her eggs",
      "Correct — it is caused by the family Tungidae."],
     ["Infestation caused by an animal hookworm larva migrating through human epidermis",
      "That describes cutaneous larva migrans."],
     ["Infestation caused by a mite tunnelling through the stratum corneum of the skin",
      "That describes scabies."],
     ["Infestation caused by a flatworm larva penetrating skin during freshwater exposure",
      "That describes cercarial dermatitis."]],
   c=0, cite=c(37)),

 dict(topic="Fleas and tungiasis", io=IOA,
   q="Which diseases do rat fleas and cat fleas transmit?",
   opts=[
     ["Rat fleas transmit bubonic plague; cat fleas are a vector for bubonic plague and endemic typhus",
      "Correct — both belong to the family Pulicidae."],
     ["Rat fleas transmit Lyme disease; cat fleas are a vector for Rocky Mountain spotted fever",
      "Those are both tick-borne rather than flea-borne."],
     ["Rat fleas transmit tungiasis; cat fleas are a vector for cutaneous larva migrans",
      "Tungiasis is caused by a different flea family and larva migrans by hookworms."],
     ["Rat fleas transmit endemic typhus only; cat fleas transmit no human disease at all",
      "Cat fleas are a vector for two named diseases."]],
   c=0, cite=c(37)),

 dict(topic="Fleas and tungiasis", io=IOA,
   q="How does tungiasis present?",
   opts=[
     ["Papules enlarging over weeks to 4 to 10 mm, sometimes a yellow translucent nodule, on the feet and web spaces",
      "Correct — pain, pruritus and even autoamputation of toes can follow."],
     ["Linear or clustered urticarial papules usually on the lower legs, with bullae in sensitised people",
      "That describes the reaction to Pulicidae flea bites."],
     ["A row of grouped painless bites with a haemorrhagic punctum appearing overnight",
      "That describes bedbug bites."],
     ["A slowly advancing serpentine trail on the foot with intense pruritus for weeks",
      "That describes cutaneous larva migrans."]],
   c=0, cite=c(38)),

 dict(topic="Fleas and tungiasis", io=IOA,
   q="How is tungiasis diagnosed and managed?",
   opts=[
     ["Dermoscopy visualises ovoid eggs; treatment is surgical excision or cryotherapy with tetanus prophylaxis",
      "Correct — systemic antibiotics are also given."],
     ["Skin scraping under mineral oil shows the organism; treatment is overnight topical permethrin",
      "That is the approach to scabies."],
     ["Serology detects antibodies to the organism; treatment is oral doxycycline for ten days",
      "That is the approach to tick-borne infection."],
     ["Physical examination alone is diagnostic; treatment is symptomatic with an exterminator",
      "That is the approach to bedbugs."]],
   c=0, cite=c(40)),

 dict(topic="Fleas and tungiasis", io=IOA,
   q="How is tungiasis prevented?",
   opts=[
     ["Avoid walking barefoot or in sandals along beaches in endemic areas, and avoid sitting in the sand",
      "Correct — Nigeria, the Caribbean, India and Brazil are the named examples."],
     ["Avoid direct head-to-head contact and do not share combs, brushes or hair accessories",
      "That prevents head lice."],
     ["Wear protective clothing, perform tick checks and apply repellent every two hours",
      "That prevents tick-borne illness."],
     ["Engage an exterminator and inspect second-hand mattresses before bringing them home",
      "That prevents bedbug infestation."]],
   c=0, cite=c(40)),

 dict(topic="Hymenoptera", io=IOA,
   q="How should a honeybee sting be removed and why?",
   opts=[
     ["Scrape it off with a card edge or dull knife held parallel to the skin, as fast as possible",
      "Correct — the barbed ovipositor stays impaled and continues to pump venom."],
     ["Grasp it with fine forceps and pull it straight out with steady traction on the shaft",
      "Scraping parallel to the surface is the described technique."],
     ["Leave it in place, since removing it releases the remaining venom into the tissue",
      "It should be removed as fast as possible."],
     ["Apply ice for twenty minutes first, then remove it once the swelling has settled",
      "Delay allows more venom to be pumped in."]],
   c=0, cite=c(42)),

 dict(topic="Hymenoptera", io=IOA,
   q="What is characteristic of fire ant venom and behaviour?",
   opts=[
     ["The venom induces mast cell degranulation, and the ants usually attack in groups",
      "Correct — flushing, pruritus, hives, abdominal pain, nausea, vomiting and diarrhoea can follow."],
     ["The venom is a neurotoxin, and the insects sting only when their nest is disturbed",
      "Alpha-latrotoxin is the neurotoxin of the black widow spider."],
     ["The venom is injected through hollow hairs, and contact occurs passively on brushing",
      "That mechanism belongs to caterpillars."],
     ["The venom is cytotoxic, producing central necrosis with a surrounding blanched rim",
      "That describes the brown recluse spider bite."]],
   c=0, cite=c(42)),

 dict(topic="Hymenoptera", io=IOA,
   q="What proportion of Hymenoptera stings produce a generalised systemic reaction?",
   opts=[
     ["Between 0.4% and 3%",
      "Correct — anaphylactic reactions include urticaria, angio-oedema and bronchospasm."],
     ["Between 10% and 15%",
      "That substantially overstates the stated range."],
     ["Between 25% and 30%",
      "That is far higher than the stated range."],
     ["Fewer than 1 in 10,000",
      "That understates the stated range."]],
   c=0, cite=c(43)),

 dict(topic="Hymenoptera", io=IOA,
   q="How does a severe local reaction to a sting differ from the typical reaction?",
   opts=[
     ["It produces extensive oedema at the site with induration lasting up to one week",
      "Correct — the typical reaction is immediate burning, erythema, swelling and urticaria."],
     ["It produces generalised urticaria, angio-oedema and bronchospasm within minutes",
      "That describes a generalised systemic reaction."],
     ["It produces central necrosis with an eschar forming between days five and seven",
      "That describes a brown recluse bite."],
     ["It produces cramping abdominal pain and muscle spasm within thirty minutes",
      "That describes a black widow bite."]],
   c=0, cite=c(43)),

 dict(topic="Hymenoptera", io=IOA,
   q="Which long-term measures are offered after a sting-induced anaphylactic reaction?",
   opts=[
     ["Carry an epinephrine auto-injector, and desensitisation therapy where the skin test is positive",
      "Correct — immunotherapy is specified for fire ant hypersensitivity."],
     ["Carry oral antihistamines, with a short course of prednisolone kept for emergencies",
      "Those do not replace epinephrine in anaphylaxis."],
     ["Carry a topical corticosteroid, with local anaesthetic injection for pain control",
      "Those address mild local cutaneous reactions."],
     ["Carry oral doxycycline, to be started at the first sign of any systemic symptoms",
      "Antibiotics have no role in a venom reaction."]],
   c=0, cite=c(44)),

 dict(topic="Caterpillars", io=IOA,
   q="By which mechanisms do caterpillars produce skin disease?",
   opts=[
     ["Mechanical irritation by pointed hairs, toxin injection through hollow hairs, and hypersensitivity to hairs",
      "Correct — the aggregate of these effects is called lepidopterism."],
     ["Direct penetration of the skin by larvae that then migrate through the epidermal layer",
      "That describes cutaneous larva migrans."],
     ["Injection of a neurotoxin through a modified ovipositor when the insect is threatened",
      "That describes Hymenoptera stings."],
     ["Burrowing into the stratum corneum where the organism deposits its eggs and faeces",
      "That describes the scabies mite."]],
   c=0, cite=c(46)),

 dict(topic="Caterpillars", io=IOA,
   q="Which caterpillar is described as the most poisonous, and what does its sting produce?",
   opts=[
     ["The asp or puss caterpillar, producing an intensely painful sting and train-track purpura",
      "Correct. The gypsy moth caterpillar causes erucism and processionary caterpillars cause anaphylaxis."],
     ["The gypsy moth caterpillar, producing pruritic papules arranged in linear streaks",
      "That is erucism, or caterpillar dermatitis, and is not the most poisonous."],
     ["The processionary caterpillar, producing urticaria, angio-oedema and anaphylaxis",
      "That species causes those reactions but is not named the most poisonous."],
     ["The tarantula, producing pruritus and granulomatous reactions from embedded hairs",
      "A tarantula is a spider rather than a caterpillar."]],
   c=0, cite=c(47)),

 dict(topic="Caterpillars", io=IOA,
   q="Which specific physical measure is used in caterpillar exposure?",
   opts=[
     ["Stripping the hairs off the skin with adhesive tape",
      "Correct, alongside symptomatic therapy and antivenom for certain categories."],
     ["Scraping the site with a card edge held parallel to the skin",
      "That is the technique for removing a honeybee stinger."],
     ["Applying blue or black ink and looking for a zigzag line",
      "That is the burrow ink test for scabies."],
     ["Combing the area after applying a hair moisturiser for two minutes",
      "That is a physical method used for head lice."]],
   c=0, cite=c(48)),

 dict(topic="Caterpillars", io=IOA,
   q="Which symptomatic treatments are listed for caterpillar exposure?",
   opts=[
     ["Systemic antihistamines, menthol or camphor preparations, potent topical or systemic steroids, and analgesia",
      "Correct — oral or parenteral narcotic analgesics are named for pain."],
     ["Overnight topical permethrin to the whole skin surface with a second application one week later",
      "That is the treatment of scabies."],
     ["Oral albendazole for three days, with repeated courses if folliculitis is present",
      "That is the treatment of cutaneous larva migrans."],
     ["Calcium gluconate, muscle relaxants and benzodiazepines with tetanus vaccination",
      "That is envenomation treatment for a black widow spider bite."]],
   c=0, cite=c(48)),

 dict(topic="Cutaneous larva migrans", io=IOA,
   q="What causes cutaneous larva migrans and how is it acquired?",
   opts=[
     ["Larvae of animal hookworms, mostly from dogs and cats, acquired from sand or soil with animal faeces",
      "Correct — the infected human is a dead-end host."],
     ["Larvae of parasitic flatworms released by snails, acquired by swimming in fresh water",
      "That describes cercarial dermatitis."],
     ["An adult female flea burrowing into the skin, acquired by walking barefoot on beaches",
      "That describes tungiasis."],
     ["A mite tunnelling in the stratum corneum, acquired by prolonged close physical contact",
      "That describes scabies."]],
   c=0, cite=c(50)),

 dict(topic="Cutaneous larva migrans", io=IOA,
   q="Describe the classic lesion of cutaneous larva migrans.",
   opts=[
     ["An erythematous, raised, vesicular, linear or serpentine trail advancing 2 to 3 cm each day",
      "Correct — intensely pruritic and painful, lasting two to eight weeks, with rare systemic symptoms."],
     ["A thin thread-like linear or J-shaped tunnel 1 to 10 mm long in the interdigital webs",
      "That is the scabies burrow."],
     ["A large expanding round lesion over 5 cm with central clearing at the site of a bite",
      "That is erythema migrans in Lyme disease."],
     ["Erythematous papules in linear streaks after brushing against a caterpillar's hairs",
      "That is caterpillar dermatitis."]],
   c=0, cite=c(51)),

 dict(topic="Cutaneous larva migrans", io=IOA,
   q="What is hookworm folliculitis?",
   opts=[
     ["Follicular papules and pustules confined to one location, usually the buttock",
      "Correct — it may need repeated courses of treatment."],
     ["Follicular pustules over the trunk and buttocks after hot tub exposure",
      "That is Pseudomonas folliculitis from the previous lecture."],
     ["Pustules on an erythematous base each pierced by a single central hair shaft",
      "That is ordinary bacterial folliculitis."],
     ["Indurated crusted nodules on the trunk of an infant with heavy infestation",
      "Those nodules occur in infantile scabies."]],
   c=0, cite=c(51)),

 dict(topic="Cutaneous larva migrans", io=IOA,
   q="How is cutaneous larva migrans treated?",
   opts=[
     ["Albendazole 400 mg by mouth daily for three days, or ivermectin 200 micrograms per kilogram for one to two days",
      "Correct — topical therapy is less effective and surgical excision or cryotherapy is not recommended."],
     ["Topical permethrin applied overnight to the whole skin surface with a repeat application at one week",
      "That is the treatment of scabies."],
     ["Surgical excision or cryotherapy of the advancing edge of the lesion under local anaesthesia",
      "Those are specifically not recommended for this condition."],
     ["Doxycycline 100 mg by mouth twice daily for a course of ten to fourteen days",
      "That regimen belongs to tick-borne illness."]],
   c=0, cite=c(54)),

 dict(topic="Cutaneous larva migrans", io=IOA,
   q="What does light microscopy with mineral oil show in cutaneous larva migrans?",
   opts=[
     ["Live and dead larvae, particularly in patients with folliculitis",
      "Correct — histology shows larvae with an eosinophilic infiltrate."],
     ["Mites, ova and faecal pellets scraped from an unexcoriated burrow",
      "That is what the scabies scraping shows."],
     ["Ovoid eggs visible within the lesion when viewed on dermoscopy",
      "That describes the diagnosis of tungiasis."],
     ["Nits attached at the base of hairs plucked from the affected area",
      "That describes the confirmation of pubic lice."]],
   c=0, cite=c(53)),
]
