# CMS I Lecture 4 (Cutaneous Bacterial Infections) — SET 1 pool B (objective style).
# Furuncles, carbuncles, hidradenitis suppurativa, erythrasma, impetigo.
#
# Options drafted at matched lengths. Correct answer is ALWAYS written first
# (c=0); the partition script rotates.
SRC = "4.  Cutaneous Bacterial Infections.pptx"
def c(n): return f"{SRC}, Slide {n}"

IOA = "Objective a — Etiologies, epidemiology, risk factors, manifestations, differential diagnosis, testing, management, referrals, education and prognosis for cutaneous bacterial infections"
IOB = "Objective b — Unique considerations of methicillin-resistant Staphylococcus aureus skin infections"
IOC = "Objective c — Differentiate primary from secondary bacterial infection of the skin"
IOD = "Objective d — Medical care strategies across infant, adolescent, adult and elderly populations"

POOL_B = [
 dict(topic="Furuncles and carbuncles", io=IOA,
   q="What is a furuncle?",
   opts=[
     ["A deep-seated abscess of a hair follicle and the adjacent subcutaneous tissue",
      "Correct. Staphylococcus aureus is the commonest organism."],
     ["An inflammation of the follicle wall and ostia forming a superficial pustule",
      "That is folliculitis, which is confined to the follicle."],
     ["A collection of purulent material seeded by traumatic inoculation of bacteria",
      "That is an abscess, which arises from inoculation rather than a follicle."],
     ["An infection of the upper dermis extending into superficial skin lymphatics",
      "That is erysipelas."]],
   c=0, cite=c(59)),

 dict(topic="Furuncles and carbuncles", io=IOA,
   q="What is a carbuncle?",
   opts=[
     ["Two or more confluent furuncles with separate heads",
      "Correct — interconnecting furuncles arising in several hair follicles."],
     ["A single furuncle larger than five millimetres across",
      "Size alone does not make a furuncle a carbuncle."],
     ["A furuncle that has become secondarily infected with yeast",
      "Secondary yeast infection is not what defines it."],
     ["A furuncle that has failed to respond to oral antibiotics",
      "Treatment response is not part of the definition."]],
   c=0, cite=c(59)),

 dict(topic="Furuncles and carbuncles", io=IOA,
   q="Where do furuncles and carbuncles typically occur?",
   opts=[
     ["In areas prone to friction or minor trauma — back of neck, face, axillae and buttocks",
      "Correct. Shaving and insect bites are named traumatic risk factors."],
     ["In intertriginous areas kept warm and moist — inner thighs, scrotum and toe webs",
      "That is the distribution of erythrasma."],
     ["In areas bearing apocrine glands — axilla, groin, breasts and perineum",
      "That is the distribution of hidradenitis suppurativa."],
     ["On the lower extremity in the great majority of cases, rarely bilateral",
      "That is the distribution of cellulitis and erysipelas."]],
   c=0, cite=c(61)),

 dict(topic="Furuncles and carbuncles", io=IOA,
   q="Which three factors predispose to recurrent furunculosis?",
   opts=[
     ["Obesity, diabetes and nasal carriage of Staphylococcus aureus",
      "Correct. Immunocompromise and trauma are the broader risk categories."],
     ["Smoking, hot weather and obstruction of the apocrine ducts",
      "Those are predisposing factors for hidradenitis suppurativa."],
     ["Impaired lymphatic drainage, tinea pedis and previous impetigo",
      "Those are risk factors for erysipelas."],
     ["Manicure, ingrown nail and the habit of biting the nails",
      "Those are predisposing factors for acute paronychia."]],
   c=0, cite=c(62)),

 dict(topic="Furuncles and carbuncles", io=IOA,
   q="How does a carbuncle differ from a furuncle at presentation?",
   opts=[
     ["It is extremely painful and more often produces malaise, chills and fever",
      "Correct. Systemic symptoms are more common with a carbuncle."],
     ["It is painless and produces no systemic symptoms of any kind at all",
      "Carbuncles are described as extremely painful."],
     ["It presents as a single opening with a surrounding zone of erythema",
      "That is the furuncle. Carbuncles have sieve-like multiple openings."],
     ["It presents as a plaque raised above the skin with a demarcated edge",
      "That describes erysipelas."]],
   c=0, cite=c(63)),

 dict(topic="Furuncles and carbuncles", io=IOA,
   q="Describe the physical findings of a carbuncle.",
   opts=[
     ["Several loculated abscesses, superficial pustules, necrotic plugs and sieve-like draining openings",
      "Correct — a deeper infection made of interconnecting furuncles in several follicles."],
     ["A single firm tender nodule with one opening and a surrounding zone of erythema",
      "That is the furuncle rather than the carbuncle."],
     ["Nodules, sinus tracts and meshlike scarring in the axilla or the perineum",
      "That describes hidradenitis suppurativa."],
     ["A well-demarcated raised plaque with red streaks extending toward a lymph node",
      "That describes erysipelas with lymphatic involvement."]],
   c=0, cite=c(63)),

 dict(topic="Furuncles and carbuncles", io=IOA,
   q="When are oral antibiotics indicated for a furuncle?",
   opts=[
     ["A single lesion over 5 mm, a lesion under 5 mm that fails drainage, expanding cellulitis, immunocompromise or endocarditis risk",
      "Correct. No antibiotics are needed if the patient is afebrile with a single lesion under 5 mm."],
     ["Any furuncle at all, since Staphylococcus aureus is the commonest cause and can seed the bloodstream",
      "Warm compresses alone suffice for small furuncles."],
     ["Only after culture has confirmed methicillin-resistant Staphylococcus aureus in the drained material",
      "Empiric therapy is started on clinical grounds before culture returns."],
     ["Only when the patient is febrile, since fever is what separates local from systemic infection",
      "Several non-febrile indications are listed."]],
   c=0, cite=c(65)),

 dict(topic="Furuncles and carbuncles", io=IOB,
   q="Which oral antibiotics are used for furuncles and carbuncles when methicillin-resistant Staphylococcus aureus is cultured or suspected?",
   opts=[
     ["Trimethoprim-sulfamethoxazole, clindamycin or doxycycline",
      "Correct. Empiric therapy for the sensitive organism is dicloxacillin or cephalexin."],
     ["Dicloxacillin, cephalexin or amoxicillin-clavulanate",
      "Those are the empiric agents for methicillin-sensitive disease."],
     ["Penicillin V, erythromycin or clarithromycin",
      "Penicillin V is used for erysipelas and the macrolides for erythrasma."],
     ["Ciprofloxacin, levofloxacin or moxifloxacin",
      "Ciprofloxacin is named for resistant Pseudomonas folliculitis."]],
   c=0, cite=c(66)),

 dict(topic="Furuncles and carbuncles", io=IOA,
   q="What is the mainstay of treatment for a carbuncle?",
   opts=[
     ["Incision and drainage, with endocarditis prophylaxis for at-risk patients",
      "Correct, alongside oral antibiotics chosen for the likely organism."],
     ["Warm compresses alone, since most carbuncles drain without intervention",
      "Warm compresses are usually sufficient only for small furuncles."],
     ["Oral antibiotics alone, since drainage risks seeding the bloodstream",
      "Drainage is the mainstay rather than a hazard to avoid."],
     ["Wide surgical excision of the affected area under general anaesthesia",
      "Wide excision is the curative option in hidradenitis suppurativa."]],
   c=0, cite=c(67)),

 dict(topic="Hidradenitis suppurativa", io=IOA,
   q="What is hidradenitis suppurativa and where does it occur?",
   opts=[
     ["Inflammation of cutaneous apocrine glands, most often in the axilla, and also groin, breasts or perineum",
      "Correct. It is also called acne inversa because it resembles acne vulgaris."],
     ["Inflammation of the eccrine sweat glands, most often on the palms, soles and the axillary vault",
      "Eccrine glands are the ones involved in hyperhidrosis, not this condition."],
     ["Infection of the upper third of the stratum corneum in intertriginous skin under heat and humidity",
      "That describes erythrasma."],
     ["Infection of the hair follicle extending into the adjacent subcutaneous fat of the neck and back",
      "That describes a furuncle."]],
   c=0, cite=c(68)),

 dict(topic="Hidradenitis suppurativa", io=IOA,
   q="Which factors predispose to hidradenitis suppurativa?",
   opts=[
     ["Hot weather, excessive perspiration, obesity, apocrine duct obstruction, secondary infection and smoking",
      "Correct. Smoking cessation is described as essential in management."],
     ["Cold dry weather, low body weight, occupational chemical exposure and repeated hand immersion",
      "Repeated immersion is a predisposing factor for chronic paronychia."],
     ["Impaired lymphatic drainage, tinea pedis, obesity and any pre-existing skin infection",
      "Those are the risk factors for erysipelas."],
     ["Puberty, androgen excess, genetics, lithium therapy and acnegenic mineral oil exposure",
      "Those are the predisposing factors for acne vulgaris."]],
   c=0, cite=c(68)),

 dict(topic="Hidradenitis suppurativa", io=IOA,
   q="Which three elements are required to diagnose hidradenitis suppurativa?",
   opts=[
     ["Typical lesions, characteristic distribution in axilla and groin, and recurrence more than twice in six months",
      "Correct. It is primarily a clinical diagnosis; biopsy is not usually required."],
     ["Positive bacterial culture, characteristic distribution over the trunk, and failure of oral antibiotic therapy",
      "Culture and treatment failure are not part of the diagnostic criteria."],
     ["A biopsy showing apocrine gland destruction, raised inflammatory markers, and a family history of disease",
      "Biopsy is not usually required to make the diagnosis."],
     ["Coral-red fluorescence under a Wood's lamp, intertriginous distribution, and a history of diabetes mellitus",
      "That fluorescence is the diagnostic finding in erythrasma."]],
   c=0, cite=c(74)),

 dict(topic="Hidradenitis suppurativa", io=IOA,
   q="Which lesion type is characteristic of hidradenitis suppurativa on examination?",
   opts=[
     ["The double comedone — a blackhead with two or more openings",
      "Correct, alongside nodules, sinus tracts, abscesses and meshlike scarring."],
     ["The honey-coloured adherent crust overlying a superficial erosion",
      "That is non-bullous impetigo."],
     ["The follicular pustule pierced by a single central hair shaft",
      "That is folliculitis."],
     ["The tense clear bulla that leaves a collarette after rupture",
      "That is bullous impetigo."]],
   c=0, cite=c(70)),

 dict(topic="Hidradenitis suppurativa", io=IOA,
   q="Which preventive measures are advised in hidradenitis suppurativa?",
   opts=[
     ["Avoid heat, cleanse daily with antibacterial soap or benzoyl peroxide wash, lose weight, stop smoking",
      "Correct, along with avoiding constrictive clothing and considering laser hair removal."],
     ["Avoid all water contact, apply a barrier ointment daily, gain weight and use an occlusive dressing",
      "None of those measures is recommended for this condition."],
     ["Shower immediately after any hot tub use and monitor the disinfectant levels in the water",
      "Those are the preventive measures for Pseudomonas folliculitis."],
     ["Avoid sharing towels or razors and isolate from school until treatment has been underway",
      "Those are the patient education points for impetigo."]],
   c=0, cite=c(75)),

 dict(topic="Hidradenitis suppurativa", io=IOA,
   q="Why is spironolactone used in hidradenitis suppurativa?",
   opts=[
     ["It is an aldosterone antagonist that inhibits ovarian and adrenal androgen production",
      "Correct. Combination birth control pills act by reducing gonadotropin release."],
     ["It is an immunosuppressant that blocks tumour necrosis factor in inflamed tissue",
      "That is the mechanism of infliximab."],
     ["It is a retinoid that reduces sebum production and follicular hyperkeratinisation",
      "That is oral isotretinoin, also used in this condition."],
     ["It is a corticosteroid that shrinks draining sinuses when injected into a lesion",
      "That is intralesional triamcinolone acetonide."]],
   c=0, cite=c(78)),

 dict(topic="Hidradenitis suppurativa", io=IOA,
   q="Which intervention offers the best chance of permanent cure in hidradenitis suppurativa?",
   opts=[
     ["Wide excision of the affected areas",
      "Correct. Large fluctuant cysts are meanwhile incised and drained."],
     ["Long-term systemic antibiotic therapy",
      "Long-term outcomes with systemic antibiotics are often poor."],
     ["Intralesional triamcinolone injections",
      "Those decrease the size of draining sinuses rather than cure."],
     ["Infliximab given for severe disease",
      "That is used for disease unresponsive to corticosteroids."]],
   c=0, cite=c(79)),

 dict(topic="Erythrasma", io=IOA,
   q="Which organism causes erythrasma and where does it live?",
   opts=[
     ["Corynebacterium minutissimum, invading the upper third of the stratum corneum",
      "Correct. Heat and humidity are the favourable conditions; diabetics are high risk."],
     ["Candida albicans, colonising the space beneath a separated proximal nail fold",
      "That is the organism of chronic paronychia."],
     ["Pseudomonas aeruginosa, entering the follicle from inadequately chlorinated water",
      "That organism causes hot tub folliculitis."],
     ["Staphylococcus aureus, releasing epidermolytic toxins that split the epidermis",
      "That mechanism produces bullous impetigo."]],
   c=0, cite=c(80)),

 dict(topic="Erythrasma", io=IOA,
   q="Where does erythrasma most commonly appear?",
   opts=[
     ["Inner thighs, crural region, scrotum, and between the fourth and fifth toes",
      "Correct. Less common sites are the axilla, under the breasts and intergluteal folds."],
     ["Back of the neck, face, axillae and buttocks, favouring areas of friction",
      "That is the distribution of furuncles and carbuncles."],
     ["Face and extremities, spreading by scratching and self-inoculation",
      "That is the distribution of non-bullous impetigo."],
     ["Lower extremity in most patients, almost never affecting both legs",
      "That is the distribution of cellulitis."]],
   c=0, cite=c(81)),

 dict(topic="Erythrasma", io=IOA,
   q="What is the diagnostic finding in erythrasma?",
   opts=[
     ["Coral-red fluorescence under a Wood's lamp",
      "Correct. That is what separates it from tinea and candidiasis clinically."],
     ["Green fluorescence under a Wood's lamp",
      "The colour described is coral-red."],
     ["Branching hyphae on a potassium hydroxide mount",
      "That would indicate a dermatophyte infection instead."],
     ["Gram-positive cocci in chains on a Gram stain",
      "That appearance suggests streptococcal infection."]],
   c=0, cite=c(83)),

 dict(topic="Erythrasma", io=IOA,
   q="How is erythrasma treated?",
   opts=[
     ["Topical erythromycin or clindamycin if localised, oral erythromycin or clarithromycin if widespread",
      "Correct. An antifungal cream such as miconazole is added if yeast is also present."],
     ["Topical mupirocin if localised, oral dicloxacillin or cephalexin if the disease is widespread",
      "That is the treatment ladder for impetigo."],
     ["Dilute acetic acid compresses if localised, oral ciprofloxacin if the disease is widespread",
      "That is the treatment for Pseudomonas folliculitis."],
     ["Topical antifungal alone if localised, oral fluconazole if the disease proves severe",
      "That is the treatment for chronic paronychia."]],
   c=0, cite=c(84)),

 dict(topic="Impetigo", io=IOA,
   q="What level of the skin does impetigo infect, and which organisms cause it?",
   opts=[
     ["A superficial epidermal infection, most often Staphylococcus aureus or Streptococcus pyogenes",
      "Correct. It is very contagious and autoinoculable, and common in infants and children."],
     ["An infection of the upper dermis and superficial lymphatics, most often Streptococcus pyogenes",
      "That describes erysipelas."],
     ["An infection of the deeper dermis and subcutaneous tissue, streptococcal or staphylococcal",
      "That describes cellulitis."],
     ["An infection of the tissue surrounding muscle and fascia, usually polymicrobial in nature",
      "That describes necrotizing fasciitis."]],
   c=0, cite=c(85)),

 dict(topic="Impetigo", io=IOC,
   q="What is the primary portal of entry for impetigo?",
   opts=[
     ["Minor superficial breaks in the skin such as cuts and bug bites",
      "Correct. No predisposing lesion is identified in most patients."],
     ["An occluded apocrine duct that ruptures into the surrounding dermis",
      "That mechanism belongs to hidradenitis suppurativa."],
     ["A hair follicle already inflamed by shaving or occlusive clothing",
      "That mechanism belongs to folliculitis and furuncles."],
     ["Traumatic inoculation of bacteria deep into the dermal tissues",
      "That mechanism describes abscess formation."]],
   c=0, cite=c(86)),

 dict(topic="Impetigo", io=IOA,
   q="Describe the classic appearance of non-bullous impetigo.",
   opts=[
     ["A macule evolves into a vesicle or pustule that ruptures, leaving a honey-coloured adherent crust",
      "Correct, typically on the face and extremities, with regional lymphadenopathy common."],
     ["Tense clear or cloudy bullae appear on intact skin and leave a collarette after they rupture",
      "That is bullous impetigo."],
     ["A vesicle over inflamed skin deepens into a dermal ulcer with a thick grey-yellow crust",
      "That is ecthyma."],
     ["Papules and pustules on an erythematous base, each pierced by a single central hair",
      "That is folliculitis."]],
   c=0, cite=c(87)),

 dict(topic="Impetigo", io=IOA,
   q="What causes bullous impetigo and what distinguishes it clinically?",
   opts=[
     ["Staphylococcus aureus epidermolytic toxins; bullae leave collarettes and lymphadenopathy is uncommon",
      "Correct. Bullous disease is exclusively staphylococcal."],
     ["Streptococcus pyogenes exotoxins; the crust is honey-coloured and lymphadenopathy is common",
      "That describes non-bullous impetigo, which can be streptococcal."],
     ["Pseudomonas aeruginosa endotoxins; lesions follow water exposure and spare the palms and soles",
      "That describes hot tub folliculitis."],
     ["Corynebacterium minutissimum invasion; lesions are intertriginous and fluoresce coral-red",
      "That describes erythrasma."]],
   c=0, cite=c(89)),

 dict(topic="Impetigo", io=IOA,
   q="What distinguishes ecthyma from ordinary impetigo?",
   opts=[
     ["It deepens into a dermal ulceration with a thicker grey-yellow crust, heals slowly and scars",
      "Correct, usually on the lower extremities, with regional lymphadenopathy common."],
     ["It remains confined to the epidermis, resolves within a week and never leaves a scar behind",
      "That describes ordinary impetigo rather than ecthyma."],
     ["It produces tense bullae on intact skin that rupture to leave shallow moist erosions",
      "That describes bullous impetigo."],
     ["It spreads rapidly along superficial lymphatics with a sharply demarcated raised edge",
      "That describes erysipelas."]],
   c=0, cite=c(91)),

 dict(topic="Impetigo", io=IOB,
   q="When should cultures be obtained in impetigo?",
   opts=[
     ["When the patient is at high risk for methicillin-resistant Staphylococcus aureus, or when post-streptococcal glomerulonephritis is present",
      "Correct — a health-care worker or teacher is the example given of high risk."],
     ["In every case at first presentation, since staphylococcal and streptococcal disease are treated differently",
      "Impetigo is most often diagnosed by clinical appearance alone."],
     ["Only when the lesions have failed to respond after a full two-week course of topical mupirocin",
      "Culture is directed by resistance risk and complications, not treatment duration."],
     ["Only in children under three years of age, since they are the group at highest risk of complications",
      "Post-streptococcal glomerulonephritis particularly affects three to seven year olds."]],
   c=0, cite=c(93)),

 dict(topic="Impetigo", io=IOA,
   q="Which topical agent is adequate for most cases of impetigo?",
   opts=[
     ["Mupirocin ointment, as effective as oral therapy with fewer side effects",
      "Correct — crusts should be removed before applying it."],
     ["Retapamulin ointment, the only agent specifically licensed for impetigo",
      "It is licensed for impetigo but is far more expensive than mupirocin."],
     ["Clindamycin solution, which also reduces bacterial colonisation broadly",
      "That is a topical agent for acne and pseudofolliculitis barbae."],
     ["Benzoyl peroxide wash, which suppresses growth of the causative organism",
      "That is used in acne and hidradenitis suppurativa."]],
   c=0, cite=c(94)),

 dict(topic="Impetigo", io=IOD,
   q="Which oral antibiotic is described as the drug of choice for impetigo in children?",
   opts=[
     ["Cephalexin",
      "Correct. Clindamycin is used where there is penicillin allergy."],
     ["Doxycycline",
      "Doxycycline is limited to children over eight years old."],
     ["Dicloxacillin",
      "It is listed as an option but not the paediatric drug of choice."],
     ["Erythromycin",
      "It is not the agent named for children here."]],
   c=0, cite=c(95)),

 dict(topic="Impetigo", io=IOD,
   q="What isolation advice is given for a child with impetigo?",
   opts=[
     ["Isolate until treatment has been underway for twenty-four to forty-eight hours",
      "Correct, and do not share towels, clothing, bath water, washcloths or razors."],
     ["Isolate until every crusted lesion has completely healed and the skin is clear",
      "The stated interval is tied to starting treatment, not to healing."],
     ["No isolation is needed at any point, since impetigo does not spread person to person",
      "Impetigo is described as very contagious and autoinoculable."],
     ["Isolate for a full ten days from the appearance of the very first crusted lesion",
      "That is longer than the interval given."]],
   c=0, cite=c(96)),

 dict(topic="Impetigo", io=IOA,
   q="Which complication may follow impetigo, and can antibiotics prevent it?",
   opts=[
     ["Acute post-streptococcal glomerulonephritis, which antibiotics do not prevent",
      "Correct — the immune activation usually precedes antibiotic treatment."],
     ["Acute rheumatic fever, which prompt antibiotic treatment reliably prevents",
      "Rheumatic fever is not the complication named for impetigo here."],
     ["Necrotizing fasciitis, which early oral antibiotics prevent in most cases",
      "That is a separate condition requiring surgical debridement."],
     ["Toxic shock syndrome, which topical mupirocin has been shown to prevent",
      "That is not the complication described."]],
   c=0, cite=c(97)),

 dict(topic="Impetigo", io=IOA,
   q="How does acute post-streptococcal glomerulonephritis present after impetigo?",
   opts=[
     ["Sudden oedema, haematuria with smoky or tea-coloured urine, proteinuria and hypertension",
      "Correct, especially in three to seven year olds."],
     ["Gradual weight loss, painless jaundice, pale stools and dark urine over several weeks",
      "That picture is unrelated to this complication."],
     ["Fever with a sandpaper rash, strawberry tongue and circumoral pallor within days",
      "That describes scarlet fever rather than this renal complication."],
     ["Migratory joint pain, a new heart murmur and subcutaneous nodules over the elbows",
      "That describes acute rheumatic fever."]],
   c=0, cite=c(97)),
]
