# CMS I Lecture 3 (Dermatology II) — SET 2, vignette pool B.
# Erythema nodosum, granuloma annulare, pyoderma gangrenosum, acne rosacea,
# hyperhidrosis.
#
# Options drafted at matched lengths. Lead-ins varied and tracked.
#
# Correct answer is ALWAYS written first (c=0); the partition script rotates.
SRC = "3. Dermatology  II.pptx"
def c(n): return f"{SRC}, Slide {n}"

IOA = "Objective a — Etiologies, manifestations, diagnosis and management of dermatological conditions"

POOL_B = [
 dict(topic="Erythema nodosum", io=IOA,
   q="A 27-year-old woman has tender red lumps on both shins that appeared over a week, preceded by fever and joint aches. Examination shows bilateral tender nodules 2 to 4 cm on the anterior tibial surfaces; none is ulcerated. Which is the most likely diagnosis?",
   opts=[
     ["Erythema nodosum",
      "Correct — bilateral tender anterior shin nodules that do not ulcerate, after a prodrome of fever and arthralgia."],
     ["Nodular vasculitis, also called erythema induratum",
      "That favours the posterior legs, ulcerates, and shows lobular panniculitis on biopsy."],
     ["Cellulitis of both lower legs",
      "Cellulitis is unilateral, warm and expanding, with positive cultures and antibiotic response."],
     ["Superficial thrombophlebitis of the long saphenous vein",
      "That produces a linear cord along the vein and is confirmed on ultrasound."]],
   c=0, cite=c(43)),

 dict(topic="Erythema nodosum", io=IOA,
   q="A 30-year-old woman has erythema nodosum, bilateral ankle arthritis and hilar lymphadenopathy on chest radiograph. Which is the most likely underlying diagnosis?",
   opts=[
     ["Sarcoidosis presenting as Löfgren syndrome",
      "Correct, and it has the best prognosis of all sarcoidosis presentations, with over 90% spontaneous remission."],
     ["Inflammatory bowel disease, most likely Crohn's disease",
      "Bowel disease is an association but would not produce hilar lymphadenopathy."],
     ["Primary tuberculosis with mediastinal involvement",
      "Tuberculosis is a trigger and can produce hilar changes, but the triad here is characteristic of Löfgren."],
     ["Streptococcal infection with post-infectious reaction",
      "Streptococcus is the commonest infectious trigger but does not cause hilar lymphadenopathy."]],
   c=0, cite=c(44)),

 dict(topic="Erythema nodosum", io=IOA,
   q="A 25-year-old man with erythema nodosum has no bowel or respiratory symptoms and no recent drug exposure. Which initial investigations should be ordered?",
   opts=[
     ["Antistreptolysin O titre, throat culture, chest radiograph and inflammatory markers",
      "Correct, with tuberculin or interferon gamma testing and a pregnancy test where relevant."],
     ["Serum protein electrophoresis, antinuclear and antineutrophil cytoplasmic antibodies",
      "That panel investigates pyoderma gangrenosum."],
     ["Complement C4, C1-esterase inhibitor function and serum tryptase",
      "That panel investigates urticaria and angio-oedema."],
     ["Fasting insulin, haemoglobin A1c and a full lipid profile",
      "That panel investigates acanthosis nigricans."]],
   c=0, cite=c(44)),

 dict(topic="Erythema nodosum", io=IOA,
   q="A 32-year-old woman with idiopathic erythema nodosum has painful shins interfering with work. Infection has been excluded. Which is the most appropriate treatment?",
   opts=[
     ["Rest, leg elevation, compression stockings and a nonsteroidal anti-inflammatory drug",
      "Correct — supportive care first, with potassium iodide effective for idiopathic and recurrent disease."],
     ["A prolonged course of oral antibiotics directed at streptococcus",
      "There is no evidence of active infection to treat."],
     ["Long-term systemic corticosteroids continued for several months",
      "A short course may be used once infection is excluded, but not as prolonged therapy."],
     ["Surgical excision of the most symptomatic nodules on each shin",
      "The condition is a reaction pattern and resolves; excision has no role."]],
   c=0, cite=c(44)),

 dict(topic="Granuloma annulare", io=IOA,
   q="A 9-year-old girl has a ring of small flesh-coloured bumps on the back of her hand, present for four months and not itchy. There is no scale on the border. Which is the most likely diagnosis?",
   opts=[
     ["Localised granuloma annulare",
      "Correct — the absent scale is what separates it from tinea, and localised disease predominates in children."],
     ["Tinea corporis of the dorsal hand",
      "That has a scaling border and is potassium hydroxide positive."],
     ["Necrobiosis lipoidica of early onset",
      "That produces shin plaques with a yellow-waxy atrophic centre."],
     ["Subacute cutaneous lupus erythematosus",
      "That is photodistributed with positive antinuclear and anti-Ro antibodies."]],
   c=0, cite=c(50)),

 dict(topic="Granuloma annulare", io=IOA,
   q="A 58-year-old man has hundreds of small papules over the trunk and limbs, present for a year and mildly itchy. Biopsy confirms granuloma annulare. Which is the most appropriate next step?",
   opts=[
     ["Screen for diabetes, thyroid disease and dyslipidaemia, with age-appropriate malignancy screening",
      "Correct — generalised disease in an adult over fifty carries these associations, including lymphoma."],
     ["Reassure that the condition is benign and arrange review in two years",
      "That is appropriate for localised disease but generalised disease warrants systemic workup."],
     ["Begin intralesional triamcinolone to each of the affected lesions",
      "Intralesional therapy suits symptomatic localised lesions, not hundreds of papules."],
     ["Begin oral terbinafine on the assumption of widespread dermatophyte infection",
      "The biopsy has confirmed granuloma annulare, which is not fungal."]],
   c=0, cite=c(51)),

 dict(topic="Granuloma annulare", io=IOA,
   q="The parent of a child with a single asymptomatic granuloma annulare ring asks whether treatment is needed. Which is the most appropriate counselling point?",
   opts=[
     ["It is benign and self-limiting, with about half resolving within two years, so treatment is for cosmesis or discomfort",
      "Correct, and there is no malignant potential."],
     ["It is premalignant and should be excised to prevent later transformation",
      "There is no malignant potential in granuloma annulare."],
     ["It is contagious to other children and school attendance should be limited",
      "The condition is not infectious."],
     ["It will persist unchanged lifelong unless systemic therapy is started early",
      "About half resolve spontaneously within two years."]],
   c=0, cite=c(52)),

 dict(topic="Pyoderma gangrenosum", io=IOA,
   q="A 42-year-old woman with ulcerative colitis has a rapidly enlarging painful ulcer on her shin with an undermined violaceous border. It began as a pustule. A previous surgical debridement made it substantially worse. Which is the most likely diagnosis?",
   opts=[
     ["Pyoderma gangrenosum",
      "Correct — the pathergy after debridement is nearly diagnostic, alongside the undermined violaceous border and bowel disease."],
     ["Necrotising soft tissue infection of the lower leg",
      "That would produce systemic toxicity and positive cultures, and would require urgent debridement."],
     ["Venous ulceration from chronic venous insufficiency",
      "That sits in the gaiter region with surrounding hyperpigmentation and lacks pathergy."],
     ["Squamous cell carcinoma arising in a chronic wound",
      "That has irregular margins without pathergy and is identified on biopsy."]],
   c=0, cite=c(58)),

 dict(topic="Pyoderma gangrenosum", io=IOA,
   q="A 45-year-old man has a painful expanding leg ulcer and pyoderma gangrenosum is suspected. Which is the most appropriate diagnostic approach?",
   opts=[
     ["Biopsy the ulcer edge and take wound cultures, since the diagnosis is one of exclusion",
      "Correct — there is no gold standard test, so malignancy and infection must be excluded first."],
     ["Take a punch biopsy from the ulcer centre for direct immunofluorescence",
      "Immunofluorescence addresses autoimmune blistering disease rather than this."],
     ["Order an ankle-brachial index and venous duplex ultrasound only",
      "Vascular studies help exclude a differential but cannot establish the diagnosis."],
     ["Start empirical antibiotics and reassess the ulcer in two weeks",
      "Delay allows a rapidly progressive ulcer to enlarge, and the condition is not infectious."]],
   c=0, cite=c(59)),

 dict(topic="Pyoderma gangrenosum", io=IOA,
   q="A 39-year-old woman with Crohn's disease has biopsy-supported pyoderma gangrenosum that continues to enlarge on high-dose prednisone. Which is the most appropriate next treatment?",
   opts=[
     ["Infliximab at 5 mg/kg intravenously",
      "Correct — it is approved for pyoderma gangrenosum in inflammatory bowel disease and is the biologic of choice."],
     ["Surgical debridement of the ulcer bed followed by grafting",
      "Debridement worsens the ulcer through pathergy and is specifically avoided."],
     ["Omalizumab at 300 mg subcutaneously every four weeks",
      "That is approved for refractory chronic urticaria."],
     ["Topical high-potency corticosteroid applied to the ulcer base",
      "Topical agents are used at the wound edges for pain rather than as systemic control."]],
   c=0, cite=c(60)),

 dict(topic="Pyoderma gangrenosum", io=IOA,
   q="A patient with pyoderma gangrenosum asks why the wound clinic will not debride the ulcer as they would for other wounds. Which is the most appropriate explanation?",
   opts=[
     ["The ulcer worsens with trauma, a phenomenon called pathergy, so debridement makes it larger",
      "Correct — this is the single most consequential management point in the condition."],
     ["The ulcer is infected and debridement would spread bacteria into the bloodstream",
      "The condition is not infectious despite its name."],
     ["The ulcer will heal faster if left completely undisturbed by any dressing",
      "Moist wound dressings and non-adherent contact layers are actively used."],
     ["Debridement is deferred only until systemic immunosuppression has taken effect",
      "Debridement is avoided altogether because of pathergy."]],
   c=0, cite=c(60)),

 dict(topic="Acne rosacea", io=IOA,
   q="A 46-year-old fair-skinned woman has eighteen months of central facial redness with visible fine vessels across both cheeks and the nose. She flushes with red wine and hot drinks. There are no papules, pustules or comedones. Which subtype is this?",
   opts=[
     ["Erythematotelangiectatic rosacea",
      "Correct — persistent central erythema, flushing and telangiectasias without papules or pustules, and the most common subtype."],
     ["Papulopustular rosacea in its early phase",
      "That subtype has transient central papules and pustules on a background of erythema."],
     ["Phymatous rosacea affecting the nose",
      "That produces skin thickening and nodular enlargement, predominantly in males."],
     ["Acne vulgaris of adult onset",
      "That would show open or closed comedones, which are absent in rosacea."]],
   c=0, cite=c(66)),

 dict(topic="Acne rosacea", io=IOA,
   q="A 52-year-old woman with papulopustular rosacea has not improved on topical metronidazole after eight weeks. Skin scraping shows a heavy Demodex burden. Which is the most appropriate next treatment?",
   opts=[
     ["Ivermectin 1% cream",
      "Correct — it is superior to metronidazole in Demodex-associated papulopustular disease."],
     ["Brimonidine 0.33% gel applied each morning",
      "That is an alpha-adrenergic agonist for erythema rather than for papules and pustules."],
     ["Azelaic acid 15% gel applied twice daily",
      "Effective for this subtype, but ivermectin specifically targets the demonstrated Demodex burden."],
     ["A high-potency topical corticosteroid applied twice daily",
      "Topical steroids are a listed trigger and can worsen rosacea."]],
   c=0, cite=c(69)),

 dict(topic="Acne rosacea", io=IOA,
   q="A 49-year-old man with rosacea reports gritty, red eyes and blurred vision that has worsened over two weeks. Which is the most appropriate next step?",
   opts=[
     ["Urgent ophthalmology referral for slit-lamp examination",
      "Correct — ocular rosacea with visual symptoms risks corneal scarring if untreated."],
     ["Begin topical ivermectin to the face and review in six weeks",
      "That addresses cutaneous disease and would delay assessment of the eye."],
     ["Begin sub-antimicrobial doxycycline and review in three months",
      "Doxycycline is used in ocular rosacea, but visual symptoms need urgent assessment first."],
     ["Advise artificial tears and reassess at his next routine appointment",
      "Visual change with corneal risk should not wait for routine review."]],
   c=0, cite=c(70)),

 dict(topic="Acne rosacea", io=IOA,
   q="A 41-year-old woman newly diagnosed with rosacea asks whether treatment will cure it. Which is the most appropriate counselling point?",
   opts=[
     ["It is a chronic condition that therapy controls rather than eliminates, so long-term management and daily sun protection are expected",
      "Correct, alongside a trigger diary and gentle non-irritating skincare."],
     ["A twelve-week course of oral antibiotics usually produces permanent remission",
      "Therapy controls symptoms; it does not eliminate the disease."],
     ["Avoiding alcohol alone will resolve the condition within several months",
      "Alcohol is one trigger among many and avoidance does not cure it."],
     ["Laser treatment removes the underlying disease and prevents any recurrence",
      "Laser addresses telangiectasias and erythema but not the underlying condition."]],
   c=0, cite=c(70)),

 dict(topic="Hyperhidrosis", io=IOA,
   q="A 19-year-old man reports excessive sweating of both palms and soles since early adolescence, enough to smudge his handwriting. It never occurs while he is asleep. Which is the most likely diagnosis?",
   opts=[
     ["Primary focal hyperhidrosis",
      "Correct — bilateral, focal, adolescent onset and absent during sleep are the defining features."],
     ["Secondary generalised hyperhidrosis",
      "That is generalised, may be asymmetric, and can occur at night."],
     ["Frey syndrome producing gustatory sweating",
      "That causes unilateral facial sweating triggered by eating."],
     ["Autonomic neuropathy from undiagnosed diabetes",
      "That is asymmetric with associated neurologic features."]],
   c=0, cite=c(73)),

 dict(topic="Hyperhidrosis", io=IOA,
   q="A 54-year-old man reports new generalised sweating including at night, with episodes of headache and palpitations, and his blood pressure is 178/104. Which is the most appropriate initial testing?",
   opts=[
     ["Twenty-four hour urine metanephrines and catecholamines",
      "Correct — episodic sweating with headache, palpitations and hypertension points to phaeochromocytoma."],
     ["Minor's starch-iodine test to map the distribution of sweating",
      "That maps primary focal disease rather than investigating a secondary cause."],
     ["Gravimetric measurement of axillary sweat output over five minutes",
      "That quantifies sweating rather than identifying the underlying cause."],
     ["Photopatch testing to a standard series of photoallergens",
      "That investigates photoallergic contact dermatitis."]],
   c=0, cite=c(74)),

 dict(topic="Hyperhidrosis", io=IOA,
   q="A 22-year-old woman with primary axillary hyperhidrosis has not improved with nightly aluminium chloride. Which is the most appropriate next step?",
   opts=[
     ["Glycopyrronium 2.4% cloth applied once daily, or an oral anticholinergic",
      "Correct — topical glycopyrronium is approved for axillary disease, with oral anticholinergics as second line."],
     ["Endoscopic thoracic sympathectomy to provide permanent relief",
      "That is a last resort for palmar disease refractory to everything else, and carries compensatory sweating risk."],
     ["Microwave thermolysis to destroy the axillary glands permanently",
      "That is third-line procedural therapy rather than the next step."],
     ["Reassurance that the condition is caused by anxiety and will settle",
      "Anxiety exacerbates but does not cause primary hyperhidrosis."]],
   c=0, cite=c(75)),

 dict(topic="Hyperhidrosis", io=IOA,
   q="A 27-year-old man is considering botulinum toxin for axillary hyperhidrosis. Which is the most appropriate counselling point?",
   opts=[
     ["It is effective for three to six months, so retreatment will be needed",
      "Correct — setting that expectation is specifically named in the patient education."],
     ["It permanently destroys the sweat glands in the treated area",
      "That describes microwave thermolysis rather than botulinum toxin."],
     ["It carries a risk of compensatory sweating elsewhere in over 30%",
      "That risk belongs to endoscopic thoracic sympathectomy."],
     ["It commonly causes dry mouth and urinary retention as side effects",
      "Those are the anticholinergic effects of oral therapy."]],
   c=0, cite=c(76)),

 dict(topic="Hyperhidrosis", io=IOA,
   q="A 24-year-old woman with primary hyperhidrosis says she has been told repeatedly that she just needs to wash more and relax. Which is the most appropriate counselling point?",
   opts=[
     ["Primary hyperhidrosis is a medical condition rather than a problem of hygiene or anxiety",
      "Correct — the misconception is addressed directly, and quality-of-life impairment is comparable to severe psoriasis."],
     ["Improved hygiene and stress reduction will resolve the sweating over time",
      "Anxiety exacerbates the condition but neither causes nor cures it."],
     ["The condition affects a very small minority and treatment options are limited",
      "It affects roughly 3 to 5% of the population and has a full treatment ladder."],
     ["Sweating of this kind always indicates a serious underlying systemic illness",
      "Primary disease is idiopathic; secondary causes are what require investigation."]],
   c=0, cite=c(76)),
]
