# -*- coding: utf-8 -*-
"""Lecture 23 vignette pool B -- Valvular Heart Disease: mitral stenosis, mitral
regurgitation, mitral valve prolapse.

KEYS ARE WRITTEN SHORT ON PURPOSE -- detail lives in the explanation.

Patient vignettes with a varied lead-in (the lead-in decides the answer).
Scope (cms_e4l23_scope.py): no mitral stenosis maneuver is keyed (slide 38 is
contested); mitral stenosis is graded as severe only (slide 40 bands overlap);
mitral regurgitation severity only as "regurgitant fraction 50% or more"; the
slide 44 label and the slide 52/53 copy errors are never keyed as printed.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _cmse3_q import Q
from cms_e4l23_scope import *


def S(topic, io, q, opts, cite, slot):
    d = Q(topic, io, q, opts, cite); d["slot"] = slot; return d


def V(topic, io, q, opts, cite, slot, lead):
    d = S(topic, io, q, opts, cite, slot); d["lead"] = lead; return d


QUESTIONS = [

# ------------------------------------------------------------- mitral stenosis
V(T_MS, IO_MS,
  "A 42-year-old woman who had rheumatic fever as a child has breathlessness on exertion. At the apex there is a low-pitched rumbling diastolic murmur that begins with an opening snap (a sharp sound just after the second heart sound), best heard with the bell in the left lateral decubitus position (lying on the left side). Which is the most likely diagnosis?",
  [["Mitral stenosis",
    "Correct. Rumble means stenosis and diastolic narrows it to the mitral or tricuspid valve; the apex, the opening snap after the second heart sound and the left lateral position mark mitral stenosis. Rheumatic heart disease is its most common cause."],
   ["Tricuspid stenosis",
    "Tricuspid stenosis is also a diastolic rumble with an opening snap, but it sits at the left lower sternal border near the xiphoid and grows louder with inspiration. This murmur is at the apex."],
   ["Aortic regurgitation",
    "Aortic regurgitation is diastolic but high-pitched and blowing, at the third intercostal space on the left. Blowing means regurgitation; this murmur is a low-pitched rumble."],
   ["Mitral regurgitation",
    "Mitral regurgitation is at the apex too, but it is a holosystolic blowing murmur radiating to the axilla. This murmur is diastolic and rumbling, which is stenosis."]],
  C(38, 34), "differential", "diagnosis"),

V(T_MS, IO_MS,
  "A 48-year-old woman with rheumatic mitral stenosis has an echocardiogram showing a markedly enlarged left atrium. Which complication is she at greatest risk of developing?",
  [["Atrial fibrillation",
    "Correct. In mitral stenosis the left atrium enlarges under raised pressure, and left atrial enlargement predisposes to an abnormal rhythm such as atrial fibrillation, which is common in severe disease."],
   ["Aortic root dilation",
    "Aortic root dilation is a cause of aortic regurgitation, found on echo. Mitral stenosis enlarges the left atrium, which predisposes to atrial fibrillation."],
   ["Left ventricular dilation",
    "Eccentric left ventricular dilation is the volume response of aortic and mitral regurgitation. Mitral stenosis loads the left atrium, predisposing to atrial fibrillation."],
   ["Concentric hypertrophy",
    "Concentric left ventricular hypertrophy is the pressure response to aortic stenosis. Mitral stenosis enlarges the left atrium instead, and that leads to atrial fibrillation."]],
  C(35, 39), "complication", "complication"),

V(T_MS, IO_MS,
  "A 53-year-old woman with mitral stenosis and an enlarged left atrium now has an irregularly irregular pulse from atrial fibrillation. Which complication does this rhythm place her at risk for?",
  [["Thromboembolism",
    "Correct. Left atrial enlargement in mitral stenosis predisposes to atrial fibrillation, and atrial fibrillation is a risk factor for thromboembolism. That is why the rhythm matters beyond the palpitations."],
   ["Aortic dissection",
    "Aortic dissection is a cause of acute aortic regurgitation and of root disease. The risk that follows atrial fibrillation in mitral stenosis is thromboembolism."],
   ["Papillary muscle rupture",
    "Papillary muscle rupture follows an acute myocardial infarction and causes acute mitral regurgitation. Atrial fibrillation in mitral stenosis raises the risk of thromboembolism."],
   ["Carotid radiation of the murmur",
    "Radiation to the carotids describes the aortic stenosis murmur, not a complication. Atrial fibrillation in mitral stenosis raises the risk of thromboembolism."]],
  C(35), "complication", "complication"),

V(T_MS, IO_MS,
  "A 51-year-old woman with long-standing mitral stenosis develops a hoarse voice and some difficulty swallowing. Which explains her hoarseness?",
  [["The enlarged left atrium on the nerve",
    "Correct. Hoarseness in mitral stenosis (Ortner syndrome) comes from the enlarged left atrium impinging on the left recurrent laryngeal nerve; dysphagia comes from the atrium pressing on the esophagus."],
   ["A dilated aortic root on the trachea",
    "A dilated aortic root is a cause of aortic regurgitation. In mitral stenosis the hoarseness comes from the enlarged left atrium pressing on the left recurrent laryngeal nerve."],
   ["Ruptured bronchial vein anastomoses",
    "Rupture of small bronchial vein anastomoses under high left atrial pressure causes hemoptysis in mitral stenosis. Hoarseness comes from the atrium compressing the recurrent laryngeal nerve."],
   ["An enlarged liver from congestion",
    "An enlarged, congested liver causes right upper quadrant pain in tricuspid stenosis. Hoarseness in mitral stenosis is the enlarged left atrium on the recurrent laryngeal nerve."]],
  C(37), "manifestation", "complication"),

V(T_MS, IO_MS,
  "A 39-year-old woman who emigrated from a country where rheumatic fever is common has breathlessness on exertion and orthopnea (breathlessness lying flat). A diastolic rumble is heard at the apex. Which is the most appropriate initial test?",
  [["Transthoracic echocardiogram",
    "Correct. Any patient with symptoms suggestive of mitral stenosis, such as dyspnea on exertion or orthopnea, should get an echocardiogram. It shows a large left atrium and the stenotic mitral valve."],
   ["Cardiac catheterization",
    "Cardiac catheterization is not necessary for mitral stenosis and is usually done for an ischemic evaluation. The test that answers her symptoms is a transthoracic echocardiogram."],
   ["Electrocardiogram only",
    "An electrocardiogram may show left atrial abnormality or atrial fibrillation, but it does not show the valve. Suggestive symptoms call for an echocardiogram."],
   ["No test until symptoms worsen",
    "She already has suggestive symptoms, and dyspnea on exertion or orthopnea is the trigger for an echocardiogram. Waiting would miss a treatable stenosis."]],
  C(43, 39), "initial test", "test"),

V(T_MS, IO_MS,
  "A 45-year-old woman with rheumatic mitral stenosis is in sinus rhythm. Which electrocardiogram finding is most expected?",
  [["Left atrial abnormality",
    "Correct. Mitral stenosis raises left atrial size and pressure, so the electrocardiogram shows left atrial abnormality. Atrial fibrillation is common in severe disease, and right ventricular hypertrophy appears with pulmonary hypertension."],
   ["Right axis deviation alone",
    "Right axis deviation with right ventricular hypertrophy is the electrocardiogram of pulmonic stenosis. Mitral stenosis shows left atrial abnormality first."],
   ["Right atrial enlargement only",
    "Right atrial enlargement out of proportion to right ventricular hypertrophy is the tricuspid stenosis pattern. Mitral stenosis shows left atrial abnormality."],
   ["An expected normal tracing",
    "Mitral stenosis enlarges the left atrium, and the electrocardiogram reflects that as left atrial abnormality. A normal tracing is not what is expected."]],
  C(39), "test finding", "test"),

V(T_MS, IO_MS,
  "A 44-year-old woman with mitral stenosis has breathlessness on exertion and orthopnea (breathlessness lying flat). Her valve area is 1.3 cm2, so the stenosis is not yet severe. Which is the most appropriate treatment?",
  [["A loop diuretic",
    "Correct. Mitral stenosis with symptoms of dyspnea and orthopnea is treated medically with a loop diuretic such as furosemide or bumetanide. Surgery waits for severe stenosis with symptoms or pulmonary hypertension."],
   ["Hydralazine",
    "Hydralazine is one of the afterload reducers for chronic aortic regurgitation. The medical treatment for dyspnea and orthopnea in mitral stenosis is a loop diuretic."],
   ["Balloon valvotomy",
    "Percutaneous balloon valvotomy is surgical treatment for severe mitral stenosis (area below 1.0 cm2) with symptoms or pulmonary hypertension. Her area of 1.3 cm2 is not yet severe."],
   ["No therapy",
    "No therapy is the plan only when mitral stenosis is asymptomatic with sinus rhythm. She has dyspnea and orthopnea, which call for a loop diuretic."]],
  C(41, 42), "first-line", "treatment"),

V(T_MS, IO_MS,
  "A 50-year-old woman with mitral stenosis has worsening breathlessness. Echocardiogram shows a valve area of 0.8 cm2, a mean gradient of 14 mmHg and a peak velocity of 3.4 m/s. Which is the most appropriate treatment?",
  [["Percutaneous balloon valvotomy",
    "Correct. Her values are severe (area below 1.0 cm2, mean gradient above 10 mmHg, velocity above 3.0 m/s), and severe mitral stenosis with symptomatic dyspnea or pulmonary hypertension is an indication for percutaneous balloon valvotomy."],
   ["A loop diuretic indefinitely",
    "A loop diuretic treats dyspnea and orthopnea, but severe mitral stenosis with symptoms meets the indication for intervention. The procedure is percutaneous balloon valvotomy."],
   ["Transcatheter aortic valve replacement",
    "Transcatheter aortic valve replacement treats severe aortic stenosis, a different valve. Severe symptomatic mitral stenosis is treated with percutaneous balloon valvotomy."],
   ["Afterload reduction with hydralazine",
    "Afterload reduction is medical management for chronic aortic regurgitation. Severe symptomatic mitral stenosis needs percutaneous balloon valvotomy."]],
  C(42, 40), "escalation", "treatment"),

V(T_MS, IO_MS,
  "A 36-year-old woman has mitral stenosis found on an echocardiogram done before pregnancy. She has no symptoms and is in sinus rhythm. Which is the most appropriate next step?",
  [["Cardiology consultation",
    "Correct. All patients with evidence of mitral stenosis on echocardiogram should have a cardiology consult to evaluate them and set the frequency of follow-up. Asymptomatic disease in sinus rhythm needs no therapy yet."],
   ["Start a loop diuretic",
    "Loop diuretics treat dyspnea and orthopnea in mitral stenosis. With no symptoms and sinus rhythm she needs no therapy, but the echo finding still warrants a cardiology consult."],
   ["Balloon valvotomy now",
    "Balloon valvotomy is for severe mitral stenosis with symptoms or pulmonary hypertension. An asymptomatic patient in sinus rhythm is referred to cardiology for evaluation."],
   ["No follow-up needed",
    "Mitral stenosis on echocardiogram is not dismissed; it should have a cardiology consult to set follow-up. Only therapy, not referral, is withheld when she is asymptomatic."]],
  C(43, 41), "referral", "referral"),

# ------------------------------------------------------- mitral regurgitation
V(T_MR, IO_MR,
  "A 60-year-old man has palpitations and fatigue. There is a holosystolic blowing murmur at the apex that radiates to the axilla and is loudest in the left lateral decubitus position (lying on the left side). Which is the most likely diagnosis?",
  [["Mitral regurgitation",
    "Correct. Blowing means regurgitation and holosystolic narrows it to the mitral or tricuspid valve; the apex, the radiation to the axilla and the left lateral position mark mitral regurgitation."],
   ["Tricuspid regurgitation",
    "Tricuspid regurgitation is holosystolic too, but it sits at the left mid or lower sternal border near the epigastrium and grows louder with inspiration. It does not radiate to the axilla."],
   ["Aortic stenosis",
    "Aortic stenosis is a harsh crescendo-decrescendo systolic murmur at the second right intercostal space radiating to the carotids. This murmur is blowing and holosystolic."],
   ["Mitral valve prolapse",
    "Mitral valve prolapse gives a mid-systolic click at the apex and is usually asymptomatic. A holosystolic blowing murmur to the axilla is established mitral regurgitation."]],
  C(48, 73), "differential", "diagnosis"),

V(T_MR, IO_MR,
  "A 64-year-old man, three days after an acute myocardial infarction, has sudden breathlessness, crackles in both lungs and a new holosystolic murmur at the apex radiating to the axilla. Which is the most likely cause?",
  [["Papillary muscle rupture",
    "Correct. An acute myocardial infarction with papillary muscle rupture is an acute cause of mitral regurgitation, and acute mitral regurgitation presents with left-sided heart failure symptoms such as dyspnea and rales."],
   ["Myxomatous degeneration",
    "Myxomatous degeneration causes mitral valve prolapse, a chronic cause of mitral regurgitation. The sudden murmur three days after an infarction points to papillary muscle rupture."],
   ["Rheumatic heart disease",
    "Rheumatic heart disease is a cause of mitral regurgitation, but it does not arrive suddenly three days after an infarction. Papillary muscle rupture does."],
   ["Tricuspid annular dilation",
    "Tricuspid annular dilation causes tricuspid regurgitation in pulmonary hypertension, heard at the lower sternal border. An apical murmur after infarction is papillary muscle rupture."]],
  C(45, 47), "etiology", "diagnosis"),

V(T_MR, IO_MR,
  "A 59-year-old man has a holosystolic blowing murmur at the apex radiating to the axilla. He is asked to squeeze a hand grip firmly for a minute while the examiner listens. How does the murmur change?",
  [["It becomes louder",
    "Correct. Squatting and handgrip increase the mitral regurgitation murmur: peripheral vascular resistance to ventricular ejection rises and pushes more regurgitation back into the left atrium."],
   ["It becomes softer",
    "Softening is the response of mitral regurgitation to standing or the Valsalva maneuver. Handgrip raises resistance to ejection and makes the murmur louder."],
   ["It does not change",
    "Handgrip does change it: raising peripheral resistance to ejection augments regurgitation into the left atrium, so the murmur gets louder."],
   ["It becomes diastolic",
    "No maneuver moves a murmur from systole into diastole; mitral regurgitation stays holosystolic. Handgrip simply makes it louder."]],
  C(48), "test finding", "test"),

V(T_MR, IO_MR,
  "A 62-year-old woman has a holosystolic blowing murmur at the apex radiating to the axilla. She stands up quickly from squatting while the examiner listens. How does the murmur change?",
  [["It becomes softer",
    "Correct. The mitral regurgitation murmur decreases with standing or the Valsalva maneuver and increases with squatting and handgrip, which raise resistance to ventricular ejection."],
   ["It becomes louder",
    "Louder is the response to squatting or handgrip, which raise resistance to ejection. Standing reduces the mitral regurgitation murmur."],
   ["It does not change",
    "Standing does change it: the mitral regurgitation murmur decreases with standing or the Valsalva maneuver."],
   ["It gains a click",
    "A mid-systolic click is the sign of mitral valve prolapse, not a response to a maneuver. Standing makes the mitral regurgitation murmur softer."]],
  C(48), "test finding", "test"),

V(T_MR, IO_MR,
  "A 66-year-old man with chronic mitral regurgitation has an echocardiogram showing a regurgitant fraction of 64%. Which severity does this indicate?",
  [["Severe regurgitation",
    "Correct. Mitral regurgitation is severe when the regurgitant fraction is 50% or more, meaning over half of the blood ejected goes backward. A fraction of 30 to 49% is moderate and below 30% is mild."],
   ["Moderate regurgitation",
    "Moderate mitral regurgitation is a regurgitant fraction of 30 to 49%. At 64%, more than half of each beat leaks back, which is severe."],
   ["Mild regurgitation",
    "Mild mitral regurgitation is a regurgitant fraction below 30%. A fraction of 64% is severe."],
   ["Ungradeable by echocardiogram",
    "Echocardiography grades mitral regurgitation by regurgitant fraction; left heart catheterization is not required. A fraction of 64% is severe."]],
  C(50, 49), "test finding", "test"),

V(T_MR, IO_MR,
  "A 67-year-old woman has severe mitral regurgitation with symptoms of left ventricular systolic dysfunction. Her ejection fraction is 52% and the left ventricular end-systolic dimension is 45 mm. Which is the most appropriate treatment?",
  [["A mitral valve clip or replacement",
    "Correct. Surgery is indicated for severe mitral regurgitation with symptomatic left ventricular systolic dysfunction, an ejection fraction below 60% or an end-systolic dimension above 40 mm. Options include a mitral valve clip or transcatheter mitral valve replacement."],
   ["Percutaneous balloon valvotomy",
    "Balloon valvotomy opens a stenotic mitral valve; it would not stop a leak. Severe symptomatic mitral regurgitation is treated with a clip or valve replacement."],
   ["A loop diuretic and yearly echo",
    "Medical management alone is not enough once severe regurgitation has an ejection fraction below 60% and an end-systolic dimension above 40 mm. She meets the surgical indications."],
   ["Aortic valve replacement",
    "Aortic valve replacement treats aortic stenosis or regurgitation. Her lesion is mitral, so the intervention is a mitral valve clip or replacement."]],
  C(52), "escalation", "treatment"),

V(T_MR, IO_MR,
  "A 70-year-old man with chronic mitral regurgitation also has atrial fibrillation and pulmonary hypertension. He is not yet a surgical candidate. Which is part of his medical management?",
  [["Treating his atrial fibrillation",
    "Correct. Medical treatment of mitral regurgitation aims to increase forward cardiac output while reducing regurgitant volume, and to treat comorbidities such as atrial fibrillation and pulmonary hypertension."],
   ["A nitrate to lower his preload",
    "Avoiding nitrates is the preload rule for aortic stenosis. The named medical steps in mitral regurgitation are raising forward output and treating atrial fibrillation and pulmonary hypertension."],
   ["Balloon valvotomy of the valve",
    "Balloon valvotomy treats severe mitral stenosis, not a leaking valve. Medical care for mitral regurgitation treats the comorbid atrial fibrillation and pulmonary hypertension."],
   ["Ignoring the rhythm for now",
    "Atrial fibrillation is one of the comorbidities that medical management of mitral regurgitation specifically treats, along with pulmonary hypertension."]],
  C(51), "first-line", "treatment"),

V(T_MR, IO_MR,
  "A 69-year-old woman has severe mitral regurgitation. Which electrocardiogram finding is most expected?",
  [["Left atrial enlargement",
    "Correct. Severe mitral regurgitation shows left atrial enlargement and left ventricular hypertrophy on the electrocardiogram, though with low sensitivity and questionable specificity."],
   ["Right axis deviation",
    "Right axis deviation with right ventricular hypertrophy is the pulmonic stenosis electrocardiogram. Severe mitral regurgitation shows left atrial enlargement."],
   ["Right atrial enlargement",
    "Right atrial enlargement out of proportion to right ventricular hypertrophy is the tricuspid stenosis pattern. Mitral regurgitation enlarges the left atrium."],
   ["An expected normal tracing",
    "Severe mitral regurgitation dilates the left atrium under volume and pressure load, so left atrial enlargement is the expected finding, not a normal tracing."]],
  C(49), "test finding", "test"),

# ---------------------------------------------------- mitral valve prolapse
V(T_MVP, IO_MVP,
  "A 22-year-old healthy woman has no symptoms. On a routine examination a mid-systolic click is heard at the apex with no murmur. Which is the most likely diagnosis?",
  [["Mitral valve prolapse",
    "Correct. Mitral valve prolapse usually affects healthy women aged 15 to 30, is usually benign and asymptomatic, and gives a mid-systolic click at the apex as the leaflets flare into the left atrium."],
   ["Mitral stenosis",
    "Mitral stenosis gives an opening snap and a low-pitched diastolic rumble at the apex, usually decades after rheumatic fever. A lone mid-systolic click is prolapse."],
   ["Aortic stenosis",
    "Aortic stenosis is a harsh systolic crescendo-decrescendo murmur at the second right intercostal space, mostly in older adults. A mid-systolic click is prolapse."],
   ["Mitral regurgitation",
    "Mitral regurgitation is a holosystolic blowing murmur radiating to the axilla. A click with no murmur is prolapse, which may later progress to regurgitation."]],
  C(54), "manifestation", "diagnosis"),

V(T_MVP, IO_MVP,
  "A 24-year-old woman has a mid-systolic click at the apex. An echocardiogram is ordered. Which finding confirms the suspected valve problem?",
  [["Thick, redundant mitral leaflets",
    "Correct. Mitral valve prolapse is diagnosed by echocardiogram showing thickened, redundant mitral leaflets greater than 5 mm, flaring into the left atrium during systole, from myxomatous degeneration."],
   ["A calcified, narrowed aortic valve",
    "Thickened, calcified aortic leaflets with reduced opening are the echo finding of aortic stenosis. Prolapse shows thickened, redundant mitral leaflets."],
   ["A dilated tricuspid annulus",
    "A dilated tricuspid annulus causes tricuspid regurgitation in pulmonary hypertension. The echo finding of prolapse is thickened, redundant mitral leaflets."],
   ["A dilated aortic root",
    "A dilated aortic root is a cause of aortic regurgitation found on echo. Prolapse is confirmed by thickened, redundant mitral leaflets over 5 mm."]],
  C(54), "test finding", "test"),

V(T_MVP, IO_MVP,
  "A 19-year-old woman is found to have a mid-systolic click at the apex at a sports physical. She feels well. Which is the most appropriate initial test?",
  [["Echocardiogram",
    "Correct. Mitral valve prolapse is diagnosed by echocardiogram, which shows thickened, redundant mitral leaflets greater than 5 mm bowing into the left atrium during systole."],
   ["Cardiac catheterization",
    "Catheterization is invasive and not how prolapse is diagnosed. An echocardiogram shows the thickened, redundant mitral leaflets."],
   ["Electrocardiogram",
    "An electrocardiogram does not show valve anatomy. The diagnosis of mitral valve prolapse is made by echocardiogram."],
   ["Chest radiograph",
    "A chest radiograph does not show the leaflets or their motion. A mid-systolic click is investigated with an echocardiogram showing redundant leaflets."]],
  C(54), "initial test", "test"),

V(T_MVP, IO_MVP,
  "A 26-year-old woman with echocardiogram-confirmed mitral valve prolapse has no symptoms and no murmur. She is worried about her heart. Which is the most appropriate counseling?",
  [["Usually benign; no treatment is needed",
    "Correct. Mitral valve prolapse is usually benign and asymptomatic, and usually no treatment is necessary. Intervention is considered only if it progresses to mitral regurgitation."],
   ["Lifelong warfarin to prevent clots",
    "Lifelong warfarin is for mechanical heart valves. Uncomplicated mitral valve prolapse is usually benign and needs no treatment."],
   ["Avoid all exercise for life",
    "Exercise restriction is the advice for aortic stenosis, which is preload dependent. Mitral valve prolapse is usually benign with no treatment needed."],
   ["Plan an early valve replacement",
    "Replacement is considered only if prolapse progresses to mitral regurgitation. Asymptomatic prolapse is usually benign and needs no treatment."]],
  C(54), "education", "education"),

V(T_MVP, IO_MVP,
  "A 31-year-old woman with known mitral valve prolapse is followed over several years. Which complication can the prolapse progress to?",
  [["Mitral regurgitation",
    "Correct. Mitral valve prolapse may develop the signs and symptoms of mitral regurgitation; prolapse is also listed among the chronic causes of mitral regurgitation."],
   ["Mitral stenosis",
    "Mitral stenosis is a narrowing that comes mostly from rheumatic heart disease. Prolapse lets the leaflets flare backward, so it progresses to regurgitation."],
   ["Aortic stenosis",
    "Aortic stenosis is degenerative in older adults or from a bicuspid valve. Mitral valve prolapse progresses to mitral regurgitation."],
   ["Tricuspid stenosis",
    "Tricuspid stenosis is mainly rheumatic worldwide and congenital in the United States. Mitral valve prolapse may progress to mitral regurgitation."]],
  C(54, 45), "complication", "complication"),

V(T_MVP, IO_MVP,
  "A 34-year-old woman with mitral valve prolapse has now developed symptomatic severe mitral regurgitation with a falling ejection fraction. Which is the most appropriate treatment?",
  [["A mitral clip or valve replacement",
    "Correct. Prolapse usually needs no treatment, but if it progresses to mitral regurgitation the options are a clip, transcatheter mitral valve replacement, or biological or mechanical replacement."],
   ["Reassurance with no treatment",
    "Reassurance fits uncomplicated prolapse. Once it has progressed to symptomatic severe regurgitation, a clip or valve replacement is indicated."],
   ["Percutaneous balloon valvotomy",
    "Balloon valvotomy treats severe mitral stenosis. A prolapsed valve that now leaks severely is treated with a clip or replacement."],
   ["Aortic valve replacement",
    "Aortic valve replacement treats disease of the aortic valve. Prolapse that progresses to mitral regurgitation is treated at the mitral valve."]],
  C(54, 52), "escalation", "treatment"),
]
