# -*- coding: utf-8 -*-
"""Cut option texts back to reference scale.

Measured against the 40 reference items Jaxon supplied: their options run a
MEDIAN OF 19 CHARACTERS (2 words), p75 28, max 66. Ours were a median of 59 and
39% exceeded the reference maximum -- roughly 3x too wordy. The reference puts
the action or the name in the option and the reasoning in the explanation; I had
been putting both in the option.

That was also the real cause of the length bias I "fixed" earlier by padding
distractors. The reference set is itself 13% gameable, not 0% -- a naturally
written set lands there. Shortening the correct answers fixes the wordiness and
the bias together, so the padding in cmsderm_lengthfix.py is now retired.

LEAD narrows a stem's final question sentence where the old one asked two things
(a two-part question forces a two-part option). OPTS replaces a whole option set,
so the five stay parallel.
"""

LEAD = {
("l10",1): "What is the characteristic tactile finding?",
("l10",3): "What is the most likely diagnosis?",
("l10",4): "What is the preferred management?",
("l10",5): "What subtype is this?",
("l10",8): "What is the most common subtype of melanoma?",
("l10",11): "What is the dominant prognostic variable?",
("l10",18): "Where does the tumour usually arise, and why is recognition delayed?",
("l9",3): "What is the most likely diagnosis?",
("l9",12): "What is the most likely diagnosis?",
("l3",23): "What mechanism is responsible?",
("l7",2): "What accounts for the improving tensile strength of a maturing scar?",
}

OPTS = {
("l10",0): ["Biopsy","Liquid nitrogen cryotherapy","Field-directed therapy","Observation for one year","Reassurance"],
("l10",1): ["Sandpaper texture","Velvety texture","A stuck-on quality","Pearly with telangiectasias","Boggy and fluctuant"],
("l10",3): ["Cutaneous squamous cell carcinoma","Basal cell carcinoma","Actinic keratosis","Keratoacanthoma","Amelanotic melanoma"],
("l10",4): ["Surgical excision or Mohs micrographic surgery","Topical imiquimod or fluorouracil","Cryotherapy","Radiotherapy","Observation alone"],
("l10",5): ["Nodular basal cell carcinoma","Nodular squamous cell carcinoma","Sebaceous hyperplasia","Keratoacanthoma","Amelanotic melanoma"],
("l10",6): ["High-risk sites, recurrence, or aggressive histology","Every basal cell carcinoma","Only after topical therapy fails twice","Only for tumours over 5 cm","Never; surgery is not required"],
("l10",7): ["Asymmetry, border, colour, diameter, evolution","Asymmetry, bleeding, crusting, depth, erosion","Abscess, bulla, cyst, dermatitis, erythema","Age, burn history, complexion, dysplasia, exposure","Asymmetry, border, colour, dermoscopy, excision"],
("l10",8): ["Superficial spreading melanoma","Lentigo maligna melanoma","Nodular melanoma","Acral lentiginous melanoma","Amelanotic melanoma"],
("l10",9): ["0.5 to 1 cm in situ, 1 cm under 1 mm, 1 to 2 cm over","1 cm in situ, 2 cm under 1 mm, 3 cm over 1 mm","5 mm for every melanoma","No re-excision after the biopsy","Margins set by lesion diameter"],
("l10",10): ["1.0 mm, or 0.8 mm with other risk factors","Any thickness","Only at 4 mm or greater","Only with palpable nodes","By lesion diameter"],
("l10",11): ["Breslow thickness","Lesion diameter","Asymmetry","Fitzpatrick skin type","Anatomic subtype"],
("l10",12): ["Monthly, including scalp, palms, soles, and nails","Annually, limited to sun-exposed skin","Not needed if a clinician examines yearly","Focus on counting total naevi","Report only lesions over 6 mm"],
("l10",13): ["Oral examination; start or optimise antiretroviral therapy","Oral examination; start chemotherapy first","Ophthalmological examination; intralesional vincristine","Lymph node examination; observation","Skin examination alone; mucosa is spared"],
("l10",15): ["Chronicity, treatment resistance, odd distribution","Pruritus","Truncal involvement","Scale","A positive potassium hydroxide preparation"],
("l10",16): ["Stage-directed, skin-directed therapy","Immediate combination chemotherapy","No treatment at any stage","Excision of all involved skin","Indefinite high-dose corticosteroids"],
("l10",17): ["Nail unit melanoma; Hutchinson sign","Subungual haematoma","Benign longitudinal melanonychia","Onychomycosis","Glomus tumour"],
("l10",18): ["In the matrix; it is rare and not sun-driven","In the nail bed; only fair-skinned patients","In the matrix; pain is always present","In the periungual skin; easily seen","In the matrix; it is over-diagnosed"],
("l10",20): ["Characterise the lesion before naming it","Name the likely diagnosis, then seek support","Biopsy every lesion first","Photograph and review next visit","Refer every pigmented lesion"],
("l10",21): ["Premalignant, on a continuum with carcinoma","Entirely benign and unrelated","Invasive carcinoma from the outset","It progresses to basal cell carcinoma","It progresses to melanoma"],
("l10",22): ["Selected superficial disease, clearance confirmed","All nodular tumours, no follow-up","High-risk facial tumours","Recurrent tumours after excision","Any tumour the patient wants left alone"],
("l10",24): ["Human herpesvirus 8, in blood and lymph vessel lining","Human papillomavirus, in keratinocytes","Human immunodeficiency virus, in endothelium","Ultraviolet damage to dermal fibroblasts","Malignant T cells migrating to skin"],

("l1",0): ["Sensitivity","Specificity","Pretest probability","Posttest probability","Positive predictive value"],
("l1",1): ["Sensitivity reduces false negatives; specificity false positives","Sensitivity reduces false positives; specificity false negatives","Both reduce false negatives equally","Neither relates to false results","Sensitivity is for screening, specificity for diagnosis"],
("l1",2): ["Pretest is before the result, posttest after","Pretest is after the result, posttest before","They are the same quantity","Pretest applies only to screening","Posttest ignores the clinical picture"],
("l1",3): ["Screening seeks occult disease; diagnosis reduces uncertainty","Screening confirms a diagnosis; diagnosis seeks occult disease","They are interchangeable","Screening is only for emergency medicine","Diagnostic testing replaces the examination"],
("l1",4): ["Gather, interpret, then form a problem representation","Generate hypotheses, gather, then test","Order tests, interpret, then take a history","Treat symptoms, observe, then diagnose","Apply a guideline, then confirm it fits"],
("l1",5): ["Vascular, infectious, neoplastic, degenerative, iatrogenic, congenital, autoimmune, trauma, endocrine","Vascular, inflammatory, neurological, drug-related, idiopathic, cardiac, allergic, toxic, environmental","A physical examination sequence","A checklist for appraising evidence","A pretest probability score"],
("l1",6): ["Propose hypotheses, then test them against the data","Treat symptoms before a diagnosis is reached","Recognise patterns automatically","Apply an if-then guideline rule","Rank diagnoses purely by frequency"],
("l1",7): ["An unstable patient with an atypical presentation","A stable outpatient with a classic presentation","A research setting appraising evidence","A screening programme","Any situation at all"],
("l1",8): ["An atypical presentation of a common disease is likelier","A typical presentation of a rare disease is likelier","Rare diagnoses should never be considered","All diagnoses are equally likely until tested","Assume the most serious diagnosis first"],
("l1",9): ["Ask questions that would disprove your diagnosis","Apply a guideline rule early","Gather all data regardless of relevance","Rely on quick pattern recognition","Defer decisions until all results return"],
("l1",10): ["Probability, likely success, tolerability, risk-benefit","Probability of disease alone","The cost of treatment alone","Withhold until the diagnosis is certain","Treat whenever disease is possible"],
("l1",11): ["To help patients understand their risks and options","To ensure patients accept the chosen plan","To satisfy documentation requirements","To shorten the consultation","To transfer the decision to the patient"],
("l1",12): ["Cost, health literacy, and cultural or religious factors","Cost of medications only","Patient motivation only","Dosing complexity only","Barriers cannot be anticipated"],
("l1",13): ["It is time consuming and evidence is often unavailable","It always answers definitively but is expensive","It cannot be combined with guidelines","It applies only to surgical decisions","It removes the need for judgement"],
("l1",14): ["What disease, should we test, should we treat","What disease, what prognosis, what cost","Which guideline, which specialist, when to follow up","Is the patient stable, certain, and informed","Pretest, posttest, and likelihood ratio"],

("l9",0): ["Autosomal dominant; cryotherapy is not used","Autosomal recessive; cryotherapy is first line","Somatic mutation; excision is first line","Autosomal dominant; one treatment clears them","X-linked; response is equal in all skin types"],
("l9",1): ["Lentigines do not fade seasonally; ephelides do","Lentigines fade in winter; ephelides do not","Lentigines are always over 2 cm","Lentigines never involve mucosa","Lentigines always require excision"],
("l9",2): ["Basal melanocyte proliferation with more melanin","T cell destruction of melanocytes","Dermal capillary proliferation","Somatic mutation present from birth","Hyperinsulinaemia driving keratinocyte growth"],
("l9",3): ["Seborrheic keratoses","Malignant melanoma","Solar lentigines","Dermatosis papulosa nigrans","Congenital melanocytic naevi"],
("l9",4): ["Dermatosis papulosa nigrans, a benign variant","Dermatosis papulosa nigrans, a premalignant variant","Multiple lentigines","Syringomas","Melanocytic naevi"],
("l9",6): ["Phototherapy, narrow band ultraviolet B preferred","Topical therapy alone at any extent","Psoralen with ultraviolet A preferred","Surgical grafting for all patients","No treatment is available"],
("l9",7): ["Larger lesions carry more risk; image brain and spine","Smaller lesions carry more risk; no imaging","Risk is unrelated to size; no imaging","Larger lesions carry more risk; always excise fully","It regresses spontaneously; observe"],
("l9",8): ["Nevus spilus; observe with sun protection","Nevus spilus; excise immediately","A cafe au lait macule","A dysplastic naevus","A blue nevus"],
("l9",9): ["It is suspicious and warrants evaluation","It is expected with many moles; no action","It is a blue nevus; no evaluation","It is a Spitz nevus; always benign","It confirms melanoma without biopsy"],
("l9",10): ["Dermal melanocytes; biopsy larger lesions","Epidermal melanocytes; always clinical","Keratinocytes; cryotherapy","Lipid-laden macrophages; lipid screening","Dilated capillaries; blanches"],
("l9",11): ["Reed nevus, lower extremities in the thirties","Spitz nevus, children, face and neck","Blue nevus, adolescence, dorsal hands","Dysplastic naevus, irregular borders","Congenital melanocytic nevus, from birth"],
("l9",12): ["Spitz nevus","Pigmented spindle cell nevus","Pyogenic granuloma","Molluscum contagiosum","Common acquired melanocytic nevus"],
("l9",13): ["Biopsy, excising where melanoma is a concern","Clinical diagnosis; no biopsy needed","Biopsy, then excise all naevi prophylactically","Dermoscopy alone","No follow-up once documented"],
("l9",14): ["Sun protection with patient education","Cryotherapy to each lesion","Surgical excision of each macule","Systemic depigmenting therapy","No management is possible"],

("l3",1): ["Wheals migrate and last under 24 hours","Wheals stay fixed for several days","Only erythema multiforme itches","Only urticaria affects the limbs","Only erythema multiforme blanches"],
("l3",2): ["Granular immunoglobulin A in dermal papillae","Linear immunoglobulin G at the basement membrane","Net-like intercellular immunoglobulin G","No deposits; mites on scraping","Band-like lymphocytes in the upper dermis"],
("l3",3): ["Check glucose-6-phosphate dehydrogenase; monitor blood count","Check glucose-6-phosphate dehydrogenase; monitor renal function","Check thyroid function; monitor blood count","Check liver function; monitor for photosensitivity","No testing or monitoring needed"],
("l3",4): ["A strict lifelong gluten-free diet","Indefinite dapsone monotherapy","A gluten-free diet for six weeks","High-potency topical steroids alone","Lifelong systemic corticosteroids"],
("l3",5): ["Paraneoplastic acanthosis nigricans","Insulin-resistant acanthosis nigricans","Confluent and reticulated papillomatosis","Postinflammatory hyperpigmentation","A niacin or corticosteroid effect"],
("l3",8): ["A second-generation antihistamine","Oral prednisone for five days","Intramuscular epinephrine","A first-generation antihistamine","Skin biopsy before treatment"],
("l3",9): ["Urticarial vasculitis; low complement","Chronic urticaria; normal complement","Hereditary angioedema; low C4","Mastocytosis; positive Darier sign","Anaphylaxis; raised tryptase"],
("l3",12): ["Palisading granulomas with central necrobiosis","Septal panniculitis without vasculitis","Dermal neutrophils without organisms","Hyphae in the stratum corneum","Band-like lymphocytes in the upper dermis"],
("l3",13): ["Fasting glucose and haemoglobin A1c","Chest radiograph","Immunoglobulin A tissue transglutaminase","Colonoscopy","No screening is indicated"],
("l3",14): ["Avoid debridement","Debride to remove devitalised tissue","Intravenous antibiotics as definitive therapy","Ankle-brachial index, then compression","A dry adherent dressing twice daily"],
("l3",15): ["A diagnosis of exclusion","Confirmed by a specific biopsy finding","Confirmed by wound culture","Confirmed by a pathergy test","Confirmed by inflammatory bowel disease"],
("l3",18): ["Primary focal; topical aluminium chloride","Primary focal; botulinum toxin A","Secondary; endocrine investigation","Frey syndrome; topical glycopyrronium","Anxiety disorder; psychological therapy"],
("l3",19): ["Withdraw all suspect medications","Admit to a burn unit","Give systemic corticosteroids","Obtain a skin biopsy","Start broad-spectrum antibiotics"],
("l3",20): ["Detachment over 30 percent of body surface","Mucosal involvement","A drug trigger","A prodrome","A positive Nikolsky sign"],
("l3",21): ["SCORTEN","The Parkland formula","The Fitzpatrick scale","The minimal erythema dose","The ankle-brachial index"],
("l3",22): ["Cool compresses, early anti-inflammatories, hydration","Cold immersion and delayed anti-inflammatories","Immediate systemic corticosteroids","Liberal topical anaesthetics","Prophylactic oral antibiotics"],
("l3",23): ["Phototoxicity, non-immunologic and dose-dependent","Photoallergy, immunologic and needing sensitisation","Phototoxicity, immunologic and dose-independent","Polymorphous light eruption","Phytophotodermatitis from plant contact"],
("l3",25): ["Ultraviolet-induced TP53 mutation","Ultraviolet-induced melanocyte proliferation","Hyperinsulinaemia driving keratinocyte growth","Immunoglobulin A complex deposition","Loss of elastic tissue"],
("l3",27): ["Intrinsic aging gives fine lines without pigment change","Intrinsic aging gives coarse deep wrinkles","Intrinsic aging spares the posterior neck","Intrinsic aging is driven by ultraviolet A","Only intrinsic aging responds to tretinoin"],
("l3",28): ["Broad-spectrum factor 30 daily, reapplied every 2 hours","Broad-spectrum factor 30 daily, applied once","Factor 15, reapplied only after swimming","Physical barriers alone","Only for Fitzpatrick types I to III"],
("l3",29): ["Suppressive oral acyclovir or valacyclovir","Continuous oral antihistamines","Continuous topical corticosteroids","Oral prednisone at each episode","Avoid anti-inflammatories and sulfonamides"],
("l3",30): ["Weight loss and glycaemic control","Topical retinoids","Laser therapy or dermabrasion","Topical corticosteroids","Reassurance with no intervention"],
("l3",31): ["Immunoglobulin E mediated, an immunologic trigger","Immunoglobulin E mediated, a non-immunologic trigger","A delayed type IV reaction","Immune complex deposition","Complement deficiency"],
("l3",33): ["About 75 percent; benign and self-limiting","About 75 percent; progresses to malignancy","About 25 percent; benign and self-limiting","About 75 percent; needs lifelong immunosuppression","About 50 percent; invariably recurs"],
("l3",34): ["Inflammatory bowel disease and arthritis","Celiac and autoimmune thyroid disease","Diabetes and gastrointestinal malignancy","Venous and arterial insufficiency","Sarcoidosis and streptococcal infection"],
("l3",39): ["A burn unit or intensive care unit","A general medical ward","Outpatient management","A surgical ward for debridement","Emergency department observation"],
("l3",40): ["First degree; 3 to 5 days with desquamation","First degree; 1 to 2 weeks with infection risk","Second degree; 3 to 5 days","Second degree; prophylactic antibiotics","Third degree; surgical referral"],
("l3",42): ["Field cancerisation","Pathergy","Koebner phenomenon","Photoallergy","Paraneoplastic change"],
("l3",43): ["Tretinoin, with initial irritation over 6 to 12 months","Tretinoin, with results in two weeks and no irritation","Hydroquinone","Topical corticosteroids nightly","Calcipotriene"],
("l3",44): ["Baseline ultraviolet sensitivity; all types need care","Baseline sensitivity; types V and VI need none","The likelihood of rosacea","The severity of an existing sunburn","The required sun protection factor alone"],

("l8",1): ["Close contact for 15 to 20 minutes; itch at 4 to 6 weeks","Brief casual contact; itch within 24 hours","Airborne spread; itch after 1 week","Contaminated water; itch within hours","Head-to-head contact; itch at 4 to 6 weeks"],
("l8",2): ["Microscopy of the mite, ova, or feces","Microscopy plus a positive Nikolsky sign","Potassium hydroxide showing spaghetti and meatballs","Serology for anti-mite antibodies","A burrow ink test alone"],
("l8",3): ["Overnight to all skin; itch may persist for weeks","To visible areas only; resolves in 24 hours","Overnight to all skin; persistent itch means failure","Twenty minutes then rinse; no other measures","Weekly for three months"],
("l8",4): ["Crusted scabies; highly infectious despite no itch","Crusted scabies; less infectious than ordinary scabies","Post-scabietic dermatitis; not infectious","Xerosis of aging; emollients only","Psoriasis; topical corticosteroids"],
("l8",5): ["Staphylococcal superinfection and post-scabietic papules","Systemic parasitic infection of internal organs","Permanent scarring alopecia","Post-streptococcal glomerulonephritis in all","Malignant transformation of the burrow"],
("l8",6): ["Finding live lice by wet combing","Finding nits alone","Potassium hydroxide of plucked hairs","A skin scraping under mineral oil","Wood's lamp examination"],
("l8",7): ["Linear excoriations of the back, neck, and waist","Scalp involvement with lymphadenopathy","It is always asymptomatic","Burrows in the finger webs","Spread by head-to-head contact"],
("l8",8): ["Resistance is rising; read the result at 24 hours","Resistance is falling; read it immediately","Head lice are self-limiting","Oral antibiotics are always needed","Essential oils are first line"],
("l8",9): ["Cimex lectularius; breakfast, lunch, and dinner","Sarcoptes scabiei; the delta-wing jet","Pediculus humanus corporis; linear excoriations","Tunga penetrans; translucent foot nodules","Cercariae; urticaria after water exposure"],
("l8",10): ["A professional exterminator","Washing bedding at 60 degrees Celsius alone","Treating all contacts with permethrin","A pediculicide to the skin","No environmental action"],
("l8",12): ["Excision or cryotherapy, with tetanus prophylaxis","Oral albendazole for 3 days","Whole-body overnight permethrin","Antihistamines and oatmeal baths alone","Professional extermination of the home"],
("l8",13): ["Intramuscular or subcutaneous epinephrine","Cleaning, ice, and local anaesthetic","An oral antihistamine at home","A topical corticosteroid","Local wound debridement"],
("l8",14): ["Cutaneous larva migrans; albendazole or ivermectin","Cutaneous larva migrans; excision or cryotherapy","Cutaneous larva migrans; topical therapy alone","Tungiasis; excision of the flea","Scabies; whole-body permethrin"],
("l8",16): ["Necrosis at 2 to 3 days, eschar by day 7; delay surgery","Full-thickness necrosis within hours; debride now","Resolution without tissue loss","Systemic symptoms within 30 minutes","Painless induration with vesicles by 36 hours"],
("l8",17): ["Calcium gluconate, analgesia, and muscle relaxants","Albendazole and ivermectin","Overnight topical permethrin","Surgical debridement of the bite","Doxycycline for 5 to 10 days"],
("l8",18): ["Pacific Northwest; a painless bite","Midwest and Southeast; the red, white, and blue sign","Northeast; erythema migrans","Southwest; crampy abdominal pain","Pacific Northwest; immediate severe pain"],
("l8",19): ["Embedded hairs; conjunctivitis or corneal granuloma","Necrotic ulceration from cytotoxic venom","Muscle spasm and abdominal pain","A serpentine advancing track","No cutaneous or ocular effects"],
("l8",20): ["Lepidopterism; strip the hairs off","Erucism; systemic corticosteroids only","Arachnidism; antivenom","Tungiasis; excision","Cercarial dermatitis; oatmeal baths"],
("l8",21): ["Stage 1 erythema migrans; treat clinically","Stage 1; wait for two-tier serology","Stage 2; intravenous ceftriaxone","Stage 3; look for arthritis","Cellulitis; cephalexin"],
("l8",22): ["Doxycycline, with amoxicillin in children and pregnancy","Amoxicillin, with doxycycline for failure","Intravenous ceftriaxone for all stages","No antibiotics for stage 1","Topical permethrin to the bite"],
("l8",23): ["Monoarticular arthritis of a weight-bearing joint","Erythema migrans at the bite site","Cranial nerve palsies and meningitis","A rash starting on ankles and wrists","Symmetric small-joint polyarthritis"],
("l8",24): ["Doxycycline, used in children for this infection","Amoxicillin; doxycycline is contraindicated","Supportive care only","Intravenous ceftriaxone for 14 days","Withhold until serology returns"],
("l8",25): ["Fever, headache, and rash, in about 60 percent","Fever, headache, and rash, in nearly all","Fever, arthritis, and erythema migrans","Fever, cough, and rash","Rash, pruritus, and lymphadenopathy"],
("l8",26): ["Thrombocytopenia, hyponatraemia, normal white count","Leukocytosis with thrombocytosis","Hypernatraemia and hyperglycaemia","Eosinophilia with raised immunoglobulin E","A positive potassium hydroxide preparation"],
("l8",27): ["Cercarial dermatitis; snails complete the cycle","Cutaneous larva migrans; from contaminated soil","Tungiasis; a flea penetrating the foot","Scabies; a burrowing mite","Bedbug bites from campsite bedding"],
("l8",28): ["Antihistamines, oatmeal baths, and antipruritic lotions","Oral albendazole for 3 days","Whole-body overnight permethrin","Doxycycline for 5 to 10 days","Extermination of the water source"],
("l8",30): ["Wash, or bag for 14 days; 60 degrees Celsius kills mites","Bag for 24 hours","Wash in cold water","Discard all bedding and clothing","No environmental measures needed"],

("l2",1): ["A topical corticosteroid plus regular emollient","Emollients alone","Oral cephalexin","Oral terbinafine","Systemic prednisone"],
("l2",7): ["Ketoconazole shampoo and cream","A high-potency topical corticosteroid","Oral terbinafine","Oral doxycycline","Topical mupirocin"],
("l2",8): ["Stop the steroid; warn of a temporary flare","Stop the steroid; expect no flare","Increase the steroid potency","Add adapalene, continue the steroid","Oral isotretinoin"],
("l2",9): ["Fold involvement with satellite lesions","Erythema in the diaper area","The recent amoxicillin course","Scaling at the edge","The one-week duration"],
("l2",10): ["Frequent changes and a thick barrier paste","A topical antifungal at each change","A high-potency topical corticosteroid","Oral cephalexin","Leaving the diaper off entirely"],
("l2",12): ["Acute unilateral swelling suggests venous thrombosis","Bilateral change makes cellulitis likely","No fever excludes a vascular event","Brown discoloration means infection","Start compression immediately"],
("l2",14): ["Acantholysis with intraepithelial blisters","Subepithelial blistering, no acantholysis","Neutrophils in a row at the junction","Granular immunoglobulin A at papillary tips","Band-like lymphocytes in the dermis"],
("l2",16): ["Exclamation point hairs","Round patches of loss","Absence of scarring","A history of atopy","Sudden onset over three weeks"],
("l2",19): ["Finasteride is oral and works best with minoxidil","Finasteride is topical and minoxidil oral","Minoxidil works best at the frontal hairline","Finasteride's sexual effects are permanent","Neither agent alters the course"],
("l2",24): ["Human leukocyte antigen B27","Human leukocyte antigen Cw6","Stiffness worsening with activity","Symmetric small joints, sparing distal","A positive rheumatoid factor"],
("l2",25): ["About 41 percent of their children","About 8 percent of their children","About 50 percent; autosomal dominant","No increased risk; it is not heritable","Risk is set by human leukocyte antigen B27"],
("l2",27): ["Reassurance, with an antihistamine for itch","Reassurance alone, no treatment for itch","Oral acyclovir for all patients","Oral terbinafine","Oral prednisone over two weeks"],
("l2",29): ["A band-like lymphocytic infiltrate","Acantholysis with intraepithelial blisters","Subepithelial blistering with neutrophils","Parakeratosis with neutrophilic microabscesses","Granulomas around degenerated collagen"],
("l2",30): ["Break the itch-scratch cycle","Indefinite potent topical corticosteroid","Surgical excision of the plaque","An oral antifungal","Reassurance alone"],
("l2",31): ["Short lukewarm showers; emollient within minutes","Hot showers; moisturise hours later","A keratolytic onto the fissures","A high-potency corticosteroid twice daily","A scented body wash daily"],
("l2",34): ["Purpura, an emergency until proven otherwise","Petechiae, an emergency until proven otherwise","Purpura, benign and observable","Ecchymosis from minor trauma","A wheal from dermal fluid"],
("l2",37): ["Confirm with viral polymerase chain reaction","Accept the Tzanck smear as definitive","Bacterial culture and sensitivity","Direct immunofluorescence of perilesional skin","A potassium hydroxide preparation"],
("l2",38): ["Lesion for histology, perilesional for immunofluorescence","Bulla centre for immunofluorescence alone","A shave biopsy of the blister roof","Potassium hydroxide of blister fluid","Patch testing for an allergen"],
("l2",39): ["Low potency on the face, low to medium on the body","High potency on the face, low on the body","The same high-potency agent at both sites","Clobetasol at both sites for two weeks","Emollients alone at both sites"],
("l2",41): ["Adequate for the skin, inadequate for the nails","Adequate for both skin and nails","Inadequate for both; systemic needed for each","Add a topical corticosteroid to both","Neither site needs treatment"],
("l2",42): ["Start gradually, expect irritation, protect from sun","Start at full frequency immediately","Expect greater sun tolerance","No pregnancy precautions are needed","Combine with a potent corticosteroid"],
("l2",43): ["Ointments are more occlusive than creams or lotions","Lotions are the most occlusive","Creams and ointments are equally occlusive","Vehicle matters only for corticosteroids","Avoid occlusive vehicles in xerosis"],
("l2",44): ["Apply after rinsing and avoid fragranced products","Apply only to inflamed areas","Use a fragranced moisturiser","Withhold on steroid days","Bathe in hot water first"],
("l2",45): ["It is clinical; no routine laboratory testing","Check an immunoglobulin E level in every child","Biopsy every child before treatment","Patch test every child at diagnosis","Culture every child at diagnosis"],
("l2",46): ["Reduced filaggrin impairing the barrier","Autoantibodies against keratinocyte adhesion","Autoantibody damage to the basement membrane","Malassezia overgrowth in sebaceous areas","T cells infiltrating the hair follicle"],
("l2",47): ["About 20 percent of children; often begins early","About 20 percent; never begins after childhood","More common in females than males","About 2 percent of children","It resolves in all by adolescence"],
("l2",49): ["Alkalis act in minutes to a day; soaps over weeks","Both act only after weeks","Alkalis over weeks; soaps in minutes","Neither acts before 48 to 72 hours","Alkalis act systemically; soaps locally"],
("l2",50): ["Delayed type IV reaction, most often to urushiol","Immediate type I reaction to urushiol","Delayed type IV reaction, most often to nickel","Direct barrier disruption, no immune role","A type III immune complex reaction"],
("l2",51): ["Malassezia overgrowth at sebum-rich sites","Malassezia overgrowth at flexural sites","An acquired dermatophyte infection","Staphylococcus aureus colonisation","Autoimmunity against sebaceous glands"],
("l2",52): ["Open or closed comedones","Papulopustules on the face","Sparing beside the vermilion border","Central erythema with telangiectasia","Scale on scalp and nasolabial folds"],
("l2",54): ["A Wood's lamp, evaluating pigment change","A dermoscope, magnifying under polarised light","A transilluminator, separating solid from fluid","A trichoscope, magnifying the scalp","A phototherapy unit delivering ultraviolet B"],
("l2",55): ["Patch testing for contact dermatitis; prick for immediate","Prick testing for contact dermatitis; patch for immediate","Both detect delayed type IV reactions","Patch detects fungi; prick detects bacteria","Both are performed on blood samples"],
("l2",56): ["Emollients, topical steroids, and calcipotriene","Salicylic acid and coal tar","Methotrexate immediately","A biologic agent","A tapering course of oral prednisone"],
("l2",57): ["A vitamin D analogue; caution over nephrotoxicity","A vitamin D analogue; risk of atrophy","A retinoid; irritation and photosensitivity","A calcineurin inhibitor for the face","A keratolytic used second line"],
("l2",59): ["Irregular, blotchy borders that are not well defined","Clear borders but irregular internal colour","Smaller than 1 cm","Elevated above the surrounding skin","It changes when pressure is applied"],

("l7",1): ["Lines run through a callus but are broken by a wart","Lines are broken by a callus, run through a wart","Lines are broken by both","Lines run through both","Lines cannot be assessed on the sole"],
("l7",2): ["Progressive cross-linking of collagen fibres","New elastin deposition","Continued fibroblast proliferation","Vascular ingrowth","Strength is fixed at the time of closure"],
("l7",3): ["It extends beyond the margins and does not regress","It developed within four weeks","It stays within the wound margins","It flattens with time","It is always painless"],
("l7",4): ["Excision alone recurs in 50 to 100 percent","Excision alone is usually curative","Excise only after a confirmatory biopsy","Silicone sheeting for one week first","Cryotherapy instead, with no adverse effects"],
("l7",5): ["Prevention, including avoiding ear piercing","Early excision of every lesion","Intralesional steroid alone","Compression for one week after injury","Routine biopsy of every lesion"],
("l7",6): ["Diagnose the lesion at the base","Send the horn; leave the base alone","A conical shape means benign","Painless means it can be reassured","Cryotherapy without histology"],
("l7",7): ["Harmless growths where skin rubs together","Premalignant lesions requiring excision","Viral warts spread by contact","A marker of internal malignancy","They resolve on their own"],
("l7",8): ["Prevention, with repositioning every two hours","Prophylactic hydrocolloid dressings","Repositioning every eight hours","Referral for surgical debridement","Restricting fluids"],
("l7",10): ["Obesity, sedentary life, dense natal cleft hair","Female sex, pregnancy, oestrogen excess","Prematurity and low birth weight","Fair skin, sun exposure, age over 40","Venous insufficiency and lymphoedema"],
("l7",11): ["The dimple sign; peripheral pigment network","The dimple sign, seen in lipoma","Nikolsky sign","Darier sign","Auspitz sign"],
("l7",12): ["Usually painless, but the commonest painful skin tumour","Invariably painful","Always pruritic, never painful","Painful only after malignant change","Symptomatic only if over 3 cm"],
("l7",13): ["Biopsy","Observation for 3 to 6 months","Dermoscopy","A potassium hydroxide preparation","Clinical appearance alone"],
("l7",14): ["Excision with 5 mm margins","Observation alone","Excision with 1 mm margins","Cryotherapy without histology","Intralesional corticosteroid"],
("l7",15): ["Delay excision; inject triamcinolone now","Excise the capsule now while inflamed","Leave it alone permanently","Aspirate and discharge","Urgent wide excision"],
("l7",16): ["It is enclosed epithelium filled with keratin","It arises from apocrine glands","It has no lining, being a pseudo-cyst","It contains lipid-laden macrophages","It is filled with joint mucin"],
("l7",18): ["Rapid growth to 4 to 6 months, then slow involution","Steady growth with no involution","Involution from birth, gone by 6 weeks","Rapid growth with malignant risk","No change during childhood"],
("l7",20): ["Present at birth; darkens and never involutes","Appears at six months; proliferates then involutes","Present at birth; involutes by school age","A soft yellow lipid plaque","An acquired adult capillary proliferation"],
("l7",21): ["Nevus simplex","An infantile hemangioma","A port-wine stain","A cherry angioma","A pyogenic granuloma"],
("l7",22): ["Benign capillary proliferation; more will appear","Benign, but can progress to malignancy","Caused by increased melanocytes","Biopsy is needed to diagnose them","They indicate liver disease"],
("l7",23): ["Dilated existing vessels; ask about oestrogen and alcohol","Capillary proliferation with age; no history needed","Dilated dermal capillaries present from birth","A vascular tumour after minor trauma","Blood extravasated into the dermis"],
("l7",24): ["Pyogenic granuloma, neither infectious nor granulomatous","Pyogenic granuloma, a granulomatous infection","Cherry angioma","Amelanotic melanoma","Dermatofibroma"],
("l7",25): ["Neurofibromatosis type 1; Crowe's sign","Neurofibromatosis type 1; Darier sign","Neurofibromatosis type 2","Multiple lentigines from sun exposure","Postinflammatory hyperpigmentation"],
("l7",26): ["Lipid-laden macrophages; screen for hyperlipidaemia","Lipid-laden macrophages; no investigation needed","Keratin in an epithelial cyst; excise","Eccrine duct neoplasms of puberty","Dilated capillaries; laser therapy"],
("l7",27): ["Lipoma; observe if asymptomatic","Epidermoid cyst; excise the capsule","Dermatofibroma; positive dimple sign","Abscess; incise and drain","Liposarcoma; urgent wide excision"],
("l7",28): ["A pseudo-cyst of mucin extruded from the joint","A true cyst lined by epithelium","An eccrine duct neoplasm","An overgrowth of dense fibrous tissue","A collection of lipid-laden macrophages"],
("l7",29): ["Dermoscopy","A potassium hydroxide preparation","A Wood's lamp examination","Serum lipid measurement","No test; excise every lesion"],
("l7",30): ["Intralesional steroid, silicone sheeting, or laser","No treatment is ever appropriate","Excision alone, which never recurs","Cryotherapy is always contraindicated","Systemic corticosteroids over six weeks"],
("l7",31): ["It warms the scar, raising collagenase; worn up to a year","It cools the scar; worn for two weeks","It induces hypoxia; worn for one month","It delivers steroid; worn for six weeks","It blocks ultraviolet; worn outdoors"],
("l7",32): ["Superficial, mixed, and deep; superficial commonest","Superficial, mixed, and deep; deep commonest","Capillary, cavernous, arteriovenous","Congenital, infantile, acquired","Proliferative, involuting, involuted"],
("l7",33): ["Compression of vital structures and blocked vision","Malignant transformation to angiosarcoma","Progressive darkening throughout life","Systemic hypertension from shunting","No complications occur"],
("l7",34): ["A dilated capillary under 1 mm that blanches","A dilated capillary under 1 mm that does not blanch","A 1 to 2 mm blood deposit that does not blanch","A capillary proliferation forming a papule","A congenital malformation"],
("l7",35): ["Over 5 mm before puberty, over 15 mm after","Over 15 mm before puberty, over 5 mm after","Over 5 mm at any age","Over 1 cm at any age","Size is not part of the definition"],
("l7",36): ["A large tumour in nerve covering that may invade","A discrete nerve sheath tumour at the surface","A pigmented macule growing with the child","Freckles under 5 mm in body folds","A tumour confined to brain and spinal cord"],
("l7",37): ["A soft pedunculated papilloma in areas of friction","A firm nodule with a keratin core on the sole","A translucent papule over a finger joint","A hard conical keratotic projection","A bright red friable papule that bleeds"],
("l7",38): ["Reduced sebocyte turnover; no malignant potential","Eccrine duct proliferation; low malignant risk","Fibrous overgrowth with local invasion","Ultraviolet dysplasia that may become carcinoma","Capillary proliferation with bleeding risk"],
("l7",39): ["Counselling on sunscreen and self-examination","Reassurance alone","Referral for full-body photography","Prophylactic excision of all lesions","Advising complete avoidance of outdoors"],

("l4",1): ["A topical retinoid, an oral antibiotic, and benzoyl peroxide","A topical retinoid and an oral antibiotic","An oral antibiotic alone, indefinitely","A topical retinoid alone","Oral isotretinoin as monotherapy"],
("l4",2): ["Pregnancy tests before, monthly, and 5 weeks after","A pregnancy test before starting only","Monthly liver tests, no pregnancy testing","Pregnancy tests before and one week after","No specific requirements"],
("l4",3): ["Separate them by at least three hours","Apply them together for better penetration","Apply together, washing vigorously between","Use only one of the two","Apply both twice daily; clear in a week"],
("l4",6): ["Reassurance; most resolve in 2 to 10 days","Oral ciprofloxacin for all patients","Oral trimethoprim-sulfamethoxazole","Topical mupirocin three times daily","Shower after hot tub use to prevent it"],
("l4",7): ["A foreign body reaction to re-entrant hair","Follicular infection by Staphylococcus aureus","An allergic reaction to shaving products","Apocrine gland occlusion","Follicular hyperkeratinisation with excess sebum"],
("l4",8): ["Avoid lift-and-cut razors; use a single blade","Use a multi-blade lift-and-cut razor","Shave daily against the grain","Keep shaving; rely on a topical steroid","Use a chemical depilatory on shaved skin"],
("l4",9): ["Warm compresses without antibiotics","Warm compresses plus oral cephalexin","Immediate incision and drainage","Oral trimethoprim-sulfamethoxazole","Squeezing the lesion"],
("l4",10): ["A carbuncle; incision and drainage","A furuncle; incision and drainage","A carbuncle; oral antibiotics alone","An abscess; warm soaks","Hidradenitis suppurativa; topical clindamycin"],
("l4",11): ["Typical lesions, axilla and groin, recurrence","Typical lesions, distribution, positive culture","Typical lesions, distribution, and biopsy","Fever, leukocytosis, and a draining sinus","One abscess with a family history"],
("l4",13): ["Corynebacterium minutissimum; topical erythromycin","Corynebacterium minutissimum; oral erythromycin","A dermatophyte; topical terbinafine","Candida albicans; topical miconazole","Staphylococcus aureus; topical mupirocin"],
("l4",14): ["Topical mupirocin, removing crusts first","Topical mupirocin over the intact crusts","Oral cephalexin","Oral trimethoprim-sulfamethoxazole","Oral penicillin V"],
("l4",15): ["Glomerulonephritis; antibiotics do not prevent it","Glomerulonephritis; earlier antibiotics would have","Treatment failure needing a new antibiotic","Rheumatic fever after the skin infection","An allergic reaction to the antibiotic"],
("l4",16): ["Staphylococcus aureus alone, via epidermolytic toxin","Staphylococcus or Streptococcus, via a skin break","Streptococcus pyogenes, by dermal invasion","Corynebacterium in the stratum corneum","Autoantibody against the basement membrane"],
("l4",19): ["Cellulitis has indistinct, unraised borders","Cellulitis is bilateral, erysipelas unilateral","Only cellulitis produces fever","Only erysipelas is streptococcal","Only cellulitis follows a portal of entry"],
("l4",20): ["Necrotizing fasciitis","A normal first-day treatment response","Contact dermatitis","Deep vein thrombosis alone","Allergy to cephalexin"],
("l4",21): ["Devitalised tissue; antibiotics cannot reach it","The expected look of resolving cellulitis","A drug reaction to the antibiotic","Deep vein thrombosis; anticoagulate","Increase the dose and observe"],
("l4",22): ["Immediate surgical consultation for debridement","Magnetic resonance imaging first","Antibiotics, reassess in 24 hours","Admit for observation and elevate","Bedside incision and drainage"],
("l4",23): ["Gas suggests Clostridium, not group A streptococcus","Gas suggests group A streptococcus, not Clostridium","Gas is present in every case","Gas means the infection is superficial","Gas means a fungal cause"],
("l4",24): ["Incision and drainage with oral antibiotics","Warm soaks three times daily alone","A topical antifungal and dry hands","Oral acyclovir for herpetic whitlow","Nail plate removal"],
("l4",25): ["Candida albicans; keep the hands dry","Staphylococcus aureus; keep the hands dry","Candida albicans; soak the hands daily","Pseudomonas aeruginosa; remove the nail","A dermatophyte; oral terbinafine"],
("l4",27): ["A healthcare worker or teacher","Any child under five","Any patient with honey-coloured crusting","Any patient on topical mupirocin","Only those who failed oral antibiotics"],
("l4",28): ["Hyperkeratinisation, sebum, Cutibacterium, inflammation","Hyperkeratinisation, reduced sebum, bacteria, inflammation","Apocrine occlusion, bacteria, sinus tracts, scarring","Neurovascular dysregulation and Demodex overgrowth","Autoimmune folliculitis and androgen excess"],
("l4",30): ["It suppresses Cutibacterium and limits resistance","It is comedolytic and normalises keratinisation","It inhibits tyrosinase and lightens pigment","It decreases sebum excretion","It provides ultraviolet protection"],
("l4",31): ["4 to 6 weeks; back and chest take 3 to 4 months","4 to 6 weeks, with all sites responding equally","Improvement within one week","No improvement for at least six months","Response cannot be measured objectively"],
("l4",32): ["Acne mechanica from pressure on the follicle","Drug-induced acne from an anabolic steroid","Endocrine acne from insulin resistance","Emotional stress raising cortisol","Genetic predisposition"],
("l4",33): ["Hyperandrogenism, unresponsive to topical therapy","Mild comedonal acne, never treated","A man with papulopustular acne","A woman planning pregnancy soon","Any adolescent, as first-line therapy"],
("l4",34): ["Mupirocin to the nares for the carrier state","A longer course of the same cream","Oral ciprofloxacin","A potassium hydroxide mount of a hair","An antibacterial soap alone"],
("l4",35): ["A potassium hydroxide wet mount","A Tzanck smear","A mineral oil preparation","A Wood's lamp examination","Direct immunofluorescence"],
("l4",36): ["Abscess from inoculation; furuncle from a follicle","Abscess from a follicle; furuncle from inoculation","Abscess involves apocrine, furuncle eccrine glands","Abscess is superficial; furuncle epidermal","Abscess is sterile; furuncle infected"],
("l4",38): ["Clinical; cultures and imaging add little","Blood and tissue cultures in every patient","Magnetic resonance imaging for depth","Skin biopsy in every patient","No laboratory testing is ever useful"],
("l4",39): ["Limited area, minimal pain, no systemic signs","Any cellulitis of the lower leg","Any patient who is afebrile","Any patient already on antibiotics","Only patients under 40"],
("l4",40): ["Bacterial killing inflames it; review at 48 hours","Bacterial killing inflames it; review after 7 days","The antibiotic is failing; change it on day one","The patient has become allergic","Devitalised tissue needing debridement"],
("l4",41): ["Trauma, burns, surgery, immunosuppression, alcoholism","Obesity, poor hygiene, occlusive clothing, humidity","Lymphatic impairment, athlete's foot, obesity","Manicure, ingrown nail, and nail biting","Wet work and chemical exposure"],
("l4",42): ["An aldosterone antagonist that lowers androgens","An immunosuppressant blocking tumour necrosis factor","It shrinks sinuses when injected into the lesion","A retinoid normalising keratinisation","An antibiotic suppressing the organism"],
("l4",44): ["Inner thighs, groin, and fourth toe web; often silent","Face and lower leg, with sudden high fever","Axilla, groin, and perineum, recurrent and painful","Around the nose and mouth, honey-crusted","Scalp, thighs, and trunk, with follicular pustules"],

("l6",1): ["They survive only on dead keratin","Salivary enzymes kill them","They require sebum","They are obligate intracellular organisms","They can involve mucosa if immunocompromised"],
("l6",2): ["Oral therapy; topicals miss the hair shaft","A topical cream to the lesion and beyond","An antifungal shampoo alone","A topical corticosteroid first","No treatment; it resolves after puberty"],
("l6",4): ["It excludes nothing; Trichophyton rarely fluoresces","It excludes tinea capitis","It indicates a bacterial cause","It means oral therapy can be avoided","It confirms Microsporum infection"],
("l6",6): ["Tinea corporis clears centrally; eczema does not","Nummular eczema clears centrally; tinea does not","Only tinea corporis is pruritic","Only nummular eczema affects the limbs","Only tinea corporis is well demarcated"],
("l6",7): ["It supports tinea cruris; candida involves the scrotum","It argues against a dermatophyte","It indicates erythrasma","It indicates inverse psoriasis","It has no diagnostic significance"],
("l6",10): ["Confirm the fungus; many dystrophic nails are not","Start terbinafine empirically","Obtain a Wood's lamp examination","Start topical antifungal therapy","Remove the nails surgically first"],
("l6",11): ["Six weeks fingernails, twelve toenails; check liver","Twelve weeks fingernails, six toenails; check liver","Two weeks for both; no monitoring","Six weeks for both; check renal function","Lifelong therapy"],
("l6",12): ["Dermatophyte elsewhere, none at the site, resolves","Dermatophyte elsewhere, fungal elements at the site","Positive bacterial culture, responds to antibiotics","Positive Wood's lamp, negative scraping, biopsy","Symmetric, painless, self-resolving"],
("l6",13): ["Tinea incognito; stop the corticosteroid","Tinea incognito; increase the steroid potency","Contact allergy; patch test first","Steroid atrophy; emollient and observe","Psoriasis unmasked; start calcipotriene"],
("l6",14): ["Satellite lesions; a topical azole covers both","Satellite lesions; nystatin covers both","Central clearing; terbinafine covers both","Coral-red fluorescence; topical erythromycin","Honey-coloured crusting; topical mupirocin"],
("l6",15): ["Dry the folds and reduce friction and occlusion","Apply an occlusive ointment to the folds","Increase the frequency of hot showers","Apply a high-potency corticosteroid","Bind the folds tightly together"],
("l6",16): ["Short hyphae with yeast clusters","Long septate branching hyphae","Budding yeast with pseudohyphae","Mites, eggs, and fecal pellets","No organisms; biopsy is needed"],
("l6",17): ["Pigment recovery lags months behind clearance","It is treatment failure needing oral therapy","Vitiligo is developing at the sites","It is now contagious to the household","A secondary bacterial infection"],
("l6",20): ["Pre-eruptive, acute eruptive, postherpetic neuralgia","Prodromal fever, generalised eruption, desquamation","Incubation, contagious, and latency","Pre-eruptive, eruptive, and scarring","Erythematous, bullous, and necrotic"],
("l6",21): ["It stops abruptly at the midline","It crosses the midline symmetrically","It is generalised over trunk and face","It follows a Christmas tree pattern","It is confined to skin folds"],
("l6",22): ["Hutchinson sign; start antivirals immediately","Hutchinson sign; its absence excludes eye disease","Ramsay Hunt syndrome","Zoster sine herpete","Disseminated zoster"],
("l6",23): ["Within 72 hours, and later if lesions still form","Within 72 hours only, never after","Within 7 days, with no exceptions","Only after polymerase chain reaction confirms it","Only once postherpetic neuralgia develops"],
("l6",24): ["Pain beyond 90 days; gabapentin or a tricyclic","Pain beyond 90 days; long-term opioids","Pain beyond 7 days; antivirals","Pain beyond 30 days; corticosteroids","Any acute pain; acetaminophen"],
("l6",25): ["Two doses from age 50, or 19 if immunosuppressed","A single dose from age 50","Two doses from age 65 only","Two doses only after an episode of zoster","Two doses in childhood"],
("l6",26): ["He cannot catch shingles, but could catch chickenpox","He can catch shingles from the lesions","There is no transmission risk at all","Transmission is by respiratory droplets only","Only if he has never had chickenpox"],
("l6",27): ["Either type causes either site; location is unreliable","Genital lesions are always type 2","Oral is always type 1, genital always type 2","The vesicle appearance identifies the type","The prodrome identifies the type"],
("l6",28): ["Nucleic acid amplification; a negative old swab excludes nothing","Viral culture; a negative result excludes infection","Immunoglobulin M serology","A Tzanck smear, which types the virus","A potassium hydroxide preparation"],
("l6",29): ["Daily suppressive valacyclovir","Patient-initiated episodic therapy","Topical acyclovir during outbreaks","Prophylaxis for the uninfected partner","No antiviral therapy"],
("l6",30): ["Do not incise; cover it and start oral antivirals","Incise and drain, then give antivirals","Incise and drain, then give antibiotics","A topical antifungal and a dry hand","Observe without treatment or precautions"],
("l6",31): ["Observation; procedures may scar or pigment","Curettage of every lesion at the first visit","Oral acyclovir","Topical mupirocin to each lesion","Salicylic acid 40 percent to each lesion"],
("l6",32): ["Central umbilication of a pearly dome-shaped papule","A rough grey surface with thrombosed capillaries","A stuck-on look with comedone-like openings","An annular plaque with central clearing","Grouped vesicles on an erythematous base"],
("l6",33): ["Thrombosed capillaries, distinguishing it from a callus","Keratin plugs, distinguishing it from a keratosis","Melanocytic nests, excluding melanoma","Fungal elements, excluding tinea manuum","Deep roots, confirming the need for excision"],
("l6",34): ["Flat warts; observe, as they resolve spontaneously","Verruca vulgaris; salicylic acid to each","Molluscum contagiosum; cantharidin","Plantar warts; salicylic acid and cryotherapy","Seborrheic keratoses; no treatment"],
("l6",36): ["Tinea barbae; oral antifungal therapy is required","Bacterial folliculitis; oral cephalexin","Tinea barbae; a topical cream is enough","Pseudofolliculitis barbae; change shaving","Acne vulgaris; a topical retinoid"],
("l6",37): ["Tinea manuum, often one palm and both soles","Irritant contact dermatitis","Palmar psoriasis","Dyshidrotic eczema","Chronic paronychia"],
("l6",38): ["Topical first line; oral if extensive or refractory","Oral terbinafine first line","Topical nystatin first line","Oral fluconazole for everyone","A high-potency topical corticosteroid"],
("l6",39): ["Avoid aspirin; use caution with anti-inflammatories","Avoid acetaminophen; prefer aspirin","Avoid all analgesics","Give antivirals instead of analgesia","Give systemic corticosteroids"],
("l6",40): ["Zoster sine herpete","Postherpetic neuralgia","The pre-eruptive phase","Ramsay Hunt syndrome","Disseminated zoster"],
("l6",41): ["Ramsay Hunt syndrome; add a systemic corticosteroid","Ramsay Hunt syndrome; an antiviral alone","Herpes zoster ophthalmicus; ophthalmology referral","Bell palsy; a corticosteroid alone","Otitis externa; antibiotic drops"],
("l6",42): ["Syphilis","Chancroid","Trauma","Candidiasis","Herpes simplex recurrence"],
("l6",43): ["Assess for other sexually transmitted infections","Assume abuse from the location alone","Reassure that it is never sexually transmitted","Give acyclovir and screen only for herpes","Refer for excision of all lesions"],
("l6",44): ["No therapy eradicates the virus; recurrence happens","Cryotherapy eradicates it and prevents recurrence","Treat all warts at diagnosis","Biopsy every wart first","Excise deeply; they reach the dermis"],
("l6",45): ["Thoracic about 55 percent, cranial about 20 percent","Cranial about 55 percent, thoracic about 20 percent","Sacral in the majority","Lumbar in the majority","No dermatome predominates"],
("l6",46): ["To the lesion and 1 to 2 cm beyond the border","To the visible lesion, stopping when it clears","To the whole limb","To the centre of the lesion only","Distance does not matter with oral therapy"],
("l6",48): ["No exclusion once treated; do not share hair items","Stay out of school until the scalp is clear","No household measures are needed","Stop treatment when itching improves","All household contacts take oral antifungals"],
("l6",49): ["By body location: capitis, corporis, cruris, pedis","By species: Trichophyton, Microsporum, Epidermophyton","By depth of dermal invasion","By whether it is contagious","By the patient's age"],
}
