# -*- coding: utf-8 -*-
"""Chronic Vision Loss and Tumors (Lecture 13) -- third pool, from the chart rows."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _cmsophtho_style import Q

D = "Chronic Vision Loss & Tumors"
IO = ("a — Chronic vision loss and ocular tumors: etiologies, epidemiology, risk factors, clinical "
      "manifestations, differential diagnosis, diagnostic testing, management, referrals, patient "
      "education, prognosis")

QUESTIONS = [

Q("Dry macular degeneration", IO,
  "What proportion of age-related macular degeneration is the dry form?",
  [["About eighty per cent", "Correct — the wet form accounts for the remaining twenty."],
   ["About half", "Understates the dry share."],
   ["About twenty per cent", "That is the WET share."],
   ["About ninety-five per cent", "Overstates the dry share."],
   ["About sixty per cent", "Below the stated figure."]],
  "two-step", D, 11),

Q("Dry macular degeneration", IO,
  "A 79-year-old woman has non-exudative macular degeneration. What is the single most important "
  "advice?",
  [["Stop smoking", "Correct — it comes ahead of supplementation."],
   ["Increase screen brightness", "Helpful for function but not the key advice."],
   ["Wear sunglasses outdoors", "Not the headline instruction."],
   ["Reduce salt intake", "Not a named measure."],
   ["Take daily aspirin", "Not a named measure for this condition."]],
  "treatment", D, 14),

Q("Dry macular degeneration", IO,
  "Which supplement formulation is named for dry macular degeneration?",
  [["AREDS2 — vitamins C and E, zinc, copper, lutein and zeaxanthin", "Correct."],
   ["Vitamin A alone", "Vitamin A toxicity is in fact a cause of papilledema."],
   ["Calcium and vitamin D", "A bone formulation, not an ocular one."],
   ["Iron and folate", "A haematinic combination with no ocular indication here."],
   ["Omega-3 alone", "Not among the named constituents."]],
  "treatment", D, 14),

Q("Wet macular degeneration", IO,
  "In wet macular degeneration, what does the choroidal neovascularisation eventually form?",
  [["A disciform scar", "Correct — it bleeds into the retina and organises."],
   ["Drusen", "Drusen are the deposits of the DRY form."],
   ["A macular hole", "Not the described end point."],
   ["An epiretinal membrane", "A different macular lesion entirely."],
   ["A cherry-red spot", "That is the central retinal artery occlusion finding."]],
  "two-step", D, 11),

Q("Wet macular degeneration", IO,
  "Which treatments are named for wet macular degeneration?",
  [["Intravitreal anti-VEGF, thermal laser photocoagulation or photodynamic therapy",
    "Correct."],
   ["AREDS2 supplementation alone", "That is the dry-form measure."],
   ["Laser trabeculoplasty", "A glaucoma procedure."],
   ["Scleral buckle", "A retinal detachment repair."],
   ["Lens extraction", "Addresses cataract."]],
  "treatment", D, 14),

Q("Nuclear cataract", IO,
  "A 72-year-old man has a brown discolouration at the centre of the lens and finds distance vision "
  "worse than near. Which cataract type is this?",
  [["Nuclear", "Correct — the myopic shift is why some patients read without glasses again."],
   ["Cortical", "Spoke-like opacities from the periphery inward."],
   ["Posterior subcapsular", "A plate-like opacity at the back of the lens."],
   ["Zonular", "The commonest paediatric type."],
   ["Polar", "A less common central paediatric type."]],
  "diagnosis", D, 36),

Q("Cortical cataract", IO,
  "A 68-year-old woman has spoke-like opacities extending inward from the lens periphery. When do "
  "symptoms begin?",
  [["Once the opacity reaches the centre, with glare as the commonest complaint",
    "Correct — it is asymptomatic until then."],
   ["Immediately, with loss of distance vision", "It is asymptomatic early."],
   ["Only after surgery", "Symptoms precede surgery."],
   ["Only in dim light", "Glare in bright conditions is the complaint."],
   ["Never; it is always asymptomatic", "It becomes symptomatic centrally."]],
  "two-step", D, 37),

Q("Posterior subcapsular cataract", IO,
  "A 46-year-old man on long-term corticosteroids has glare and trouble reading, and notes his "
  "vision improves once his pupils are dilated at the clinic. Which cataract type is this?",
  [["Posterior subcapsular", "Correct — characteristically improves with dilation, more rapid in "
                             "onset, and classically under fifty."],
   ["Nuclear", "Age-related, with a myopic shift rather than improvement on dilation."],
   ["Cortical", "Spoke-like peripheral opacities."],
   ["Zonular", "The commonest PAEDIATRIC type, a white opacity around the nucleus."],
   ["Polar", "A less common paediatric type, central and caught earlier."]],
  "diagnosis", D, 36),

Q("Posterior subcapsular cataract", IO,
  "Besides lens extraction, what else should be addressed in steroid-related posterior subcapsular "
  "cataract?",
  [["The steroid burden", "Correct — review the cause as well as removing the lens."],
   ["The intraocular pressure alone", "A separate steroid effect, but not the stated review."],
   ["The refractive correction", "Does not address the cause."],
   ["The patient's diet", "Not a named factor."],
   ["The corneal curvature", "Not related to the cataract."]],
  "two-step", D, 36),

Q("Pediatric cataract", IO,
  "Which is the commonest paediatric cataract type?",
  [["Zonular", "Correct — a white opacity around the nucleus."],
   ["Polar", "Less common, but central and therefore caught earlier."],
   ["Nuclear", "The age-related adult type."],
   ["Cortical", "The spoke-like adult type."],
   ["Posterior subcapsular", "Associated with steroids and diabetes."]],
  "two-step", D, 38),

Q("Pediatric cataract", IO,
  "A neonate is found to have a dense unilateral cataract. How does the timing of surgery differ "
  "from an adult?",
  [["It is done early rather than deferred, to prevent amblyopia",
    "Correct — in adults surgery waits until function is affected."],
   ["It is deferred until school age", "Delay causes irreversible amblyopia."],
   ["It is deferred until the child can cooperate", "The visual system will not wait."],
   ["It is never performed in neonates", "It is performed early."],
   ["It is done only if both eyes are affected", "A unilateral dense cataract is the greater "
                                                 "amblyopia risk."]],
  "treatment", D, 38),

Q("Myopia", IO,
  "Which lens corrects myopia, and how?",
  [["A concave lens, which scatters light and moves the focus back",
    "Correct — negative dioptre."],
   ["A convex lens, which converges light forward", "That corrects hyperopia."],
   ["A toric lens", "That corrects astigmatism."],
   ["A prism", "Used for diplopia rather than refractive error."],
   ["No lens; only surgery corrects it", "Spectacle correction is the named treatment."]],
  "two-step", D, 18),

Q("Myopia", IO,
  "Which risk factors for myopia are named?",
  [["Family history and prolonged near work", "Correct, and trauma displacing the lens forward "
                                              "can cause it."],
   ["Smoking and hypertension", "Vascular risk factors for other conditions."],
   ["Steroid use", "Associated with posterior subcapsular cataract."],
   ["Sun and wind exposure", "Associated with pinguecula and pterygium."],
   ["Contact lens wear", "Associated with corneal ulcer."]],
  "two-step", D, 18),

Q("Hyperopia", IO,
  "Which lens corrects hyperopia, and how?",
  [["A convex lens, which converges light forward onto the retina",
    "Correct — positive dioptre."],
   ["A concave lens, which scatters light", "That corrects myopia."],
   ["A toric lens", "That corrects astigmatism."],
   ["A prism", "Used for diplopia."],
   ["A tinted lens", "Does not alter refraction."]],
  "two-step", D, 19),

Q("Hyperopia", IO,
  "Which causes of hyperopia are named besides a naturally short eye?",
  [["Trauma displacing the lens backwards, or a mass behind the globe",
    "Correct — anything shortening the effective axial length."],
   ["Prolonged near work", "That is a myopia risk factor."],
   ["Corticosteroid use", "Associated with cataract."],
   ["Chronic sun exposure", "Associated with surface degenerations."],
   ["Diabetes alone", "Associated with cortical cataract and retinopathy."]],
  "two-step", D, 19),

Q("Astigmatism", IO,
  "Why does astigmatism blur vision at every distance?",
  [["Uneven curvature means no single point of focus forms on the retina",
    "Correct — multiple focal points."],
   ["The eye is too long", "That is myopia, which blurs distance selectively."],
   ["The eye is too short", "That is hyperopia."],
   ["The lens has stiffened", "That is presbyopia, a near problem."],
   ["The lens is opaque", "That is cataract."]],
  "two-step", D, 20),

Q("Astigmatism", IO,
  "Which lens corrects astigmatism?",
  [["A toric lens", "Correct."],
   ["A concave lens", "Corrects myopia."],
   ["A convex lens", "Corrects hyperopia."],
   ["A bifocal lens", "Addresses presbyopia alongside distance correction."],
   ["A prism", "Used for diplopia."]],
  "treatment", D, 20),

Q("Retinoblastoma", IO,
  "Which inheritance feature makes retinoblastoma easy to miss on family history?",
  [["The mutation is often recessive", "Correct — so the family history may be unremarkable."],
   ["It is always sporadic", "It arises from a genetic mutation."],
   ["It is X-linked", "Not the described pattern."],
   ["It only occurs in adults", "It is almost exclusively a disease of young children."],
   ["It is caused by an infection", "It is a genetic malignancy."]],
  "two-step", D, 41),

Q("Retinoblastoma", IO,
  "Besides leukocoria, how may retinoblastoma present?",
  [["Poor vision or a turned eye", "Correct."],
   ["A painful red eye with discharge", "That suggests infection."],
   ["Sudden painless total vision loss", "That is a vascular occlusion picture."],
   ["Bilateral disc swelling", "That is papilledema."],
   ["Recurrent nosebleeds", "Not an ocular presentation."]],
  "two-step", D, 41),

Q("Retinoblastoma", IO,
  "How is retinoblastoma managed?",
  [["Multimodal therapy under ocular oncology, with genetic counselling",
    "Correct — enucleation for large tumours."],
   ["Observation with annual photographs", "That is nevus surveillance."],
   ["Topical chemotherapy alone", "Not the described management."],
   ["Laser trabeculoplasty", "A glaucoma procedure."],
   ["Spectacle correction", "Does not treat a malignancy."]],
  "treatment", D, 42),

Q("Uveal melanoma", IO,
  "What is the commonest eye cancer in adults?",
  [["Uveal melanoma", "Correct — from melanocytes of the choroid, ciliary body or iris."],
   ["Retinoblastoma", "Almost exclusively a childhood tumour."],
   ["Conjunctival melanoma", "A distinct and less common entity."],
   ["Squamous cell carcinoma", "Named among the malignant neoplasms but not the commonest."],
   ["Iris nevus", "A benign lesion."]],
  "diagnosis", D, 44),

Q("Uveal melanoma", IO,
  "Which treatment is now most commonly used for uveal melanoma?",
  [["Radiation therapy", "Correct — enucleation is less often needed than it once was."],
   ["Enucleation in all cases", "Less often required now."],
   ["Topical chemotherapy", "Not the described treatment."],
   ["Observation alone", "Not appropriate for a malignancy."],
   ["Laser trabeculoplasty", "A glaucoma procedure."]],
  "treatment", D, 46),

Q("Uveal melanoma", IO,
  "How is uveal melanoma usually discovered?",
  [["Incidentally", "Correct — it is often found on routine examination."],
   ["Through sudden painful vision loss", "That is the acute angle-closure picture."],
   ["Through a red painful eye", "Suggests an inflammatory or infective cause."],
   ["Through bilateral field loss", "Suggests a chiasmal or intracranial process."],
   ["Through recurrent conjunctivitis", "Unrelated."]],
  "two-step", D, 44),

Q("Iris nevus", IO,
  "Which features describe a benign iris nevus?",
  [["Flat, under 3 mm, avascular and on the inferior iris",
    "Correct — and usually apparent around puberty."],
   ["Raised, vascular and rapidly growing", "Those are the concerning features."],
   ["Bilateral and symmetrical", "It is typically unilateral."],
   ["Painful and photophobic", "It is asymptomatic."],
   ["Associated with discharge", "It is not an inflammatory lesion."]],
  "diagnosis", D, 48),

Q("Iris nevus", IO,
  "How is an iris nevus followed up?",
  [["More frequently at first to confirm it is not growing, then annually",
    "Correct — surveillance with dilated review."],
   ["A single review and then discharge", "Stability must be established over time."],
   ["Immediate excision", "Not indicated for a benign lesion."],
   ["Monthly review indefinitely", "More often than the described schedule."],
   ["No follow-up at all", "Surveillance is the management."]],
  "treatment", D, 49),

Q("Conjunctival melanoma", IO,
  "How does a conjunctival melanoma differ in appearance from a conjunctival nevus?",
  [["The melanoma is raised and often vascular; the nevus is flat with clear cysts",
    "Correct — the cysts are the characteristic benign feature."],
   ["The melanoma is flat and the nevus raised", "That reverses the distinction."],
   ["Both look identical", "They have distinguishing features."],
   ["The melanoma is always amelanotic", "It is a pigmented lesion."],
   ["The nevus is always painful", "Both are typically asymptomatic."]],
  "two-step", D, 53),

Q("Idiopathic intracranial hypertension", IO,
  "Which demographic does idiopathic intracranial hypertension primarily affect?",
  [["Overweight women of childbearing age", "Correct."],
   ["Elderly men", "Wrong sex and wrong age band."],
   ["Young children", "The condition is described in adults."],
   ["Postmenopausal women", "The stated group is of childbearing age."],
   ["Men over fifty", "The condition predominantly affects women."]],
  "two-step", D, 4),

Q("Idiopathic intracranial hypertension", IO,
  "Which symptoms are named in idiopathic intracranial hypertension?",
  [["Intractable headache, transient visual obscuration and intracranial noises",
    "Correct, with pain behind the eyes and mild pain on eye movement."],
   ["Severe eye pain with nausea and halos", "That is acute angle closure."],
   ["Itching and stringy discharge", "That is allergic conjunctivitis."],
   ["Flashes, floaters and a curtain", "That is retinal detachment."],
   ["Jaw claudication and scalp tenderness", "That is giant cell arteritis."]],
  "two-step", D, 4),

Q("Idiopathic intracranial hypertension", IO,
  "What is the initial treatment of idiopathic intracranial hypertension?",
  [["Acetazolamide promptly, with a supervised weight reduction programme",
    "Correct — surgical cerebrospinal fluid diversion only if medical therapy fails."],
   ["Immediate optic nerve sheath fenestration", "Reserved for failure of medical therapy."],
   ["Topical pressure-lowering drops", "They address intraocular pressure, which is not raised."],
   ["High-dose corticosteroids", "Not the named first-line treatment."],
   ["Observation alone", "Untreated, vision is at risk."]],
  "treatment", D, 5),
]
