# -*- coding: utf-8 -*-
# Clinical Pathophysiology I Lecture 4 -- pool C.
# Objective 3: the molecular mechanisms of common ocular pathologies -- the
# inflammatory "-itises", eyelid and adnexal disease, corneal and lacrimal
# pathology.
#
# THIS IS THE POOL THAT OVERLAPS CMS I EXAM 2 LECTURE 1 ALMOST EXACTLY. The two
# lectures cover the same condition list. The line is that Clinical
# Pathophysiology asks WHY THE TISSUE FAILS and CMS asks WHAT TO DO, so every
# question here is a mechanism, an anatomical site, or a defining feature --
# never a management decision. cp_l4_partition.py enforces it.
#
# Correct answer is ALWAYS written first (c=0); the partition script rotates.
SRC = "4. Ophthalmic Pathophysiology_STUDENT VERSION_v2.pptx"
def c(n): return f"{SRC}, Slide {n}"
def au(): return "Lecture recording, 26 August 2026"

IO3 = "c — Describe the molecular mechanisms of common ocular pathologies"

POOL_C = [
 dict(topic="Where the -itis is", io=IO3, slot="etiology",
   q="Which tissue is inflamed in episcleritis?",
   opts=[
     ["The deep subconjunctival, episcleral tissue",
      "Correct — the episclera is a thin vascular layer between conjunctiva and sclera, and because the sclera itself is uninvolved there is no structural threat to the globe."],
     ["The sclera itself", "That is scleritis, which is deeper and vision-threatening."],
     ["The conjunctiva", "That is conjunctivitis."],
     ["The cornea", "That is keratitis."]],
   c=0, cite=c(5)),

 dict(topic="Where the -itis is", io=IO3, slot="etiology",
   q="Which structures are involved in anterior uveitis?",
   opts=[
     ["The iris alone, or the iris and ciliary body together",
      "Correct — iritis, or iridocyclitis when the ciliary body is included."],
     ["The choroid and the retina",
      "Those are involved in posterior uveitis."],
     ["The whole globe including the vitreous and aqueous",
      "That is endophthalmitis."],
     ["The sclera and the episclera",
      "Those are the scleritis and episcleritis territories."]],
   c=0, cite=c(5)),

 dict(topic="Where the -itis is", io=IO3, slot="etiology",
   q="What does endophthalmitis involve?",
   opts=[
     ["The intraocular fluids and tissues, especially the vitreous and aqueous",
      "Correct — organisms reach the vitreous and aqueous, which are avascular and immunologically privileged, so infection there meets little resistance and destroys the retina rapidly."],
     ["Only the anterior chamber",
      "Anterior chamber involvement alone is anterior uveitis or hypopyon; endophthalmitis extends through the intraocular fluids including the vitreous."],
     ["Only the cornea and conjunctiva",
      "Those are surface structures."],
     ["The orbital soft tissue behind the globe",
      "That is orbital cellulitis."]],
   c=0, cite=c(5)),

 dict(topic="Where the -itis is", io=IO3, slot="etiology",
   q="How does panophthalmitis differ from endophthalmitis?",
   opts=[
     ["It involves all layers of the globe and may extend into orbital tissue",
      "Correct — panophthalmitis extends beyond the intraocular contents through the sclera into the orbit, which is why it can present with proptosis and restricted movement."],
     ["It involves only the vitreous",
      "That is narrower than endophthalmitis, not broader."],
     ["It is limited to the anterior segment",
      "The term means the opposite."],
     ["It spares the sclera",
      "It involves all layers, sclera included."]],
   c=0, cite=c(5)),

 dict(topic="Conjunctivitis", io=IO3, slot="etiology",
   q="Which virus is named as the viral cause of conjunctivitis?",
   opts=[
     ["Adenovirus", "Correct — adenovirus replicates in conjunctival epithelium and provokes a lymphocytic response, producing follicles and preauricular adenopathy with watery discharge."],
     ["Herpes simplex virus", "That deck entry is for epithelial keratitis."],
     ["Varicella zoster virus", "That appears under herpes zoster ophthalmicus."],
     ["Cytomegalovirus", "Cytomegalovirus infects the retina in immunocompromised patients rather than causing conjunctivitis."]],
   c=0, cite=c(14)),

 dict(topic="Conjunctivitis", io=IO3, slot="manifestation",
   q="What is the defining feature of conjunctivitis?",
   opts=[
     ["Hyperaemia without severe deep pain",
      "Correct — the absence of deep pain is what separates it from the vision-threatening entries."],
     ["Deep boring pain with scleral melting risk",
      "That is scleritis."],
     ["White blood cells and flare in the anterior chamber",
      "That is anterior uveitis."],
     ["Stromal ulceration in a contact lens wearer",
      "That is keratitis."]],
   c=0, cite=c(14)),

 dict(topic="Episcleritis", io=IO3, slot="manifestation",
   q="How is episcleritis characterised?",
   opts=[
     ["A self-limiting inflammatory blush, not vision-threatening and without severe pain",
      "Correct — inflammation confined to a superficial vascular layer resolves spontaneously, and because the sclera and deeper structures are spared there is neither severe pain nor threat to vision."],
     ["A vision-threatening emergency with deep boring pain",
      "That is scleritis."],
     ["An infection of the corneal stroma",
      "That is keratitis."],
     ["A granulomatous blockage of a meibomian gland",
      "That is a chalazion."]],
   c=0, cite=c(14)),

 dict(topic="Scleritis", io=IO3, slot="manifestation",
   q="What distinguishes scleritis from episcleritis?",
   opts=[
     ["Severe deep boring pain, vision threat and a risk of scleral melting",
      "Correct — the sclera is densely innervated and is the structural coat of the eye, so its inflammation causes boring pain and progressive thinning that can perforate the globe."],
     ["A superficial blush that clears on its own",
      "That describes episcleritis."],
     ["Photophobia with a ciliary flush and cells in the anterior chamber",
      "That is anterior uveitis."],
     ["A dendritic ulcer on fluorescein staining",
      "That is herpes simplex epithelial keratitis."]],
   c=0, cite=c(14)),

 dict(topic="Scleritis", io=IO3, slot="etiology",
   q="Which systemic diseases are linked strongly to scleritis?",
   opts=[
     ["Rheumatoid arthritis, granulomatosis with polyangiitis and systemic vasculitis",
      "Correct — all three are immune-complex and vasculitic diseases, and the sclera's collagen and small vessels are targeted by the same process that attacks joints and lung."],
     ["Systemic lupus erythematosus, psoriatic arthritis and ankylosing spondylitis",
      "Those are seronegative and connective tissue associations of anterior uveitis, which is a different intraocular compartment and a different immune mechanism."],
     ["Diabetes mellitus and hypertension",
      "Diabetes and hypertension damage the retinal microvasculature; they do not drive the vasculitic scleral inflammation of scleritis."],
     ["Sarcoidosis and choroidal melanoma",
      "Those are exudative retinal detachment causes here."]],
   c=0, cite=c(14)),

 dict(topic="Anterior uveitis", io=IO3, slot="test finding",
   q="What is found in the anterior chamber in anterior uveitis?",
   opts=[
     ["White blood cells and flare",
      "Correct — cells and flare in the anterior chamber define it."],
     ["Pus forming a visible layer",
      "That is a hypopyon, a more advanced finding shown separately."],
     ["Blood forming a visible layer",
      "That is a hyphaema, from trauma."],
     ["Vitreous cells and chorioretinal lesions",
      "Those belong to posterior uveitis."]],
   c=0, cite=c(14)),

 dict(topic="Anterior uveitis", io=IO3, slot="etiology",
   q="Which systemic associations are given for anterior uveitis?",
   opts=[
     ["Systemic lupus erythematosus, psoriatic arthritis, inflammatory bowel disease and ankylosing spondylitis",
      "Correct — these are the HLA-B27 associated and connective tissue diseases, in which the same immune process that inflames joints and bowel targets the uveal tract."],
     ["Rheumatoid arthritis, granulomatosis with polyangiitis and vasculitis",
      "Those are vasculitic diseases associated with scleritis; anterior uveitis tracks the HLA-B27 and connective tissue group."],
     ["Diabetes mellitus and chronic kidney disease",
      "Diabetes and chronic kidney disease are not immune-mediated uveitis associations; the uveitis group is the HLA-B27 and connective tissue diseases."],
     ["Sarcoidosis and severe malignant hypertension",
      "Those appear under exudative retinal detachment."]],
   c=0, cite=c(14)),

 dict(topic="Hypopyon", io=IO3, slot="test finding",
   q="What is a hypopyon?",
   opts=[
     ["Pus in the anterior chamber", "Correct — inflammatory cells sediment under gravity in the aqueous, forming a visible layer of pus at the bottom of the anterior chamber."],
     ["Blood in the anterior chamber", "That is a hyphaema."],
     ["Fluid beneath the neurosensory retina", "That is a retinal detachment."],
     ["Yellow debris beneath the retinal pigment epithelium", "Those are drusen."]],
   c=0, cite=c(15)),

 dict(topic="Keratitis", io=IO3, slot="risk factors",
   q="Which patient group is flagged as at particular risk in keratitis, and from which organism?",
   opts=[
     ["Contact lens wearers, from Pseudomonas",
      "Correct — Pseudomonas produces proteases that digest corneal stroma and adheres to hydrogel lens material, so a lens wearer can lose the cornea within days."],
     ["Contact lens wearers, from Staphylococcus aureus",
      "Staphylococcus aureus causes keratitis but is not the organism that makes contact lens wear so dangerous; Pseudomonas is, through its stromal proteases."],
     ["Elderly patients, from Streptococcus pneumoniae",
      "Age is not the flagged risk factor here; contact lens wear is, with Pseudomonas as the destructive organism."],
     ["Immunosuppressed patients, from Candida",
      "Fungal keratitis occurs but is not the highlighted pairing; contact lens wear with Pseudomonas is."]],
   c=0, cite=c(14)),

 dict(topic="Keratitis", io=IO3, slot="complication",
   q="Which complications are attached to keratitis?",
   opts=[
     ["Corneal stromal ulceration, perforation and endophthalmitis",
      "Correct — infection digests the stroma into an ulcer, the thinned cornea perforates, and organisms then enter the intraocular fluids to cause endophthalmitis."],
     ["Scleral melting and globe rupture",
      "Scleral melting belongs to scleritis."],
     ["Retinal tear and vitreous haemorrhage",
      "Those are posterior segment complications."],
     ["Optic disc cupping and peripheral field loss",
      "That is glaucomatous damage."]],
   c=0, cite=c(14)),

 dict(topic="Orbital cellulitis", io=IO3, slot="etiology",
   q="What anatomically defines orbital, as opposed to periorbital, cellulitis?",
   opts=[
     ["Infection has breached the orbital septum and lies posterior to the globe",
      "Correct — the orbital septum is a fibrous sheet running from periosteum to tarsal plate, and whether infection lies in front of or behind it determines whether the globe and optic nerve are at risk."],
     ["Infection is confined to the preseptal lids and periocular skin",
      "That is periorbital, or preseptal, cellulitis."],
     ["Infection has spread from the paranasal sinuses only",
      "Sinus spread is a route, not the anatomical definition."],
     ["Infection involves the lacrimal sac",
      "That is dacryocystitis."]],
   c=0, cite=c(16)),

 dict(topic="Orbital cellulitis", io=IO3, slot="manifestation",
   q="Which findings are given for orbital cellulitis that periorbital cellulitis lacks?",
   opts=[
     ["Proptosis, decreased extraocular movement and a risk of optic nerve compression",
      "Correct — a post-septal collection occupies a closed bony orbit, so it pushes the globe forward, inflames the extraocular muscles and raises pressure on the optic nerve."],
     ["Erythema and oedema of the lid, localised by the septum",
      "That is the periorbital picture."],
     ["Crusting of the lid margin with altered tear film",
      "That is blepharitis."],
     ["A yellowish nodule that does not cross the cornea",
      "That is a pinguecula."]],
   c=0, cite=c(16)),

 dict(topic="Periorbital cellulitis", io=IO3, slot="etiology",
   q="Why does periorbital cellulitis stay localised, and what does it spare?",
   opts=[
     ["The orbital septum acts as a firm barrier, so extraocular movement and vision are spared",
      "Correct — the septum is a fibrous barrier fusing periosteum to tarsal plate, so infection in front of it cannot reach the muscles or optic nerve behind."],
     ["The conjunctiva acts as a barrier, so the cornea is spared",
      "The conjunctiva is a thin mucous membrane, not a barrier to spread; the orbital septum is what confines preseptal infection."],
     ["The tear film washes the infection away, so the globe is spared",
      "The tear film contains lysozyme but cannot contain a soft tissue infection; the orbital septum is the anatomical barrier."],
     ["It is always viral, so it does not spread",
      "Both forms are usually bacterial; what keeps preseptal disease localised is the orbital septum rather than the organism."]],
   c=0, cite=c(16)),

 dict(topic="Blepharitis", io=IO3, slot="etiology",
   q="What is the mechanism by which meibomian gland obstruction produces blepharitis symptoms?",
   opts=[
     ["Altered tear film composition causes excessive tear evaporation, irritating the lid margin",
      "Correct — meibomian lipid normally seals the tear film, so when the glands block, the aqueous layer evaporates too quickly and the exposed lid margin and ocular surface become inflamed."],
     ["Bacterial invasion of the tarsal plate causes an abscess",
      "That describes a hordeolum rather than blepharitis."],
     ["Aqueous tear production falls because the lacrimal gland is inflamed",
      "That is dacryoadenitis and aqueous-deficient dry eye."],
     ["The eyelashes turn inward and abrade the cornea",
      "That is trichiasis from entropion."]],
   c=0, cite=c(16)),

 dict(topic="Dry eye", io=IO3, slot="etiology",
   q="What are the two routes to keratoconjunctivitis sicca, and what is the common downstream step?",
   opts=[
     ["Aqueous tear deficiency or excessive evaporation, both raising tear osmolarity and damaging the corneal epithelium",
      "Correct — two upstream causes converging on a single mechanism."],
     ["Bacterial and viral infection, both causing purulent discharge",
      "Infection produces purulent discharge and an inflammatory response; dry eye arises from tear deficiency or evaporation raising tear osmolarity."],
     ["Raised intraocular pressure and optic nerve compression",
      "That is glaucoma."],
     ["Ultraviolet exposure and fibrovascular proliferation",
      "That is pinguecula and pterygium."]],
   c=0, cite=c(16)),

 dict(topic="Herpes simplex keratitis", io=IO3, slot="test finding",
   q="What is the classical corneal finding in herpes simplex epithelial keratitis?",
   opts=[
     ["A dendritic ulcer with terminal bulbs on fluorescein staining",
      "Correct — virus spreads cell to cell through the epithelium along a branching front, and the swollen terminal bulbs mark where infected cells have lifted away."],
     ["A geographic ulcer with a hypopyon",
      "A geographic ulcer is what a dendrite becomes when it enlarges, often after corticosteroid exposure; the classical finding is the branching dendrite with terminal bulbs."],
     ["A ring infiltrate in a contact lens wearer",
      "That pattern is associated with other organisms."],
     ["A wedge of fibrovascular tissue crossing the limbus",
      "That is a pterygium."]],
   c=0, cite=c(17)),

 dict(topic="Herpes zoster ophthalmicus", io=IO3, slot="etiology",
   q="Which nerve distribution does herpes zoster ophthalmicus follow?",
   opts=[
     ["The first division of the trigeminal nerve",
      "Correct — the ophthalmic division, and the rash respects the midline."],
     ["The facial nerve",
      "The facial nerve is motor to the muscles of expression; zoster ophthalmicus reactivates in the trigeminal ganglion and follows its ophthalmic sensory division."],
     ["The second division of the trigeminal nerve",
      "The maxillary division does not carry the ophthalmic distribution."],
     ["The oculomotor nerve",
      "That is a motor nerve to the extraocular muscles."]],
   c=0, cite=c(17)),

 dict(topic="Herpes zoster ophthalmicus", io=IO3, slot="test finding",
   q="What is Hutchinson sign and why does it matter?",
   opts=[
     ["A vesicle on the tip of the nose, indicating nasociliary branch involvement and therefore high ocular risk",
      "Correct — the nasociliary branch supplies both the tip of the nose and the globe, so vesicles on the nose tip mark that the branch carrying virus also innervates the eye."],
     ["A vesicle on the eyelid margin, indicating meibomian gland involvement",
      "The sign is on the nose tip and reflects the nasociliary branch."],
     ["A dendritic corneal ulcer, indicating simplex rather than zoster",
      "That is the simplex finding."],
     ["Unilateral rash crossing the midline, indicating disseminated disease",
      "The zoster rash respects the midline; crossing it is not this sign."]],
   c=0, cite=c(17)),

 dict(topic="Pinguecula and pterygium", io=IO3, slot="etiology",
   q="What is the shared mechanism behind pinguecula and pterygium?",
   opts=[
     ["Submucosal fibrovascular conjunctival proliferation from chronic ultraviolet, wind and dust exposure",
      "Correct — chronic ultraviolet and mechanical irritation damage limbal stem cells and provoke fibrovascular proliferation in the conjunctival substantia propria."],
     ["Bacterial colonisation of the limbal conjunctiva",
      "Neither lesion is infective; both are degenerative fibrovascular proliferations driven by chronic ultraviolet, wind and dust exposure."],
     ["Deposition of cholesterol in the conjunctival stroma",
      "That describes xanthelasma, and it affects the lids."],
     ["Rupture of episcleral capillaries beneath the conjunctiva",
      "That is a subconjunctival haemorrhage."]],
   c=0, cite=c(17)),

 dict(topic="Pinguecula and pterygium", io=IO3, slot="differential",
   q="What single feature separates a pterygium from a pinguecula?",
   opts=[
     ["The pterygium encroaches onto the cornea; the pinguecula does not",
      "Correct — Webster put it as crossing the limbus, and called this section important."],
     ["The pterygium is yellow; the pinguecula is triangular",
      "The colour and shape descriptions are the wrong way round and are not the separator."],
     ["The pterygium is painful; the pinguecula is painless",
      "Both are typically painless or mildly irritating; what separates them is whether the fibrovascular tissue has crossed the limbus onto the cornea."],
     ["The pterygium is bilateral; the pinguecula is unilateral",
      "Laterality is not the separator."]],
   c=0, cite=c(17)),

 dict(topic="Chalazion and hordeolum", io=IO3, slot="differential",
   q="What is the mechanism and character of a chalazion?",
   opts=[
     ["A chronic, non-tender, sterile granulomatous lipogranuloma of a blocked meibomian gland",
      "Correct — sterile and granulomatous is what separates it from an infection."],
     ["An acute, tender, focal abscess of a gland at the lid margin",
      "That is a hordeolum."],
     ["A cholesterol-filled plaque along the nasal eyelid",
      "That is xanthelasma."],
     ["Redundant lid skin with prolapse of orbital fat",
      "That is dermatochalasis."]],
   c=0, cite=c(17)),

 dict(topic="Chalazion and hordeolum", io=IO3, slot="etiology",
   q="Which glands are involved in an external as opposed to an internal hordeolum?",
   opts=[
     ["External involves the glands of Zeis or Moll; internal involves a meibomian gland",
      "Correct — the glands of Zeis and Moll open at the lash line so their infection points outward, while the meibomian glands lie within the tarsal plate so their infection points onto the conjunctival surface."],
     ["External involves a meibomian gland; internal involves the glands of Zeis or Moll",
      "The assignment is reversed: the superficial glands of Zeis and Moll give the external form, and the deeper meibomian glands the internal one."],
     ["Both involve the lacrimal gland",
      "The lacrimal gland is not involved in hordeolum."],
     ["Both involve the tarsal plate itself rather than any gland",
      "The tarsal plate holds the meibomian glands but is not itself the site."]],
   c=0, cite=c(17)),

 dict(topic="Eyelid anatomy", io=IO3, slot="etiology",
   q="Which glands produce the lipid layer of the tear film, and where do they sit?",
   opts=[
     ["The meibomian glands, modified sebaceous glands within the tarsal plates",
      "Correct — and the lipid layer is what prevents evaporation."],
     ["The glands of Zeis and Moll, associated with the eyelash follicles",
      "Those are sebaceous and modified sweat glands of the lash line."],
     ["The lacrimal gland, in the superotemporal orbit",
      "That produces the aqueous component."],
     ["The goblet cells of the palpebral conjunctiva",
      "Those produce mucin, not lipid."]],
   c=0, cite=c(13)),

 dict(topic="Eyelid anatomy", io=IO3, slot="etiology",
   q="What does the lipid layer of the tear film do?",
   opts=[
     ["It prevents evaporation", "Correct — meibomian lipid spreads as the outermost layer and seals the aqueous beneath it, so without it the tear film evaporates within seconds of a blink."],
     ["It provides the bulk volume of the tears", "That is the aqueous component."],
     ["It anchors the tear film to the corneal epithelium", "That is the mucin layer's role."],
     ["It carries immunoglobulin to the ocular surface", "Immunoglobulin A is carried in the aqueous layer from the lacrimal gland; the lipid layer's role is to retard evaporation."]],
   c=0, cite=c(13)),

 dict(topic="Eyelid anatomy", io=IO3, slot="etiology",
   q="What is the fornix, and why does it matter mechanically?",
   opts=[
     ["A flexible junctional cul-de-sac that permits free rotation of the globe",
      "Correct — the conjunctiva doubles back on itself at the fornix, creating a reserve of slack membrane that lets the globe rotate fully without tethering."],
     ["The dense fibrous plate giving the eyelid its shape",
      "That is the tarsus."],
     ["The sphincteric muscle responsible for blinking",
      "That is orbicularis oculi."],
     ["The junction where the conjunctiva meets the cornea",
      "That is the limbus."]],
   c=0, cite=c(13)),

 dict(topic="Eyelid anatomy", io=IO3, slot="etiology",
   q="Which muscle closes the eyelids, and what type is it?",
   opts=[
     ["Orbicularis oculi, a sphincteric striated muscle",
      "Correct — responsible for blinking and forced closure."],
     ["Levator palpebrae superioris, a striated muscle",
      "That elevates the lid rather than closing it."],
     ["Müller muscle, a smooth muscle",
      "That contributes to lid elevation, not closure."],
     ["The ciliary muscle, a smooth muscle",
      "That governs accommodation inside the eye."]],
   c=0, cite=c(13)),

 dict(topic="Corneal injury", io=IO3, slot="differential",
   q="What anatomically separates a corneal abrasion from a corneal ulceration?",
   opts=[
     ["An abrasion is limited to the epithelium; an ulcer penetrates the epithelial basement membrane into the stroma",
      "Correct — the depth relative to the basement membrane is the dividing line."],
     ["An abrasion involves the stroma; an ulcer is limited to the epithelium",
      "This reverses the two."],
     ["An abrasion is infective; an ulcer is mechanical",
      "Causation runs the other way: abrasions are typically mechanical and ulcers typically infective, but the defining difference is depth relative to the basement membrane."],
     ["An abrasion always scars; an ulcer heals cleanly",
      "The reverse holds: an abrasion heals rapidly without scarring because the basement membrane is intact, while an ulcer scars."]],
   c=0, cite=c(19)),

 dict(topic="Corneal injury", io=IO3, slot="etiology",
   q="What molecular mechanism causes tissue loss in a corneal ulcer?",
   opts=[
     ["Bacterial collagenases melt corneal tissue",
      "Correct — bacterial collagenases digest the collagen lamellae of the stroma, so tissue is lost and the replacement collagen is laid down irregularly, scattering light as a scar."],
     ["Neutrophil elastase digests the epithelial basement membrane",
      "Host neutrophil enzymes contribute to the damage, but the melting of stromal tissue is attributed to bacterial collagenases."],
     ["Osmotic swelling from sorbitol accumulation",
      "That is the diabetic cataract mechanism."],
     ["Complement-mediated lysis of keratocytes",
      "Complement-mediated lysis is not the mechanism; bacterial collagenases digest the stromal collagen directly."]],
   c=0, cite=c(19)),

 dict(topic="Corneal injury", io=IO3, slot="prognosis",
   q="Why does a corneal abrasion heal without scarring while an ulcer does not?",
   opts=[
     ["The abrasion has not breached the basement membrane, so the epithelium regenerates over intact scaffolding",
      "Correct — an intact basement membrane guides epithelial cells back in their original arrangement, whereas stromal loss is repaired with disorganised collagen that scatters light."],
     ["The abrasion is avascular and so cannot form scar tissue",
      "The whole cornea is avascular; that is not the difference."],
     ["The abrasion is always sterile and the ulcer always infected",
      "Infection is not the defining difference; a sterile ulcer still scars, because the stroma below the basement membrane has been lost."],
     ["The abrasion is treated sooner",
      "Timing affects outcome but not the principle; the scaffolding of the basement membrane is what allows scar-free regeneration."]],
   c=0, cite=c(19)),

 dict(topic="Lacrimal disease", io=IO3, slot="differential",
   q="What separates dacryocystitis from dacryoadenitis anatomically?",
   opts=[
     ["Dacryocystitis is the lacrimal SAC at the medial canthus; dacryoadenitis is the lacrimal GLAND at the superotemporal orbital rim",
      "Correct — sac against gland, and medial against superotemporal."],
     ["Dacryocystitis is the gland and dacryoadenitis is the sac",
      "This reverses the two."],
     ["Both involve the lacrimal gland, differing only in chronicity",
      "They involve different structures."],
     ["Both involve the nasolacrimal duct, differing only in organism",
      "The duct is downstream of the sac and is not the distinction."]],
   c=0, cite=c(19)),

 dict(topic="Lacrimal disease", io=IO3, slot="manifestation",
   q="Which lid deformity is associated with dacryoadenitis?",
   opts=[
     ["An S-shaped lid deformity", "Correct — the inflamed lacrimal gland enlarges in the lateral upper lid, depressing that portion of the lid margin and giving it an S-shaped contour."],
     ["An inward-turning lid margin", "That is entropion."],
     ["An outward-turning lid margin", "That is ectropion."],
     ["A drooping upper lid from levator weakness", "That is ptosis."]],
   c=0, cite=c(19)),

 dict(topic="Subconjunctival haemorrhage", io=IO3, slot="etiology",
   q="What is the mechanism of a subconjunctival haemorrhage?",
   opts=[
     ["Rupture of delicate episcleral or conjunctival capillaries, leaking blood beneath the conjunctiva",
      "Correct — these vessels are thin-walled and unsupported by surrounding tissue, so a rise in venous pressure or impaired haemostasis lets blood track freely in the potential space beneath the conjunctiva."],
     ["Leakage of aqueous humour into the subconjunctival space",
      "Aqueous does not leak there in this condition."],
     ["Fibrovascular proliferation from ultraviolet exposure",
      "That is pinguecula and pterygium."],
     ["Breakdown of the blood-retinal barrier",
      "That is a posterior segment mechanism."]],
   c=0, cite=c(19)),

 dict(topic="Subconjunctival haemorrhage", io=IO3, slot="risk factors",
   q="Which triggers are listed for subconjunctival haemorrhage?",
   opts=[
     ["Valsalva from coughing, vomiting or heavy lifting, minor trauma, hypertension, age-related vessel fragility and coagulopathy",
      "Correct — each either raises venous pressure abruptly, weakens the vessel wall, or impairs clotting, and any of the three lets an unsupported conjunctival capillary rupture."],
     ["Ultraviolet light, wind and dust exposure",
      "Those drive pinguecula and pterygium."],
     ["Contact lens wear and corneal abrasion",
      "Those relate to keratitis."],
     ["Chronic corticosteroid use and diabetes",
      "Corticosteroids and diabetes promote cataract through lens metabolism; conjunctival bleeding follows raised venous pressure, fragile vessels or impaired clotting."]],
   c=0, cite=c(19)),

 dict(topic="Subconjunctival haemorrhage", io=IO3, slot="prognosis",
   q="What is the natural course of a subconjunctival haemorrhage?",
   opts=[
     ["Benign, resolving over one to two weeks with bruise-like colour changes",
      "Correct — the extravasated blood is broken down and reabsorbed like any bruise, passing through the same haemoglobin degradation colours over one to two weeks."],
     ["Progressive, threatening vision within days",
      "The blood lies outside the globe and does not affect the visual axis, so vision is unthreatened and the collection reabsorbs."],
     ["Permanent, leaving a fibrovascular scar",
      "It resolves."],
     ["Recurrent by definition, requiring long-term follow-up",
      "Recurrence is not intrinsic to the condition; a single episode resolves completely, though repeated ones prompt a search for a bleeding tendency."]],
   c=0, cite=c(19)),

 dict(topic="Dermatochalasis", io=IO3, slot="etiology",
   q="What is dermatochalasis, and what is its functional consequence?",
   opts=[
     ["Redundant eyelid skin with prolapse of orbital fat, which can seriously limit the visual field",
      "Correct — loss of skin elasticity with age lets the upper lid skin and herniated orbital fat drape over the lid margin, physically occluding the superior visual field."],
     ["Cholesterol-filled plaques around the lids associated with hyperlipidaemia",
      "That is xanthelasma."],
     ["Inward turning of the lid margin causing corneal abrasion",
      "That is entropion."],
     ["Chronic granulomatous blockage of a meibomian gland",
      "That is a chalazion."]],
   c=0, cite=c(18)),

 dict(topic="Xanthelasma", io=IO3, slot="etiology",
   q="What are xanthelasma lesions made of, and what are they associated with?",
   opts=[
     ["Abnormal lipid deposition around the lids, usually bilateral, associated with hyperlipidaemia",
      "Correct — lipid-laden macrophages accumulate in the dermis of the thin periocular skin, and their presence signals disordered lipid handling even where serum lipids read normal."],
     ["Redundant skin with prolapsed orbital fat, associated with ageing",
      "That is dermatochalasis."],
     ["Sterile granuloma of a meibomian gland, associated with rosacea",
      "That is a chalazion."],
     ["Fibrovascular conjunctival tissue, associated with ultraviolet exposure",
      "That is pinguecula."]],
   c=0, cite=c(18)),
]
