# -*- coding: utf-8 -*-
# Clinical Pathophysiology I Lecture 4 -- pool C.
# Objective 3: the molecular mechanisms of common ocular pathologies -- the
# inflammatory "-itises", eyelid and adnexal disease, corneal and lacrimal
# pathology.
#
# THIS IS THE POOL THAT OVERLAPS CMS I EXAM 2 LECTURE 1 ALMOST EXACTLY. The two
# lectures cover the same condition list. The line is that Clinical
# Pathophysiology asks WHY THE TISSUE FAILS and CMS asks WHAT TO DO, so every
# question here is a mechanism, an anatomical site, or a defining feature --
# never a management decision. cp_l4_partition.py enforces it.
#
# Correct answer is ALWAYS written first (c=0); the partition script rotates.
SRC = "4. Ophthalmic Pathophysiology_STUDENT VERSION_v2.pptx"
def c(n): return f"{SRC}, Slide {n}"
def au(): return "Lecture recording, 26 August 2026"

IO3 = "c — Describe the molecular mechanisms of common ocular pathologies"

POOL_C = [
 dict(topic="Where the -itis is", io=IO3, slot="etiology",
   q="Which tissue is inflamed in episcleritis?",
   opts=[
     ["The deep subconjunctival, episcleral tissue",
      "Correct — the deck places episcleritis in the episcleral layer, superficial to sclera."],
     ["The sclera itself", "That is scleritis, which is deeper and vision-threatening."],
     ["The conjunctiva", "That is conjunctivitis."],
     ["The cornea", "That is keratitis."]],
   c=0, cite=c(5)),

 dict(topic="Where the -itis is", io=IO3, slot="etiology",
   q="Which structures are involved in anterior uveitis?",
   opts=[
     ["The iris alone, or the iris and ciliary body together",
      "Correct — iritis, or iridocyclitis when the ciliary body is included."],
     ["The choroid and the retina",
      "Those are involved in posterior uveitis."],
     ["The whole globe including the vitreous and aqueous",
      "That is endophthalmitis."],
     ["The sclera and the episclera",
      "Those are the scleritis and episcleritis territories."]],
   c=0, cite=c(5)),

 dict(topic="Where the -itis is", io=IO3, slot="etiology",
   q="What does endophthalmitis involve?",
   opts=[
     ["The intraocular fluids and tissues, especially the vitreous and aqueous",
      "Correct — the speaker notes define it as inflammation of the intraocular contents."],
     ["Only the anterior chamber",
      "The deck describes involvement of the whole intraocular contents."],
     ["Only the cornea and conjunctiva",
      "Those are surface structures."],
     ["The orbital soft tissue behind the globe",
      "That is orbital cellulitis."]],
   c=0, cite=c(5)),

 dict(topic="Where the -itis is", io=IO3, slot="etiology",
   q="How does panophthalmitis differ from endophthalmitis?",
   opts=[
     ["It involves all layers of the globe and may extend into orbital tissue",
      "Correct — the speaker notes draw exactly this distinction."],
     ["It involves only the vitreous",
      "That is narrower than endophthalmitis, not broader."],
     ["It is limited to the anterior segment",
      "The term means the opposite."],
     ["It spares the sclera",
      "It involves all layers, sclera included."]],
   c=0, cite=c(5)),

 dict(topic="Conjunctivitis", io=IO3, slot="etiology",
   q="Which virus does the deck name as the viral cause of conjunctivitis?",
   opts=[
     ["Adenovirus", "Correct — the deck's named viral agent."],
     ["Herpes simplex virus", "That deck entry is for epithelial keratitis."],
     ["Varicella zoster virus", "That appears under herpes zoster ophthalmicus."],
     ["Cytomegalovirus", "Not named by the deck for conjunctivitis."]],
   c=0, cite=c(14)),

 dict(topic="Conjunctivitis", io=IO3, slot="manifestation",
   q="What is the defining feature of conjunctivitis in the deck's inflammation table?",
   opts=[
     ["Hyperaemia without severe deep pain",
      "Correct — the absence of deep pain is what separates it from the vision-threatening entries."],
     ["Deep boring pain with scleral melting risk",
      "That is scleritis."],
     ["White blood cells and flare in the anterior chamber",
      "That is anterior uveitis."],
     ["Stromal ulceration in a contact lens wearer",
      "That is keratitis."]],
   c=0, cite=c(14)),

 dict(topic="Episcleritis", io=IO3, slot="manifestation",
   q="How does the deck characterise episcleritis?",
   opts=[
     ["A self-limiting inflammatory blush, not vision-threatening and without severe pain",
      "Correct — the deck's characterisation, in deliberate contrast to scleritis."],
     ["A vision-threatening emergency with deep boring pain",
      "That is scleritis."],
     ["An infection of the corneal stroma",
      "That is keratitis."],
     ["A granulomatous blockage of a meibomian gland",
      "That is a chalazion."]],
   c=0, cite=c(14)),

 dict(topic="Scleritis", io=IO3, slot="manifestation",
   q="What distinguishes scleritis from episcleritis?",
   opts=[
     ["Severe deep boring pain, vision threat and a risk of scleral melting",
      "Correct — the deck flags scleritis as an emergency for exactly these reasons."],
     ["A superficial blush that clears on its own",
      "That describes episcleritis."],
     ["Photophobia with a ciliary flush and cells in the anterior chamber",
      "That is anterior uveitis."],
     ["A dendritic ulcer on fluorescein staining",
      "That is herpes simplex epithelial keratitis."]],
   c=0, cite=c(14)),

 dict(topic="Scleritis", io=IO3, slot="etiology",
   q="Which systemic diseases does the deck link strongly to scleritis?",
   opts=[
     ["Rheumatoid arthritis, granulomatosis with polyangiitis and systemic vasculitis",
      "Correct — the three the deck names."],
     ["Systemic lupus erythematosus, psoriatic arthritis and ankylosing spondylitis",
      "Those are the deck's anterior uveitis associations."],
     ["Diabetes mellitus and hypertension",
      "Those drive retinopathy rather than scleritis in this deck."],
     ["Sarcoidosis and choroidal melanoma",
      "Those are exudative retinal detachment causes here."]],
   c=0, cite=c(14)),

 dict(topic="Anterior uveitis", io=IO3, slot="test finding",
   q="What is found in the anterior chamber in anterior uveitis?",
   opts=[
     ["White blood cells and flare",
      "Correct — cells and flare in the anterior chamber define it."],
     ["Pus forming a visible layer",
      "That is a hypopyon, a more advanced finding shown separately."],
     ["Blood forming a visible layer",
      "That is a hyphaema, from trauma."],
     ["Vitreous cells and chorioretinal lesions",
      "Those belong to posterior uveitis."]],
   c=0, cite=c(14)),

 dict(topic="Anterior uveitis", io=IO3, slot="etiology",
   q="Which systemic associations does the deck give for anterior uveitis?",
   opts=[
     ["Systemic lupus erythematosus, psoriatic arthritis, inflammatory bowel disease and ankylosing spondylitis",
      "Correct — the deck's four associations for iritis."],
     ["Rheumatoid arthritis, granulomatosis with polyangiitis and vasculitis",
      "Those are the deck's scleritis associations."],
     ["Diabetes mellitus and chronic kidney disease",
      "Not the deck's uveitis associations."],
     ["Sarcoidosis and severe malignant hypertension",
      "Those appear under exudative retinal detachment."]],
   c=0, cite=c(14)),

 dict(topic="Hypopyon", io=IO3, slot="test finding",
   q="What is a hypopyon?",
   opts=[
     ["Pus in the anterior chamber", "Correct — the deck labels it directly on the image slide."],
     ["Blood in the anterior chamber", "That is a hyphaema."],
     ["Fluid beneath the neurosensory retina", "That is a retinal detachment."],
     ["Yellow debris beneath the retinal pigment epithelium", "Those are drusen."]],
   c=0, cite=c(15)),

 dict(topic="Keratitis", io=IO3, slot="risk factors",
   q="Which patient group does the deck flag as at particular risk in keratitis, and from which organism?",
   opts=[
     ["Contact lens wearers, from Pseudomonas",
      "Correct — the deck names both the group and the organism."],
     ["Contact lens wearers, from Staphylococcus aureus",
      "The deck names Pseudomonas for contact lens keratitis."],
     ["Elderly patients, from Streptococcus pneumoniae",
      "Not the deck's flagged group or organism."],
     ["Immunosuppressed patients, from Candida",
      "Not what the deck highlights here."]],
   c=0, cite=c(14)),

 dict(topic="Keratitis", io=IO3, slot="complication",
   q="Which complications does the deck attach to keratitis?",
   opts=[
     ["Corneal stromal ulceration, perforation and endophthalmitis",
      "Correct — the progression the deck sets out, which is why it is an emergency."],
     ["Scleral melting and globe rupture",
      "Scleral melting belongs to scleritis."],
     ["Retinal tear and vitreous haemorrhage",
      "Those are posterior segment complications."],
     ["Optic disc cupping and peripheral field loss",
      "That is glaucomatous damage."]],
   c=0, cite=c(14)),

 dict(topic="Orbital cellulitis", io=IO3, slot="etiology",
   q="What anatomically defines orbital, as opposed to periorbital, cellulitis?",
   opts=[
     ["Infection has breached the orbital septum and lies posterior to the globe",
      "Correct — the septum is the dividing structure in the deck's table."],
     ["Infection is confined to the preseptal lids and periocular skin",
      "That is periorbital, or preseptal, cellulitis."],
     ["Infection has spread from the paranasal sinuses only",
      "Sinus spread is a route, not the anatomical definition."],
     ["Infection involves the lacrimal sac",
      "That is dacryocystitis."]],
   c=0, cite=c(16)),

 dict(topic="Orbital cellulitis", io=IO3, slot="manifestation",
   q="Which findings does the deck give for orbital cellulitis that periorbital cellulitis lacks?",
   opts=[
     ["Proptosis, decreased extraocular movement and a risk of optic nerve compression",
      "Correct — the deck's discriminating findings, all consequences of a post-septal collection."],
     ["Erythema and oedema of the lid, localised by the septum",
      "That is the periorbital picture."],
     ["Crusting of the lid margin with altered tear film",
      "That is blepharitis."],
     ["A yellowish nodule that does not cross the cornea",
      "That is a pinguecula."]],
   c=0, cite=c(16)),

 dict(topic="Periorbital cellulitis", io=IO3, slot="etiology",
   q="Why does periorbital cellulitis stay localised, and what does it spare?",
   opts=[
     ["The orbital septum acts as a firm barrier, so extraocular movement and vision are spared",
      "Correct — the septum is why the deck says this form spares movement and vision."],
     ["The conjunctiva acts as a barrier, so the cornea is spared",
      "The conjunctiva is not the barrier the deck names."],
     ["The tear film washes the infection away, so the globe is spared",
      "Not a mechanism the deck describes."],
     ["It is always viral, so it does not spread",
      "The deck gives bacterial causes for both forms."]],
   c=0, cite=c(16)),

 dict(topic="Blepharitis", io=IO3, slot="etiology",
   q="What is the mechanism by which meibomian gland obstruction produces blepharitis symptoms?",
   opts=[
     ["Altered tear film composition causes excessive tear evaporation, irritating the lid margin",
      "Correct — the deck's causal chain from gland to symptom."],
     ["Bacterial invasion of the tarsal plate causes an abscess",
      "That describes a hordeolum rather than blepharitis."],
     ["Aqueous tear production falls because the lacrimal gland is inflamed",
      "That is dacryoadenitis and aqueous-deficient dry eye."],
     ["The eyelashes turn inward and abrade the cornea",
      "That is trichiasis from entropion."]],
   c=0, cite=c(16)),

 dict(topic="Dry eye", io=IO3, slot="etiology",
   q="What are the two routes to keratoconjunctivitis sicca, and what is the common downstream step?",
   opts=[
     ["Aqueous tear deficiency or excessive evaporation, both raising tear osmolarity and damaging the corneal epithelium",
      "Correct — two upstream causes converging on a single mechanism."],
     ["Bacterial and viral infection, both causing purulent discharge",
      "Infection is not the deck's mechanism for dry eye."],
     ["Raised intraocular pressure and optic nerve compression",
      "That is glaucoma."],
     ["Ultraviolet exposure and fibrovascular proliferation",
      "That is pinguecula and pterygium."]],
   c=0, cite=c(16)),

 dict(topic="Herpes simplex keratitis", io=IO3, slot="test finding",
   q="What is the classical corneal finding in herpes simplex epithelial keratitis?",
   opts=[
     ["A dendritic ulcer with terminal bulbs on fluorescein staining",
      "Correct — the deck's classical description, terminal bulbs included."],
     ["A geographic ulcer with a hypopyon",
      "Not the classical simplex description in the deck."],
     ["A ring infiltrate in a contact lens wearer",
      "That pattern is associated with other organisms."],
     ["A wedge of fibrovascular tissue crossing the limbus",
      "That is a pterygium."]],
   c=0, cite=c(17)),

 dict(topic="Herpes zoster ophthalmicus", io=IO3, slot="etiology",
   q="Which nerve distribution does herpes zoster ophthalmicus follow?",
   opts=[
     ["The first division of the trigeminal nerve",
      "Correct — the ophthalmic division, and the rash respects the midline."],
     ["The facial nerve",
      "A common misstatement, but the deck is clear that this is trigeminal territory."],
     ["The second division of the trigeminal nerve",
      "The maxillary division does not carry the ophthalmic distribution."],
     ["The oculomotor nerve",
      "That is a motor nerve to the extraocular muscles."]],
   c=0, cite=c(17)),

 dict(topic="Herpes zoster ophthalmicus", io=IO3, slot="test finding",
   q="What is Hutchinson sign and why does it matter?",
   opts=[
     ["A vesicle on the tip of the nose, indicating nasociliary branch involvement and therefore high ocular risk",
      "Correct — the sign, its anatomical basis and its significance, as the deck gives them."],
     ["A vesicle on the eyelid margin, indicating meibomian gland involvement",
      "The sign is on the nose tip and reflects the nasociliary branch."],
     ["A dendritic corneal ulcer, indicating simplex rather than zoster",
      "That is the simplex finding."],
     ["Unilateral rash crossing the midline, indicating disseminated disease",
      "The zoster rash respects the midline; crossing it is not this sign."]],
   c=0, cite=c(17)),

 dict(topic="Pinguecula and pterygium", io=IO3, slot="etiology",
   q="What is the shared mechanism behind pinguecula and pterygium?",
   opts=[
     ["Submucosal fibrovascular conjunctival proliferation from chronic ultraviolet, wind and dust exposure",
      "Correct — the deck's shared mechanism, which is why it calls them surfer's eye."],
     ["Bacterial colonisation of the limbal conjunctiva",
      "Neither lesion is infective in the deck's account."],
     ["Deposition of cholesterol in the conjunctival stroma",
      "That describes xanthelasma, and it affects the lids."],
     ["Rupture of episcleral capillaries beneath the conjunctiva",
      "That is a subconjunctival haemorrhage."]],
   c=0, cite=c(17)),

 dict(topic="Pinguecula and pterygium", io=IO3, slot="differential",
   q="What single feature separates a pterygium from a pinguecula?",
   opts=[
     ["The pterygium encroaches onto the cornea; the pinguecula does not",
      "Correct — Webster put it as crossing the limbus, and called this section important."],
     ["The pterygium is yellow; the pinguecula is triangular",
      "The colour and shape descriptions are the wrong way round and are not the separator."],
     ["The pterygium is painful; the pinguecula is painless",
      "Pain is not the discriminator the deck gives."],
     ["The pterygium is bilateral; the pinguecula is unilateral",
      "Laterality is not the separator."]],
   c=0, cite=c(17)),

 dict(topic="Chalazion and hordeolum", io=IO3, slot="differential",
   q="What is the mechanism and character of a chalazion?",
   opts=[
     ["A chronic, non-tender, sterile granulomatous lipogranuloma of a blocked meibomian gland",
      "Correct — sterile and granulomatous is what separates it from an infection."],
     ["An acute, tender, focal abscess of a gland at the lid margin",
      "That is a hordeolum."],
     ["A cholesterol-filled plaque along the nasal eyelid",
      "That is xanthelasma."],
     ["Redundant lid skin with prolapse of orbital fat",
      "That is dermatochalasis."]],
   c=0, cite=c(17)),

 dict(topic="Chalazion and hordeolum", io=IO3, slot="etiology",
   q="Which glands are involved in an external as opposed to an internal hordeolum?",
   opts=[
     ["External involves the glands of Zeis or Moll; internal involves a meibomian gland",
      "Correct — the deck's gland-by-gland distinction."],
     ["External involves a meibomian gland; internal involves the glands of Zeis or Moll",
      "This reverses the deck's assignment."],
     ["Both involve the lacrimal gland",
      "The lacrimal gland is not involved in hordeolum."],
     ["Both involve the tarsal plate itself rather than any gland",
      "The tarsal plate holds the meibomian glands but is not itself the site."]],
   c=0, cite=c(17)),

 dict(topic="Eyelid anatomy", io=IO3, slot="etiology",
   q="Which glands produce the lipid layer of the tear film, and where do they sit?",
   opts=[
     ["The meibomian glands, modified sebaceous glands within the tarsal plates",
      "Correct — and the lipid layer is what prevents evaporation."],
     ["The glands of Zeis and Moll, associated with the eyelash follicles",
      "Those are sebaceous and modified sweat glands of the lash line."],
     ["The lacrimal gland, in the superotemporal orbit",
      "That produces the aqueous component."],
     ["The goblet cells of the palpebral conjunctiva",
      "Those produce mucin, not lipid."]],
   c=0, cite=c(13)),

 dict(topic="Eyelid anatomy", io=IO3, slot="etiology",
   q="What does the lipid layer of the tear film do?",
   opts=[
     ["It prevents evaporation", "Correct — the deck's stated function, which is why its loss causes dry eye."],
     ["It provides the bulk volume of the tears", "That is the aqueous component."],
     ["It anchors the tear film to the corneal epithelium", "That is the mucin layer's role."],
     ["It carries immunoglobulin to the ocular surface", "Not the function the deck assigns to lipid."]],
   c=0, cite=c(13)),

 dict(topic="Eyelid anatomy", io=IO3, slot="etiology",
   q="What is the fornix, and why does it matter mechanically?",
   opts=[
     ["A flexible junctional cul-de-sac that permits free rotation of the globe",
      "Correct — the deck's definition and its mechanical purpose."],
     ["The dense fibrous plate giving the eyelid its shape",
      "That is the tarsus."],
     ["The sphincteric muscle responsible for blinking",
      "That is orbicularis oculi."],
     ["The junction where the conjunctiva meets the cornea",
      "That is the limbus."]],
   c=0, cite=c(13)),

 dict(topic="Eyelid anatomy", io=IO3, slot="etiology",
   q="Which muscle closes the eyelids, and what type is it?",
   opts=[
     ["Orbicularis oculi, a sphincteric striated muscle",
      "Correct — responsible for blinking and forced closure."],
     ["Levator palpebrae superioris, a striated muscle",
      "That elevates the lid rather than closing it."],
     ["Müller muscle, a smooth muscle",
      "That contributes to lid elevation, not closure."],
     ["The ciliary muscle, a smooth muscle",
      "That governs accommodation inside the eye."]],
   c=0, cite=c(13)),

 dict(topic="Corneal injury", io=IO3, slot="differential",
   q="What anatomically separates a corneal abrasion from a corneal ulceration?",
   opts=[
     ["An abrasion is limited to the epithelium; an ulcer penetrates the epithelial basement membrane into the stroma",
      "Correct — the depth relative to the basement membrane is the dividing line."],
     ["An abrasion involves the stroma; an ulcer is limited to the epithelium",
      "This reverses the two."],
     ["An abrasion is infective; an ulcer is mechanical",
      "The deck describes the reverse pattern of causation."],
     ["An abrasion always scars; an ulcer heals cleanly",
      "The deck says an abrasion heals rapidly without scarring and an ulcer scars."]],
   c=0, cite=c(19)),

 dict(topic="Corneal injury", io=IO3, slot="etiology",
   q="What molecular mechanism causes tissue loss in a corneal ulcer?",
   opts=[
     ["Bacterial collagenases melt corneal tissue",
      "Correct — the deck names collagenase-driven melting as the mechanism of scarring."],
     ["Neutrophil elastase digests the epithelial basement membrane",
      "The deck names bacterial collagenases specifically."],
     ["Osmotic swelling from sorbitol accumulation",
      "That is the diabetic cataract mechanism."],
     ["Complement-mediated lysis of keratocytes",
      "Not the mechanism the deck gives."]],
   c=0, cite=c(19)),

 dict(topic="Corneal injury", io=IO3, slot="prognosis",
   q="Why does a corneal abrasion heal without scarring while an ulcer does not?",
   opts=[
     ["The abrasion has not breached the basement membrane, so the epithelium regenerates over intact scaffolding",
      "Correct — the deck ties the healing difference to the depth of the defect."],
     ["The abrasion is avascular and so cannot form scar tissue",
      "The whole cornea is avascular; that is not the difference."],
     ["The abrasion is always sterile and the ulcer always infected",
      "Infection contributes but the deck's distinction is anatomical depth."],
     ["The abrasion is treated sooner",
      "Timing is not the deck's explanation."]],
   c=0, cite=c(19)),

 dict(topic="Lacrimal disease", io=IO3, slot="differential",
   q="What separates dacryocystitis from dacryoadenitis anatomically?",
   opts=[
     ["Dacryocystitis is the lacrimal SAC at the medial canthus; dacryoadenitis is the lacrimal GLAND at the superotemporal orbital rim",
      "Correct — sac against gland, and medial against superotemporal."],
     ["Dacryocystitis is the gland and dacryoadenitis is the sac",
      "This reverses the two."],
     ["Both involve the lacrimal gland, differing only in chronicity",
      "They involve different structures."],
     ["Both involve the nasolacrimal duct, differing only in organism",
      "The duct is downstream of the sac and is not the distinction."]],
   c=0, cite=c(19)),

 dict(topic="Lacrimal disease", io=IO3, slot="manifestation",
   q="Which lid deformity does the deck associate with dacryoadenitis?",
   opts=[
     ["An S-shaped lid deformity", "Correct — the deck's characteristic sign for lacrimal gland inflammation."],
     ["An inward-turning lid margin", "That is entropion."],
     ["An outward-turning lid margin", "That is ectropion."],
     ["A drooping upper lid from levator weakness", "That is ptosis."]],
   c=0, cite=c(19)),

 dict(topic="Subconjunctival haemorrhage", io=IO3, slot="etiology",
   q="What is the mechanism of a subconjunctival haemorrhage?",
   opts=[
     ["Rupture of delicate episcleral or conjunctival capillaries, leaking blood beneath the conjunctiva",
      "Correct — the deck's vascular mechanism."],
     ["Leakage of aqueous humour into the subconjunctival space",
      "Aqueous does not leak there in this condition."],
     ["Fibrovascular proliferation from ultraviolet exposure",
      "That is pinguecula and pterygium."],
     ["Breakdown of the blood-retinal barrier",
      "That is a posterior segment mechanism."]],
   c=0, cite=c(19)),

 dict(topic="Subconjunctival haemorrhage", io=IO3, slot="risk factors",
   q="Which triggers does the deck list for subconjunctival haemorrhage?",
   opts=[
     ["Valsalva from coughing, vomiting or heavy lifting, minor trauma, hypertension, age-related vessel fragility and coagulopathy",
      "Correct — the deck's full trigger list."],
     ["Ultraviolet light, wind and dust exposure",
      "Those drive pinguecula and pterygium."],
     ["Contact lens wear and corneal abrasion",
      "Those relate to keratitis."],
     ["Chronic corticosteroid use and diabetes",
      "Those are cataract risks in this deck."]],
   c=0, cite=c(19)),

 dict(topic="Subconjunctival haemorrhage", io=IO3, slot="prognosis",
   q="What is the natural course of a subconjunctival haemorrhage?",
   opts=[
     ["Benign, resolving over one to two weeks with bruise-like colour changes",
      "Correct — the deck's stated course."],
     ["Progressive, threatening vision within days",
      "The deck calls it benign."],
     ["Permanent, leaving a fibrovascular scar",
      "It resolves."],
     ["Recurrent by definition, requiring long-term follow-up",
      "The deck does not describe it this way."]],
   c=0, cite=c(19)),

 dict(topic="Dermatochalasis", io=IO3, slot="etiology",
   q="What is dermatochalasis, and what is its functional consequence?",
   opts=[
     ["Redundant eyelid skin with prolapse of orbital fat, which can seriously limit the visual field",
      "Correct — the deck's definition and the reason it matters functionally."],
     ["Cholesterol-filled plaques around the lids associated with hyperlipidaemia",
      "That is xanthelasma."],
     ["Inward turning of the lid margin causing corneal abrasion",
      "That is entropion."],
     ["Chronic granulomatous blockage of a meibomian gland",
      "That is a chalazion."]],
   c=0, cite=c(18)),

 dict(topic="Xanthelasma", io=IO3, slot="etiology",
   q="What are xanthelasma lesions made of, and what are they associated with?",
   opts=[
     ["Abnormal lipid deposition around the lids, usually bilateral, associated with hyperlipidaemia",
      "Correct — the deck's composition, distribution and association."],
     ["Redundant skin with prolapsed orbital fat, associated with ageing",
      "That is dermatochalasis."],
     ["Sterile granuloma of a meibomian gland, associated with rosacea",
      "That is a chalazion."],
     ["Fibrovascular conjunctival tissue, associated with ultraviolet exposure",
      "That is pinguecula."]],
   c=0, cite=c(18)),
]
