# Clinical Pathophysiology I, Lecture 2 (Dermatology) — pool part A
# Objective a (integumentary anatomy) and objective b (primary skin lesions).
#
# SCOPE GUARD: this class is pathophysiology only. The same Dermatology material
# appears in Clinical Medicine and Surgery I Exam 1, taught in the same term.
# Every question here asks what is happening in the tissue and why. No first-line
# treatment, no drug of choice, no next step -- a question that would sit equally
# well in the CMS exam is pitched wrong for this one.
#
# Correct answer always written first; the partition script rotates.
SRC = "Pathophys Dermatology - Gopal 2026 SV.pptx"
def c(n): return f"{SRC}, Slide {n}"

IOA = "a — Anatomy of the integumentary system"
IOB = "b — Pathophysiology of primary skin lesions"

POOL_A = [
 dict(topic="Skin functions", io=IOA,
   q="Where does each step of vitamin D activation take place, beginning in the skin?",
   opts=[
     ["Cholecalciferol forms in the skin under ultraviolet B light, then is hydroxylated in the liver and then the kidneys to calcitriol",
      "Correct. The skin only starts the process; two further hydroxylation steps in separate organs are needed before the hormone is active."],
     ["Calcitriol is produced directly in the skin under ultraviolet B light and requires no further modification",
      "The skin produces cholecalciferol, which is inactive until hydroxylated twice elsewhere."],
     ["Cholecalciferol is produced in the liver, then hydroxylated in the skin and finally in the kidneys",
      "Production starts in the skin, not the liver: ultraviolet B light forms cholecalciferol, which the liver and then the kidneys hydroxylate."],
     ["Cholecalciferol is produced in the skin and hydroxylated entirely within the kidneys in a single step",
      "Two organs are involved in activation, the liver first and then the kidney."]],
   c=0, cite=c(3)),

 dict(topic="Skin functions", io=IOA,
   q="Which receptors carry the sensations of touch and pressure?",
   opts=[
     ["Meissner's corpuscles, Pacinian corpuscles and Merkel cells",
      "Correct. Meissner's serve fine discriminative touch and low-frequency vibration, Pacinian respond to deep pressure and vibration, and Merkel cells serve light touch."],
     ["Ruffini endings, Krause bulbs and free nerve endings only",
      "Free nerve endings sense touch, pain and temperature, but touch and pressure are carried by Meissner's corpuscles, Pacinian corpuscles and Merkel cells."],
     ["Golgi tendon organs and muscle spindles",
      "Golgi tendon organs and muscle spindles are not skin receptors; touch and pressure are carried by Meissner's corpuscles, Pacinian corpuscles and Merkel cells."],
     ["Langerhans cells and melanocytes",
      "Langerhans cells are immune sentinels and melanocytes make pigment; touch and pressure are carried by Meissner's corpuscles, Pacinian corpuscles and Merkel cells."]],
   c=0, cite=c(3)),

 dict(topic="Epidermis", io=IOA,
   q="Which statement correctly describes the cell population of the epidermis?",
   opts=[
     ["Keratinocytes (about 90 percent), melanocytes, Merkel cells and Langerhans cells",
      "Correct. The epidermis holds keratinocytes, melanocytes, Merkel cells and Langerhans cells, and keratinocytes, which produce keratin, make up about 90 percent of it."],
     ["Fibroblasts, macrophages, adipocytes and mast cells, with fibroblasts predominating",
      "Fibroblasts, macrophages, adipocytes and mast cells are cells of the dermis; the epidermis holds keratinocytes, melanocytes, Merkel cells and Langerhans cells."],
     ["Melanocytes, Merkel cells, fibroblasts and histiocytes, with melanocytes predominating",
      "Fibroblasts and histiocytes are dermal cells, and melanocytes are a minority; keratinocytes make up about 90 percent of the epidermis."],
     ["Keratinocytes and melanocytes only, in roughly equal proportion",
      "The epidermis has four cell types, adding Merkel cells and Langerhans cells, and keratinocytes far outnumber melanocytes at about 90 percent."]],
   c=0, cite=c(6)),

 dict(topic="Epidermis", io=IOA,
   q="Which statement correctly describes epidermal cell turnover?",
   opts=[
     ["Every 30 to 60 days, and turnover is more rapid in younger patients",
      "Correct. Epidermal cells turn over every 30 to 60 days, rising from the basement membrane zone to shed, and turnover is faster in younger patients."],
     ["Every 24 to 48 hours, with no age dependence",
      "Every 24 to 48 hours is far too fast; epidermal turnover takes 30 to 60 days and is more rapid in younger patients."],
     ["Every 6 to 12 months, more rapid in older patients",
      "Turnover takes 30 to 60 days, not 6 to 12 months, and it is more rapid in younger patients rather than older ones."],
     ["Turnover ceases after adolescence",
      "The epidermis keeps turning over, every 30 to 60 days, as cells rise from the basement membrane zone and eventually shed."]],
   c=0, cite=c(6)),

 dict(topic="Epidermis", io=IOA,
   q="Which layer of the epidermis is the site of cellular division?",
   opts=[
     ["The basal layer, or stratum basale, the deepest layer",
      "Correct. A single layer of rapidly dividing columnar keratinocytes, which also contains melanocytes and Merkel cells."],
     ["The stratum corneum, the outermost layer",
      "The stratum corneum is 20 to 30 layers of keratin and dead keratinocytes; cell division takes place in the deepest layer, the stratum basale."],
     ["The granular layer, or stratum granulosum",
      "The stratum granulosum holds 3 to 5 layers of diamond-shaped cells with keratohyalin granules; division occurs in the deepest layer, the stratum basale."],
     ["The stratum lucidum",
      "The stratum lucidum is 2 to 3 layers of flattened dead keratinocytes, which do not divide; cell division occurs in the stratum basale."]],
   c=0, cite=c(7)),

 dict(topic="Epidermis", io=IOA,
   q="What gives the spinous layer its alternative name of prickle cell layer?",
   opts=[
     ["Keratinocytes connected by intercellular connections called desmosomes, which form a spiny appearance",
      "Correct. The 8 to 10 keratinocyte layers of the stratum spinosum are joined by desmosomes, which give the spiny look behind the name prickle cell layer."],
     ["Keratohyalin granules that give the cells a rough outline",
      "Keratohyalin granules mark the stratum granulosum above; the spiny look comes from desmosomes connecting the keratinocytes of the spinous layer."],
     ["Melanin granules transferred from melanocytes",
      "Melanin transfer does not create the spiny appearance; desmosomes connecting 8 to 10 layers of keratinocytes form the prickle cell layer."],
     ["Dead flattened keratinocytes packed into scales",
      "Dead flattened keratinocytes packed into scales form the stratum corneum; the prickle cell appearance comes from desmosomes."]],
   c=0, cite=c(7)),

 dict(topic="Epidermis", io=IOA,
   q="Which layer forms the semi-impermeable barrier of the skin?",
   opts=[
     ["The stratum corneum, 20 to 30 layers of keratin and dead keratinocytes cemented together",
      "Correct. The stratum corneum, the outermost layer, packs 20 to 30 layers of keratin and dead keratinocytes into a semi-impermeable barrier."],
     ["The stratum basale, a single layer of dividing columnar keratinocytes",
      "The stratum basale is the deepest layer, where cells divide; the barrier is formed by the outermost layer, the stratum corneum."],
     ["The stratum granulosum, 3 to 5 layers of diamond-shaped cells",
      "The stratum granulosum holds keratohyalin granules but is not the barrier; the stratum corneum forms the semi-impermeable barrier."],
     ["The papillary dermis, a thin superficial connective tissue layer",
      "The papillary dermis is a connective tissue layer, not epidermis; the barrier is the stratum corneum of keratin and dead keratinocytes."]],
   c=0, cite=c(8)),

 dict(topic="Dermis", io=IOA,
   q="Which statement correctly describes the primary component of the dermis?",
   opts=[
     ["Collagen, produced by fibroblasts, providing tensile strength",
      "Correct. Collagen is the primary component of the dermis; fibroblasts produce it, and it provides the skin's tensile strength."],
     ["Keratin, produced by keratinocytes, providing an impermeable barrier",
      "Keratin is produced by keratinocytes in the epidermis; the primary dermal component is collagen, made by fibroblasts for tensile strength."],
     ["Elastin, produced by mast cells, providing tensile strength",
      "Elastin provides elastic recoil, not tensile strength, and mast cells do not make it; collagen from fibroblasts provides tensile strength."],
     ["Melanin, produced by melanocytes, providing ultraviolet protection",
      "Melanin is an epidermal pigment from melanocytes; collagen made by fibroblasts is the primary component of the dermis."]],
   c=0, cite=c(11)),

 dict(topic="Dermis", io=IOA,
   q="What are the two connective tissue layers of the dermis?",
   opts=[
     ["Papillary, the thin superficial layer, and reticular, the dense deeper layer",
      "Correct. The dermis consists of two connective tissue layers: the thin superficial papillary layer and the dense deeper reticular layer."],
     ["Basale and spinosum",
      "The stratum basale and stratum spinosum are epidermal layers; the dermis has a thin superficial papillary layer and a dense deeper reticular layer."],
     ["Corneum and lucidum",
      "The stratum corneum and stratum lucidum are outer epidermal layers; the dermis consists of the papillary and reticular connective tissue layers."],
     ["Papillary and subcutaneous",
      "The subcutaneous layer, or hypodermis, is the third layer of skin rather than dermis; the deeper dermal layer is the dense reticular layer."]],
   c=0, cite=c(11)),

 dict(topic="Dermis", io=IOA,
   q="Which dermal cell mediates immunoglobulin E-mediated inflammation?",
   opts=[
     ["The mast cell",
      "Correct, and its degranulation is the mechanism behind both the wheal and urticaria."],
     ["The fibroblast",
      "Fibroblasts produce the collagen that gives the dermis tensile strength; the mast cell is the dermal cell behind immunoglobulin E-mediated inflammation."],
     ["The melanocyte",
      "Melanocytes are pigment cells of the epidermal basal layer; the mast cell is the dermal cell that mediates immunoglobulin E-mediated inflammation."],
     ["The keratinocyte",
      "Keratinocytes make up about 90 percent of the epidermis and produce keratin; mast cells mediate immunoglobulin E-mediated inflammation in the dermis."]],
   c=0, cite=c(13)),

 dict(topic="Appendages", io=IOA,
   q="How do eccrine and apocrine sweat glands differ in secretion and function?",
   opts=[
     ["Eccrine secrete water and electrolytes for evaporative cooling; apocrine, mainly axillary and anogenital, secrete protein and lipids as scent glands",
      "Correct. Eccrine glands open onto the skin surface and cool the body by evaporation; body odor comes from bacterial degradation of apocrine sweat, not from the sweat itself."],
     ["Eccrine sit in the axilla and secrete lipids; apocrine open onto the surface and secrete water and electrolytes",
      "This swaps the two glands: eccrine glands open onto the skin surface for evaporative cooling, and apocrine glands sit in the axilla and anogenital areas."],
     ["Both secrete sebum, differing only in the body regions they occupy",
      "Neither sweat gland secretes sebum; eccrine glands secrete water and electrolytes, apocrine glands protein and fatty lipids, and sebaceous glands make sebum."],
     ["Eccrine secrete keratin and apocrine secrete melanin",
      "Neither gland secretes keratin or melanin; eccrine glands secrete water and electrolytes, and apocrine glands secrete protein and fatty lipids."]],
   c=0, cite=c(14)),

 dict(topic="Appendages", io=IOA,
   q="What is sebum primarily composed of?",
   opts=[
     ["Triglycerides, wax esters and squalene",
      "Correct, produced by the sebaceous glands associated with hair follicles to lubricate skin and hair."],
     ["Water, sodium and chloride",
      "Water, sodium and chloride make up eccrine sweat; sebum from sebaceous glands is mainly triglycerides, wax esters and squalene."],
     ["Keratin and keratohyalin",
      "Keratin comes from keratinocytes and keratohyalin fills the granular layer; sebum is mainly triglycerides, wax esters and squalene."],
     ["Collagen and elastin",
      "Collagen and elastin are dermal fibers; sebum is a lipid secretion of triglycerides, wax esters and squalene from sebaceous glands."]],
   c=0, cite=c(15)),

 dict(topic="Appendages", io=IOA,
   q="Which statement correctly describes androgen regulation of hair?",
   opts=[
     ["Terminal hair is androgen-regulated; vellus hair grows independently of androgens",
      "Correct. Thick terminal hair on the head, beard, axillae and pubic areas is androgen-regulated; fine vellus hair grows independently of androgens."],
     ["Vellus hair is androgen-regulated; terminal hair grows independently",
      "This swaps them: vellus hair, the fine short hair of most of the adult body, grows independently of androgens, and terminal hair is androgen-regulated."],
     ["Lanugo hair is androgen-regulated; terminal hair is not",
      "Lanugo is the fine hair of newborns, not the androgen-regulated type; terminal hair is the type that androgens regulate."],
     ["All three types are equally androgen-dependent",
      "The types differ: terminal hair of the head, beard, axillae and pubic areas is androgen-regulated, while vellus hair grows independently of androgens."]],
   c=0, cite=c(15)),

 dict(topic="Lesion categories", io=IOB,
   q="What distinguishes a primary from a secondary skin lesion?",
   opts=[
     ["A primary lesion is the direct result of the underlying disease and retains its original unmodified appearance; a secondary lesion has been modified over time",
      "Correct, and a secondary lesion may or may not still resemble the lesion it came from."],
     ["A primary lesion is palpable and a secondary lesion is flat",
      "Palpability separates papules, nodules and plaques from flat macules within the primary group; a secondary lesion is instead one modified over time."],
     ["A primary lesion is benign and a secondary lesion is malignant",
      "Neither category implies malignancy; a primary lesion is the direct result of the underlying disease, while a secondary one has been modified over time."],
     ["A primary lesion appears first in time and a secondary lesion appears elsewhere on the body",
      "Timing and body site do not define it; a secondary lesion is one modified over time, while a primary lesion is the direct result of the underlying disease."]],
   c=0, cite=c(17)),

 dict(topic="Macules", io=IOB,
   q="What separates a macule from a patch, and what do both share?",
   opts=[
     ["Size — a macule is up to 5 millimeters and a patch greater than 5 — and both are circumscribed, flat discolorations that are NOT palpable",
      "Correct. Impalpability is the defining feature of this pair."],
     ["Size — a macule is greater than 5 millimeters and a patch up to 5 — and both are palpable",
      "The sizes are reversed and both are impalpable."],
     ["Depth — a macule is epidermal and a patch is dermal — and both are elevated",
      "Neither is elevated; the distinction is size, not depth."],
     ["Color — a macule is hyperpigmented and a patch hypopigmented — and both are palpable",
      "Either can be hyper- or hypopigmented, and neither is palpable."]],
   c=0, cite=c(20)),

 dict(topic="Macules", io=IOB,
   q="How does the mechanism of a hypopigmented macule such as vitiligo differ from that of a hyperpigmented macule?",
   opts=[
     ["Loss of melanocytes, against increased melanin production in the basal layer of the epidermis",
      "Correct. Vitiligo reflects loss of melanocytes, while hyperpigmented macules such as ephelides, café au lait spots and Mongolian spots reflect increased basal melanin."],
     ["Increased melanin production, against loss of melanocytes",
      "This reverses them: hypopigmentation as in vitiligo is loss of melanocytes, and hyperpigmentation is increased melanin in the basal layer."],
     ["Capillary rupture with blood deposition in the dermis",
      "Capillary rupture depositing blood in the dermis produces petechiae and purpura; vitiligo reflects loss of melanocytes."],
     ["Dilatation and thinning of superficial dermal vessels",
      "Dilatation and thinning of superficial dermal vessels is telangiectasia; a hypopigmented macule reflects loss of melanocytes."]],
   c=0, cite=c(20)),

 dict(topic="Papules", io=IOB,
   q="What is the tissue basis of a papule?",
   opts=[
     ["Epidermal hyperplasia with hyperkeratosis, over dermal inflammation and dense collagen",
      "Correct. A papule is an elevated solid lesion under 5 millimeters, built from epidermal hyperplasia with hyperkeratosis over dermal inflammation, as in seborrheic keratosis."],
     ["Fluid containing inflammatory cells collecting within or beneath the epidermis",
      "Fluid with inflammatory cells within or beneath the epidermis forms a vesicle; a papule is solid, from hyperplasia with hyperkeratosis."],
     ["Separation of epidermis from dermis with fluid accumulation",
      "Epidermis separating from dermis with fluid accumulation forms a bulla; a papule is solid, from epidermal hyperplasia and dense dermal collagen."],
     ["Focal loss of the epidermis without penetration below the dermal-epidermal junction",
      "Focal epidermal loss above the junction is an erosion, a secondary lesion; a papule is an elevated solid lesion from epidermal hyperplasia."]],
   c=0, cite=c(22)),

 dict(topic="Papules", io=IOB,
   q="A nodule is greater than 5 millimeters. What tissue does it arise from?",
   opts=[
     ["Dermal-based tissue with dense collagen bundles, extending into subcutaneous tissue",
      "Correct. A nodule is an elevated, solid lesion over 5 millimeters: a dermal-based lesion of dense collagen bundles extending into subcutaneous tissue."],
     ["Superficial epidermis only, with no dermal involvement",
      "A nodule is not confined to the epidermis; it is a dermal-based lesion of dense collagen bundles that extends into subcutaneous tissue."],
     ["Fluid accumulating between epidermis and dermis",
      "Fluid collecting between a separated epidermis and dermis describes a bulla; a nodule is solid, built of dense dermal collagen bundles and subcutaneous tissue."],
     ["Dilated superficial capillaries without inflammatory infiltration",
      "Dilated superficial dermal capillaries without inflammatory infiltrate define telangiectasia; a nodule is a solid lesion of dense dermal collagen bundles."]],
   c=0, cite=c(22)),

 dict(topic="Papules", io=IOB,
   q="How does a plaque form, and what is seen in the tissue?",
   opts=[
     ["By confluence of papules, with marked epidermal thickening and dilated blood vessels in the dermis",
      "Correct. It is elevated, superficial and greater than 1 centimeter — plaque psoriasis is the example."],
     ["By separation of the epidermis from the dermis with fluid accumulation",
      "That is a bulla."],
     ["By loss of melanocytes across a broad area",
      "That produces a hypopigmented patch."],
     ["By long-term scratching thickening the epidermis",
      "That is lichenification, a secondary lesion."]],
   c=0, cite=c(22)),

 dict(topic="Vesicles", io=IOB,
   q="What distinguishes a vesicle from a bulla?",
   opts=[
     ["A vesicle is up to 5 millimeters, with fluid within or beneath the epidermis; a bulla is larger and separates epidermis from dermis",
      "Correct. A vesicle holds fluid containing inflammatory cells within or directly beneath the epidermis; a bulla, greater than 5 millimeters, involves separation of epidermis from dermis. The bulla represents a deeper plane of cleavage, not merely a bigger blister."],
     ["A vesicle is greater than 5 millimeters and a bulla up to 5, with identical mechanisms",
      "The sizes are reversed: a vesicle is up to 5 millimeters and a bulla is larger, and a bulla forms by separation of the epidermis from the dermis."],
     ["A vesicle is solid and a bulla is fluid-filled",
      "Both are fluid-filled lesions; a vesicle collects fluid within or beneath the epidermis, and a bulla forms where the epidermis separates from the dermis."],
     ["A vesicle contains purulent material and a bulla contains serous fluid",
      "Purulent material of leukocytes and debris defines a pustule; vesicle fluid contains inflammatory cells, and bulla fluid collects between epidermis and dermis."]],
   c=0, cite=c(25)),

 dict(topic="Vesicles", io=IOB,
   q="Which factors cause bullae?",
   opts=[
     ["Mechanical factors, infections, toxins, chemicals and autoimmunity",
      "Correct, with bullous impetigo as the bacterial example and bullous pemphigoid as the autoimmune one."],
     ["Increased melanin production and ultraviolet exposure only",
      "Increased melanin production causes hyperpigmented macules; bullae arise from mechanical, infectious, toxic, chemical or autoimmune injury."],
     ["Capillary rupture and thrombocytopenia",
      "Capillary rupture and thrombocytopenia cause petechiae and purpura; bullae arise from mechanical factors, infections, toxins, chemicals and autoimmunity."],
     ["Androgen stimulation of sebaceous glands",
      "Androgen stimulation is not a cause of blistering; bullae arise from mechanical factors, infections, toxins, chemical exposure and autoimmune reactions."]],
   c=0, cite=c(25)),

 dict(topic="Wheal", io=IOB,
   q="Trace the mechanism of a wheal from trigger to itch.",
   opts=[
     ["An immune trigger causes mast cells to release histamine; histamine induces vasodilation and vascular permeability so plasma leaks into the dermis, and it acts on cutaneous nerve endings to create pruritus",
      "Correct. One mediator produces both the swelling and the itch, which is why the lesion is transient."],
     ["Neutrophils release proteases that digest dermal collagen, producing a depression",
      "That is closer to ulceration than to a wheal."],
     ["Keratinocytes proliferate and thicken the epidermis, raising the surface",
      "That produces a papule or plaque, and it is not transient."],
     ["Capillaries rupture and blood accumulates in the dermis",
      "That produces petechiae or purpura, which are non-blanchable."]],
   c=0, cite=c(28)),

 dict(topic="Pustule", io=IOB,
   q="What does a pustule contain, and what organisms are typically involved?",
   opts=[
     ["Purulent material of leukocytes, cellular debris, serous fluid and possibly microorganisms, typically Gram-positive bacteria such as Staphylococcus aureus or Streptococcus pyogenes",
      "Correct — a pustule is a visible collection of neutrophils, usually responding to Gram-positive skin flora, though in rosacea the same appearance occurs without any organism."],
     ["Clear serous fluid only, always sterile",
      "Pustules contain purulent material, though they may sometimes be sterile."],
     ["Blood deposited in the dermis from ruptured capillaries",
      "That produces petechiae or purpura."],
     ["Keratin arising from a hair follicle",
      "That describes an epidermal inclusion cyst."]],
   c=0, cite=c(29)),

 dict(topic="Cyst and tumor", io=IOB,
   q="Which description of an epidermal inclusion cyst is accurate?",
   opts=[
     ["A hair follicle, and it contains keratin",
      "Correct. An epidermal inclusion cyst arises from a hair follicle and contains keratin, enclosed in a capsule within the dermis or subcutaneous layer."],
     ["A sweat gland, and it contains sodium and chloride",
      "Eccrine sweat carries sodium and chloride, but an epidermal inclusion cyst arises from a hair follicle and contains keratin."],
     ["A sebaceous gland, and it contains only squalene",
      "An epidermal inclusion cyst does not arise from a sebaceous gland; it arises from a hair follicle and is filled with keratin."],
     ["A blood vessel, and it contains clotted blood",
      "Clotted blood is not its content; an epidermal inclusion cyst arises from a hair follicle and contains keratin."]],
   c=0, cite=c(30)),

 dict(topic="Cyst and tumor", io=IOB,
   q="How are dermatofibroma and lipoma characterized in the tissue?",
   opts=[
     ["Dermatofibroma is a benign overgrowth of fibrous tissue in the dermis; lipoma is a benign enclosed capsule of adipocytes",
      "Correct. Dermatofibroma is a benign overgrowth of fibrous tissue in the dermis, and lipoma is a benign enclosed capsule of adipocytes."],
     ["Dermatofibroma is a benign capsule of adipocytes; lipoma is fibrous overgrowth",
      "This swaps the two: dermatofibroma is a benign overgrowth of fibrous tissue in the dermis, and lipoma is a benign enclosed capsule of adipocytes."],
     ["Both are malignant proliferations of keratinocytes",
      "Both are benign, and neither is keratinocyte-derived: dermatofibroma is fibrous tissue in the dermis and lipoma is encapsulated adipocytes."],
     ["Dermatofibroma is keratin-filled and lipoma is fluid-filled",
      "Keratin filling describes an epidermal inclusion cyst from a hair follicle; dermatofibroma is fibrous tissue and lipoma is a capsule of adipocytes."]],
   c=0, cite=c(30)),
]
