# Clinical Pathophysiology I, Lecture 2 (Dermatology) — pool part C
# Objective d: molecular mechanisms of common dermatological conditions.
#
# This is the section where the Clin Path / CMS line matters most, because the
# same diseases are taught in both. Everything here asks about the mechanism --
# which pathway, which cell, which mediator. Nothing asks how to treat it.
SRC = "Pathophys Dermatology - Gopal 2026 SV.pptx"
def c(n): return f"{SRC}, Slide {n}"

IOD = "d — Molecular mechanisms of common dermatological conditions"

POOL_C = [
 dict(topic="Vascular lesions", io=IOD,
   q="What causes petechiae, and what size defines them?",
   opts=[
     ["Minor bleeding into the dermis from capillary rupture, infection, thrombocytopenia or vasculitis, 1 to 2 millimetres or less",
      "Correct, and they are non-blanchable because the blood sits outside the vessel rather than within it."],
     ["Permanent dilatation of superficial dermal vessels, 1 to 2 millimetres",
      "That is telangiectasia, which blanches and involves no extravasated blood."],
     ["Increased melanin production in the basal layer, up to 5 millimetres",
      "That produces a hyperpigmented macule."],
     ["Mast cell histamine release with plasma leakage, up to 5 millimetres",
      "That produces a wheal, which is transient and blanchable."]],
   c=0, cite=c(42)),

 dict(topic="Vascular lesions", io=IOD,
   q="How do petechiae, purpura and ecchymoses differ?",
   opts=[
     ["By size — petechiae 1 to 2 millimetres or less, purpura 3 to 10 millimetres, ecchymoses greater than 10 millimetres — with similar underlying pathology",
      "Correct. It is a single process of bleeding into the dermis described at three scales."],
     ["By mechanism — petechiae from capillary rupture, purpura from vessel dilatation, ecchymoses from melanin deposition",
      "The pathology is described as similar across all three."],
     ["By depth — petechiae epidermal, purpura dermal, ecchymoses subcutaneous",
      "All involve blood in the dermis; the distinction given is size."],
     ["By blanchability — petechiae blanch, purpura and ecchymoses do not",
      "All three are non-blanchable."]],
   c=0, cite=c(42)),

 dict(topic="Vascular lesions", io=IOD,
   q="Henoch-Schonlein purpura involves which systems, and which patients?",
   opts=[
     ["Skin, joints, kidneys and intestines, commonly in children aged 3 to 10 years",
      "Correct — an immunoglobulin A vasculitis, which is why it is not confined to the skin."],
     ["Skin and lungs only, commonly in older adults",
      "Neither the organs nor the age group match."],
     ["Skin and liver, commonly in neonates",
      "Those organs and that age group are not described."],
     ["Skin alone, with no systemic involvement, at any age",
      "The whole point of naming it is that it is systemic."]],
   c=0, cite=c(42)),

 dict(topic="Vascular lesions", io=IOD,
   q="What defines telangiectasia at the tissue level?",
   opts=[
     ["Permanent dilatation and thinning of the endothelium of capillaries, venules and arterioles in the superficial dermis, with NO inflammatory cell infiltration",
      "Correct. The absence of inflammatory infiltrate is the discriminating feature."],
     ["Capillary rupture with blood deposited into the dermis",
      "That produces petechiae and purpura."],
     ["Dense inflammatory infiltration around dilated vessels",
      "The lecture states specifically that there is no inflammatory infiltration."],
     ["Proliferation of new vessels driven by vascular endothelial growth factor",
      "That mechanism is described for nail clubbing."]],
   c=0, cite=c(44)),

 dict(topic="Urticaria", io=IOD,
   q="What is the mechanism of urticaria?",
   opts=[
     ["Mast cell degranulation releasing histamine, producing wheals",
      "Correct, and it may be acute or chronic with a wide range of triggers."],
     ["T cell-mediated delayed hypersensitivity 48 to 72 hours after exposure",
      "That is allergic contact dermatitis."],
     ["Dysplastic keratinocyte proliferation from ultraviolet damage",
      "That is actinic keratosis."],
     ["Capillary rupture with extravasation of blood",
      "That produces petechiae and purpura."]],
   c=0, cite=c(46)),

 dict(topic="Contact dermatitis", io=IOD,
   q="What are the two phases of allergic contact dermatitis?",
   opts=[
     ["Sensitization, in which Langerhans cells present haptens to T cells to create specialised memory; and elicitation, in which re-exposure to the same hapten promotes T cell migration and cutaneous inflammation",
      "Correct — a delayed hypersensitivity reaction occurring 48 to 72 hours after exposure. Nickel and poison ivy are the examples."],
     ["Sensitization by mast cell degranulation, then elicitation by histamine release",
      "That is the immunoglobulin E pathway of urticaria, not the T cell pathway here."],
     ["Irritation, then hyperkeratosis of the stratum corneum",
      "That describes irritant contact dermatitis and lichenification respectively."],
     ["Radial growth, then vertical growth",
      "Those are the growth phases of melanoma."]],
   c=0, cite=c(49)),

 dict(topic="Contact dermatitis", io=IOD,
   q="What is the key mechanistic difference between irritant and allergic contact dermatitis?",
   opts=[
     ["Irritant contact dermatitis is caused by direct cutaneous interaction with a chemical, biologic or physical agent and does NOT require prior exposure; allergic requires prior sensitization",
      "Correct, and the lecture notes the two can be clinically difficult to tell apart, which is why the exposure history matters."],
     ["Irritant requires prior sensitization and allergic does not",
      "This reverses the two."],
     ["Irritant is immunoglobulin E-mediated and allergic is T cell-mediated",
      "Allergic contact dermatitis is T cell-mediated; irritant is not an immune memory process at all."],
     ["Irritant affects only the dermis and allergic only the epidermis",
      "Neither is defined by layer."]],
   c=0, cite=c(51)),

 dict(topic="Eczema", io=IOD,
   q="Which protein deficiency contributes to atopic dermatitis, and what does it reflect?",
   opts=[
     ["Insufficient filaggrin, reflecting a compromised epidermal barrier",
      "Correct, alongside an overactive immune system and genetic, environmental and psychogenic factors."],
     ["Insufficient collagen, reflecting fibroblast failure",
      "Collagen loss relates to atrophy and ulceration rather than eczema."],
     ["Insufficient elastin, reflecting loss of recoil",
      "Elastin degradation is part of atrophy."],
     ["Insufficient keratohyalin, reflecting loss of the granular layer",
      "Loss of the stratum granulosum is described for psoriasis."]],
   c=0, cite=c(52)),

 dict(topic="Eczema", io=IOD,
   q="Eczematous dermatitis results from which type of inflammatory reaction?",
   opts=[
     ["T cell-mediated",
      "Correct — a chronic condition with frequent or infrequent flares, known as the itch that rashes."],
     ["Immunoglobulin E-mediated mast cell degranulation alone",
      "That is the urticaria mechanism."],
     ["Neutrophil-driven suppurative inflammation",
      "That would produce pustules."],
     ["Complement-mediated vessel destruction",
      "That describes a vasculitis."]],
   c=0, cite=c(52)),

 dict(topic="Neurodermatitis", io=IOD,
   q="What is the suspected mechanism of neurodermatitis, and what does the cycle produce?",
   opts=[
     ["Hypersensitivity of nerves is suspected though the exact cause is unknown; repeated itching and scratching produces thick, rough, leathery, scaly plaques",
      "Correct, and it can begin during extreme stress, anxiety, emotional trauma or depression."],
     ["Autoimmune T cell infiltration producing silvery scale",
      "That is psoriasis."],
     ["Human papillomavirus proliferation of the epidermis",
      "That is verrucae vulgaris."],
     ["Dysplastic keratinocyte change from ultraviolet damage",
      "That is actinic keratosis."]],
   c=0, cite=c(53)),

 dict(topic="Seborrheic dermatitis", io=IOD,
   q="Which factors contribute to seborrhoeic dermatitis, and where does it occur?",
   opts=[
     ["Cutaneous microbiome dysbiosis, altered immune response and epidermal barrier dysfunction, affecting regions rich in sebaceous glands — scalp, face and upper trunk",
      "Correct, and the lecture is explicit that the cause is incompletely understood. Dandruff is the non-inflammatory form."],
     ["A single fungal pathogen acting alone, affecting the palms and soles",
      "The cause is described as multifactorial and incompletely understood, and the distribution follows sebaceous glands."],
     ["Autoimmune T cell activation, affecting the elbows and knees",
      "That distribution and mechanism belong to psoriasis."],
     ["Ultraviolet damage, affecting sun-exposed skin",
      "That is actinic keratosis."]],
   c=0, cite=c(55)),

 dict(topic="Seborrheic keratosis", io=IOD,
   q="What is a seborrhoeic keratosis at the cellular level, and what mutation is implicated?",
   opts=[
     ["A benign proliferation of immature keratinocytes, possibly from activating mutations in the tyrosine kinase receptor fibroblast growth factor receptor-3",
      "Correct, and the lecture notes the exact mechanism remains unknown. It is the most common skin growth in older adults."],
     ["A malignant proliferation of basal keratinocytes driven by the Hedgehog pathway",
      "That is basal cell carcinoma."],
     ["A dysplastic keratinocyte proliferation driven by cumulative ultraviolet exposure",
      "That is actinic keratosis."],
     ["A benign overgrowth of fibrous tissue in the dermis",
      "That is dermatofibroma."]],
   c=0, cite=c(58)),

 dict(topic="Actinic keratosis", io=IOD,
   q="What is the pathophysiology of actinic keratosis, and what does it carry a higher risk of?",
   opts=[
     ["Damage from excessive cumulative ultraviolet exposure leading to intraepidermal proliferation of dysplastic keratinocytes, carrying higher risk for squamous cell carcinoma",
      "Correct — it is described as the most common precancer, which is exactly why the dysplasia matters."],
     ["Benign proliferation of immature keratinocytes, carrying higher risk for basal cell carcinoma",
      "Benign immature keratinocyte proliferation describes seborrhoeic keratosis."],
     ["Human papillomavirus infection of basal cells, carrying higher risk for melanoma",
      "That is verrucae vulgaris, and it does not lead to melanoma."],
     ["Autoimmune T cell infiltration, carrying higher risk for lymphoma",
      "No such mechanism is described here."]],
   c=0, cite=c(60)),

 dict(topic="Psoriasis", io=IOD,
   q="Which cells drive psoriasis, and which cytokines does the lecture name?",
   opts=[
     ["Active T cells infiltrating the epidermis stimulate keratinocyte proliferation and excessive cytokine production, particularly tumour necrosis factor alpha, interferon gamma and interleukin-12",
      "Correct. It is a chronic autoimmune inflammatory dermatosis, and skin cells multiply up to ten times faster than normal."],
     ["Mast cells release histamine which drives keratinocyte proliferation",
      "That is the urticaria pathway and does not produce psoriasis."],
     ["Langerhans cells present haptens to T cells producing delayed hypersensitivity",
      "That is allergic contact dermatitis."],
     ["Melanocytes proliferate at the dermal-epidermal junction",
      "That is the origin of melanoma."]],
   c=0, cite=c(62)),

 dict(topic="Psoriasis", io=IOD,
   q="Which structural epidermal changes occur in psoriasis?",
   opts=[
     ["Epidermal hyperplasia, loss of the stratum granulosum, and failure of epidermal cells to secrete lipids producing xeroderma",
      "Correct. Losing the granular layer is what leaves the characteristic scale."],
     ["Thinning of the epidermis with slowed keratinocyte division",
      "That is atrophy, the opposite direction of change."],
     ["Separation of epidermis from dermis with fluid accumulation",
      "That is a bulla."],
     ["Loss of melanocytes from the basal layer",
      "That produces vitiligo."]],
   c=0, cite=c(62)),

 dict(topic="Verrucae", io=IOD,
   q="How does human papillomavirus produce a common wart?",
   opts=[
     ["It invades epidermal basal cells through microabrasions, leading to proliferation of the epidermis",
      "Correct, and clinical variants of warts are often associated with distinct viral subtypes."],
     ["It infects melanocytes at the dermal-epidermal junction",
      "That is where melanoma arises, and it is not viral."],
     ["It triggers mast cell degranulation in the dermis",
      "That is the urticaria mechanism."],
     ["It digests keratin using keratinases and proteases",
      "That is how dermatophytes behave."]],
   c=0, cite=c(64)),

 dict(topic="Dermatophytes", io=IOD,
   q="How do dermatophytes obtain nutrition, and in which layer do they typically live?",
   opts=[
     ["Spores secrete keratinases and proteases to metabolise and digest keratin in skin, hair and nails, typically within the stratum corneum",
      "Correct — Trichophyton, Microsporum and Epidermophyton are the three most common, and the annular patch with central clearing follows from this."],
     ["They invade basal cells through microabrasions and drive epidermal proliferation",
      "That is human papillomavirus."],
     ["They release histamine from mast cells producing wheals",
      "That is urticaria."],
     ["They proliferate within the dermis, digesting collagen",
      "The stated location is the stratum corneum, and the substrate is keratin."]],
   c=0, cite=c(65)),

 dict(topic="Dermatophytes", io=IOD,
   q="Which tinea subtype affects the nails, and what is its other name?",
   opts=[
     ["Tinea unguium, also called onychomycosis",
      "Correct. Corporis is trunk and limbs, pedis foot, cruris groin, capitis head, facialis face, manuum hand, barbae beard."],
     ["Tinea capitis, also called onychomycosis",
      "Tinea capitis affects the head."],
     ["Tinea manuum, affecting the nails of the hand",
      "Tinea manuum affects the hand rather than the nails specifically."],
     ["Tinea barbae, affecting nails and beard",
      "Tinea barbae affects the beard area."]],
   c=0, cite=c(65)),

 dict(topic="Nails", io=IOD,
   q="What produces leukonychia, and what else can cause it?",
   opts=[
     ["Temporary incomplete keratinization at the nail bed, usually harmless nail bed damage but also seen with heavy metal poisoning",
      "Correct — white streaks or spots, also called Mee's lines."],
     ["A halt of keratin production, associated with illness and malnourishment",
      "That is Beau's lines, which are transverse grooves."],
     ["Overgrowth of connective tissue in the nail bed",
      "That is Terry's nails."],
     ["Increased capillary density with vascular endothelial growth factor release",
      "That is clubbing."]],
   c=0, cite=c(72)),

 dict(topic="Nails", io=IOD,
   q="What is the suspected mechanism of koilonychia?",
   opts=[
     ["Impaired keratin synthesis associated with deficiency anaemia, weakening the nail plate into raised ridges that are thin and concave",
      "Correct, and the lecture notes the exact pathophysiology is unknown."],
     ["A halt of keratin production producing transverse grooves",
      "That is Beau's lines."],
     ["Overgrowth of connective tissue producing an opaque nail",
      "That is Terry's nails."],
     ["Incomplete keratinization producing white spots",
      "That is leukonychia."]],
   c=0, cite=c(72)),

 dict(topic="Nails", io=IOD,
   q="What causes Beau's lines, and what are they associated with?",
   opts=[
     ["A halt of keratin production producing horizontal or transverse grooves, associated with illness, stress, injury to the nail and malnourishment",
      "Correct — the groove marks the period during which the nail stopped being made."],
     ["Overgrowth of connective tissue in the nail bed, associated with liver disease and diabetes",
      "That is Terry's nails."],
     ["Increased capillary density, associated with lung disease",
      "That is clubbing."],
     ["Impaired keratin synthesis, associated with deficiency anaemia",
      "That is koilonychia."]],
   c=0, cite=c(73)),

 dict(topic="Nails", io=IOD,
   q="What is the main pathologic finding in nail clubbing, and what mediates it?",
   opts=[
     ["Increased capillary density, with increased release of vascular endothelial growth factor",
      "Correct, and it is associated with lung, cardiovascular, liver and inflammatory bowel disease."],
     ["Overgrowth of connective tissue in the nail bed",
      "That is Terry's nails."],
     ["A halt of keratin production at the matrix",
      "That is Beau's lines."],
     ["Incomplete keratinization at the nail bed",
      "That is leukonychia."]],
   c=0, cite=c(74)),

 dict(topic="Nails", io=IOD,
   q="What produces Terry's nails, and what conditions is it associated with?",
   opts=[
     ["Overgrowth of connective tissue in the nail bed, associated with aging, liver disease, congestive heart failure or diabetes",
      "Correct — the nail is opaque except for a dark band at the tip."],
     ["Increased capillary density with vascular endothelial growth factor release",
      "That is clubbing."],
     ["Impaired keratin synthesis with deficiency anaemia",
      "That is koilonychia."],
     ["Temporary incomplete keratinization at the nail bed",
      "That is leukonychia."]],
   c=0, cite=c(73)),

 dict(topic="Basal cell carcinoma", io=IOD,
   q="Which signalling pathway does basal cell carcinoma overactivate, and in which cells?",
   opts=[
     ["The Hedgehog signalling pathway, following ultraviolet-induced mutation of basal keratinocytes in the epidermis",
      "Correct. It is the most common skin cancer and the most common malignancy in humans, slow growing and rarely metastasising."],
     ["The tp53 tumour suppressor pathway, in differentiated keratinocytes",
      "That is squamous cell carcinoma."],
     ["Fibroblast growth factor receptor-3, in immature keratinocytes",
      "That is implicated in seborrhoeic keratosis, which is benign."],
     ["Uninhibited melanocyte growth at the dermal-epidermal junction",
      "That is melanoma."]],
   c=0, cite=c(76)),

 dict(topic="Squamous cell carcinoma", io=IOD,
   q="Which gene mutation is named for squamous cell carcinoma, and which histological features are pathognomonic?",
   opts=[
     ["Mutation in the tp53 tumour suppressor gene, with keratin pearls and epithelial pearls as pathognomonic features",
      "Correct. It derives from keratinocytes, and immunosuppression is a notable risk factor."],
     ["Overactivation of the Hedgehog pathway, with pearly papules and telangiectasias",
      "Those describe basal cell carcinoma."],
     ["Activating mutation of fibroblast growth factor receptor-3, with a stuck-on waxy appearance",
      "That is seborrhoeic keratosis, which is benign."],
     ["Autosomal dominant inheritance with variable penetrance and radial growth",
      "Those features are described for melanoma."]],
   c=0, cite=c(77)),

 dict(topic="Melanoma", io=IOD,
   q="Where do melanocytes normally sit, and what drives their malignant transformation?",
   opts=[
     ["At the dermal-epidermal junction, with ultraviolet light and oxidative stress damaging melanocyte DNA and leading to uninhibited growth",
      "Correct, and the risk is inherited as an autosomal dominant trait with variable penetrance."],
     ["Within the stratum corneum, transformed by keratinase digestion",
      "That describes dermatophyte behaviour, not melanocyte biology."],
     ["In the reticular dermis, transformed by fibroblast dysregulation",
      "Fibroblast dysregulation is the keloid mechanism."],
     ["In the basal layer, transformed by Hedgehog pathway activation",
      "Hedgehog activation is the basal cell carcinoma mechanism."]],
   c=0, cite=c(80)),

 dict(topic="Melanoma", io=IOD,
   q="What are the growth phases of melanoma, in order?",
   opts=[
     ["Radial growth within the epidermis, then vertical growth penetrating the dermis, then increasing tumour thickness, then metastatic invasion of lymphatics and blood vessels",
      "Correct. The shift from radial to vertical is the point at which depth begins to matter."],
     ["Vertical growth first, then radial spread within the epidermis",
      "This reverses the first two phases."],
     ["Inflammatory, proliferative, then remodelling",
      "Those are the phases of wound healing."],
     ["Sensitization then elicitation",
      "Those are the phases of allergic contact dermatitis."]],
   c=0, cite=c(80)),

 dict(topic="Melanoma", io=IOD,
   q="How is melanoma risk inherited, according to the lecture?",
   opts=[
     ["As an autosomal dominant trait with variable penetrance",
      "Correct, though ultraviolet light and oxidative stress remain the primary driving factor."],
     ["As an autosomal recessive trait with complete penetrance",
      "Neither the pattern nor the penetrance matches."],
     ["As an X-linked trait",
      "No such inheritance is described."],
     ["It is entirely environmental with no inherited component",
      "An inherited component is described explicitly."]],
   c=0, cite=c(80)),

 dict(topic="Skin cancers", io=IOD,
   q="Which skin cancer is described as the most common malignancy in humans, and how does it behave?",
   opts=[
     ["Basal cell carcinoma, slow growing and rarely metastasising, typically on the head and neck",
      "Correct. Squamous cell carcinoma is the second most common."],
     ["Squamous cell carcinoma, rapidly metastasising",
      "Squamous cell carcinoma is second most common."],
     ["Melanoma, slow growing and rarely metastasising",
      "Melanoma progresses through radial to vertical growth and can metastasise."],
     ["Actinic keratosis, which is the most common malignancy",
      "Actinic keratosis is a precancer rather than a malignancy."]],
   c=0, cite=c(76)),

 dict(topic="Contact dermatitis", io=IOD,
   q="A patient reacts to a nickel earring 48 to 72 hours after wearing it. Which mechanism does the delay reflect?",
   opts=[
     ["Delayed hypersensitivity requiring T cell migration after re-exposure to a hapten previously presented by Langerhans cells",
      "Correct. The delay is the time the cellular response takes, which is what distinguishes it from an immediate mast cell reaction."],
     ["Immediate immunoglobulin E-mediated mast cell degranulation",
      "That reaction occurs within minutes and produces wheals."],
     ["Direct chemical injury requiring no prior exposure",
      "That is irritant contact dermatitis, which does not require sensitization."],
     ["Viral proliferation within basal keratinocytes",
      "That is verrucae vulgaris."]],
   c=0, cite=c(49)),

 dict(topic="Psoriasis", io=IOD,
   q="Why does psoriatic skin become dry, in the lecture's account?",
   opts=[
     ["Epidermal cells fail to secrete lipids, producing xeroderma",
      "Correct — the dryness follows from a secretory failure rather than from water loss alone."],
     ["Eccrine sweat glands are destroyed by inflammation",
      "Sweat gland destruction is not described in psoriasis."],
     ["The stratum corneum is lost entirely",
      "The granular layer is lost; the scale that remains is stratum corneum."],
     ["Sebaceous glands overproduce sebum, which dries the surface",
      "Excess sebum relates to seborrhoeic dermatitis, and it does not dry the skin."]],
   c=0, cite=c(62)),
]
