# -*- coding: utf-8 -*-
# Interpretation of Medical Literature, Session 7 -- Risk and Ratios. Risk factors
# and how risk is recognized and used, cohort studies (concurrent and
# historical), absolute, attributable and relative risk, confounding and how it
# is controlled, effect modification, case-control studies, and the odds ratio.
#
# NUMBERS ARE FAIR HERE. Like the diagnostic tests session, this session works
# its measures through 2x2 tables. So arithmetic questions are fair, and they are
# written the way the session writes them -- the counts are supplied and the
# question asks what follows. Every figure in a calculation question is FRESH
# (none is taken from the worked examples) and was recomputed in Python before
# being written down.
#
# KEYS ARE WRITTEN SHORT ON PURPOSE -- detail lives in the explanation.
#
# Correct answer is ALWAYS written first (c=0); the partition script rotates.
SRC = "7 PAJ5512 Risk MBF 2026sc.pptx"
def c(n):  return f"{SRC}, Slide {n}"

IO1 = "Describe the importance of risk and risk factors in studies of disease"
IO2 = "Interpret relative risks"
IO3 = "Discuss methods of predicting risk"
IO4 = "Describe cohort studies and the advantages and limitations of this type of study design in medical research"
IO5 = "Discuss methods of comparing risk"
IO6 = "Explain confounding variables and methods for controlling confounding"
IO7 = "Describe effect modification"
IO8 = "Describe case control studies and the advantages and limitations of this type of study design in medical research"
IO9 = "Interpret relative risks and odds ratios"

POOL = [

# ---------------------------------------------------------------- IO 1
{"topic": "Risk factors", "io": IO1, "slot": "definition",
 "q": "What is a risk factor?",
 "opts": [
  ["A factor tied to a higher chance of later disease",
   "Correct, because it raises the probability of developing the disease later rather than making it certain, which is why risk factors describe groups and not a guaranteed outcome for one person."],
  ["A factor that guarantees later disease",
   "A risk factor increases the probability of developing the disease later; it does not make the disease certain, and many exposed people never develop it."],
  ["A factor that appears only after disease begins",
   "A risk factor is defined by raising the probability of developing the disease LATER, so it comes before the disease rather than after it."],
  ["A treatment that lowers the chance of disease",
   "A treatment that lowers the chance of disease is a protective intervention, whereas a risk factor is associated with an INCREASE in the probability of disease."]],
 "c": 0, "cite": c(3)},

{"topic": "Risk factors", "io": IO1, "slot": "principle",
 "q": "Which situation makes a risk easiest to recognize?",
 "opts": [
  ["A large risk with rapid effects",
   "Correct, because a big effect that appears soon after exposure is hard to miss. Long latency, low incidence and many already-known risk factors each make a risk harder to spot."],
  ["A small risk with a long latency",
   "A long latency between exposure and disease can obscure the result, and a small risk needs a larger affected population before a difference shows."],
  ["A rare disease with delayed onset",
   "Low disease incidence makes a risk harder to recognize, and delayed onset adds a long latency; a rare disease needs a very large cohort to show a difference."],
  ["A common disease with many known risk factors",
   "When a common disease already has known risk factors it is difficult to distinguish new ones, so recognition is harder rather than easier."]],
 "c": 0, "cite": c(4)},

{"topic": "Risk factors", "io": IO1, "slot": "principle",
 "q": "How can a long latency between exposure and disease affect the results of a study?",
 "opts": [
  ["It can obscure the association",
   "Correct, because the disease appears long after the exposure, so the two can look unrelated unless people are followed for a sufficient period of time."],
  ["It makes the association easier to see",
   "A long latency does the opposite: with a long gap between exposure and disease the result can be obscured, whereas a large risk with rapid effects is easy to recognize."],
  ["It strengthens the association",
   "Latency does not strengthen an association; it hides one, because the disease shows up long after the exposure took place."],
  ["It has no effect on the results",
   "Latency does matter: a long gap between exposure and disease can obscure results, which is why follow-up must last long enough to observe the outcome."]],
 "c": 0, "cite": c(4)},

{"topic": "Risk factors", "io": IO1, "slot": "principle",
 "q": "What is needed to detect a difference between exposed and unexposed groups when the risk is small?",
 "opts": [
  ["A larger affected population",
   "Correct, because a small risk produces few extra cases, so many more people must be affected before exposed and unexposed groups can be told apart."],
  ["A shorter follow-up period",
   "Shortening follow-up would leave even fewer cases to compare; a small risk calls for a larger affected population instead."],
  ["Fewer unexposed persons",
   "The comparison needs the unexposed group; with a small risk, a larger population must be affected to detect a difference."],
  ["A single exposed patient",
   "One patient cannot show a difference between groups; detecting a small risk needs a larger population."]],
 "c": 0, "cite": c(5)},

{"topic": "Risk factors", "io": IO1, "slot": "principle",
 "q": "How can a frequent exposure that causes disease go unnoticed?",
 "opts": [
  ["No exposed versus unexposed comparison",
   "Correct, because when most people are exposed the disease may seem ordinary; comparing exposed persons with unexposed persons is what reveals the risk."],
  ["The exposure was measured too precisely",
   "Precise measurement is not the barrier; a frequent exposure is obscured when exposed persons are never compared with unexposed persons."],
  ["The disease appeared too quickly",
   "A large risk with rapid effects is easy to recognize; the trouble with a frequent exposure is the missing comparison with unexposed persons."],
  ["The unexposed group was too large",
   "The size of the unexposed group is not the problem; the risk is obscured when there is no unexposed comparison group at all."]],
 "c": 0, "cite": c(4)},

{"topic": "Uses of risk", "io": IO1, "slot": "application",
 "q": "A clinician advises a patient to stop smoking to lower the chance of lung cancer. Which use of risk information is this?",
 "opts": [
  ["Prevention",
   "Correct, because removing a risk factor lowers the probability of developing the disease, as with controlling hypertension to prevent heart failure or avoiding second-hand smoke."],
  ["Prediction",
   "Prediction estimates the probability of a future event from data on groups; advising removal of the factor goes further and aims to lower that probability."],
  ["Diagnosis",
   "Diagnosis concerns whether disease is already present, and the best predictor in an individual is early clinical disease, not a risk factor."],
  ["Cause",
   "Cause concerns whether a risk factor actually produces the disease, and a factor can predict disease without causing it; advice to remove a factor is prevention."]],
 "c": 0, "cite": c(7)},

{"topic": "Uses of risk", "io": IO1, "slot": "principle",
 "q": "A factor is found to predict a disease well. What does that show about causation?",
 "opts": [
  ["It may only be a disease marker",
   "Correct: risk factors may predict disease without being a cause, which is the case for disease markers."],
  ["It proves the factor causes the disease",
   "Prediction is not proof of causation; a risk factor may predict disease without being its cause, as with a disease marker."],
  ["It shows the factor is protective",
   "A factor that predicts disease is associated with an increase in the probability of disease, so it is a risk factor rather than a protective one."],
  ["It shows removing it will prevent the disease",
   "Prevention through removing a factor lowers the probability of disease, but a marker that merely predicts disease without causing it would not be helped by removal."]],
 "c": 0, "cite": c(6)},

{"topic": "Studies of risk", "io": IO1, "slot": "principle",
 "q": "Why are experimental studies of risk in humans limited?",
 "opts": [
  ["Ethical constraints on exposing people",
   "Correct, since investigators cannot ethically assign people to a harmful exposure, so observational designs are used: concurrent (prospective) cohort, historical (retrospective) cohort and case-control studies."],
  ["Risk cannot be expressed as a ratio",
   "Risk can be expressed as relative risk, a ratio of incidences; the limit on experiments is ethical rather than mathematical."],
  ["Experiments cannot measure incidence",
   "Experiments can measure incidence; the limit is that exposing people to a suspected harm is unethical, which is why observational studies are used."],
  ["Exposures cannot be measured in humans",
   "Exposures can be measured in humans; the constraint is that people cannot ethically be assigned to a harmful exposure."]],
 "c": 0, "cite": c(8)},

# ---------------------------------------------------------------- IO 2
{"topic": "Relative risk", "io": IO2, "slot": "principle",
 "q": "What does a relative risk of 1 indicate?",
 "opts": [
  ["Equal risk in exposed and unexposed",
   "Correct: 1 is the null value, meaning absolute risk in the exposed equals absolute risk in the unexposed, so there is no association between exposure and disease."],
  ["Exposed persons have double the risk",
   "A relative risk of 2 would mean double the risk; a value of 1 means the two risks are equal, which is the null value."],
  ["Exposure fully protects against disease",
   "Protection appears as a value below 1; a relative risk of exactly 1 means the exposure makes no difference to risk."],
  ["Every exposed person develops the disease",
   "A relative risk of 1 says nothing about everyone falling ill; it says the risk in the exposed equals the risk in the unexposed."]],
 "c": 0, "cite": c(20)},

{"topic": "Relative risk", "io": IO2, "slot": "principle",
 "q": "What does a relative risk below 1 suggest?",
 "opts": [
  ["The exposure may be protective",
   "Correct, because risk in the exposed is lower than in the unexposed, a negative association, as with protection through exposure to an effective vaccine."],
  ["The exposure increases risk",
   "An increase in risk corresponds to a relative risk above 1, where the risk in the exposed exceeds the risk in the unexposed."],
  ["The exposure has no effect",
   "No effect corresponds to the null value of exactly 1; a value below 1 means the exposed have lower risk than the unexposed."],
  ["The exposure was measured wrongly",
   "A value below 1 is a valid result, not a measurement error; it reflects lower risk in the exposed, as with an effective vaccine."]],
 "c": 0, "cite": c(20)},

{"topic": "Relative risk", "io": IO2, "slot": "application",
 "q": "A study reports a relative risk of 0.6 for an exposure. What does that mean?",
 "opts": [
  ["Exposed persons have 40 percent lower risk",
   "Correct: the risk in exposed persons is 0.6 times that in unexposed persons, which is 40 percent lower, indicating a possibly protective association."],
  ["Exposed persons have 60 percent higher risk",
   "A relative risk of 0.6 is below 1, so risk is lower in the exposed; a 60 percent rise would be a relative risk of 1.6."],
  ["Exposed persons have 40 percent higher risk",
   "A 40 percent rise would be a relative risk of 1.4; 0.6 is below the null value of 1 and points to lower risk in the exposed."],
  ["Exposed and unexposed persons have equal risk",
   "Equal risk corresponds to a relative risk of exactly 1, the null value; 0.6 means the exposed group has lower risk."]],
 "c": 0, "cite": c(20)},

{"topic": "Relative risk", "io": IO2, "slot": "application",
 "q": "A cohort study finds a relative risk of 2.5. How likely are exposed persons to develop the disease compared with unexposed persons?",
 "opts": [
  ["2.5 times as likely",
   "Correct: relative risk is the ratio of the incidence in exposed persons to the incidence in unexposed persons, so 2.5 means exposed persons are two and a half times as likely."],
  ["2.5 percent more likely",
   "Relative risk is a ratio, not a percentage; a 2.5 percent increase in risk would be a relative risk of 1.025."],
  ["Half as likely",
   "Half as likely corresponds to a relative risk of 0.5, below the null value; 2.5 is above 1, so risk is higher in the exposed."],
  ["25 percent more likely",
   "A 25 percent increase would be a relative risk of 1.25; 2.5 means two and a half times the risk."]],
 "c": 0, "cite": c(19)},

{"topic": "Relative risk", "io": IO2, "slot": "principle",
 "q": "For an intervention that prevents disease, what relative risk is expected?",
 "opts": [
  ["Less than one",
   "Correct, because prevention should leave the exposed group, those receiving the intervention, with lower risk than the unexposed group."],
  ["Greater than one",
   "A value above one would mean the risk in the exposed exceeds the risk in the unexposed, which is what a harmful exposure shows."],
  ["Exactly one",
   "One is the null value and would mean the intervention makes no difference to risk, so nothing would be prevented."],
  ["A negative number",
   "Relative risk is a ratio of two incidences, and incidences cannot be negative, so the ratio cannot be either."]],
 "c": 0, "cite": c(19)},

{"topic": "Relative risk", "io": IO2, "slot": "limitation",
 "q": "Why does a relative risk alone not show the size of a patient's risk?",
 "opts": [
  ["It cancels out incidence",
   "Correct: dividing one incidence by another removes the incidence itself, so a doubling of risk looks the same whether the baseline is 1 in 10,000 or 1 in 10."],
  ["It counts only the exposed group",
   "Relative risk uses both groups, exposed and unexposed; what it lacks is the baseline incidence itself, because the division cancels it."],
  ["It cannot exceed two",
   "Relative risk can take any value above zero; the limitation is that the ratio hides how large the underlying incidence is."],
  ["It is always close to one",
   "Relative risk can be far from one; a value of 2.0 can arise from very different baseline incidences, which the ratio conceals."]],
 "c": 0, "cite": c(21)},

{"topic": "Relative risk", "io": IO2, "slot": "calculation",
 "q": "In a cohort study, 8 percent of exposed and 2 percent of unexposed persons developed a disease. What is the relative risk?",
 "opts": [
  ["4.0",
   "Correct: 8 percent divided by 2 percent gives 4.0, so exposed persons are four times as likely to develop the disease."],
  ["0.25",
   "That inverts the ratio; relative risk puts the incidence in the exposed on top, and 2 divided by 8 gives the reciprocal of the right value."],
  ["6.0",
   "Six is the difference in percentage points, which is the attributable risk; relative risk divides the two incidences rather than subtracting."],
  ["10",
   "Ten is the sum of the two percentages; relative risk is the incidence in the exposed divided by the incidence in the unexposed."]],
 "c": 0, "cite": c(19)},

{"topic": "Relative risk", "io": IO2, "slot": "calculation",
 "q": "In a cohort, 10 of 500 vaccinated and 40 of 500 unvaccinated persons developed influenza. What is the relative risk of influenza with vaccination?",
 "opts": [
  ["0.25",
   "Correct: 0.02 divided by 0.08 is 0.25; a value below 1 means the vaccinated have lower risk, here one quarter of the risk in the unvaccinated."],
  ["4.0",
   "That inverts the ratio and would suggest the vaccinated have four times the risk; vaccination is the exposure, so its incidence goes on top."],
  ["0.06",
   "0.06 is the difference in incidence, 0.08 minus 0.02, which is the size of the attributable risk rather than the ratio."],
  ["0.02",
   "0.02 is the incidence among the vaccinated, the absolute risk in the exposed group; relative risk compares it with the incidence in the unvaccinated."]],
 "c": 0, "cite": c(20)},

{"topic": "Relative risk", "io": IO2, "slot": "calculation",
 "q": "In a cohort, 12 of 300 exposed and 16 of 400 unexposed persons developed a disease. What does this show?",
 "opts": [
  ["No association with the exposure",
   "Correct: 12 of 300 and 16 of 400 are both 0.04, so the relative risk is 1.0, the null value, which indicates no association between exposure and disease."],
  ["Exposure lowers the risk by a quarter",
   "Comparing raw counts, 12 against 16, ignores the different group sizes; both incidences are 0.04, giving a relative risk of exactly 1."],
  ["Exposure raises the risk by a third",
   "Sixteen over twelve compares counts in groups of different size; converting to incidences gives 0.04 in each group and a relative risk of 1."],
  ["The counts are insufficient to judge",
   "The counts and group sizes are enough to calculate both incidences, 0.04 each, so the relative risk of 1.0 can be found."]],
 "c": 0, "cite": c(25)},

# ---------------------------------------------------------------- IO 3
{"topic": "Uses of risk", "io": IO3, "slot": "principle",
 "q": "In an individual patient, what is the best predictor of disease?",
 "opts": [
  ["Presence of early clinical disease",
   "Correct: risk factors raise the probability of disease, but in an individual it is early clinical disease itself that predicts best."],
  ["Presence of a single risk factor",
   "A risk factor raises the probability for groups of people; in an individual, early clinical disease is the better predictor."],
  ["The relative risk of the exposure",
   "Relative risk describes the strength of an association in groups, not what will happen to one person, for whom early clinical disease predicts best."],
  ["Incidence in the wider population",
   "Incidence in a population gives a probability for the group; for an individual patient the best predictor is early clinical disease."]],
 "c": 0, "cite": c(6)},

{"topic": "Uses of risk", "io": IO3, "slot": "principle",
 "q": "On what are probabilities of a future event based when predicting from risk factors?",
 "opts": [
  ["Data from groups of people",
   "Correct: predictions from risk factors are probabilities drawn from groups, which is why they fit an individual only loosely."],
  ["One patient followed in detail",
   "A single patient cannot yield a probability; predictions from risk factors are probabilities based on groups."],
  ["The clinician's judgment alone",
   "Clinical judgment is not the source of the probability; predictions from risk factors rest on data from groups of people."],
  ["Laboratory results from relatives",
   "Relatives' results do not define the probability; risk-based predictions come from groups of people sharing the factor."]],
 "c": 0, "cite": c(6)},

{"topic": "Uses of risk", "io": IO3, "slot": "application",
 "q": "A report gives the probability that a smoker will develop lung disease within ten years, based on cohort data. Which use of risk information is this?",
 "opts": [
  ["Prediction",
   "Correct, because prediction of a future event uses probabilities based on groups, here the incidence observed in a cohort of smokers."],
  ["Prevention",
   "Prevention means removing the risk factor to lower the probability of disease; the report only states a probability and removes nothing."],
  ["Diagnosis",
   "Diagnosis concerns disease already present, and the best predictor in an individual is early clinical disease rather than a group probability."],
  ["Cause",
   "Cause concerns whether the factor produces the disease; a probability from group data can be reported without showing that the factor is a cause."]],
 "c": 0, "cite": c(6)},

{"topic": "Studies of risk", "io": IO3, "slot": "principle",
 "q": "Which study design establishes incidence directly?",
 "opts": [
  ["Cohort study",
   "Correct: following exposed and unexposed persons forward shows who develops the disease, so incidence, the absolute risk, is found directly."],
  ["Case-control study",
   "A case-control study starts from persons who already have the condition, so incidence in exposed and unexposed persons cannot be found directly; it yields an odds ratio."],
  ["Case report",
   "A case report describes a single patient and supplies no group to divide by, so no incidence can be calculated; a cohort study follows a defined group."],
  ["Expert opinion",
   "Expert opinion is not a study of a followed group, so it cannot count new cases; a cohort study establishes incidence directly."]],
 "c": 0, "cite": c(16)},

{"topic": "Absolute risk", "io": IO3, "slot": "calculation",
 "q": "During two years, 18 of 600 patients on a surgical ward developed a pressure injury. What is the absolute risk?",
 "opts": [
  ["3 percent",
   "Correct: absolute risk is incidence, the number of new cases divided by the number of people in the group, so 18 divided by 600 is 0.03."],
  ["18 percent",
   "Eighteen is the number of new cases, not a percentage; incidence divides it by the 600 people in the group."],
  ["0.3 percent",
   "0.3 percent is 0.003, a tenfold slip; 18 divided by 600 is 0.03, which is 3 percent."],
  ["33 percent",
   "33 comes from dividing the group size by the number of cases, which inverts the fraction; incidence puts the new cases on top."]],
 "c": 0, "cite": c(17)},

{"topic": "Absolute risk", "io": IO3, "slot": "formula",
 "q": "How is incidence, or absolute risk, calculated?",
 "opts": [
  ["New cases in a period divided by group size",
   "Correct, and because it does not compare exposed with unexposed, absolute risk does not show whether the exposure is associated with increased risk."],
  ["All current cases divided by group size",
   "Dividing all existing cases by the group counts old and new cases together; incidence counts only NEW cases arising over the period."],
  ["New cases divided by all current cases",
   "The denominator of incidence is the number of people in the group, not the number of cases."],
  ["Exposed cases divided by unexposed cases",
   "Counts of cases ignore group sizes; relative risk divides the incidence in the exposed by the incidence in the unexposed."]],
 "c": 0, "cite": c(17)},

{"topic": "Relative risk", "io": IO3, "slot": "calculation",
 "q": "In unexposed persons the incidence is 0.05, and an exposure carries a relative risk of 3. How many cases are expected among 200 exposed persons?",
 "opts": [
  ["30",
   "Correct: the incidence in the exposed is 3 times 0.05, which is 0.15, and 0.15 times 200 persons gives 30 cases."],
  ["10",
   "Ten is 200 times the unexposed incidence of 0.05, the number expected without the exposure; the relative risk of 3 raises the exposed incidence to 0.15."],
  ["60",
   "Sixty is twice the correct count; multiplying the unexposed incidence by 3 gives 0.15, and applying that to 200 persons gives 30."],
  ["600",
   "600 multiplies the head count by the relative risk, which exceeds the size of the group; the relative risk multiplies the incidence, not the number of people."]],
 "c": 0, "cite": c(19)},

# ---------------------------------------------------------------- IO 4
{"topic": "Cohort studies", "io": IO4, "slot": "definition",
 "q": "What defines a cohort?",
 "opts": [
  ["People sharing a trait, followed over time",
   "Correct, and the shared characteristic may be age, date of birth, an exposure, having a specific disease, or taking part in a preventive or therapeutic intervention."],
  ["Cases matched with healthy controls",
   "Matching cases with controls describes a case-control study; a cohort is assembled by a shared characteristic and followed forward."],
  ["Patients randomly assigned to treatment",
   "Random assignment defines a randomized trial; a cohort is a group with a common characteristic assembled at a similar point and followed over time."],
  ["A single patient followed in detail",
   "A cohort is a group of people rather than one patient; the members share a characteristic and are followed over time."]],
 "c": 0, "cite": c(9)},

{"topic": "Cohort studies", "io": IO4, "slot": "principle",
 "q": "What must a cohort study have so that attrition does not falsely skew the outcome?",
 "opts": [
  ["Complete follow-up of the cohort",
   "Correct: if participants drop out, the outcome data can be falsely skewed, so the cohort must also be followed long enough to observe the expected outcome."],
  ["A larger control group",
   "A larger control group does not replace participants who are lost; the safeguard is complete follow-up of everyone in the cohort."],
  ["Random assignment to exposure",
   "Exposure is observed rather than assigned in a cohort study; dropout is addressed by following everyone through to the outcome."],
  ["Recall of past exposures",
   "Recall of past exposure is a concern in case-control studies; in a cohort, losses are prevented by following everyone over time."]],
 "c": 0, "cite": c(10)},

{"topic": "Cohort studies", "io": IO4, "slot": "definition",
 "q": "Which type of cohort study identifies the cohort from records and follows it forward to the present?",
 "opts": [
  ["Historical (retrospective) cohort",
   "Correct: the cohort is assembled in the past from records and followed forward to the present, so the outcomes have already occurred."],
  ["Concurrent (prospective) cohort",
   "A concurrent cohort is assembled in the present and followed into the future; it does not depend on past records."],
  ["Case-control study",
   "A case-control study is grouped by disease; despite sometimes being called retrospective, a historical cohort is grouped by exposure and followed forward."],
  ["Randomized controlled trial",
   "A randomized trial assigns the exposure by chance; a historical cohort only observes an exposure already recorded in the past."]],
 "c": 0, "cite": c(13)},

{"topic": "Cohort studies", "io": IO4, "slot": "limitation",
 "q": "What limits the usefulness of a historical cohort study?",
 "opts": [
  ["Records may lack needed data points",
   "Correct, since records were not set up for all the data points the research needs, so data may be incomplete until the study has run long enough."],
  ["Outcomes have not yet occurred",
   "In a historical cohort the outcomes have already occurred; the problem is incomplete records, not waiting for outcomes."],
  ["Participants cannot be identified",
   "The cohort is identified from records, so identification is possible; the weakness is that those records may lack the data needed."],
  ["Exposure is assigned by chance",
   "Exposure in a cohort study is observed, not assigned; the limit here is the completeness of the records."]],
 "c": 0, "cite": c(12)},

{"topic": "Cohort strengths and limits", "io": IO4, "slot": "advantage",
 "q": "Which is an advantage of cohort studies?",
 "opts": [
  ["Incidence can be established directly",
   "Correct, because following exposed and unexposed persons forward shows how many develop disease; exposure is also recorded without knowledge of the outcome."],
  ["Rare diseases can be studied cheaply",
   "Rare diseases need a very large cohort, so cohort studies are inefficient and expensive for them; case-control studies suit rare disease."],
  ["Results are available within weeks",
   "Cohort results may not be available for many years, since the group must be followed until the outcome occurs."],
  ["Few participants need enrolling",
   "A large cohort must be enrolled, which is why cohort studies are inefficient."]],
 "c": 0, "cite": c(14)},

{"topic": "Cohort strengths and limits", "io": IO4, "slot": "limitation",
 "q": "What limits the risk factors a cohort study can examine?",
 "opts": [
  ["Only exposures recorded at the outset",
   "Correct, so other contributing exposures may be missed when a disease has multiple causes."],
  ["Only diseases with short latency",
   "Cohorts can be followed for long periods; the limit is that only the exposure recorded at the outset can be followed."],
  ["Only exposed persons are followed",
   "Both exposed and unexposed persons are followed and compared; the limit concerns which exposures were recorded at the start."],
  ["Only one outcome can be studied",
   "A cohort can assess the relationship between an exposure and a number of outcomes; the restriction concerns which exposures were recorded."]],
 "c": 0, "cite": c(15)},

{"topic": "Cohort strengths and limits", "io": IO4, "slot": "advantage",
 "q": "What advantage does a retrospective cohort study have over a prospective one?",
 "opts": [
  ["It is faster, cheaper and more efficient",
   "Correct, because the data were already collected for another purpose and the outcomes have already occurred; the trade-off is a narrower range of risk factors."],
  ["It studies a wider range of risk factors",
   "The range of risk factors is NARROWER in a retrospective cohort, because only what was already recorded can be studied."],
  ["It measures exposure in a standardized way",
   "Measurement of exposure may not be standardized in a retrospective cohort; a prospective study can set up standardized measurement."],
  ["It can examine any patient characteristic",
   "A retrospective cohort cannot examine characteristics missing from the data set, whereas a prospective study can collect data not found in most medical records."]],
 "c": 0, "cite": c(16)},

{"topic": "Cohort strengths and limits", "io": IO4, "slot": "limitation",
 "q": "Why is a prospective cohort study impractical for rare diseases?",
 "opts": [
  ["Enrollment must far exceed the few events",
   "Correct: it is impractical because many more subjects must be enrolled than experience the event of interest, and it is also expensive and slow."],
  ["Rare diseases have no measurable exposures",
   "Exposures to rare diseases can be measured; the difficulty is the very large number of subjects needed."],
  ["The cohort cannot be followed forward",
   "A prospective cohort is followed forward by design; the problem is that so few of those enrolled develop the rare disease."],
  ["Standardized measures are unavailable",
   "A prospective cohort can set up standardized ways of measuring exposure; the limit is sample size, not measurement."]],
 "c": 0, "cite": c(16)},

{"topic": "Studies of risk", "io": IO4, "slot": "differential",
 "q": "Researchers randomly select 400 people who exercise and 400 who do not, then follow them for ten years. Why is this not a randomized controlled trial?",
 "opts": [
  ["Exposure was not randomly assigned",
   "Correct: random assignment of the exposure is what defines a randomized trial; here the groups were defined by an exposure people already had, making this a prospective cohort study."],
  ["Participants were followed over time",
   "Following participants forward is common to cohort studies and trials alike; random ASSIGNMENT is what separates a trial."],
  ["Participants were chosen at random",
   "Random selection describes how people were picked, not how the exposure was allocated; how people are assigned makes the difference."],
  ["The groups were equal in size",
   "Group size does not distinguish designs; a trial requires random assignment to the exposure or treatment."]],
 "c": 0, "cite": c(22)},

# ---------------------------------------------------------------- IO 5
{"topic": "Attributable risk", "io": IO5, "slot": "definition",
 "q": "What does attributable risk measure?",
 "opts": [
  ["Excess incidence in the exposed group",
   "Correct: it is the incidence in exposed persons minus the incidence in non-exposed persons, the possibility of disease following exposure."],
  ["How many times likelier exposed persons are",
   "That describes relative risk, a ratio of the two incidences; attributable risk is their difference."],
  ["Incidence in the whole population",
   "Incidence in a population is absolute risk, which takes no account of exposure to a risk factor."],
  ["Odds of exposure among cases",
   "Odds of exposure among cases belong to the odds ratio of a case-control study; attributable risk compares incidences in exposed and unexposed persons."]],
 "c": 0, "cite": c(18)},

{"topic": "Attributable risk", "io": IO5, "slot": "formula",
 "q": "How is attributable risk calculated?",
 "opts": [
  ["Exposed incidence minus unexposed incidence",
   "Correct: subtracting the incidence in non-exposed persons from that in exposed persons leaves the incidence attributable to the exposure."],
  ["Exposed incidence divided by unexposed incidence",
   "Dividing the two incidences gives relative risk, a ratio measuring strength of association, rather than attributable risk."],
  ["Unexposed incidence minus exposed incidence",
   "Subtracting in that order reverses the sign; attributable risk starts from the incidence in the exposed persons."],
  ["Exposed incidence plus unexposed incidence",
   "Adding the two incidences gives a meaningless combination; attributable risk is the difference between them."]],
 "c": 0, "cite": c(18)},

{"topic": "Relative risk", "io": IO5, "slot": "formula",
 "q": "How is relative risk calculated?",
 "opts": [
  ["Exposed incidence divided by unexposed incidence",
   "Correct: it expresses how many times more likely exposed persons are than non-exposed persons, and it examines the strength of association."],
  ["Exposed incidence minus unexposed incidence",
   "Subtracting the two incidences gives attributable risk, the excess in the exposed, rather than relative risk."],
  ["Unexposed incidence divided by exposed incidence",
   "Inverting the ratio is a common slip; relative risk puts the incidence in the exposed persons on top."],
  ["Exposed cases divided by all cases",
   "Cases alone ignore group sizes; relative risk is built from incidences in the exposed and unexposed groups."]],
 "c": 0, "cite": c(19)},

{"topic": "Attributable risk", "io": IO5, "slot": "calculation",
 "q": "Incidence is 15 per 500 in exposed persons and 5 per 500 in unexposed persons. What is the attributable risk?",
 "opts": [
  ["0.02",
   "Correct: the exposed incidence is 0.03 and the unexposed incidence is 0.01, and their difference is 0.02."],
  ["3.0",
   "Three is the ratio of the two incidences, 0.03 over 0.01, which is the relative risk rather than the attributable risk."],
  ["0.04",
   "0.04 is the sum of the two incidences; attributable risk is the incidence in the exposed minus the incidence in the unexposed."],
  ["0.03",
   "0.03 is the incidence in the exposed alone; attributable risk subtracts the unexposed incidence of 0.01 from it."]],
 "c": 0, "cite": c(18)},

{"topic": "Relative risk", "io": IO5, "slot": "calculation",
 "q": "In a cohort, 36 of 300 exposed and 20 of 400 unexposed persons developed disease. What is the relative risk?",
 "opts": [
  ["2.4",
   "Correct: 36 divided by 300 is 0.12, 20 divided by 400 is 0.05, and 0.12 divided by 0.05 is 2.4."],
  ["1.8",
   "1.8 divides the raw case counts, 36 by 20, ignoring the different group sizes; each count must first be turned into an incidence."],
  ["0.07",
   "0.07 is the difference between the incidences, 0.12 minus 0.05, which is the attributable risk rather than the ratio."],
  ["0.42",
   "0.42 inverts the ratio, unexposed over exposed; relative risk puts the incidence in the exposed persons on top."]],
 "c": 0, "cite": c(19)},

{"topic": "Attributable risk", "io": IO5, "slot": "application",
 "q": "Two exposures each have a relative risk of 2.0. Baseline incidence is 1 in 1,000 for the first and 1 in 10 for the second. Which has the greater attributable risk?",
 "opts": [
  ["The second, with the higher baseline",
   "Correct: attributable risk is the difference in incidence, 0.1 for the second exposure (0.2 minus 0.1) against 0.001 for the first, so the same relative risk hides a huge gap in excess cases."],
  ["The first, with the lower baseline",
   "The first exposure's excess is only 0.001 (0.002 minus 0.001); a low baseline gives a small attributable risk despite the same ratio."],
  ["Both, because the relative risks are equal",
   "Equal relative risks do not give equal attributable risks; relative risk cancels out incidence, whereas attributable risk depends on it."],
  ["Neither can be calculated",
   "Both can be calculated from the stated incidences, as the exposed incidence minus the unexposed incidence."]],
 "c": 0, "cite": c(21)},

{"topic": "Absolute risk", "io": IO5, "slot": "limitation",
 "q": "What can absolute risk not show?",
 "opts": [
  ["Whether exposure raises the risk",
   "Correct: absolute risk is simply the incidence in a population, so it says nothing about whether an exposure is associated with increased risk; attributable and relative risk add that."],
  ["How many new cases arose in the period",
   "The number of new cases is the numerator of absolute risk, so it is exactly what the measure reports."],
  ["How large the studied group was overall",
   "Group size is the denominator of absolute risk, so the measure is built directly on it."],
  ["How long the group was followed",
   "Absolute risk is incidence over a given time, so the follow-up period is part of the measure."]],
 "c": 0, "cite": c(17)},

{"topic": "Relative risk", "io": IO5, "slot": "calculation",
 "q": "The incidence is 0.02 in unexposed persons. An exposure carries a relative risk of 4. What is the incidence in exposed persons?",
 "opts": [
  ["0.08",
   "Correct: relative risk is the exposed incidence divided by the unexposed incidence, so the exposed incidence is 4 times 0.02, which is 0.08."],
  ["0.06",
   "0.06 is the excess over the baseline, the attributable risk (0.08 minus 0.02), not the exposed incidence itself."],
  ["0.005",
   "0.005 divides the baseline by the relative risk; a relative risk above 1 multiplies the baseline instead."],
  ["0.02",
   "0.02 is the baseline in the unexposed; a relative risk of 4 means the exposed incidence is four times that."]],
 "c": 0, "cite": c(19)},

# ---------------------------------------------------------------- IO 6
{"topic": "Confounding", "io": IO6, "slot": "definition",
 "q": "What is a confounding variable?",
 "opts": [
  ["A factor related to both exposure and outcome",
   "Correct: it is an additional independent factor, and because it is related to both exposure and outcome it can distort the apparent association."],
  ["A factor related only to the outcome",
   "A factor tied only to the outcome cannot account for a difference between exposed and unexposed persons; a confounder is related to BOTH."],
  ["A factor that changes the size of the effect",
   "A variable whose presence or absence changes the effect of exposure is an effect modifier, which is not a bias."],
  ["A factor unrelated to exposure and outcome",
   "A factor unrelated to both would leave the association undistorted; a confounder is related to exposure and to outcome."]],
 "c": 0, "cite": c(26)},

{"topic": "Confounding", "io": IO6, "slot": "principle",
 "q": "What kind of error does confounding cause?",
 "opts": [
  ["Systematic error (bias)",
   "Correct: confounding causes systematic error, because an additional factor related to both exposure and outcome distorts the association in a consistent way."],
  ["Error caused by chance alone",
   "Chance produces random variation, equally likely above or below the truth; confounding is a systematic error, a bias."],
  ["Sampling error from a small study",
   "Small samples add random error; confounding is a bias that arises from a factor related to both exposure and outcome."],
  ["Error from participants dropping out",
   "Dropout is the attrition effect, a separate problem; confounding is systematic error from a third factor."]],
 "c": 0, "cite": c(26)},

{"topic": "Confounding", "io": IO6, "slot": "application",
 "q": "In a study of coffee drinking and pancreatic cancer, smoking is more common among coffee drinkers and also raises cancer risk. What role does smoking play?",
 "opts": [
  ["A confounder",
   "Correct: smoking is related to both the exposure, coffee, and the outcome, cancer, so it can produce a false association, a systematic error."],
  ["An effect modifier",
   "An effect modifier changes the size of the exposure's effect and is not a bias; smoking here is linked to both exposure and outcome."],
  ["The outcome",
   "The outcome is the cancer being studied; smoking is an additional factor rather than the disease itself."],
  ["The exposure",
   "The exposure under study is coffee drinking; smoking is an additional factor linked to both exposure and outcome."]],
 "c": 0, "cite": c(26)},

{"topic": "Controlling confounding", "io": IO6, "slot": "differential",
 "q": "Which method gives each patient an equal chance of falling into either group?",
 "opts": [
  ["Randomization",
   "Correct: it is applied in the design phase and spreads confounders between the groups by chance."],
  ["Restriction",
   "Restriction limits the range of characteristics of patients in the study rather than assigning them by chance."],
  ["Matching",
   "Matching selects comparison patients with the same characteristics as each patient in the other group rather than assigning by chance."],
  ["Stratification",
   "Stratification compares rates within subgroups with otherwise similar probability of the outcome, and is applied in the analysis phase."]],
 "c": 0, "cite": c(27)},

{"topic": "Controlling confounding", "io": IO6, "slot": "differential",
 "q": "For each patient in one group, comparison patients with the same characteristics are chosen. Which method is this?",
 "opts": [
  ["Matching",
   "Correct, and it can be applied at both the design and the analysis phase, choosing comparison patients who share every characteristic except the one under study."],
  ["Restriction",
   "Restriction limits the range of characteristics of patients in the study, rather than pairing patients one by one."],
  ["Randomization",
   "Randomization gives each patient an equal chance of either group rather than pairing patients by characteristics."],
  ["Simple adjustment",
   "Simple adjustment is a mathematical correction of crude rates for one or a few characteristics, applied at the analysis phase."]],
 "c": 0, "cite": c(27)},

{"topic": "Controlling confounding", "io": IO6, "slot": "differential",
 "q": "Which method compares rates within subgroups that have a similar probability of the outcome?",
 "opts": [
  ["Stratification",
   "Correct: comparing rates within strata of otherwise similar risk is an analysis-phase method for controlling confounding."],
  ["Restriction",
   "Restriction limits the range of characteristics of patients in the study, which is a design-phase method rather than a comparison within subgroups."],
  ["Multivariable adjustment",
   "Multivariable adjustment uses mathematical modeling to adjust for differences in a large number of factors, not comparison within subgroups."],
  ["Matching",
   "Matching selects comparison patients with the same characteristics, rather than comparing rates within strata of similar risk."]],
 "c": 0, "cite": c(27)},

{"topic": "Controlling confounding", "io": IO6, "slot": "differential",
 "q": "Which analysis method uses mathematical modeling to adjust for a large number of factors?",
 "opts": [
  ["Multivariable adjustment",
   "Correct: it adjusts for differences in many factors related to the outcome using mathematical modeling techniques, in the analysis phase."],
  ["Simple adjustment",
   "Simple adjustment corrects crude rates for one or a few characteristics, so that equal weight is given to strata of similar risk."],
  ["Stratification",
   "Stratification compares rates within subgroups of similar risk rather than modeling many factors at once."],
  ["Restriction",
   "Restriction limits the range of patient characteristics in the study, a design-phase method rather than a model."]],
 "c": 0, "cite": c(27)},

{"topic": "Controlling confounding", "io": IO6, "slot": "differential",
 "q": "Which pair of methods is applied only in the design phase?",
 "opts": [
  ["Randomization and restriction",
   "Correct: both are built into the study plan, whereas matching works at either phase and the remaining methods are analysis-phase methods."],
  ["Matching and stratification",
   "Stratification is an analysis method, and matching can be used at either phase, so this pair is not design-only."],
  ["Simple and multivariable adjustment",
   "Both adjustment methods are applied in the analysis phase, after the data are collected, not in the design phase."],
  ["Stratification and randomization",
   "Stratification is analysis-only and randomization is design-only, so this pair does not sit in the design phase together."]],
 "c": 0, "cite": c(27)},

# ---------------------------------------------------------------- IO 7
{"topic": "Effect modification", "io": IO7, "slot": "definition",
 "q": "What is effect modification?",
 "opts": [
  ["A variable changes the effect of exposure",
   "Correct: the presence or absence of the variable changes the effect of the exposure, and the change may be synergistic or antagonistic."],
  ["A third factor distorts the association",
   "A third factor related to both exposure and outcome that distorts the association is confounding, a bias; effect modification is not a bias."],
  ["Participants drop out during follow-up",
   "Losing participants during follow-up is the attrition effect; effect modification concerns how a variable alters the effect of exposure."],
  ["Results vary randomly between samples",
   "Random variation is chance; effect modification is a variable whose presence or absence alters the effect of exposure."]],
 "c": 0, "cite": c(28)},

{"topic": "Effect modification", "io": IO7, "slot": "differential",
 "q": "How does effect modification differ from confounding?",
 "opts": [
  ["It is a real effect, not a bias",
   "Correct: confounding is a systematic error to be controlled, whereas effect modification is not a bias but a genuine change in the effect of exposure."],
  ["It is a bias that must be removed",
   "Effect modification is explicitly not a bias; confounding is the systematic error that methods such as matching and stratification try to remove."],
  ["It arises only in randomized trials",
   "Effect modification can arise in observational studies too; what defines it is a variable that changes the effect of exposure."],
  ["It always weakens the effect",
   "The change may be synergistic, strengthening the effect, or antagonistic, weakening it; it does not always weaken it."]],
 "c": 0, "cite": c(28)},

{"topic": "Effect modification", "io": IO7, "slot": "definition",
 "q": "Effect modification that strengthens the effect of an exposure is called what?",
 "opts": [
  ["Synergistic",
   "Correct, and effect modification that weakens the effect of exposure is antagonistic; neither form is a bias."],
  ["Antagonistic",
   "Antagonistic effect modification weakens or opposes the effect of the exposure rather than strengthening it."],
  ["Confounding",
   "Confounding is a systematic error from a factor related to both exposure and outcome, not a way in which an effect is strengthened."],
  ["Systematic",
   "Systematic describes error (bias) such as confounding; the forms of effect modification are synergistic and antagonistic."]],
 "c": 0, "cite": c(28)},

{"topic": "Effect modification", "io": IO7, "slot": "definition",
 "q": "Effect modification that weakens the effect of an exposure is called what?",
 "opts": [
  ["Antagonistic",
   "Correct, and effect modification that strengthens the effect of exposure is synergistic; neither form is a bias."],
  ["Synergistic",
   "Synergistic effect modification strengthens the effect of the exposure rather than weakening it."],
  ["Random",
   "Random describes chance variation; the two forms of effect modification are synergistic and antagonistic."],
  ["Confounding",
   "Confounding is a systematic error, a bias, whereas effect modification is not a bias."]],
 "c": 0, "cite": c(28)},

{"topic": "Effect modification", "io": IO7, "slot": "example",
 "q": "Aspirin raises the risk of upper gastrointestinal bleeding much more in older patients than in younger ones. What is age in this relationship?",
 "opts": [
  ["An effect modifier",
   "Correct: the exposure acts differently depending on age, which is what effect modification means, as opposed to age merely distorting the association."],
  ["A confounder",
   "A confounder distorts an association because it is related to both exposure and outcome; here age changes the size of the exposure's own effect."],
  ["The dependent variable",
   "The dependent variable is the outcome, which here is bleeding; age is the variable that changes how strongly aspirin acts."],
  ["A control group",
   "A control group is a comparison group of unexposed subjects; age here is a characteristic that changes the exposure's effect."]],
 "c": 0, "cite": c(28)},

{"topic": "Effect modification", "io": IO7, "slot": "application",
 "q": "A drug lowers blood pressure far more in younger than in older adults. What does age represent here?",
 "opts": [
  ["An effect modifier",
   "Correct: the effect of the exposure differs according to the level of another variable, which is effect modification and not a bias."],
  ["A confounder",
   "A confounder is linked to both exposure and outcome and distorts the association; here age changes the size of the drug's effect."],
  ["A source of recall bias",
   "Recall bias concerns inaccurate memory of past exposure; age here alters the size of the drug's effect."],
  ["A matched control",
   "Matching selects comparison patients with the same characteristics; it does not describe a variable that changes the effect of an exposure."]],
 "c": 0, "cite": c(28)},

# ---------------------------------------------------------------- IO 8
{"topic": "Case-control studies", "io": IO8, "slot": "definition",
 "q": "On what basis are the two groups of a case-control study chosen?",
 "opts": [
  ["Whether they have the condition",
   "Correct: the case group has the condition and the control group does not, and each is then compared for earlier exposure."],
  ["Whether they were exposed",
   "Grouping by exposure defines a cohort study; a case-control study groups by whether the condition is present."],
  ["Whether they were randomly assigned",
   "Random assignment defines a randomized trial; case-control groups are formed by condition and are not allocated."],
  ["Whether they finished follow-up",
   "Completing follow-up matters in cohort studies; a case-control study does not follow persons forward."]],
 "c": 0, "cite": c(30)},

{"topic": "Case-control studies", "io": IO8, "slot": "application",
 "q": "Which situation favors a case-control design?",
 "opts": [
  ["A rare disease with long latency",
   "Correct: a cohort would need a very large group followed for years for few cases, whereas a case-control study starts from the cases and needs a smaller sample."],
  ["A common disease with rapid onset",
   "A common disease with rapid onset produces cases quickly in a cohort, so the cohort's drawbacks matter less."],
  ["A need to measure incidence directly",
   "Incidence is established directly by a cohort study, not by a case-control study."],
  ["A budget for decades of follow-up",
   "Long follow-up is exactly what a case-control study avoids; a cohort study is the design that needs it."]],
 "c": 0, "cite": c(29)},

{"topic": "Case-control studies", "io": IO8, "slot": "advantage",
 "q": "Why do case-control studies need smaller samples than cohort studies?",
 "opts": [
  ["Cases are picked for having the condition",
   "Correct: a cohort must be large because only a limited number of those followed get the condition, whereas a case-control study starts with people who already have it."],
  ["Controls are not required for the comparison",
   "Controls are essential, since exposure in cases is compared with exposure in persons without the condition."],
  ["Exposure is randomly assigned to subjects",
   "Exposure is observed rather than assigned in a case-control study; random assignment belongs to trials."],
  ["Bias from recall of exposure is removed",
   "Recall bias is a recognized limitation of case-control studies, because subjects are often asked about past exposure."]],
 "c": 0, "cite": c(29)},

{"topic": "Case-control studies", "io": IO8, "slot": "advantage",
 "q": "What does a case-control study not need to do that a cohort study does?",
 "opts": [
  ["Wait for the condition to develop",
   "Correct, since the cases already have the condition, which is why results do not take years to obtain."],
  ["Define who counts as a case",
   "A case group must still be defined as persons who have the condition; that is the starting point of the design."],
  ["Identify a comparison group",
   "The control group without the condition is required, since exposure in cases is compared with exposure in controls."],
  ["Ask about earlier exposure",
   "Earlier exposure is exactly what the study asks about, which is why recall bias is a concern."]],
 "c": 0, "cite": c(29)},

{"topic": "Case-control studies", "io": IO8, "slot": "framework",
 "q": "In which direction does a case-control study look for exposure?",
 "opts": [
  ["Backward from disease to past exposure",
   "Correct: cases and controls are identified first and then compared for earlier exposure, so the research runs backward in time and yields an estimate of relative risk."],
  ["Forward from exposure to disease",
   "Looking forward from exposure to disease describes a cohort study, which follows exposed and unexposed persons over time."],
  ["Forward from random assignment",
   "Random assignment belongs to trials; a case-control study starts from persons who already have or lack the condition."],
  ["Only at the moment of diagnosis",
   "Exposure at diagnosis alone would say nothing about earlier exposure; the design looks back at exposure before the condition."]],
 "c": 0, "cite": c(31)},

{"topic": "Case-control studies", "io": IO8, "slot": "limitation",
 "q": "Which bias threatens a case-control study when subjects are asked about past exposure?",
 "opts": [
  ["Recall bias",
   "Correct: accuracy of memory and the ability to recall specific information are imperfect, so reported exposure may be inaccurate, especially once subjects know the disease being studied."],
  ["Attrition effect",
   "Attrition is dropout during follow-up, a cohort problem; case-control subjects are not followed forward."],
  ["Publication bias",
   "Publication bias concerns which finished studies get published, not how exposure is reported by subjects."],
  ["Non-response bias",
   "Non-response bias arises when responders differ from non-responders; recall bias specifically concerns inaccurate memory of past exposure."]],
 "c": 0, "cite": c(33)},

{"topic": "Case-control studies", "io": IO8, "slot": "application",
 "q": "A study compares patients with newly diagnosed melanoma to patients without it and asks about past sunburns. What is the exposure?",
 "opts": [
  ["Sunburns in the past",
   "Correct: the exposure is the factor compared between the groups, here past sunburns, while the presence or absence of melanoma defines the groups."],
  ["A diagnosis of melanoma",
   "Melanoma is the condition that defines the case group, not the exposure being asked about."],
  ["Being in the control group",
   "Control status is defined by not having the condition; the exposure is the factor asked about, past sunburns."],
  ["The patient's age at diagnosis",
   "Age is a characteristic that might be matched or considered as a confounder, not the exposure this study asks about."]],
 "c": 0, "cite": c(31)},

{"topic": "Case-control studies", "io": IO8, "slot": "limitation",
 "q": "Why is a cohort study often impractical for an exposure with a long latency and a rare outcome?",
 "opts": [
  ["Latency means long waits, large samples",
   "Correct: with a latency between exposure and pathological effect a large sample is needed and only a limited number get the condition; case-control studies need smaller samples and no waiting."],
  ["Exposure cannot be measured in them",
   "Cohort studies record exposure at the outset; the difficulty is the latency and the large sample needed, not measurement."],
  ["They cannot follow persons over time",
   "Following persons over time is what defines a cohort study; the trouble is how long and how large the follow-up must be."],
  ["They always rely on recall of exposure",
   "Recall of exposure is the weakness of case-control studies; a cohort records exposure at the outset."]],
 "c": 0, "cite": c(29)},

# ---------------------------------------------------------------- IO 9
{"topic": "Odds ratio", "io": IO9, "slot": "principle",
 "q": "Why do cohort studies usually use relative risk rather than odds ratio?",
 "opts": [
  ["Incidence can be calculated directly",
   "Correct: cohort studies can directly calculate the incidence of disease in the exposed versus non-exposed, so relative risk is usually used rather than the odds ratio."],
  ["Odds cannot be calculated from cohort data",
   "Odds can be calculated from any 2x2 table; what a cohort allows is direct calculation of incidence, so relative risk is used."],
  ["Cohort studies lack an unexposed group",
   "Cohort studies compare exposed with unexposed persons, and that comparison is what gives the relative risk."],
  ["Odds ratios apply only to randomized trials",
   "The odds ratio is the measure of association for case-control studies, not for randomized trials."]],
 "c": 0, "cite": c(35)},

{"topic": "Odds ratio", "io": IO9, "slot": "formula",
 "q": "In a 2x2 table with exposed cases (a), exposed noncases (b), unexposed cases (c) and unexposed noncases (d), what is the odds ratio?",
 "opts": [
  ["ad divided by bc",
   "Correct: the odds of exposure in cases, a over c, divided by the odds of exposure in controls, b over d, simplifies to ad over bc."],
  ["ac divided by bd",
   "That multiplies within columns; the odds of exposure in cases (a over c) divided by the odds in controls (b over d) simplifies to ad over bc."],
  ["ab divided by cd",
   "That multiplies across rows; the odds ratio is ad over bc, the cross-products of the 2x2 table."],
  ["a/(a+b) divided by c/(c+d)",
   "That expression is the relative risk formula for a cohort table, built from incidences in the exposed and unexposed rows rather than odds."]],
 "c": 0, "cite": c(36)},

{"topic": "Relative risk", "io": IO9, "slot": "formula",
 "q": "In a cohort 2x2 table with exposed cases (a), exposed noncases (b), unexposed cases (c) and unexposed noncases (d), which expression gives the relative risk?",
 "opts": [
  ["a/(a+b) divided by c/(c+d)",
   "Correct: the incidence in the exposed, a over a plus b, divided by the incidence in the unexposed, c over c plus d."],
  ["ad divided by bc",
   "That is the odds ratio, the measure of association for case-control studies rather than the relative risk of a cohort."],
  ["a/(a+c) divided by b/(b+d)",
   "That divides within columns, comparing the proportion exposed among cases with that among noncases, which is how a case-control table is read."],
  ["a/c divided by b/d",
   "That is the odds ratio written another way (equal to ad over bc); relative risk uses the incidences a/(a+b) and c/(c+d)."]],
 "c": 0, "cite": c(36)},

{"topic": "Odds ratio", "io": IO9, "slot": "calculation",
 "q": "In a case-control study, 60 of 100 cases and 30 of 100 controls had been exposed. What is the odds ratio?",
 "opts": [
  ["3.5",
   "Correct: the odds of exposure are 60 to 40, which is 1.5, in cases and 30 to 70, about 0.43, in controls, and the ratio is 3.5, matching ad over bc, 4,200 over 1,200."],
  ["2.0",
   "2.0 divides the exposed counts, 60 by 30, ignoring the unexposed counts; odds compare exposed with unexposed within each group."],
  ["1.5",
   "1.5 is only the odds of exposure among cases; the odds ratio divides it by the odds of exposure among controls."],
  ["0.29",
   "0.29 inverts the ratio, control odds over case odds; the odds in cases go on top."]],
 "c": 0, "cite": c(38)},

{"topic": "Odds ratio", "io": IO9, "slot": "calculation",
 "q": "In a case-control study, 48 of 60 cases had been exposed. What are the odds of exposure among cases?",
 "opts": [
  ["4",
   "Correct: odds compare those exposed with those not exposed, 48 to 12, which is 4."],
  ["0.8",
   "0.8 is the proportion exposed, 48 of 60; odds divide exposed by unexposed instead."],
  ["0.25",
   "0.25 inverts the odds, 12 over 48; the exposed count goes on top."],
  ["1.25",
   "1.25 divides the total by the exposed (60 over 48); odds are exposed over unexposed, 48 over 12."]],
 "c": 0, "cite": c(38)},

{"topic": "Odds ratio", "io": IO9, "slot": "calculation",
 "q": "In a case-control study, 20 of 100 cases and 40 of 100 controls had been exposed. What is the odds ratio?",
 "opts": [
  ["0.38",
   "Correct: (20 over 80) divided by (40 over 60) is 0.25 over 0.67, about 0.375, which is below 1, so exposure is associated with lower odds of disease."],
  ["2.7",
   "2.7 inverts the ratio, control odds over case odds; the odds of exposure in cases go on top."],
  ["0.50",
   "0.50 divides the exposed counts, 20 by 40, ignoring the unexposed counts; odds compare exposed with unexposed within each group."],
  ["0.25",
   "0.25 is only the odds of exposure among cases, 20 to 80; the odds ratio divides it by the odds of exposure among controls."]],
 "c": 0, "cite": c(38)},

{"topic": "Odds ratio", "io": IO9, "slot": "application",
 "q": "Patients with lung disease had six times the odds of prior asbestos exposure compared with patients without it. Which statement follows?",
 "opts": [
  ["Exposed persons have six times the odds of disease",
   "Correct: the odds ratio is the same whichever way it is read, so it can be stated as the odds of disease in the exposed, which is what is actually wanted."],
  ["Six percent of exposed persons develop disease",
   "An odds ratio is a ratio of odds, not the percentage of exposed persons who are affected."],
  ["Unexposed persons have six times the odds of disease",
   "That reverses the direction; an odds ratio above 1 means the exposed, not the unexposed, have the greater odds."],
  ["One in six exposed persons has the disease",
   "An odds ratio of six is not a one-in-six frequency; it compares odds between groups."]],
 "c": 0, "cite": c(39)},

{"topic": "Odds ratio", "io": IO9, "slot": "principle",
 "q": "What does an odds ratio from a case-control study estimate?",
 "opts": [
  ["Relative risk",
   "Correct: an odds ratio is an estimated relative risk, which is why the case-control design ends in an estimate of relative risk."],
  ["Attributable risk",
   "Attributable risk is a difference between incidences, which a case-control study cannot supply directly; the odds ratio estimates relative risk."],
  ["Absolute risk",
   "Absolute risk is incidence in a population, which a case-control study cannot supply directly; the odds ratio estimates relative risk."],
  ["Incidence in the exposed",
   "Incidence in the exposed cannot be calculated directly in a case-control study; the odds ratio estimates the relative risk instead."]],
 "c": 0, "cite": c(36)},

{"topic": "Odds ratio", "io": IO9, "slot": "application",
 "q": "Researchers enroll 150 patients with a rare cancer and 300 without it, and ask about past exposure. Which measure of association suits this study?",
 "opts": [
  ["Odds ratio",
   "Correct, because the odds ratio is the measure of association for case-control studies, while relative risk is used for cohort studies."],
  ["Relative risk",
   "Relative risk is used for cohort studies, where incidence in the exposed and unexposed can be calculated directly."],
  ["Attributable risk",
   "Attributable risk subtracts incidences, which this design cannot supply directly; the odds ratio is the measure for case-control studies."],
  ["Absolute risk",
   "Absolute risk is the incidence in a population, which needs a followed group; the odds ratio is the measure for case-control studies."]],
 "c": 0, "cite": c(35)},
]
