# -*- coding: utf-8 -*-
# Interpretation of Medical Literature, Session 1 -- pool B: the bias taxonomy,
# chance, and internal versus external validity. Pool A carries epidemiology,
# evidence-based medicine and the anatomy of a study.
#
# Sourcing as in pool A: slides only, each question citing its slide.
#
# Correct answer is ALWAYS written first (c=0); the partition script rotates.
from medlit_s1_pool_a import c, IOA, IOB, IOC, IOD, IOE

POOL_B = [

{"topic": "Bias", "io": IOE, "slot": "definition",
 "q": "What is bias in medical research?",
 "opts": [
  ["Systematic error producing conclusions that differ from the true results",
   "Correct, and the word systematic separates it from chance: bias pushes results consistently in one direction, whereas random variation is equally likely to go either way."],
  ["Random variation producing conclusions that differ from the true results",
   "That is chance. Bias is systematic rather than random, which is why it cannot be corrected by enlarging the sample."],
  ["A deliberate attempt by investigators to mislead readers",
   "Bias need not be deliberate at all, and can enter at any stage from conception and design through to interpretation."],
  ["A difference between two groups that reaches statistical significance",
   "Statistical significance concerns whether a difference is likely to be due to chance rather than whether systematic error is present."]],
 "c": 0, "cite": c(38)},

{"topic": "Bias", "io": IOE, "slot": "principle",
 "q": "At which stages of a study can bias occur?",
 "opts": [
  ["Conception and design, collection, analysis and interpretation",
   "Correct, which is why appraising a study means reading the whole of it: a sound design can still be undone by how the data were gathered, analysed or read."],
  ["Data collection only",
   "Collection is one stage among four; bias can equally enter at design, analysis or interpretation."],
  ["Only after the results have been published",
   "Publication bias concerns which studies appear in print, but bias within a study arises during its conduct, from design through interpretation."],
  ["Only when the investigators have a financial conflict of interest",
   "A conflict of interest is one specific threat to objectivity, but bias arises from many sources and at every stage of a study."]],
 "c": 0, "cite": c(38)},

{"topic": "Bias", "io": IOE, "slot": "principle",
 "q": "What follows from the fact that a study has the potential for bias?",
 "opts": [
  ["Bias should be considered, but potential does not always mean it is present",
   "Correct, and the practical consequence is that bias is often detectable when reading an article, so the reader's job is to look for it rather than to assume it either way."],
  ["The study's conclusions must be rejected",
   "Potential for bias is a reason to examine a study carefully rather than to discard it, since the potential does not establish that bias occurred."],
  ["The study's conclusions can be accepted without further scrutiny",
   "The potential for bias is precisely what should prompt scrutiny, since bias is often detectable from a careful reading."],
  ["Statistical analysis will correct for it",
   "Analysis can estimate the effect of chance, but no analysis corrects for unknown biases."]],
 "c": 0, "cite": c(38)},

{"topic": "Selection bias", "io": IOE, "slot": "definition",
 "q": "When does selection bias occur?",
 "opts": [
  ["When compared groups differ in more ways than the study's focus",
   "Correct, and the consequence is severe: few conclusions can be drawn about the topic of interest, because the difference in outcome cannot be attributed to the thing being studied. What matters is that those extra differences affect the outcome."],
  ["When the method of measurement leads to incorrect results",
   "That is measurement bias, which concerns how data are gathered rather than who ends up in each group."],
  ["When participants drop out of the study before it ends",
   "That is the attrition effect, which reduces the sample size during the study rather than distorting the groups at the outset."],
  ["When research without significant results is less likely to be published",
   "That is publication bias, which operates on the body of literature rather than within a single study's sample."]],
 "c": 0, "cite": c(40)},

{"topic": "Selection bias", "io": IOE, "slot": "application",
 "q": "A trial compares surgical with medical therapy. Patients in the surgical arm were healthy enough to tolerate an operation, while the medical arm carried more comorbidities. Which bias does this illustrate?",
 "opts": [
  ["Selection bias",
   "Correct. The groups differ in baseline health as well as in treatment, so a difference in outcome cannot be attributed to the therapy, which is the defining problem of biased sampling."],
  ["Measurement bias",
   "Measurement bias would arise from how the outcome was assessed rather than from a difference in who was allocated to each group."],
  ["Publication bias",
   "Publication bias concerns whether studies reach print according to their results rather than how participants were assigned within one study."],
  ["Non-response bias",
   "Non-response bias arises when survey respondents differ from those who do not reply, which is not the situation described."]],
 "c": 0, "cite": c(40)},

{"topic": "Selection bias", "io": IOE, "slot": "principle",
 "q": "At which stage of a study is selection bias an important consideration?",
 "opts": [
  ["Study design",
   "Correct, because how the groups are assembled is decided then. Confounding by contrast is an important consideration during data analysis, once the data exist."],
  ["Data analysis",
   "Data analysis is where confounding is an important consideration. Sampling is settled at the design stage."],
  ["Data interpretation",
   "Interpretation is too late to alter who was enrolled; sampling has to be addressed when the study is designed."],
  ["Publication",
   "Publication concerns which completed studies appear in print rather than how a study's groups were assembled."]],
 "c": 0, "cite": c(40)},

{"topic": "Measurement bias", "io": IOE, "slot": "definition",
 "q": "What is measurement bias?",
 "opts": [
  ["The method of measurement leads to incorrect results",
   "Correct, and the example given is blood pressure: if standardised procedures are not followed for every measurement taken during a study, the resulting values cannot be trusted."],
  ["The groups compared differ in more ways than the study's focus",
   "That is selection bias, which concerns who is in each group rather than how they were measured."],
  ["The effect of a covariate cannot be separated from the effect under study",
   "That is confounding, which concerns the analysis of an association rather than the accuracy of the measurement itself."],
  ["Only a subset of the relevant data is made available",
   "That is reporting bias, which concerns what is disclosed rather than how it was measured."]],
 "c": 0, "cite": c(41)},

{"topic": "Confounding", "io": IOE, "slot": "definition",
 "q": "What defines confounding?",
 "opts": [
  ["The covariate's effect cannot be separated from the variable studied",
   "Correct, and the covariate must be associated with both the exposure and the outcome, which is what allows it to masquerade as the relationship under investigation."],
  ["The covariate must be the direct cause of the disease",
   "A covariate does not need to cause the disease in order to confound; association with both exposure and outcome is enough."],
  ["The measurement instrument produces consistently high readings",
   "That is measurement bias, arising from method rather than from an uncontrolled third variable."],
  ["Participants in the control group seek other treatments",
   "That is performance bias, where care differs between groups in ways other than the intervention studied."]],
 "c": 0, "cite": c(42)},

{"topic": "Confounding", "io": IOE, "slot": "principle",
 "q": "What can give rise to confounding?",
 "opts": [
  ["Selection bias or chance",
   "Correct, and this is why it is an important consideration during data analysis: whether it arose by biased sampling or by bad luck, the analysis is where it has to be detected and addressed."],
  ["Publication bias alone",
   "Publication bias operates across a literature rather than creating an uncontrolled variable within one study's data."],
  ["Attrition alone",
   "Attrition reduces sample size when participants drop out, which is a separate problem from a covariate entangled with the exposure."],
  ["Failure to blind the outcome assessor",
   "Blinding protects against performance bias; confounding may result from selection bias or from chance."]],
 "c": 0, "cite": c(42)},

{"topic": "Confounding", "io": IOE, "slot": "application",
 "q": "In a medication trial, the placebo control group turns out to be older on average than the experimental group. What does this represent?",
 "opts": [
  ["Age acting as a confounding variable",
   "Correct, because age is plausibly associated with both group membership and the outcome, so its effect cannot be separated from the effect of the medication being tested."],
  ["Measurement bias in recording age",
   "Nothing suggests age was measured wrongly; the problem is that it differs systematically between the groups being compared."],
  ["Attrition effect",
   "Attrition describes participants dropping out during the study rather than a baseline difference between the groups."],
  ["Reporting bias by the investigators",
   "Reporting bias concerns withholding a subset of data rather than an imbalance in a baseline characteristic."]],
 "c": 0, "cite": c(43)},

{"topic": "Procedural bias", "io": IOE, "slot": "definition",
 "q": "What is procedural bias?",
 "opts": [
  ["Interview or questionnaire results are affected by the method of delivery",
   "Correct, and the example is pointed: administering a questionnaire after an operation while the patient is still under the after-effects of anaesthesia."],
  ["Participants drop out before the study is complete",
   "That is the attrition effect, which reduces sample size rather than distorting how responses were elicited."],
  ["Respondents differ systematically from non-respondents",
   "That is non-response bias, which concerns who answers rather than the circumstances in which they were asked."],
  ["Care differs between the groups in ways other than the intervention",
   "That is performance bias, which concerns treatment received rather than how information was collected."]],
 "c": 0, "cite": c(44)},

{"topic": "Attrition effect", "io": IOE, "slot": "definition",
 "q": "What is the attrition effect, and what is its consequence?",
 "opts": [
  ["Participants drop out of the study, which reduces the sample size",
   "Correct, and a smaller sample is the immediate consequence, which matters because a study's ability to detect a real difference depends on how many participants remain."],
  ["Participants are allocated to groups that differ at baseline",
   "That is selection bias, present from the beginning rather than developing as participants leave."],
  ["Survey respondents differ systematically from those who do not respond",
   "That is non-response bias, which concerns a survey's respondents rather than participants leaving a study in progress."],
  ["Investigators withhold a subset of their data",
   "That is reporting bias, a decision about disclosure rather than participants departing."]],
 "c": 0, "cite": c(44)},

{"topic": "Non-response bias", "io": IOE, "slot": "definition",
 "q": "Why does non-response bias matter?",
 "opts": [
  ["Responders may differ from non-respondents",
   "Correct, and the consequence is about generalisation: a survey answered by an unrepresentative subset describes that subset rather than the whole population."],
  ["The sample size falls below the level needed for analysis",
   "A falling sample size describes the attrition effect. Non-response bias concerns who answers rather than how many."],
  ["The questionnaire was delivered at an inappropriate moment",
   "That is procedural bias, which concerns the method of delivery rather than the difference between responders and non-responders."],
  ["Results that are not statistically significant go unpublished",
   "That is publication bias, which shapes the literature rather than an individual survey's sample."]],
 "c": 0, "cite": c(44)},

{"topic": "Performance bias", "io": IOE, "slot": "definition",
 "q": "What is performance bias?",
 "opts": [
  ["Care differs between the groups in ways other than the topic of interest",
   "Correct, and the example is that participants in a control group may seek other treatments once they know they are receiving a placebo, which changes their care independently of the trial."],
  ["The measurement method produces systematically incorrect values",
   "That is measurement bias, which concerns how outcomes are recorded rather than what care participants actually received."],
  ["Groups differ at baseline in ways that affect the outcome",
   "That is selection bias, arising from how the groups were assembled rather than from what happened to them during the study."],
  ["Only favourable results are made available",
   "That is reporting bias, concerning disclosure of data rather than differences in care delivered."]],
 "c": 0, "cite": c(45)},

{"topic": "Performance bias", "io": IOE, "slot": "prevention",
 "q": "What protects against performance bias?",
 "opts": [
  ["Blinding of study participants",
   "Correct, and the mechanism follows directly from the example: a participant who does not know they are on placebo has no reason to go looking for other treatment."],
  ["Increasing the sample size",
   "A larger sample reduces the influence of random variation but does nothing about a systematic difference in the care each group receives."],
  ["Disclosing conflicts of interest",
   "Disclosure addresses threats to objectivity from financial or personal considerations rather than differences in care between groups."],
  ["Publishing the study protocol in advance",
   "Blinding of participants is what is named as the protection here, because it removes the knowledge that drives the behaviour."]],
 "c": 0, "cite": c(45)},

{"topic": "Reporting bias", "io": IOE, "slot": "definition",
 "q": "What is reporting bias?",
 "opts": [
  ["Only a subset of all relevant data is made available",
   "Correct, and it is distinct from publication bias: here the study appears, but not all of what it found appears with it."],
  ["Research without significant results is less likely to be published",
   "That is publication bias, which determines whether a study appears at all rather than how much of it is disclosed."],
  ["The method of questionnaire delivery distorts the answers",
   "That is procedural bias, concerning how data were collected rather than how much of it was reported."],
  ["Financial considerations affect the objectivity of the investigators",
   "That is a conflict of interest, which is about the influences on investigators rather than the completeness of what they report."]],
 "c": 0, "cite": c(45)},

{"topic": "Publication bias", "io": IOE, "slot": "definition",
 "q": "What drives publication bias?",
 "opts": [
  ["Research without significant results is less likely to be published",
   "Correct, and two forces sustain it: journal editor preference, and sponsors being less likely to support research unfavourable to them or to their product."],
  ["Investigators disclose only a subset of the data they collected",
   "That is reporting bias, operating within a published study rather than determining which studies are published."],
  ["Participants drop out before the study is complete",
   "That is the attrition effect, a problem inside a study rather than a filter on what reaches the literature."],
  ["Journals publish only research funded by government agencies",
   "The named drivers are editor preference and sponsor reluctance regarding unfavourable results, not the source of funding as such."]],
 "c": 0, "cite": c(46)},

{"topic": "Publication bias", "io": IOE, "slot": "principle",
 "q": "Why might a sponsoring company contribute to publication bias?",
 "opts": [
  ["It is less likely to support research unfavourable to its product",
   "Correct, and it sits alongside journal editor preference as the second force keeping results that show nothing out of the literature."],
  ["It insists that all its funded studies be published in full",
   "Publishing everything would counteract publication bias rather than contribute to it."],
  ["It requires investigators to disclose conflicts of interest",
   "Disclosure is a protection against threats to objectivity rather than a driver of publication bias."],
  ["It selects participants who are most likely to benefit",
   "Choosing favourable participants would produce selection bias within a study rather than bias in what gets published."]],
 "c": 0, "cite": c(46)},

{"topic": "Conflict of interest", "io": IOE, "slot": "definition",
 "q": "What is a conflict of interest, and what should be done about it?",
 "opts": [
  ["Financial or personal considerations affect objectivity",
   "Correct, and the reason disclosure rather than exclusion is the remedy is that the impact may be unconscious as well as conscious, so the reader is left to weigh it. Authors should disclose it."],
  ["A disagreement between investigators about how to analyse the data",
   "The term concerns financial or personal considerations bearing on objectivity rather than a methodological dispute."],
  ["An imbalance between the intervention and control groups",
   "A baseline imbalance is selection bias or confounding rather than a conflict of interest."],
  ["A study whose results contradict those of an earlier study",
   "Contradictory findings raise questions about validity rather than constituting a conflict of interest."]],
 "c": 0, "cite": c(46)},

{"topic": "Chance", "io": IOD, "slot": "definition",
 "q": "What is chance in medical research?",
 "opts": [
  ["Random variation producing conclusions that differ from the true results",
   "Correct, and the crucial property is that it is random: it is equally likely to produce a result higher or lower than the truth, unlike bias, which pushes one way."],
  ["Systematic error producing conclusions that differ from the true results",
   "That is bias. Chance is random rather than systematic, which is what makes the two behave differently."],
  ["A deliberate decision to report only favourable findings",
   "That is reporting bias, a choice rather than random variation."],
  ["The probability that a patient will develop a given disease",
   "That is a statement of risk about patients rather than a source of error in a study's conclusions."]],
 "c": 0, "cite": c(47)},

{"topic": "Chance", "io": IOD, "slot": "principle",
 "q": "What can be done about chance in a study?",
 "opts": [
  ["It can be estimated statistically and reduced, but never eliminated",
   "Correct, and it may coexist with bias, so demonstrating that a result is unlikely to be due to chance does not establish that it is free of systematic error. Good study design is what reduces it."],
  ["It can be eliminated entirely by a sufficiently large sample",
   "Good study design reduces random variation but never removes it completely."],
  ["It can be corrected for during data analysis like any other error",
   "Statistical analysis estimates the degree of random variation rather than correcting the results for it."],
  ["It is present only in studies that also contain bias",
   "The two are independent sources of error, although they may coexist in the same study."]],
 "c": 0, "cite": c(47)},

{"topic": "Chance", "io": IOD, "slot": "application",
 "q": "A series of blood pressure measurements in a study all fall above the true value. What does that pattern indicate?",
 "opts": [
  ["Bias, because the error is systematic not random",
   "Correct. Random variation would scatter the readings above and below the true value with equal likelihood, so a consistent one-sided departure points to systematic error."],
  ["Chance, because measurement always varies",
   "Random variation is equally likely to produce a higher or a lower result, so readings that all land on one side are not explained by chance."],
  ["Confounding by an unmeasured variable",
   "Confounding distorts an association between variables rather than displacing every measurement in the same direction."],
  ["Attrition, because participants left the study",
   "Attrition reduces the number of participants rather than shifting the recorded values consistently upward."]],
 "c": 0, "cite": c(48)},

{"topic": "Study quality", "io": IOD, "slot": "principle",
 "q": "What is the relationship between study design, bias and chance?",
 "opts": [
  ["Poor design leaves data vulnerable to both of them",
   "Correct, and the asymmetry matters: statistics can estimate the effect of chance, but there is no equivalent repair for a bias nobody has identified."],
  ["Good statistical analysis compensates for any weakness in design",
   "Analysis can estimate the effect of chance but cannot correct for unknown biases, so design cannot be rescued after the fact."],
  ["Bias and chance are the same phenomenon described differently",
   "One is systematic and one is random, which is precisely why they are handled differently."],
  ["Chance affects only small studies and bias only large ones",
   "Neither is confined by study size; random variation and systematic error can appear in studies of any scale."]],
 "c": 0, "cite": c(49)},

{"topic": "Validity", "io": IOC, "slot": "principle",
 "q": "Which two questions should a provider ask when presented with a study?",
 "opts": [
  ["Are the conclusions valid for the sample, and does the sample represent my patients?",
   "Correct, and the two map onto the two kinds of validity: the first is internal validity, the second external validity, which is why both have to be asked."],
  ["Was the study published in a high-impact journal, and how often is it cited?",
   "Journal standing is not what determines whether conclusions hold for the sample or apply to your patients."],
  ["How large was the sample, and how long did the study run?",
   "Size and duration bear on a study's quality but are not the two questions named for judging validity."],
  ["Who funded the study, and were the results statistically significant?",
   "Funding and significance are worth knowing, but the two validity questions concern correctness within the sample and applicability beyond it."]],
 "c": 0, "cite": c(50)},

{"topic": "Validity", "io": IOC, "slot": "definition",
 "q": "What is internal validity?",
 "opts": [
  ["The degree to which results are correct for the sample of patients studied",
   "Correct, and it is the prior question: results that are not correct for the people actually studied cannot be true of anyone else either."],
  ["The degree to which results are also true in other clinical settings",
   "That is external validity, sometimes called generalisability, which asks about applicability beyond the study."],
  ["The degree to which a measurement instrument gives consistent readings",
   "Consistency of measurement is a separate property; internal validity concerns whether the study's conclusions are correct for its own sample."],
  ["The proportion of enrolled participants who completed the study",
   "Completion relates to the attrition effect rather than to whether conclusions are correct for those studied."]],
 "c": 0, "cite": c(51)},

{"topic": "Validity", "io": IOC, "slot": "definition",
 "q": "What is external validity also called?",
 "opts": [
  ["Generalisability",
   "Correct, and it is rarely determined from a single study, which is why one trial supporting an intervention does not establish that it will work in a different setting."],
  ["Reliability",
   "Reliability concerns consistency of measurement rather than whether findings hold in other clinical settings."],
  ["Internal validity",
   "Internal validity is the separate question of whether the conclusions are correct for the sample actually studied."],
  ["Significance",
   "Statistical significance concerns the role of chance in a result rather than whether that result applies elsewhere."]],
 "c": 0, "cite": c(51)},

{"topic": "Validity", "io": IOC, "slot": "principle",
 "q": "What is noted about determining external validity?",
 "opts": [
  ["It is rarely determined from a single study",
   "Correct, and the practical consequence is that a result has to be reproduced in other settings and populations before it can be relied on outside the original one."],
  ["It follows automatically once internal validity is established",
   "Results can be entirely correct for the sample studied and still not hold in a different clinical setting."],
  ["It is established by the size of the sample alone",
   "A large sample improves precision but does not by itself show that findings transfer to other settings."],
  ["It is determined by the journal in which the study appears",
   "Where a study is published says nothing about whether its findings generalise to other populations."]],
 "c": 0, "cite": c(51)},
]
