# -*- coding: utf-8 -*-
# Interpretation of Medical Literature, Session 9 -- Statistics, Correlation and
# Causation. Probability, significance and the p value, the null hypothesis, type
# I and type II error, the common statistical tests, confidence intervals,
# statistical power, multiple comparisons, multivariable modeling, statistical
# versus clinical significance, types of cause, criteria for causation, pitfalls
# in causal research, and how study design limits causal conclusions.
#
# CALCULATION. As in the Tests session, arithmetic questions are fair here. The
# figures are SUPPLIED and the stem asks what follows (probability from counts,
# the complement, power from the type II error probability, the number of false
# positives expected by chance across many comparisons, and how to read a
# confidence interval around a relative risk or a difference). Every figure below
# was recomputed in Python before it was written; none is taken from the deck's
# own worked example.
#
# WHERE THE DECK IS LOOSE, THE TRUTH IS KEYED (see the report that accompanied
# this file): a p value is the probability of a difference at least this large
# by chance ALONE if no true difference exists (not the probability that the null
# hypothesis is true); the type II error is a failure to detect a real difference.
#
# KEYS ARE WRITTEN SHORT ON PURPOSE -- detail lives in the explanation.
#
# Correct answer is ALWAYS written first (c=0); the partition script rotates.
SRC = "9 PAJ5512 Statistics Causation MBF_2026sc.pptx"
def c(n):  return f"{SRC}, Slide {n}"

IOA = ("Explain the following statistical concepts: Significance, P value, Null "
       "hypothesis, Confidence interval, Statistical power, Multiple comparisons, "
       "Multivariable modeling")
IOB = "Compare and contrast statistical significance and clinical importance"
IOC = "Define criteria to determine causation"
IOD = "Discuss the impact of study design on the ability to determine causation"

POOL = [

# ---------------------------------------------------------------- Probability
{"topic": "Probability", "io": IOA, "slot": "formula",
 "q": "How is the probability of an event estimated from counts?",
 "opts": [
  ["Times it occurs divided by times it can occur",
   "Correct, and the result must lie between zero, meaning the event cannot occur, and one, meaning it will definitely occur."],
  ["Times it occurs divided by times it does not occur",
   "That ratio is the odds rather than the probability; a probability puts the occurrences over ALL the opportunities, occurrences included."],
  ["Times it does not occur divided by times it can occur",
   "That is the probability that the event does NOT occur, the complement of the one being estimated."],
  ["Times it can occur divided by times it occurs",
   "Inverting the fraction gives a value of one or more, but a probability can never exceed one."]],
 "c": 0, "cite": c(4)},

{"topic": "Probability", "io": IOA, "slot": "calculation",
 "q": "In a clinic of 240 patients, 36 have the condition. What is the probability that a randomly chosen patient has it?",
 "opts": [
  ["0.15",
   "Correct: 36 divided by 240 is 0.15, the number with the condition over the number of patients who could have had it."],
  ["0.85",
   "That is 204 divided by 240, the probability of NOT having the condition; the sum of the two probabilities is one."],
  ["0.18",
   "That divides 36 by the 204 patients without the condition, which gives odds; the denominator must be all 240 patients."],
  ["6.7",
   "That inverts the fraction (240 divided by 36); a probability can never exceed one."]],
 "c": 0, "cite": c(4)},

{"topic": "Probability", "io": IOA, "slot": "calculation",
 "q": "The probability that a sampled patient has a condition is 0.35. What is the probability that a sampled patient does not have it?",
 "opts": [
  ["0.65",
   "Correct: the probabilities of all possible events in the sample must sum to one, so the complement of 0.35 is 0.65."],
  ["0.35",
   "That repeats the probability of HAVING the condition; the probability of not having it is what remains of the total of one."],
  ["0.50",
   "A probability of 0.5 would mean an equal chance of occurring or not occurring, which is not what 0.35 implies."],
  ["1.35",
   "That adds 0.35 to one; a probability cannot exceed one, and the complement is found by subtracting from one."]],
 "c": 0, "cite": c(4)},

# ---------------------------------------------------- Significance and p value
{"topic": "Significance and p value", "io": IOA, "slot": "definition",
 "q": "What does statistical significance describe?",
 "opts": [
  ["How unlikely it is that the result arose by chance",
   "Correct, so a more statistically significant result is less likely to be chance and a less significant one is more likely to be chance."],
  ["How much the treatment helps an individual patient",
   "That describes clinical significance, which asks whether a difference matters to patients rather than whether chance could explain it."],
  ["How carefully the study was designed and carried out",
   "Design quality bears on bias and validity, whereas statistical significance concerns only how likely chance is as the explanation."],
  ["Whether the result would change clinical practice",
   "That is a judgment of clinical importance; a result can be statistically significant and still leave practice unchanged."]],
 "c": 0, "cite": c(6)},

{"topic": "Significance and p value", "io": IOA, "slot": "definition",
 "q": "What does a p value express?",
 "opts": [
  ["Chance of such data if no true difference",
   "Correct, calculated on the assumption that no true difference exists, so it is not the probability that the null hypothesis is true or that the treatment works."],
  ["The probability that the treatment truly works",
   "A p value cannot say how likely a treatment is to work; it says how probable data this extreme would be by chance if there were no true difference."],
  ["The size of the difference between groups",
   "Size of difference is the effect size; a p value can be very small for a tiny difference when the sample is large."],
  ["The probability that the study is biased",
   "Bias is systematic error that a p value cannot detect; the p value addresses random chance only."]],
 "c": 0, "cite": c(7)},

{"topic": "Significance and p value", "io": IOA, "slot": "principle",
 "q": "Below what p value is a result generally accepted as statistically significant?",
 "opts": [
  ["0.05",
   "Correct, meaning a chance of about 1 in 20; a p value of 0.01 (1 in 100) is generally called highly significant and 0.001 (1 in 1000) very highly significant."],
  ["0.50",
   "A p value of 0.5 means the chance explanation is 50/50, which is nowhere near the accepted threshold of 0.05."],
  ["0.10",
   "The generally accepted cutoff is stricter than 0.10; a value below 0.05 is what is usually called statistically significant."],
  ["0.01",
   "A p value below 0.01 is generally called highly significant, which is a stricter grade above the ordinary 0.05 cutoff."]],
 "c": 0, "cite": c(7)},

{"topic": "Significance and p value", "io": IOA, "slot": "principle",
 "q": "How is the 0.05 cutoff for significance best described?",
 "opts": [
  ["An arbitrary convention",
   "Correct: nothing changes in the data between a p value of 0.049 and 0.051; 0.05 is simply the number generally agreed on."],
  ["A law of probability theory",
   "Probability theory does not dictate 0.05; the cutoff was chosen by convention, and other values could equally have been used."],
  ["A proof of clinical benefit",
   "Even a result below 0.05 says only that chance is an unlikely explanation, not that the finding matters to patients."],
  ["A limit set by regulators",
   "Regulators often adopt 0.05, but they took up an existing statistical convention; the cutoff did not originate as a regulatory rule and is not a law of probability."]],
 "c": 0, "cite": c(7)},

{"topic": "Significance and p value", "io": IOA, "slot": "interpretation",
 "q": "A trial reports a p value of 0.03 for a new drug against placebo. Which statement is best supported?",
 "opts": [
  ["The difference is statistically significant",
   "Correct, because 0.03 falls below the generally accepted threshold of 0.05, making chance an unlikely explanation."],
  ["There is a 3 percent chance the drug does not work",
   "The p value assumes no true difference and gives the chance of data this extreme; it is not the probability that the drug fails."],
  ["The drug works in 97 percent of patients",
   "A p value says nothing about what share of patients respond; it is a probability calculated under the no-difference assumption."],
  ["The difference is large enough to change practice",
   "Statistical significance does not imply clinical importance, which depends on how large the difference is and whether it matters to patients."]],
 "c": 0, "cite": c(7)},

{"topic": "Significance and p value", "io": IOA, "slot": "interpretation",
 "q": "A trial reports a p value of 0.20. Which statement is best supported?",
 "opts": [
  ["The result is not statistically significant",
   "Correct, since 0.20 is above the threshold of 0.05, so chance remains a reasonable explanation for the difference seen."],
  ["The treatment has been shown to have no effect",
   "A non-significant result does not prove that no difference exists; the study may have lacked power, producing a type II error."],
  ["Eighty percent of patients improved",
   "A p value is not a proportion of patients; it is the probability of data this extreme if there were no true difference."],
  ["The result is very highly significant",
   "Very highly significant is reserved for p values around 0.001 or lower; 0.20 does not reach even the ordinary 0.05 threshold."]],
 "c": 0, "cite": c(7)},

# ------------------------------------------------------------ Null hypothesis
{"topic": "Null hypothesis", "io": IOA, "slot": "definition",
 "q": "What does the null hypothesis state?",
 "opts": [
  ["That there is no difference",
   "Correct, and it is usually the opposite of what the researchers hope to find; it is the hypothesis that statistical analysis sets out to test."],
  ["That there is an important difference",
   "The presence of a difference is the alternative to the null hypothesis, which is what the researchers are typically trying to show."],
  ["That any difference is due to bias",
   "Bias is systematic error; the null hypothesis instead states that no true difference exists, so any observed gap is chance."],
  ["That the sample is unrepresentative",
   "Representativeness concerns external validity; the null hypothesis is a statement about whether groups differ."]],
 "c": 0, "cite": c(8)},

{"topic": "Null hypothesis", "io": IOA, "slot": "application",
 "q": "Researchers hope to show that a new drug lowers blood pressure more than placebo. What is the null hypothesis?",
 "opts": [
  ["The drug and placebo lower pressure equally",
   "Correct: the null hypothesis is that there is no difference, which is the opposite of what the researchers hope to find."],
  ["The drug lowers pressure more than placebo",
   "That is the researchers' hoped-for finding, the alternative hypothesis; the null hypothesis is its opposite."],
  ["The placebo lowers pressure more than the drug",
   "That states a difference in the wrong direction; the null hypothesis states no difference in either direction."],
  ["The drug lowers pressure in every patient",
   "That is a sweeping claim of universal benefit, whereas the null hypothesis is simply that there is no difference."]],
 "c": 0, "cite": c(8)},

{"topic": "Null hypothesis", "io": IOA, "slot": "principle",
 "q": "When the data offer little support for the null hypothesis, what gains support?",
 "opts": [
  ["That a difference is present",
   "Correct: evidence against the null hypothesis, which states no difference, is what lends support to a difference being present."],
  ["That the study is free of bias",
   "Weak support for the null hypothesis says nothing about bias, which is a systematic error the statistical test cannot detect."],
  ["That the groups were identical",
   "Identical groups is what the null hypothesis itself states, so weak support for it points away from that idea."],
  ["That the sample was adequate",
   "Sample adequacy relates to power and precision and cannot be inferred from how well the data fit the null hypothesis."]],
 "c": 0, "cite": c(8)},

# ------------------------------------------------------- Type I and type II
{"topic": "Type I and type II error", "io": IOA, "slot": "definition",
 "q": "What is a type I error?",
 "opts": [
  ["Stating there is a difference when there is not",
   "Correct: a false positive, also called an alpha error, which is the error most medical research is concerned with and is judged through the p value."],
  ["Stating there is no difference when there is",
   "That is a type II error, a false negative, in which a real difference is missed."],
  ["Finding a difference that truly exists",
   "Detecting a real difference is a correct conclusion, not an error; a type I error reports a difference that is not real."],
  ["Measuring the outcome incorrectly",
   "Faulty measurement is measurement bias; a type I error is a wrong conclusion about whether a true difference exists."]],
 "c": 0, "cite": c(10)},

{"topic": "Type I and type II error", "io": IOA, "slot": "definition",
 "q": "What is a type II error?",
 "opts": [
  ["Stating there is no difference when there is",
   "Correct: a false negative, also called a beta error, in which a real difference is missed and the result appears not significant."],
  ["Stating there is a difference when there is not",
   "That is a type I error, a false positive, in which chance produces an apparent difference that is not real."],
  ["Finding no difference where none exists",
   "That is a correct conclusion; a type II error requires that a real difference exists and goes undetected."],
  ["Choosing the wrong statistical test",
   "Test selection is a separate matter; a type II error is defined by missing a difference that truly exists."]],
 "c": 0, "cite": c(11)},

{"topic": "Type I and type II error", "io": IOA, "slot": "application",
 "q": "A trial concludes that a supplement lowers cholesterol, but in truth it has no effect. Which error occurred?",
 "opts": [
  ["Type I error",
   "Correct: a difference was declared when none exists, a false positive, which is the alpha error."],
  ["Type II error",
   "A type II error would be missing a real effect; here an effect was claimed that does not exist."],
  ["No error",
   "The conclusion disagrees with the truth, so an error occurred; the correct conclusion would have been no significant difference."],
  ["Confounding",
   "Confounding is a covariate whose effect cannot be separated from the variable studied, not a mismatch between conclusion and truth."]],
 "c": 0, "cite": c(9)},

{"topic": "Type I and type II error", "io": IOA, "slot": "application",
 "q": "A short trial finds no significant benefit from a drug that truly works. Which error occurred?",
 "opts": [
  ["Type II error",
   "Correct: a real difference was missed, a false negative, which can result from limits such as short follow-up."],
  ["Type I error",
   "A type I error would be claiming a benefit that does not exist, whereas here a real benefit went undetected."],
  ["No error",
   "The drug truly works but the result was reported as not significant, so the conclusion is wrong and an error occurred."],
  ["Recall bias",
   "Recall bias is difficulty remembering past exposures; it is unrelated to a false negative statistical conclusion."]],
 "c": 0, "cite": c(11)},

{"topic": "Type I and type II error", "io": IOA, "slot": "discrimination",
 "q": "When no true difference exists, which conclusion is correct?",
 "opts": [
  ["That the result is not significant",
   "Correct: with no true difference, a non-significant test result is right, while a significant result would be a type I error."],
  ["That the result is significant",
   "A significant result when no true difference exists is a type I error, a false positive."],
  ["That the null hypothesis is false",
   "The null hypothesis states there is no difference, so when no difference exists it is true and should not be rejected."],
  ["That the study has high power",
   "Power is the chance of detecting a difference that DOES exist, so it is not a conclusion about a case with no difference."]],
 "c": 0, "cite": c(9)},

{"topic": "Type I and type II error", "io": IOA, "slot": "principle",
 "q": "Which study limitation can produce a type II error?",
 "opts": [
  ["Short follow-up or poor compliance",
   "Correct: too brief a follow-up or subjects not adhering can hide a real difference, so the result looks not significant though it is a false negative."],
  ["A p value smaller than 0.001",
   "A p value that small is a significant result, which is the opposite of the not significant result that defines a type II error."],
  ["Random assignment of participants",
   "Random assignment is a strength of design that balances the groups; it does not cause a real difference to be missed."],
  ["Blinding the investigators",
   "Blinding reduces bias; it does not by itself hide a true difference, whereas study limits such as follow-up length can."]],
 "c": 0, "cite": c(11)},

# ----------------------------------------------------------- Statistical tests
{"topic": "Statistical tests", "io": IOA, "slot": "discrimination",
 "q": "Which test compares two means?",
 "opts": [
  ["Student t test",
   "Correct, used between two means; the F test extends this to two or more means."],
  ["Fisher exact test",
   "The Fisher exact test compares two proportions when there are only a small number of observations."],
  ["Mann-Whitney U test",
   "The Mann-Whitney U test compares two medians rather than two means."],
  ["Chi-square test",
   "The chi-square test compares two or more proportions when there is a large number of observations."]],
 "c": 0, "cite": c(13)},

{"topic": "Statistical tests", "io": IOA, "slot": "discrimination",
 "q": "Which test compares two proportions when there are few observations?",
 "opts": [
  ["Fisher exact test",
   "Correct: it handles two proportions when the number of observations is small, where the chi-square test would be unsuitable."],
  ["Chi-square test",
   "The chi-square test compares proportions but is used when there is a large number of observations."],
  ["Student t test",
   "The Student t test compares two means, which are averages of continuous values rather than proportions."],
  ["Mann-Whitney U test",
   "The Mann-Whitney U test compares two medians rather than proportions."]],
 "c": 0, "cite": c(13)},

{"topic": "Statistical tests", "io": IOA, "slot": "discrimination",
 "q": "Which technique models an outcome measured as time to an event?",
 "opts": [
  ["Cox proportional hazards",
   "Correct: it models a time-to-event outcome, whereas logistic regression handles a dichotomous outcome."],
  ["Logistic regression",
   "Logistic regression models a dichotomous outcome (event or no event), not the time until an event occurs."],
  ["Pearson's r",
   "Pearson's r describes the extent of association between two variables and does not model multiple variables."],
  ["Propensity score",
   "A propensity score is used to select matching controls rather than to model time to an event."]],
 "c": 0, "cite": c(13)},

# --------------------------------------------------------- Confidence interval
{"topic": "Confidence interval", "io": IOA, "slot": "definition",
 "q": "What does a 95 percent confidence interval give?",
 "opts": [
  ["A range that should contain the true value",
   "Correct: the boundaries are the confidence limits, and if the study were repeated many times about 95 percent of such intervals would contain the true value."],
  ["The range holding 95 percent of patients' values",
   "That describes the spread of individual values; a confidence interval expresses uncertainty about the estimate itself."],
  ["The range in which the p value must fall",
   "A p value is a single probability, and the interval is a range around the estimate of the true value, not a range for the p value."],
  ["The range of bias in the estimate",
   "A confidence interval reflects random variation and precision; it does not measure or correct systematic error."]],
 "c": 0, "cite": c(14)},

{"topic": "Confidence interval", "io": IOA, "slot": "principle",
 "q": "What does a confidence interval indicate about an estimate?",
 "opts": [
  ["Its statistical precision",
   "Correct: a narrow interval means a precise estimate and a wide interval a less precise one."],
  ["Its clinical importance",
   "Clinical importance depends on whether the size of the effect matters to patients, not on how narrow the interval is."],
  ["Its freedom from bias",
   "An interval can be narrow and still be wrong if the study is biased; precision is not accuracy."],
  ["Its statistical power",
   "Power is the chance of detecting a true difference, calculated as one minus the type II error probability, which is a different quantity."]],
 "c": 0, "cite": c(14)},

{"topic": "Confidence interval", "io": IOA, "slot": "interpretation",
 "q": "A study reports a relative risk of 0.70 with a 95 percent confidence interval of 0.55 to 0.90. What does that show?",
 "opts": [
  ["A statistically significant reduction in risk",
   "Correct: a relative risk of 1 means no difference, and this whole interval lies below 1, so the reduction is statistically significant."],
  ["No significant difference between groups",
   "The interval does not include 1, the value of no difference, so the difference is statistically significant."],
  ["A statistically significant increase in risk",
   "Values below 1 mean the risk is lower in the exposed or treated group; an increase would need values above 1."],
  ["An estimate too imprecise to interpret",
   "The interval is reasonably narrow and excludes 1, so it supports a real reduction rather than uncertainty about direction."]],
 "c": 0, "cite": c(15)},

{"topic": "Confidence interval", "io": IOA, "slot": "interpretation",
 "q": "A study reports a relative risk of 1.2 with a 95 percent confidence interval of 0.8 to 1.8. What does that show?",
 "opts": [
  ["No statistically significant difference",
   "Correct: the interval contains 1, the value of no difference, so a true relative risk of 1 cannot be excluded."],
  ["A proven 20 percent increase in risk",
   "The point estimate is 1.2, but the interval runs from below 1 to well above it, so an increase is not established."],
  ["A statistically significant protective effect",
   "Part of the interval lies below 1, but part lies above it, so neither benefit nor harm is established."],
  ["A precise estimate of harm",
   "The interval is wide, spanning both benefit and harm, so the estimate is imprecise rather than precise."]],
 "c": 0, "cite": c(15)},

{"topic": "Confidence interval", "io": IOA, "slot": "interpretation",
 "q": "Which 95 percent confidence interval for a difference in mean weight loss between two groups shows a statistically significant difference?",
 "opts": [
  ["1.0 to 3.5 kilograms",
   "Correct: for a difference the value of no effect is zero, and this interval lies entirely above zero."],
  ["-0.5 to 3.0 kilograms",
   "This interval contains zero, the value of no difference, so it is not statistically significant."],
  ["-2.0 to 1.5 kilograms",
   "This interval straddles zero, so no difference between the groups cannot be excluded."],
  ["-1.5 to 0.5 kilograms",
   "This interval also contains zero, so it does not show a statistically significant difference."]],
 "c": 0, "cite": c(15)},

{"topic": "Confidence interval", "io": IOA, "slot": "interpretation",
 "q": "Two studies both estimate a relative risk of 0.6. Study A's 95 percent interval is 0.5 to 0.7 and Study B's is 0.2 to 1.8. Which statement is correct?",
 "opts": [
  ["Study A's estimate is more precise",
   "Correct: a narrower interval means greater statistical precision, and Study B's interval also contains 1, so it is not significant."],
  ["Study B's estimate is more precise",
   "A wider interval means LESS precision; Study B's range of 0.2 to 1.8 leaves the true value very uncertain."],
  ["Both estimates are equally precise",
   "The same point estimate can carry different precision; the width of the interval is what distinguishes them."],
  ["Study B shows a significant reduction",
   "Study B's interval contains 1, the value of no difference, so a significant reduction is not shown."]],
 "c": 0, "cite": c(15)},

# --------------------------------------------------------- Statistical power
{"topic": "Statistical power", "io": IOA, "slot": "definition",
 "q": "What is statistical power?",
 "opts": [
  ["The chance of detecting a real difference",
   "Correct: the probability that a study will find a statistically significant difference when the difference really exists."],
  ["The chance of reporting a false difference",
   "That describes a type I error (false positive); power concerns finding differences that are truly there."],
  ["The size of the difference between groups",
   "The size of a difference is the effect size; power is a probability of detecting a difference that exists."],
  ["The chance that the null hypothesis is true",
   "The null hypothesis being true means no difference exists; power is defined for the case where a difference does exist."]],
 "c": 0, "cite": c(16)},

{"topic": "Statistical power", "io": IOA, "slot": "formula",
 "q": "How is statistical power calculated?",
 "opts": [
  ["One minus the type II error probability",
   "Correct: power equals 1 minus P beta, where P beta is the probability of a type II error, so power is high when a study is likely to detect true differences."],
  ["One minus the type I error probability",
   "That would be the complement of the false positive probability, not power; power is defined from the type II error."],
  ["One minus the p value",
   "A p value belongs to the observed result and is not how power is calculated."],
  ["The type II error probability itself",
   "That value is the chance of missing a real difference; power is its complement, one minus that probability."]],
 "c": 0, "cite": c(16)},

{"topic": "Statistical power", "io": IOA, "slot": "calculation",
 "q": "A study has a 20 percent chance of a type II error. What is its statistical power?",
 "opts": [
  ["80 percent",
   "Correct: power is 1 minus the type II error probability, so 1 minus 0.20 is 0.80."],
  ["20 percent",
   "That is the type II error probability itself; power is its complement."],
  ["95 percent",
   "That is the level used for confidence intervals, not a value derived from a 20 percent type II error probability."],
  ["5 percent",
   "That is the usual threshold for the type I error and has no place in calculating power from the type II error."]],
 "c": 0, "cite": c(16)},

{"topic": "Statistical power", "io": IOA, "slot": "calculation",
 "q": "A study has a statistical power of 0.90. What is its probability of a type II error?",
 "opts": [
  ["0.10",
   "Correct: power is 1 minus the type II error probability, so the probability of a type II error is 1 minus 0.90, or 0.10."],
  ["0.90",
   "That is the power itself, the chance of detecting a real difference, not the chance of missing one."],
  ["0.05",
   "That is the conventional threshold for the type I error and cannot be read from a power of 0.90."],
  ["0.01",
   "Nothing in a power of 0.90 gives a type II error probability of 0.01; the two must sum to one."]],
 "c": 0, "cite": c(16)},

{"topic": "Statistical power", "io": IOA, "slot": "application",
 "q": "A small trial of a drug that truly works reports a p value of 0.30. Which explanation is most plausible?",
 "opts": [
  ["Too little power to detect the difference",
   "Correct: a small study has a low probability of detecting a real difference, so a false negative (type II error) is likely."],
  ["The drug has been proven ineffective",
   "A non-significant result cannot prove there is no effect; in a small study it often reflects insufficient power."],
  ["A type I error has occurred",
   "A type I error means a difference was claimed that does not exist, whereas here a real difference was missed."],
  ["The null hypothesis has been proven true",
   "A non-significant result fails to reject the null hypothesis but does not prove it true."]],
 "c": 0, "cite": c(16)},

# ------------------------------------------------------- Multiple comparisons
{"topic": "Multiple comparisons", "io": IOA, "slot": "principle",
 "q": "What can happen when many comparisons are made in one study?",
 "opts": [
  ["Some may look significant by chance",
   "Correct: the strength of statistical tests depends on the number of questions asked and how focused they are, and it is not always possible to know how many comparisons were made."],
  ["Every p value becomes more accurate",
   "More comparisons do not improve any p value; they raise the number of chances for a spurious significant result."],
  ["Type II errors become impossible",
   "The number of comparisons has no such effect, and missing a real difference remains possible."],
  ["Confidence intervals become narrower",
   "Interval width depends on precision of the estimate, not on how many other comparisons were made."]],
 "c": 0, "cite": c(17)},

{"topic": "Multiple comparisons", "io": IOA, "slot": "calculation",
 "q": "A study makes 60 comparisons between groups, none reflecting a true difference. If significance is set at a p value of 0.05, about how many will appear significant by chance?",
 "opts": [
  ["3",
   "Correct: a p value of 0.05 corresponds to a chance of 1 in 20, and 60 divided by 20 is 3."],
  ["6",
   "That doubles the expected number; 60 comparisons at 1 in 20 gives 3 by chance alone."],
  ["30",
   "That treats half of the comparisons as significant, whereas a threshold of 0.05 corresponds to only 1 in 20."],
  ["0",
   "With none of the differences real, the only significant results are chance ones, and at 1 in 20 about 3 are expected among 60."]],
 "c": 0, "cite": c(17)},

{"topic": "Multiple comparisons", "io": IOA, "slot": "calculation",
 "q": "A study makes 200 comparisons, none reflecting a true difference. If significance is set at a p value of 0.01, about how many will appear significant by chance?",
 "opts": [
  ["2",
   "Correct: a p value of 0.01 corresponds to a chance of 1 in 100, and 200 divided by 100 is 2."],
  ["10",
   "That uses the 0.05 threshold (1 in 20) rather than 0.01; at 1 in 100 the expected number among 200 is 2."],
  ["20",
   "That applies a 1 in 10 chance, but a p value of 0.01 corresponds to 1 in 100."],
  ["0",
   "Even with no real differences, chance alone yields significant results at the stated rate, about 2 among 200 at 1 in 100."]],
 "c": 0, "cite": c(17)},

{"topic": "Multiple comparisons", "io": IOA, "slot": "discrimination",
 "q": "Which practice makes multiple comparisons misleading?",
 "opts": [
  ["Picking interesting results after analysis",
   "Correct: selecting the interesting comparisons once the analysis is done, and then building the article around them without reporting how many questions were examined, distorts the data."],
  ["Naming the primary question beforehand",
   "Stating the primary question in advance protects against this distortion, because the main comparison is fixed before the data are seen."],
  ["Reporting every comparison that was made",
   "Reporting all comparisons lets readers judge how many chance findings to expect; hiding them is what misleads."],
  ["Limiting the study to a few focused questions",
   "Fewer, focused questions give stronger statistical tests, since the strength of tests depends on the number of questions asked."]],
 "c": 0, "cite": c(18)},

# ------------------------------------------------------ Multivariable modeling
{"topic": "Multivariable modeling", "io": IOA, "slot": "definition",
 "q": "What does multivariable modeling examine?",
 "opts": [
  ["The effect of two or more variables together",
   "Correct: it uses a mathematical construct, an equation, to examine variables together, including their combined effect in predicting a clinical event."],
  ["The effect of a single variable in isolation",
   "A single variable alone is what a simple comparison examines; multivariable modeling looks at two or more together."],
  ["The order in which patients enter a study",
   "Order of entry is a matter of enrollment and randomization, not what a multivariable model analyzes."],
  ["The reliability of one repeated measurement",
   "Reliability concerns getting similar results on repetition; a multivariable model examines several variables and an outcome."]],
 "c": 0, "cite": c(19)},

{"topic": "Multivariable modeling", "io": IOA, "slot": "principle",
 "q": "In multivariable modeling, what does taking other variables into account allow?",
 "opts": [
  ["Isolating one variable's effect on the outcome",
   "Correct: it looks at the effect of one variable on the outcome while accounting for other variables such as confounders or effect modifiers."],
  ["Removing all random error from the estimate",
   "Modeling does not remove random error, which is estimated statistically and never eliminated."],
  ["Proving the outcome is caused by the variable",
   "Adjustment reduces the influence of measured variables but cannot prove cause; unknown bias and unmeasured confounding remain."],
  ["Eliminating the need for a comparison group",
   "A comparison is still needed; modeling adjusts for other variables within the comparison rather than replacing it."]],
 "c": 0, "cite": c(19)},

{"topic": "Multivariable modeling", "io": IOA, "slot": "principle",
 "q": "Which variables are considered first for inclusion in a model?",
 "opts": [
  ["Those most strongly associated with the outcome",
   "Correct: after identifying variables related to the outcome, including confounders and effect modifiers, those with the strongest association are considered for inclusion."],
  ["Those least associated with the outcome",
   "Weakly associated variables add little; the strongest associations are the ones considered for inclusion."],
  ["Those easiest to measure in every patient",
   "Convenience of measurement does not decide inclusion, which is guided by the strength of association with the outcome."],
  ["Those with the most missing data",
   "Variables with extensive missing data are a problem for a model and are not chosen for that reason."]],
 "c": 0, "cite": c(20)},

{"topic": "Multivariable modeling", "io": IOA, "slot": "discrimination",
 "q": "Which effect is a multivariable model poor at identifying?",
 "opts": [
  ["Effect modification",
   "Correct: among the limitations of such models is being poor at identifying effect modification, and they may also omit rare variables with a strong relationship to the outcome."],
  ["Confounding",
   "Taking confounders into account is exactly what a multivariable model is designed to do."],
  ["Random error",
   "Random error occurs by chance and is accounted for through the p values, not by the modeling process itself."],
  ["Recall bias",
   "Recall bias is difficulty remembering exposures and cannot be corrected by modeling, but it is not what the model's limitation concerns."]],
 "c": 0, "cite": c(21)},

{"topic": "Multivariable modeling", "io": IOA, "slot": "principle",
 "q": "On what does the validity of a multivariable model depend?",
 "opts": [
  ["Whether its assumptions about the data hold",
   "Correct: its validity rests on assumptions about the data, which commonly include assumptions such as normality and independence of errors."],
  ["How many patients were recruited",
   "The number recruited affects precision and power, whereas the model's validity rests on its assumptions about the data."],
  ["Whether every variable reaches significance",
   "A model does not require every variable to be significant; its validity rests on assumptions about the data."],
  ["How many variables are entered",
   "Adding more variables does not secure validity; the assumptions about the data are what must hold."]],
 "c": 0, "cite": c(21)},

# ---------------------------------------------------------- Clinical importance
{"topic": "Clinical importance", "io": IOB, "slot": "principle",
 "q": "Which statement about statistical and clinical significance is true?",
 "opts": [
  ["A significant result may lack clinical relevance",
   "Correct: differences can have a p value below 0.0001 and still have no relevance to clinical practice."],
  ["A significant result is always clinically important",
   "Statistical significance does not imply clinical significance; the size of the difference and its relevance to patients decide importance."],
  ["A clinically important result is always significant",
   "An important difference can fail to reach statistical significance, for example in a small study with low power."],
  ["The two always agree in a large sample",
   "A large sample makes even small differences statistically significant, which often separates statistical from clinical significance."]],
 "c": 0, "cite": c(22)},

{"topic": "Clinical importance", "io": IOB, "slot": "interpretation",
 "q": "A difference has a p value below 0.0001. What follows about its relevance to clinical practice?",
 "opts": [
  ["Nothing; it may have no relevance",
   "Correct: the p value speaks to chance, not to importance, so a difference with a p value below 0.0001 can still be irrelevant to practice."],
  ["It must be highly relevant to practice",
   "A very small p value does not make a difference clinically relevant; that depends on its size and meaning for patients."],
  ["It is relevant only if the sample was small",
   "In a small sample a difference is harder to make significant, and sample size does not determine clinical relevance."],
  ["It is irrelevant because the p value is too low",
   "A low p value does not make a difference irrelevant either; it simply gives no information about clinical importance."]],
 "c": 0, "cite": c(22)},

{"topic": "Clinical importance", "io": IOB, "slot": "application",
 "q": "A trial of 40,000 patients finds a drug lowers systolic blood pressure by 1 millimeter of mercury, with a p value below 0.0001. What is the best interpretation?",
 "opts": [
  ["Statistically significant but of doubtful clinical importance",
   "Correct: small differences can be statistically significant, especially in very large samples, yet a fall this small is unlikely to matter to patients."],
  ["Clinically important but not statistically significant",
   "A p value below 0.0001 is strongly statistically significant, and a 1 millimeter fall is unlikely to be clinically important."],
  ["Neither statistically nor clinically significant",
   "The p value is far below 0.05, so the result is statistically significant."],
  ["Both statistically and clinically important",
   "The result is statistically significant, but a 1 millimeter fall is small; larger differences tend to be more clinically significant."]],
 "c": 0, "cite": c(22)},

{"topic": "Clinical importance", "io": IOB, "slot": "application",
 "q": "A small trial finds a 30 percent lower death rate with a p value of 0.12. What is the best interpretation?",
 "opts": [
  ["Possibly important but not statistically significant",
   "Correct: the size of the difference could matter clinically, but a p value of 0.12 does not reach 0.05, and a small study may simply lack power."],
  ["Statistically significant and clinically important",
   "A p value of 0.12 is above the accepted 0.05 threshold, so the result is not statistically significant."],
  ["Statistically significant but clinically trivial",
   "The result is not statistically significant, and a 30 percent lower death rate would not be trivial if real."],
  ["Proof that the treatment has no effect",
   "A non-significant result cannot prove no effect, particularly in a small study at risk of a type II error."]],
 "c": 0, "cite": c(22)},

{"topic": "Clinical importance", "io": IOB, "slot": "discrimination",
 "q": "Which question addresses clinical rather than statistical significance?",
 "opts": [
  ["Would it matter to the patient?",
   "Correct: clinical significance is about relevance to practice and patients, whereas p values and intervals address chance."],
  ["Is the p value below 0.05?",
   "That is a test of statistical significance, whether chance is an unlikely explanation."],
  ["Does the interval exclude no effect?",
   "That is also a statistical question, since an interval excluding the value of no effect indicates statistical significance."],
  ["Was the null hypothesis rejected?",
   "Rejecting the null hypothesis is a statistical decision that says nothing about whether the difference matters."]],
 "c": 0, "cite": c(22)},

{"topic": "Clinical importance", "io": IOB, "slot": "principle",
 "q": "Which differences tend to be more clinically significant?",
 "opts": [
  ["Larger differences",
   "Correct, although small differences can still be statistically significant, so size and p value must be judged separately."],
  ["Smaller differences",
   "Smaller differences tend to matter less clinically, even though they can still be statistically significant."],
  ["Differences from smaller samples",
   "Sample size affects statistical significance and precision, not how much the difference matters clinically."],
  ["Differences with lower p values",
   "A lower p value shows only that chance is less likely, not that the difference is larger or more important."]],
 "c": 0, "cite": c(22)},

{"topic": "Clinical importance", "io": IOB, "slot": "discrimination",
 "q": "Which pairing best contrasts statistical and clinical significance?",
 "opts": [
  ["Chance versus relevance to patients",
   "Correct: statistical significance asks how likely chance is as an explanation, while clinical significance asks whether the difference matters to practice."],
  ["Random error versus systematic error",
   "That contrasts two sources of error in a study, not the two kinds of significance."],
  ["Precision versus accuracy of measurement",
   "Precision and accuracy describe measurement quality, not the difference between statistical and clinical significance."],
  ["Validity versus reliability of a test",
   "Those are properties of measurement, not the two kinds of significance."]],
 "c": 0, "cite": c(5)},

# -------------------------------------------------------------- Types of cause
{"topic": "Types of cause", "io": IOC, "slot": "definition",
 "q": "How is causality defined?",
 "opts": [
  ["A factor that helps produce the outcome",
   "Correct: causality exists if a factor produces or contributes to the production of a specified outcome, which allows for multiple causes."],
  ["Any factor associated with an outcome",
   "Association is not causation; a non-causal association can be statistically significant and still have no causal relationship."],
  ["Any factor that occurs before an outcome",
   "Preceding an outcome is only one criterion (temporality) and does not establish that the factor produces it."],
  ["Any factor with a significant p value",
   "A significant p value shows chance is unlikely as an explanation, not that the factor produces the outcome."]],
 "c": 0, "cite": c(23)},

{"topic": "Types of cause", "io": IOC, "slot": "principle",
 "q": "Koch's postulates for infectious disease illustrate which model of causation?",
 "opts": [
  ["A single cause",
   "Correct: the organism must be present in every case, isolated and grown in pure culture, cause a specific disease and be recovered from an inoculated animal."],
  ["A web of causation",
   "A web of causation involves many interacting factors, whereas Koch's postulates link one organism to one disease."],
  ["Multiple interacting causes",
   "Koch's postulates assign disease to one specific organism rather than to several interacting causes."],
  ["An indirect chain of causes",
   "An indirect chain runs through intervening variables, which is not what Koch's postulates describe."]],
 "c": 0, "cite": c(25)},

{"topic": "Types of cause", "io": IOC, "slot": "definition",
 "q": "What defines a sufficient cause?",
 "opts": [
  ["If it is present, the disease always occurs",
   "Correct: a sufficient cause precedes the disease and guarantees it whenever present."],
  ["If it is absent, the disease cannot occur",
   "That defines a NECESSARY cause, which must be present for the disease to occur."],
  ["If it is present, the disease sometimes occurs",
   "That describes a risk factor, which increases the probability of disease without guaranteeing it."],
  ["If it is absent, the disease occurs less often",
   "That describes a risk factor, which is neither sufficient nor necessary."]],
 "c": 0, "cite": c(26)},

{"topic": "Types of cause", "io": IOC, "slot": "application",
 "q": "Disease X never occurs without exposure Y, but many exposed people stay healthy. What kind of cause is Y?",
 "opts": [
  ["Necessary but not sufficient",
   "Correct: the disease cannot occur if Y is absent (necessary), but Y being present does not guarantee disease (not sufficient)."],
  ["Sufficient but not necessary",
   "A sufficient cause would always produce disease when present, but here many exposed people stay healthy."],
  ["Both necessary and sufficient",
   "Y would have to always cause disease when present to be sufficient, which the healthy exposed people rule out."],
  ["Neither necessary nor sufficient",
   "The disease never occurs without Y, which makes Y necessary rather than merely a risk factor."]],
 "c": 0, "cite": c(26)},

{"topic": "Types of cause", "io": IOC, "slot": "application",
 "q": "Poverty raises tuberculosis risk partly through crowded housing and malnutrition. What are those two factors called?",
 "opts": [
  ["Intervening variables",
   "Correct: in indirect causality one factor acts through intervening variables that are in turn directly causal."],
  ["Sufficient causes",
   "A sufficient cause would always produce disease when present, which crowded housing and malnutrition do not."],
  ["Necessary causes",
   "A necessary cause must be present for disease to occur; here they are steps on the pathway from poverty."],
  ["Confounders",
   "A confounder is a separate factor associated with both exposure and outcome; these lie on the causal pathway itself."]],
 "c": 0, "cite": c(27)},

{"topic": "Types of cause", "io": IOC, "slot": "application",
 "q": "Ice cream sales and drowning deaths both rise in summer, and the link is statistically significant. What does this represent?",
 "opts": [
  ["A non-causal association",
   "Correct: the relationship is statistically significant yet no causal relationship exists, because a shared factor such as summer weather drives both."],
  ["A sufficient cause",
   "A sufficient cause would always lead to the outcome, which ice cream sales do not do for drowning."],
  ["A dose-response relationship",
   "A dose-response relationship is a criterion for cause showing higher exposure leading to higher disease rates, which does not establish a cause here."],
  ["A necessary cause",
   "Drowning can occur without ice cream sales, so ice cream cannot be a necessary cause."]],
 "c": 0, "cite": c(28)},

# --------------------------------------------------------- Criteria for causation
{"topic": "Criteria for causation", "io": IOC, "slot": "principle",
 "q": "Before concluding that an association is causal, what must be excluded?",
 "opts": [
  ["Bias, chance and confounding",
   "Correct, taken in that order: bias in selection or measurement, then chance, then confounding, and only if none explains it is a cause likely."],
  ["Dose-response, reversibility and specificity",
   "Those are criteria that SUPPORT a causal relationship, not alternative explanations to be excluded."],
  ["Temporality, strength and analogy",
   "Those are also criteria supporting cause; the explanations to exclude are bias, chance and confounding."],
  ["Precision, power and validity",
   "Those are properties of a study rather than the alternative explanations an association must be freed of."]],
 "c": 0, "cite": c(29)},

{"topic": "Criteria for causation", "io": IOC, "slot": "definition",
 "q": "Which criterion requires that the cause precede the effect?",
 "opts": [
  ["Temporality",
   "Correct: the cause must come before the effect, and a non-causal association can arise when the temporal relationship is wrong."],
  ["Consistency",
   "Consistency means the findings are replicable in other studies, not that the cause comes first."],
  ["Specificity",
   "Specificity means one cause leads to one effect and says nothing about timing."],
  ["Analogy",
   "Analogy means a similar cause and effect pattern exists for a similar exposure and disease."]],
 "c": 0, "cite": c(30)},

{"topic": "Criteria for causation", "io": IOC, "slot": "definition",
 "q": "How is strength of association judged in a causal assessment?",
 "opts": [
  ["By the size of the relative risk",
   "Correct: a large relative risk is a strong association, which makes a causal relationship more likely."],
  ["By how many studies report it",
   "That describes consistency, meaning findings are replicable in other studies, rather than strength."],
  ["By whether a mechanism is known",
   "That is biologic plausibility, whether the relationship makes sense biologically."],
  ["By whether exposure can be reversed",
   "That is reversibility, in which decreased exposure leads to less disease."]],
 "c": 0, "cite": c(30)},

{"topic": "Criteria for causation", "io": IOC, "slot": "application",
 "q": "Lung cancer rates rise with the number of cigarettes smoked each day. Which criterion does this satisfy?",
 "opts": [
  ["Dose-response",
   "Correct: a larger exposure leads to a higher rate of disease."],
  ["Reversibility",
   "Reversibility would be shown by less disease after exposure is reduced or stopped."],
  ["Specificity",
   "Specificity means one cause leads to one effect, which a rise in rate with exposure does not show."],
  ["Consistency",
   "Consistency requires the finding to be replicated in other studies, which the stem does not describe."]],
 "c": 0, "cite": c(30)},

{"topic": "Criteria for causation", "io": IOC, "slot": "application",
 "q": "Lung cancer risk falls in people who stop smoking. Which criterion does this satisfy?",
 "opts": [
  ["Reversibility",
   "Correct: decreased exposure is followed by less disease, which is the reversibility criterion and supports a causal relationship."],
  ["Dose-response",
   "Dose-response describes higher exposure producing more disease, whereas this describes exposure being reduced."],
  ["Temporality",
   "Temporality requires only that the cause come before the effect; it does not describe risk falling after quitting."],
  ["Analogy",
   "Analogy compares with a similar exposure and disease elsewhere, which the stem does not describe."]],
 "c": 0, "cite": c(30)},

{"topic": "Criteria for causation", "io": IOC, "slot": "application",
 "q": "Several studies in different populations find the same association. Which criterion does this satisfy?",
 "opts": [
  ["Consistency",
   "Correct: findings that are replicable in other studies make a causal relationship more likely."],
  ["Biologic plausibility",
   "Biologic plausibility asks whether the relationship makes sense biologically, not whether other studies agree."],
  ["Specificity",
   "Specificity is one cause leading to one effect, which replication alone does not show."],
  ["Temporality",
   "Temporality concerns whether the cause precedes the effect and is not shown by repeated findings."]],
 "c": 0, "cite": c(30)},

{"topic": "Criteria for causation", "io": IOC, "slot": "application",
 "q": "A known mechanism explains how an exposure could injure tissue. Which criterion does this satisfy?",
 "opts": [
  ["Biologic plausibility",
   "Correct: the relationship makes sense biologically, which strengthens the case that it is causal."],
  ["Consistency",
   "Consistency requires replication in other studies rather than a mechanism."],
  ["Analogy",
   "Analogy requires a similar cause and effect pattern for a similar exposure and disease, not a mechanism for this one."],
  ["Strength of association",
   "Strength refers to a large relative risk, which the stem does not give."]],
 "c": 0, "cite": c(30)},

{"topic": "Criteria for causation", "io": IOC, "slot": "definition",
 "q": "What does the specificity criterion state?",
 "opts": [
  ["One cause leads to one effect",
   "Correct, though it is a demanding criterion, because a single exposure often produces several effects and a cause need not be specific to be real."],
  ["One effect can have many causes",
   "That describes multiple causes or a web of causation, not the specificity criterion."],
  ["Larger exposure leads to more disease",
   "That is the dose-response criterion, in which a larger exposure leads to a higher rate of disease."],
  ["Less exposure leads to less disease",
   "That is the reversibility criterion, in which decreased exposure leads to less disease."]],
 "c": 0, "cite": c(30)},

{"topic": "Criteria for causation", "io": IOC, "slot": "principle",
 "q": "What happens to the evidence for causation as more criteria are met?",
 "opts": [
  ["The case for a cause grows stronger",
   "Correct: the more criteria for causation that are met, the stronger the case, though causation cannot be proved beyond all doubt."],
  ["Causation is proven beyond doubt",
   "Meeting many criteria strengthens the case but does not prove cause with certainty."],
  ["The case for a cause grows weaker",
   "Each additional criterion met adds support for a causal relationship rather than reducing it."],
  ["The case for a cause is unchanged",
   "The criteria are cumulative evidence, so meeting more of them strengthens the case."]],
 "c": 0, "cite": c(33)},

# ----------------------------------------------------------- Pitfalls in causal research
{"topic": "Causal pitfalls", "io": IOC, "slot": "definition",
 "q": "Which bias arises from difficulty remembering past exposures?",
 "opts": [
  ["Recall bias",
   "Correct: participants' difficulty in remembering distorts the reported exposure or history."],
  ["Selection bias",
   "Selection bias concerns how people get into the study, such as poor randomization."],
  ["Measurement bias",
   "Measurement bias comes from operator error, calibration or similar problems with the measurement itself."],
  ["Publication bias",
   "Publication bias concerns which studies get published, not how participants recall exposures."]],
 "c": 0, "cite": c(34)},

{"topic": "Causal pitfalls", "io": IOC, "slot": "principle",
 "q": "How is random error accounted for in a study?",
 "opts": [
  ["Through the p values used",
   "Correct: random error occurs by chance and is accounted for through the p values, whereas bias and confounding require design and analysis."],
  ["By blinding the participants",
   "Blinding protects against performance and measurement bias, not random error, which is handled statistically."],
  ["By matching cases with controls",
   "Matching addresses confounding, not random error, which arises by chance."],
  ["By excluding older participants",
   "Excluding a group would change who is studied and would not account for chance variation."]],
 "c": 0, "cite": c(34)},

# ------------------------------------------------------ Study design and cause
{"topic": "Design and causation", "io": IOD, "slot": "discrimination",
 "q": "Which design gives the strongest evidence for causation?",
 "opts": [
  ["Randomized controlled trial",
   "Correct, listed with systematic reviews at the top of the hierarchy of designs, well above cohort, case-control, cross-sectional and case series designs."],
  ["Case-control study",
   "Case-control studies sit lower in the hierarchy of designs, below randomized trials and cohort studies."],
  ["Cross-sectional study",
   "Cross-sectional studies rank low because exposure and outcome are measured together."],
  ["Case series",
   "A case series ranks near the bottom of the hierarchy of designs, above only a case report."]],
 "c": 0, "cite": c(35)},

{"topic": "Design and causation", "io": IOD, "slot": "discrimination",
 "q": "Which design provides the weakest evidence for causation?",
 "opts": [
  ["Case report",
   "Correct: it sits at the bottom of the hierarchy of designs, below case series and cross-sectional designs."],
  ["Cohort study",
   "Cohort studies rank well above the bottom, below trials but above case-control studies."],
  ["Non-randomized trial",
   "A non-randomized trial sits in the upper part of the hierarchy, above cohort and case-control studies and well above the weakest designs."],
  ["Case-control study",
   "Case-control studies rank above time series, cross-sectional studies, case series and case reports."]],
 "c": 0, "cite": c(35)},

{"topic": "Design and causation", "io": IOD, "slot": "discrimination",
 "q": "Which design ranks above a case-control study for causal evidence?",
 "opts": [
  ["Cohort study",
   "Correct: in the hierarchy of designs for causal evidence a cohort study sits above a case-control study, which looks backward from the outcome."],
  ["Cross-sectional study",
   "A cross-sectional study ranks below a case-control study, because exposure and outcome are measured together."],
  ["Case series",
   "A case series ranks below a case-control study, since it describes patients without any comparison group."],
  ["Case report",
   "A case report sits at the very bottom of the hierarchy of designs for causal evidence, below a case-control study."]],
 "c": 0, "cite": c(35)},

{"topic": "Design and causation", "io": IOD, "slot": "principle",
 "q": "Why does random assignment strengthen causal conclusions?",
 "opts": [
  ["It balances confounders between the groups",
   "Correct: random assignment spreads confounding factors evenly, although random error remains and is still accounted for through p values."],
  ["It removes all random error from results",
   "Random error is never eliminated; it is estimated statistically and reflected in the p values."],
  ["It guarantees a significant result",
   "Random assignment does not guarantee statistical significance, which depends on the true difference and the study's power."],
  ["It makes measurements more reliable",
   "Reliability of measurement is a separate property that depends on the measuring method, not on how groups are assigned."]],
 "c": 0, "cite": c(35)},

{"topic": "Design and causation", "io": IOD, "slot": "principle",
 "q": "Why is a cross-sectional study weak evidence for causation?",
 "opts": [
  ["It cannot show which came first",
   "Correct: exposure and outcome are measured at the same time, so the temporal sequence, an essential criterion for cause, cannot be established."],
  ["It always has too few participants",
   "A cross-sectional study can have many participants; its weakness is timing, not size."],
  ["It does not measure the outcome",
   "It measures both exposure and outcome, but together at a single point in time."],
  ["It cannot detect any association",
   "It can detect associations; it simply cannot show that the exposure came before the outcome."]],
 "c": 0, "cite": c(35)},

{"topic": "Design and causation", "io": IOD, "slot": "application",
 "q": "A well-designed randomized trial finds no effect of an exposure on an outcome. What does that provide?",
 "opts": [
  ["Strong evidence against a causal link",
   "Correct, because a strong design combined with a finding of no effect gives strong evidence against cause, provided the trial had adequate power."],
  ["Strong evidence for a causal link",
   "A finding of no effect argues against cause, however strong the design."],
  ["Weak evidence against a causal link",
   "Design strength matters: a randomized trial is at the top of the hierarchy, so its evidence is strong, not weak."],
  ["No evidence either way",
   "A strong design finding no effect is informative, giving strong evidence against a causal link."]],
 "c": 0, "cite": c(35)},

{"topic": "Design and causation", "io": IOD, "slot": "discrimination",
 "q": "Which finding argues against a causal relationship?",
 "opts": [
  ["The disease appears before the exposure",
   "Correct: an incorrect temporal sequence argues against cause, as do no dose-response, no reversibility, no specificity, no analogy or no biologic plausibility."],
  ["Risk rises as exposure rises",
   "A dose-response relationship, higher exposure with more disease, argues FOR a causal relationship rather than against it."],
  ["Several studies replicate the association",
   "Consistency, findings replicated in other studies, argues FOR a causal relationship rather than against it."],
  ["A plausible biologic mechanism exists",
   "Biologic plausibility, a relationship that makes sense biologically, argues FOR a causal relationship rather than against it."]],
 "c": 0, "cite": c(35)},

]
