"""Microbiology Exam 1 — all six lectures, weighted by Webster's own review.

WEIGHTING comes from her in-class Exam 1 review (11 September 2026, the last
seventeen minutes of the Nonspecific Immunity lecture), where she walked her
objectives for the three lectures she taught and graded them. Her "know cold"
items carry the most questions here; her two explicit skips carry one each.
She did NOT review Lectures 3, 4 and 6 and said so, so those are weighted
evenly rather than lightly — silence is not a de-emphasis. Both calculations
she confirmed as examinable are included: the therapeutic index and the
decimal reduction.

ONE QUESTION PER QUESTION. Her spoken style is to stack several demands in
one breath — "What causes fever? Why is fever good? Why is fever bad?" — and
an earlier version of this pool copied that into the stems. That is how she
teaches, not how an exam item should be written: a stacked stem tests three
things at once, so a student who knows two of them still gets it wrong and
learns nothing about which part they missed. Every stem here asks exactly
one thing. Where she stacked, the parts are split into separate questions,
which is also why this pool is longer than the objectives alone would need.

What IS kept from how she asks:
  - reasoning FORWARD from a structure to what follows from it, rather than
    reciting the structure (she refused to let the class recite the Gram
    wall and made them go on to what would kill the organism);
  - mechanism rather than a list, where she asked for the mechanism;
  - the discriminations she corrects herself on, because those are the ones
    she expects to be got wrong.

Stems are self-contained: the review sets the weighting, the DECKS supply
every fact, and nothing here cites a lecture or a lecturer.
"""

L1 = "Lecture 1  Dr. Webster -  Review of General Microbiology .pptx"
L2 = "Lecture Number 2  - Antibiotics and Resistance - Dr. Webster.pptx"
L3 = "PAJ5200.Microbe-human-interactions(1).pptx"
L4 = "PAJ5200.Transmission_of_microbes-2.pptx"
L5 = "Lecture 5  Dr. Webster Nonspecific Immunity.pptx"
L6 = "PAJ5200.Specific_Immunity-2.pptx"

POOL = [

# ─────────── Lecture 1 — Review of General Microbiology (15) ───────────

dict(topic="General Microbiology", io="1.4 — Gram-positive versus Gram-negative",
  q="A Gram-positive organism is isolated from a wound. Which agent is it especially vulnerable to?",
  opts=[["Nothing that acts on the wall", "The exposed peptidoglycan makes wall-active agents more effective here rather than less."],
        ["Polymyxin", "Polymyxin disrupts the outer membrane, which Gram-positive organisms do not have, so there is nothing for it to act on."],
        ["An aminoglycoside alone", "Aminoglycosides act at the ribosome and are not the agent whose effect follows directly from a Gram-positive wall."],
        ["Lysozyme", "Correct. Its thick peptidoglycan is the enzyme's substrate and lies exposed as the outermost layer, with no outer membrane covering it."]],
  c=3, cite=L1 + ", Slides 24-29"),

dict(topic="General Microbiology", io="1.4 — Gram-positive versus Gram-negative",
  q="Which wall feature makes Gram-negative organisms resistant to many agents that kill Gram-positive ones?",
  opts=[["An outer membrane", "Correct. It acts as a permeability barrier, excluding large and hydrophobic molecules before they can reach the peptidoglycan beneath."],
        ["A thicker peptidoglycan layer", "Their peptidoglycan is thinner than a Gram-positive organism's, and thickness confers no permeability barrier in any case."],
        ["Teichoic acid", "Teichoic acid runs through the Gram-positive wall and is absent from the Gram-negative envelope."],
        ["A capsule", "A capsule resists phagocytosis rather than excluding drugs, and it is not restricted to Gram-negative organisms."]],
  c=0, cite=L1 + ", Slides 26-29"),

dict(topic="General Microbiology", io="1.4 — Gram-positive versus Gram-negative",
  q="What is released from a Gram-negative organism when the cell lyses?",
  opts=[["Exotoxin", "An exotoxin is a protein actively secreted by a living cell rather than a wall component freed on lysis."],
        ["Lipid A", "Correct. Lipid A is the toxic portion of the lipopolysaccharide built into the outer membrane, so it only reaches the host when the cell breaks apart."],
        ["Lysozyme", "Lysozyme is a host enzyme found in tears and secretions, not a bacterial product."],
        ["Teichoic acid", "Teichoic acid belongs to the Gram-positive wall and is not the toxic component released here."]],
  c=1, cite=L1 + ", Slides 26-29"),

dict(topic="General Microbiology", io="1.2 — Types of infectious pathogens",
  q="What makes mycoplasmas unusual among bacteria?",
  opts=[["They have two cell walls", "No bacterium has two walls, and what distinguishes mycoplasmas is having none."],
        ["They have no ribosomes", "No bacterium lacks ribosomes; they would be unable to make protein at all."],
        ["They have no cell wall", "Correct. The absence of peptidoglycan is the single feature from which everything else about them follows."],
        ["They have no genetic material", "Every cellular organism carries deoxyribonucleic acid, mycoplasmas included."]],
  c=2, cite=L1 + ", Slides 14-18"),

dict(topic="General Microbiology", io="1.2 — Types of infectious pathogens",
  q="Because mycoplasmas lack a cell wall, which drug class is useless against them?",
  opts=[["The macrolides", "Macrolides act at the bacterial ribosome, which mycoplasmas do possess, so they remain effective."],
        ["The penicillins", "Correct. A penicillin blocks crosslinking of peptidoglycan, so an organism that builds no peptidoglycan offers the drug no target at all."],
        ["The tetracyclines", "Tetracyclines also act at the ribosome and are among the agents used against these organisms."],
        ["The fluoroquinolones", "Fluoroquinolones act on the enzymes managing bacterial deoxyribonucleic acid rather than on the wall."]],
  c=1, cite=L1 + ", Slides 14-18"),

dict(topic="General Microbiology", io="1.3 — Bacterial structures that enhance pathogenicity",
  q="Which structure allows a bacterium to survive heat, drying and disinfectants for years?",
  opts=[["The plasmid", "A plasmid is extrachromosomal genetic material rather than a protective structure."],
        ["The capsule", "A capsule resists phagocytosis but is destroyed by heat and disinfectants along with the rest of the cell."],
        ["The flagellum", "The flagellum provides motility and confers no resistance to physical or chemical stress."],
        ["The endospore", "Correct. It is a dormant, dehydrated form with a tough protective coat that withstands conditions which kill the vegetative cell."]],
  c=3, cite=L1 + ", Slides 30-36"),

dict(topic="General Microbiology", io="1.3 — Bacterial structures that enhance pathogenicity",
  q="Which structure allows a bacterium to resist being engulfed by a phagocyte?",
  opts=[["The capsule", "Correct. Its slippery polysaccharide layer prevents the phagocyte from gripping the surface, so the cell cannot be taken up."],
        ["The endospore", "Sporulation is a response to environmental hardship rather than a defense against phagocytosis."],
        ["Fimbriae", "Fimbriae mediate attachment to host tissue and do nothing to prevent engulfment."],
        ["The ribosome", "The ribosome synthesizes protein and has no role at the cell surface."]],
  c=0, cite=L1 + ", Slides 30-36"),

dict(topic="General Microbiology", io="1.5 — Identification methods and culture media",
  q="What does calling a medium 'selective' mean?",
  opts=[["It suppresses the growth of unwanted organisms", "Correct. Something in the medium, such as a high salt concentration, prevents organisms other than the ones sought from growing at all."],
        ["It shows visible differences between organisms", "That describes a differential medium, which lets everything grow but makes the colonies look different."],
        ["It supplies extra nutrients for fastidious organisms", "That describes an enriched medium, which supports demanding organisms rather than excluding others."],
        ["It maintains a constant incubation temperature", "Temperature is an incubation condition rather than a property of the medium itself."]],
  c=0, cite=L1 + ", Slides 43-44"),

dict(topic="General Microbiology", io="1.5 — Identification methods and culture media",
  q="Which three results are read from blood agar?",
  opts=[["Growth, no growth and partial growth", "A simple growth reading would make the medium selective; blood agar is differential because it shows how the blood is changed."],
        ["Acid, gas and no change", "Those are read from a carbohydrate fermentation medium rather than from blood agar."],
        ["Coagulase, catalase and oxidase", "Those are separate biochemical tests performed on an isolate rather than readings from a plate."],
        ["Gamma, alpha and beta hemolysis", "Correct. Each organism digests the hemoglobin to a different degree — none, partial, or complete — and the plate shows that difference directly."]],
  c=3, cite=L1 + ", Slides 43-44"),

dict(topic="General Microbiology", io="1.6 — The bacterial growth curve",
  q="Bacterial growth refers to an increase in what?",
  opts=[["Cell number", "Correct. The individual cells stay much the same size; what rises is how many of them there are, through repeated binary fission."],
        ["Cell size", "Cells enlarge only slightly before dividing, and growth is defined by the number of cells rather than their dimensions."],
        ["Colony diameter", "Colony spread on a plate reflects motility and available nutrient rather than defining growth itself."],
        ["Genome size", "The genome is copied faithfully at each division rather than enlarging."]],
  c=0, cite=L1 + ", Slides 37-40"),

dict(topic="General Microbiology", io="1.6 — The bacterial growth curve",
  q="Why does a bacterial population rise exponentially rather than arithmetically?",
  opts=[["Each division doubles the population", "Correct. Binary fission turns one cell into two, so the count goes 2, 4, 8, 16 rather than climbing by a fixed amount each generation."],
        ["Each cell grows at a constant rate", "Constant enlargement of individual cells would give a steady arithmetic increase, not a doubling curve."],
        ["Nutrients are consumed at a constant rate", "Nutrient consumption limits growth in later phases rather than explaining the shape of the rise."],
        ["Cells divide faster as the population grows", "Division rate is roughly constant during log phase; it is the doubling that makes the curve exponential."]],
  c=0, cite=L1 + ", Slides 37-40"),

dict(topic="General Microbiology", io="1.6 — The bacterial growth curve",
  q="In which phase of the growth curve are bacteria most vulnerable to control methods?",
  opts=[["Death phase", "The survivors in death phase are typically the most resistant members of the population."],
        ["Lag phase", "In lag phase the cells are synthesizing enzymes but not yet dividing, so the usual drug targets are not active."],
        ["Stationary phase", "Division has slowed as nutrients run out, which makes these cells harder rather than easier to kill."],
        ["Log phase", "Correct. Most antimicrobials act on processes only running in a dividing cell, such as wall synthesis, so the fastest-dividing population is the most exposed."]],
  c=3, cite=L1 + ", Slides 37-40"),

dict(topic="General Microbiology", io="1.7 — Lytic versus lysogenic replication",
  q="What does a bacterium gain when a phage genome integrates into its chromosome?",
  opts=[["Loss of its plasmids", "Lysogeny adds genetic material rather than removing it; plasmids are unaffected by prophage integration."],
        ["Immediate lysis of neighboring cells", "Lysis of the host is the lytic outcome; lysogeny is defined by the genome integrating quietly instead."],
        ["New traits, such as a toxin gene", "Correct. The prophage is copied along with the chromosome, so a harmless-looking organism can acquire and pass on a toxin gene, which is how diphtheria and cholera toxins arise."],
        ["A thicker cell wall", "Integration changes the genetic content of the cell rather than its wall structure."]],
  c=2, cite=L1 + ", Slides 52-56"),

dict(topic="General Microbiology", io="1.8 — Animal virus versus phage replication",
  q="What must happen after an animal virus enters a host cell that does not happen with a phage?",
  opts=[["The genome must be injected", "Injecting the genome through the wall is the phage mechanism, and it is what removes the need for uncoating."],
        ["The virion must be uncoated", "Correct. The whole particle is taken in, so the capsid has to be stripped away before the genetic material can be used; a phage injects its genome and leaves the coat outside."],
        ["The cell must be lysed", "Lysis releases progeny at the end of phage replication rather than being a step that follows entry."],
        ["The genome must be reversed", "No such step exists; what the animal virus requires is release of its genome from the capsid."]],
  c=1, cite=L1 + ", Slide 58"),

dict(topic="General Microbiology", io="1.11 — Microbial control and the death curve",
  q="A disinfectant reduces a population from 10,000,000 organisms to 10,000. How many decimal reductions is that?",
  opts=[["One thousand", "A thousand is the fold-reduction achieved rather than the number of decimal steps it represents."],
        ["Four", "A fall from ten million to ten thousand is a thousandfold, which is three tenfold steps rather than four."],
        ["Six", "Six reductions would take ten million down to ten organisms rather than to ten thousand."],
        ["Three", "Correct. Each decimal reduction removes ninety percent of whatever remains, so a thousandfold fall is three tenfold steps."]],
  c=3, cite=L1 + ", Slides 62-68"),

# ─────────── Lecture 2 — Antibiotics and Resistance (13) ───────────

dict(topic="Antibiotics and Resistance", io="2.3 — Therapeutic index",
  q="A drug has a toxic dose for half the population of 400 milligrams and an effective dose for half the population of 50 milligrams. What is its therapeutic index?",
  opts=[["350", "Subtracting the doses gives a figure that changes with the units used and cannot be compared between drugs."],
        ["0.125", "This inverts the ratio; putting the effective dose on top yields a value below one for every usable drug."],
        ["8", "Correct. The index is the toxic dose divided by the effective dose, so 400 over 50 gives 8."],
        ["450", "Adding the doses produces a number with no meaning; the index is a ratio."]],
  c=2, cite=L2 + ", Slides 18-20"),

dict(topic="Antibiotics and Resistance", io="2.3 — Therapeutic index",
  q="What does a LARGER therapeutic index tell you about a drug?",
  opts=[["It is safer", "Correct. A wide gap between the dose that works and the dose that harms leaves more room for error in dosing and for variation between patients."],
        ["It is more potent", "Potency describes how small the effective dose is; the index measures the margin between working and toxic doses."],
        ["It acts more quickly", "Onset depends on absorption and distribution rather than on the ratio between two doses."],
        ["It is more likely to be bactericidal", "Whether a drug kills or merely inhibits is independent of its safety margin."]],
  c=0, cite=L2 + ", Slides 18-20"),

dict(topic="Antibiotics and Resistance", io="2.7 — Mechanisms of drug resistance",
  q="An antibiotic course is followed by an infection that no longer responds to it. What has happened to the bacterial population?",
  opts=[["The immune system spared the resistant cells", "The immune system does not discriminate by antibiotic susceptibility; the drug is what removes the susceptible population."],
        ["The antibiotic caused resistance genes to form", "Exposure selects among variation that already exists; the mutations or acquired genes were present before the drug arrived."],
        ["The bacteria learned to avoid the drug", "Bacteria have no such adaptive capacity within a generation; what changes is which organisms survive to reproduce."],
        ["Resistant organisms already present were selected for", "Correct. The drug removes the susceptible competition rather than creating anything, so the few organisms that already carried resistance are left to multiply unopposed."]],
  c=3, cite=L2 + ", Slides 45-52"),

dict(topic="Antibiotics and Resistance", io="2.7 — Mechanisms of drug resistance",
  q="Which resistance mechanism destroys the antibiotic molecule itself?",
  opts=[["Target modification", "Modifying the binding site leaves the drug chemically unchanged and simply unable to attach."],
        ["An efflux pump", "A pump removes the drug intact rather than destroying it, keeping the internal concentration too low to act."],
        ["Enzymatic inactivation", "Correct. An enzyme such as beta-lactamase chemically cleaves the drug, so it can no longer bind its target however much of it is present."],
        ["Reduced permeability", "Reduced permeability keeps the drug out of the cell rather than breaking it apart."]],
  c=2, cite=L2 + ", Slides 45-52"),

dict(topic="Antibiotics and Resistance", io="2.7 — Mechanisms of drug resistance",
  q="Which resistance mechanism keeps the antibiotic from ever reaching a useful concentration inside the cell?",
  opts=[["Target modification", "An altered target allows the drug to accumulate normally but prevents it from binding."],
        ["Enzymatic inactivation", "An enzyme destroys the drug chemically rather than controlling how much of it is inside the cell."],
        ["Efflux pumping", "Correct. The pump exports the drug as fast as it enters, so it never accumulates to a level that would inhibit its target."],
        ["Biofilm formation", "A biofilm impedes penetration into the community rather than acting at the individual cell membrane."]],
  c=2, cite=L2 + ", Slides 45-52"),

dict(topic="Antibiotics and Resistance", io="2.6 — Mechanisms of action",
  q="Which bacterial target is completely absent from human cells?",
  opts=[["The peptidoglycan cell wall", "Correct. Nothing in a human cell corresponds to it, which is why drugs that attack it are among the safest antimicrobials available."],
        ["The ribosome", "Human cells have ribosomes too; they differ in size from the bacterial ones but are certainly present."],
        ["The plasma membrane", "Every human cell has a plasma membrane, which is why membrane-active agents such as the polymyxins are comparatively toxic."],
        ["Deoxyribonucleic acid", "Human cells carry deoxyribonucleic acid, so it cannot be exploited for selective toxicity on its own."]],
  c=0, cite=L2 + ", Slides 24-32"),

dict(topic="Antibiotics and Resistance", io="2.6 — Mechanisms of action",
  q="Which step do the penicillins block?",
  opts=[["Protein synthesis at the ribosome", "That is where the aminoglycosides, macrolides and tetracyclines act."],
        ["Crosslinking of the cell wall", "Correct. The beta-lactam ring inactivates the transpeptidase that links peptidoglycan strands, so the wall cannot be completed and the cell bursts."],
        ["Folate synthesis", "Folate synthesis is blocked by the sulfonamides and trimethoprim."],
        ["Deoxyribonucleic acid replication", "Replication is disrupted by the fluoroquinolones acting on bacterial gyrase."]],
  c=1, cite=L2 + ", Slides 24-32"),

dict(topic="Antibiotics and Resistance", io="2.6 — Mechanisms of action",
  q="Which drug class acts at the bacterial ribosome?",
  opts=[["The polymyxins", "Polymyxins disrupt the bacterial membrane rather than protein synthesis."],
        ["The penicillins", "Penicillins act at the cell wall, inactivating the enzyme that crosslinks peptidoglycan."],
        ["The aminoglycosides", "Correct. They bind the bacterial ribosome and halt translation, which is selective because the bacterial ribosome differs in size from the human one."],
        ["The sulfonamides", "Sulfonamides block folate synthesis by mimicking para-aminobenzoic acid."]],
  c=2, cite=L2 + ", Slides 24-32"),

dict(topic="Antibiotics and Resistance", io="2.2 — Prokaryotic versus eukaryotic targets",
  q="Why are there fewer drugs available against fungal and protozoal infections than against bacterial ones?",
  opts=[["Those pathogens are eukaryotes, like us", "Correct. Selective toxicity needs a difference to exploit, and a eukaryotic pathogen's structure and physiology closely resemble our own, so safe targets are scarce."],
        ["Those pathogens reproduce too slowly", "Slow growth complicates treatment duration but is not why the range of available drugs is narrow."],
        ["Those infections resolve on their own", "Many are severe and even fatal untreated, so the limitation is pharmacological rather than a lack of need."],
        ["Those pathogens have tougher cell walls", "Fungi do have walls, but the constraint is their eukaryotic cell biology rather than wall toughness."]],
  c=0, cite=L2 + ", Slides 12-16"),

dict(topic="Antibiotics and Resistance", io="2.4 — Drug clearance and the dosage schedule",
  q="What happens if doses of an antibiotic are spaced too far apart?",
  opts=[["The drug accumulates and becomes toxic", "Accumulation results from dosing too frequently or from impaired clearance, not from long intervals."],
        ["Organisms regrow between doses", "Correct. Clearance removes the drug continuously, so once the concentration drops below what inhibits the organism the suppressed population resumes multiplying."],
        ["Resistance genes are created by the low level", "Low concentrations select for resistant organisms already present rather than generating new genes."],
        ["Absorption from the gut is reduced", "Absorption depends on the drug and the gut rather than on the interval between doses."]],
  c=1, cite=L2 + ", Slides 21-23"),

dict(topic="Antibiotics and Resistance", io="2.6 — Bacteriostatic versus bactericidal",
  q="What does a bacteriostatic drug do?",
  opts=[["Kills the organism outright", "Killing outright defines a bactericidal agent; a bacteriostatic one only halts replication and waits on host immunity."],
        ["Inhibits growth without killing", "Correct. It halts replication and leaves the host's immune system to clear the organisms that are already there."],
        ["Blocks the organism from attaching to host cells", "Blocking attachment is a function of antibody rather than a category of antimicrobial action."],
        ["Prevents the organism from acquiring resistance genes", "No antimicrobial works by blocking gene transfer; a bacteriostatic drug simply inhibits growth without killing."]],
  c=1, cite=L2 + ", Slides 33-36"),

dict(topic="Antibiotics and Resistance", io="2.6 — Bacteriostatic versus bactericidal",
  q="In which patient does choosing a bactericidal rather than a bacteriostatic drug matter most?",
  opts=[["The neutropenic patient", "Correct. A bacteriostatic agent relies on host immunity to finish the job, and a patient without functioning neutrophils cannot supply it."],
        ["The elderly patient", "Age alters dosing and clearance but does not remove the immune contribution the way neutropenia does."],
        ["The patient with a penicillin allergy", "Allergy restricts which drug can be used rather than whether it must kill outright."],
        ["The patient with kidney impairment", "Renal impairment affects dose adjustment rather than the need for a killing agent."]],
  c=0, cite=L2 + ", Slides 33-36"),

dict(topic="Antibiotics and Resistance", io="2.8 — Other problems with antimicrobial therapy",
  q="A patient develops profuse diarrhea after a broad-spectrum antibiotic course. What has occurred?",
  opts=[["Hypersensitivity", "A hypersensitivity reaction produces rash, bronchospasm or anaphylaxis rather than an overgrowth."],
        ["Direct toxicity", "Some agents do irritate the gut, but an overgrowth following destruction of the flora is superinfection rather than a toxic effect."],
        ["Superinfection", "Correct. Removing the resident flora frees the niche they had been occupying, letting a resistant organism overgrow where it previously could not."],
        ["Resistance", "Resistance would show as the original infection failing to respond, not as a new organism flourishing."]],
  c=2, cite=L2 + ", Slides 55-58"),

dict(topic="Antibiotics and Resistance", io="2.1 — Major historical events and names",
  q="Who first observed the inhibition of bacterial growth by a contaminating mold?",
  opts=[["Fleming", "Correct. He noticed the zone of inhibition around the mold on a culture plate, which is the observation that opened the way to penicillin."],
        ["Florey", "Florey worked with Chain on purifying the compound and showing it could treat infection, after the original observation."],
        ["Chain", "Chain shared in the development work that turned penicillin into a usable drug rather than making the first observation."],
        ["Ehrlich", "Ehrlich's contribution was the magic bullet concept and early chemotherapy, well before penicillin was seen."]],
  c=0, cite=L2 + ", Slides 5-10"),

# ─────────── Lecture 3 — Microbe-Human Interactions (10) ───────────
# Not reviewed in class, so weighted evenly rather than lightly.

dict(topic="Microbe-Human Interactions", io="1 — Define resident flora",
  q="By what mechanism does resident flora protect the host?",
  opts=[["It raises local temperature to inhibit invaders", "Fever is a host response driven by cytokines rather than anything the flora produce."],
        ["It secretes antibody against pathogens", "Antibody is produced by plasma cells of the host immune system rather than by bacteria."],
        ["It digests pathogens as they arrive", "Flora compete for space and nutrients rather than consuming newcomers, which is what denies a pathogen anywhere to establish."],
        ["It occupies the niche first", "Correct. Competition for space and nutrients means a newly arrived pathogen finds nowhere to establish and nothing left to consume."]],
  c=3, cite=L3 + ", Slides 8-16"),

dict(topic="Microbe-Human Interactions", io="1 — Define resident flora",
  q="Which body site carries the largest resident microbial population?",
  opts=[["Small intestine", "The small intestine carries a rising population along its length but stays far below the colon, partly because transit is quicker there."],
        ["Oral cavity", "The mouth is heavily colonized but does not approach the numbers found in the large intestine."],
        ["Nasal passages", "The nose carries a modest resident population, including the staphylococci that matter for surgical infection, but nothing near colonic numbers."],
        ["Large intestine", "Correct. The colon holds by far the densest population in the body, which is why disturbing it with antibiotics has such marked consequences."]],
  c=3, cite=L3 + ", Slides 8-16"),

dict(topic="Microbe-Human Interactions", io="1 — Define resident flora",
  q="Which of these is normally sterile?",
  opts=[["Conjunctiva", "The conjunctiva carries a sparse resident population despite the flushing action of tears."],
        ["Large intestine", "The colon is the most heavily colonized site in the body; the sterile compartments are blood and cerebrospinal fluid."],
        ["Distal urethra", "A short portion of the urethra carries flora, which is why a voided specimen is not sterile."],
        ["Cerebrospinal fluid", "Correct. It is an internal compartment that no organism should reach, which is why any growth from it is significant."]],
  c=3, cite=L3 + ", Slides 8-16"),

dict(topic="Microbe-Human Interactions", io="1 — Define resident flora",
  q="What defines a TRUE pathogen?",
  opts=[["It is always Gram-negative", "Gram reaction has no bearing on whether an organism can overcome normal defenses."],
        ["It sickens a healthy person", "Correct. It carries enough virulence to overcome intact defenses, which is precisely what an opportunist cannot do."],
        ["It always produces an exotoxin", "Toxin production is one virulence factor among many and is not what defines the category."],
        ["It is acquired only in hospital", "Where an organism is acquired describes the setting rather than its capacity to cause disease."]],
  c=1, cite=L3 + ", Slides 18-24"),

dict(topic="Microbe-Human Interactions", io="1 — Define resident flora",
  q="Under which circumstance does an opportunist cause disease?",
  opts=[["When it is exposed to an antibiotic", "Antibiotic exposure may select it but the disease still requires compromised defenses or an unnatural site."],
        ["When it acquires a capsule", "A capsule aids virulence but is not the circumstance that converts an opportunist into a pathogen."],
        ["When the host has already had the infection", "Prior infection generally confers some protection rather than enabling disease."],
        ["When host defenses are compromised", "Correct. An organism that is harmless as resident flora becomes pathogenic once the defenses holding it in check fail, or once it reaches a site it does not belong in."]],
  c=3, cite=L3 + ", Slides 18-24"),

dict(topic="Microbe-Human Interactions", io="3 — Endotoxins versus exotoxins",
  q="When is endotoxin released?",
  opts=[["When the organism is phagocytosed intact", "Engulfment alone does not release it; the cell must be broken apart."],
        ["Continuously, secreted by the living cell", "Active secretion by a living cell describes an exotoxin; endotoxin is a wall component freed only when the cell lyses."],
        ["Only during sporulation", "Sporulation is a dormancy process unrelated to endotoxin release."],
        ["When the bacterial cell lyses", "Correct. It is a structural component of the Gram-negative outer membrane, so it only reaches the host once the cell breaks apart."]],
  c=3, cite=L3 + ", Slides 40-46"),

dict(topic="Microbe-Human Interactions", io="3 — Endotoxins versus exotoxins",
  q="Which organisms produce endotoxin?",
  opts=[["All bacteria equally", "Only the Gram-negative envelope carries the lipopolysaccharide from which endotoxin comes."],
        ["Gram-positive bacteria", "Gram-positive organisms have no outer membrane and therefore no lipopolysaccharide."],
        ["Fungi", "Fungal walls are built on chitin and glucan and contain no lipopolysaccharide."],
        ["Gram-negative bacteria", "Correct. Endotoxin is the lipid A portion of lipopolysaccharide, which is built into the Gram-negative outer membrane and found nowhere else."]],
  c=3, cite=L3 + ", Slides 40-46"),

dict(topic="Microbe-Human Interactions", io="2 — Steps in the progression of infectious disease",
  q="Which structure allows a bacterium to attach to host tissue?",
  opts=[["The capsule", "The capsule resists phagocytosis rather than mediating attachment."],
        ["Fimbriae", "Correct. They are the adhesins that anchor the organism to a specific receptor on the host cell, without which it would simply be washed away."],
        ["The endospore", "The endospore is a dormant survival form and plays no part in adhesion."],
        ["The ribosome", "The ribosome synthesizes protein inside the cell; attachment to host tissue is mediated by surface fimbriae."]],
  c=1, cite=L3 + ", Slides 30-38"),

dict(topic="Microbe-Human Interactions", io="4 — Stages in the course of an infection",
  q="What distinguishes a sign from a symptom?",
  opts=[["A sign is treatable; a symptom is not", "Treatability has no bearing on the definition; what separates them is whether the finding is observed or felt."],
        ["A sign is felt by the patient; a symptom is observed", "This reverses them: the sign is what the clinician observes and the symptom is what the patient feels."],
        ["A sign appears early; a symptom appears late", "Timing does not define either term; the distinction is whether the finding is observed or reported."],
        ["A sign is observed; a symptom is felt by the patient", "Correct. The distinction is who perceives it, which is why a sign can be recorded objectively and a symptom must be reported."]],
  c=3, cite=L3 + ", Slides 50-58"),

dict(topic="Microbe-Human Interactions", io="4 — Stages in the course of an infection",
  q="What is a sequela?",
  opts=[["A second infection following the first", "A further infection following the first is a secondary infection; a sequela is lasting damage left behind."],
        ["Lasting damage after the illness", "Correct. It is the permanent tissue or organ injury left behind once the acute illness has resolved, such as blindness following gonococcal conjunctivitis."],
        ["The interval before symptoms appear", "That is the incubation period, which precedes illness rather than following it."],
        ["A relapse of the original illness", "A relapse is the same illness returning rather than lasting damage from it."]],
  c=1, cite=L3 + ", Slides 50-58"),

# ─────────── Lecture 4 — Transmission of Microorganisms (9) ───────────

dict(topic="Transmission of Microorganisms", io="1 — Describe the chain of infection",
  q="How many links make up the chain of infection?",
  opts=[["Eight", "Eight overstates it; the chain has six links, running from the agent through to the susceptible host."],
        ["Four", "Four omits several links; the chain runs from the agent through to the susceptible host in six steps."],
        ["Six", "Correct. Agent, reservoir, portal of exit, mode of transmission, portal of entry and susceptible host, and breaking any one of them interrupts spread."],
        ["Three", "Three is far too few to describe the route from reservoir to host."]],
  c=2, cite=L4 + ", Slides 6-14"),

dict(topic="Transmission of Microorganisms", io="1 — Describe the chain of infection",
  q="Which link in the chain of infection does hand hygiene break?",
  opts=[["The susceptible host", "Protecting the host describes vaccination or prophylaxis rather than hand hygiene."],
        ["The reservoir", "Removing the reservoir would mean eliminating where the organism lives and multiplies, which hand hygiene does not do."],
        ["The mode of transmission", "Correct. Washing removes organisms from the hands that would otherwise carry them from one host to the next, which is the link most readily interrupted."],
        ["The portal of exit", "Closing the portal of exit would mean containing secretions, as a mask or dressing does."]],
  c=2, cite=L4 + ", Slides 6-14"),

dict(topic="Transmission of Microorganisms", io="1 — Describe the chain of infection",
  q="What is a fomite?",
  opts=[["A contaminated non-living object", "Correct. It is any inanimate item that carries organisms from one person to another, such as a stethoscope or a keyboard."],
        ["A living carrier showing no symptoms", "A symptomless living carrier is a carrier rather than a fomite."],
        ["An airborne droplet nucleus", "A droplet nucleus is a suspended particle rather than an object."],
        ["An insect that transmits disease", "An insect that transmits disease is a vector, which is living."]],
  c=0, cite=L4 + ", Slides 40-52"),

dict(topic="Transmission of Microorganisms", io="1 — Describe the chain of infection",
  q="What distinguishes a PASSIVE carrier from an active one?",
  opts=[["The passive carrier has been treated", "Treatment status defines neither category; the passive carrier is distinguished by never being infected at all."],
        ["The passive carrier shows no symptoms", "An active carrier may also be symptomless; the distinction is whether they are infected at all."],
        ["The passive carrier is not infected", "Correct. They simply transfer organisms on hands or clothing without the organism ever establishing in them, which is why hand hygiene matters so much among staff."],
        ["The passive carrier transmits only by air", "Route of transmission does not separate them; the passive carrier is simply never infected themselves."]],
  c=2, cite=L4 + ", Slides 16-26"),

dict(topic="Transmission of Microorganisms", io="1 — Describe the chain of infection",
  q="What separates a vector from a reservoir?",
  opts=[["The vector carries the organism; the reservoir harbors it", "Correct. The reservoir is where the organism normally lives and multiplies, while the vector merely transports it to a new host."],
        ["The vector harbors the organism; the reservoir carries it", "This reverses them: the reservoir is where the organism lives and multiplies, and the vector merely transports it."],
        ["The vector is inanimate; the reservoir is living", "An inanimate carrier is a fomite; a vector is by definition living."],
        ["The vector is always an insect; the reservoir always an animal", "Neither is restricted to those categories; the distinction is whether the organism lives there or is merely carried."]],
  c=0, cite=L4 + ", Slides 16-26"),

dict(topic="Transmission of Microorganisms", io="1 — Describe the chain of infection",
  q="Why can a zoonotic infection not be eradicated the way smallpox was?",
  opts=[["Zoonotic organisms resist all antimicrobials", "Many are readily treatable; the obstacle is the reservoir rather than resistance."],
        ["Zoonotic organisms mutate too quickly", "Mutation rate complicates vaccine design for some agents but is not the barrier to eradication here."],
        ["Zoonotic infections are always viral", "Zoonoses may be bacterial, viral, fungal or protozoan, and smallpox itself was a virus that was eradicated."],
        ["The animal reservoir persists", "Correct. Eradication requires removing every place the organism can live, and an infection maintained in animals continues however many human cases are cured."]],
  c=3, cite=L4 + ", Slides 28-36"),

dict(topic="Transmission of Microorganisms", io="1 — Describe the chain of infection",
  q="Which patients are most at risk from hospital-acquired infection?",
  opts=[["Outpatients attending clinics", "Hospital-acquired infection is defined by acquisition during an admission."],
        ["The young and otherwise healthy", "Intact immunity is protective, making this group the least at risk."],
        ["The immunocompromised", "Correct. Impaired defenses allow organisms of low virulence, including the patient's own flora, to establish infection they could not otherwise cause."],
        ["Patients on short admissions", "Longer stays with more devices carry higher risk than short ones."]],
  c=2, cite=L4 + ", Slides 40-46"),

dict(topic="Transmission of Microorganisms", io="1 — Describe the chain of infection",
  q="What determines whether a disinfectant actually works on a surface?",
  opts=[["Whether the surface looks clean", "A visibly clean surface may still carry a biofilm, which is part of why appearance is misleading."],
        ["Its concentration and contact time", "Correct. An agent applied too dilute, or wiped away before its contact time has elapsed, will not achieve the reduction it is rated for however good the chemical is."],
        ["The temperature of the room", "Ambient temperature has little bearing compared with concentration and dwell time."],
        ["The brand of the product", "Brand is a procurement matter rather than a determinant of kill."]],
  c=1, cite=L4 + ", Slides 56-64"),

dict(topic="Transmission of Microorganisms", io="1 — Describe the chain of infection",
  q="Which mechanism of horizontal gene transfer uses a virus as the carrier?",
  opts=[["Conjugation", "Conjugation requires direct contact between cells through a pilus."],
        ["Transformation", "In transformation the recipient takes up naked genetic material released into the environment, with no virus involved."],
        ["Transduction", "Correct. A bacteriophage packages host genetic material and injects it into the next cell, carrying resistance genes between organisms that never touch."],
        ["Binary fission", "Binary fission is ordinary cell division and passes genes vertically rather than horizontally."]],
  c=2, cite=L4 + ", Slides 66-72"),

# ─────────── Lecture 5 — Nonspecific Host Defenses (18) ───────────
# Her heaviest lecture: nine of twelve objectives graded "know cold".

dict(topic="Nonspecific Host Defenses", io="3.1 — The three lines of defense",
  q="Which of the three lines of defense is the specific one?",
  opts=[["All three equally", "Only the third line recognizes a particular antigen and remembers it."],
        ["The first", "The first line is a set of barriers that block anything indiscriminately, which is the definition of nonspecific."],
        ["The second", "The second line is protective cells and antimicrobial substances acting without regard to which organism is present."],
        ["The third", "Correct. Only the third is acquired through exposure to a particular antigen and carries memory of it; the first two act identically against anything."]],
  c=3, cite=L5 + ", Slide 4"),

dict(topic="Nonspecific Host Defenses", io="3.2 — First line barriers",
  q="Into which first-line category does lysozyme fall?",
  opts=[["Microbiological", "The microbiological barrier is the resident flora competing for the niche."],
        ["Physical", "A physical barrier obstructs mechanically, as intact skin and the ciliary escalator do."],
        ["Chemical", "Correct. It is an enzyme that digests peptidoglycan, attacking the invader chemically rather than obstructing it."],
        ["Genetic", "The genetic barrier refers to inherited resistance rather than a secreted enzyme."]],
  c=2, cite=L5 + ", Slides 13-18"),

dict(topic="Nonspecific Host Defenses", io="3.2 — First line barriers",
  q="Into which first-line category does the resident flora fall?",
  opts=[["Chemical", "A chemical barrier is a substance such as lysozyme or gastric acid rather than a population of organisms."],
        ["Microbiological", "Correct. Protection comes from living organisms occupying the niche and competing for nutrients, which is neither a physical nor a chemical mechanism."],
        ["Physical", "A physical barrier obstructs mechanically; the flora work by competition."],
        ["Genetic", "The genetic barrier refers to inherited resistance rather than colonization."]],
  c=1, cite=L5 + ", Slides 13-18"),

dict(topic="Nonspecific Host Defenses", io="3.2 — First line barriers",
  q="Lysozyme strips the entire wall from which organisms?",
  opts=[["Fungi", "Fungal walls are built on chitin and glucan rather than peptidoglycan."],
        ["Gram-negative organisms", "Their peptidoglycan is thinner but sits beneath an outer membrane the enzyme cannot cross, so it is shielded."],
        ["Gram-positive organisms", "Correct. The intuition that a thicker wall is sturdier is backwards here: their peptidoglycan is the enzyme's substrate and lies exposed as the outermost layer."],
        ["Both Gram-positive and Gram-negative equally", "Access differs: the Gram-negative outer membrane keeps the enzyme away from its substrate."]],
  c=2, cite=L5 + ", Slides 13-18"),

dict(topic="Nonspecific Host Defenses", io="3.3 — Recognition: receptors and patterns",
  q="What does a pathogen-associated molecular pattern represent?",
  opts=[["A conserved microbial structure", "Correct. Because these structures are shared across whole classes of organism and absent from us, a small set of receptors can detect almost any invader."],
        ["A molecule released by injured host cells", "That describes a damage-associated pattern, which signals tissue injury rather than infection."],
        ["A specific antigen unique to one organism", "Recognizing a unique antigen is the job of the adaptive system rather than these receptors."],
        ["An antibody bound to a microbial surface", "Antibody belongs to the specific response and is not what these receptors detect."]],
  c=0, cite=L5 + ", Slides 20-30"),

dict(topic="Nonspecific Host Defenses", io="3.3 — Recognition: receptors and patterns",
  q="What does a damage-associated molecular pattern signal?",
  opts=[["Successful clearance of an infection", "These patterns initiate a response rather than signaling its resolution."],
        ["The presence of a Gram-negative organism", "A microbial component such as lipopolysaccharide is a pathogen-associated pattern rather than a damage signal."],
        ["Injury to the host's own cells", "Correct. Molecules normally kept inside a cell appear outside when it is damaged, so the same receptor system provokes inflammation after sterile injury as after infection."],
        ["Antibody production by plasma cells", "Antibody belongs to the specific response and is unrelated to damage signaling."]],
  c=2, cite=L5 + ", Slides 20-30"),

dict(topic="Nonspecific Host Defenses", io="3.4 — The leukocytes",
  q="Which leukocyte is the most numerous?",
  opts=[["The monocyte", "Monocytes account for only about 3 to 7 percent; the neutrophil dominates the differential at 55 to 90 percent."],
        ["The lymphocyte", "Lymphocytes come second at about 20 to 35 percent, behind neutrophils at roughly 55 to 90 percent."],
        ["The neutrophil", "Correct. Neutrophils make up roughly 55 to 90 percent of the differential, which is why a raised total count so often reflects a neutrophil response."],
        ["The eosinophil", "Eosinophils are only 1 to 3 percent of the differential; neutrophils make up 55 to 90 percent."]],
  c=2, cite=L5 + ", Slides 66-70"),

dict(topic="Nonspecific Host Defenses", io="3.4 — The leukocytes",
  q="What is the eosinophil's principal role?",
  opts=[["Antibody production", "Antibody is secreted by plasma cells derived from B lymphocytes."],
        ["Release of histamine", "Histamine release is the basophil and mast cell function; the eosinophil defends against parasites."],
        ["Antigen presentation to lymphocytes", "Antigen presentation belongs to macrophages and dendritic cells."],
        ["Defense against parasites", "Correct. Its granules carry proteins toxic to organisms far too large to phagocytose, particularly helminths, which are released into the surrounding space."]],
  c=3, cite=L5 + ", Slides 66-70"),

dict(topic="Nonspecific Host Defenses", io="3.4 — The leukocytes",
  q="What is the basophil's principal role?",
  opts=[["Defense against helminths", "Antiparasitic defense is the eosinophil's role; the basophil releases histamine and related mediators."],
        ["Release of chemical mediators", "Correct. It degranulates to release histamine and related mediators, driving the vascular changes of inflammation and the allergic response."],
        ["Phagocytosis of bacteria", "Neutrophils and macrophages are the dedicated phagocytes; the basophil releases mediators instead."],
        ["Killing virus-infected cells", "Killing virus-infected cells is the natural killer cell's work; the basophil releases chemical mediators."]],
  c=1, cite=L5 + ", Slides 66-70"),

dict(topic="Nonspecific Host Defenses", io="3.5 — Macrophage versus neutrophil",
  q="What can a macrophage do that a neutrophil cannot?",
  opts=[["Release histamine", "Histamine release belongs to basophils and mast cells rather than to either phagocyte."],
        ["Phagocytose bacteria", "Both are phagocytes, so engulfment does not separate them; only the macrophage presents antigen to lymphocytes."],
        ["Migrate towards a chemical signal", "Both move by chemotaxis toward infection; the macrophage is distinguished by presenting antigen to lymphocytes."],
        ["Present antigen to lymphocytes", "Correct. This is the step that recruits the specific immune system, which is why the macrophage bridges innate and adaptive defense while the neutrophil simply kills and dies."]],
  c=3, cite=L5 + ", Slides 66-72"),

dict(topic="Nonspecific Host Defenses", io="3.6 — White blood count with differential",
  q="What does the differential add that a total white cell count alone cannot give?",
  opts=[["Whether the cell types are in normal proportion", "Correct. A normal total can conceal a badly skewed mix, and it is the proportion that distinguishes a bacterial from a viral pattern."],
        ["The total number of white cells, more precisely", "The plain count already gives the total; the differential adds the proportion of each cell type."],
        ["The identity of the infecting organism", "It can suggest a pattern but cannot name an organism; that needs culture or molecular testing."],
        ["The antibody titre against the organism", "Antibody titres are a separate serological test; the differential reports the proportion of each white cell type."]],
  c=0, cite=L5 + ", Slides 70-74"),

dict(topic="Nonspecific Host Defenses", io="3.7 — Inflammation",
  q="Which set lists the four classical signs of inflammation?",
  opts=[["Heat, swelling, bleeding and numbness", "Bleeding and numbness are not classical signs of inflammation."],
        ["Redness, heat, pus and fever", "Pus and fever are consequences of some inflammation rather than the classical four signs."],
        ["Swelling, pain, itching and scaling", "Itching and scaling are not classical signs; the four are redness, heat, swelling and pain."],
        ["Redness, heat, swelling and pain", "Correct. Rubor, calor, tumor and dolor, with loss of function sometimes added as a fifth."]],
  c=3, cite=L5 + ", Slides 34-40"),

dict(topic="Nonspecific Host Defenses", io="3.7 — Inflammation",
  q="What produces the redness and heat of inflammation?",
  opts=[["Vasoconstriction concentrating blood in the area", "Constriction would reduce flow, leaving the area paler and cooler rather than red and warm."],
        ["Vasodilation increasing blood flow to the area", "Correct. Widening the supplying arterioles brings more warm blood into the injured region, which accounts for both the color and the temperature."],
        ["Neutrophils releasing pigment into the tissue", "Neutrophils release enzymes and reactive species rather than any pigment."],
        ["Fluid leaking into the interstitial space", "Leaking fluid accounts for the swelling rather than the redness and heat."]],
  c=1, cite=L5 + ", Slides 34-40"),

dict(topic="Nonspecific Host Defenses", io="3.8 — Fever",
  q="What causes fever?",
  opts=[["Endotoxin acting directly on the skin", "Endotoxin works by inducing host cytokines rather than acting on the skin."],
        ["Dehydration raising core temperature", "Fluid loss can raise temperature passively but fever is a regulated change in the set point."],
        ["Histamine released from mast cells", "Histamine drives the local vascular changes of inflammation rather than the systemic set-point change."],
        ["Cytokines reset the set point", "Correct. Interleukin-1, interleukin-6 and tumor necrosis factor act systemically on the hypothalamus, which then defends a higher target temperature."]],
  c=3, cite=L5 + ", Slides 40-46"),

dict(topic="Nonspecific Host Defenses", io="3.8 — Fever",
  q="Why is fever beneficial?",
  opts=[["It kills all pathogens outright", "Fever inhibits growth rather than sterilizing; it does not eliminate the organism by itself."],
        ["It inhibits pathogen growth", "Correct. Many organisms replicate poorly above normal body temperature, while the host's own enzymatic and cellular responses run faster."],
        ["It prevents the pathogen from entering cells", "Cell entry depends on receptor interactions rather than on temperature."],
        ["It stimulates antibody production exclusively", "Antibody production is driven by antigen and helper T cell signals rather than by temperature alone."]],
  c=1, cite=L5 + ", Slides 40-46"),

dict(topic="Nonspecific Host Defenses", io="3.8 — Fever",
  q="Why is a high fever dangerous?",
  opts=[["High temperatures damage tissue", "Correct. Above a certain point host proteins begin to denature, so the same response that inhibits the organism starts to harm the patient."],
        ["It suppresses the immune response", "Moderate fever accelerates immune reactions rather than suppressing them."],
        ["It causes the pathogen to mutate", "Temperature does not drive mutation in the way this implies."],
        ["It prevents antibiotics from working", "Fever does not abolish antibiotic activity; its danger is that high temperatures denature host proteins."]],
  c=0, cite=L5 + ", Slides 40-46"),

dict(topic="Nonspecific Host Defenses", io="3.9 — Interferon",
  q="What does interferon do to a virus?",
  opts=[["It destroys viral particles directly", "Interferon has no direct virucidal action; it induces an antiviral state in neighboring uninfected cells."],
        ["It prevents spread rather than killing the virus", "Correct. It acts on neighboring uninfected cells, inducing an antiviral state so the infection cannot propagate; the already-infected cell is not rescued."],
        ["It coats the virus so phagocytes engulf it", "Coating a target for phagocytosis is opsonization, performed by antibody and complement."],
        ["It lyses the infected cell immediately", "Killing infected cells is the work of cytotoxic T cells and natural killer cells."]],
  c=1, cite=L5 + ", Slides 48-52"),

dict(topic="Nonspecific Host Defenses", io="3.10 — Complement",
  q="In what order are the three complement pathways activated?",
  opts=[["Classical, then lectin, then alternative", "That is the order in which the pathways were discovered, which runs opposite to the order of activation."],
        ["Alternative, then lectin, then classical", "Correct. The alternative pathway fires immediately with no prior recognition needed, the lectin pathway follows, and the classical comes last because it waits on antibody."],
        ["Lectin, then alternative, then classical", "The alternative pathway is the one that can act immediately, so it comes first."],
        ["Classical, then alternative, then lectin", "The classical pathway is the slowest because it requires antibody to be present."]],
  c=1, cite=L5 + ", Slides 42-46"),

dict(topic="Nonspecific Host Defenses", io="3.10 — Complement",
  q="Which component do all three complement pathways converge on?",
  opts=[["C1", "C1 begins the classical pathway alone and is not shared by the other two."],
        ["C3", "Correct. The pathways differ only in how they are switched on; all three end by cleaving C3, which is why it is the pivotal molecule of the cascade."],
        ["C9", "C9 forms part of the membrane attack complex assembled well after the convergence point."],
        ["Mannose-binding lectin", "Mannose-binding lectin initiates the lectin pathway alone; all three pathways converge on cleaving C3."]],
  c=1, cite=L5 + ", Slides 42-46"),

dict(topic="Nonspecific Host Defenses", io="3.4 — The leukocytes",
  q="Why does pus form at a site of bacterial infection?",
  opts=[["Bacteria secrete it as a waste product", "Pus is host material, consisting of dead leukocytes, protein and tissue debris."],
        ["Macrophages migrate in and release pigment", "Macrophages clear debris rather than producing the material, and no pigment is involved."],
        ["Spent neutrophils die at the site", "Correct. Each neutrophil carries one load of granule contents and no means of making more, so the cells are spent by their own killing and accumulate as purulent material."],
        ["Plasma leaks from dilated capillaries", "Leaking plasma produces the swelling of inflammation rather than purulent material."]],
  c=2, cite=L5 + ", Slides 76-78"),

# ─────────── Lecture 6 — Specific Immunity (9) ───────────
# Also not reviewed in class, and weighted evenly for the same reason.

dict(topic="Specific Immunity", io="1 — Relate innate and specific immunity",
  q="A newborn receives antibody across the placenta. Which type of immunity is that?",
  opts=[["Artificial passive", "Artificial passive immunity means receiving antibody as a deliberate treatment, such as an immunoglobulin injection."],
        ["Natural active", "Natural active immunity follows actually having the infection and mounting your own response."],
        ["Natural passive", "Correct. Nothing was engineered, so it is natural, and the infant receives ready-made antibody rather than producing it, so it is passive and temporary."],
        ["Artificial active", "Artificial active immunity is what vaccination produces, where the recipient makes their own response."]],
  c=2, cite=L6 + ", Slides 6-12"),

dict(topic="Specific Immunity", io="1 — Relate innate and specific immunity",
  q="Which type of immunity does vaccination produce?",
  opts=[["Artificial active", "Correct. The antigen is administered deliberately, so it is artificial, and the recipient mounts their own response and forms memory, so it is active."],
        ["Artificial passive", "Passive immunity means receiving preformed antibody, which confers no memory and fades."],
        ["Natural active", "Natural active immunity follows genuine infection rather than deliberate administration."],
        ["Natural passive", "Natural passive immunity is antibody received across the placenta or in breast milk."]],
  c=0, cite=L6 + ", Slides 6-12"),

dict(topic="Specific Immunity", io="4 — Antibody structure, class and function",
  q="How many chains make up an antibody monomer?",
  opts=[["Four", "Correct. Two identical heavy chains and two identical light chains form the Y-shaped molecule."],
        ["Two", "Two chains would be half a monomer; the complete unit has two heavy and two light."],
        ["Six", "Six exceeds the monomer, which is built from four chains: two heavy and two light."],
        ["Eight", "Eight would describe a larger assembly rather than the basic monomer."]],
  c=0, cite=L6 + ", Slides 40-48"),

dict(topic="Specific Immunity", io="4 — Antibody structure, class and function",
  q="Which antibody class appears first in a new infection?",
  opts=[["Immunoglobulin M", "Correct. It is produced first and is by far the largest, its ten binding sites making it highly effective at agglutinating antigen early on."],
        ["Immunoglobulin G", "Immunoglobulin G dominates later and in the secondary response rather than appearing first."],
        ["Immunoglobulin A", "Immunoglobulin A is secreted onto mucosal surfaces rather than leading the systemic response."],
        ["Immunoglobulin E", "Immunoglobulin E is present in trace amounts and is associated with allergy and parasites."]],
  c=0, cite=L6 + ", Slides 50-60"),

dict(topic="Specific Immunity", io="4 — Antibody structure, class and function",
  q="Which antibody class guards mucosal surfaces?",
  opts=[["Immunoglobulin M", "Immunoglobulin M is too large to be secreted efficiently onto surfaces."],
        ["Immunoglobulin A", "Correct. It is secreted across epithelium onto the mucous membranes of the gut, airway and urogenital tract, where it blocks attachment."],
        ["Immunoglobulin D", "Immunoglobulin D sits on the surface of naive B cells rather than guarding mucosa."],
        ["Immunoglobulin E", "Immunoglobulin E binds mast cells and basophils and mediates allergic responses."]],
  c=1, cite=L6 + ", Slides 50-60"),

dict(topic="Specific Immunity", io="3 — Antigens, antibodies and leukocytes",
  q="When are lymphocyte receptor specificities generated?",
  opts=[["After the antigen arrives, in response to it", "This is the discarded instructional model; receptors are made in advance."],
        ["Before any antigen has entered", "Correct. The repertoire is produced during lymphocyte development by gene rearrangement, so an arriving antigen selects a clone that already exists rather than instructing anything."],
        ["Only during an active infection", "The repertoire is laid down during development rather than generated afresh at each infection."],
        ["Continuously, in proportion to antigen exposure", "Diversity is generated independently of which antigens happen to be present."]],
  c=1, cite=L6 + ", Slides 30-38"),

dict(topic="Specific Immunity", io="3 — Antigens, antibodies and leukocytes",
  q="Class two major histocompatibility complex molecules present antigen to which cell?",
  opts=[["The helper T cell", "Correct. Class two is carried by antigen-presenting cells and displays engulfed material to the helper subset, which bears the matching cluster of differentiation 4 marker."],
        ["The cytotoxic T cell", "Cytotoxic T cells recognize antigen displayed on class one molecules instead."],
        ["The B cell", "B cells recognize antigen directly through their own surface receptor."],
        ["The natural killer cell", "Natural killer cells respond to the absence of class one rather than being presented to."]],
  c=0, cite=L6 + ", Slides 20-28"),

dict(topic="Specific Immunity", io="3 — Antigens, antibodies and leukocytes",
  q="What does opsonization do?",
  opts=[["Coats the organism so phagocytes can engulf it", "Correct. The coating marks the target and gives the phagocyte a surface it can bind, which greatly increases the rate of engulfment."],
        ["Blocks the organism's attachment sites", "Blocking attachment sites is neutralization; opsonization coats the organism so phagocytes can grip it."],
        ["Clumps organisms together", "Clumping is agglutination, which immobilizes antigen rather than marking it for uptake."],
        ["Punches holes in the organism's membrane", "Lysis requires the complement membrane attack complex; opsonization merely coats the target for engulfment."]],
  c=0, cite=L6 + ", Slides 62-70"),

dict(topic="Specific Immunity", io="3 — Antigens, antibodies and leukocytes",
  q="How does a second exposure to the same antigen differ from the first?",
  opts=[["It is identical to the first", "The whole purpose of immunological memory is that the second response differs markedly."],
        ["It is slower and produces more immunoglobulin M", "Immunoglobulin M dominates the first response; the memory response is faster and rich in immunoglobulin G."],
        ["It is faster and produces far more immunoglobulin G", "Correct. Memory cells laid down by the first exposure are already present and pre-committed, so the response begins sooner, climbs higher and switches class."],
        ["It is weaker, because tolerance has developed", "Tolerance applies to self antigens; a repeated foreign antigen provokes a stronger response."]],
  c=2, cite=L6 + ", Slides 72-80"),
]
