# -*- coding: utf-8 -*-
# Microbiology Exam 1, Lecture 5 — Host Defenses: Nonspecific Mechanisms, pool C.
# Objectives 5 and 6 in depth: leukocyte classes and their percentages, the white
# count with differential, phagocytosis, dendritic cells, natural killer cells,
# and the lymphoid system that hosts the encounter.
#
# Four options throughout. Answers written SHORT from the outset.
SRC = "Lecture 5  Dr. Webster Nonspecific Immunity.pptx"
def c(n): return f"{SRC}, Slide {n}"

IO5 = "5 — Describe the roles of the different classes of leukocytes in the second and third lines of defense"
IO6 = "6 — Describe the role of a white blood count with differential"
IO3 = "3 — List the key factors involved in innate immunity"

POOL_C = [
 # ---------------- lymphoid system ----------------
 dict(topic="Lymphoid system", io=IO3,
   q="Where do lymphatic capillaries NOT reach?",
   opts=[["The central nervous system",
          "Correct — everywhere else is permeated. Bone, placenta and thymus."],
         ["The skin and gut",
          "Both are richly supplied, and both have their own lymphoid tissue."],
         ["The lungs and liver",
          "Both are served."],
         ["Nowhere — they reach every tissue",
          "Four exceptions are named."]],
   c=0, cite=c(63)),
 dict(topic="Lymphoid system", io=IO3,
   q="What is the lymphatic system's role in inflammation?",
   opts=[["It acts as the drain-off system",
          "Correct — plus surveillance, recognition and protection. Returning extracellular fluid to the circulation."],
         ["It produces the inflammatory cytokines",
          "Macrophages do that."],
         ["It forms the physical barrier at the portal of entry",
          "That is the first line."],
         ["It manufactures complement",
          "Complement is a plasma protein system, largely hepatic."]],
   c=0, cite=c(63)),
 dict(topic="Lymphoid system", io=IO3,
   q="Which are the PRIMARY lymphoid organs, and what does each make?",
   opts=[["Thymus for T cells, bone marrow for B cells",
          "Correct — primary organs produce the adaptive cells."],
         ["Spleen for T cells, lymph nodes for B cells",
          "Both are SECONDARY organs, where lymphocytes engage pathogens."],
         ["Bone marrow for T cells, thymus for B cells",
          "Reversed."],
         ["Peyer's patches and the appendix",
          "Both are gut-associated secondary tissue."]],
   c=0, cite=c(64)),
 dict(topic="Lymphoid system", io=IO3,
   q="What happens in the SECONDARY lymphoid organs?",
   opts=[["Lymphoid cells engage pathogens",
          "Correct — spleen, lymph nodes, and the associated tissues."],
         ["Lymphocytes are produced",
          "That is the primary organs' job."],
         ["Complement is synthesised",
          "Not their described function."],
         ["Antibody is degraded",
          "Not a function given."]],
   c=0, cite=c(64)),
 dict(topic="Lymphoid system", io=IO3,
   q="What does GALT stand for, and what are its two named components?",
   opts=[["Gut-associated lymphoid tissue — Peyer's patches and the appendix",
          "Correct."],
         ["Gut-associated lymphatic trunk — the cisterna chyli and thoracic duct",
          "Not the term's meaning."],
         ["Generalised lymphoid tissue — spleen and thymus",
          "The thymus is a primary organ, and the term is specific to the gut."],
         ["Gastric-associated lymphoid tissue — the fundus and antrum",
          "GALT covers the gut broadly, and the named components are different."]],
   c=0, cite=c(64)),
 dict(topic="Lymphoid system", io=IO3,
   q="Which tissue does BALT refer to?",
   opts=[["Bronchial-associated lymphoid tissue", "Correct."],
         ["Bone-associated lymphoid tissue", "Not a term used."],
         ["Blood-associated lymphoid tissue", "Not a term used."],
         ["Bladder-associated lymphoid tissue", "Not a term used."]],
   c=0, cite=c(64)),
 dict(topic="Lymphoid system", io=IO3,
   q="Where do encounters between host defenses and invaders take place?",
   opts=[["The reticuloendothelial system",
          "Correct — the four compartments named. Extracellular fluid, bloodstream and lymphatic system."],
         ["The bloodstream only",
          "Three other compartments are listed."],
         ["Inside epithelial cells only",
          "Not the described set."],
         ["The bone marrow and thymus only",
          "Those are where adaptive cells are produced, not where encounters occur."]],
   c=0, cite=c(62)),
 # ---------------- granulocytes ----------------
 dict(topic="Granulocytes", io=IO5,
   q="What percentage of white cells are NEUTROPHILS, and what is their role?",
   opts=[["55 to 90 per cent; they are phagocytes",
          "Correct — lobed nuclei with lavender granules."],
         ["1 to 3 per cent; they are phagocytes",
          "That percentage belongs to eosinophils."],
         ["20 to 35 per cent; they are phagocytes",
          "That percentage belongs to lymphocytes."],
         ["0.5 per cent; they release chemical mediators",
          "That describes basophils."]],
   c=0, cite=c(66)),
 dict(topic="Granulocytes", io=IO5,
   q="What percentage are EOSINOPHILS, and what do they do?",
   opts=[["1 to 3 per cent",
          "Correct — orange granules and a bilobed nucleus. They destroy eukaryotic pathogens and are minor phagocytes."],
         ["55 to 90 per cent; they are the main phagocytes",
          "That is the neutrophil."],
         ["0.5 per cent; they release potent chemical mediators",
          "That is the basophil."],
         ["3 to 7 per cent; they present antigen",
          "That is the monocyte and macrophage."]],
   c=0, cite=c(66)),
 dict(topic="Granulocytes", io=IO5,
   q="What percentage are BASOPHILS, and what is their function?",
   opts=[["0.5 per cent; they release potent chemical mediators",
          "Correct — constricted nuclei with dark blue granules."],
         ["1 to 3 per cent; they destroy eukaryotic pathogens",
          "That is the eosinophil."],
         ["20 to 35 per cent; they produce antibody",
          "That is the lymphocyte, and only B cells produce antibody."],
         ["3 to 7 per cent; they are the largest white cells",
          "That is the monocyte."]],
   c=0, cite=c(66)),
 dict(topic="Granulocytes", io=IO5,
   q="How are mast cells related to basophils?",
   opts=[["Related, but tissue-bound and nonmotile",
          "Correct — the deck says it is unsure whether they share one."],
         ["They are identical cells with different names",
          "They are related but distinct, and mast cells are tissue-bound."],
         ["Mast cells are a type of neutrophil",
          "They are not granulocytes of the neutrophil line."],
         ["They share a confirmed common progenitor",
          "The deck states this is uncertain."]],
   c=0, cite=c(66)),
 # ---------------- agranulocytes ----------------
 dict(topic="Agranulocytes", io=IO5,
   q="What percentage are MONOCYTES and macrophages, and what distinguishes them physically?",
   opts=[["3 to 7 per cent",
          "Correct, and they are phagocytic. They are the largest white cells, with a kidney-shaped nucleus."],
         ["20 to 35 per cent; they have a round nucleus",
          "That is the lymphocyte."],
         ["55 to 90 per cent; they have lobed nuclei",
          "That is the neutrophil."],
         ["0.5 per cent; they have constricted nuclei",
          "That is the basophil."]],
   c=0, cite=c(67)),
 dict(topic="Agranulocytes", io=IO5,
   q="Besides phagocytosis, what three roles do monocytes and macrophages have?",
   opts=[["Cellular housekeeping, antigen presentation to lymphocytes",
          "Correct. Cytokine secretion."],
         ["Antibody production, memory, and complement fixation",
          "Antibody and memory belong to adaptive immunity."],
         ["Clotting, chemotaxis, and opsonisation",
          "Not the three roles named."],
         ["Histamine release, parasite killing, and mucus production",
          "Those belong to other cells entirely."]],
   c=0, cite=c(67)),
 dict(topic="Agranulocytes", io=IO5,
   q="What is a macrophage, developmentally?",
   opts=[["The final differentiation of a monocyte",
          "Correct — and it may take a special designation depending on the tissue. In tissues."],
         ["A neutrophil that has left the blood",
          "Neutrophils remain neutrophils."],
         ["An activated B cell",
          "That becomes a plasma cell."],
         ["A dendritic cell that has matured",
          "Dendritic cells are a separate line."]],
   c=0, cite=c(67)),
 dict(topic="Agranulocytes", io=IO5,
   q="What percentage are LYMPHOCYTES, and which of them belong to INNATE immunity?",
   opts=[["20 to 35 per cent",
          "Correct — B and T cells are adaptive. The non-B non-T lymphocytes, including natural killer cells."],
         ["20 to 35 per cent; the B cells",
          "B cells provide adaptive humoral immunity."],
         ["55 to 90 per cent; the T cells",
          "Wrong percentage, and T cells are adaptive."],
         ["3 to 7 per cent; all of them",
          "Wrong percentage, and only the non-B non-T group is innate."]],
   c=0, cite=c(70)),
 dict(topic="Agranulocytes", io=IO5,
   q="What do activated B cells and activated T cells each do?",
   opts=[["B cells produce antibody",
          "Correct — humoral against cell-mediated. T cells modulate immune function and kill foreign cells."],
         ["B cells kill foreign cells; T cells produce antibody",
          "Reversed."],
         ["Both produce antibody",
          "Only B cells do."],
         ["Both are part of innate immunity",
          "Both are adaptive."]],
   c=0, cite=c(70)),
 # ---------------- differential ----------------
 dict(topic="Differential count", io=IO6,
   q="What does a differential white count actually measure?",
   opts=[["The number of each type of white cell",
          "Correct — proportion is the point, not just the total. Whether they are in normal proportion."],
         ["The total white cell count alone",
          "That is the white count without a differential."],
         ["The haemoglobin concentration",
          "A red cell measure."],
         ["The rate of phagocytosis",
          "Not something the differential measures."]],
   c=0, cite=c(71)),
 dict(topic="Differential count", io=IO6,
   q="Which of these is a use of the differential white count?",
   opts=[["Diagnosing infection types",
          "Correct — six uses. Inflammation, allergies, immune disorders, leukaemia and myelodysplastic syndrome."],
         ["Measuring clotting time",
          "A coagulation test."],
         ["Assessing renal function",
          "A chemistry panel measure."],
         ["Detecting antibody titre",
          "A serological test."]],
   c=0, cite=c(71)),
 # ---------------- phagocytosis ----------------
 dict(topic="Phagocytosis", io=IO5,
   q="Which are the PRIMARY phagocytes?",
   opts=[["Macrophages and neutrophils",
          "Correct — though other leukocytes have been found to be phagocytic too."],
         ["Eosinophils and basophils",
          "The eosinophil is described as a MINOR phagocyte; the basophil releases mediators."],
         ["B cells and T cells",
          "Adaptive lymphocytes."],
         ["Natural killer cells and mast cells",
          "Natural killer cells kill by inducing apoptosis rather than engulfing."]],
   c=0, cite=c(73)),
 dict(topic="Phagocytosis", io=IO5,
   q="How do macrophages and neutrophils differ in lifespan and location?",
   opts=[["Macrophages are long-lived tissue residents",
          "Correct — macrophages raise the alarm, neutrophils answer it. Neutrophils are short-lived and circulate in blood."],
         ["Macrophages are short-lived circulators; neutrophils are long-lived residents",
          "Reversed."],
         ["Both are long-lived tissue residents",
          "Neutrophils are short-lived dedicated killers."],
         ["Both circulate and neither enters tissue",
          "Both reach tissue; the macrophage already lives there."]],
   c=0, cite=c(75)),
 dict(topic="Phagocytosis", io=IO5,
   q="Which cell works as infection begins, and which waits to be called?",
   opts=[["The macrophage works first and raises the alarm",
          "Correct. The neutrophil waits for it to enter tissue."],
         ["The neutrophil works first and calls the macrophage",
          "The order is the other way round."],
         ["Both arrive simultaneously",
          "The macrophage is already resident."],
         ["The dendritic cell works first and calls both",
          "Dendritic cells carry antigen to lymph nodes rather than raising the local alarm."]],
   c=0, cite=c(75)),
 dict(topic="Phagocytosis", io=IO5,
   q="What does NADPH oxidase produce in the respiratory burst, and what does that achieve?",
   opts=[["Superoxide, which raises the pH",
          "Correct — the pH shift is what enables digestion."],
         ["Hydrogen peroxide, which is immediately degraded by catalase",
          "Catalase degrades hydrogen peroxide to LIMIT damage, not as the killing step."],
         ["Nitric oxide, which relaxes the vessel",
          "Not the described product."],
         ["Lysozyme, which digests peptidoglycan",
          "Lysozyme is an enzyme, not a product of the oxidase."]],
   c=0, cite=c(77)),
 dict(topic="Phagocytosis", io=IO5,
   q="How do phagocytes limit damage from toxic oxygen species?",
   opts=[["They synthesise enzymes such as catalase",
          "Correct — toxic species can otherwise diffuse out and harm host cells. Which degrades hydrogen peroxide to water and oxygen."],
         ["They expel the species into the bloodstream",
          "That would spread the damage."],
         ["They stop producing them after one minute",
          "Not the described control."],
         ["They rely on complement to neutralise them",
          "Complement has no such role."]],
   c=0, cite=c(78)),
 dict(topic="Phagocytosis", io=IO5,
   q="Why do neutrophils die after doing their job?",
   opts=[["Granules cannot be replenished",
          "Correct — one use and they are spent."],
         ["They are killed by complement",
          "Complement targets pathogens, and human cells are protected."],
         ["They are consumed by the pathogen",
          "Not the reason given."],
         ["They differentiate into macrophages",
          "Macrophages come from monocytes."]],
   c=0, cite=c(78)),
 dict(topic="Phagocytosis", io=IO5,
   q="What is pus composed of?",
   opts=[["Dead organisms",
          "Correct. Dead neutrophils and dead tissue."],
         ["Serum and fibrin only",
          "Not the described composition."],
         ["Lymph and macrophages",
          "Not the described composition."],
         ["Complement proteins and antibody",
          "Both are present in inflammation but do not constitute pus."]],
   c=0, cite=c(78)),
 dict(topic="Phagocytosis", io=IO5,
   q="What is netosis?",
   opts=[["A neutrophil bursting to form a DNA trap",
          "Correct — the neutrophil extracellular trap."],
         ["A macrophage engulfing a dead neutrophil",
          "That is ordinary phagocytic clean-up."],
         ["A macrophage dying after releasing interleukin 1 beta",
          "That is pyroptosis."],
         ["A natural killer cell inducing apoptosis",
          "A different mechanism in a different cell."]],
   c=0, cite=c(78)),
 dict(topic="Phagocytosis", io=IO5,
   q="What do MAST cells contribute, and against what?",
   opts=[["Tissue residents with histamine granules, against parasites",
          "Correct."],
         ["Circulating cells that produce interferon",
          "That describes plasmacytoid dendritic cells."],
         ["Antigen presentation to T cells",
          "That is the dendritic cell."],
         ["Formation of the membrane attack complex",
          "A complement function."]],
   c=0, cite=c(74)),
 dict(topic="Phagocytosis", io=IO5,
   q="What do EOSINOPHILS defend against, and how?",
   opts=[["The extracellular space against parasites",
          "Correct — tissue residents with antimicrobial molecules and enzymes. Particularly helminths, by releasing granule contents."],
         ["Intracellular viruses, by inducing apoptosis",
          "That is the natural killer cell."],
         ["Bacteria in blood, by opsonisation",
          "Opsonisation is done by proteins, not cells."],
         ["Fungi, by producing interferon",
          "Not an eosinophil function."]],
   c=0, cite=c(74)),
 # ---------------- dendritic cells ----------------
 dict(topic="Dendritic cells", io=IO5,
   q="What is a myeloid dendritic cell's job?",
   opts=[["Patrol tissues, take up antigen",
          "Correct — the bridge to an adaptive response. Transport it to the nearest lymph node for T cells."],
         ["Kill virus-infected cells directly",
          "That is the natural killer cell."],
         ["Produce antibody",
          "That is the plasma cell."],
         ["Form the ciliary escalator",
          "An epithelial structure."]],
   c=0, cite=c(79)),
 dict(topic="Dendritic cells", io=IO5,
   q="Why does it matter whether a dendritic cell matures before reaching the lymph node?",
   opts=[["An immature one activates poorly",
          "Correct — it may mature on the way if stimulated by antigen or inflammatory cytokines."],
         ["An immature one cannot enter the lymph node at all",
          "It can arrive; it just fails to activate effectively."],
         ["A mature one cannot carry antigen",
          "Maturation is what makes it effective."],
         ["Maturity has no bearing on activation",
          "It is the stated difference."]],
   c=0, cite=c(79)),
 # ---------------- NK cells ----------------
 dict(topic="Natural killer cells", io=IO5,
   q="What do natural killer cells kill?",
   opts=[["Cells infected by viruses",
          "Correct — cytotoxic against infected cells. Bacteria or protozoan parasites."],
         ["Free bacteria in plasma",
          "They act on infected CELLS."],
         ["Only cancer cells",
          "Infected cells too."],
         ["Only extracellular parasites",
          "Those are handled by eosinophils and mast cells."]],
   c=0, cite=c(81)),
 dict(topic="Natural killer cells", io=IO5,
   q="Which innate lymphoid cell responds to large extracellular parasites like worms?",
   opts=[["ILC2, at mucosal surfaces", "Correct."],
         ["ILC1, against intracellular pathogens", "ILC1 holds the line against viruses until natural killer cells arrive."],
         ["ILC3, against extracellular bacteria and fungi", "ILC3 is abundant in mucosal tissue and contains gut commensals."],
         ["Lymphoid tissue inducer cells", "Those facilitate development of secondary lymphoid tissue."]],
   c=0, cite=c(81)),
 dict(topic="Natural killer cells", io=IO5,
   q="What does the lymphoid tissue inducer cell do?",
   opts=[["Develops secondary lymphoid tissue", "Correct."],
         ["Kills virus-infected cells", "That is the natural killer cell."],
         ["Responds to helminths at mucosal surfaces", "That is ILC2."],
         ["Produces antibody", "That is the plasma cell."]],
   c=0, cite=c(81)),
 dict(topic="Natural killer cells", io=IO5,
   q="What distinguishes the CD56 dim from the CD56 bright natural killer cell?",
   opts=[["CD56 dim kills virally infected cells",
          "Correct — two effector functions in subpopulations adapted to their tissue. CD56 bright secretes cytokines to maintain inflammation."],
         ["CD56 dim secretes cytokines; CD56 bright kills",
          "Reversed."],
         ["Both only kill",
          "One subpopulation is cytokine-secreting."],
         ["Both only secrete cytokines",
          "One subpopulation is cytotoxic."]],
   c=0, cite=c(82)),
 dict(topic="Natural killer cells", io=IO5,
   q="What do uterine natural killer cells do?",
   opts=[["Enlarge the spiral arteries for the fetus",
          "Correct — specialised CD56 bright cells secreting growth factors and noninflammatory cytokines."],
         ["Kill fetal cells recognised as foreign",
          "The opposite of their described role."],
         ["Produce antibody for the fetus",
          "Not their function."],
         ["Form the placental barrier",
          "Not their described role."]],
   c=0, cite=c(83)),
 dict(topic="Natural killer cells", io=IO5,
   q="What is preeclampsia postulated to involve, in terms of uterine natural killer cells?",
   opts=[["Abnormal killer-cell immunoglobulin-like receptor activity",
          "Correct — a postulated mechanism involving the trophoblast interaction. More inhibitory than activating."],
         ["Excess activating signals and vessel over-enlargement",
          "The imbalance described runs the other way."],
         ["Complete absence of uterine natural killer cells",
          "Not what is postulated."],
         ["Failure of complement regulation",
          "Not the proposed mechanism."]],
   c=0, cite=c(83)),
 dict(topic="Natural killer cells", io=IO5,
   q="By how much does natural killer cytotoxicity rise on exposure to type 1 interferons?",
   opts=[["20 to 100 fold", "Correct."],
         ["About twofold", "Far below the stated rise."],
         ["About tenfold", "Still short of the stated range."],
         ["It does not change", "Interferon markedly increases it."]],
   c=0, cite=c(84)),
 dict(topic="Natural killer cells", io=IO5,
   q="Which stimulus favours natural killer CYTOTOXIC function, and which favours cytokine production?",
   opts=[["Interferons alpha and beta favour cytotoxicity",
          "Correct — the same cell steered two ways. Interleukin 12 favours cytokine production."],
         ["Interleukin 12 favours cytotoxicity; interferons favour cytokine production",
          "Reversed."],
         ["Both favour cytotoxicity equally",
          "They steer different functions."],
         ["Neither affects which function dominates",
          "The deck describes exactly this steering."]],
   c=0, cite=c(84)),
 dict(topic="Natural killer cells", io=IO5,
   q="What is the ONE requirement of natural killer cell receptors?",
   opts=[["They must inhibit the cell from killing healthy self-cells",
          "Correct — killing is a balance of activating against inhibitory signals."],
         ["They must recognise a specific antigen",
          "That is adaptive specificity."],
         ["They must bind complement",
          "Not a requirement described."],
         ["They must be identical on every natural killer cell",
          "Receptor combinations vary."]],
   c=0, cite=c(87)),
 dict(topic="Natural killer cells", io=IO5,
   q="When does a natural killer cell kill its target?",
   opts=[["When activating signals outweigh inhibitory",
          "Correct — infection, malignancy or trauma changes the surface."],
         ["Whenever it contacts any cell",
          "Healthy self-cells are spared."],
         ["Only when antibody is bound",
          "That is a different, antibody-dependent mechanism."],
         ["Only when complement has been fixed",
          "Not the trigger described."]],
   c=0, cite=c(87)),
 dict(topic="Natural killer cells", io=IO5,
   q="How does a natural killer cell kill, and who cleans up?",
   opts=[["Cytotoxic granules induce apoptosis",
          "Correct — the target shrinks and its chromatin condenses."],
         ["It engulfs the target cell whole",
          "That is phagocytosis, which natural killer cells do not perform."],
         ["It fixes complement on the target",
          "Not its mechanism."],
         ["It secretes antibody onto the target",
          "Antibody comes from plasma cells."]],
   c=0, cite=c(89)),
 dict(topic="Natural killer cells", io=IO5,
   q="How do natural killer cells and macrophages cooperate?",
   opts=[["Macrophages recruit and activate natural killer cells",
          "Correct — a reciprocal loop at the infection site. Those return interferon gamma, enhancing macrophage phagocytosis."],
         ["Natural killer cells recruit macrophages, which return interleukin 12",
          "The interferon gamma runs from natural killer cell to macrophage."],
         ["They compete for the same targets",
          "They cooperate rather than compete at the infection site."],
         ["They do not interact",
          "Real cooperation is explicitly described."]],
   c=0, cite=c(90)),
 dict(topic="Natural killer cells", io=IO5,
   q="What happens if natural killer cells cannot contain an infection?",
   opts=[["They call in dendritic cells",
          "Correct — and control passes to T cells."],
         ["The infection is cleared by complement alone",
          "Not the described escalation."],
         ["Nothing further happens",
          "The adaptive system is recruited."],
         ["The macrophage takes over killing",
          "The escalation described is to the adaptive response."]],
   c=0, cite=c(91)),
 # ---------------- induced innate ----------------
 dict(topic="Induced innate response", io=IO3,
   q="Over what interval does the INDUCED innate response operate?",
   opts=[["Four hours to four days", "Correct — after the immediate defences and before adaptive immunity."],
         ["Zero to four hours", "That is the immediate phase."],
         ["Four to fourteen days", "That range belongs to the adaptive response."],
         ["Instantly on contact", "The induced response takes time to develop."]],
   c=0, cite=c(55)),
 dict(topic="Induced innate response", io=IO3,
   q="Is the induced innate response specific to the type of invader?",
   opts=[["No — it is still nonspecific",
          "Correct, though it uses more extensive pattern recognition."],
         ["Yes — it is tailored to each pathogen",
          "That is adaptive immunity."],
         ["Only for viruses",
          "It is nonspecific throughout."],
         ["Only after four days",
          "It remains nonspecific."]],
   c=0, cite=c(57)),
 dict(topic="Induced innate response", io=IO3,
   q="Which three cells carry out the extensive pattern recognition of the induced innate response?",
   opts=[["Macrophages, neutrophils and dendritic cells",
          "Correct."],
         ["B cells, T cells and plasma cells",
          "All adaptive."],
         ["Erythrocytes, platelets and endothelium",
          "Not the recognising cells named."],
         ["Mast cells, eosinophils and basophils",
          "They contribute to defence but are not the three named here."]],
   c=0, cite=c(57)),
 # ---------------- coordination ----------------
 dict(topic="Coordination", io=IO3,
   q="What happens to infection in someone LACKING innate immunity?",
   opts=[["Infections are uncontrolled",
          "Correct — innate immunity is the prerequisite. The adaptive response cannot be deployed."],
         ["Infection is controlled initially but never cleared",
          "That describes lacking ADAPTIVE immunity."],
         ["Infection is cleared normally",
          "It is not."],
         ["Only viral infections are affected",
          "The failure is general."]],
   c=0, cite=c(93)),
 dict(topic="Coordination", io=IO3,
   q="What happens to infection in someone lacking ADAPTIVE immunity?",
   opts=[["Controlled at first, but never cleared",
          "Correct — control without clearance."],
         ["It is uncontrolled from the outset",
          "That describes lacking innate immunity."],
         ["It is cleared normally",
          "Clearance requires both."],
         ["Only bacterial infections are affected",
          "The failure is general."]],
   c=0, cite=c(93)),
 dict(topic="Coordination", io=IO3,
   q="What does the deck cite as evidence that innate immunity is very effective?",
   opts=[["We carry vast resident microbes and stay well",
          "Correct."],
         ["Vaccination protects against most diseases",
          "Vaccination works through adaptive immunity."],
         ["Antibiotics cure most infections",
          "Not the argument made."],
         ["Infections are rare in childhood",
          "Not the argument made."]],
   c=0, cite=c(92)),
 dict(topic="Coordination", io=IO3,
   q="What is the consequence of a rare inheritable defect in an innate immune mechanism?",
   opts=[["A substantial reduction in protection",
          "Correct — which is itself evidence of how much innate immunity is doing."],
         ["No measurable effect",
          "The reduction is described as substantial."],
         ["Only a mild seasonal susceptibility",
          "Understates the stated consequence."],
         ["Complete loss of adaptive immunity",
          "Adaptive immunity is a separate system, though it depends on innate function."]],
   c=0, cite=c(92)),
]
