# -*- coding: utf-8 -*-
# Microbiology Exam 2, Lecture 9 — Cocci of Medical Importance, pool B: the STREPTOCOCCI
# and ENTEROCOCCI (slides 21-53). Same conventions as pool A: four options, key in position 0,
# `org` carries the Appendix 2 coverage axis and is stripped before rendering.
#
# Minutes spoken (local transcript, 59:37 total) put the streptococci at ~26 minutes, the
# largest block of the lecture, so this pool is the largest.
#
# TRUTH CHECKS applied here (the guide carries each one):
#   - slide 38 says group B Streptococcus is treated "usually with IV antibiotics during vaginal
#     delivery; streptomycin is commonly used", and the lecturer said the same of her own
#     delivery. Intrapartum prophylaxis is intravenous PENICILLIN (ampicillin the alternative);
#     streptomycin is not used. No question names the intrapartum drug; the treatment question
#     keys penicillin for groups A and B from slide 44.
#   - slide 30 says superantigens release "tissue necrotic factor"; the cytokine is TUMOR
#     necrosis factor. The superantigen key is the deck's "strong lymphocyte stimulants".
#   - slide 48's "60-70% of all cases of bacterial pneumonia" is a dated textbook figure; no
#     question asks the percentage.
#   - slide 50's "90 different capsular types": more than 100 are now recognized; no question
#     asks the number.
#   - slide 53's two vaccines: the conjugate vaccine for young children is keyed. Current adult
#     schedules also use conjugate vaccines, so no question keys the polysaccharide vaccine as
#     THE adult vaccine. The lecturer's "recommended every year" is not true of pneumococcal
#     vaccines and is not used.
#   - slide 23's "17 groups" (about 20 Lancefield groups are described) is not asked; the
#     lecturer told the class not to dig into the Lancefield letters beyond A and B.
SRC = "PAJ5200.Cocci of Med importance.pptx"
def c(n): return f"{SRC}, Slide {n}"

IO1 = ("1 — Compare and contrast the morphology, medium, laboratory tests, biochemical reactions, "
       "diseases, and methods of treatment, and prevention of cocci of medical importance")
IO2 = "2 — Describe the modes of transmission by which humans acquire cocci of medical importance"

POOL_B = [

# ---- streptococci in general (slides 21-25) ----
dict(topic="Streptococci", io=IO1, org=["strep"],
  q="How do streptococci react in the catalase test?",
  opts=[["Catalase negative",
         "Correct: streptococci do not produce catalase, though they do have a peroxidase system; staphylococci are catalase positive."],
        ["Catalase positive",
         "Catalase positivity is the staphylococcal result, the bubbling with hydrogen peroxide that separates the two genera."],
        ["Coagulase positive",
         "Coagulase positivity identifies Staphylococcus aureus, not a streptococcus."],
        ["Oxidase positive",
         "Cytochrome oxidase is produced by Neisseria; the streptococcal test result to know is catalase negative."]],
  c=0, cite=c(21)),

dict(topic="Streptococci", io=IO1, org=["strep"],
  q="Why do most parasitic streptococci need enriched media to grow?",
  opts=[["They are fastidious",
         "Correct: most parasitic forms are fastidious and require enriched media, growing as small, nonpigmented colonies on blood agar."],
        ["They are salt tolerant",
         "Salt tolerance is staphylococcal; streptococci grow poorly on mannitol salts agar, which is too saline for them."],
        ["They form endospores",
         "Streptococci are non-spore-forming; the need for enriched media comes from being fastidious."],
        ["They are strict anaerobes",
         "Streptococci are facultative anaerobes; the need for enriched media comes from being fastidious."]],
  c=0, cite=c(21)),

dict(topic="Streptococci", io=IO1, org=["strep"],
  q="How do streptococci respond to drying, heat and disinfectants?",
  opts=[["They are very sensitive",
         "Correct: streptococci are very sensitive to drying, heat and disinfectants."],
        ["They are highly resistant",
         "Withstanding extremes of salt, pH and heat describes Staphylococcus aureus; streptococci are very sensitive."],
        ["They survive as spores",
         "Streptococci are non-spore-forming, and they are very sensitive to drying, heat and disinfectants."],
        ["They need them to grow",
         "Streptococci need enriched media to grow; drying, heat and disinfectants kill them readily."]],
  c=0, cite=c(21)),

dict(topic="Streptococci", io=IO1, org=["strep"],
  q="On which medium do streptococci grow poorly?",
  opts=[["Mannitol salts agar",
         "Correct: streptococci do not grow well on mannitol salts agar, which is too saline for them."],
        ["Blood agar",
         "Streptococci grow as small, nonpigmented colonies on blood agar, which also shows their hemolysis."],
        ["Enriched media",
         "Most parasitic streptococci are fastidious and REQUIRE enriched media."],
        ["Chocolate agar",
         "Chocolate agar is one of the media used for Streptococcus pneumoniae, alongside blood agar."]],
  c=0, cite=c(21)),

dict(topic="Streptococci", io=IO1, org=["strep"],
  q="On what is the Lancefield classification of streptococci based?",
  opts=[["Cell wall carbohydrate antigens",
         "Correct: Lancefield groups (A, B, C and so on, after Rebecca Lancefield, 1933) rest on cell wall antigens, the C-carbohydrates."],
        ["Patterns of hemolysis",
         "Hemolysis is the OTHER classification system, often combined with deoxyribonucleic acid sequence analysis."],
        ["Ribosomal gene sequences",
         "16S ribosomal RNA gene sequencing is a later method used alongside hemolysis, not the basis of the Lancefield groups."],
        ["Capsular serotype numbers",
         "Capsular types are how Streptococcus pneumoniae varies; Lancefield grouping rests on cell wall carbohydrate antigens."]],
  c=0, cite=c(23)),

dict(topic="Streptococci", io=IO1, org=["strep"],
  q="What is beta hemolysis?",
  opts=[["Complete hemolysis on blood agar",
         "Correct: beta hemolysis is complete hemolysis on a blood agar plate, seen as a clear zone; groups A, B, C, G and some D are beta hemolytic."],
        ["Partial hemolysis, greenish",
         "Partial hemolysis with a greenish color is ALPHA hemolysis, as in Streptococcus pneumoniae and the viridans group."],
        ["No change around colonies",
         "An unchanged plate means no hemolysis at all; beta hemolysis is complete lysis of the red cells."],
        ["Clotting of the blood agar",
         "Clotting is the coagulase reaction of Staphylococcus aureus, tested with plasma rather than read on blood agar."]],
  c=0, cite=c(23)),

dict(topic="Streptococci", io=IO1, org=["viridans", "strep"],
  q="What does the name viridans refer to?",
  opts=[["The greenish partial hemolysis",
         "Correct: viridis is Latin-derived for green, after the greenish color of partial (alpha) hemolysis around the colonies."],
        ["The clear complete hemolysis",
         "Clear, complete hemolysis is beta hemolysis, the reaction of groups A and B; viridans names the green of alpha hemolysis."],
        ["The golden color of colonies",
         "Golden colonies give Staphylococcus aureus its name; viridans refers to green."],
        ["The long chains of cells",
         "Chains are the arrangement of all streptococci; viridans refers to the greenish partial hemolysis."]],
  c=0, cite=c(23)),

dict(topic="Streptococci", io=IO1, org=["pneumoniae", "strep"],
  q="Which of these is alpha hemolytic?",
  opts=[["Streptococcus pneumoniae",
         "Correct: Streptococcus pneumoniae and the viridans group are alpha hemolytic, producing partial, greenish hemolysis."],
        ["Streptococcus pyogenes",
         "Streptococcus pyogenes is group A and BETA hemolytic, giving complete hemolysis on blood agar."],
        ["Streptococcus agalactiae",
         "Streptococcus agalactiae is group B and BETA hemolytic, giving complete rather than partial hemolysis."],
        ["Staphylococcus aureus",
         "Staphylococcus aureus produces hemolysins that give beta hemolysis on blood agar."]],
  c=0, cite=c(23)),

dict(topic="Enterococci", io=IO1, org=["enterococcus"],
  q="Which genus was separated from Streptococcus using 16S ribosomal RNA gene analysis?",
  opts=[["Enterococcus",
         "Correct: Enterococcus, along with Lactococcus, was separated from Streptococcus in 1984 using 16S ribosomal RNA gene analysis."],
        ["Neisseria",
         "Neisseria is a Gram-negative genus that was never part of Streptococcus."],
        ["Staphylococcus",
         "Staphylococcus is a separate catalase-positive genus that was never part of Streptococcus."],
        ["Branhamella",
         "Branhamella was reclassified into Moraxella by 16S analysis; it was never part of Streptococcus."]],
  c=0, cite=c(25)),

dict(topic="Enterococci", io=IO2, org=["enterococcus"],
  q="Where do Enterococcus faecalis and the other group D enterococci normally live?",
  opts=[["The human large intestine",
         "Correct: the group D enterococci are normal colonists of the human large intestine."],
        ["The human throat",
         "The throat and nasopharynx are the habitat of Streptococcus pyogenes."],
        ["The gums and teeth",
         "The gums and teeth are where the viridans streptococci are most numerous."],
        ["The anterior nares",
         "The anterior nares are where humans mostly carry Staphylococcus aureus."]],
  c=0, cite=c(39)),

dict(topic="Enterococci", io=IO1, org=["enterococcus"],
  q="Which infections do the enterococci cause, particularly in debilitated persons?",
  opts=[["Urinary, wound and skin",
         "Correct: enterococci cause opportunistic urinary, wound and skin infections, particularly in debilitated persons."],
        ["Meningitis and septicemia",
         "Meningitis with septicemia is the picture of Neisseria meningitidis, or of group B Streptococcus in newborns."],
        ["Pharyngitis and scarlet fever",
         "Pharyngitis and scarlet fever belong to group A Streptococcus pyogenes."],
        ["Caries and periodontitis",
         "Dental caries, gingivitis and periodontitis are linked to the viridans streptococci."]],
  c=0, cite=c(39)),

dict(topic="Enterococci", io=IO1, org=["enterococcus"],
  q="How is enterococcal infection usually treated?",
  opts=[["Multiple antibiotic therapy",
         "Correct: enterococcal infection treatment usually requires multiple antibiotic therapy."],
        ["Penicillin alone",
         "Penicillin alone is the common treatment for groups A and B streptococci, not for enterococci."],
        ["Surgical drainage",
         "Surgical perforation is the management of staphylococcal abscesses."],
        ["A conjugate vaccine",
         "A conjugate vaccine is given to young children against Streptococcus pneumoniae."]],
  c=0, cite=c(44)),

# ---- Streptococcus pyogenes (slides 27-37) ----
dict(topic="Streptococcus pyogenes", io=IO1, org=["pyogenes"],
  q="Which streptococcus is the most serious streptococcal pathogen, Lancefield group A?",
  opts=[["Streptococcus pyogenes",
         "Correct: beta-hemolytic Streptococcus pyogenes, group A, is the most serious of the streptococcal pathogens."],
        ["Streptococcus agalactiae",
         "Streptococcus agalactiae is group B, the leading cause of neonatal pneumonia, sepsis and meningitis."],
        ["Streptococcus mutans",
         "Streptococcus mutans is a viridans streptococcus behind dental plaque and caries."],
        ["Streptococcus pneumoniae",
         "Streptococcus pneumoniae is alpha hemolytic and is not assigned a Lancefield group."]],
  c=0, cite=c(27)),

dict(topic="Streptococcus pyogenes", io=IO2, org=["pyogenes"],
  q="What is the reservoir of Streptococcus pyogenes?",
  opts=[["Humans only",
         "Correct: it is strictly a human parasite, and humans are the only reservoir; other streptococci may be zoonotic."],
        ["Farm animals",
         "Animal sources describe some other streptococci, such as groups C and G, which are common animal flora."],
        ["Arid soil",
         "Soil is no reservoir of Streptococcus pyogenes; it is strictly a human parasite, and humans are its only reservoir."],
        ["Fomites",
         "Fomites can TRANSMIT Streptococcus pyogenes, but the reservoir is humans alone."]],
  c=0, cite=c(32)),

dict(topic="Streptococcus pyogenes", io=IO2, org=["pyogenes"],
  q="Which streptococcus is strictly a human parasite, inhabiting the throat, nasopharynx and occasionally the skin?",
  opts=[["Streptococcus pyogenes",
         "Correct: group A Streptococcus pyogenes is strictly a human parasite, and humans are its only reservoir."],
        ["Streptococcus agalactiae",
         "Streptococcus agalactiae, group B, is found in the cow udder as well as the human vagina, so it is not strictly a human parasite."],
        ["Enterococcus faecalis",
         "Enterococcus faecalis colonizes the human and animal intestine rather than being a strictly human throat parasite."],
        ["Streptococcus mutans",
         "Streptococcus mutans lives in the oral cavity on the teeth, where its slime layers build plaque."]],
  c=0, cite=c(27)),

dict(topic="Streptococcus pyogenes", io=IO2, org=["pyogenes"],
  q="Which is a route of Streptococcus pyogenes transmission?",
  opts=[["Respiratory droplets",
         "Correct: transmission is by contact, droplets, food and fomites."],
        ["Tick bites",
         "No arthropod route is listed; Streptococcus pyogenes spreads by contact, droplets, food and fomites."],
        ["Arid desert soil",
         "No soil route is described; humans are the only reservoir, and spread is by contact, droplets, food and fomites."],
        ["The birth canal",
         "Passage through the birth canal is how group B Streptococcus and the gonococcus reach newborns."]],
  c=0, cite=c(32)),

dict(topic="Streptococcus pyogenes", io=IO2, org=["pyogenes"],
  q="What is the usual portal of entry for Streptococcus pyogenes?",
  opts=[["Skin or pharynx",
         "Correct: the portal of entry is generally the skin or the pharynx, matching its skin and throat infections."],
        ["Urinary tract",
         "The urinary tract is a site of enterococcal and Staphylococcus saprophyticus infection."],
        ["Eustachian tube",
         "The eustachian tube is how Streptococcus pneumoniae reaches the middle ear."],
        ["Large intestine",
         "The large intestine is the normal home of the enterococci; Streptococcus pyogenes enters through skin or pharynx."]],
  c=0, cite=c(32)),

dict(topic="Streptococcus pyogenes", io=IO2, org=["pyogenes"],
  q="Which group is predominantly affected by Streptococcus pyogenes skin and throat infections?",
  opts=[["Children",
         "Correct: children are the predominant group affected for both cutaneous and throat infections."],
        ["Newborns",
         "Newborns are the group at risk from group B Streptococcus acquired during vaginal delivery."],
        ["The elderly",
         "The elderly are among those at greatest risk of Streptococcus pneumoniae rather than of group A disease."],
        ["College students",
         "Young adults in dormitories are a high-risk group for Neisseria meningitidis."]],
  c=0, cite=c(32)),

dict(topic="Streptococcus pyogenes", io=IO1, org=["pyogenes"],
  q="What does M-protein contribute to Streptococcus pyogenes?",
  opts=[["Resistance to phagocytosis",
         "Correct: M-protein contributes to its resistance to phagocytosis."],
        ["Protection from lysozyme",
         "Protection against lysozyme comes from the C-carbohydrates; M-protein resists phagocytosis instead."],
        ["Adherence by short fibers",
         "Short protein fibers for adherence are the fimbriae, a separate surface antigen from the one asked about."],
        ["Blocking of complement",
         "Hindering complement and the neutrophil response is the job of C5a protease."]],
  c=0, cite=c(28)),

dict(topic="Streptococcus pyogenes", io=IO1, org=["pyogenes"],
  q="Which Streptococcus pyogenes surface antigen contributes most to its resistance to phagocytosis?",
  opts=[["M-protein",
         "Correct: M-protein contributes to the resistance of Streptococcus pyogenes to phagocytosis."],
        ["C-carbohydrate",
         "The C-carbohydrates protect against lysozyme and are the basis of the Lancefield groups."],
        ["Fimbriae",
         "Fimbriae are short protein fibers that give adherence rather than resistance to phagocytosis."],
        ["Streptolysin S",
         "Streptolysin S is a hemolysin that causes cell and tissue injury rather than a surface antigen."]],
  c=0, cite=c(28)),

dict(topic="Streptococcus pyogenes", io=IO1, org=["pyogenes"],
  q="Which Streptococcus pyogenes surface component protects it against lysozyme?",
  opts=[["C-carbohydrates",
         "Correct: the C-carbohydrates protect it against lysozyme, and they are also the antigens rapid tests detect."],
        ["M-protein",
         "M-protein contributes to resistance to phagocytosis rather than to lysozyme."],
        ["Fimbriae",
         "Fimbriae are short protein fibers for adherence; protection against lysozyme comes from the C-carbohydrates."],
        ["C5a protease",
         "C5a protease hinders the complement and neutrophil response."]],
  c=0, cite=c(28)),

dict(topic="Streptococcus pyogenes", io=IO1, org=["pyogenes"],
  q="Why is the hyaluronic acid capsule of Streptococcus pyogenes an advantage to it?",
  opts=[["It provokes little immune response",
         "Correct: the hyaluronic acid capsule looks like the body's own hyaluronic acid, so it provokes little immune response."],
        ["It digests fibrin clots",
         "Digesting fibrin clots is streptokinase, an extracellular enzyme rather than the capsule."],
        ["It lyses red blood cells",
         "Lysing red cells is the work of the streptolysins, the hemolysins of Streptococcus pyogenes."],
        ["It cleaves secretory IgA",
         "Cleaving secretory immunoglobulin A is the IgA protease of Neisseria."]],
  c=0, cite=c(28)),

dict(topic="Streptococcus pyogenes", io=IO1, org=["pyogenes"],
  q="Which Streptococcus pyogenes toxin induces fever and the typical red rash?",
  opts=[["Erythrogenic toxin",
         "Correct: erythrogenic (pyrogenic) toxin induces fever and the typical red rash, the toxin behind scarlet fever."],
        ["Streptolysin O",
         "Streptolysin O is a hemolysin that causes cell and tissue injury rather than the rash."],
        ["Streptokinase",
         "Streptokinase is an extracellular enzyme that digests fibrin clots; the fever and rash come from erythrogenic toxin."],
        ["Hyaluronidase",
         "Hyaluronidase is an enzyme that breaks down connective tissue."]],
  c=0, cite=c(30)),

dict(topic="Streptococcus pyogenes", io=IO1, org=["pyogenes"],
  q="What are the superantigens of Streptococcus pyogenes?",
  opts=[["Strong lymphocyte stimulants",
         "Correct: superantigens are strong monocyte and lymphocyte stimulants that cause the release of tumor necrosis factor."],
        ["Fibrin-digesting enzymes",
         "Digesting fibrin clots is the enzyme streptokinase; superantigens strongly stimulate monocytes and lymphocytes."],
        ["Red cell hemolysins",
         "The hemolysins are streptolysin O and streptolysin S, which injure cells; superantigens are immune stimulants."],
        ["Adhesive surface fibers",
         "Short protein fibers for adherence are the fimbriae, a separate surface antigen from the one asked about."]],
  c=0, cite=c(30)),

dict(topic="Streptococcus pyogenes", io=IO1, org=["pyogenes"],
  q="What are streptolysin O and streptolysin S?",
  opts=[["Hemolysins",
         "Correct: the streptolysins are hemolysins, and both cause cell and tissue injury."],
        ["Fibrinolysins",
         "Fibrin clots are digested by streptokinase, an extracellular enzyme, not by the streptolysins."],
        ["Superantigens",
         "Superantigens are strong monocyte and lymphocyte stimulants, a separate class of toxin."],
        ["Adhesins",
         "Adherence is the role of the fimbriae, short protein fibers on the surface."]],
  c=0, cite=c(30)),

dict(topic="Streptococcus pyogenes", io=IO1, org=["pyogenes"],
  q="Which Streptococcus pyogenes enzyme digests fibrin clots?",
  opts=[["Streptokinase",
         "Correct: streptokinase digests fibrin clots, alongside hyaluronidase and deoxyribonuclease among its extracellular enzymes."],
        ["Hyaluronidase",
         "Hyaluronidase breaks down connective tissue; the fibrin-digesting enzyme is streptokinase."],
        ["Deoxyribonuclease",
         "Deoxyribonuclease is the extracellular enzyme that hydrolyzes deoxyribonucleic acid rather than fibrin."],
        ["Coagulase",
         "Coagulase forms clots rather than digesting them, and it belongs to Staphylococcus aureus."]],
  c=0, cite=c(31)),

dict(topic="Streptococcus pyogenes", io=IO1, org=["pyogenes"],
  q="Which streptococcal skin infection forms a highly contagious crust and often occurs in epidemics in schoolchildren?",
  opts=[["Impetigo",
         "Correct: streptococcal impetigo (pyoderma) is superficial lesions that break and form a highly contagious crust."],
        ["Erysipelas",
         "Erysipelas enters through a break in the skin and spreads into the dermis and subcutaneous tissues."],
        ["Folliculitis",
         "Folliculitis is a staphylococcal inflammation of the hair follicle."],
        ["Carbuncle",
         "A carbuncle is a deep staphylococcal lesion made of interconnected furuncles."]],
  c=0, cite=c(33)),

dict(topic="Streptococcus pyogenes", io=IO1, org=["pyogenes"],
  q="Which streptococcal infection enters through a break in the skin and spreads to the dermis and subcutaneous tissues?",
  opts=[["Erysipelas",
         "Correct: erysipelas enters through a break in the skin, spreads to the dermis and subcutaneous tissues, and can remain superficial or become systemic."],
        ["Impetigo",
         "Impetigo is SUPERFICIAL lesions that break and form a contagious crust."],
        ["Scarlet fever",
         "Scarlet fever is a systemic infection from a strain carrying the erythrogenic toxin gene."],
        ["Folliculitis",
         "Folliculitis is staphylococcal inflammation of a hair follicle."]],
  c=0, cite=c(33)),

dict(topic="Streptococcus pyogenes", io=IO1, org=["pyogenes"],
  q="What makes a Streptococcus pyogenes strain able to cause scarlet fever?",
  opts=[["A prophage for erythrogenic toxin",
         "Correct: scarlet fever strains carry a prophage that codes for erythrogenic toxin, and this can lead to sequelae."],
        ["A plasmid for penicillinase",
         "Penicillinase inactivates penicillin; it is a resistance enzyme, not the basis of scarlet fever."],
        ["A capsule of hyaluronic acid",
         "The hyaluronic acid capsule provokes little immune response, but it is not what produces scarlet fever."],
        ["An extra layer of M-protein",
         "M-protein resists phagocytosis; scarlet fever depends on a prophage coding erythrogenic toxin."]],
  c=0, cite=c(36)),

dict(topic="Streptococcus pyogenes", io=IO1, org=["pyogenes"],
  q="Which long-term complication of group A streptococcal infection follows pharyngitis and can cause extensive heart valve damage?",
  opts=[["Rheumatic fever",
         "Correct: rheumatic fever follows overt or subclinical pharyngitis in children, with carditis, arthritis, chorea and fever."],
        ["Glomerulonephritis",
         "Acute glomerulonephritis is the KIDNEY complication: nephritis, raised blood pressure, occasionally heart failure."],
        ["Scarlet fever",
         "Scarlet fever is a systemic infection from an erythrogenic-toxin strain, not the valve-damaging sequela itself."],
        ["Subacute endocarditis",
         "Subacute endocarditis is the most serious viridans infection, from blood-borne bacteria settling on the valves."]],
  c=0, cite=c(37)),

dict(topic="Streptococcus pyogenes", io=IO1, org=["pyogenes"],
  q="Which group A streptococcal sequela causes nephritis and raised blood pressure and can lead to kidney failure?",
  opts=[["Acute glomerulonephritis",
         "Correct: acute glomerulonephritis causes nephritis and increased blood pressure, and can become chronic, leading to kidney failure."],
        ["Rheumatic fever",
         "Rheumatic fever damages the heart valves and causes arthritis, chorea and fever rather than nephritis."],
        ["Toxic shock syndrome",
         "Streptococcal toxic shock is a systemic infection, not the kidney sequela that can become chronic."],
        ["Urinary tract infection",
         "Urinary tract infection is a direct infection by enterococci or staphylococci, not an immune sequela of group A."]],
  c=0, cite=c(37)),

dict(topic="Streptococcal treatment", io=IO1, org=["pyogenes", "agalactiae"],
  q="How are group A and group B streptococcal infections commonly treated?",
  opts=[["With penicillin",
         "Correct: groups A and B are commonly treated with penicillin unless it is contraindicated by resistance or allergy."],
        ["With vancomycin",
         "Vancomycin is the drug some methicillin-resistant Staphylococcus aureus strains are still susceptible to."],
        ["With surgery alone",
         "Surgical perforation is the management of staphylococcal abscesses."],
        ["With a vaccine",
         "No vaccine is listed for groups A or B; vaccines are listed for the pneumococcus and meningococcus."]],
  c=0, cite=c(44)),

dict(topic="Streptococcal treatment", io=IO1, org=["pyogenes"],
  q="Who may be prescribed long-term penicillin prophylaxis?",
  opts=[["People with past rheumatic fever",
         "Correct: those with a history of rheumatic fever or recurrent strep throat may receive long-term penicillin prophylaxis."],
        ["Every pregnant woman at term",
         "Pregnant women are SCREENED for group B Streptococcus and treated if positive, not all placed on long-term penicillin."],
        ["Every child before dental work",
         "Antibiotics before dental work are now reserved for certain heart conditions, and are not long-term prophylaxis."],
        ["All contacts of gonorrhea cases",
         "Prophylaxis of close contacts is listed for meningococcal disease rather than gonorrhea."]],
  c=0, cite=c(44)),

# ---- group B Streptococcus (slide 38) ----
dict(topic="Streptococcus agalactiae", io=IO1, org=["agalactiae"],
  q="Group B Streptococcus (Streptococcus agalactiae) is the most prevalent cause of which infections?",
  opts=[["Neonatal sepsis and meningitis",
         "Correct: it is the most prevalent cause of neonatal pneumonia, sepsis and meningitis."],
        ["Dental caries and plaque",
         "Dental caries and plaque are linked to Streptococcus mutans, a viridans streptococcus."],
        ["Pharyngitis in schoolchildren",
         "Pharyngitis in children is the classic disease of group A Streptococcus pyogenes."],
        ["Opportunistic urinary infection",
         "Opportunistic urinary infection in debilitated persons is typical of the enterococci."]],
  c=0, cite=c(38)),

dict(topic="Streptococcus agalactiae", io=IO2, org=["agalactiae"],
  q="How does group B Streptococcus reach the newborn?",
  opts=[["During vaginal delivery",
         "Correct: it can be transferred to the infant during vaginal delivery and cause severe infection in the child."],
        ["Across the placenta",
         "Group B Streptococcus lives in the mother's vagina and reaches the infant during vaginal delivery; it is not carried across the placenta."],
        ["By contaminated food",
         "Food is a route for Streptococcus pyogenes and for staphylococcal enterotoxin rather than for neonatal group B infection."],
        ["Through a tooth socket",
         "Dental procedures let viridans streptococci into the blood; group B reaches the newborn during delivery."]],
  c=0, cite=c(38)),

dict(topic="Streptococcus agalactiae", io=IO1, org=["agalactiae"],
  q="What is the preventive step against group B streptococcal infection of newborns?",
  opts=[["Screening and treating mothers",
         "Correct: pregnant women should be screened and treated for group B Streptococcus, with intravenous antibiotics during vaginal delivery."],
        ["Vaccinating infants at birth",
         "No group B vaccine is listed; the measure is screening pregnant women and treating those who are positive."],
        ["Antibiotic eye ointment",
         "Topical antibiotic prophylaxis at birth prevents GONOCOCCAL conjunctivitis rather than group B infection."],
        ["Long-term oral penicillin",
         "Long-term penicillin prophylaxis is for people with a history of rheumatic fever or recurrent strep throat."]],
  c=0, cite=c(38)),

dict(topic="Streptococcus agalactiae", io=IO1, org=["agalactiae"],
  q="A pregnant woman is expected to deliver vaginally. What is recommended for group B Streptococcus?",
  opts=[["Screen her and treat if positive",
         "Correct: pregnant women should be screened and treated, usually with intravenous antibiotics during vaginal delivery."],
        ["Vaccinate the infant at birth",
         "No group B vaccine is listed; protection comes from screening the mother and treating during delivery."],
        ["Plan a routine cesarean",
         "Cesarean delivery is not the listed measure; the mother is screened and, if positive, treated during vaginal delivery."],
        ["Give lifelong penicillin",
         "Long-term penicillin prophylaxis is for people with a history of rheumatic fever or recurrent strep throat."]],
  c=0, cite=c(38)),

dict(topic="Streptococcus agalactiae", io=IO2, org=["agalactiae"],
  q="Where does group B Streptococcus regularly reside in humans?",
  opts=[["The vagina and large intestine",
         "Correct: it regularly resides in the human vagina, pharynx and large intestine."],
        ["The gums and tooth surfaces",
         "The gums and teeth are where the viridans streptococci are most numerous."],
        ["The scalp and external ear",
         "The scalp, face and external ear are the home of Staphylococcus capitis."],
        ["The meninges and spinal fluid",
         "The meninges and cerebrospinal fluid are normally sterile, and are sites of disease rather than residence."]],
  c=0, cite=c(38)),

# ---- viridans group (slides 45-47) ----
dict(topic="Viridans streptococci", io=IO2, org=["viridans"],
  q="How do viridans streptococci usually gain entrance to the body to cause disease?",
  opts=[["Via dental or surgical procedures",
         "Correct: they are not very invasive on their own; dental or surgical procedures may facilitate entrance to the body."],
        ["By invading intact skin",
         "Viridans streptococci are not very invasive on their own; they need a procedure to get in."],
        ["Through the birth canal",
         "Passage through the birth canal is how group B Streptococcus and the gonococcus reach newborns."],
        ["By aspiration into lungs",
         "Aspiration into the lungs is how Streptococcus pneumoniae causes pneumonia."]],
  c=0, cite=c(45)),

dict(topic="Viridans streptococci", io=IO2, org=["viridans"],
  q="Where are the viridans streptococci the most numerous and widespread residents?",
  opts=[["The gums, teeth and mouth",
         "Correct: they are the most numerous residents of the gums, teeth and oral cavity, and are also found in nasopharynx, genital tract and skin."],
        ["The human large intestine",
         "The large intestine is the normal home of the group D enterococci."],
        ["The anterior nares",
         "The anterior nares are where humans mostly carry Staphylococcus aureus."],
        ["The armpits and groin",
         "The armpits and groin are the home of Staphylococcus hominis."]],
  c=0, cite=c(45)),

dict(topic="Viridans streptococci", io=IO1, org=["viridans"],
  q="What is the most serious infection caused by the viridans streptococci?",
  opts=[["Subacute endocarditis",
         "Correct: blood-borne bacteria settle and grow on the heart lining or valves, and colonize them by forming biofilms."],
        ["Rheumatic fever",
         "Rheumatic fever is a sequela of group A pharyngitis rather than a direct viridans infection."],
        ["Scarlet fever",
         "Scarlet fever comes from Streptococcus pyogenes strains carrying the erythrogenic toxin prophage."],
        ["Neonatal meningitis",
         "Neonatal meningitis is most often caused by group B Streptococcus."]],
  c=0, cite=c(46)),

dict(topic="Viridans streptococci", io=IO1, org=["viridans"],
  q="A 62-year-old with pre-existing heart valve disease develops endocarditis weeks after a tooth extraction. Which group of organisms is most likely?",
  opts=[["Viridans streptococci",
         "Correct: a dental procedure lets these oral residents into the blood, and pre-existing heart disease puts the patient at high risk of subacute endocarditis."],
        ["Group A streptococci",
         "Group A Streptococcus damages valves through rheumatic fever after pharyngitis rather than by direct infection after dental work."],
        ["Group B streptococci",
         "Group B Streptococcus can cause endocarditis in debilitated patients, but the dental route points to the oral viridans group."],
        ["Gram-negative diplococci",
         "Gram-negative diplococci are Neisseria, which are not oral residents entering through a tooth socket."]],
  c=0, cite=c(46)),

dict(topic="Viridans streptococci", io=IO1, org=["viridans"],
  q="Which viridans streptococcus produces slime layers that adhere to teeth and form the basis of plaque?",
  opts=[["Streptococcus mutans",
         "Correct: Streptococcus mutans produces slime layers that adhere to teeth, and it is involved in dental caries."],
        ["Streptococcus pneumoniae",
         "Streptococcus pneumoniae is alpha hemolytic but lives in the nasopharynx and causes pneumonia and otitis media."],
        ["Streptococcus pyogenes",
         "Streptococcus pyogenes is group A, causing pharyngitis and skin infection rather than plaque."],
        ["Enterococcus faecalis",
         "Enterococcus faecalis colonizes the large intestine and causes opportunistic urinary, wound and skin infection."]],
  c=0, cite=c(47)),

dict(topic="Viridans streptococci", io=IO1, org=["viridans"],
  q="What is the current practice on prophylactic antibiotics before dental procedures?",
  opts=[["Kept for certain heart conditions",
         "Correct: persons with certain pre-existing heart conditions may receive them, though many dentists have discontinued it except in extreme circumstances."],
        ["Given to every dental patient",
         "Prophylaxis is not universal; it is kept for certain pre-existing heart conditions."],
        ["Given only to young children",
         "The deciding factor is a pre-existing heart condition rather than the patient's age."],
        ["Banned for all dental work",
         "It has not been abandoned; it is still given for certain heart conditions in extreme circumstances."]],
  c=0, cite=c(47)),

# ---- Streptococcus pneumoniae (slides 48-53) ----
dict(topic="Streptococcus pneumoniae", io=IO1, org=["pneumoniae"],
  q="What is the cell morphology of Streptococcus pneumoniae?",
  opts=[["Lancet-shaped cells in pairs",
         "Correct: small, lancet-shaped cells arranged in pairs and short chains."],
        ["Bean-shaped cells in pairs",
         "Bean-shaped Gram-negative diplococci are Neisseria; the pneumococcus is lancet shaped and Gram-positive."],
        ["Spheres in irregular clusters",
         "Spheres in irregular clusters are the staphylococci; the pneumococcus forms lancet-shaped pairs and short chains."],
        ["Spheres in very long chains",
         "Long chains are typical of streptococci such as Streptococcus pyogenes."]],
  c=0, cite=c(48)),

dict(topic="Streptococcus pneumoniae", io=IO1, org=["pneumoniae"],
  q="Streptococcus pneumoniae is capnophilic. What does that mean?",
  opts=[["Favored by carbon dioxide",
         "Correct: capnophilic means carbon dioxide loving; its growth is improved by 5 to 10% carbon dioxide."],
        ["Favored by low oxygen",
         "Needing a low oxygen concentration is microaerophilic, the term used for Neisseria."],
        ["Favored by high salt",
         "Withstanding high salinity describes Staphylococcus aureus; capnophilic means carbon dioxide loving."],
        ["Favored by no oxygen",
         "Growth without oxygen describes anaerobes; Streptococcus pneumoniae is aerotolerant and carbon dioxide loving."]],
  c=0, cite=c(48)),

dict(topic="Streptococcus pneumoniae", io=IO1, org=["pneumoniae"],
  q="Which media are required to culture Streptococcus pneumoniae?",
  opts=[["Blood or chocolate agar",
         "Correct: culture requires blood or chocolate agar, and growth is improved by extra carbon dioxide."],
        ["Mannitol salts agar",
         "Mannitol salts agar is too saline for streptococci; the pneumococcus needs blood or chocolate agar."],
        ["Plain nutrient broth",
         "Streptococci are fastidious and need enriched media; for the pneumococcus that means blood or chocolate agar."],
        ["Bile esculin agar",
         "Bile esculin hydrolysis is an identification test listed for streptococci, not the culture medium for the pneumococcus."]],
  c=0, cite=c(48)),

dict(topic="Streptococcus pneumoniae", io=IO1, org=["pneumoniae"],
  q="Why may Streptococcus pneumoniae cultures die when exposed to high levels of laboratory oxygen?",
  opts=[["They lack catalase and peroxidase",
         "Correct: they are aerotolerant anaerobes lacking catalase and peroxidases, so high laboratory oxygen can kill cultures."],
        ["They lack a cell wall entirely",
         "Streptococcus pneumoniae is a Gram-positive coccus with a cell wall; the problem is the missing catalase and peroxidases."],
        ["They lack a protective capsule",
         "All pathogenic strains form LARGE capsules; the oxygen sensitivity comes from lacking catalase and peroxidases."],
        ["They form spores in oxygen",
         "Streptococci are non-spore-forming; the oxygen sensitivity comes from lacking catalase and peroxidases."]],
  c=0, cite=c(48)),

dict(topic="Streptococcus pneumoniae", io=IO1, org=["pneumoniae"],
  q="What is the major virulence factor of Streptococcus pneumoniae?",
  opts=[["Its large capsule",
         "Correct: all pathogenic strains form large capsules, and the capsule is the major virulence factor."],
        ["Its M-protein",
         "M-protein, resisting phagocytosis, is a virulence factor of Streptococcus pyogenes."],
        ["Its coagulase",
         "Coagulase is the diagnostic enzyme of Staphylococcus aureus."],
        ["Its endotoxin",
         "Endotoxin comes from Gram-negative cells such as Neisseria meningitidis, not from a Gram-positive coccus."]],
  c=0, cite=c(50)),

dict(topic="Streptococcus pneumoniae", io=IO1, org=["pneumoniae"],
  q="What varies among the capsular types of Streptococcus pneumoniae?",
  opts=[["Its specific soluble substance",
         "Correct: the specific soluble substance of the capsule varies among types, which is why there are many different capsular types."],
        ["Its Lancefield group letter",
         "Streptococcus pneumoniae carries no Lancefield group; its types are capsular."],
        ["Its Gram stain reaction",
         "Every type is a Gram-positive coccus; what varies is the specific soluble substance of the capsule."],
        ["Its hemolysis pattern",
         "Streptococcus pneumoniae is alpha hemolytic throughout; what varies is the capsule's specific soluble substance."]],
  c=0, cite=c(50)),

dict(topic="Streptococcus pneumoniae", io=IO1, org=["pneumoniae"],
  q="Besides pneumococcal pneumonia, which disease is Streptococcus pneumoniae a causative agent of?",
  opts=[["Otitis media",
         "Correct: it causes pneumococcal pneumonia and otitis media, reaching the middle ear by the eustachian tube."],
        ["Gonorrhea",
         "Gonorrhea is caused by Neisseria gonorrhoeae, a Gram-negative diplococcus, not by the pneumococcus."],
        ["Dental caries",
         "Dental caries involves Streptococcus mutans, a viridans streptococcus."],
        ["Impetigo",
         "Impetigo is a skin infection of Staphylococcus aureus and Streptococcus pyogenes."]],
  c=0, cite=c(50)),

dict(topic="Streptococcus pneumoniae", io=IO2, org=["pneumoniae"],
  q="How does Streptococcus pneumoniae reach the middle ear?",
  opts=[["Via the eustachian tube",
         "Correct: it gains access to the middle ear by way of the eustachian tube."],
        ["Via the bloodstream",
         "Spread through the bloodstream to cross the blood-brain barrier is the route of Neisseria meningitidis."],
        ["Via a skin wound",
         "Wounds are a route for staphylococci and Streptococcus pyogenes rather than to the middle ear."],
        ["Via the birth canal",
         "The birth canal transmits group B Streptococcus and the gonococcus to newborns."]],
  c=0, cite=c(52)),

dict(topic="Streptococcus pneumoniae", io=IO2, org=["pneumoniae"],
  q="How does pneumococcal pneumonia begin?",
  opts=[["Cells are aspirated into lungs",
         "Correct: pneumonia occurs when the bacterial cells are aspirated into the lungs of susceptible individuals, where they multiply rapidly."],
        ["Cells are eaten in food",
         "Food is a route for Streptococcus pyogenes and for staphylococcal toxin rather than for pneumococcal pneumonia."],
        ["Cells enter through a device",
         "Medical devices are a source of staphylococcal bacteremia; pneumococcal pneumonia follows aspiration."],
        ["Cells cross the placenta",
         "Pneumococcal pneumonia begins with aspiration of the organism into the lungs."]],
  c=0, cite=c(52)),

dict(topic="Streptococcus pneumoniae", io=IO2, org=["pneumoniae"],
  q="Pneumococcal infections are usually endogenous. What does that mean?",
  opts=[["From the person's own flora",
         "Correct: 5 to 50% of people carry it in the nasopharynx, and infection usually comes from that carriage, especially if the host is immunocompromised."],
        ["From contaminated surfaces",
         "It is a very delicate bacterium that does not survive long outside its habitat, so surfaces are not the usual source."],
        ["From an animal reservoir",
         "No animal reservoir is described; the source is the person's own nasopharyngeal flora."],
        ["From another patient's blood",
         "Blood exposure is not the route; endogenous means the infection comes from the host's own flora."]],
  c=0, cite=c(51)),

dict(topic="Streptococcus pneumoniae", io=IO2, org=["pneumoniae"],
  q="Who is at greatest risk of Streptococcus pneumoniae infection?",
  opts=[["Young children and the elderly",
         "Correct: those at greatest risk include young children, the elderly, the immune compromised, those with other lung or viral disease, and people in close quarters."],
        ["Healthy young athletes",
         "Healthy adults are not a listed risk group; risk centers on the very young, the elderly and the compromised."],
        ["Women using tampons",
         "Tampon use is classically associated with staphylococcal toxic shock syndrome."],
        ["Military burn patients",
         "Military hospitals are where Acinetobacter baumannii became an important hospital-acquired infection."]],
  c=0, cite=c(51)),

dict(topic="Streptococcus pneumoniae", io=IO1, org=["pneumoniae"],
  q="Which pneumococcal vaccine is given to children 2 to 23 months old?",
  opts=[["The conjugate vaccine",
         "Correct: the conjugate vaccine is for children 2 to 23 months old."],
        ["The polysaccharide vaccine",
         "The capsular antigen (polysaccharide) vaccine has been the option for older adults and other high-risk individuals, not for infants."],
        ["A live attenuated vaccine",
         "No live pneumococcal vaccine is listed; the two vaccines are a capsular antigen vaccine and a conjugate vaccine."],
        ["A toxoid vaccine",
         "The pneumococcal vaccines target the capsule; no toxoid vaccine is listed."]],
  c=0, cite=c(53)),

dict(topic="Streptococcus pneumoniae", io=IO1, org=["pneumoniae"],
  q="What problem now affects the traditional treatment of pneumococcal infection?",
  opts=[["Rising penicillin resistance",
         "Correct: it was traditionally treated with penicillin G or V, but drug resistance is increasing."],
        ["No vaccine exists for it",
         "Two vaccines are available for high-risk individuals, a capsular antigen vaccine and a conjugate vaccine."],
        ["It cannot be cultured",
         "It can be cultured on blood or chocolate agar with extra carbon dioxide."],
        ["It forms resistant spores",
         "Streptococci are non-spore-forming; the problem is rising penicillin resistance."]],
  c=0, cite=c(53)),

# ---- identification (slides 24, 40-43) ----
dict(topic="Identification", io=IO1, org=["pyogenes", "strep"],
  q="A beta-hemolytic streptococcus is bacitracin sensitive. What is it most likely to be?",
  opts=[["Streptococcus pyogenes",
         "Correct: bacitracin-sensitive beta-hemolytic streptococci are group A, Streptococcus pyogenes."],
        ["Streptococcus agalactiae",
         "Group B streptococci, Streptococcus agalactiae, are bacitracin RESISTANT, as are group C."],
        ["Streptococcus pneumoniae",
         "Streptococcus pneumoniae is ALPHA hemolytic and is picked out by optochin sensitivity."],
        ["Streptococcus mutans",
         "Streptococcus mutans belongs to the viridans group, which is alpha hemolytic and optochin resistant."]],
  c=0, cite=c(24)),

dict(topic="Identification", io=IO1, org=["pneumoniae", "strep"],
  q="An alpha-hemolytic streptococcus is optochin sensitive. Which organism is it?",
  opts=[["Streptococcus pneumoniae",
         "Correct: among alpha-hemolytic streptococci, optochin sensitivity identifies Streptococcus pneumoniae."],
        ["Viridans streptococci",
         "The viridans streptococci are alpha hemolytic but optochin RESISTANT, grouped with the group D streptococci."],
        ["Streptococcus pyogenes",
         "Streptococcus pyogenes is BETA hemolytic and identified by bacitracin sensitivity."],
        ["Streptococcus agalactiae",
         "Streptococcus agalactiae is beta hemolytic and bacitracin resistant."]],
  c=0, cite=c(24)),

dict(topic="Identification", io=IO1, org=["agalactiae", "strep"],
  q="Which beta-hemolytic streptococci are bacitracin resistant?",
  opts=[["Groups B and C",
         "Correct: bacitracin-resistant beta-hemolytic streptococci are groups B and C."],
        ["Group A only",
         "Group A, Streptococcus pyogenes, is the bacitracin-SENSITIVE beta-hemolytic group."],
        ["The viridans group",
         "The viridans group is alpha hemolytic, sorted by optochin rather than bacitracin."],
        ["The pneumococci",
         "The pneumococci are ALPHA hemolytic and optochin sensitive, so bacitracin does not sort them."]],
  c=0, cite=c(24)),

dict(topic="Identification", io=IO1, org=["strep", "pyogenes"],
  q="Rapid diagnostic tests for streptococci use monoclonal antibodies that react with what?",
  opts=[["C-carbohydrates",
         "Correct: rapid tests use monoclonal antibodies against the C-carbohydrates, a serological or immunological method."],
        ["M-protein",
         "M-protein resists phagocytosis; the rapid tests target the C-carbohydrates."],
        ["Hemolysins",
         "Hemolysins are read on blood agar, a phenotypic method, not detected by the rapid antibody tests."],
        ["Catalase",
         "Streptococci do not produce catalase, and the catalase test uses hydrogen peroxide rather than antibodies."]],
  c=0, cite=c(40)),

dict(topic="Identification", io=IO1, org=["strep"],
  q="Which of these is a phenotypic culture test used to identify streptococci?",
  opts=[["Bile esculin hydrolysis",
         "Correct: culture with the bacitracin disc test, the CAMP test and bile esculin hydrolysis are the phenotypic methods."],
        ["Monoclonal antibody test",
         "Monoclonal antibodies against C-carbohydrates are the serological or immunological method."],
        ["Ribosomal gene sequencing",
         "16S ribosomal RNA gene sequencing is a genotypic method, used alongside hemolysis classification."],
        ["Spinal fluid Gram stain",
         "Gram staining cerebrospinal fluid is part of the clinical diagnosis of Neisseria meningitidis."]],
  c=0, cite=c(40)),

dict(topic="Identification", io=IO1, org=["strep"],
  q="In the CAMP test, the CAMP-factor protein works synergistically with what?",
  opts=[["Beta-hemolytic Staphylococcus aureus",
         "Correct: the CAMP factor works synergistically with beta-hemolytic Staphylococcus aureus to produce a flame or arrow shape on blood agar."],
        ["A disc of bacitracin antibiotic",
         "Bacitracin discs test sensitivity among beta-hemolytic streptococci; they are not the CAMP partner."],
        ["A disc of optochin reagent",
         "Optochin discs separate Streptococcus pneumoniae from other alpha-hemolytic streptococci."],
        ["Drops of hydrogen peroxide",
         "Hydrogen peroxide is the catalase test reagent, not part of the CAMP test."]],
  c=0, cite=c(43)),

dict(topic="Identification", io=IO1, org=["strep"],
  q="What does a positive CAMP test look like on a blood agar plate?",
  opts=[["A flame or arrow shape",
         "Correct: the synergy between the CAMP factor and beta-hemolytic Staphylococcus aureus produces a flame or arrow shape."],
        ["Bubbles on a glass slide",
         "Bubbles with hydrogen peroxide are a positive catalase test."],
        ["A greenish colony halo",
         "A greenish zone around colonies is alpha, partial, hemolysis rather than the CAMP reaction."],
        ["A clot in the plasma",
         "A clot in plasma is a positive coagulase test for Staphylococcus aureus."]],
  c=0, cite=c(43)),

dict(topic="Identification", io=IO1, org=["strep"],
  q="Which organism has the CAMP technique detected effectively in food and clinical specimens?",
  opts=[["Listeria monocytogenes",
         "Correct: the technique has been effective in detecting Listeria monocytogenes, a Gram-positive rod with a temperature range of 0 to 40 degrees Celsius."],
        ["Neisseria gonorrhoeae",
         "Neisseria gonorrhoeae is identified presumptively by Gram-negative diplococci inside neutrophils."],
        ["Streptococcus mutans",
         "Streptococcus mutans is a viridans streptococcus found on the teeth."],
        ["Acinetobacter baumannii",
         "Acinetobacter baumannii is a multidrug-resistant coccobacillus, an important hospital-acquired infection in military hospitals."]],
  c=0, cite=c(43)),
]
