# -*- coding: utf-8 -*-
# Microbiology Exam 2, Lecture 10 — Gram-Positive Bacilli of Medical Importance
# (Dr. Webster), pool A: the scheme and the SPORE-FORMERS (deck slides 4-49):
# Bacillus anthracis, Bacillus cereus, Clostridium perfringens, Clostridium
# tetani, Clostridium botulinum and Clostridioides difficile.
#
# The deck file is named "Lecture 9 Dr. Webster ..." but the calendar row and the
# recording make it Lecture 10 (the deck names no number on its title slide).
#
# Four options throughout. KEYS SHORT and explanations FULL on the first pass.
#
# SCOPE, from the recording (both transcripts agree):
#   * "I'm not going to be testing you on the percentages. But you do need to
#     know what is the most common, what's the deadliest, how the different
#     things work." [part 1, 12:34] -> no question turns on a percentage, a
#     mortality figure or a case count.
#   * "I'm not going to be asking you what antibiotics to use to treat these
#     things because that's what we have our PDRs for" [part 2, 8:03] -> no
#     question asks which antibiotic. Antitoxin, debridement, hyperbaric oxygen,
#     ventilators, fecal transplant and vaccines are still "methods of treatment
#     and prevention" and ARE asked.
#   * Myonecrosis toxins: "at least 17 different ones and I'm not going to ask
#     you to name them, but look at the things they do" [part 1, 24:39].
#
# The syllabus gives this lecture TWO numbered objectives; objective 1 carries
# most of the deck, objective 2 (transmission) is tagged wherever a question
# asks how the organism is acquired.
SRC = "Lecture 9 Dr. Webster Gram positive Bacilli.pptx"
def c(n): return f"{SRC}, Slide {n}"

IO1 = ("1 — Compare and contrast the morphology, medium, laboratory tests, biochemical reactions, "
       "diseases, clinical manifestations, methods of treatment, and prevention of Gram-positive "
       "bacilli of medical importance")
IO2 = ("2 — Describe the modes of transmission by which humans acquire Gram-positive bacilli of "
       "medical importance")
IMG = "micro-exam-2-quiz-images"

POOL_A = [

# ---------------------------------------------------------------- the scheme
dict(topic="Classification", io=IO1,
  q="Medically important Gram-positive bacilli are divided into three groups by which two properties?",
  opts=[["Spores and acid-fastness",
         "Correct: spore-formers split from non-spore-formers first, and the irregular non-spore-formers then split by whether they are acid-fast."],
        ["Capsules and motility",
         "Capsules and flagella vary within every group (Listeria is motile, Bacillus anthracis has a capsule); the groups rest on endospores and acid-fastness."],
        ["Oxygen use and catalase",
         "Oxygen use and catalase separate Bacillus from Clostridium inside the spore-formers rather than defining the three general groups."],
        ["Cell size and colony color",
         "Cell size and colony color are not the dividing properties; the groups are defined by endospore formation and acid-fast staining."]],
  c=0, cite=c(4)),

dict(topic="Classification", io=IO1,
  q="In the scheme for differentiating Gram-positive bacilli, which genus is an obligately anaerobic spore-former?",
  opts=[["Clostridium",
         "Correct: the spore-formers divide into the aerobic or facultatively anaerobic Bacillus and the obligately anaerobic Clostridium."],
        ["Bacillus",
         "Bacillus is the spore-former that is aerobic or facultatively anaerobic, the other branch from Clostridium."],
        ["Listeria",
         "Listeria forms no spores; it sits with Erysipelothrix among the regular non-spore-formers that stain uniformly."],
        ["Corynebacterium",
         "Corynebacterium forms no spores; it is an irregular, non-acid-fast bacillus alongside Cutibacterium."]],
  c=0, cite=c(5)),

dict(topic="Classification", io=IO1,
  q="Which two genera make up the filamentous, branching Gram-positive bacilli?",
  opts=[["Actinomyces and Nocardia",
         "Correct: both are nonmotile filamentous bacteria related to the mycobacteria, and both can cause chronic skin and soft tissue infection."],
        ["Listeria and Erysipelothrix",
         "Listeria and Erysipelothrix are the regular non-spore-formers, rods that stain uniformly and keep one shape."],
        ["Corynebacterium and Cutibacterium",
         "Corynebacterium and Cutibacterium are irregular but non-acid-fast and not filamentous; they are pleomorphic rods."],
        ["Bacillus and Clostridium",
         "Bacillus and Clostridium are the spore-forming rods rather than filamentous, branching cells."]],
  c=0, cite=c(5)),

dict(topic="Classification", io=IO1,
  q="Which spore positions distinguish Bacillus anthracis from Clostridium tetani?",
  opts=[["Central in Bacillus anthracis, terminal in Clostridium tetani",
         "Correct: Bacillus anthracis carries a centrally located spore, while the spore of Clostridium tetani swells one end of the rod, the drumstick shape."],
        ["Terminal in Bacillus anthracis, central in Clostridium tetani",
         "This reverses the pair: the Bacillus anthracis spore sits in the middle of the cell and the Clostridium tetani spore at one end."],
        ["Central in both, but larger in Clostridium tetani",
         "The two differ in position, not just size: the Bacillus anthracis spore is central and the Clostridium tetani spore is terminal."],
        ["Terminal in both Bacillus anthracis and Clostridium tetani",
         "The Clostridium tetani spore is terminal, but the Bacillus anthracis spore sits in the center of the vegetative cell."]],
  c=0, cite=c(8)),

dict(topic="Classification", io=IO1,
  q="Judging by where the spores sit in the chained, block-shaped rods shown, which genus are they?",
  img=IMG + "/l10-s008.jpg",
  alt="Gram-stained chains of rods containing spores, high magnification.",
  slide="Slide 8",
  opts=[["Bacillus",
         "Correct: the unstained spores sit in the middle of each cell, the central spores of Bacillus anthracis, here in chains of block-shaped rods."],
        ["Clostridium",
         "A terminal clostridial spore, as in Clostridium tetani, swells one end of the rod rather than sitting in the middle of the cell as these do."],
        ["Listeria",
         "Listeria forms no spores at all; it appears as coccobacilli to long filaments with no unstained ovals."],
        ["Mycobacterium",
         "Mycobacteria form no spores and are acid-fast rather than staining well with the Gram stain shown."]],
  c=0, cite=c(8)),

dict(topic="Classification", io=IO1,
  q="Judging by where the spores sit in the rods shown, which genus are they?",
  img=IMG + "/l10-s028.jpg",
  alt="Stained rods containing spores on a yellow background, high magnification.",
  slide="Slide 28",
  opts=[["Clostridium",
         "Correct: the spores swell one end of each rod, the terminal spores of Clostridium tetani with its drumstick shape."],
        ["Bacillus",
         "The Bacillus anthracis spore sits in the center of the cell without swelling it, rather than at one end as these do."],
        ["Lactobacillus",
         "Lactobacillus forms no spores; it is a regular, uniformly staining rod of the normal flora."],
        ["Corynebacterium",
         "Corynebacterium forms no spores; it is pleomorphic, with granules and palisades rather than terminal swellings."]],
  c=0, cite=c(28)),

dict(topic="Classification", io=IO1,
  q="Which pair of traits describes the genus Bacillus?",
  opts=[["Aerobic and catalase positive",
         "Correct: Bacillus is aerobic (aerobic or facultatively anaerobic in the scheme) and catalase positive, the opposite of Clostridium on both counts."],
        ["Anaerobic and catalase negative",
         "Anaerobic and catalase negative describes Clostridium, the other spore-forming genus."],
        ["Acid-fast and strictly aerobic",
         "Acid-fast staining belongs to Mycobacterium, a non-spore-forming irregular bacillus."],
        ["Nonmotile and pleomorphic",
         "The genus is described as motile rods (Bacillus anthracis is the nonmotile exception), and pleomorphism marks the irregular non-spore-formers such as Corynebacterium."]],
  c=0, cite=c(7)),

dict(topic="Classification", io=IO1,
  q="Which pair of traits describes the genus Clostridium?",
  opts=[["Anaerobic and catalase negative",
         "Correct: Clostridium is anaerobic and catalase negative, and produces its oval or spherical spores only under anaerobic conditions."],
        ["Aerobic and catalase positive",
         "Aerobic and catalase positive describes Bacillus, the other spore-forming genus."],
        ["Acid-fast and slow growing",
         "Acid-fast staining and slow growth describe Mycobacterium, which forms no spores."],
        ["Aerotolerant and nontoxigenic",
         "Aerotolerant and nontoxigenic describes Cutibacterium acnes; Clostridium makes some of the most toxic substances known."]],
  c=0, cite=c(19)),

dict(topic="Classification", io=IO1,
  q="Under what conditions does Clostridium produce its spores?",
  opts=[["Only under anaerobic conditions",
         "Correct: the oval or spherical spores are produced only under anaerobic conditions, which fits an anaerobic, catalase-negative genus."],
        ["Only on exposure to oxygen",
         "Oxygen does not trigger sporulation; Clostridium spores are produced only under anaerobic conditions."],
        ["Only inside host macrophages",
         "Clostridium does not sporulate inside macrophages; its spores form under anaerobic conditions, in soil or in dead tissue."],
        ["Only at refrigeration temperature",
         "Growth during refrigeration is the trait of Listeria monocytogenes, which forms no spores at all."]],
  c=0, cite=c(19)),

dict(topic="Classification", io=IO1,
  q="What is the primary habitat of the genus Bacillus?",
  opts=[["Soil",
         "Correct: Bacillus is mostly saprobic, degrades complex macromolecules and lives primarily in soil."],
        ["The human colon",
         "The colon is home to Clostridioides difficile in low numbers, not the primary habitat of Bacillus."],
        ["Pig tonsils",
         "The tonsils of healthy pigs are the reservoir of Erysipelothrix rhusiopathiae rather than of Bacillus."],
        ["Sebaceous glands",
         "Pilosebaceous glands are home to Cutibacterium acnes rather than to Bacillus."]],
  c=0, cite=c(7)),

dict(topic="Classification", io=IO1,
  q="Which antibiotic is produced by members of the genus Bacillus?",
  opts=[["Bacitracin",
         "Correct: Bacillus produces gramicidin, tyrocidine, bacitracin, mycobacillin, surfactin, bacilysin and subtilin."],
        ["Vancomycin",
         "Vancomycin appears here as a treatment for severe Clostridioides difficile infection rather than as a Bacillus product."],
        ["Streptomycin",
         "Streptomycin appears here among the tuberculosis drugs rather than among the antibiotics Bacillus produces."],
        ["Dapsone",
         "Dapsone appears here as a leprosy drug; the Bacillus products include bacitracin, gramicidin and subtilin."]],
  c=0, cite=c(7)),

# --------------------------------------------------------- Bacillus anthracis
dict(topic="Bacillus anthracis", io=IO1,
  q="Why is Bacillus anthracis historically significant?",
  opts=[["It was used to prove Koch's postulates",
         "Correct: Koch's postulates, the method for proving that an organism causes a disease, were developed with Bacillus anthracis and anthrax."],
        ["It was the first organism sequenced",
         "Its significance is Koch's postulates: isolate from every case, grow in pure culture, reproduce the disease, re-isolate."],
        ["It was the source of the first antibiotic",
         "The Bacillus antibiotics (bacitracin, gramicidin) are not its claim to fame; Bacillus anthracis is tied to Koch's postulates."],
        ["It was the first bacterium seen in tissue",
         "Bacillus anthracis matters historically because Koch's postulates were worked out with it and anthrax."]],
  c=0, cite=c(8)),

dict(topic="Bacillus anthracis", io=IO1,
  q="What do Bacillus anthracis cells look like?",
  opts=[["Large, block-shaped rods",
         "Correct: large, block-shaped rods, often in chains, with centrally located spores that do not take up the stain."],
        ["Curved rods in pairs",
         "Bacillus anthracis cells are straight, large and block-shaped rather than curved."],
        ["Branching filaments",
         "Branching filaments are the shape of Actinomyces and Nocardia, the filamentous Gram-positive bacilli."],
        ["Club-shaped rods in palisades",
         "Pleomorphic rods in palisades are Corynebacterium diphtheriae, not the block-shaped Bacillus anthracis."]],
  c=0, cite=c(8)),

dict(topic="Bacillus anthracis", io=IO1,
  q="Why is Bacillus anthracis a Category A priority pathogen?",
  opts=[["It is a potential weapon of bioterrorism",
         "Correct: its spores make it a bioterrorism concern, and an accidental release from a Soviet bioweapon facility in 1979 was highly fatal."],
        ["It is the commonest cause of food poisoning",
         "Bacillus anthracis is not a common food poisoning agent; its Category A status reflects its potential as a weapon of bioterrorism."],
        ["It spreads easily by respiratory droplets",
         "Anthrax is a zoonosis acquired from spores, not by droplets between people; the Category A concern is bioterrorism."],
        ["It resists every class of antibiotic",
         "Anthrax responds to several antibiotics; the Category A designation reflects its potential use as a weapon."]],
  c=0, cite=c(8)),

dict(topic="Bacillus anthracis", io=IO1,
  q="What does protective antigen do in the anthrax exotoxin?",
  opts=[["Creates a receptor site for the other two parts",
         "Correct: protective antigen binds host cells, giving edema factor and lethal factor their receptor site, the glue of the toxin."],
        ["Impairs phagocytosis and blocks monocyte cytokines",
         "Impairing phagocytosis and blocking tumor necrosis factor and interleukin 6 production is the work of edema factor."],
        ["Lyses macrophages, releasing a cytokine surge",
         "Lysing macrophages at high levels, with a flood of cytokines, is the work of lethal factor."],
        ["Coats the cell as a polypeptide capsule",
         "The polypeptide capsule is a separate virulence factor that resists phagocytes, not a component of the exotoxin."]],
  c=0, cite=c(9)),

dict(topic="Bacillus anthracis", io=IO1,
  q="At high levels, what does anthrax lethal factor do to macrophages?",
  opts=[["Lyses them, releasing a surge of cytokines",
         "Correct: at high levels lethal factor is cytolytic for macrophages, releasing interleukin 1, tumor necrosis factor alpha and nitric oxide in bulk."],
        ["Activates them to kill the bacillus",
         "Lethal factor works against the host: at low levels it suppresses cytokine release, at high levels it destroys macrophages."],
        ["Converts them into multinucleate giant cells",
         "Giant cells belong to the tubercle of tuberculosis; anthrax lethal factor lyses macrophages instead."],
        ["Traps them in the lymph nodes",
         "Lethal factor does not trap macrophages; at high levels it lyses them and floods the body with cytokines."]],
  c=0, cite=c(9)),

dict(topic="Bacillus anthracis", io=IO1,
  q="How does anthrax toxin produce a picture resembling septic shock?",
  opts=[["Excessive cytokine release triggers the shock cascade",
         "Correct: when lethal factor lyses macrophages, the massive release of interleukin 1, tumor necrosis factor alpha and nitric oxide drives inflammation and shock."],
        ["The toxin blocks acetylcholine release at the junction",
         "Blocking acetylcholine release at the neuromuscular junction is how botulinum toxin paralyzes, not how anthrax causes shock."],
        ["The bacilli multiply inside red cells and lyse them",
         "Bacillus anthracis does not live in red cells; its shock comes from the cytokine flood after macrophage lysis."],
        ["The capsule clogs the small vessels of the lung",
         "The capsule resists phagocytosis; the shock comes from excessive cytokine release, as in septic shock."]],
  c=0, cite=c(9)),

dict(topic="Bacillus anthracis", io=IO1,
  q="Which is the most common form of anthrax?",
  opts=[["Cutaneous",
         "Correct: cutaneous anthrax, acquired through cuts or incisions in the skin, accounts for the great majority of human cases."],
        ["Pulmonary",
         "Pulmonary anthrax (woolsorters' disease) is the deadliest form rather than the most common one."],
        ["Gastrointestinal",
         "Gastrointestinal anthrax follows eating contaminated meat and is far less common than the cutaneous form."],
        ["Injection",
         "Injection anthrax has been identified in heroin-injecting addicts in northern Europe and not yet in the United States."]],
  c=0, cite=c(10)),

dict(topic="Bacillus anthracis", io=IO1,
  q="Which form of anthrax is the most deadly?",
  opts=[["Pulmonary",
         "Correct: untreated pulmonary anthrax (woolsorters' disease) is almost always fatal within about three days of the first symptoms."],
        ["Cutaneous",
         "Cutaneous anthrax is the most common form and the least lethal, healing to an eschar in most treated patients."],
        ["Gastrointestinal",
         "Gastrointestinal anthrax is serious, and most patients survive with aggressive treatment; pulmonary anthrax is the deadliest."],
        ["Injection",
         "Injection anthrax spreads faster than the cutaneous form, but the most deadly form is pulmonary anthrax."]],
  c=0, cite=c(13)),

dict(topic="Bacillus anthracis", io=IO1,
  q="How does a cutaneous anthrax lesion progress?",
  opts=[["Painless papule, ulcer, then black eschar",
         "Correct: it first appears as a painless papule, rapidly ulcerates with surrounding vesicles, and ends as a black necrotic eschar."],
        ["Painful pustule, to abscess, to a flat scar",
         "The first lesion of cutaneous anthrax is a painless papule, and it ends as a necrotic eschar rather than an abscess."],
        ["Itchy wheal, to blister, to a healing crust",
         "A wheal is an allergic skin response; cutaneous anthrax runs from painless papule to ulcer to necrotic eschar."],
        ["Red nodule, to draining sinus, to fibrosis",
         "Draining lesions are the pattern of actinomycosis; cutaneous anthrax ends in a black necrotic eschar."]],
  c=0, cite=c(10)),

dict(topic="Bacillus anthracis", io=IO1,
  q="What is the lesion shown on this man's jaw and neck?",
  img=IMG + "/l10-s011.jpg",
  alt="Two views of a lesion on a man's jaw and neck.",
  slide="Slide 11",
  opts=[["The eschar of cutaneous anthrax",
         "Correct: a black necrotic eschar over red, swollen skin is the end stage of cutaneous anthrax, which begins as a painless papule where spores enter a cut."],
        ["The blackened tissue of gas gangrene",
         "Gas gangrene follows deep, dirty wounds with dead tissue and spreads with gas through muscle rather than forming a single crusted eschar."],
        ["The nodules of lepromatous leprosy",
         "Lepromatous leprosy produces many deep nodules that disfigure the face, not a single black crusted lesion like this one."],
        ["A pseudomembrane of diphtheria",
         "The diphtheria pseudomembrane forms in the throat from solidified inflammatory fluid, not as a black crust on the neck."]],
  c=0, cite=c(11)),

dict(topic="Bacillus anthracis", io=IO2,
  q="How is cutaneous anthrax acquired?",
  opts=[["Spores enter through a skin cut",
         "Correct: spores enter through cuts or incisions, germinate in the tissue and grow, which is why it is the commonest form."],
        ["Spores are inhaled from animal wool",
         "Inhaling spores from infected animal products is how pulmonary anthrax (woolsorters' disease) is acquired."],
        ["Meat from an infected animal is eaten",
         "Eating contaminated meat produces gastrointestinal anthrax, with ulcers of the mouth and esophagus."],
        ["Heroin is injected into the muscle",
         "Injecting contaminated heroin produces injection anthrax, deep in the muscle where the drug went."]],
  c=0, cite=c(10)),

dict(topic="Bacillus anthracis", io=IO2,
  q="Why is pulmonary anthrax called woolsorters' disease?",
  opts=[["Sorters inhale spores from infected wool",
         "Correct: it is acquired by inhaling spores from infected animal products or soil, so people handling wool from infected sheep were exposed."],
        ["Wool fibers cut the skin and let spores in",
         "Spores entering through cuts cause cutaneous anthrax; woolsorters' disease is the inhaled, pulmonary form."],
        ["Sorters swallow spores from their hands",
         "Swallowed spores in meat cause gastrointestinal anthrax; woolsorters' disease is acquired by inhalation."],
        ["Sheep transmit the bacillus by biting",
         "Anthrax is a zoonosis acquired from spores, not by animal bites; woolsorters inhale spores from the wool."]],
  c=0, cite=c(13)),

dict(topic="Bacillus anthracis", io=IO2,
  q="How is gastrointestinal anthrax acquired?",
  opts=[["By eating infected animal meat",
         "Correct: ingestion of contaminated meat leads to ulceration of the mouth and esophagus and localized lymphadenopathy."],
        ["By drinking water containing spores",
         "Gastrointestinal anthrax is acquired by eating contaminated meat rather than from drinking water."],
        ["By inhaling spores from animal hides",
         "Inhaling spores from animal products causes pulmonary anthrax, the most deadly form."],
        ["By injecting contaminated heroin",
         "Contaminated heroin causes injection anthrax, an infection of the deep muscle at the injection site."]],
  c=0, cite=c(14)),

dict(topic="Bacillus anthracis", io=IO1,
  q="Where is the infection evident in injection anthrax?",
  opts=[["In the deep muscle at the injection site",
         "Correct: the symptoms resemble cutaneous anthrax, but the infection is in deep muscle where the drug was injected, so it spreads faster and is harder to recognize."],
        ["In the lungs after the spores are inhaled",
         "Infection of the lungs after inhaled spores is pulmonary anthrax, not the injection form."],
        ["In the mouth and esophagus",
         "Ulcers of the mouth and esophagus mark gastrointestinal anthrax from eaten meat."],
        ["In the skin over a minor cut",
         "Infection through a cut in the skin is cutaneous anthrax; injection anthrax lies deeper, in the muscle."]],
  c=0, cite=c(12)),

dict(topic="Bacillus anthracis", io=IO1,
  q="In pulmonary anthrax, what happens after alveolar macrophages engulf the inhaled endospores?",
  opts=[["Exotoxins kill the macrophages",
         "Correct: the exotoxins kill macrophages en masse, and the illness moves from cough, fever and chills to edema, capillary thrombosis and shock."],
        ["The spores are destroyed in lysosomes",
         "The spores are not destroyed; inside the macrophages the bacillus releases exotoxins that kill them."],
        ["Granulomas wall off the infection",
         "Walling off in granulomas (tubercles) is the host response in primary tuberculosis, not in pulmonary anthrax."],
        ["A pseudomembrane forms in the bronchi",
         "A pseudomembrane is the hallmark of respiratory diphtheria, forming in the throat rather than the bronchi."]],
  c=0, cite=c(13)),

dict(topic="Bacillus anthracis", io=IO1,
  q="Which complication can follow any type of anthrax?",
  opts=[["Meningitis",
         "Correct: anthrax meningitis can complicate every form, and it appears in up to half of patients with pulmonary anthrax."],
        ["Myocarditis",
         "Myocarditis, with an abnormal electrocardiogram, is a target-organ effect of diphtheria toxin."],
        ["Toxic megacolon",
         "Toxic megacolon is a complication of Clostridioides difficile disease of the colon."],
        ["Descending paralysis",
         "Descending muscular paralysis is the signature of botulism, from toxin blocking acetylcholine release."]],
  c=0, cite=c(15)),

dict(topic="Bacillus anthracis", io=IO1,
  q="Besides antibiotics, what is pulmonary anthrax treated with?",
  opts=[["Neutralizing antitoxin",
         "Correct: pulmonary anthrax is also treated with antitoxin, aimed at the toxins that drive its shock."],
        ["Hyperbaric oxygen therapy",
         "Hyperbaric oxygen floods tissue with oxygen to inhibit the anaerobe of gas gangrene rather than treating anthrax."],
        ["Fecal microbiota transplant",
         "Fecal microbiota transplant restores colonic flora in Clostridioides difficile infection."],
        ["Surgical removal of the lung",
         "Surgery is not the added treatment; pulmonary anthrax is given antitoxin to neutralize the toxins."]],
  c=0, cite=c(16)),

dict(topic="Bacillus anthracis", io=IO1,
  q="What kind of vaccine is the human anthrax vaccine, Biothrax?",
  opts=[["A purified toxoid",
         "Correct: Biothrax is a purified toxoid, given to high-risk occupations and military personnel."],
        ["Live spores",
         "Live spores, with toxoid, are used to protect livestock rather than people."],
        ["A killed whole-cell vaccine",
         "The human vaccine contains no whole cells; it is a purified toxoid."],
        ["A polysaccharide conjugate",
         "The anthrax capsule is polypeptide, not polysaccharide, and the human vaccine is a purified toxoid."]],
  c=0, cite=c(16)),

dict(topic="Bacillus anthracis", io=IO1,
  q="Who is the human anthrax vaccine intended for?",
  opts=[["High-risk workers and military personnel",
         "Correct: it is reserved for high-risk occupations and military personnel, and is not given to those under 18 or over 65."],
        ["All children on the routine schedule",
         "Anthrax vaccine is not part of the routine childhood schedule; it is not given to anyone under 18."],
        ["Adults over 65 with chronic lung disease",
         "The vaccine is not given to people over 65; it is for high-risk occupations and the military."],
        ["Travelers to tropical regions",
         "Travel is not the indication; the vaccine is for high-risk occupations and military personnel."]],
  c=0, cite=c(16)),

# ----------------------------------------------------------- Bacillus cereus
dict(topic="Bacillus cereus", io=IO2,
  q="How does Bacillus cereus most commonly make people ill?",
  opts=[["Through contaminated food",
         "Correct: it is most commonly a foodborne illness; its spores are very commonly airborne and dustborne and land on foods."],
        ["Through deep puncture wounds",
         "Deep puncture wounds are the classic route for Clostridium tetani and for the gas gangrene organisms."],
        ["Through respiratory droplets",
         "Respiratory droplets spread Corynebacterium diphtheriae and Mycobacterium tuberculosis rather than Bacillus cereus."],
        ["Through contact with armadillos",
         "Armadillos are a possible zoonotic source of leprosy, not of Bacillus cereus."]],
  c=0, cite=c(17)),

dict(topic="Bacillus cereus", io=IO2,
  q="Why can rice that was cooked and then reheated still cause Bacillus cereus illness?",
  opts=[["Its spores survive cooking",
         "Correct: Bacillus cereus grows in rice, potatoes and meat, and its spores survive both cooking and reheating."],
        ["It grows only during refrigeration",
         "Growth during refrigeration is the trait of Listeria monocytogenes, which forms no spores."],
        ["Its toxin forms only in the intestine",
         "Toxin made in the intestine after eating is Clostridium perfringens gastroenteritis, not the Bacillus cereus emetic form."],
        ["It needs a sealed, low-acid can",
         "A sealed, low-acid, home-canned food is the setting for Clostridium botulinum."]],
  c=0, cite=c(17)),

dict(topic="Bacillus cereus", io=IO1,
  q="What produces the emetic form of Bacillus cereus food poisoning?",
  opts=[["A small, heat-stable peptide",
         "Correct: the emetic form comes from a small, heat-stable peptide; the diarrheal form comes from a large protein."],
        ["A large molecular weight protein",
         "A large molecular weight protein toxin causes the diarrheal form rather than the emetic form."],
        ["Invasion of the intestinal wall",
         "Bacillus cereus food poisoning is a toxin effect, with symptoms due to exotoxin rather than invasion."],
        ["A neurotoxin blocking acetylcholine",
         "Blocking acetylcholine release is botulinum toxin, which paralyzes rather than causing vomiting."]],
  c=0, cite=c(17)),

dict(topic="Bacillus cereus", io=IO1,
  q="How is typical Bacillus cereus food poisoning treated?",
  opts=[["No treatment; it lasts a day",
         "Correct: the illness runs about 24 hours, and no treatment is given."],
        ["With antitoxin and ventilator support",
         "Antitoxin with cardiac and respiratory support is the treatment for botulism, not for Bacillus cereus."],
        ["With fecal microbiota transplant",
         "Fecal microbiota transplant is used for Clostridioides difficile infection rather than Bacillus cereus."],
        ["With surgical debridement",
         "Debridement removes dead tissue in gas gangrene; Bacillus cereus food poisoning needs no treatment."]],
  c=0, cite=c(17)),

dict(topic="Bacillus cereus", io=IO2,
  q="Which contaminated product has caused Bacillus cereus sepsis at injection sites?",
  opts=[["Alcohol prep pads",
         "Correct: rare infections have been traced to contaminated alcohol prep pads, producing clinical sepsis from contaminated injection sites."],
        ["Honey pacifiers",
         "Honey pacifiers were linked to infant botulism rather than to Bacillus cereus sepsis."],
        ["Black tar heroin",
         "Black tar heroin is associated with wound botulism in people who inject drugs."],
        ["Raw cow's milk",
         "Raw cow's milk carries Mycobacterium avium subspecies paratuberculosis rather than Bacillus cereus sepsis."]],
  c=0, cite=c(18)),

dict(topic="Bacillus cereus", io=IO1,
  q="What is welder's anthrax?",
  opts=[["Bacillus cereus making anthrax toxin",
         "Correct: anthrax toxins have been identified in this disease of metal workers, but they are produced by Bacillus cereus; metal fume inhalation may predispose."],
        ["Bacillus anthracis inhaled with metal dust",
         "The toxin in welder's anthrax is anthrax toxin, but the organism producing it is Bacillus cereus rather than Bacillus anthracis."],
        ["Cutaneous anthrax entering through burns",
         "Welder's anthrax is a disease of metal workers caused by toxin-producing Bacillus cereus, not burns infected with Bacillus anthracis."],
        ["Nocardia lung disease mimicking anthrax",
         "Nocardia causes a tuberculosis-like pulmonary disease; welder's anthrax is caused by Bacillus cereus making anthrax toxins."]],
  c=0, cite=c(18)),

# ---------------------------------------------------------- Clostridium genus
dict(topic="Classification", io=IO1,
  q="Most Clostridium infections fall into which two types?",
  opts=[["Wounds and food intoxications",
         "Correct: the clostridia are opportunistic pathogens causing wound and tissue infections and food intoxications."],
        ["Respiratory and urinary infections",
         "Respiratory and urinary infections are not the clostridial pattern; their infections are wound or tissue infections and food intoxications."],
        ["Sexually and blood-borne infections",
         "Clostridia are not sexually or blood-borne pathogens; they cause wound infections and food intoxications."],
        ["Eye infections and skin abscesses",
         "Severe eye infections are linked to Bacillus cereus; the clostridia cause wound infections and food intoxications."]],
  c=0, cite=c(20)),

# --------------------------------------------- Clostridium perfringens (wounds)
dict(topic="Clostridium perfringens", io=IO1,
  q="Which organism most commonly causes gas gangrene?",
  opts=[["Clostridium perfringens",
         "Correct: Clostridium perfringens is the most common cause of myonecrosis (gas gangrene), though Clostridium novyi and Clostridium septicum can also cause it."],
        ["Clostridium tetani",
         "Clostridium tetani causes tetanus, a neuromuscular disease, rather than gas gangrene."],
        ["Clostridium botulinum",
         "Clostridium botulinum causes botulism, a paralytic intoxication, rather than gas gangrene."],
        ["Clostridioides difficile",
         "Clostridioides difficile causes antibiotic-associated colitis rather than gas gangrene."]],
  c=0, cite=c(21)),

dict(topic="Clostridium perfringens", io=IO1,
  q="How does a mixed infection help myonecrosis develop?",
  opts=[["Aerobes use up the oxygen",
         "Correct: aerobic bacteria in the wound consume the oxygen, producing the low oxygen tension the anaerobic spores need to germinate and grow."],
        ["Aerobes supply toxins the anaerobe lacks",
         "Clostridium perfringens makes its own toxins; the aerobic partners matter because they use up oxygen."],
        ["Aerobes digest tissue so spores can enter",
         "The partners' role is to consume oxygen; Clostridium perfringens spreads through tissue with its own enzymes."],
        ["Two organisms are needed to form the gas",
         "The gas comes from Clostridium perfringens fermenting muscle carbohydrate; the aerobes lower the oxygen tension."]],
  c=0, cite=c(22)),

dict(topic="Clostridium perfringens", io=IO2,
  q="Which wound most predisposes a patient to myonecrosis?",
  opts=[["A compound fracture",
         "Correct: compound fractures, like surgical incisions, diabetic ulcers, septic abortions, puncture and gunshot wounds, create the dead tissue and low oxygen the organism needs."],
        ["A shallow abrasion",
         "A shallow surface wound has too much oxygen for the anaerobic spores to germinate."],
        ["A clean paper cut",
         "A clean superficial cut lacks the damaged, dead tissue and anaerobic conditions myonecrosis requires."],
        ["A superficial sunburn",
         "Sunburn does not create the deep, dead, oxygen-poor tissue in which Clostridium perfringens grows."]],
  c=0, cite=c(22)),

dict(topic="Clostridium perfringens", io=IO1,
  q="Why do so few wounds carrying Clostridium perfringens develop myonecrosis?",
  opts=[["It needs dead tissue and low oxygen",
         "Correct: it is not highly invasive, so although most contaminated wounds carry it, disease needs damaged, dead tissue and anaerobic conditions."],
        ["Most wounds carry strains that lack spores",
         "The organism forms spores readily; disease depends on host factors, dead tissue and low oxygen."],
        ["Vaccination protects most of the population",
         "No vaccine against myonecrosis is available; disease depends on dead tissue and anaerobic conditions."],
        ["It is killed rapidly by skin bacteria",
         "Other bacteria help rather than hinder it, by using up oxygen in a mixed infection."]],
  c=0, cite=c(23)),

dict(topic="Clostridium perfringens", io=IO1,
  q="What produces the gas in gas gangrene?",
  opts=[["Fermentation of muscle carbohydrate",
         "Correct: the organisms ferment muscle carbohydrates, forming gas and destroying more tissue."],
        ["Air drawn in through the wound",
         "The gas is made by the bacteria fermenting muscle carbohydrate rather than drawn in from outside."],
        ["Respiration by the aerobic partners",
         "The aerobic partners use up oxygen; the gas comes from Clostridium perfringens fermenting muscle carbohydrate."],
        ["Nitric oxide from activated macrophages",
         "Nitric oxide release is part of the anthrax cytokine surge; gas gangrene gas comes from fermentation of muscle carbohydrate."]],
  c=0, cite=c(23)),

dict(topic="Clostridium perfringens", io=IO1,
  q="Which enzymes let Clostridium perfringens spread through connective tissue?",
  opts=[["Collagenase, hyaluronidase",
         "Correct: with deoxyribonuclease, collagenase and hyaluronidase break down the collagen fibrils and hyaluronic acid of connective tissue, letting the infection spread."],
        ["Catalase and peroxidase",
         "Clostridium is catalase negative, and catalase and peroxidase break down hydrogen peroxide rather than spreading infection."],
        ["Coagulase and urease",
         "Coagulase and urease are enzymes detected in laboratory identification of other organisms; the clostridial spreading factors are collagenase and hyaluronidase."],
        ["Lipase and amylase",
         "The spreading enzymes are collagenase, hyaluronidase and deoxyribonuclease rather than digestive lipase or amylase."]],
  c=0, cite=c(24)),

dict(topic="Clostridium perfringens", io=IO1,
  q="What separates true myonecrosis from anaerobic cellulitis?",
  opts=[["Spreading necrosis with fever",
         "Correct: true myonecrosis spreads from the local infection with fever, tachycardia and blackened necrotic tissue, whereas anaerobic cellulitis stays localized."],
        ["Gas forms only in true myonecrosis",
         "Anaerobic cellulitis also has gas and tissue damage; the difference is that it remains localized."],
        ["Anaerobic cellulitis stays painless",
         "Pain is not the distinguishing feature; anaerobic cellulitis stays localized, while true myonecrosis spreads."],
        ["A different genus causes each one",
         "Both are clostridial wound infections; they differ in extent, localized against spreading."]],
  c=0, cite=c(26)),

dict(topic="Clostridium perfringens", io=IO1,
  q="Why is hyperbaric oxygen used in gas gangrene?",
  opts=[["Oxygen inhibits the anaerobe",
         "Correct: a hyperbaric chamber floods the tissues with oxygen, which inhibits the anaerobic clostridia, alongside debridement and antibiotics."],
        ["It neutralizes the circulating toxin",
         "Neutralizing circulating toxin is the job of antitoxin, as in botulism and tetanus, not of oxygen."],
        ["It restores the normal skin flora",
         "Restoring normal flora is the logic of fecal microbiota transplant in Clostridioides difficile, not hyperbaric oxygen."],
        ["It dissolves the pockets of gas",
         "The point of oxygen is to inhibit the anaerobe; the gas comes from ongoing fermentation of muscle carbohydrate."]],
  c=0, cite=c(27)),

dict(topic="Clostridium perfringens", io=IO1,
  q="Which measure prevents gas gangrene?",
  opts=[["Cleansing dirty, deep wounds",
         "Correct: immediate cleansing of dirty or deep wounds, compound fractures and infected incisions is the prevention, because no vaccine is available."],
        ["A toxoid booster every 10 years",
         "A toxoid booster every 10 years prevents tetanus; no vaccine against gas gangrene is available."],
        ["Pasteurization of dairy products",
         "Pasteurization and cooking prevent listeriosis, not wound infection with Clostridium perfringens."],
        ["Boiling food for 10 minutes",
         "Boiling home-bottled foods for 10 minutes is a botulism precaution rather than wound care."]],
  c=0, cite=c(27)),

# --------------------------------------- Clostridium perfringens (food) & tetani
dict(topic="Clostridium perfringens", io=IO1,
  q="In Clostridium perfringens gastroenteritis, where is the toxin produced?",
  opts=[["In the intestine, after eating",
         "Correct: spores surviving inadequate cooking germinate in the food, and once eaten the toxin is produced in the intestine, acting on epithelial cells."],
        ["In the food, before it is eaten",
         "Toxin preformed in food is the pattern of botulism; Clostridium perfringens makes its toxin in the intestine."],
        ["In the liver, after absorption",
         "The toxin is produced in the intestine and acts on intestinal epithelial cells."],
        ["In the bloodstream, after invasion",
         "Clostridium perfringens gastroenteritis is not invasive; the toxin forms in the intestine and recovery is rapid."]],
  c=0, cite=c(41)),

dict(topic="Clostridium perfringens", io=IO2,
  q="Which foods are most commonly involved in Clostridium perfringens gastroenteritis?",
  opts=[["Meat and fish",
         "Correct: spores in food that was not cooked enough to destroy them germinate and multiply, especially if the food is left unrefrigerated."],
        ["Home-canned vegetables",
         "Low-acid, home-canned vegetables are the classic source of Clostridium botulinum, not Clostridium perfringens."],
        ["Honey and baby food",
         "Honey and homemade baby food are associated with infant botulism."],
        ["Soft cheeses",
         "Soft cheeses and dairy products are the vehicles of Listeria monocytogenes."]],
  c=0, cite=c(41)),

dict(topic="Clostridium perfringens", io=IO1,
  q="How does Clostridium perfringens food poisoning compare with botulism?",
  opts=[["It is mild, whereas botulism is severe",
         "Correct: Clostridium perfringens causes a mild intestinal illness with rapid recovery, whereas Clostridium botulinum causes a rare but severe intoxication."],
        ["It is severe, whereas botulism is mild",
         "This reverses them: botulism is the rare but severe intoxication, and Clostridium perfringens food poisoning is mild."],
        ["Both cause descending paralysis",
         "Only botulism paralyzes; Clostridium perfringens causes abdominal pain, diarrhea and nausea."],
        ["Both come from home-canned food",
         "Home-canned low-acid food is the botulism source; Clostridium perfringens comes from undercooked meat and fish."]],
  c=0, cite=c(33)),

dict(topic="Clostridium tetani", io=IO2,
  q="How do Clostridium tetani spores usually enter the body?",
  opts=[["Through puncture wounds",
         "Correct: spores usually enter through puncture wounds, and also through burns, umbilical stumps, frostbite and crushed body parts."],
        ["By inhaling contaminated dust",
         "Inhaled spores are the route of pulmonary anthrax rather than tetanus."],
        ["By eating undercooked meat",
         "Undercooked meat and fish are the vehicles of Clostridium perfringens gastroenteritis."],
        ["By droplets from a carrier",
         "Droplets from carriers spread Corynebacterium diphtheriae, not the soil organism Clostridium tetani."]],
  c=0, cite=c(29)),

dict(topic="Clostridium tetani", io=IO2,
  q="How do newborns in developing countries acquire tetanus?",
  opts=[["The umbilical stump",
         "Correct: spores entering the umbilical stump cause neonatal tetanus, which is why it is seen in developing countries."],
        ["Their mother's milk",
         "Tetanus is not carried in breast milk; neonates are infected through the umbilical stump."],
        ["Honey in their feeds",
         "Honey is associated with infant botulism, the flaccid floppy baby syndrome, rather than tetanus."],
        ["The placenta",
         "The organism does not cross the placenta; neonatal tetanus enters through the umbilical stump."]],
  c=0, cite=c(29)),

dict(topic="Clostridium tetani", io=IO1,
  q="What does tetanospasmin block the release of?",
  opts=[["Gamma-aminobutyric acid and glycine",
         "Correct: the neurotoxin blocks release of the inhibitory transmitters gamma-aminobutyric acid and glycine from spinal neurons, so muscles contract uncontrollably."],
        ["Acetylcholine at the neuromuscular junction",
         "Blocking acetylcholine release at the neuromuscular junction is botulinum toxin, which causes flaccid paralysis."],
        ["Norepinephrine from sympathetic nerves",
         "Tetanospasmin targets the inhibitory transmitters gamma-aminobutyric acid and glycine, not norepinephrine."],
        ["Histamine from tissue mast cells",
         "Histamine release from mast cells is an allergic mechanism; tetanospasmin blocks inhibitory neurotransmitters."]],
  c=0, cite=c(29)),

dict(topic="Clostridium tetani", io=IO1,
  q="What is the clinical result of tetanospasmin action?",
  opts=[["Uncontrolled muscle contraction",
         "Correct: with the inhibitory signals blocked, muscles contract uncontrollably, as in lockjaw and risus sardonicus."],
        ["Descending flaccid paralysis",
         "Descending flaccid paralysis is botulism, where acetylcholine release is blocked."],
        ["Loss of pain sensation in the skin",
         "Local loss of pain reception comes from nerve damage in tuberculoid leprosy, not tetanus."],
        ["Myocarditis with an abnormal rhythm",
         "Myocarditis with an abnormal electrocardiogram is a target-organ effect of diphtheria toxin."]],
  c=0, cite=c(29)),

dict(topic="Clostridium tetani", io=IO1,
  q="What usually causes death in tetanus?",
  opts=[["Respiratory failure from spasm",
         "Correct: death most often comes from respiratory failure, as spasm of the breathing muscles and larynx stops effective breathing."],
        ["Septic shock from cytokine release",
         "Shock from a cytokine flood is the picture of severe anthrax rather than tetanus."],
        ["Perforation of the colon",
         "Colon perforation is a complication of Clostridioides difficile disease."],
        ["Asphyxiation by a throat membrane",
         "Asphyxiation by a throat pseudomembrane is the danger in respiratory diphtheria."]],
  c=0, cite=c(29)),

dict(topic="Clostridium tetani", io=IO1,
  q="How does the length of the incubation period relate to tetanus severity?",
  opts=[["A shorter incubation means more serious disease",
         "Correct: incubation runs about 4 to 10 days, and the shorter it is, the more serious the disease."],
        ["A longer incubation means more serious disease",
         "This reverses it: the shorter the incubation, the more serious the tetanus."],
        ["Incubation length has no bearing on severity",
         "Incubation length matters: a short incubation, delayed care and head wounds all worsen the outlook."],
        ["Only wounds of the feet shorten incubation",
         "Wound site matters in a different way, with head wounds carrying a worse outlook; a shorter incubation means more serious disease."]],
  c=0, cite=c(29)),

dict(topic="Clostridium tetani", io=IO1,
  q="Why does human tetanus immune globulin not reverse spasms that have already begun?",
  opts=[["It cannot neutralize toxin already bound",
         "Correct: antitoxin inactivates circulating toxin but does not counteract toxin already bound, so treatment also controls the infection and uses muscle relaxants."],
        ["It is cleared before it reaches the blood",
         "The antitoxin does reach the circulation, where it inactivates free toxin; it cannot reach toxin already bound."],
        ["It kills only the vegetative cells",
         "Antitoxin acts on toxin, not on bacteria; controlling the infection is the job of antibiotics."],
        ["It acts only on the dormant spores",
         "Antitoxin does not act on spores; it neutralizes circulating toxin, not toxin already bound to nerves."]],
  c=0, cite=c(32)),

dict(topic="Clostridium tetani", io=IO1,
  q="How often is a tetanus vaccine booster needed?",
  opts=[["Every 10 years",
         "Correct: a vaccine is available, and a booster is needed every 10 years."],
        ["Every year",
         "Annual boosters are the anthrax vaccine schedule for high-risk workers; tetanus boosters are every 10 years."],
        ["Every 6 months",
         "Tetanus protection does not need six-monthly doses; a booster every 10 years maintains it."],
        ["Never after childhood",
         "Tetanus protection wanes, so adults need a booster every 10 years."]],
  c=0, cite=c(32)),

dict(topic="Clostridium tetani", io=IO1,
  q="The newborn shown is held rigid and arched. Which toxin produces this picture?",
  img=IMG + "/l10-s031.jpg",
  alt="A newborn held by an adult, its whole body rigidly arched backward with the head thrown back.",
  slide="Slide 31",
  opts=[["Tetanospasmin",
         "Correct: rigid, arched spasms in a newborn are neonatal tetanus, the umbilical stump infection seen in developing countries."],
        ["Botulinum toxin",
         "Botulinum toxin produces a limp, floppy infant with flaccid paralysis rather than rigid arching."],
        ["Diphtheria toxin",
         "Diphtheria toxin targets the heart and nerves, causing myocarditis and weakness rather than rigid spasms."],
        ["Anthrax lethal factor",
         "Anthrax lethal factor lyses macrophages and can cause shock; it does not cause rigid muscle spasms."]],
  c=0, cite=c(31)),

dict(topic="Clostridium tetani", io=IO1,
  q="In the United States, in whom is tetanus most common?",
  opts=[["Older adults and drug users",
         "Correct: it is most common among geriatric patients and intravenous drug users; in developing countries, among neonates."],
        ["Vaccinated schoolchildren",
         "School-age children are protected by the vaccination series; tetanus is most common in older adults and people who inject drugs."],
        ["Pregnant women",
         "Pregnancy is a risk setting for listeriosis, through the fetus, rather than for tetanus."],
        ["Farmers handling pigs",
         "Pig handlers are exposed to Erysipelothrix rhusiopathiae; tetanus is commonest in older adults and drug users."]],
  c=0, cite=c(28)),

# ----------------------------------------------------- Clostridium botulinum
dict(topic="Clostridium botulinum", io=IO2,
  q="Foodborne botulism is most associated with which foods?",
  opts=[["Low-acid, home-canned vegetables",
         "Correct: home-canned green beans and corn are the classic sources, though meats, fish and dairy can also carry it."],
        ["Cooked rice left out and reheated",
         "Reheated rice is the classic vehicle of Bacillus cereus food poisoning."],
        ["Unpasteurized soft cheeses",
         "Soft cheeses and dairy are the vehicles of Listeria monocytogenes."],
        ["Undercooked ground chicken",
         "Undercooked meat and poultry are linked to listeriosis and Clostridium perfringens rather than to botulism."]],
  c=0, cite=c(34)),

dict(topic="Clostridium botulinum", io=IO1,
  q="Why does inadequate home canning lead to botulism?",
  opts=[["Air is removed but the spores survive",
         "Correct: without reliable temperature and pressure the air is evacuated but the spores remain, and the anaerobic jar favors germination and toxin."],
        ["Oxygen enters and feeds the spores",
         "Clostridium botulinum is anaerobic; poor canning removes oxygen, which is what lets the spores germinate."],
        ["The acid in the food activates the toxin",
         "Botulism is associated with low-acid foods; vinegar is a preservative against it."],
        ["Sugar in the jar converts into toxin",
         "Toxin is made by vegetative cells after spores germinate in the airless jar, not from sugar."]],
  c=0, cite=c(35)),

dict(topic="Clostridium botulinum", io=IO1,
  q="How does botulinum toxin cause paralysis?",
  opts=[["It blocks acetylcholine release",
         "Correct: botulin is carried to neuromuscular junctions and blocks the release of acetylcholine, which is needed for muscle contraction."],
        ["It blocks inhibitory transmitters in the cord",
         "Blocking the inhibitory transmitters gamma-aminobutyric acid and glycine is tetanospasmin, which causes spasm."],
        ["It destroys myelin on peripheral nerves",
         "Botulin leaves the nerve intact; it blocks acetylcholine release at the neuromuscular junction."],
        ["It lyses motor neurons in the spinal cord",
         "Botulin does not kill motor neurons; it blocks acetylcholine release where they meet the muscle."]],
  c=0, cite=c(35)),

dict(topic="Clostridium botulinum", io=IO1,
  q="Which pattern of paralysis does botulism produce?",
  opts=[["Descending muscular paralysis",
         "Correct: double or blurred vision and difficulty swallowing come first, then paralysis descends, and respiratory compromise can follow."],
        ["Uncontrolled spastic contraction",
         "Uncontrolled contraction is tetanus, where inhibitory transmitters are blocked."],
        ["Patchy loss of pain sensation",
         "Patchy loss of pain reception is tuberculoid leprosy, from damage to peripheral nerves."],
        ["Weakness confined to the heart",
         "Diphtheria toxin targets the heart and nerves; botulism produces a descending paralysis of skeletal muscle."]],
  c=0, cite=c(37)),

dict(topic="Clostridium botulinum", io=IO1,
  q="Which early symptoms point to botulism?",
  opts=[["Double vision, trouble swallowing",
         "Correct: double or blurred vision, difficulty swallowing and dizziness come first, sometimes with nausea and vomiting."],
        ["Lockjaw and arching spasms",
         "Lockjaw and arching spasms are tetanus, the spastic counterpart of botulism."],
        ["Watery diarrhea and fever",
         "Watery diarrhea with fever is the opening of Clostridioides difficile disease."],
        ["Sore throat and a gray membrane",
         "A sore throat with a pseudomembrane is respiratory diphtheria."]],
  c=0, cite=c(37)),

dict(topic="Clostridium botulinum", io=IO1,
  q="Why has the mortality of botulism fallen?",
  opts=[["Ventilators support breathing",
         "Correct: ventilator support carries patients through the descending paralysis, and mortality has fallen as a result."],
        ["A routine childhood vaccine",
         "No routine botulism vaccine is described; the fall in mortality is credited to ventilators."],
        ["Universal antibiotic prophylaxis",
         "Antibiotics are not the explanation; supporting respiration with ventilators is."],
        ["Fecal microbiota transplant",
         "Fecal microbiota transplant treats Clostridioides difficile, not botulism."]],
  c=0, cite=c(37)),

dict(topic="Clostridium botulinum", io=IO1,
  q="What syndrome does the infant shown illustrate?",
  img=IMG + "/l10-s038.jpg",
  alt="An infant held face down by an adult.",
  slide="Slide 38",
  opts=[["Floppy baby syndrome",
         "Correct: the limp infant is infant botulism, flaccid paralysis from toxin released after ingested spores germinate in the gut."],
        ["Neonatal tetanus",
         "Neonatal tetanus produces a rigid, arched infant, the spastic opposite of the limp baby shown."],
        ["Neonatal listeriosis",
         "Listeriosis in newborns affects the brain and meninges rather than producing this limp, flaccid paralysis."],
        ["Diphtheritic paralysis",
         "Diphtheria toxin can cause weakness, but diphtheria occurs in unimmunized children with a throat pseudomembrane."]],
  c=0, cite=c(38)),

dict(topic="Clostridium botulinum", io=IO2,
  q="How does infant botulism arise?",
  opts=[["Ingested spores germinate in the gut",
         "Correct: the infant swallows spores, which germinate and release toxin in the immature gut, causing floppy baby syndrome."],
        ["Preformed toxin is eaten in canned food",
         "Eating toxin already made in improperly canned food is foodborne botulism rather than the infant form."],
        ["Spores enter through the umbilical stump",
         "Spores entering the umbilical stump cause neonatal tetanus rather than botulism."],
        ["Toxin crosses the placenta",
         "Infant botulism is acquired after birth by swallowing spores, not across the placenta."]],
  c=0, cite=c(38)),

dict(topic="Clostridium botulinum", io=IO2,
  q="Which food is a classic source of infant botulism?",
  opts=[["Honey",
         "Correct: infant botulism may be associated with honey or homemade baby food; honey pacifiers caused cases in 2018."],
        ["Breast milk",
         "Breast milk is not a described source; honey and homemade baby food are."],
        ["Fresh fruit",
         "Fresh fruit is not a described source; infant botulism is linked to honey and homemade baby food."],
        ["Cooked rice",
         "Cooked, reheated rice is linked to Bacillus cereus food poisoning rather than infant botulism."]],
  c=0, cite=c(38)),

dict(topic="Clostridium botulinum", io=IO1,
  q="Which is the most common form of botulism?",
  opts=[["Infant botulism",
         "Correct: infant botulism accounts for most botulism cases each year, well ahead of foodborne and wound botulism."],
        ["Foodborne botulism",
         "Foodborne botulism is the classic form but now a minority of cases; infant botulism is the most common."],
        ["Wound botulism",
         "Wound botulism, linked to black tar heroin, is less common than infant botulism."],
        ["Iatrogenic botulism",
         "Iatrogenic botulism from cosmetic or therapeutic toxin use is rare."]],
  c=0, cite=c(39)),

dict(topic="Clostridium botulinum", io=IO2,
  q="Wound botulism is most associated with which group?",
  opts=[["Black tar heroin users",
         "Correct: spores enter a wound and cause the food poisoning symptoms, and the classic setting is intravenous drug use with black tar heroin."],
        ["Metal workers who weld",
         "Welders are the group affected by welder's anthrax, caused by Bacillus cereus."],
        ["Swimmers with pool scrapes",
         "Scrapes on swimming pool concrete are linked to Mycobacterium marinum granuloma."],
        ["Gardeners with rose-thorn cuts",
         "Gardening cuts are not the described setting; wound botulism is associated with injecting black tar heroin."]],
  c=0, cite=c(38)),

dict(topic="Clostridium botulinum", io=IO1,
  q="What is iatrogenic botulism?",
  opts=[["Illness from medical use of the toxin",
         "Correct: it occurs when cosmetic or therapeutic procedures that use botulinum toxin cause systemic intoxication."],
        ["Toxin made by spores growing in a wound",
         "Spores growing in a wound and making toxin is wound botulism."],
        ["Toxin from spores colonizing an adult gut",
         "Toxin from intestinal colonization in someone over age 1 is intestinal colonization botulism."],
        ["Paralysis from eating home-canned food",
         "Eating preformed toxin in home-canned food is foodborne botulism."]],
  c=0, cite=c(39)),

dict(topic="Clostridium botulinum", io=IO1,
  q="What is the central treatment for botulism?",
  opts=[["Antitoxin and respiratory support",
         "Correct: after confirming toxin in food, intestinal contents or feces, antitoxin is given with cardiac and respiratory support."],
        ["Hyperbaric oxygen with wound debridement",
         "Hyperbaric oxygen with debridement is the approach to gas gangrene."],
        ["Fecal microbiota transplant by colonoscope",
         "Fecal microbiota transplant is a treatment for Clostridioides difficile infection."],
        ["Muscle relaxants with a toxoid booster",
         "Muscle relaxants are part of tetanus care; botulism, already flaccid, is treated with antitoxin and support."]],
  c=0, cite=c(40)),

dict(topic="Clostridium botulinum", io=IO1,
  q="Which home precaution prevents botulism from home-bottled foods?",
  opts=[["Boiling it for 10 minutes",
         "Correct: boil home-bottled foods for at least 10 minutes, discard bulging cans, and preserve properly with sodium nitrite, salt or vinegar."],
        ["Sealing jars in a plain water bath",
         "A plain water bath removes air without killing the spores; reliable temperature and pressure are needed."],
        ["Storing the jars in the refrigerator",
         "Refrigeration is not the stated precaution; boiling home-bottled foods for 10 minutes is."],
        ["Keeping bulging cans for later use",
         "Bulging cans and containers should be discarded, never kept."]],
  c=0, cite=c(40)),

# ------------------------------------------------- Clostridioides difficile
dict(topic="Clostridioides difficile", io=IO1,
  q="Why was Clostridium difficile reclassified as Clostridioides difficile?",
  opts=[["Ribonucleic acid sequencing",
         "Correct: it was formerly classified as Clostridium but was differentiated by ribonucleic acid sequencing."],
        ["It was found to form no spores",
         "It still forms spores, as the clostridia do; the reclassification came from ribonucleic acid sequencing."],
        ["It was found to grow in oxygen",
         "It remains an anaerobe; ribonucleic acid sequencing is what separated it from Clostridium."],
        ["It was found to stain acid-fast",
         "Acid-fast staining belongs to the mycobacteria; the new genus came from ribonucleic acid sequencing."]],
  c=0, cite=c(42)),

dict(topic="Clostridioides difficile", io=IO1,
  q="How does broad-spectrum antibiotic treatment lead to Clostridioides difficile disease?",
  opts=[["It kills the competing flora",
         "Correct: the organism is a low-number, relatively non-invasive colon resident; killing the other bacteria lets it overgrow and make enterotoxins."],
        ["It makes the organism invade the colon wall",
         "The organism is relatively non-invasive; the damage comes from enterotoxins after it overgrows."],
        ["It carries resistant spores into the gut",
         "The organism is already a normal colon resident in low numbers; antibiotics remove its competitors."],
        ["It switches on toxin in all gut bacteria",
         "Only Clostridioides difficile makes these enterotoxins, once antibiotics have cleared its competitors."]],
  c=0, cite=c(42)),

dict(topic="Clostridioides difficile", io=IO2,
  q="In which setting is Clostridioides difficile a major cause of diarrhea?",
  opts=[["Hospitals and healthcare settings",
         "Correct: it is a major cause of diarrhea in hospitals, long stays in healthcare settings raise the risk, and increased precautions are taken to prevent spread."],
        ["Swimming pools and hot tubs",
         "Swimming pools are linked to Mycobacterium marinum granuloma rather than to Clostridioides difficile."],
        ["Restaurants serving reheated rice",
         "Reheated rice is the classic source of Bacillus cereus food poisoning."],
        ["Farms raising pigs",
         "Pig farms are where Erysipelothrix rhusiopathiae is acquired."]],
  c=0, cite=c(43)),

dict(topic="Clostridioides difficile", io=IO1,
  q="Which complication belongs to Clostridioides difficile disease?",
  opts=[["Toxic megacolon",
         "Correct: it causes antibiotic-associated (pseudomembranous) colitis, toxic megacolon and perforation of the colon."],
        ["Myocarditis",
         "Myocarditis with an abnormal electrocardiogram is a target-organ effect of diphtheria toxin."],
        ["Meningitis",
         "Meningitis can complicate any form of anthrax and is a risk of listeriosis in vulnerable patients."],
        ["Descending paralysis",
         "Descending paralysis is the pattern of botulism, from blocked acetylcholine release."]],
  c=0, cite=c(43)),

dict(topic="Clostridioides difficile", io=IO1,
  q="Besides antibiotics, which drugs raise the risk of Clostridioides difficile infection?",
  opts=[["Gastric acid inhibitors",
         "Correct: gastric acid inhibitors such as famotidine (Pepcid) and omeprazole (Prilosec) are a listed risk, with antibiotics, surgery, long stays and advanced age."],
        ["Inhaled corticosteroids",
         "Inhaled corticosteroids are not among the listed risks; gastric acid inhibitors are."],
        ["Beta blockers",
         "Beta blockers are not among the listed risks; the listed drug risk besides antibiotics is gastric acid suppression."],
        ["Statins",
         "Statins are not among the listed risks; gastric acid inhibitors such as Pepcid and Prilosec are."]],
  c=0, cite=c(45)),

dict(topic="Clostridioides difficile", io=IO1,
  q="What is the pseudomembrane of Clostridioides difficile colitis?",
  opts=[["Sloughed necrotic intestinal lining",
         "Correct: as the disease progresses the intestinal lining becomes necrotic and sloughs off as the pseudomembrane, and the wall can go on to perforate."],
        ["Solidified fluid coating the throat",
         "Solidified inflammatory fluid in the throat is the pseudomembrane of respiratory diphtheria."],
        ["A biofilm of spores on the colon",
         "The pseudomembrane is sloughed necrotic intestinal lining, not a layer of spores."],
        ["A granuloma walling off the bacteria",
         "Granulomas (tubercles) belong to tuberculosis; the colitis pseudomembrane is sloughed necrotic intestinal lining."]],
  c=0, cite=c(46)),

dict(topic="Clostridioides difficile", io=IO1,
  q="The raised yellow-white plaques shown line a patient's colon. Which organism produces them?",
  img=IMG + "/l10-s047.jpg",
  alt="Colonoscopy view of pink colon lining dotted with raised yellow-white plaques, two of them marked with arrows.",
  slide="Slide 47",
  opts=[["Clostridioides difficile",
         "Correct: these are the pseudomembranes of antibiotic-associated colitis, sloughed necrotic intestinal lining."],
        ["Clostridium perfringens",
         "Clostridium perfringens causes a mild, rapidly resolving gastroenteritis, not pseudomembranous colitis."],
        ["Listeria monocytogenes",
         "Listeria is often mild in healthy adults and affects the brain and meninges in vulnerable patients rather than forming colonic plaques."],
        ["Bacillus cereus",
         "Bacillus cereus causes a 24-hour toxin illness of vomiting or diarrhea without colonic plaques."]],
  c=0, cite=c(47)),

dict(topic="Clostridioides difficile", io=IO1,
  q="Which measure is part of managing even a mild Clostridioides difficile case?",
  opts=[["Withdrawing the antimicrobial",
         "Correct: withdrawal of the inciting antimicrobial, with fluid and electrolyte replacement, is part of managing every case, mild ones included."],
        ["Immediate surgical colectomy",
         "Surgery is not the approach to mild disease; fluids and withdrawal of the antimicrobial are."],
        ["Hyperbaric oxygen sessions",
         "Hyperbaric oxygen is used in gas gangrene to inhibit the anaerobe in tissue."],
        ["Antitoxin and ventilation",
         "Antitoxin with respiratory support is the treatment of botulism."]],
  c=0, cite=c(48)),

dict(topic="Clostridioides difficile", io=IO1,
  q="What does fecal microbiota transplant do for Clostridioides difficile infection?",
  opts=[["Restores normal colonic flora from a donor",
         "Correct: donor cultures are given by colonoscope or nasogastric tube, or as capsules, re-establishing the flora that keeps the organism in check."],
        ["Delivers antitoxin directly into the colon",
         "Fecal transplant contains donor bacteria rather than antitoxin against the enterotoxins."],
        ["Removes the pseudomembrane surgically",
         "No tissue is removed; the transplant replaces the lost normal flora."],
        ["Vaccinates the patient against the toxin",
         "Fecal transplant is not a vaccine; it repopulates the colon with donor flora."]],
  c=0, cite=c(48)),
]
