# -*- coding: utf-8 -*-
# Microbiology Exam 1, Lecture 5 — Host Defenses: Nonspecific Mechanisms, pool B.
# Objectives 5-11: leukocyte classes, the white count with differential,
# inflammation, fever, interferon, and complement.
#
# Four options throughout. Answers written SHORT from the outset.
SRC = "Lecture 5  Dr. Webster Nonspecific Immunity.pptx"
def c(n): return f"{SRC}, Slide {n}"

IO5 = "5 — Describe the roles of the different classes of leukocytes in the second and third lines of defense"
IO6 = "6 — Describe the role of a white blood count with differential"
IO7 = "7 — Describe the characteristic components of inflammation"
IO8 = "8 — Describe the mechanism of pathogenic fever"
IO9 = "9 — Explain the beneficial and harmful effects of fever"
IO10 = "10 — Compare and contrast the origin and functions of interferon"
IO11 = "11 — Discuss the complement system"

POOL_B = [
 # ---------------- inflammation ----------------
 dict(topic="Inflammation", io=IO7,
   q="What are the five cardinal signs of inflammation?",
   opts=[["Rubor, calor, tumor, dolor and functio laesa",
          "Correct — redness, heat, swelling, pain and loss of function."],
         ["Rubor, calor, tumor and dolor only",
          "Four of the five; loss of function is the fifth."],
         ["Fever, chills, rigors and sweats",
          "Systemic features, not the cardinal signs of local inflammation."],
         ["Erythema, oedema, induration and fluctuance",
          "Clinical descriptors, but not the five named terms."]],
   c=0, cite=c(29)),
 dict(topic="Inflammation", io=IO7,
   q="What does 'functio laesa' mean?",
   opts=[["Lost function", "Correct — the fifth cardinal sign."],
         ["Heat", "That is calor."],
         ["Swelling", "That is tumor."],
         ["Pain", "That is dolor."]],
   c=0, cite=c(29)),
 dict(topic="Inflammation", io=IO7,
   q="What is an inflammasome, and what does it activate?",
   opts=[["A protein complex that activates interleukin 1 beta",
          "Correct, and in large quantities."],
         ["A receptor that detects viral RNA",
          "That is the retinoic acid inducible gene."],
         ["A complement convertase",
          "Convertases are complement enzymes."],
         ["A granule inside the neutrophil",
          "Neutrophil granules hold antimicrobial contents; the inflammasome is an assembled protein complex."]],
   c=0, cite=c(34)),
 dict(topic="Inflammation", io=IO7,
   q="How does interleukin 1 beta escape the macrophage, and what happens to the cell?",
   opts=[["Through pores; the cell dies by pyroptosis",
          "Correct — release costs the cell its life."],
         ["It is exported by vesicle and the macrophage survives",
          "Release requires a pore-forming cascade, and it kills the cell."],
         ["It diffuses freely across the membrane",
          "A pore-forming cascade is required."],
         ["It is released only after phagocytosis",
          "Release follows inflammasome activation, not phagocytosis."]],
   c=0, cite=c(34)),
 dict(topic="Inflammation", io=IO7,
   q="What can mutations in inflammasome genes cause?",
   opts=[["Autoinflammatory diseases", "Correct."],
         ["Severe combined immunodeficiency", "Not the consequence named."],
         ["Complement deficiency", "A separate system."],
         ["Chronic granulomatous disease", "Not attributed to inflammasome genes here."]],
   c=0, cite=c(34)),
 dict(topic="Inflammation", io=IO7,
   q="Which cytokine dilates blood vessels to produce heat, swelling, redness and pain?",
   opts=[["Tumour necrosis factor",
          "Correct — increasing blood volume in the infected area."],
         ["Interleukin 6",
          "Interleukin 6 raises temperature."],
         ["CXCL8",
          "That is a chemokine, attracting leukocytes."],
         ["Interferon gamma",
          "Interferon gamma activates macrophages."]],
   c=0, cite=c(35)),
 dict(topic="Inflammation", io=IO7,
   q="Which molecules act as CHEMOKINES to attract white blood cells to the infection?",
   opts=[["CXCL8, CCL2 and interleukin 12",
          "Correct."],
         ["Interleukin 1 beta and tumour necrosis factor alpha alone",
          "Both are inflammatory cytokines, but the chemokines named are different."],
         ["Interferons alpha and beta",
          "Antiviral cytokines."],
         ["C3b and C4b",
          "Complement opsonins."]],
   c=0, cite=c(35)),
 dict(topic="Inflammation", io=IO7,
   q="What do endothelial cells do in response to inflammatory cytokines?",
   opts=[["Upregulate adhesion molecules",
          "Correct — both are needed to let leukocytes leave the vessel."],
         ["Tighten their junctions to seal the vessel",
          "The junctions loosen."],
         ["Begin phagocytosis",
          "Not an endothelial role described here."],
         ["Secrete antibody",
          "Antibody comes from plasma cells."]],
   c=0, cite=c(35)),
 dict(topic="Inflammation", io=IO7,
   q="Which adhesion pair binds FIRST as a leukocyte begins to leave the blood?",
   opts=[["L-selectin to CD34",
          "Correct — the transient interaction that makes the cell roll."],
         ["Integrin LFA-1 to ICAM-1",
          "That is the firmer second interaction, after rolling."],
         ["C3b to complement receptor 1",
          "An opsonin interaction, not adhesion for extravasation."],
         ["Antibody to Fc receptor",
          "Adaptive, and not part of rolling."]],
   c=0, cite=c(36)),
 dict(topic="Inflammation", io=IO7,
   q="Which integrin pairing holds the leukocyte firmly to the endothelium?",
   opts=[["LFA-1 to ICAM-1",
          "Correct — an immunoglobulin-like molecule on the endothelial side."],
         ["L-selectin to CD34",
          "That is the rolling interaction."],
         ["CR1 to C3b",
          "Complement, not adhesion."],
         ["CD56 to MHC class I",
          "Not an adhesion pair described here."]],
   c=0, cite=c(36)),
 dict(topic="Inflammation", io=IO7,
   q="What is diapedesis?",
   opts=[["Squeezing between endothelial cells",
          "Correct — guided by chemokines."],
         ["Rolling along the endothelial surface",
          "That is the selectin-mediated step before diapedesis."],
         ["Engulfing a pathogen",
          "That is phagocytosis."],
         ["Bursting to release DNA traps",
          "That is netosis."]],
   c=0, cite=c(37)),
 # ---------------- fever ----------------
 dict(topic="Fever", io=IO8,
   q="Which three cytokines have systemic effects including FEVER?",
   opts=[["Interleukin 1 beta",
          "Correct — the same three that act locally. Interleukin 6 and tumour necrosis factor alpha."],
         ["Interferons alpha, beta and gamma",
          "Antiviral cytokines rather than the pyrogens named."],
         ["CXCL8, CCL2 and interleukin 12",
          "Chemokines."],
         ["C3a, C5a and properdin",
          "Complement components."]],
   c=0, cite=c(38)),
 dict(topic="Fever", io=IO9,
   q="How does fever act against BACTERIA specifically?",
   opts=[["It starves them of iron",
          "Correct — iron starvation is the antibacterial mechanism."],
         ["It denatures their ribosomes",
          "Not the mechanism given."],
         ["It lyses their cell walls",
          "That is lysozyme and complement."],
         ["It blocks their adhesion to mucosa",
          "Not attributed to fever."]],
   c=0, cite=c(38)),
 dict(topic="Fever", io=IO9,
   q="Which of these is a BENEFICIAL effect of fever?",
   opts=[["It increases production and activity of neutrophils",
          "Correct, alongside enhanced T cell proliferation and immune signalling."],
         ["It increases viral replication",
          "Fever DECREASES replication of viral and bacterial pathogens."],
         ["It suppresses T cell proliferation",
          "It enhances it."],
         ["It reduces tissue resistance to tumour necrosis factor alpha",
          "It ENHANCES tissue resistance to its damaging effects."]],
   c=0, cite=c(38)),
 dict(topic="Fever", io=IO9,
   q="How does fever affect tissue resistance to tumour necrosis factor alpha?",
   opts=[["It ENHANCES resistance to its damaging effects",
          "Correct — a protective effect against the body's own mediator."],
         ["It reduces resistance, worsening damage",
          "The opposite of what is described."],
         ["It has no effect on it",
          "An effect is explicitly listed."],
         ["It converts it into interleukin 6",
          "No such conversion occurs."]],
   c=0, cite=c(38)),
 dict(topic="Fever", io=IO8,
   q="Which cytokine besides tumour necrosis factor alpha is named as increasing temperature?",
   opts=[["Interleukin 6", "Correct."],
         ["CXCL8", "A chemokine."],
         ["Interferon beta", "Assists B and T cell maturation and the inflammatory response."],
         ["Interleukin 12", "Listed among the chemokines attracting leukocytes."]],
   c=0, cite=c(35)),
 # ---------------- TNF local vs systemic ----------------
 dict(topic="Tumour necrosis factor", io=IO7,
   q="What does LOCAL release of tumour necrosis factor alpha achieve in venules?",
   opts=[["It clots the blood in venules",
          "Correct — containment, alongside increased flow, permeability and adhesiveness. Preventing spread of infection to the blood."],
         ["It dissolves clots to improve flow",
          "It causes clotting rather than dissolving it."],
         ["It reduces vessel permeability",
          "Permeability increases."],
         ["It prevents leukocytes adhering",
          "Endothelial adhesiveness for white cells and platelets increases."]],
   c=0, cite=c(39)),
 dict(topic="Tumour necrosis factor", io=IO7,
   q="Why is SYSTEMIC release of tumour necrosis factor alpha catastrophic?",
   opts=[["It induces shock in all tissues at once",
          "Correct — the same mechanism that contains a local infection becomes lethal at scale."],
         ["It suppresses all immune function",
          "Not the mechanism described."],
         ["It causes uncontrolled bleeding only",
          "Shock and organ failure are the stated consequences."],
         ["It has no systemic effect",
          "It is described as catastrophic."]],
   c=0, cite=c(40)),
 # ---------------- complement ----------------
 dict(topic="Complement", io=IO11,
   q="How many proteins make up the complement system, and in what form do they circulate?",
   opts=[["More than thirty",
          "Correct — soluble proteases awaiting cleavage. Circulating as inactive zymogens."],
         ["About nine, circulating fully active",
          "Both the number and the activation state are wrong."],
         ["More than thirty, circulating fully active",
          "They circulate inactive, as zymogens."],
         ["Three, produced only on infection",
          "Complement is ubiquitous in blood and lymph."]],
   c=0, cite=c(42)),
 dict(topic="Complement", io=IO11,
   q="How are complement proteins activated?",
   opts=[["By cleavage, in a cascade",
          "Correct."],
         ["By phosphorylation",
          "Not the described mechanism."],
         ["By binding calcium",
          "Not the described mechanism."],
         ["By transcriptional upregulation",
          "They are already present and are activated by cleavage."]],
   c=0, cite=c(42)),
 dict(topic="Complement", io=IO11,
   q="What gives complement its distinctive chemical activity?",
   opts=[["A high-energy thioester bond",
          "Correct — exposed on C3b when C3 is cleaved."],
         ["A disulfide bridge",
          "Not the bond named."],
         ["A phosphodiester bond",
          "That is a nucleic acid bond."],
         ["A peptidoglycan cross-link",
          "A bacterial cell wall feature."]],
   c=0, cite=c(42)),
 dict(topic="Complement", io=IO11,
   q="What are the two fates of the exposed thioester bond on C3b?",
   opts=[["Attack by water, making it soluble",
          "Correct — the second is complement fixation. Or reaction with a hydroxyl or amino group on a pathogen surface."],
         ["Cleavage by lysozyme or by defensins",
          "Neither acts on the thioester bond."],
         ["Binding antibody or binding interferon",
          "Not the fates described."],
         ["Conversion to C3a or to C5a",
          "C3a is the OTHER fragment of C3, not a fate of the bond."]],
   c=0, cite=c(43)),
 dict(topic="Complement", io=IO11,
   q="What is complement FIXATION?",
   opts=[["C3b attaching to a pathogen surface",
          "Correct. Marking it for destruction."],
         ["C3a recruiting phagocytes",
          "That is the role of the smaller fragment, not fixation."],
         ["The assembly of the membrane attack complex",
          "That happens later, from C5b onward."],
         ["Antibody binding to antigen",
          "An adaptive event."]],
   c=0, cite=c(43)),
 dict(topic="Complement", io=IO11,
   q="What does the C3a fragment do?",
   opts=[["Recruits phagocytes", "Correct — while C3b marks the pathogen."],
         ["Forms the membrane attack complex", "That begins with C5b."],
         ["Opsonises the pathogen", "That is C3b."],
         ["Inactivates factor H", "Factor H is a regulator; C3a does not act on it."]],
   c=0, cite=c(43)),
 dict(topic="Complement", io=IO11,
   q="Name the three complement activation pathways in the order they become active.",
   opts=[["Alternative, then lectin, then classical",
          "Correct — though they were DISCOVERED classical, alternative, lectin."],
         ["Classical, then alternative, then lectin",
          "That is the order of DISCOVERY, not of activation."],
         ["Lectin, then classical, then alternative",
          "The alternative pathway activates first."],
         ["Classical, then lectin, then alternative",
          "Neither the activation nor the discovery order."]],
   c=0, cite=c(44)),
 dict(topic="Complement", io=IO11,
   q="What do all three complement pathways converge on?",
   opts=[["Cleavage of C3 into C3a and C3b",
          "Correct — they start differently and end the same way."],
         ["Formation of the membrane attack complex only",
          "That is downstream of C3 cleavage and not reached by every activation."],
         ["Release of histamine",
          "A mast cell event."],
         ["Production of interferon",
          "A separate antiviral system."]],
   c=0, cite=c(44)),
 dict(topic="Complement", io=IO11,
   q="Which molecule is by far the most important in the complement cascade?",
   opts=[["C3", "Correct — the pathways differ mainly in how they get to it."],
         ["C1", "Part of the classical pathway's start, not the pivot."],
         ["C5", "Downstream of C3."],
         ["C9", "The final membrane attack complex component."]],
   c=0, cite=c(45)),
 dict(topic="Complement", io=IO11,
   q="Why is the CLASSICAL pathway part of both innate and adaptive immunity?",
   opts=[["Either C-reactive protein or antibody starts it",
          "Correct — two different triggers into the same pathway."],
         ["It is activated only by antibody",
          "C-reactive protein can trigger it too, which is the innate half."],
         ["It is activated only by C-reactive protein",
          "Antibody activation is the adaptive half."],
         ["It requires both simultaneously",
          "Either trigger suffices."]],
   c=0, cite=c(45)),
 dict(topic="Complement", io=IO11,
   q="What does PROPERDIN (factor P) do?",
   opts=[["Increases complement activation",
          "Correct — a positive regulator."],
         ["Makes C3b susceptible to cleavage, reducing activation",
          "That is factor H."],
         ["Cleaves C3b into iC3b",
          "That is factor I, acting after factor H."],
         ["Disrupts C3 convertase on human cells",
          "That is decay accelerating factor or membrane cofactor protein."]],
   c=0, cite=c(46)),
 dict(topic="Complement", io=IO11,
   q="How do factor H and factor I work together?",
   opts=[["Factor H makes C3b susceptible to cleavage by factor I",
          "Correct — a two-step brake. Creating iC3b which cannot form a convertase."],
         ["Factor H cleaves C3b and factor I binds the product",
          "The roles are the other way round."],
         ["Both increase complement activation",
          "Both reduce it."],
         ["Both form part of the membrane attack complex",
          "They are regulators, not components of the complex."]],
   c=0, cite=c(46)),
 dict(topic="Complement", io=IO11,
   q="Which two MEMBRANE proteins protect human cells by disrupting C3bBb?",
   opts=[["Decay accelerating factor and cofactor protein",
          "Correct — they act rapidly when the convertase forms on a human surface."],
         ["Factor H and factor I",
          "Those are plasma proteins."],
         ["Properdin and C-reactive protein",
          "Properdin increases activation; C-reactive protein is an opsonin."],
         ["CD59 and clusterin",
          "Those protect against the MEMBRANE ATTACK COMPLEX rather than the C3 convertase."]],
   c=0, cite=c(47)),
 dict(topic="Complement", io=IO11,
   q="What is an opsonin?",
   opts=[["A protein that promotes phagocytosis",
          "Correct — C3b is the example."],
         ["A pore-forming protein",
          "That describes the membrane attack complex."],
         ["A cytokine that raises temperature",
          "A pyrogen, not an opsonin."],
         ["An enzyme that cleaves peptidoglycan",
          "That is lysozyme."]],
   c=0, cite=c(48)),
 dict(topic="Complement", io=IO11,
   q="What does complement receptor 1 bind, and what is its second role?",
   opts=[["C3b; it also protects human cells",
          "Correct — offence and defence from one receptor."],
         ["C5a, driving chemotaxis only",
          "C5a acts through its own receptors."],
         ["Antibody Fc regions only",
          "That is an Fc receptor."],
         ["Mannose residues only",
          "That is a lectin receptor."]],
   c=0, cite=c(48)),
 dict(topic="Complement", io=IO11,
   q="What does the alternative C5 convertase do?",
   opts=[["Cleaves C5 into C5a and C5b",
          "Correct — it forms when C3b binds existing C3bBb complexes."],
         ["Cleaves C3 into C3a and C3b",
          "That is the C3 convertase."],
         ["Assembles C9 into a pore",
          "That is the final step of the membrane attack complex."],
         ["Inactivates factor H",
          "Not a convertase function."]],
   c=0, cite=c(49)),
 dict(topic="Complement", io=IO11,
   q="What are the two roles of C5a?",
   opts=[["It recruits neutrophils",
          "Correct — chemotaxis plus inflammation. It is the most potent anaphylatoxin."],
         ["It opsonises pathogens and forms pores",
          "Opsonisation is C3b; pores are the membrane attack complex."],
         ["It inhibits complement and clears debris",
          "Those are regulatory and scavenger functions."],
         ["It initiates the membrane attack complex",
          "That is C5b."]],
   c=0, cite=c(49)),
 dict(topic="Complement", io=IO11,
   q="Which fragment initiates the membrane attack complex?",
   opts=[["C5b", "Correct."],
         ["C5a", "C5a recruits neutrophils and drives inflammation."],
         ["C3a", "C3a recruits phagocytes."],
         ["C3b", "C3b opsonises and builds the C5 convertase."]],
   c=0, cite=c(49)),
 dict(topic="Complement", io=IO11,
   q="Which proteins prevent soluble C5b, C6 and C7 associating with human membranes?",
   opts=[["S protein, clusterin and factor J",
          "Correct."],
         ["CD59 and homologous restriction factor",
          "Those act later, preventing C9 from joining a complex that has already attached."],
         ["Decay accelerating factor and membrane cofactor protein",
          "Those disrupt the C3 convertase."],
         ["Factor H and factor I",
          "Those regulate C3b."]],
   c=0, cite=c(51)),
 dict(topic="Complement", io=IO11,
   q="What does CD59 (protectin) prevent?",
   opts=[["C9 from joining an attached complex",
          "Correct — the last line of protection against self-lysis."],
         ["C3 convertase from forming",
          "That is decay accelerating factor and membrane cofactor protein."],
         ["C3b from being deposited",
          "That is factor H and factor I."],
         ["C5a from recruiting neutrophils",
          "Not a function of CD59."]],
   c=0, cite=c(51)),
 dict(topic="Complement", io=IO11,
   q="How do Streptococcus pyogenes and Staphylococcus aureus evade complement?",
   opts=[["They coat themselves in sialic acid",
          "Correct — they mimic the human cell surface. Which binds factor H so their C3b is inactivated."],
         ["They secrete an enzyme that digests C3",
          "Not the described mechanism."],
         ["They shed the membrane attack complex",
          "Not the described evasion strategy."],
         ["They block the classical pathway only",
          "The evasion works through factor H regardless of pathway."]],
   c=0, cite=c(52)),
 dict(topic="Complement", io=IO11,
   q="Why does antibody defeat the sialic acid evasion strategy?",
   opts=[["Antibody masks the sialic acid first",
          "Correct — so these bacteria resist complement ONLY when no specific antibody is present."],
         ["Antibody cleaves sialic acid enzymatically",
          "It masks rather than cleaves."],
         ["Antibody inactivates factor H directly",
          "It acts on the bacterial surface, not on factor H."],
         ["Antibody prevents C5 cleavage",
          "Not the mechanism described."]],
   c=0, cite=c(52)),
 dict(topic="Complement", io=IO11,
   q="What can C3a and C5a cause in extreme cases?",
   opts=[["Anaphylactic shock",
          "Correct — they are ligands on phagocytes, endothelium and mast cells."],
         ["Immunological memory",
          "A property of adaptive immunity."],
         ["Pyroptosis of macrophages",
          "That follows inflammasome activation."],
         ["Netosis of neutrophils",
          "A separate neutrophil death process."]],
   c=0, cite=c(53)),
 # ---------------- interferon ----------------
 dict(topic="Interferon", io=IO10,
   q="Which cells produce interferon ALPHA?",
   opts=[["Lymphocytes and macrophages", "Correct."],
         ["Fibroblasts and epithelial cells", "Those produce interferon beta."],
         ["T cells", "T cells produce interferon gamma."],
         ["Hepatocytes", "The liver produces acute-phase proteins, not interferon alpha."]],
   c=0, cite=c(59)),
 dict(topic="Interferon", io=IO10,
   q="Which cells produce interferon BETA?",
   opts=[["Fibroblasts and epithelial cells", "Correct."],
         ["Lymphocytes and macrophages", "Those produce interferon alpha."],
         ["T cells", "Those produce interferon gamma."],
         ["Neutrophils", "Not a named interferon source."]],
   c=0, cite=c(59)),
 dict(topic="Interferon", io=IO10,
   q="Which cells produce interferon GAMMA?",
   opts=[["T cells", "Correct."],
         ["Fibroblasts", "They produce interferon beta."],
         ["Macrophages", "They produce interferon alpha; gamma ACTIVATES them."],
         ["Epithelial cells", "They produce interferon beta."]],
   c=0, cite=c(59)),
 dict(topic="Interferon", io=IO10,
   q="What does interferon actually do to a virus?",
   opts=[["Nothing directly",
          "Correct. Interferon does not kill viruses; it stops spread to surrounding tissue."],
         ["Lyses the viral envelope",
          "Defensins damage enveloped viruses; interferon does not."],
         ["Digests viral nucleic acid",
          "Not its mechanism."],
         ["Opsonises virus for phagocytosis",
          "That is an opsonin function."]],
   c=0, cite=c(60)),
 dict(topic="Interferon", io=IO10,
   q="How does interferon protect uninfected cells?",
   opts=[["It induces antiviral proteins in them",
          "Correct — it prepares the neighbours."],
         ["It coats them in sialic acid",
          "That is a bacterial evasion strategy."],
         ["It forms pores in their membranes",
          "That would kill them."],
         ["It presents viral antigen to T cells",
          "Dendritic cells do that."]],
   c=0, cite=c(59)),
 dict(topic="Interferon", io=IO10,
   q="Which interferon activates natural killer cells?",
   opts=[["Interferon alpha", "Correct."],
         ["Interferon beta", "Beta assists B and T cell maturation and the inflammatory response."],
         ["Interferon gamma", "Gamma inhibits cancer cells, stimulates B cells and activates macrophages."],
         ["None of them", "Interferon alpha is named for this role."]],
   c=0, cite=c(61)),
 dict(topic="Interferon", io=IO10,
   q="What does interferon GAMMA do?",
   opts=[["Inhibits cancer, stimulates B cells, activates macrophages",
          "Correct — and it increases macrophage effectiveness."],
         ["Activates natural killer cells",
          "That is interferon alpha."],
         ["Assists B and T cell maturation",
          "That is interferon beta."],
         ["Blocks the complement cascade",
          "Not an interferon function."]],
   c=0, cite=c(61)),
 dict(topic="Interferon", io=IO10,
   q="Besides viral defense, what effect do interferons have on tumours?",
   opts=[["They suppress tumours",
          "Correct."],
         ["They promote tumour growth",
          "The opposite."],
         ["They have no effect on tumours",
          "Tumour suppression is explicitly listed."],
         ["They opsonise tumour cells for complement",
          "Not an interferon function."]],
   c=0, cite=c(59)),
 dict(topic="Interferon", io=IO10,
   q="What makes plasmacytoid dendritic cells 'professional interferon producing cells'?",
   opts=[["Within six hours of activation",
          "Correct — an extraordinary commitment of the cell's machinery. 60% of the cell's transcription makes type 1 interferon."],
         ["They produce interferon continuously at low level",
          "The response is a burst on activation."],
         ["They are the only cells that make interferon",
          "Many cell types make interferon."],
         ["They convert interferon alpha into gamma",
          "No such conversion occurs."]],
   c=0, cite=c(80)),
]
