# -*- coding: utf-8 -*-
# PD2 Lecture 4 (Advanced ENT History and Exam, Prof. Gray) -- pool B:
# hearing screening, the tuning fork tests, and the nose.
#
# THE TUNING FORK BLOCK IS THE WEIGHTED ONE. A video played in class said
# outright: "the Weber and the Rinne tests are both high yield, the difference
# between sensorineural hearing loss and conductive hearing loss is also high
# yield ... it will be three points on test day." The lecturer then added his
# own correction to it, because the video covered the sensorineural case and
# left the conductive one implicit.
#
# The two mnemonics taught aloud are carded as mnemonics, not as findings:
# "Rinne is under the penny" (mastoid, below the pinna) and "Weber tells you
# WHETHER it is the right or the left".
#
# Correct answer is ALWAYS written first (c=0); the partition script rotates.
SRC = "PD II ENT 2026.pptx"
def c(n): return f"{SRC}, Slide {n}"
def au(): return "Lecture recording, 3 September 2026"

IO = "Instructional Objectives — Advanced ENT History and Examination"

POOL_B = [
 dict(topic="Hearing screening", io=IO, slot="initial test",
   q="How is the whispered voice test set up?",
   opts=[
     ["Stand two feet behind the patient, occlude the ear not being tested",
      "Correct. The examiner stands two feet behind the patient and occludes the ear not being tested, then whispers a three-item sequence twice."],
     ["Stand two feet in front of the patient so they can see your mouth",
      "Seeing the mouth is exactly what the test has to prevent, which is why the examiner stands behind."],
     ["Stand across the room and speak at conversational volume",
      "The test is a quiet whisper at two feet; conversational volume tests nothing."],
     ["Stand beside the patient and whisper into both ears at once",
      "Each ear is tested on its own with the other occluded, whispering from two feet behind the patient."]],
   c=0, cite=c(35)),

 dict(topic="Hearing screening", io=IO, slot="test finding",
   q="What result on the whispered voice test counts as normal?",
   opts=[
     ["Normal is three or more of six correct",
      "Correct. Normal is three or more of six correct, and four of six incorrect is abnormal; the three-item sequence is whispered twice."],
     ["Normal is six of six correct; anything less is abnormal",
      "Six of six is not required; three or more correct out of six already counts as a normal whispered voice test."],
     ["Normal is one of six correct",
      "One of six correct would be a markedly abnormal result; the normal threshold is three or more."],
     ["Normal is any response at all; the test is qualitative",
      "The test is scored, not qualitative: three or more of six correct is normal and four of six incorrect is abnormal."]],
   c=0, cite=c(35)),

 dict(topic="Hearing screening", io=IO, slot="initial test",
   q="Besides the whispered voice, which two bedside hearing screens are used?",
   opts=[
     ["Finger rub and a watch",
      "Correct — both are crude but immediately available, and both test whether any sound is heard at all."],
     ["Tuning fork and audiometry",
      "The tuning fork tests distinguish the TYPE of loss; they are not screens for its presence, and audiometry is not a bedside screen."],
     ["Otoscopy and insufflation",
      "Both examine the ear structurally rather than screening hearing."],
     ["Weber and Rinne",
      "Weber and Rinne are tuning fork tests that distinguish conductive from sensorineural loss; they are not bedside screens."]],
   c=0, cite=c(35)),

 dict(topic="Hearing loss", io=IO, slot="etiology",
   q="Which list contains only CONDUCTIVE causes of hearing loss?",
   opts=[
     ["Cerumen, foreign bodies, effusions, exostoses, tumors and tympanic membrane perforation",
      "Correct. Every one of them obstructs or loads the external or middle ear."],
     ["Presbycusis, noise exposure, acoustic neuroma and Ménière disease",
      "Presbycusis, noise exposure, acoustic neuroma and Ménière disease are all sensorineural, inner ear causes."],
     ["Cerumen, presbycusis, effusions and noise exposure",
      "A mixed list: presbycusis and noise exposure are sensorineural."],
     ["Rubella, cytomegalovirus and hereditary loss",
      "Rubella, cytomegalovirus and hereditary loss are sensorineural causes arising in the inner ear, not conductive ones."]],
   c=0, cite=c(36)),

 dict(topic="Hearing loss", io=IO, slot="etiology",
   q="Which description of exostoses is correct?",
   opts=[
     ["Benign bony growths in the ear canal, causing conductive loss",
      "Correct. They narrow the canal mechanically, which is why the loss is conductive."],
     ["Benign bony growths on the ossicles, causing sensorineural loss",
      "They are canal growths, and any canal problem produces conductive loss."],
     ["Malignant bone tumors of the temporal bone",
      "Exostoses are benign bony growths in the canal; a malignant temporal bone tumor is a different problem entirely."],
     ["Cholesterol deposits in the middle ear",
      "Exostoses are not middle-ear deposits of any kind. They are benign bony growths, and they sit in the canal."]],
   c=0, cite=c(36)),

 dict(topic="Hearing loss", io=IO, slot="etiology",
   q="Which viral infections cause SENSORINEURAL hearing loss?",
   opts=[
     ["Rubella and cytomegalovirus",
      "Correct — both damage the inner ear, and both matter most when the exposure was congenital."],
     ["Rhinovirus and influenza",
      "These cause upper respiratory infection, which contributes to serous effusion — a conductive problem."],
     ["Respiratory syncytial virus and adenovirus",
      "Respiratory syncytial virus and adenovirus are not the viral causes of sensorineural loss; those are rubella and cytomegalovirus."],
     ["Herpes simplex and varicella zoster",
      "Herpes simplex and varicella zoster are not the viral causes of sensorineural loss; those are rubella and cytomegalovirus."]],
   c=0, cite=c(37)),

 dict(topic="Hearing loss", io=IO, slot="manifestation",
   q="What frequency pattern does presbycusis take?",
   opts=[
     ["Higher frequency loss",
      "Correct, and it is why the complaint is about clarity rather than volume — the high registers carry the consonants."],
     ["Lower frequency loss",
      "Presbycusis takes the higher frequencies, not the lower ones, so the higher registers are lost and sound may be distorted."],
     ["All frequencies equally",
      "The loss is not flat across frequencies; presbycusis is a higher frequency loss, so sound may be distorted."],
     ["Loss confined to the speech range, sparing higher and lower tones",
      "Presbycusis is a higher frequency loss, not a loss confined to the middle of the speech range."]],
   c=0, cite=c(37)),

 dict(topic="Hearing loss", io=IO, slot="manifestation",
   q="A patient's own voice is UNUSUALLY LOUD. Which kind of hearing loss does that suggest?",
   opts=[
     ["Sensorineural",
      "Correct. In sensorineural loss the voice may be loud because hearing is difficult, including hearing one's own voice."],
     ["Conductive — the middle ear amplifies the patient's own voice",
      "In conductive loss the voice stays SOFT, because the inner ear and cochlear nerve are intact and bone conduction carries the patient's own voice perfectly well."],
     ["Either — voice volume does not distinguish them",
      "It does distinguish them, and it costs nothing to notice while taking the history."],
     ["Neither — loud voice indicates a psychiatric cause",
      "A loud voice is a feature of sensorineural loss, where hearing is difficult; it does not indicate a psychiatric cause."]],
   c=0, cite=c(45)),

 dict(topic="Hearing loss", io=IO, slot="manifestation",
   q="A patient speaks unusually SOFTLY despite a hearing complaint. Which loss does that point to?",
   opts=[
     ["Conductive — the inner ear and cochlear nerve are intact",
      "Correct. In conductive loss the voice remains soft because the inner ear and cochlear nerve are intact, so the patient's own voice is heard normally."],
     ["Sensorineural — the patient compensates by speaking quietly",
      "The opposite: sensorineural loss tends to make the voice loud, because hearing is difficult for the patient."],
     ["Mixed loss only",
      "A soft voice is a feature of conductive loss, where the inner ear and cochlear nerve are intact; it is not specific to mixed loss."],
     ["Presbycusis specifically",
      "Presbycusis is sensorineural, and would make the voice loud."]],
   c=0, cite=c(45)),

 dict(topic="Hearing loss", io=IO, slot="epidemiology",
   q="At what age do conductive and sensorineural hearing loss typically begin?",
   opts=[
     ["Conductive up to about forty; sensorineural in later years",
      "Correct. Conductive loss usually begins in childhood and young adulthood, up to age 40, and sensorineural loss in middle or later years."],
     ["Conductive in middle or later years; sensorineural in childhood",
      "Reversed. Sensorineural loss is the later-onset pattern, and conductive loss is the one that shows up from childhood to about forty."],
     ["Both typically begin after sixty",
      "Only sensorineural loss typically begins in middle or later years; conductive loss begins in childhood, up to about age 40."],
     ["Both typically begin in childhood",
      "Only conductive loss begins in childhood and young adulthood; sensorineural loss usually begins in middle or later years."]],
   c=0, cite=c(45)),

 dict(topic="Hearing loss", io=IO, slot="test finding",
   q="Which statement about otoscopic findings in hearing loss is correct?",
   opts=[
     ["Conductive loss is usually visible, except in otosclerosis",
      "Correct. In conductive loss the abnormality is usually visible, except in otosclerosis, while the sensorineural problem is not visible."],
     ["Sensorineural loss is usually visible; conductive loss is not",
      "Reversed — the sensorineural problem lies beyond anything the otoscope can reach."],
     ["Both are usually visible",
      "The inner ear and cochlear nerve cannot be seen with an otoscope."],
     ["Conductive loss is always visible with no exception",
      "Otosclerosis is the exception: a conductive loss in which the abnormality is usually not visible on otoscopy."]],
   c=0, cite=c(45)),

 dict(topic="Tuning fork tests", io=IO, slot="initial test",
   q="Which setup is correct for the tuning fork hearing tests?",
   opts=[
     ["A 512 hertz fork — the smaller one — in a quiet room",
      "Correct. The frequency matters because it sits in the speech range and rings long enough to compare two positions."],
     ["A 128 hertz fork — the larger one — in a quiet room",
      "The larger low-frequency fork is used to test vibration sense, not hearing."],
     ["A 512 hertz fork, with background noise to mask the other ear",
      "A quiet room is specified; masking with noise is not part of the technique."],
     ["Any available fork, since only the comparison matters",
      "The frequency is specified, and a low-frequency fork is felt as much as heard."]],
   c=0, cite=c(39)),

 dict(topic="Tuning fork tests", io=IO, slot="initial test",
   q="Where is the fork placed for the WEBER test?",
   opts=[
     ["On the top of the head or mid-forehead",
      "Correct. The base of the fork sits on the top of the head or mid-forehead, and the test evaluates unilateral hearing loss by lateralization."],
     ["On the mastoid process, to compare bone against air conduction",
      "A fork on the mastoid comparing bone with air conduction is the Rinne test; Weber uses the top of the head or mid-forehead."],
     ["Just outside the ear canal, to test air conduction alone",
      "Air conduction alone is the second half of Rinne, not Weber."],
     ["Behind the ear on the occiput, to test both ears simultaneously",
      "The occiput is not used; for Weber the base of the fork sits on the top of the head or the mid-forehead."]],
   c=0, cite=c(41)),

 dict(topic="Tuning fork tests", io=IO, slot="test finding",
   q="What is a NORMAL Weber result?",
   opts=[
     ["Midline, or heard equally in both ears",
      "Correct. There is no lateralization to report when both sides transmit equally."],
     ["Lateralized to the right",
      "Any lateralization is abnormal in a patient with unilateral loss."],
     ["Heard only through bone conduction",
      "Weber is a bone conduction test throughout; the finding is where the sound goes, not how it travels."],
     ["Not heard at all",
      "A normal patient hears the tone, and it sits in the midline or is heard in both ears equally."]],
   c=0, cite=c(42)),

 dict(topic="Tuning fork tests", io=IO, slot="test finding",
   q="In unilateral CONDUCTIVE loss, which way does the Weber sound lateralize?",
   opts=[
     ["To the IMPAIRED ear",
      "Correct. Sound lateralizes to the impaired ear, because room noise is not well heard on that side, so detection of the vibrations improves."],
     ["To the GOOD ear, because the impaired ear transmits nothing",
      "That is the sensorineural pattern. In conductive loss the cochlea is intact and hears the bone-conducted tone perfectly."],
     ["It does not lateralize in conductive loss",
      "Lateralization is precisely what the test detects, and conductive loss produces it."],
     ["It alternates between ears",
      "Alternating lateralization is not a recognized Weber result; the sound goes one way or stays midline."]],
   c=0, cite=c(45)),

 dict(topic="Tuning fork tests", io=IO, slot="test finding",
   q="In unilateral SENSORINEURAL loss, which way does the Weber sound lateralize?",
   opts=[
     ["To the GOOD ear",
      "Correct. Sound lateralizes to the good ear, because inner ear or cochlear nerve damage impairs transmission to the affected ear."],
     ["To the IMPAIRED ear, because the damage amplifies bone conduction",
      "That is the conductive pattern, and damage does not amplify anything."],
     ["It does not lateralize in sensorineural loss",
      "It does lateralize: in unilateral sensorineural loss the sound goes to the good ear, away from the damage."],
     ["It lateralizes to whichever ear was tested first",
      "Which ear was tested first has no bearing on where the sound lateralizes."]],
   c=0, cite=c(42)),

 dict(topic="Tuning fork tests", io=IO, slot="test finding",
   q="The Weber test is done and the patient hears the tone only in the LEFT ear. Which ear has sensorineural hearing loss?",
   opts=[
     ["The right",
      "Correct. Sensorineural loss lateralizes AWAY from the damaged side, so hearing the tone on the left places the lesion on the right."],
     ["The left",
      "That would be true for a conductive loss, which lateralizes TOWARD the affected side."],
     ["Neither — this is a normal result",
      "A normal result is midline or heard in both ears; hearing the tone in one ear only means it has lateralized."],
     ["Both",
      "Weber evaluates unilateral loss; a bilateral symmetrical loss would not lateralize."]],
   c=0, cite=c(42)),

 dict(topic="Tuning fork tests", io=IO, slot="initial test",
   q="How is the RINNE test performed, in order?",
   opts=[
     ["Fork on the mastoid until the sound stops, then beside the canal",
      "Correct. Bone conduction comes first, with the fork on the mastoid until the sound stops; the fork then moves close to the canal and the patient is asked if it is still heard."],
     ["Fork close to the canal first, then on the mastoid once the sound stops",
      "The sequence starts at the mastoid, testing bone conduction first."],
     ["Fork on the vertex of the head, then moved to the mastoid",
      "The top of the head is where the Weber fork goes; Rinne starts on the mastoid and then moves close to the canal."],
     ["Fork held in front of both ears simultaneously",
      "Rinne tests one ear at a time and compares two positions on that ear."]],
   c=0, cite=c(43)),

 dict(topic="Tuning fork tests", io=IO, slot="test finding",
   q="What is a NORMAL Rinne result?",
   opts=[
     ["Air conduction heard longer than bone conduction",
      "Correct. Normally sound is heard longer through air than through bone, so air conduction outlasts bone conduction."],
     ["Bone conduction heard longer than air conduction",
      "Bone conduction outlasting air conduction is the conductive hearing loss result, not the normal one."],
     ["Both heard for exactly the same duration",
      "Equal duration is grouped with the conductive finding, not the normal one."],
     ["Neither heard, in a quiet room",
      "A normal patient hears both, and hears the tone longer through air than through bone."]],
   c=0, cite=c(44)),

 dict(topic="Tuning fork tests", io=IO, slot="test finding",
   q="What is the Rinne result in CONDUCTIVE hearing loss?",
   opts=[
     ["Bone conduction equal to or greater than air conduction",
      "Correct. Bone conduction equals or outlasts air conduction, because vibrations through bone bypass the impaired external or middle ear to reach the cochlea."],
     ["Air conduction greater than bone conduction",
      "That is the normal pattern, which also persists in sensorineural loss."],
     ["Neither is heard at all",
      "Conductive loss reduces air conduction; it does not abolish hearing by bone."],
     ["Bone conduction is heard but air conduction is heard longer",
      "Air conduction lasting longer is the normal ratio, which also holds in sensorineural loss; conductive loss gives bone equal to or longer than air."]],
   c=0, cite=c(44)),

 dict(topic="Tuning fork tests", io=IO, slot="test finding",
   q="What is the Rinne result in SENSORINEURAL hearing loss?",
   opts=[
     ["Air conduction still greater than bone conduction",
      "Correct. Air conduction stays longer than bone conduction and the normal pattern prevails, because the inner ear or cochlear nerve fails however the vibrations arrive."],
     ["Bone conduction greater than air conduction, because the inner ear is damaged",
      "That is the conductive pattern; a damaged inner ear does not favor the bone route."],
     ["Neither route is heard",
      "Sensorineural loss reduces hearing but does not usually abolish it."],
     ["The result is unpredictable in sensorineural loss",
      "The result is predictable: in sensorineural loss air conduction still outlasts bone conduction, as it does normally."]],
   c=0, cite=c(45)),

 dict(topic="Tuning fork tests", io=IO, slot="test finding",
   q="A normal Rinne on the right, and the Weber lateralizes to the right. Which finding does this combination indicate?",
   opts=[
     ["Sensorineural loss in the LEFT ear",
      "Correct. A normal Rinne rules out conductive loss on the side tested, and Weber lateralizing right, toward the good ear, places sensorineural damage on the left."],
     ["Conductive loss in the right ear",
      "Conductive loss on the right would give an ABNORMAL Rinne on the right — bone greater than air."],
     ["Sensorineural loss in the right ear",
      "Sensorineural loss lateralizes AWAY from the affected side, so a right-sided lesion would send the Weber left."],
     ["Conductive loss in the left ear",
      "Left conductive loss would also lateralize Weber to the left, not the right."]],
   c=0, cite=c(45)),

 dict(topic="Tuning fork tests", io=IO, slot="avoid",
   q="Which two situations can the tuning fork tests NOT distinguish?",
   opts=[
     ["Normal hearing from bilateral sensorineural loss, and normal hearing from mixed conductive and sensorineural loss",
      "Correct. Both tests work by comparing sides or routes, so a loss that is symmetrical or that affects both routes leaves the comparison looking normal."],
     ["Conductive from sensorineural loss",
      "That is precisely what they DO distinguish: the tuning fork tests separate conductive from sensorineural loss."],
     ["Right-sided from left-sided loss",
      "Right-sided from left-sided loss is exactly what the Weber test answers, by lateralization in unilateral hearing loss."],
     ["Presbycusis from noise-induced loss",
      "Neither test names a cause such as presbycusis; what they cannot tell apart is normal hearing from bilateral sensorineural or mixed loss."]],
   c=0, cite=c(38)),

 dict(topic="Nose history", io=IO, slot="risk factors",
   q="Why should recent dental work be asked about when a patient presents with facial pain?",
   opts=[
     ["Dental work may affect the maxillary sinuses",
      "Correct. The maxillary sinus floor sits directly above the upper tooth roots, so a dental procedure can present as sinus pain."],
     ["Dental anesthetic commonly causes anosmia",
      "Anosmia is asked about separately in the nose history; it is not tied to dental anesthetic."],
     ["Dental work is a recognized cause of epistaxis",
      "Dental work is not an epistaxis cause; those are trauma, inflammation, dry mucosa, foreign body and tumor."],
     ["Dental infection is the commonest cause of frontal sinusitis",
      "The link is with the maxillary sinuses, not the frontal ones; recent dental work may affect the maxillary sinuses."]],
   c=0, cite=c(48)),

 dict(topic="Nose history", io=IO, slot="etiology",
   q="Which drug histories are specifically relevant to nasal symptoms?",
   opts=[
     ["Topical decongestants causing rhinitis medicamentosa, and cocaine",
      "Correct. Both damage the nasal mucosa directly, and both are missed unless asked about by name."],
     ["Beta blockers and calcium channel blockers",
      "Cardiovascular drugs can cause nasal congestion, but the two to ask about by name are topical decongestants and cocaine."],
     ["Aminoglycosides and loop diuretics",
      "Aminoglycosides and loop diuretics matter in the hearing history; the nasal drug history covers rhinitis medicamentosa and cocaine."],
     ["Inhaled corticosteroids and antihistamines",
      "These are not the drugs to ask about; rhinitis medicamentosa from decongestants and cocaine use are the nasal drug histories."]],
   c=0, cite=c(49)),

 dict(topic="Nose history", io=IO, slot="referral",
   q="Which epistaxis history suggests a SYSTEMIC problem rather than a local one?",
   opts=[
     ["Recurrent bleeding, or bleeding and bruising elsewhere on the body",
      "Correct. One nosebleed is local until proven otherwise; a pattern of bleeding at other sites changes the question entirely."],
     ["Bleeding from one nostril after digital trauma",
      "Bleeding after digital trauma is a local cause; recurrence, or bleeding and bruising elsewhere, suggests a systemic problem."],
     ["Bleeding that follows a recent upper respiratory infection",
      "Inflammation after an infection is a local cause of epistaxis, like trauma, dry mucosa, a foreign body or a tumor."],
     ["Bleeding in dry winter air",
      "Dry mucosa is a local cause; a systemic problem is suggested by recurrent bleeding or bleeding and bruising elsewhere."]],
   c=0, cite=c(49)),

 dict(topic="Nose exam", io=IO, slot="initial test",
   q="How is nasal patency tested?",
   opts=[
     ["Occlude one nostril and ask the patient to breathe in",
      "Correct. Each side is tested separately, because unilateral obstruction is what carries the worrying differential."],
     ["Ask the patient to blow the nose and listen for asymmetry",
      "Blowing the nose tells you nothing about which side is obstructed. Each nostril is occluded in turn and the patient breathes in."],
     ["Hold a mirror under the nose and compare the two areas of condensation",
      "A mirror would show condensation from both nostrils together; the test isolates one side at a time."],
     ["Transilluminate each nostril in a dark room",
      "Transillumination assesses the sinuses; patency is tested by occluding one nostril and having the patient breathe in."]],
   c=0, cite=c(50)),

 dict(topic="Nose exam", io=IO, slot="differential",
   q="What does UNILATERAL nasal obstruction suggest?",
   opts=[
     ["A foreign body",
      "Correct. Unilateral obstruction suggests a foreign body, a tumor or a deviated septum, all structural causes on the blocked side."],
     ["Allergic rhinitis",
      "Allergic rhinitis affects the nose as a whole rather than one side."],
     ["Viral rhinitis",
      "Viral rhinitis congests both sides. Unilateral obstruction is what points to a structural cause."],
     ["Rhinitis medicamentosa",
      "Rhinitis medicamentosa belongs to the medication history; unilateral obstruction points to a foreign body, tumor or deviated septum."]],
   c=0, cite=c(50)),

 dict(topic="Nose exam", io=IO, slot="risk factors",
   q="Nasal polyps are associated with which conditions?",
   opts=[
     ["Asthma, aspirin sensitivity and cystic fibrosis",
      "Correct. Nasal polyps are associated with allergic rhinitis, aspirin sensitivity, asthma, chronic sinus infection and cystic fibrosis."],
     ["Hypertension, anticoagulation and atherosclerosis",
      "Hypertension, anticoagulation and atherosclerosis are not polyp associations; polyps go with asthma, allergy and cystic fibrosis."],
     ["Smoking, alcohol and reflux",
      "Smoking, alcohol and reflux relate to hoarseness and tobacco history; polyps go with asthma and aspirin sensitivity."],
     ["Diabetes, obesity and sleep apnea",
      "Diabetes, obesity and sleep apnea are not polyp associations; polyps go with allergy, aspirin sensitivity, asthma and cystic fibrosis."]],
   c=0, cite=c(50)),

 dict(topic="Nose exam", io=IO, slot="test finding",
   q="How does the nasal mucosa look in VIRAL rhinitis compared with ALLERGIC rhinitis?",
   opts=[
     ["Viral is red and swollen; allergic is pale, bluish or red",
      "Correct. The pale bluish appearance is the one that points to allergy, and it is easy to miss if you are only looking for redness."],
     ["Viral is pale and bluish; allergic is red and swollen",
      "Reversed. The pale bluish mucosa is the allergic picture; viral rhinitis makes it red and swollen."],
     ["Both are identical and cannot be distinguished",
      "They are distinguishable, and mucosal color is what separates them."],
     ["Viral is ulcerated; allergic is bleeding",
      "Ulceration and bleeding are separate findings to look for, not the viral–allergic distinction."]],
   c=0, cite=c(52)),

 dict(topic="Nose exam", io=IO, slot="etiology",
   q="What causes a PERFORATED nasal septum?",
   opts=[
     ["Trauma, surgery or drug use",
      "Correct. All three destroy the septal blood supply or the cartilage itself, and drug use is the one patients do not volunteer."],
     ["Allergic rhinitis and chronic sinusitis",
      "Allergic rhinitis and chronic sinusitis inflame the mucosa without destroying the cartilage underneath it."],
     ["A foreign body lodged for several days",
      "A foreign body causes unilateral obstruction rather than perforation; septal perforation comes from trauma, surgery or drug use."],
     ["Repeated epistaxis from Kiesselbach's plexus",
      "Bleeding from the anterior septum does not itself perforate it."]],
   c=0, cite=c(52)),

 dict(topic="Nose exam", io=IO, slot="initial test",
   q="How are the frontal and maxillary sinuses palpated?",
   opts=[
     ["Press UP on both, avoiding the eyes",
      "Correct. Both the frontal and the maxillary sinuses are pressed upward, and the frontal sinuses are pressed while avoiding the eyes."],
     ["Press DOWN on the frontal sinuses and down on the maxillary sinuses",
      "The direction for both sinuses is upward, not downward, with care to avoid the eyes over the frontal sinuses."],
     ["Press directly on the globes to assess the frontal sinuses",
      "The eyes must be avoided, not pressed; the frontal sinuses are palpated by pressing upward while avoiding the eyes."],
     ["Percuss both sinuses with a reflex hammer",
      "The sinuses are palpated by pressing upward for pain or tenderness, not percussed with a reflex hammer."]],
   c=0, cite=c(53)),

 dict(topic="Nose exam", io=IO, slot="initial test",
   q="How is transillumination of the MAXILLARY sinus performed?",
   opts=[
     ["In a dark room, shine the light down below the inner eye corner",
      "Correct. In a dark room the light shines down just below the inner corner of the eye, with the patient's mouth open."],
     ["In a dark room, shine the light up under the brow close to the nose",
      "Shining the light up under the brow close to the nose is the frontal sinus technique, not the maxillary one."],
     ["In a bright room, shine the light through the cheek from the side",
      "A dark room is required, and the light is placed below the medial canthus."],
     ["Shine the light into the nostril and look at the forehead",
      "Shining the light into the nostril tests nothing; the maxillary sinus is lit from below the medial canthus."]],
   c=0, cite=c(54)),

 dict(topic="Nose exam", io=IO, slot="test finding",
   q="Which interpretation of an ABSENT glow on sinus transillumination is correct?",
   opts=[
     ["Thickened mucosa or secretions, but the test is not specific",
      "Correct. Absence of glow suggests thickened mucosa or secretions, but transillumination is neither sensitive nor specific."],
     ["Thickened mucosa or secretions, and it is diagnostic of sinusitis",
      "Transillumination is neither sensitive nor specific, so an absent glow cannot be diagnostic of sinusitis on its own."],
     ["A normal air-filled sinus",
      "An air-filled sinus transmits the light, so a normal sinus GLOWS."],
     ["A deviated septum",
      "Transillumination looks at the sinuses, not the septum; an absent glow suggests thickened mucosa or secretions."]],
   c=0, cite=c(54)),

 dict(topic="Sinusitis", io=IO, slot="test finding",
   q="Which statement about discharge in acute sinusitis is correct?",
   opts=[
     ["Purulent discharge is suggestive",
      "Correct, and the distinction matters — patients and clinicians both over-read green discharge as proof of bacterial infection. But the COLOR of the discharge is not diagnostic."],
     ["Green discharge is diagnostic of bacterial infection",
      "Discharge color is not diagnostic, so green discharge does not prove bacterial infection; purulence is only suggestive."],
     ["Clear discharge excludes sinusitis",
      "Clear discharge does not exclude sinusitis, because discharge color is not diagnostic in either direction."],
     ["Discharge is absent in acute sinusitis",
      "Nasal discharge is one of the suggestive features of acute sinusitis, along with local tenderness, pain and fever."]],
   c=0, cite=c(55)),

 dict(topic="Sinusitis", io=IO, slot="differential",
   q="Under what symptom duration is acute BACTERIAL sinusitis unlikely?",
   opts=[
     ["Less than seven days",
      "Correct. Most cases under a week are viral, which is the single most useful piece of timing in the nose section."],
     ["Less than three days",
      "Three days is too short a threshold; acute bacterial sinusitis is unlikely whenever symptoms have lasted under seven days."],
     ["Less than four weeks",
      "Four weeks is the boundary between acute and subacute disease, not the bacterial threshold."],
     ["Less than twelve weeks",
      "Twelve weeks is not the threshold; acute bacterial sinusitis is unlikely when symptoms have lasted under seven days."]],
   c=0, cite=c(55)),

 dict(topic="Septal hematoma", io=IO, slot="etiology",
   q="How does a septal hematoma form?",
   opts=[
     ["Injured vessels bleed between the lining and the cartilage",
      "Correct. Injury disrupts the blood vessels and pulls the lining away from the cartilage, allowing blood to collect between the two."],
     ["Blood collects within the cartilage itself",
      "Blood does not collect inside the cartilage; it collects between the septal lining and the cartilage beneath it."],
     ["Chronic inflammation erodes the septum until it bleeds",
      "Erosion through the septum describes a perforation, caused by trauma, surgery or drug use, not a hematoma."],
     ["Venous engorgement of the turbinates spreads to the septum",
      "Turbinate engorgement is not the mechanism; a hematoma is blood collecting between the septal lining and the cartilage."]],
   c=0, cite=c(57)),

 dict(topic="Septal hematoma", io=IO, slot="complication",
   q="Why does a septal hematoma require URGENT drainage?",
   opts=[
     ["To prevent necrosis of the septal cartilage",
      "Correct. The cartilage has no blood supply of its own — it depends on the lining that the hematoma has stripped away, so the clock starts immediately."],
     ["To prevent the blood tracking into the orbit",
      "Orbital spread is not the reason; drainage is urgent to prevent necrosis of the septal cartilage."],
     ["To prevent airway obstruction",
      "Obstruction may occur but is not why the drainage is urgent."],
     ["To prevent secondary sinusitis",
      "Infection is not the reason for urgency; drainage is urgent to prevent necrosis of the septal cartilage."]],
   c=0, cite=c(57)),
]
