# -*- coding: utf-8 -*-
# PD2 Lecture 3 -- pool C: acuity, fields, ocular motility, the pupils,
# fundoscopy, trauma and disposition.
#
# EXCLUSIONS OBSERVED HERE:
#  * the CORNEAL REFLECTION test -- "we've already done this, so I'm not gonna
#    test you on it ... we already did that in PD1"
#  * the ADIE'S PUPIL ASSOCIATIONS slide (dysautonomia, Shy-Drager, diabetes,
#    amyloidosis) -- "it's not on my test this time". ADIE'S PUPIL ITSELF IS IN:
#    "you should know Adie's pupil, that could be on my test."
#  * the LATIN EXPANSIONS of OD/OS/OU -- "I don't care if you remember Oculus
#    Sinister or Dexter." THE ABBREVIATIONS ARE IN: "those are terms that you
#    must remember."
#
# Correct answer is ALWAYS written first (c=0); the partition script rotates.
SRC = "PD II Advanced Exam Ocular Lecture - Beck.pptx"
def c(n): return f"{SRC}, Slide {n}"
def ci(n): return f"{SRC}, Slide {n} (image only)"
def au(): return "Lecture recording, 26 August 2026"

IO = "Instructional Objectives — Advanced Ocular Medical History and Examination"

POOL_C = [
 dict(topic="Visual acuity", io=IO, slot="test finding",
   q="Which statement correctly defines OD and OU?",
   opts=[
     ["OD is the right eye; OU is both eyes",
      "Correct — OD refers to the right eye, OS to the left eye and OU to both eyes."],
     ["OS is the right eye; OD is both eyes",
      "OS refers to the left eye, and OD is the right eye; both eyes are recorded as OU."],
     ["OU is the right eye; OS is both eyes",
      "OU refers to both eyes and OS to the left eye; the right eye is recorded as OD."],
     ["OD is the left eye; OS is the right",
      "This swaps them: OD is the right eye and OS the left eye, while OU refers to both eyes."]],
   c=0, cite=c(49)),

 dict(topic="Visual acuity", io=IO, slot="test finding",
   q="What does an acuity of 20/200 mean?",
   opts=[
     ["At 20 feet the patient reads print that a person with normal vision could read at 200 feet",
      "Correct — at 20 feet the patient reads what normal vision reads at 200 feet; the larger the second number, the worse the vision."],
     ["At 200 feet the patient reads print that a normal eye reads at 20 feet",
      "This reverses the distances: the patient stands at 20 feet, and 200 feet is where normal vision reads the same print."],
     ["The patient sees 20 percent of normal at 200 feet",
      "The notation is not a percentage; at 20 feet the patient reads print that normal vision reads at 200 feet."],
     ["The patient has 200 degrees of visual field at 20 feet",
      "Snellen notation measures acuity, not the field; at 20 feet the patient reads print normal vision reads at 200 feet."]],
   c=0, cite=c(49)),

 dict(topic="Visual acuity", io=IO, slot="test finding",
   q="Which refractive problem impairs near vision because the crystalline lens stiffens with age?",
   opts=[
     ["Presbyopia",
      "Correct — presbyopia is age-related stiffening of the crystalline lens, impairing near vision; the patient sees better with the card farther away."],
     ["Myopia",
      "Myopia, nearsightedness, impairs far vision rather than near vision, and it is not an age-related stiffening of the lens."],
     ["Astigmatism",
      "Astigmatism comes from unequal corneal or lenticular curvatures and blurs vision; lens stiffening with age is presbyopia."],
     ["Amblyopia",
      "Amblyopia is decreased vision from childhood; stiffening of the crystalline lens with age, impairing near vision, is presbyopia."]],
   c=0, cite="PD II Advanced Exam Ocular Lecture - Beck.pptx, Slide 50"),

 dict(topic="Pinhole test", io=IO, slot="test finding",
   q="What does the pinhole test distinguish?",
   opts=[
     ["A refractive error from other causes",
      "Correct — a pinhole passes only light perpendicular to the lens, so a deficit it corrects is refractive; if not, consider cataract or nerve disease."],
     ["Glaucoma from cataract, by measuring pressure indirectly",
      "The pinhole does not measure pressure, which is the tonometer pen's job; it separates refractive error from other causes."],
     ["A field defect from an acuity problem, by isolating quadrants",
      "Fields are tested by confrontation; the pinhole is an acuity test that separates refractive error from other causes."],
     ["An afferent from an efferent pupil defect",
      "Afferent defects are found with the swinging light test; the pinhole separates refractive error from other causes of poor acuity."]],
   c=0, cite=c(52)),

 dict(topic="Pinhole test", io=IO, slot="differential",
   q="If a visual deficit is NOT corrected by pinhole testing, what should be considered?",
   opts=[
     ["Cataract, optic nerve disease, or retinal disease",
      "Correct — if the pinhole does not correct the deficit, consider cataracts, optic nerve disease or retinal disease."],
     ["Simple myopia or astigmatism",
      "Myopia and astigmatism are refractive errors, which the pinhole corrects; uncorrected loss suggests cataract, nerve or retinal disease."],
     ["Dry eye",
      "Dry eye is not among the causes to consider; uncorrected loss suggests cataract, optic nerve disease or retinal disease."],
     ["Blepharitis",
      "Blepharitis is a lid inflammation, not a cause to consider; uncorrected loss suggests cataract, optic nerve or retinal disease."]],
   c=0, cite=c(52)),

 dict(topic="Visual fields", io=IO, slot="initial test",
   q="Which two tests together make up the best confrontation field examination?",
   opts=[
     ["The static finger wiggle test and the kinetic red target test",
      "Correct — confrontation fields are best tested by combining the static finger wiggle test with the kinetic red target test."],
     ["The swinging light test and the cover-uncover test",
      "The swinging light test checks optic nerve function and cover-uncover muscle imbalance; fields use finger wiggle and red target."],
     ["The pinhole test and the Snellen chart",
      "The pinhole and Snellen chart test visual acuity; confrontation fields use the finger wiggle and kinetic red target tests."],
     ["Tonometry and fundoscopy",
      "Tonometry measures intraocular pressure and fundoscopy views the disc and retina; fields use the finger wiggle and red target tests."]],
   c=0, cite=c(53)),

 dict(topic="Visual fields", io=IO, slot="initial test",
   q="How is the static finger wiggle test performed?",
   opts=[
     ["Wiggling fingers brought slowly inward from beside the ears until seen",
      "Correct — at arm's length, hands two feet apart beside the ears, wiggling fingers come slowly inward until seen, quadrant by quadrant."],
     ["Moving a red-topped pin inward from beyond each quadrant boundary",
      "A red-topped pin moved in from each quadrant is the kinetic red target test, the static test's partner."],
     ["Shining a light alternately into each eye",
      "Swinging a light between the eyes is the swinging light test of optic nerve function, not a field test."],
     ["Covering and uncovering each eye in turn",
      "Covering and uncovering each eye reveals slight muscle imbalance; it is not a visual field test."]],
   c=0, cite=c(53)),

 dict(topic="Visual fields", io=IO, slot="initial test",
   q="How is the kinetic red target test performed?",
   opts=[
     ["Move a 5 mm red-topped pin inward from beyond the boundary of each quadrant along a line bisecting the meridians, and ask when the pin first appears RED",
      "Correct — a 5 mm red-topped pin moves inward along lines bisecting the meridians, and the endpoint is when it first appears red."],
     ["Move a white target inward and ask when it is first seen at all",
      "The target is a 5 mm red-topped pin, and the endpoint is when it first appears red, not when it is first seen."],
     ["Wiggle the fingers and bring them into view",
      "Wiggling fingers into view is the static finger wiggle test; the kinetic test uses a 5 mm red-topped pin."],
     ["Ask the patient to count fingers at each quadrant",
      "Counting fingers is not this test; the kinetic test moves a 5 mm red pin inward and asks when it first looks red."]],
   c=0, cite=c(54)),

 dict(topic="Visual fields", io=IO, slot="test finding",
   q="Where is the normal blind spot found?",
   opts=[
     ["15 degrees temporal to the line of gaze",
      "Correct — the blind spot sits 15 degrees temporal to the line of gaze and enlarges in glaucoma, optic neuritis and papilledema."],
     ["15 degrees nasal to the line of gaze; enlarged in cataract",
      "It is temporal, not nasal, and optic nerve conditions such as glaucoma, optic neuritis and papilledema enlarge it."],
     ["At the center of the visual field; enlarged in macular degeneration",
      "The blind spot is not central; it lies 15 degrees temporal to the line of gaze."],
     ["30 degrees temporal; enlarged in retinal detachment",
      "It lies 15 degrees temporal, not 30, and it enlarges in glaucoma, optic neuritis and papilledema."]],
   c=0, cite=c(55)),

 dict(topic="Visual fields", io=IO, slot="test finding",
   q="A temporal field defect in one eye should prompt what?",
   opts=[
     ["Testing for a nasal defect in the other eye",
      "Correct — a temporal defect in one eye may suggest a nasal defect in the other eye, so test that possibility."],
     ["Immediate fundoscopy of the same eye only",
      "Fundoscopy is not the next step; a temporal defect in one eye may mean a nasal defect in the other, which should be tested."],
     ["Repeating acuity in the same eye",
      "Acuity is not the next step; a temporal field defect in one eye should prompt testing the other eye for a nasal defect."],
     ["Measuring intraocular pressure",
      "Pressure is not the next step; a temporal field defect in one eye should prompt testing the other eye for a nasal defect."]],
   c=0, cite=c(55)),

 dict(topic="Extraocular movement", io=IO, slot="test finding",
   q="What is nystagmus?",
   opts=[
     ["Fine rhythmic oscillation of the eyes",
      "Correct — nystagmus is fine rhythmic oscillation of the eyes, and a few beats on lateral gaze are normal."],
     ["Misalignment of the visual axes — a few degrees is normal",
      "Nonalignment of the eyes is strabismus; nystagmus is fine rhythmic oscillation of the eyes."],
     ["Drooping of the upper lid — a few millimeters is normal",
      "Drooping of the upper lid is ptosis; nystagmus is fine rhythmic oscillation of the eyes."],
     ["Unequal pupil size — a few millimeters is normal",
      "Unequal pupils are anisocoria, where half to one millimeter is common; nystagmus is fine rhythmic oscillation of the eyes."]],
   c=0, cite=c(63)),

 dict(topic="Extraocular movement", io=IO, slot="escalation",
   q="What should you do if nystagmus is seen on lateral gaze?",
   opts=[
     ["Bring the finger back into binocular vision",
      "Correct — bring the finger back into binocular vision; nystagmus that persists there suggests a neurologic condition."],
     ["Repeat the test with the other eye covered",
      "Covering an eye is not the step; bring the finger back into the binocular field and see whether the nystagmus persists."],
     ["Refer immediately regardless",
      "A few beats on lateral gaze are normal, so first bring the finger back into binocular vision and see if it persists."],
     ["Measure the intraocular pressure",
      "Pressure has no role here; bring the finger back into binocular vision and consider neurologic disease if nystagmus persists."]],
   c=0, cite=c(63)),

 dict(topic="Cover-uncover test", io=IO, slot="initial test",
   q="What does the cover-uncover test reveal?",
   opts=[
     ["A slight muscle imbalance not otherwise seen",
      "Correct — the cover-uncover test may reveal a slight muscle imbalance not otherwise seen."],
     ["An afferent pupillary defect",
      "An afferent pupillary defect is found with the swinging light test; cover-uncover reveals slight muscle imbalance."],
     ["A refractive error",
      "Refractive error is shown by pinhole testing; the cover-uncover test reveals slight muscle imbalance."],
     ["A field defect",
      "Field defects are found by confrontation testing; the cover-uncover test reveals slight muscle imbalance."]],
   c=0, cite=c(67)),

 dict(topic="Lid lag", io=IO, slot="test finding",
   q="What is a positive lid lag test?",
   opts=[
     ["The rim of sclera is visible above the iris on downward gaze",
      "Correct — in lid lag the eye and lid do not move together, so sclera shows above the iris on downgaze; it suggests hyperthyroidism."],
     ["The upper lid droops below the pupil at rest — most often myasthenia gravis",
      "A drooping upper lid is ptosis; a positive lid lag shows a rim of sclera above the iris on downward gaze."],
     ["The lower lid turns outward — most often aging",
      "An out-turned lower lid is ectropion, common in the elderly; lid lag shows sclera above the iris on downward gaze."],
     ["The eye is displaced forward — most often orbital tumor",
      "Forward displacement of the eye is proptosis; lid lag shows a rim of sclera above the iris on downward gaze."]],
   c=0, cite=c(69)),

 dict(topic="Pupils", io=IO, slot="test finding",
   q="How much difference in pupil size is common?",
   opts=[
     ["Half to one millimeter is common",
      "Correct — a difference of half to one millimeter is common, and anisocoria is benign if the pupillary reactions are normal."],
     ["Any difference at all is abnormal",
      "Small differences are common: half to one millimeter is normal, and a difference over 1 mm is abnormal."],
     ["Up to three millimeters is common",
      "Three millimeters is too much; half to one millimeter is common, and more than 1 mm is abnormal."],
     ["It is benign only if both pupils are under three millimeters",
      "Benign anisocoria depends on normal pupillary reactions, not absolute size; half to one millimeter of difference is common."]],
   c=0, cite=c(70)),

 dict(topic="Pupils", io=IO, slot="test finding",
   q="Which pupil finding is abnormal?",
   opts=[
     ["A difference in size greater than 1 mm",
      "Correct — a size difference greater than 1 mm is abnormal, as is a pupil that reacts poorly to direct light."],
     ["Any pupil under 4 mm",
      "A pupil under 4 mm is not abnormal by itself; a size difference greater than 1 mm or a poorly reactive pupil is."],
     ["Any pupil that constricts to light",
      "Constricting to direct light is the normal direct reflex; a poorly reactive pupil is what is abnormal."],
     ["Equal pupils that both react briskly",
      "Equal, briskly reacting pupils are normal; a size difference over 1 mm or a poorly reactive pupil is abnormal."]],
   c=0, cite=c(71)),

 dict(topic="Pupils", io=IO, slot="escalation",
   q="An acute, significantly dilated pupil is a medical emergency particularly when accompanied by what?",
   opts=[
     ["Headache or other neurologic signs",
      "Correct — with headache or neurologic signs, an acutely dilated pupil may mean uncal herniation or a posterior communicating artery aneurysm."],
     ["Itching or discharge — from allergic conjunctivitis",
      "Itching and discharge point to allergy, which leaves the pupil unaffected; headache or neurologic signs make the dilated pupil an emergency."],
     ["Fever — from orbital cellulitis",
      "Fever is not the warning pairing; an acutely dilated pupil is an emergency with headache or other neurologic signs."],
     ["Blurred vision alone — from cataract",
      "Cataract is a lens opacity that does not dilate the pupil; headache or neurologic signs make a dilated pupil an emergency."]],
   c=0, cite=c(73)),

 dict(topic="Swinging light test", io=IO, slot="initial test",
   q="Which purpose and indication describe the swinging light test?",
   opts=[
     ["Functional impairment of the optic nerve and the integrity of the visual pathways; indicated for anisocoria",
      "Correct — the swinging light test checks optic nerve function and visual pathway integrity, and its indication is anisocoria."],
     ["Alignment of the visual axes; indicated for diplopia",
      "Muscle imbalance is revealed by the cover-uncover test; the swinging light test assesses optic nerve function for anisocoria."],
     ["Refractive error; indicated for blurred vision",
      "Refractive error is shown by the pinhole test; the swinging light test assesses optic nerve function and is indicated for anisocoria."],
     ["Intraocular pressure; indicated for headache",
      "Pressure is measured with a tonometer pen; the swinging light test assesses optic nerve function and is indicated for anisocoria."]],
   c=0, cite=c(74)),

 dict(topic="Swinging light test", io=IO, slot="test finding",
   q="What is the abnormal finding on the swinging light test?",
   opts=[
     ["Paradoxical pupil DILATION to direct light with an intact consensual reflex",
      "Correct — an afferent optic nerve lesion, the Marcus Gunn pupil, dilates paradoxically to direct light while the consensual reflex stays intact."],
     ["Failure of the consensual reflex with a normal direct reflex — an efferent defect",
      "The abnormal response is afferent, from the optic nerve: the consensual reflex is intact and the pupil dilates to direct light."],
     ["Both pupils constricting more than expected",
      "Brisk constriction of both pupils is the normal response; the abnormal one is paradoxical dilation to direct light."],
     ["The pupil failing to constrict on accommodation only",
      "A pupil that fails only on accommodation is not the finding; the swinging light abnormality is paradoxical dilation to direct light."]],
   c=0, cite=c(76)),

 dict(topic="Swinging light test", io=IO, slot="etiology",
   q="Why does moving the light to the affected eye cause BOTH pupils to dilate in an afferent defect?",
   opts=[
     ["The afferent stimulus on that side is reduced",
      "Correct — the reduced afferent stimulus reduces the efferent signals to both pupils, so a net dilation occurs."],
     ["The affected pupil is pharmacologically blocked",
      "Pharmacologic sphincter block is a cause of a dilated pupil, but the swinging light dilation comes from reduced afferent input."],
     ["The oculomotor nerve is compressed on that side",
      "Oculomotor compression causes a fixed dilated pupil; the swinging light dilation comes from reduced afferent input from the optic nerve."],
     ["The ciliary ganglion has degenerated",
      "Ciliary ganglion degeneration causes Adie's tonic pupil; the swinging light dilation comes from reduced afferent input."]],
   c=0, cite=c(77)),

 dict(topic="Near reaction", io=IO, slot="etiology",
   q="Which nerve mediates the pupillary constriction of the near reaction?",
   opts=[
     ["The oculomotor nerve; accompanied by convergence and accommodation",
      "Correct — the oculomotor nerve mediates the near constriction; convergence and accommodation happen alongside it but are not part of it."],
     ["The optic nerve; accompanied by convergence and dilation",
      "The oculomotor nerve, not the optic nerve, mediates the near constriction, and the pupils constrict rather than dilate."],
     ["The trochlear nerve; accompanied by depression and intorsion",
      "The trochlear nerve does not mediate it; the near constriction, like the light reaction, is mediated by the oculomotor nerve, cranial nerve III."],
     ["The abducens nerve; accompanied by abduction",
      "The abducens nerve does not mediate it, and the eyes converge rather than abduct; the near constriction is mediated by the oculomotor nerve."]],
   c=0, cite=c(80)),

 dict(topic="Adie's tonic pupil", io=IO, slot="test finding",
   q="What are the pupil findings in Adie's tonic pupil?",
   opts=[
     ["Large, regular, usually unilateral",
      "Correct — Adie's pupil is large, regular and usually unilateral, with a reduced light reaction and a very slow near reaction."],
     ["Small, unequal and irregular; no light reaction but constricts on accommodation",
      "Small, irregular pupils that accommodate but do not react to light are the Argyll Robertson pupil; Adie's is large and regular."],
     ["Small but briskly reactive, with ptosis and anhidrosis",
      "A small, briskly reactive pupil with ptosis and anhidrosis is Horner syndrome; Adie's pupil is large and regular."],
     ["Dilated and fixed to both light and near, with ptosis and lateral deviation",
      "A dilated pupil fixed to light and near, with ptosis and lateral deviation, is oculomotor palsy; Adie's keeps a slow near reaction."]],
   c=0, cite=c(82)),

 dict(topic="Adie's tonic pupil", io=IO, slot="etiology",
   q="What is the underlying lesion in Adie's tonic pupil?",
   opts=[
     ["Degeneration of the ciliary ganglia and the postganglionic parasympathetic fibers",
      "Correct — Adie's pupil results from degeneration of the ciliary ganglia and the postganglionic parasympathetic fibers."],
     ["Interruption of the sympathetic supply",
      "Interrupted sympathetic supply produces Horner syndrome's small pupil; Adie's comes from ciliary ganglion degeneration."],
     ["Compression of the oculomotor nerve",
      "Oculomotor compression gives a dilated pupil fixed to light and near; Adie's comes from ciliary ganglion degeneration."],
     ["Demyelination of the optic nerve",
      "Optic nerve disease causes an afferent defect; Adie's comes from degeneration of the ciliary ganglia and parasympathetic fibers."]],
   c=0, cite=c(82)),

 dict(topic="Argyll Robertson pupil", io=IO, slot="test finding",
   q="What is the defining behavior of the Argyll Robertson pupil?",
   opts=[
     ["It accommodates but does not react to light",
      "Correct — the Argyll Robertson pupil does not react to light but constricts on accommodation: it accommodates but does not react."],
     ["It reacts to light but does not accommodate",
      "This reverses it: the Argyll Robertson pupil constricts on accommodation but does not react to light."],
     ["It reacts to neither light nor accommodation",
      "It still reacts to accommodation; the Argyll Robertson pupil fails only the light reaction."],
     ["It reacts to both, but slowly",
      "A slow light and near response is closer to Adie's tonic pupil; the Argyll Robertson pupil does not react to light at all."]],
   c=0, cite=c(84)),

 dict(topic="Argyll Robertson pupil", io=IO, slot="etiology",
   q="Which conditions is the Argyll Robertson pupil associated with?",
   opts=[
     ["Classically tertiary syphilis, but today more often diabetes; also described in Lyme meningoradiculitis",
      "Correct — classically tertiary syphilis, but today more likely seen in diabetics, and also described in Lyme meningoradiculitis."],
     ["Only tertiary syphilis",
      "Syphilis is only the classical association; today it is more likely seen in diabetics, and it occurs in Lyme meningoradiculitis."],
     ["Multiple sclerosis and optic neuritis",
      "Multiple sclerosis and optic neuritis cause optic atrophy; the Argyll Robertson pupil goes with syphilis, diabetes and Lyme disease."],
     ["Graves disease and myasthenia gravis",
      "Graves disease causes proptosis and myasthenia gravis ptosis; the Argyll Robertson pupil goes with syphilis, diabetes and Lyme disease."]],
   c=0, cite=c(85)),

 dict(topic="Argyll Robertson pupil", io=IO, slot="test finding",
   q="What happens when a mydriatic is instilled in an Argyll Robertson pupil?",
   opts=[
     ["Incomplete dilation", "Correct — mydriatics cause only an incomplete dilation of an Argyll Robertson pupil."],
     ["Full and rapid dilation", "The dilation is incomplete, not full; mydriatics only partly dilate the small, irregular Argyll Robertson pupil."],
     ["No change at all", "The pupil does respond, but incompletely; mydriatics cause an incomplete dilation of an Argyll Robertson pupil."],
     ["Paradoxical constriction", "A mydriatic dilates rather than constricts; in an Argyll Robertson pupil the dilation is simply incomplete."]],
   c=0, cite=c(84)),

 dict(topic="Dilated pupil", io=IO, slot="differential",
   q="Once local eye disease is excluded, which of these remains a cause of a dilated pupil?",
   opts=[
     ["Compression or other lesion of the third cranial nerve",
      "Correct — the three remaining causes are a third nerve lesion, ciliary ganglion damage causing Adie's pupil, and pharmacologic sphincter block."],
     ["Glaucoma, cataract and macular degeneration",
      "Those are local eye diseases, already excluded; what remains is a third nerve lesion, an Adie's pupil or a pharmacologic block."],
     ["Horner syndrome, myasthenia gravis and Graves disease",
      "Horner syndrome gives a SMALL pupil; what remains is a third nerve lesion, an Adie's pupil or a pharmacologic block."],
     ["Optic neuritis, papilledema and optic atrophy",
      "Optic nerve disease affects the afferent limb; the remaining causes are a third nerve lesion, an Adie's pupil or pharmacologic block."]],
   c=0, cite=c(86)),

 dict(topic="Horner syndrome", io=IO, slot="test finding",
   q="Which three features define Horner syndrome?",
   opts=[
     ["Ptosis, miosis of the affected eye, anhidrosis of the ipsilateral face",
      "Correct — Horner syndrome gives ptosis, miosis and ipsilateral facial anhidrosis, and the small pupil still reacts to light and near."],
     ["Ptosis, mydriasis, lateral deviation, and a fixed pupil",
      "A fixed dilated pupil with ptosis and lateral deviation is oculomotor palsy; Horner gives ptosis, miosis and anhidrosis."],
     ["Lid lag, proptosis, chemosis and diplopia",
      "Lid lag and proptosis are hyperthyroid and Graves signs; Horner syndrome gives ptosis, miosis and anhidrosis."],
     ["A large slow pupil with reduced light reaction and slow near reaction",
      "A large pupil with slow light and near reactions is Adie's tonic pupil; Horner syndrome gives a small pupil with ptosis."]],
   c=0, cite=c(88)),

 dict(topic="Horner syndrome", io=IO, slot="etiology",
   q="What is interrupted in Horner syndrome?",
   opts=[
     ["The sympathetic innervation of the pupil and the levator palpebrae superioris",
      "Correct — interrupting sympathetic supply to the pupil and levator palpebrae superioris explains both the miosis and the ptosis."],
     ["The parasympathetic supply through the ciliary ganglion",
      "Parasympathetic loss at the ciliary ganglion produces Adie's tonic pupil; Horner syndrome is a sympathetic interruption."],
     ["The oculomotor nerve",
      "Oculomotor paralysis gives a dilated fixed pupil with lateral deviation; Horner syndrome is a sympathetic interruption."],
     ["The optic nerve",
      "Optic nerve damage gives an afferent (Marcus Gunn) defect; Horner syndrome is a sympathetic interruption."]],
   c=0, cite=c(88)),

 dict(topic="Horner syndrome", io=IO, slot="test finding",
   q="What additional finding appears in CONGENITAL Horner syndrome?",
   opts=[
     ["The involved iris is lighter in color",
      "Correct — in congenital Horner syndrome the involved iris is lighter in color than its fellow, which is called heterochromia."],
     ["The involved iris is darker in color",
      "The involved iris is lighter, not darker, than its fellow in congenital Horner syndrome."],
     ["Bilateral ptosis",
      "Horner ptosis affects the involved side; the congenital form adds a lighter iris on that side, called heterochromia."],
     ["Proptosis of the affected eye",
      "Proptosis signals orbital disease; congenital Horner syndrome adds a lighter iris on the affected side."]],
   c=0, cite=c(87)),

 dict(topic="Oculomotor palsy", io=IO, slot="test finding",
   q="What is the pupil finding in an oculomotor nerve palsy?",
   opts=[
     ["A dilated pupil fixed to both light and near effort",
      "Correct — in oculomotor paralysis the dilated pupil is fixed to light and near effort, with ptosis and lateral deviation."],
     ["A small pupil that reacts briskly, with ptosis and anhidrosis",
      "A small, briskly reactive pupil with ptosis and anhidrosis is Horner syndrome, not an oculomotor palsy."],
     ["A large pupil with a slow but present near reaction",
      "A large pupil with a very slow but present near reaction is Adie's tonic pupil; the third nerve pupil is fixed."],
     ["Small irregular pupils that accommodate but do not react",
      "Small irregular pupils that accommodate but do not react are Argyll Robertson pupils; the third nerve pupil is dilated and fixed."]],
   c=0, cite=c(89)),

 dict(topic="Oblique lighting", io=IO, slot="test finding",
   q="What does the crescent shadow test with oblique lighting assess?",
   opts=[
     ["The depth of the anterior chamber angle",
      "Correct — a shadow on the medial iris means it is bowed forward into a narrow angle, raising the risk of narrow-angle glaucoma."],
     ["Corneal clarity — a shadow means an epithelial defect",
      "Areas of cornea devoid of epithelium are shown by fluorescein uptake; the oblique light shadow reflects a narrow angle."],
     ["Lens opacity — a shadow means cataract",
      "Cataract is seen as a lens opacity through the pupil; the oblique light shadow reflects a narrow iris-cornea angle."],
     ["Pupil reactivity — a shadow means an afferent defect",
      "Afferent defects are found with the swinging light test; the oblique light shadow reflects a narrow angle."]],
   c=0, cite=c(90)),

 dict(topic="Corneal scar", io=IO, slot="differential",
   q="How is a corneal scar distinguished from a cataract on examination?",
   opts=[
     ["The scar is a superficial grayish-white corneal opacity",
      "Correct — a corneal scar is a superficial grayish white opacity, while a cataract lies deeper and is seen only through the pupil."],
     ["The scar is visible only through the pupil; the cataract is superficial",
      "This reverses them: the scar is superficial in the cornea, and the cataract is on a deeper plane, seen through the pupil."],
     ["The scar is painful; the cataract is not",
      "Pain does not separate them; the scar is a superficial corneal opacity and the cataract lies deeper, behind the pupil."],
     ["The scar affects vision more than the cataract",
      "Effect on vision is not the test; the scar is a superficial corneal opacity and the cataract lies deeper, behind the pupil."]],
   c=0, cite=c(92)),

 dict(topic="Fundoscopy", io=IO, slot="avoid",
   q="In which three situations should the pupils NOT be dilated?",
   opts=[
     ["If serial neurologic examinations are required, in elderly patients who have had cataract surgery, and if acute angle-closure glaucoma is suspected",
      "Correct — do not dilate when serial neurologic exams are needed, in elderly patients after cataract surgery, or if angle closure is suspected."],
     ["In any patient over sixty-five, in diabetics, and in contact lens wearers",
      "Age alone is not the rule; it is elderly patients who have had cataract surgery, plus serial neurologic exams and suspected angle closure."],
     ["If the patient has conjunctivitis, blepharitis or dry eye",
      "Surface conditions are not contraindications; avoid dilation for serial neurologic exams, post-cataract elderly patients and suspected angle closure."],
     ["If visual acuity is reduced in either eye",
      "Reduced acuity is not a contraindication; avoid dilation for serial neurologic exams, post-cataract elderly patients or suspected angle closure."]],
   c=0, cite=c(99)),

 dict(topic="Fundoscopy", io=IO, slot="education",
   q="What must be documented when the pupils are dilated?",
   opts=[
     ["The time of dilation and the agents used",
      "Correct — record the time of dilation and the agents used; a weak mydriatic reverses in 4 to 6 hours."],
     ["The visual acuity before dilation only",
      "Acuity is not what dilation requires you to record; document the time of dilation and the agents used."],
     ["The patient's consent form number",
      "A form number is not what is recorded; document the time of dilation and the agents used."],
     ["Nothing specific",
      "Dilation must be documented: record both the time of dilation and the agents used."]],
   c=0, cite=c(99)),

 dict(topic="Normal fundus", io=IO, slot="test finding",
   q="What is the normal appearance of the fundus and disc?",
   opts=[
     ["Yellowish-orange to cream color, small disc vessels, a sharp disc margin, and a cup located centrally or slightly temporal with a diameter normally less than half the disc",
      "Correct — the normal fundus is yellowish orange to cream, with a sharp disc margin and a central cup under half the disc diameter."],
     ["Pink with blurred margins and no visible cup",
      "A pink swollen disc with blurred margins and no visible cup is papilledema from raised intracranial pressure."],
     ["White with absent tiny disc vessels",
      "A white disc with absent tiny vessels is optic atrophy, from death of optic nerve fibers."],
     ["An enlarged cup with vessels sinking in around the disc",
      "An enlarged cup with vessels sinking in is glaucomatous cupping; the normal cup is less than half the disc diameter."]],
   c=0, cite=c(102)),

 dict(topic="Papilledema", io=IO, slot="test finding",
   q="What are the fundoscopic findings in papilledema?",
   opts=[
     ["A pink swollen disc with blurred margins and no visible cup, with loss of vessel pulsations",
      "Correct — increased intracranial pressure swells the disc: pink, margins blurred, cup not visible, vessel pulsations lost."],
     ["A white disc with absent tiny vessels — from death of optic nerve fibers",
      "A white disc with absent tiny vessels is optic atrophy; papilledema is a pink swollen disc with blurred margins."],
     ["An enlarged cup more than half the disc diameter — from raised intraocular pressure",
      "An enlarged cup over half the disc is glaucomatous cupping; papilledema is a swollen disc in which the cup is not visible."],
     ["Cotton-wool patches and hard exudates — from diabetes",
      "Cotton-wool patches and hard exudates are retinal lesions of diabetes and hypertension; papilledema is a swollen pink disc."]],
   c=0, cite=c(103)),

 dict(topic="Glaucomatous cupping", io=IO, slot="test finding",
   q="What are the fundoscopic findings in glaucomatous cupping?",
   opts=[
     ["An enlarged cup with vessels sinking in",
      "Correct — raised pressure in the eye enlarges the physiologic cup beyond half the disc diameter, with vessels sinking in around it."],
     ["A pink swollen disc with blurred margins",
      "A pink swollen disc with blurred margins is papilledema from raised intracranial pressure, where the cup is not visible."],
     ["A white disc with absent vessels",
      "A white disc without its tiny vessels is optic atrophy; glaucomatous cupping enlarges the cup beyond half the disc."],
     ["A cherry-red spot at the macula",
      "A cherry-red macula is not a cupping finding; glaucomatous cupping enlarges the cup beyond half the disc diameter."]],
   c=0, cite=c(103)),

 dict(topic="Optic atrophy", io=IO, slot="differential",
   q="Which description of optic atrophy is correct?",
   opts=[
     ["A white disc with absent tiny disc vessels, from death of optic nerve fibers — seen in optic neuritis, multiple sclerosis and temporal arteritis",
      "Correct — death of optic nerve fibers leaves a white disc without its tiny vessels, seen in optic neuritis, multiple sclerosis and temporal arteritis."],
     ["A pink swollen disc — seen in raised intracranial pressure",
      "A pink swollen disc from raised intracranial pressure is papilledema; optic atrophy leaves a white disc."],
     ["An enlarged cup — seen in glaucoma",
      "An enlarged cup is glaucomatous cupping; optic atrophy is a white disc with its tiny vessels absent."],
     ["Beading of the retinal veins — seen in diabetes",
      "Venous beading is severe nonproliferative diabetic retinopathy; optic atrophy is a white disc with absent tiny vessels."]],
   c=0, cite=c(105)),

 dict(topic="Trauma", io=IO, slot="etiology",
   q="How does the SIZE of the striking object change the injury?",
   opts=[
     ["Larger objects transfer most of the energy to the orbital rim",
      "Correct — larger objects transfer most of their energy to the orbital rim, while smaller objects may strike the globe itself."],
     ["Larger objects strike the globe directly; smaller objects hit the rim",
      "This reverses the mechanics: smaller objects may strike the globe directly, while larger ones load the orbital rim."],
     ["Object size makes no difference",
      "Size is important: it determines whether the periocular soft tissues or the globe itself is likely to be injured."],
     ["Only velocity matters, not size",
      "Velocity matters for penetration, but size matters too: larger objects hit the orbital rim, smaller ones the globe."]],
   c=0, cite=c(111)),

 dict(topic="Orbital fracture", io=IO, slot="test finding",
   q="Which examination findings suggest an orbital blow-out fracture?",
   opts=[
     ["A sunken eye, hypesthesia of the infraorbital area, diplopia particularly on upward gaze, decreased ocular motility, and sometimes an ipsilateral nosebleed",
      "Correct — an orbital fracture gives a sunken eye, infraorbital hypesthesia, diplopia on upgaze, reduced motility and sometimes a nosebleed."],
     ["Proptosis with painful restricted movement and fever",
      "Proptosis signals orbital disease such as orbital cellulitis; a blow-out fracture gives a sunken eye instead."],
     ["A fixed mid-dilated pupil with a cloudy cornea",
      "A dilated fixed pupil with a cloudy cornea fits acute glaucoma; a blow-out fracture gives a sunken eye and diplopia."],
     ["Flattening of the cheek with pain on opening the mouth",
      "A flattened cheek with pain on opening the mouth suggests a zygomatic fracture, not an orbital floor fracture."]],
   c=0, cite=c(114)),

 dict(topic="Enophthalmos", io=IO, slot="test finding",
   q="Which description fits a sunken eye from an orbital floor fracture?",
   opts=[
     ["Ecchymosis, point tenderness and a palpable step-off around the orbital rim — best observed from above the head looking down toward the eyes",
      "Correct — a sunken eye with ecchymosis, point tenderness and a rim step-off suggests a floor fracture; look down from above the head."],
     ["Fever and purulent discharge — best observed with a slit lamp",
      "Fever and purulent discharge suggest infection; a floor fracture shows ecchymosis, tenderness and a rim step-off, seen from above."],
     ["Photophobia and a dendrite — best seen with fluorescein",
      "Fluorescein is taken up by corneal defects; a floor fracture shows ecchymosis, tenderness and a rim step-off, seen from above."],
     ["A red painless patch — best seen in ambient light",
      "A painless red patch is a subconjunctival hemorrhage; a floor fracture shows ecchymosis, tenderness and a rim step-off."]],
   c=0, cite=c(115)),

 dict(topic="Zygomatic fracture", io=IO, slot="test finding",
   q="Which findings suggest a zygomatic fracture?",
   opts=[
     ["Flattening of the malar eminence best seen from behind the seated patient looking down, edema and ecchymosis of the temple or infraorbital area, and a palpable step-off on palpating the zygoma",
      "Correct — a zygomatic fracture flattens the malar eminence, seen from behind, with temple or infraorbital swelling and a palpable step-off."],
     ["A sunken eye with diplopia on upward gaze",
      "A sunken eye with diplopia on upward gaze points to an orbital floor fracture; the zygoma shows a flattened cheek."],
     ["Proptosis with restricted painful movement",
      "Proptosis signals orbital disease such as cellulitis or tumor; a zygomatic fracture flattens the cheek instead."],
     ["A 360-degree subconjunctival hemorrhage",
      "Hemorrhage encircling the cornea after trauma raises concern for globe rupture; a zygomatic fracture flattens the cheek."]],
   c=0, cite=c(117)),

 dict(topic="Zygomatic fracture", io=IO, slot="etiology",
   q="Why may a zygomatic fracture cause pain on opening the mouth?",
   opts=[
     ["The temporalis muscle passes medial to the arch and inserts on the mandible",
      "Correct — the temporalis passes medial to the zygomatic arch and inserts on the mandible, so a fracture can hurt on opening."],
     ["The masseter originates on the mandible and inserts on the zygoma",
      "The pain is explained by the temporalis, which passes medial to the arch and inserts on the mandible, not by the masseter."],
     ["The infraorbital nerve is compressed during jaw movement",
      "Infraorbital nerve damage causes hypesthesia of the infraorbital area; mouth-opening pain comes from the temporalis under the arch."],
     ["The temporomandibular joint is always involved",
      "The jaw joint is not the explanation; the temporalis passes medial to the zygomatic arch and inserts on the mandible."]],
   c=0, cite=c(116)),

 dict(topic="Hyphema", io=IO, slot="test finding",
   q="What is a hyphema?",
   opts=[
     ["Bleeding into the anterior chamber, usually from blunt trauma",
      "Correct — a hyphema is bleeding in the anterior chamber, normally from blunt trauma; check acuity, pupils, red reflex and pressure."],
     ["Blood beneath the conjunctiva — check the blood pressure only",
      "Blood beneath the conjunctiva is a subconjunctival hemorrhage; a hyphema is bleeding into the anterior chamber."],
     ["Pus in the anterior chamber — check for infection",
      "A hyphema is blood, not pus, in the anterior chamber, and it usually follows blunt trauma."],
     ["Bleeding into the vitreous — check the fundus only",
      "Vitreous bleeding reduces the red reflex; a hyphema is bleeding into the anterior chamber from blunt trauma."]],
   c=0, cite=c(118)),

 dict(topic="Corneal abrasion", io=IO, slot="test finding",
   q="Why must the upper lid be everted in a corneal abrasion?",
   opts=[
     ["A foreign body embedded in the upper tarsal conjunctiva can repeatedly scratch the cornea as the eye opens and closes",
      "Correct — a foreign body embedded in the upper tarsal conjunctiva can scratch the cornea each time the eye opens and closes."],
     ["To measure the intraocular pressure accurately",
      "Pressure is measured with a tonometer pen; eversion is to find a foreign body under the upper lid scratching the cornea."],
     ["To apply fluorescein more evenly",
      "Fluorescein is simply placed in the eye and viewed under blue light; eversion is to find a foreign body under the upper lid."],
     ["To assess the tear film",
      "The tear film is not the reason; eversion looks for a foreign body in the upper tarsal conjunctiva scratching the cornea."]],
   c=0, cite=c(120)),

 dict(topic="Corneal abrasion", io=IO, slot="avoid",
   q="What is the rule about topical anesthetic in corneal abrasion?",
   opts=[
     ["Use it for diagnosis, not as a treatment",
      "Correct — topical anesthetic brings immediate relief of an abrasion, but it is used for diagnosis and not as a treatment."],
     ["It should be prescribed for home use to control pain",
      "It is not a take-home treatment; topical anesthetic in abrasion is used for diagnosis only, despite the immediate relief."],
     ["It should never be used at all",
      "It is used, but for diagnosis: topical anesthetic brings immediate relief of an abrasion and is not a treatment."],
     ["It is only useful if the cornea is hazy",
      "A hazy cornea suggests bacterial infection; topical anesthetic is used for diagnosis of an abrasion, not treatment."]],
   c=0, cite=c(120)),

 dict(topic="Corneal abrasion", io=IO, slot="test finding",
   q="What does a HAZY cornea in a suspected abrasion suggest?",
   opts=[
     ["Bacterial infection should be suspected", "Correct — if the cornea is hazy in a suspected abrasion, a bacterial infection should be suspected."],
     ["The abrasion is healing normally", "Haziness is not a healing sign; in a suspected abrasion a hazy cornea should raise suspicion of bacterial infection."],
     ["The fluorescein was applied incorrectly", "Haziness is a finding in the cornea, not a staining error; it should raise suspicion of bacterial infection."],
     ["Raised intraocular pressure", "A steamy cornea goes with acute glaucoma's pressure rise; in an abrasion, haziness suggests bacterial infection."]],
   c=0, cite=c(120)),

 dict(topic="Fluorescein", io=IO, slot="initial test",
   q="How is a fluorescein stain performed?",
   opts=[
     ["Orange dye is instilled and a blue light used",
      "Correct — orange dye goes into the eye and a blue light shows foreign bodies or corneal damage, since bare areas take up the dye."],
     ["The dye stains intact epithelium and spares defects",
      "It is the reverse: the dye is taken up by areas of cornea devoid of epithelium, lit with a blue light."],
     ["The dye is injected and photographed with a blue flash",
      "The dye is placed in the eye, not injected; a blue light then shows foreign bodies or corneal damage."],
     ["The dye changes the color of the aqueous humor",
      "The dye is placed on the eye and viewed under blue light, where areas of cornea without epithelium take it up."]],
   c=0, cite=c(121)),

 dict(topic="Corneal ulcer", io=IO, slot="test finding",
   q="Which corneal ulcer is NOT very painful?",
   opts=[
     ["Herpes simplex corneal ulcers", "Correct — corneal ulcers usually bring pain and photophobia, but herpes simplex corneal ulcers are not very painful."],
     ["Bacterial corneal ulcers", "Bacterial ulcers cause pain, photophobia and tearing; it is herpes simplex ulcers that are not very painful."],
     ["Fungal corneal ulcers", "Fungal ulcers share the usual pain and photophobia; it is herpes simplex ulcers that are not very painful."],
     ["Amoebic corneal ulcers", "Amoebic ulcers share the usual pain and photophobia; it is herpes simplex ulcers that are not very painful."]],
   c=0, cite=c(122)),

 dict(topic="Corneal ulcer", io=IO, slot="initial test",
   q="At what setting can an ophthalmoscope be used to look for a corneal ulcer?",
   opts=[
     ["Set at +40 diopters, giving roughly a ten times magnifier",
      "Correct — +40 diopters in effect fixes a 10 times magnifying lens, though fluorescein staining is more sensitive for early ulcers."],
     ["Set at zero diopters — and this is more sensitive than fluorescein",
      "The setting is +40 diopters, not zero, and fluorescein staining is more sensitive than the ophthalmoscope for early ulcers."],
     ["Set at minus 20 diopters — with fluorescein being less sensitive",
      "The setting is +40 diopters, and fluorescein is the MORE sensitive test for early ulcers."],
     ["No ophthalmoscope setting is useful here",
      "The ophthalmoscope at +40 diopters acts as a 10 times magnifier that may reveal the corneal ulcer."]],
   c=0, cite=c(123)),

 dict(topic="Referral", io=IO, slot="referral",
   q="Which complaints fall in the EMERGENT group, referred to ophthalmology immediately?",
   opts=[
     ["Sudden vision loss, retinal artery occlusion, chemical burns, rupture, acute angle-closure glaucoma, and vitreous hemorrhage",
      "Correct — sudden vision loss, retinal artery occlusion, chemical burns, rupture, angle closure and vitreous hemorrhage go to ophthalmology immediately."],
     ["Acute glaucoma, orbital cellulitis, corneal ulcer or abrasion, retinal detachment, macular edema, and hyphema",
      "Those are the urgent complaints, sent for ophthalmology follow-up in one day or less rather than immediately."],
     ["Blepharitis, chalazion and dry eye",
      "None of these is on the emergent list, which includes sudden vision loss, chemical burns and globe rupture."],
     ["Conjunctivitis and subconjunctival hemorrhage",
      "A subconjunctival hemorrhage is usually harmless, and neither is emergent; chemical burns and rupture are."]],
   c=0, cite=c(124)),

 dict(topic="Referral", io=IO, slot="referral",
   q="Which of these belongs in the URGENT group, seen by ophthalmology within a day or less?",
   opts=[
     ["Acute glaucoma",
      "Correct — acute glaucoma is on the urgent list with orbital cellulitis, corneal ulcer or abrasion, retinal detachment and hyphema."],
     ["Sudden vision loss, chemical burns and globe rupture",
      "Those are emergent complaints, referred to ophthalmology immediately rather than within a day."],
     ["Dry eye and blepharitis",
      "Neither is on the urgent list, which includes acute glaucoma, orbital cellulitis, retinal detachment and hyphema."],
     ["Pinguecula and pterygium",
      "A pinguecula is harmless, and neither is on the urgent list, which includes acute glaucoma and retinal detachment."]],
   c=0, cite=c(124)),

 dict(topic="Referral", io=IO, slot="education",
   q="Which of these complaints should be referred to ophthalmology IMMEDIATELY?",
   opts=[
     ["Chemical burn",
      "Correct — chemical burns are emergent and go to ophthalmology immediately, as do rupture and sudden vision loss."],
     ["Hyphema",
      "Hyphema is urgent, not emergent: it needs ophthalmology follow-up within one day or less."],
     ["Orbital cellulitis",
      "Orbital cellulitis is urgent, not emergent: it needs ophthalmology follow-up within one day or less."],
     ["Corneal abrasion",
      "A corneal abrasion is urgent, not emergent: it needs ophthalmology follow-up within one day or less."]],
   c=0, cite="PD II Advanced Exam Ocular Lecture - Beck.pptx, Slide 124"),
]
