# -*- coding: utf-8 -*-
# Physical Diagnosis 2, Lecture 5 — pool B: murmurs, the manoeuvres, and the
# peripheral vascular examination. Pool A carries history through extra sounds.
#
# STANDING RULE: no question may depend on having the deck open.
# KEYS SHORT, explanations NAME the replacement rather than just negating.
from pd2_l5_pool_a import c, SRC

IO_MUR = "Identify the physical characteristics of cardiac thrills and murmurs"
IO_MAN = "Demonstrate the proper clinical skills for maneuvers to evaluate murmurs"
IO_PV = "Compare and contrast the physical examination findings related to abnormal peripheral arterial and venous function"
IO_ED = "Define the physical examination findings of peripheral edema"
IO_EX = "Demonstrate proper clinical skills for a complete and focused cardiovascular physical examination"

POOL_B = [

{"topic": "Murmurs", "io": IO_MUR, "slot": "manifestation",
 "q": "What produces a murmur?",
 "opts": [["Turbulent blood flow over a valve",
   "Correct, and it sounds like a swoosh. Five situations produce it: obstructed valve, increased flow through a normal valve, ejection into a dilated chamber, regurgitant flow, and abnormal shunting."],
  ["Closure of the atrioventricular valves",
   "That produces S1, a discrete heart sound rather than the sustained sound of turbulence."],
  ["Inflammation of the pericardial sac",
   "That produces a pericardial friction rub, described as scratchy and scraping."],
  ["Abrupt deceleration of a stenotic valve opening",
   "That produces an opening snap."]],
 "c": 0, "cite": c(46)},

{"topic": "Murmurs", "io": IO_MUR, "slot": "etiology",
 "q": "Which of these is a named cause of a murmur?",
 "opts": [["Ejection into a dilated chamber",
   "Correct, alongside flow across a partially obstructed valve, increased flow through a normal valve in a small child, regurgitant flow across an incompetent valve, and abnormal shunting to a lower pressure chamber."],
  ["Inflammation of the pericardium",
   "That produces a friction rub rather than a murmur."],
  ["Reduced ventricular compliance",
   "That produces S4, the atrial gallop."],
  ["High left ventricular filling pressure",
   "That produces a pathologic S3."]],
 "c": 0, "cite": c(46)},

{"topic": "Thrills", "io": IO_MUR, "slot": "test finding",
 "q": "How is a thrill assessed?",
 "opts": [["With the balls of the hand against the chest wall",
   "Correct — a thrill is the palpable vibration or buzzing of a murmur, easiest to feel in the position that accentuates that murmur."],
  ["With the fingertips over the apex",
   "The fingertips are used to locate the apical impulse; a thrill is felt with the balls of the hand."],
  ["With the diaphragm of the stethoscope",
   "The stethoscope hears murmurs; a thrill is a palpable finding."],
  ["With the thumb pressed for two seconds",
   "Thumb pressure held for two seconds tests for pitting oedema rather than for a thrill."]],
 "c": 0, "cite": c(47)},

{"topic": "Murmur characteristics", "io": IO_MUR, "slot": "test finding",
 "q": "Which seven characteristics describe a murmur?",
 "opts": [["Timing, shape, location, radiation, intensity",
   "Correct, and a complete description gives all seven — which is what allows two murmurs at the same site to be told apart. Pitch and quality complete the seven."],
  ["Timing, intensity and pitch only",
   "Those are three of the seven; shape, location, radiation and quality complete the list."],
  ["Onset, duration, severity and radiation",
   "The characteristics named are timing, shape, location, radiation, intensity, pitch and quality."],
  ["Systolic, diastolic and continuous",
   "Those are categories of timing rather than the full set of characteristics."]],
 "c": 0, "cite": c(48)},

{"topic": "Murmur timing", "io": IO_MUR, "slot": "test finding",
 "q": "How can palpating the carotid help with murmur timing?",
 "opts": [["Systolic murmurs match the carotid upstroke",
   "Correct — a systolic murmur falls between S1 and S2, a diastolic one between S2 and S1, and the carotid gives you an external marker for which is which."],
  ["Diastolic murmurs coincide with the carotid upstroke",
   "The carotid upstroke marks systole, so it is the systolic murmurs that coincide with it."],
  ["The carotid pulse identifies the murmur's intensity",
   "Intensity is graded on the six-point Levine scale rather than by the carotid."],
  ["The carotid pulse indicates the shape of the murmur",
   "Shape is the configuration of intensity over time, judged by listening."]],
 "c": 0, "cite": c(50)},

{"topic": "Murmur shape", "io": IO_MUR, "slot": "test finding",
 "q": "What defines the shape of a murmur?",
 "opts": [["Its intensity over time",
   "Correct — crescendo-decrescendo is diamond shaped, decrescendo begins at maximum and fades, and plateau does not change."],
  ["Where it is loudest on the chest wall",
   "That is location, found by exploring where the murmur is heard loudest."],
  ["Whether it radiates elsewhere",
   "Radiation is a separate characteristic from shape, describing where the sound travels."],
  ["Whether it is high, medium or low",
   "That is pitch, one of the other seven characteristics."]],
 "c": 0, "cite": c(54)},

{"topic": "Murmur shape", "io": IO_MUR, "slot": "test finding",
 "q": "What is a decrescendo murmur?",
 "opts": [["It begins at maximum and fades to silence",
   "Correct, and aortic regurgitation is the classic example — early diastolic, high frequency, decrescendo."],
  ["One that rises and then falls in intensity",
   "That is crescendo-decrescendo, the diamond shape of aortic and pulmonic stenosis."],
  ["One whose intensity does not change",
   "That is a plateau shape, seen in tricuspid regurgitation."],
  ["One that rises steadily to a peak at S2",
   "A murmur crescendoing up to S2 is the late systolic murmur following a mitral valve prolapse click."]],
 "c": 0, "cite": c(54)},

{"topic": "Murmur intensity", "io": IO_MUR, "slot": "test finding",
 "q": "How is murmur intensity graded?",
 "opts": [["A six-point scale, written as a fraction",
   "Correct — the Levine grading system, which is why a murmur is reported as, say, 3 out of 6 rather than as loud or soft."],
  ["On a four-point scale like pitting oedema",
   "Four-point grading applies to pitting oedema and to pulse amplitude rather than to murmurs."],
  ["As high, medium or low",
   "Those are the categories of pitch rather than intensity."],
  ["As blowing, harsh, rumbling or musical",
   "Those are the categories of quality."]],
 "c": 0, "cite": c(56)},

{"topic": "Murmur quality", "io": IO_MUR, "slot": "test finding",
 "q": "Which words describe the quality of a murmur?",
 "opts": [["Blowing, harsh, rumbling, musical",
   "Correct, and quality is distinct from pitch, which is categorised simply as high, medium or low."],
  ["High, medium, low",
   "Those are the categories of pitch."],
  ["Crescendo, decrescendo, plateau",
   "Those describe shape, the configuration of intensity over time."],
  ["Systolic, diastolic, continuous",
   "Those describe timing."]],
 "c": 0, "cite": c(57)},

{"topic": "Murmur location", "io": IO_MUR, "slot": "test finding",
 "q": "What does the radiation of a murmur help establish?",
 "opts": [["Site of origin, intensity, flow direction",
   "Correct, which is why radiation is recorded rather than treated as incidental — it carries information about the lesion itself. Bone conduction in the thorax as well."],
  ["The grade of the murmur on the six-point scale",
   "Intensity grading is a separate characteristic from where the sound travels."],
  ["Whether the murmur is innocent or pathologic",
   "That distinction rests on structural abnormality, physiologic state and the response to manoeuvres."],
  ["The patient's ejection fraction",
   "Ejection fraction is not something the physical examination measures."]],
 "c": 0, "cite": c(55)},

{"topic": "Innocent murmurs", "io": IO_MUR, "slot": "differential",
 "q": "What characterises an innocent midsystolic murmur?",
 "opts": [["No physiologic or structural abnormality",
   "Correct, usually from increased blood flow. It diminishes when the patient stands, sits up, or performs a Valsalva, and is common in infancy and childhood, disappearing by adulthood. It grades 1 to 3 out of 6."],
  ["A physiologic change in body metabolism",
   "That describes a PHYSIOLOGIC murmur, as in anaemia, pregnancy, fever or hyperthyroidism."],
  ["A structural abnormality of the heart or great vessels",
   "That describes a PATHOLOGIC murmur, such as aortic stenosis or hypertrophic cardiomyopathy."],
  ["Always grade 4 or above with a thrill",
   "An innocent murmur is grade 1 to 3; a thrill implies grade 4 or above and suggests pathology."]],
 "c": 0, "cite": c(66)},

{"topic": "Physiologic murmurs", "io": IO_MUR, "slot": "etiology",
 "q": "Which states produce a physiologic midsystolic murmur?",
 "opts": [["Anaemia, pregnancy, fever, thyrotoxicosis",
   "Correct — changes in body metabolism rather than a structural abnormality, which is what separates them from the pathologic group."],
  ["Aortic stenosis and pulmonic stenosis",
   "Aortic and pulmonic stenosis are pathologic, arising from structural abnormality of the valve."],
  ["Hypertrophic cardiomyopathy and atrial septal defect",
   "Both are pathologic structural causes of a midsystolic murmur."],
  ["Mitral and tricuspid regurgitation",
   "Those produce pansystolic murmurs rather than midsystolic ones."]],
 "c": 0, "cite": c(66)},

{"topic": "Aortic stenosis", "io": IO_MUR, "slot": "test finding",
 "q": "Describe the murmur of aortic stenosis.",
 "opts": [["Midsystolic, crescendo-decrescendo, harsh",
   "Correct, in the aortic area, radiating often to the carotids, down the left sternal border and even to the apex. A thrill implies grade 4 or above. The pitch is medium."],
  ["Pansystolic, plateau, medium and blowing",
   "That describes tricuspid regurgitation at the lower left sternal border."],
  ["Early diastolic, decrescendo, high frequency",
   "That describes aortic regurgitation, which may be mistaken for breath sounds."],
  ["Mid to late diastolic, low-pitched rumble",
   "That describes mitral stenosis, heard with the bell at the apex."]],
 "c": 0, "cite": c(67)},

{"topic": "Aortic stenosis", "io": IO_MAN, "slot": "test finding",
 "q": "Which manoeuvres affect the murmur of aortic stenosis?",
 "opts": [["Better sitting forward; louder on squatting",
   "Correct, because both squatting and leg raise increase venous return and preload, sending more blood past the narrowed valve. Leg raise does the same."],
  ["Louder with Valsalva and on standing",
   "Those manoeuvres reduce preload, which makes hypertrophic cardiomyopathy louder and aortic stenosis softer."],
  ["Unchanged by any manoeuvre",
   "Squatting and leg raise both increase it; Valsalva and standing soften it."],
  ["Louder with isometric handgrip only",
   "Handgrip increases mitral regurgitation, pulmonic stenosis, ventricular septal defect, aortic regurgitation and mitral stenosis."]],
 "c": 0, "cite": c(67)},

{"topic": "Pulmonic stenosis", "io": IO_MUR, "slot": "test finding",
 "q": "Where does the murmur of pulmonic stenosis radiate?",
 "opts": [["Toward the left shoulder and neck, if loud",
   "Correct, from the pulmonic area. It is midsystolic, crescendo-decrescendo, medium and harsh, and no manoeuvres are listed for it."],
  ["To the carotids and down the left sternal border",
   "That is the radiation of aortic stenosis."],
  ["To the left axilla",
   "That is the radiation of mitral regurgitation."],
  ["To the right sternum and xiphoid",
   "That is the radiation of tricuspid regurgitation, which notably does NOT go to the axilla."]],
 "c": 0, "cite": c(68)},

{"topic": "Hypertrophic cardiomyopathy", "io": IO_MUR, "slot": "test finding",
 "q": "Where is the murmur of hypertrophic cardiomyopathy heard, and where does it never radiate?",
 "opts": [["Erb's point and tricuspid area; never the neck",
   "Correct — it radiates down the left sternal border to the apex and possibly to the base, but never to the neck, which distinguishes it from aortic stenosis."],
  ["The aortic area; never to the apex",
   "Aortic stenosis is heard in the aortic area and may radiate even to the apex."],
  ["The apex; never to the axilla",
   "Mitral regurgitation is heard at the apex and radiates to the left axilla."],
  ["The pulmonic area; never to the shoulder",
   "Pulmonic stenosis is heard in the pulmonic area and may radiate to the left shoulder and neck."]],
 "c": 0, "cite": c(70)},

{"topic": "Hypertrophic cardiomyopathy", "io": IO_MAN, "slot": "test finding",
 "q": "How do manoeuvres affect the murmur of hypertrophic cardiomyopathy?",
 "opts": [["Decreases on squatting, increases on Valsalva",
   "Correct, and it is exactly the reverse of aortic stenosis — which is the point of doing the manoeuvres at all. Standing increases it too."],
  ["Increases with squatting; decreases with Valsalva",
   "That is the aortic stenosis pattern; hypertrophic cardiomyopathy behaves oppositely."],
  ["Unchanged by any manoeuvre",
   "It is the murmur that responds most clearly, which is why the manoeuvres distinguish it."],
  ["Increases only with isometric handgrip",
   "Handgrip increases mitral regurgitation, pulmonic stenosis and ventricular septal defect among others."]],
 "c": 0, "cite": c(70)},

{"topic": "Hypertrophic cardiomyopathy", "io": IO_MUR, "slot": "manifestation",
 "q": "Why is the murmur of hypertrophic cardiomyopathy singled out as important to learn?",
 "opts": [["So a sports physical is not signed off incorrectly",
   "Correct — it is high-pitched, crescendo-decrescendo and midsystolic at the left lower sternal border, and missing it in a young athlete has obvious consequences."],
  ["Because it is the commonest murmur in adults",
   "Aortic stenosis and mitral regurgitation are far more common in adults."],
  ["Because it always produces a thrill",
   "Its intensity is described as variable rather than always loud enough for a thrill."],
  ["Because it radiates to the carotids",
   "It never radiates to the neck, which is one of the features distinguishing it from aortic stenosis."]],
 "c": 0, "cite": c(60)},

{"topic": "Valsalva", "io": IO_MAN, "slot": "test finding",
 "q": "What does the Valsalva manoeuvre do haemodynamically?",
 "opts": [["Raises intrathoracic pressure, drops preload",
   "Correct — forceful expiration against a closed airway, decreasing left ventricular filling. The hypertrophic cardiomyopathy murmur increases; aortic stenosis softens or does not change."],
  ["Raises preload by returning blood from the legs",
   "That is squatting or leg raise, which increases venous return."],
  ["Increases afterload by sustained muscle contraction",
   "That is the isometric handgrip."],
  ["Has no effect on ventricular filling",
   "The Valsalva specifically decreases left ventricular filling by raising intrathoracic pressure."]],
 "c": 0, "cite": c(61)},

{"topic": "Valsalva", "io": IO_MAN, "slot": "education",
 "q": "How is a patient asked to perform a Valsalva?",
 "opts": [["Bear down as if straining",
   "Correct, with the patient supine and your hand on their mid-abdomen. The manoeuvre can also identify heart failure and pulmonary hypertension. Or push against your hand on their abdomen."],
  ["Squat quickly from standing",
   "Squatting increases venous return rather than raising intrathoracic pressure."],
  ["Grip both hands tightly for thirty seconds",
   "That is the isometric handgrip manoeuvre."],
  ["Lean forward and exhale completely",
   "That position is used to hear aortic regurgitation and the pericardial friction rub better."]],
 "c": 0, "cite": c(61)},

{"topic": "Standing from squatting", "io": IO_MAN, "slot": "test finding",
 "q": "What happens when a patient stands quickly from squatting?",
 "opts": [["Blood pools in the legs; preload falls",
   "Correct — less blood returns to the heart, so the hypertrophic cardiomyopathy murmur becomes louder and the aortic stenosis murmur softer."],
  ["Blood returns from the legs and preload rises",
   "That is what happens on squatting FROM standing, or on leg raise."],
  ["Intrathoracic pressure rises",
   "That is the Valsalva manoeuvre."],
  ["Afterload rises through muscular contraction",
   "That is the isometric handgrip."]],
 "c": 0, "cite": c(62)},

{"topic": "Squatting", "io": IO_MAN, "slot": "test finding",
 "q": "Why does squatting from standing make aortic stenosis louder?",
 "opts": [["More blood rushes past the narrowed valve",
   "Correct — squatting forces leg volume back to the heart, raising preload and left ventricular filling."],
  ["The outflow tract obstruction worsens",
   "Increased filling REDUCES the obstruction in hypertrophic cardiomyopathy, which is why that murmur softens."],
  ["Intrathoracic pressure rises",
   "That is the Valsalva mechanism."],
  ["The valve area decreases",
   "The valve is unchanged; what changes is the volume of blood crossing it."]],
 "c": 0, "cite": c(62)},

{"topic": "Squatting", "io": IO_MAN, "slot": "test finding",
 "q": "What happens to mitral valve prolapse on squatting or leg raise?",
 "opts": [["It is moved later in systole",
   "Correct, because the increased ventricular volume delays the point at which the redundant leaflet balloons into the atrium."],
  ["It becomes louder and earlier",
   "Increased filling moves it LATER in systole rather than earlier."],
  ["It disappears entirely",
   "The described effect is a shift in timing rather than abolition."],
  ["It becomes a diastolic murmur",
   "The click and following murmur remain systolic; only their timing within systole shifts."]],
 "c": 0, "cite": c(62)},

{"topic": "Handgrip", "io": IO_MAN, "slot": "test finding",
 "q": "Which murmurs does isometric handgrip increase?",
 "opts": [["Mitral regurgitation and pulmonic stenosis",
   "Correct, together with the diastolic murmurs of aortic regurgitation and mitral stenosis — a different set from the preload manoeuvres. Ventricular septal defect too."],
  ["Aortic stenosis and hypertrophic cardiomyopathy",
   "Those two are distinguished by the preload manoeuvres of Valsalva, standing and squatting."],
  ["Tricuspid regurgitation only",
   "Tricuspid regurgitation may increase slightly with inspiration rather than with handgrip."],
  ["The pericardial friction rub",
   "That may increase when the patient leans forward, exhales and holds their breath."]],
 "c": 0, "cite": c(63)},

{"topic": "Pansystolic murmurs", "io": IO_MUR, "slot": "manifestation",
 "q": "What defines a pansystolic murmur?",
 "opts": [["It begins with S1 and continues to S2",
   "Correct — something is open through all of systole, with blood flowing from a high pressure chamber to a lower one through a structure that should be closed. All are pathologic."],
  ["It occupies the middle of systole only",
   "That is a midsystolic murmur, which may be innocent, physiologic or pathologic."],
  ["It begins after a click in mid systole",
   "That is a late systolic murmur, following a mitral valve prolapse click."],
  ["It spans both systole and diastole",
   "A sound heard through both is a continuous murmur or a pericardial friction rub."]],
 "c": 0, "cite": c(72)},

{"topic": "Tricuspid regurgitation", "io": IO_MUR, "slot": "test finding",
 "q": "Where does the murmur of tricuspid regurgitation radiate, and where does it not?",
 "opts": [["To sternum, xiphoid and midclavicular line",
   "Correct, and that exclusion is the discriminator from mitral regurgitation, which does radiate to the axilla. NOT to the axilla."],
  ["To the left axilla",
   "That is mitral regurgitation; tricuspid regurgitation specifically does not radiate there."],
  ["To the carotids",
   "That is the radiation of aortic stenosis."],
  ["To the left shoulder and neck",
   "That is the radiation of a loud pulmonic stenosis murmur."]],
 "c": 0, "cite": c(73)},

{"topic": "Tricuspid regurgitation", "io": IO_MUR, "slot": "test finding",
 "q": "Describe the shape, pitch and location of tricuspid regurgitation.",
 "opts": [["Plateau, medium frequency, blowing",
   "Correct, and it may increase slightly with inspiration — the right-sided murmur behaving as right-sided sounds do. It sits at the lower left sternal border."],
  ["Crescendo-decrescendo, harsh, in the aortic area",
   "That describes aortic stenosis."],
  ["Decrescendo, high frequency, in the aortic area",
   "That describes aortic regurgitation."],
  ["Low-pitched rumble at the apex",
   "That describes mitral stenosis, heard with the bell."]],
 "c": 0, "cite": c(73)},

{"topic": "Mitral regurgitation", "io": IO_MUR, "slot": "test finding",
 "q": "Describe the murmur of mitral regurgitation.",
 "opts": [["Pansystolic at the apex, harsh",
   "Correct, radiating to the left axilla, with an apical thrill if loud. The harshness is attributed to the left ventricle being the powerful chamber. The frequency is medium to high."],
  ["Pansystolic at the lower left sternal border, blowing",
   "That describes tricuspid regurgitation, which does not radiate to the axilla."],
  ["Midsystolic in the aortic area, crescendo-decrescendo",
   "That describes aortic stenosis."],
  ["Early diastolic, decrescendo, high frequency",
   "That describes aortic regurgitation."]],
 "c": 0, "cite": c(74)},

{"topic": "Mitral regurgitation", "io": IO_MAN, "slot": "test finding",
 "q": "Which manoeuvres increase the murmur of mitral regurgitation?",
 "opts": [["Handgrip or squatting",
   "Correct, both of which increase the resistance the left ventricle works against or the volume it handles."],
  ["Valsalva or standing",
   "Those reduce preload and are used to bring out hypertrophic cardiomyopathy."],
  ["Inspiration",
   "Slight increase with inspiration is characteristic of tricuspid regurgitation, a right-sided murmur."],
  ["Leaning forward after full exhalation",
   "That position brings out aortic regurgitation and the pericardial friction rub."]],
 "c": 0, "cite": c(74)},

{"topic": "Diastolic murmurs", "io": IO_MUR, "slot": "differential",
 "q": "How do diastolic murmurs compare with systolic ones?",
 "opts": [["Less common and more difficult to hear",
   "Correct, which is why the positioning and the choice of chest piece matter more for them than for the systolic murmurs."],
  ["More common and easier to hear",
   "They are described as both less common and harder to hear."],
  ["Equally common but louder",
   "Diastolic murmurs are less common and more difficult to hear rather than louder than systolic ones."],
  ["Always pathologic and always loud",
   "They are harder to hear rather than louder, with aortic regurgitation typically grade 1 to 3."]],
 "c": 0, "cite": c(76)},

{"topic": "Aortic regurgitation", "io": IO_MUR, "slot": "test finding",
 "q": "What can the murmur of aortic regurgitation be mistaken for?",
 "opts": [["Breath sounds",
   "Correct, because it is high frequency and blowing. It is early diastolic, decrescendo, grade 1 to 3, from the aortic area down the left intercostal space."],
  ["A pericardial friction rub",
   "A rub is scratchy and scraping, heard intermittently through both systole and diastole."],
  ["An opening snap",
   "An opening snap is a discrete high-pitched sound rather than a sustained blowing murmur."],
  ["S3",
   "S3 is a low-pitched early diastolic sound best heard with the bell."]],
 "c": 0, "cite": c(77)},

{"topic": "Aortic regurgitation", "io": IO_MAN, "slot": "education",
 "q": "What position brings out aortic regurgitation?",
 "opts": [["Sitting forward, breath held after exhaling",
   "Correct, and the same position is used for the pericardial friction rub — both are brought closer to the chest wall by it."],
  ["Left lateral decubitus with the bell",
   "Left lateral decubitus with the bell is the position for mitral stenosis, S3 and S4."],
  ["Supine while bearing down",
   "That is the Valsalva manoeuvre, used to distinguish hypertrophic cardiomyopathy."],
  ["Standing quickly from a squat",
   "That reduces preload and is used to distinguish hypertrophic cardiomyopathy from aortic stenosis."]],
 "c": 0, "cite": c(77)},

{"topic": "Mitral stenosis", "io": IO_MUR, "slot": "test finding",
 "q": "How is the murmur of mitral stenosis best heard?",
 "opts": [["Bell at the apex, left lateral decubitus",
   "Correct — a low-pitched decrescendo rumble, mid to late diastolic, grade 1 to 4, with little or no radiation."],
  ["With the diaphragm at the base, sitting forward",
   "That approach suits aortic regurgitation and the pericardial friction rub."],
  ["With the diaphragm at the apex, supine",
   "The diaphragm at the apex is used for S1; a low-pitched rumble needs the bell."],
  ["With the bell in the aortic area",
   "The aortic area carries aortic stenosis and the aortic ejection sound."]],
 "c": 0, "cite": c(79)},

{"topic": "Tricuspid stenosis", "io": IO_MUR, "slot": "differential",
 "q": "What distinguishes tricuspid from mitral stenosis on auscultation?",
 "opts": [["Its location near the xiphoid",
   "Correct — both are mid to late diastolic low-pitched rumbles of grade 1 to 4 heard with the bell, so location is what separates them. Tricuspid stenosis follows an opening snap. That is the lower left sternal border."],
  ["Its high pitch",
   "Both tricuspid and mitral stenosis are low-pitched rumbles requiring the bell rather than the diaphragm."],
  ["Its timing in systole",
   "Both tricuspid and mitral stenosis are mid to late diastolic murmurs rather than systolic ones."],
  ["Its radiation to the axilla",
   "Both have little or no radiation; axillary radiation belongs to mitral regurgitation."]],
 "c": 0, "cite": c(80)},

{"topic": "Pericardial friction rub", "io": IO_MUR, "slot": "test finding",
 "q": "What does a pericardial friction rub sound like, and when is it heard?",
 "opts": [["Scratchy and scraping, through both phases",
   "Correct — high pitched, best with the diaphragm, plateau shape, most often at Erb's point, and it may increase when the patient leans forward, exhales and holds their breath."],
  ["A low-pitched rumble confined to diastole",
   "That describes mitral or tricuspid stenosis."],
  ["A blowing decrescendo in early diastole",
   "That describes aortic regurgitation."],
  ["A harsh crescendo-decrescendo in mid systole",
   "That describes aortic or pulmonic stenosis."]],
 "c": 0, "cite": c(81)},

{"topic": "Pericardial friction rub", "io": IO_MUR, "slot": "etiology",
 "q": "What causes a pericardial friction rub?",
 "opts": [["Inflammation of the pericardial sac",
   "Correct — pericarditis. It is the one auscultatory finding here that crosses both phases of the cycle."],
  ["Turbulent flow across a stenotic valve",
   "That produces a stenotic murmur such as aortic stenosis."],
  ["Regurgitant flow across an incompetent valve",
   "That produces a regurgitant murmur such as mitral regurgitation."],
  ["Reduced ventricular compliance",
   "That produces S4."]],
 "c": 0, "cite": c(81)},

{"topic": "Peripheral inspection", "io": IO_PV, "slot": "test finding",
 "q": "What is normal capillary refill time?",
 "opts": [["Two to three seconds",
   "Correct, tested by pressing on the fingernail and noting how long the nail bed takes to become pink again."],
  ["Under one second",
   "The normal window is two to three seconds, so under one second would be unusually brisk."],
  ["Five to six seconds",
   "That would be prolonged against the two to three second normal."],
  ["It varies too much to have a normal value",
   "A normal of two to three seconds is specified, so the measure is not too variable to use."]],
 "c": 0, "cite": c(85)},

{"topic": "Quincke sign", "io": IO_PV, "slot": "test finding",
 "q": "What is Quincke's pulse?",
 "opts": [["The capillary bed flashing red to pale with each heartbeat",
   "Correct, seen after releasing nail bed pressure — a visible pulsation in the capillary bed rather than a palpable one."],
  ["A delay between radial and femoral pulses",
   "That is pulse lag, which raises the possibility of coarctation of the aorta."],
  ["A bounding pulse graded 4 plus",
   "That is an amplitude grading rather than a capillary sign."],
  ["Pain behind the knee on forced dorsiflexion",
   "That is a positive Homan's sign, which checks for deep vein thrombosis."]],
 "c": 0, "cite": c(85)},

{"topic": "Pulse amplitude", "io": IO_PV, "slot": "test finding",
 "q": "What does an amplitude of 2 plus indicate?",
 "opts": [["Brisk and normal",
   "Correct, on a scale where 4 plus is bounding, 3 plus increased, 1 plus faint or diminished and 0 absent. The standing instruction is to always compare both sides."],
  ["Increased",
   "Increased amplitude is graded 3 plus, while 2 plus denotes a brisk and normal pulse."],
  ["Faint or diminished",
   "That is 1 plus."],
  ["Bounding",
   "That is 4 plus, the top of the scale."]],
 "c": 0, "cite": c(86)},

{"topic": "Peripheral inspection", "io": IO_ED, "slot": "test finding",
 "q": "What does oedema do to the surface anatomy of a limb?",
 "opts": [["It obscures veins, tendons and bones",
   "Correct, which is why inspection notes relative size, symmetry and the prominence of those structures — and why one limb is always compared with the other."],
  ["Makes veins and tendons more prominent",
   "Oedema obscures them rather than highlighting them."],
  ["Changes skin colour to brown",
   "Brown pigmentation is haemosiderin staining, a feature of chronic venous insufficiency."],
  ["Produces hair loss over the shins",
   "Loss of hair is a feature of chronic arterial insufficiency."]],
 "c": 0, "cite": c(87)},

{"topic": "Pitting oedema", "io": IO_ED, "slot": "test finding",
 "q": "How is pitting oedema tested for?",
 "opts": [["Press firmly with the thumb, two seconds",
   "Correct, over the dorsum of the foot, posterior to the medial malleolus, and over the shins. The pit is the depression the thumb leaves."],
  ["Press with the balls of the hand against the limb",
   "That technique is used to feel for a thrill on the chest wall."],
  ["Press on the nail bed and time the refill",
   "That is capillary refill, normally two to three seconds."],
  ["Dorsiflex the foot forcefully with the knee bent",
   "That is Homan's sign, testing for deep vein thrombosis."]],
 "c": 0, "cite": c(88)},

{"topic": "Arterial insufficiency", "io": IO_PV, "slot": "manifestation",
 "q": "What pain pattern characterises chronic arterial insufficiency?",
 "opts": [["Pain on walking, progressing to rest pain",
   "Correct — claudication. Chronic venous insufficiency by contrast produces no pain."],
  ["No pain at any stage",
   "That is chronic VENOUS insufficiency."],
  ["Pain only when the limb is elevated",
   "Elevation produces foot pallor in arterial insufficiency rather than pain specifically."],
  ["Pain behind the knee on dorsiflexion",
   "That is a positive Homan's sign for deep vein thrombosis."]],
 "c": 0, "cite": c(91)},

{"topic": "Arterial insufficiency", "io": IO_PV, "slot": "test finding",
 "q": "What are the skin findings of chronic arterial insufficiency?",
 "opts": [["Thin shiny skin, hair loss, cool to touch",
   "Correct, with no oedema, painful ulceration unless neuropathy is present, gangrene, decreased pulses, foot pallor on elevation and dusky rubor. The colour is pale or dusky red."],
  ["Thickened skin with brown pigmentation and pitting oedema",
   "Those are the findings of chronic VENOUS insufficiency."],
  ["Normal temperature with cyanosis when dependent",
   "Normal temperature and dependent cyanosis belong to venous insufficiency."],
  ["Warm erythematous skin with bounding pulses",
   "Arterial insufficiency gives cool skin with decreased pulses."]],
 "c": 0, "cite": c(91)},

{"topic": "Venous insufficiency", "io": IO_PV, "slot": "test finding",
 "q": "What are the findings of chronic venous insufficiency?",
 "opts": [["No pain, normal temperature, pitting oedema",
   "Correct — the haemosiderin staining, thickened skin, normal pulses, and gangrene rare or absent. With brown pigmentation."],
  ["Painful ulceration with thin shiny skin and hair loss",
   "Those are the findings of chronic ARTERIAL insufficiency."],
  ["Cool skin with decreased pulses and no oedema",
   "Those are arterial findings; venous insufficiency gives normal temperature and normal pulses."],
  ["Foot pallor on elevation with dusky rubor",
   "Foot pallor on elevation and dusky rubor are arterial findings rather than venous ones."]],
 "c": 0, "cite": c(93)},

{"topic": "Ulceration", "io": IO_PV, "slot": "differential",
 "q": "Where do venous ulcers typically occur?",
 "opts": [["Around the ankles, over both malleoli",
   "Correct — areas of venous congestion where compressed skin becomes ischaemic. The ulcers contain small painful granulation tissue and fibrin, with irregular borders."],
  ["Over the tips of the toes",
   "Distal painful ulceration is more characteristic of arterial insufficiency."],
  ["Over the shins only",
   "The shins are one of the sites tested for pitting, but venous ulcers occur around the ankles."],
  ["On the dorsum of the foot",
   "The dorsum of the foot is one of the sites for testing pitting oedema."]],
 "c": 0, "cite": c(93)},

{"topic": "Pulses", "io": IO_PV, "slot": "differential",
 "q": "What may absent peripheral pulses suggest?",
 "opts": [["Arterial disorder from atherosclerosis",
   "Correct, with small vessel disease such as diabetes mellitus also to consider. Pulses may also simply be difficult to palpate in obese or muscular patients. Or from systemic embolism."],
  ["Chronic venous insufficiency",
   "Pulses are described as NORMAL in chronic venous insufficiency."],
  ["Pitting oedema of any cause",
   "Oedema obscures landmarks but is not itself a cause of absent pulses."],
  ["Deep vein thrombosis",
   "Deep vein thrombosis is a venous problem; the arterial pulse is not the finding it produces."]],
 "c": 0, "cite": c(96)},

{"topic": "Carotid pulse", "io": IO_EX, "slot": "education",
 "q": "How is the carotid examined?",
 "opts": [["Auscultate first, then palpate one side at a time",
   "Correct, with the patient holding their breath, lateral to the trachea. Palpating both at once risks compromising cerebral flow."],
  ["Palpate both sides simultaneously to compare",
   "The carotids are palpated ONE AT A TIME, unlike the radial and femoral pulses compared for lag."],
  ["Palpate first, then auscultate",
   "Auscultation comes before palpation, so that the vessel is not disturbed before listening."],
  ["Auscultate while the patient breathes normally",
   "The patient is asked to hold their breath, so breath sounds do not obscure a bruit."]],
 "c": 0, "cite": c(97)},

{"topic": "Peripheral pulses", "io": IO_EX, "slot": "test finding",
 "q": "Where is the brachial pulse found?",
 "opts": [["Medial to the biceps tendon at the elbow",
   "Correct, and the radial pulse is found at the lateral portion of the wrist while the ulnar is medial."],
  ["Lateral to the biceps tendon at the elbow",
   "The brachial pulse lies MEDIAL to the biceps tendon at the antecubital fossa."],
  ["At the lateral portion of the wrist",
   "That is the radial pulse."],
  ["Behind the medial malleolus",
   "That is the posterior tibial pulse."]],
 "c": 0, "cite": c(98)},

{"topic": "Peripheral pulses", "io": IO_EX, "slot": "test finding",
 "q": "What is true of the ulnar pulse?",
 "opts": [["It may not be palpable even when normal",
   "Correct — palpate deeply on the medial flexor surface of the wrist, and partially flexing the wrist may help find it."],
  ["It is always easily palpable",
   "The normal ulnar pulse may not be palpable at all, so absence does not imply disease."],
  ["It is found at the lateral wrist",
   "The lateral portion of the wrist carries the radial pulse; the ulnar is medial."],
  ["It is assessed with the wrist fully extended",
   "Partially FLEXING the wrist may help find it, since it is palpated deeply on the flexor surface."]],
 "c": 0, "cite": c(100)},

{"topic": "Femoral pulse", "io": IO_EX, "slot": "test finding",
 "q": "Where is the femoral pulse palpated?",
 "opts": [["Below the inguinal ligament, midway along it",
   "Correct, and it must be palpated under clothing — except in lab and testing conditions, where you palpate over clothing but verbalise that to the facilitator. Between the iliac spine and pubic symphysis."],
  ["Directly over the inguinal ligament at its midpoint",
   "The femoral pulse is found BELOW the inguinal ligament rather than directly over it."],
  ["In the femoral triangle lateral to the sartorius",
   "The landmark given is midway between the anterior superior iliac spine and the pubic symphysis."],
  ["At the midpoint of the thigh",
   "The pulse is palpated high in the groin rather than mid-thigh."]],
 "c": 0, "cite": c(101)},

{"topic": "Pulse lag", "io": IO_EX, "slot": "differential",
 "q": "What should a radial to femoral pulse lag prompt you to consider?",
 "opts": [["Coarctation of the aorta",
   "Correct, found by palpating the radial and femoral pulses simultaneously and noting a delay between them."],
  ["Deep vein thrombosis",
   "That is tested for with Homan's sign, not with pulse timing."],
  ["Chronic venous insufficiency",
   "Pulses are normal in chronic venous insufficiency, which presents instead with pitting oedema."],
  ["Mitral valve prolapse",
   "That produces a mid to late systolic click on auscultation."]],
 "c": 0, "cite": c(102)},

{"topic": "Popliteal pulse", "io": IO_EX, "slot": "education",
 "q": "What is true about the popliteal pulse?",
 "opts": [["It is harder to feel, and sometimes absent",
   "Correct, and this may not matter if the more distal pulses are present. With the knee flexed, press fingertips deeply into the popliteal fossa."],
  ["It is the easiest lower limb pulse to find",
   "It is described as harder to feel than the others."],
  ["Its absence always indicates arterial disease",
   "Its absence may not be an issue if the more distal pulses are present."],
  ["It is palpated with the knee fully extended",
   "The knee is flexed and relaxed, or flexed to 90 degrees with the patient prone."]],
 "c": 0, "cite": c(103)},

{"topic": "Distal pulses", "io": IO_EX, "slot": "test finding",
 "q": "Where is the dorsalis pedis pulse found?",
 "opts": [["Dorsum of the foot, lateral to the toe tendon",
   "Correct, and the posterior tibial pulse is found behind the medial malleolus — the two distal pulses used for the ankle brachial index."],
  ["Behind the medial malleolus",
   "That is the posterior tibial pulse."],
  ["Behind the lateral malleolus",
   "The posterior tibial is behind the MEDIAL malleolus; nothing is described behind the lateral."],
  ["In the popliteal fossa",
   "That is the popliteal pulse."]],
 "c": 0, "cite": c(104)},

{"topic": "Bruits", "io": IO_EX, "slot": "test finding",
 "q": "What is a bruit?",
 "opts": [["A murmur-like sound of vascular origin",
   "Correct, auscultated over the aorta, renal, iliac and femoral arteries. Not of cardiac origin."],
  ["A palpable vibration from a loud murmur",
   "That is a thrill, felt with the balls of the hand."],
  ["A scratchy sound from pericardial inflammation",
   "That is a pericardial friction rub."],
  ["A high-pitched sound from a stenotic mitral valve opening",
   "That is an opening snap."]],
 "c": 0, "cite": c(106)},

{"topic": "Bruits", "io": IO_EX, "slot": "test finding",
 "q": "Where are the renal arteries auscultated for bruits?",
 "opts": [["Three to four centimetres lateral to it",
   "Correct, with the aorta itself in the midline halfway to the umbilicus, and the iliacs 3 to 4 cm lateral to the umbilicus and about 2 cm inferior."],
  ["Three to four centimetres lateral to the umbilicus",
   "That is where the iliac arteries are auscultated."],
  ["Directly over the femoral artery in the groin",
   "That is where the femoral arteries are auscultated."],
  ["In the midline of the abdomen",
   "The midline of the abdomen is where the aorta is auscultated rather than the renal arteries."]],
 "c": 0, "cite": c(106)},

{"topic": "Allen test", "io": IO_EX, "slot": "initial test",
 "q": "What does the Allen test evaluate?",
 "opts": [["Patency of the radial and ulnar arteries",
   "Correct — compress both, have the patient clench for thirty seconds, then open the fist and release one artery, watching the hand fill. They supply the hand."],
  ["Presence of deep vein thrombosis",
   "That is what Homan's sign checks for."],
  ["The ratio of ankle to brachial pressure",
   "That is the ankle brachial index."],
  ["The adequacy of capillary refill",
   "Capillary refill is tested by pressing the nail bed, with a normal of two to three seconds."]],
 "c": 0, "cite": c(108)},

{"topic": "Allen test", "io": IO_EX, "slot": "education",
 "q": "How long is the patient asked to clench the fist in the Allen test?",
 "opts": [["Thirty seconds",
   "Correct, with both arteries occluded. The fist is then opened and one artery released to watch the hand fill."],
  ["Two seconds",
   "Two seconds is the minimum thumb pressure for testing pitting oedema."],
  ["Ten minutes",
   "Ten minutes supine is the rest period before measuring brachial pressure for an ankle brachial index."],
  ["Until the patient reports pain",
   "The duration given is thirty seconds of clenching rather than being guided by symptoms."]],
 "c": 0, "cite": c(108)},

{"topic": "Ankle brachial index", "io": IO_EX, "slot": "initial test",
 "q": "How is the ankle brachial index calculated?",
 "opts": [["Higher ankle pressure over brachial systolic",
   "Correct, calculated for each leg and recorded to two decimal places. The normal range is 0.90 to 1.40."],
  ["Brachial systolic over the higher ankle pressure",
   "The ratio runs the other way, with the ankle pressure on top."],
  ["Lower of the two ankle pressures over the brachial systolic",
   "The HIGHER of the two ankle artery pressures is used as the numerator rather than the lower."],
  ["Average of both ankle pressures over the average brachial",
   "The higher single ankle pressure is used rather than an average."]],
 "c": 0, "cite": c(110)},

{"topic": "Ankle brachial index", "io": IO_EX, "slot": "education",
 "q": "How should the patient be prepared before brachial pressure is measured for an ankle brachial index?",
 "opts": [["Supine and resting for ten minutes",
   "Correct, and the cuff is inflated 20 mm Hg above the last audible pulse then deflated at about 1 mm Hg per second, with two measurements averaged in each arm."],
  ["Seated with feet flat for five minutes",
   "The patient is supine for ten minutes rather than seated, since posture alters the pressure."],
  ["Standing for two minutes",
   "Standing would alter the pressures; the patient is supine and resting."],
  ["Immediately on arrival, with no rest",
   "A ten minute supine rest is specified before the brachial pressure is taken."]],
 "c": 0, "cite": c(111)},

{"topic": "Ankle brachial index", "io": IO_EX, "slot": "test finding",
 "q": "What is the normal range for the ankle brachial index?",
 "opts": [["0.90 to 1.40",
   "Correct. Above 1.40 suggests a non-compressible calcified vessel, below 0.90 suggests peripheral arterial disease, and below 0.50 suggests severe disease."],
  ["0.50 to 0.90",
   "That range spans the values suggestive of peripheral arterial disease."],
  ["1.40 to 2.00",
   "Values above 1.40 suggest a non-compressible calcified vessel."],
  ["0.10 to 0.50",
   "Values below 0.50 suggest severe peripheral arterial disease."]],
 "c": 0, "cite": c(110)},

{"topic": "Ankle brachial index", "io": IO_EX, "slot": "test finding",
 "q": "What does an ankle brachial index above 1.40 suggest?",
 "opts": [["A non-compressible calcified vessel",
   "Correct, and it is the counter-intuitive one — a high value reflects a stiff artery rather than good perfusion."],
  ["Severe peripheral arterial disease",
   "That is suggested by a value below 0.50."],
  ["Mild peripheral arterial disease",
   "Values below 0.90 suggest peripheral arterial disease, at the opposite end of the scale."],
  ["A normal result",
   "Normal runs from 0.90 to 1.40; above that suggests calcification."]],
 "c": 0, "cite": c(113)},

{"topic": "Homan's sign", "io": IO_EX, "slot": "initial test",
 "q": "How is Homan's sign elicited, and what is a positive result?",
 "opts": [["Forceful dorsiflexion, knee bent; pain behind it",
   "Correct — a test that checks for deep vein thrombosis, performed quickly and forcefully at the ankle."],
  ["Compression of both wrist arteries; delayed hand filling",
   "That is the Allen test, assessing radial and ulnar patency."],
  ["Thumb pressure for two seconds; a persisting depression",
   "Thumb pressure held for two seconds leaving a depression tests for pitting oedema."],
  ["Simultaneous radial and femoral palpation; a delay",
   "That is pulse lag, raising the possibility of coarctation."]],
 "c": 0, "cite": c(114)},

{"topic": "Varicosities", "io": IO_PV, "slot": "manifestation",
 "q": "What are varicosities?",
 "opts": [["Mild to severe dilatation of veins",
   "Correct, and they are among the associated findings of chronic venous insufficiency along with oedema, purpura, stasis dermatitis and dependent cyanosis. Mainly in the lower extremities."],
  ["Thickened arterial walls with reduced elasticity",
   "That describes arterial disease rather than a venous dilatation."],
  ["Brown discolouration from haemosiderin",
   "That is a pigmentation change of chronic venous insufficiency rather than the dilatation itself."],
  ["Ulceration around the medial malleolus",
   "That is the typical site of venous ulceration."]],
 "c": 0, "cite": c(95)},
]
