# -*- coding: utf-8 -*-
# PDM I Lecture 3 -- pool D. Ear, nose and throat testing. Syllabus objective g.
#
# THE TYMPANOGRAM TYPES APPEAR TWICE IN THIS DECK AND THE TWO LISTS DIFFER.
# Slide 27 gives three types (A, B, C) with B split by canal volume. Slide 32
# gives five (A, B, C, AS, AD) with different wording, and its speaker notes add
# the -200 mm H2O treatment threshold and the causes of AS and AD. Neither
# contradicts the other; slide 32 is simply the fuller list. Questions here cite
# whichever slide states the fact being asked, and no question forces a choice
# between a three-type and a five-type answer.
SRC = "3. svDerm, ENT, Ophtho.pptx"
def c(n): return f"{SRC}, Slide {n}"
def cn(n): return f"{SRC}, Slide {n} (speaker notes)"

IOG = "Objective g — Discuss indications for rapid streptococcal testing, throat cultures, audiometry and tympanometry"

POOL_D = [
 dict(topic="Rapid strep testing", io=IOG, slot="initial test",
   q="What is the indication for a rapid streptococcal antigen test?",
   opts=[
     ["Suspected group A streptococcal pharyngitis in a patient with supportive clinical features",
      "Correct — the test follows a clinical suspicion rather than replacing the assessment."],
     ["Any sore throat, as a screening test before examination",
      "The deck requires supportive features on clinical presentation first."],
     ["Persistent or severe symptoms that have followed an initial negative throat culture",
      "That sequence is reversed; culture confirms a negative rapid test."],
     ["Suspected peritonsillar abscess before imaging",
      "Abscess is an imaging question, not a rapid antigen one."]],
   c=0, cite=c(25)),

 dict(topic="Rapid strep testing", io=IOG, slot="test finding",
   q="What is the sensitivity of the rapid streptococcal antigen test, and what does that produce?",
   opts=[
     ["About seventy to ninety per cent, which can lead to false negatives",
      "Correct — imperfect sensitivity is why a negative result may need confirming."],
     ["About seventy to ninety per cent, which can lead to false positives",
      "Limited sensitivity produces false negatives, not false positives."],
     ["About ninety-five to ninety-nine per cent, which makes confirmation unnecessary",
      "The deck gives a lower figure and does require confirmation in children."],
     ["About fifty per cent, which makes the test unhelpful in practice",
      "The figure given is higher, and the test is presented as useful."]],
   c=0, cite=c(25)),

 dict(topic="Rapid strep testing", io=IOG, slot="escalation",
   q="A rapid streptococcal test is negative in a child. What does the deck advise?",
   opts=[
     ["Confirm with a throat culture",
      "Correct — the clinical pearl for children specifically."],
     ["Treat empirically for group A streptococcus",
      "The deck does not advise empiric treatment on a negative test."],
     ["Repeat the rapid antigen test the following day",
      "Repeating the rapid test is not the advice given."],
     ["Send antistreptococcal antibody titres",
      "The deck says explicitly not to use these for acute pharyngitis."]],
   c=0, cite=c(25)),

 dict(topic="Rapid strep testing", io=IOG, slot="escalation",
   q="Is confirmatory culture after a negative rapid test routinely required in adults?",
   opts=[
     ["No, it is not routinely required for adult patients",
      "Correct — the pearl applies to children, not routinely to adults."],
     ["Yes, it is required for all adults just as it is for children",
      "The deck states the opposite for adults."],
     ["Yes, but only in adults over sixty-five",
      "No such age threshold is given."],
     ["Only if the adult has had rheumatic fever previously",
      "No such qualifier is given."]],
   c=0, cite=c(25)),

 dict(topic="Throat culture", io=IOG, slot="gold standard",
   q="What is the advantage of throat culture over rapid antigen testing?",
   opts=[
     ["It is the gold standard, with the highest sensitivity",
      "Correct — the deck names it gold standard for exactly this reason."],
     ["It is faster and can be done at the point of care",
      "Speed and point-of-care use are advantages of the rapid antigen test."],
     ["It distinguishes carriage from acute infection",
      "The deck does not make this claim for culture."],
     ["It gives antibiotic susceptibilities for group A streptococcus",
      "Susceptibilities are a wound-culture advantage on an earlier slide."]],
   c=0, cite=c(25)),

 dict(topic="Throat culture", io=IOG, slot="avoid",
   q="What is the limitation of throat culture?",
   opts=[
     ["Delayed results, taking twenty-four to forty-eight hours",
      "Correct — the trade-off against the rapid antigen test's speed."],
     ["Sensitivity of only seventy to ninety per cent",
      "That figure belongs to the rapid antigen test."],
     ["It cannot be performed in children",
      "It is specifically recommended in children after a negative rapid test."],
     ["It requires a specialised transport medium not stocked in most clinics",
      "The deck does not raise this."]],
   c=0, cite=c(25)),

 dict(topic="Throat culture", io=IOG, slot="avoid",
   q="Which test does the deck say not to use to diagnose acute pharyngitis?",
   opts=[
     ["Antistreptococcal antibody titres",
      "Correct — the antistreptolysin O titre is explicitly excluded for acute diagnosis."],
     ["Rapid streptococcal antigen testing",
      "That is the recommended first test when clinical features support it."],
     ["Throat culture",
      "That is the gold standard for this diagnosis."],
     ["Point-of-care ultrasound of the neck",
      "Ultrasound is discussed for neck masses, not excluded for pharyngitis."]],
   c=0, cite=c(25)),

 dict(topic="Throat culture", io=IOG, slot="initial test",
   q="Besides confirming a negative rapid test, what is the other listed indication for throat culture?",
   opts=[
     ["Persistent or severe symptoms",
      "Correct — the second indication given."],
     ["A history of rheumatic fever in the family",
      "Not one of the indications listed."],
     ["Any patient who has already taken antibiotics",
      "Prior antibiotics are not the stated indication."],
     ["Exposure to a household contact with pharyngitis",
      "Contact history is not listed here."]],
   c=0, cite=c(25)),

 dict(topic="Audiometry", io=IOG, slot="first-line",
   q="What does audiometry quantify, and when is it performed?",
   opts=[
     ["The degree and type of hearing loss, performed after abnormal physical examination findings",
      "Correct — it follows the examination rather than preceding it."],
     ["The mobility of the tympanic membrane, performed after abnormal examination findings",
      "Mobility is what tympanometry measures."],
     ["The degree and type of hearing loss, performed as a routine screen at every visit",
      "The deck places it after abnormal examination findings."],
     ["Middle-ear pressure, performed when effusion is suspected",
      "That is tympanometry's role."]],
   c=0, cite=c(27)),

 dict(topic="Audiometry", io=IOG, slot="differential",
   q="Which distinction does audiometry make?",
   opts=[
     ["Conductive from sensorineural hearing loss",
      "Correct — the type of loss, not merely its degree."],
     ["Effusion from perforation",
      "That distinction is made by tympanometry with canal volume."],
     ["Acute from chronic otitis media with effusion",
      "Audiometry does not date the disease."],
     ["Unilateral from bilateral loss",
      "Laterality is apparent clinically; the deck's stated distinction is the type of loss."]],
   c=0, cite=c(27)),

 dict(topic="Audiometry", io=IOG, slot="first-line",
   q="Which three indications for audiometry does the deck list?",
   opts=[
     ["Suspected or confirmed hearing loss, persistent otitis media with effusion, and asymmetric loss",
      "Correct — all three, with asymmetric loss serving to screen for retrocochlear pathology."],
     ["Suspected hearing loss, tinnitus, and vertigo",
      "Tinnitus and vertigo are not on this list."],
     ["Eustachian tube dysfunction, middle-ear effusion, and tympanic membrane perforation",
      "Those are the tympanometry indications."],
     ["Any ear pain, any ear discharge, and any foreign body",
      "None of these three is listed for audiometry."]],
   c=0, cite=c(27)),

 dict(topic="Audiometry", io=IOG, slot="referral",
   q="Why is asymmetric hearing loss an indication for audiometry?",
   opts=[
     ["To screen for retrocochlear pathology",
      "Correct — the reason the deck gives for testing asymmetry."],
     ["To confirm the presence of middle-ear fluid",
      "That is what the air-bone gap indicates."],
     ["To decide whether a hearing aid will help",
      "Not the reason given here."],
     ["To document a baseline before ototoxic treatment",
      "Not the reason given on this slide."]],
   c=0, cite=c(27)),

 dict(topic="Audiometry", io=IOG, slot="test finding",
   q="What does an air-bone gap of ten decibels or more correlate with?",
   opts=[
     ["Middle-ear fluid",
      "Correct — the deck ties this gap to fluid in the middle ear."],
     ["Sensorineural hearing loss",
      "A sensorineural loss does not produce an air-bone gap."],
     ["A perforated tympanic membrane",
      "Perforation is identified by a flat tympanogram with high canal volume."],
     ["Retrocochlear pathology",
      "That is suggested by asymmetry rather than by an air-bone gap."]],
   c=0, cite=c(27)),

 dict(topic="Audiometry", io=IOG, slot="test finding",
   q="What counts as a fail on primary-care conventional audiometry?",
   opts=[
     ["More than twenty decibels hearing level at one or more frequencies",
      "Correct — the threshold the deck sets for a fail."],
     ["More than ten decibels hearing level at one or more frequencies",
      "Ten decibels is the air-bone gap figure, not the fail threshold."],
     ["More than forty decibels hearing level at two or more frequencies",
      "Neither the level nor the number of frequencies matches."],
     ["Any threshold above zero decibels hearing level",
      "That is not the criterion given."]],
   c=0, cite=c(27)),

 dict(topic="Pure tone audiometry", io=IOG, slot="initial test",
   q="What does bone conduction audiometry use, and where is it applied?",
   opts=[
     ["A mechanical device transmitting sound by vibration through the forehead or mastoid bone",
      "Correct — device and both application sites."],
     ["A mechanical device transmitting sound by vibration through the tragus or ear canal",
      "The sites given are the forehead and the mastoid."],
     ["An insert earphone delivering tones directly to the tympanic membrane",
      "That is air conduction."],
     ["A tuning fork placed on the mastoid and then beside the ear",
      "That is the bedside Rinne test rather than bone conduction audiometry."]],
   c=0, cite=c(29)),

 dict(topic="Pure tone audiometry", io=IOG, slot="initial test",
   q="At what levels does screening pure tone audiometry present tones?",
   opts=[
     ["Twenty-five to thirty decibels for adults, and fifteen to twenty decibels for children",
      "Correct — the upper limits of normal hearing, set lower for children."],
     ["Fifteen to twenty decibels for adults, and twenty-five to thirty decibels for children",
      "The two are the wrong way round."],
     ["Zero to ten decibels for adults, and ten to fifteen decibels for children",
      "Neither figure matches the slide."],
     ["Forty to fifty decibels for adults, and thirty to forty decibels for children",
      "Both figures are well above the levels given."]],
   c=0, cite=c(29)),

 dict(topic="Pure tone audiometry", io=IOG, slot="test finding",
   q="What does a threshold search determine?",
   opts=[
     ["The softest sound heard at each frequency half of the time",
      "Correct — the fifty per cent criterion is what defines a threshold."],
     ["The softest sound heard at each frequency every time it is presented",
      "The criterion is fifty per cent, not every presentation."],
     ["The loudest sound tolerated at each frequency",
      "That is a discomfort level, not a threshold."],
     ["The frequency at which hearing first becomes abnormal",
      "The search is across frequencies for level, not for a frequency."]],
   c=0, cite=c(29)),

 dict(topic="Pure tone audiometry", io=IOG, slot="test finding",
   q="How are right and left ear thresholds recorded on an audiogram?",
   opts=[
     ["Right as a red circle, left as a blue cross",
      "Correct — red circle right, blue cross left."],
     ["Right as a blue cross, left as a red circle",
      "The two are swapped."],
     ["Right as a red cross, left as a blue circle",
      "The symbols are attached to the wrong sides."],
     ["Right as a black circle, left as a black triangle",
      "Neither colour nor symbol matches the convention given."]],
   c=0, cite=c(29)),

 dict(topic="Pure tone audiometry", io=IOG, slot="test finding",
   q="What is recorded on the vertical axis of an audiogram, and what does pure tone audiometry require of the room?",
   opts=[
     ["Sound intensity on the vertical axis, and a quiet environment",
      "Correct — both details from the same slide."],
     ["Frequency on the vertical axis, and a quiet environment",
      "Intensity goes on the vertical axis."],
     ["Sound intensity on the vertical axis, and a soundproof booth in every case",
      "The deck asks for a quiet environment rather than specifying a booth."],
     ["Compliance on the vertical axis, and a quiet environment",
      "Compliance is the tympanogram's vertical axis, not the audiogram's."]],
   c=0, cite=c(29)),

 dict(topic="Tympanometry", io=IOG, slot="first-line",
   q="What does tympanometry objectively measure?",
   opts=[
     ["Tympanic membrane mobility and middle-ear function",
      "Correct — mobility and function together."],
     ["The degree and type of hearing loss",
      "That is audiometry."],
     ["The presence of a middle-ear infection",
      "It measures mechanics, not infection directly."],
     ["Bone conduction thresholds across the speech spectrum",
      "That is bone conduction audiometry."]],
   c=0, cite=c(27)),

 dict(topic="Tympanometry", io=IOG, slot="first-line",
   q="Which three indications for tympanometry does the deck list?",
   opts=[
     ["Suspected effusion, otitis media with effusion, and eustachian tube dysfunction",
      "Correct — the three indications as given."],
     ["Suspected effusion, asymmetric hearing loss, and tinnitus",
      "Asymmetric loss and tinnitus are not tympanometry indications here."],
     ["Persistent otitis media with effusion, hearing loss, and retrocochlear pathology",
      "Those overlap with the audiometry list, not the tympanometry one."],
     ["Any ear pain, any ear discharge, and any hearing complaint",
      "The list is more specific than this."]],
   c=0, cite=c(27)),

 dict(topic="Tympanometry", io=IOG, slot="initial test",
   q="What is varied during tympanometry, and what is measured?",
   opts=[
     ["Air pressure in the external canal is varied while the reflected energy from a tone is measured",
      "Correct — pressure is the variable and reflected energy is the measurement."],
     ["The frequency of the tone is varied while the patient's threshold is measured",
      "That describes pure tone audiometry."],
     ["Air pressure in the middle ear is varied while canal volume is measured",
      "The pressure varied is in the external canal."],
     ["The intensity of the tone is varied while tympanic membrane movement is directly observed",
      "Intensity is not the variable in tympanometry."]],
   c=0, cite=c(31)),

 dict(topic="Tympanometry", io=IOG, slot="test finding",
   q="How does compliance relate to the intensity of the reflected tone?",
   opts=[
     ["The less compliant the system, the greater the intensity of the reflected tone",
      "Correct — a stiff system reflects more sound back."],
     ["The less compliant the system, the lower the intensity of the reflected tone",
      "The relationship is stated the other way round."],
     ["Compliance and reflected intensity are unrelated",
      "The whole test depends on the relationship between them."],
     ["Compliance determines the pressure peak but not the reflected intensity",
      "Reflected energy is what the test actually measures."]],
   c=0, cite=c(31)),

 dict(topic="Tympanometry", io=IOG, slot="test finding",
   q="What are the axes of a tympanogram, and where does a normal pressure peak sit?",
   opts=[
     ["Pressure along the horizontal axis and compliance along the vertical, with a normal peak at fifty millimetres of water",
      "Correct — both axes and the normal peak point."],
     ["Compliance along the horizontal axis and pressure along the vertical, with a normal peak at fifty millimetres of water",
      "The axes are the other way round."],
     ["Pressure along the horizontal axis and compliance along the vertical, with a normal peak at minus two hundred millimetres of water",
      "Minus two hundred is the threshold at which negative pressure becomes significant for treatment."],
     ["Frequency along the horizontal axis and intensity along the vertical, with a normal peak at fifty decibels",
      "Those are audiogram axes, not tympanogram ones."]],
   c=0, cite=c(31)),

 dict(topic="Tympanogram types", io=IOG, slot="test finding",
   q="What does a type A tympanogram indicate?",
   opts=[
     ["Normal middle ear function",
      "Correct — type A is the normal curve."],
     ["Restricted tympanic membrane mobility",
      "That is type B."],
     ["Significant negative pressure in the middle ear cavity",
      "That is type C."],
     ["Normal pressure with reduced mobility",
      "That is type AS."]],
   c=0, cite=c(32)),

 dict(topic="Tympanogram types", io=IOG, slot="test finding",
   q="What does a type B tympanogram indicate?",
   opts=[
     ["Restricted tympanic membrane mobility",
      "Correct — the flat curve of a stiff or fluid-filled middle ear."],
     ["Significant negative middle-ear pressure",
      "That is type C."],
     ["Normal middle ear function",
      "That is type A."],
     ["Hypermobility of the tympanic membrane",
      "That is type AD."]],
   c=0, cite=c(32)),

 dict(topic="Tympanogram types", io=IOG, slot="differential",
   q="A tympanogram is flat with a high canal volume. What does this suggest?",
   opts=[
     ["Perforation or a patent tube",
      "Correct — the extra volume is the middle-ear space now in continuity with the canal."],
     ["Middle-ear effusion",
      "Effusion gives a flat tympanogram with a NORMAL canal volume."],
     ["Eustachian tube dysfunction",
      "That gives a type C curve with negative pressure."],
     ["Ossicular chain fixation",
      "That gives a type AS curve, not a flat one with high volume."]],
   c=0, cite=c(27)),

 dict(topic="Tympanogram types", io=IOG, slot="differential",
   q="A tympanogram is flat with a normal canal volume. What does this suggest?",
   opts=[
     ["Middle-ear effusion",
      "Correct — flat with normal volume points to fluid rather than perforation."],
     ["Perforation or a patent tube",
      "That combination raises the canal volume."],
     ["Negative middle-ear pressure",
      "That is the type C pattern."],
     ["A hypermobile tympanic membrane",
      "That is type AD."]],
   c=0, cite=c(27)),

 dict(topic="Tympanogram types", io=IOG, slot="test finding",
   q="What does a type C tympanogram indicate?",
   opts=[
     ["Significant negative pressure in the middle ear cavity, from eustachian tube dysfunction",
      "Correct — negative pressure with normal mobility."],
     ["Restricted tympanic membrane mobility, from middle-ear fluid or otitis media",
      "That is type B."],
     ["Normal pressure with reduced mobility, from ossicular chain fixation",
      "That is type AS."],
     ["Normal pressure with hypermobility, from ossicular disarticulation",
      "That is type AD."]],
   c=0, cite=c(32)),

 dict(topic="Tympanogram types", io=IOG, slot="escalation",
   q="How negative must middle-ear pressure be before it is considered significant for treatment?",
   opts=[
     ["More negative than minus two hundred millimetres of water",
      "Correct — the threshold given in the speaker notes."],
     ["More negative than minus fifty millimetres of water",
      "Fifty is the normal peak pressure point, not the treatment threshold."],
     ["More negative than minus one hundred millimetres of water",
      "Not the figure given."],
     ["Any negative pressure at all",
      "The notes set a specific threshold rather than treating any negativity as significant."]],
   c=0, cite=cn(32)),

 dict(topic="Tympanogram types", io=IOG, slot="test finding",
   q="What does a type AS tympanogram show, and what causes it?",
   opts=[
     ["Normal pressure with reduced mobility, from ossicular chain fixation or tympanosclerosis",
      "Correct — the S stands for stiff or shallow."],
     ["Normal pressure with hypermobility, from ossicular disarticulation",
      "That is type AD."],
     ["Negative middle-ear pressure with normal mobility, from eustachian tube dysfunction",
      "That is type C."],
     ["Restricted mobility with a flat curve, from middle-ear effusion",
      "That is type B."]],
   c=0, cite=cn(32)),

 dict(topic="Tympanogram types", io=IOG, slot="test finding",
   q="What does a type AD tympanogram show, and what does it indicate?",
   opts=[
     ["Normal pressure with hypermobility, indicating a flaccid tympanic membrane",
      "Correct — the deck attributes it to disarticulation."],
     ["Normal pressure with reduced mobility, indicating tympanosclerosis",
      "That is type AS."],
     ["Negative pressure with normal mobility, indicating eustachian tube dysfunction",
      "That is type C."],
     ["A flat curve, indicating a perforated tympanic membrane",
      "That is a type B pattern with raised canal volume."]],
   c=0, cite=cn(32)),

 dict(topic="Tympanogram types", io=IOG, slot="test finding",
   q="Which tympanogram type is typical of sensorineural hearing loss with a normally functioning middle ear?",
   opts=[
     ["Type A",
      "Correct — the notes state type A curves typify both normal hearing and sensorineural loss."],
     ["Type B",
      "Type B indicates a stiff middle-ear system such as otitis media."],
     ["Type C",
      "Type C indicates negative middle-ear pressure."],
     ["Type AD",
      "Type AD indicates a flaccid tympanic membrane."]],
   c=0, cite=cn(32)),
]
