# -*- coding: utf-8 -*-
"""PDM I -- "Read the panel, name the diagnosis": complete blood count set.

Jaxon, 2026-09-10: "Create 2 quizzes with 30 questions for PDM that have like
lab results (with normal ranges) and then the answer choices be things like
'Iron deficiency anemia'."

WHY THE RANGES ARE PRINTED IN EVERY STEM, and not just as a convenience. It is
how this exam actually works -- Professor Shah teaches reference ranges as
approximate and lab-dependent on purpose ("it doesn't matter what the range is,
it just matters what the range is for where you're working"), and Professor
Reynolds says outright that ranges are always supplied. It also resolves the
problem that stopped pdm_l4_partition.py building number questions at all: the
deck gives lymphocytes, platelets and red cell distribution width two different
ways, so no question there could hinge on a disputed figure. Here nothing is
recalled -- the figure is on the page and the work is interpreting it.

STEMS ARE PLAIN TEXT. The engine assigns the stem with textContent, so a table
would not render and neither would an entity; panels are written inline with
literal middots and en-dashes.

The correct answer is authored FIRST in every item. pdm_lab_partition.py
rotates it, so no position can drift toward a favourite.
"""

def panel(intro, rows, lead):
    """intro sentence + inline lab panel + the question. rows: (name, value, ref)."""
    body = " · ".join("%s %s (%s)" % (n, v, r) for n, v, r in rows)
    return "%s %s. %s" % (intro, body, lead)


DX = "What is the most likely diagnosis?"
CAUSE = "What is the most likely cause?"

QUESTIONS = [

{"topic": "Microcytic anemia", "io": "g — Compare and contrast laboratory patterns associated with microcytic, normocytic and macrocytic anemia",
 "slot": "diagnosis",
 "q": panel("A 34-year-old woman has six months of fatigue and heavy periods. Her results are",
   [("hemoglobin", "9.1 g/dL", "12.0–15.5"), ("mean corpuscular volume", "72 fL", "80–100"),
    ("ferritin", "6 ng/mL", "15–200"), ("total iron-binding capacity", "465 µg/dL", "250–400")], DX),
 "opts": [
   ["Iron deficiency anemia",
    "Correct. Microcytic with a LOW ferritin and a HIGH iron-binding capacity — the marrow is short of iron and the body has increased its carrying capacity to hunt for more. In a menstruating woman this is the commonest anemia there is, and it still obliges you to think about occult blood loss."],
   ["Anemia of chronic disease",
    "This gives a low iron too, but ferritin is an acute phase reactant and rises; the binding capacity FALLS rather than rises. Both markers here point the other way."],
   ["Beta thalassemia trait",
    "Also microcytic, but iron studies are normal — ferritin would not be 6. The red cell count also tends to be preserved or high, which is what separates it."],
   ["Vitamin B12 deficiency",
    "That is macrocytic, with a volume above 100 rather than 72. Wrong side of the algorithm entirely."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, iron studies"},

{"topic": "Microcytic anemia", "io": "g — Compare and contrast laboratory patterns associated with microcytic, normocytic and macrocytic anemia",
 "slot": "diagnosis",
 "q": panel("A 68-year-old man with rheumatoid arthritis has mild fatigue. His results are",
   [("hemoglobin", "10.4 g/dL", "13.5–17.5"), ("mean corpuscular volume", "84 fL", "80–100"),
    ("ferritin", "410 ng/mL", "15–200"), ("total iron-binding capacity", "198 µg/dL", "250–400")], DX),
 "opts": [
   ["Anemia of chronic disease",
    "Correct. Ferritin HIGH and binding capacity LOW is the mirror image of iron deficiency: iron exists but inflammation sequesters it, and ferritin rises as an acute phase reactant. The volume sits normocytic or mildly microcytic."],
   ["Iron deficiency anemia",
    "Would show the opposite pair — ferritin low, binding capacity high. A ferritin of 410 effectively excludes it."],
   ["Sideroblastic anemia",
    "Iron is high here too, but this is far rarer and the smear shows ringed sideroblasts on iron staining rather than an inflammatory picture."],
   ["Folate deficiency",
    "Macrocytic, and it does not move ferritin or binding capacity in this pattern."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, iron studies"},

{"topic": "Microcytic anemia", "io": "g — Compare and contrast laboratory patterns associated with microcytic, normocytic and macrocytic anemia",
 "slot": "diagnosis",
 "q": panel("A 24-year-old man of Mediterranean descent is anemic on a routine panel and feels well. His results are",
   [("hemoglobin", "11.8 g/dL", "13.5–17.5"), ("mean corpuscular volume", "68 fL", "80–100"),
    ("red blood cell count", "6.1 million/µL", "4.5–5.9"), ("ferritin", "142 ng/mL", "15–200")], DX),
 "opts": [
   ["Beta thalassemia trait",
    "Correct. Markedly microcytic with NORMAL iron stores and a red cell count that is high rather than low — the marrow makes plenty of small cells. Iron deficiency cannot produce that combination."],
   ["Iron deficiency anemia",
    "Ferritin is normal at 142, and the red cell count would be low rather than 6.1 million. Both findings argue against it."],
   ["Anemia of chronic disease",
    "There is no inflammatory context, the anemia is mild, and the degree of microcytosis is far greater than this usually produces."],
   ["Lead poisoning",
    "Also microcytic with normal iron, but the smear shows basophilic stippling and there would be an exposure history."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, microcytic causes"},

{"topic": "Macrocytic anemia", "io": "g — Compare and contrast laboratory patterns associated with microcytic, normocytic and macrocytic anemia",
 "slot": "diagnosis",
 "q": panel("A 71-year-old man has fatigue and pins and needles in both feet. His results are",
   [("hemoglobin", "9.6 g/dL", "13.5–17.5"), ("mean corpuscular volume", "118 fL", "80–100"),
    ("vitamin B12", "94 pg/mL", "200–900"), ("smear", "macroovalocytes and hypersegmented neutrophils", "—")], DX),
 "opts": [
   ["Vitamin B12 deficiency",
    "Correct. Macrocytic with a low B12, and the smear gives the megaloblastic signature — macroovalocytes with hypersegmented neutrophils. The neuropathy is what distinguishes it from folate deficiency clinically."],
   ["Folate deficiency",
    "Produces an identical smear, but the B12 level here is the discriminator — and folate deficiency does not cause the neurological findings."],
   ["Alcoholic liver disease",
    "A common non-megaloblastic macrocytosis, but it does NOT produce macroovalocytes or hypersegmented neutrophils. Their presence points at impaired DNA synthesis."],
   ["Myelodysplastic syndrome",
    "Can be macrocytic, but usually with cytopenias in more than one line and dysplastic changes rather than a pure megaloblastic picture."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, macrocytic causes"},

{"topic": "Macrocytic anemia", "io": "g — Compare and contrast laboratory patterns associated with microcytic, normocytic and macrocytic anemia",
 "slot": "diagnosis",
 "q": panel("A 52-year-old man who drinks heavily is anemic. His results are",
   [("hemoglobin", "11.2 g/dL", "13.5–17.5"), ("mean corpuscular volume", "106 fL", "80–100"),
    ("vitamin B12 and folate", "both normal", "—"), ("smear", "round macrocytes, no hypersegmentation", "—")], DX),
 "opts": [
   ["Non-megaloblastic macrocytosis of liver disease and alcohol",
    "Correct. Macrocytic with normal B12 and folate and, decisively, NO macroovalocytes or hypersegmented neutrophils. Without those the problem is not DNA synthesis, and alcohol and liver disease are the usual explanation."],
   ["Vitamin B12 deficiency",
    "Excluded by a normal B12, and the smear lacks the megaloblastic changes it would produce."],
   ["Folate deficiency",
    "Folate is normal, and it would give the same hypersegmented picture that is absent here."],
   ["Hereditary spherocytosis",
    "That raises the mean corpuscular hemoglobin concentration and shows spherocytes; it does not produce macrocytosis."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, macrocytic causes"},

{"topic": "Normocytic anemia", "io": "g — Compare and contrast laboratory patterns associated with microcytic, normocytic and macrocytic anemia", "slot": "diagnosis",
 "q": panel("A 29-year-old woman is admitted after a road traffic collision with a pelvic fracture. Two days later her results are",
   [("hemoglobin", "8.4 g/dL", "12.0–15.5"), ("mean corpuscular volume", "89 fL", "80–100"),
    ("reticulocyte count", "6.8%", "0.5–2.5"), ("ferritin", "165 ng/mL", "15–200")], DX),
 "opts": [
   ["Acute blood loss anemia",
    "Correct. Normocytic with a HIGH reticulocyte count — the marrow is responding normally to a sudden loss, and the cells it makes are of normal size. Stores are still adequate, which is why ferritin is untouched this early."],
   ["Iron deficiency anemia",
    "Takes weeks to develop and would be microcytic with a low ferritin. Neither is present two days after the injury."],
   ["Aplastic anemia",
    "The marrow would be failing, so the reticulocyte count would be LOW rather than 6.8%, and other cell lines would fall too."],
   ["Anemia of chronic disease",
    "Develops over weeks of inflammation and is hypo-proliferative — the reticulocyte response would be blunted, not brisk."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, normocytic branch"},

{"topic": "Normocytic anemia", "io": "g — Compare and contrast laboratory patterns associated with microcytic, normocytic and macrocytic anemia", "slot": "diagnosis",
 "q": panel("A 26-year-old woman has jaundice and dark urine. Her results are",
   [("hemoglobin", "7.9 g/dL", "12.0–15.5"), ("reticulocyte count", "9.2%", "0.5–2.5"),
    ("unconjugated bilirubin", "4.1 mg/dL", "0.2–0.8"), ("haptoglobin", "undetectable", "30–200 mg/dL")], DX),
 "opts": [
   ["Hemolytic anemia",
    "Correct. A high reticulocyte count with a raised UNCONJUGATED bilirubin and an undetectable haptoglobin is the hemolysis triad — cells are being destroyed, free hemoglobin is mopping up the haptoglobin, and the marrow is compensating hard."],
   ["Acute blood loss anemia",
    "Also raises reticulocytes, but blood leaving the body does not release hemoglobin into plasma, so haptoglobin and bilirubin stay normal."],
   ["Gilbert syndrome",
    "Raises unconjugated bilirubin, but causes no anemia, no reticulocytosis and no haptoglobin consumption."],
   ["Aplastic anemia",
    "The reticulocyte count would be low and there would be no hyperbilirubinemia; the marrow is not producing."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, hemolysis"},

{"topic": "Pancytopenia", "io": "e — Discuss the clinical significance of abnormalities in red blood cells, white blood cells and platelets", "slot": "diagnosis",
 "q": panel("A 33-year-old man has fatigue, bruising and recurrent infections. His results are",
   [("hemoglobin", "7.2 g/dL", "13.5–17.5"), ("white blood cell count", "1,900/µL", "4,500–11,000"),
    ("platelets", "24,000/µL", "150,000–400,000"), ("reticulocyte count", "0.2%", "0.5–2.5")], DX),
 "opts": [
   ["Aplastic anemia",
    "Correct. All three lines are down and the reticulocyte count is LOW — the marrow is not producing anything. That combination of pancytopenia with an absent reticulocyte response is what defines marrow failure."],
   ["Immune thrombocytopenic purpura",
    "Drops platelets alone. Hemoglobin and white cells would be normal, and they are not."],
   ["Hemolytic anemia",
    "Would drive reticulocytes UP, and does not by itself cause leukopenia or thrombocytopenia."],
   ["Iron deficiency anemia",
    "Affects the red line only, is microcytic, and if anything raises the platelet count rather than lowering it."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, pancytopenia"},

{"topic": "Red cell morphology", "io": "g — Compare and contrast laboratory patterns associated with microcytic, normocytic and macrocytic anemia", "slot": "diagnosis",
 "q": panel("A 4-year-old living in old housing has irritability and abdominal pain. Her results are",
   [("hemoglobin", "9.8 g/dL", "11.5–15.5"), ("mean corpuscular volume", "70 fL", "80–100"),
    ("ferritin", "88 ng/mL", "15–200"), ("smear", "coarse basophilic stippling", "—")], DX),
 "opts": [
   ["Lead poisoning",
    "Correct. Microcytic with NORMAL iron stores, and the smear finding settles it — basophilic stippling is ribosomal RNA scattered evenly through the cytoplasm, and the classic association is lead."],
   ["Iron deficiency anemia",
    "The commonest microcytic anemia at this age, but ferritin is normal at 88 and it does not produce stippling."],
   ["Beta thalassemia trait",
    "Microcytic with normal iron as well, and it is the differential here — but stippling points to lead, and thalassemia usually preserves the red cell count."],
   ["Anemia of chronic disease",
    "There is no inflammatory illness, and it does not cause stippling."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, red cell inclusions"},

{"topic": "Red cell morphology", "io": "g — Compare and contrast laboratory patterns associated with microcytic, normocytic and macrocytic anemia", "slot": "diagnosis",
 "q": panel("A 22-year-old man has anemia and splenomegaly. His results are",
   [("hemoglobin", "10.1 g/dL", "13.5–17.5"), ("mean corpuscular volume", "82 fL", "80–100"),
    ("mean corpuscular hemoglobin concentration", "38 g/dL", "32–36"),
    ("smear", "round cells lacking central pallor", "—")], DX),
 "opts": [
   ["Hereditary spherocytosis",
    "Correct. A RAISED mean corpuscular hemoglobin concentration is the automated flag for it, and the smear matches — perfectly round cells that have lost their central pallor. Few things push that index above the range."],
   ["Iron deficiency anemia",
    "Moves the concentration DOWN, not up, and produces hypochromic cells with widened central pallor — the opposite appearance."],
   ["Sickle cell disease",
    "The smear would show thin crescents forming under low oxygen tension, not uniformly round cells."],
   ["Autoimmune hemolytic anemia",
    "Can also produce spherocytes, but they are acquired and the direct antiglobulin test is positive; the hereditary form runs in families."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, mean corpuscular hemoglobin concentration"},

{"topic": "Red cell morphology", "io": "g — Compare and contrast laboratory patterns associated with microcytic, normocytic and macrocytic anemia", "slot": "diagnosis",
 "q": panel("A 30-year-old man had a splenectomy after trauma five years ago. His routine smear shows",
   [("single dark purple nuclear fragments in red cells", "present", "absent"),
    ("target cells", "present", "absent"), ("hemoglobin", "14.1 g/dL", "13.5–17.5")], CAUSE),
 "opts": [
   ["He has no spleen to remove the inclusions",
    "Correct. Those fragments are Howell-Jolly bodies, and the spleen normally plucks them out — so finding them means absent or non-functioning splenic tissue. Target cells appear after splenectomy too, from redundant membrane."],
   ["Iron deficiency has produced the inclusions",
    "Iron deficiency gives hypochromic microcytic cells; it does not leave nuclear remnants behind, and the hemoglobin here is normal."],
   ["He has lead poisoning",
    "Lead gives basophilic stippling — fine blue dots spread evenly through the cytoplasm — not a single discrete nuclear fragment."],
   ["He has glucose-6-phosphate dehydrogenase deficiency",
    "That shows Heinz bodies, which are denatured hemoglobin at the cell periphery and need a supravital stain to see at all."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, Howell-Jolly bodies"},

{"topic": "Red cell morphology", "io": "g — Compare and contrast laboratory patterns associated with microcytic, normocytic and macrocytic anemia", "slot": "diagnosis",
 "q": panel("A 19-year-old man develops anemia days after starting an oxidant drug. His results are",
   [("hemoglobin", "8.8 g/dL", "13.5–17.5"), ("reticulocyte count", "7.1%", "0.5–2.5"),
    ("supravital stain", "inclusions at the cell periphery", "—"), ("smear", "bite cells", "—")], DX),
 "opts": [
   ["Glucose-6-phosphate dehydrogenase deficiency",
    "Correct. Heinz bodies are denatured hemoglobin sitting at the edge of the cell and are invisible without a supravital stain; the spleen bites them out, leaving bite cells. An oxidant trigger completes the picture."],
   ["Hereditary spherocytosis",
    "Gives round cells without central pallor and a raised hemoglobin concentration index, and it is not triggered by oxidant drugs."],
   ["Immune hemolytic anemia",
    "Would be confirmed by a positive direct antiglobulin test and does not need a supravital stain to show inclusions."],
   ["Lead poisoning",
    "Basophilic stippling is visible on the ordinary stain and is spread through the cytoplasm, not at the periphery."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, Heinz bodies"},

{"topic": "White cell lines", "io": "e — Discuss the clinical significance of abnormalities in red blood cells, white blood cells and platelets", "slot": "diagnosis",
 "q": panel("A 41-year-old woman has a fever and a productive cough. Her results are",
   [("white blood cell count", "19,400/µL", "4,500–11,000"), ("neutrophils", "84%", "54–62"),
    ("bands", "11%", "0–5"), ("lymphocytes", "9%", "24–44")], CAUSE),
 "opts": [
   ["A bacterial infection",
    "Correct. Neutrophils dominate and bands are raised — a left shift, meaning the marrow is releasing immature neutrophils faster than it can mature them. That pairing is the bacterial signature."],
   ["A viral infection",
    "Would raise LYMPHOCYTES rather than neutrophils, and lymphocytes here are suppressed at 9%."],
   ["A parasitic infestation",
    "Raises eosinophils, which are not elevated in this differential."],
   ["An allergic reaction",
    "Also an eosinophil response, and it would not produce a band count of 11%."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, neutrophils and left shift"},

{"topic": "White cell lines", "io": "e — Discuss the clinical significance of abnormalities in red blood cells, white blood cells and platelets", "slot": "diagnosis",
 "q": panel("A 9-year-old has a week of fever, sore throat and fatigue. His results are",
   [("white blood cell count", "14,800/µL", "4,500–11,000"), ("lymphocytes", "62%", "24–44"),
    ("neutrophils", "28%", "54–62"), ("smear", "atypical lymphocytes", "—")], CAUSE),
 "opts": [
   ["A viral infection",
    "Correct. A lymphocyte-predominant leukocytosis with atypical lymphocytes on the smear is the viral pattern, and in this age group with pharyngitis it points hard at infectious mononucleosis."],
   ["A bacterial infection",
    "Would push neutrophils up with a left shift; here neutrophils are the suppressed line."],
   ["An allergic reaction",
    "Drives eosinophils, and produces neither lymphocytosis nor atypical forms."],
   ["A bone marrow failure syndrome",
    "The total white count is raised rather than reduced, so production is not the problem."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, lymphocytes"},

{"topic": "White cell lines", "io": "e — Discuss the clinical significance of abnormalities in red blood cells, white blood cells and platelets", "slot": "diagnosis",
 "q": panel("A 27-year-old man recently back from travel has itching and a rash. His results are",
   [("white blood cell count", "12,100/µL", "4,500–11,000"), ("eosinophils", "18%", "1–3"),
    ("neutrophils", "48%", "54–62"), ("hemoglobin", "13.9 g/dL", "13.5–17.5")], CAUSE),
 "opts": [
   ["A parasitic infestation or an allergic process",
    "Correct. Eosinophils are the line raised by parasites, allergy and — less often — malignancy. At 18% against a range of 1 to 3, the eosinophil is the whole finding here."],
   ["A bacterial infection",
    "Neutrophils would lead and would be raised rather than mildly low."],
   ["A viral infection",
    "Lymphocytes carry the viral response; eosinophils are not the viral line."],
   ["Corticosteroid therapy",
    "Steroids raise neutrophils by demargination and actually SUPPRESS eosinophils."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, eosinophils"},

{"topic": "Absolute neutrophil count", "io": "d — Calculate absolute white blood cell counts", "slot": "interpretation",
 "q": panel("A patient on chemotherapy is reviewed before the next cycle. His results are",
   [("white blood cell count", "1,200/µL", "4,500–11,000"), ("neutrophils", "22%", "54–62"),
    ("bands", "6%", "0–5")], "Calculate the absolute neutrophil count and grade it."),
 "opts": [
   ["336 per microlitre — severe neutropenia",
    "Correct. Bands count WITH the neutrophils: 1,200 × (22 + 6) ÷ 100 = 336. Below 500 is severe, which is the threshold that changes precautions and antibiotic decisions."],
   ["264 per microlitre — severe neutropenia",
    "This leaves the bands out. They are immature neutrophils and belong in the numerator — that omission is the classic error."],
   ["336 per microlitre — moderate neutropenia",
    "The arithmetic is right but the grade is not: moderate is 500 to under 1,000, and 336 is below 500."],
   ["1,200 per microlitre — mild neutropenia",
    "That is the total white count, not the neutrophil count. A percentage means nothing until it is applied to the total."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, absolute neutrophil count"},

{"topic": "Platelets", "io": "e — Discuss the clinical significance of abnormalities in red blood cells, white blood cells and platelets", "slot": "diagnosis",
 "q": panel("A 28-year-old woman has petechiae and gum bleeding after a viral illness. She is otherwise well. Her results are",
   [("platelets", "18,000/µL", "150,000–400,000"), ("hemoglobin", "13.4 g/dL", "12.0–15.5"),
    ("white blood cell count", "7,100/µL", "4,500–11,000"), ("smear", "no schistocytes", "—")], DX),
 "opts": [
   ["Immune thrombocytopenic purpura",
    "Correct. An ISOLATED thrombocytopenia — red cells and white cells untouched — with a normal smear after a viral illness. The absence of schistocytes is what separates it from the microangiopathies."],
   ["Thrombotic thrombocytopenic purpura",
    "Also drops platelets, but consumes red cells too: you would expect anemia and schistocytes, and there are none."],
   ["Aplastic anemia",
    "Would take all three lines down, and here hemoglobin and white cells are normal."],
   ["Disseminated intravascular coagulation",
    "Consumes platelets alongside clotting factors, with schistocytes and deranged coagulation studies rather than an isolated fall."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, platelets"},

{"topic": "Platelets", "io": "e — Discuss the clinical significance of abnormalities in red blood cells, white blood cells and platelets", "slot": "diagnosis",
 "q": panel("A 44-year-old woman has confusion, fever and bruising. Her results are",
   [("platelets", "22,000/µL", "150,000–400,000"), ("hemoglobin", "8.1 g/dL", "12.0–15.5"),
    ("reticulocyte count", "6.4%", "0.5–2.5"), ("smear", "numerous schistocytes", "—")], DX),
 "opts": [
   ["A thrombotic microangiopathy",
    "Correct. Low platelets PLUS a hemolytic anemia with schistocytes is consumption inside small vessels — red cells are being sheared as they pass. The fever and confusion complete the classic pentad."],
   ["Immune thrombocytopenic purpura",
    "Drops platelets alone and leaves the smear normal; there would be no anemia and no fragmented cells."],
   ["Iron deficiency anemia",
    "Microcytic and hypo-proliferative, with a raised rather than reduced platelet count and no schistocytes."],
   ["Hereditary spherocytosis",
    "Produces round cells without central pallor, not fragments, and does not consume platelets."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, schistocytes"},

{"topic": "Erythrocytosis", "io": "a — Explain the components of a complete blood count", "slot": "diagnosis",
 "q": panel("A 58-year-old man has headaches, itching after hot showers and a ruddy face. He does not smoke. His results are",
   [("hemoglobin", "19.8 g/dL", "13.5–17.5"), ("hematocrit", "59%", "41–53"),
    ("white blood cell count", "14,200/µL", "4,500–11,000"), ("platelets", "612,000/µL", "150,000–400,000")], DX),
 "opts": [
   ["Polycythemia vera",
    "Correct. All THREE lines are raised, which points at a clonal marrow disorder rather than a response to anything. A secondary cause drives red cells alone; it has no reason to raise white cells and platelets too."],
   ["Chronic hypoxia from lung disease",
    "Raises red cells only, as an appropriate erythropoietin response. It leaves white cells and platelets alone."],
   ["Dehydration",
    "Concentrates everything proportionally and resolves with fluids; it does not produce a platelet count of 612,000."],
   ["Anemia of chronic disease",
    "The wrong direction entirely — that lowers hemoglobin rather than raising it."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, red cell count raised"},

{"topic": "Red cell morphology", "io": "g — Compare and contrast laboratory patterns associated with microcytic, normocytic and macrocytic anemia", "slot": "diagnosis",
 "q": panel("A 47-year-old man with cirrhosis has a routine panel. His results are",
   [("hemoglobin", "11.6 g/dL", "13.5–17.5"), ("mean corpuscular volume", "103 fL", "80–100"),
    ("smear", "cells with a dark centre inside the pale area", "—"),
    ("vitamin B12 and folate", "normal", "—")], CAUSE),
 "opts": [
   ["Liver disease has added redundant membrane to the red cells",
    "Correct. Those are target cells — a bullseye produced by too much membrane for the volume of hemoglobin. Liver disease and splenectomy are the two classic causes, and the macrocytosis here is non-megaloblastic."],
   ["Vitamin B12 deficiency has impaired DNA synthesis",
    "B12 is normal, and megaloblastic change gives macroovalocytes and hypersegmented neutrophils rather than targets."],
   ["Iron is being lost chronically from the gut",
    "Iron deficiency is microcytic; this volume is 103 fL, which is the wrong direction."],
   ["The spleen is sequestering red cells",
    "Hypersplenism lowers counts but does not create the target appearance; redundant membrane does."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, target cells"},

{"topic": "Red cell morphology", "io": "e — Discuss the clinical significance of abnormalities in red blood cells, white blood cells and platelets", "slot": "diagnosis",
 "q": panel("A 66-year-old man has anemia and a firm enlarged spleen. His results are",
   [("hemoglobin", "9.2 g/dL", "13.5–17.5"), ("smear", "teardrop-shaped red cells", "—"),
    ("platelets", "96,000/µL", "150,000–400,000"), ("white blood cell count", "3,800/µL", "4,500–11,000")], CAUSE),
 "opts": [
   ["The marrow is being infiltrated and replaced",
    "Correct. Teardrop cells are made when red cells squeeze out of a marrow packed with scar tissue or tumour. With cytopenias in all three lines and splenomegaly, infiltration is the mechanism."],
   ["The spleen has been removed",
    "The spleen is present and enlarged, and asplenia gives Howell-Jolly bodies and target cells rather than teardrops."],
   ["Oxidant stress is denaturing hemoglobin",
    "That gives Heinz bodies and bite cells, and needs a supravital stain to demonstrate."],
   ["Iron stores are exhausted",
    "Iron deficiency is microcytic and hypochromic and does not produce teardrop forms or pancytopenia."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, teardrop cells"},

{"topic": "Hemoglobin and hematocrit", "io": "b — Explain the difference between hemoglobin and hematocrit", "slot": "interpretation",
 "q": panel("A results screen shows a value that does not look right to the clinician. The results are",
   [("hemoglobin", "9.0 g/dL", "13.5–17.5"), ("hematocrit", "48%", "41–53")], "Why is this pair implausible?"),
 "opts": [
   ["The hematocrit should be roughly three times the hemoglobin",
    "Correct. Multiply the hemoglobin by three and the hematocrit should land nearby — 9 predicts about 27, not 48. A pair that far apart means a sampling or analyser problem worth repeating."],
   ["The hematocrit should equal the hemoglobin",
    "They measure different things — an amount in a volume against a percentage of packed cells — so they are never equal."],
   ["The hemoglobin should be roughly three times the hematocrit",
    "The multiplication runs the other way; this would predict a hematocrit of 3 from a hemoglobin of 9."],
   ["Both values are normal, so nothing is wrong",
    "The hemoglobin is well below its range, so the panel is not normal even before the mismatch is considered."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, hemoglobin against hematocrit"},

{"topic": "Red cell indices", "io": "c — Discuss red blood cell indices", "slot": "interpretation",
 "q": panel("A panel reports the indices below. The results are",
   [("mean corpuscular volume", "74 fL", "80–100"), ("mean corpuscular hemoglobin", "23 pg", "27–33"),
    ("mean corpuscular hemoglobin concentration", "29 g/dL", "32–36")], "How are these cells best described?"),
 "opts": [
   ["Microcytic and hypochromic",
    "Correct. Volume below range makes them small, and both hemoglobin indices below range make them pale — central pallor exceeding a third of the diameter. Iron deficiency and thalassemia sit here."],
   ["Macrocytic and normochromic",
    "Macrocytic would need a volume above 100; this is 74, at the other end."],
   ["Normocytic and hyperchromic",
    "The volume is not normal, and hyperchromic would need the concentration ABOVE 36 rather than below 32."],
   ["Microcytic and hyperchromic",
    "The size is right but the colour is not — a concentration of 29 is below the range, so the cells are pale, not dense."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, red cell indices"},

{"topic": "Anemia workup", "io": "h — Compare and contrast laboratory tests used in the evaluation of anemia", "slot": "next step",
 "q": panel("A 55-year-old woman has a microcytic anemia. Her results are",
   [("mean corpuscular volume", "76 fL", "80–100"), ("ferritin", "120 ng/mL", "15–200"),
    ("serum iron", "82 µg/dL", "60–170"), ("total iron-binding capacity", "310 µg/dL", "250–400"),
    ("smear", "no stippling", "—")], "What does this pattern point to?"),
 "opts": [
   ["Thalassemia trait",
    "Correct. Microcytic with all three iron studies normal and no stippling — the algorithm's endpoint. Iron is available, so the small cells are a production defect rather than a supply problem."],
   ["Iron deficiency anemia",
    "Every iron study is normal, which is precisely what iron deficiency cannot look like."],
   ["Lead poisoning",
    "The other cause of microcytosis with normal iron — but it is excluded here by the absence of basophilic stippling."],
   ["Anemia of chronic disease",
    "Ferritin would be raised and binding capacity reduced; both sit mid-range."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, microcytic algorithm"},

{"topic": "White cell lines", "io": "e — Discuss the clinical significance of abnormalities in red blood cells, white blood cells and platelets", "slot": "diagnosis",
 "q": panel("A 62-year-old woman on prednisone for polymyalgia has a raised white count and feels well, with no fever. Her results are",
   [("white blood cell count", "14,600/µL", "4,500–11,000"), ("neutrophils", "82%", "54–62"),
    ("bands", "2%", "0–5"), ("eosinophils", "0%", "1–3")], CAUSE),
 "opts": [
   ["Corticosteroids have demarginated neutrophils",
    "Correct. Steroids detach neutrophils from the vessel wall into the circulating pool, so the count rises without any new production — which is why bands stay normal. They also suppress eosinophils, and here eosinophils are zero."],
   ["An occult bacterial infection",
    "Would come with a left shift; bands are normal at 2% and the patient has no fever."],
   ["A myeloproliferative disorder",
    "Would usually disturb more than one line and persist; this is explained by an obvious drug."],
   ["An allergic reaction",
    "Raises eosinophils. They are absent here, which points the opposite way."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, demargination"},

{"topic": "Platelets", "io": "e — Discuss the clinical significance of abnormalities in red blood cells, white blood cells and platelets", "slot": "interpretation",
 "q": panel("A 39-year-old woman with heavy periods has these results",
   [("hemoglobin", "9.4 g/dL", "12.0–15.5"), ("mean corpuscular volume", "71 fL", "80–100"),
    ("platelets", "580,000/µL", "150,000–400,000"), ("ferritin", "7 ng/mL", "15–200")],
   "How should the platelet count be read?"),
 "opts": [
   ["A reactive rise that iron deficiency itself causes",
    "Correct. Iron deficiency is one of the listed causes of a raised platelet count, alongside trauma, acute hemorrhage and polycythemia vera. It needs no separate workup — treat the iron deficiency and it settles."],
   ["Evidence of a second, independent bone marrow disorder",
    "Unnecessary. The anemia already explains it, and invoking two diagnoses where one accounts for both findings is the error being tested."],
   ["A laboratory artefact requiring a repeat sample",
    "There is nothing inconsistent here — the value fits the clinical picture rather than contradicting it."],
   ["A sign of impending bleeding",
    "A high platelet count is not a bleeding risk in this setting; her bleeding is menstrual and is the cause, not the consequence."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, platelets raised"},

{"topic": "Red cell morphology", "io": "e — Discuss the clinical significance of abnormalities in red blood cells, white blood cells and platelets", "slot": "diagnosis",
 "q": panel("A 71-year-old man has back pain and anemia. His results are",
   [("hemoglobin", "9.7 g/dL", "13.5–17.5"), ("smear", "red cells stacked in chains like rows of coins", "—"),
    ("total protein", "10.8 g/dL", "6.0–8.3"), ("erythrocyte sedimentation rate", "112 mm/hr", "0–20")], CAUSE),
 "opts": [
   ["Raised serum proteins have neutralised the cells' surface charge",
    "Correct. That stacking is rouleaux: red cells normally repel each other with a negative surface charge, and excess protein cancels it so they clump in chains. The very high total protein and sedimentation rate fit a paraprotein."],
   ["Antibodies are agglutinating the red cells",
    "Agglutination clumps cells irregularly rather than stacking them in neat chains, and it is temperature-dependent."],
   ["The marrow is infiltrated by fibrous tissue",
    "That gives teardrop cells, not rouleaux, and would not raise the total protein."],
   ["The cells have lost membrane and become spherical",
    "Spherocytes are round and individual; they do not stack, and the hemoglobin concentration index would rise."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, rouleaux"},

{"topic": "Components of the panel", "io": "a — Explain the components of a complete blood count", "slot": "interpretation",
 "q": panel("A well 30-year-old man has a pre-employment panel. His results are",
   [("hemoglobin", "15.1 g/dL", "13.5–17.5"), ("mean corpuscular volume", "91 fL", "80–100"),
    ("white blood cell count", "7,600/µL", "4,500–11,000"), ("platelets", "268,000/µL", "150,000–400,000")],
   "How should this panel be reported?"),
 "opts": [
   ["Normal, with no further testing indicated",
    "Correct. Every value sits inside its range. Recognising a normal panel is a real skill — a reference range is the mean plus or minus two standard deviations, so chasing values that are merely near an edge generates work rather than answers."],
   ["Early iron deficiency, because the volume is below the midpoint",
    "Being below the middle of a range is not being outside it. 91 fL is unambiguously normal."],
   ["Mild anemia, because the hemoglobin is not at the top of the range",
    "Anemia means falling below the lower limit, not below the maximum. 15.1 is comfortably inside."],
   ["Thrombocytopenia, because the platelet count is under 300,000",
    "The lower limit is 150,000, so 268,000 sits comfortably inside the range. Thrombocytopenia means falling below the floor, not below the midpoint."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, reference ranges"},

{"topic": "Anemia workup", "io": "h — Compare and contrast laboratory tests used in the evaluation of anemia", "slot": "next step",
 "q": panel("A 63-year-old man is found to have iron deficiency anemia on a routine panel. He reports no bleeding. His results are",
   [("hemoglobin", "10.2 g/dL", "13.5–17.5"), ("mean corpuscular volume", "70 fL", "80–100"),
    ("ferritin", "5 ng/mL", "15–200")], "What must accompany treatment?"),
 "opts": [
   ["Evaluation for occult blood loss",
    "Correct. In a man of this age iron deficiency is a bleeding diagnosis until proven otherwise, and it is often the first sign of gastrointestinal bleeding. Replacing the iron without finding the leak treats the number, not the patient."],
   ["Nothing beyond oral iron and a repeat panel",
    "This is the trap. The anemia will correct and the cause will be missed, which is the outcome the teaching exists to prevent."],
   ["Bone marrow biopsy",
    "Not indicated for straightforward iron deficiency, where the mechanism is loss rather than a production failure."],
   ["Hemoglobin electrophoresis",
    "That investigates thalassemia, and thalassemia does not lower ferritin to 5."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, iron deficiency"},

{"topic": "White cell lines", "io": "e — Discuss the clinical significance of abnormalities in red blood cells, white blood cells and platelets", "slot": "diagnosis",
 "q": panel("A 60-year-old man has fatigue and early satiety with a very large spleen. His results are",
   [("white blood cell count", "96,000/µL", "4,500–11,000"),
    ("differential", "the full range of maturing granulocytes", "—"),
    ("platelets", "540,000/µL", "150,000–400,000"), ("hemoglobin", "10.8 g/dL", "13.5–17.5")], DX),
 "opts": [
   ["A myeloproliferative disorder",
    "Correct. A white count near 100,000 with granulocytes at every stage of maturation and a massive spleen is clonal overproduction, not a response to infection. The raised platelets and mild anemia fit the same process."],
   ["A bacterial infection",
    "Even severe sepsis rarely reaches 96,000, and it produces mature neutrophils with bands rather than the entire maturation series."],
   ["A viral infection",
    "Raises lymphocytes and does not produce granulocytes at every stage or splenomegaly of this degree."],
   ["Corticosteroid therapy",
    "Demargination can raise the count, but only modestly, and it does not enlarge the spleen or raise platelets."]],
 "c": 0, "cite": "Complete Blood Count and Hematology Diagnostics - Shahsv.pptx, white cell count raised"},

]
