# Principles of Diagnostic Medicine I, Lecture 2 (Principles of Medical Imaging) — pool C.
# Patient positioning, the imaging planes, contrast media and the relationship
# with the radiology team. Syllabus objectives c, e, g, h, i.
#
# Same two Reynolds rules as pools A and B, asserted in the partition script.
#
# CONTRAST DOSES. The deck gives exactly one volume, the litre of normal saline
# used for renal protection before iodinated contrast, and it is asked WITH its
# indication so the number is readable. Nothing else here carries a number.
#
# Every question carries slot="..." per the fact-slot standard.
# Correct answer is ALWAYS written first (c=0); the partition script rotates.
SRC = "2. svPrinciples of Medical Imaging.pptx"
def c(n): return f"{SRC}, Slide {n}"

IOC = "Objective c — Discuss anatomical structures best visualized by each imaging modality"
IOE = "Objective e — Discuss the importance of patient positioning in medical imaging"
IOG = "Objective g — Compare and contrast the risks and benefits associated with contrast administration"
IOH = "Objective h — Discuss contraindications and safety considerations of commonly used imaging modalities"
IOI = "Objective i — Discuss the importance of communication between the physician assistant and radiology team"

POOL_C = [
 dict(topic="Positioning", io=IOE, slot="manifestation",
   q="How are radiographic projections named?",
   opts=[
     ["In the direction the beam travels, from what it strikes first to the most distal portion",
      "Correct — so posterior-anterior means the beam enters the back and exits the front."],
     ["In the direction the patient faces, from the side nearest the film to the side furthest away",
      "The naming follows the beam rather than which way the patient is turned."],
     ["In the order the structures appear, from the most superficial down to the deepest tissue",
      "Projections are not named for the order in which structures are encountered on the image."],
     ["In the position of the detector, from the cassette's near edge to its furthest corner",
      "The detector's own geometry does not supply the name of the projection."]],
   c=0, cite=c(35)),

 dict(topic="Positioning", io=IOE, slot="first-line",
   q="Why is the posterior-anterior chest view preferred over the anterior-posterior view?",
   opts=[
     ["It reduces magnification of the heart, so cardiomegaly is not misread, and it lowers dose to radiation-sensitive organs",
      "Correct — the heart sits anteriorly, so it is closer to the detector on this view."],
     ["It reduces magnification of the lungs, so effusion is not missed, and it raises dose to less sensitive posterior tissue",
      "Magnification affects the heart, and no view is preferred for raising dose anywhere."],
     ["It shortens the exposure time needed, so motion blur is reduced, and it removes the need for a lateral view",
      "The deck notes these views are typically still combined with a lateral."],
     ["It removes overlap of the ribs entirely, so fractures are easier to see, and it avoids the need for oblique views",
      "Posterior ribs are better visualised, but overlap is not removed entirely."]],
   c=0, cite=c(40)),

 dict(topic="Positioning", io=IOE, slot="first-line",
   q="Beyond the heart, what else is better seen on the posterior-anterior chest view?",
   opts=[
     ["Maximum visualisation of the lung, better visualisation of the apices, and well visualised posterior ribs",
      "Correct — all three are listed alongside the cardiac and dose advantages."],
     ["Maximum visualisation of the mediastinum, better visualisation of the hila, and well visualised anterior ribs",
      "The deck names the lung fields, apices and posterior ribs rather than these."],
     ["Maximum visualisation of the diaphragm, better visualisation of free air, and well visualised gastric bubble",
      "Free air beneath the diaphragm is what an upright abdominal series is for."],
     ["Maximum visualisation of the pleura, better visualisation of layering fluid, and well visualised costophrenic angles",
      "Layering fluid with gravity is the decubitus view's stated purpose."]],
   c=0, cite=c(40)),

 dict(topic="Positioning", io=IOC, slot="initial test",
   q="What is the decubitus position used to evaluate?",
   opts=[
     ["Pleural effusion, because gravity lets the fluid around the lung level out and be seen",
      "Correct — fluid in the pleural space moves when the patient is laid on their side."],
     ["Free air under the diaphragm, because gravity lets the air rise to the highest point",
      "Free intraperitoneal air is sought on an upright abdominal series."],
     ["Bowel obstruction, because gravity separates the air from the fluid within the loops",
      "Air-fluid levels within bowel are assessed on the abdominal series."],
     ["Aortic calcification, because gravity displaces the overlying bowel gas out of the field",
      "The decubitus view is not described for vascular calcification here."]],
   c=0, cite=c(41)),

 dict(topic="Positioning", io=IOC, slot="initial test",
   q="What does a kidney-ureter-bladder film evaluate, and how is the patient positioned?",
   opts=[
     ["The genitourinary tract, with the patient supine and the film shot anterior-posterior",
      "Correct — supine and anterior-posterior distinguishes it from the abdominal series."],
     ["The gastrointestinal tract, with the patient standing and the film shot anterior-posterior",
      "Standing and anterior-posterior describes the abdominal series, which assesses bowel."],
     ["The genitourinary tract, with the patient standing and the film shot posterior-anterior",
      "The kidney-ureter-bladder film is taken supine, not upright."],
     ["The gastrointestinal tract, with the patient supine and the film shot posterior-anterior",
      "Both halves are wrong: it is a urinary study and it is an anterior-posterior film."]],
   c=0, cite=c(42)),

 dict(topic="Positioning", io=IOC, slot="initial test",
   q="What does an abdominal series evaluate, and how is the patient positioned?",
   opts=[
     ["The gastrointestinal tract, with the patient standing, to assess air-fluid levels or free air",
      "Correct — upright is what makes free air and air-fluid levels visible."],
     ["The genitourinary tract, with the patient supine, to assess stones within the collecting system",
      "Supine and urinary describes the kidney-ureter-bladder film instead."],
     ["The gastrointestinal tract, with the patient supine, to assess bowel wall thickness and oedema",
      "The series is shot standing, and wall thickness is not what it is described as assessing."],
     ["The retroperitoneum, with the patient in decubitus, to assess the psoas shadows and the flanks",
      "Decubitus positioning is described for pleural effusion, not for this study."]],
   c=0, cite=c(43)),

 dict(topic="Positioning", io=IOC, slot="differential",
   q="Which enteric pathologies is the abdominal series named as evaluating?",
   opts=[
     ["Small bowel obstruction, perforation and volvulus",
      "Correct — the three named examples of enteric pathology."],
     ["Appendicitis, diverticulitis and inflammatory bowel disease",
      "These are not the examples the deck gives for the plain abdominal series."],
     ["Cholelithiasis, pancreatitis and hepatic abscess",
      "These hepatobiliary conditions are not named for this study."],
     ["Peptic ulceration, gastritis and oesophageal stricture",
      "Luminal mucosal disease is assessed with oral contrast rather than a plain series."]],
   c=0, cite=c(43)),

 dict(topic="Imaging planes", io=IOE, slot="manifestation",
   q="Which three standard planes are used in cross-sectional imaging, and how does each divide the body?",
   opts=[
     ["Axial into upper and lower, coronal into anterior and posterior, sagittal into right and left",
      "Correct — axial is also called transverse and is the commonest of the three."],
     ["Axial into anterior and posterior, coronal into right and left, sagittal into upper and lower",
      "Each plane here is matched to the wrong division of the body."],
     ["Axial into right and left, coronal into upper and lower, sagittal into anterior and posterior",
      "This rotates all three assignments and is wrong on each one."],
     ["Axial into upper and lower, coronal into right and left, sagittal into anterior and posterior",
      "Coronal and sagittal are swapped; coronal separates front from back."]],
   c=0, cite=c(45)),

 dict(topic="Imaging planes", io=IOE, slot="manifestation",
   q="What are the midsagittal and parasagittal planes?",
   opts=[
     ["Midsagittal runs in the body's midline; parasagittal sections lie to either side of it",
      "Correct — the midsagittal plane is also called the median plane."],
     ["Midsagittal runs through the umbilicus; parasagittal sections lie above and below it",
      "Both sagittal planes are vertical and separate right from left, not upper from lower."],
     ["Midsagittal runs across the shoulders; parasagittal sections lie anterior and posterior",
      "That division is coronal rather than sagittal."],
     ["Midsagittal runs at the level of the heart; parasagittal sections are angled off the axis",
      "The distinction is position relative to the midline, not level or angle."]],
   c=0, cite=c(45)),

 dict(topic="Positioning", io=IOE, slot="manifestation",
   q="On a traditional transverse computed tomography or magnetic resonance image, where is the patient's left side?",
   opts=[
     ["On the reader's right, because the convention is as if you are looking at the patient's feet",
      "Correct — the patient is supine and you view from below."],
     ["On the reader's left, because the convention is as if you are standing behind the patient",
      "The convention places the patient's left on the reader's right, not the left."],
     ["On the reader's right, because the convention is as if you are looking down from the head",
      "The orientation given is from the feet upward, which is why left and right swap."],
     ["On the reader's left, because the convention is as if the image were a photograph",
      "Cross-sectional images are not read as photographs of the front of the patient."]],
   c=0, cite=c(46)),

 dict(topic="Positioning", io=IOE, slot="manifestation",
   q="How are patients usually positioned for computed tomography, nuclear medicine and magnetic resonance studies?",
   opts=[
     ["Supine, and the images are traditionally acquired in transverse sections",
      "Correct — supine is the standard across all three of these."],
     ["Standing, and the images are traditionally acquired in coronal sections",
      "Upright positioning belongs to the abdominal series and the chest radiograph."],
     ["Decubitus, and the images are traditionally acquired in sagittal sections",
      "Decubitus is a plain-film position used to look for layering pleural fluid."],
     ["Prone, and the images are traditionally acquired in oblique sections",
      "Prone is not the standard position described for these scanners."]],
   c=0, cite=c(46)),

 dict(topic="Positioning", io=IOE, slot="education",
   q="What does the deck call the most important thing to remember about ultrasound orientation?",
   opts=[
     ["Where the indicator is: on the right of the screen in cardiac imaging, on the left for everything else",
      "Correct — it is called crucial, because the whole image flips with it."],
     ["Where the indicator is: on the left of the screen in cardiac imaging, on the right for everything else",
      "This reverses the convention the deck gives for the heart."],
     ["How deep the focus is set: shallow for superficial structures, deep for abdominal structures",
      "Focal depth matters for image quality but is not the orientation rule stated."],
     ["Which frequency is selected: high for superficial structures, low for deeper structures",
      "Transducer frequency is a resolution and penetration trade-off, not orientation."]],
   c=0, cite=c(48)),

 dict(topic="Positioning", io=IOE, slot="manifestation",
   q="How are patients positioned for ultrasound examinations?",
   opts=[
     ["Dozens of positions depending on the structure and the complaint, most often some form of supine",
      "Correct — head position varies, and the position follows what is being examined."],
     ["A single standardised position for every study, with the transducer angle changed instead",
      "The deck describes dozens of potential positions rather than one standard."],
     ["Standing for all abdominal work and seated for all cardiac work, without exception",
      "No such rigid division is described, and most patients are some form of supine."],
     ["Prone for all studies, so that the transducer can be applied along the posterior surface",
      "Prone is not the usual ultrasound position described here."]],
   c=0, cite=c(47)),

 dict(topic="Contrast media", io=IOG, slot="first-line",
   q="What is contrast material most commonly used for?",
   opts=[
     ["Imaging arteries or veins, and delineating and characterising masses",
      "Correct — neoplastic versus benign, and abscess versus cyst, are the examples given."],
     ["Imaging bone detail, and delineating and characterising fracture lines",
      "Bone is well seen without contrast, which is not what the deck describes."],
     ["Imaging lung parenchyma, and delineating and characterising interstitial change",
      "Interstitial lung disease is not a stated indication for contrast administration."],
     ["Imaging joint cartilage, and delineating and characterising degenerative change",
      "Contrast can be injected into joints, but this is not its commonest use."]],
   c=0, cite=c(50)),

 dict(topic="Contrast media", io=IOG, slot="complication",
   q="Why does the deck name cancer as a risk factor for all contrast material?",
   opts=[
     ["Because the dyes are technically radioactive, as are the imaging techniques themselves",
      "Correct — the deck states the risk in exactly those terms."],
     ["Because the dyes are nephrotoxic, and chronic renal injury raises malignancy risk over time",
      "Nephrotoxicity is a real risk of iodinated contrast, but it is not the reason given."],
     ["Because the dyes are retained in tissue indefinitely, and retained foreign material transforms",
      "Indefinite tissue retention is not the mechanism the deck describes."],
     ["Because the dyes provoke chronic inflammation, and chronic inflammation is carcinogenic",
      "Inflammation is not the pathway named here for contrast-associated risk."]],
   c=0, cite=c(50)),

 dict(topic="Contrast media", io=IOG, slot="agent/regimen",
   q="Into which spaces can contrast be injected, and what is each study called?",
   opts=[
     ["Joints for an arthrogram, the central nervous system intrathecally, and the bladder for a retrograde pyelogram",
      "Correct — three routes named besides the intravascular and enteral ones."],
     ["Joints for a venogram, the central nervous system intravenously, and the bladder for a cystogram",
      "A venogram images veins, and intrathecal is the route named for the nervous system."],
     ["Muscle for a myogram, the pleural space directly, and the ureter for an antegrade pyelogram",
      "None of these three routes is described in the deck."],
     ["Bowel for an arthrogram, the epidural space, and the renal pelvis for a cystogram",
      "The names are attached to the wrong spaces throughout."]],
   c=0, cite=c(50)),

 dict(topic="Contrast media", io=IOG, slot="agent/regimen",
   q="Which agent is named for intravenous contrast in computed tomography, and what is it?",
   opts=[
     ["Omnipaque (iohexol), a radioactive form of iodine given into the vein",
      "Correct — the same agent is used, at higher concentration, for angiography."],
     ["Visipaque (iodixanol), a barium salt suspension given into the vein",
      "Iodixanol is iodinated and iso-osmolal; barium is enteral and never intravenous."],
     ["Gadolinium, a paramagnetic metal chelate given into the vein",
      "Gadolinium is the magnetic resonance agent, not the computed tomography one."],
     ["Gastrografin, a water-soluble iodinated agent given into the vein",
      "Gastrografin is an oral agent used when perforation is suspected."]],
   c=0, cite=c(52)),

 dict(topic="Contrast media", io=IOH, slot="initial test",
   q="What must be checked before giving intravenous iodinated contrast, and why?",
   opts=[
     ["Blood urea nitrogen and creatinine, because the agent is nephrotoxic",
      "Correct — and a litre of normal saline is given to protect the kidneys."],
     ["Liver function tests and bilirubin, because the agent is cleared hepatically",
      "The concern named is renal rather than hepatic."],
     ["Thyroid function tests, because the iodine load can precipitate thyrotoxicosis",
      "Thyroid effects are real clinically but are not what this deck requires checking."],
     ["Complete blood count and platelets, because the agent affects coagulation",
      "Coagulation is not the risk the deck attaches to iodinated contrast."]],
   c=0, cite=c(52)),

 dict(topic="Contrast media", io=IOH, slot="first-line",
   q="What is given alongside intravenous iodinated contrast to protect the kidneys?",
   opts=[
     ["One litre of normal saline",
      "Correct — the only volume the deck specifies, and it is renal protection."],
     ["One litre of lactated Ringer's",
      "The deck names normal saline specifically rather than a balanced solution."],
     ["One gram of acetylcysteine",
      "Acetylcysteine is not mentioned in this lecture."],
     ["One dose of intravenous furosemide",
      "Forcing diuresis is not what the deck describes for renal protection here."]],
   c=0, cite=c(52)),

 dict(topic="Contrast media", io=IOH, slot="avoid",
   q="Which oral contrast agent is contraindicated when perforation is suspected, and what is used instead?",
   opts=[
     ["Barium is contraindicated because it is toxic to extra-intestinal tissue; use gastrografin",
      "Correct — barium outside the bowel causes alkaline burns."],
     ["Gastrografin is contraindicated because it is toxic to extra-intestinal tissue; use barium",
      "This reverses them; gastrografin is the agent chosen when perforation is possible."],
     ["Iohexol is contraindicated because it is toxic to extra-intestinal tissue; use barium",
      "Iohexol is the intravascular agent and is not the oral contrast in question."],
     ["Both are contraindicated because either is toxic to extra-intestinal tissue; use none",
      "Gastrografin exists precisely so that a study can still be done."]],
   c=0, cite=c(52)),

 dict(topic="Contrast media", io=IOG, slot="first-line",
   q="What is oral contrast indicated for?",
   opts=[
     ["Structure or disease of the intraluminal space, anywhere from the upper oesophagus to the rectum",
      "Correct — it outlines the lumen of the gastrointestinal tract."],
     ["Structure or disease of the vascular space, anywhere from the aortic root to the digital arteries",
      "Vascular imaging requires an intravascular injection, not an oral agent."],
     ["Structure or disease of the pleural space, anywhere from the apex to the costophrenic angle",
      "Oral contrast does not reach the pleural space."],
     ["Structure or disease of the urinary space, anywhere from the renal pelvis to the urethra",
      "The urinary tract is imaged with an injected or retrograde agent instead."]],
   c=0, cite=c(52)),

 dict(topic="Contrast media", io=IOG, slot="agent/regimen",
   q="What are the named indications for intravenous contrast in computed tomography?",
   opts=[
     ["Inflammation, cancer staging, tumour delineation, vasculopathy, emboli, thrombi, stenosis and aneurysms",
      "Correct — the vascular indications and the oncological ones are listed together."],
     ["Fracture, dislocation, foreign body, joint effusion, bone tumour, osteomyelitis and arthritis",
      "Musculoskeletal indications of this kind are not what contrast is listed for."],
     ["Stroke, demyelination, cord compression, disc herniation, meningitis and hydrocephalus",
      "Central nervous system tumour characterisation is listed under magnetic resonance."],
     ["Pneumonia, effusion, pneumothorax, atelectasis, emphysema and interstitial lung disease",
      "These parenchymal lung findings are not the contrast indications named."]],
   c=0, cite=c(52)),

 dict(topic="Contrast media", io=IOG, slot="agent/regimen",
   q="Which agent is used for fluoroscopic swallow studies, and how is the study performed?",
   opts=[
     ["Oral barium, with sequential x-rays taken as the patient swallows it",
      "Correct — real-time imaging is what makes fluoroscopy suit a swallow study."],
     ["Oral gadolinium, with sequential magnetic resonance images taken as the patient swallows",
      "Gadolinium is intravenous and belongs to magnetic resonance, not fluoroscopy."],
     ["Intravenous iohexol, with sequential computed tomography images taken during swallowing",
      "An intravascular agent does not opacify the swallowed bolus."],
     ["Oral technetium, with sequential gamma camera images taken as the patient swallows",
      "Technetium is a nuclear medicine tracer rather than a swallow-study agent."]],
   c=0, cite=c(51)),

 dict(topic="Contrast media", io=IOH, slot="education",
   q="What does the deck say about shellfish allergy and iodinated contrast?",
   opts=[
     ["There should be no cross-reactivity between shellfish and iodinated radiocontrast",
      "Correct — the cross-reactivity idea is explicitly rejected."],
     ["There is well-established cross-reactivity, so the two allergies must be treated as one",
      "This is the belief the deck corrects rather than the position it takes."],
     ["There is partial cross-reactivity, so contrast may be given at a reduced concentration",
      "No such graded approach is described; the cross-reactivity itself is denied."],
     ["There is cross-reactivity only with the iso-osmolal agents such as iodixanol",
      "The deck draws no agent-specific exception of this kind."]],
   c=0, cite=c(53)),

 dict(topic="Contrast media", io=IOH, slot="risk factors",
   q="Which patients are described as high risk before contrast administration?",
   opts=[
     ["Patients with a documented anaphylactic reaction to any medication",
      "Correct — the history that matters is anaphylaxis to anything, not to iodine alone."],
     ["Patients with a documented allergy to shellfish or to dietary iodine",
      "The deck states there should be no cross-reactivity from shellfish."],
     ["Patients with a documented reaction to any topical antiseptic containing iodine",
      "Topical iodine reactions are not the risk marker named."],
     ["Patients with a documented history of asthma or of seasonal allergic rhinitis",
      "Atopy generally is not the specific high-risk marker the deck gives."]],
   c=0, cite=c(53)),

 dict(topic="Contrast media", io=IOH, slot="education",
   q="What does the deck give as the key takeaway on contrast safety?",
   opts=[
     ["Always ask about allergies and assess kidney function",
      "Correct — and pre-treatment exists when contrast is absolutely necessary."],
     ["Always withhold contrast when any drug allergy is documented",
      "Pre-treatment is available, so a documented allergy is not an absolute bar."],
     ["Always use the iso-osmolal agent regardless of the indication or the patient",
      "Iodixanol is believed safer but is not mandated for every study."],
     ["Always obtain written consent and give a prophylactic antihistamine",
      "Neither of these is stated as the takeaway for contrast administration."]],
   c=0, cite=c(53)),

 dict(topic="Contrast media", io=IOG, slot="agent/regimen",
   q="Which agent is used for magnetic resonance contrast, and what are its indications?",
   opts=[
     ["Gadolinium, for central nervous system tumours, metastases, soft tissue masses and arthrograms",
      "Correct — and central nervous system tumours are typically characterised without biopsy."],
     ["Iohexol, for central nervous system tumours, metastases, soft tissue masses and arthrograms",
      "Iohexol is the iodinated agent used in computed tomography and angiography."],
     ["Technetium-99, for bone scans, myocardial perfusion and functional brain imaging",
      "Those are the single photon emission tomography indications, not magnetic resonance."],
     ["Barium, for luminal structures anywhere from the upper oesophagus down to the rectum",
      "Barium is an enteral agent and has no role in magnetic resonance imaging."]],
   c=0, cite=c(54)),

 dict(topic="Contrast media", io=IOH, slot="initial test",
   q="What must be assessed before a magnetic resonance study with contrast, and why?",
   opts=[
     ["Blood urea nitrogen and creatinine, because renal function matters primarily for clearance",
      "Correct — gadolinium can damage kidneys, though less than iodinated contrast."],
     ["Blood urea nitrogen and creatinine, because gadolinium is more nephrotoxic than iodine",
      "The deck says the opposite: it is not as harmful as computed tomography contrast."],
     ["Thyroid function, because gadolinium chelates iodine and can precipitate a thyroid storm",
      "Gadolinium contains no iodine and this mechanism does not apply."],
     ["Nothing beforehand, because gadolinium is inert and is excreted unchanged in the bile",
      "The deck requires assessing renal function regardless."]],
   c=0, cite=c(54)),

 dict(topic="Contrast media", io=IOG, slot="differential",
   q="Which vascular magnetic resonance studies are performed without contrast?",
   opts=[
     ["Magnetic resonance angiography and magnetic resonance venography",
      "Correct — both are done without a contrast agent."],
     ["Computed tomography angiography and computed tomography venography",
      "The computed tomography vascular studies do require an iodinated injection."],
     ["Coronary angiography and retrograde pyelography",
      "Both of these are performed with injected contrast material."],
     ["Arthrography and intrathecal myelography",
      "Both are defined by contrast being injected into a space."]],
   c=0, cite=c(54)),

 dict(topic="Contrast media", io=IOH, slot="complication",
   q="What are the stated risks of fluorodeoxyglucose-18?",
   opts=[
     ["No contraindications and no known nephrotoxicity, though it may cause hyperglycaemia",
      "Correct — it is renally cleared, so the urinary tract is always contrast positive."],
     ["No contraindications and no known nephrotoxicity, though it may cause hypoglycaemia",
      "The agent is a glucose analogue; the effect named is a rise, not a fall."],
     ["Significant nephrotoxicity requiring pre-hydration, and it may cause hyperglycaemia",
      "Pre-hydration and nephrotoxicity belong to iodinated contrast instead."],
     ["Frequent anaphylaxis requiring pre-treatment, and it may cause hyperglycaemia",
      "Allergic reactions to the nuclear medicine agents are described as rare."]],
   c=0, cite=c(55)),

 dict(topic="Contrast media", io=IOG, slot="agent/regimen",
   q="What are technetium-99's stated indications, and how does it distribute?",
   opts=[
     ["Bone scans, myocardial perfusion, functional brain imaging, immunoscintigraphy and sentinel node identification; it travels to areas of higher blood flow and cellular activity",
      "Correct — a white blood cell uptake scan is also named."],
     ["Cancer staging, brain disorders and cardiac blood flow, with tumour delineation; it concentrates wherever glucose consumption is highest",
      "Glucose consumption describes fluorodeoxyglucose in positron emission tomography."],
     ["Vasculopathy, emboli, thrombi, stenosis and aneurysm assessment; it fills the vascular lumen and is imaged during the first pass",
      "Luminal filling on a first pass describes iodinated angiographic contrast."],
     ["Central nervous system tumours, metastases and soft tissue masses; it shortens relaxation times in the tissue it reaches",
      "Altering relaxation times is how gadolinium works in magnetic resonance."]],
   c=0, cite=c(56)),

 dict(topic="Contrast media", io=IOH, slot="prognosis",
   q="What is the stated safety record of technetium-99?",
   opts=[
     ["Allergic reactions are rare, and no organ damage has previously been documented",
      "Correct — neither nephrotoxicity nor hepatotoxicity is documented."],
     ["Allergic reactions are common, though no organ damage has previously been documented",
      "The deck describes allergic reactions as rare rather than common."],
     ["Allergic reactions are rare, though documented nephrotoxicity requires pre-hydration",
      "No nephrotoxicity has been documented for this agent."],
     ["Allergic reactions are rare, though documented hepatotoxicity requires liver monitoring",
      "Hepatotoxicity is specifically listed as not documented."]],
   c=0, cite=c(56)),

 dict(topic="Radiology team", io=IOI, slot="referral",
   q="Why does the deck stress giving the radiologist relevant clinical information?",
   opts=[
     ["The radiologist has not seen the patient, so the history is what guides their read",
      "Correct — the report is only as good as the question it is answering."],
     ["The radiologist bills separately, so the indication must be documented for the claim",
      "Billing is not the reason the deck gives for communicating."],
     ["The radiologist selects the modality, so the history determines which scanner is booked",
      "They can guide the choice, but the reason stated here is the quality of the read."],
     ["The radiologist repeats the study otherwise, so the history prevents duplicate imaging",
      "Avoiding repeat imaging is described as a benefit of post-processing instead."]],
   c=0, cite=c(58)),

 dict(topic="Radiology team", io=IOI, slot="referral",
   q="What does the deck advise when a radiology report comes back vague?",
   opts=[
     ["Contact the radiologist to discuss the patient",
      "Correct — the relationship is described as interprofessional and team-based."],
     ["Repeat the study using a different modality",
      "Repeating the study is not the first response the deck advises."],
     ["Order the next test in the diagnostic sequence",
      "Moving on without clarifying the report is not what is advised."],
     ["Refer the patient to the relevant specialist",
      "Onward referral is not the response the deck names to a vague report."]],
   c=0, cite=c(58)),

 dict(topic="Radiology team", io=IOI, slot="referral",
   q="What should you do if you are unsure which modality to order?",
   opts=[
     ["Tell the radiologist what you are looking for, and they can guide the choice",
      "Correct — the question you are asking is the useful thing to communicate."],
     ["Order the study with the widest range of densities, and narrow down afterwards",
      "Defaulting to the broadest study is not the advice the deck gives."],
     ["Order the study with the lowest radiation dose, and escalate only if it is negative",
      "Dose matters in the diagnostic approach, but this is not the stated advice."],
     ["Order both the plain film and the cross-sectional study at the same visit",
      "Ordering in parallel is not what the deck recommends for uncertainty."]],
   c=0, cite=c(58)),

 dict(topic="Radiology team", io=IOI, slot="education",
   q="What practical ordering point does the deck make about imaging several body regions?",
   opts=[
     ["Multiple body parts or sections may mean multiple orders, giving brain, cervical, thoracic and lumbar spine as the example",
      "Correct — one clinical question can require four separate requests."],
     ["Multiple body parts should be combined into a single order so the patient is scanned once",
      "The deck makes the opposite point about how these studies are requested."],
     ["Multiple body parts require the radiologist to countersign the request before booking",
      "No countersignature requirement is described."],
     ["Multiple body parts must be imaged on separate days to limit cumulative radiation dose",
      "Magnetic resonance emits no ionizing radiation, and no such rule is stated."]],
   c=0, cite=c(58)),
]
