# -*- coding: utf-8 -*-
# PDM I Lecture 8 (Cardiac Imaging and Vascular Studies, Ayelet Elwaya) -- pool B.
# Stress testing, cardiac computed tomography, nuclear cardiology, cardiovascular
# magnetic resonance, and the invasive studies. Pool A carries chest radiography,
# vascular ultrasound and echocardiography.
#
# Numbers handled as in pool A: the 85 per cent of predicted maximum heart rate
# is SUPPLIED in the stem and the question asks what follows from it, rather
# than asking the student to recall or compute it.
SRC = "Cardiac Imaging and Vascular Studies - Elwaya.pptx"
def c(n):  return f"{SRC}, Slide {n}"

IOC = "Compare and contrast cardiovascular imaging modalities"
IOE = "Discuss indications, advantages, and limitations of stress testing"
IOF = "Discuss indications, advantages, and limitations of nuclear cardiology studies"
IOG = "Discuss indications, advantages, and limitations of cardiac CT"
IOH = "Discuss indications, advantages, and limitations of cardiac MRI"
IOI = "Discuss indications, advantages, and limitations of coronary angiography"

POOL_B = [

{"topic": "Stress testing", "io": IOE, "slot": "modality choice",
 "q": "Which types of stress test are described?",
 "opts": [
  ["Exercise, echocardiographic, nuclear, pharmacological",
   "Correct. Two axes run through the list: how the heart is stressed, and how it is then imaged, and the four names are combinations of those two. Echocardiographic, nuclear and pharmacological."],
  ["Exercise, pharmacological, treadmill and bicycle",
   "Echocardiographic and nuclear stress testing are described as separate types alongside these two."],
  ["Nuclear, magnetic resonance, catheter and Doppler",
   "Magnetic resonance is described separately from the stress tests rather than as one of them."],
  ["Treadmill, bicycle, handgrip and cold pressor",
   "These are two modalities within the standard exercise test rather than two types of stress test."]],
 "c": 0, "cite": c(28)},

{"topic": "Exercise stress test", "io": IOE, "slot": "mechanism",
 "q": "How does an exercise stress test detect myocardial ischemia?",
 "opts": [
  ["Indirectly, by continuous electrocardiographic monitoring",
   "Correct. It never images the heart at all; it infers ischemia from what the electrocardiogram does as demand rises, which is why the word is indirectly."],
  ["Directly, by imaging myocardial perfusion during exercise",
   "Direct perfusion imaging is what the nuclear study adds; the standard exercise test relies on the electrocardiogram."],
  ["By measuring coronary artery calcium before and after exercise",
   "Calcium scoring is a non-contrast computed tomography study and is not part of stress testing."],
  ["By measuring ejection fraction at peak exercise",
   "Ejection fraction is an echocardiographic measure; the standard exercise test does not obtain it."]],
 "c": 0, "cite": c(29)},

{"topic": "Exercise stress test", "io": IOE, "slot": "interpretation",
 "q": "Which electrocardiographic changes during an exercise stress test suggest ischemia?",
 "opts": [
  ["ST depression",
   "Correct. Both appear as the heart is worked and are what the continuous monitoring exists to catch. Or the development of premature ventricular contractions."],
  ["ST elevation with reciprocal change",
   "The changes described for this test are ST depression and ectopy rather than elevation."],
  ["A prolonged QT interval",
   "QT prolongation is not among the described findings; ST depression and premature ventricular contractions are."],
  ["Loss of P waves",
   "Absent P waves indicate atrial fibrillation rather than the ischemic changes described."]],
 "c": 0, "cite": c(29)},

{"topic": "Exercise stress test", "io": IOE, "slot": "modality choice",
 "q": "Which exercise modalities are used, and which is preferred among the cycles?",
 "opts": [
  ["Treadmill and cycle ergometer",
   "Correct, and arm ergometry exists for patients who cannot use their legs, which keeps the test available to more people. With the stationary bicycle preferred."],
  ["Treadmill only",
   "Cycle ergometry is described alongside the treadmill as one of the two common modalities."],
  ["Arm ergometry, as first choice",
   "Arm ergometry is listed but the stationary bicycle is the preferred cycle."],
  ["Step testing",
   "Step testing is not among the modalities described, which are the treadmill, the cycle ergometer and arm ergometry."]],
 "c": 0, "cite": c(30)},

{"topic": "Exercise stress test", "io": IOE, "slot": "complication",
 "q": "Which complications of exercise stress testing are described?",
 "opts": [
  ["Arrhythmia, angina, infarction and death",
   "Correct. The test deliberately provokes the thing it is looking for, which is why it is supervised and why it has a stopping rule."],
  ["Contrast-induced nephropathy",
   "No contrast is given in a standard exercise stress test. The complications are arrhythmia, angina, infarction and death."],
  ["Malignancy induced by radiation exposure",
   "The standard exercise test uses no ionizing radiation. Its complications are arrhythmia, angina, infarction and death."],
  ["Esophageal perforation",
   "That risk belongs to transesophageal echocardiography rather than to exercise testing."]],
 "c": 0, "cite": c(30)},

{"topic": "Exercise stress test", "io": IOE, "slot": "interpretation",
 "q": "A patient stops an exercise stress test having reached 70 percent of their predicted maximum heart rate, with no electrocardiographic changes. How should the result be read?",
 "opts": [
  ["Inadequate to exclude ischemia",
   "Correct. The threshold for a valid test is 85 percent, so a negative result below it says nothing about the heart, only about the test."],
  ["A negative test, excluding ischemia",
   "A negative result only counts once the heart rate threshold has been reached."],
  ["A positive test",
   "Nothing here indicates ischemia; the problem is that the test was not taken far enough to say."],
  ["Equivocal, requiring repeat in six months",
   "The result is uninterpretable rather than equivocal, and the stated consequence is that ischemia has not been excluded."]],
 "c": 0, "cite": c(31)},

{"topic": "Exercise stress test", "io": IOE, "slot": "indication",
 "q": "Which of these is a stated indication for exercise stress testing?",
 "opts": [
  ["Cardiac assessment before non-cardiac surgery in a high-risk patient",
   "Correct, alongside symptoms suggesting ischemia, known ischemic disease with a change in status, prior revascularization and newly diagnosed heart failure."],
  ["Acute chest pain before acute coronary syndrome has been excluded",
   "The indication applies specifically after acute coronary syndrome and infarction have been excluded, not before."],
  ["Suspected aortic dissection",
   "Dissection is assessed by imaging the aorta rather than by stressing the heart."],
  ["Screening an asymptomatic patient with no risk factors",
   "Screening in that setting is not among the listed indications."]],
 "c": 0, "cite": c(32)},

{"topic": "Exercise stress test", "io": IOE, "slot": "procedure",
 "q": "What is obtained before an exercise stress test begins?",
 "opts": [
  ["A resting electrocardiogram",
   "Correct. Without the resting baseline there is nothing to compare the exercise tracing against. Blood pressure both supine and standing."],
  ["A resting echocardiogram in every case",
   "A resting echocardiogram is obtained for the echocardiographic stress test rather than for the standard one."],
  ["A coronary calcium score",
   "Calcium scoring is a separate computed tomography study. What is obtained first is a resting tracing and blood pressure."],
  ["A radionuclide injection at rest",
   "Resting tracer injection belongs to the nuclear perfusion study."]],
 "c": 0, "cite": c(33)},

{"topic": "Exercise stress test", "io": IOE, "slot": "procedure",
 "q": "When is an exercise stress test terminated?",
 "opts": [
  ["At maximum performance",
   "Correct. Three separate stopping conditions, only one of which is the patient simply having had enough. On signs or symptoms of ischemia, or at a predetermined endpoint."],
  ["Only when the patient asks to stop",
   "The patient's request is not the only stopping condition; ischemic signs and a predetermined endpoint also stop it."],
  ["After a fixed twelve minutes regardless of response",
   "No fixed duration is given; the endpoints are performance, symptoms or a predetermined target."],
  ["When blood pressure returns to baseline",
   "Blood pressure is monitored through the test rather than used as the endpoint."]],
 "c": 0, "cite": c(33)},

{"topic": "Echocardiographic stress test", "io": IOE, "slot": "modality choice",
 "q": "For which patient is an echocardiographic stress test the appropriate initial choice?",
 "opts": [
  ["One who can exercise but whose resting tracing is abnormal",
   "Correct. The electrocardiogram cannot be read for ischemia if it is already abnormal, so the imaging has to carry the answer instead."],
  ["One who cannot exercise at all",
   "A patient unable to exercise is given a pharmacological stress test."],
  ["One with a normal resting electrocardiogram who can exercise",
   "That patient can have the standard exercise test, which is simpler."],
  ["One with suspected aortic dissection",
   "Dissection is assessed by imaging the aorta rather than by stress testing."]],
 "c": 0, "cite": c(37)},

{"topic": "Echocardiographic stress test", "io": IOE, "slot": "procedure",
 "q": "What is the echocardiogram looking for after exercise, and why must it be obtained quickly?",
 "opts": [
  ["Abnormal left ventricular wall motion induced by exercise",
   "Correct. The finding is transient, so the patient is asked to dismount quickly and the heart is imaged before it settles. Which resolves as the heart recovers."],
  ["Valve gradients, which take time to develop",
   "The study looks for induced wall motion abnormality rather than valve gradients."],
  ["Pericardial fluid, which accumulates after exertion",
   "Pericardial fluid is not what the post-exercise images are looking for."],
  ["Coronary calcium, which is best seen at high heart rates",
   "Calcium is assessed by computed tomography and is unrelated to heart rate."]],
 "c": 0, "cite": c(37)},

{"topic": "Pharmacological stress test", "io": IOE, "slot": "indication",
 "q": "Which patients receive a pharmacological rather than an exercise stress test?",
 "opts": [
  ["Those who cannot exercise",
   "Correct. The heart still has to be stressed; if the legs cannot do it, a drug does it instead. Usually because of a physical limitation."],
  ["Those with a normal resting electrocardiogram",
   "A normal resting tracing makes the standard exercise test easier to interpret rather than ruling it out."],
  ["Those with renal impairment",
   "Renal impairment is a consideration for iodinated contrast rather than for exercise capacity."],
  ["Those under forty years of age",
   "Age is not the basis for choosing it; inability to exercise, usually from a physical limitation, is."]],
 "c": 0, "cite": c(38)},

{"topic": "Cardiac computed tomography", "io": IOG, "slot": "procedure",
 "q": "Why are cardiac medications given before a cardiac computed tomography study?",
 "opts": [
  ["To control heart rate, since the moving heart degrades the images",
   "Correct, and the study is also synchronized to an electrocardiogram so the heart can be examined at chosen points in the cycle."],
  ["To dilate the coronary arteries so contrast reaches the myocardium",
   "Rate control is the stated reason, together with electrocardiographic synchronization."],
  ["To prevent an allergic reaction to the contrast",
   "Premedication for contrast allergy is not what is described here."],
  ["To provoke ischemia during the scan",
   "Provoking ischemia is what a stress test does; the medication here steadies the heart."]],
 "c": 0, "cite": c(41)},

{"topic": "Cardiac computed tomography", "io": IOG, "slot": "modality choice",
 "q": "What is a non-contrast cardiac computed tomography particularly useful for?",
 "opts": [
  ["Coronary artery calcium scoring",
   "Correct. Calcium is dense enough to be seen without contrast, so the study that needs no contrast is the one that measures it."],
  ["Assessing coronary stenosis",
   "Assessing stenosis requires contrast, which is what computed tomography angiography adds."],
  ["Measuring ejection fraction",
   "Ejection fraction is a functional measure obtained by echocardiography or magnetic resonance."],
  ["Detecting valve vegetations",
   "Vegetations are sought on echocardiography, particularly the transesophageal study."]],
 "c": 0, "cite": c(40)},

{"topic": "Cardiac computed tomography", "io": IOG, "slot": "indication",
 "q": "Which is a stated indication for coronary computed tomography angiography?",
 "opts": [
  ["Evaluating an equivocal or non-diagnostic stress test",
   "Correct. It answers the question the stress test left open, alongside assessing chest pain and detecting or excluding stenosis and plaque."],
  ["Assessing myocardial viability after infarction",
   "Viability is assessed by nuclear perfusion imaging or magnetic resonance."],
  ["Measuring pulmonary artery occlusion pressure",
   "That is measured at right heart catheterization rather than by computed tomography angiography."],
  ["Locating the origin of an arrhythmia",
   "Arrhythmia localization is the role of electrophysiological testing."]],
 "c": 0, "cite": c(42)},

{"topic": "Cardiac computed tomography", "io": IOG, "slot": "indication",
 "q": "Which is an indication for cardiac computed tomography rather than the angiographic study?",
 "opts": [
  ["Pre-operative planning before cardiac surgery",
   "Correct, alongside calcium deposits, coronary anatomical anomalies and congenital disease, and it is usually done immediately before the angiographic study. Particularly valvular and great vessel procedures."],
  ["Detecting and excluding coronary stenosis",
   "Stenosis detection is the indication for the angiographic study."],
  ["Assessing exercise capacity",
   "Exercise capacity is assessed by stress testing rather than by cardiac computed tomography."],
  ["Evaluating deep venous thrombosis",
   "Deep vein thrombosis is assessed by vascular ultrasound rather than by cardiac computed tomography."]],
 "c": 0, "cite": c(43)},

{"topic": "Cardiac computed tomography", "io": IOG, "slot": "advantage",
 "q": "What advantages does cardiac computed tomography have over echocardiography?",
 "opts": [
  ["Superior resolution and noninvasive coronary assessment",
   "Correct, with fast acquisition and interpretation as well, which together make it the anatomical study of choice. It also shows internal structures directly, and acquires and reports quickly."],
  ["Assessment of cardiac function as well as anatomy",
   "Function is exactly what it cannot assess; that is left to echocardiography and magnetic resonance."],
  ["Freedom from ionizing radiation",
   "Radiation is one of its disadvantages rather than an advantage; magnetic resonance is what avoids it."],
  ["Independence from heart rate and rhythm",
   "It is rhythm and rate dependent, which is why rate control is given beforehand."]],
 "c": 0, "cite": c(44)},

{"topic": "Cardiac computed tomography", "io": IOG, "slot": "limitation",
 "q": "What is the blooming artifact, and why does it matter?",
 "opts": [
  ["Heavy calcification appears larger than it is",
   "Correct. The artifact exaggerates the very lesion the study was ordered to assess, which is a limitation worth naming rather than a curiosity. So a stenosis looks more severe."],
  ["Motion during the scan blurs the coronary arteries",
   "Motion blur is a separate problem, addressed by rate control and gating."],
  ["Contrast pools in the ventricle and obscures the valve",
   "That is not what blooming describes. Blooming makes dense calcium appear larger than it is."],
  ["Radiation scatter degrades the image at the edges",
   "Blooming relates to dense calcium appearing larger than it is, rather than to radiation scatter."]],
 "c": 0, "cite": c(44)},

{"topic": "Cardiac computed tomography", "io": IOG, "slot": "limitation",
 "q": "What is the fundamental limitation of cardiac computed tomography compared with echocardiography and magnetic resonance?",
 "opts": [
  ["It assesses anatomy but not function",
   "Correct. It shows the structure in great detail and cannot tell you how well it is working, which decides when it is the wrong study."],
  ["It cannot show the coronary arteries",
   "Noninvasive coronary assessment is one of its strengths. What it cannot show is function."],
  ["It cannot be used in patients with a normal heart rate",
   "A controlled heart rate is what it requires rather than what excludes it."],
  ["It requires an endoscope",
   "No endoscope is involved; that belongs to transesophageal echocardiography."]],
 "c": 0, "cite": c(44)},

{"topic": "Nuclear cardiology", "io": IOF, "slot": "mechanism",
 "q": "On what principle does radionuclide myocardial perfusion imaging work?",
 "opts": [
  ["Under stress, diseased myocardium receives less blood flow than normal myocardium",
   "Correct, so comparing stress images against rest images is what makes the difference visible rather than either set alone."],
  ["Diseased myocardium takes up more tracer than normal myocardium",
   "Uptake is reduced rather than increased where flow is reduced."],
  ["Tracer is taken up only by scarred tissue",
   "Uptake marks functional, viable tissue; scar does not take it up."],
  ["The tracer is metabolized into a contrast agent within the coronary arteries",
   "The tracer emits gamma rays that the camera detects rather than becoming contrast."]],
 "c": 0, "cite": c(49)},

{"topic": "Nuclear cardiology", "io": IOF, "slot": "interpretation",
 "q": "A region of myocardium shows no tracer uptake on either the stress or the rest images. What does that indicate?",
 "opts": [
  ["Dead tissue",
   "Correct. Uptake requires functional myocardium, so tissue that never lights up is not ischemic but infarcted."],
  ["Inducible ischemia",
   "Inducible ischemia shows reduced uptake after stress with better uptake at rest, rather than absent uptake in both."],
  ["Normal myocardium",
   "Normal tissue takes up tracer in both sets of images; absent uptake in both indicates infarction."],
  ["An artifact of the gamma camera",
   "Absent uptake in both sets is a finding rather than an artifact."]],
 "c": 0, "cite": c(48)},

{"topic": "Nuclear cardiology", "io": IOF, "slot": "interpretation",
 "q": "Tracer uptake in a region is normal at rest but reduced after stress. What does that pattern indicate?",
 "opts": [
  ["Inducible ischemia, from a coronary stenosis",
   "Correct. The tissue is alive but cannot increase its supply when demand rises, which is what a stenosis does."],
  ["Infarcted, non-viable tissue",
   "Infarcted tissue shows no uptake in either set. Reduced uptake only after stress indicates inducible ischemia."],
  ["Normal myocardium",
   "Normal tissue maintains or increases uptake under stress rather than losing it."],
  ["A pericardial effusion",
   "Pericardial fluid is not assessed by perfusion imaging; the pattern described indicates inducible ischemia."]],
 "c": 0, "cite": c(48)},

{"topic": "Nuclear cardiology", "io": IOF, "slot": "modality choice",
 "q": "How does nuclear perfusion imaging compare with standard and echocardiographic stress testing?",
 "opts": [
  ["Its sensitivity and specificity are superior",
   "Correct, which is why it is worth the tracer and the radiation when the simpler tests have not settled the question."],
  ["It is less accurate but faster",
   "It is described as more accurate than standard and echocardiographic stress testing rather than less."],
  ["It is equivalent in accuracy but avoids radiation",
   "It uses a radioactive tracer, and it is described as more accurate."],
  ["It assesses anatomy rather than perfusion",
   "It assesses perfusion and thus viability rather than anatomy."]],
 "c": 0, "cite": c(49)},

{"topic": "Nuclear cardiology", "io": IOF, "slot": "procedure",
 "q": "How is the heart stressed for a nuclear perfusion study in a patient who cannot exercise?",
 "opts": [
  ["Pharmacologically, with an agent such as adenosine",
   "Correct. The stress can be produced by exercise or by drug, and the imaging is the same either way."],
  ["By transesophageal pacing",
   "Pacing is not the described method; pharmacological stress with an agent such as adenosine is."],
  ["By cold pressor testing",
   "Not among the described methods. Pharmacological stress, with an agent such as adenosine, is used instead."],
  ["The study cannot be performed without exercise",
   "Pharmacological stress exists precisely so that it can be performed without exercise."]],
 "c": 0, "cite": c(47)},

{"topic": "Cardiovascular magnetic resonance", "io": IOH, "slot": "advantage",
 "q": "What does cardiovascular magnetic resonance avoid that computed tomography does not?",
 "opts": [
  ["Both ionizing radiation and iodinated contrast",
   "Correct. Both avoided at once, which matters most in the young patient and in the patient with impaired kidneys."],
  ["Dependence on the operator",
   "Operator dependence is a limitation of ultrasound rather than the point of comparison here."],
  ["Any need for a resting heart rate",
   "Rate control is a computed tomography requirement; it is not what magnetic resonance is described as avoiding."],
  ["Sedation and airway monitoring",
   "Sedation is required for transesophageal echocardiography rather than being the contrast drawn here."]],
 "c": 0, "cite": c(55)},

{"topic": "Cardiovascular magnetic resonance", "io": IOH, "slot": "indication",
 "q": "What is done before a cardiovascular magnetic resonance study is ordered?",
 "opts": [
  ["An echocardiogram",
   "Correct. It is the first-line functional study, and magnetic resonance answers what it leaves unresolved rather than replacing it."],
  ["A coronary angiogram",
   "Angiography is invasive and is not a prerequisite for magnetic resonance."],
  ["A nuclear perfusion study",
   "A perfusion study is not the stated prerequisite; an echocardiogram is done before magnetic resonance is ordered."],
  ["A coronary calcium score",
   "Calcium scoring is not the stated prerequisite; an echocardiogram is done first."]],
 "c": 0, "cite": c(56)},

{"topic": "Cardiovascular magnetic resonance", "io": IOH, "slot": "indication",
 "q": "Which aortic conditions is cardiovascular magnetic resonance used to diagnose and monitor?",
 "opts": [
  ["Aneurysm, dissection, hematoma, coarctation",
   "Correct. All four are questions about the wall and the lumen of a large vessel, which is where its detailed anatomy is most useful."],
  ["The coronary artery calcium burden",
   "Calcium is scored by non-contrast computed tomography rather than by magnetic resonance."],
  ["Valve vegetations",
   "Vegetations are sought on echocardiography, particularly the transesophageal study."],
  ["Deep venous thrombosis",
   "Deep vein thrombosis is assessed by vascular ultrasound rather than by cardiovascular magnetic resonance."]],
 "c": 0, "cite": c(56)},

{"topic": "Cardiovascular magnetic resonance", "io": IOH, "slot": "indication",
 "q": "Which cardiomyopathy questions is cardiovascular magnetic resonance used to answer?",
 "opts": [
  ["Hypertrophic cardiomyopathy",
   "Correct. Each turns on what the muscle itself is doing, which is where it outperforms the studies that show the arteries. Ischemic against nonischemic, acute myocarditis and cardiac sarcoidosis."],
  ["The degree of coronary stenosis",
   "Stenosis is assessed by computed tomography angiography or catheter angiography."],
  ["Exercise capacity",
   "Exercise capacity is assessed by stress testing rather than by magnetic resonance."],
  ["Left atrial appendage thrombus",
   "Appendage thrombus is sought on transesophageal echocardiography."]],
 "c": 0, "cite": c(57)},

{"topic": "Electrophysiological testing", "io": IOI, "slot": "indication",
 "q": "What does electrophysiological testing do?",
 "opts": [
  ["Investigates rhythm disorders and locates an arrhythmia",
   "Correct, and where applicable it treats as well as diagnoses, by ablating the tissue it has just located. It reveals the precise location, and where applicable treats it by ablation in the same sitting."],
  ["Assesses myocardial perfusion under stress conditions",
   "Perfusion under stress is the nuclear study. Electrophysiological testing investigates rhythm disorders."],
  ["Measures the cardiothoracic ratio",
   "That is a chest radiograph measurement rather than an electrophysiological one."],
  ["Visualizes coronary anatomy",
   "Coronary anatomy is shown by angiography; electrophysiological testing locates arrhythmias."]],
 "c": 0, "cite": c(61)},

{"topic": "Electrophysiological testing", "io": IOI, "slot": "mechanism",
 "q": "What does catheter ablation do during electrophysiological testing?",
 "opts": [
  ["Inactivates part of the heart by destroying that tissue",
   "Correct. The tissue is not merely silenced but destroyed, which is what makes the treatment definitive."],
  ["Stimulates the area to restore normal conduction",
   "Stimulation is used to identify the arrhythmia; the ablation destroys rather than restores."],
  ["Places a permanent pacing wire in the atrium",
   "Catheters are placed for the study, but ablation itself destroys tissue."],
  ["Delivers a drug directly to the arrhythmic focus",
   "Ablation is a physical rather than a pharmacological treatment."]],
 "c": 0, "cite": c(62)},

{"topic": "Electrophysiological testing", "io": IOI, "slot": "indication",
 "q": "Which patient with syncope is an indication for electrophysiological testing?",
 "opts": [
  ["One with ischemic or other structural heart disease",
   "Correct, alongside sick sinus syndrome, survivors of sudden cardiac arrest without an established cause, ectopic beats and a suspected aberrant pathway."],
  ["One with a normal heart and a clear vasovagal trigger",
   "A clear benign cause is not among the listed indications, which center on structural disease and unexplained arrest."],
  ["One with suspected aortic dissection",
   "Dissection is an imaging question rather than an electrophysiological one."],
  ["One with deep venous thrombosis",
   "Not among the listed indications, which concern syncope with structural disease, sick sinus syndrome and unexplained arrest."]],
 "c": 0, "cite": c(63)},

{"topic": "Coronary angiography", "io": IOI, "slot": "modality choice",
 "q": "What is coronary angiography the gold standard for?",
 "opts": [
  ["Coronary artery anatomy and cardiac function",
   "Correct, which is why it is usually performed before any percutaneous or surgical intervention on the coronary arteries."],
  ["Assessing myocardial viability",
   "Viability is assessed by nuclear perfusion imaging or magnetic resonance."],
  ["Measuring the coronary calcium score",
   "Calcium scoring is a non-contrast computed tomography study."],
  ["Detecting valve vegetations",
   "Vegetations are sought on echocardiography. Angiography is the gold standard for coronary anatomy and cardiac function."]],
 "c": 0, "cite": c(66)},

{"topic": "Cardiac catheterization", "io": IOI, "slot": "indication",
 "q": "What does LEFT heart catheterization assess?",
 "opts": [
  ["Coronary anatomy, aortic pressure and left ventricular function",
   "Correct. Everything on the systemic side of the circulation, which is the side the left heart serves. Together with systemic vascular resistance, and aortic and mitral valve function, and left ventricular pressure."],
  ["Pulmonary artery pressure and vascular resistance",
   "These are right heart measurements. The left heart study assesses coronary anatomy and the systemic side."],
  ["Tricuspid and pulmonic valve function",
   "These are assessed at right heart catheterization; the left study covers the aortic and mitral valves."],
  ["Right atrial pressure",
   "That is a right heart measurement rather than one obtained from the left side."]],
 "c": 0, "cite": c(68)},

{"topic": "Cardiac catheterization", "io": IOI, "slot": "indication",
 "q": "What does RIGHT heart catheterization assess?",
 "opts": [
  ["Right-sided pressures, pulmonary resistance, valves and shunts",
   "Correct. The pulmonary side of the circulation, and the shunts that connect the two sides. In full: right atrial and right ventricular pressure, pulmonary artery and occlusion pressure, pulmonary vascular resistance, tricuspid and pulmonic valve function, and intracardiac shunts."],
  ["The coronary artery anatomy",
   "Coronary anatomy is assessed from the left side rather than the right."],
  ["Aortic and mitral valve function",
   "Both are left heart structures, assessed at left rather than right catheterization."],
  ["Systemic vascular resistance",
   "That is a left heart measurement; the right study gives pulmonary vascular resistance instead."]],
 "c": 0, "cite": c(69)},

{"topic": "Coronary angiography", "io": IOI, "slot": "indication",
 "q": "Which is a listed indication for coronary angiography?",
 "opts": [
  ["Severe angina despite medical therapy",
   "Correct, together with acute infarction, a high-risk noninvasive test result, high-risk patients undergoing non-cardiac surgery, and arrhythmias suspected to be vascular in origin. Or unstable angina."],
  ["Screening an asymptomatic patient",
   "Screening is not an indication for an invasive study carrying the risks this one does."],
  ["Suspected deep venous thrombosis",
   "That is assessed by vascular ultrasound rather than by coronary angiography."],
  ["Newly diagnosed atrial fibrillation alone",
   "Atrial fibrillation alone is not among the listed indications."]],
 "c": 0, "cite": c(71)},

{"topic": "Coronary angiography", "io": IOI, "slot": "procedure",
 "q": "How is coronary angiography performed?",
 "opts": [
  ["Under local anesthesia with intravenous sedation",
   "Correct, and pressures are measured as the catheter goes, so it yields hemodynamic information alongside the pictures. With catheters guided by fluoroscopy and contrast injected into each coronary artery."],
  ["Under general anesthesia with the patient intubated",
   "Local anesthesia with intravenous sedation is what is described, with fluoroscopic guidance."],
  ["Without contrast, using ultrasound guidance",
   "Radiographic contrast is injected into each coronary artery."],
  ["Through the esophagus",
   "The esophageal route belongs to transesophageal echocardiography."]],
 "c": 0, "cite": c(72)},

{"topic": "Coronary angiography", "io": IOI, "slot": "advantage",
 "q": "What can be done during a coronary angiogram that cannot be done during any of the noninvasive studies?",
 "opts": [
  ["Treatment, by percutaneous coronary intervention there and then",
   "Correct. It is the one study that can fix what it finds while the catheter is still in place."],
  ["Measurement of ejection fraction",
   "Ejection fraction can be obtained noninvasively by echocardiography."],
  ["Assessment of myocardial viability",
   "Viability is assessed noninvasively by nuclear imaging or magnetic resonance."],
  ["Calcium scoring",
   "Calcium scoring is a noninvasive computed tomography study and needs no catheter."]],
 "c": 0, "cite": c(72)},

{"topic": "Coronary angiography", "io": IOI, "slot": "complication",
 "q": "Which complications of coronary angiography occur at the catheter insertion site?",
 "opts": [
  ["Hematoma and pseudoaneurysm",
   "Correct, and the pseudoaneurysm is the one to check for deliberately, since it maintains a continuous communication with the artery."],
  ["Contrast nephropathy and arrhythmia",
   "Both are recognized risks of the procedure but are not site complications."],
  ["Esophageal perforation",
   "That belongs to transesophageal echocardiography rather than to arterial catheterization."],
  ["Pneumothorax",
   "Not among the described site complications, which are hematoma and pseudoaneurysm."]],
 "c": 0, "cite": c(78)},

{"topic": "Coronary angiography", "io": IOI, "slot": "complication",
 "q": "What distinguishes a pseudoaneurysm at the puncture site from a simple hematoma?",
 "opts": [
  ["It pulsates, and still communicates with the artery",
   "Correct. Blood still moves in and out of it, which is why it can keep expanding and why the site is always checked."],
  ["It is larger but does not pulsate",
   "Pulsatility is the distinguishing feature, along with a continuous communication with the artery."],
  ["It resolves without intervention in every case",
   "The continuous arterial communication is what makes it more than a bruise."],
  ["It occurs only in the radial artery",
   "The femoral site is the one specifically illustrated, and what defines it is pulsatility and arterial communication."]],
 "c": 0, "cite": c(78)},
]
