# -*- coding: utf-8 -*-
# PDM I Lecture 12 (Ectopy, Escape Rhythms and Supraventricular Dysrhythmias, Scott Mathis) --
# pool B. Objectives f-h: wandering atrial pacemaker and multifocal atrial tachycardia (the deck's
# atrial tachycardia), atrial flutter, atrial fibrillation, and atrioventricular nodal reentrant
# tachycardia (the rhythm the deck and the lecturer call supraventricular tachycardia), with
# their anatomy and physiology.
#
# Strips viewed at full size; crops in extract_pdm_l12_figures.py (the slide 16 strip carried
# the words "wandering atrial pacemaker" in its watermark, now cropped). Alt text describes
# only what is visible. Stems that state a rate carry the normal adult resting range.
#
# WORDING AND TRUTH, flagged in the guide rather than keyed on the slide's words:
#   * slide 5 lists "Multifocal atrial pacemaker (MAT)"; the rhythm is multifocal atrial
#     TACHYCARDIA (slide 17 has it right).
#   * slide 38 places the reentry circuit "in between the internodal pathways of the sinus node
#     and the AV node"; current teaching puts the slow and fast pathways of this circuit in and
#     around the atrioventricular node itself. Questions key only what both say: a reentry circuit
#     over a slow and a fast pathway, triggered by an ectopic beat.
#   * slide 38 says ALL cases of this reentry tachycardia are triggered by an ectopic focus such
#     as a premature atrial complex; that is the usual trigger, not the only one, so the trigger
#     question asks what USUALLY sets it off (2026-10-08 fact-check). The slide 38 onset strip
#     shows the rate change, not a premature beat, so the stem carries the ask.
#   * slide 27 gives the flutter atrial rate as 200-350; the classic flutter rate (and both of
#     the deck's worked strips) is about 300, which is what is keyed.
# NAME USED FOR THE STRIPS. "Supraventricular tachycardia" is keyed for the regular narrow
# reentry tachycardia because that is the name the deck gives it ("commonly referred to as
# SVT") and the syllabus objective uses; every explanation says why sinus, junctional and
# multifocal atrial tachycardia are not called that here, in the deck's sense.
# Emphasis (recording): reentry tachycardia about 13 minutes, flutter about 10, fibrillation 8,
# wandering pacemaker and multifocal atrial tachycardia about 5.
from pdm_l12_pool_a import Q, c

IOF = "Recognize common supraventricular dysrhythmias: atrial tachycardia, supraventricular tachycardia (SVT), atrial flutter, atrial fibrillation"
IOG = "Compare and contrast ECG findings associated with supraventricular dysrhythmias: atrial flutter, atrial fibrillation, SVT, atrial tachycardia"
IOH = "Discuss the related anatomy and physiology of supraventricular arrhythmias"

WAP_ALT = "Pink grid strip of narrow complexes at slightly uneven spacing; the small waves before them vary in shape."
WAP2_ALT = "Wide pink grid strip with deep narrow complexes at uneven spacing; the small waves in front of them change shape."
MAT_ALT = "Blue grid strip of rapid narrow complexes at uneven spacing; three upward arrows below point to small waves of differing shape."
MAT2_ALT = "Small lead II strip of very rapid narrow complexes at uneven spacing with small waves of varying shape between them."
FL_ALT = "Rhythm strip with three-second tick marks: narrow complexes separated by a continuous zigzag baseline of repeating pointed waves."
FL3_ALT = "Long rhythm strip of narrow spikes with a repeating pointed zigzag baseline between them, the spikes evenly spaced."
FLV_ALT = "Gray grid strip of four narrow complexes at unequal spacing, with a continuous rounded zigzag baseline between them."
AF_ALT = "Pink grid strip of narrow complexes at unpredictable spacing, with a wavy, shapeless baseline and no distinct waves before them."
AF2_ALT = "Pink grid strip of narrow complexes at constantly changing intervals, over a fine uneven baseline."
NR_ALT = "Blue grid strip of very rapid, evenly spaced narrow complexes; after each one the trace climbs to a single pointed wave that falls straight into the next complex."
NR2_ALT = "Gray grid strip with a faint watermark, showing very rapid, evenly spaced narrow complexes with small notches at their ends."

POOL_B = [

# ------------------------------------------------------------ wandering atrial pacemaker / multifocal atrial tachycardia
Q("Wandering atrial pacemaker", IOF, "name WAP",
  "A 60-year-old man's rate is 60 per minute (normal 60 to 100); his strip is shown. What is the rhythm?",
  ("Wandering atrial pacemaker",
   "Correct. The rhythm is irregular, under 100 per minute, with P waves of at least three different shapes still married to the QRS: a wandering atrial pacemaker."),
  [("Multifocal atrial tachycardia",
    "Multifocal atrial tachycardia has the same three-shape P waves but runs over 100 per minute; at 60 it is a wandering atrial pacemaker."),
   ("Sinus arrhythmia",
    "Sinus arrhythmia is irregular too, but every P wave has the same sinus shape; here the P waves change shape."),
   ("Atrial fibrillation",
    "Atrial fibrillation has no P waves at all, only fibrillatory waves; here distinct P waves precede every QRS.")],
  c(11, 12, 13, 14), img="l12-s013-wandering-atrial-pacemaker.jpg", alt=WAP_ALT, slide=13),

Q("Wandering atrial pacemaker", IOF, "name WAP b",
  "A 66-year-old woman's rate is 65 per minute (normal 60 to 100); her strip is shown. What is the rhythm?",
  ("Wandering atrial pacemaker",
   "Correct. P waves of at least three shapes, each married to its QRS, an irregular rhythm and a rate under 100 make a wandering atrial pacemaker."),
  [("Multifocal atrial tachycardia",
    "Multifocal atrial tachycardia needs a rate over 100 per minute; at 65 this is a wandering atrial pacemaker."),
   ("Premature atrial complexes",
    "Premature atrial complexes are occasional early beats in an otherwise sinus rhythm; here the P wave shape keeps changing."),
   ("Normal sinus rhythm",
    "Normal sinus rhythm is regular with one P wave shape; here it is irregular with several.")],
  c(11, 15, 16), img="l12-s016-wandering-atrial-pacemaker-b.png", alt=WAP2_ALT, slide=16),

Q("Wandering atrial pacemaker", IOG, "WAP definition",
  "A 70-year-old man has a wandering atrial pacemaker. How many P wave shapes define it?",
  ("At least three",
   "Correct. At least three different areas of the atria compete to be the pacemaker, so there are P waves of at least three different morphologies."),
  [("At least two",
    "Two shapes is not enough; a wandering atrial pacemaker needs at least three competing atrial sites and P wave shapes."),
   ("Exactly one",
    "One P wave shape means one pacemaker, the sinus node; a wandering pacemaker shows at least three."),
   ("None visible",
    "No visible P waves fits atrial fibrillation or a junctional rhythm; a wandering pacemaker has P waves of three shapes.")],
  c(11, 12)),

Q("Multifocal atrial tachycardia", IOF, "name MAT",
  "A 74-year-old woman's rate is 180 per minute (normal 60 to 100); her strip is shown, the arrows marking P waves. What is the rhythm?",
  ("Multifocal atrial tachycardia",
   "Correct. P waves of at least three shapes, still married to the QRS, in an irregular rhythm over 100 per minute make multifocal atrial tachycardia."),
  [("Wandering atrial pacemaker",
    "A wandering atrial pacemaker has the same P wave variety but is under 100 per minute; at 180 it is multifocal atrial tachycardia."),
   ("Atrial fibrillation",
    "Atrial fibrillation is irregular with no P waves; here distinct P waves of different shapes precede the QRS complexes."),
   ("Supraventricular tachycardia",
    "The reentry tachycardia called supraventricular tachycardia is regular with no visible P waves; this rhythm is irregular with several P shapes.")],
  c(17, 18, 19, 20), img="l12-s019-multifocal-atrial-tachycardia.jpg", alt=MAT_ALT, slide=19),

Q("Multifocal atrial tachycardia", IOF, "name MAT b",
  "A 77-year-old man's rate is 150 per minute (normal 60 to 100); his strip is shown. What is the rhythm?",
  ("Multifocal atrial tachycardia",
   "Correct. An irregular rhythm over 100 per minute with P waves of at least three shapes married to narrow complexes is multifocal atrial tachycardia."),
  [("Sinus tachycardia",
    "Sinus tachycardia is regular with one sinus P wave shape; here the rhythm is irregular and the P waves vary."),
   ("Atrial flutter",
    "Atrial flutter shows a regular sawtooth baseline instead of P waves; here separate P waves of differing shapes appear."),
   ("Wandering atrial pacemaker",
    "A wandering atrial pacemaker is the same rhythm under 100 per minute; at 150 it is multifocal atrial tachycardia.")],
  c(17, 18, 21, 22), img="l12-s021-multifocal-atrial-tachycardia-b.jpg", alt=MAT2_ALT, slide=21),

Q("Multifocal atrial tachycardia", IOG, "WAP vs MAT",
  "A 69-year-old woman's strip shows P waves of three different shapes. What separates multifocal atrial tachycardia from a wandering atrial pacemaker?",
  ("A rate over 100 per minute",
   "Correct. Multifocal atrial tachycardia is exactly a wandering atrial pacemaker except that the rate is over 100 per minute."),
  [("Regular R to R intervals",
    "Both are irregular, because the pacemaker site keeps shifting; only the rate separates them."),
   ("Absent P waves",
    "Both show P waves of at least three shapes; the difference is a rate over 100 per minute."),
   ("Wide QRS complexes",
    "Either may have narrow or wide QRS complexes; the rate over 100 per minute is what separates them.")],
  c(12, 17, 18)),

Q("Multifocal atrial tachycardia", IOG, "MAT vs fibrillation",
  "A 72-year-old man has an irregular narrow-complex tachycardia. Which finding favors multifocal atrial tachycardia over atrial fibrillation?",
  ("P waves of three distinct shapes",
   "Correct. Multifocal atrial tachycardia has visible P waves of at least three morphologies married to the QRS; atrial fibrillation has no P waves, only fibrillatory waves."),
  [("An irregularly irregular rhythm",
    "Irregularly irregular is the defining regularity of atrial fibrillation; both rhythms are irregular."),
   ("A rate over 100 per minute",
    "Both rhythms can run over 100 per minute; distinct P waves of three shapes point to multifocal atrial tachycardia."),
   ("Narrow QRS complexes",
    "Both are supraventricular and can have narrow complexes; the three P wave shapes are the distinguishing finding.")],
  c(18, 33)),

# ------------------------------------------------------------ atrial flutter
Q("Atrial flutter", IOF, "name flutter",
  "A 68-year-old man's strip is shown. What is the rhythm?",
  ("Atrial flutter",
   "Correct. The baseline between the narrow QRS complexes is a continuous sawtooth of flutter waves, a pattern pathognomonic of atrial flutter."),
  [("Atrial fibrillation",
    "Atrial fibrillation has a chaotic, shapeless baseline and an irregularly irregular rhythm; this baseline is an organized sawtooth."),
   ("Multifocal atrial tachycardia",
    "Multifocal atrial tachycardia shows separate P waves of three shapes; here the baseline is a repeating sawtooth."),
   ("Wandering atrial pacemaker",
    "A wandering atrial pacemaker shows distinct P waves of several shapes under 100 per minute, not a sawtooth.")],
  c(24, 26, 27), img="l12-s024-atrial-flutter-five-to-one.jpg", alt=FL_ALT, slide=24),

Q("Atrial flutter", IOF, "name flutter b",
  "A 71-year-old woman's strip is shown. What is the rhythm?",
  ("Atrial flutter",
   "Correct. Regularly spaced narrow complexes ride on a repeating pointed sawtooth baseline (flutter waves at an atrial rate of about 300): atrial flutter."),
  [("Nodal reentry tachycardia",
    "Nodal reentry tachycardia, often simply called supraventricular tachycardia, has no visible atrial waves; this baseline is a sawtooth of flutter waves."),
   ("Atrial fibrillation",
    "Fibrillation is irregularly irregular with a disorganized baseline; this strip is regular with an organized sawtooth."),
   ("Junctional tachycardia",
    "Junctional tachycardia has a single inverted P wave per QRS; here several flutter waves fill each interval.")],
  c(27, 28, 29), img="l12-s029-atrial-flutter-three-to-one.jpg", alt=FL3_ALT, slide=29),

Q("Atrial flutter", IOG, "variable conduction",
  "A 75-year-old man's strip is shown; the flutter waves are constant but the R to R intervals vary. How should it be documented?",
  ("Flutter with variable conduction",
   "Correct. When the ratio of flutter waves to QRS complexes keeps changing, the rhythm is irregular and is documented as atrial flutter with variable conduction."),
  [("Flutter with 2:1 conduction",
    "A fixed 2:1 ratio would give evenly spaced QRS complexes; here the spacing changes, so the conduction is variable."),
   ("Atrial fibrillation",
    "Fibrillation has no organized waves; this baseline keeps its regular flutter waves, only the conduction varies."),
   ("Flutter with 4:1 conduction",
    "A fixed ratio of any number gives a regular rhythm; unequal R to R intervals mean variable conduction.")],
  c(25, 30, 31), img="l12-s030-atrial-flutter-variable-conduction.jpg", alt=FLV_ALT, slide=30),

Q("Atrial flutter", IOG, "document ratio",
  "A 66-year-old woman's flutter strip shows three flutter waves before every QRS, regularly. How is it documented?",
  ("Atrial flutter with 3:1 ratio",
   "Correct. Flutter is documented with its flutter-wave-to-QRS ratio; three flutter waves per QRS is atrial flutter with a 3:1 ratio."),
  [("Atrial flutter with 1:3 ratio",
    "The ratio is written flutter waves first, then QRS: three to one, 3:1."),
   ("Atrial flutter, variable",
    "Variable conduction is used only when the ratio changes beat to beat; a constant three per QRS is 3:1."),
   ("Atrial tachycardia, 3:1",
    "Sawtooth flutter waves define atrial flutter, documented as flutter with its 3:1 ratio.")],
  c(25)),

Q("Atrial flutter", IOG, "sawtooth",
  "A 63-year-old man's strip is being reviewed for a supraventricular rhythm. Which pattern is pathognomonic of atrial flutter?",
  ("A sawtooth baseline",
   "Correct. Flutter waves form a unique sawtooth pattern on the paper, and this sawtooth pattern is pathognomonic of atrial flutter."),
  [("An irregularly irregular rhythm",
    "Irregularly irregular is the regularity of atrial fibrillation; flutter can be regular or irregular, but always sawtoothed."),
   ("Inverted P waves",
    "Inverted P waves with a short PR mark a junctional rhythm; flutter has flutter waves instead of P waves."),
   ("Pseudo S waves",
    "Pseudo S waves are retrograde P waves buried at the end of the QRS in reentry tachycardia, not flutter.")],
  c(24)),

Q("Atrial flutter", IOG, "flutter atrial rate",
  "A 70-year-old woman has atrial flutter. What atrial rate do the flutter waves usually represent?",
  ("About 300 per minute",
   "Correct. The flutter waves reflect an atrial rate of about 300 per minute (the range given is 200 to 350); the ventricular rate depends on the conduction ratio."),
  [("About 100 per minute",
    "One hundred is closer to the ventricular rate in 3:1 flutter; the atrial rate is about 300."),
   ("About 150 per minute",
    "One hundred fifty is the ventricular rate in 2:1 flutter; the atrial rate is about 300."),
   ("Indeterminate",
    "An indeterminate atrial rate describes atrial fibrillation; flutter waves are organized, at about 300 per minute.")],
  c(27, 29, 31)),

Q("Atrial flutter", IOG, "count flutter waves",
  "A 67-year-old man's flutter ratio is unclear. How are the flutter waves counted?",
  ("Count troughs to the next QRS",
   "Correct. Draw a line through the peaks of the flutter waves and count the troughs until the next QRS complex; that number sets the ratio."),
  [("Count QRS complexes for six seconds",
    "That gives the ventricular rate, not the flutter ratio; the ratio comes from counting troughs between QRS complexes."),
   ("Measure the PR interval",
    "Flutter has no PR interval, because there are no P waves; count the flutter-wave troughs to the next QRS."),
   ("Divide 300 by the boxes",
    "That is the 300 rate method; the flutter ratio comes from counting troughs between QRS complexes.")],
  c(26, 27)),

Q("Atrial flutter", IOH, "flutter mechanism",
  "A 58-year-old woman develops atrial flutter. What produces the rapid atrial rate?",
  ("A reentry circuit",
   "Correct. Atrial flutter is a rapid atrial rate caused by a reentry circuit, most often in the right atrium."),
  [("Multiple chaotic foci",
    "Many chaotic atrial sites firing at once produce atrial fibrillation; flutter is a single reentry circuit."),
   ("Three competing foci",
    "Three or more competing atrial sites are a wandering pacemaker or multifocal atrial tachycardia; flutter is reentry."),
   ("A failing sinus node",
    "A failing sinus node leads to escape rhythms; flutter's rapid atrial rate comes from a reentry circuit.")],
  c(23)),

Q("Atrial flutter", IOH, "flutter location",
  "A 62-year-old man's flutter circuit is mapped. Where does it most often run?",
  ("The right atrium",
   "Correct. The reentry circuit of atrial flutter most often occurs in the right atrium."),
  [("The left atrium",
    "The left atrium can be involved, but flutter's reentry circuit most often runs in the right atrium."),
   ("The atrioventricular node",
    "A reentry circuit over the slow and fast pathways near the node is atrioventricular nodal reentrant tachycardia; flutter runs in the right atrium."),
   ("The left ventricle",
    "Flutter is an atrial rhythm; its reentry circuit is in the right atrium, not the ventricles.")],
  c(23)),

Q("Atrial flutter", IOH, "flutter substrate",
  "A 76-year-old woman has atrial flutter. Which atrial change sets up its circuit?",
  ("Enlarged or scarred atrial tissue",
   "Correct. The flutter reentry circuit is caused by chamber enlargement or by scarred or ischemic tissue."),
  [("A hypersensitive sinus node",
    "Sinus node problems give sinus pauses, arrest or exit block; flutter arises from enlarged, scarred or ischemic atrium."),
   ("An extra internodal tract",
    "The internodal tracts are normal anatomy; flutter's circuit is set up by enlarged, scarred or ischemic tissue."),
   ("High vagal tone",
    "Vagal tone changes the sinus rate, as in sinus arrhythmia; flutter comes from enlarged or scarred atrial tissue.")],
  c(23)),

# ------------------------------------------------------------ atrial fibrillation
Q("Atrial fibrillation", IOF, "name fibrillation",
  "A 78-year-old man's strip is shown. What is the rhythm?",
  ("Atrial fibrillation",
   "Correct. Narrow complexes at irregularly irregular intervals over a disorganized baseline with no P waves (fibrillatory waves only) is atrial fibrillation."),
  [("Atrial flutter",
    "Flutter shows an organized sawtooth baseline; this baseline is chaotic and the spacing unpredictable."),
   ("Multifocal atrial tachycardia",
    "Multifocal atrial tachycardia is irregular too, but has distinct P waves of three shapes; here there are none."),
   ("Sinus arrhythmia",
    "Sinus arrhythmia keeps a normal P wave before every QRS; here no P waves can be found.")],
  c(32, 33, 34, 35), img="l12-s034-atrial-fibrillation.jpg", alt=AF_ALT, slide=34),

Q("Atrial fibrillation", IOF, "name fibrillation b",
  "An 81-year-old woman's strip is shown. What is the rhythm?",
  ("Atrial fibrillation",
   "Correct. The R to R intervals never repeat (irregularly irregular), there are no P waves, and the atrial rate cannot be determined: atrial fibrillation."),
  [("Wandering atrial pacemaker",
    "A wandering atrial pacemaker is irregular but has distinct P waves of three shapes married to the QRS; here there are none."),
   ("Atrial flutter, variable",
    "Flutter with variable conduction is irregular, but its baseline is an organized sawtooth; this one is not."),
   ("Sinus exit block",
    "Sinus exit block is a sinus rhythm with dropped cycles and normal P waves; here P waves are absent.")],
  c(33, 36, 37), img="l12-s036-atrial-fibrillation-b.jpg", alt=AF2_ALT, slide=36),

Q("Atrial fibrillation", IOG, "irregularly irregular",
  "A 73-year-old man's rhythm is described as irregularly irregular. Which rhythm does that phrase describe?",
  ("Atrial fibrillation",
   "Correct. Atrial fibrillation is irregularly irregular: chaotic atrial activity gives the atrioventricular node no pattern to follow."),
  [("Atrial flutter",
    "Flutter is regular at a fixed ratio or irregular with variable conduction, but its sawtooth stays organized."),
   ("Sinus arrhythmia",
    "Sinus arrhythmia varies regularly with breathing, with a P wave before every beat."),
   ("Junctional rhythm",
    "Junctional rhythms are regular by definition; an irregular spot means a premature beat.")],
  c(33)),

Q("Atrial fibrillation", IOG, "f waves",
  "A 70-year-old woman's strip shows no P waves in atrial fibrillation. What replaces them?",
  ("Fibrillatory waves",
   "Correct. Atrial fibrillation has no P waves; fibrillatory (f) waves are present instead, and the atrial rate is indeterminate."),
  [("Flutter waves",
    "Flutter waves form the organized sawtooth of atrial flutter; fibrillation shows disorganized fibrillatory waves."),
   ("Inverted P waves",
    "Inverted P waves come from a junctional impulse; fibrillation has fibrillatory waves instead of P waves."),
   ("Retrograde P waves",
    "Retrograde P waves follow the QRS in junctional beats and reentry tachycardia; fibrillation shows fibrillatory waves.")],
  c(33, 35, 37)),

Q("Atrial fibrillation", IOH, "fibrillation mechanism",
  "A 76-year-old man develops atrial fibrillation. What is happening in his atria?",
  ("Many sites fire chaotically",
   "Correct. Atrial fibrillation is irregular electrical activity of multiple sites within the atria, which suppresses the sinoatrial node."),
  [("One reentry loop circulates",
    "A single reentry circuit, usually in the right atrium, is atrial flutter; fibrillation is many sites firing chaotically."),
   ("Three foci take turns",
    "Three competing foci with distinct P waves is a wandering pacemaker or multifocal atrial tachycardia."),
   ("The sinus node fires faster",
    "In fibrillation the sinus node is suppressed, not speeded up; chaotic atrial sites take over.")],
  c(32)),

Q("Atrial fibrillation", IOH, "atrial kick",
  "A 79-year-old woman's atria are fibrillating. What does she lose?",
  ("The atrial kick",
   "Correct. In atrial fibrillation the atria quiver rather than contract, so the atrial kick (contraction) is lost; most ventricular filling is passive and continues."),
  [("All ventricular filling",
    "Seventy to 80 percent of ventricular filling is passive and continues; what is lost is the atrial kick."),
   ("Ventricular contraction",
    "The ventricles still contract, at an irregular rate; what fibrillating atria lose is their own kick."),
   ("Atrioventricular conduction",
    "Impulses still reach the ventricles irregularly through the node; the lost function is the atrial kick.")],
  c(32)),

Q("Atrial fibrillation", IOG, "flutter vs fibrillation",
  "A 74-year-old man has an irregular atrial rhythm. Which finding favors atrial flutter over atrial fibrillation?",
  ("Organized sawtooth waves",
   "Correct. Flutter's waves are organized into a sawtooth, at an atrial rate of about 300; fibrillation has chaotic fibrillatory waves and an indeterminate atrial rate."),
  [("An irregular R to R",
    "Both can be irregular (flutter with variable conduction); the organized sawtooth is the flutter finding."),
   ("Narrow QRS complexes",
    "Both are supraventricular and usually narrow; only flutter has the sawtooth baseline."),
   ("No visible P waves",
    "Neither has true P waves; flutter's organized sawtooth sets it apart.")],
  c(24, 27, 33)),

# ------------------------------------------------------------ atrioventricular nodal reentrant tachycardia (supraventricular tachycardia)
Q("Reentry tachycardia", IOF, "name SVT",
  "A 28-year-old woman has sudden palpitations; her rate is 200 per minute (normal 60 to 100). What is the rhythm on her strip?",
  ("Nodal reentry tachycardia",
   "Correct. A regular, narrow-complex tachycardia with no visible P waves at 150 to 300 per minute is atrioventricular nodal reentrant tachycardia, the most common paroxysmal supraventricular tachycardia (often simply called supraventricular tachycardia)."),
  [("Sinus tachycardia",
    "Sinus tachycardia shows a distinct upright P wave before each QRS; here no separate P wave can be picked out between the complexes."),
   ("Multifocal atrial tachycardia",
    "Multifocal atrial tachycardia is irregular with P waves of three shapes; this rhythm is perfectly regular."),
   ("Atrial fibrillation",
    "Atrial fibrillation is irregularly irregular; these complexes are evenly spaced.")],
  c(38, 40, 41, 42), img="l12-s041-atrioventricular-nodal-reentrant-tachycardia.jpg", alt=NR_ALT, slide=41),

Q("Reentry tachycardia", IOF, "name SVT b",
  "A 34-year-old man's rate is 160 per minute (normal 60 to 100); his strip is shown. What is the rhythm?",
  ("Nodal reentry tachycardia",
   "Correct. A regular narrow-complex tachycardia over 150 per minute with retrograde P waves after the QRS (an RP interval rather than a PR) is atrioventricular nodal reentrant tachycardia, the most common paroxysmal supraventricular tachycardia."),
  [("Atrial fibrillation",
    "Atrial fibrillation is irregularly irregular with no P waves; this tachycardia is perfectly regular with a notch after each QRS."),
   ("Multifocal atrial tachycardia",
    "Multifocal atrial tachycardia is irregular with P waves of three shapes; this rhythm is regular with one notch after each QRS."),
   ("Atrial flutter",
    "Flutter shows a sawtooth of flutter waves between complexes; here only a small notch follows each QRS.")],
  c(40, 43, 44), img="l12-s043-atrioventricular-nodal-reentrant-tachycardia-b.jpg", alt=NR2_ALT, slide=43),

Q("Reentry tachycardia", IOG, "SVT criteria",
  "A 31-year-old woman has a rapid rhythm. Which combination defines atrioventricular nodal reentrant tachycardia?",
  ("Regular, narrow, no visible P",
   "Correct. Atrioventricular nodal reentrant tachycardia is regular and narrow at 150 to 300 per minute, with P waves not visible or retrograde."),
  [("Irregular, narrow, no P waves",
    "Irregular and narrow without P waves describes atrial fibrillation."),
   ("Regular, wide, no P waves",
    "A regular wide rhythm without P waves is ventricular, such as idioventricular rhythm; the reentry tachycardia is narrow."),
   ("Regular, narrow, sawtooth",
    "A sawtooth baseline is atrial flutter; the reentry tachycardia has no visible atrial waves.")],
  c(38, 40)),

Q("Reentry tachycardia", IOG, "rate not rhythm",
  "A 22-year-old marathon runner's rate is 190 per minute (normal 60 to 100), with an upright P wave before every QRS. What is the rhythm?",
  ("Sinus tachycardia",
   "Correct. The rate does not determine the rhythm: normal P waves married to every QRS make it sinus, so this is sinus tachycardia, even at 190."),
  [("Nodal reentry tachycardia",
    "Nodal reentry tachycardia, the rhythm usually called supraventricular tachycardia, has no visible P waves (or retrograde ones); upright P before each QRS is sinus."),
   ("Multifocal atrial tachycardia",
    "Multifocal atrial tachycardia needs P waves of three shapes and is irregular; one upright P shape is sinus."),
   ("Junctional tachycardia",
    "Junctional tachycardia has inverted, hidden or retrograde P waves; an upright P before each QRS is sinus.")],
  c(40)),

Q("Reentry tachycardia", IOH, "SVT trigger",
  "A 26-year-old woman's strip is shown; her rate jumps abruptly from about 100 to about 200 per minute (normal 60 to 100). What kind of beat usually sets off this reentry tachycardia?",
  ("A premature atrial complex",
   "Correct. Atrioventricular nodal reentrant tachycardia is usually set off by an ectopic beat, typically a premature atrial complex near the fast or slow tract."),
  [("A ventricular escape beat",
    "An escape beat arrives late after nodal failure; the reentry tachycardia is usually started by an early atrial ectopic beat."),
   ("A dropped sinus cycle",
    "A dropped cycle is sinus exit block; a narrow-complex reentry tachycardia usually starts with a premature atrial complex."),
   ("A junctional escape beat",
    "Junctional escape beats come late after the sinus node fails; the usual trigger is an early atrial beat.")],
  c(38), img="l12-s038-reentry-tachycardia-onset.png",
  alt="Pink grid strip labeled 100 bpm on the left and 200 bpm on the right; regular narrow complexes abruptly become twice as frequent.", slide=38),

Q("Reentry tachycardia", IOH, "typical circuit",
  "A 30-year-old man has typical atrioventricular nodal reentrant tachycardia. How does the circuit travel?",
  ("Down the slow tract, up the fast",
   "Correct. In the typical form the circuit travels counterclockwise down the slow tract and up the fast tract; P waves are absent or buried at the end of the QRS."),
  [("Down the fast tract, up the slow",
    "Down the fast and up the slow is the atypical form, in which retrograde P waves are clearly visible."),
   ("Around the right atrium",
    "A circuit around the right atrium is atrial flutter, which produces a sawtooth baseline."),
   ("Through Bachmann's bundle",
    "Bachmann's bundle carries impulses between the atria; the reentry circuit uses the slow and fast tracts.")],
  c(39)),

Q("Reentry tachycardia", IOH, "atypical",
  "A 38-year-old woman has the atypical form of atrioventricular nodal reentrant tachycardia. What does her strip show?",
  ("Clearly visible retrograde P waves",
   "Correct. In the atypical form the circuit runs down the fast tract and up the slow, so retrograde P waves are clearly visible, with an RP interval rather than a PR."),
  [("A sawtooth baseline",
    "A sawtooth baseline belongs to atrial flutter, a right atrial reentry circuit; the atypical nodal form shows retrograde P waves."),
   ("Upright P waves before QRS",
    "Upright P waves before each QRS mean a sinus or atrial origin; the atypical form shows retrograde P waves."),
   ("Wide, bizarre QRS complexes",
    "The reentry tachycardia is narrow; the atypical form differs only in its clearly visible retrograde P waves.")],
  c(39)),

Q("Reentry tachycardia", IOG, "pseudo S",
  "A 33-year-old man's regular narrow tachycardia is shown; the highlighted notch ends each QRS. What is the notch?",
  ("A buried retrograde P wave",
   "Correct. In the typical form, retrograde P waves are buried at the end of the QRS complex; these are called pseudo S waves."),
  [("A true S wave",
    "A true S wave is part of ventricular depolarization; this notch is a retrograde P wave buried at the end of the QRS."),
   ("A flutter wave",
    "Flutter waves form a continuous sawtooth between complexes; here a single notch ends each QRS."),
   ("A fibrillatory wave",
    "Fibrillatory waves are chaotic baseline activity in atrial fibrillation, not a repeating notch on a regular rhythm.")],
  c(39), img="l12-s039-pseudo-s-waves.png",
  alt="Rhythm strip of tall, evenly spaced narrow complexes; a yellow circle highlights the small notch at the end of each one.", slide=39),

Q("Reentry tachycardia", IOH, "circuit pathways",
  "A 29-year-old woman is told she has a reentry tachycardia that uses two conduction pathways. Which two?",
  ("A slow tract and a fast tract",
   "Correct. The reentry circuit of atrioventricular nodal reentrant tachycardia runs over the slow (inferior posterior) and fast (superior anterior) tracts."),
  [("The two bundle branches",
    "The bundle branches carry the impulse into the ventricles; the reentry circuit uses the slow and fast tracts."),
   ("Bachmann's bundle and the His",
    "Bachmann's bundle links the atria and the His bundle leads to the ventricles; the circuit uses the slow and fast tracts."),
   ("Two Purkinje fascicles",
    "The Purkinje network lies in the ventricles; this narrow reentry tachycardia circulates over the slow and fast tracts.")],
  c(38, 39)),

Q("Reentry tachycardia", IOG, "SVT vs flutter 2:1",
  "A 59-year-old man has a regular narrow tachycardia at 150 per minute (normal 60 to 100). Which finding would make it atrial flutter rather than the reentry tachycardia?",
  ("Sawtooth flutter waves",
   "Correct. Atrial flutter (often 2:1, about 150 per minute) shows sawtooth flutter waves; the reentry tachycardia has no visible P waves or only retrograde ones."),
  [("No visible P waves",
    "No visible P waves fits the reentry tachycardia, not flutter."),
   ("A regular R to R",
    "Both rhythms can be regular; the sawtooth flutter waves are what identify flutter."),
   ("A narrow QRS",
    "Both are supraventricular and narrow; the sawtooth identifies flutter.")],
  c(24, 27, 40)),
]
