# -*- coding: utf-8 -*-
# PDM I Lecture 6 (Urinalysis, Prof. Stacie Gopal) -- pool B.
# The chemistry pads: pH, leukocyte esterase, nitrites, ketones, glucose.
# Syllabus objective a.
#
# Where Gopal weighted the material out loud (1 September recording):
#   23:11  "Leukocyte esterase indicates pyuria. That's the take-home point."
#   23:30  "Please make sure you call it nitrites and not nitrates."
#   24:06  Escherichia coli is the commonest cause of urinary tract infection
#          AND is not urease-positive, so a negative nitrite does not exclude
#          one. This is the single most emphasised idea in the lecture.
#
# Correct answer is ALWAYS written first (c=0); the partition script rotates.
SRC = "6. Urinalysis Diagnostics SV Gopal Fall 2026.pptx"
def c(n):  return f"{SRC}, Slide {n}"
def au(t): return f"Lecture recording, 1 September 2026, {t}"

IOA = "a — Describe the following urinalysis parameters"

POOL_B = [
 dict(topic="pH", io=IOA, slot="mechanism",
   q="What does the urine pH reflect?",
   opts=[
     ["The renal tubules' ability to hold the hydrogen ion concentration steady",
      "Correct — it reports tubular handling of hydrogen ions."],
     ["The rate at which the glomerulus filters plasma",
      "Filtration rate is a separate measure from urine pH."],
     ["The concentration of protein crossing the glomerulus",
      "Protein is measured on its own pad."],
     ["The total volume of urine produced each day",
      "Volume is not what the pH pad reports."]],
   c=0, cite=c(16)),

 dict(topic="pH", io=IOA, slot="mechanism",
   q="By which two processes do the kidneys mainly maintain pH balance?",
   opts=[
     ["Excreting hydrogen ions such as ammonium, and reabsorbing and producing bicarbonate",
      "Correct — acid out, bicarbonate kept and made."],
     ["Excreting bicarbonate and reabsorbing hydrogen ions",
      "That reverses both halves."],
     ["Excreting potassium and reabsorbing sodium",
      "Those move to balance electrolytes rather than pH."],
     ["Excreting urea and reabsorbing creatinine",
      "Neither is a route for acid-base control."]],
   c=0, cite=c(16)),

 dict(topic="pH", io=IOA, slot="interpretation",
   q="Which four things alter the urine pH?",
   opts=[
     ["Diet, medications, systemic acid-base disorders, and renal tubular function",
      "Correct — all four shift it."],
     ["Only the systemic acid-base status",
      "Diet, drugs, and tubular function shift it too."],
     ["Only the time of day the sample was collected",
      "Timing is not among the influences on pH."],
     ["Only the patient's age",
      "Age is not what moves the urine pH."]],
   c=0, cite=c(16)),

 dict(topic="pH", io=IOA, slot="interpretation",
   q="A patient with a urinary tract infection has persistently alkaline urine. Which organisms does that suggest?",
   opts=[
     ["Urea-splitting organisms such as Proteus, Klebsiella, or Pseudomonas",
      "Correct — splitting urea raises the pH."],
     ["Escherichia coli",
      "Escherichia coli is associated with acidic urine instead."],
     ["Candida species",
      "Yeast is not what drives the urine alkaline here."],
     ["Lactobacillus species",
      "These are commensal organisms rather than a cause of alkaline urine."]],
   c=0, cite=c(17)),

 dict(topic="pH", io=IOA, slot="interpretation",
   q="Which of these produces acidic urine?",
   opts=[
     ["Ketoacidosis",
      "Correct — ketoacidosis drives the urine acidic."],
     ["Renal tubular acidosis",
      "Despite the name, this one gives alkaline urine."],
     ["Metabolic alkalosis",
      "Alkalosis pushes the urine alkaline."],
     ["A diet high in fruit and vegetables",
      "That diet alkalinises the urine."]],
   c=0, cite=c(17)),

 dict(topic="pH", io=IOA, slot="interpretation",
   q="A diet high in meat has which effect on the urine?",
   opts=[
     ["It makes the urine acidic",
      "Correct — meat acidifies the urine."],
     ["It makes the urine alkaline",
      "Fruit and vegetables do that, not meat."],
     ["It has no effect on the urine pH",
      "Diet is one of the recognised influences."],
     ["It raises the specific gravity without changing the pH",
      "The pH does shift with a meat-heavy diet."]],
   c=0, cite=c(17)),

 dict(topic="pH and stones", io=IOA, slot="interpretation",
   q="Which stones form in acidic urine?",
   opts=[
     ["Calcium oxalate and uric acid",
      "Correct — both are associated with acidic urine."],
     ["Triple phosphate and struvite",
      "Those form in alkaline urine."],
     ["Cystine and xanthine only",
      "Neither is the pairing associated with acidic urine here."],
     ["Stones do not vary with the urine pH",
      "The pH is used to assess and treat stone disease precisely because it does."]],
   c=0, cite=c(18)),

 dict(topic="pH and stones", io=IOA, slot="treatment",
   q="A patient forms uric acid stones. Which change to the urine is the aim of treatment?",
   opts=[
     ["Make the urine more alkaline",
      "Correct — alkalinising the urine is the management for uric acid stones."],
     ["Make the urine more acidic",
      "Acid urine is what favours these stones forming."],
     ["Leave the pH alone and restrict fluid",
      "Restricting fluid would concentrate the urine and worsen matters."],
     ["Make the urine more alkaline only if an infection is present",
      "Alkalinisation is the management here regardless of infection."]],
   c=0, cite=c(18)),

 dict(topic="pH and stones", io=IOA, slot="treatment",
   q="Struvite stones have formed in alkaline urine. What does treatment target?",
   opts=[
     ["The urinary tract infection, since urease-producing bacteria drive them",
      "Correct — treating the infection addresses the cause."],
     ["Acidification of the urine with a high-fruit diet",
      "Fruit alkalinises the urine, which is the wrong direction and not the target."],
     ["Long-term alkalinisation of the urine",
      "Alkaline urine is what these stones form in."],
     ["Fluid restriction to reduce stone volume",
      "Restricting fluid concentrates the urine and does not treat the cause."]],
   c=0, cite=c(18)),

 dict(topic="Leukocyte esterase", io=IOA, slot="mechanism",
   q="How does the leukocyte esterase pad detect white cells?",
   opts=[
     ["It detects the esterase those cells release into the urine",
      "Correct — the enzyme is what the pad reacts to."],
     ["It counts intact white cells directly on the pad",
      "Counting cells needs microscopy."],
     ["It detects antibodies produced against the infecting organism",
      "The pad detects an enzyme, not antibodies."],
     ["It detects the nitrites those cells produce",
      "Nitrites come from bacteria and have their own pad."]],
   c=0, cite=c(19)),

 dict(topic="Leukocyte esterase", io=IOA, slot="interpretation",
   q="A leukocyte esterase result is positive. What does that indicate?",
   opts=[
     ["Pyuria — white cells in the urine",
      "Correct — that is the take-home meaning of a positive pad."],
     ["Bacteriuria, confirmed",
      "Bacteria need a culture to confirm."],
     ["Hematuria",
      "Blood has its own pad."],
     ["Glomerular protein loss",
      "Protein loss is read from the protein pad."]],
   c=0, cite=au("23:11")),

 dict(topic="Leukocyte esterase", io=IOA, slot="next step",
   q="A symptomatic patient has a positive leukocyte esterase. What comes next?",
   opts=[
     ["Urine culture and sensitivity",
      "Correct — culture and sensitivity follow."],
     ["Start treatment and do not culture",
      "Culture still guides which agent will work."],
     ["Repeat the dipstick in one week",
      "Delay does nothing for a symptomatic patient."],
     ["Order renal ultrasound first",
      "Imaging is not the next step for a suspected simple infection."]],
   c=0, cite=c(19)),

 dict(topic="Leukocyte esterase", io=IOA, slot="limitation",
   q="A patient has symptoms of a urinary tract infection but the leukocyte esterase is negative. What follows?",
   opts=[
     ["Still send a urine culture and sensitivity, since a negative does not exclude infection",
      "Correct — a negative pad does not rule the infection out."],
     ["Infection is excluded and no culture is needed",
      "A negative result does not exclude it."],
     ["Repeat the dipstick before doing anything else",
      "Repeating the same test adds nothing here."],
     ["Treat empirically without culture, since the pad is negative",
      "A negative pad is not a reason to skip the culture."]],
   c=0, cite=c(19)),

 dict(topic="Leukocyte esterase", io=IOA, slot="interpretation",
   q="Besides urinary tract infection, which conditions can turn the leukocyte esterase positive?",
   opts=[
     ["Interstitial cystitis and glomerulonephritis",
      "Correct — both are inflammatory and can produce pyuria."],
     ["Diabetes insipidus and dehydration",
      "Neither produces white cells in the urine."],
     ["Rhabdomyolysis and muscle injury",
      "Those give a positive blood pad through myoglobin."],
     ["Multiple myeloma and amyloidosis",
      "Those show up as protein rather than as pyuria."]],
   c=0, cite=c(19)),

 dict(topic="Nitrites", io=IOA, slot="mechanism",
   q="How do nitrites come to appear in urine?",
   opts=[
     ["Urease-producing bacteria reduce urinary nitrates to nitrites",
      "Correct — bacterial reductase performs the conversion."],
     ["White cells release them as they degranulate",
      "White cells release esterase, which is a different pad."],
     ["The renal tubules secrete them when acidotic",
      "The tubules do not secrete nitrites."],
     ["They are filtered unchanged from the plasma",
      "They are generated in the urine by bacteria."]],
   c=0, cite=c(20)),

 dict(topic="Nitrites", io=IOA, slot="limitation",
   q="How long must urine sit in the bladder between voids for nitrites to be detectable?",
   opts=[
     ["More than four hours",
      "Correct — the conversion needs that long."],
     ["About thirty minutes",
      "That is far too short for the conversion."],
     ["About one hour",
      "Still short of the interval the conversion needs."],
     ["A full twenty-four hours",
      "Longer than required, and not how the test is used."]],
   c=0, cite=c(20)),

 dict(topic="Nitrites", io=IOA, slot="limitation",
   q="Why does a negative nitrite result fail to exclude a urinary tract infection?",
   opts=[
     ["Escherichia coli causes most infections and is rarely urease-positive",
      "Correct — the commonest organism does not turn the pad positive."],
     ["The pad only works on a first-morning specimen",
      "Timing between voids matters, but the organism is the reason here."],
     ["Nitrites are destroyed by refrigeration",
      "Refrigeration is not what limits this pad."],
     ["The pad cannot detect nitrites below body temperature",
      "Temperature is not the limitation."]],
   c=0, cite=au("24:06")),

 dict(topic="Nitrites", io=IOA, slot="limitation",
   q="How does nitrite sensitivity compare with leukocyte esterase for detecting a urinary tract infection?",
   opts=[
     ["Nitrites are the less sensitive of the two",
      "Correct — leukocyte esterase picks up more infections."],
     ["Nitrites are the more sensitive of the two",
      "That reverses the comparison."],
     ["The two have identical sensitivity",
      "They differ, which is why both pads are read."],
     ["Sensitivity cannot be compared between the two pads",
      "They are directly compared for this purpose."]],
   c=0, cite=c(20)),

 dict(topic="Nitrites", io=IOA, slot="interpretation",
   q="Which organisms are urease-producing and so turn the nitrite pad positive?",
   opts=[
     ["Proteus mirabilis, Klebsiella pneumoniae, and Staphylococcus strains",
      "Correct — these three produce urease."],
     ["Escherichia coli and Enterococcus faecalis",
      "Escherichia coli is rarely urease-positive."],
     ["Candida albicans and Aspergillus species",
      "Yeasts and moulds are not what the pad detects."],
     ["Lactobacillus and Gardnerella species",
      "These raise the question of the urinary microbiome rather than infection."]],
   c=0, cite=c(20)),

 dict(topic="Ketones", io=IOA, slot="mechanism",
   q="What does ketonuria indicate about how cells are producing energy?",
   opts=[
     ["They are metabolising fatty acids instead of glucose",
      "Correct — ketones are the by-product of that switch."],
     ["They are metabolising glucose instead of fatty acids",
      "That is the normal state and produces no ketones."],
     ["They are metabolising protein instead of carbohydrate",
      "Protein breakdown is not what produces ketones."],
     ["They have stopped producing energy altogether",
      "Ketones mark a change of fuel rather than a halt."]],
   c=0, cite=c(21)),

 dict(topic="Ketones", io=IOA, slot="mechanism",
   q="Where are ketones formed, and what normally happens to them?",
   opts=[
     ["Formed in the liver and normally metabolised completely",
      "Correct — which is why only a negligible amount reaches the urine."],
     ["Formed in the kidney and normally excreted unchanged",
      "The liver forms them, and they are normally used up."],
     ["Formed in muscle and normally stored there",
      "Muscle is not where ketones are formed."],
     ["Formed in the pancreas and normally reabsorbed",
      "The pancreas does not form ketones."]],
   c=0, cite=c(21)),

 dict(topic="Ketones", io=IOA, slot="interpretation",
   q="Which of these produces ketonuria?",
   opts=[
     ["A high-fat, low-carbohydrate diet",
      "Correct — special diets of this kind produce ketones."],
     ["A diet high in fruit and vegetables",
      "That alkalinises the urine rather than producing ketones."],
     ["Overhydration",
      "Overhydration dilutes the urine without producing ketones."],
     ["Recent contrast administration",
      "Contrast raises the specific gravity rather than producing ketones."]],
   c=0, cite=c(21)),

 dict(topic="Ketones", io=IOA, slot="interpretation",
   q="Ketones are found in the urine of a febrile infant. How should that be read?",
   opts=[
     ["Febrile illness in infants and children is a recognised cause",
      "Correct — fever in the young is on the list."],
     ["It is diagnostic of type 1 diabetes mellitus",
      "Ketones alone do not diagnose diabetes."],
     ["It indicates a urinary tract infection",
      "Infection shows on the leukocyte esterase and nitrite pads."],
     ["It is always a laboratory error in children",
      "It is a genuine finding in a febrile child."]],
   c=0, cite=c(21)),

 dict(topic="Ketones", io=IOA, slot="next step",
   q="Ketones are found on a dipstick. Which analyte should be checked alongside them?",
   opts=[
     ["Glucose",
      "Correct — ketones prompt looking at the glucose."],
     ["Bilirubin",
      "Bilirubin answers a hepatic question rather than this one."],
     ["Nitrites",
      "Nitrites address infection."],
     ["Specific gravity",
      "Concentration does not explain the ketones."]],
   c=0, cite=au("26:50")),

 dict(topic="Glucose", io=IOA, slot="mechanism",
   q="Why is there normally no glucose in urine?",
   opts=[
     ["All filtered glucose is reabsorbed in the proximal tubules",
      "Correct — reabsorption is complete under normal conditions."],
     ["Glucose is too large to cross the glomerulus",
      "Glucose is filtered freely; it is then reabsorbed."],
     ["Glucose is broken down by tubular enzymes",
      "It is reabsorbed intact rather than digested."],
     ["Glucose is bound to albumin and retained in plasma",
      "Glucose circulates unbound."]],
   c=0, cite=c(22)),

 dict(topic="Glucose", io=IOA, slot="mechanism",
   q="What is the tubular threshold?",
   opts=[
     ["The blood glucose above which the tubules can no longer reabsorb it all",
      "Correct — beyond it, glucose spills into the urine."],
     ["The urine glucose above which diabetes is diagnosed",
      "Glucosuria alone does not diagnose diabetes."],
     ["The pressure at which the glomerulus stops filtering",
      "The threshold concerns reabsorption, not filtration pressure."],
     ["The lowest specific gravity the kidney can produce",
      "That is a different measure of concentrating ability."]],
   c=0, cite=c(22)),

 dict(topic="Glucose", io=IOA, slot="limitation",
   q="Glucose is found on a dipstick. Why is that not diagnostic on its own?",
   opts=[
     ["The tubular threshold varies between individuals",
      "Correct — the threshold is not the same in everyone."],
     ["The pad cross-reacts with ketones",
      "The pads are independent of one another."],
     ["Glucose is normally present in small amounts",
      "Glucose should read negative normally."],
     ["The result depends on how long the urine sat in the bladder",
      "That interval matters for nitrites, not for glucose."]],
   c=0, cite=c(22)),

 dict(topic="Glucose", io=IOA, slot="interpretation",
   q="A pregnant patient has trace glucose in the urine. How should that be interpreted?",
   opts=[
     ["It can be normal in pregnancy, from a reduced tubular threshold",
      "Correct — the threshold falls in pregnancy."],
     ["It establishes gestational diabetes",
      "A trace finding does not establish the diagnosis."],
     ["It indicates a urinary tract infection",
      "Infection shows on different pads."],
     ["It always indicates a laboratory error",
      "It is a recognised normal finding in pregnancy."]],
   c=0, cite=c(22)),

 dict(topic="Glucose", io=IOA, slot="interpretation",
   q="Which of these can produce glucosuria even when the serum glucose is within normal limits?",
   opts=[
     ["Renal disease that impairs tubular reabsorption",
      "Correct — the leak is tubular rather than a high blood level."],
     ["Dehydration",
      "Dehydration concentrates the urine without spilling glucose."],
     ["A urinary tract infection with Escherichia coli",
      "Infection does not itself spill glucose."],
     ["A diet high in meat",
      "Meat shifts the pH rather than causing glucosuria."]],
   c=0, cite=c(22)),

 dict(topic="Glucose", io=IOA, slot="interpretation",
   q="A patient receiving intravenous fluids containing dextrose has glucose in the urine. How is that read?",
   opts=[
     ["It is expected in a patient receiving dextrose",
      "Correct — this is a recognised and normal explanation."],
     ["It confirms undiagnosed diabetes mellitus",
      "The dextrose infusion explains it."],
     ["It indicates the fluids should be stopped",
      "The finding is expected rather than a reason to stop."],
     ["It indicates renal tubular damage",
      "The infused dextrose is the simpler explanation."]],
   c=0, cite=c(22)),
]
