# -*- coding: utf-8 -*-
"""New Pharmacology Exam 1 questions, Lecture 1 part A: beta-lactams and vancomycin.

Written for the second set of five master exams. Every item is new -- none
duplicates a stem already in the topic quizzes or vignettes. The correct answer
is authored at index 0 throughout; apply_pharm_v3_rotation.py moves it to a
rotating position afterwards so no authoring habit can bias the key.
"""
D = "Antibiotics, Antivirals, and Antifungals.pptx, Slide %d"

QUESTIONS = [
 dict(topic="Penicillins", io="4a — Penicillins", cite=D % 17,
  q="Penicillin G is the drug of choice for which infections?",
  opts=[["Syphilis, gas gangrene and meningococcus", "Correct. It has good Gram-positive coccal activity but no Staphylococcus coverage."],
        ["Diabetic foot, animal bites and cellulitis", "Those go to ampicillin/sulbactam instead."],
        ["Nosocomial pneumonia and intra-abdominal sepsis", "Those belong to piperacillin/tazobactam."],
        ["Methicillin-resistant Staphylococcus aureus bacteraemia", "Vancomycin is the treatment of choice there."]]),

 dict(topic="Penicillins", io="4a — Penicillins", cite=D % 17,
  q="What is missing from the natural penicillin spectrum?",
  opts=[["Staphylococcus and aerobic Gram-negative organisms", "Correct. Anaerobic activity is present, except against Bacteroides."],
        ["Anaerobes of every kind, including Bacteroides", "Anaerobic activity is present apart from Bacteroides."],
        ["Gram-positive cocci, which need a broader agent", "Gram-positive coccal activity is the strength of this group."],
        ["Streptococci, which require a cephalosporin", "Streptococcal coverage is retained."]]),

 dict(topic="Penicillins", io="4a — Penicillins", cite=D % 18,
  q="Which penicillin form is given as a single long-acting intramuscular dose?",
  opts=[["Penicillin G benzathine, marketed as Bicillin", "Correct. The benzathine salt is what makes the one-time dose possible."],
        ["Penicillin V potassium, marketed as Pen VK", "That is the oral form, stable in stomach acid."],
        ["Penicillin G given as benzylpenicillin", "That form is given intravenously."],
        ["Amoxicillin, marketed as Amoxil", "Amoxicillin is oral only."]]),

 dict(topic="Penicillins", io="4a — Penicillins", cite=D % 18,
  q="Why is penicillin V potassium the oral choice?",
  opts=[["It is stable in stomach acid", "Correct. Penicillin G is given intravenously instead."],
        ["It has a much longer half-life", "Duration is what the benzathine salt provides."],
        ["It penetrates the central nervous system", "That is not the property that makes it oral."],
        ["It avoids first-pass hepatic metabolism", "Acid stability is the stated reason."]]),

 dict(topic="Penicillins", io="4a — Penicillins", cite=D % 19,
  q="Aminopenicillins are the drug of choice for which organisms?",
  opts=[["Enterococcus and Listeria", "Correct, along with endocarditis prophylaxis and upper respiratory infection."],
        ["Pseudomonas and Serratia", "Antipseudomonal penicillins are needed for those."],
        ["Bacteroides and Clostridium", "Anaerobic cover is limited and excludes Bacteroides."],
        ["Staphylococcus and Streptococcus", "There is no Staphylococcus coverage in this group."]]),

 dict(topic="Penicillins", io="4a — Penicillins", cite=D % 19,
  q="Which aminopenicillin can only be given by mouth?",
  opts=[["Amoxicillin", "Correct. Ampicillin can be given intravenously or orally."],
        ["Ampicillin", "Ampicillin is available intravenously and orally."],
        ["Piperacillin", "Piperacillin is an intravenous antipseudomonal agent."],
        ["Nafcillin", "Nafcillin is given intravenously."]]),

 dict(topic="Penicillins", io="4a — Penicillins", cite=D % 21,
  q="Which severe skin reactions are listed for the aminopenicillins?",
  opts=[["Stevens-Johnson syndrome and toxic epidermal necrolysis", "Correct, alongside interstitial nephritis and Clostridium difficile infection."],
        ["Erythema nodosum and pyoderma gangrenosum", "Neither is among the listed reactions."],
        ["Acanthosis nigricans and necrobiosis lipoidica diabeticorum", "Neither is a penicillin reaction."],
        ["Pemphigus vulgaris and bullous pemphigoid", "Neither appears among these adverse effects."]]),

 dict(topic="Penicillins", io="4a — Penicillins", cite=D % 21,
  q="Which past medical history is a contraindication to aminopenicillins?",
  opts=[["Cholestatic jaundice or hepatic dysfunction", "Correct, in addition to penicillin allergy itself."],
        ["Chronic kidney disease requiring dialysis", "Renal function alters dosing rather than contraindicating."],
        ["Poorly controlled diabetes mellitus", "Diabetes is not given as a contraindication."],
        ["Previous Clostridium difficile infection", "That is a listed adverse effect, not a contraindication."]]),

 dict(topic="Penicillins", io="4a — Penicillins", cite=D % 22,
  q="What should be monitored during penicillin therapy?",
  opts=[["Renal and hepatic function, and platelets", "Correct. Renal function also drives how often the drug is given."],
        ["Serum drug troughs before the fourth dose", "That monitoring belongs to vancomycin."],
        ["Creatine phosphokinase and muscle pain", "That is daptomycin monitoring."],
        ["Visual acuity and colour discrimination", "Vision monitoring is a voriconazole concern."]]),

 dict(topic="Penicillins", io="4a — Penicillins", cite=D % 23,
  q="How do bacteria resist penicillin?",
  opts=[["Beta-lactamase cleaves the ring", "Correct. That is why beta-lactamase inhibitors were developed."],
        ["The ribosomal target is methylated", "That is a macrolide resistance route, not this one."],
        ["An efflux pump removes the drug", "The stated mechanism is enzymatic destruction."],
        ["Porin channels close to block entry", "The named mechanism is modification of the antibiotic."]]),

 dict(topic="Penicillins", io="4a — Penicillins", cite=D % 24,
  q="What is true of the beta-lactamase inhibitors themselves?",
  opts=[["They have no antibacterial activity of their own", "Correct. They irreversibly inactivate beta-lactamase."],
        ["They are bactericidal against Gram-negatives", "They carry no antibacterial activity."],
        ["They reversibly slow the enzyme", "The inactivation is irreversible."],
        ["They work by blocking penicillin-binding proteins", "That is what the penicillin itself does."]]),

 dict(topic="Penicillins", io="4a — Penicillins", cite=D % 25,
  q="What does adding a beta-lactamase inhibitor to an aminopenicillin achieve?",
  opts=[["Anaerobic cover including Bacteroides, plus MSSA", "Correct, which is why it suits bites and diabetic foot infection."],
        ["Antipseudomonal activity and Gram-negative reach", "Piperacillin/tazobactam is the antipseudomonal option."],
        ["Coverage of resistant Staphylococcus aureus", "Methicillin-resistant organisms are not covered."],
        ["Central nervous system penetration for meningitis", "Carbapenems are the group noted for that."]]),

 dict(topic="Penicillins", io="4a — Penicillins", cite=D % 25,
  q="Ampicillin/sulbactam is the drug of choice for which problems?",
  opts=[["Skin and soft tissue, diabetic foot, and bites", "Correct. The added Bacteroides cover is what suits bite wounds."],
        ["Syphilis, gas gangrene and meningococcus", "Those belong to penicillin G."],
        ["Neutropenic fever and hospital-acquired pneumonia", "Cefepime is the drug of choice there."],
        ["Endocarditis and osteomyelitis in penicillin allergy", "Vancomycin covers that situation."]]),

 dict(topic="Penicillins", io="4a — Penicillins", cite=D % 26,
  q="What were nafcillin, oxacillin and dicloxacillin designed to cover?",
  opts=[["Methicillin-sensitive Staphylococcus aureus", "Correct, with decreased activity against other organisms as the trade-off."],
        ["Pseudomonas aeruginosa in hospital infection", "The antipseudomonal penicillins do that."],
        ["Enterococcus and Listeria monocytogenes", "Those are aminopenicillin targets."],
        ["Anaerobes including Bacteroides fragilis", "Anaerobic cover is not this group's purpose."]]),

 dict(topic="Penicillins", io="4a — Penicillins", cite=D % 27,
  q="Which Gram-positive organisms does piperacillin/tazobactam retain?",
  opts=[["Methicillin-sensitive Staphylococcus aureus only", "Correct. It adds Gram-negative and antipseudomonal reach."],
        ["Both sensitive and resistant Staphylococcus aureus", "Resistant strains are not covered."],
        ["Enterococcus but not Staphylococcus species", "Staphylococcal cover is what is retained."],
        ["No Gram-positive organisms whatsoever", "Gram-positive cover is maintained."]]),

 dict(topic="Penicillins", io="4a — Penicillins", cite=D % 28,
  q="How is extended-infusion piperacillin/tazobactam given?",
  opts=[["3.375 to 4.5 grams every 8 hours over 4 hours", "Correct. The standard schedule is every 6 hours over 30 minutes."],
        ["3.375 to 4.5 grams every 6 hours over 30 minutes", "That is the standard rather than the extended infusion."],
        ["1 to 2 grams every 8 hours over 30 minutes", "That is closer to a cephalosporin schedule."],
        ["4.5 grams once daily over 60 minutes", "Once-daily dosing is not used here."]]),

 dict(topic="Cephalosporins", io="4b — Cephalosporins", cite=D % 30,
  q="How are the cephalosporins mostly eliminated?",
  opts=[["Renally", "Correct, and they also penetrate cerebrospinal fluid well."],
        ["Hepatically, through bile", "Renal elimination is what is stated."],
        ["By plasma esterases", "That is how succinylcholine is cleared."],
        ["Unchanged through the lungs", "That is not an elimination route here."]]),

 dict(topic="Cephalosporins", io="4b — Cephalosporins", cite=D % 30,
  q="Which cephalosporins carry antipseudomonal activity?",
  opts=[["Ceftazidime, cefepime and ceftolozane", "Correct. Most other cephalosporins lack it."],
        ["Cefazolin, cephalexin and cefprozil", "Those are first and second generation agents without it."],
        ["Ceftriaxone, cefotaxime and cefdinir", "Those third generation agents are not the antipseudomonal ones."],
        ["Ceftaroline, cefoxitin and cefotetan", "None of those carries antipseudomonal activity."]]),

 dict(topic="Cephalosporins", io="4b — Cephalosporins", cite=D % 31,
  q="What happens as cephalosporin generation advances?",
  opts=[["More Gram-negative activity, less Gram-positive", "Correct, except that the fourth generation keeps both."],
        ["More Gram-positive activity, less Gram-negative", "The trade runs the other way."],
        ["Anaerobic activity increases with each step", "Anaerobic cover is not what changes across generations."],
        ["Central nervous system penetration steadily falls", "Penetration is described as good for the class."]]),

 dict(topic="Cephalosporins", io="4b — Cephalosporins", cite=D % 31,
  q="Which cephalosporin generation gains Gram-negative reach without losing Gram-positive?",
  opts=[["Fourth generation", "Correct, which is what separates cefepime from the third generation."],
        ["Second generation", "Second generation sits mid-way in the usual trade-off."],
        ["Third generation", "Third generation loses more Gram-positive coverage."],
        ["First generation", "First generation is the Gram-positive end of the range."]]),

 dict(topic="Cephalosporins", io="4b — Cephalosporins", cite=D % 32,
  q="Which first generation cephalosporin is taken by mouth for cellulitis?",
  opts=[["Cephalexin", "Correct, at 500 milligrams every 6 to 12 hours."],
        ["Cefazolin", "Cefazolin is given intravenously for prophylaxis."],
        ["Cefuroxime", "Cefuroxime is a second generation agent."],
        ["Cefprozil", "Cefprozil is a second generation agent."]]),

 dict(topic="Cephalosporins", io="4b — Cephalosporins", cite=D % 32,
  q="Which organism do the first generation cephalosporins fail to cover?",
  opts=[["Enterococcus", "Correct. They do cover some Escherichia coli, Proteus and Klebsiella."],
        ["Escherichia coli", "Some Escherichia coli coverage is present."],
        ["Proteus species", "Proteus is among the Gram-negatives covered."],
        ["Klebsiella species", "Klebsiella is among the Gram-negatives covered."]]),

 dict(topic="Cephalosporins", io="4b — Cephalosporins", cite=D % 33,
  q="What do the second generation cephalosporins add over the first?",
  opts=[["Haemophilus influenzae, Neisseria and Enterobacter", "Correct, though Enterobacter develops resistance rapidly."],
        ["Pseudomonas aeruginosa and Acinetobacter", "Antipseudomonal activity is not a second generation feature."],
        ["Methicillin-resistant Staphylococcus aureus", "Only ceftaroline carries that."],
        ["Listeria monocytogenes and Enterococcus", "Neither is added at this generation."]]),

 dict(topic="Cephalosporins", io="4b — Cephalosporins", cite=D % 34,
  q="Which cephalosporin needs no dose adjustment in renal impairment?",
  opts=[["Ceftriaxone", "Correct, and it also carries good streptococcal coverage."],
        ["Ceftazidime", "Ceftazidime is dosed every 8 hours with renal considerations."],
        ["Cefepime", "Cefepime requires renal adjustment."],
        ["Ceftaroline", "Ceftaroline must be renally adjusted."]]),

 dict(topic="Cephalosporins", io="4b — Cephalosporins", cite=D % 34,
  q="Which cephalosporin is preferred in neonatal fever and sepsis?",
  opts=[["Cefotaxime", "Correct, because ceftriaxone cannot be used in the first 30 days of life."],
        ["Ceftriaxone", "Ceftriaxone is the one avoided in the first 30 days of life."],
        ["Cefazolin", "Cefazolin is a surgical prophylaxis agent."],
        ["Cefuroxime", "Cefuroxime is not the neonatal preference."]]),

 dict(topic="Cephalosporins", io="4b — Cephalosporins", cite=D % 35,
  q="What is the ceftriaxone dose for meningitis?",
  opts=[["2 grams intravenously every 12 hours", "Correct, against a usual range of 1 to 2 grams every 12 to 24 hours."],
        ["1 gram intravenously every 24 hours", "That sits at the low end of ordinary dosing."],
        ["500 milligrams intravenously every 6 hours", "That is not a ceftriaxone schedule."],
        ["4 grams intravenously every 8 hours", "That exceeds the stated 4 gram daily maximum."]]),

 dict(topic="Cephalosporins", io="4b — Cephalosporins", cite=D % 36,
  q="Cefepime is the drug of choice in which settings?",
  opts=[["Neutropenic fever and nosocomial pneumonia", "Correct, along with pseudomonal infection."],
        ["Surgical prophylaxis and simple cellulitis", "Those are first generation indications."],
        ["Syphilis and other spirochaetal disease", "Penicillin G is the agent there."],
        ["Clostridium difficile colitis given orally", "Oral vancomycin and metronidazole cover that."]]),

 dict(topic="Cephalosporins", io="4b — Cephalosporins", cite=D % 36,
  q="What does cefepime not cover?",
  opts=[["Resistant Staphylococcus, Enterococcus, anaerobes", "Correct, despite its broad Gram-negative and Gram-positive reach."],
        ["Pseudomonas aeruginosa and Enterobacter", "Antipseudomonal activity is one of its features."],
        ["Streptococcus pneumoniae and other streptococci", "Gram-positive coverage is retained."],
        ["Escherichia coli and Klebsiella pneumoniae", "Gram-negative coverage is a strength."]]),

 dict(topic="Cephalosporins", io="4b — Cephalosporins", cite=D % 37,
  q="Which cephalosporin covers methicillin-resistant Staphylococcus aureus?",
  opts=[["Ceftaroline", "Correct, approved for community-acquired pneumonia and skin infection."],
        ["Ceftolozane with tazobactam", "That combination has no resistant Staphylococcus cover."],
        ["Cefepime", "Cefepime specifically lacks it."],
        ["Ceftazidime", "Ceftazidime has no resistant Staphylococcus activity."]]),

 dict(topic="Cephalosporins", io="4b — Cephalosporins", cite=D % 38,
  q="What is ceftolozane/tazobactam approved to treat?",
  opts=[["Complicated intra-abdominal and urinary infection", "Correct, with metronidazole added for the intra-abdominal indication."],
        ["Community-acquired pneumonia and skin infection", "Those are the ceftaroline approvals."],
        ["Neutropenic fever and ventilator pneumonia", "Cefepime is the drug of choice there."],
        ["Meningitis and other central nervous system infection", "Carbapenems are noted for that penetration."]]),

 dict(topic="Monobactams", io="4c — Monobactams", cite=D % 40,
  q="What does aztreonam cover?",
  opts=[["Gram-negative organisms only", "Correct, with a spectrum resembling the aminoglycosides."],
        ["Gram-positive organisms only", "Gram-positive activity is absent."],
        ["Anaerobes and Gram-positive aerobes", "Neither group is covered."],
        ["Broad coverage of all three groups", "Coverage is restricted to Gram-negatives."]]),

 dict(topic="Monobactams", io="4c — Monobactams", cite=D % 41,
  q="Why can aztreonam be used in true penicillin allergy?",
  opts=[["It has no cross-reactivity with beta-lactams", "Correct, which is the practical reason it is kept in reserve."],
        ["It is not a beta-lactam antibiotic at all", "It is a beta-lactam, but without cross-reactivity."],
        ["It is always co-administered with a steroid", "No such requirement is given."],
        ["Its allergic reactions are limited to rash", "The reason given is absence of cross-reactivity."]]),

 dict(topic="Carbapenems", io="4d — Carbapenems", cite=D % 43,
  q="What makes the carbapenems unusually broad?",
  opts=[["Greater resistance to beta-lactamase hydrolysis", "Correct, which is why they suit extended spectrum producers."],
        ["A completely different cellular target", "They remain beta-lactams acting on the cell wall."],
        ["Combination with a beta-lactamase inhibitor", "Resistance to hydrolysis is intrinsic here."],
        ["Concentration-dependent killing with a long effect", "That is not the stated reason."]]),

 dict(topic="Carbapenems", io="4d — Carbapenems", cite=D % 43,
  q="Carbapenems are the drug of choice for which infections?",
  opts=[["Multidrug-resistant Gram-negative and ESBL producers", "Correct, along with nosocomial infection and meningitis."],
        ["Methicillin-resistant Staphylococcus aureus bacteraemia", "Resistant Staphylococcus is specifically not covered."],
        ["Uncomplicated urinary infection in the community", "That would be far broader than needed."],
        ["Syphilis and other spirochaetal infections", "Penicillin G remains the agent there."]]),

 dict(topic="Carbapenems", io="4d — Carbapenems", cite=D % 44,
  q="Which carbapenem is specifically linked to seizures?",
  opts=[["Imipenem", "Correct, and seizures are named among the things to monitor."],
        ["Ertapenem", "Ertapenem is dosed 1 gram daily without that flag."],
        ["Meropenem", "Meropenem does not carry the specific note."],
        ["Doripenem", "Doripenem does not carry the specific note."]]),

 dict(topic="Carbapenems", io="4d — Carbapenems", cite=D % 44,
  q="How is ertapenem dosed?",
  opts=[["1 gram intravenously once daily", "Correct, infused over 30 minutes."],
        ["500 milligrams intravenously every 6 hours", "That is the imipenem schedule."],
        ["1 to 2 grams intravenously every 8 hours", "That is the meropenem schedule."],
        ["500 milligrams intravenously every 8 hours", "That is the doripenem schedule."]]),

 dict(topic="Vancomycin", io="4j — Glycopeptides and lipopeptides", cite=D % 46,
  q="How does vancomycin differ mechanically from a penicillin?",
  opts=[["It binds two D-alanines rather than the enzyme", "Correct. It is a glycopeptide, not a beta-lactam."],
        ["It blocks the 50S ribosomal subunit instead", "That is a protein synthesis inhibitor mechanism."],
        ["It disrupts the outer membrane as a detergent", "That is the polymyxin mechanism."],
        ["It inhibits DNA gyrase and topoisomerase IV", "That is the fluoroquinolone mechanism."]]),

 dict(topic="Vancomycin", io="4j — Glycopeptides and lipopeptides", cite=D % 46,
  q="Why is resistance to vancomycin harder to develop?",
  opts=[["It binds the substrate rather than the enzyme", "Correct, so a single enzymatic change does not defeat it."],
        ["It is given only by the intravenous route", "Route is not what makes resistance difficult."],
        ["It is bacteriostatic rather than bactericidal", "That is not the stated reason."],
        ["It is always combined with a second agent", "Combination therapy is not required."]]),

 dict(topic="Vancomycin", io="4j — Glycopeptides and lipopeptides", cite=D % 47,
  q="Which vancomycin indication is given by mouth?",
  opts=[["Clostridium difficile infection", "Correct. Other indications use the intravenous route."],
        ["Methicillin-resistant Staphylococcus aureus bacteraemia", "That is treated intravenously."],
        ["Endocarditis in a penicillin-allergic patient", "Endocarditis is treated intravenously."],
        ["Surgical prophylaxis in penicillin allergy", "Prophylaxis is given intravenously."]]),

 dict(topic="Vancomycin", io="4j — Glycopeptides and lipopeptides", cite=D % 48,
  q="What is the goal vancomycin trough?",
  opts=[["10 to 15 or 15 to 20 micrograms per millilitre", "Correct, and which of the two depends on the indication."],
        ["1 to 2 micrograms per millilitre", "That range is closer to an aminoglycoside trough."],
        ["30 to 40 micrograms per millilitre", "That is above the stated target."],
        ["5 to 10 or 20 to 25 micrograms per millilitre", "That is the gentamicin trough goal."]]),

 dict(topic="Vancomycin", io="4j — Glycopeptides and lipopeptides", cite=D % 48,
  q="What is suggested when the vancomycin minimum inhibitory concentration is 2 or above?",
  opts=[["Alternative therapy such as linezolid", "Correct, because the target ratio becomes hard to achieve."],
        ["Doubling the interval between doses", "Lengthening the interval would lower exposure further."],
        ["Switching from intravenous to oral dosing", "Oral vancomycin is reserved for Clostridium difficile."],
        ["Adding an aminoglycoside for synergy", "Synergy dosing is an enterococcal aminoglycoside concept."]]),

 dict(topic="Vancomycin", io="4j — Glycopeptides and lipopeptides", cite=D % 50,
  q="What loading dose is used for vancomycin in critically ill patients?",
  opts=[["25 to 30 milligrams per kilogram", "Correct, rounded to the nearest 500 milligrams."],
        ["15 to 20 milligrams per kilogram", "That is the maintenance dose rather than the load."],
        ["7 milligrams per kilogram once daily", "That is tobramycin and gentamicin dosing."],
        ["4 to 6 milligrams per kilogram daily", "That is daptomycin dosing."]]),

 dict(topic="Vancomycin", io="4j — Glycopeptides and lipopeptides", cite=D % 50,
  q="At a creatinine clearance above 70 millilitres per minute, how often is vancomycin given?",
  opts=[["Every 8 hours", "Correct. The interval lengthens as clearance falls."],
        ["Every 12 hours", "That interval applies at 50 to 70 millilitres per minute."],
        ["Every 24 hours", "That applies at 30 to 49 millilitres per minute."],
        ["One dose, then check a random level", "That approach is used below 30 millilitres per minute."]]),

 dict(topic="Vancomycin", io="4j — Glycopeptides and lipopeptides", cite=D % 51,
  q="Red man syndrome belongs to which category of vancomycin problem?",
  opts=[["An infusion-related reaction", "Correct, grouped with fever, chills and phlebitis."],
        ["An immunoglobulin E mediated allergy", "It is described as infusion-related rather than allergic."],
        ["A dose-dependent renal toxicity", "Nephrotoxicity is monitored separately."],
        ["A delayed hypersensitivity rash", "The reaction is tied to the infusion itself."]]),

 dict(topic="Vancomycin", io="4j — Glycopeptides and lipopeptides", cite=D % 51,
  q="When is a vancomycin trough drawn?",
  opts=[["15 to 30 minutes before the next dose", "Correct, usually around the third or fourth dose."],
        ["30 minutes after the infusion finishes", "That timing defines a peak, not a trough."],
        ["Immediately after the first dose is given", "Levels are drawn around the third or fourth dose."],
        ["At any point in the dosing interval", "The timing must be specified relative to administration."]]),
]
