# -*- coding: utf-8 -*-
"""New Pharmacology Exam 1 questions, Lecture 3 part B: adrenergic agonists and
antagonists. Correct answer at index 0; rotated later."""
D = "03. ANS Pharmacology(1).pptx, Slide %d"

QUESTIONS = [
 dict(topic="Adrenergic receptors", io="5 — Identify the location and effects of alpha-one, alpha-two, beta-one and beta-two stimulation", cite=D % 75,
  q="Which properties do the catecholamines share?",
  opts=[["High potency and rapid inactivation", "Correct, along with poor penetration into the brain."],
        ["Low potency and a long half-life", "Both run opposite to what is described."],
        ["Good oral absorption and slow clearance", "Oral epinephrine is inactivated in the gut."],
        ["Resistance to monoamine oxidase", "That describes the noncatecholamines."]]),

 dict(topic="Adrenergic receptors", io="5 — Identify the location and effects of alpha-one, alpha-two, beta-one and beta-two stimulation", cite=D % 76,
  q="Where are alpha-2 receptors located?",
  opts=[["On presynaptic nerve endings and other cells", "Correct, whereas alpha-1 sits postsynaptically on the effector organ."],
        ["On the postsynaptic membrane of the effector organ", "That is the alpha-1 location."],
        ["Only within the central nervous system", "They are found peripherally as well."],
        ["On the neuromuscular endplate", "That is a nicotinic site."]]),

 dict(topic="Adrenergic receptors", io="5 — Identify the location and effects of alpha-one, alpha-two, beta-one and beta-two stimulation", cite=D % 77,
  q="Which agent is most potent at beta receptors?",
  opts=[["Isoproterenol", "Correct, ahead of epinephrine and then norepinephrine."],
        ["Epinephrine", "Epinephrine sits second in the beta order."],
        ["Norepinephrine", "Norepinephrine is least potent at beta receptors."],
        ["Phenylephrine", "Phenylephrine is an alpha-1 agonist."]]),

 dict(topic="Adrenergic agonists", io="6 — Summarize the synthesis, release, and subsequent destiny of ANS neurotransmitters", cite=D % 79,
  q="Which enzymes inactivate the catecholamines?",
  opts=[["Catechol-O-methyltransferase and monoamine oxidase", "Correct, acting postsynaptically and within the neuron."],
        ["Acetylcholinesterase and pseudocholinesterase", "Those act on acetylcholine and succinylcholine."],
        ["Dihydrofolate reductase and thymidylate synthase", "Those belong to folate metabolism."],
        ["Cytochrome P450 3A4 and 1A2", "Those are hepatic drug-metabolising enzymes."]]),

 dict(topic="Adrenergic agonists", io="6 — Summarize the synthesis, release, and subsequent destiny of ANS neurotransmitters", cite=D % 79,
  q="Why do catecholamines cause anxiety and tremor despite poor brain entry?",
  opts=[["Too polar to enter, but they still cause central effects", "Correct, producing anxiety, tremor and headache."],
        ["They are actively transported across the barrier", "They penetrate poorly."],
        ["They are converted to lipophilic metabolites centrally", "That is not the explanation given."],
        ["They open the blood-brain barrier directly", "That is not described."]]),

 dict(topic="Adrenergic agonists", io="6 — Summarize the synthesis, release, and subsequent destiny of ANS neurotransmitters", cite=D % 80,
  q="Why do the noncatecholamines last longer?",
  opts=[["Catechol-O-methyltransferase does not inactivate them", "Correct, and they are poor substrates for monoamine oxidase."],
        ["They bind receptors irreversibly", "Their action is not irreversible."],
        ["They are stored in vesicles for later release", "Storage is not the stated reason."],
        ["They are excreted unchanged by the kidney", "Enzyme resistance is the stated reason."]]),

 dict(topic="Adrenergic agonists", io="10 — Mechanism, pharmacokinetics, indications, contraindications and adverse effects: adrenergic agonists", cite=D % 81,
  q="Which agents are indirect-acting adrenergic agonists?",
  opts=[["Amphetamine, cocaine and tyramine", "Correct, while ephedrine and pseudoephedrine are mixed-action."],
        ["Ephedrine and pseudoephedrine", "Those are mixed-action agents."],
        ["Epinephrine and norepinephrine", "Those are direct-acting."],
        ["Phenylephrine and isoproterenol", "Those are direct-acting."]]),

 dict(topic="Adrenergic agonists", io="5 — Identify the location and effects of alpha-one, alpha-two, beta-one and beta-two stimulation", cite=D % 83,
  q="Which epinephrine effect predominates at low dose?",
  opts=[["Beta effects, producing vasodilation", "Correct, while alpha vasoconstriction predominates at high dose."],
        ["Alpha effects, producing vasoconstriction", "That happens at higher doses."],
        ["Neither; the effects cancel out", "One predominates depending on dose."],
        ["Muscarinic effects on the heart", "Epinephrine is not a cholinergic agent."]]),

 dict(topic="Adrenergic agonists", io="4 — Predict the effects of adrenergic and cholinergic stimulation and inhibition on effector organs", cite=D % 83,
  q="What does epinephrine do to systolic and diastolic pressures?",
  opts=[["Raises systolic and lowers diastolic", "Correct, alongside increased cardiac output."],
        ["Raises both systolic and diastolic", "Diastolic pressure falls."],
        ["Lowers both systolic and diastolic", "Systolic pressure rises."],
        ["Lowers systolic and raises diastolic", "The pattern runs the other way."]]),

 dict(topic="Adrenergic agonists", io="4 — Predict the effects of adrenergic and cholinergic stimulation and inhibition on effector organs", cite=D % 84,
  q="Through which receptor does epinephrine reduce insulin release?",
  opts=[["Alpha-1", "Correct, while glycogenolysis and glucagon release run through beta-2."],
        ["Beta-1", "Beta-1 drives the cardiac effects."],
        ["Beta-2", "Beta-2 raises glycogenolysis and glucagon."],
        ["Alpha-2", "Alpha-2 is presynaptic and not the one named."]]),

 dict(topic="Adrenergic agonists", io="3 — Identify indications for adrenergic agonists", cite=D % 84,
  q="Why is albuterol preferred for chronic asthma over epinephrine?",
  opts=[["Longer duration and less cardiac stimulation", "Correct, as a selective beta-2 agonist."],
        ["It is the only agent that reaches the airway", "Epinephrine also produces bronchodilation."],
        ["It can be given by mouth effectively", "Duration and selectivity are the stated reasons."],
        ["It has no adverse effects at all", "Tremor and restlessness still occur."]]),

 dict(topic="Adrenergic agonists", io="3 — Identify indications for adrenergic agonists", cite=D % 85,
  q="Why is epinephrine added to local anaesthetic solutions?",
  opts=[["It causes vasoconstriction and prolongs the block", "Correct, at about 1 part in 100,000."],
        ["It speeds the onset of anaesthesia", "Duration rather than onset is the benefit."],
        ["It reduces the pain of injection", "Vasoconstriction and duration are the reasons."],
        ["It prevents allergic reactions to the anaesthetic", "That is not the stated purpose."]]),

 dict(topic="Adrenergic agonists", io="10 — Mechanism, pharmacokinetics, indications, contraindications and adverse effects: adrenergic agonists", cite=D % 86,
  q="Why is epinephrine ineffective by mouth?",
  opts=[["Intestinal enzymes inactivate it", "Correct, so it is given by injection or inhalation."],
        ["It is destroyed by stomach acid", "Intestinal enzymes are the stated reason."],
        ["It is not absorbed across the gut wall", "Inactivation rather than absorption is the issue."],
        ["It binds irreversibly to food proteins", "That is not the described problem."]]),

 dict(topic="Adrenergic agonists", io="8 — Drug interactions of adrenergic agonists", cite=D % 87,
  q="Why does hyperthyroidism exaggerate epinephrine's effects?",
  opts=[["Increased production of adrenergic receptors", "Correct, giving a hypersensitive response."],
        ["Reduced hepatic clearance of the drug", "Receptor number is the stated mechanism."],
        ["Reduced monoamine oxidase activity", "That is not the described mechanism."],
        ["Increased catecholamine storage in nerves", "Receptor production is the stated reason."]]),

 dict(topic="Adrenergic agonists", io="8 — Drug interactions of adrenergic agonists", cite=D % 88,
  q="Why does cocaine exaggerate the effects of epinephrine?",
  opts=[["It prevents reuptake of the catecholamine", "Correct, so the cardiovascular actions are amplified."],
        ["It increases adrenergic receptor numbers", "That is the hyperthyroidism mechanism."],
        ["It blocks monoamine oxidase in the gut", "That describes the tyramine interaction."],
        ["It sensitises the heart as an anaesthetic gas would", "That describes inhalation anaesthetics."]]),

 dict(topic="Adrenergic agonists", io="8 — Drug interactions of adrenergic agonists", cite=D % 88,
  q="How do inhalation anaesthetics interact with epinephrine?",
  opts=[["They sensitise the heart, causing tachycardia", "Correct, which matters during anaesthesia."],
        ["They block its cardiac effects entirely", "Sensitisation rather than blockade occurs."],
        ["They speed its hepatic metabolism", "That is not the described interaction."],
        ["They convert it to norepinephrine", "No such conversion is described."]]),

 dict(topic="Adrenergic agonists", io="4 — Predict the effects of adrenergic and cholinergic stimulation and inhibition on effector organs", cite=D % 89,
  q="How does norepinephrine compare with epinephrine at blood vessels?",
  opts=[["It produces greater vasoconstriction", "Correct, acting mainly through alpha-1 receptors."],
        ["It produces greater vasodilation", "Vasoconstriction is the dominant action."],
        ["It has no vascular effect at all", "Vasoconstriction is its principal action."],
        ["It acts mainly on beta-2 receptors", "Alpha receptors are the ones most affected."]]),

 dict(topic="Adrenergic agonists", io="5 — Summarize side effects of adrenergic agonists", cite=D % 90,
  q="How is norepinephrine extravasation treated?",
  opts=[["Phentolamine, an alpha antagonist", "Correct, because extreme vasoconstriction causes the damage."],
        ["Dantrolene given intravenously", "That treats malignant hyperthermia."],
        ["A local beta blocker injection", "The problem is alpha-mediated vasoconstriction."],
        ["Warm compresses alone", "An alpha antagonist is the stated treatment."]]),

 dict(topic="Adrenergic agonists", io="3 — Identify indications for adrenergic agonists", cite=D % 91,
  q="What is isoproterenol used for?",
  opts=[["Stimulating the heart in an emergency", "Correct, as a beta-1 and beta-2 agonist."],
        ["Chronic maintenance of asthma", "Inhaled products are no longer available."],
        ["Raising blood pressure in septic shock", "Phenylephrine and dopamine serve there."],
        ["Nasal decongestion", "Oxymetazoline and phenylephrine are used for that."]]),

 dict(topic="Adrenergic agonists", io="4 — Predict the effects of adrenergic and cholinergic stimulation and inhibition on effector organs", cite=D % 92,
  q="How does dopamine affect the renal circulation?",
  opts=[["It dilates renal and splanchnic arteries", "Correct, through dopaminergic receptors."],
        ["It constricts renal arteries at all doses", "Vasoconstriction occurs only at very high doses."],
        ["It has no effect on renal blood flow", "Renal dilation is a specific action."],
        ["It reduces glomerular filtration directly", "Dilation of renal arteries is described."]]),

 dict(topic="Adrenergic agonists", io="3 — Identify indications for adrenergic agonists", cite=D % 93,
  q="What is dopamine used to treat?",
  opts=[["Cardiogenic and septic shock", "Correct, with nausea, hypertension and arrhythmias as adverse effects."],
        ["Chronic heart failure at home", "Dobutamine is the agent for acute failure support."],
        ["Anaphylaxis in the community", "Epinephrine is used there."],
        ["Asthma exacerbation", "Albuterol is used there."]]),

 dict(topic="Adrenergic agonists", io="3 — Identify indications for adrenergic agonists", cite=D % 94,
  q="What advantage does dobutamine have over other sympathomimetics?",
  opts=[["It does not greatly raise myocardial oxygen demand", "Correct, which suits inotropic support after cardiac surgery."],
        ["It has no effect on atrioventricular conduction", "It increases conduction, so atrial fibrillation needs caution."],
        ["It can be given by mouth", "It is given intravenously."],
        ["Tolerance never develops with prolonged use", "Tolerance may develop."]]),

 dict(topic="Adrenergic agonists", io="7 — Contraindications for adrenergic agonists", cite=D % 94,
  q="Why is dobutamine used cautiously in atrial fibrillation?",
  opts=[["It speeds atrioventricular conduction", "Correct, which risks a faster ventricular response."],
        ["It causes profound bradycardia", "It is a positive chronotrope."],
        ["It lowers blood pressure sharply", "That is not the stated concern."],
        ["It prolongs the QT interval", "Conduction, not repolarisation, is the concern."]]),

 dict(topic="Adrenergic agonists", io="10 — Patient education for adrenergic agonists", cite=D % 95,
  q="Why should oxymetazoline not be used beyond three days?",
  opts=[["Rebound congestion, rhinitis medicamentosa", "Correct, as an alpha-1 and alpha-2 agonist decongestant."],
        ["It causes permanent loss of smell", "Rebound congestion is the stated risk."],
        ["It raises intraocular pressure dangerously", "It is used to relieve eye redness."],
        ["It causes nasal mucosal ulceration", "Rebound congestion is what is described."]]),

 dict(topic="Adrenergic agonists", io="4 — Predict the effects of adrenergic and cholinergic stimulation and inhibition on effector organs", cite=D % 96,
  q="Why does phenylephrine cause reflex bradycardia?",
  opts=[["It raises systolic and diastolic pressure", "Correct, as a selective alpha-1 agonist."],
        ["It stimulates cardiac beta-1 receptors", "It is selective for alpha-1."],
        ["It blocks sympathetic outflow centrally", "That is clonidine's mechanism."],
        ["It acts directly on the sinoatrial node", "The bradycardia is reflex."]]),

 dict(topic="Adrenergic agonists", io="2 — Mechanism of action of adrenergic agonists", cite=D % 97,
  q="How does clonidine lower blood pressure?",
  opts=[["It acts centrally to reduce sympathetic outflow", "Correct, as an alpha-2 agonist inhibiting vasomotor centres."],
        ["It blocks peripheral alpha-1 receptors", "That is the prazosin mechanism."],
        ["It blocks beta-1 receptors in the heart", "That is a beta blocker action."],
        ["It dilates arteries directly as a nitrate", "The action is central and receptor-mediated."]]),

 dict(topic="Adrenergic agonists", io="3 — Identify indications for adrenergic agonists", cite=D % 97,
  q="Besides hypertension, what is clonidine used for?",
  opts=[["Withdrawal from opiates, tobacco and benzodiazepines", "Correct, by minimising withdrawal symptoms."],
        ["Acute asthma exacerbation", "Albuterol is used there."],
        ["Benign prostatic hyperplasia with poor stream", "Tamsulosin and alfuzosin serve there."],
        ["Open-angle glaucoma", "Timolol is used there."]]),

 dict(topic="Adrenergic agonists", io="5 — Summarize side effects of adrenergic agonists", cite=D % 98,
  q="Which adverse effects follow albuterol?",
  opts=[["Tremor, restlessness, apprehension and anxiety", "Correct, as a selective beta-2 agonist."],
        ["Lethargy, sedation and dry mouth", "Those follow clonidine."],
        ["Dizziness and nasal congestion", "Those follow the alpha-1 blockers."],
        ["Bradycardia with bronchoconstriction and wheeze", "Those follow propranolol."]]),

 dict(topic="Adrenergic agonists", io="2 — Mechanism of action of adrenergic agonists", cite=D % 100,
  q="How does amphetamine act on the adrenergic nerve?",
  opts=[["It blocks reuptake and releases catecholamines", "Correct, raising blood pressure and cardiac stimulation."],
        ["It binds postsynaptic receptors directly", "It acts indirectly."],
        ["It inhibits monoamine oxidase in the gut", "That is not the described action."],
        ["It depletes vesicular stores permanently", "That is reserpine's action."]]),

 dict(topic="Adrenergic agonists", io="3 — Identify indications for adrenergic agonists", cite=D % 100,
  q="What is amphetamine used to treat?",
  opts=[["Hyperactivity, narcolepsy, appetite control", "Correct, alongside its central stimulant activity."],
        ["Hypertension and stable angina pectoris", "Those are beta blocker indications."],
        ["Shock requiring vascular resistance", "Norepinephrine is used there."],
        ["Motion sickness on a long journey", "Scopolamine is used for that."]]),

 dict(topic="Adrenergic agonists", io="8 — Drug interactions of adrenergic agonists", cite=D % 101,
  q="Why is tyramine dangerous with a monoamine oxidase inhibitor?",
  opts=[["It is normally oxidised by that enzyme in the gut", "Correct, so a serious vasopressor effect can follow."],
        ["It becomes a direct receptor agonist", "It displaces stored norepinephrine instead."],
        ["It blocks the inhibitor from working", "Its own metabolism is what is blocked."],
        ["It prevents norepinephrine being synthesised", "It displaces stored transmitter."]]),

 dict(topic="Adrenergic agonists", io="8 — Drug interactions of adrenergic agonists", cite=D % 101,
  q="Where is tyramine found?",
  opts=[["Fermented foods such as cheese and wine", "Correct, and it has no therapeutic use of its own."],
        ["Citrus fruit and grapefruit juice", "Those affect cytochrome metabolism instead."],
        ["Dairy products containing calcium", "Calcium chelates tetracyclines instead."],
        ["Green leafy vegetables high in vitamin K", "Those matter for warfarin."]]),

 dict(topic="Adrenergic agonists", io="2 — Mechanism of action of adrenergic agonists", cite=D % 102,
  q="How does cocaine act as a local anaesthetic?",
  opts=[["It blocks neuronal sodium channels", "Correct, separate from its blockade of norepinephrine reuptake."],
        ["It blocks alpha-1 receptors locally", "It potentiates rather than blocks adrenergic action."],
        ["It depletes local catecholamine stores", "That is reserpine's mechanism."],
        ["It inhibits monoamine oxidase locally", "Sodium channel blockade is the anaesthetic action."]]),

 dict(topic="Adrenergic agonists", io="10 — Patient education for adrenergic agonists", cite=D % 104,
  q="What happened to ephedra-containing herbal products in 2004?",
  opts=[["They were banned by the regulator", "Correct, though ephedrine itself was once used to prevent asthma."],
        ["They were moved behind the pharmacy counter", "That applies to pseudoephedrine."],
        ["They were reclassified as prescription only", "A ban is what is described."],
        ["They were approved for nasal congestion", "The action taken was a ban."]]),

 dict(topic="Adrenergic antagonists", io="11 — Mechanism, pharmacokinetics, indications, contraindications and adverse effects: adrenergic antagonists", cite=D % 107,
  q="What cardiovascular reflex do the alpha blockers induce?",
  opts=[["Reflex tachycardia", "Correct, and the effects are more profound on standing."],
        ["Reflex bradycardia", "Tachycardia is what follows."],
        ["No change in heart rate", "A reflex change is described."],
        ["Reflex bronchodilation", "The reflex described is cardiovascular."]]),

 dict(topic="Adrenergic antagonists", io="2 — Mechanism of action of adrenergic antagonists", cite=D % 108,
  q="Why must the body make new receptors after phenoxybenzamine?",
  opts=[["The block is irreversible and non-competitive", "Correct, and that takes at least 24 hours."],
        ["The drug destroys the receptor protein directly", "It binds irreversibly rather than destroying protein."],
        ["The receptors are internalised permanently", "New synthesis is the stated requirement."],
        ["The drug depletes norepinephrine stores", "That is reserpine's action."]]),

 dict(topic="Adrenergic antagonists", io="2 — Mechanism of action of adrenergic antagonists", cite=D % 109,
  q="What is epinephrine reversal?",
  opts=[["Alpha vasoconstriction is blocked, leaving beta vasodilation", "Correct, so blood pressure falls instead of rising."],
        ["Beta effects are blocked, leaving the alpha action unopposed", "The blockade here is of alpha receptors."],
        ["Epinephrine is converted to norepinephrine", "No conversion occurs."],
        ["The drug reverses reuptake into the neuron", "That is not what the term means."]]),

 dict(topic="Adrenergic antagonists", io="3 — Identify indications for adrenergic antagonists", cite=D % 109,
  q="What is phenoxybenzamine used to treat?",
  opts=[["Phaeochromocytoma", "Correct, along with autonomic hyperreflexia in paraplegic patients."],
        ["Benign prostatic hyperplasia", "Tamsulosin and alfuzosin serve there."],
        ["Chronic open-angle glaucoma", "Timolol is used there."],
        ["Hypertensive emergency by infusion", "Labetalol is used there."]]),

 dict(topic="Adrenergic antagonists", io="3 — Identify indications for adrenergic antagonists", cite=D % 110,
  q="Which alpha blocker treats hypertensive crisis after abrupt clonidine withdrawal?",
  opts=[["Phentolamine", "Correct, and it also reverses norepinephrine extravasation."],
        ["Phenoxybenzamine", "That is used in phaeochromocytoma."],
        ["Prazosin", "Prazosin is used for ordinary hypertension."],
        ["Tamsulosin", "Tamsulosin is used for prostatic hyperplasia."]]),

 dict(topic="Adrenergic antagonists", io="3 — Identify indications for adrenergic antagonists", cite=D % 111,
  q="Which alpha-1 blockers are used for benign prostatic hyperplasia?",
  opts=[["Tamsulosin and alfuzosin", "Correct, by relaxing bladder neck and prostatic smooth muscle."],
        ["Prazosin and terazosin", "Those are named for hypertension."],
        ["Doxazosin and phentolamine", "Doxazosin is named for hypertension."],
        ["Labetalol and carvedilol", "Those are mixed alpha and beta blockers."]]),

 dict(topic="Adrenergic antagonists", io="5 — Summarize side effects of adrenergic antagonists", cite=D % 111,
  q="What metabolic benefit do the alpha-1 blockers offer?",
  opts=[["Improved lipid profile and glucose metabolism", "Correct, alongside lowered peripheral resistance."],
        ["Reduced fasting blood glucose only", "Both lipids and glucose are mentioned."],
        ["Weight loss through appetite suppression", "That is not a stated effect."],
        ["Lowered uric acid concentration", "That is not a stated effect."]]),

 dict(topic="Adrenergic antagonists", io="4 — Predict the effects of adrenergic and cholinergic stimulation and inhibition on effector organs", cite=D % 114,
  q="What does propranolol do to the sinoatrial and atrioventricular nodes?",
  opts=[["Depresses both, producing bradycardia", "Correct, as a negative inotrope and chronotrope."],
        ["Stimulates both, producing tachycardia", "It is an antagonist."],
        ["Affects the atrioventricular node only", "Both nodes are depressed."],
        ["Leaves conduction unchanged", "Conduction is depressed."]]),

 dict(topic="Adrenergic antagonists", io="7 — Contraindications for adrenergic antagonists", cite=D % 115,
  q="Why is propranolol contraindicated in asthma?",
  opts=[["Beta-2 blockade causes bronchoconstriction", "Correct, which is why cardioselective agents exist."],
        ["It causes pulmonary oedema directly", "Bronchoconstriction is the stated problem."],
        ["It triggers an allergic reaction in the airway", "The effect is receptor-mediated."],
        ["It reduces respiratory drive centrally", "Bronchoconstriction is the mechanism."]]),

 dict(topic="Adrenergic antagonists", io="7 — Contraindications for adrenergic antagonists", cite=D % 115,
  q="Why is propranolol risky in a patient prone to hypoglycaemia?",
  opts=[["It blunts the normal physiological response to it", "Correct, and it reduces glycogenolysis and glucagon secretion."],
        ["It causes hyperglycaemia that masks the problem", "Fasting hypoglycaemia is the listed effect."],
        ["It increases insulin secretion directly", "That is not the described action."],
        ["It prevents glucose absorption from the gut", "The effect is on glycogenolysis and glucagon."]]),

 dict(topic="Adrenergic antagonists", io="3 — Identify indications for adrenergic antagonists", cite=D % 116,
  q="Why is propranolol useful in hyperthyroidism?",
  opts=[["It blunts widespread sympathetic stimulation", "Correct, treating the symptoms rather than the thyroid."],
        ["It reduces thyroid hormone synthesis", "It acts on the sympathetic response."],
        ["It blocks hormone release from the gland", "It does not act on the gland."],
        ["It speeds hormone clearance from plasma", "That is not the described action."]]),

 dict(topic="Adrenergic antagonists", io="3 — Identify indications for adrenergic antagonists", cite=D % 116,
  q="How does propranolol help after myocardial infarction?",
  opts=[["It prevents a second infarct and reduces infarct size", "Correct, and lowers sudden death from arrhythmia."],
        ["It dissolves the occluding thrombus", "It has no thrombolytic action."],
        ["It dilates the coronary arteries directly", "That is not the described mechanism."],
        ["It raises cardiac output to perfuse the muscle", "It reduces cardiac output and work."]]),

 dict(topic="Adrenergic antagonists", io="5 — Summarize side effects of adrenergic antagonists", cite=D % 117,
  q="Which metabolic disturbances follow propranolol?",
  opts=[["Fasting hypoglycaemia and raised lipids", "Correct, with both cholesterol and triglycerides rising."],
        ["Hyperglycaemia and low triglycerides", "The pattern runs the other way."],
        ["Hyperkalaemia and metabolic acidosis", "Those are not the listed effects."],
        ["Hyponatraemia from fluid retention", "Sodium retention is described, not low sodium."]]),

 dict(topic="Adrenergic antagonists", io="8 — Drug interactions of adrenergic antagonists", cite=D % 118,
  q="Which drugs inhibit propranolol metabolism?",
  opts=[["Cimetidine, fluoxetine, paroxetine and ritonavir", "Correct, while barbiturates, phenytoin and rifampin induce it."],
        ["Barbiturates, phenytoin and rifampin together", "Those induce rather than inhibit metabolism."],
        ["Iron, antacids and calcium products", "Those chelate other drug classes."],
        ["Tyramine-containing fermented foods", "Those matter for monoamine oxidase inhibitors."]]),

 dict(topic="Adrenergic antagonists", io="3 — Identify indications for adrenergic antagonists", cite=D % 119,
  q="Why is timolol used in chronic open-angle glaucoma?",
  opts=[["It reduces production of aqueous humour", "Correct, and it is more potent than propranolol."],
        ["It increases outflow through the trabecular meshwork", "Reduced production is the stated action."],
        ["It constricts the pupil to open the angle", "That is a cholinergic agonist effect."],
        ["It dilates the ciliary body vessels", "Reduced aqueous production is the mechanism."]]),

 dict(topic="Adrenergic antagonists", io="11 — Mechanism, pharmacokinetics, indications, contraindications and adverse effects: adrenergic antagonists", cite=D % 120,
  q="Which beta blockers are selective for beta-1 receptors?",
  opts=[["Atenolol, metoprolol and bisoprolol", "Correct, useful when pulmonary function is impaired."],
        ["Propranolol, timolol and nadolol", "Those are nonselective."],
        ["Labetalol and carvedilol", "Those add alpha-1 blockade."],
        ["Pindolol and phenoxybenzamine", "Pindolol is nonselective and the other is an alpha blocker."]]),

 dict(topic="Adrenergic antagonists", io="11 — Mechanism, pharmacokinetics, indications, contraindications and adverse effects: adrenergic antagonists", cite=D % 121,
  q="Which agents have intrinsic sympathomimetic activity?",
  opts=[["Acebutolol and pindolol", "Correct, weakly stimulating while also antagonising."],
        ["Atenolol and metoprolol", "Those are selective antagonists without it."],
        ["Timolol and nadolol", "Those are nonselective antagonists without it."],
        ["Labetalol and carvedilol", "Those add alpha-1 blockade instead."]]),

 dict(topic="Adrenergic antagonists", io="3 — Identify indications for adrenergic antagonists", cite=D % 122,
  q="Which agent is given intravenously for a hypertensive emergency?",
  opts=[["Labetalol", "Correct, blocking alpha-1 along with both beta receptors."],
        ["Carvedilol", "Carvedilol is used in heart failure."],
        ["Propranolol", "Propranolol is not the named emergency agent."],
        ["Timolol", "Timolol is used in glaucoma."]]),

 dict(topic="Adrenergic antagonists", io="3 — Identify indications for adrenergic antagonists", cite=D % 122,
  q="What has carvedilol been shown to do in heart failure?",
  opts=[["Prevent cardiovascular mortality", "Correct, and it reduces lipid peroxidation and wall thickening."],
        ["Restore ejection fraction to normal", "Mortality benefit is what is described."],
        ["Reverse ventricular remodelling completely", "Reduced wall thickening is described, not reversal."],
        ["Eliminate the need for other therapy", "That claim is not made."]]),

 dict(topic="Adrenergic antagonists", io="2 — Mechanism of action of adrenergic antagonists", cite=D % 123,
  q="How does reserpine deplete neurotransmitters?",
  opts=[["It blocks transport into storage vesicles", "Correct, affecting norepinephrine, dopamine and serotonin."],
        ["It blocks release of stored norepinephrine", "That is guanethidine's action."],
        ["It inhibits monoamine oxidase", "That would raise rather than deplete transmitter."],
        ["It blocks the postsynaptic receptor", "It acts on storage rather than the receptor."]]),

 dict(topic="Adrenergic antagonists", io="2 — Mechanism of action of adrenergic antagonists", cite=D % 123,
  q="What is intrinsic sympathomimetic activity?",
  opts=[["Weak agonist action alongside receptor blockade", "Correct, useful where a blocker causes excessive bradycardia."],
        ["Complete blockade of both beta receptor types", "That describes a plain nonselective antagonist."],
        ["Selective blockade of beta-1 receptors only", "That describes cardioselectivity."],
        ["Added blockade of alpha-1 receptors", "That describes labetalol and carvedilol."]]),
]
