# -*- coding: utf-8 -*-
"""Short clinical vignettes for Pharmacology I Exam 1.

House style for THIS bank, set by Jaxon on 2026-08-30: a stem of one or two
sentences, FOUR options, and options short enough to scan. The reasoning lives
in the per-option explanation, not in the option text -- which is what went
wrong with the original pharm bank, where the median option ran 48 characters
and a quarter of them passed 66.

Targets enforced by pharm_vig_partition.py: stem <= 150 chars, option <= 42,
option median <= 26. Four options throughout, matching the rest of this class.
"""
SRC1 = "Antibiotics, Antivirals, and Antifungals"
SRC2 = "02. Dermatology Medications"
SRC3 = "03. ANS Pharmacology"

# dict(topic, q, opts[[text, why]], c, deck, slide)
POOL = [
 # ---------------- L1: antibacterials ----------------
 dict(topic="Vancomycin", q="Twenty minutes into a vancomycin infusion a patient flushes red over the face and neck and itches. What is this?",
   opts=[["Red man syndrome", "An infusion-rate reaction, not an allergy."],
         ["Anaphylaxis", "That gives airway compromise and hypotension."],
         ["Stevens-Johnson syndrome", "That is a mucocutaneous blistering reaction over days."],
         ["Serum sickness", "That appears a week or more later with fever and arthralgia."]],
   c=0, deck=SRC1, slide=51),
 dict(topic="Vancomycin", q="A patient develops red man syndrome during a vancomycin infusion. What is the fix?",
   opts=[["Slow the infusion", "It is rate-related; the deck infuses 1 gram over 60 minutes."],
         ["Stop vancomycin permanently", "The drug can be continued more slowly."],
         ["Give adrenaline", "Reserved for true anaphylaxis."],
         ["Switch to oral vancomycin", "Oral does not treat a systemic infection."]],
   c=0, deck=SRC1, slide=51),
 dict(topic="Vancomycin", q="A patient has Clostridium difficile colitis. Which route of vancomycin treats it?",
   opts=[["Oral", "Intravenous vancomycin will not reach the gut lumen."],
         ["Intravenous", "That treats systemic infection only."],
         ["Intramuscular", "Not a route used for vancomycin."],
         ["Either route works", "The route is the whole point of the question."]],
   c=0, deck=SRC1, slide=47),
 dict(topic="Legionella", q="A hotel guest has pneumonia. The air-conditioning unit was contaminated. Most likely organism?",
   opts=[["Legionella", "The stock stem for it, from the original American Legion outbreak."],
         ["Streptococcus pneumoniae", "The commonest cause overall, but not this scenario."],
         ["Mycoplasma pneumoniae", "Atypical, but spread person to person."],
         ["Klebsiella pneumoniae", "Classically alcohol use, not air conditioning."]],
   c=0, deck=SRC1, slide=55),
 dict(topic="Macrolides", q="A patient on erythromycin is started on a class III antiarrhythmic. Which risk rises?",
   opts=[["QT prolongation", "Worse with class Ia and III agents and electrolyte abnormalities."],
         ["Tendon rupture", "That is the fluoroquinolone risk."],
         ["Nephrotoxicity", "Not the macrolide pattern."],
         ["Bone marrow suppression", "Not the macrolide pattern."]],
   c=0, deck=SRC1, slide=57),
 dict(topic="Macrolides", q="A patient on clarithromycin has a rising digoxin level. What is the mechanism?",
   opts=[["CYP3A4 inhibition", "Macrolide metabolites form an inactive complex with CYP3A."],
         ["Cation chelation", "That reduces absorption of tetracyclines and quinolones."],
         ["Renal competition", "Not the interaction described."],
         ["Protein displacement", "Not the interaction described."]],
   c=0, deck=SRC1, slide=59),
 dict(topic="Tetracyclines", q="A 6-year-old needs an antibiotic. Why avoid doxycycline?",
   opts=[["Teeth discoloration", "It binds calcium; also depresses skeletal growth."],
         ["Tendon rupture", "That is the fluoroquinolone risk."],
         ["Seizures", "That is imipenem."],
         ["Grey discolouration of skin", "Not an effect this deck gives."]],
   c=0, deck=SRC1, slide=63),
 dict(topic="Tetracyclines", q="A patient takes doxycycline with breakfast and an iron tablet. What happens?",
   opts=[["Absorption falls", "Tetracyclines chelate iron and calcium."],
         ["Absorption rises", "The interaction works the other way."],
         ["The iron is inactivated", "The concern is the antibiotic level."],
         ["No interaction", "Cation chelation is explicitly flagged."]],
   c=0, deck=SRC1, slide=63),
 dict(topic="Tetracyclines", q="A patient on doxycycline in Florida develops a severe sunburn after brief sun exposure. Why?",
   opts=[["Photosensitivity", "Flagged as a tetracycline adverse effect."],
         ["Phototoxic contact reaction", "Not the mechanism named here."],
         ["Drug-induced lupus", "Not the effect described."],
         ["Fixed drug eruption", "Not the effect described."]],
   c=0, deck=SRC1, slide=63),
 dict(topic="Fluoroquinolones", q="A patient on levofloxacin develops sudden posterior ankle pain. What is the concern?",
   opts=[["Achilles tendon rupture", "Tendonitis and tendon rupture are the class risk."],
         ["Septic arthritis", "Not the drug effect being tested."],
         ["Gout", "Not a fluoroquinolone effect."],
         ["Compartment syndrome", "Not a fluoroquinolone effect."]],
   c=0, deck=SRC1, slide=79),
 dict(topic="Fluoroquinolones", q="Which fluoroquinolone should not be used for a urinary tract infection?",
   opts=[["Moxifloxacin", "The one that does not cover urinary tract infection."],
         ["Ciprofloxacin", "Used for urinary tract infection."],
         ["Levofloxacin", "Used for urinary tract infection."],
         ["All are suitable", "Moxifloxacin is explicitly excluded."]],
   c=0, deck=SRC1, slide=78),
 dict(topic="Fluoroquinolones", q="An 82-year-old on ciprofloxacin becomes confused and cannot sleep. What is the likely cause?",
   opts=[["Central nervous system toxicity", "Dizziness, insomnia and somnolence, worse in the elderly."],
         ["Hepatic encephalopathy", "Not the effect being tested."],
         ["Serotonin syndrome", "That is the linezolid interaction."],
         ["Anticholinergic delirium", "Not a fluoroquinolone effect."]],
   c=0, deck=SRC1, slide=79),
 dict(topic="Clindamycin", q="A patient on clindamycin develops profuse foul-smelling diarrhoea. What is the diagnosis?",
   opts=[["Clostridium difficile colitis", "Clindamycin is the most likely antibiotic to cause it."],
         ["Viral gastroenteritis", "The drug history points elsewhere."],
         ["Ischaemic colitis", "Not the drug effect being tested."],
         ["Lactose intolerance", "Not the drug effect being tested."]],
   c=0, deck=SRC1, slide=81),
 dict(topic="Clindamycin", q="A young woman has septic shock after a retained tampon. Which antibiotic binds the toxin?",
   opts=[["Clindamycin", "Used for toxin-mediated disease because it binds the toxin."],
         ["Vancomycin", "Kills the organism but does not bind the toxin."],
         ["Ceftriaxone", "Not the toxin-binding agent."],
         ["Gentamicin", "Not the toxin-binding agent."]],
   c=0, deck=SRC1, slide=80),
 dict(topic="Metronidazole", q="A patient on metronidazole drinks alcohol and becomes flushed and nauseated. What is this?",
   opts=[["Disulfiram-like reaction", "The single most testable fact about this drug."],
         ["Anaphylaxis", "Not the reaction described."],
         ["Alcohol withdrawal", "The drug interaction is the point."],
         ["Serotonin syndrome", "That belongs to linezolid."]],
   c=0, deck=SRC1, slide=86),
 dict(topic="Linezolid", q="A patient on an SSRI is started on linezolid and becomes agitated, febrile and tremulous. What is this?",
   opts=[["Serotonin syndrome", "Interacts with SSRIs, tyramine foods and pseudoephedrine."],
         ["Neuroleptic malignant syndrome", "Not the interaction being tested."],
         ["Malignant hyperthermia", "That follows succinylcholine with halothane."],
         ["Sepsis", "The drug interaction is the point."]],
   c=0, deck=SRC1, slide=71),
 dict(topic="Linezolid", q="Which laboratory value needs watching on prolonged linezolid?",
   opts=[["Platelet count", "Thrombocytopenia is the listed toxicity."],
         ["Serum creatinine", "Renal monitoring belongs to vancomycin and the aminoglycosides."],
         ["Potassium", "The electrolyte watch belongs to amphotericin and posaconazole."],
         ["Prothrombin time", "Clotting is the Bactrim-and-warfarin interaction."]],
   c=0, deck=SRC1, slide=71),
 dict(topic="Imipenem", q="A patient on imipenem with renal impairment has a seizure. Is this expected?",
   opts=[["Yes, seizures are a known imipenem effect", "The unique side effect flagged for this agent."],
         ["No, carbapenems do not cause seizures", "Imipenem specifically does."],
         ["Only with intrathecal use", "Not the qualifier given."],
         ["Only in children", "Not the qualifier given."]],
   c=0, deck=SRC1, slide=44),
 dict(topic="Aztreonam", q="A patient with a true penicillin allergy needs gram-negative cover. Which agent is safe?",
   opts=[["Aztreonam", "No documented cross-reactivity with beta-lactams."],
         ["Ceftriaxone", "A beta-lactam, though cross-reactivity is under 1%."],
         ["Meropenem", "A beta-lactam."],
         ["Piperacillin", "A penicillin."]],
   c=0, deck=SRC1, slide=41),
 dict(topic="Ceftriaxone", q="A 2-week-old has suspected sepsis. Which cephalosporin is preferred?",
   opts=[["Cefotaxime", "Ceftriaxone cannot be used in the first 30 days of life."],
         ["Ceftriaxone", "Contraindicated in the first 30 days of life."],
         ["Cefazolin", "Not the agent named for neonatal sepsis."],
         ["Cefepime", "Not the agent named for neonatal sepsis."]],
   c=0, deck=SRC1, slide=34),
 dict(topic="Aminoglycosides", q="A patient on gentamicin reports new ringing in the ears. Which toxicity is this?",
   opts=[["Ototoxicity", "Listed with nephrotoxicity for the class."],
         ["Neurotoxicity", "Not the effect described."],
         ["Hepatotoxicity", "Not an aminoglycoside effect."],
         ["Retinal toxicity", "That is voriconazole's visual effect."]],
   c=0, deck=SRC1, slide=68),
 dict(topic="Aminoglycosides", q="Why did aminoglycoside dosing change from every 8 hours to once daily?",
   opts=[["Concentration-dependent killing", "Plus a post-antibiotic effect."],
         ["Time-dependent killing", "That favours frequent dosing."],
         ["Reduced cost", "Not the pharmacologic reason."],
         ["Better oral absorption", "They are not given orally."]],
   c=0, deck=SRC1, slide=68),
 dict(topic="Bactrim", q="An immunocompromised patient needs prophylaxis against Pneumocystis pneumonia. Which drug?",
   opts=[["Trimethoprim/sulfamethoxazole", "Treatment and prophylaxis for Pneumocystis jirovecii."],
         ["Azithromycin", "Used for Mycobacterium avium prophylaxis."],
         ["Doxycycline", "Not the agent for Pneumocystis."],
         ["Metronidazole", "Anaerobic cover, not Pneumocystis."]],
   c=0, deck=SRC1, slide=84),
 dict(topic="Bactrim", q="A patient on warfarin is started on Bactrim. What happens to the INR?",
   opts=[["It rises significantly", "Through CYP2C9 inhibition."],
         ["It falls", "The interaction runs the other way."],
         ["It is unchanged", "A significant interaction is flagged."],
         ["It becomes unmeasurable", "Not a real outcome."]],
   c=0, deck=SRC1, slide=85),
 dict(topic="Polymyxins", q="Which three black box warnings does polymyxin carry?",
   opts=[["Kidney, nerve, neuromuscular", "Nephrotoxicity, neurotoxicity, neuromuscular blockade."],
         ["Liver, ear, seizures", "Ototoxicity is aminoglycoside; seizures are imipenem."],
         ["Marrow, rash, colitis", "Marrow is flucytosine; colitis is clindamycin."],
         ["Heart, tendon, skin", "That mixes the macrolide, quinolone and tetracycline risks."]],
   c=0, deck=SRC1, slide=88),

 # ---------------- L1: antifungals and antivirals ----------------
 dict(topic="Amphotericin B", q="A patient starting amphotericin B spikes a fever with rigors. What is the pre-treatment?",
   opts=[["Paracetamol, antihistamine, corticosteroid", "The listed pre-medication for the reaction."],
         ["Adrenaline", "Reserved for anaphylaxis."],
         ["Normal saline alone", "Saline addresses the renal tubule damage, not the fever."],
         ["Stop the drug permanently", "It is pre-medicated, not abandoned."]],
   c=0, deck=SRC1, slide=98),
 dict(topic="Amphotericin B", q="Which electrolyte pattern accompanies amphotericin B?",
   opts=[["Low potassium and low magnesium", "Hypokalaemia and hypomagnesaemia."],
         ["High potassium and high magnesium", "The opposite of the listed effect."],
         ["Low sodium alone", "Not the listed pattern."],
         ["High calcium", "Not the listed pattern."]],
   c=0, deck=SRC1, slide=99),
 dict(topic="Azoles", q="A woman of childbearing age is prescribed itraconazole. What must be checked first?",
   opts=[["A pregnancy test", "It is teratogenic."],
         ["Renal function", "Not the flagged pre-treatment check."],
         ["An ECG", "Not the flagged pre-treatment check."],
         ["Liver biopsy", "Not required."]],
   c=0, deck=SRC1, slide=104),
 dict(topic="Voriconazole", q="A patient on voriconazole reports visual disturbance. How common is this?",
   opts=[["About 30%", "Visual effects occur in roughly a third."],
         ["Under 1%", "Far more common than that."],
         ["About 5%", "Understates it."],
         ["Nearly all patients", "Overstates it."]],
   c=0, deck=SRC1, slide=107),
 dict(topic="Fluconazole", q="Which azole penetrates the central nervous system for cryptococcal meningitis?",
   opts=[["Fluconazole", "Best oral absorption and it penetrates the CNS."],
         ["Ketoconazole", "Does not enter the CNS."],
         ["Itraconazole", "Not the agent named for meningitis."],
         ["Griseofulvin", "An antidermatophyte, not for meningitis."]],
   c=0, deck=SRC1, slide=106),
 dict(topic="Griseofulvin", q="A patient asks how long griseofulvin takes for a toenail infection. What do you say?",
   opts=[["Up to 12 months", "Scalp 1 month, fingernails 6 to 9, toenails up to 12."],
         ["About 2 weeks", "Far too short."],
         ["About 6 weeks", "That is closer to a fingernail course."],
         ["A single dose", "That is fluconazole for vaginal candidiasis."]],
   c=0, deck=SRC1, slide=110),
 dict(topic="Griseofulvin", q="How should griseofulvin be taken to improve absorption?",
   opts=[["With a high-fat meal", "Absorption increases with fat."],
         ["On an empty stomach", "The opposite of the advice."],
         ["With milk", "Not the stated advice."],
         ["With an antacid", "Not the stated advice."]],
   c=0, deck=SRC1, slide=111),
 dict(topic="Acyclovir", q="A patient on intravenous acyclovir has a rising creatinine. What prevents this?",
   opts=[["Good hydration", "It crystallizes in the renal tubule."],
         ["A loop diuretic", "Not the stated measure."],
         ["Alkalinising the urine", "Not the stated measure."],
         ["Slowing the infusion", "Hydration is the measure given."]],
   c=0, deck=SRC1, slide=123),
 dict(topic="Oseltamivir", q="A patient presents on day 4 of influenza. What limits oseltamivir now?",
   opts=[["It must start within 48 hours", "The window has passed."],
         ["It needs a negative rapid test", "Not the stated limit."],
         ["It cannot be given orally", "Oral is the only route."],
         ["It is contraindicated in adults", "It is not."]],
   c=0, deck=SRC1, slide=126),
 dict(topic="Ganciclovir", q="A transplant patient on ganciclovir has a falling neutrophil count. Is this expected?",
   opts=[["Yes, neutropenia in 15 to 40%", "Plus thrombocytopenia and CNS effects."],
         ["No, it spares the marrow", "Marrow suppression is prominent."],
         ["Only with oral dosing", "Not the qualifier given."],
         ["Only in children", "Not the qualifier given."]],
   c=0, deck=SRC1, slide=125),

 # ---------------- L2: dermatology ----------------
 dict(topic="Isotretinoin", q="A woman is starting isotretinoin. Which programme must she enrol in?",
   opts=[["iPledge", "Committed to pregnancy prevention."],
         ["REMS for clozapine", "The wrong programme."],
         ["A photosensitivity registry", "Not a real requirement here."],
         ["No programme is needed", "Enrolment is mandatory."]],
   c=0, deck=SRC2, slide=27),
 dict(topic="Isotretinoin", q="Which mood change must be monitored on isotretinoin?",
   opts=[["Developing depression", "Explicitly flagged for monitoring."],
         ["Mania", "Not the flagged effect."],
         ["Psychosis", "Not the flagged effect."],
         ["No monitoring is needed", "Monitoring is explicitly required."]],
   c=0, deck=SRC2, slide=27),
 dict(topic="Topical retinoids", q="A patient applies tretinoin each morning and burns. What is the advice?",
   opts=[["Apply it at night", "Tretinoin is photolabile."],
         ["Apply it twice daily", "Would worsen the irritation."],
         ["Add benzoyl peroxide", "That inactivates tretinoin."],
         ["Stop all acne therapy", "An unnecessary escalation."]],
   c=0, deck=SRC2, slide=24),
 dict(topic="Topical retinoids", q="Which agent inactivates tretinoin if layered with it?",
   opts=[["Benzoyl peroxide", "It inactivates tretinoin."],
         ["Adapalene", "Stable with benzoyl peroxide."],
         ["Clindamycin", "Commonly combined with it."],
         ["Azelaic acid", "Not the stated interaction."]],
   c=0, deck=SRC2, slide=24),
 dict(topic="Topical retinoids", q="A patient wants a retinoid that tolerates sun and benzoyl peroxide. Which one?",
   opts=[["Adapalene", "Stable in sunlight and with benzoyl peroxide."],
         ["Tretinoin", "Photolabile and inactivated by benzoyl peroxide."],
         ["Tazarotene", "Not the one named for stability."],
         ["Isotretinoin", "A systemic agent."]],
   c=0, deck=SRC2, slide=25),
 dict(topic="Acne", q="A patient stopped benzoyl peroxide because of irritation. What is the next step?",
   opts=[["A topical retinoid", "The next step he gave for this exact scenario."],
         ["Oral isotretinoin", "Too large a jump for a first failure."],
         ["Oral prednisone", "Not the acne pathway."],
         ["Stop all treatment", "Not a management step."]],
   c=0, deck=SRC2, slide=23),
 dict(topic="Benzoyl peroxide", q="A patient complains their pillowcases are going pale. Which agent?",
   opts=[["Benzoyl peroxide", "It bleaches hair, clothes and fabric."],
         ["Tretinoin", "Not a bleaching agent."],
         ["Clindamycin lotion", "Not a bleaching agent."],
         ["Azelaic acid", "Causes hypopigmentation of skin, not fabric."]],
   c=0, deck=SRC2, slide=21),
 dict(topic="Topical steroids", q="A child needs a topical steroid for facial eczema. Which potency?",
   opts=[["Low potency", "Low potency for face, intertriginous areas and infants."],
         ["Superpotent", "Inappropriate for the face."],
         ["High potency", "Inappropriate for the face."],
         ["Any potency is fine", "Site determines potency."]],
   c=0, deck=SRC2, slide=37),
 dict(topic="Topical steroids", q="A patient using a potent topical steroid for months develops thin, fragile skin. What is this?",
   opts=[["Skin atrophy", "A local adverse effect of topical steroids."],
         ["Contact dermatitis", "Usually related to the vehicle."],
         ["Tinea incognito", "Not the effect being tested."],
         ["Psoriasis", "Not a steroid adverse effect."]],
   c=0, deck=SRC2, slide=38),
 dict(topic="Topical steroids", q="Which vehicle gives the greatest potency for the same steroid?",
   opts=[["Ointment", "Ointment is greater than cream, which is greater than lotion."],
         ["Lotion", "The least occlusive."],
         ["Cream", "Intermediate."],
         ["Foam", "Not the ranking given."]],
   c=0, deck=SRC2, slide=38),
 dict(topic="Immunomodulators", q="Why is tacrolimus ointment second line rather than first for atopic dermatitis?",
   opts=[["Possible cancer risk", "Second line after topical steroids."],
         ["It is ineffective", "It does reduce severity."],
         ["It causes atrophy", "That is the steroid effect."],
         ["It cannot be used on the face", "Not the stated reason."]],
   c=0, deck=SRC2, slide=43),
 dict(topic="Imiquimod", q="A patient on imiquimod for warts has redness and erosions. What do you tell them?",
   opts=[["Inflammation parallels efficacy", "Expected; it tracks with the drug working."],
         ["Stop immediately", "The reaction is expected."],
         ["It is an allergy", "Not the stated interpretation."],
         ["Add a topical steroid", "Not the stated advice."]],
   c=0, deck=SRC2, slide=57),
 dict(topic="Neomycin", q="A patient using triple antibiotic ointment develops dermatitis around the wound. Which component?",
   opts=[["Neomycin", "It frequently causes sensitization."],
         ["Bacitracin", "Allergic dermatitis is rare and there is no systemic toxicity."],
         ["Polymyxin B", "Allergic reactions are uncommon."],
         ["The petrolatum base", "Not the flagged sensitiser."]],
   c=0, deck=SRC2, slide=49),
 dict(topic="Ciclopirox", q="A patient asks how well ciclopirox nail lacquer works for onychomycosis. What do you say?",
   opts=[["Under 12% effective", "The figure the deck gives."],
         ["About half of patients", "Overstates it substantially."],
         ["Almost always curative", "Overstates it substantially."],
         ["It works within two weeks", "Not a duration claim the deck makes."]],
   c=0, deck=SRC2, slide=52),

 # ---------------- L3: autonomic ----------------
 dict(topic="Beta blockers", q="A patient with asthma is started on propranolol and becomes wheezy. Why?",
   opts=[["Beta-2 blockade", "Contraindicated in asthma and COPD."],
         ["Alpha-1 blockade", "Not the mechanism."],
         ["Muscarinic blockade", "Not the mechanism."],
         ["Beta-1 blockade", "Cardiac, not bronchial."]],
   c=0, deck=SRC3, slide=115),
 dict(topic="Beta blockers", q="A diabetic on propranolol no longer notices hypoglycaemia. Why?",
   opts=[["It blunts the sympathetic warning signs", "It attenuates the normal response to hypoglycaemia."],
         ["It raises the glucose threshold", "Not the mechanism."],
         ["It destroys beta cells", "Not the mechanism."],
         ["It blocks insulin release", "Not the effect described."]],
   c=0, deck=SRC3, slide=115),
 dict(topic="Beta blockers", q="A patient stops propranolol abruptly and develops arrhythmias. Why?",
   opts=[["Beta receptor up-regulation", "Never stop a beta blocker suddenly."],
         ["Rebound alpha stimulation", "Not the stated mechanism."],
         ["Accumulated metabolite", "Not the stated mechanism."],
         ["Withdrawal of the vehicle", "Not a real mechanism."]],
   c=0, deck=SRC3, slide=117),
 dict(topic="Beta blockers", q="A beta blocker begins with a letter from N to Z. What does that suggest?",
   opts=[["Non-selective", "A to M are generally cardioselective."],
         ["Cardioselective", "That is A to M."],
         ["It has alpha blockade", "That is labetalol and carvedilol."],
         ["It has intrinsic sympathomimetic activity", "That is acebutolol and pindolol."]],
   c=0, deck=SRC3, slide=120),
 dict(topic="Atropine", q="A patient is hot, dry, flushed, confused, with dilated pupils and urinary retention. Which toxidrome?",
   opts=[["Anticholinergic", "Mad as a hatter, blind as a bat, red as a beet, dry as a bone, hot as Hades."],
         ["Cholinergic", "That gives salivation, lacrimation and diarrhoea."],
         ["Sympathomimetic", "Would sweat rather than be dry."],
         ["Opioid", "Would give pinpoint pupils."]],
   c=0, deck=SRC3, slide=50),
 dict(topic="Atropine", q="A farm worker is bradycardic, salivating and wheezing after pesticide exposure. Which drug reverses the muscarinic effects?",
   opts=[["Atropine", "The antidote for cholinesterase inhibitor insecticides."],
         ["Pralidoxime", "Reactivates the enzyme but does not enter the CNS."],
         ["Neostigmine", "Would worsen it."],
         ["Physostigmine", "Would worsen it."]],
   c=0, deck=SRC3, slide=51),
 dict(topic="Pralidoxime", q="What is the limitation of pralidoxime in organophosphate poisoning?",
   opts=[["It does not enter the CNS", "And cannot overcome reversible inhibitors."],
         ["It only works orally", "Not the stated limit."],
         ["It worsens bradycardia", "Not the stated limit."],
         ["It has no antidotal role", "It does reactivate the enzyme."]],
   c=0, deck=SRC3, slide=42),
 dict(topic="Succinylcholine", q="After succinylcholine with halothane a patient becomes rigid, acidotic and hyperpyrexic. Treatment?",
   opts=[["Dantrolene and rapid cooling", "Malignant hyperthermia."],
         ["Neostigmine", "Does not reverse a depolarising blocker."],
         ["Atropine", "Not the treatment for malignant hyperthermia."],
         ["Naloxone", "Not relevant."]],
   c=0, deck=SRC3, slide=70),
 dict(topic="Succinylcholine", q="A patient stays paralysed far longer than expected after succinylcholine. Why?",
   opts=[["Plasma cholinesterase deficiency", "A genetic variant with low or absent enzyme."],
         ["Renal failure", "Not the stated cause."],
         ["Malignant hyperthermia", "That presents with rigidity and fever."],
         ["Hypokalaemia", "Succinylcholine raises potassium."]],
   c=0, deck=SRC3, slide=70),
 dict(topic="Oxymetazoline", q="A patient has used Afrin for a week and is more congested than before. What is this?",
   opts=[["Rhinitis medicamentosa", "Rebound congestion past three days."],
         ["Allergic rhinitis", "The drug history is the point."],
         ["Sinusitis", "Not the effect being tested."],
         ["Nasal polyps", "Not a drug effect."]],
   c=0, deck=SRC3, slide=95),
 dict(topic="Oxymetazoline", q="How is rebound congestion from oxymetazoline managed?",
   opts=[["Taper the drug down", "A taper lets the receptors recover."],
         ["Increase the dose", "Would deepen the rebound."],
         ["Add an antihistamine", "Not the stated fix."],
         ["Continue indefinitely", "The three-day limit is the point."]],
   c=0, deck=SRC3, slide=95),
 dict(topic="Alpha-1 blockers", q="A patient faints after the first dose of prazosin. What is this?",
   opts=[["First-dose syncope", "Give the first dose at bedtime."],
         ["Anaphylaxis", "Not the effect described."],
         ["Vasovagal syncope", "The drug effect is the point."],
         ["Arrhythmia", "Not the stated effect."]],
   c=0, deck=SRC3, slide=111),
 dict(topic="Alpha-1 blockers", q="Which alpha-1 blockers are used for benign prostatic hyperplasia?",
   opts=[["Tamsulosin and alfuzosin", "They reduce bladder neck and prostate tone."],
         ["Prazosin and terazosin", "Those are used for hypertension."],
         ["Phentolamine", "Short-term pheochromocytoma management."],
         ["Phenoxybenzamine", "Pheochromocytoma."]],
   c=0, deck=SRC3, slide=111),
 dict(topic="Clonidine", q="A patient stops clonidine abruptly and the blood pressure spikes. What is this?",
   opts=[["Rebound hypertension", "Never stop clonidine abruptly."],
         ["Pheochromocytoma", "The drug history is the point."],
         ["Serotonin syndrome", "Not the effect described."],
         ["Malignant hypertension of pregnancy", "Not relevant."]],
   c=0, deck=SRC3, slide=97),
 dict(topic="Norepinephrine", q="A norepinephrine infusion extravasates and the skin blanches. What is given?",
   opts=[["Phentolamine", "An alpha antagonist reverses the vasoconstriction."],
         ["More norepinephrine", "Would worsen it."],
         ["Adrenaline", "Would worsen the vasoconstriction."],
         ["Atropine", "Not the treatment."]],
   c=0, deck=SRC3, slide=90),
 dict(topic="Epinephrine", q="A patient in anaphylaxis needs immediate treatment. Which drug?",
   opts=[["Epinephrine", "Anaphylactic shock is a listed indication."],
         ["Norepinephrine", "Used for shock from vasodilation, not anaphylaxis."],
         ["Dobutamine", "For acute heart failure."],
         ["Dopamine", "For cardiogenic and septic shock."]],
   c=0, deck=SRC3, slide=85),
 dict(topic="Epinephrine", q="Why is epinephrine added to a local anaesthetic?",
   opts=[["It prolongs the block", "Vasoconstriction at the injection site."],
         ["It speeds onset", "The stated benefit is duration."],
         ["It reduces allergy", "Not the reason."],
         ["It buffers the pH", "Not the reason."]],
   c=0, deck=SRC3, slide=85),
 dict(topic="Phenylephrine", q="A patient given intravenous phenylephrine develops a slower heart rate. Why?",
   opts=[["Reflex bradycardia", "A baroreceptor response to the rise in pressure."],
         ["Direct beta-1 blockade", "Phenylephrine is an alpha-1 agonist."],
         ["Vagal nerve stimulation", "Not the stated mechanism."],
         ["Sick sinus syndrome", "Not a drug effect."]],
   c=0, deck=SRC3, slide=96),
 dict(topic="Bethanechol", q="A patient cannot void after surgery with no obstruction. Which drug stimulates the bladder?",
   opts=[["Bethanechol", "Used for postoperative and postpartum urinary retention."],
         ["Oxybutynin", "Would worsen retention."],
         ["Atropine", "Would worsen retention."],
         ["Tamsulosin", "Used for prostatic obstruction, not atony."]],
   c=0, deck=SRC3, slide=30),
 dict(topic="Myasthenia gravis", q="Which drug is used for chronic management of myasthenia gravis?",
   opts=[["Pyridostigmine", "Edrophonium is for diagnosis, not maintenance."],
         ["Edrophonium", "Short-acting, used to diagnose."],
         ["Atropine", "Would worsen weakness."],
         ["Succinylcholine", "A paralytic."]],
   c=0, deck=SRC3, slide=39),
 dict(topic="Dobutamine", q="A patient in acute heart failure needs inotropic support. Which agent?",
   opts=[["Dobutamine", "Raises cardiac output without much rise in oxygen demand."],
         ["Phenylephrine", "A pure vasoconstrictor."],
         ["Clonidine", "Lowers sympathetic outflow."],
         ["Propranolol", "Negative inotrope."]],
   c=0, deck=SRC3, slide=94),
 dict(topic="Tyramine", q="A patient on a monoamine oxidase inhibitor eats aged cheese and the pressure spikes. Why?",
   opts=[["Tyramine displaces norepinephrine", "Normally destroyed by MAO in the gut."],
         ["Direct alpha agonism", "Tyramine acts indirectly."],
         ["Cheese contains adrenaline", "Not true."],
         ["Beta-2 stimulation", "Not the mechanism."]],
   c=0, deck=SRC3, slide=101),
 dict(topic="Timolol", q="Which beta blocker is used topically for chronic open-angle glaucoma?",
   opts=[["Timolol", "Reduces aqueous humour production."],
         ["Propranolol", "Systemic, and contraindicated in asthma."],
         ["Atenolol", "A cardioselective oral agent."],
         ["Carvedilol", "Oral, with added alpha-1 blockade."]],
   c=0, deck=SRC3, slide=119),
 dict(topic="Scopolamine", q="A patient using a scopolamine patch develops one blurred, dilated pupil. What is the cause?",
   opts=[["Touching the eye after the patch", "Wash hands thoroughly after handling it."],
         ["A stroke", "The drug history explains it."],
         ["Third nerve palsy", "The drug history explains it."],
         ["Migraine", "Not the cause."]],
   c=0, deck=SRC3, slide=54),
]
