# Pharmacology I Lecture 2 — Dermatology Medications, pool part A
# Vehicles and penetration, acne pathogenesis, and the acne drugs.
#
# WEIGHTING, per Dr. McInnis to the class 2026-08-28: students over-invest in
# mechanism. Indications, patient education, side effects and contraindications
# are deliberately the heavier categories here. The syllabus agrees -- four of
# its ten dermatology objectives are exactly those four, and mechanism is one.
#
# Per Dr. Wood, NO question's correct answer is a dose or a concentration.
# Potency CLASS and "start low, titrate" are technique and stay in.
SRC = "02. Dermatology Medications(1).pptx"
def c(n): return f"{SRC}, Slide {n}"

IO1  = "1 — Identify dermatologic drug classes and commonly prescribed dermatologic drugs"
IO2  = "2 — Describe the molecular mechanism of action of dermatologic drugs"
IO3  = "3 — Identify indications for commonly used dermatologic drugs"
IO4  = "4 — Describe absorption, distribution, metabolism, and excretion of dermatologic drugs"
IO5  = "5 — Summarize side effects and toxic manifestations of dermatologic drugs"
IO7  = "7 — Identify contraindications for dermatologic drugs"
IO8  = "8 — Discuss potential drug-drug, drug-food, and drug-herb interactions"
IO10 = "10 — Outline appropriate patient education for dermatologic drugs"

POOL_A = [

 dict(topic="Topical vehicles", io=IO4,
   q="Which body sites are named as more permeable to a topical drug?",
   opts=[
     ["Scrotum, face, axilla and scalp",
      "Correct. The scrotum, face, axilla and scalp have a thin stratum corneum, and the axilla is naturally occluded, so all four absorb far more drug than ordinary skin."],
     ["Palms, soles, knees and elbows",
      "These are the thick, keratinised sites where penetration is poorest, which is the opposite of what is asked."],
     ["Back, chest, abdomen and buttocks",
      "The trunk is ordinary-thickness skin with average penetration; the highly permeable sites are the thin or naturally occluded ones."],
     ["Shins, forearms, dorsal hands and neck",
      "These are average to poorly penetrated sites, the shin especially, where skin is thin over bone but poorly perfused."]],
   c=0, cite=c(4)),

 dict(topic="Topical vehicles", io=IO4,
   q="A patient's corticosteroid is not controlling a plaque. Based on the concentration gradient principle, what is predicted?",
   opts=[
     ["Raising the concentration increases drug transfer and can overcome the resistance",
      "Correct. Absorption across the stratum corneum is driven by the concentration gradient, so a higher concentration drives more drug into the skin and can overcome apparent resistance."],
     ["Concentration has little effect once the stratum corneum is saturated",
      "The gradient keeps driving transfer; increasing the concentration increases the amount of drug crossing rather than reaching a plateau."],
     ["Changing to a more drying vehicle will matter more than concentration",
      "Vehicle matters, but it is a separate variable; the concentration gradient is what this principle predicts."],
     ["Only a change to a systemic agent will overcome it",
      "Systemic therapy is reserved for moderate-severe disease, not for a single unresponsive plaque."]],
   c=0, cite=c(4)),

 dict(topic="Topical vehicles", io=IO4,
   q="What is the depot effect, and what does it allow?",
   opts=[
     ["Skin acts as a reservoir for the drug, which may permit once daily dosing of short acting drugs",
      "Correct. The reservoir is what lets a short acting drug be given less often than its half-life suggests."],
     ["The drug is stored in subcutaneous fat and released during exercise",
      "The reservoir is the stratum corneum itself rather than adipose tissue, and release is steady rather than exercise-dependent."],
     ["The vehicle evaporates and leaves crystals that dissolve slowly in sweat",
      "Nothing crystallises in sweat; the drug binds within the stratum corneum, which then releases it gradually."],
     ["Repeated applications saturate hair follicles and shut down absorption",
      "The depot effect prolongs availability rather than stopping absorption."]],
   c=0, cite=c(5)),

 dict(topic="Topical vehicles", io=IO5,
   q="Occlusion increases efficacy. What must be flagged alongside that?",
   opts=[
     ["It raises the question of increased toxicity as well",
      "Correct. Occlusion hydrates the stratum corneum and drives more drug in, so systemic absorption and local adverse effects rise along with efficacy."],
     ["It reliably shortens the required duration of therapy",
      "Occlusion increases the amount absorbed rather than shortening the course; the trade-off is greater toxicity."],
     ["It prevents the vehicle from exerting any therapeutic effect of its own",
      "A vehicle can be therapeutic in its own right, by hydrating or drying the skin, and occlusion does not remove that."],
     ["It makes regional variation in penetration irrelevant",
      "Regional variation remains a separate major variable."]],
   c=0, cite=c(5)),

 dict(topic="Topical vehicles", io=IO3,
   q="Which vehicle is placed at the most drying end of its range, and which at the least?",
   opts=[
     ["Tinctures are the most drying and ointments the least",
      "Correct. The list runs tinctures, wet dressings, lotions, gels, aerosols, powders, pastes, creams, foams, ointments."],
     ["Ointments are the most drying and tinctures the least",
      "This reverses the range: tinctures are alcohol-based and most drying, while ointments are the greasiest and least drying."],
     ["Creams are the most drying and gels the least",
      "Both sit in the middle of the range rather than at its ends."],
     ["Powders are the most drying and lotions the least",
      "Powders are within the list but tinctures anchor the drying end."]],
   c=0, cite=c(7)),

 dict(topic="Topical vehicles", io=IO3,
   q="A lesion is oozing, vesicular and crusting. Which end of the vehicle range is paired with that presentation?",
   opts=[
     ["The drying end of the range",
      "Correct. Oozing, vesiculation and crusting are matched to drying vehicles; scaling, lichenification and xerosis to the least drying."],
     ["The least drying end of the range",
      "That end is paired with scaling, lichenification and xerosis, which is the opposite presentation."],
     ["The middle of the range, regardless of the lesion",
      "The vehicle is matched to the lesion rather than defaulting to the middle; a wet lesion takes a drying vehicle."],
     ["Vehicle choice is not linked to lesion morphology",
      "Morphology drives vehicle choice directly: wet lesions take drying vehicles and dry, scaly lesions take greasy ones."]],
   c=0, cite=c(7)),

 dict(topic="Topical vehicles", io=IO10,
   q="Which vehicle should be avoided in intertriginous areas?",
   opts=[
     ["Ointment",
      "Correct. Ointment is a water-in-oil preparation that leaves an occlusive film, and in a skin fold that traps heat and moisture and promotes maceration."],
     ["Gel",
      "Gel is water-soluble and greaseless, which suits the scalp and hairy areas and does not macerate a fold."],
     ["Lotion",
      "Lotion is a suspension that spreads thinly and evaporates, making it suitable at most sites including folds."],
     ["Cream",
      "Cream is an oil-in-water emulsion that absorbs without leaving an occlusive film, so it is well suited to folds."]],
   c=0, cite=c(8)),

 dict(topic="Topical vehicles", io=IO10,
   q="Which vehicle is recommended for the scalp and hairy locations, and why?",
   opts=[
     ["Gel or foam, because it foams well and leaves low residue",
      "Correct. Gel and foam are greaseless and water-soluble, so they reach the scalp through hair and leave little residue behind."],
     ["Ointment, because the oil film protects hair shafts",
      "Ointment leaves a greasy film, which is why it is not the scalp choice here."],
     ["Paste, because it stays where it is applied",
      "Paste is in the vehicle list but is not the scalp recommendation."],
     ["Powder, because it absorbs sebum",
      "Powder cannot be worked through hair to reach the scalp; gel and foam are used for their low residue."]],
   c=0, cite=c(8)),

 dict(topic="Acne pathogenesis", io=IO2,
   q="Which set gives the four major factors in acne?",
   opts=[
     ["Increased sebum production, altered keratinization with ductal hyperproliferation, bacterial colonization, and release of inflammatory mediators",
      "Correct. Sebum feeds the organism, altered keratinisation plugs the duct, bacterial colonisation follows in the anaerobic environment, and inflammatory mediators produce the visible lesion; each drug class targets one of these."],
     ["Increased sebum production, dermal collagen loss, viral colonization, and complement activation",
      "Collagen loss and viral colonization are not among the four factors given."],
     ["Follicular atrophy, reduced keratinization, fungal overgrowth, and histamine release",
      "Keratinisation increases rather than decreases, the follicle is plugged rather than atrophic, and the organism is bacterial rather than fungal."],
     ["Androgen deficiency, barrier dysfunction, immunoglobulin E elevation, and mast cell degranulation",
      "Barrier dysfunction and raised immunoglobulin E belong to the atopic dermatitis section."]],
   c=0, cite=c(10)),

 dict(topic="Acne pathogenesis", io=IO2,
   q="Which organism is named as proliferating in the anaerobic conditions created by pooled sebum?",
   opts=[
     ["Propionibacterium acnes",
      "Correct. Pooled sebum creates anaerobic conditions in which this organism proliferates."],
     ["Staphylococcus aureus",
      "Staphylococcus aureus is a skin pathogen but is aerobic and is not the organism of the acne follicle."],
     ["Malassezia furfur",
      "Malassezia furfur is a yeast, responsible for pityriasis versicolor rather than for acne."],
     ["Streptococcus pyogenes",
      "Streptococcus pyogenes causes impetigo and cellulitis, not the anaerobic colonisation of the pilosebaceous unit."]],
   c=0, cite=c(12)),

 dict(topic="Acne pathogenesis", io=IO2,
   q="What does bacterial lipase do in the acne cascade?",
   opts=[
     ["Hydrolyses triglycerides into free fatty acids",
      "Correct, and those free fatty acids feed the increase in keratinization and microcomedone formation."],
     ["Cleaves keratin so the follicular plug loosens",
      "Keratinisation increases in acne rather than being broken down; the plug forms rather than loosening."],
     ["Converts testosterone to dihydrotestosterone",
      "That conversion appears under azelaic acid's proposed mechanism, not bacterial lipase."],
     ["Digests the sebaceous gland basement membrane",
      "Lipase acts on sebum triglycerides, not on basement membrane; the free fatty acids it releases are what irritate the follicle."]],
   c=0, cite=c(12)),

 dict(topic="Acne pathogenesis", io=IO1,
   q="How are acne lesions divided?",
   opts=[
     ["Noninflammatory as open and closed comedones; inflammatory as papulopustular and nodular lesions",
      "Correct. That split is what decides whether topical or systemic therapy is chosen."],
     ["Noninflammatory as papules; inflammatory as comedones",
      "This reverses the two categories."],
     ["Superficial as pustular; deep as comedonal",
      "The division is by inflammation rather than depth, because that is what decides between topical and systemic therapy."],
     ["Acute as nodular; chronic as comedonal",
      "Acne is a chronic disease throughout; the useful division is inflammatory against noninflammatory, not acute against chronic."]],
   c=0, cite=c(12)),

 dict(topic="Drug-induced acne", io=IO5,
   q="A patient develops pustular inflammation on the trunk a few weeks after starting a systemic corticosteroid. What happens when the steroid is stopped?",
   opts=[
     ["An initial worsening, because inflammation increases",
      "Correct, and warning the patient of this in advance is what stops them abandoning the plan."],
     ["Immediate and complete resolution of the eruption",
      "Withdrawal removes the steroid's immunosuppression, so the eruption flares before it settles rather than clearing at once."],
     ["Conversion of the pustules into open comedones",
      "This transformation is not described."],
     ["No change, because the eruption is independent of the drug",
      "The eruption is drug-induced, and its course follows the drug: stopping it provokes an initial flare as inflammation rebounds."]],
   c=0, cite=c(15)),

 dict(topic="Drug-induced acne", io=IO5,
   q="Which systemic corticosteroid is explicitly excluded from causing drug-induced acne?",
   opts=[
     ["Hydrocortisone",
      "Correct. Hydrocortisone is the one systemic corticosteroid not associated with the acneiform eruption, its low potency being the likely reason."],
     ["Prednisone",
      "Prednisone is named elsewhere as an oral corticosteroid used in therapy, not as the exception here."],
     ["Dexamethasone",
      "Dexamethasone is given as a treatment option, and is not the stated exception."],
     ["Methylprednisolone",
      "This appears in the atopic dermatitis section, not as the exception."]],
   c=0, cite=c(15)),

 dict(topic="Drug-induced acne", io=IO5,
   q="Besides systemic corticosteroids, which drug groups are listed as causing acne?",
   opts=[
     ["Antiepileptics, tuberculostatics and lithium",
      "Correct. Antiepileptics, antituberculous agents and lithium all provoke an acneiform eruption, typically monomorphic and on the trunk rather than the face."],
     ["Beta blockers, thiazides and statins",
      "Beta blockers, thiazides and statins are not acneiform; thiazides cause photosensitivity and statins myopathy."],
     ["Proton pump inhibitors, metformin and warfarin",
      "These are not named as acne-inducing agents."],
     ["Antihistamines, decongestants and montelukast",
      "Sedating antihistamines appear under atopic dermatitis for itching, not as a cause of acne."]],
   c=0, cite=c(15)),

 dict(topic="Acne treatment principles", io=IO3,
   q="Which structure is identified as the critical target of acne treatment?",
   opts=[
     ["The microcomedone",
      "Correct. Eliminating follicular occlusion at the microcomedone arrests the cascade."],
     ["The mature nodule",
      "The nodule is the end point of the cascade; treatment aims upstream at the microcomedone that starts it."],
     ["The sebaceous gland acinus",
      "Sebum production is one of the four factors, but the microcomedone is the named target."],
     ["The dermal papilla",
      "The dermal papilla belongs to the hair growth cycle, not to the pilosebaceous occlusion that drives acne."]],
   c=0, cite=c(17)),

 dict(topic="Acne treatment principles", io=IO3,
   q="How is topical therapy separated from systemic therapy in acne?",
   opts=[
     ["Topical for mild to moderate disease, systemic for moderate to severe",
      "Correct. Severity is what moves a patient onto systemic therapy."],
     ["Topical for inflammatory disease, systemic for comedonal disease",
      "This inverts it; comedonal disease is where topical retinoid therapy is first line."],
     ["Topical for adults, systemic for adolescents",
      "Age does not set the route; severity does, with topical therapy for mild to moderate and systemic for moderate to severe disease."],
     ["Topical for the face, systemic for the trunk",
      "Site is not what determines the route here."]],
   c=0, cite=c(17)),

 dict(topic="Acne treatment principles", io=IO10,
   q="What are patients advised about washing in acne?",
   opts=[
     ["Do not wash too frequently; twice a day, balancing cleanliness against drying and irritation",
      "Correct, and it adds that once rinsed off no active product remains on the skin."],
     ["Wash as often as possible to remove surface oils",
      "Excessive scrubbing and washing is listed as a contributory factor, so this would worsen the disease."],
     ["Use a high pH soap to maximise degreasing",
      "A high pH may degrade the activity of other agents and is less tolerable on the skin."],
     ["Avoid washing the affected area entirely while on treatment",
      "Cleansing is part of non-pharmacologic therapy rather than something to avoid."]],
   c=0, cite=c(18)),

 dict(topic="Topical therapy principles", io=IO10,
   q="Why should topical acne therapy be applied to the whole affected area rather than to individual spots?",
   opts=[
     ["Topical therapy only works where it is applied",
      "Correct, and that is why the whole affected area is treated rather than visible lesions alone."],
     ["Spot application increases the risk of systemic absorption",
      "Whole-area application increases the treated surface, so it would if anything raise absorption; the reason is that untreated follicles keep forming microcomedones."],
     ["The vehicle is only stable when spread thinly over a wide area",
      "Vehicle stability is a formulation consideration, not the reason for whole-area application."],
     ["Individual lesions are already resolving by the time they are visible",
      "Visible lesions are the end of a process that began weeks earlier, so treating only them leaves the forming microcomedones untouched."]],
   c=0, cite=c(19)),

 dict(topic="Topical therapy principles", io=IO10,
   q="Most topical acne agents cause skin irritation. What does that lead to, and how should therapy be started?",
   opts=[
     ["It can lead to patient discontinuation, so start with lower strength and increase gradually",
      "Correct. Anticipating the irritation is what keeps a patient on therapy."],
     ["It confirms the drug is working, so maintain the starting strength",
      "Irritation is a barrier to adherence rather than a sign of efficacy, and holding the starting strength is what makes patients stop."],
     ["It requires an immediate switch to systemic therapy",
      "Severity, not irritation, is what moves a patient to systemic therapy."],
     ["It is prevented entirely by using an alcoholic solution",
      "Alcoholic solutions are more irritating, not less; a non-alcoholic vehicle is the option to consider when irritation is a problem."]],
   c=0, cite=c(19)),

 dict(topic="Benzoyl peroxide", io=IO2,
   q="What happens to benzoyl peroxide after it penetrates the stratum corneum?",
   opts=[
     ["It is converted to benzoic acid, which is active against Propionibacterium acnes",
      "Correct. It crosses unchanged and is converted once through."],
     ["It is converted to salicylic acid, which is keratinolytic",
      "Salicylic acid is a separate keratinolytic agent; benzoyl peroxide is converted to benzoic acid."],
     ["It is converted to retinoic acid, which corrects keratinization",
      "Retinoic acid is the acid form of vitamin A and belongs to the retinoid section."],
     ["It remains unchanged and works purely by oxidising sebum",
      "It does not act unchanged; it crosses the stratum corneum and is then converted to benzoic acid, which is the antibacterial form."]],
   c=0, cite=c(21)),

 dict(topic="Benzoyl peroxide", io=IO10,
   q="Which adverse effect of benzoyl peroxide most needs to be raised with a patient before they start it?",
   opts=[
     ["It can bleach hair, clothing and bedding",
      "Correct. This is the practical warning that prevents a patient ruining clothes and abandoning the drug."],
     ["It causes a permanent blue-grey discolouration of the skin",
      "The discolouration is bleaching of hair and fabric rather than any permanent change in skin pigment."],
     ["It commonly causes systemic hypersensitivity reactions",
      "The adverse effects are local irritation of skin and mucous membranes; systemic hypersensitivity is not a feature."],
     ["It stains the skin orange for the duration of therapy",
      "Benzoyl peroxide is an oxidising agent that bleaches rather than stains, which is why it ruins coloured towels and bedding."]],
   c=0, cite=c(21)),

 dict(topic="Azelaic acid", io=IO2,
   q="What are the two proposed actions of azelaic acid?",
   opts=[
     ["Antimicrobial activity and inhibition of the conversion of testosterone to dihydrotestosterone",
      "Correct. Azelaic acid is antimicrobial against Propionibacterium acnes and inhibits the conversion of testosterone to dihydrotestosterone, although its mechanism is not fully established."],
     ["Inhibition of fungal cell wall formation and keratinolysis",
      "Fungal cell wall inhibition belongs to the azole antifungals."],
     ["Conversion to benzoic acid and comedolysis",
      "That is benzoyl peroxide's route."],
     ["Inhibition of T cell activation and mast cell stabilisation",
      "That is the topical immunomodulator mechanism."]],
   c=0, cite=c(22)),

 dict(topic="Azelaic acid", io=IO10,
   q="A patient starting azelaic acid asks how long before it works. What should they be told?",
   opts=[
     ["Improvement occurs over six to eight weeks with continuous therapy",
      "Correct, and setting that expectation is what prevents early abandonment."],
     ["Improvement should be obvious within the first week",
      "One week is far too soon; azelaic acid needs six to eight weeks of continuous use, and expecting faster results leads patients to abandon it."],
     ["It works only after a course of oral antibiotics has finished",
      "No such sequencing is described."],
     ["It should be stopped once irritation appears",
      "Mild irritation and dryness are expected adverse reactions rather than stopping points."]],
   c=0, cite=c(22)),

 dict(topic="Azelaic acid", io=IO5,
   q="Which pigmentary adverse effect is attached to azelaic acid?",
   opts=[
     ["Hypopigmentation",
      "Correct. It is listed with mild skin irritation and dryness."],
     ["Hyperpigmentation of sun-exposed areas",
      "Azelaic acid lightens rather than darkens the skin, which is why it is also used for post-inflammatory hyperpigmentation."],
     ["Slate-grey discolouration of the nail beds",
      "This is not described for azelaic acid."],
     ["Yellow staining of the sclera",
      "No ocular pigment change is attributed to this agent."]],
   c=0, cite=c(22)),

 dict(topic="Topical retinoids", io=IO3,
   q="For which form of acne is a topical retinoid first line?",
   opts=[
     ["Noninflammatory, comedonal acne",
      "Correct, and for inflammatory acne it is often combined with other agents rather than used alone."],
     ["Nodular acne with scarring",
      "That severity is where systemic therapy, including isotretinoin, is considered."],
     ["Acne associated with adrenal hyperactivity",
      "Adrenal hyperactivity is addressed with low-dose oral corticosteroid therapy; the retinoid's first-line role is in comedonal disease."],
     ["Drug-induced acne from systemic corticosteroids",
      "Drug-induced acne is managed by addressing the offending drug; the retinoid is first line in ordinary comedonal acne."]],
   c=0, cite=c(23)),

 dict(topic="Topical retinoids", io=IO2,
   q="Which three actions are attributed to topical retinoic acid?",
   opts=[
     ["Corrects abnormal follicular keratinization, reduces Propionibacterium acnes counts, and reduces inflammation",
      "Correct. Retinoic acid normalises follicular keratinisation so the plug does not form, lowers Propionibacterium acnes counts and damps inflammation, which is why it covers both lesion types."],
     ["Dissolves existing comedones, blocks androgen receptors, and thins the epidermis",
      "Androgen receptor blockade belongs to the antiandrogen section."],
     ["Converts to benzoic acid, bleaches the skin, and reduces sebum",
      "Conversion to benzoic acid is benzoyl peroxide."],
     ["Inhibits fungal ergosterol, reduces scaling, and stimulates interferon",
      "Ergosterol inhibition is the allylamines and interferon stimulation is imiquimod."]],
   c=0, cite=c(23)),

 dict(topic="Topical retinoids", io=IO7,
   q="Which patient should not be given a topical retinoid?",
   opts=[
     ["A patient who is pregnant",
      "Correct. Retinoids are vitamin A derivatives and teratogenic, so they are avoided in pregnancy even by the topical route."],
     ["A patient with a history of eczema",
      "Eczema is not given as a contraindication to topical retinoid therapy."],
     ["A patient taking an oral contraceptive",
      "Oral contraceptives are listed as a useful acne therapy in some women, not a conflict."],
     ["A patient over sixty years of age",
      "Age is no bar; topical retinoids are used in older patients for wrinkles and dyspigmentation as well as for acne."]],
   c=0, cite=c(24)),

 dict(topic="Topical retinoids", io=IO10,
   q="Why should tretinoin be applied at night?",
   opts=[
     ["It is photolabile",
      "Correct. Being degraded by light is the reason for nightly application, distinct from the photosensitivity it also causes."],
     ["Sebum production peaks overnight",
      "Sebum timing is not the issue; tretinoin is degraded by light, so daytime application destroys the drug."],
     ["It stains clothing if applied during the day",
      "Bleaching of clothing belongs to benzoyl peroxide."],
     ["It must be applied at the same time as benzoyl peroxide",
      "Benzoyl peroxide inactivates tretinoin, so they are not applied together."]],
   c=0, cite=c(24)),

 dict(topic="Topical retinoids", io=IO8,
   q="Which interaction is described between benzoyl peroxide and tretinoin?",
   opts=[
     ["Benzoyl peroxide inactivates tretinoin",
      "Correct, and it is why adapalene, which is stable with benzoyl peroxide, is highlighted separately."],
     ["Benzoyl peroxide increases tretinoin absorption to toxic levels",
      "Benzoyl peroxide oxidises and inactivates tretinoin rather than increasing its absorption, so the pair applied together does less, not more."],
     ["Tretinoin prevents benzoyl peroxide from converting to benzoic acid",
      "The direction is the reverse: benzoyl peroxide inactivates tretinoin, which is why adapalene, stable alongside it, is preferred in combination."],
     ["The two together cause systemic hypervitaminosis A",
      "No systemic vitamin A toxicity is described from this pairing."]],
   c=0, cite=c(24)),

 dict(topic="Topical retinoids", io=IO1,
   q="Which two properties are used to distinguish adapalene from tretinoin?",
   opts=[
     ["Adapalene is stable in sunlight and stable with benzoyl peroxide",
      "Correct, and it also tends to be less irritating."],
     ["Adapalene is a systemic agent and requires pregnancy testing",
      "Adapalene is a topical retinoid; the pregnancy programme belongs to isotretinoin."],
     ["Adapalene is used only for psoriasis rather than acne",
      "Tazarotene is the retinoid used for both acne and psoriasis; adapalene is distinguished by its stability in light and with benzoyl peroxide."],
     ["Adapalene must be applied only at night because it is photolabile",
      "This describes tretinoin; adapalene is the photostable one, which is precisely what separates them."]],
   c=0, cite=c(25)),

 dict(topic="Topical retinoids", io=IO3,
   q="Which retinoid is paired with Kaposi sarcoma?",
   opts=[
     ["Alitretinoin",
      "Correct. Bexarotene is the one paired with T-cell lymphoma."],
     ["Bexarotene",
      "Bexarotene is paired with cutaneous T-cell lymphoma; alitretinoin is the one used for Kaposi sarcoma."],
     ["Tazarotene",
      "Tazarotene is used for acne and psoriasis."],
     ["Adapalene",
      "Adapalene is an acne agent notable for its stability."]],
   c=0, cite=c(25)),

 dict(topic="Topical antibiotics for acne", io=IO1,
   q="Which topical antibiotic is named as the preferred agent for acne, and what is happening to the alternative?",
   opts=[
     ["Clindamycin is preferred; erythromycin is losing efficacy to Propionibacterium acnes resistance",
      "Correct, and both are noted to lack systemic side effects."],
     ["Erythromycin is preferred; clindamycin is losing efficacy to resistance",
      "This reverses the two: clindamycin is preferred, and it is erythromycin whose usefulness is being eroded by Propionibacterium acnes resistance."],
     ["Mupirocin is preferred; bacitracin is losing efficacy",
      "Those two belong to the other topical antibiotics section, not to acne."],
     ["Neomycin is preferred; polymyxin B is losing efficacy",
      "Neomycin is noted for causing sensitisation and is not the acne agent."]],
   c=0, cite=c(26)),

 dict(topic="Isotretinoin", io=IO7,
   q="What is true of isotretinoin and pregnancy?",
   opts=[
     ["It is contraindicated in pregnancy and breastfeeding, and men should avoid it as well",
      "Correct, and the iPledge programme exists around exactly this risk."],
     ["It is safe in the second and third trimesters",
      "It is contraindicated, without a safe window."],
     ["It is contraindicated only in the first trimester",
      "There is no safe trimester; isotretinoin is teratogenic throughout, which is why contraception is required before, during and after the course."],
     ["It requires no pregnancy precautions because it is applied topically",
      "Isotretinoin here is the systemic retinoid, not a topical agent."]],
   c=0, cite=c(27)),

 dict(topic="Isotretinoin", io=IO5,
   q="Which laboratory change is listed among isotretinoin's adverse reactions?",
   opts=[
     ["Increased serum lipids",
      "Correct, and it sits alongside retinoid dermatitis, photophobia, arthralgia, headaches, alopecia and brittle nails."],
     ["Reduced serum calcium",
      "No calcium effect is described for isotretinoin."],
     ["Raised serum immunoglobulin E",
      "Raised immunoglobulin E is a minor indicator of atopic dermatitis."],
     ["Reduced white cell count",
      "Isotretinoin does not suppress the white cell count; the laboratory change to watch is a rise in serum lipids."]],
   c=0, cite=c(27)),

 dict(topic="Isotretinoin", io=IO10,
   q="Which psychiatric issue should be monitored for during isotretinoin therapy?",
   opts=[
     ["Signs of developing depression",
      "Correct. Depression, and rarely suicidal ideation, has been reported with isotretinoin, so mood is checked at each review."],
     ["New-onset mania",
      "Mania is not the reported association; depression and rarely suicidal ideation are what monitoring targets."],
     ["Auditory hallucinations",
      "This is not among the monitoring points given."],
     ["Obsessive-compulsive symptoms",
      "Obsessive-compulsive symptoms are not an isotretinoin association; depression is the mood change monitored for."]],
   c=0, cite=c(27)),

 dict(topic="Systemic antibiotics for acne", io=IO2,
   q="What is the anti-inflammatory action of tetracyclines in acne?",
   opts=[
     ["They chelate calcium ions, which prevents neutrophil and monocyte chemotaxis",
      "Correct. That is an anti-inflammatory action separate from killing the organism."],
     ["They stabilise mast cell membranes and block histamine release",
      "Mast cell activation is addressed by the topical immunomodulators."],
     ["They inhibit the conversion of testosterone to dihydrotestosterone",
      "That is proposed for azelaic acid."],
     ["They stimulate macrophages to release tumour necrosis factor alpha",
      "That is imiquimod's mechanism."]],
   c=0, cite=c(28)),

 dict(topic="Systemic antibiotics for acne", io=IO7,
   q="Which two groups are contraindicated from receiving tetracyclines?",
   opts=[
     ["Children under eight years and pregnant women",
      "Correct. Tetracyclines chelate calcium and deposit in developing teeth and bone, staining teeth permanently in children under eight and crossing the placenta in pregnancy."],
     ["Adolescents and the elderly",
      "Adolescents are the population most often treated for acne, not a contraindicated group."],
     ["Patients with eczema and patients with psoriasis",
      "Neither condition is given as a contraindication to tetracyclines."],
     ["Patients taking oral contraceptives and patients on spironolactone",
      "Both are acne therapies rather than contraindications; the contraindicated groups are children under eight and pregnant women."]],
   c=0, cite=c(28)),

 dict(topic="Other acne therapies", io=IO1,
   q="Which antiandrogen is named for acne?",
   opts=[
     ["Spironolactone",
      "Correct. Spironolactone blocks the androgen receptor, reducing sebum production, and is available as a gel as well as orally."],
     ["Finasteride",
      "Finasteride inhibits five-alpha-reductase and is used for androgenetic alopecia and prostatic hyperplasia rather than acne."],
     ["Ketoconazole",
      "Ketoconazole appears here as a topical azole antifungal."],
     ["Cyproterone",
      "Cyproterone is an antiandrogen used elsewhere, but spironolactone is the agent used for acne here."]],
   c=0, cite=c(29)),

 dict(topic="Other acne therapies", io=IO5,
   q="Which two problems are attached to intralesional steroid injection of an inflammatory nodule?",
   opts=[
     ["Systemic absorption leading to adrenal suppression, and local tissue atrophy",
      "Correct. Both are consequences of injecting a steroid into the lesion."],
     ["Permanent hyperpigmentation and keloid formation",
      "Neither follows from the injection; the concerns are systemic absorption with adrenal suppression and local tissue atrophy at the site."],
     ["Bleaching of hair and clothing",
      "That belongs to benzoyl peroxide."],
     ["Photosensitivity and severe sunburn",
      "That belongs to the topical retinoids."]],
   c=0, cite=c(30)),
]
