# Pharmacology I Lecture 1 — Antivirals, pool part A
# Syllabus objectives 5 through 8: anti-herpes, anti-cytomegalovirus and
# anti-influenza agents. Note the printed syllabus numbers these oddly --
# objective 5 introduces the antivirals and the three classes then appear as
# top-level items 6, 7 and 8 rather than 5a to 5c.
#
# Correct answer always written first; the partition script rotates.
# No dosage recall -- Dr. Wood does not test dosages. Bioavailability is asked
# as a COMPARISON (prodrug versus parent) rather than as a percentage to recall.
SRC = "Antibiotics, Antivirals, and Antifungals.pptx"
def c(n): return f"{SRC}, Slide {n}"

IO5 = "Objective 5 — Antiviral classes"
IO6 = "Objective 6 — Anti-herpes agents"
IO7 = "Objective 7 — Anti-cytomegalovirus agents"
IO8 = "Objective 8 — Anti-influenza agents"

POOL_A = [
 dict(topic="Principles", io=IO5,
   q="Which approaches to antiviral therapy does the lecture list?",
   opts=[
     ["Blocking attachment and uncoating, inhibiting nucleic acid and protein synthesis, inhibiting specific viral enzymes, blocking assembly and release, and stimulating the host immune system",
      "Correct. Every agent in this lecture maps onto one of these — acyclovir onto nucleic acid synthesis, oseltamivir onto viral release."],
     ["Blocking bacterial cell wall synthesis, ribosomal binding, and folate metabolism",
      "Those are antibacterial strategies and have no viral equivalent."],
     ["Disrupting the ergosterol membrane, inhibiting glucan synthesis, and blocking mitosis",
      "Those are the antifungal strategies."],
     ["Chelating metal ions, alkalinising the urine, and inducing hepatic enzymes",
      "None of these appears among the antiviral approaches."]],
   c=0, cite=c(118)),

 dict(topic="Herpesviruses", io=IO6,
   q="Which sites does herpes simplex type 1 characteristically affect?",
   opts=[
     ["Mouth, face, skin, oesophagus or brain",
      "Correct. Type 2 covers genitals, rectum, hands or meninges — the split is anatomical rather than absolute."],
     ["Genitals, rectum, hands or meninges",
      "Those are the type 2 sites."],
     ["Retina, oesophagus and colon",
      "Those are cytomegalovirus manifestations."],
     ["Skin in a dermatomal distribution following chickenpox",
      "That describes varicella-zoster reactivation as shingles."]],
   c=0, cite=c(119)),

 dict(topic="Herpesviruses", io=IO6,
   q="Which sites does herpes simplex type 2 characteristically affect?",
   opts=[
     ["Genitals, rectum, hands or meninges",
      "Correct, against type 1's mouth, face, skin, oesophagus or brain."],
     ["Mouth, face, skin, oesophagus or brain",
      "Those are the type 1 sites."],
     ["Retinitis, oesophagitis and colitis",
      "Those are cytomegalovirus manifestations."],
     ["Liver, spleen and bone marrow",
      "Those are not the sites the lecture gives for type 2."]],
   c=0, cite=c(119)),

 dict(topic="Herpesviruses", io=IO7,
   q="Which manifestations does the lecture attribute to cytomegalovirus?",
   opts=[
     ["Retinitis, oesophagitis and colitis",
      "Correct, and they occur chiefly in transplant recipients and other immunocompromised patients."],
     ["Chickenpox and shingles",
      "Those are varicella-zoster."],
     ["Cold sores and genital ulceration",
      "Those are herpes simplex types 1 and 2."],
     ["Influenza-like illness with fever and myalgia",
      "That is influenza, treated with oseltamivir."]],
   c=0, cite=c(119)),

 dict(topic="Herpesviruses", io=IO6,
   q="Which two conditions does varicella-zoster virus cause?",
   opts=[
     ["Chickenpox and shingles",
      "Correct — primary infection and later reactivation of the same virus."],
     ["Cold sores and genital ulceration",
      "Those are herpes simplex types 1 and 2."],
     ["Retinitis and colitis",
      "Those are cytomegalovirus manifestations."],
     ["Infectious mononucleosis and hepatitis",
      "Neither is attributed to varicella-zoster here."]],
   c=0, cite=c(119)),

 dict(topic="Acyclovir", io=IO6,
   q="How does acyclovir achieve selectivity for infected cells?",
   opts=[
     ["It is selectively phosphorylated by viral thymidine kinase, so it is only activated where the virus is replicating",
      "Correct. Selectivity comes from an enzyme the virus supplies, which is the cleanest form of selective toxicity in this lecture."],
     ["It is concentrated by a transporter expressed only on infected cells",
      "The lecture attributes selectivity to viral thymidine kinase, not to a transporter."],
     ["It binds a viral capsid protein that has no human counterpart",
      "The mechanism given is phosphorylation followed by incorporation into viral DNA."],
     ["It is activated only at the low pH found inside infected cells",
      "No pH-dependent activation is described."]],
   c=0, cite=c(121)),

 dict(topic="Acyclovir", io=IO6,
   q="Once phosphorylated and incorporated into viral DNA, how does acyclovir stop replication?",
   opts=[
     ["It is a guanine analogue lacking the sugar moiety, so the chain cannot elongate past it",
      "Correct — chain termination by a missing sugar, which is a structural rather than an enzymatic block."],
     ["It cross-links the two DNA strands so they cannot separate",
      "Cross-linking is not the mechanism described."],
     ["It causes helical structure loss and strand breakage",
      "That is metronidazole's effect on bacterial DNA."],
     ["It inhibits DNA gyrase and prevents supercoiling",
      "That is the fluoroquinolone mechanism in bacteria."]],
   c=0, cite=c(121)),

 dict(topic="Acyclovir", io=IO6,
   q="Which infections are acyclovir and valacyclovir indicated for?",
   opts=[
     ["Herpes simplex and varicella-zoster",
      "Correct. Cytomegalovirus requires ganciclovir or valganciclovir instead."],
     ["Cytomegalovirus retinitis in transplant recipients",
      "That is the ganciclovir and valganciclovir indication."],
     ["Influenza A and B",
      "That is oseltamivir."],
     ["Human immunodeficiency virus infection",
      "Antiretroviral therapy is not covered in this lecture."]],
   c=0, cite=c(122)),

 dict(topic="Acyclovir", io=IO6,
   q="Why does valacyclovir achieve substantially higher oral bioavailability than acyclovir?",
   opts=[
     ["It is a prodrug, which is converted after absorption",
      "Correct. The same prodrug strategy explains famciclovir against penciclovir, and valganciclovir against ganciclovir."],
     ["It is given intravenously rather than orally",
      "Both are oral agents; the difference is the prodrug design."],
     ["It resists degradation by stomach acid where acyclovir does not",
      "Acid stability is the property that distinguishes penicillin V, not these agents."],
     ["It is absorbed through a different segment of the bowel",
      "The lecture attributes the difference to the prodrug form."]],
   c=0, cite=c(122)),

 dict(topic="Acyclovir", io=IO6,
   q="Which renal adverse effect is characteristic of acyclovir, and how is it mitigated?",
   opts=[
     ["It crystallises in the renal tubule, so hydration and renal function must be maintained",
      "Correct. Note how this differs from amphotericin B, which damages the tubule directly rather than crystallising in it."],
     ["It causes direct renal tubule damage requiring hydration with normal saline",
      "That is amphotericin B's mechanism of renal injury."],
     ["It causes interstitial nephritis requiring corticosteroids",
      "Interstitial nephritis is listed among the aminopenicillin effects."],
     ["Its intravenous vehicle accumulates in renal failure",
      "That is voriconazole's cyclodextrin problem."]],
   c=0, cite=c(123)),

 dict(topic="Acyclovir", io=IO6,
   q="Which central nervous system effects are listed for acyclovir?",
   opts=[
     ["Seizures, delirium and tremor",
      "Correct, alongside nausea, vomiting, rash and bone marrow suppression."],
     ["Confusion, ataxia, seizures and coma",
      "That fuller list belongs to ganciclovir and valganciclovir."],
     ["Peripheral neuropathy and tendon rupture",
      "Those are fluoroquinolone effects."],
     ["Visual disturbance in about 30 percent of patients",
      "That is voriconazole."]],
   c=0, cite=c(123)),

 dict(topic="Acyclovir", io=IO6,
   q="What does the lecture say about starting acyclovir within the first 24 hours of chickenpox?",
   opts=[
     ["It shortens the acute illness but does not cure the infection",
      "Correct — the virus is not eradicated, which is why reactivation as shingles remains possible later."],
     ["It cures the infection and prevents later reactivation as shingles",
      "The lecture is explicit that it does not cure the infection."],
     ["It has no effect unless combined with valacyclovir",
      "No such combination requirement is given."],
     ["It prevents transmission to contacts but does not alter the illness",
      "The stated benefit is a shorter acute illness."]],
   c=0, cite=c(123)),

 dict(topic="Penciclovir", io=IO6,
   q="How do penciclovir and famciclovir relate to acyclovir?",
   opts=[
     ["They have a similar mechanism and similar actions and toxicity, and are used in herpes simplex and varicella-zoster infection",
      "Correct. Famciclovir is the oral prodrug and penciclovir the intravenous parent, mirroring valacyclovir and acyclovir."],
     ["They act on a completely different target and are used for cytomegalovirus",
      "Cytomegalovirus is the ganciclovir indication; these two share acyclovir's target and indications."],
     ["They inhibit neuraminidase and are used for influenza",
      "That is oseltamivir."],
     ["They are protease inhibitors used in human immunodeficiency virus infection",
      "Antiretroviral agents are not covered in this lecture."]],
   c=0, cite=c(124)),

 dict(topic="Penciclovir", io=IO6,
   q="Which of penciclovir and famciclovir is the oral prodrug?",
   opts=[
     ["Famciclovir, which is oral and considerably better absorbed",
      "Correct. Penciclovir is the intravenous parent with poor oral bioavailability."],
     ["Penciclovir, which is oral and considerably better absorbed",
      "Penciclovir is the intravenous agent with low bioavailability."],
     ["Both are prodrugs of acyclovir",
      "They are their own pair; neither is a prodrug of acyclovir."],
     ["Neither is a prodrug; both are given intravenously",
      "Famciclovir is an orally administered prodrug."]],
   c=0, cite=c(124)),

 dict(topic="Ganciclovir", io=IO7,
   q="Which patients are ganciclovir and valganciclovir indicated for?",
   opts=[
     ["Transplant recipients and immunocompromised patients with cytomegalovirus",
      "Correct. It is a guanine analogue inhibiting in a manner similar to acyclovir, but aimed at a different herpesvirus."],
     ["Otherwise healthy adults with recurrent cold sores",
      "Herpes simplex in an immunocompetent patient is treated with acyclovir or valacyclovir."],
     ["Children with chickenpox within the first 24 hours",
      "That is the acyclovir indication."],
     ["Adults with influenza A within 48 hours of onset",
      "That is oseltamivir."]],
   c=0, cite=c(125)),

 dict(topic="Ganciclovir", io=IO7,
   q="Which haematologic adverse effects limit ganciclovir?",
   opts=[
     ["Neutropenia and thrombocytopenia",
      "Correct, and about a third of patients must stop intravenous treatment because of side effects."],
     ["Megaloblastic anaemia and agranulocytosis from folate antagonism",
      "Those are the sulfamethoxazole/trimethoprim blood dyscrasias."],
     ["Haemolysis triggered by glucose-6-phosphate dehydrogenase deficiency",
      "That mechanism is not discussed for this agent."],
     ["Isolated eosinophilia with no clinical consequence",
      "The effects listed are clinically significant enough to stop treatment."]],
   c=0, cite=c(125)),

 dict(topic="Ganciclovir", io=IO7,
   q="What proportion of patients must stop intravenous ganciclovir because of side effects?",
   opts=[
     ["About a third",
      "Correct — a striking figure, and the reason the better-absorbed oral prodrug matters clinically."],
     ["About 1 in 20",
      "The lecture gives a far higher proportion."],
     ["Almost none; it is generally well tolerated",
      "It is poorly tolerated, which is the point of the slide."],
     ["Essentially all patients",
      "The figure given is around a third rather than universal."]],
   c=0, cite=c(125)),

 dict(topic="Ganciclovir", io=IO7,
   q="Which central nervous system effects are listed for ganciclovir?",
   opts=[
     ["Confusion, ataxia, seizures and coma",
      "Correct, occurring in a minority of patients alongside the haematologic effects."],
     ["Seizures, delirium and tremor only",
      "That shorter list is acyclovir's."],
     ["Peripheral neuropathy and tendon injury",
      "Those are fluoroquinolone effects."],
     ["Blurred vision and mental confusion from enzyme induction",
      "That profile belongs to griseofulvin."]],
   c=0, cite=c(125)),

 dict(topic="Ganciclovir", io=IO7,
   q="Which of ganciclovir and valganciclovir is the better-absorbed oral form?",
   opts=[
     ["Valganciclovir, the prodrug",
      "Correct. Ganciclovir's oral bioavailability is very low, which is why the prodrug exists."],
     ["Ganciclovir, the parent compound",
      "Ganciclovir is the poorly absorbed parent."],
     ["Both are equally absorbed",
      "The prodrug is substantially better absorbed."],
     ["Neither is absorbed orally; both are intravenous only",
      "Valganciclovir is an oral agent."]],
   c=0, cite=c(125)),

 dict(topic="Oseltamivir", io=IO8,
   q="What is oseltamivir's mechanism of action?",
   opts=[
     ["It inhibits influenza virus neuraminidase, preventing budding progeny from being cleaved free of the host cell",
      "Correct — it blocks viral release rather than viral entry or replication."],
     ["It blocks viral attachment to the host cell receptor",
      "Attachment blockade is one of the general approaches listed, but not oseltamivir's mechanism."],
     ["It is a guanine analogue that terminates the viral nucleic acid chain",
      "That is the acyclovir family's mechanism."],
     ["It inhibits a viral protease, preventing cleavage of polypeptide precursors",
      "Protease inhibition is not this agent's mechanism."]],
   c=0, cite=c(126)),

 dict(topic="Oseltamivir", io=IO8,
   q="Within what window must oseltamivir be started?",
   opts=[
     ["As soon as possible, within 48 hours of symptom onset",
      "Correct. Because it blocks release rather than killing virus already present, late treatment has little to act on."],
     ["Within 7 days of symptom onset",
      "The stated window is considerably shorter."],
     ["Within the first 24 hours, as with acyclovir in chickenpox",
      "The 24-hour figure belongs to acyclovir in chickenpox; oseltamivir's window is 48 hours."],
     ["At any point during the illness, with equal benefit",
      "Timing is central to its effectiveness."]],
   c=0, cite=c(126)),

 dict(topic="Oseltamivir", io=IO8,
   q="Which viruses does oseltamivir target, and in what season?",
   opts=[
     ["Influenza A and B, in a season running roughly October to March",
      "Correct, and resistance has been becoming a problem over time."],
     ["Influenza A only, year-round",
      "It targets both A and B, and the lecture gives a defined season."],
     ["Herpes simplex and varicella-zoster, year-round",
      "Those are the acyclovir family's targets."],
     ["Cytomegalovirus in transplant recipients",
      "That is the ganciclovir indication."]],
   c=0, cite=c(126)),

 dict(topic="Oseltamivir", io=IO8,
   q="What kind of compound is oseltamivir as administered?",
   opts=[
     ["A prodrug converted to its carboxylate form",
      "Correct — another prodrug in a lecture full of them, alongside valacyclovir, famciclovir and valganciclovir."],
     ["An active guanine analogue requiring no conversion",
      "It requires conversion, and it is not a guanine analogue."],
     ["A monoclonal antibody against viral haemagglutinin",
      "No antibody therapy is described here."],
     ["A live attenuated preparation",
      "That would describe a vaccine rather than an antiviral drug."]],
   c=0, cite=c(126)),

 dict(topic="Oseltamivir", io=IO8,
   q="What route and dosing consideration apply to oseltamivir?",
   opts=[
     ["Available orally only, and requiring renal dose adjustment",
      "Correct. Renal adjustment is a consideration rather than a dose to memorise."],
     ["Available intravenously only, with hepatic adjustment",
      "It is an oral agent and the adjustment named is renal."],
     ["Available orally and intravenously, with no adjustment needed",
      "It is oral only, and renal adjustment is required."],
     ["Available as an inhaled powder only",
      "Inhaled administration is not described for this agent."]],
   c=0, cite=c(127)),

 dict(topic="Oseltamivir", io=IO8,
   q="What does the lecture note about oseltamivir resistance?",
   opts=[
     ["It has been becoming a problem over time",
      "Correct — the same trajectory the antibacterial section describes for the fluoroquinolones."],
     ["Resistance has never been reported",
      "The lecture states resistance is becoming a problem."],
     ["Resistance is prevented entirely by starting within 48 hours",
      "Early treatment improves efficacy but is not a resistance strategy."],
     ["Resistance occurs only in influenza B",
      "No such restriction is stated."]],
   c=0, cite=c(126)),

 dict(topic="Principles", io=IO5,
   q="Several antivirals in this lecture are prodrugs. Which set is correct?",
   opts=[
     ["Valacyclovir, famciclovir, valganciclovir and oseltamivir",
      "Correct. Improving oral absorption is a recurring design theme across the whole antiviral section."],
     ["Acyclovir, penciclovir, ganciclovir and zanamivir",
      "Those are parent compounds rather than prodrugs."],
     ["Amphotericin B, caspofungin and griseofulvin",
      "Those are antifungals, and none is described as a prodrug."],
     ["Metronidazole, linezolid and daptomycin",
      "Those are antibacterials outside this objective."]],
   c=0, cite=c(122)),

 dict(topic="Principles", io=IO5,
   q="Which antiviral approach does oseltamivir represent?",
   opts=[
     ["Inhibiting viral release",
      "Correct — neuraminidase frees budding progeny, so blocking it traps new virus at the cell surface."],
     ["Blocking viral attachment to cells",
      "Attachment blockade is a listed approach but not this drug's."],
     ["Inhibiting nucleic acid synthesis",
      "That is the acyclovir family's approach."],
     ["Stimulating the host immune system",
      "That approach is listed but is not oseltamivir's mechanism."]],
   c=0, cite=c(118)),

 dict(topic="Principles", io=IO5,
   q="Which antiviral approach does the acyclovir family represent?",
   opts=[
     ["Inhibiting nucleic acid synthesis",
      "Correct — the drug is incorporated into viral DNA and terminates the chain."],
     ["Inhibiting viral release",
      "That is oseltamivir's approach."],
     ["Blocking uncoating after entry",
      "Uncoating blockade is a listed approach but not this family's."],
     ["Inhibiting viral assembly",
      "Assembly inhibition is listed separately from nucleic acid synthesis."]],
   c=0, cite=c(118)),

 dict(topic="Acyclovir", io=IO6,
   q="Which non-neurologic adverse effects are listed for acyclovir?",
   opts=[
     ["Nausea, vomiting, rash and bone marrow suppression",
      "Correct, with hydration and renal function to be maintained because of tubular crystallisation."],
     ["Neutropenia and thrombocytopenia as the dominant effects",
      "Those are the ganciclovir effects."],
     ["Photosensitivity and tooth discoloration",
      "Those are tetracycline effects."],
     ["Disulfiram-like reaction with ethanol",
      "That belongs to metronidazole."]],
   c=0, cite=c(123)),

 dict(topic="Herpesviruses", io=IO6,
   q="Which herpesviruses does this lecture group together as targets for antiviral therapy?",
   opts=[
     ["Herpes simplex, varicella-zoster and cytomegalovirus",
      "Correct — the first two share the acyclovir family, while cytomegalovirus needs ganciclovir."],
     ["Herpes simplex and influenza A only",
      "Influenza is not a herpesvirus and is treated with oseltamivir."],
     ["Cytomegalovirus and human immunodeficiency virus",
      "Antiretroviral therapy is outside this lecture."],
     ["Varicella-zoster and hepatitis B",
      "Hepatitis is not covered here."]],
   c=0, cite=c(119)),
]
