# -*- coding: utf-8 -*-
"""Rapid-drill bank: dermatology medications.
Same rule as tools/pharm_drill_antibacterials.py."""
ITEMS = [
dict(q="Which acne treatment bleaches hair and clothing?",
     ans="Benzoyl peroxide", src=("L2", 21),
     why="It bleaches hair and clothes — the practical warning every patient needs before the first application.",
     wrong=[("Azelaic acid", "Causes mild irritation and dryness, and can HYPOpigment the skin — a different problem."),
            ("Tretinoin", "Causes erythema, peeling and photosensitivity."),
            ("Clindamycin", "A topical antibiotic, with no bleaching.")]),

dict(q="Which topical acne agent can cause hypopigmentation?",
     ans="Azelaic acid", src=("L2", 22),
     why="Hypopigmentation alongside mild irritation and dryness.",
     wrong=[("Benzoyl peroxide", "Bleaches hair and fabric, but the skin effect described is irritation."),
            ("Adapalene", "A retinoid — erythema and peeling."),
            ("Erythromycin", "A topical antibiotic.")]),

dict(q="Which oral acne drug causes retinoid dermatitis, photophobia and raised serum lipids?",
     ans="Isotretinoin", src=("L2", 27),
     why="Retinoid dermatitis, photophobia, arthralgia, headache, alopecia, brittle nails and raised lipids.",
     wrong=[("Doxycycline", "Photosensitivity and gastrointestinal upset, not this cluster."),
            ("Spironolactone", "An antiandrogen used in some women."),
            ("Benzoyl peroxide", "Topical, and it bleaches fabric.")]),

dict(q="Which class must be avoided in pregnancy and causes photosensitivity and severe sunburn?",
     ans="Topical retinoids", src=("L2", 24),
     why="Tretinoin, adapalene and tazarotene — photosensitivity, severe sunburn, and avoided in pregnancy.",
     wrong=[("Benzoyl peroxide", "Not the agent carrying the pregnancy restriction."),
            ("Azelaic acid", "Not the agent carrying it."),
            ("Bacitracin", "A topical antibiotic with no systemic issue.")]),

dict(q="The erythema, desquamation, burning and stinging from topical retinoids do what over time?",
     ans="Decrease with time and with emollients", src=("L2", 24),
     why="They settle — which is exactly what the patient must be told, or they stop the drug in week two.",
     wrong=[("Worsen steadily until the drug is stopped", "Not what happens; the skin adapts."),
            ("Are unaffected by emollients", "Emollients are specifically recommended."),
            ("Indicate an allergic reaction", "They are expected irritation, not allergy.")]),

dict(q="Which topical antibiotic is preferred for acne, though it is losing efficacy to resistance?",
     ans="Clindamycin", src=("L2", 23),
     why="The preferred topical antibiotic, with efficacy falling over time because of Propionibacterium acnes resistance.",
     wrong=[("Erythromycin", "Also used, but clindamycin is named as preferred."),
            ("Mupirocin", "Used for staphylococcal skin infection and nasal carriage."),
            ("Bacitracin", "Used for minor wounds.")]),

dict(q="Which drugs are used as antiandrogens for acne in some women?",
     ans="Spironolactone", src=("L2", 29),
     why="Useful in some women, working on the hormonal driver rather than the follicle.",
     wrong=[("Isotretinoin", "Used in severe acne but not as an antiandrogen."),
            ("Doxycycline", "An antibiotic."),
            ("Adapalene", "A topical retinoid.")]),

dict(q="Local tissue atrophy and adrenal suppression, with the need to taper to prevent a flare, belong to which acne treatment?",
     ans="Corticosteroids", src=("L2", 30),
     why="Atrophy locally, adrenal suppression systemically, and tapering to prevent rebound.",
     wrong=[("Topical retinoids", "Cause irritation, not atrophy or adrenal suppression."),
            ("Benzoyl peroxide", "Bleaching and irritation."),
            ("Azelaic acid", "Irritation and hypopigmentation.")]),

dict(q="Skin atrophy, acne, rosacea and allergic dermatitis are the LOCAL effects of which class?",
     ans="Topical corticosteroids", src=("L2", 39),
     why="The local list. Systemically they can suppress the adrenal axis, raise glucose, and cause glaucoma, cataracts and growth retardation in children.",
     wrong=[("Topical retinoids", "Cause erythema and peeling that settles."),
            ("Topical immunomodulators", "Cause a burning sensation."),
            ("Topical antifungals", "Rarely cause local reaction.")]),

dict(q="Glaucoma, cataracts and growth retardation in children are SYSTEMIC risks of which class?",
     ans="Topical corticosteroids", src=("L2", 39),
     why="Absorbed steroid produces systemic effects — which is why potency and duration are limited, especially in children.",
     wrong=[("Topical antifungals", "Negligible absorption."),
            ("Benzoyl peroxide", "No systemic effect."),
            ("Mupirocin", "No systemic effect.")]),

dict(q="Which agents are second-line for atopic dermatitis, after topical steroids, and cause a burning sensation?",
     ans="Tacrolimus", src=("L2", 43),
     why="Topical immunomodulators, second line, with burning on application — and avoided in patients with weakened immune systems.",
     wrong=[("Topical corticosteroids", "These are the FIRST-line agents they follow."),
            ("Topical retinoids", "Used for acne and photoageing."),
            ("Imiquimod", "Used for warts and premalignant lesions.")]),

dict(q="Which topical class must be avoided in patients with weakened immune systems?",
     ans="Topical immunomodulators", src=("L2", 44),
     why="Tacrolimus and pimecrolimus suppress local immunity, so they are avoided where immunity is already impaired.",
     wrong=[("Topical corticosteroids", "Used with care but not carrying this specific restriction."),
            ("Topical antifungals", "No such restriction."),
            ("Benzoyl peroxide", "No such restriction.")]),

dict(q="Which topical antibiotic has no systemic toxicity and only rarely causes allergic dermatitis?",
     ans="Bacitracin", src=("L2", 46),
     why="Rare allergic dermatitis, no systemic toxicity.",
     wrong=[("Neomycin", "Frequently sensitises and can accumulate systemically."),
            ("Polymyxin B", "Neurotoxic and nephrotoxic if absorbed."),
            ("Mupirocin", "Well tolerated but this description belongs to bacitracin.")]),

dict(q="Which tetracycline restriction matters most when prescribing for skin disease?",
     ans="Contraindicated under 8 years old and in pregnancy", src=("L2", 25),
     why="Contraindicated in children under eight and in pregnant women — the same rule that governs systemic use.",
     wrong=[("Contraindicated in renal failure and dialysis", "Not the stated restriction."),
            ("Contraindicated with dairy and antacids only", "Chelation matters, but it is not the contraindication stated."),
            ("Contraindicated over 65 years of age", "Not a stated restriction.")]),

dict(q="Which acne agent is used when resistance has made a topical antibiotic less useful, and is often combined with it?",
     ans="Benzoyl peroxide", src=("L2", 21),
     why="Combining it with a topical antibiotic slows the resistance that is eroding clindamycin and erythromycin.",
     wrong=[("Isotretinoin", "Reserved for severe disease."),
            ("Spironolactone", "A hormonal option in some women."),
            ("Tacrolimus", "For atopic dermatitis.")]),

dict(q="Which agent causes skin irritation in virtually every patient who uses it?",
     ans="Imiquimod", src=("L2", 57),
     why="Irritation in virtually all patients — expected, and not a reason to stop.",
     wrong=[("Bacitracin", "Rarely causes any reaction."),
            ("Mupirocin", "Well tolerated."),
            ("Nystatin", "Well tolerated.")]),

dict(q="Which topical antifungal is for candidal infection specifically?",
     ans="Nystatin", src=("L2", 54),
     why="For candidal infection — tolnaftate in the same pairing has NO candidal activity.",
     wrong=[("Tolnaftate", "No candidal activity at all."),
            ("Terbinafine", "For dermatophytes."),
            ("Ciclopirox", "The nail lacquer for onychomycosis.")]),

dict(q="Which topical drug is applied as a lacquer to the nail?",
     ans="Ciclopirox", src=("L2", 52),
     why="Penlac nail lacquer, for onychomycosis.",
     wrong=[("Terbinafine", "Oral or topical cream for dermatophytes."),
            ("Nystatin", "Cream or oral suspension for Candida."),
            ("Mupirocin", "An antibacterial ointment.")]),

dict(q="Which class treats athlete's foot, ringworm and jock itch — the superficial dermatophytes?",
     ans="Allylamines", src=("L2", 53),
     why="Terbinafine and naftifine, oral or topical.",
     wrong=[("Nystatin", "Candida only, with no dermatophyte activity."),
            ("Bacitracin", "An antibacterial."),
            ("Imiquimod", "For warts and premalignant lesions.")]),

dict(q="Which topical antibiotic can accumulate systemically if used over a large area?",
     ans="Neomycin", src=("L2", 49),
     why="Systemic accumulation, on top of frequent sensitisation.",
     wrong=[("Bacitracin", "No systemic toxicity."),
            ("Mupirocin", "Not described as accumulating."),
            ("Clindamycin", "Topical use for acne, not this concern.")]),

dict(q="Which agents are used topically for recurrent cold sores?",
     ans="Penciclovir", src=("L2", 55),
     why="Topical antivirals for recurrent orolabial herpes simplex.",
     wrong=[("Imiquimod", "For warts and premalignant lesions."),
            ("Mupirocin", "An antibacterial."),
            ("Tacrolimus", "An immunomodulator.")]),

dict(q="Which topical antifungals are used for vulvovaginal candidiasis?",
     ans="Topical azoles", src=("L2", 51),
     why="Clotrimazole, miconazole and sertaconazole, topically and vaginally.",
     wrong=[("Tolnaftate", "No candidal activity."),
            ("Terbinafine", "Dermatophytes only."),
            ("Bacitracin", "An antibacterial.")]),

dict(q="What is the most important thing to tell a patient starting a topical retinoid about the sun?",
     ans="It causes photosensitivity and severe sunburn", src=("L2", 24),
     why="Photosensitivity and severe sunburn — so sun protection is part of the prescription.",
     wrong=[("It protects against sunburn", "The opposite."),
            ("It has no interaction with sun exposure", "It does."),
            ("It should only be applied in the morning", "It is applied at night, but the sun point is the photosensitivity.")]),

dict(q="Which topical antibacterial must be kept off open or denuded skin at high dose?",
     ans="Polymyxin B", src=("L2", 48),
     why="Because of neurotoxicity and nephrotoxicity if enough is absorbed.",
     wrong=[("Bacitracin", "No systemic toxicity."),
            ("Mupirocin", "Safe on broken skin."),
            ("Clindamycin", "Used on acne-bearing skin.")]),

dict(q="Which drug is applied inside the nose rather than to a lesion?",
     ans="Mupirocin", src=("L2", 47),
     why="To eliminate nasal carriage of Staphylococcus aureus, MRSA included.",
     wrong=[("Bacitracin", "Applied to wounds."),
            ("Imiquimod", "Applied to warts and keratoses."),
            ("Ciclopirox", "Applied to nails.")]),
]
