# Pharmacology I Lecture 2 — Dermatology Medications, pool part B
# Atopic dermatitis, topical corticosteroid potency, immunomodulators, and the
# topical antibiotic / antifungal / antiviral agents.
#
# Same weighting as part A: indications, patient education, side effects and
# contraindications carry the count, per Dr. McInnis 2026-08-28.
SRC = "02. Dermatology Medications(1).pptx"
def c(n): return f"{SRC}, Slide {n}"

IO1  = "1 — Identify dermatologic drug classes and commonly prescribed dermatologic drugs"
IO2  = "2 — Describe the molecular mechanism of action of dermatologic drugs"
IO3  = "3 — Identify indications for commonly used dermatologic drugs"
IO4  = "4 — Describe absorption, distribution, metabolism, and excretion of dermatologic drugs"
IO5  = "5 — Summarize side effects and toxic manifestations of dermatologic drugs"
IO7  = "7 — Identify contraindications for dermatologic drugs"
IO9  = "9 — List commonly used protocols and patient monitoring for dermatologic drugs"
IO10 = "10 — Outline appropriate patient education for dermatologic drugs"

POOL_B = [

 dict(topic="Atopic dermatitis", io=IO1,
   q="Which conditions make up the atopic triad that atopic dermatitis belongs to?",
   opts=[
     ["Asthma and allergic rhino-conjunctivitis",
      "Correct. The three share an atopic tendency to immunoglobulin E mediated inflammation, and in the skin a defective barrier is the major contributor."],
     ["Psoriasis and seborrheic dermatitis",
      "Psoriasis is immune-mediated but not atopic, and seborrheic dermatitis relates to Malassezia; neither belongs to the triad."],
     ["Urticaria and angioedema",
      "These are not the two conditions named."],
     ["Acne vulgaris and rosacea",
      "Acne and rosacea are pilosebaceous disorders with no atopic basis; the triad is eczema, asthma and allergic rhino-conjunctivitis."]],
   c=0, cite=c(33)),

 dict(topic="Atopic dermatitis", io=IO1,
   q="Which set gives the MAJOR indicators of atopic dermatitis?",
   opts=[
     ["Pruritus, rash in areas typical of the disease, chronic or repeated symptoms, and family history",
      "Correct. Raised immunoglobulin E, positive skin tests, dry patchy scales and infection susceptibility are the minor ones."],
     ["Raised immunoglobulin E, positive allergy skin tests, and dry patchy scales",
      "These are listed as minor indicators rather than major ones."],
     ["Edema, vesicles, erosions and ulcers",
      "Edema, vesicles, erosions and ulcers describe the local inflammation imiquimod causes, not atopic dermatitis indicators."],
     ["Comedones, papulopustular lesions, and nodules",
      "Comedones, papulopustular lesions and nodules are the noninflammatory and inflammatory lesions of acne, not atopic dermatitis indicators."]],
   c=0, cite=c(34)),

 dict(topic="Atopic dermatitis", io=IO10,
   q="A parent asks what to do at home for a child with atopic dermatitis. Which set matches the non-pharmacologic advice?",
   opts=[
     ["Lukewarm baths with lubricant applied afterwards, short fingernails, and avoiding overheating",
      "Correct. Lukewarm water avoids stripping lipid, a lubricant seals in the moisture, short nails limit the damage from scratching, and overheating provokes itch."],
     ["Hot baths to open the pores, followed by air drying",
      "Baths are specified as lukewarm, and a lubricant is applied after."],
     ["Frequent washing with a high pH soap",
      "That advice belongs to the acne cleansing discussion, and even there frequent washing is discouraged."],
     ["Occlusive dressings over all affected areas overnight",
      "Occlusion is discussed as a variable in topical drug delivery, not as home care for children."]],
   c=0, cite=c(36)),

 dict(topic="Atopic dermatitis", io=IO3,
   q="Why is a sedating antihistamine included in the non-pharmacologic advice for a child with atopic dermatitis?",
   opts=[
     ["To reduce night-time itching",
      "Correct. The sedating property is being used for the itch that disrupts sleep."],
     ["To reverse the skin barrier dysfunction",
      "Barrier dysfunction is addressed by lubricants and hydration, not antihistamines."],
     ["To treat the secondary skin infections",
      "Secondary infection is treated with an antibacterial agent; the antihistamine is chosen for its sedating effect on night-time itch."],
     ["To lower serum immunoglobulin E",
      "Nothing here is aimed at lowering immunoglobulin E; the antihistamine is used for its sedative effect on night-time scratching."]],
   c=0, cite=c(36)),

 dict(topic="Atopic dermatitis", io=IO3,
   q="Which agents are the gold standard for atopic dermatitis?",
   opts=[
     ["Topical corticosteroids",
      "Correct, with the agent chosen by severity and by site of disease."],
     ["Topical immunomodulators",
      "Tacrolimus and pimecrolimus are named as second line, after topical steroids."],
     ["Oral corticosteroids",
      "These are used for short courses during exacerbations rather than as the standard."],
     ["Sedating antihistamines",
      "These address night-time itching rather than the disease itself."]],
   c=0, cite=c(37)),

 dict(topic="Atopic dermatitis", io=IO3,
   q="Which potency of topical steroid is directed to the face, intertriginous areas and infants?",
   opts=[
     ["Low potency",
      "Correct. These sites have thin or occluded skin that absorbs far more drug, so a low potency agent is used to limit atrophy and systemic absorption, and it also suits long-term therapy."],
     ["Medium potency",
      "Medium potency is for ordinary body skin, which is thicker and absorbs less than the face, folds or an infant's skin."],
     ["Medium to high potency",
      "That is reserved for exacerbations, for one to two weeks before stepping down."],
     ["Superpotent, class 1",
      "A superpotent steroid on facial or intertriginous skin causes rapid atrophy and striae, and in an infant risks adrenal suppression."]],
   c=0, cite=c(37)),

 dict(topic="Atopic dermatitis", io=IO9,
   q="An exacerbation warrants a medium to high potency corticosteroid. What should be done next?",
   opts=[
     ["Use it for one to two weeks, then switch to a lower potency",
      "Correct. The step-down is the protocol rather than continuing at strength."],
     ["Continue it indefinitely to prevent relapse",
      "Continuing at potency is what produces atrophy, striae and adrenal suppression; the strength is stepped down once the flare settles."],
     ["Stop abruptly once the flare settles and use nothing further",
      "Stopping outright invites rebound; the potency is stepped down to a lower agent rather than withdrawn completely."],
     ["Add an oral corticosteroid for the same duration",
      "Oral corticosteroids are a separate short-course option, not a routine addition."]],
   c=0, cite=c(37)),

 dict(topic="Topical corticosteroids", io=IO5,
   q="Which four factors determine the adverse reactions of a topical steroid?",
   opts=[
     ["Potency, duration, area of body covered, and occlusiveness of the preparation",
      "Correct, and it ranks occlusiveness as ointment greater than cream greater than lotion."],
     ["Patient age, sex, weight and skin type",
      "Patient demographics are not the determinants; what matters is how strong the drug is, how long it is used, how much skin it covers and how occlusive the vehicle is."],
     ["Drug solubility, vehicle stability, pH and storage",
      "These are vehicle formulation considerations rather than determinants of adverse effect."],
     ["Frequency of bathing, soap choice, humidity and season",
      "These are contributory factors discussed under acne."]],
   c=0, cite=c(38)),

 dict(topic="Topical corticosteroids", io=IO5,
   q="Which of these is a LOCAL adverse effect of topical steroids, rather than a systemic one?",
   opts=[
     ["Skin atrophy",
      "Correct. Local effects are skin atrophy, acne, rosacea and allergic dermatitis related to the vehicle."],
     ["Adrenal suppression",
      "Adrenal suppression follows systemic absorption through the skin and is a systemic effect; the local ones are atrophy, acne, rosacea and vehicle allergy."],
     ["Cataracts",
      "Cataracts are listed as systemic, alongside glaucoma."],
     ["Growth retardation in children",
      "Growth retardation reflects systemic absorption in children; the local effects are confined to the treated skin."]],
   c=0, cite=c(38)),

 dict(topic="Topical corticosteroids", io=IO5,
   q="Which systemic effects are attributed to topical corticosteroids?",
   opts=[
     ["Adrenal suppression, infections, hyperglycemia, glaucoma, cataracts and growth retardation in children",
      "Correct. That a topical agent can do all of this is the point of the potency and duration warnings."],
     ["Hepatotoxicity, nephrotoxicity and ototoxicity",
      "Neuro and nephrotoxicity are raised for polymyxin B on denuded skin, not for steroids."],
     ["Raised serum lipids and brittle nails",
      "Those belong to systemic isotretinoin."],
     ["Photosensitivity and severe sunburn",
      "That is the topical retinoid profile."]],
   c=0, cite=c(38)),

 dict(topic="Topical corticosteroids", io=IO1,
   q="Which agent is placed in class 1, superpotent?",
   opts=[
     ["Clobetasol propionate",
      "Correct, listed in class 1 in cream, ointment, lotion, spray, shampoo and foam forms."],
     ["Hydrocortisone",
      "Hydrocortisone sits at the least potent end of the chart."],
     ["Desonide",
      "Desonide lotion appears in class 5, lower mid-strength."],
     ["Triamcinolone acetonide cream",
      "Triamcinolone acetonide cream sits in class 5, mid-strength; clobetasol propionate is the class 1 superpotent agent."]],
   c=0, cite=c(41)),

 dict(topic="Topical immunomodulators", io=IO2,
   q="What is the mechanism of tacrolimus and pimecrolimus?",
   opts=[
     ["They inhibit activation of T cells, mast cells and keratinocytes",
      "Correct, and that is why they are positioned as a steroid-sparing option."],
     ["They inhibit fungal cytochrome P450",
      "That is the azole antifungal mechanism."],
     ["They stimulate release of interferon alpha",
      "That is imiquimod."],
     ["They chelate calcium and block chemotaxis",
      "That is the tetracycline anti-inflammatory action."]],
   c=0, cite=c(43)),

 dict(topic="Topical immunomodulators", io=IO7,
   q="Which patient should avoid topical tacrolimus or pimecrolimus?",
   opts=[
     ["A patient with a weakened immune system",
      "Correct. These calcineurin inhibitors suppress local T cell activity, so they are avoided where immunity is already weakened, with a possible cancer risk noted alongside."],
     ["A patient with a history of acne",
      "Acne is not a stated contraindication for these agents."],
     ["A patient over the age of sixty",
      "Age alone is not given as a bar."],
     ["A patient using an emollient",
      "Emollients are part of routine care and are not a conflict."]],
   c=0, cite=c(43)),

 dict(topic="Topical immunomodulators", io=IO10,
   q="Which two counseling points are attached to the topical immunomodulators?",
   opts=[
     ["Expect a burning sensation, and use a high SPF sunscreen",
      "Correct. Both are given explicitly with these agents."],
     ["Expect bleaching of clothing, and apply only at night",
      "Those belong to benzoyl peroxide and tretinoin respectively."],
     ["Expect hypopigmentation, and allow six to eight weeks",
      "That is the azelaic acid counseling."],
     ["Expect photophobia, and monitor mood",
      "Those belong to systemic isotretinoin."]],
   c=0, cite=c(43)),

 dict(topic="Oral corticosteroids", io=IO10,
   q="Why does an oral corticosteroid course for atopic dermatitis need a tapering dose?",
   opts=[
     ["To prevent a flare-up",
      "Correct. The taper protects against rebound rather than against withdrawal symptoms alone."],
     ["To avoid precipitating drug-induced acne",
      "Drug-induced acne is discussed under acne and is not the reason for the taper here."],
     ["To allow the topical steroid to be started safely",
      "No such sequencing requirement is described."],
     ["To reduce the risk of secondary infection",
      "Treating secondary infection is a separate goal of therapy."]],
   c=0, cite=c(44)),

 dict(topic="Bacitracin", io=IO2,
   q="How does bacitracin work, and what is true of its systemic toxicity?",
   opts=[
     ["It is a peptide antibiotic that prevents cell wall synthesis, and it has no systemic toxicity",
      "Correct, with allergic dermatitis noted only rarely."],
     ["It binds bacterial transfer RNA to stop protein synthesis, and it accumulates systemically",
      "That mechanism is mupirocin's, and bacitracin is the one with no systemic toxicity."],
     ["It interrupts the cytoplasmic membrane, and it risks nephrotoxicity",
      "That describes polymyxin B."],
     ["It inhibits protein synthesis, and it frequently causes sensitization",
      "That describes the topical aminoglycosides, neomycin in particular."]],
   c=0, cite=c(46)),

 dict(topic="Mupirocin", io=IO3,
   q="Which use is given for mupirocin beyond ordinary skin infection?",
   opts=[
     ["Eliminating nasal carriage of Staphylococcus aureus",
      "Correct, and its coverage is most gram positive aerobes, especially meticillin-resistant Staphylococcus aureus."],
     ["Eliminating vaginal candidiasis",
      "That indication belongs to the azole antifungals."],
     ["Treating recurrent orolabial herpes simplex",
      "That is acyclovir and penciclovir."],
     ["Treating onychomycosis of the toenails",
      "That is the ciclopirox nail lacquer."]],
   c=0, cite=c(47)),

 dict(topic="Mupirocin", io=IO2,
   q="What is mupirocin's mechanism?",
   opts=[
     ["It binds bacterial transfer RNA, preventing protein synthesis",
      "Correct. Mupirocin inhibits isoleucyl transfer RNA synthetase, halting bacterial protein synthesis; it is not absorbed systemically, though it can irritate mucous membranes."],
     ["It prevents bacterial cell wall synthesis",
      "That is bacitracin."],
     ["It interrupts the bacterial cytoplasmic membrane",
      "That is polymyxin B."],
     ["It inhibits fungal ergosterol production",
      "That is the allylamines."]],
   c=0, cite=c(47)),

 dict(topic="Polymyxin B", io=IO7,
   q="What warning is attached to polymyxin B?",
   opts=[
     ["Avoid using it on open wounds or denuded skin in high doses, because of neurotoxicity and nephrotoxicity risk",
      "Correct. Loss of the barrier is what turns a topical agent into a systemic exposure."],
     ["Avoid it in pregnancy because it is teratogenic",
      "Teratogenicity is the concern with retinoids and tetracyclines; the polymyxin B warning is neurotoxicity and nephrotoxicity from systemic absorption through broken skin."],
     ["Avoid it in children under eight because it stains teeth",
      "That restriction belongs to the tetracyclines."],
     ["Avoid it with benzoyl peroxide because it is inactivated",
      "That interaction is tretinoin with benzoyl peroxide."]],
   c=0, cite=c(48)),

 dict(topic="Polymyxin B", io=IO3,
   q="Which organisms is polymyxin B effective against?",
   opts=[
     ["Gram negative organisms including Pseudomonas, Escherichia coli and Klebsiella",
      "Correct, which is the complement to bacitracin's gram positive coverage."],
     ["Gram positive cocci including streptococci and staphylococci",
      "That is bacitracin's coverage."],
     ["Dermatophytes and Candida",
      "Those are covered by the antifungal agents."],
     ["Herpes simplex virus types 1 and 2",
      "Those are covered by the topical antivirals."]],
   c=0, cite=c(48)),

 dict(topic="Topical aminoglycosides", io=IO5,
   q="Which problem is specifically attached to topical neomycin?",
   opts=[
     ["It frequently causes sensitization",
      "Correct, and the class can also accumulate systemically."],
     ["It bleaches hair and clothing",
      "That is benzoyl peroxide."],
     ["It causes hypopigmentation",
      "That is azelaic acid."],
     ["It is inactivated by benzoyl peroxide",
      "That interaction belongs to tretinoin."]],
   c=0, cite=c(49)),

 dict(topic="Azole antifungals", io=IO2,
   q="What is the mechanism of the topical azole antifungals?",
   opts=[
     ["They inhibit fungal cytochrome P450, preventing cell wall formation",
      "Correct, and the named agents are clotrimazole, ketoconazole, miconazole and sertaconazole."],
     ["They inhibit ergosterol production directly",
      "The allylamines inhibit squalene epoxidase to block ergosterol synthesis directly; the azoles act earlier, through fungal cytochrome P450."],
     ["They inhibit uptake of molecular precursors at the fungal cell wall",
      "That is ciclopirox."],
     ["They bind fungal transfer RNA to stop protein synthesis",
      "No topical antifungal works by binding transfer RNA; that is mupirocin's antibacterial mechanism."]],
   c=0, cite=c(51)),

 dict(topic="Azole antifungals", io=IO10,
   q="A patient is starting a topical azole. What should they be told about duration?",
   opts=[
     ["Treatment is generally prolonged, on the order of two to three weeks",
      "Correct, and stopping early is how a treated infection returns."],
     ["A single application is usually curative",
      "A single application cannot clear a dermatophyte from the stratum corneum; two to three weeks of continuous treatment is needed."],
     ["Treatment continues until the rash disappears, then stops immediately",
      "Stopping when the rash clears leaves viable fungus in the stratum corneum, which is why the course runs a set two to three weeks."],
     ["Treatment must continue for at least six months",
      "Six months applies to oral treatment of nail infection; a topical azole for skin runs two to three weeks."]],
   c=0, cite=c(51)),

 dict(topic="Azole antifungals", io=IO3,
   q="Why is an azole sometimes combined with a corticosteroid?",
   opts=[
     ["For more rapid symptom relief",
      "Correct. The steroid addresses symptoms while the antifungal addresses the organism."],
     ["To prevent the development of resistance",
      "Resistance is raised for erythromycin in acne, not as the reason for this combination."],
     ["To allow a shorter total course of therapy",
      "The course remains prolonged either way; the steroid is added for faster relief of itch and inflammation, not to shorten treatment."],
     ["To make the preparation less irritating to the skin",
      "Local irritation is listed as the adverse reaction, but symptom relief is the stated reason."]],
   c=0, cite=c(51)),

 dict(topic="Ciclopirox", io=IO10,
   q="A patient asks about the ciclopirox nail lacquer for onychomycosis. What is true of how well it works?",
   opts=[
     ["It is less than twelve percent effective",
      "Correct, and saying so up front is what keeps expectations honest for a months-long treatment."],
     ["It is curative in the majority of patients",
      "Cure rates are low, under twelve percent, because the lacquer penetrates the nail plate poorly to reach fungus in the nail bed."],
     ["It works only on fingernails, not toenails",
      "It is marketed for both fingernails and toenails; the limitation is its low cure rate, not the site."],
     ["It is as effective as oral terbinafine",
      "No such comparison is made, and the stated efficacy is low."]],
   c=0, cite=c(52)),

 dict(topic="Allylamines", io=IO1,
   q="Which two agents are named as allylamines, and how do they work?",
   opts=[
     ["Naftifine and terbinafine, which inhibit ergosterol production and prevent cell wall synthesis",
      "Correct, with local irritation as the adverse reaction."],
     ["Clotrimazole and miconazole, which inhibit fungal cytochrome P450",
      "Those are azoles."],
     ["Nystatin and tolnaftate, which bind sterols directly",
      "Those are grouped separately under other antifungals."],
     ["Ciclopirox and sertaconazole, which block precursor uptake",
      "Ciclopirox blocks precursor uptake but is not an allylamine, and sertaconazole is an azole."]],
   c=0, cite=c(53)),

 dict(topic="Other antifungals", io=IO3,
   q="Which gap in coverage is flagged for tolnaftate?",
   opts=[
     ["It has no Candida activity",
      "Correct. Tolnaftate covers dermatophytes but has no activity against Candida, so a candidal intertrigo needs nystatin or an azole instead."],
     ["It has no dermatophyte activity",
      "Dermatophyte infection is what it is used for."],
     ["It has no activity below the stratum corneum",
      "Depth is not the issue; the gap is organism coverage, since tolnaftate treats dermatophytes but not Candida."],
     ["It has no activity on the scalp",
      "Site is not the stated gap."]],
   c=0, cite=c(54)),

 dict(topic="Other antifungals", io=IO4,
   q="What is true of nystatin's absorption?",
   opts=[
     ["It has no oral absorption",
      "Correct, which is why it is used for cutaneous and mucosal candidal infection rather than systemically."],
     ["It is well absorbed orally and distributes widely",
      "Nystatin is not absorbed from the gut at all, which is exactly why oral suspension works against candidal infection of the mouth and intestine without systemic exposure."],
     ["It is absorbed only through inflamed skin",
      "Inflamed skin absorbs more of most topical drugs, but nystatin is characterized by essentially no absorption, which is what keeps it safe."],
     ["It accumulates systemically with repeated use",
      "Systemic accumulation is raised for the topical aminoglycosides."]],
   c=0, cite=c(54)),

 dict(topic="Topical antivirals", io=IO3,
   q="What are acyclovir and penciclovir used for topically, and what kind of molecule are they?",
   opts=[
     ["Recurrent orolabial herpes simplex infection; they are synthetic guanine analogs",
      "Correct, active against herpes simplex virus types 1 and 2."],
     ["External and perianal warts; they are immunomodulators",
      "That is imiquimod."],
     ["Vulvovaginal candidiasis; they are azoles",
      "That is the azole antifungal indication."],
     ["Actinic keratoses; they are retinoids",
      "Actinic keratosis is treated with imiquimod or fluorouracil; acyclovir and penciclovir are guanine analogs active against herpes simplex."]],
   c=0, cite=c(56)),

 dict(topic="Imiquimod", io=IO3,
   q="Which set gives imiquimod's indications?",
   opts=[
     ["External and perianal warts, actinic keratoses, and basal cell carcinoma",
      "Correct. All three sit under the same immunomodulator."],
     ["Orolabial herpes, shingles, and molluscum contagiosum",
      "Herpes simplex is treated with the topical or oral antivirals; imiquimod is used for warts, actinic keratoses and basal cell carcinoma."],
     ["Acne vulgaris, rosacea, and atopic dermatitis",
      "None of these are imiquimod indications here."],
     ["Onychomycosis, tinea versicolor, and candidiasis",
      "Those are ciclopirox's indications."]],
   c=0, cite=c(57)),

 dict(topic="Imiquimod", io=IO2,
   q="What does imiquimod do?",
   opts=[
     ["It stimulates peripheral mononuclear cells to release interferon alpha and macrophages to produce tumor necrosis factor alpha and interleukins",
      "Correct. It is an immunomodulator rather than a directly cytotoxic agent."],
     ["It inhibits T cell, mast cell and keratinocyte activation",
      "That is tacrolimus and pimecrolimus, which suppress rather than stimulate."],
     ["It is converted to benzoic acid after crossing the stratum corneum",
      "That is benzoyl peroxide."],
     ["It corrects abnormal follicular keratinization",
      "That is a topical retinoid action."]],
   c=0, cite=c(57)),

 dict(topic="Imiquimod", io=IO10,
   q="A patient on imiquimod reports redness, swelling and erosions at the site. What is true of this?",
   opts=[
     ["Skin irritation occurs in virtually all patients, and the degree of inflammation parallels efficacy",
      "Correct, so the reaction is expected and is not by itself a reason to stop."],
     ["It indicates an allergic reaction and the drug should be stopped",
      "The inflammation is the drug working rather than an allergy; imiquimod is an immune response modifier, and the local reaction is how it clears the lesion."],
     ["It is unusual and suggests secondary bacterial infection",
      "Irritation occurs in virtually all patients rather than being unusual."],
     ["It means the dose is too low and should be increased",
      "The reaction indicates an active immune response rather than an inadequate dose; increasing it would only worsen the erosion."]],
   c=0, cite=c(57)),

 dict(topic="Imiquimod", io=IO9,
   q="How often is imiquimod applied?",
   opts=[
     ["Two to five times per week",
      "Correct, which is a weekly schedule rather than a daily one."],
     ["Twice daily without interruption",
      "That schedule belongs to azelaic acid once titrated up."],
     ["Once monthly",
      "Monthly application is far too infrequent to sustain the local immune response; imiquimod is applied two to five times per week."],
     ["Only at night, because it is photolabile",
      "Photolability is tretinoin's property."]],
   c=0, cite=c(57)),
]
