# -*- coding: utf-8 -*-
"""Rapid-drill bank: cholinergic, anticholinergic and neuromuscular agents.
Same rule as tools/pharm_drill_antibacterials.py."""
ITEMS = [
dict(q="Which neuromuscular blocker causes malignant hyperthermia?",
     ans="Succinylcholine", src=("L3", 66),
     why="Malignant hyperthermia and hyperkalaemia. Treatment is rapid cooling and dantrolene.",
     wrong=[("Rocuronium", "A nondepolarizing blocker; no malignant hyperthermia."),
            ("Vecuronium", "A nondepolarizing blocker."),
            ("Atracurium", "Nondepolarizing, and its quirk is histamine release.")]),

dict(q="Which neuromuscular blocker releases histamine?",
     ans="Atracurium", src=("L3", 65),
     why="Histamine release is what separates it from the other nondepolarizing blockers.",
     wrong=[("Succinylcholine", "Depolarizing, and its flags are malignant hyperthermia and hyperkalaemia."),
            ("Rocuronium", "No histamine release."),
            ("Pancuronium", "No histamine release.")]),

dict(q="Which drug reactivates acetylcholinesterase after organophosphate poisoning?",
     ans="Pralidoxime", src=("L3", 42),
     why="It reactivates inhibited acetylcholinesterase. Two limits: it does not enter the central nervous system, and it cannot overcome reversible inhibitors such as physostigmine.",
     wrong=[("Atropine", "Blocks the muscarinic effects but does not reactivate the enzyme."),
            ("Physostigmine", "An inhibitor itself — it would make the poisoning worse."),
            ("Neostigmine", "Also an inhibitor.")]),

dict(q="Which cholinesterase inhibitor is used to DIAGNOSE myasthenia gravis?",
     ans="Edrophonium", src=("L3", 35),
     why="Very short acting, so it is used for diagnosis and to reverse nondepolarizing blockers after surgery.",
     wrong=[("Pyridostigmine", "Used for CHRONIC management of myasthenia gravis, not diagnosis."),
            ("Neostigmine", "Used to reverse blockade and stimulate bladder and gut."),
            ("Physostigmine", "Crosses into the central nervous system; used for anticholinergic toxicity.")]),

dict(q="Which cholinesterase inhibitor is used for the CHRONIC management of myasthenia gravis?",
     ans="Pyridostigmine", src=("L3", 38),
     why="Long acting, so it is the maintenance drug — edrophonium is the diagnostic one.",
     wrong=[("Edrophonium", "Too short acting; it is used to diagnose."),
            ("Physostigmine", "Used for anticholinergic toxicity."),
            ("Pralidoxime", "Reactivates the enzyme in organophosphate poisoning.")]),

dict(q="Which agent stimulates a postpartum or postoperative atonic bladder and has NO nicotinic activity?",
     ans="Bethanechol", src=("L3", 30),
     why="Muscarinic only, with no nicotinic action, so it is used for the atonic bladder.",
     wrong=[("Carbachol", "Has BOTH muscarinic and nicotinic activity."),
            ("Pilocarpine", "Used for glaucoma and for dry mouth."),
            ("Neostigmine", "An indirect agent — it inhibits the enzyme instead.")]),

dict(q="Which cholinergic agonist has both muscarinic AND nicotinic activity and is used to lower intraocular pressure?",
     ans="Carbachol", src=("L3", 32),
     why="Both receptor types, and it decreases intraocular pressure in glaucoma.",
     wrong=[("Bethanechol", "Muscarinic only, with no nicotinic activity."),
            ("Pilocarpine", "Muscarinic; used for glaucoma and xerostomia."),
            ("Atropine", "An antagonist — it does the opposite.")]),

dict(q="Which drug lowers intraocular pressure AND stimulates salivation in dry mouth?",
     ans="Pilocarpine", src=("L3", 33),
     why="Both indications belong to it — glaucoma and xerostomia.",
     wrong=[("Carbachol", "Glaucoma, but not the xerostomia indication."),
            ("Bethanechol", "The bladder drug."),
            ("Timolol", "Lowers intraocular pressure by reducing aqueous production, and does nothing for saliva.")]),

dict(q="Dry mouth, blurred vision and “sandy eyes” describe the effects of which drug?",
     ans="Atropine", src=("L3", 51),
     why="Classic antimuscarinic effects, along with urinary retention and constipation.",
     wrong=[("Bethanechol", "Does the opposite — it increases secretions."),
            ("Pilocarpine", "Increases salivation."),
            ("Neostigmine", "Increases secretions.")]),

dict(q="“Mad as a hatter, blind as a bat, red as a beet” describes toxicity from which group?",
     ans="Antimuscarinics", src=("L3", 50),
     why="The anticholinergic toxidrome.",
     wrong=[("Cholinergic agonists", "Produce the opposite picture — wet, slow and constricted."),
            ("Beta blockers", "Cause bradycardia and fatigue, not delirium and flushing."),
            ("Organophosphates", "Cholinesterase inhibitors, so again the opposite picture.")]),

dict(q="Which drug shows bradycardia at lower doses but tachycardia at higher doses?",
     ans="Atropine", src=("L3", 51),
     why="The dose-dependent reversal that catches people out.",
     wrong=[("Propranolol", "Slows the heart at every dose."),
            ("Bethanechol", "Slows the heart."),
            ("Isoproterenol", "Stimulates the heart at every dose.")]),

dict(q="Which antimuscarinic is used to prevent motion sickness, with instructions to wash the hands after applying it?",
     ans="Scopolamine", src=("L3", 54),
     why="A patch for motion sickness — and hands must be washed, or the drug is transferred to the eye.",
     wrong=[("Atropine", "Not used for motion sickness."),
            ("Ipratropium", "Inhaled, for chronic obstructive pulmonary disease."),
            ("Oxybutynin", "For the overactive bladder.")]),

dict(q="Which inhaled antimuscarinics are used for maintenance bronchodilation in chronic obstructive pulmonary disease?",
     ans="Tiotropium", src=("L3", 55),
     why="Maintenance inhaled bronchodilators; glycopyrrolate in the same group is also used for drooling and hyperhidrosis.",
     wrong=[("Albuterol", "A beta-2 agonist, and it is the rescue rather than the antimuscarinic maintenance."),
            ("Scopolamine", "For motion sickness."),
            ("Atropine", "Not used as a maintenance inhaler.")]),

dict(q="Which antimuscarinics lower intravesical pressure and increase bladder capacity?",
     ans="Oxybutynin", src=("L3", 56),
     why="The bladder antimuscarinics, reducing the frequency of bladder contractions.",
     wrong=[("Bethanechol", "The opposite — it stimulates an atonic bladder."),
            ("Ipratropium", "Inhaled for the airway."),
            ("Scopolamine", "For motion sickness.")]),

dict(q="Which cholinesterase inhibitor crosses into the central nervous system and can cause convulsions at high dose?",
     ans="Physostigmine", src=("L3", 36),
     why="It enters the central nervous system, which is why it is the one used for anticholinergic toxicity — and why it convulses at high dose.",
     wrong=[("Neostigmine", "Does not cross into the central nervous system."),
            ("Pyridostigmine", "Does not cross appreciably."),
            ("Pralidoxime", "Explicitly does not penetrate the central nervous system.")]),

dict(q="Which drugs slow the progression of Alzheimer's disease and mostly cause gastrointestinal distress?",
     ans="Donepezil", src=("L3", 40),
     why="The centrally acting cholinesterase inhibitors, whose limiting side effect is gastrointestinal.",
     wrong=[("Neostigmine", "Peripheral, for myasthenia gravis and the bladder."),
            ("Edrophonium", "Diagnostic only."),
            ("Atropine", "An antagonist, which would worsen cognition.")]),

dict(q="Salivation, flushing, falling blood pressure, abdominal pain, diarrhoea and bronchospasm together are the effects of what?",
     ans="Cholinergic excess", src=("L3", 38),
     why="The muscarinic picture produced by cholinesterase inhibitors and direct agonists.",
     wrong=[("Anticholinergic excess", "The opposite: dry, flushed, hot, delirious, retaining urine."),
            ("Beta blockade", "Bradycardia and fatigue, without secretions."),
            ("Alpha-1 blockade", "Orthostatic hypotension and nasal congestion.")]),

dict(q="Which class must be used with caution in reactive airway disease because it causes bronchospasm?",
     ans="Cholinergic agonists", src=("L3", 31),
     why="Bronchospasm is the reason for caution in reactive airway disease.",
     wrong=[("Antimuscarinics", "Used to OPEN the airway in COPD."),
            ("Beta-2 agonists", "Used to open the airway in asthma."),
            ("Alpha-1 blockers", "Not a bronchial issue.")]),

dict(q="Organophosphates are most commonly encountered as what?",
     ans="Agricultural insecticides", src=("L3", 42),
     why="Irreversible cholinesterase inhibitors used as insecticides; poisoning shows nicotinic or muscarinic signs.",
     wrong=[("Prescription eye drops", "Not the common source of poisoning."),
            ("Topical acne treatments", "Unrelated."),
            ("Inhaled anaesthetics", "Unrelated.")]),

dict(q="Which drug is given as an ANTIDOTE to competitive neuromuscular blockers after surgery?",
     ans="Neostigmine", src=("L3", 38),
     why="Raises acetylcholine to out-compete the blocker at the junction.",
     wrong=[("Succinylcholine", "A blocker itself — it would deepen the block."),
            ("Atropine", "Given alongside to limit muscarinic effects, but it does not reverse the block."),
            ("Pralidoxime", "For organophosphates, and it cannot reverse a competitive blocker.")]),

dict(q="Nondepolarizing blockers are used for which purpose?",
     ans="Relaxing skeletal muscle for intubation", src=("L3", 63),
     why="Adjuvants in anaesthesia — intubation, fracture alignment and dislocation correction.",
     wrong=[("Treating myasthenia gravis", "They would worsen it."),
            ("Reversing organophosphate poisoning", "That is pralidoxime and atropine."),
            ("Lowering intraocular pressure", "That is pilocarpine, carbachol or timolol.")]),

dict(q="Nicotine at higher doses does what to blood pressure and to gut and bladder activity?",
     ans="Blood pressure falls and gut activity ceases", src=("L3", 59),
     why="Stimulation first, then paralysis of all ganglia — so the early effects reverse.",
     wrong=[("Blood pressure rises further and gut activity increases", "That is the early, low-dose phase only."),
            ("Both are unchanged", "Ganglionic effects are dose-dependent, not absent."),
            ("Blood pressure rises while gut activity ceases", "Mixes the two phases.")]),

dict(q="Hyperkalaemia after a neuromuscular blocker points to which agent?",
     ans="Succinylcholine", src=("L3", 66),
     why="Hyperkalaemia alongside malignant hyperthermia — the two dangers of the depolarizing blocker.",
     wrong=[("Rocuronium", "Nondepolarizing; no potassium shift."),
            ("Cisatracurium", "Nondepolarizing."),
            ("Pancuronium", "Nondepolarizing.")]),

dict(q="Malignant hyperthermia is treated with rapid cooling and which drug?",
     ans="Dantrolene", src=("L3", 66),
     why="Dantrolene, with rapid cooling.",
     wrong=[("Pralidoxime", "For organophosphate poisoning."),
            ("Neostigmine", "Reverses nondepolarizing blockade."),
            ("Atropine", "Blocks muscarinic effects; no role here.")]),

dict(q="Which agent has NO therapeutic use but causes a serious pressor reaction in a patient on a monoamine oxidase inhibitor?",
     ans="Tyramine", src=("L3", 106),
     why="No therapeutic use; found in fermented foods such as cheese and wine.",
     wrong=[("Nicotine", "Has therapeutic use in cessation products."),
            ("Cocaine", "Has a therapeutic use as a local anaesthetic."),
            ("Ephedrine", "Has therapeutic use as a decongestant.")]),

dict(q="Which cholinergic agent is used to decrease intraocular pressure in glaucoma AND has both receptor actions, given intraocularly during surgery?",
     ans="Carbachol", src=("L3", 32),
     why="Both muscarinic and nicotinic, used intraocularly.",
     wrong=[("Bethanechol", "Muscarinic only and used for the bladder."),
            ("Physostigmine", "An indirect agent."),
            ("Scopolamine", "An antagonist.")]),

dict(q="Which effects would you expect from a patient who has taken too much of an antimuscarinic?",
     ans="Confusion, hallucinations and delirium", src=("L3", 51),
     why="The central antimuscarinic picture, on top of dry mouth, blurred vision and retention.",
     wrong=[("Salivation, diarrhoea and bronchospasm", "That is cholinergic excess."),
            ("Bradycardia and hypotension", "Cholinergic, not antimuscarinic."),
            ("Tendon rupture and photosensitivity", "Fluoroquinolone effects, not autonomic.")]),

dict(q="Which of these groups inhibits cholinesterase IRREVERSIBLY?",
     ans="Organophosphates", src=("L3", 42),
     why="Irreversible, which is why the enzyme has to be reactivated with pralidoxime rather than simply out-competed.",
     wrong=[("Cholinergic agonists", "They act on the receptor directly and do not touch the enzyme."),
            ("Antimuscarinics", "They block the receptor; they are not enzyme inhibitors at all."),
            ("Nondepolarizing blockers", "They compete at the neuromuscular junction, not at cholinesterase.")]),

dict(q="Which antimuscarinic is used for excessive drooling in cerebral palsy and for hyperhidrosis?",
     ans="Glycopyrrolate", src=("L3", 55),
     why="Named for both, alongside its inhaled use in the same family.",
     wrong=[("Scopolamine", "For motion sickness."),
            ("Oxybutynin", "For the bladder."),
            ("Atropine", "Not the agent used for these.")]),

dict(q="Why can pralidoxime not be used against physostigmine poisoning?",
     ans="It cannot overcome reversible inhibitors", src=("L3", 42),
     why="It reactivates the enzyme after IRREVERSIBLE inhibition; a reversible inhibitor is not bound the same way.",
     wrong=[("It is too slow to act", "Speed is not the stated limitation."),
            ("It is inactivated by the liver first", "Not the stated limitation."),
            ("It only works in children", "Not the stated limitation.")]),
]
