# -*- coding: utf-8 -*-
"""Pharmacology I Exam 2 -- Ophthalmology, topic 3: glaucoma and diagnostic agents.

Sizing and exclusions are explained in pharm_oph_pool_anti.py.

The richest section of the deck and the one that rewards the drug frame most:
five classes, each sorted by whether it reduces aqueous PRODUCTION or increases
OUTFLOW, and each with one adverse effect that decides whether a given patient
can have it -- asthma for the non-selective beta blockers, age under two for
the alpha-2 agonists, and visual blurring for the cholinergics in a young
patient who still accommodates.
"""

QUESTIONS = [

{"topic": "Glaucoma pharmacology", "io": "Describe the mechanism of action of ophthalmic drugs",
 "slot": "mechanism",
 "q": "Glaucoma drugs work by one of two strategies. What are they?",
 "opts": [
  ["Reducing production or increasing outflow",
   "Correct. Every agent in this section sorts into one or the other, and some do both. Sorting a drug by which side it is on is the fastest way to remember the whole class list."],
  ["Decreasing aqueous production or reducing episcleral venous pressure",
   "Episcleral venous pressure is not one of the two targets; drug therapy works on production and on outflow."],
  ["Increasing outflow or reducing optic nerve metabolic demand",
   "Neuroprotection is not among the described mechanisms; the drugs are pressure drugs."],
  ["Dilating the pupil or constricting the ciliary muscle",
   "Cholinergics do contract the ciliary muscle, but as a means to increase outflow rather than as a strategy in itself."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 60"},

{"topic": "Glaucoma pharmacology", "io": "Identify indications and contraindications of ophthalmic drugs",
 "slot": "drug choice",
 "q": "Which classes INCREASE aqueous outflow?",
 "opts": [
  ["Prostaglandins, alpha adrenergic agonists and cholinergic agonists",
   "Correct. The alpha agonists appear on both sides — they decrease production and increase outflow — which is why they are easy to misplace."],
  ["Beta blockers, carbonic anhydrase inhibitors and prostaglandins",
   "The first two decrease production; only the prostaglandins in this list increase outflow."],
  ["Carbonic anhydrase inhibitors and cholinergic agonists only",
   "Carbonic anhydrase inhibitors reduce production rather than improving drainage."],
  ["Beta blockers alone",
   "Beta blockers are a production drug, and second line at that."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 64"},

{"topic": "Prostaglandin analogues", "io": "Identify indications and contraindications of ophthalmic drugs",
 "slot": "drug choice",
 "q": "Which class is first line for open angle glaucoma, and how often is it given?",
 "opts": [
  ["Prostaglandin analogues, once daily",
   "Correct. They are the most commonly used glaucoma medications and the first line agents. Once daily is the whole dose — and more often is actively worse, not merely unnecessary."],
  ["Beta blockers, twice daily",
   "Beta blockers are described as second line, though therapy may reasonably start with either a prostaglandin or a beta blocker."],
  ["Carbonic anhydrase inhibitors, three times daily",
   "Not first line, and their bitter taste and stinging limit acceptability."],
  ["Cholinergic agonists, four times daily",
   "Frequent dosing and side effects make compliance poor; they are far from first choice."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slides 64 and 66"},

{"topic": "Prostaglandin analogues", "io": "Identify indications and contraindications of ophthalmic drugs",
 "slot": "education",
 "q": "A patient using latanoprost thinks two drops a night will lower the pressure further. What should they be told?",
 "opts": [
  ["Exceeding once daily dosing inhibits the pressure-lowering effect",
   "Correct. This is counter-intuitive and therefore a good question: more drug does not mean more effect, it means less. Once daily is the maximum as well as the minimum."],
  ["Two drops a night is acceptable if the pressure is not at target",
   "It would work against the goal rather than toward it: exceeding once daily actively inhibits the pressure-lowering effect."],
  ["It is harmless but wasteful",
   "Not harmless. The extra dose is not merely wasted; it reduces the pressure-lowering effect the patient is taking the drug for."],
  ["It should be split to morning and evening instead",
   "Splitting the dose still exceeds once daily in total, so the same inhibition of the pressure-lowering effect applies."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 66"},

{"topic": "Prostaglandin analogues", "io": "Identify indications and contraindications of ophthalmic drugs",
 "slot": "adverse effect",
 "q": "Which cosmetic adverse effects should a patient starting a prostaglandin analogue be warned about?",
 "opts": [
  ["Eyelash and iris colour change, with hyperaemia",
   "Correct. The eyelash effect is marketed as a product in its own right, and iris darkening can be permanent — which is why it is a consent conversation rather than a footnote, particularly when only one eye is treated."],
  ["Permanent pupillary constriction and myopia",
   "Fixed small pupils and induced myopia are cholinergic agonist effects, which is why young patients tolerate miotics so poorly."],
  ["Bitter taste and stinging on instillation",
   "Bitter taste and stinging belong to the carbonic anhydrase inhibitors, and between them affect more than half of those patients."],
  ["Bradycardia and wheeze",
   "Systemic beta blocker effects; prostaglandins have limited systemic side effects."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 65"},

{"topic": "Beta blockers", "io": "Describe the mechanism of action of ophthalmic drugs",
 "slot": "mechanism",
 "q": "How do ophthalmic beta blockers lower intraocular pressure?",
 "opts": [
  ["They block beta receptors in the ciliary epithelium",
   "Correct. Less catecholamine activation means less cyclic AMP, and less aqueous is made. They act on the production side, not on drainage."],
  ["They increase outflow through the trabecular meshwork",
   "Increasing outflow is what the prostaglandins and the cholinergic agonists do; the beta blockers work on production instead."],
  ["They inhibit carbonic anhydrase in the ciliary epithelium",
   "A different production-side mechanism belonging to dorzolamide and brinzolamide."],
  ["They contract the ciliary muscle",
   "That is the cholinergic agonists, and it opens outflow rather than reducing production."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 67"},

{"topic": "Beta blockers", "io": "Identify indications and contraindications of ophthalmic drugs",
 "slot": "contraindication",
 "q": "A patient with asthma needs a topical beta blocker for glaucoma. Which agent is safer, and why?",
 "opts": [
  ["Betaxolol, because it is beta-1 selective",
   "Correct. Beta-2 receptors mediate bronchodilation, so blocking them raises airway resistance. Betaxolol is the beta-1 selective option on this list; carteolol, timolol and levobunolol are non-selective."],
  ["Timolol, because it is beta-1 selective",
   "Timolol is non-selective, which is precisely the problem in asthma."],
  ["Levobunolol, because it is more efficacious",
   "Non-selective agents are more efficacious, but that efficacy comes with the beta-2 blockade this patient cannot afford."],
  ["Carteolol, because it has no systemic absorption",
   "All topical beta blockers can be absorbed nasolacrimally, and carteolol is non-selective."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slides 67-68"},

{"topic": "Beta blockers", "io": "Identify indications and contraindications of ophthalmic drugs",
 "slot": "adverse effect",
 "q": "Which systemic adverse effects can a topical ophthalmic beta blocker produce?",
 "opts": [
  ["Bradycardia, heart block and bronchoconstriction",
   "Correct. A drop is not a local-only treatment — nasolacrimal absorption avoids first-pass metabolism, so a topical beta blocker can do everything a systemic one does."],
  ["Hypertension and tachycardia",
   "The opposite direction; beta blockade slows the heart rather than speeding it."],
  ["Central nervous system depression and apnoea",
   "That is the alpha-2 agonist risk, and specifically in children under two."],
  ["Bitter taste and allergic conjunctivitis",
   "Bitter taste and allergic conjunctivitis are carbonic anhydrase inhibitor effects, and are local rather than systemic."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 67"},

{"topic": "Alpha adrenergic agonists", "io": "Describe the mechanism of action of ophthalmic drugs",
 "slot": "mechanism",
 "q": "How do ophthalmic alpha-2 agonists lower intraocular pressure?",
 "opts": [
  ["They reduce production and increase outflow",
   "Correct. They work on both sides of the equation, which is why they appear in both lists — decreased production and increased outflow."],
  ["They block beta receptors in the ciliary epithelium",
   "That is the beta blockers, which reduce production by cutting cyclic AMP in the ciliary epithelium rather than improving drainage."],
  ["They contract the ciliary muscle to open the trabecular meshwork",
   "That is the cholinergic agonists, which contract the ciliary muscle and open the trabecular meshwork to increase outflow."],
  ["They analogue prostaglandin F2-alpha at prostaglandin receptors",
   "That is the prostaglandin analogues, which bind prostaglandin receptors and increase outflow as the first-line agents."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 69"},

{"topic": "Alpha adrenergic agonists", "io": "Identify indications and contraindications of ophthalmic drugs",
 "slot": "contraindication",
 "q": "In which patients are ophthalmic alpha-2 agonists contraindicated, and why?",
 "opts": [
  ["Children under two, from apnoea risk",
   "Correct. A hard age contraindication, and the mechanism is the same central alpha-2 effect that makes imidazoline ingestion dangerous in toddlers. Worth holding alongside that question."],
  ["Patients with asthma, because of bronchoconstriction",
   "Bronchoconstriction is the non-selective beta blocker problem, because beta-2 receptors in the lung mediate bronchodilation."],
  ["Patients with sulfonamide allergy",
   "Sulfonamide allergy is the contraindication to sulfacetamide among the ocular antibiotics, and has nothing to do with alpha agonists."],
  ["Patients over 65, because of falls",
   "Age over 65 is not a contraindication. The age limit runs the other way \u2014 under two years."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 69"},

{"topic": "Alpha adrenergic agonists", "io": "Describe the mechanism of action of ophthalmic drugs",
 "slot": "drug choice",
 "q": "Apraclonidine is highly ionised at physiological pH while brimonidine is more lipophilic. What is the practical consequence?",
 "opts": [
  ["Ionisation limits blood-brain barrier penetration",
   "Correct. A charged molecule crosses membranes poorly, so it stays where it is put. Brimonidine, being more lipophilic, is also the one with less allergic conjunctivitis."],
  ["Ionisation increases corneal penetration and local potency",
   "Charged molecules cross membranes less readily, not more, so ionisation reduces penetration rather than increasing local potency."],
  ["Lipophilicity prevents systemic absorption",
   "Lipophilicity favours crossing membranes, including the blood-brain barrier."],
  ["The difference is purely one of shelf stability",
   "It is a pharmacokinetic difference with a clinical consequence, not a formulation one."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 69"},

{"topic": "Carbonic anhydrase inhibitors", "io": "Describe the mechanism of action of ophthalmic drugs",
 "slot": "mechanism",
 "q": "How do dorzolamide and brinzolamide lower pressure?",
 "opts": [
  ["They inhibit carbonic anhydrase in the ciliary epithelium",
   "Correct. Less bicarbonate means less fluid follows it, so aqueous production falls. It is a production-side drug, like the beta blockers but by a different route."],
  ["They increase outflow through the trabecular meshwork",
   "Carbonic anhydrase inhibitors do not act on drainage at all; they reduce bicarbonate production so less fluid is made."],
  ["They block beta receptors in the ciliary body",
   "That is the beta blockers, though both end up reducing production."],
  ["They activate muscarinic receptors on the ciliary muscle",
   "That is the cholinergic agonists, which contract the ciliary muscle and open the trabecular meshwork to increase outflow."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 70"},

{"topic": "Carbonic anhydrase inhibitors", "io": "Identify indications and contraindications of ophthalmic drugs",
 "slot": "adverse effect",
 "q": "Which adverse effects most affect whether a patient will keep taking a topical carbonic anhydrase inhibitor?",
 "opts": [
  ["Bitter taste and stinging",
   "Correct. Neither is dangerous, but between them they affect over half of patients — and a drop that tastes foul and stings is a drop that gets skipped. The taste comes from nasolacrimal drainage to the pharynx."],
  ["Bradycardia and heart block",
   "Bradycardia and heart block are systemic beta blocker effects, reaching the circulation through nasolacrimal absorption."],
  ["Iris darkening and eyelash growth",
   "Iris darkening and eyelash growth are prostaglandin analogue effects, and are cosmetic rather than tolerability problems."],
  ["Fixed small pupils and myopia",
   "Fixed small pupils and myopia are cholinergic agonist effects, and they are what make miotics hard for younger patients."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 70"},

{"topic": "Cholinergic agonists", "io": "Describe the mechanism of action of ophthalmic drugs",
 "slot": "mechanism",
 "q": "How does pilocarpine lower intraocular pressure?",
 "opts": [
  ["It activates muscarinic receptors on the ciliary muscle",
   "Correct. Contracting the ciliary muscle pulls on the trabecular meshwork and opens the drainage route — an outflow drug achieved by a muscle action."],
  ["It blocks muscarinic receptors, dilating the pupil",
   "That is the antimuscarinic cycloplegics, which do the opposite."],
  ["It reduces aqueous production by inhibiting carbonic anhydrase",
   "Carbonic anhydrase inhibition is a different class acting on production, whereas pilocarpine works by improving outflow."],
  ["It analogues prostaglandin F2-alpha",
   "Analoguing prostaglandin F2-alpha is what latanoprost and its relatives do; pilocarpine acts through muscarinic receptors instead."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 72"},

{"topic": "Cholinergic agonists", "io": "Identify indications and contraindications of ophthalmic drugs",
 "slot": "adverse effect",
 "q": "Why are younger patients usually intolerant of miotic therapy?",
 "opts": [
  ["Visual blurring from induced myopia",
   "Correct. Fixed small pupils, induced myopia and visual disturbance are the effects, and a young eye with active accommodation notices them most. That, plus frequent dosing, is why compliance is poor."],
  ["Systemic bradycardia from muscarinic activation",
   "Systemic bradycardia is not the reason given. What young patients cannot tolerate is the visual blurring from induced myopia."],
  ["Permanent iris colour change",
   "Permanent iris colour change is a prostaglandin analogue effect and has nothing to do with muscarinic agonists."],
  ["Increased airway resistance",
   "Increased airway resistance is a non-selective beta blocker concern, mediated by beta-2 blockade in the lung."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 72"},

{"topic": "Combination products", "io": "Identify indications and contraindications of ophthalmic drugs",
 "slot": "drug choice",
 "q": "A patient is already on timolol and needs a second agent. Which combination product makes sense, and what is the general advantage of combinations?",
 "opts": [
  ["Brimonidine with timolol, targeting both mechanisms",
   "Correct. Given the drug someone is already on, the question is what second-line agent helps most. Adding an alpha agonist to a beta blocker hits both production and outflow, and fewer drops improves compliance."],
  ["A second beta blocker, because the effect is additive",
   "Adding a drug with the same mechanism gains little and doubles the class's adverse effects."],
  ["Dorzolamide with timolol, because both increase outflow",
   "The product exists, but the reasoning is wrong — both of those reduce production rather than increasing outflow."],
  ["Pilocarpine alone, because miotics are best tolerated",
   "Miotics are among the least well tolerated, which is why compliance with them is poor."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 73"},

{"topic": "Glaucoma definitions", "io": "Identify indications and contraindications of ophthalmic drugs", "slot": "diagnosis",
 "q": "A patient has an intraocular pressure of 26 mmHg with a normal optic nerve and no visual field loss. What is this called?",
 "opts": [
  ["Ocular hypertension",
   "Correct. Pressure above the normal 10 to 21 mmHg but with no optic nerve damage and no field loss. It is a risk factor rather than a disease, and whether to treat depends on the other risk factors."],
  ["Open angle glaucoma",
   "That requires damage — the patient may have optic nerve damage or reduced visual field. Pressure alone is not the diagnosis."],
  ["Angle closure glaucoma",
   "A blockage of the drainage canal, usually with acute pain, and often with a normal optic nerve early. Nothing here suggests it."],
  ["Normal tension glaucoma",
   "Would require optic nerve damage at a normal pressure — the opposite combination."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 61"},

{"topic": "Glaucoma definitions", "io": "Identify indications and contraindications of ophthalmic drugs", "slot": "diagnosis",
 "q": "What distinguishes angle closure glaucoma from open angle glaucoma?",
 "opts": [
  ["Blockage of the drainage canal, with acute pain",
   "Correct. Open angle comes from increased production or reduced drainage and damages the nerve over time; angle closure is a mechanical blockage that presents acutely and painfully. Drug therapy targets open angle disease."],
  ["Increased aqueous production with a gradual course",
   "Increased production or reduced drainage with a gradual course describes open angle disease, not the mechanical blockage of angle closure."],
  ["Optic nerve damage at a normal intraocular pressure",
   "Optic nerve damage at a normal pressure would be normal tension disease. Angle closure is defined by the blocked drainage canal."],
  ["Raised pressure without any optic nerve damage",
   "Raised pressure with no optic nerve damage is ocular hypertension \u2014 a risk factor rather than either form of glaucoma."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 61"},

{"topic": "Glaucoma definitions", "io": "Describe the mechanism of action of ophthalmic drugs", "slot": "mechanism",
 "q": "What is the sequence by which glaucoma causes blindness?",
 "opts": [
  ["Optic neuropathy, axon loss, field loss, blindness",
   "Correct. The irreversibility is the point — the axons do not come back, which is why the whole of therapy is aimed at preventing progression rather than recovering vision."],
  ["Raised pressure causes corneal oedema and then scarring",
   "Corneal oedema and scarring are not the pathway. Glaucoma blinds by destroying retinal ganglion cell axons at the optic nerve."],
  ["Raised pressure causes cataract formation",
   "Cataract is a glucocorticoid risk, not the glaucoma mechanism."],
  ["Raised pressure detaches the retina",
   "Retinal detachment is not the described sequence. The damage is at the optic nerve head, and it is irreversible once the axons are lost."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 60"},

{"topic": "Glaucoma therapy", "io": "Identify indications and contraindications of ophthalmic drugs", "slot": "next step",
 "q": "Which patients with raised pressure are treated, and which are monitored?",
 "opts": [
  ["Treat those with risk factors; monitor those without",
   "Correct. Raised pressure alone is not automatically a prescription. Risk factors decide, and in their absence you watch for the change that would make it a disease."],
  ["All patients with pressure above 21 mmHg are treated",
   "That would treat every ocular hypertensive, which is not the stated approach."],
  ["Only those who already have visual field loss are treated",
   "Waiting for field loss means waiting for irreversible axon loss, which is what treatment exists to prevent."],
  ["Treatment is started only once both eyes are affected",
   "Not a criterion given, and therapy may deliberately start in one eye."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 74"},

{"topic": "Glaucoma therapy", "io": "Identify indications and contraindications of ophthalmic drugs", "slot": "next step",
 "q": "Why might glaucoma therapy be started in one eye only?",
 "opts": [
  ["To judge efficacy and tolerability against the untreated eye",
   "Correct. The other eye acts as its own control, which tells you whether the drug is doing anything and whether the patient can tolerate it before both eyes are committed."],
  ["Because bilateral treatment doubles the systemic absorption to unsafe levels",
   "Systemic absorption is a genuine concern with beta blockers, but the stated reason for a one-eye trial is assessment."],
  ["Because only the worse eye requires treatment",
   "Both eyes will usually need treating; this is a trial, not a final plan."],
  ["To reduce the cost of therapy",
   "Cost is not the reason given for a one-eye trial. The untreated eye serves as a control for efficacy and tolerability."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 74"},

{"topic": "Glaucoma therapy", "io": "Identify indications and contraindications of ophthalmic drugs", "slot": "next step",
 "q": "What is the general target for pressure reduction in glaucoma therapy?",
 "opts": [
  ["A 20 to 30 per cent reduction in intraocular pressure",
   "Correct. The goal is expressed as a proportion rather than an absolute number, which matches the stated aim: prevent progressive optic nerve damage with the least risk and fewest side effects."],
  ["A pressure below 10 mmHg in every patient",
   "Below 10 is under the normal range; the target is relative, not a universal floor."],
  ["A 50 per cent reduction regardless of starting pressure",
   "More aggressive than the stated goal, and it would mean more drugs and more side effects."],
  ["Any reduction at all, however small",
   "Any reduction at all is too permissive to count as a target; the stated goal is a 20 to 30 per cent fall in pressure."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 74"},

{"topic": "Ocular anaesthetics", "io": "Describe the mechanism of action of ophthalmic drugs", "slot": "mechanism",
 "q": "How do tetracaine and proparacaine work?",
 "opts": [
  ["They inhibit sodium influx into the neuron",
   "Correct. Blocking the sodium channel stops the action potential, so the nerve cannot signal. It is the same mechanism as any local anaesthetic, applied to the ocular surface."],
  ["They block muscarinic receptors on the ciliary muscle",
   "Blocking muscarinic receptors to dilate is the antimuscarinic cycloplegics, which is the opposite of what an anaesthetic does."],
  ["They activate alpha-1 receptors to vasoconstrict",
   "Activating alpha-1 receptors to vasoconstrict is the ocular decongestants, which reduce redness rather than producing anaesthesia."],
  ["They inhibit prostaglandin synthesis",
   "Inhibiting prostaglandin synthesis is the nonsteroidal anti-inflammatories; it reduces inflammation rather than blocking nerve conduction."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 75"},

{"topic": "Ocular anaesthetics", "io": "Identify indications and contraindications of ophthalmic drugs", "slot": "education",
 "q": "A patient has had proparacaine for foreign body removal. What must they be told, and what must you NOT do?",
 "opts": [
  ["Numb for 10 to 20 minutes, no blink reflex, never prescribe",
   "Correct. No blink reflex means the eye is unprotected for the duration. And these are explicitly not to be prescribed for home use — repeated application is toxic to the epithelium and delays healing."],
  ["The eye stays numb for several hours, and a short prescription is reasonable for pain",
   "Both halves wrong: the duration is 10 to 20 minutes and a prescription is exactly what must not happen."],
  ["Vision will blur for about twenty minutes, and they should not drive",
   "That is the ointment counselling point; anaesthetics numb rather than blur."],
  ["They should keep the eye open to let the drug disperse",
   "With no blink reflex the eye needs protecting, not holding open."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 75"},

{"topic": "Cycloplegics", "io": "Describe the mechanism of action of ophthalmic drugs", "slot": "mechanism",
 "q": "How do atropine, cyclopentolate and tropicamide produce mydriasis?",
 "opts": [
  ["They competitively block muscarinic acetylcholine receptors",
   "Correct. Blocking muscarinic receptors is the exact opposite of pilocarpine's action, which is why one dilates and the other constricts. They are used diagnostically and in uveitis to prevent synechiae and relieve ciliary spasm."],
  ["They activate alpha-1 adrenergic receptors",
   "That is phenylephrine, the sympathomimetic route to the same endpoint."],
  ["They activate muscarinic receptors on the iris dilator",
   "Activating muscarinic receptors constricts the pupil, as pilocarpine does. Dilation requires blocking them, not stimulating them."],
  ["They inhibit carbonic anhydrase in the ciliary body",
   "Carbonic anhydrase inhibition is a glaucoma mechanism that lowers pressure and has no effect on pupil size at all."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 76"},

{"topic": "Cycloplegics", "io": "Describe the mechanism of action of ophthalmic drugs", "slot": "drug choice",
 "q": "Phenylephrine also dilates the pupil. How does it differ from the antimuscarinics?",
 "opts": [
  ["It is a sympathomimetic, more light-reactive",
   "Correct. Two routes to mydriasis — block the constrictor or stimulate the dilator — and the sympathomimetic leaves more light reactivity, which matters if the pupil response still needs assessing."],
  ["It is an antimuscarinic with a longer duration",
   "Phenylephrine is a sympathomimetic acting on the dilator muscle, not an antimuscarinic blocking the constrictor."],
  ["It produces cycloplegia without mydriasis",
   "It produces mydriasis; the antimuscarinics are the ones that also paralyse accommodation."],
  ["It constricts rather than dilates",
   "Constriction is the cholinergic agonist effect. Phenylephrine dilates, which is why it is grouped with the mydriatics."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 77"},

{"topic": "Cycloplegics", "io": "Identify indications and contraindications of ophthalmic drugs", "slot": "drug choice",
 "q": "Besides fundoscopy, what therapeutic use do cycloplegics have?",
 "opts": [
  ["Uveitis, to prevent synechiae and relieve ciliary spasm",
   "Correct. Keeping the pupil moving stops the iris adhering, and relaxing the ciliary muscle relieves the pain of spasm. So they are not purely diagnostic agents."],
  ["Glaucoma, to increase aqueous outflow",
   "Dilating the pupil can precipitate angle closure; the outflow drugs are the cholinergics, which do the opposite."],
  ["Bacterial conjunctivitis, to reduce photophobia",
   "Not an indication given, and it would not treat the infection."],
  ["Dry eye, to reduce tear evaporation",
   "Cycloplegics have no role in dry eye; reducing tear evaporation is not something pupil dilation or ciliary paralysis achieves."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 76"},

{"topic": "Fluorescein", "io": "Identify indications and contraindications of ophthalmic drugs", "slot": "drug choice",
 "q": "What does fluorescein show, and what is it used for?",
 "opts": [
  ["Epithelial defects of cornea and conjunctiva",
   "Correct. It reveals where the epithelium is broken. Its adverse effects are hypersensitivity and a burning sensation, which is true of most things put on an injured eye."],
  ["Raised intraocular pressure, for glaucoma screening",
   "Pressure is measured by tonometry, which needs an anaesthetic rather than a dye."],
  ["Fungal elements, for suspected fungal keratitis",
   "Fungal disease is confirmed by culture and microscopy, not by fluorescein."],
  ["Retinal detachment, by staining the posterior segment",
   "Fluorescein is an anterior segment stain. It shows epithelial defects of cornea and conjunctiva, not posterior segment pathology."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 78"},

{"topic": "Glaucoma pharmacology", "io": "Identify indications and contraindications of ophthalmic drugs", "slot": "drug choice",
 "q": "Which classes reduce aqueous PRODUCTION?",
 "opts": [
  ["Alpha agonists, beta blockers and carbonic anhydrase inhibitors",
   "Correct. The alpha agonists sit on both sides of the list, which is the part most easily got wrong — they reduce production AND increase outflow."],
  ["Prostaglandins, beta blockers and cholinergic agonists",
   "Prostaglandins and cholinergic agonists are outflow drugs, so neither belongs on a list of agents that reduce aqueous production."],
  ["Cholinergic agonists and carbonic anhydrase inhibitors only",
   "Cholinergics work on outflow by contracting the ciliary muscle."],
  ["Prostaglandins alone",
   "Prostaglandins are the first-line agents but they work by increasing outflow, which puts them on the other side of this division."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 64"},

{"topic": "Glaucoma therapy", "io": "Identify indications and contraindications of ophthalmic drugs", "slot": "drug choice",
 "q": "Which classes are named as reasonable places to START glaucoma therapy?",
 "opts": [
  ["A prostaglandin analogue or a beta blocker",
   "Correct. Either is a reasonable opening move, though the prostaglandins are described as first line and the most commonly used, with beta blockers second line."],
  ["A carbonic anhydrase inhibitor or a cholinergic agonist",
   "Both are available, but neither is offered as the usual starting point — tolerability is the problem with each."],
  ["A combination product from the outset",
   "Combinations are for when multiple agents are needed, not for starting."],
  ["A cholinergic agonist alone",
   "Compliance is poor because of side effects and frequent dosing, so it is a poor first choice."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 74"},

{"topic": "Glaucoma pharmacology", "io": "Identify indications and contraindications of ophthalmic drugs", "slot": "drug choice",
 "q": "Why is more than one agent often needed to control intraocular pressure?",
 "opts": [
  ["Targeting production and outflow together",
   "Correct. Combinations are described as synergistic for exactly that reason, and they also cut the number of drops a patient has to manage, which helps compliance."],
  ["Tolerance develops to every single agent within weeks",
   "Tolerance is not the stated reason; inadequate pressure reduction is."],
  ["Each agent can only be used at half dose",
   "Half-dosing is not how combinations work; agents are combined for synergy across mechanisms, not to dilute each one."],
  ["Single agents are contraindicated in open angle disease",
   "Therapy routinely starts with a single agent, usually a prostaglandin or a beta blocker, so monotherapy is plainly not contraindicated."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slides 64 and 73"},

{"topic": "Ocular anaesthetics", "io": "Identify indications and contraindications of ophthalmic drugs", "slot": "drug choice",
 "q": "For which procedures are topical ocular anaesthetics indicated?",
 "opts": [
  ["Tonometry, foreign body removal, corneal surgery",
   "Correct. All three need the surface insensate but not the eye immobilised. That also explains why tonometry cannot simply be done on any patient without preparation."],
  ["Fundoscopy and pupil assessment",
   "Those need dilation, which is what the cycloplegics and phenylephrine are for."],
  ["Treatment of corneal abrasion pain at home",
   "Explicitly ruled out: these are not prescribed for home use, because repeated application is toxic to the epithelium and delays healing."],
  ["Intravitreal injection only",
   "Not the listed indications, which are all anterior and superficial."]],
 "c": 0, "cite": "Ophthalmology-2.pptx, Slide 75"},

]
